Repository MetaMask/metamask-extension, pull requests merged in 2018-03, with the labels that each got.

#3381 Add retry transaction back into old ui transaction list item
  CHANGELOG.md
  old-ui/app/components/transaction-list-item.js
Labels: Needs QA, ready

#3309 Add Edge Support
  app/scripts/background.js
  app/scripts/edge-encryptor.js
  package.json
  test/unit/edge-encryptor-test.js
Labels: L8-release, T8-needsresearch

#3335 Import account disclaimer and change loose label to imported.
  CHANGELOG.md
  old-ui/app/accounts/import/index.js
  old-ui/app/components/account-dropdowns.js
  old-ui/app/css/lib.css
  ui/app/accounts/import/index.js
  ui/app/components/dropdowns/components/account-dropdowns.js
  ui/app/css/itcss/components/account-menu.scss
  ui/app/css/itcss/components/new-account.scss
Labels: ready

#3575 Tranlate to German
  app/_locales/de/messages.json
Labels: T07-i18n

#3708 A Tale Of Sourcemaps and Sentries
  app/scripts/lib/setupRaven.js
  app/scripts/vendor/raven.min.js
  gulpfile.js
  package-lock.json
  package.json
Labels: S13 - Sentry, T16-buildSystem
