Repository MetaMask/metamask-extension, pull requests merged in 2018-09, with the labels that each got.

#5351 Fix gh-pages job
  .circleci/config.yml
Labels: needs review

#5361 Mozilla addon linter + Firefox builds passing
  .circleci/config.yml
  gulpfile.js
  package-lock.json
  package.json
Labels: S06-firefox, needs review

#5363 deps - eth-block-tracker@4.0.2 for safe-eventemitter
  package-lock.json
  package.json
Labels: L00-provider

#5368 bugfix: update eth_signTypedData_v3 parameter order
  app/scripts/metamask-controller.js
  package-lock.json
Labels: 4.10

#5353 EIP-1102: Add deprecation message
  app/scripts/inpage.js
  app/scripts/lib/auto-reload.js
Labels: 4.10
