Repository MetaMask/metamask-extension, pull requests merged in 2021-08, with the labels that each got.

#11714 Fix 11709 - Always show fiat on mainnet
  ui/components/app/edit-gas-display/edit-gas-display.component.js
Labels: EIP-1559

#11713 EIP-1559 - Only show advanced form toggle when radio buttons are present
  ui/components/app/edit-gas-display/edit-gas-display.component.js
Labels: EIP-1559

#11711 Fix #11703 - Provide wiring for approval modal
  test/e2e/metamask-ui.spec.js
  ui/components/app/modals/modal.js
  ui/hooks/useApproveTransaction.js
  ui/pages/confirm-approve/confirm-approve.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
Labels: EIP-1559

#11700 Fix #11695 - Prevent maxFee and maxPriorityFee imbalance
  app/_locales/en/messages.json
  ui/helpers/constants/gas.js
  ui/hooks/useGasFeeInputs.js
Labels: EIP-1559

#11620 Ensure that gas fee/prices params are not updated while in send edit stage/mode
  ui/ducks/send/send.js
Labels: EIP-1559

#11722 Rejecting EIP-1559 transactions on unsupported networks
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/lib/util.js
  app/scripts/controllers/transactions/lib/util.test.js
Labels: EIP-1559

#11728 remove estimate detail in advanced gas controls
  ui/components/app/advanced-gas-controls/advanced-gas-controls.component.js
Labels: EIP-1559

#11710 Fix 11705 - Reset gas limit when radio button clicked
  ui/components/app/advanced-gas-controls/advanced-gas-controls.component.js
  ui/hooks/useGasFeeInputs.js
Labels: EIP-1559

#11724 Show warning when network request for fee market estimates fails
  app/_locales/en/messages.json
  ui/components/app/edit-gas-display/edit-gas-display.component.js
  ui/components/app/edit-gas-popover/edit-gas-popover.component.js
  ui/hooks/useGasFeeInputs.js
Labels: EIP-1559

#11716 EIP-1559 - Fall back to gasLimit and gasPrice for hardware wallets
  app/scripts/controllers/transactions/index.js
  app/scripts/metamask-controller.js
  ui/components/app/advanced-gas-controls/advanced-gas-controls.component.js
  ui/components/app/edit-gas-display/edit-gas-display.component.js
  ui/components/app/edit-gas-popover/edit-gas-popover.component.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/ducks/swaps/swaps.js
  ui/hooks/useGasFeeEstimates.js
  ui/hooks/useGasFeeEstimates.test.js
  ui/hooks/useGasFeeInputs.js
  ui/hooks/useGasFeeInputs.test.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/send/send-content/send-content.component.js
  ui/pages/send/send-content/send-content.component.test.js
  ui/pages/send/send-content/send-content.container.js
  ui/pages/send/send.test.js
  ui/pages/swaps/fee-card/fee-card.js
  ui/pages/swaps/fee-card/fee-card.test.js
  ui/pages/swaps/index.js
  ui/pages/swaps/swaps.util.js
  ui/pages/swaps/view-quote/view-quote.js
  ui/selectors/confirm-transaction.js
  ui/selectors/selectors.js
  ui/store/actions.js
Labels: EIP-1559

#11712 Remove button group for non-EIP-1559 networks
  app/_locales/en/messages.json
  test/e2e/metamask-ui.spec.js
  test/e2e/tests/from-import-ui.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/tests/send-edit.spec.js
  test/e2e/tests/send-eth.spec.js
  ui/pages/send/send-content/send-gas-row/send-gas-row.component.js
  ui/pages/send/send-content/send-gas-row/send-gas-row.component.test.js
Labels: EIP-1559

#11733 EIP-1559 - Return null from GasTiming if on non-1559 network
  ui/components/app/gas-timing/gas-timing.component.js
Labels: EIP-1559

#11735 EIP-1559 - Ensure transaction detail font-size and icon colors are consistent with Figma design
  ui/components/app/advanced-gas-controls/index.scss
  ui/components/app/transaction-detail-item/index.scss
  ui/components/app/transaction-detail-item/transaction-detail-item.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: EIP-1559

#11727 Ensure that gas price in popover updates when api provided estimate updates
  ui/hooks/useGasFeeInputs.js
Labels: EIP-1559

#11740 EIP-1559 - Fix education modal typo
  app/_locales/en/messages.json
Labels: EIP-1559

#11736 EIP-1559 - Provide better validation for gas price and gas limit
  app/_locales/en/messages.json
  ui/components/app/advanced-gas-controls/advanced-gas-controls.component.js
  ui/components/ui/numeric-input/numeric-input.component.js
  ui/helpers/constants/gas.js
  ui/hooks/useGasFeeInputs.js
Labels: EIP-1559

#11754 Rename effective gas price field to total gas fee
  app/_locales/en/messages.json
  ui/components/app/transaction-breakdown/transaction-breakdown.component.js
Labels: EIP-1559

#11750 Allows users to set a max priority fee below suggested, just showing a warning in that case
  app/_locales/en/messages.json
  ui/hooks/useGasFeeInputs.js
Labels: EIP-1559

#11749 Allow max priority fee to be below 1, and only require it to be greater than 0
  app/_locales/en/messages.json
  ui/helpers/constants/gas.js
  ui/hooks/useGasFeeInputs.js
Labels: EIP-1559

#11748 Fixing errors in EditGasDisplay
  ui/components/app/edit-gas-display/edit-gas-display.component.js
  ui/components/ui/radio-group/radio-group.component.js
Labels: EIP-1559

#11742 remove unnecessary conversion call
  ui/components/app/gas-timing/gas-timing.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: EIP-1559

#11757 EIP-1559 - Remove unncessary props from AdvancedFormControls
  ui/components/app/advanced-gas-controls/advanced-gas-controls.component.js
  ui/components/app/edit-gas-display/edit-gas-display.component.js
  ui/components/app/edit-gas-popover/edit-gas-popover.component.js
Labels: EIP-1559

#11762 EIP-1559 - Temporarily remove the loading heartbeat from the transaction detail
  ui/components/app/transaction-detail/transaction-detail.component.js
Labels: EIP-1559

#11759 EIP-1559 - Prevent uncaught exception when passing fees to getGasFeeTimeEstimate
  ui/components/app/gas-timing/gas-timing.component.js
Labels: EIP-1559

#11751 Show advanced options, and hide radio buttons, for advanced gas settings users
  app/_locales/en/messages.json
  ui/components/app/edit-gas-display/edit-gas-display.component.js
  ui/components/app/edit-gas-popover/edit-gas-popover.component.js
  ui/hooks/useGasFeeInputs.js
Labels: EIP-1559

#11763 Provide pointer cursor for radio group buttons
  ui/components/ui/radio-group/index.scss
Labels: EIP-1559

#11746 Stop GasFeeController polling when pop closes
  app/scripts/background.js
  app/scripts/controllers/app-state.js
  app/scripts/metamask-controller.js
  shared/constants/app.js
  ui/components/app/gas-customization/gas-modal-page-container/gas-modal-page-container-component.test.js
  ui/components/app/gas-customization/gas-modal-page-container/gas-modal-page-container.component.js
  ui/ducks/send/send.js
  ui/hooks/useGasFeeEstimates.test.js
  ui/hooks/useSafeGasEstimatePolling.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction/confirm-transaction.component.js
  ui/pages/send/send.js
  ui/store/actions.js
Labels: EIP-1559

#11758 EIP-1559 - Fix mislabeled MaxPriority fee key
  ui/helpers/constants/gas.js
Labels: EIP-1559

#11766 Fix legacy unapproved tx handling
  ui/hooks/useGasFeeInputs.js
Labels: EIP-1559

#11773 Fix NumericInput PropType error
  ui/components/ui/numeric-input/numeric-input.component.js
Labels: EIP-1555-v1.01

#11783 Separate out non blocking gas errors
  app/_locales/en/messages.json
  ui/hooks/useGasFeeInputs.js
Labels: EIP-1559, EIP-1559-Release-Blocker

#11781 Restore heartbeat to transaction confirmation, use isGasEstimatesLoading more broadly
  test/jest/mock-store.js
  ui/components/app/advanced-gas-controls/advanced-gas-controls.component.js
  ui/components/app/edit-gas-popover/edit-gas-popover.component.js
  ui/components/app/gas-timing/gas-timing.component.js
  ui/components/app/gas-timing/gas-timing.component.test.js
  ui/components/app/transaction-detail/transaction-detail.component.js
  ui/components/ui/form-field/form-field.js
  ui/components/ui/loading-heartbeat/index.js
  ui/components/ui/loading-heartbeat/index.scss
  ui/components/ui/numeric-input/numeric-input.component.js
  ui/ducks/app/app.js
  ui/ducks/metamask/metamask.js
  ui/hooks/useGasFeeEstimates.js
  ui/hooks/useGasFeeEstimates.test.js
  ui/hooks/useShouldAnimateGasEstimations.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/swaps/fee-card/fee-card.test.js
  ui/store/actionConstants.js
Labels: EIP-1559-Release-Blocker

#11779 fix confirm transaction details to match spec
  app/_locales/en/messages.json
  ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.component.js
  ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.container.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
Labels: EIP-1559-Release-Blocker

#11787 EIP-1559 - Ensure form always displays when there are errors
  ui/components/app/edit-gas-display/edit-gas-display.component.js
Labels: EIP-1559-Release-Blocker

#11788 Fixes updates on the confirm screen.
  app/scripts/controllers/swaps.js
  app/scripts/controllers/swaps.test.js
  app/scripts/controllers/transactions/index.js
  app/scripts/metamask-controller.js
  ui/components/app/advanced-gas-controls/advanced-gas-controls.component.js
  ui/components/app/edit-gas-display/edit-gas-display.component.js
  ui/components/app/edit-gas-popover/edit-gas-popover.component.js
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/ducks/swaps/swaps.js
  ui/helpers/utils/conversions.util.js
  ui/hooks/useGasFeeInputs.js
  ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.container.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/swaps/view-quote/view-quote.js
  ui/selectors/confirm-transaction.js
  ui/store/actions.js
Labels: EIP-1559-Release-Blocker

#11770 Selected radio group label should be black
  ui/components/ui/radio-group/radio-group.component.js
Labels: EIP-1555-v1.01

#11769 Correct the vertical margins on the RadioGroup component
  ui/components/ui/radio-group/index.scss
  ui/components/ui/radio-group/radio-group.component.js
Labels: EIP-1555-v1.01

#11771 Keep radio group contained and equal width
  ui/components/ui/radio-group/index.scss
Labels: EIP-1555-v1.01

#11805 EIP-1559 - Update tooltip text for gas fees
  app/_locales/en/messages.json
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: EIP-1555-v1.01

#11772 Gas Timing with Negative attitude should be bold with tooltip
  app/_locales/en/messages.json
  ui/components/app/gas-timing/gas-timing.component.js
  ui/components/app/gas-timing/index.scss
  ui/pages/swaps/fee-card/__snapshots__/fee-card.test.js.snap
Labels: EIP-1555-v1.01
