Repository MetaMask/metamask-extension, pull requests merged in 2021-11, with the labels that each got.

#12521 Exclude files from builds by build type
  .eslintrc.js
  development/build/index.js
  development/build/scripts.js
  development/build/transforms/utils.js
  lavamoat/node/policy-override.json
  lavamoat/node/policy.json
  package.json
  patches/@eslint+eslintrc+0.4.0.patch
  patches/eslint+7.23.0.patch
  patches/object.values+1.1.1.patch
  ui/helpers/utils/build-types.js
  yarn.lock
Labels: area-buildSystem, flask

#12517 Add transaction-total-banner render test to Storybook
  ui/components/app/transaction-total-banner/transaction-total-banner.stories.js
  ui/components/app/transaction-total-banner/transaction-total-banner.stories.test.js
Labels: type-story

#12530 Adding GasFee context
  ui/components/app/confirm-page-container/confirm-page-container-container.test.js
  ui/components/app/confirm-page-container/confirm-page-container.component.js
  ui/contexts/gasFee.js
  ui/hooks/gasFeeInput/useGasFeeErrors.js
  ui/hooks/gasFeeInput/useGasFeeInputs.js
Labels: EIP-1559-V2

#12567 Changes in edit link on confirm transaction page
  app/_locales/en/messages.json
  ui/components/app/transaction-detail/index.scss
  ui/components/app/transaction-detail/transaction-detail.component.js
  ui/components/app/transaction-detail/transaction-detail.component.test.js
  ui/hooks/gasFeeInput/useGasFeeInputs.js
Labels: EIP-1559-V2

#12671 Updating Chip component
  ui/components/ui/chip/README.mdx
  ui/components/ui/chip/chip.js
  ui/components/ui/chip/chip.scss
  ui/components/ui/chip/chip.stories.js
Labels: area-UI, type-story

#12666 Updating Card ui component and adding story
  ui/components/ui/card/README.mdx
  ui/components/ui/card/card.component.js
  ui/components/ui/card/card.component.test.js
  ui/components/ui/card/card.js
  ui/components/ui/card/card.stories.js
  ui/components/ui/card/card.test.js
  ui/components/ui/card/index.js
  ui/components/ui/card/index.scss
  ui/components/ui/ui-components.scss
Labels: area-UI, type-story

#12624 Adding edit gas fee modal
  app/_locales/en/messages.json
  ui/components/app/app-components.scss
  ui/components/app/confirm-page-container/confirm-page-container.component.js
  ui/components/app/edit-gas-fee-popover/edit-gas-fee-popover.js
  ui/components/app/edit-gas-fee-popover/edit-gas-fee-popover.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/index.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/index.scss
  ui/components/app/edit-gas-fee-popover/index.js
  ui/components/app/edit-gas-fee-popover/index.scss
  ui/components/app/gas-timing/gas-timing.component.js
  ui/components/app/transaction-detail/transaction-detail.component.js
  ui/helpers/constants/gas.js
  ui/helpers/utils/util.js
  ui/helpers/utils/util.test.js
  ui/hooks/gasFeeInput/useGasFeeInputs.js
  ui/hooks/gasFeeInput/useGasFeeInputs.test.js
  ui/hooks/gasFeeInput/useTransactionFunctions.js
  ui/pages/confirm-transaction-base/gas-details-item/gas-details-item.js
  ui/pages/confirm-transaction-base/low-priority-message/low-priority-message.js
Labels: EIP-1559-V2

#12742 Improve code fence transform error handling
  development/build/transforms/remove-fenced-code.js
  development/build/transforms/remove-fenced-code.test.js
Labels: flask

#12733 Confirm transaction screen - wrap lengthier values
  test/e2e/tests/send-edit.spec.js
  ui/components/app/transaction-detail-item/index.scss
  ui/components/app/transaction-detail-item/transaction-detail-item.component.js
Labels: EIP-1559-V2

#12651 Update alert-circle-icon.stories for Storybook documentation
  ui/components/ui/alert-circle-icon/README.mdx
  ui/components/ui/alert-circle-icon/alert-circle-icon.component.js
  ui/components/ui/alert-circle-icon/alert-circle-icon.stories.js
Labels: type-story

#12650 Update circle-icon.stories for Storybook documentation
  ui/components/ui/circle-icon/README.mdx
  ui/components/ui/circle-icon/circle-icon.component.js
  ui/components/ui/circle-icon/circle-icon.stories.js
Labels: type-story

#12682 Updating tags in Typography component
  ui/components/ui/typography/typography.js
  ui/components/ui/typography/typography.test.js
Labels: area-UI

#12797 Fix/12789 update icon with fallback component
  ui/components/ui/icon-border/icon-border.scss
  ui/components/ui/icon-with-fallback/README.mdx
  ui/components/ui/icon-with-fallback/icon-with-fallback.component.js
  ui/components/ui/icon-with-fallback/icon-with-fallback.scss
  ui/components/ui/icon-with-fallback/icon-with-fallback.stories.js
  ui/components/ui/icon-with-fallback/icon-with-fallback.test.js
  ui/components/ui/site-icon/README.mdx
  ui/components/ui/site-icon/site-icon.js
  ui/components/ui/site-icon/site-icon.stories.js
  ui/components/ui/site-icon/site-icon.test.js
  ui/components/ui/typography/typography.test.js
  ui/pages/swaps/dropdown-search-list/__snapshots__/dropdown-search-list.test.js.snap
  ui/pages/swaps/main-quote-summary/__snapshots__/main-quote-summary.test.js.snap
  ui/pages/swaps/searchable-item-list/__snapshots__/searchable-item-list.test.js.snap
  ui/pages/swaps/view-quote/__snapshots__/view-quote.test.js.snap
Labels: area-UI, type-story

#12621 Fix button-group.stories for new Storybook documentation
  ui/components/ui/button-group/README.mdx
  ui/components/ui/button-group/button-group.component.js
  ui/components/ui/button-group/button-group.stories.js
Labels: type-story

#12838 Feat/12837 add className to ToggleButton component
  ui/components/ui/toggle-button/toggle-button.component.js
Labels: area-UI

#12757 Fix checkbox for new Storybook format
  ui/components/ui/check-box/README.mdx
  ui/components/ui/check-box/check-box.component.js
  ui/components/ui/check-box/check-box.stories.js
Labels: type-story

#12619 EIP-1559 V2 : Advanced gas fee modal - Max base fee and Priority fee inputs
  app/_locales/en/messages.json
  app/images/high-arrow.svg
  app/images/low-arrow.svg
  app/scripts/controllers/transactions/index.js
  shared/modules/conversion.utils.js
  shared/modules/conversion.utils.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-input-subtext/advanced-gas-fee-input-subtext.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-input-subtext/advanced-gas-fee-input-subtext.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-input-subtext/index.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-input-subtext/index.scss
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/advanced-gas-fee-inputs.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/basefee-input.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/basefee-input.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/index.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/index.scss
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priorityfee-input.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priorityfee-input.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-popover.js
  ui/components/app/advanced-gas-fee-popover/index.scss
  ui/components/app/app-components.scss
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.test.js
  ui/components/app/transaction-detail/transaction-detail.component.test.js
  ui/components/ui/form-field/form-field.js
  ui/components/ui/form-field/index.scss
  ui/contexts/transaction-modal.js
  ui/hooks/gasFeeInput/useGasFeeInputs.js
  ui/hooks/gasFeeInput/useTransactionFunctions.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/gas-details-item/gas-details-item.js
Labels: EIP-1559-V2
