Repository MetaMask/metamask-extension, pull requests merged in 2021-12, with the labels that each got.

#12745 Implement Flask onboarding UI
  app/_locales/en/messages.json
  lavamoat/build-system/policy-override.json
  ui/components/app/app-components.scss
  ui/components/app/flask/experimental-area/experimental-area.js
  ui/components/app/flask/experimental-area/experimental-area.stories.js
  ui/components/app/flask/experimental-area/index.js
  ui/components/app/flask/experimental-area/index.scss
  ui/css/design-system/colors.scss
  ui/helpers/constants/routes.js
  ui/pages/first-time-flow/first-time-flow-switch/first-time-flow-switch.component.js
  ui/pages/first-time-flow/first-time-flow.component.js
  ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js
  ui/pages/onboarding-flow/onboarding-flow.js
Labels: flask

#12655 Adding SnapSettingsCard ui component
  app/_locales/en/messages.json
  package.json
  ui/components/app/app-components.scss
  ui/components/app/flask/snap-settings-card/README.mdx
  ui/components/app/flask/snap-settings-card/index.js
  ui/components/app/flask/snap-settings-card/index.scss
  ui/components/app/flask/snap-settings-card/snap-settings-card.js
  ui/components/app/flask/snap-settings-card/snap-settings-card.stories.js
  ui/components/app/flask/snap-settings-card/snap-settings-card.test.js
  yarn.lock
Labels: area-UI, type-story

#12688 Textarea UI component
  ui/components/ui/textarea/README.mdx
  ui/components/ui/textarea/index.js
  ui/components/ui/textarea/index.scss
  ui/components/ui/textarea/textarea.js
  ui/components/ui/textarea/textarea.stories.js
  ui/components/ui/textarea/textarea.test.js
  ui/components/ui/ui-components.scss
  ui/css/design-system/attributes.scss
  ui/helpers/constants/design-system.js
Labels: area-UI, type-story

#12894 Fix unlock-page component for new Storybook format
  ui/pages/unlock-page/README.mdx
  ui/pages/unlock-page/unlock-page.component.js
  ui/pages/unlock-page/unlock-page.stories.js
Labels: type-story

#12971 Storybook updating styles so they don't override fontawesome
  .storybook/metamask-storybook-theme.js
  .storybook/preview-head.html
  .storybook/preview.js
Labels: type-story

#12819 Fix transaction-detail for new Storybook format
  ui/components/app/transaction-detail/README.mdx
  ui/components/app/transaction-detail/transaction-detail.component.js
  ui/components/app/transaction-detail/transaction-detail.stories.js
Labels: type-story

#12820 Fix transaction-detail-item for new Storybook format
  ui/components/app/transaction-detail-item/README.mdx
  ui/components/app/transaction-detail-item/transaction-detail-item.component.js
  ui/components/app/transaction-detail-item/transaction-detail-item.stories.js
Labels: type-story

#12818 Fix pulse-loader component for new Storybook format
  ui/components/ui/pulse-loader/README.mdx
  ui/components/ui/pulse-loader/pulse-loader.stories.js
Labels: type-story

#12900 Fix radio-group component to for new Storybook format
  ui/components/ui/radio-group/README.mdx
  ui/components/ui/radio-group/radio-group.component.js
  ui/components/ui/radio-group/radio-group.stories.js
Labels: type-story

#12897 Fix slider component to for new Storybook format
  ui/components/ui/slider/README.mdx
  ui/components/ui/slider/slider.component.js
  ui/components/ui/slider/slider.stories.js
Labels: type-story

#12901 Fix info-tooltip component to for new Storybook format
  ui/components/ui/info-tooltip/README.mdx
  ui/components/ui/info-tooltip/info-tooltip.js
  ui/components/ui/info-tooltip/info-tooltip.stories.js
Labels: type-story

#12896 Fix popover component to for new Storybook format
  ui/components/ui/popover/README.mdx
  ui/components/ui/popover/popover.component.js
  ui/components/ui/popover/popover.stories.js
Labels: type-story

#12895 Fix dropdown-input-pair component to for new Storybook format
  ui/pages/swaps/dropdown-input-pair/README.mdx
  ui/pages/swaps/dropdown-input-pair/dropdown-input-pair.js
  ui/pages/swaps/dropdown-input-pair/dropdown-input-pair.stories.js
Labels: type-story

#12893 Fix account-list-item component for new Storybook format
  ui/components/app/account-list-item/README.mdx
  ui/components/app/account-list-item/account-list-item.js
  ui/components/app/account-list-item/account-list-item.stories.js
Labels: type-story

#12889 Fix text-field component for new Storybook format
  ui/components/ui/text-field/README.mdx
  ui/components/ui/text-field/text-field.component.js
  ui/components/ui/text-field/text-field.stories.js
Labels: type-story

#12888 Fix identicon component for new Storybook format
  ui/components/ui/identicon/README.mdx
  ui/components/ui/identicon/identicon.component.js
  ui/components/ui/identicon/identicon.stories.js
  ui/components/ui/identicon/index.scss
Labels: type-story

#12887 Fix icon component for new Storybook format
  ui/components/ui/icon/README.mdx
  ui/components/ui/icon/approve-icon.component.js
  ui/components/ui/icon/copy-icon.component.js
  ui/components/ui/icon/icon.stories.js
  ui/components/ui/icon/info-icon-inverted.component.js
  ui/components/ui/icon/info-icon.component.js
  ui/components/ui/icon/interaction-icon.component.js
  ui/components/ui/icon/overview-buy-icon.component.js
  ui/components/ui/icon/overview-send-icon.component.js
  ui/components/ui/icon/paper-airplane-icon.js
  ui/components/ui/icon/receive-icon.component.js
  ui/components/ui/icon/send-icon.component.js
  ui/components/ui/icon/sign-icon.component.js
  ui/components/ui/icon/sun-check-icon.component.js
  ui/components/ui/icon/swap-icon-for-list.component.js
  ui/components/ui/icon/swap-icon.component.js
Labels: type-story

#12874 Fix Actionable message for new Storybook format
  ui/components/ui/actionable-message/README.mdx
  ui/components/ui/actionable-message/actionable-message.js
  ui/components/ui/actionable-message/actionable-message.stories.js
Labels: type-story

#12957 Updating storybook documentation guidelines
  ui/2.DOCUMENTATION.stories.mdx
Labels: area-documentation, type-story

#12892 Fix metamask-translation component for new Storybook format
  ui/components/app/metamask-translation/README.mdx
  ui/components/app/metamask-translation/metamask-translation.js
  ui/components/app/metamask-translation/metamask-translation.stories.js
Labels: type-story

#13014 Identicon size fix
  ui/components/ui/identicon/identicon.component.js
Labels: area-UI

#12756 Fix form-field for new Storybook format
  ui/components/ui/form-field/README.mdx
  ui/components/ui/form-field/form-field.js
  ui/components/ui/form-field/form-field.stories.js
Labels: type-story

#12755 Fix signature-request for new Storybook format
  ui/components/app/signature-request/README.mdx
  ui/components/app/signature-request/signature-request.component.js
  ui/components/app/signature-request/signature-request.stories.js
Labels: type-story

#12816 Fix dropdown component for new Storybook format
  ui/components/ui/dropdown/README.mdx
  ui/components/ui/dropdown/dropdown.js
  ui/components/ui/dropdown/dropdown.stories.js
Labels: type-story

#12815 Fix error-message component to match new Storybook format
  ui/components/ui/error-message/README.mdx
  ui/components/ui/error-message/error-message.component.js
  ui/components/ui/error-message/error-message.stories.js
Labels: type-story

#12817 Fix toggle-button component for new Storybook format
  ui/components/ui/toggle-button/README.mdx
  ui/components/ui/toggle-button/toggle-button.component.js
  ui/components/ui/toggle-button/toggle-button.stories.js
Labels: type-story

#13029 Wire up stability slider in new 'edit gas fee' modal
  ui/components/app/edit-gas-fee-popover/network-statistics/status-slider/index.scss
  ui/components/app/edit-gas-fee-popover/network-statistics/status-slider/status-slider.js
  ui/components/app/edit-gas-fee-popover/network-statistics/status-slider/status-slider.test.js
  ui/components/app/edit-gas-fee-popover/network-statistics/tooltips.js
Labels: EIP-1559-V2

#12996 EIP-1559 V2: Advanced gas fee modal - getting 12 hour ranges of base fee and priority fee
  test/data/mock-estimates.json
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/basefee-input.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/utils.js
Labels: EIP-1559-V2

#13025 EIP-1559 V2: Advanced gas fee modal - base fee and priority fee trends
  app/images/down-arrow.svg
  app/images/up-arrow.svg
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-input-subtext/advanced-gas-fee-input-subtext.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-input-subtext/advanced-gas-fee-input-subtext.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js
Labels: EIP-1559-V2

#12911 EIP-1559 V2: Adding default settings to advanced gas modal
  app/_locales/en/messages.json
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/index.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/index.scss
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/advanced-gas-fee-inputs.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/index.scss
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-popover.js
  ui/components/app/advanced-gas-fee-popover/context/advancedGasFeePopover.js
  ui/components/app/advanced-gas-fee-popover/index.scss
  ui/components/app/app-components.scss
Labels: EIP-1559-V2
