Repository MetaMask/metamask-extension, pull requests merged in 2022-02, with the labels that each got.

#13402 Use ActionableMessage for ConfirmAddSuggestionToken warnings
  .storybook/test-data.js
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/css/base-styles.scss
  ui/helpers/constants/zendesk-url.js
  ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.component.js
  ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.stories.js
  ui/pages/confirm-add-suggested-token/index.scss
  ui/pages/import-token/import-token.component.js
  ui/pages/pages.scss
Labels: Team 🌳

#13329 Adding metrics events for EIP-1559 V2 flow
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-save/advanced-gas-fee-save.js
  ui/components/app/cancel-speedup-popover/cancel-speedup-popover.js
  ui/components/app/edit-gas-fee-button/edit-gas-fee-button.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.js
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/contexts/transaction-modal.js
  ui/hooks/gasFeeInput/useTransactionFunction.test.js
  ui/hooks/gasFeeInput/useTransactionFunctions.js
  ui/hooks/useEventFragment.js
  ui/hooks/useTransactionEventFragment.js
  ui/pages/confirm-approve/confirm-approve.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/swaps/view-quote/view-quote.js
Labels: EIP-1559-V2

#13306 Feat/hide 0 balances
  ui/components/app/app-components.scss
  ui/components/app/token-list-display/index.js
  ui/components/app/token-list-display/token-list-display.js
  ui/components/app/token-list-display/token-list-display.scss
  ui/pages/send/send-content/send-asset-row/send-asset-row.component.js
Labels: Team 🌱

#12431 Add currency symbol validation in the add network form
  app/_locales/en/messages.json
  test/e2e/tests/custom-rpc-history.spec.js
  ui/components/ui/form-field/form-field.js
  ui/components/ui/form-field/index.scss
  ui/pages/settings/networks-tab/index.scss
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/settings/networks-tab/networks-form/networks-form.test.js
  ui/pages/settings/networks-tab/networks-tab-content/networks-tab-content.test.js
Labels: Team 🌳

#13503 update test-dapp to 5.0.0
  package.json
  test/e2e/tests/edit-gas-fee.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/signature-request.spec.js
  yarn.lock
Labels: Team 🌳

#13599 Include transactions from all networks in state logs
  app/scripts/metamask-controller.js
  ui/index.js
  ui/store/actions.js
Labels: Team 🌱

#13640 E2e mocking
  development/mock-e2e.js
  package.json
  test/e2e/ganache.js
  test/e2e/helpers.js
  test/e2e/webdriver/chrome.js
  test/e2e/webdriver/firefox.js
  yarn.lock
Labels: area-testSuite, Team 🌳

#13594 ConfirmImportToken: Convert to Functional Component; Add storybook controls
  ui/ducks/metamask/metamask.js
  ui/pages/confirm-import-token/confirm-import-token.component.js
  ui/pages/confirm-import-token/confirm-import-token.container.js
  ui/pages/confirm-import-token/confirm-import-token.js
  ui/pages/confirm-import-token/confirm-import-token.stories.js
  ui/pages/confirm-import-token/confirm-import-token.test.js
  ui/pages/confirm-import-token/index.js
Labels: Team 🌳

#13633 Fixed Add Recipient Stories and migrated to use control args.
  ui/pages/send/send-content/add-recipient/add-recipient.stories.js
Labels: type-story

#13628 mįgrated truncated definition list stories from addon knobs to use controls.
  ui/components/ui/truncated-definition-list/truncated-definition-list.stories.js
Labels: type-story

#13493 Update "Forgot Password?" copy
  app/_locales/am/messages.json
  app/_locales/ar/messages.json
  app/_locales/bg/messages.json
  app/_locales/bn/messages.json
  app/_locales/ca/messages.json
  app/_locales/da/messages.json
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/et/messages.json
  app/_locales/fa/messages.json
  app/_locales/fi/messages.json
  app/_locales/fil/messages.json
  app/_locales/fr/messages.json
  app/_locales/he/messages.json
  app/_locales/hi/messages.json
  app/_locales/hr/messages.json
  app/_locales/ht/messages.json
  app/_locales/hu/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/kn/messages.json
  app/_locales/ko/messages.json
  app/_locales/lt/messages.json
  app/_locales/lv/messages.json
  app/_locales/ms/messages.json
  app/_locales/no/messages.json
  app/_locales/ph/messages.json
  app/_locales/pl/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ro/messages.json
  app/_locales/ru/messages.json
  app/_locales/sk/messages.json
  app/_locales/sl/messages.json
  app/_locales/sr/messages.json
  app/_locales/sv/messages.json
  app/_locales/sw/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/uk/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  test/e2e/metamask-ui.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  ui/helpers/constants/zendesk-url.js
  ui/pages/keychains/index.scss
  ui/pages/keychains/restore-vault.js
  ui/pages/keychains/restore-vault.test.js
  ui/pages/unlock-page/README.mdx
  ui/pages/unlock-page/index.scss
  ui/pages/unlock-page/unlock-page.component.js
  ui/pages/unlock-page/unlock-page.component.test.js
Labels: Team 🌱

#13704 E2e phishing detection
  development/mock-e2e.js
  test/e2e/helpers.js
  test/e2e/tests/phishing-detection.spec.js
Labels: area-testSuite, Team 🌳

#13669 Deleting transactions from `currentNetworkTxnList` based on unique address along with nonce and chainId
  app/scripts/controllers/transactions/tx-state-manager.js
Labels: Sev1-high, Team 🌱

#13214 Feat/settings search
  app/_locales/en/messages.json
  test/e2e/tests/custom-rpc-history.spec.js
  ui/components/app/account-menu/account-menu.component.js
  ui/components/app/tab-bar/index.scss
  ui/components/ui/search-icon/search-icon.component.js
  ui/components/ui/text-field/text-field.component.js
  ui/helpers/utils/settings-search.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/alerts-tab/alerts-tab.js
  ui/pages/settings/alerts-tab/alerts-tab.scss
  ui/pages/settings/contact-list-tab/contact-list-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/index.scss
  ui/pages/settings/info-tab/info-tab.component.js
  ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js
  ui/pages/settings/networks-tab/networks-list/networks-list.js
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/settings-search-list/index.js
  ui/pages/settings/settings-search-list/settings-search-list.js
  ui/pages/settings/settings-search/index.js
  ui/pages/settings/settings-search/settings-search.js
  ui/pages/settings/settings-search/settings-search.stories.js
  ui/pages/settings/settings-tab/settings-tab.component.js
  ui/pages/settings/settings-tab/settings-tab.component.test.js
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.component.test.js
Labels: Team 🌱

#13657 Installing design tokens and writing docs in storybook
  .depcheckrc.yml
  .storybook/3.COLORS.stories.mdx
  .storybook/images/design.token.graphic.svg
  .storybook/preview.js
  package.json
  ui/css/index.scss
  yarn.lock
Labels: area-documentation, area-UI, type-story

#13182 Implement Network specific insufficient currency warning #12965
  app/_locales/en/messages.json
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.test.js
  ui/components/app/confirm-page-container/confirm-page-container-content/index.scss
  ui/components/app/confirm-page-container/confirm-page-container.component.js
  ui/components/app/confirm-page-container/confirm-page-container.container.js
  ui/components/app/confirm-page-container/index.scss
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirm-transaction-base/transaction-alerts/transaction-alerts.js
  ui/pages/confirm-transaction-base/transaction-alerts/transaction-alerts.scss
  ui/pages/confirm-transaction-base/transaction-alerts/transaction-alerts.test.js
Labels: PS-team, Team 🌱

#13682 add account_type and device_model to tx metrics
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/metamask-controller.js
  shared/constants/hardware-wallets.js
  ui/components/app/account-menu/keyring-label.js
Labels: area-hardware

#13743 Increase the txHistoryLimit in the transaction controller to 60
  app/scripts/metamask-controller.js
Labels: Sev1-high, Team 🌱

#13496 Replace uses of updateTransaction (from the tx controller) with less powerful methods for each specific state transition
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
Labels: Sev1-high

#13180 Create 'Add network' page
  app/_locales/en/messages.json
  app/images/arbitrum.svg
  app/images/optimism.svg
  app/images/times.svg
  ui/components/app/add-network/add-network.js
  ui/components/app/add-network/add-network.stories.js
  ui/components/app/add-network/index.js
  ui/components/app/add-network/index.scss
  ui/components/app/app-components.scss
Labels: Team 🌱

#13772 UI/UX update - Error message in Import NFT
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/pages/add-collectible/add-collectible.js
  ui/pages/add-collectible/index.scss
  ui/pages/home/home.component.js
  ui/pages/pages.scss
Labels: area-NFTs, Team 🌱

#13482 Refactor ESLint config
  .eslintrc.babel.js
  .eslintrc.base.js
  .eslintrc.js
  .eslintrc.jsdoc.js
  .eslintrc.node.js
  .prettierignore
  development/build/transforms/utils.js
  lavamoat/build-system/policy-override.json
  test/e2e/tests/add-hide-token.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/signature-request.spec.js
Labels: Team 🌳
