Repository MetaMask/metamask-extension, pull requests merged in 2022-10, with the labels that each got.

#16044 Some icon fixes
  app/images/icons/icon-search-filled.svg
  ui/components/component-library/icon/icon.js
Labels: area-UI, design-system

#16047 Fixes display of avatar in flex container
  ui/components/component-library/base-avatar/base-avatar.scss
Labels: area-UI

#16003 Replace setInterval with chrome alarms for MetaMetrics FinalizeEventFragment
  app/scripts/controllers/metametrics.js
  app/scripts/lib/util.js
  shared/constants/alarms.js
Labels: PR - P1

#16062 forwarding refs to Box and Text component
  ui/components/component-library/text/text.js
  ui/components/component-library/text/text.test.js
  ui/components/ui/box/box.js
  ui/components/ui/box/box.test.js
Labels: area-UI, design-system

#16022 Removing use of window object from sentry code
  app/scripts/lib/setupSentry.js
Labels: PR - P1

#16079 15090: add primary button
  ui/components/component-library/button-base/button-base.js
  ui/components/component-library/button-base/button-base.test.js
  ui/components/component-library/button-primary/README.mdx
  ui/components/component-library/button-primary/button-primary.constants.js
  ui/components/component-library/button-primary/button-primary.js
  ui/components/component-library/button-primary/button-primary.scss
  ui/components/component-library/button-primary/button-primary.stories.js
  ui/components/component-library/button-primary/button-primary.test.js
  ui/components/component-library/button-primary/index.js
  ui/components/component-library/component-library-components.scss
Labels: design-system, IA/NAV

#16043 Adding `TextFieldBase` component
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/text-field-base/README.mdx
  ui/components/component-library/text-field-base/index.js
  ui/components/component-library/text-field-base/text-field-base.constants.js
  ui/components/component-library/text-field-base/text-field-base.js
  ui/components/component-library/text-field-base/text-field-base.scss
  ui/components/component-library/text-field-base/text-field-base.stories.js
  ui/components/component-library/text-field-base/text-field-base.test.js
Labels: area-UI, design-system, IA/NAV

#16103 Fixes optional chaining bug in storybook
  package.json
  yarn.lock
Labels: type-story

#16118 Adding border radius full to `Box` component
  ui/components/ui/box/README.mdx
  ui/components/ui/box/box.js
  ui/components/ui/box/box.scss
  ui/components/ui/box/box.stories.js
  ui/components/ui/box/box.test.js
  ui/helpers/constants/design-system.js
Labels: area-UI, design-system

#15795 added AvatarAccount component
  ui/components/component-library/avatar-account/README.mdx
  ui/components/component-library/avatar-account/avatar-account.constants.js
  ui/components/component-library/avatar-account/avatar-account.js
  ui/components/component-library/avatar-account/avatar-account.scss
  ui/components/component-library/avatar-account/avatar-account.stories.js
  ui/components/component-library/avatar-account/avatar-account.test.js
  ui/components/component-library/avatar-account/index.js
  ui/components/component-library/component-library-components.scss
Labels: design-system, IA/NAV

#16122 add decrypt e2e
  test/e2e/tests/encrypt-decrypt.spec.js
Labels: Extension QA Board

#15991 [MV3] Add e2e chrome test job for MV3 build
  .circleci/config.yml
Labels: Extension QA Board

#16137 e2e test for gas API fallback
  test/e2e/tests/gas-api-fallback.spec.js
  ui/components/app/edit-gas-display/edit-gas-display.component.js
Labels: Extension QA Board

#15978 Persist state in metaRPCHandler so that we are sure state is persisted before sending back response to actions
  app/scripts/background.js
  app/scripts/lib/createMetaRPCHandler.js
  app/scripts/lib/local-store.js
  app/scripts/lib/local-store.test.js
  app/scripts/lib/network-store.js
  app/scripts/metamask-controller.js
Labels: DO-NOT-MERGE, Extension QA Board, PR - P1

#16020 MV3 Segment Fix
  app/scripts/controllers/metametrics.js
  app/scripts/lib/segment/analytics.js
  app/scripts/lib/segment/analytics.test.js
  app/scripts/lib/segment/index.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: PR - P1

#15947 Added Tag Component
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/tag/README.mdx
  ui/components/component-library/tag/index.js
  ui/components/component-library/tag/tag.js
  ui/components/component-library/tag/tag.scss
  ui/components/component-library/tag/tag.stories.js
  ui/components/component-library/tag/tag.test.js
Labels: design-system, IA/NAV

#15676 Added AvatarBadge component
  ui/components/component-library/avatar-with-badge/README.mdx
  ui/components/component-library/avatar-with-badge/avatar-with-badge.constants.js
  ui/components/component-library/avatar-with-badge/avatar-with-badge.js
  ui/components/component-library/avatar-with-badge/avatar-with-badge.scss
  ui/components/component-library/avatar-with-badge/avatar-with-badge.stories.js
  ui/components/component-library/avatar-with-badge/avatar-with-badge.test.js
  ui/components/component-library/avatar-with-badge/index.js
  ui/components/component-library/component-library-components.scss
Labels: design-system, IA/NAV

#16135 added AvatarFavicon component
  ui/components/component-library/avatar-favicon/README.mdx
  ui/components/component-library/avatar-favicon/avatar-favicon.js
  ui/components/component-library/avatar-favicon/avatar-favicon.scss
  ui/components/component-library/avatar-favicon/avatar-favicon.stories.js
  ui/components/component-library/avatar-favicon/avatar-favicon.test.js
  ui/components/component-library/avatar-favicon/index.js
  ui/components/component-library/component-library-components.scss
Labels: design-system, IA/NAV

#16170 Update to text-field-base docs
  ui/components/component-library/text-field-base/README.mdx
  ui/components/component-library/text-field-base/text-field-base.stories.js
Labels: area-documentation, area-UI

#16213 Chromedriver v106
  .circleci/scripts/chrome-install.sh
  package.json
  yarn.lock
Labels: Extension QA Board

#16033 Updating controller dependency
  app/scripts/background.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/tests/phishing-detection.spec.js
  yarn.lock
Labels: Extension QA Board

#16093 [FLASK] Allow snaps insights to show on regular EOA transactions
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: flask

#16282 [e2e] Fix Dapp interactions flaky test on chrome
  test/e2e/tests/dapp-interactions.spec.js
Labels: Extension QA Board

#16298 [E2E] Restore tests
  test/e2e/restore/MetaMaskUserData.json
  test/e2e/tests/backup-restore.spec.js
Labels: Extension QA Board
