Repository MetaMask/metamask-extension, pull requests merged in 2022-09, with the labels that each got.

#15337 MV3: add retry logic to actions
  .storybook/preview.js
  app/scripts/ui.js
  test/jest/background.js
  ui/index.js
  ui/store/action-queue/index.js
  ui/store/action-queue/index.test.js
  ui/store/action-queue/queue.integration.test.js
  ui/store/actions.js
  ui/store/actions.test.js
Labels: PR - P1

#15667 Make addUnapprovedTransaction action idempotent
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/controllers/transactions/tx-state-manager.js
  shared/modules/transaction.utils.js
  ui/ducks/send/send.test.js
  ui/store/actions.js
Labels: PR - P1

#15585 Make updateTransactionSendFlowHistory background method idempotent
  app/scripts/controllers/transactions/index.js
  app/scripts/metamask-controller.actions.test.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/store/actions.js
Labels: PR - P1

#15709 Making addPermittedAccount and removePermittedAccount methods idempotent
  app/scripts/controllers/permissions/background-api.js
  app/scripts/controllers/permissions/background-api.test.js
Labels: PR - P1

#15638 converted Jazzicon component to functional component and added story
  ui/components/ui/jazzicon/README.mdx
  ui/components/ui/jazzicon/jazzicon.component.js
  ui/components/ui/jazzicon/jazzicon.stories.js
Labels: area-UI, design-system

#15744 ConfirmPage: update setApprovalForAll dialog copy
  app/_locales/en/messages.json
  ui/components/app/confirm-page-container/confirm-page-container.component.js
Labels: area-transactions, area-NFTs

#15675 Make cancel transaction idempotent
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/metamask-controller.js
  ui/store/actions.js
Labels: PR - P1

#15782 Fixing storybook lint issues
  ui/components/app/collectible-default-image/collectible-default-image.stories.js
  ui/components/component-library/avatar-network/avatar-network.stories.js
  ui/components/component-library/avatar-token/avatar-token.stories.js
Labels: type-story

#15386 Replace web3js package with ethersjs package
  app/scripts/controllers/detect-tokens.js
  app/scripts/lib/account-tracker.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy.json
  package.json
Labels: PR - P1

#15688 Make createSpeedUpTransaction action idempotent
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/metamask-controller.js
  ui/store/actions.js
Labels: PR - P1

#15798 Updating Chromedriver to the last version
  .circleci/scripts/chrome-install.sh
  package.json
  yarn.lock
Labels: Extension QA Board

#15784 Update reset.scss to revive <b> element font-weight
  ui/components/app/flask/experimental-area/index.scss
  ui/components/app/transaction-activity-log/index.scss
  ui/css/reset.scss
Labels: area-UI

#15777 MV3: Migrate permissions
  app/manifest/v3/_base.json
Labels: MV3, MV3-non_perf

#15494 MV3: contentscript.js - re-activate streams when Service Worker terminates and then resets
  app/scripts/contentscript.js
  app/scripts/inpage.js
Labels: Extension QA Board, PR - P1

#15604 [e2e] Refactor send-hex-address spec using Ganache seeder
  test/e2e/tests/send-hex-address.spec.js
Labels: Extension QA Board

#15835 Displaying the aggregators from tokenList in Detected token popover
  .storybook/test-data.js
  app/scripts/controllers/detect-tokens.js
  app/scripts/controllers/detect-tokens.test.js
  ui/components/app/detected-token/detected-token-details/detected-token-details.js
  ui/components/app/detected-token/detected-token-details/detected-token-details.test.js
  ui/components/app/detected-token/detected-token.test.js
Labels: area-tokens

#15737 Make metrics related actions idempotent
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  ui/store/action-queue/index.js
  ui/store/actions.js
  ui/store/actions.test.js
Labels: PR - P1

#15839 Add test insights on circle ci for test-unit job
  .circleci/config.yml
  jest.config.js
  package.json
  yarn.lock
Labels: Extension QA Board

#15551 Ability to buy tokens with Coinbase Pay and Transak
  app/scripts/lib/buy-url.js
  app/scripts/lib/buy-url.test.js
  development/ts-migration-dashboard/files-to-convert.json
  shared/constants/network.ts
  ui/components/app/deposit-popover/deposit-popover.js
  ui/components/app/deposit-popover/index.js
  ui/components/app/deposit-popover/on-ramp-item.js
  ui/components/app/modals/deposit-ether-modal/deposit-ether-modal.component.js
  ui/components/app/modals/deposit-ether-modal/deposit-ether-modal.container.js
  ui/components/app/modals/deposit-ether-modal/index.js
  ui/components/app/modals/deposit-ether-modal/index.scss
  ui/components/app/modals/index.scss
  ui/components/app/modals/modal.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/token-overview.js
  ui/selectors/selectors.js
  ui/store/actionConstants.js
  ui/store/actions.js
Labels: Extension QA Board

#15880 Update copy on token detection title and desc in advanced settings
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/import-token/import-token.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.js
Labels: area-tokens

#15921 Portfolio site e2e
  package.json
  test/e2e/tests/portfolio-site.spec.js
  test/e2e/webdriver/driver.js
  ui/pages/home/home.component.js
Labels: Extension QA Board

#13186 [i18n] Fix typo in locale key
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/edit-gas-fee-popover/edit-gas-fee-popover.js
Labels: type-i18n

#15878 Bump keystone package versions to latest
  app/scripts/account-import-strategies/account-import-strategies.test.js
  app/scripts/account-import-strategies/index.js
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/tx-gas-utils.js
  app/scripts/lib/decrypt-message-manager.js
  app/scripts/lib/personal-message-manager.js
  app/scripts/lib/util.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy.json
  package.json
  shared/modules/conversion.utils.js
  shared/modules/hexstring-utils.js
  shared/modules/siwe.js
  ui/components/app/modals/export-private-key-modal/export-private-key-modal.component.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/ducks/metamask/metamask.js
  ui/helpers/utils/optimism/buildUnserializedTransaction.js
  ui/helpers/utils/util.js
  yarn.lock
Labels: PR - P1

#15931 Replacing setTimeout in auto-lock time limit with chrome alarm
  app/manifest/v3/_base.json
  app/scripts/controllers/app-state.js
  shared/constants/alarms.js
Labels: PR - P1

#15958 Send message to inpage when extension revives
  app/scripts/contentscript.js
Labels: PR - P1

#15995 [E2E]: Revoke nft approval
  package.json
  test/e2e/tests/collectibles.spec.js
  test/e2e/webdriver/driver.js
  yarn.lock
Labels: Extension QA Board

#15818 bump smart-transactions-controller version
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  ui/hooks/useTokenData.test.js
  yarn.lock
Labels: PR - P1

#16005 Fixing icon paths to work in github pages
  ui/components/component-library/icon/icon.js
  ui/components/component-library/icon/icon.test.js
Labels: type-story

#15522 Created a custom spending cap component
  app/_locales/en/messages.json
  ui/components/app/app-components.scss
  ui/components/app/custom-spending-cap/custom-spending-cap-tooltip.js
  ui/components/app/custom-spending-cap/custom-spending-cap.js
  ui/components/app/custom-spending-cap/custom-spending-cap.stories.js
  ui/components/app/custom-spending-cap/index.js
  ui/components/app/custom-spending-cap/index.scss
  ui/components/ui/form-field/form-field.js
  ui/components/ui/form-field/index.scss
Labels: design-system

#15851 Fix 3box replacement for MV3
  app/scripts/controllers/backup.js
  ui/components/ui/export-text-container/export-text-container.component.js
  ui/helpers/utils/export-utils.js
  ui/pages/first-time-flow/seed-phrase/confirm-seed-phrase/confirm-seed-phrase.component.js
  ui/pages/first-time-flow/seed-phrase/reveal-seed-phrase/reveal-seed-phrase.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.js
Labels: PR - P1

#16027 add icons auto size
  ui/components/component-library/icon/README.mdx
  ui/components/component-library/icon/icon.scss
  ui/components/component-library/icon/icon.stories.js
  ui/components/component-library/icon/icon.test.js
  ui/helpers/constants/design-system.js
Labels: design-system
