Repository MetaMask/metamask-extension, pull requests merged in 2022-12, with the labels that each got.

#16671 [FLASK] Expose transaction origin to transaction insight snaps
  app/_locales/en/messages.json
  ui/components/app/confirm-page-container/flask/snap-insight.js
  ui/components/app/connected-accounts-permissions/connected-accounts-permissions.js
  ui/components/app/flask/update-snap-permission-list/update-snap-permission-list.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
  ui/helpers/utils/permission.js
  ui/hooks/flask/useTransactionInsightSnap.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/selectors/permissions.js
  ui/selectors/permissions.test.js
Labels: flask

#16048 [FLASK] Add snap alerts and prompts via `snap_dialog` RPC method
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  shared/constants/app.ts
  shared/constants/permissions.ts
  ui/components/app/app-components.scss
  ui/components/app/flask/copyable/copyable.js
  ui/components/app/flask/copyable/index.js
  ui/components/app/flask/copyable/index.scss
  ui/components/app/flask/snap-delineator/index.js
  ui/components/app/flask/snap-delineator/index.scss
  ui/components/app/flask/snap-delineator/snap-delineator.js
  ui/components/app/flask/snap-delineator/snap-delineator.stories.js
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/components/ui/icon/icon-copied.js
  ui/components/ui/icon/icon.stories.js
  ui/css/design-system/attributes.scss
  ui/helpers/constants/design-system.js
  ui/helpers/utils/permission.js
  ui/pages/confirmation/components/confirmation-footer/confirmation-footer.js
  ui/pages/confirmation/components/confirmation-footer/confirmation-footer.scss
  ui/pages/confirmation/confirmation.js
  ui/pages/confirmation/confirmation.scss
  ui/pages/confirmation/templates/add-ethereum-chain.js
  ui/pages/confirmation/templates/flask/snap-alert/snap-alert.js
  ui/pages/confirmation/templates/flask/snap-confirm/index.scss
  ui/pages/confirmation/templates/flask/snap-confirm/snap-confirm.js
  ui/pages/confirmation/templates/flask/snap-confirmation/snap-confirmation.js
  ui/pages/confirmation/templates/flask/snap-prompt/index.scss
  ui/pages/confirmation/templates/flask/snap-prompt/snap-prompt.js
  ui/pages/confirmation/templates/index.js
  ui/pages/confirmation/templates/switch-ethereum-chain.js
  ui/selectors/selectors.js
Labels: area-snaps, flask

#16669 `TextFieldSearch` house keeping 🧹
  ui/components/component-library/text-field-search/README.mdx
  ui/components/component-library/text-field-search/__snapshots__/text-field-search.test.js.snap
  ui/components/component-library/text-field-search/text-field-search.js
  ui/components/component-library/text-field-search/text-field-search.stories.js
  ui/components/component-library/text-field-search/text-field-search.test.js
Labels: area-UI, design-system, IA/NAV

#16667 `TextFieldBase` house keeping 🧹
  ui/components/component-library/icon/icon.stories.js
  ui/components/component-library/text-field-base/README.mdx
  ui/components/component-library/text-field-base/__snapshots__/text-field-base.test.js.snap
  ui/components/component-library/text-field-base/text-field-base.js
  ui/components/component-library/text-field-base/text-field-base.stories.js
  ui/components/component-library/text-field-base/text-field-base.test.js
  ui/components/component-library/text-field/text-field.js
Labels: area-UI, design-system, IA/NAV

#14811 Remove new address alert
  app/_locales/am/messages.json
  app/_locales/ar/messages.json
  app/_locales/bg/messages.json
  app/_locales/bn/messages.json
  app/_locales/ca/messages.json
  app/_locales/da/messages.json
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/et/messages.json
  app/_locales/fa/messages.json
  app/_locales/fi/messages.json
  app/_locales/fil/messages.json
  app/_locales/fr/messages.json
  app/_locales/he/messages.json
  app/_locales/hi/messages.json
  app/_locales/hr/messages.json
  app/_locales/hu/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/kn/messages.json
  app/_locales/ko/messages.json
  app/_locales/lt/messages.json
  app/_locales/lv/messages.json
  app/_locales/ms/messages.json
  app/_locales/no/messages.json
  app/_locales/ph/messages.json
  app/_locales/pl/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ro/messages.json
  app/_locales/ru/messages.json
  app/_locales/sk/messages.json
  app/_locales/sl/messages.json
  app/_locales/sr/messages.json
  app/_locales/sv/messages.json
  app/_locales/sw/messages.json
  app/_locales/th/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/uk/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  test/e2e/tests/address-book.spec.js
  test/e2e/tests/contract-interactions.spec.js
  test/e2e/tests/edit-gas-fee.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/send-hex-address.spec.js
  ui/components/app/confirm-page-container/confirm-page-container-container.test.js
  ui/components/app/confirm-page-container/confirm-page-container.component.js
  ui/components/app/confirm-page-container/confirm-page-container.container.js
  ui/components/app/confirm-page-container/enableEIP1559V2-notice/enableEIP1559V2-notice.js
  ui/components/app/confirm-page-container/enableEIP1559V2-notice/index.scss
  ui/pages/send/send-content/send-content.component.js
  ui/pages/send/send-content/send-content.container.js
  ui/pages/send/send-content/send-content.stories.js
Labels: PR - P1

#16851 NFTs: Update COLLECTIBLES_V1 to NFTS_V1
  .metamaskrc.dist
  app/scripts/metamask-controller.js
  development/build/config.js
  development/build/scripts.js
  ui/components/app/wallet-overview/token-overview.js
  ui/components/app/wallet-overview/token-overview.test.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/helpers/constants/settings.js
  ui/pages/home/home.component.js
  ui/pages/import-token/import-token.component.js
  ui/pages/import-token/import-token.test.js
  ui/pages/routes/routes.component.js
  ui/pages/settings/experimental-tab/experimental-tab.component.js
Labels: area-NFTs, team-extension-UX

#16723 housekeeping for tag url
  ui/components/component-library/tag-url/README.mdx
  ui/components/component-library/tag-url/tag-url.js
  ui/components/component-library/tag-url/tag-url.stories.js
  ui/components/component-library/tag-url/tag-url.test.js
Labels: area-UI, design-system, IA/NAV

#16839 [FLASK] `snaps-monorepo@0.26.1`
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: flask

#16785 [FLASK] Create E2E test for tx-insights
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  ui/components/app/confirm-page-container/flask/snap-insight.js
Labels: flask

#16605 [FLASK] Implement Snaps UI Renderer
  app/_locales/en/messages.json
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  ui/components/app/app-components.scss
  ui/components/app/flask/snap-ui-renderer/index.js
  ui/components/app/flask/snap-ui-renderer/index.scss
  ui/components/app/flask/snap-ui-renderer/snap-ui-renderer.js
  ui/components/app/flask/snap-ui-renderer/snap-ui-renderer.stories.js
  ui/components/app/flask/snap-ui-renderer/snap-ui-renderer.test.js
  ui/components/app/metamask-template-renderer/safe-component-list.js
  yarn.lock
Labels: flask

#16864 [FLASK] Fix a crash that occurred after a snap confirmation had been approved
  ui/pages/confirmation/confirmation.js
Labels: flask

#16894 [FLASK] De-flake snaps E2E tests
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
Labels: flask

#16911 [FLASK] Allow Snaps UI to use Markdown for text formatting
  lavamoat/browserify/flask/policy.json
  lavamoat/build-system/policy.json
  package.json
  ui/components/app/app-components.scss
  ui/components/app/flask/snap-ui-markdown/index.js
  ui/components/app/flask/snap-ui-markdown/index.scss
  ui/components/app/flask/snap-ui-markdown/snap-ui-markdown.js
  ui/components/app/flask/snap-ui-renderer/snap-ui-renderer.js
  ui/components/app/metamask-template-renderer/safe-component-list.js
  yarn.lock
Labels: flask

#16932 [FLASK] Bump snaps `iframe-execution-environment`
  app/scripts/metamask-controller.js
Labels: flask

#16956 [FLASK] Fix race condition with transaction insights
  ui/hooks/flask/useTransactionInsightSnap.js
Labels: flask

#16928 added goerli and sepolia inverse colors
  ui/components/ui/box/box.stories.js
  ui/css/design-system/colors.scss
  ui/helpers/constants/design-system.js
Labels: design-system

#16663 housekeeping for avatar network
  ui/components/component-library/avatar-network/README.mdx
  ui/components/component-library/avatar-network/__snapshots__/avatar-network.test.js.snap
  ui/components/component-library/avatar-network/avatar-network.constants.js
  ui/components/component-library/avatar-network/avatar-network.js
  ui/components/component-library/avatar-network/avatar-network.scss
  ui/components/component-library/avatar-network/avatar-network.stories.js
  ui/components/component-library/avatar-network/avatar-network.test.js
  ui/components/component-library/avatar-network/index.js
  ui/components/component-library/avatar-with-badge/README.mdx
  ui/components/component-library/avatar-with-badge/avatar-with-badge.stories.js
  ui/components/component-library/avatar-with-badge/avatar-with-badge.test.js
  ui/components/component-library/index.js
  ui/components/component-library/picker-network/__snapshots__/picker-network.test.js.snap
  ui/components/component-library/picker-network/picker-network.js
Labels: area-UI, design-system, IA/NAV

#16662 Avatar Token HouseKeeping
  ui/components/component-library/avatar-token/README.mdx
  ui/components/component-library/avatar-token/__snapshots__/avatar-token.test.js.snap
  ui/components/component-library/avatar-token/avatar-token.constants.js
  ui/components/component-library/avatar-token/avatar-token.js
  ui/components/component-library/avatar-token/avatar-token.scss
  ui/components/component-library/avatar-token/avatar-token.stories.js
  ui/components/component-library/avatar-token/avatar-token.test.js
Labels: area-UI, design-system, IA/NAV

#16905 Renaming broken stories to clean up console
  .storybook/main.js
  ui/components/component-library/avatar-base/avatar-base.stories.js
  ui/components/component-library/avatar-icon/avatar-icon.js
  ui/components/component-library/icon/icon.js
  ui/components/ui/box/box.stories.js
  ui/components/ui/color-indicator/color-indicator.stories.js
  ui/components/ui/list-item/list-item.stories.js
  ui/components/ui/truncated-definition-list/truncated-definition-list.stories.js
  ui/components/ui/update-nickname-popover/update-nickname-popover.stories.js
  ui/pages/confirm-approve/confirm-approve.stories-to-do.js
  ui/pages/confirm-deploy-contract/confirm-deploy-contract.stories-to-do.js
  ui/pages/confirm-send-ether/confirm-send-ether.stories-to-do.js
  ui/pages/confirm-send-token/confirm-send-token.stories-to-do.js
  ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.stories-to-do.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.stories-to-do.js
  ui/pages/send/send-content/add-recipient/add-recipient.stories.js
  ui/pages/send/send-content/send-gas-row/send-gas-row.stories.js
  ui/pages/swaps/exchange-rate-display/exchange-rate-display.stories.js
Labels: type-story

#16756 Security and Privacy Settings Re-org
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/ph/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/lib/util.js
  shared/constants/metametrics.js
  shared/lib/ui-utils.js
  test/e2e/fixture-builder.js
  test/e2e/restore/MetaMaskUserData.json
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/import-token/import-token.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/index.scss
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/security-tab/security-tab.test.js
  ui/store/actions.js
Labels: privacy

#16981 [FLASK] `snaps-monorepo@0.27.1`
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: flask

#16693 Moved subscribe and filter into network controller
  app/scripts/controllers/network/network-controller.js
  app/scripts/controllers/permissions/specifications.js
  app/scripts/metamask-controller.js
Labels: Extension QA Board

#16985 AvatarWithBadge Housekeeping
  ui/components/component-library/avatar-with-badge/README.mdx
  ui/components/component-library/avatar-with-badge/__snapshots__/avatar-with-badge.test.js.snap
  ui/components/component-library/avatar-with-badge/avatar-with-badge.constants.js
  ui/components/component-library/avatar-with-badge/avatar-with-badge.js
  ui/components/component-library/avatar-with-badge/avatar-with-badge.scss
  ui/components/component-library/avatar-with-badge/avatar-with-badge.stories.js
  ui/components/component-library/avatar-with-badge/avatar-with-badge.test.js
  ui/components/component-library/avatar-with-badge/index.js
  ui/components/component-library/index.js
Labels: area-UI, design-system, IA/NAV

#16801 [FLASK] Resolve `snap_dialog` approval on close
  app/scripts/background.js
Labels: flask

#17029 Add `codefi.network` host permission
  app/manifest/v2/_base.json
Labels: Extension QA Board

#16752 Prevent account name collisions
  app/_locales/am/messages.json
  app/_locales/en/messages.json
  app/_locales/fa/messages.json
  app/_locales/no/messages.json
  app/_locales/ta/messages.json
  package.json
  ui/components/app/modals/account-details-modal/account-details-modal.component.js
  ui/components/ui/editable-label/editable-label.js
  ui/components/ui/editable-label/editable-label.stories.js
  ui/components/ui/editable-label/index.scss
  ui/helpers/utils/accounts.js
  ui/pages/create-account/index.scss
  ui/pages/create-account/new-account.component.js
Labels: team-key-management
