Repository MetaMask/metamask-extension, pull requests merged in 2022-08, with the labels that each got.

#15307 added AvatarBase Component
  ui/components/component-library/base-avatar/README.mdx
  ui/components/component-library/base-avatar/base-avatar.js
  ui/components/component-library/base-avatar/base-avatar.scss
  ui/components/component-library/base-avatar/base-avatar.stories.js
  ui/components/component-library/base-avatar/base-avatar.test.js
  ui/components/component-library/base-avatar/index.js
  ui/components/component-library/component-library-components.scss
  ui/components/ui/box/box.js
  ui/components/ui/box/index.js
  ui/css/index.scss
Labels: area-UI, design-system, IA/NAV

#15388 Adding shadow docs to storybook
  .storybook/4.SHADOW.stories.mdx
  .storybook/5.BREAKPOINTS.stories.mdx
  .storybook/preview.js
Labels: area-documentation, design-system

#14781 MV3: Re-activate service worker and reconnect UI streams
  app/scripts/app-init.js
  app/scripts/ui.js
  ui/index.js
Labels: MV3, PR - P1

#15426 Moving incorrectly ordered page component to correct pages category
  .storybook/preview.js
  ui/pages/confirmation/components/confirmation-network-switch/confirmation-network-switch.stories.js
Labels: type-story

#14438 Add Sign-In with Ethereum
  .metamaskrc.dist
  app/_locales/en/messages.json
  app/scripts/lib/personal-message-manager.js
  development/build/scripts.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy.json
  package.json
  shared/modules/siwe.js
  ui/components/app/app-components.scss
  ui/components/app/permissions-connect-header/permissions-connect-header.component.js
  ui/components/app/signature-request-siwe/README.mdx
  ui/components/app/signature-request-siwe/index.js
  ui/components/app/signature-request-siwe/index.scss
  ui/components/app/signature-request-siwe/signature-request-siwe-header/index.js
  ui/components/app/signature-request-siwe/signature-request-siwe-header/index.scss
  ui/components/app/signature-request-siwe/signature-request-siwe-header/signature-request-siwe-header.js
  ui/components/app/signature-request-siwe/signature-request-siwe-header/signature-request-siwe-header.stories.js
  ui/components/app/signature-request-siwe/signature-request-siwe-message/index.js
  ui/components/app/signature-request-siwe/signature-request-siwe-message/index.scss
  ui/components/app/signature-request-siwe/signature-request-siwe-message/signature-request-siwe-message.js
  ui/components/app/signature-request-siwe/signature-request-siwe-message/signature-request-siwe-message.stories.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request-siwe/signature-request-siwe.stories.js
  ui/components/ui/site-origin/site-origin.js
  ui/components/ui/site-origin/site-origin.stories.js
  ui/pages/confirm-transaction/conf-tx.js
  yarn.lock
Labels: stedmap team

#15392 Update Babel and dependencies
  babel.config.js
  development/build/index.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy-override.json
  lavamoat/build-system/policy.json
  package.json
  patches/@babel+runtime+7.18.9.patch
  yarn.lock
Labels: Extension QA Board

#15481 [E2E]: Set approval for all e2e
  package.json
  test/e2e/ganache.js
  test/e2e/helpers.js
  test/e2e/seeder/ganache-seeder.js
  test/e2e/seeder/smart-contracts.js
  test/e2e/tests/collectibles.spec.js
  yarn.lock
Labels: Extension QA Board

#15218 Only check if a user has enough token balance before calling STX
  app/scripts/metamask-controller.js
  package.json
  ui/ducks/swaps/swaps.js
  ui/helpers/utils/conversions.util.js
  ui/helpers/utils/conversions.util.test.js
  ui/pages/swaps/build-quote/build-quote.js
  ui/pages/swaps/build-quote/build-quote.test.js
  ui/pages/swaps/view-quote/view-quote.js
  ui/store/actions.js
  yarn.lock
Labels: PR - P1

#14682 deps - patch ethereumjs-util/dist/secp256k1 for lazy loading
  patches/eth-sig-util++ethereumjs-util+5.2.1.patch
Labels: MV3, PR - P1

#15513 Fixing design system icon alternative color const
  ui/helpers/constants/design-system.js
Labels: design-system

#15518 Adding polymorphic 'as' prop to Box component and updating Typography component to use the same
  ui/components/app/create-new-vault/create-new-vault.js
  ui/components/app/edit-gas-display-education/edit-gas-display-education.component.js
  ui/components/app/edit-gas-display/edit-gas-display.component.js
  ui/components/app/flask/snap-settings-card/snap-settings-card.js
  ui/components/app/flask/snaps-authorship-pill/snaps-authorship-pill.js
  ui/components/app/recovery-phrase-reminder/recovery-phrase-reminder.js
  ui/components/ui/box/README.mdx
  ui/components/ui/box/box.js
  ui/components/ui/box/box.stories.js
  ui/components/ui/box/box.test.js
  ui/components/ui/chip/chip.js
  ui/components/ui/confusable/confusable.component.js
  ui/components/ui/definition-list/definition-list.js
  ui/components/ui/numeric-input/numeric-input.component.js
  ui/components/ui/typography/README.mdx
  ui/components/ui/typography/typography.js
  ui/components/ui/typography/typography.stories.js
  ui/components/ui/typography/typography.test.js
  ui/pages/first-time-flow/seed-phrase/seed-phrase-intro/seed-phrase-intro.component.js
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.js
  ui/pages/permissions-connect/flask/snap-install/snap-install.js
  ui/pages/permissions-connect/flask/snap-update/snap-update.js
  ui/pages/swaps/awaiting-signatures/awaiting-signatures.js
  ui/pages/swaps/build-quote/build-quote.js
  ui/pages/swaps/fee-card/fee-card.js
Labels: area-UI, design-system, IA/NAV

#14649 [e2e] Enabling/Disabling token conversion on testnets
  test/e2e/mock-e2e.js
  test/e2e/tests/advanced-settings.spec.js
Labels: area-testSuite, Extension QA Board

#15507 added color prop to Box component
  ui/components/ui/box/README.mdx
  ui/components/ui/box/box.js
  ui/components/ui/box/box.scss
  ui/components/ui/box/box.stories.js
  ui/components/ui/box/box.test.js
  ui/helpers/constants/design-system.js
Labels: design-system, IA/NAV

#15353 Capture user actions times for MV2 benchmark and generate artifacts
  .circleci/config.yml
  development/metamaskbot-build-announce.js
  package.json
  test/e2e/user-actions-benchmark.js
Labels: PR - P1

#15565 Adding initial and transparent to Box component
  ui/components/app/ledger-instruction-field/ledger-instruction-field.js
  ui/components/app/wallet-overview/index.scss
  ui/components/ui/box/README.mdx
  ui/components/ui/box/box.js
  ui/components/ui/box/box.stories.js
  ui/components/ui/box/box.test.js
  ui/components/ui/typography/README.mdx
  ui/components/ui/typography/typography.js
  ui/components/ui/typography/typography.stories.js
  ui/css/design-system/colors.scss
  ui/css/utilities/colors.scss
  ui/helpers/constants/design-system.js
  ui/pages/swaps/view-on-block-explorer/__snapshots__/view-on-block-explorer.test.js.snap
Labels: area-UI, design-system

#15448 Fix #14846 - Inject provider for MV3 via app-init
  app/manifest/v3/_base.json
  app/scripts/app-init.js
  app/scripts/contentscript.js
  app/scripts/inpage.js
  shared/modules/provider-injection.js
Labels: PR - P1

#15553 [e2e] Refactor contract-interactions spec using Ganache seeder
  test/e2e/tests/contract-interactions.spec.js
Labels: Extension QA Board

#15601 [e2e] Refactor failing-contract spec using Ganache seeder
  test/e2e/tests/failing-contract.spec.js
Labels: Extension QA Board

#15607 Token Detection clean up - Fixing swaps performance slow down
  ui/hooks/useTokensToSearch.js
  ui/pages/swaps/build-quote/build-quote.js
Labels: area-tokens

#15605 [e2e] Refactor send-to-contract spec using Ganache seeder
  test/e2e/tests/send-to-contract.spec.js
Labels: Extension QA Board

#15289 New metrics data for token approval transactions
  app/scripts/controllers/transactions/index.js
  shared/constants/transaction.js
  ui/pages/confirm-approve/confirm-approve.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: area-metrics

#15609 Adding `BaseIcon` UI component
  ui/components/component-library/base-icon/README.mdx
  ui/components/component-library/base-icon/base-icon.js
  ui/components/component-library/base-icon/base-icon.scss
  ui/components/component-library/base-icon/base-icon.stories.js
  ui/components/component-library/base-icon/base-icon.test.js
  ui/components/component-library/base-icon/index.js
  ui/components/component-library/component-library-components.scss
  ui/components/ui/box/box.js
  ui/helpers/constants/design-system.js
Labels: area-UI, design-system, IA/NAV

#15621 Fix Signature Request styles
  ui/components/app/signature-request-original/index.scss
  ui/components/app/signature-request-original/signature-request-original.component.js
Labels: type-bug

#15466 added avatar token component
  ui/components/component-library/avatar-token/README.mdx
  ui/components/component-library/avatar-token/avatar-token.js
  ui/components/component-library/avatar-token/avatar-token.scss
  ui/components/component-library/avatar-token/avatar-token.stories.js
  ui/components/component-library/avatar-token/avatar-token.test.js
  ui/components/component-library/avatar-token/index.js
  ui/components/component-library/base-avatar/README.mdx
  ui/components/component-library/base-avatar/base-avatar.js
  ui/components/component-library/base-avatar/base-avatar.scss
  ui/components/component-library/base-avatar/base-avatar.stories.js
  ui/components/component-library/component-library-components.scss
Labels: design-system, IA/NAV

#15502 added avatar network component
  ui/components/component-library/avatar-network/README.mdx
  ui/components/component-library/avatar-network/avatar-network.js
  ui/components/component-library/avatar-network/avatar-network.scss
  ui/components/component-library/avatar-network/avatar-network.stories.js
  ui/components/component-library/avatar-network/avatar-network.test.js
  ui/components/component-library/avatar-network/index.js
  ui/components/component-library/avatar-token/README.mdx
  ui/components/component-library/avatar-token/avatar-token.test.js
  ui/components/component-library/component-library-components.scss
Labels: design-system, IA/NAV

#15602 Add test case to ensure that action addCustomNetwork is idempotent
  app/scripts/metamask-controller.actions.test.js
Labels: PR - P1

#15587 Add unit test coverage to ensure that addToken method is idempotent.
  app/scripts/metamask-controller.actions.test.js
Labels: PR - P1

#15583 Adding unit test case to for idempotent behaviour of importAccountWithStrategy idempotent
  app/scripts/metamask-controller.actions.test.js
Labels: PR - P1

#15468 Add validation to production build script
  .circleci/config.yml
  .gitignore
  .metamaskrc.dist
  development/build/config.js
  development/build/constants.js
  development/build/index.js
  development/build/scripts.js
  development/build/utils.js
  package.json
Labels: Extension QA Board

#15672 Fix Sentry in LavaMoat contexts
  app/scripts/background.js
  app/scripts/sentry-install.js
  patches/@lavamoat+lavapack+3.1.0.patch
  ui/index.js
Labels: Extension QA Board

#13319 New network info popup
  app/_locales/en/messages.json
  app/scripts/controllers/app-state.js
  app/scripts/metamask-controller.js
  shared/constants/tokens.js
  ui/components/ui/new-network-info/index.js
  ui/components/ui/new-network-info/index.scss
  ui/components/ui/new-network-info/new-network-info.js
  ui/components/ui/new-network-info/new-network-info.test.js
  ui/components/ui/ui-components.scss
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/selectors/selectors.js
  ui/store/actions.js
Labels: Team 🌱

#15677 Fix Sentry deduplication of events that were never sent
  app/scripts/lib/sentry-filter-events.ts
  app/scripts/lib/setupSentry.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: Extension QA Board

#13869 add e2e test for default icons
  test/e2e/tests/settings-general.spec.js
  test/e2e/tests/threebox.spec.js
Labels: area-testSuite, Extension QA Board

#15715 Sentry e2e test
  app/scripts/lib/setupSentry.js
  package.json
  test/e2e/mock-e2e.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/metrics.spec.js
Labels: Extension QA Board
