Repository MetaMask/metamask-extension, pull requests merged in 2022-06, with the labels that each got.

#14605 Snap notifications integration
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  test/data/mock-state.json
  ui/components/app/account-menu/account-menu.component.js
  ui/components/app/account-menu/account-menu.container.js
  ui/components/app/account-menu/index.scss
  ui/components/app/app-header/app-header.component.js
  ui/components/app/app-header/app-header.container.js
  ui/components/app/app-header/index.scss
  ui/helpers/constants/notifications.js
  ui/helpers/constants/routes.js
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/notifications/index.js
  ui/pages/notifications/index.scss
  ui/pages/notifications/notification.test.js
  ui/pages/notifications/notifications.js
  ui/pages/pages.scss
  ui/pages/routes/routes.component.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.js
Labels: area-snaps

#14786 Storybook: add TransactionListItem component page
  .storybook/initial-states/transactions.js
  ui/components/app/transaction-list-item/transaction-list-item.stories.js
Labels: type-story, stedmap team

#14835 Updating icon color
  ui/components/app/collectibles-items/collectibles-items.js
  ui/components/app/collectibles-items/index.scss
Labels: area-UI

#14810 manifest.json: add https://chainid.network/chains.json to permissions
  app/manifest/v2/_base.json
  app/manifest/v3/_base.json
Labels: stedmap team

#14272 Allow locally hosted RPC and Block Explorer Urls with `wallet_addEthereumChain`
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
Labels: stedmap team

#14756 Fix to infinite loading on approve screen
  app/_locales/en/messages.json
  ui/hooks/useAssetDetails.js
  ui/hooks/useAssetDetails.test.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-approve/confirm-approve-content/index.scss
  ui/pages/confirm-approve/confirm-approve.js
Labels: stedmap team

#14823 Fix for: Invalid transaction envelope type: specified type "0x0" but including...requires type: "0x2"
  app/scripts/controllers/transactions/pending-tx-tracker.js
  app/scripts/controllers/transactions/tx-state-manager.js
  app/scripts/controllers/transactions/tx-state-manager.test.js
Labels: area-Sentry, stedmap team

#14962 MetaMetrics: Fixes TypeError: Object.values(...).reduce(...).flat is not a function
  app/scripts/controllers/metametrics.js
Labels: area-Sentry, stedmap team

#14857 Fix/14856 network settings page
  ui/components/app/dropdowns/network-dropdown.js
  ui/components/app/dropdowns/network-dropdown.test.js
  ui/components/app/network-display/network-display.js
  ui/components/ui/color-indicator/color-indicator.js
  ui/components/ui/text-field/index.scss
  ui/helpers/constants/design-system.js
  ui/pages/settings/networks-tab/index.scss
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js
  ui/pages/settings/networks-tab/networks-list/networks-list.js
  ui/pages/settings/networks-tab/networks-tab.js
Labels: area-UI

#14788 Sentry documentation
  README.md
  development/README.md
Labels: Extension QA Board

#14972 Only have timeout for when payload is getState
  app/scripts/lib/metaRPCClientFactory.js
  app/scripts/lib/metaRPCClientFactory.test.js
Labels: stedmap team

#13980 Fix edit-gas-display render Storybook
  ui/components/app/edit-gas-display/edit-gas-display.component.js
Labels: type-story

#14992 Fixing tooltip theming by enforcing default theme
  ui/components/app/edit-gas-fee-popover/network-statistics/tooltips.js
  ui/components/ui/info-tooltip/index.scss
  ui/components/ui/info-tooltip/info-tooltip.js
  ui/components/ui/info-tooltip/info-tooltip.stories.js
  ui/components/ui/tooltip/index.scss
  ui/components/ui/tooltip/tooltip.js
  ui/components/ui/tooltip/tooltip.stories.js
  ui/pages/swaps/fee-card/fee-card.js
  ui/pages/swaps/main-quote-summary/main-quote-summary.js
  ui/pages/swaps/view-quote/view-quote-price-difference.js
Labels: area-UI, theming

#15071 UI and storybook updates
  ui/components/app/collectible-default-image/collectible-default-image.js
  ui/components/app/collectible-default-image/collectible-default-image.stories.js
  ui/components/app/collectible-default-image/index.scss
  ui/components/app/collectible-details/collectible-details.js
  ui/components/app/collectible-details/collectible-details.stories.js
  ui/components/app/collectibles-items/collectibles-items.js
Labels: area-UI
