Repository MetaMask/metamask-extension, pull requests merged in 2022-04, with the labels that each got.

#14315 Fixing account details label colors
  ui/components/ui/editable-label/editable-label.stories.js
  ui/components/ui/editable-label/index.scss
Labels: theming, rc :package:

#14308 Fix/14302 about fox logo
  app/images/info-logo.png
  app/phishing.html
  ui/pages/settings/info-tab/index.scss
  ui/pages/settings/info-tab/info-tab.component.js
  ui/pages/settings/info-tab/info-tab.stories.js
Labels: theming, rc :package:

#14322 Fix Buy Ether via Moonpay and Wyre actions
  ui/components/app/modals/deposit-ether-modal/deposit-ether-modal.component.js
Labels: rc :package:

#14274 Token Value component for Tokens Detected page
  .storybook/test-data.js
  ui/components/app/app-components.scss
  ui/components/app/detected-token/detected-token-values/detected-token-values.js
  ui/components/app/detected-token/detected-token-values/detected-token-values.stories.js
  ui/components/app/detected-token/detected-token-values/detected-token-values.test.js
  ui/components/app/detected-token/detected-token-values/index.scss
Labels: area-tokens, QA Board, transaction safety team

#14312 Dark Mode: Fix QR display
  ui/components/app/qr-hardware-popover/qr-hardware-sign-request/player.js
  ui/css/utilities/colors.scss
Labels: theming, rc :package:

#14334 color fix for hover on swaps quote
  ui/pages/swaps/select-quote-popover/index.scss
Labels: theming, rc :package:

#14169 Token Details component for Tokens Detected page
  ui/components/app/app-components.scss
  ui/components/app/detected-token/detected-token-details/detected-token-details.js
  ui/components/app/detected-token/detected-token-details/detected-token-details.stories.js
  ui/components/app/detected-token/detected-token-details/detected-token-details.test.js
  ui/components/app/detected-token/detected-token-details/index.scss
Labels: area-tokens, QA Board, transaction safety team

#14318 Adding the link component to load Tokens found page
  app/_locales/en/messages.json
  ui/components/app/app-components.scss
  ui/components/app/asset-list/detetcted-tokens-link/detected-tokens-link.js
  ui/components/app/asset-list/detetcted-tokens-link/index.scss
  ui/selectors/selectors.js
Labels: area-tokens, QA Board

#14317 Update eth-ledger-bridge-keyring to 0.11.0
  package.json
  yarn.lock
Labels: rc :package:

#14333 Updatin contract deployment text label to be darker
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-summary/index.scss
Labels: theming, rc :package:

#14337 update chromedriver and chrome binary to v100
  .circleci/scripts/chrome-install.sh
  package.json
  yarn.lock
Labels: area-testSuite, Team 🌳, QA Board

#14259 Add e2e testcase for Settings Search functionality
  test/e2e/tests/settings-search.spec.js
Labels: Team 🌳, QA Board

#14361 Dark Mode: Fix Actionable Messages
  ui/components/ui/actionable-message/index.scss
Labels: theming, rc :package:

#14346 Dark Mode: What's New Announcement
  app/_locales/en/messages.json
  app/images/darkmode-banner.png
  shared/notifications/index.js
  test/e2e/fixtures/address-entry/state.json
  test/e2e/fixtures/connected-state/state.json
  test/e2e/fixtures/custom-rpc/state.json
  test/e2e/fixtures/custom-token/state.json
  test/e2e/fixtures/eip-1559-v2-dapp/state.json
  test/e2e/fixtures/eip-1559-v2/state.json
  test/e2e/fixtures/import-ui/state.json
  test/e2e/fixtures/imported-account/state.json
  test/e2e/fixtures/localization/state.json
  test/e2e/fixtures/metrics-enabled/state.json
  test/e2e/fixtures/navigate-transactions/state.json
  test/e2e/fixtures/onboarding/state.json
  test/e2e/fixtures/send-edit-v2/state.json
  test/e2e/fixtures/send-edit/state.json
  test/e2e/fixtures/threebox-enabled/state.json
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: theming, rc :package:

#14348 Settings:TabBar: Fix text wrap style
  ui/components/app/tab-bar/index.scss
Labels: Team 🌳

#14353 Feature Flag Swap API mock
  test/e2e/mock-e2e.js
Labels: Team 🌳, QA Board

#14251 Update token detection logic to only control auto-detection
  ui/components/ui/identicon/identicon.component.js
  ui/components/ui/nickname-popover/nickname-popover.component.js
  ui/components/ui/update-nickname-popover/update-nickname-popover.js
  ui/helpers/utils/icon-factory.js
  ui/hooks/useAddressDetails.js
  ui/hooks/useTokensToSearch.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/import-token/token-list/token-list.component.js
  ui/pages/token-details/token-details-page.js
Labels: area-tokens, QA Board, transaction safety team

#14331 Storybook housekeeping 🧹
  ui/components/app/app-header/app-header.stories.js
  ui/components/app/modals/confirm-remove-account/confirm-remove-account.stories.js
  ui/components/app/modals/export-private-key-modal/export-private-key-modal.stories.js
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.stories.js
  ui/pages/first-time-flow/seed-phrase/reveal-seed-phrase/reveal-seed-phrase.stories.js
  ui/pages/permissions-connect/redirect/permissions-redirect.stories.js
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.stories.js
Labels: type-story

#14375 Update ganache
  package.json
  yarn.lock
Labels: area-testSuite, Team 🌳, QA Board

#14385 Updating info ActionableMessage type to default
  ui/pages/import-token/import-token.component.js
  ui/pages/import-token/import-token.container.js
Labels: area-tokens

#14181 Changes in build for new service worker added (#13975)
  .metamaskrc.dist
  app/manifest/mv3/_base.json
  app/manifest/mv3/brave.json
  app/manifest/mv3/chrome.json
  app/manifest/mv3/firefox.json
  app/manifest/mv3/opera.json
  app/scripts/app-init.js
  app/scripts/background.js
  development/build/manifest.js
  development/build/scripts.js
  package.json
Labels: MV3, stedmap team

#14108 Fix script tag injection in MV3
  app/manifest/mv3/_base.json
  app/scripts/contentscript.js
Labels: MV3, stedmap team

#14047 Fix delayed loading of UI in MV3
  app/home.html
  app/scripts/background.js
  app/scripts/ui.js
Labels: MV3, stedmap team

#14394 E2e infura requests
  test/e2e/mock-e2e.js
Labels: Team 🌳, QA Board

#14423 Remove unused function
  test/data/fetch-mocks.json
  test/e2e/webdriver/index.js
Labels: Team 🌳, QA Board

#14411 Swap : Fix undefined icon url
  ui/hooks/useTokensToSearch.js
Labels: area-swaps

#14386 E2e settings search msgs
  test/e2e/tests/settings-search.spec.js
Labels: Team 🌳, QA Board

#14216 Update DetectTokenController for token detection v2
  app/_locales/en/messages.json
  app/scripts/controllers/detect-tokens.js
  app/scripts/metamask-controller.js
  shared/modules/network.utils.js
  ui/components/app/app-components.scss
  ui/components/app/asset-list/detetcted-tokens-link/detected-tokens-link.js
  ui/components/app/asset-list/detetcted-tokens-link/index.scss
  ui/selectors/selectors.js
  ui/store/actions.js
Labels: area-tokens, QA Board, transaction safety team

#14382 track address book usage
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
  shared/constants/metametrics.js
Labels: area-metrics, Team 🌳

#14378 enable skipped test
  test/e2e/tests/phishing-detection.spec.js
Labels: area-testSuite, Team 🌳, QA Board

#14392 Enhanced Gas Fee UI : Fix gas values overlaping with labels
  ui/components/app/edit-gas-fee-popover/edit-gas-tooltip/index.scss
Labels: area-UI, area-transactions, EIP-1559-V2

#14367 MetaMetrics: Identify 'nft_autodetection_enabled' & 'opensea_api_enabled'
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
  shared/constants/metametrics.js
Labels: area-metrics, Team 🌳

#14427 MetaMetrics: Identify 'number_of_tokens' user trait
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
  shared/constants/metametrics.js
Labels: Team 🌳

#13785 HoldToRevealButton component
  app/_locales/en/messages.json
  app/images/lock-icon.svg
  app/images/unlock-icon.svg
  ui/components/app/app-components.scss
  ui/components/app/hold-to-reveal-button/hold-to-reveal-button.js
  ui/components/app/hold-to-reveal-button/hold-to-reveal-button.stories.js
  ui/components/app/hold-to-reveal-button/hold-to-reveal-button.test.js
  ui/components/app/hold-to-reveal-button/index.js
  ui/components/app/hold-to-reveal-button/index.scss
Labels: team-key-management

#14435 Docs - segment metrics
  README.md
  development/README.md
  docs/README.md
Labels: Team 🌳

#14444 E2e connected state
  test/e2e/fixtures/navigate-transactions/state.json
  test/e2e/tests/contract-interactions.spec.js
  test/e2e/tests/failing-contract.spec.js
  test/e2e/tests/navigate-transactions.spec.js
  test/e2e/tests/send-eth.spec.js
Labels: Team 🌳, QA Board

#14434 E2e readme docs
  README.md
Labels: Team 🌳, QA Board

#14535 Update Dark Mode What's New message
  app/_locales/en/messages.json
Labels: rc :package:

#14553 Updating text/muted to text/alternative for select text on home screen
  ui/components/app/selected-account/index.scss
  ui/components/app/wallet-overview/index.scss
  ui/components/ui/list-item/index.scss
  ui/pages/home/home.component.js
Labels: area-UI, theming

#14537 Lavamoat - protect all UI contexts
  development/build/scripts.js
  lavamoat/browserify/beta/policy-override.json
  lavamoat/browserify/flask/policy-override.json
  lavamoat/browserify/main/policy-override.json
  patches/zxcvbn+4.4.2.patch
Labels: QA Board
