Repository MetaMask/metamask-extension, pull requests merged in 2022-11, with the labels that each got.

#16310 Chromedriver v107
  .circleci/scripts/chrome-install.sh
  package.json
  yarn.lock
Labels: Extension QA Board

#16014 add e2e test for editing and deleting contact from address book
  test/e2e/tests/address-book.spec.js
Labels: PS-team, Extension QA Board

#16354 [FLASK] Fix crash on snaps settings page if snap has no permissions
  ui/selectors/permissions.js
Labels: flask

#16335 Fix issue where ens resolution stops working after sw is terminated
  ui/ducks/ens.js
Labels: PR - P1

#16293 Adding HelpText component
  ui/components/component-library/help-text/README.mdx
  ui/components/component-library/help-text/help-text.js
  ui/components/component-library/help-text/help-text.stories.js
  ui/components/component-library/help-text/help-text.test.js
  ui/components/component-library/help-text/index.js
Labels: area-UI, design-system, IA/NAV

#16203 Adding Label component
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/label/README.mdx
  ui/components/component-library/label/index.js
  ui/components/component-library/label/label.js
  ui/components/component-library/label/label.scss
  ui/components/component-library/label/label.stories.js
  ui/components/component-library/label/label.test.js
Labels: area-UI, design-system, IA/NAV

#15774 Show error message if service worker did not load (respond to the UI)
  app/_locales/en/messages.json
  app/scripts/background.js
  app/scripts/ui.js
  shared/lib/error-utils.js
  shared/lib/error-utils.test.js
  ui/css/errors.scss
Labels: PR - P1

#16355 tag component housekeeping
  ui/components/component-library/tag/README.mdx
  ui/components/component-library/tag/__snapshots__/tag.test.js.snap
  ui/components/component-library/tag/tag.js
  ui/components/component-library/tag/tag.scss
  ui/components/component-library/tag/tag.stories.js
  ui/components/component-library/tag/tag.test.js
Labels: design-system, IA/NAV

#16365 [FLASK] Fix some issues with installing snaps that request eth_accounts
  ui/pages/permissions-connect/permissions-connect.component.js
Labels: flask

#16074 Fix the rendering of certain domain names in connected-sites list
  CHANGELOG.md
  test/e2e/tests/dapp-interactions.spec.js
  ui/components/app/signature-request-original/__snapshots__/signature-request-original.test.js.snap
  ui/components/ui/site-origin/site-origin.js
  ui/components/ui/site-origin/site-origin.test.js
Labels: Extension QA Board

#16344 Fix issue with awaiting swaps page
  test/jest/mock-store.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/swaps/awaiting-swap/awaiting-swap.js
  ui/pages/swaps/awaiting-swap/awaiting-swap.test.js
  ui/pages/swaps/index.js
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.js
  ui/selectors/selectors.js
Labels: PR - P1

#14245 [Bug]: Balance does not update on duplicate chainId network #13690
  app/scripts/lib/account-tracker.js
  app/scripts/metamask-controller.js
Labels: PR - P1

#16402 HelpText propType fix
  ui/components/component-library/help-text/help-text.js
Labels: area-UI, design-system

#16198 Persisting segment events in MetaMetricsController store
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
  app/scripts/lib/segment/analytics.js
  app/scripts/lib/util.js
Labels: Extension QA Board

#16407 Fix to direct the token detection settings search to the correct row
  ui/pages/settings/advanced-tab/advanced-tab.component.js
Labels: type-bug

#16267 Make event tracking idempotent using unique messageId
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
  app/scripts/metamask-controller.js
  ui/store/actions.js
Labels: PR - P1

#16239 [FLASK] Add snap cronjobs
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  shared/constants/permissions.ts
  ui/helpers/utils/permission.js
Labels: flask

#16416 [FLASK] Catch and display error in snaps insight
  app/_locales/en/messages.json
  ui/components/app/confirm-page-container/flask/snap-insight.js
  ui/hooks/flask/useTransactionInsightSnap.js
Labels: flask

#16343 BETA - Update verbiage for success messages after onboarding
  app/_locales/en/messages.json
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/onboarding-flow/creation-successful/creation-successful.js
  ui/pages/settings/info-tab/index.scss
  ui/pages/settings/info-tab/info-tab.component.js
Labels: PR - P1

#16159 Added Tag Url Component
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/tag-url/README.mdx
  ui/components/component-library/tag-url/__snapshots__/tag-url.test.js.snap
  ui/components/component-library/tag-url/index.js
  ui/components/component-library/tag-url/tag-url.js
  ui/components/component-library/tag-url/tag-url.scss
  ui/components/component-library/tag-url/tag-url.stories.js
  ui/components/component-library/tag-url/tag-url.test.js
Labels: design-system, IA/NAV

#16383 Upgrade geckodriver to latest version, run ci tests with Firefox v106.0.4
  .circleci/scripts/firefox-install.sh
  package.json
  yarn.lock
Labels: Extension QA Board

#16473 [FLASK] Fix an issue with updating snaps that have caveat permissions
  ui/components/app/flask/update-snap-permission-list/update-snap-permission-list.js
Labels: flask

#16075 MV3: Update service worker restart logic and keep-alive logic for dapp support
  app/scripts/background.js
  app/scripts/contentscript.js
  app/scripts/lib/util.js
  shared/constants/app.ts
  shared/modules/browser-runtime.utils.js
Labels: Extension QA Board, PR - P1

#11212 [i18n:zh_tw] Sync and update translation for zh_TW
  app/_locales/zh_TW/messages.json
Labels: type-i18n

#16486 added 50% border radius support to the Box component
  ui/components/ui/box/README.mdx
  ui/components/ui/box/box.scss
  ui/components/ui/box/box.stories.js
  ui/components/ui/box/box.test.js
  ui/helpers/constants/design-system.js
Labels: area-UI, design-system

#16439 upgrade gulp-autoprefixer
  .browserslistrc
  lavamoat/build-system/policy.json
  package.json
  ui/components/app/transaction-detail-item/index.scss
  ui/components/app/transaction-list-item-details/index.scss
  ui/components/ui/list-item/index.scss
  ui/components/ui/page-container/index.scss
  ui/pages/permissions-connect/index.scss
  yarn.lock
Labels: Extension QA Board

#16296 Adding `TextFieldSearch` component
  test/lib/render-helpers.js
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/text-field-base/text-field-base.constants.js
  ui/components/component-library/text-field-search/README.mdx
  ui/components/component-library/text-field-search/index.js
  ui/components/component-library/text-field-search/text-field-search.js
  ui/components/component-library/text-field-search/text-field-search.scss
  ui/components/component-library/text-field-search/text-field-search.stories.js
  ui/components/component-library/text-field-search/text-field-search.test.js
  ui/components/component-library/text-field/text-field.js
  ui/components/component-library/text-field/text-field.test.js
Labels: area-UI, design-system, IA/NAV

#16508 Adding some propType fixes to `TextFieldBase`
  ui/components/component-library/text-field-base/text-field-base.js
  ui/components/component-library/text-field-base/text-field-base.test.js
Labels: area-UI, design-system

#16505 Beta: Update long logo to new imagery
  ui/components/ui/metafox-logo/horizontal-logo.js
Labels: PR - P1

#16307 BETA - Add beta banner to all screens
  app/_locales/en/messages.json
  app/scripts/controllers/app-state.js
  app/scripts/metamask-controller.js
  test/data/mock-state.json
  ui/components/app/app-components.scss
  ui/components/app/app-header/app-header.component.js
  ui/components/app/app-header/app-header.container.js
  ui/components/app/beta-header/__snapshots__/beta-header.test.js.snap
  ui/components/app/beta-header/beta-header.stories.js
  ui/components/app/beta-header/beta-header.test.js
  ui/components/app/beta-header/index.js
  ui/components/app/beta-header/index.scss
  ui/helpers/constants/beta.js
  ui/selectors/selectors.js
  ui/store/actions.js
Labels: PR - P1

#16489 Updating welcome message
  app/_locales/en/messages.json
  ui/pages/first-time-flow/welcome/beta-welcome-footer.component.js
  ui/pages/first-time-flow/welcome/index.scss
  ui/pages/first-time-flow/welcome/welcome-footer.component.js
Labels: PR - P1

#16441 Component library adding global index and other housekeeping
  development/generate-icon-names.js
  ui/components/component-library/button-base/README.mdx
  ui/components/component-library/button-base/button-base.js
  ui/components/component-library/button-link/README.mdx
  ui/components/component-library/button-primary/README.mdx
  ui/components/component-library/button-secondary/README.mdx
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/help-text/README.mdx
  ui/components/component-library/icon/README.mdx
  ui/components/component-library/index.js
  ui/components/component-library/label/README.mdx
  ui/components/component-library/text-field-base/README.mdx
  ui/components/component-library/text-field/README.mdx
  ui/components/component-library/text/README.mdx
Labels: area-UI, design-system, IA/NAV

#16519 Updating background hover colors with new color design tokens
  ui/components/app/account-menu/index.scss
  ui/components/app/connected-status-indicator/index.scss
  ui/components/app/dropdowns/dropdown.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/index.scss
  ui/components/app/flask/snaps-authorship-pill/index.scss
  ui/components/app/selected-account/index.scss
  ui/components/app/transaction-decoding/components/ui/copy-raw-data/index.scss
  ui/components/ui/list-item/index.scss
  ui/components/ui/menu/menu.scss
  ui/css/itcss/components/send.scss
  ui/pages/create-account/connect-hardware/index.scss
  ui/pages/notifications/index.scss
  ui/pages/settings/index.scss
  ui/pages/swaps/dropdown-search-list/index.scss
  ui/pages/swaps/searchable-item-list/index.scss
Labels: area-UI, design-system

#16543 Updating network colors with design tokens
  .storybook/test-data.js
  ui/components/app/flask/experimental-area/index.scss
  ui/css/design-system/colors.scss
  ui/css/utilities/colors.scss
Labels: area-UI, design-system

#16570 Updated Text style in Tag Url
  ui/components/component-library/tag-url/__snapshots__/tag-url.test.js.snap
  ui/components/component-library/tag-url/tag-url.js
Labels: area-UI, design-system, IA/NAV

#16466 updated background color for picker network
  ui/components/component-library/picker-network/__snapshots__/picker-network.test.js.snap
  ui/components/component-library/picker-network/picker-network.js
  ui/components/component-library/picker-network/picker-network.scss
Labels: area-UI, design-system, IA/NAV

#16535 Updating tokensChainsCache[chainId].data to object from array in user state
  app/scripts/migrations/077.js
  app/scripts/migrations/077.test.js
  app/scripts/migrations/index.js
Labels: type-bug, Sev2-normal, team-extension-client

#16510 updated responsive props for border radius
  ui/components/ui/box/box.scss
  ui/components/ui/box/box.stories.js
  ui/css/design-system/attributes.scss
Labels: area-UI, design-system

#16597 [FLASK] Improve Snaps E2E stability
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-confirm.spec.js
  test/e2e/snaps/test-snap-error.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-update.spec.js
Labels: flask

#16599 [e2e] [MV3] Fix Custom RPC e2e test failures for MV3 build
  test/e2e/tests/custom-rpc-history.spec.js
  test/e2e/webdriver/driver.js
Labels: Extension QA Board

#16611 added sm border radius
  ui/css/design-system/attributes.scss
Labels: area-UI, design-system

#16525 [FLASK] `snaps-monorepo@0.24.1`
  app/_locales/en/messages.json
  app/scripts/controllers/permissions/flask/snap-permissions.js
  app/scripts/controllers/permissions/specifications.js
  app/scripts/controllers/permissions/specifications.test.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/policy-override.json
  package.json
  shared/constants/permissions.test.js
  shared/constants/permissions.ts
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-update.spec.js
  ui/components/app/permissions-connect-permission-list/index.scss
  ui/helpers/utils/permission.js
  ui/pages/permissions-connect/flask/util.js
  yarn.lock
Labels: flask

#16526 [FLASK] Fix a crash that happens after snap install
  ui/pages/permissions-connect/flask/snap-install/snap-install.js
Labels: flask

#16503 [FLASK] Clear notification state on restore
  app/scripts/metamask-controller.js
Labels: flask

#15913 Keep memstore contents after service worker restarts
  app/scripts/app-init.js
  app/scripts/controllers/ens/index.js
  app/scripts/controllers/swaps.js
  app/scripts/controllers/transactions/index.js
  app/scripts/lib/account-tracker.js
  app/scripts/lib/decrypt-message-manager.js
  app/scripts/lib/encryption-public-key-manager.js
  app/scripts/lib/message-manager.js
  app/scripts/lib/personal-message-manager.js
  app/scripts/lib/typed-message-manager.js
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: PR - P1

#16629 Fixed tag propType issue in unit tests
  ui/components/component-library/tag/tag.js
Labels: area-UI, design-system

#16583 avatar base component housekeeping
  ui/components/component-library/avatar-account/avatar-account.js
  ui/components/component-library/avatar-base/README.mdx
  ui/components/component-library/avatar-base/__snapshots__/avatar-base.test.js.snap
  ui/components/component-library/avatar-base/avatar-base.constants.js
  ui/components/component-library/avatar-base/avatar-base.js
  ui/components/component-library/avatar-base/avatar-base.scss
  ui/components/component-library/avatar-base/avatar-base.stories.js
  ui/components/component-library/avatar-base/avatar-base.test.js
  ui/components/component-library/avatar-base/index.js
  ui/components/component-library/avatar-favicon/avatar-favicon.js
  ui/components/component-library/avatar-network/avatar-network.js
  ui/components/component-library/avatar-network/avatar-network.stories.js
  ui/components/component-library/avatar-token/avatar-token.js
  ui/components/component-library/avatar-token/avatar-token.stories.js
  ui/components/component-library/base-avatar/README.mdx
  ui/components/component-library/base-avatar/base-avatar.test.js
  ui/components/component-library/base-avatar/index.js
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/index.js
  ui/components/component-library/picker-network/__snapshots__/picker-network.test.js.snap
  ui/components/component-library/tag-url/__snapshots__/tag-url.test.js.snap
Labels: area-UI, design-system, IA/NAV

#16621 Icon house keeping updates
  ui/components/component-library/avatar-favicon/avatar-favicon.test.js
  ui/components/component-library/button-icon/__snapshots__/button-icon.test.js.snap
  ui/components/component-library/button-link/button-link.test.js
  ui/components/component-library/button-primary/button-primary.test.js
  ui/components/component-library/button-secondary/button-secondary.test.js
  ui/components/component-library/icon/README.mdx
  ui/components/component-library/icon/__snapshots__/icon.test.js.snap
  ui/components/component-library/icon/icon.constants.js
  ui/components/component-library/icon/icon.js
  ui/components/component-library/icon/icon.scss
  ui/components/component-library/icon/icon.stories.js
  ui/components/component-library/icon/icon.test.js
  ui/components/component-library/icon/index.js
  ui/components/component-library/index.js
  ui/components/component-library/picker-network/__snapshots__/picker-network.test.js.snap
  ui/components/component-library/tag-url/__snapshots__/tag-url.test.js.snap
  ui/components/component-library/text-field-base/text-field-base.js
  ui/components/component-library/text-field-base/text-field-base.scss
Labels: area-UI, design-system, IA/NAV

#15558 Fix #15050 - MV3: Keep the user logged in when service worker restarts
  app/scripts/background.js
  app/scripts/metamask-controller.js
  app/scripts/ui.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/policy-override.json
  lavamoat/build-system/policy.json
  package.json
  test/e2e/tests/from-import-ui.spec.js
  test/lib/mock-encryptor.js
  yarn.lock
Labels: MV3, PR - P1

#16603 [e2e] [MV3] Fix Add Account e2e flaky test for MV3 build
  test/e2e/tests/add-account.spec.js
Labels: Extension QA Board

#16655 [e2e] [MV3] Mitigate completely flaky test Deletes custom RPC
  test/e2e/tests/custom-rpc-history.spec.js
Labels: Extension QA Board

#16659 Resetting spending cap value to empty when a token allowance request is rejected.
  ui/pages/token-allowance/token-allowance.js
Labels: type-bug, area-transactions, rc :heavy_check_mark:

#16547 Migrate to new controller packages
  .circleci/config.yml
  .gitignore
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/controllers/permissions/caveat-mutators.js
  app/scripts/controllers/permissions/caveat-mutators.test.js
  app/scripts/controllers/permissions/specifications.js
  app/scripts/controllers/preferences.test.js
  app/scripts/lib/ComposableObservableStore.js
  app/scripts/lib/ComposableObservableStore.test.js
  app/scripts/lib/rpc-method-middleware/createMethodMiddleware.js
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  app/scripts/migrations/037.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/policy-override.json
  lavamoat/build-system/policy.json
  package.json
  shared/constants/gas.js
  ui/ducks/send/send.js
  ui/helpers/utils/util.js
  ui/hooks/useGasFeeEstimates.js
  ui/hooks/useTokensToSearch.js
  ui/pages/add-collectible/add-collectible.js
  yarn.lock
Labels: type-refactor, Extension QA Board

#16606 [e2e] Setup MV3 specific test folder and add 1 simple testcase introducing Service Worker re-start
  .circleci/config.yml
  test/e2e/mv3/dapp-interactions.spec.js
  test/e2e/run-all.js
Labels: Extension QA Board

#16670 [FLASK] Add Snaps JSON-RPC handler permission
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  shared/constants/permissions.ts
  ui/helpers/utils/permission.js
Labels: flask

#16250 DAPP action replay improvements
  app/scripts/contentscript.js
  package.json
  yarn.lock
Labels: PR - P1

#16681 `HelpText` house keeping 🧹
  ui/components/component-library/help-text/README.mdx
  ui/components/component-library/help-text/__snapshots__/help-text.test.js.snap
  ui/components/component-library/help-text/help-text.js
  ui/components/component-library/help-text/help-text.stories.js
  ui/components/component-library/help-text/help-text.test.js
Labels: area-UI, design-system, IA/NAV

#16680 `Label` house keeping 🧹
  ui/components/component-library/label/README.mdx
  ui/components/component-library/label/__snapshots__/label.test.js.snap
  ui/components/component-library/label/label.js
  ui/components/component-library/label/label.stories.js
  ui/components/component-library/label/label.test.js
Labels: area-UI, design-system, IA/NAV

#16673 [FLASK] `snaps-monorepo@0.25.0`
  app/_locales/en/messages.json
  app/scripts/controllers/permissions/specifications.test.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/policy-override.json
  package.json
  shared/constants/permissions.ts
  test/e2e/snaps/enums.js
  ui/helpers/utils/permission.js
  yarn.lock
Labels: flask

#16628 [FLASK] Create E2E test for snap management
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/webdriver/driver.js
  ui/components/app/flask/snap-remove-warning/snap-remove-warning.js
Labels: flask
