Repository MetaMask/metamask-extension, pull requests merged in 2022-05, with the labels that each got.

#14568 E2e send tests
  test/e2e/tests/edit-gas-fee.spec.js
  test/e2e/tests/send-edit.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/webdriver/driver.js
Labels: area-testSuite, Team 🌳, QA Board

#14565 LavaMoat - UI upgrade - secure package naming
  development/build/scripts.js
  lavamoat/browserify/beta/policy-override.json
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy-override.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy-override.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/policy-override.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: QA Board

#14625 Fix SRP paste duplication
  test/e2e/helpers.js
  test/e2e/tests/from-import-ui.spec.js
  ui/components/app/srp-input/srp-input.js
Labels: QA Board

#14674 Updating alert text color
  ui/components/app/confirm-page-container/confirm-detail-row/index.scss
  ui/components/app/ledger-instruction-field/ledger-instruction-field.js
Labels: area-UI

#14685 Fix auto lock e2e test
  test/e2e/tests/auto-lock.spec.js
Labels: QA Board

#14617 Chromedriver v101
  .circleci/scripts/chrome-install.sh
  package.json
  yarn.lock
Labels: area-testSuite, Team 🌳, QA Board

#14441 Event tracking for Token Detection V2
  app/scripts/controllers/detect-tokens.js
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/metamask-controller.js
  shared/constants/metametrics.js
  ui/components/app/asset-list/detetcted-tokens-link/detected-tokens-link.js
  ui/components/app/asset-list/detetcted-tokens-link/detected-tokens-link.stories.js
  ui/components/app/asset-list/detetcted-tokens-link/detected-tokens-link.test.js
  ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js
  ui/components/app/detected-token/detected-token.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/token-overview.js
  ui/pages/add-collectible/add-collectible.js
  ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.js
  ui/pages/confirm-import-token/confirm-import-token.js
Labels: area-tokens, area-metrics

#14707 Storybook: add SignatureRequestOriginal
  ui/components/app/signature-request-original/README.mdx
  ui/components/app/signature-request-original/signature-request-original.stories.js
Labels: type-story

#14688 Fix an edge case with missing top assets in Swaps
  ui/pages/confirmation/templates/add-ethereum-chain.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/swaps/index.js
  ui/pages/swaps/swaps.util.js
Labels: area-Sentry, stedmap team

#14769 Enables the "Safe Transaction From" copy for safeTransferFrom transactions
  ui/hooks/useTransactionDisplayData.js
  ui/hooks/useTransactionDisplayData.test.js
Labels: type-i18n, area-Sentry, area-transactions, stedmap team
