Repository MetaMask/metamask-extension, pull requests merged in 2022-07, with the labels that each got.

#14777 Remove global transaction state from send flow
  shared/constants/tokens.js
  test/jest/mocks.js
  ui/components/app/asset-list-item/asset-list-item.js
  ui/components/app/collectible-details/collectible-details.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/token-overview.js
  ui/components/ui/token-input/token-input.component.js
  ui/ducks/send/helpers.js
  ui/ducks/send/helpers.test.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/pages/confirm-send-ether/confirm-send-ether.container.js
  ui/pages/confirm-send-token/confirm-send-token.component.js
  ui/pages/confirm-send-token/confirm-send-token.container.js
  ui/pages/confirm-send-token/confirm-send-token.js
  ui/pages/send/send-content/send-amount-row/amount-max-button/amount-max-button.test.js
  ui/pages/send/send-header/send-header.component.test.js
  ui/pages/send/send.js
  ui/pages/send/send.test.js
  ui/selectors/custom-gas.js
  ui/selectors/custom-gas.test.js
  ui/store/actions.js
Labels: Extension QA Board, stedmap team

#15139 Disable Seedphrase import button after switching seedphrase length
  ui/components/app/srp-input/srp-input.js
Labels: area-seedPhrase

#15010 Add setApprovalForAll confirmation view
  app/_locales/en/messages.json
  shared/constants/transaction.js
  shared/modules/transaction.utils.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-summary/confirm-page-container-summary.component.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
  ui/helpers/constants/routes.js
  ui/helpers/constants/transactions.js
  ui/helpers/utils/token-util.js
  ui/helpers/utils/transactions.util.js
  ui/hooks/useTransactionDisplayData.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-approve/confirm-approve.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-switch/confirm-transaction-switch.component.js
  ui/pages/confirm-transaction/confirm-token-transaction-switch.js
Labels: PR - P1

#13588 Show users a warning when they are sending directly to a token contract
  app/_locales/en/messages.json
  test/e2e/tests/send-hex-address.spec.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/helpers/constants/common.js
  ui/helpers/utils/token-util.js
  ui/pages/send/send-content/add-recipient/add-recipient.component.js
  ui/pages/send/send-content/send-content.component.js
  ui/pages/send/send-content/send-content.component.test.js
  ui/pages/send/send-content/send-content.container.js
  ui/pages/send/send.js
  ui/pages/send/send.scss
  ui/pages/send/send.test.js
Labels: type-bug, Sev1-high

#15133 Adding tasks for MV3 test build
  .circleci/config.yml
  development/build/scripts.js
  package.json
Labels: PR - P1

#15259 enable direct routing to the send page
  ui/ducks/send/send.js
  ui/pages/send/send-header/send-header.component.js
  ui/pages/send/send.js
  ui/pages/send/send.test.js
Labels: Extension QA Board

#15245 Fix invalid build timestamp on certain timezones
  development/build/etc.js
Labels: Extension QA Board

#15186 Disable Seedphrase import button if any of the characters is in uppercase
  app/_locales/en/messages.json
  ui/components/app/srp-input/srp-input.js
Labels: area-seedPhrase, area-Sentry

#15156 added storybook files to alert and breadcrumbs component
  ui/components/ui/alert/README.mdx
  ui/components/ui/alert/alert.stories.js
  ui/components/ui/alert/index.js
  ui/components/ui/alert/index.test.js
  ui/components/ui/breadcrumbs/README.mdx
  ui/components/ui/breadcrumbs/breadcrumbs.stories.js
  ui/components/ui/confusable/README.mdx
  ui/components/ui/confusable/confusable.stories.js
  ui/components/ui/dialog/README.mdx
  ui/components/ui/dialog/dialog.stories.js
  ui/components/ui/export-text-container/README.mdx
  ui/components/ui/export-text-container/export-text.stories.js
  ui/components/ui/hex-to-decimal/README.mdx
  ui/components/ui/hex-to-decimal/hex-to-decimal.stories.js
Labels: area-UI, type-story

#15157 Capturing load time stats
  app/scripts/app-init.js
  development/build/scripts.js
  package.json
  test/e2e/mv3/stats.js
Labels: MV3, PR - P1

#15106 Add responsive props to Box component
  ui/components/app/add-network/add-network.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js
  ui/components/app/cancel-speedup-popover/cancel-speedup-popover.js
  ui/components/app/collectibles-items/collectibles-items.js
  ui/components/app/confirm-page-container/enableEIP1559V2-notice/enableEIP1559V2-notice.js
  ui/components/app/detected-token/detected-token-address/detected-token-address.js
  ui/components/app/detected-token/detected-token-ignored-popover/detected-token-ignored-popover.js
  ui/components/app/edit-gas-fee-popover/network-statistics/network-statistics.js
  ui/components/app/recovery-phrase-reminder/recovery-phrase-reminder.js
  ui/components/app/transaction-detail-item/transaction-detail-item.component.js
  ui/components/ui/box/README.mdx
  ui/components/ui/box/box.js
  ui/components/ui/box/box.scss
  ui/components/ui/box/box.stories.js
  ui/components/ui/box/box.test.js
  ui/components/ui/box/index.js
  ui/components/ui/callout/callout.stories.js
  ui/components/ui/textarea/textarea.js
  ui/components/ui/typography/typography.js
  ui/css/design-system/attributes.scss
  ui/css/design-system/breakpoints.scss
  ui/helpers/constants/design-system.js
  ui/pages/confirm-transaction-base/transaction-alerts/transaction-alerts.js
  ui/pages/confirmation/confirmation.js
  ui/pages/home/home.component.js
  ui/pages/keychains/restore-vault.js
  ui/pages/settings/settings-tab/settings-tab.component.js
  ui/pages/swaps/import-token/import-token.js
  ui/pages/token-details/token-details-page.js
Labels: DO-NOT-MERGE

#15191 MV3 bundle size stats
  development/metamaskbot-build-announce.js
  test/e2e/mv3-perf-stats/bundle-size.js
  test/e2e/mv3-perf-stats/index.js
  test/e2e/mv3-perf-stats/init-load-stats.js
Labels: PR - P1

#15209 Bundlesize stats over time
  .circleci/config.yml
  .circleci/scripts/bundle-stats-commit.sh
  test/e2e/mv3-perf-stats/bundle-size.js
Labels: PR - P1

#15264 Updating design tokens package and shadow values with new tokens
  .storybook/test-data.js
  package.json
  ui/components/app/account-menu/index.scss
  ui/components/app/dropdowns/dropdown.js
  ui/components/app/gas-customization/gas-price-button-group/gas-price-button-group.stories.js
  ui/components/app/gas-customization/gas-price-button-group/index.scss
  ui/components/app/gas-customization/gas-slider/gas-slider.stories.js
  ui/components/app/gas-customization/gas-slider/index.scss
  ui/components/app/home-notification/index.scss
  ui/components/app/modals/hide-token-confirmation-modal/hide-token-confirmation.stories.js
  ui/components/app/modals/hide-token-confirmation-modal/index.scss
  ui/components/app/modals/modal.js
  ui/components/app/modals/new-account-modal/index.scss
  ui/components/app/modals/new-account-modal/new-account-modal.stories.js
  ui/components/app/signature-request-original/index.scss
  ui/components/app/signature-request/index.scss
  ui/components/ui/button-group/index.scss
  ui/components/ui/button/buttons.scss
  ui/components/ui/callout/callout.scss
  ui/components/ui/menu/menu.scss
  ui/components/ui/page-container/index.scss
  ui/components/ui/page-container/page-container.stories.js
  ui/components/ui/popover/index.scss
  ui/components/ui/sender-to-recipient/index.scss
  ui/components/ui/slider/slider.component.js
  ui/components/ui/tooltip/index.scss
  ui/components/ui/url-icon/index.scss
  ui/css/itcss/components/newui-sections.scss
  ui/css/itcss/components/send.scss
  ui/pages/asset/asset.scss
  ui/pages/confirm-decrypt-message/confirm-decrypt-message.scss
  ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.scss
  ui/pages/confirmation/components/confirmation-network-switch/index.scss
  ui/pages/create-account/index.scss
  ui/pages/first-time-flow/seed-phrase/confirm-seed-phrase/index.scss
  ui/pages/home/index.scss
  ui/pages/import-token/token-list/index.scss
  ui/pages/onboarding-flow/recovery-phrase/index.scss
  ui/pages/permissions-connect/redirect/index.scss
  ui/pages/settings/index.scss
  ui/pages/swaps/build-quote/index.scss
  ui/pages/swaps/dropdown-search-list/index.scss
  ui/pages/swaps/index.scss
  ui/pages/swaps/select-quote-popover/index.scss
  yarn.lock
Labels: area-UI, design-system

#15175 Modify transaction type and add contract method data to metrics
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  shared/constants/transaction.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: PR - P1

#15338 Fix for script to measure bundle size over time
  .circleci/scripts/bundle-stats-commit.sh
  test/e2e/mv3-perf-stats/bundle-size.js
Labels: MV3

#15273 added tx details popup to cancelled Swap
  ui/components/app/transaction-list-item/smart-transaction-list-item.component.js
  ui/components/app/transaction-list/transaction-list.component.js
Labels: PR - P1

#15261 Bumps eth-lattice-keyring to v0.10.0
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: PR - P1

#15302 Adjusting the height of account menu nav items to expand scroll area
  ui/components/app/account-menu/index.scss
Labels: area-UI

#15197 Added speed up metrics data for transaction events and properly track speed up type
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  shared/constants/transaction.js
Labels: PR - P1

#15381 Adding readme for component-library folder
  ui/components/component-library/COMPONENT-LIBARY.stories.mdx
  ui/components/component-library/README.md
Labels: area-documentation, design-system, IA/NAV

#14782 Bundle optimazation 0
  ui/helpers/utils/optimism/fetchEstimatedL1Fee.js
  ui/helpers/utils/util.js
Labels: MV3, PR - P1
