Repository MetaMask/metamask-extension, pull requests merged in 2022-03, with the labels that each got.

#13831 Updating all Box background and border color instances
  ui/components/app/flask/snap-settings-card/snap-settings-card.js
  ui/components/app/flask/snaps-authorship-pill/index.scss
  ui/components/app/flask/snaps-authorship-pill/snaps-authorship-pill.js
  ui/components/ui/box/box.js
  ui/components/ui/box/box.stories.js
  ui/components/ui/box/index.js
  ui/components/ui/callout/callout.js
  ui/components/ui/callout/callout.scss
  ui/components/ui/callout/callout.stories.js
  ui/components/ui/card/README.mdx
  ui/components/ui/card/card.js
  ui/components/ui/chip/chip-with-input.js
  ui/components/ui/chip/chip.js
  ui/components/ui/chip/chip.scss
  ui/components/ui/chip/chip.stories.js
  ui/components/ui/icon/index.scss
  ui/components/ui/textarea/index.scss
  ui/components/ui/textarea/textarea.js
  ui/components/ui/truncated-definition-list/truncated-definition-list.js
  ui/components/ui/typography/typography.js
  ui/pages/first-time-flow/seed-phrase/seed-phrase-intro/seed-phrase-intro.component.js
  ui/pages/onboarding-flow/recovery-phrase/recovery-phrase-chips.js
Labels: area-UI, type-story

#13833 Fix v10.11: Unable to find value of key "eth_accounts" for locale "en" in Permissions Modal
  ui/components/app/connected-accounts-permissions/connected-accounts-permissions.component.js
  ui/components/app/connected-accounts-permissions/connected-accounts-permissions.js
  ui/components/app/connected-accounts-permissions/index.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
  ui/hooks/usePermissionDescriptions.js
Labels: type-bug, type-i18n, Team 🌳

#13834 [GridPlus] Updates Lattice dependencies
  app/manifest/_base.json
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: area-hardware, hardware-lattice1

#13838 Showing new message while converting token to NFT
  app/_locales/en/messages.json
  ui/components/app/modals/convert-token-to-nft-modal/convert-token-to-nft-modal.js
  ui/pages/add-collectible/add-collectible.js
Labels: area-NFTs

#13854 update chromedriver
  .circleci/scripts/chrome-install.sh
  package.json
  yarn.lock
Labels: Team 🌳

#13841 E2e improve mocking
  development/mock-e2e.js
  test/e2e/helpers.js
  test/e2e/tests/phishing-detection.spec.js
Labels: Team 🌳

#13758 Typography design token color and docs update
  ui/components/ui/typography/README.mdx
  ui/components/ui/typography/typography.js
  ui/components/ui/typography/typography.stories.js
  ui/helpers/constants/design-system.js
Labels: area-documentation, area-UI, design-system

#13864 Updating AccountList to use darkmode colors
  ui/components/ui/account-list/account-list.js
  ui/components/ui/account-list/account-list.stories.js
  ui/components/ui/account-list/index.scss
Labels: area-UI, type-story

#13861 Updating all caret icons for dark mode 🥕
  app/images/caret-left-black.svg
  app/images/caret-left.svg
  app/images/caret-right.svg
  app/images/icons/caret-down.svg
  app/images/icons/collapse.svg
  ui/components/app/add-network/add-network.js
  ui/components/app/add-network/index.scss
  ui/components/app/app-header/app-header.component.js
  ui/components/app/app-header/index.scss
  ui/components/app/confirm-page-container/confirm-page-container-header/confirm-page-container-header.component.js
  ui/components/app/confirm-page-container/confirm-page-container-header/confirm-page-container-header.stories.js
  ui/components/app/confirm-page-container/confirm-page-container-header/index.scss
  ui/components/app/network-display/index.scss
  ui/components/app/network-display/network-display.js
  ui/components/app/network-display/network-display.stories.js
  ui/components/app/tab-bar/index.scss
  ui/components/app/tab-bar/tab-bar.js
  ui/components/app/tab-bar/tab-bar.stories.js
  ui/components/ui/button/buttons.scss
  ui/components/ui/disclosure/disclosure.scss
  ui/components/ui/disclosure/disclosure.stories.js
  ui/components/ui/dropdown/dropdown.js
  ui/components/ui/dropdown/dropdown.scss
  ui/components/ui/icon/icon-caret-down.js
  ui/components/ui/icon/icon-caret-left.js
  ui/components/ui/icon/icon-caret-right.js
  ui/components/ui/icon/icon-caret-up.js
  ui/components/ui/icon/icon.stories.js
  ui/components/ui/icon/index.scss
  ui/components/ui/sender-to-recipient/index.scss
  ui/components/ui/sender-to-recipient/sender-to-recipient.component.js
  ui/components/ui/sender-to-recipient/sender-to-recipient.stories.js
  ui/pages/send/send-content/add-recipient/add-recipient.component.js
  ui/pages/send/send-content/add-recipient/add-recipient.stories.js
  ui/pages/send/send.scss
  ui/pages/settings/contact-list-tab/index.scss
  ui/pages/settings/index.scss
  ui/pages/settings/networks-tab/index.scss
  ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js
  ui/pages/settings/networks-tab/networks-list-item/networks-list-item.stories.js
  ui/pages/settings/settings-search-list/settings-search-list.js
Labels: area-UI, type-story

#13818 Add e2e testcase for token details functionality
  test/e2e/tests/token-details.spec.js
  test/e2e/webdriver/driver.js
Labels: Team 🌳, QA Board

#13878 Fix build - context deadline exceeded
  test/e2e/tests/phishing-detection.spec.js
Labels: Team 🌳

#13899 Updating ActionableMessage to be dark mode compatible
  ui/components/ui/actionable-message/actionable-message.js
  ui/components/ui/actionable-message/actionable-message.stories.js
  ui/components/ui/actionable-message/index.scss
  ui/pages/home/home.component.js
Labels: area-UI, type-story

#13947 Updating account and network icons
  app/images/check-white.svg
  app/images/connect-icon.svg
  app/images/import-account.svg
  app/images/plus-btn-white.svg
  app/images/settings.svg
  app/images/support.svg
  ui/components/app/account-menu/account-menu.component.js
  ui/components/app/account-menu/index.scss
  ui/components/app/dropdowns/network-dropdown.js
  ui/components/ui/icon/README.mdx
  ui/components/ui/icon/icon-check.js
  ui/components/ui/icon/icon-cog.js
  ui/components/ui/icon/icon-connect.js
  ui/components/ui/icon/icon-import.js
  ui/components/ui/icon/icon-plus.js
  ui/components/ui/icon/icon-speech-bubbles.js
  ui/components/ui/icon/icon.stories.js
  ui/css/itcss/components/network.scss
Labels: area-UI, type-story

#13888 Make Edit Gas Fee testcase independent of arbitrary Wait time for Gas Editing
  test/e2e/tests/edit-gas-fee.spec.js
Labels: Team 🌳, QA Board

#13975 Changes in build for new service worker added
  app/manifest/_base.json
  app/manifest/firefox.json
  app/scripts/app-init.js
  development/build/scripts.js
Labels: MV3

#13535 Fix issue where we show contract address as recipient when calling safe transfer method on erc721 or erc1155 contracts
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  package.json
  shared/constants/transaction.js
  shared/modules/transaction.utils.js
  shared/modules/transaction.utils.test.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-summary/confirm-page-container-summary.component.js
  ui/ducks/confirm-transaction/confirm-transaction.duck.js
  ui/helpers/constants/routes.js
  ui/helpers/utils/token-util.js
  ui/helpers/utils/transactions.util.js
  ui/helpers/utils/transactions.util.test.js
  ui/hooks/useAssetDetails.js
  ui/hooks/useTokenData.js
  ui/hooks/useTokenDisplayValue.test.js
  ui/pages/confirm-approve/confirm-approve.util.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirm-transaction-switch/confirm-transaction-switch.component.js
  ui/pages/confirm-transaction/confirm-token-transaction-switch.js
  ui/pages/swaps/view-quote/view-quote.js
  yarn.lock
Labels: area-NFTs

#14044 Set Chrome logger to level 3: Log_Fatal
  test/e2e/webdriver/chrome.js
Labels: Team 🌳, QA Board

#14045 Fix flaky test: add account
  test/e2e/tests/add-account.spec.js
Labels: Team 🌳, QA Board

#14063 Dark Mode: updating COLORS.BLACK to COLORS.TEXT_DEFAULT
  ui/components/app/gas-details-item/gas-details-item-title/index.scss
  ui/components/app/gas-details-item/gas-details-item.js
  ui/components/ui/box/README.mdx
  ui/components/ui/definition-list/definition-list.stories.js
  ui/components/ui/typography/README.mdx
  ui/components/ui/typography/typography.js
  ui/helpers/constants/design-system.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmation/confirmation.js
Labels: area-UI

#13495 Add TypeScript to the linting process
  .depcheckrc.yml
  .eslintrc.js
  .eslintrc.typescript-compat.js
  .gitignore
  development/build/index.js
  jsconfig.json
  lavamoat/build-system/policy-override.json
  lavamoat/build-system/policy.json
  package.json
  patches/@keystonehq+bc-ur-registry+0.4.4.patch
  patches/await-semaphore+0.1.3.patch
  patches/eslint-import-resolver-typescript+2.5.0.patch
  patches/typescript+4.4.4.patch
  tsconfig.json
  yarn.lock
Labels: Team 🌳

#14093 ImportToken does not clear up the page when going back
  ui/pages/confirm-import-token/confirm-import-token.js
Labels: area-tokens

#13977 Move Token Detection toggle to Advanced tab.
  .metamaskrc.dist
  app/_locales/en/messages.json
  development/build/scripts.js
  ui/helpers/utils/settings-search.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.component.test.js
  ui/pages/settings/experimental-tab/experimental-tab.container.js
Labels: area-tokens, QA Board

#13953 Dark mode: Adding wyre, transak and deposit eth logo
  app/images/deposit-eth.svg
  app/images/transak.svg
  app/images/wyre.svg
  ui/components/app/modals/deposit-ether-modal/deposit-ether-modal.component.js
  ui/components/app/modals/deposit-ether-modal/index.scss
  ui/components/ui/logo/README.mdx
  ui/components/ui/logo/logo-deposit-eth.js
  ui/components/ui/logo/logo-transak.js
  ui/components/ui/logo/logo-wyre.js
  ui/components/ui/logo/logo.stories.js
Labels: area-UI, type-story

#14205 Update pasteIntoField method
  test/e2e/webdriver/driver.js
Labels: Team 🌳, QA Board

#14184 Dark Mode: Remove ui colors
  ui/components/app/cancel-speedup-popover/index.scss
  ui/components/app/collectible-details/index.scss
  ui/components/app/flask/experimental-area/index.scss
  ui/components/app/transaction-detail-item/index.scss
  ui/components/ui/definition-list/definition-list.scss
  ui/css/design-system/colors.scss
  ui/css/utilities/colors.scss
  ui/pages/permissions-connect/flask/snap-install/index.scss
  ui/pages/settings/flask/view-snap/index.scss
  ui/pages/swaps/loading-swaps-quotes/loading-swap-quotes.stories.js
  ui/pages/swaps/smart-transaction-status/index.scss
Labels: theming

#14189 Dark Mode : Swap hex colors in ui/components/app folder
  ui/components/app/add-network/add-network.js
  ui/components/app/app-loading-spinner/app-loading-spinner.js
  ui/components/app/collectible-details/collectible-details.js
  ui/components/app/edit-gas-display/edit-gas-display.component.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.js
  ui/components/app/modals/qr-scanner/qr-scanner.component.js
  ui/components/app/qr-hardware-popover/enhanced-reader.js
  ui/components/app/selected-account/selected-account.component.js
  ui/components/app/srp-input/srp-input.js
  ui/components/app/token-cell/token-cell.js
  ui/components/app/transaction-decoding/components/ui/copy-raw-data/copy-raw-data.component.js
  ui/components/app/transaction-decoding/transaction-decoding.component.js
  ui/components/app/transaction-icon/transaction-icon.js
Labels: theming

#13646 update gas fees
  app/scripts/controllers/transactions/index.js
  app/scripts/metamask-controller.js
  test/e2e/metamask-ui.spec.js
  test/e2e/tests/edit-gas-fee.spec.js
  test/e2e/tests/send-edit.spec.js
  test/e2e/tests/send-eth.spec.js
  ui/components/app/cancel-speedup-popover/cancel-speedup-popover.test.js
  ui/components/app/edit-gas-popover/edit-gas-popover.component.js
  ui/components/app/gas-customization/gas-modal-page-container/gas-modal-page-container.container.js
  ui/ducks/metamask/metamask.js
  ui/hooks/gasFeeInput/useTransactionFunction.test.js
  ui/hooks/gasFeeInput/useTransactionFunctions.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/store/actions.js
Labels: QA Board

#14210 Dark mode: user preferenced currency eth logo
  app/images/eth.svg
  ui/components/app/confirm-page-container/confirm-detail-row/confirm-detail-row.component.js
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.stories.js
  ui/components/ui/currency-display/currency-display.component.js
  ui/components/ui/currency-display/index.scss
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: theming

#14213 Dark mode: token search icon
  app/images/tokensearch.svg
  ui/components/ui/icon/icon-token-search.js
  ui/components/ui/icon/icon.stories.js
  ui/pages/import-token/token-list/token-list-placeholder/token-list-placeholder.component.js
Labels: theming

#14104 Token address component for Tokens Detected page
  app/_locales/en/messages.json
  ui/components/app/app-components.scss
  ui/components/app/detected-token/detected-token-address/detected-token-address.js
  ui/components/app/detected-token/detected-token-address/detected-token-address.stories.js
  ui/components/app/detected-token/detected-token-address/detected-token-address.test.js
  ui/components/app/detected-token/detected-token-address/index.scss
Labels: area-tokens, QA Board

#14208 Dark Mode: Remove last unused colors
  ui/components/app/modals/account-details-modal/index.scss
  ui/css/design-system/colors.scss
  ui/css/itcss/components/send.scss
  ui/css/utilities/colors.scss
  ui/pages/create-account/index.scss
  ui/pages/settings/flask/view-snap/index.scss
  ui/pages/settings/info-tab/index.scss
Labels: theming

#14211 Dark mode: confirm approve content popout and user approve check icon
  app/images/popout.svg
  app/images/user-check.svg
  ui/components/app/modals/confirm-remove-account/confirm-remove-account.component.js
  ui/components/app/modals/confirm-remove-account/confirm-remove-account.stories.js
  ui/components/app/modals/confirm-remove-account/index.scss
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.stories.js
  ui/pages/create-account/connect-hardware/account-list.js
  ui/pages/create-account/connect-hardware/account-list.stories.js
Labels: theming

#14200 Dark mode: updating permissions redirect check icon
  app/images/permissions-check.svg
  ui/pages/permissions-connect/redirect/index.scss
  ui/pages/permissions-connect/redirect/permissions-redirect.component.js
  ui/pages/permissions-connect/redirect/permissions-redirect.stories.js
Labels: theming

#14214 Dark Mode: Swap hex colors in ui/pages
  ui/pages/add-collectible/add-collectible.js
  ui/pages/confirm-decrypt-message/confirm-decrypt-message.component.js
  ui/pages/confirm-transaction-base/transaction-alerts/transaction-alerts.js
  ui/pages/import-token/import-token.component.js
  ui/pages/onboarding-flow/recovery-phrase/review-recovery-phrase.js
  ui/pages/settings/contact-list-tab/view-contact/view-contact.component.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js
  ui/pages/settings/networks-tab/networks-tab.js
  ui/pages/swaps/awaiting-signatures/__snapshots__/swap-step-icon.test.js.snap
  ui/pages/swaps/awaiting-signatures/swap-step-icon.js
  ui/pages/swaps/awaiting-swap/__snapshots__/quotes-timeout-icon.test.js.snap
  ui/pages/swaps/awaiting-swap/__snapshots__/swap-failure-icon.test.js.snap
  ui/pages/swaps/awaiting-swap/__snapshots__/swap-success-icon.test.js.snap
  ui/pages/swaps/awaiting-swap/quotes-timeout-icon.js
  ui/pages/swaps/awaiting-swap/swap-failure-icon.js
  ui/pages/swaps/awaiting-swap/swap-success-icon.js
  ui/pages/swaps/countdown-timer/__snapshots__/timer-icon.test.js.snap
  ui/pages/swaps/countdown-timer/timer-icon.js
  ui/pages/swaps/exchange-rate-display/exchange-rate-display.stories.js
  ui/pages/swaps/fee-card/pig-icon.js
  ui/pages/swaps/main-quote-summary/__snapshots__/main-quote-summary.test.js.snap
  ui/pages/swaps/main-quote-summary/main-quote-summary.js
  ui/pages/swaps/select-quote-popover/sort-list/__snapshots__/sort-list.test.js.snap
  ui/pages/swaps/select-quote-popover/sort-list/sort-list.js
  ui/pages/swaps/smart-transaction-status/__snapshots__/canceled-icon.test.js.snap
  ui/pages/swaps/smart-transaction-status/__snapshots__/timer-icon.test.js.snap
  ui/pages/swaps/smart-transaction-status/__snapshots__/unknown-icon.test.js.snap
  ui/pages/swaps/smart-transaction-status/canceled-icon.js
  ui/pages/swaps/smart-transaction-status/timer-icon.js
  ui/pages/swaps/smart-transaction-status/unknown-icon.js
  ui/pages/swaps/view-quote/__snapshots__/view-quote.test.js.snap
  ui/pages/token-details/token-details-page.js
  ui/pages/unlock-page/unlock-page.component.js
Labels: theming

#14207 Dark Mode: Remove feature flag
  development/build/scripts.js
  ui/pages/routes/routes.component.js
  ui/pages/settings/experimental-tab/experimental-tab.component.js
Labels: theming

#14209 Dark mode icon onboarding twitter
  app/images/icons/red-triangle-exclaim.svg
  app/images/icons/yellow-bell.svg
  app/images/twitter-icon.png
  app/images/warning-icon.png
  ui/pages/onboarding-flow/create-password/index.scss
  ui/pages/onboarding-flow/import-srp/import-srp.js
  ui/pages/onboarding-flow/import-srp/index.scss
  ui/pages/onboarding-flow/index.scss
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/onboarding-flow/secure-your-wallet/index.scss
  ui/pages/onboarding-flow/secure-your-wallet/skip-srp-backup-popover.js
Labels: theming

#13489 Add TypeScript to the build system
  babel.config.js
  development/build/index.js
  development/build/scripts.js
  lavamoat/build-system/policy-override.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: Team 🌳

#14149 E2e dapp interactions
  test/e2e/helpers.js
  test/e2e/tests/dapp-interactions.spec.js
Labels: Team 🌳, QA Board

#14124 Update What's new screen with Token Detection information
  app/_locales/en/messages.json
  app/images/token-detection.svg
  shared/notifications/index.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: area-tokens, QA Board

#14157 Token Aggregators component for Tokens Detected page
  app/_locales/en/messages.json
  ui/components/app/app-components.scss
  ui/components/app/detected-token/detected-token-aggregators/detected-token-aggregators.js
  ui/components/app/detected-token/detected-token-aggregators/detected-token-aggregators.stories.js
  ui/components/app/detected-token/detected-token-aggregators/detected-token-aggregators.test.js
  ui/components/app/detected-token/detected-token-aggregators/index.scss
Labels: area-tokens

#14002 Enable Token Detection by default on supported networks
  app/scripts/controllers/preferences.js
Labels: area-tokens

#14034 Enable Token search functionality on supported networks
  app/_locales/en/messages.json
  shared/constants/network.js
  ui/pages/import-token/import-token.component.js
  ui/pages/import-token/import-token.container.js
  ui/pages/import-token/index.scss
  ui/selectors/selectors.js
Labels: area-tokens, QA Board

#13819 Adjusting the padding in Alert / error state
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/collectibles-detection-notice/collectibles-detection-notice.js
  ui/components/app/collectibles-detection-notice/index.scss
  ui/components/app/collectibles-tab/collectibles-tab.js
  ui/pages/add-collectible/add-collectible.js
  ui/pages/home/home.component.js
  ui/pages/home/index.scss
Labels: area-NFTs

#14286 Updating design-tokens to 1.5.1
  package.json
  yarn.lock
Labels: theming

#13627 Mįgrated list item stories from addon knobs to use controls.
  ui/components/ui/list-item/list-item.stories.js
Labels: type-story

#14195 MetaMetrics: add segment.identify
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
Labels: Team 🌳

#14305 Fix/14230 dark mode fixes
  app/images/warning.svg
  ui/components/app/app-header/app-header.component.js
  ui/components/app/app-header/app-header.stories.js
  ui/components/app/app-header/index.scss
  ui/components/ui/page-container/index.scss
  ui/css/base-styles.scss
  ui/pages/keychains/reveal-seed.js
  ui/pages/keychains/reveal-seed.stories.js
Labels: theming, rc :package:
