Repository MetaMask/metamask-extension, pull requests merged in 2022-01, with the labels that each got.

#13028 Storybook: Fixing font paths for storybook CI builds and storybook github page
  .storybook/main.js
  ui/css/design-system/typography.scss
Labels: type-story

#12268 Alert users when the network is busy
  app/_locales/en/messages.json
  shared/constants/gas.js
  ui/components/app/advanced-gas-controls/advanced-gas-controls.component.js
  ui/components/app/edit-gas-display/edit-gas-display.component.js
  ui/components/app/edit-gas-display/edit-gas-display.test.js
  ui/components/app/edit-gas-fee-popover/network-statistics/status-slider/status-slider.js
  ui/components/app/edit-gas-fee-popover/network-statistics/status-slider/status-slider.test.js
  ui/components/app/edit-gas-popover/edit-gas-popover.component.js
  ui/ducks/metamask/metamask.js
  ui/ducks/metamask/metamask.test.js
  ui/hooks/gasFeeInput/useGasFeeInputs.js
  ui/hooks/useGasFeeEstimates.js
  ui/pages/confirm-transaction-base/transaction-alerts/transaction-alerts.js
  ui/pages/confirm-transaction-base/transaction-alerts/transaction-alerts.test.js
  ui/selectors/transactions.js
Labels: EIP-1559-V2

#13055 Updating storybook docs
  .storybook/1.INTRODUCTION.stories.mdx
  .storybook/2.DOCUMENTATION.stories.mdx
  .storybook/main.js
  ui/components/ui/button/README.mdx
  ui/components/ui/button/button.component.js
  ui/components/ui/button/button.stories.js
Labels: area-documentation, type-story

#13196 EIP-1559 V2: : Advanced Gas Fee Modal - Updating the trend arrows
  app/images/down-arrow.svg
  app/images/level-arrow.svg
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-input-subtext/advanced-gas-fee-input-subtext.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-input-subtext/index.scss
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js
Labels: EIP-1559-V2

#13238 EIP-1559 V2: Use default gas preferences of user for all transactions
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/controllers/transactions/index.js
  test/data/mock-state.json
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/basefee-input.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js
  ui/components/app/advanced-gas-fee-popover/context/advancedGasFeePopover.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/useGasItemFeeDetails.js
  ui/selectors/selectors.test.js
Labels: EIP-1559-V2

#13203 convert knobs and actions to controls / args
  ui/pages/send/send-content/send-gas-row/gas-fee-display/gas-fee-display.stories.js
  ui/pages/send/send-content/send-hex-data-row/send-hex-data-row.stories.js
  ui/pages/send/send-footer/send-footer.stories.js
Labels: type-story

#13230 SendHeader, ContactListTab and AdvancedTab story: converted knobs and actions to controls / args
  ui/pages/send/send-header/send-header.stories.js
  ui/pages/settings/advanced-tab/advanced-tab.stories.js
  ui/pages/settings/contact-list-tab/contact-list-tab.stories.js
Labels: type-story

#13189 UpdateNickname story : convert knobs and actions to controls/args
  ui/components/ui/update-nickname-popover/README.mdx
  ui/components/ui/update-nickname-popover/update-nickname-popover.stories.js
Labels: type-story

#13354 Upgrade ganache - continued
  app/scripts/controllers/transactions/index.test.js
  package.json
  test/e2e/tests/incremental-security.spec.js
  test/stub/provider.js
  yarn.lock
Labels: area-testSuite, Team 🌳

#13382 Using new graph images for edit gas fee popover
  app/_locales/en/messages.json
  app/images/curve-high.svg
  app/images/curve-low.svg
  app/images/curve-medium.svg
  ui/components/app/edit-gas-fee-popover/edit-gas-tooltip/edit-gas-tooltip.js
Labels: EIP-1559-V2

#13419 EIP-1559 V2 UI/UX improvements
  app/images/curve-high.svg
  app/images/curve-low.svg
  app/images/curve-medium.svg
  app/scripts/controllers/transactions/index.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/index.scss
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/index.scss
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/advanced-gas-fee-inputs.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/index.scss
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/index.scss
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-popover.js
  ui/components/app/advanced-gas-fee-popover/index.scss
  ui/components/app/app-components.scss
  ui/components/app/app-loading-spinner/index.scss
  ui/components/app/cancel-speedup-popover/cancel-speedup-popover.js
  ui/components/app/edit-gas-fee-button/edit-gas-fee-button.js
  ui/components/app/edit-gas-fee-button/index.scss
  ui/components/app/edit-gas-fee-popover/edit-gas-tooltip/edit-gas-tooltip.js
  ui/components/app/edit-gas-fee-popover/edit-gas-tooltip/index.scss
  ui/components/ui/loading-heartbeat/index.js
  ui/helpers/utils/gas.js
Labels: EIP-1559-V2

#13385 Capturing default gas estimates in txMeta and passing it to metrics
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
Labels: EIP-1559-V2
