Repository MetaMask/metamask-extension, pull requests merged in 2023-08, with the labels that each got.

#20304 UX: Cleanup of NetworkListMenu properties
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: needs-ux-ds-review

#20269 UX: Update Batch Account Setting Description
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/helpers/constants/settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
Labels: needs-ux-ds-review

#20172 Added IPFS toggle
  app/_locales/en/messages.json
  app/images/default_nft.png
  test/e2e/nft/erc721-interaction.spec.js
  test/e2e/nft/import-erc1155.spec.js
  test/e2e/nft/import-nft.spec.js
  test/e2e/nft/remove-erc1155.spec.js
  test/e2e/nft/remove-nft.spec.js
  test/e2e/nft/send-nft.spec.js
  test/e2e/nft/view-erc1155-details.spec.js
  test/e2e/nft/view-nft-details.spec.js
  ui/components/app/nft-default-image/__snapshots__/nft-default-image.test.js.snap
  ui/components/app/nft-default-image/index.scss
  ui/components/app/nft-default-image/nft-default-image.js
  ui/components/app/nft-default-image/nft-default-image.stories.js
  ui/components/app/nft-default-image/nft-default-image.test.js
  ui/components/app/nft-default-image/toggle-ipfs-modal.js
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/nft-details.js
  ui/components/app/nfts-items/nfts-items.js
  ui/components/app/nfts-items/nfts-items.test.js
  ui/components/multichain/nft-item/nft-item.js
  ui/components/multichain/nft-item/nft-item.test.js
  ui/ducks/app/app.ts
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: privacy, team-extension-client, team-extension-UX, needs-ux-ds-review, needs-dev-review

#20311 Fix ipfs-ens-resolution.spec.js E2E intermittent failure
  test/e2e/tests/ipfs-ens-resolution.spec.js
Labels: needs-ux-ds-review

#20353 Fix/check pr labels
  .github/CONTRIBUTING.md
  .github/LABELING_GUIDELINES.md
  .github/scripts/check-pr-has-required-labels.ts
  .github/workflows/check-pr-labels.yml
Labels: team-extension-client, team-extension-platform

#20249 Upgrade to yarn 4
  .circleci/config.yml
  .circleci/scripts/yarn-audit.sh
  .depcheckrc.yml
  .iyarc
  .yarn/patches/improved-yarn-audit-npm-3.0.0-3e37ee431a.patch
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarn/releases/yarn-3.2.4.cjs
  .yarn/releases/yarn-4.0.0-rc.48.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: team-extension-platform

#20345 Fix migration 88 to handle the case where chainId keys can be undefined
  app/scripts/migrations/088.test.ts
  app/scripts/migrations/088.ts
  app/scripts/migrations/091.test.ts
  app/scripts/migrations/091.ts
  app/scripts/migrations/index.js
Labels: team-extension-platform

#19562 Part of #18714 & #19526: Replacing deprecated constants
  ui/components/app/snaps/install-error/install-error.js
  ui/components/app/snaps/install-error/install-error.stories.js
  ui/components/app/snaps/snap-authorship-header/snap-authorship-header.js
  ui/components/app/snaps/snap-authorship-header/snap-authorship-header.stories.js
  ui/components/app/snaps/snap-avatar/snap-avatar.js
Labels: team-design-system

#20258 UX Improvement: Fixed tooltip for token-list-item
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/token-list-item.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20336 Check for blocked snaps on extension startup
  app/scripts/background.js
  app/scripts/metamask-controller.js
Labels: team-snaps

#20071 Whats new blockaid popup
  app/_locales/en/messages.json
  app/images/blockaid-security-provider.png
  shared/notifications/index.js
  test/e2e/fixture-builder.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/components/app/whats-new-popup/whats-new-popup.test.js
  ui/selectors/selectors.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#20358 Updated copy change for the IPFS toggle
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/helpers/constants/settings.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
Labels: privacy, team-extension-client, team-extension-UX, needs-dev-review

#20241 Feat/swaps link buy gas
  app/_locales/en/messages.json
  ui/pages/swaps/prepare-swap-page/review-quote.js
Labels: team-swaps

#20367 bump @metamask/network-controller from v10.3.1 to v11.0.0
  app/scripts/migrations/092.test.ts
  app/scripts/migrations/092.ts
  app/scripts/migrations/index.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-devex

#20350 Update critical error styles
  shared/lib/error-utils.js
  ui/css/errors.scss
  ui/css/itcss/tools/utilities.scss
Labels: area-UI, team-extension-UX, team-confirmations-secure-ux-PR

#20278 Move "Enable Opensea API" and "NFT Autodetect" into Security & Privacy settings
  ui/components/app/nfts-detection-notice/nfts-detection-notice.js
  ui/components/app/nfts-tab/nfts-tab.js
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.container.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/security-tab/security-tab.test.js
  ui/store/actions.ts
Labels: privacy, team-extension-UX, needs-ux-ds-review

#20359 Close Network added popover on background click
  ui/pages/home/home.component.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20360 Added e2e test for ipfs toggle
  test/e2e/tests/ipfs-toggle.spec.js
Labels: privacy, team-extension-client, team-extension-UX

#20125 Confirmation page alerts
  .metamaskrc.dist
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/ppom/ppom.js
  app/scripts/metamask-controller.js
  builds.yml
  shared/constants/security-provider.ts
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.test.js
  ui/components/app/security-provider-banner-alert/__snapshots__/security-provider-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.stories.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request-original/signature-request-original.test.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request-siwe/signature-request-siwe.test.js
  ui/components/app/signature-request/signature-request.js
  ui/components/app/signature-request/signature-request.test.js
  ui/pages/token-allowance/token-allowance.js
  ui/pages/token-allowance/token-allowance.test.js
Labels: team-confirmations-secure-ux

#20361 fix: minimise public api of tx controller
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
Labels: team-confirmations-system

#20371 Fix 'Global Menu Explorer / Account Details' What's New
  shared/notifications/index.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: team-extension-UX, needs-ux-ds-review

#20277 Fix #20274 - Update locked network menu controls
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
Labels: team-extension-UX, needs-ux-ds-review

#20224 Fix #19647 - Allow importing multiple tokens
  test/e2e/tests/import-tokens.spec.js
  ui/components/app/token-list/token-list.js
  ui/pages/confirm-import-token/confirm-import-token.js
  ui/pages/confirm-import-token/confirm-import-token.test.js
  ui/store/actions.ts
Labels: team-extension-UX, needs-ux-ds-review

#20383 Fix import that was resulting in a `depcheck` error
  app/scripts/lib/ppom/ppom-middleware.ts
Labels: team-extension-platform

#20356 UX: Snaps: Make Notifications Font Consistent with Other Global Items
  test/e2e/snaps/test-snap-notification.spec.js
  ui/components/multichain/global-menu/global-menu.js
Labels: team-extension-UX, needs-ux-ds-review

#20219 Adapt to use new `networksMetadata` object which has replaced globally selected `networkStatus` and `networkDetails` on `NetworkController`
  .storybook/test-data.js
  app/scripts/controllers/swaps.js
  app/scripts/controllers/swaps.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  app/scripts/migrations/094.test.ts
  app/scripts/migrations/094.ts
  app/scripts/migrations/index.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/e2e/fixture-builder.js
  test/jest/mock-store.js
  ui/components/app/confirm-gas-display/confirm-gas-display.test.js
  ui/components/app/confirm-page-container/confirm-detail-row/confirm-detail-row.component.test.js
  ui/components/app/confirm-page-container/confirm-page-container-header/confirm-page-container-header.component.test.js
  ui/components/app/modals/account-details-modal/account-details-modal.test.js
  ui/components/app/transaction-alerts/transaction-alerts.stories.js
  ui/ducks/confirm-transaction/confirm-transaction.duck.test.js
  ui/ducks/metamask/metamask.js
  ui/ducks/metamask/metamask.test.js
  ui/ducks/send/send.test.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/switch-ethereum-chain.test.js.snap
  ui/pages/confirmation/templates/add-ethereum-chain.test.js
  ui/pages/confirmation/templates/switch-ethereum-chain.test.js
  ui/pages/send/send-content/send-amount-row/amount-max-button/amount-max-button.test.js
  ui/pages/send/send.test.js
  ui/pages/swaps/prepare-swap-page/review-quote.test.js
  ui/pages/swaps/view-quote/view-quote.test.js
  ui/pages/token-allowance/token-allowance.test.js
  ui/selectors/custom-gas.test.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/store.ts
  yarn.lock
Labels: team-devex

#20366 uses the asertInAnyOrder helper to fix flaky test cases
  test/e2e/metrics/transaction-finalized.spec.js
Labels: team-extension-platform

#20380 Updated copy changes for display NFT Media
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.test.js
Labels: privacy, team-extension-client, team-extension-UX

#20388 Improvements to Swaps quote auto-selection logic, fix and edge case with zero-balance tokens
  test/e2e/swaps/swaps-notifications.spec.js
  ui/ducks/swaps/swaps.js
  ui/pages/swaps/build-quote/build-quote.js
  ui/pages/swaps/build-quote/build-quote.test.js
  ui/pages/swaps/index.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.test.js
Labels: team-swaps

#19859 Part #19737 - Replace deprecated FormField component with TextField, Label, HelpText
  test/e2e/tests/custom-token-add-approve.spec.js
  ui/components/app/app-components.scss
  ui/components/app/custom-spending-cap/__snapshots__/custom-spending-cap.test.js.snap
  ui/components/app/custom-spending-cap/custom-spending-cap-tooltip.js
  ui/components/app/custom-spending-cap/custom-spending-cap.js
  ui/components/app/custom-spending-cap/custom-spending-cap.stories.js
  ui/components/app/custom-spending-cap/index.scss
  ui/pages/token-allowance/__snapshots__/token-allowance.test.js.snap
Labels: team-design-system

#19718 Replacing deprecated constants and components
  ui/components/ui/deprecated-test-networks/deprecated-test-networks.js
  ui/components/ui/deprecated-test-networks/deprecated-test-networks.stories.js
  ui/components/ui/deprecated-test-networks/index.scss
  ui/components/ui/nft-info/index.scss
  ui/components/ui/nft-info/nft-info.js
  ui/components/ui/ui-components.scss
Labels: team-design-system

#20374 feat(878): add new incomingTxn component and change styles of settings
  app/_locales/en/messages.json
  ui/components/app/incoming-trasaction-toggle/__snapshots__/incoming-transaction-toggle.test.js.snap
  ui/components/app/incoming-trasaction-toggle/incoming-transaction-toggle.test.js
  ui/components/app/incoming-trasaction-toggle/incoming-transaction-toggle.tsx
  ui/components/app/incoming-trasaction-toggle/network-toggle.tsx
  ui/pages/onboarding-flow/privacy-settings/setting.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/pages/settings/alerts-tab/alerts-tab.scss
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/index.scss
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/settings-tab/settings-tab.component.js
Labels: privacy, team-extension-client, team-extension-platform

#20309 Fix #20305 - Show the network name in Delete Network modal
  app/_locales/am/messages.json
  app/_locales/ar/messages.json
  app/_locales/bg/messages.json
  app/_locales/bn/messages.json
  app/_locales/ca/messages.json
  app/_locales/da/messages.json
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/et/messages.json
  app/_locales/fa/messages.json
  app/_locales/fi/messages.json
  app/_locales/fil/messages.json
  app/_locales/fr/messages.json
  app/_locales/he/messages.json
  app/_locales/hi/messages.json
  app/_locales/hr/messages.json
  app/_locales/hu/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/kn/messages.json
  app/_locales/ko/messages.json
  app/_locales/lt/messages.json
  app/_locales/lv/messages.json
  app/_locales/ms/messages.json
  app/_locales/no/messages.json
  app/_locales/ph/messages.json
  app/_locales/pl/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ro/messages.json
  app/_locales/ru/messages.json
  app/_locales/sk/messages.json
  app/_locales/sl/messages.json
  app/_locales/sr/messages.json
  app/_locales/sv/messages.json
  app/_locales/sw/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/uk/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  ui/components/app/modals/confirm-delete-network/__snapshots__/confirm-delete-network.test.js.snap
  ui/components/app/modals/confirm-delete-network/confirm-delete-network.component.js
  ui/components/app/modals/confirm-delete-network/confirm-delete-network.container.js
  ui/components/app/modals/confirm-delete-network/confirm-delete-network.test.js
Labels: team-extension-UX, needs-ux-ds-review

#20365 Fix-Migrate Picker-Network to TS
  ui/components/component-library/picker-network/README.mdx
  ui/components/component-library/picker-network/__snapshots__/picker-network.test.tsx.snap
  ui/components/component-library/picker-network/index.js
  ui/components/component-library/picker-network/index.ts
  ui/components/component-library/picker-network/picker-network.js
  ui/components/component-library/picker-network/picker-network.stories.tsx
  ui/components/component-library/picker-network/picker-network.test.tsx
  ui/components/component-library/picker-network/picker-network.tsx
  ui/components/component-library/picker-network/picker-network.types.ts
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
Labels: team-design-system

#20098 Add Opt-out Settings toggle for 4byte contract method names resolution
  app/_locales/en/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/metamask-controller.js
  test/data/mock-state.json
  test/e2e/tests/4byte-directory.spec.js
  ui/ducks/metamask/metamask.js
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/helpers/utils/transactions.util.js
  ui/helpers/utils/transactions.util.test.js
  ui/pages/confirm-transaction/confirm-transaction.component.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/security-tab/security-tab.test.js
  ui/selectors/confirm-transaction.js
  ui/selectors/selectors.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: privacy, team-extension-client, team-extension-UX, needs-ux-ds-review

#20334 UX Multichain: Fixed fiat and eth value in Account List Menu
  test/e2e/tests/account-token-list.spec.js
  ui/components/multichain/account-list-item/account-list-item.js
Labels: team-extension-UX, needs-ux-ds-review

#20354 Fix #19882 - MetaMask support link alignment v2
  ui/pages/home/home.component.js
Labels: team-extension-UX, needs-ux-ds-review

#20248 UX: Remove the 'Source' and 'Link' URLs from NFT detail
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/nft/view-erc1155-details.spec.js
  test/e2e/nft/view-nft-details.spec.js
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/nft-details.js
Labels: team-extension-UX, needs-ux-ds-review

#20188 Fix #20184 - Prevent overflow within the activity list
  ui/components/multichain/activity-list-item/__snapshots__/activity-list-item.test.js.snap
  ui/components/multichain/activity-list-item/activity-list-item.js
  ui/components/multichain/activity-list-item/index.scss
Labels: team-extension-UX, needs-ux-ds-review

#20420 [FLASK] `snaps@0.38.1-flask.1`
  builds.yml
Labels: flask, team-snaps

#20392 Create What's New storybook item
  .storybook/test-data.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/components/app/whats-new-popup/whats-new-popup.stories.js
Labels: team-extension-UX, needs-ux-ds-review

#20442 UX: Remove unwanted spacing from last NFT collection
  ui/components/app/nfts-items/index.scss
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20205 Fix opening of speedup popover in activity list (in the popup view)
  ui/components/multichain/activity-list-item/__snapshots__/activity-list-item.test.js.snap
  ui/components/multichain/activity-list-item/activity-list-item.js
Labels: release-blocker, release-10.35.0

#20362 Add Blockaid / PPOM Failed Request Security Alert
  app/_locales/en/messages.json
  shared/constants/security-provider.ts
  ui/components/app/security-provider-banner-alert/__snapshots__/security-provider-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.js
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.stories.js
Labels: team-confirmations-secure-ux-PR

#20434 Bump SES to fix audit failure
  app/scripts/lockdown-more.js
  package.json
  yarn.lock
Labels: team-extension-platform

#20296 Replacing deprecated constants and updating SnapSettingsCard
  ui/components/app/snaps/snap-settings-card/README.mdx
  ui/components/app/snaps/snap-settings-card/snap-settings-card.js
  ui/components/app/snaps/snap-settings-card/snap-settings-card.stories.js
Labels: team-design-system

#20411 ButtonSecondary to TS
  ui/components/app/modals/eth-sign-modal/eth-sign-modal.js
  ui/components/component-library/button-secondary/README.mdx
  ui/components/component-library/button-secondary/__snapshots__/button-secondary.test.tsx.snap
  ui/components/component-library/button-secondary/button-secondary.constants.js
  ui/components/component-library/button-secondary/button-secondary.js
  ui/components/component-library/button-secondary/button-secondary.scss
  ui/components/component-library/button-secondary/button-secondary.stories.tsx
  ui/components/component-library/button-secondary/button-secondary.test.tsx
  ui/components/component-library/button-secondary/button-secondary.tsx
  ui/components/component-library/button-secondary/button-secondary.types.ts
  ui/components/component-library/button-secondary/index.js
  ui/components/component-library/button-secondary/index.ts
  ui/components/component-library/index.js
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/import-account/bottom-buttons.js
  ui/components/multichain/import-nfts-modal/import-nfts-modal.js
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: team-design-system

#20301 Replacing deprecated component in UpdateSnapPermissionList
  ui/components/app/snaps/update-snap-permission-list/update-snap-permission-list.js
  ui/components/app/snaps/update-snap-permission-list/update-snap-permission-list.stories.js
Labels: team-design-system

#20450 `snaps@1.0.0`
  package.json
  yarn.lock
Labels: team-snaps

#20424 Log before and after each migration run
  app/scripts/lib/migrator/index.js
Labels: release-blocker, team-extension-platform

#20352 [FLASK] Create new E2E test for snaps lifecycle-hooks
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-lifecycle.spec.js
Labels: flask, team-snaps

#19814 Use `addNewAccount` from core `KeyringController`
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-shared-libraries

#20469 Update `protobufjs`
  yarn.lock
Labels: team-extension-platform

#20425 Add additional Sentry E2E tests
  app/scripts/metamask-controller.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/index.js
  ui/store/actions.ts
Labels: release-blocker, team-extension-platform

#20458 Capture app and migration version
  app/scripts/background.js
  app/scripts/controllers/app-metadata.test.ts
  app/scripts/controllers/app-metadata.ts
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
Labels: release-blocker, team-extension-platform

#20479 Fix Sentry error e2e tests
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: team-extension-platform

#20426 Split Sentry mask into UI and background masks
  app/scripts/background.js
  app/scripts/lib/setupSentry.js
  ui/index.js
Labels: release-blocker, team-extension-platform, release-10.34.5

#20451 Removing Box props description from TS component docs
  ui/components/component-library/avatar-account/README.mdx
  ui/components/component-library/avatar-base/README.mdx
  ui/components/component-library/avatar-icon/README.mdx
  ui/components/component-library/avatar-network/README.mdx
  ui/components/component-library/avatar-token/README.mdx
  ui/components/component-library/badge-wrapper/README.mdx
  ui/components/component-library/box/box.types.ts
  ui/components/component-library/button-base/README.mdx
  ui/components/component-library/button-icon/README.mdx
  ui/components/component-library/checkbox/README.mdx
  ui/components/component-library/header-base/README.mdx
  ui/components/component-library/help-text/README.mdx
  ui/components/component-library/icon/README.mdx
  ui/components/component-library/input/README.mdx
  ui/components/component-library/label/README.mdx
  ui/components/component-library/modal-content/README.mdx
  ui/components/component-library/modal-overlay/README.mdx
  ui/components/component-library/modal/README.mdx
  ui/components/component-library/tag/README.mdx
  ui/components/component-library/text/README.mdx
Labels: team-design-system

#20428 Use unflattened state for Sentry
  app/scripts/background.js
  app/scripts/lib/setupSentry.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
Labels: release-blocker, team-extension-platform, release-10.34.5

#20429 Fix Typo in en.json
  app/_locales/en/messages.json
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: team-extension-UX

#20465 Rename BackupController to Backup
  app/scripts/lib/backup.js
  app/scripts/lib/backup.test.js
  app/scripts/metamask-controller.js
Labels: team-extension-platform

#20462 Add additional validation for persisted state metadata
  app/scripts/background.js
Labels: release-blocker, team-extension-platform, release-10.34.5

#20457 Add types of hidden properties to Sentry data
  shared/modules/object.utils.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: release-blocker, team-extension-platform, release-10.34.5

#19815 Use `importAccountWithStrategy` from core `KeyringController`
  app/scripts/account-import-strategies/account-import-strategies.test.js
  app/scripts/account-import-strategies/index.js
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  ui/components/multichain/import-account/import-account.js
  ui/components/multichain/import-account/json.js
  ui/components/multichain/import-account/json.test.tsx
  ui/components/multichain/import-account/private-key.js
  yarn.lock
Labels: team-shared-libraries

#20473 Fix infinite rerender on network change while active signature request
  app/scripts/metamask-controller.js
Labels: team-confirmations-system

#20495 Remove invalid `tokensChainsCache` state
  app/scripts/migrations/077.js
  app/scripts/migrations/077.test.js
  app/scripts/migrations/092.1.test.ts
  app/scripts/migrations/092.1.ts
  app/scripts/migrations/093.test.ts
  app/scripts/migrations/index.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: team-extension-platform, release-10.34.5

#20491 Improve Sentry state pre-initialization
  app/scripts/background.js
  app/scripts/lib/local-store.js
  app/scripts/lib/local-store.test.js
  app/scripts/lib/network-store.js
  app/scripts/lib/setup-initial-state-hooks.js
  app/scripts/lib/setup-persisted-state-hook.js
  app/scripts/ui.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/index.js
Labels: release-blocker, team-extension-platform, release-10.34.5

#20455 [MMI] Fixed connect mmi button several issues
  app/scripts/controllers/mmi-controller.js
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/institutional/custody-confirm-link-modal/custody-confirm-link-modal.js
  ui/components/ui/metafox-logo/horizontal-logo.js
  ui/pages/home/institutional/institutional-home-footer.js
  ui/pages/institutional/custody/__snapshots__/custody.test.js.snap
  ui/pages/institutional/custody/custody.js
  ui/selectors/selectors.js
  yarn.lock
Labels: team-mmi

#19134 Enable snaps in stable
  .circleci/config.yml
  builds.yml
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/run-all.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: team-snaps

#20503 Track usage of snap exports
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
Labels: team-snaps

#20468 Initialize composable observable store after update
  app/scripts/lib/ComposableObservableStore.js
  app/scripts/lib/ComposableObservableStore.test.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
Labels: team-extension-platform

#20480 Updating blockaid related packages
  lavamoat/browserify/flask/policy.json
  package.json
  yarn.lock
Labels: team-confirmations-secure-ux

#20514 Add flag to update E2E snapshots
  README.md
  test/e2e/run-all.js
  test/e2e/run-e2e-test.js
Labels: team-extension-platform

#20386 Require `test-deps-depcheck` to pass CI
  .circleci/config.yml
Labels: team-extension-platform

#20521 Fix Sentry breadcrumbs collection during initialization
  app/scripts/lib/setupSentry.js
Labels: release-blocker, team-extension-platform

#20494 Security Alert Blockaid: fix propType and add instance to ConfirmApprove page
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.test.js
Labels: team-confirmations-secure-ux-PR

#20507 [MMI] Set approved status in tx controller in MMI logic
  app/scripts/controllers/transactions/index.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: team-mmi

#20517 Fix and test log.info calls run for each migration
  app/scripts/background.js
  test/e2e/fixture-builder.js
  test/e2e/tests/errors.spec.js
  ui/index.js
Labels: team-extension-platform

#20391 feat: github actions to automatically create and close bug report issue
  .github/scripts/close-release-bug-report-issue.ts
  .github/workflows/add-release-label.yml
  .github/workflows/check-pr-labels.yml
  .github/workflows/close-bug-report.yml
  .github/workflows/create-bug-report.yml
  package.json
Labels: team-extension-client, team-extension-platform

#20527 [MMI] Always redirect to MMI portfolio dashboard upon the user clicking on swaps
  ui/components/app/wallet-overview/eth-overview.js
Labels: team-mmi

#20529 Fix pre-initialization UI error state capture
  app/scripts/background.js
  app/scripts/lib/network-store.js
  app/scripts/lib/setup-initial-state-hooks.js
  app/scripts/ui.js
Labels: release-blocker, team-extension-platform

#20461 Deprecating ErrorMessage in favor of BannerAlert
  ui/components/ui/error-message/README.mdx
  ui/components/ui/error-message/error-message.component.js
  ui/components/ui/error-message/error-message.stories.js
Labels: team-design-system, needs-ux-ds-review

#20532 Fix Sentry breadcrumb collection during initialization (again)
  app/scripts/background.js
  app/scripts/lib/setup-initial-state-hooks.js
Labels: release-blocker, team-extension-platform

#20341 Use KeyringController messenger events
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-shared-libraries

#20267 [FLASK] Fix regression in transaction confirmation tabs
  test/e2e/snaps/test-snap-txinsights.spec.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
Labels: team-snaps

#20534 Master sync follow v10.34.5
  CHANGELOG.md
  package.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: team-extension-platform

#20545 updated mmi packages version
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-mmi

#20546 Remove snapshot update from release process
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: team-extension-platform

#20525 Don't call "toPrecisionWithoutTrailingZeros" if a destination value is not a number
  ui/pages/swaps/swaps.util.test.js
  ui/pages/swaps/swaps.util.ts
Labels: team-swaps

#20378 Replace IncomingTransactionsController with helper
  app/scripts/controllers/incoming-transactions.js
  app/scripts/controllers/incoming-transactions.test.js
  app/scripts/controllers/transactions/EtherscanRemoteTransactionSource.test.ts
  app/scripts/controllers/transactions/EtherscanRemoteTransactionSource.ts
  app/scripts/controllers/transactions/IncomingTransactionHelper.test.ts
  app/scripts/controllers/transactions/IncomingTransactionHelper.ts
  app/scripts/controllers/transactions/etherscan.test.ts
  app/scripts/controllers/transactions/etherscan.ts
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/controllers/transactions/types.ts
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  app/scripts/migrations/095.test.ts
  app/scripts/migrations/095.ts
  app/scripts/migrations/index.js
  jest.config.js
  shared/constants/transaction.ts
  test/e2e/fixture-builder.js
  test/e2e/tests/clear-activity.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/components/app/modals/account-details-modal/account-details-modal.test.js
  ui/selectors/nonce-sorted-transactions-selector.test.js
  ui/selectors/transactions.js
  ui/store/actions.ts
Labels: team-confirmations-system

#20544 fix(action): octokit not supported on MetaMask repos
  .github/workflows/create-bug-report.yml
Labels: team-extension-client, team-extension-platform

#20547 fix: Remove sentry warning on `undefined` `TokenListController`
  app/scripts/migrations/088.test.ts
  app/scripts/migrations/088.ts
Labels: team-extension-client, team-extension-platform

#20555 [MMI] Fixed bug that was causing to not show the correct account name
  app/scripts/controllers/mmi-controller.js
Labels: team-mmi

#19552 Enable legacy HD paths for trezor users
  app/scripts/metamask-controller.js
  development/sentry-upload-artifacts.sh
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/pages/create-account/connect-hardware/index.js
  yarn.lock
Labels: type-enhancement, team-accounts, QA Passed, release-10.36.0

#19700 fix(settings): fixed two IPFS gateway issues
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/lib/util.test.js
  app/scripts/lib/util.ts
  jest.config.js
  package.json
  test/data/mock-state.json
  ui/pages/keychains/reveal-seed.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.test.js
  yarn.lock
Labels: type-bug, team-accounts, needs-dev-review, release-10.36.0

#20565 [MMI] Fixing iconUrl issue setting the custodianName to custodianType if custodianName is undefined
  ui/pages/institutional/custody/custody.js
Labels: team-mmi

#20369 Remove call to `_updateMemStoreKeyrings`
  app/scripts/metamask-controller.js
Labels: team-accounts, QA Passed

#20520 UX: Multichain: Add address to account picker, change connection to copy button
  app/_locales/en/messages.json
  builds.yml
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/account-picker/account-picker.stories.js
  ui/components/multichain/account-picker/account-picker.test.js
  ui/components/multichain/account-picker/index.scss
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/app-header.test.js
Labels: team-extension-UX, needs-ux-ds-review

#20376 Remove web3 shim usage event
  app/scripts/lib/rpc-method-middleware/handlers/log-web3-shim-usage.js
Labels: team-extension-platform

#20582 Update snaps URLs
  app/scripts/metamask-controller.js
  builds.yml
  shared/modules/provider-injection.js
  test/env.js
Labels: team-snaps

#20585 [MMI] Fixed balance error when creating a new EOA account
  ui/selectors/selectors.js
Labels: team-mmi

#20587 fix(878): fix toggle align styles for eth-sign in settings
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
Labels: team-extension-client, team-extension-platform

#20584 Fix injection blocklist regex
  shared/modules/provider-injection.js
Labels: team-snaps

#20364 Show a slippage notification again before submitting a swap
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/constants/swaps.ts
  test/e2e/swaps/swaps-notifications.spec.js
  ui/pages/swaps/build-quote/build-quote.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
  ui/pages/swaps/prepare-swap-page/review-quote.js
  ui/pages/swaps/prepare-swap-page/slippage-notification-modal.stories.tsx
  ui/pages/swaps/prepare-swap-page/slippage-notification-modal.test.tsx
  ui/pages/swaps/prepare-swap-page/slippage-notification-modal.tsx
  ui/pages/swaps/swaps-banner-alert/swaps-banner-alert.js
  ui/pages/swaps/swaps-banner-alert/swaps-banner-alert.test.js
  ui/pages/swaps/transaction-settings/transaction-settings.js
  ui/pages/swaps/transaction-settings/transaction-settings.test.js
Labels: team-swaps

#20602 [MMI] Several last fixes
  app/scripts/metamask-controller.js
Labels: team-mmi

#20601 Update snaps-related copy
  app/_locales/en/messages.json
  ui/pages/notifications/notification.test.js
Labels: team-snaps

#20600 Always show connected accounts permissions if they exist
  ui/pages/connected-accounts/connected-accounts.component.js
Labels: team-snaps

#20550 Multichain v1 App Footer component
  app/_locales/en/messages.json
  ui/components/multichain/app-footer/app-footer.js
  ui/components/multichain/app-footer/app-footer.scss
  ui/components/multichain/app-footer/app-footer.stories.js
  ui/components/multichain/app-footer/index.js
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
Labels: needs-ux-ds-review

#20606 fix:remove extra $ after variale in french locale
  app/_locales/fr/messages.json
Labels: team-extension-client, team-extension-platform

#20612 fix:fix error of balance fetching when add/import an account
  ui/selectors/selectors.js
Labels: team-extension-client, team-extension-platform

#20385 Fix account selectors when balances are missing
  ui/components/app/edit-gas-fee-popover/edit-gas-fee-popover.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-tooltip/edit-gas-tooltip.test.js
  ui/components/app/gas-details-item/gas-details-item-title/gas-details-item-title.test.js
  ui/components/institutional/custody-confirm-link-modal/custody-confirm-link-modal.js
  ui/ducks/send/send.test.js
  ui/selectors/selectors.js
  ui/store/actions.test.js
Labels: team-extension-platform

#20537 Part of #20163 for file ui\components\app\detected-token\detected-token-values\detected-token-values.js
  ui/components/app/detected-token/detected-token-values/detected-token-values.js
Labels: team-design-system

#20576 split advancedGasFee by network and erase previous options
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/controllers/app-state.js
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/migrations/092.3.test.ts
  app/scripts/migrations/092.3.ts
  app/scripts/migrations/index.js
  test/data/mock-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.test.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-fee-popover.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.test.js
  ui/components/app/signature-request-header/__snapshots__/signature-request-header.test.js.snap
  ui/components/app/signature-request-original/__snapshots__/signature-request-original.test.js.snap
  ui/components/app/signature-request-siwe/__snapshots__/signature-request-siwe.test.js.snap
  ui/components/app/signature-request/signature-request-header/__snapshots__/signature-request-header.component.test.js.snap
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: team-extension-platform

#20624 Track snap uninstalls
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
Labels: team-snaps

#20616 Fix Sentry source maps
  development/sentry-upload-artifacts.sh
Labels: team-extension-platform

#20586 fix: Remove obsolete network controller state properties
  app/scripts/background.js
  app/scripts/migrations/092.2.test.ts
  app/scripts/migrations/092.2.ts
  app/scripts/migrations/index.js
Labels: team-extension-client, team-extension-platform

#20579 20488: Declare <Chip/> as deprecated
  ui/components/ui/chip/chip.js
  ui/components/ui/chip/chip.stories.js
Labels: team-design-system, needs-ux-ds-review

#20492 Feat/18890/button ts update
  ui/components/app/configure-snap-popup/configure-snap-popup.tsx
  ui/components/app/srp-quiz-modal/QuizContent/QuizContent.tsx
  ui/components/app/srp-quiz-modal/SRPQuiz/SRPQuiz.tsx
  ui/components/app/srp-quiz-modal/types.ts
  ui/components/component-library/button-primary/button-primary.scss
  ui/components/component-library/button/README.mdx
  ui/components/component-library/button/__snapshots__/button.test.tsx.snap
  ui/components/component-library/button/button.constants.js
  ui/components/component-library/button/button.js
  ui/components/component-library/button/button.stories.tsx
  ui/components/component-library/button/button.test.tsx
  ui/components/component-library/button/button.tsx
  ui/components/component-library/button/button.types.ts
  ui/components/component-library/button/index.js
  ui/components/component-library/button/index.ts
  ui/components/component-library/header-base/header-base.stories.tsx
  ui/components/component-library/index.js
  ui/components/component-library/input/input.stories.tsx
  ui/components/component-library/modal-content/README.mdx
  ui/components/component-library/modal-content/modal-content.stories.tsx
  ui/components/component-library/modal-header/README.mdx
  ui/components/component-library/modal-header/modal-header.stories.tsx
  ui/components/component-library/popover-header/README.mdx
  ui/components/component-library/popover-header/popover-header.stories.tsx
  ui/pages/keyring-snaps/add-snap-account-modal/add-snap-account-modal.stories.tsx
  ui/pages/keyring-snaps/add-snap-account-modal/add-snap-account-modal.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/header.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/snap-account-detail-page.tsx
  ui/pages/keyring-snaps/snap-card/snap-card.tsx
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/swaps/prepare-swap-page/smart-transactions-popover.stories.tsx
  ui/pages/swaps/prepare-swap-page/smart-transactions-popover.tsx
Labels: team-design-system, team-snaps, needs-ux-ds-review

#20634 Fixing linting issue on develop
  ui/components/app/modals/hold-to-reveal-modal/hold-to-reveal-modal.tsx
Labels: team-design-system

#20622 Declared <Menu/> as deprecate #20499
  ui/components/ui/menu/menu.js
  ui/components/ui/menu/menu.stories.js
Labels: team-design-system, needs-ux-ds-review

#20625 Update UI for blocked tokens, use the latest dev gas api URL
  app/_locales/en/messages.json
  shared/constants/swaps.ts
  shared/lib/swaps-utils.js
  ui/pages/swaps/searchable-item-list/index.scss
  ui/pages/swaps/searchable-item-list/item-list/item-list.component.js
  ui/pages/swaps/swaps.util.test.js
Labels: team-swaps

#20562 Capture exceptions
  app/scripts/controllers/swaps.js
  app/scripts/controllers/swaps.test.js
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
Labels: team-swaps

#20643 Bump snaps packages to `1.0.2`
  builds.yml
  package.json
  yarn.lock
Labels: team-snaps

#20528 UX Multichain: Added balance-overview component
  ui/components/app/asset-list/asset-list.js
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/components/multichain/balance-overview/__snapshots__/balance-overview.test.js.snap
  ui/components/multichain/balance-overview/balance-overview.js
  ui/components/multichain/balance-overview/balance-overview.stories.js
  ui/components/multichain/balance-overview/balance-overview.test.js
  ui/components/multichain/balance-overview/index.js
  ui/components/multichain/index.js
  ui/pages/home/home.component.js
Labels: team-extension-UX, needs-ux-ds-review

#20556 Created new route for connections
  ui/components/multichain/pages/connections/connections.js
  ui/components/multichain/pages/connections/index.js
  ui/components/multichain/pages/index.js
  ui/helpers/constants/routes.ts
  ui/pages/routes/routes.component.js
Labels: team-extension-UX, needs-ux-ds-review

#20559 UX Multichain: Added Select an action Modal
  app/_locales/en/messages.json
  ui/components/multichain/app-footer/app-footer-actions.tsx
  ui/components/multichain/app-footer/app-footer.js
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/select-action-modal-item/__snapshots__/select-action-item.test.js.snap
  ui/components/multichain/select-action-modal-item/index.js
  ui/components/multichain/select-action-modal-item/select-action-item.test.js
  ui/components/multichain/select-action-modal-item/select-action-modal-item.js
  ui/components/multichain/select-action-modal-item/select-action-modal-item.scss
  ui/components/multichain/select-action-modal-item/select-action-modal-item.stories.js
  ui/components/multichain/select-action-modal/index.js
  ui/components/multichain/select-action-modal/select-action-modal.js
  ui/components/multichain/select-action-modal/select-action-modal.stories.js
  ui/components/multichain/select-action-modal/select-action-modal.test.js
  ui/ducks/app/app.ts
  ui/helpers/constants/common.ts
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/store/actionConstants.ts
Labels: team-extension-UX, needs-ux-ds-review

#20637 Sync `develop` with v10.35.0
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#20632 Add whats new popup for changes to advanced gas fee
  app/_locales/en/messages.json
  app/scripts/controllers/app-state.js
  shared/notifications/index.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: release-blocker, team-extension-platform

#20375 fix: overflow of link and warnings
  ui/pages/keyring-snaps/snap-account-detail-page/__snapshots__/snap-account-detail-page.test.tsx.snap
  ui/pages/keyring-snaps/snap-account-detail-page/detail.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/header.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/snap-account-detail-page.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/snap-detail-tag.tsx
Labels: team-accounts, QA Passed

#20595 feat: Add more state props from controllers to Sentry mask
  app/scripts/lib/setupSentry.js
  shared/modules/object.utils.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
Labels: release-blocker, team-extension-client, team-extension-platform

#20640 Declared <TextField/> as deprecated
  ui/components/ui/text-field/text-field.component.js
  ui/components/ui/text-field/text-field.stories.js
Labels: team-design-system

#20617 fix: Buy button not disabled for ERC20 tokens in Sepolia
  shared/constants/network.ts
Labels: external-contributor

#19817 Use `verifySeedPhrase` from `KeyringController`
  app/scripts/lib/seed-phrase-verifier.js
  app/scripts/lib/seed-phrase-verifier.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-shared-libraries

#20530 Fix Blockaid and OpenSea BannerAlert placement for Token Allowance, Confirm Pages, SIWE, and Signature V3/V4 pages
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.test.js
  ui/components/app/security-provider-banner-alert/__snapshots__/security-provider-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.js
  ui/components/app/security-provider-banner-message/security-provider-banner-message.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request/signature-request.js
  ui/components/app/transaction-alerts/transaction-alerts.js
  ui/components/app/transaction-alerts/transaction-alerts.scss
  ui/components/app/transaction-alerts/transaction-alerts.test.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/token-allowance/token-allowance.js
Labels: team-confirmations-secure-ux-PR

#20646 Use getEncryptionPublicKey from Core KeyringController
  .yarn/patches/@metamask-keyring-controller-npm-7.2.0-fcc0c7893b.patch
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: team-shared-libraries

#20665 Bump test-dapp to v7.1.0
  package.json
  test/e2e/nft/erc721-interaction.spec.js
  yarn.lock
Labels: team-confirmations-secure-ux-PR

#20645 UX: Nit: Avoid AccountPicker props error
  ui/components/multichain/app-header/app-header.js
Labels: team-extension-UX, needs-ux-ds-review

#20676 style: update Settings > Experimental > Desktop App - adds section header
  app/_locales/en/messages.json
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
Labels: team-confirmations-secure-ux-PR

#20653 fix(20314): fix window.left negative value causing polifll warning
  app/scripts/lib/notification-manager.js
  app/scripts/lib/notification-manager.test.ts
Labels: team-extension-client, team-extension-platform

#20666 Fix: UnitInput too narrow for small and trailing zeroed numbers
  ui/components/ui/unit-input/unit-input.component.js
Labels: team-extension-UX, needs-ux-ds-review, external-contributor

#20672 Fix #20648 - Show Linea ETH fiat value by default
  ui/selectors/selectors.js
Labels: team-extension-UX, needs-ux-ds-review

#20674 style: Fix Settings pages padding
  ui/pages/settings/index.scss
Labels: area-settings, team-confirmations-secure-ux-PR

#20662 [MMI] Adding missing logic to handle custodian approval in token allowance
  app/scripts/controllers/mmi-controller.js
  ui/pages/confirm-approve/confirm-approve.js
  ui/selectors/institutional/selectors.js
Labels: team-mmi

#20661 Updating padding for 'import-token__custom-token-form' to match 'import-token__search-token'
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
Labels: team-extension-UX, needs-ux-ds-review

#20478 Subscribe to event fired by KeyringController on account removal
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/controllers/mmi-controller.test.js
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/lib/account-tracker.js
  app/scripts/lib/account-tracker.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-shared-libraries
