Repository MetaMask/metamask-extension, pull requests merged in 2023-01, with the labels that each got.

#16982 housekeeping for picker-network
  ui/components/component-library/picker-network/README.mdx
  ui/components/component-library/picker-network/picker-network.test.js
Labels: area-UI, design-system, IA/NAV

#17085 added padding/margin inline, inline-start and inline-end support to Box Component
  ui/components/ui/box/box.js
  ui/components/ui/box/box.stories.js
Labels: area-UI, design-system

#16930 avatar account housekeeping
  ui/components/component-library/avatar-account/README.mdx
  ui/components/component-library/avatar-account/__snapshots__/avatar-account.test.js.snap
  ui/components/component-library/avatar-account/avatar-account.constants.js
  ui/components/component-library/avatar-account/avatar-account.js
  ui/components/component-library/avatar-account/avatar-account.scss
  ui/components/component-library/avatar-account/avatar-account.stories.js
  ui/components/component-library/avatar-account/avatar-account.test.js
  ui/components/component-library/avatar-account/index.js
  ui/components/component-library/avatar-with-badge/avatar-with-badge.stories.js
  ui/components/component-library/index.js
Labels: area-UI, design-system, IA/NAV

#17123 [E2E] Fixes to try to deflake Snaps E2E tests
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-confirm.spec.js
  test/e2e/snaps/test-snap-error.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-update.spec.js
Labels: flask

#17146 [E2E] Change to replace confirm snap to dialog snap
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-installed.spec.js
Labels: flask

#17165 Fix 16842 - Update NFT error message so that it's caught properly and displayed
  ui/store/actions.js
Labels: team-extension-client, team-extension-UX

#16030 Minimize lodash size in dependencies
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: Extension QA Board, PR - P1

#17134 Added padding/margin inline support to the Box component
  ui/components/ui/box/README.mdx
  ui/components/ui/box/box.js
  ui/components/ui/box/box.stories.js
  ui/components/ui/box/box.test.js
  ui/css/design-system/attributes.scss
Labels: area-UI, design-system

#17238 Update chromedriver version to 109
  .circleci/scripts/chrome-install.sh
  package.json
  yarn.lock
Labels: Extension QA Board, team-extension-client

#16772 Toggle option to enable/disable balance and Token rate checking for using third-party API
  .storybook/test-data.js
  app/_locales/en/messages.json
  app/scripts/controllers/detect-tokens.js
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  shared/lib/ui-utils.js
  test/data/mock-state.json
  test/e2e/fixture-builder.js
  test/e2e/restore/MetaMaskUserData.json
  test/jest/mock-store.js
  ui/components/app/currency-input/currency-input.test.js
  ui/components/app/detected-token/detected-token-values/detected-token-values.js
  ui/components/app/gas-details-item/gas-details-item.js
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/send/gas-display/gas-display.js
  ui/pages/send/send-content/__snapshots__/send-content.component.test.js.snap
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/security-tab/security-tab.test.js
  ui/pages/swaps/build-quote/build-quote.js
  ui/pages/swaps/fee-card/fee-card.js
  ui/pages/swaps/fee-card/fee-card.test.js
  ui/pages/swaps/searchable-item-list/item-list/item-list.component.js
  ui/pages/swaps/select-quote-popover/quote-details/quote-details.js
  ui/pages/swaps/select-quote-popover/select-quote-popover.test.js
  ui/pages/swaps/select-quote-popover/sort-list/sort-list.js
  ui/pages/swaps/select-quote-popover/sort-list/sort-list.test.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.js
  yarn.lock
Labels: area-settings, privacy, team-extension-client

#17202 NFTs: Add proper padding to import warning
  ui/pages/add-collectible/add-collectible.js
Labels: area-NFTs, team-extension-client, team-extension-UX

#17061 Update LavaMoat (core/lavapack)
  .yarn/patches/async-done-npm-1.3.2-1f0a4a8997.patch
  development/build/index.js
  development/build/static.js
  lavamoat/build-system/policy.json
  package.json
  test/helpers/protect-intrinsics-helpers.js
  yarn.lock
Labels: dependencies

#17266 Fix #17162 - Add NFT disclaimer to details page
  app/_locales/en/messages.json
  ui/components/app/collectible-details/collectible-details.js
Labels: area-NFTs, team-extension-client, team-extension-UX

#17207 GasDisplay: hide duplicate testnet value
  ui/pages/send/gas-display/gas-display.js
Labels: area-transactions, team-confirmations

#16643 Persist phishing state controller state.
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: team-extension-client

#17286 Added title for each nft in send asset dropdown
  ui/pages/send/send-content/send-asset-row/send-asset-row.component.js
  ui/pages/send/send-content/send-asset-row/send-asset-row.container.js
Labels: area-NFTs, team-extension-UX

#17285 updated initial state of new imported nfts to expanded
  ui/pages/add-collectible/add-collectible.js
Labels: area-NFTs, team-extension-UX

#17299 Fix transaction decoding data types `string` and `bool`
  ui/components/app/transaction-decoding/transaction-decoding.component.js
Labels: area-transactions, team-confirmations

#17269 Fix #17138 - Allow ActionMessage to be autohidden after a given number of milliseconds
  ui/components/ui/actionable-message/actionable-message.js
  ui/pages/home/home.component.js
Labels: area-NFTs, team-extension-client, team-extension-UX

#17297 Added toaster for removed NFTs
  app/_locales/en/messages.json
  ui/components/app/collectible-details/collectible-details.js
  ui/ducks/app/app.js
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/selectors/selectors.js
  ui/store/actionConstants.js
  ui/store/actions.js
Labels: area-NFTs, team-extension-UX

#17133 Copy update for Metamask fee on Swaps
  app/_locales/en/messages.json
Labels: team-swaps

#17205 Updated Icons in Title of NFTs
  ui/components/app/collectibles-items/collectibles-items.js
  ui/hooks/useCollectiblesCollections.js
Labels: area-NFTs, team-extension-client, team-extension-UX

#17345 [FLASK] Update onboarding text to fit new panel
  ui/components/app/flask/experimental-area/experimental-area.js
Labels: flask

#17277 [FLASK] `snaps-monorepo@0.28.0`
  app/scripts/flask/snaps-blocklist.js
  app/scripts/flask/snaps-utilities.js
  app/scripts/flask/snaps-utilities.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: flask

#15461 Fix/use etherjs specific imports
  app/scripts/controllers/ens/ens.js
  app/scripts/controllers/preferences.js
  app/scripts/controllers/swaps.js
  app/scripts/controllers/swaps.test.js
  app/scripts/lib/account-tracker.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy.json
  package.json
  shared/modules/transaction.utils.js
  test/e2e/seeder/ganache-seeder.js
  ui/components/app/srp-input/srp-input.js
  ui/ducks/domains.js
  ui/ducks/send/helpers.test.js
  ui/ducks/send/send.test.js
  ui/pages/send/send.test.js
  yarn.lock
Labels: PR - P1

#17344 Nit fixes for story-test integration
  development/highlights/storybook.js
  package.json
  ui/components/app/app-header/app-header.stories.js
Labels: type-story

#17284 Add alt text for NFT images
  ui/components/app/collectible-details/collectible-details.js
  ui/components/app/collectibles-items/collectibles-items.js
  ui/helpers/utils/collectibles.js
  ui/helpers/utils/collectibles.test.js
Labels: area-NFTs

#17384 Fix broken NFT import and auto-detect flows
  app/scripts/metamask-controller.js
  ui/components/app/collectibles-tab/collectibles-tab.test.js
  ui/ducks/metamask/metamask.js
Labels: area-NFTs

#17391 fix icon names
  ui/components/app/collectible-details/collectible-details.js
  ui/components/app/flask/snap-delineator/snap-delineator.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/component-library/banner-base/README.mdx
  ui/components/component-library/banner-base/banner-base.js
  ui/components/component-library/banner-base/banner-base.stories.js
  ui/components/component-library/banner-base/banner-base.test.js
  ui/components/component-library/button-base/button-base.test.js
  ui/components/component-library/button-link/button-link.test.js
  ui/components/component-library/button-primary/button-primary.test.js
  ui/components/component-library/button-secondary/button-secondary.test.js
  ui/components/component-library/button/button.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
Labels: area-UI, design-system, IA/NAV

#17389 Fix #17388 - Remove dismiss button from NFT notification
  app/scripts/controllers/app-state.js
  app/scripts/metamask-controller.js
  test/e2e/fixture-builder.js
  ui/components/app/collectibles-detection-notice/collectibles-detection-notice.js
  ui/components/app/collectibles-tab/collectibles-tab.js
  ui/components/app/collectibles-tab/collectibles-tab.test.js
  ui/ducks/metamask/metamask.js
  ui/pages/add-collectible/add-collectible.js
  ui/store/actions.js
Labels: area-NFTs

#17392 Fix #17385 - Provide autohide callback for ActionMessage
  ui/components/ui/actionable-message/actionable-message.js
  ui/pages/home/home.component.js
Labels: area-NFTs

#17440 Fix #17362 - Ensure NFT icons are correct
  ui/components/app/collectible-options/collectible-options.js
  ui/components/ui/menu/menu-item.js
Labels: area-NFTs, team-extension-client, team-extension-UX

#17254 [e2e]Add e2e test for deleting custom network
  test/e2e/tests/add-custom-network.spec.js
Labels: PS-team

#17372 feat(mme-17214): migrate L33 files to typescript
  app/scripts/lib/buy-url.ts
  development/verify-locale-strings.js
  package.json
  shared/constants/network.ts
  shared/constants/swaps.ts
  shared/lib/swaps-utils.js
  shared/modules/declare-modules.d.ts
  ui/ducks/gas/gas-action-constants.ts
  ui/ducks/swaps/swaps.js
  ui/helpers/constants/notifications.ts
  ui/helpers/utils/i18n-helper.test.js
  ui/helpers/utils/i18n-helper.tsx
  ui/helpers/utils/moonpay.ts
  ui/helpers/utils/tx-helper.test.js
  ui/helpers/utils/tx-helper.ts
  ui/pages/home/home.container.js
  ui/pages/swaps/swaps.util.test.js
  ui/pages/swaps/swaps.util.ts
  ui/pages/swaps/view-quote/view-quote.js
  yarn.lock
Labels: team-extension-client

#17436 Add e2e test: add custome network during onboarding
  test/e2e/helpers.js
  test/e2e/tests/onboarding.spec.js
Labels: Extension QA Board, team-extension-client, team-extension-platform

#17394 Fix #17393 - Fix NFT collection header image
  ui/components/app/collectibles-items/collectibles-items.js
Labels: area-NFTs

#17400 Fix #17328 - Move NFT settings to Experimental
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/helpers/constants/settings.js
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/index.scss
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
Labels: area-NFTs

#17515 Move THEME_TYPE to new preferences.ts file
  app/scripts/controllers/preferences.js
  shared/constants/preferences.ts
  ui/pages/routes/routes.component.js
  ui/pages/settings/settings-tab/settings-tab.component.js
  ui/pages/settings/settings-tab/settings-tab.constant.js
Labels: team-extension-client
