Repository MetaMask/metamask-extension, pull requests merged in 2023-04, with the labels that each got.

#18372 [FLASK] Add permission cell component
  app/_locales/en/messages.json
  ui/components/app/app-components.scss
  ui/components/app/flask/update-snap-permission-list/update-snap-permission-list.js
  ui/components/app/permission-cell/index.js
  ui/components/app/permission-cell/index.scss
  ui/components/app/permission-cell/permission-cell.js
  ui/components/app/permission-cell/permission-cell.stories.js
  ui/components/app/permission-cell/permission-cell.test.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
  ui/helpers/utils/permission.js
  ui/pages/permissions-connect/flask/snap-install/index.scss
  ui/pages/settings/flask/view-snap/view-snap.js
Labels: team-snaps

#18283 UXMultichain: update segmented tabs
  ui/components/ui/tabs/dropdown-tab/dropdown-tab.js
  ui/components/ui/tabs/index.scss
  ui/components/ui/tabs/tab/index.scss
  ui/components/ui/tabs/tab/tab.component.js
  ui/components/ui/tabs/tabs.component.js
  ui/components/ui/tabs/tabs.stories.js
  ui/pages/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/home/index.scss
Labels: team-extension-client, team-extension-UX

#18396 Disabled button for Import Tokens Modal when no token is selected
  ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js
Labels: team-extension-client, team-extension-UX

#18356 Don't include document in scuttling config for mv3 builds
  development/build/config.js
  development/build/scripts.js
Labels: MV3, team-extension-client, team-extension-platform

#18447 [FLASK] Fix crash when requesting unknown snap permission
  ui/components/app/flask/update-snap-permission-list/update-snap-permission-list.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
  ui/helpers/utils/permission.js
  ui/pages/permissions-connect/flask/snap-install/snap-install.js
  ui/pages/permissions-connect/flask/snap-update/snap-update.js
  ui/pages/permissions-connect/flask/util.js
  ui/pages/settings/flask/view-snap/view-snap.js
Labels: flask

#18450 Small update to badgewrapper story
  ui/components/component-library/badge-wrapper/badge-wrapper.stories.tsx
Labels: design-system

#18245 [FLASK] More Snaps E2E Optimization and Delay Reductions
  .circleci/config.yml
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-error.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-update.spec.js
Labels: flask

#18411 Update new send icon
  app/images/icons/arrow-2-up-right.svg
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/token-overview.js
  ui/components/component-library/icon/icon.types.ts
Labels: team-extension-client, team-extension-UX

#18496 Fix hold to reveal button
  ui/components/app/hold-to-reveal-button/hold-to-reveal-button.js
Labels: type-bug, design-system

#18086 Disabling network and account changes after the send flow is initiated
  coverage-targets.js
  test/data/mock-send-state.json
  ui/components/app/app-header/app-header.component.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.component.test.js
Labels: type-bug, area-transactions, Sev2-normal, team-confirmations-secure-ux-PR

#18557 UX Multichain: Updated copy Address
  ui/components/app/wallet-overview/wallet-overview.js
Labels: team-extension-client, team-extension-UX

#18470 [FLASK] Revert changes made to stable permission display (UI design)
  ui/components/app/flask/snap-permissions-list/index.js
  ui/components/app/flask/snap-permissions-list/snap-permissions-list.js
  ui/components/app/flask/snap-permissions-list/snap-permissions-list.stories.js
  ui/components/app/flask/snap-permissions-list/snap-permissions-list.test.js
  ui/components/app/permission-cell/permission-cell.js
  ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.stories.js
  ui/helpers/utils/permission.js
  ui/pages/permissions-connect/flask/snap-install/snap-install.js
  ui/pages/settings/flask/view-snap/view-snap.js
Labels: team-snaps

#18589 SIWE | Sign-in With Ethereum - Add Ledger Instructions
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request-siwe/signature-request-siwe.test.js
Labels: area-signatures, team-confirmations-secure-ux-PR

#18598 Fix issue with requests with empty data being forwarded to opensea
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
Labels: release-blocker, v10.29.0

#18565 [FLASK] Remove unused snaps code
  .storybook/test-data.js
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/controllers/permissions/flask/snap-permissions.test.js
  app/scripts/metamask-controller.js
  ui/helpers/utils/permission.js
  ui/pages/confirmation/templates/flask/snap-confirmation/snap-confirmation.js
Labels: flask

#17976 New reusable gas-display component
  ui/components/app/approve-content-card/approve-content-card.js
  ui/components/app/confirm-gas-display/__snapshots__/confirm-gas-display.test.js.snap
  ui/components/app/confirm-gas-display/confirm-gas-display.js
  ui/components/app/confirm-gas-display/confirm-gas-display.test.js
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/README.mdx
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/__snapshots__/confirm-legacy-gas-display.test.js.snap
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.stories.js
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.test.js
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/index.js
  ui/components/app/confirm-gas-display/index.js
  ui/components/app/gas-details-item/gas-details-item.js
  ui/hooks/useDraftTransactionGasValues.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/send/gas-display/gas-display.js
  ui/pages/send/gas-display/index.scss
  ui/pages/send/send-content/__snapshots__/send-content.component.test.js.snap
  ui/pages/token-allowance/token-allowance.test.js
Labels: team-confirmations-secure-ux-PR

#18614 Fix error in console on rejecting signature request
  app/scripts/controllers/sign.ts
Labels: v10.29.0

#18617 fix/18577: Add title back for approving ERC20 token
  ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.js
Labels: team-extension-client, team-extension-platform, v10.29.0

#18554 Overriding gas estimate in the send page even if enough ETH is not available
  ui/pages/send/send-content/send-content.component.js
  ui/pages/send/send-content/send-content.component.test.js
  ui/pages/send/send-footer/send-footer.component.js
Labels: team-confirmations-secure-ux-PR

#18637 Ledger trezor display
  ui/pages/confirm-approve/confirm-approve.js
  ui/pages/token-allowance/token-allowance.js
  ui/pages/token-allowance/token-allowance.test.js
Labels: v10.29.0

#18524 Update gas limit on token allowance change
  test/data/mock-state.json
  ui/components/app/custom-spending-cap/__snapshots__/custom-spending-cap.test.js.snap
  ui/components/app/custom-spending-cap/custom-spending-cap.js
  ui/components/app/custom-spending-cap/custom-spending-cap.test.js
  ui/pages/token-allowance/token-allowance.js
  ui/pages/token-allowance/token-allowance.test.js
Labels: release-blocker, v10.29.0

#18635 knob to control
  .storybook/initial-states/approval-screens/add-suggested-token.js
  .storybook/test-data.js
  ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.stories.js
Labels: design-system

#18661 [E2E]: Avoid resetting the mock server
  test/e2e/helpers.js
  test/e2e/mock-e2e.js
  test/e2e/tests/ens.spec.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/metrics.spec.js
  test/e2e/tests/network-error.spec.js
Labels: team-extension-client, team-extension-platform

#18539 Fix Sentry console logs
  development/build/scripts.js
Labels: release-blocker, v10.29.0

#18660 fix(18574): fix new BigNumber() not a number: undefined for setApprovalForAll method
  ui/helpers/utils/token-util.js
  ui/hooks/useAssetDetails.test.js
Labels: team-extension-client, team-extension-platform, v10.29.0

#18570 18566 firefox ledger u2f message
  app/_locales/en/messages.json
  coverage-targets.js
  shared/notifications/index.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/helpers/constants/zendesk-url.js
  ui/pages/create-account/connect-hardware/__snapshots__/index.test.tsx.snap
  ui/pages/create-account/connect-hardware/index.js
  ui/pages/create-account/connect-hardware/index.test.tsx
  ui/selectors/selectors.js
Labels: release-blocker, team-key-management, v10.29.0

#18501 Update to component-library readme
  ui/components/component-library/README.md
Labels: area-documentation, design-system

#18259 Create New Vault test improvements
  ui/components/app/create-new-vault/create-new-vault.js
  ui/components/app/create-new-vault/create-new-vault.test.js
Labels: team-extension-client, team-extension-platform

#18258 Add Network Modal onboarding unit test
  ui/pages/onboarding-flow/add-network-modal/__snapshots__/add-network-modal.test.js.snap
  ui/pages/onboarding-flow/add-network-modal/add-network-modal.test.js
Labels: team-extension-client, team-extension-platform

#18255 Import srp onboarding unit tests
  ui/pages/onboarding-flow/import-srp/import-srp.test.js
Labels: team-extension-client, team-extension-platform

#18256 Creation successful onboarding test improvements
  ui/pages/onboarding-flow/creation-successful/creation-successful.test.js
Labels: team-extension-client, team-extension-platform

#18257 Create Password onboarding unit test, test-ids, and snapshot
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/create-password/create-password.test.js
Labels: team-extension-client, team-extension-platform

#18696 [FLASK] add new snaps wasm test
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-wasm.spec.js
Labels: flask, team-snaps

#18652 TransactionUtils: update determineTransactionType method / contractInteraction support
  shared/modules/transaction.utils.js
  shared/modules/transaction.utils.test.js
Labels: DO-NOT-MERGE, needs-qa, team-confirmations-secure-ux-PR

#18721 Update outdated browser versions
  ui/helpers/constants/common.ts
  ui/helpers/utils/util.test.js
Labels: release-blocker, v10.30.0

#18571 UX Multichain: Added product tour component
  app/_locales/en/messages.json
  app/scripts/controllers/app-state.js
  app/scripts/metamask-controller.js
  ui/components/component-library/avatar-base/avatar-base.js
  ui/components/component-library/avatar-network/avatar-network.js
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/app-header.scss
  ui/components/multichain/app-header/app-header.test.js
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/product-tour-popover/index.js
  ui/components/multichain/product-tour-popover/product-tour-popover.js
  ui/components/multichain/product-tour-popover/product-tour-popover.scss
  ui/components/multichain/product-tour-popover/product-tour-popover.stories.js
  ui/components/multichain/product-tour-popover/product-tour-popover.test.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-extension-client, team-extension-UX

#18230 Sign-in With Ethereum SIWE cleanup
  ui/components/app/signature-request-siwe/__snapshots__/signature-request-siwe.test.js.snap
  ui/components/app/signature-request-siwe/signature-request-siwe-message/index.scss
  ui/components/app/signature-request-siwe/signature-request-siwe-message/signature-request-siwe-message.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
Labels: area-signatures, team-confirmations-secure-ux-PR

#18671 Update knobs to controls in storybook: SelectQuotePopover
  ui/pages/swaps/select-quote-popover/select-quote-popover.stories.js
Labels: design-system

#18435 Part of 17670: Replace Typography with Text in detected-token-address.js
  ui/components/app/detected-token/detected-token-address/detected-token-address.js
Labels: design-system

#18569 Part of #17670: Replace Typography with Text component
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.js
Labels: design-system

#18438 [FLASK] Add updated version of the Snaps settings UI
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/data/mock-state.json
  test/e2e/snaps/test-snap-management.spec.js
  ui/components/app/flask/snap-avatar/snap-avatar.js
  ui/components/app/flask/snap-settings-card/index.scss
  ui/components/app/flask/snap-settings-card/snap-settings-card.js
  ui/components/app/flask/snap-settings-card/snap-settings-card.test.js
  ui/components/app/tab-bar/tab-bar.stories.js
  ui/pages/settings/flask/snaps-list-tab/index.scss
  ui/pages/settings/flask/snaps-list-tab/snap-list-tab.js
  ui/pages/settings/flask/view-snap/index.scss
  ui/pages/settings/flask/view-snap/view-snap.js
  ui/pages/settings/flask/view-snap/view-snap.test.js
  ui/pages/settings/settings.component.js
  ui/selectors/selectors.js
Labels: flask, team-snaps

#18719 [FLASK] Fix text selection bug in snap ui
  ui/components/app/flask/snap-ui-renderer/snap-ui-renderer.js
  ui/pages/confirmation/templates/flask/snap-alert/snap-alert.js
  ui/pages/confirmation/templates/flask/snap-confirmation/snap-confirmation.js
  ui/pages/confirmation/templates/flask/snap-prompt/snap-prompt.js
Labels: type-bug, flask, team-snaps

#18491 Shallow git clone
  .circleci/config.yml
Labels: team-key-management

#18781 [FLASK] Fix missing icon for webassembly endowment
  ui/helpers/utils/permission.js
Labels: type-bug, flask, team-snaps

#18786 [FLASK] Update permissions to use IconName and IconSize design system enum
  ui/helpers/utils/permission.js
Labels: flask, design-system, team-snaps

#18644 Part of #17670 for file network-statistics.js
  ui/components/app/edit-gas-fee-popover/network-statistics/network-statistics.js
Labels: design-system

#18508 Fix diff generation for fitness functions
  .github/workflows/fitness-functions.yml
Labels: team-extension-client, team-extension-platform

#18775 [FLASK] Expanded Snap authorship
  app/_locales/en/messages.json
  ui/components/app/app-components.scss
  ui/components/app/snaps/snap-authorship/snap-authorship.js
  ui/components/app/snaps/snap-avatar/snap-avatar.js
  ui/components/app/snaps/snap-version/index.js
  ui/components/app/snaps/snap-version/index.scss
  ui/components/app/snaps/snap-version/snap-version.js
  ui/components/app/snaps/snap-version/snap-version.stories.js
  ui/components/app/snaps/snap-version/snap-version.test.js
  ui/helpers/constants/flask/delineator.ts
  ui/pages/permissions-connect/snaps/snap-install/index.scss
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
  ui/pages/permissions-connect/snaps/snap-update/index.scss
  ui/pages/permissions-connect/snaps/snap-update/snap-update.js
  ui/pages/settings/snaps/view-snap/index.scss
  ui/pages/settings/snaps/view-snap/view-snap.js
  ui/pages/settings/snaps/view-snap/view-snap.test.js
Labels: flask

#18217 Enable editing L2 gas on optimism
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/advanced-gas-controls/advanced-gas-controls.component.js
  ui/components/app/advanced-gas-inputs/advanced-gas-inputs.component.js
  ui/components/app/advanced-gas-inputs/advanced-gas-inputs.container.js
  ui/components/app/approve-content-card/approve-content-card.js
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.test.js
  ui/components/app/multilayer-fee-message/__snapshots__/multi-layer-fee-message.test.js.snap
  ui/components/app/multilayer-fee-message/multi-layer-fee-message.js
  ui/components/app/multilayer-fee-message/multi-layer-fee-message.test.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-approve/confirm-approve.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirm-transaction/confirm-token-transaction-switch.js
  ui/pages/send/send-content/send-content.component.js
  ui/pages/send/send-content/send-content.container.js
  ui/pages/token-allowance/token-allowance.js
  ui/selectors/selectors.js
Labels: team-confirmations-secure-ux-PR

#18677 Update knobs to control: MetamaskTemplateRenderer
  ui/components/app/metamask-template-renderer/metamask-template-renderer.stories.js
Labels: design-system

#18774 Update Button prop name type to variant
  ui/components/app/modals/hold-to-reveal-modal/hold-to-reveal-modal.js
  ui/components/app/snaps/snap-version/snap-version.js
  ui/components/app/terms-of-use-popup/terms-of-use-popup.js
  ui/components/component-library/button/README.mdx
  ui/components/component-library/button/button.constants.js
  ui/components/component-library/button/button.js
  ui/components/component-library/button/button.stories.js
  ui/components/component-library/button/button.test.js
  ui/components/component-library/button/index.js
  ui/components/component-library/index.js
  ui/components/institutional/compliance-settings/compliance-settings.js
  ui/components/institutional/custody-confirm-link-modal/custody-confirm-link-modal.js
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/pages/create-account/connect-hardware/index.js
  ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.js
  ui/pages/institutional/confirm-add-institutional-feature/confirm-add-institutional-feature.js
  ui/pages/keychains/reveal-seed.js
  ui/pages/settings/snaps/view-snap/view-snap.js
Labels: design-system

#18816 Strong tag support in Text component
  ui/components/component-library/text/README.mdx
  ui/components/component-library/text/text.scss
  ui/components/component-library/text/text.stories.tsx
Labels: design-system

#18803 Update Snaps icon in settings search and fix missing icon
  ui/helpers/constants/settings.js
Labels: bug, team-snaps

#18674 UX: Multichain: Analytics
  shared/constants/metametrics.ts
  test/e2e/tests/portfolio-site.spec.js
  ui/components/app/asset-list/detected-tokens-link/detected-tokens-link.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/components/app/confirm-page-container/confirm-page-container.component.js
  ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js
  ui/components/app/detected-token/detected-token.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/token-overview.js
  ui/components/app/wallet-overview/token-overview.test.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/detected-token-banner/detected-token-banner.js
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/global-menu/global-menu.test.js
  ui/components/multichain/multichain-token-list-item/multichain-token-list-item.js
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/helpers/utils/metrics.js
  ui/helpers/utils/portfolio.js
  ui/pages/add-nft/add-nft.js
  ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.js
  ui/pages/confirm-import-token/confirm-import-token.js
  ui/pages/create-account/import-account/import-account.js
  ui/pages/create-account/new-account.component.js
  ui/pages/home/home.component.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/selectors/selectors.js
Labels: needs-ux-ds-review

#18639 Part of #17670: Replace Typography with Text component in RecoveryPhraseReminder
  ui/components/app/recovery-phrase-reminder/recovery-phrase-reminder.js
  ui/components/app/recovery-phrase-reminder/recovery-phrase-reminder.stories.js
Labels: design-system

#18833 Adding price checker deactivation for Optimism
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js
  ui/components/app/multilayer-fee-message/__snapshots__/multi-layer-fee-message.test.js.snap
  ui/components/app/multilayer-fee-message/multi-layer-fee-message.js
  ui/components/app/multilayer-fee-message/multi-layer-fee-message.test.js
Labels: type-bug, team-confirmations-secure-ux-PR

#18874 fix: remove firefox build for beta
  development/metamaskbot-build-announce.js
Labels: team-extension-client, team-extension-platform

#18710 fix(18709): fix error when switching to linea testnet using wallet_sw…
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
Labels: release-blocker, v10.30.0

#18854 E2E: update selenium webdriver
  package.json
  yarn.lock
Labels: team-extension-client, team-extension-platform

#18861 Terms of use e2e
  test/e2e/fixture-builder.js
  test/e2e/tests/terms-of-use.spec.js
Labels: team-extension-client, team-extension-platform

#18731 UX: Multichain: Set a maximum width on the network picker
  ui/components/component-library/picker-network/README.mdx
  ui/components/component-library/picker-network/picker-network.stories.js
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/app-header.scss
Labels: needs-ux-ds-review

#18873 Consistent message for third party requests across screens
  app/_locales/en/messages.json
Labels: release-blocker

#18837 Part of #17670: Replace Typography with Text component for 11 files.
  ui/components/app/custom-spending-cap/__snapshots__/custom-spending-cap.test.js.snap
  ui/components/app/qr-hardware-popover/qr-hardware-sign-request/player.js
  ui/components/app/recovery-phrase-reminder/recovery-phrase-reminder.js
  ui/components/app/security-provider-banner-message/security-provider-banner-message.js
  ui/components/ui/deprecated-test-networks/deprecated-test-networks.js
  ui/components/ui/form-field/form-field.js
  ui/components/ui/form-field/form-field.stories.js
  ui/components/ui/logo/logo.stories.js
  ui/components/ui/metafox-logo/metafox-logo.stories.js
  ui/components/ui/new-network-info/new-network-info.js
  ui/components/ui/nft-info/nft-info.js
  ui/components/ui/radio-group/radio-group.component.js
  ui/pages/onboarding-flow/add-network-modal/__snapshots__/add-network-modal.test.js.snap
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
Labels: design-system
