Repository MetaMask/metamask-extension, pull requests merged in 2023-11, with the labels that each got.

#21613 Bump `PhishingController` to `7.0.1`
  app/scripts/lib/snap-keyring/utils/isBlockedUrl.test.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#21628 fix erc1155 test flakiness
  test/e2e/tests/nft/view-erc1155-details.spec.js
Labels: team-extension-client, team-extension-platform, INVALID-PR-TEMPLATE

#21559 Decouple swaps metric logic from `TransactionController`
  app/scripts/controllers/transactions/index.js
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
  shared/constants/transaction.ts
Labels: team-confirmations-system

#21639 Mocking IPFS requests on erc1155 tests
  test/e2e/tests/nft/remove-erc1155.spec.js
  test/e2e/tests/nft/view-erc1155-details.spec.js
Labels: team-extension-client, team-extension-platform, INVALID-PR-TEMPLATE

#21640 fix: flaky tests in v11.5.0
  .circleci/config.yml
  development/lib/retry.js
  lavamoat/build-system/policy.json
  package.json
  test/e2e/accounts/common.ts
  test/e2e/accounts/create-snap-account.spec.ts
  test/e2e/accounts/remove-account-snap.spec.ts
  test/e2e/accounts/snap-account-signatures-and-disconnects.spec.ts
  test/e2e/accounts/snap-account-signatures.spec.ts
  test/e2e/accounts/snap-account-transfers.spec.ts
  test/e2e/accounts/utils.ts
  test/e2e/helpers.js
  test/e2e/json-rpc/switchEthereumChain.spec.js
  test/e2e/metamask-ui.spec.js
  test/e2e/run-all.js
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-revoke-perm.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  test/e2e/tests/add-account.spec.js
  test/e2e/tests/ens.spec.js
  test/e2e/tests/import-flow.spec.js
  test/e2e/tests/metrics/unlock-wallet.spec.js
  test/e2e/tests/nft/remove-erc1155.spec.js
  test/e2e/tests/nft/view-erc1155-details.spec.js
  test/e2e/tests/onboarding.spec.js
  test/e2e/tests/ppom-blockaid-alert.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/webdriver/chrome.js
  test/e2e/webdriver/driver.js
  test/e2e/webdriver/firefox.js
  test/e2e/webdriver/index.js
  yarn.lock
Labels: team-extension-client, team-extension-platform, INVALID-PR-TEMPLATE

#21585 One-liner to fill signature content in container
  ui/components/app/signature-request/index.scss
Labels: team-confirmations-secure-ux, INVALID-PR-TEMPLATE

#21434 UX: Update querystring for analytics
  privacy-snapshot.json
  ui/pages/onboarding-flow/create-password/create-password.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21608 UX: Send Flow: Convert Recipient Input to TypeScript
  ui/components/multichain/pages/send/components/recipient-input.tsx
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21604 Fix: Contract data reading and parsing
  shared/modules/contract-utils.test.js
  shared/modules/contract-utils.ts
  shared/modules/transaction.utils.js
  shared/modules/transaction.utils.test.js
Labels: team-confirmations-system

#21635 ci(resources): update parallelism and resource class for e2e tests
  .circleci/config.yml
Labels: team-extension-platform

#21634 UX: Add label to Select Action button
  app/_locales/en/messages.json
  ui/components/multichain/app-footer/__snapshots__/app-footer.test.js.snap
  ui/components/multichain/app-footer/app-footer.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21576 UX Multichain: Updated account picker in new send flow
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/account-picker.tsx
  ui/components/multichain/pages/send/index.scss
Labels: team-extension-UX, needs-ux-ds-review, INVALID-PR-TEMPLATE

#21643 Fix/actions improvement
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/scripts/check-template-and-add-labels.ts
  .github/scripts/shared/template.ts
Labels: team-extension-client, team-extension-platform

#21650 fix: v11.5.0 e2e test flakiness
  .circleci/config.yml
  development/lib/retry.js
  lavamoat/build-system/policy.json
  package.json
  test/e2e/accounts/common.ts
  test/e2e/accounts/create-snap-account.spec.ts
  test/e2e/accounts/remove-account-snap.spec.ts
  test/e2e/accounts/snap-account-signatures-and-disconnects.spec.ts
  test/e2e/accounts/snap-account-signatures.spec.ts
  test/e2e/accounts/snap-account-transfers.spec.ts
  test/e2e/accounts/test-remove-accounts-snap.spec.js
  test/e2e/accounts/test-snap-accounts.spec.js
  test/e2e/accounts/utils.ts
  test/e2e/helpers.js
  test/e2e/json-rpc/switchEthereumChain.spec.js
  test/e2e/metamask-ui.spec.js
  test/e2e/run-all.js
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-revoke-perm.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  test/e2e/tests/add-account.spec.js
  test/e2e/tests/ens.spec.js
  test/e2e/tests/import-flow.spec.js
  test/e2e/tests/metrics/unlock-wallet.spec.js
  test/e2e/tests/nft/remove-erc1155.spec.js
  test/e2e/tests/nft/view-erc1155-details.spec.js
  test/e2e/tests/onboarding.spec.js
  test/e2e/tests/ppom-blockaid-alert.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/webdriver/chrome.js
  test/e2e/webdriver/driver.js
  test/e2e/webdriver/firefox.js
  test/e2e/webdriver/index.js
  yarn.lock
Labels: team-extension-client, team-extension-platform, INVALID-PR-TEMPLATE

#21612 Bump snaps packages
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#21652 patch: Hide "Add Snap accounts" toggle from experimental settings
  builds.yml
  shared/modules/snap-accounts.test.ts
  shared/modules/snap-accounts.ts
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
Labels: team-accounts

#21593 fix: fix import address with non checksum Adr
  ui/helpers/utils/util.js
  ui/helpers/utils/util.test.js
Labels: team-extension-UX, QA Passed, needs-ux-ds-review

#21171 Replace MMI code fence with callbacks and arguments
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/pending-tx-tracker.js
  app/scripts/controllers/transactions/pending-tx-tracker.test.js
  app/scripts/lib/transaction/mmi-hooks.test.ts
  app/scripts/lib/transaction/mmi-hooks.ts
  app/scripts/metamask-controller.js
Labels: team-confirmations-system

#21616 [MMI] enables simple send test
  test/e2e/tests/simple-send.spec.js
Labels: team-mmi

#21617 [MMI] passing the selectedAddress field
  app/scripts/controllers/metametrics.js
Labels: team-mmi

#21539 Remove derived `targetSubjectMetadata` from state and use props
  ui/pages/permissions-connect/permissions-connect.component.js
Labels: team-snaps, QA Passed

#21658 Cherry pick accounts PR into v11.4.1
  builds.yml
  shared/modules/snap-accounts.test.ts
  shared/modules/snap-accounts.ts
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
Labels: team-accounts

#21645 fix:style: Apply 100% width to Sign-in With Ethereum (SIWE) popup
  ui/components/app/signature-request-siwe/index.scss
Labels: team-confirmations-secure-ux-PR

#21664 Fix `Text` `inherit` variant
  ui/components/component-library/text/text.scss
Labels: team-design-system

#21572 Added multichain polling to DetectTokensController via PollingControllerOnly
  .eslintrc.js
  .mocharc.js
  app/scripts/controllers/detect-tokens.js
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/metamask-controller.js
  jest.config.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-devex, INVALID-PR-TEMPLATE

#21481 e2e: with the newest version of Selenium, manually updating Geckodriver and Chromedriver is no longer necessary
  .circleci/config.yml
  .circleci/scripts/chrome-install.sh
  .circleci/scripts/firefox-install.sh
  package.json
  yarn.lock
Labels: team-accounts

#21666 Fix MMI callbacks when checking pending transaction
  app/scripts/controllers/transactions/pending-tx-tracker.js
Labels: team-confirmations-system

#21674 Resolve network names using SLIP44 when applicable
  ui/helpers/utils/util.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#21679 Fix flakiness on `user-actions-benchmark.js`
  test/e2e/user-actions-benchmark.js
Labels: team-extension-client, team-extension-platform, INVALID-PR-TEMPLATE

#21545 Add test scenarios for swap
  test/scenarios/15. swap/smart swap.csv
  test/scenarios/15. swap/swap eth.csv
Labels: area-documentation, team-extension-client, team-extension-platform

#21663 [MMI] enables some MM tests to run
  test/e2e/tests/chain-interactions.spec.js
  test/e2e/tests/nft/erc1155-interaction.spec.js
  test/e2e/tests/nft/remove-erc1155.spec.js
  test/e2e/tests/nft/send-nft.spec.js
  test/e2e/tests/nft/view-erc1155-details.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/signature-request.spec.js
  ui/pages/confirm-approve/confirm-approve-content/__snapshots__/confirm-approve-content.component.test.js.snap
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
Labels: team-mmi

#21551 UX: Multichain: Send Flow: Hex Data
  ui/components/multichain/pages/send/components/content.tsx
  ui/components/multichain/pages/send/components/hex.tsx
  ui/components/multichain/pages/send/components/index.ts
  ui/components/multichain/pages/send/send.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21671 Fix `AvatarAccount` type
  ui/components/component-library/avatar-account/avatar-account.types.ts
Labels: team-snaps, INVALID-PR-TEMPLATE

#21654 UX: Send flow: Wire submit button
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/send.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21677 document scenario
  test/scenarios/16. incoming-transactions/receive native token.csv
Labels: team-extension-client, team-extension-platform

#21657 Version v11.4.1
  CHANGELOG.md
  builds.yml
  package.json
  shared/modules/snap-accounts.test.ts
  shared/modules/snap-accounts.ts
  ui/components/app/snaps/snap-authorship-expanded/snap-authorship-expanded.js
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
  yarn.lock
Labels: team-extension-client, team-extension-platform, INVALID-PR-TEMPLATE

#21690 deps(audit): ignore metamask/types deprecation
  .yarnrc.yml
Labels: team-extension-platform

#21676 Ignore error while fetching `safeChainsList` for validation
  app/_locales/en/messages.json
  ui/pages/confirmation/templates/add-ethereum-chain.js
Labels: team-confirmations-system

#20554 [FLASK] Transaction Insights V2 Integration
  app/_locales/en/messages.json
  app/scripts/background.js
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  ui/components/app/app-components.scss
  ui/components/app/confirm-page-container/confirm-page-container.component.js
  ui/components/app/confirm-page-container/snaps/snap-insight.js
  ui/components/app/snaps/snap-delineator/index.scss
  ui/components/app/snaps/snap-delineator/snap-delineator.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/components/app/snaps/tx-insight-warnings/index.js
  ui/components/app/snaps/tx-insight-warnings/index.scss
  ui/components/app/snaps/tx-insight-warnings/tx-insight-warnings.js
  ui/helpers/constants/snaps/delineator.ts
  ui/hooks/snaps/useTransactionInsightSnap.js
  ui/hooks/snaps/useTransactionInsightSnaps.js
  ui/hooks/useTransactionInsights.js
  ui/pages/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
  ui/selectors/permissions.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-snaps

#21660 Bug: Add Network Form: Warnings & Errors disappear after a few seconds
  ui/pages/settings/networks-tab/networks-form/networks-form.js
Labels: team-extension-UX, needs-ux-ds-review

#21476 [MMI] changes for supporting MMI ECA3
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/selectors/institutional/selectors.js
  yarn.lock
Labels: team-mmi

#21668 Bump `@metamask/network-controller` to `15.1.0`
  app/scripts/lib/account-tracker.js
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  app/scripts/ui.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/tests/send-eth.spec.js
  yarn.lock
Labels: team-devex

#21334 fix typos
  README.md
  app/scripts/controllers/transactions/IncomingTransactionHelper.test.ts
  app/scripts/controllers/transactions/etherscan.test.ts
  shared/lib/swaps-utils.js
  ui/hooks/gasFeeInput/useGasFeeInputs.js
  ui/selectors/transactions.js
Labels: external-contributor

#21630 Create E2E test for snap_getFile
  test/e2e/flask/petnames.spec.js
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-get-file.spec.js
Labels: area-snaps, team-snaps, INVALID-PR-TEMPLATE

#21714 Cherry-pick snaps files hotfix
  app/scripts/metamask-controller.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#21010 Move from @download/blockies to blo
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.test.js
  ui/components/ui/identicon/blockieIdenticon/blockieIdenticon.component.js
  yarn.lock
Labels: dependencies, team-extension-platform, external-contributor

#21621 UX: Convert Page, Header, Footer, Content to TypeScript
  ui/components/multichain/pages/all-connections/__snapshots__/all-connections.test.js.snap
  ui/components/multichain/pages/page/components/content/content.tsx
  ui/components/multichain/pages/page/components/content/index.ts
  ui/components/multichain/pages/page/components/footer/footer.stories.tsx
  ui/components/multichain/pages/page/components/footer/footer.tsx
  ui/components/multichain/pages/page/components/footer/index.ts
  ui/components/multichain/pages/page/components/header/header.stories.tsx
  ui/components/multichain/pages/page/components/header/header.test.tsx
  ui/components/multichain/pages/page/components/header/header.tsx
  ui/components/multichain/pages/page/components/header/index.ts
  ui/components/multichain/pages/page/index.ts
  ui/components/multichain/pages/page/page.stories.tsx
  ui/components/multichain/pages/page/page.tsx
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21696 Update content for liquidity source info
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/ph/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/pages/swaps/select-quote-popover/quote-details/quote-details.js
Labels: area-swaps, team-swaps, INVALID-PR-TEMPLATE

#21145 Update `@metamask/eth-trezor-keyring`
  app/scripts/lib/hardware-keyring-builder-factory.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-shared-libraries, team-extension-platform

#21605 UX: Send Flow: Gas Controls
  ui/components/multichain/pages/send/components/content.tsx
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21516 Add simplified version of Snap install warning modal
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  ui/components/app/permission-cell/permission-cell.js
  ui/components/app/snaps/snap-install-warning/index.scss
  ui/components/app/snaps/snap-install-warning/snap-install-warning.js
  ui/helpers/utils/permission.js
Labels: team-snaps

#21651 deps: Update @metamask/post-message-stream and dependents
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#21707 e2e: fixing automatic installation of webdriver
  .circleci/config.yml
  test/e2e/tests/custom-rpc-history.spec.js
  test/e2e/webdriver/chrome.js
  test/e2e/webdriver/firefox.js
Labels: team-accounts, INVALID-PR-TEMPLATE

#21718 Add metrics event handler for MMI transaction updates
  app/scripts/controllers/mmi-controller.js
  app/scripts/controllers/mmi-controller.test.js
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
Labels: team-confirmations-system

#21682 Include Snap name in permissions and add `allowedOrigins` permission caveat
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/permission-cell/permission-cell.js
  ui/components/app/snaps/snap-install-warning/snap-install-warning.js
  ui/helpers/utils/permission.js
Labels: team-snaps

#21752 MMI fix scope being passed to method
  app/scripts/metamask-controller.js
Labels: team-mmi

#21507 Adding Responsive styling to Page component
  ui/components/multichain/pages/all-connections/__snapshots__/all-connections.test.js.snap
  ui/components/multichain/pages/page/index.scss
  ui/components/multichain/pages/page/page.stories.tsx
  ui/components/multichain/pages/page/page.tsx
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21522 Request queue 2
  app/_locales/en/messages.json
  app/scripts/background.js
  app/scripts/controllers/preferences.js
  app/scripts/lib/backup.test.js
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/fixture-builder.js
  test/e2e/restore/MetaMaskUserData.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/pages/confirmation/components/confirmation-network-switch/confirmation-network-switch.js
  ui/pages/confirmation/components/confirmation-network-switch/confirmation-network-switch.stories.js
  ui/pages/confirmation/templates/switch-ethereum-chain.js
  ui/pages/confirmation/templates/switch-ethereum-chain.test.js
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.container.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
  ui/selectors/selectors.js
  ui/store/actions.ts
  yarn.lock
Labels: team-devex

#21743 fix recurring signature metric event until I confirm/cancel it
  ui/components/app/signature-request/signature-request.js
Labels: team-confirmations-secure-ux

#21649 Updating ppom validator
  app/scripts/lib/setupSentry.js
  package.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: team-confirmations-secure-ux, needs-dev-review

#21672 Remove MV3 specific account code in metamask-controller.js
  app/scripts/metamask-controller.js
Labels: team-extension-platform

#21726 [MMI] Updates custodian onboarding url
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/pages/institutional/custody/custody.js
  yarn.lock
Labels: team-mmi

#19957 Implement basic confirmation row components
  ui/components/app/confirm/shared/info/row/address.stories.tsx
  ui/components/app/confirm/shared/info/row/address.tsx
  ui/components/app/confirm/shared/info/row/hook.ts
  ui/components/app/confirm/shared/info/row/index.ts
  ui/components/app/confirm/shared/info/row/row.stories.tsx
  ui/components/app/confirm/shared/info/row/row.tsx
  ui/components/app/confirm/shared/info/row/value-double.stories.tsx
  ui/components/app/confirm/shared/info/row/value-double.tsx
Labels: team-snaps, INVALID-PR-TEMPLATE

#21027 Remove legacy transaction insight
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/json-rpc/eth_call.spec.js
  test/e2e/tests/metrics/mock-data.js
  test/e2e/tests/metrics/swaps.spec.js
  ui/components/app/app-components.scss
  ui/components/app/confirm-data/README.mdx
  ui/components/app/confirm-data/confirm-data.js
  ui/components/app/confirm-data/confirm-data.stories.js
  ui/components/app/confirm-data/confirm-data.test.js
  ui/components/app/confirm-data/index.js
  ui/components/app/confirm-data/index.scss
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/components/app/confirm-page-container/confirm-page-container.component.js
  ui/components/app/transaction-decoding/components/ui/accreditation/accrediation.component.stories.js
  ui/components/app/transaction-decoding/components/ui/accreditation/accreditation.component.js
  ui/components/app/transaction-decoding/components/ui/accreditation/index.js
  ui/components/app/transaction-decoding/constants.js
  ui/components/app/transaction-decoding/index.js
  ui/components/app/transaction-decoding/index.scss
  ui/components/app/transaction-decoding/transaction-decoding.component.js
  ui/components/app/transaction-decoding/transaction-decoding.util.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
  ui/pages/confirm-deploy-contract/confirm-deploy-contract.component.js
  ui/pages/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction/confirm-transaction.transaction.test.js
  yarn.lock
Labels: team-confirmations-secure-ux, team-snaps, INVALID-PR-TEMPLATE

#21727 Update network controller to use updated eth-json-rpc-middleware
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#21721 UX: Send Flow: Update button labels
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/send.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21746 UX: Better organize Multichain SCSS file imports
  ui/components/multichain/app-footer/index.scss
  ui/components/multichain/app-header/index.scss
  ui/components/multichain/asset-list-conversion-button/index.scss
  ui/components/multichain/import-tokens-modal/index.scss
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/nft-item/index.scss
  ui/components/multichain/product-tour-popover/index.scss
  ui/components/multichain/select-action-modal-item/index.scss
  ui/components/multichain/token-list-item/index.scss
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21775 Update Smart Swaps
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/logo/metamask-smart-transactions.png
  app/images/logo/smart-transactions-header.png
  app/scripts/lib/setupSentry.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/swaps.ts
  test/e2e/tests/errors.spec.js
  test/jest/mock-store.js
  ui/ducks/swaps/swaps.js
  ui/pages/swaps/build-quote/build-quote.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
  ui/pages/swaps/prepare-swap-page/smart-transactions-popover.stories.tsx
  ui/pages/swaps/prepare-swap-page/smart-transactions-popover.tsx
  ui/pages/swaps/slippage-buttons/slippage-buttons.js
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.js
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.test.js
  ui/pages/swaps/transaction-settings/transaction-settings.js
  yarn.lock
Labels: area-swaps, team-swaps, INVALID-PR-TEMPLATE, release-11.6.0

#21755 Remove identities associated to the hardware keyring when forgetting the device
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-accounts, QA Passed

#21785 Removing width styles from Page component in multichain folder
  ui/components/multichain/pages/page/index.scss
Labels: team-design-system

#21712 Update snap builder to use controller messenger
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/lib/snap-keyring/utils/isBlockedUrl.test.ts
  app/scripts/lib/snap-keyring/utils/isBlockedUrl.ts
  app/scripts/metamask-controller.js
Labels: team-accounts, needs-dev-review

#21774 Bump snaps packages
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  builds.yml
  package.json
  shared/constants/snaps/permissions.ts
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#21745 [MMI] show unsupported networks message in address tooltip
  ui/components/multichain/address-copy-button/address-copy-button.js
  ui/components/multichain/address-copy-button/address-copy-button.test.js
Labels: team-mmi

#21769 Cherrypicking 32b249a (#21710) into v11.5.0.
  app/_locales/en/messages.json
  shared/lib/ui-utils.js
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
Labels: team-confirmations-secure-ux-PR

#21777 [MMI] add missing mmi status in tx detail pane
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/app/transaction-status-label/transaction-status-label.js
  ui/components/app/transaction-status-label/transaction-status-label.test.js
  ui/pages/institutional/custody/custody.js
Labels: team-mmi

#21779 [MMI] Improves css styles in mmi view
  ui/components/institutional/institutional-components.scss
  ui/components/institutional/jwt-url-form/__snapshots__/jwt-url-form.test.js.snap
  ui/components/institutional/jwt-url-form/jwt-url-form.js
  ui/components/institutional/jwt-url-form/jwt-url-form.scss
  ui/pages/institutional/connect-custody/index.scss
  ui/pages/institutional/custody/custody.js
  ui/pages/pages.scss
Labels: team-mmi

#21789 e2e: temporary band-aid to flaky test in errors.spec.js
  .circleci/config.yml
  test/e2e/tests/errors.spec.js
Labels: team-accounts, INVALID-PR-TEMPLATE

#21796 fix: ERC721 name does not display when approving token
  ui/helpers/utils/token-util.js
  ui/helpers/utils/token-util.test.js
Labels: team-extension-UX

#21683 Update changelog v11.5.0
  CHANGELOG.md
Labels: team-extension-client, extension-delivery, INVALID-PR-TEMPLATE

#20477 Fix: Migrate TextField to TS
  ui/components/app/custom-spending-cap/custom-spending-cap.js
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.tsx
  ui/components/component-library/button-icon/button-icon.types.ts
  ui/components/component-library/form-text-field/form-text-field.js
  ui/components/component-library/icon/icon.stories.tsx
  ui/components/component-library/index.js
  ui/components/component-library/input/index.ts
  ui/components/component-library/label/README.mdx
  ui/components/component-library/label/label.stories.tsx
  ui/components/component-library/label/label.test.tsx
  ui/components/component-library/text-field-search/text-field-search.js
  ui/components/component-library/text-field-search/text-field-search.stories.js
  ui/components/component-library/text-field/README.mdx
  ui/components/component-library/text-field/__snapshots__/text-field.test.tsx.snap
  ui/components/component-library/text-field/deprecated/__snapshots__/text-field.test.js.snap
  ui/components/component-library/text-field/deprecated/index.js
  ui/components/component-library/text-field/deprecated/text-field.constants.js
  ui/components/component-library/text-field/deprecated/text-field.js
  ui/components/component-library/text-field/deprecated/text-field.test.js
  ui/components/component-library/text-field/index.ts
  ui/components/component-library/text-field/text-field.stories.tsx
  ui/components/component-library/text-field/text-field.test.tsx
  ui/components/component-library/text-field/text-field.tsx
  ui/components/component-library/text-field/text-field.types.ts
  ui/pages/keychains/reveal-seed.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
Labels: team-design-system, team-snaps, external-contributor, INVALID-PR-TEMPLATE

#21782 feat: Add SEK currency
  ui/helpers/constants/available-conversions.json
Labels: team-extension-UX, needs-ux-ds-review

#21815 Master sync following v11.5.0
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#21792 Add loading state for snap delineator
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/confirm-page-container/snaps/snap-insight.js
  ui/components/app/snaps/snap-delineator/snap-delineator.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/hooks/useTransactionInsights.js
  ui/pages/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
Labels: team-snaps, INVALID-PR-TEMPLATE

#21744 UX: Send Flow: Place Amount field in content
  ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
  ui/components/multichain/asset-picker-amount/index.js
  ui/components/multichain/asset-picker-amount/max-clear-button.tsx
  ui/components/multichain/index.js
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/content.tsx
  ui/components/multichain/pages/send/send.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21500 Revise warning copy when adding custom network with existing currency symbol
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/ui/form-field/form-field.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/settings/networks-tab/networks-form/networks-form.test.js
Labels: team-extension-UX, needs-ux-ds-review

#21825 Revert "Master sync following v11.5.0 (#21815)"
  CHANGELOG.md
  package.json
Labels: INVALID-PR-TEMPLATE

#21827 Master sync following v11.5.0
  CHANGELOG.md
  package.json
Labels: INVALID-PR-TEMPLATE

#21828 Revert "Master sync following v11.5.0 (#21827)"
  CHANGELOG.md
  package.json
Labels: INVALID-PR-TEMPLATE

#21748 Decouple MMI controller from transaction controller internals
  app/scripts/controllers/mmi-controller.js
  app/scripts/controllers/mmi-controller.test.js
  app/scripts/metamask-controller.js
Labels: team-confirmations-system

#21581 Snaps Home Page
  app/_locales/en/messages.json
  shared/constants/permissions.test.js
  shared/constants/snaps/permissions.ts
  ui/components/app/snaps/snap-home-page/snap-home-renderer.js
  ui/components/app/snaps/snap-home-page/useSnapHome.js
  ui/helpers/utils/permission.js
  ui/pages/snaps/snap-view/snap-home.js
  ui/pages/snaps/snap-view/snap-settings.js
  ui/pages/snaps/snap-view/snap-view.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#21835 Master sync follow v11.5.0
  CHANGELOG.md
  package.json
Labels: INVALID-PR-TEMPLATE

#21695 test:e2e: Add Blockaid e2e test - "set_approval_for_all_farming" UI warning
  test/e2e/tests/ppom-blockaid-setApprovalForAll-farming.spec.js
  test/mocks/json-rpc-result.ts
Labels: team-confirmations-secure-ux-PR

#21729 UX: Send Flow: Implement Tabbed Interface for Accounts + Contacts
  app/_locales/en/messages.json
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/address-book.tsx
  ui/components/multichain/pages/send/components/recipient.tsx
  ui/components/multichain/pages/send/components/your-accounts.tsx
  ui/components/multichain/pages/send/index.scss
  ui/components/ui/tabs/tab/tab.component.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21836 Enable snap lifecycle hooks and getLocale in stable
  shared/constants/permissions.test.js
  shared/constants/snaps/permissions.ts
  test/e2e/run-all.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#21549 bump `@metamask/assets-controllers` to `^18.0.0`
  .storybook/test-data.js
  app/scripts/background.js
  app/scripts/lib/getObjStructure.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/e2e/fixture-builder.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/jest/mock-store.js
  ui/components/app/asset-list/asset-list.buy-receive.test.js
  ui/components/app/asset-list/asset-list.test.js
  ui/components/app/confirm-page-container/confirm-detail-row/confirm-detail-row.component.test.js
  ui/components/app/currency-input/currency-input.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-fee-popover.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.test.js
  ui/components/app/modals/cancel-transaction/cancel-transaction-gas-fee/cancel-transaction-gas-fee.component.test.js
  ui/components/app/signature-request/signature-request.test.js
  ui/components/app/token-cell/token-cell.test.js
  ui/components/app/transaction-activity-log/transaction-activity-log.container.test.js
  ui/components/app/transaction-breakdown/transaction-breakdown.test.js
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.test.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/app/wallet-overview/token-overview.test.js
  ui/components/multichain/balance-overview/balance-overview.test.js
  ui/components/multichain/select-action-modal/select-action-modal.test.js
  ui/components/multichain/token-list-item/token-list-item.test.js
  ui/components/ui/new-network-info/new-network-info.test.js
  ui/components/ui/token-input/token-input.component.test.js
  ui/ducks/confirm-transaction/confirm-transaction.duck.test.js
  ui/ducks/metamask/metamask.js
  ui/ducks/metamask/metamask.test.js
  ui/hooks/useAccountTotalFiatBalance.test.js
  ui/pages/asset/asset.js
  ui/pages/confirm-signature-request/index.test.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/send/send.test.js
  ui/pages/settings/settings.container.js
  ui/pages/swaps/prepare-swap-page/view-quote-price-difference.test.js
  ui/pages/swaps/view-quote/view-quote-price-difference.test.js
  ui/pages/token-allowance/token-allowance.test.js
  ui/pages/token-details/token-details-page.test.js
  ui/selectors/confirm-transaction.js
  ui/selectors/confirm-transaction.test.js
  ui/selectors/selectors.js
  yarn.lock
Labels: team-devex

#21821 Bump snaps packages
  app/scripts/lib/SnapsNameProvider.ts
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/app.ts
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.stories.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.test.js
  ui/hooks/useTransactionInsights.js
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#21479 e2e: stabilize Ganache and failOnConsoleError
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.test.js
  development/lib/retry.js
  package.json
  test/e2e/ganache.ts
  test/e2e/helpers.js
  test/e2e/metamask-ui.spec.js
  test/e2e/run-e2e-test.js
  test/e2e/webdriver/driver.js
  ui/components/ui/toggle-button/toggle-button.component.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  yarn.lock
Labels: team-accounts, INVALID-PR-TEMPLATE

#21360 Changed CTA on snap grid from 'install' to 'details'
  ui/pages/keyring-snaps/new-snap-account-page/new-snap-account-page.tsx
  ui/pages/keyring-snaps/snap-card/__snapshots__/snap-card.test.tsx.snap
  ui/pages/keyring-snaps/snap-card/snap-card.stories.tsx
  ui/pages/keyring-snaps/snap-card/snap-card.test.tsx
  ui/pages/keyring-snaps/snap-card/snap-card.tsx
Labels: area-UI, area-snaps, team-accounts

#21848 Clear current STX error
  ui/ducks/swaps/swaps.js
  ui/ducks/swaps/swaps.test.js
Labels: area-swaps, team-swaps, INVALID-PR-TEMPLATE, release-11.6.0

#21432 add: mmi playwright e2e tests
  .circleci/config.yml
  .eslintrc.js
  .gitignore
  .prettierignore
  README.md
  package.json
  playwright.config.ts
  stylelint.config.js
  test/e2e/mmi/.env.example
  test/e2e/mmi/Dockerfile
  test/e2e/mmi/README.md
  test/e2e/mmi/custodian-hooks/ICustodianTestClient.ts
  test/e2e/mmi/custodian-hooks/hooks.ts
  test/e2e/mmi/helpers/custodian-helper.ts
  test/e2e/mmi/helpers/dapps-helpers.ts
  test/e2e/mmi/helpers/extension-loader.ts
  test/e2e/mmi/helpers/oauth-api-helper.ts
  test/e2e/mmi/helpers/saturn-api-helper.ts
  test/e2e/mmi/helpers/utils.ts
  test/e2e/mmi/pageObjects/mmi-accountMenu-page.ts
  test/e2e/mmi/pageObjects/mmi-auth0-page.ts
  test/e2e/mmi/pageObjects/mmi-dummyApp-page.ts
  test/e2e/mmi/pageObjects/mmi-extension-page.ts
  test/e2e/mmi/pageObjects/mmi-main-page.ts
  test/e2e/mmi/pageObjects/mmi-mainMenu-page.ts
  test/e2e/mmi/pageObjects/mmi-network-page.ts
  test/e2e/mmi/pageObjects/mmi-saturn-page.ts
  test/e2e/mmi/pageObjects/mmi-saturn-ui-page.ts
  test/e2e/mmi/pageObjects/mmi-signup-page.ts
  test/e2e/mmi/scripts/run-visual-test.sh
  test/e2e/mmi/specs/dapp.signature.spec.ts
  test/e2e/mmi/specs/dapp.spec.ts
  test/e2e/mmi/specs/extension.visual.spec.ts
  test/e2e/mmi/specs/extension.visual.spec.ts-snapshots/popop-token-remove-approve-chromium-linux.png
  test/e2e/mmi/specs/extension.visual.spec.ts-snapshots/token-replacement-notification-chromium-linux.png
  test/e2e/mmi/specs/navigation.spec.ts
  test/e2e/mmi/specs/transactions.spec.ts
  test/e2e/mmi/specs/visual.spec.ts
  test/e2e/mmi/specs/visual.spec.ts-snapshots/connect-custodian-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-account-selection-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-added-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-connection-info-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-list-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-remove-token-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-token-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custody-accounts-selection-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/mainWindow-custodian-selected-chromium-linux.png
  yarn.lock
Labels: team-mmi

#21637 Fix: Hide loading spinner when async transaction approval modal is present
  test/e2e/tests/swaps/swaps-notifications.spec.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/pages/swaps/prepare-swap-page/smart-transactions-popover.tsx
Labels: team-accounts

#21592 Send page components address book addresslistitem
  test/e2e/tests/address-book.spec.js
  ui/components/app/contact-list/recipient-group/recipient-group.component.js
  ui/components/component-library/avatar-base/avatar-base.types.ts
  ui/components/multichain/address-list-item/address-list-item.stories.tsx
  ui/components/multichain/address-list-item/address-list-item.test.tsx
  ui/components/multichain/address-list-item/address-list-item.tsx
  ui/components/multichain/address-list-item/index.scss
  ui/components/multichain/address-list-item/index.ts
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/pages/send/components/recipient.tsx
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21829 Fix #21716 - Fix alignment of NFT send button
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/nft-details.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21826 Update snaps E2E tests for test-snaps 2.2.2
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-get-locale.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
Labels: area-snaps, team-snaps, INVALID-PR-TEMPLATE

#18794 Deprecate u2f ledger live on chrome
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/migrations/066.test.js
  app/scripts/migrations/103.test.js
  app/scripts/migrations/103.ts
  app/scripts/migrations/index.js
  shared/constants/hardware-wallets.ts
  shared/notifications/index.js
  ui/components/app/ledger-instruction-field/ledger-instruction-field.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/ducks/metamask/metamask.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
  ui/selectors/selectors.js
Labels: DO-NOT-MERGE, team-accounts, needs-dev-review

#21857 Bump snaps packages
  builds.yml
  package.json
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#21854 Only call _loginUser if there is a password in env variables
  app/scripts/metamask-controller.js
Labels: team-extension-platform, QA Passed, INVALID-PR-TEMPLATE

#21863 chore: pass the password into method _loginUser
  app/scripts/metamask-controller.js
Labels: team-mmi

#21859 Version v11.5.1
  CHANGELOG.md
  app/scripts/metamask-controller.js
  package.json
Labels: INVALID-PR-TEMPLATE

#21875 fix screenshot
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-remove-token-chromium-linux.png
Labels: team-mmi

#21851 [MMI] prevent back button from showing when we are in popup view
  ui/pages/institutional/connect-custody/__snapshots__/account-list.test.js.snap
  ui/pages/institutional/connect-custody/account-list.js
  ui/pages/institutional/connect-custody/index.scss
  ui/pages/institutional/custody/custody.js
Labels: team-mmi

#21847 Nit: Row text color
  ui/components/app/confirm/shared/info/row/row.tsx
Labels: team-confirmations-secure-ux-PR, confirmation-redesign, INVALID-PR-TEMPLATE

#21853 add notion link
  ui/components/component-library/README.md
  ui/components/component-library/avatar-account/README.mdx
  ui/components/component-library/avatar-base/README.mdx
  ui/components/component-library/avatar-favicon/README.mdx
  ui/components/component-library/avatar-icon/README.mdx
  ui/components/component-library/avatar-network/README.mdx
  ui/components/component-library/avatar-token/README.mdx
  ui/components/component-library/badge-wrapper/README.mdx
  ui/components/component-library/banner-alert/README.mdx
  ui/components/component-library/banner-base/README.mdx
  ui/components/component-library/banner-tip/README.mdx
  ui/components/component-library/box/README.mdx
  ui/components/component-library/button-base/README.mdx
  ui/components/component-library/button-icon/README.mdx
  ui/components/component-library/button-link/README.mdx
  ui/components/component-library/button-primary/README.mdx
  ui/components/component-library/button-secondary/README.mdx
  ui/components/component-library/button/README.mdx
  ui/components/component-library/checkbox/README.mdx
  ui/components/component-library/form-text-field/README.mdx
  ui/components/component-library/header-base/README.mdx
  ui/components/component-library/help-text/README.mdx
  ui/components/component-library/icon/README.mdx
  ui/components/component-library/input/README.mdx
  ui/components/component-library/label/README.mdx
  ui/components/component-library/modal-content/README.mdx
  ui/components/component-library/modal-focus/README.mdx
  ui/components/component-library/modal-header/README.mdx
  ui/components/component-library/modal-overlay/README.mdx
  ui/components/component-library/modal/README.mdx
  ui/components/component-library/picker-network/README.mdx
  ui/components/component-library/popover-header/README.mdx
  ui/components/component-library/popover/README.mdx
  ui/components/component-library/tag-url/README.mdx
  ui/components/component-library/tag/README.mdx
  ui/components/component-library/text-field-search/README.mdx
  ui/components/component-library/text-field/README.mdx
  ui/components/component-library/text/README.mdx
Labels: area-documentation, team-design-system

#21833 UX: Housekeeping: Sort imports
  .eslintrc.js
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/account-details/account-details-key.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/account-list-menu.test.js
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/activity-list-item/activity-list-item.test.js
  ui/components/multichain/address-copy-button/address-copy-button.js
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/asset-list-conversion-button/asset-list-conversion-button.js
  ui/components/multichain/connected-site-menu/connected-site-menu.js
  ui/components/multichain/create-account/create-account.js
  ui/components/multichain/detected-token-banner/detected-token-banner.test.js
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/global-menu/global-menu.test.js
  ui/components/multichain/import-account/bottom-buttons.js
  ui/components/multichain/import-account/import-account.js
  ui/components/multichain/import-account/json.js
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
  ui/components/multichain/import-tokens-modal/import-tokens-modal.test.js
  ui/components/multichain/menu-items/account-details-menu-item.test.js
  ui/components/multichain/menu-items/view-explorer-menu-item.test.js
  ui/components/multichain/network-list-item/network-list-item.js
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.stories.js
  ui/components/multichain/pages/all-connections/all-connections.js
  ui/components/multichain/pages/send/send.js
  ui/components/multichain/product-tour-popover/product-tour-popover.js
  ui/components/multichain/token-list-item/token-list-item.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21844 UX: Send Flow: Use constants for contacts and accounts tabs
  ui/components/multichain/pages/send/components/recipient.tsx
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21886 update readme and improve local testing usability
  package.json
  playwright.config.ts
  test/e2e/mmi/.env.example
  test/e2e/mmi/Dockerfile
  test/e2e/mmi/README.md
  test/e2e/mmi/helpers/extension-loader.ts
  test/e2e/mmi/resources/circleci-artifact-screnshot.png
  test/e2e/mmi/resources/trace.png
  test/e2e/mmi/scripts/run-visual-test.sh
  test/e2e/mmi/specs/extension.visual.spec.ts-snapshots/popop-token-remove-approve-chromium-linux.png
  test/e2e/mmi/specs/extension.visual.spec.ts-snapshots/popop-token-remove-approve-mmi-visual-linux.png
  test/e2e/mmi/specs/extension.visual.spec.ts-snapshots/token-replacement-notification-chromium-linux.png
  test/e2e/mmi/specs/extension.visual.spec.ts-snapshots/token-replacement-notification-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/connect-custodian-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/connect-custodian-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-account-selection-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-added-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-connection-info-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-connection-info-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-list-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-list-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-remove-token-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-remove-token-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-token-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custody-accounts-selection-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custody-accounts-selection-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/mainWindow-custodian-selected-chromium-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/mainWindow-custodian-selected-mmi-visual-linux.png
Labels: team-mmi

#21706 [Snaps] E2E test improvements
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/snaps/test-snap-get-locale.spec.js
  test/e2e/snaps/test-snap-getentropy.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-lifecycle.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-networkaccess.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-wasm.spec.js
Labels: area-snaps, team-snaps

#21896 Ignore @metamask/snaps-ui deprecation
  .yarnrc.yml
Labels: team-shared-libraries, INVALID-PR-TEMPLATE

#21887 Enable Custom UI links
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  ui/components/app/snaps/snap-link-warning/index.js
  ui/components/app/snaps/snap-link-warning/snap-link-warning.js
  ui/components/app/snaps/snap-ui-markdown/index.scss
  ui/components/app/snaps/snap-ui-markdown/snap-ui-markdown.js
  ui/pages/notifications/index.scss
  ui/pages/notifications/notifications.js
Labels: team-snaps

#21858 Clear current STX error (#21848)
  ui/ducks/swaps/swaps.js
  ui/ducks/swaps/swaps.test.js
Labels: INVALID-PR-TEMPLATE, release-11.6.0

#21791 fix: 2 Duplicated Signature requests events are triggered for any signature
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request/signature-request.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#21908 Bump snaps packages
  builds.yml
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/snaps/enums.js
  ui/components/app/confirm/shared/info/row/row.tsx
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/components/app/snaps/snap-ui-markdown/snap-ui-markdown.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#19131 [FLASK] Add support for snaps domain resolution
  app/_locales/am/messages.json
  app/_locales/ar/messages.json
  app/_locales/bg/messages.json
  app/_locales/bn/messages.json
  app/_locales/ca/messages.json
  app/_locales/da/messages.json
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/et/messages.json
  app/_locales/fa/messages.json
  app/_locales/fi/messages.json
  app/_locales/fil/messages.json
  app/_locales/fr/messages.json
  app/_locales/he/messages.json
  app/_locales/hi/messages.json
  app/_locales/hr/messages.json
  app/_locales/hu/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/kn/messages.json
  app/_locales/ko/messages.json
  app/_locales/lt/messages.json
  app/_locales/lv/messages.json
  app/_locales/ms/messages.json
  app/_locales/no/messages.json
  app/_locales/ph/messages.json
  app/_locales/pl/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ro/messages.json
  app/_locales/ru/messages.json
  app/_locales/sk/messages.json
  app/_locales/sl/messages.json
  app/_locales/sr/messages.json
  app/_locales/sv/messages.json
  app/_locales/sw/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/uk/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  shared/constants/snaps/permissions.ts
  ui/ducks/domains.js
  ui/helpers/utils/permission.js
  ui/helpers/utils/util.js
  ui/pages/send/send-content/add-recipient/add-recipient.component.js
  ui/pages/send/send-content/add-recipient/add-recipient.container.js
  ui/pages/send/send-content/add-recipient/add-recipient.container.test.js
  ui/pages/send/send-content/add-recipient/add-recipient.stories.js
  ui/pages/send/send-content/add-recipient/domain-input.component.js
  ui/pages/send/send-content/add-recipient/domain-input.container.js
  ui/pages/send/send.constants.js
  ui/pages/send/send.scss
  ui/selectors/selectors.js
Labels: team-snaps

#21931 deps: @metamask/providers@^13.1.0->^14.0.2
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-security

#21936 Add snaps pages to path name map
  ui/helpers/constants/routes.ts
Labels: team-snaps, INVALID-PR-TEMPLATE

#21753 fix: After triggering a Transaction, a Signature request metrics event is also triggered
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/transaction-alerts/transaction-alerts.js
  ui/helpers/utils/metrics.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/token-allowance/token-allowance.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#21846 Update `Copyable` Component
  app/_locales/en/messages.json
  ui/components/app/app-components.scss
  ui/components/app/snaps/copyable/copyable.js
  ui/components/app/snaps/copyable/copyable.stories.js
  ui/components/app/snaps/copyable/copyable.test.js
  ui/components/app/snaps/copyable/index.scss
  ui/components/app/snaps/show-more/index.js
  ui/components/app/snaps/show-more/index.scss
  ui/components/app/snaps/show-more/show-more.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/hooks/snaps/useIsOverflowing.js
  ui/pages/snaps/snap-view/index.scss
  ui/pages/snaps/snap-view/snap-settings.js
Labels: team-snaps

#21942 Add more snaps pages to path name map
  ui/helpers/constants/routes.ts
Labels: team-snaps, INVALID-PR-TEMPLATE

#21902 UX: Updated Popular Networks List
  app/images/base.png
  app/images/zk-sync.svg
  shared/constants/network.ts
Labels: team-extension-UX, needs-ux-ds-review, INVALID-PR-TEMPLATE

#21939 Use `(acl.)execution.metamask.io` for Snaps execution environment and registry
  app/scripts/metamask-controller.js
  builds.yml
  privacy-snapshot.json
  test/env.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#21149 Update `@metamask/eth-ledger-bridge-keyring`
  app/scripts/lib/hardware-keyring-builder-factory.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-shared-libraries

#21842 UX: Send Flow: Show amount error with component
  ui/components/multichain/asset-picker-amount/asset-picker-amount.stories.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21935 Remove unnecessary redirection / code from Swaps, update content
  app/_locales/en/messages.json
  ui/pages/swaps/prepare-swap-page/review-quote.js
  ui/pages/swaps/prepare-swap-page/smart-transactions-popover.tsx
Labels: release-blocker, team-swaps, INVALID-PR-TEMPLATE, release-11.6.0

#21923 Change SwapsController onNetworkStateChange to networkDidChange
  app/scripts/metamask-controller.js
Labels: team-devex

#21946 Fix issue where per dapp selected network state is enabled without the request queue experimental toggle enabled
  app/scripts/metamask-controller.js
Labels: team-devex, INVALID-PR-TEMPLATE

#21945 Cherry pick: Remove unnecessary redirection / code from Swaps, update content
  app/_locales/en/messages.json
  ui/pages/swaps/prepare-swap-page/review-quote.js
  ui/pages/swaps/prepare-swap-page/smart-transactions-popover.tsx
Labels: INVALID-PR-TEMPLATE

#21773 Add manual Snap update feature from Snap View component
  .storybook/test-data.js
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/metamask-controller.js
  test/data/mock-state.json
  ui/components/app/snaps/snap-list-item/snap-list-item.js
  ui/components/app/snaps/snap-update-alert/index.js
  ui/components/app/snaps/snap-update-alert/snap-update-alert.js
  ui/components/app/snaps/snap-update-alert/snap-update-alert.stories.js
  ui/components/multichain/global-menu/global-menu.js
  ui/components/ui/menu/menu-item.js
  ui/pages/permissions-connect/snaps/snap-update/snap-update.js
  ui/pages/snaps/snap-view/index.scss
  ui/pages/snaps/snap-view/snap-settings.js
  ui/pages/snaps/snap-view/snap-view.js
  ui/pages/snaps/snaps-list/snap-list.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: team-snaps

#21951 Cherry pick: Fix issue where per dapp selected network state is enabl…
  app/scripts/metamask-controller.js
Labels: INVALID-PR-TEMPLATE

#21948 Added wallet_revokePermissions rpc method
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-devex, INVALID-PR-TEMPLATE

#21955 fix: 2 Duplicated Signature requests events are triggered for any signature
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request/signature-request.js
Labels: team-confirmations-secure-ux-PR

#21959 [MMI] Guard logic for MMI specific transaction metadata
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
Labels: team-mmi

#21889 Update smart swap test scenario
  test/scenarios/15. swap/smart swap.csv
  test/scenarios/15. swap/swap eth.csv
Labels: team-extension-client, team-extension-platform

#21985 fix: currency preferences toggle not displayed
  ui/pages/settings/settings-tab/settings-tab.container.js
  ui/pages/settings/settings-tab/settings-tab.test.js
Labels: team-extension-UX

#22038 Fix unit test in ConfirmTransactionBase component
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
Labels: team-confirmations-system

#21958 Update swaps controller ethereum provider on demand instead of on network events
  app/scripts/controllers/swaps.js
  app/scripts/controllers/swaps.test.js
  app/scripts/metamask-controller.js
Labels: team-extension-platform, QA Passed, INVALID-PR-TEMPLATE

#21943 [cherry-pick Confirmations Metrics PRs] fix: After triggering a Transaction, a Signature request metrics even…
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request/signature-request.js
  ui/components/app/transaction-alerts/transaction-alerts.js
  ui/helpers/utils/metrics.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/token-allowance/token-allowance.js
Labels: release-blocker, team-confirmations-secure-ux-PR, INVALID-PR-TEMPLATE, release-11.6.0

#21949 Version v11.5.2
  .yarnrc.yml
  CHANGELOG.md
  app/scripts/controllers/swaps.js
  app/scripts/controllers/swaps.test.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#22037 skip MMI e2e optional flaky tests
  test/e2e/mmi/specs/navigation.spec.ts
  test/e2e/mmi/specs/transactions.spec.ts
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-list-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-remove-token-mmi-visual-linux.png
Labels: team-mmi

#21911 Update changelog v11.6.0
  CHANGELOG.md
Labels: team-extension-client, extension-delivery, INVALID-PR-TEMPLATE

#21953 fix: Fix warning about missing strong random number source
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/browserify/policy-override.json
Labels: team-extension-platform
