Repository MetaMask/metamask-extension, pull requests merged in 2023-03, with the labels that each got.

#17950 fix keeping the wallet unlocked after service worker restarted more than once
  app/scripts/metamask-controller.js
Labels: type-bug, team-extension-client, team-extension-platform

#17855 fix(17855): persist popup when sw is restarted
  app/scripts/background.js
  app/scripts/controllers/app-state.js
  app/scripts/lib/notification-manager.js
  app/scripts/lib/notification-manager.test.ts
  app/scripts/metamask-controller.js
  jest.config.js
Labels: team-extension-client, team-extension-platform

#17916 UX: Icon: Restore missing back chevron in settings
  ui/pages/settings/index.scss
  ui/pages/settings/settings.component.js
Labels: type-bug

#17973 fix(17857): show correctly converted account balance in sign & encrypt
  test/data/mock-state.json
  test/e2e/tests/encrypt-decrypt.spec.js
  ui/components/app/signature-request-original/__snapshots__/signature-request-original.test.js.snap
  ui/components/app/signature-request/signature-request.component.js
  ui/components/app/signature-request/signature-request.container.js
  ui/pages/confirm-decrypt-message/confirm-decrypt-message.component.js
  ui/pages/confirm-decrypt-message/confirm-decrypt-message.container.js
  ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.component.js
  ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.container.js
  ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.stories.js
  ui/selectors/selectors.test.js
Labels: team-extension-client, team-extension-platform

#17749 feat(17494): beta build trigger in release branch and cleanup
  .circleci/config.yml
  .circleci/scripts/release-bump-manifest-version.sh
  .circleci/scripts/trigger-beta-build.sh
  .circleci/scripts/validate-changelog-in-rc.sh
  .circleci/scripts/validate-source-maps-beta.sh
  development/build/utils.js
  development/lib/get-version.js
  development/metamaskbot-build-announce.js
Labels: team-extension-client, team-extension-platform

#17942 Add e2e test view erc1155 details
  test/e2e/nft/view-erc1155-details.spec.js
Labels: team-extension-client, team-extension-platform

#17763 Upgrading the Import Account modal
  app/_locales/en/messages.json
  app/scripts/account-import-strategies/index.js
  app/scripts/lib/account-tracker.test.js
  test/e2e/tests/add-account.spec.js
  test/e2e/tests/from-import-ui.spec.js
  ui/components/app/asset-list-item/asset-list-item.js
  ui/components/component-library/form-text-field/form-text-field.js
  ui/components/component-library/help-text/help-text.js
  ui/components/component-library/index.js
  ui/components/component-library/text/index.js
  ui/components/component-library/text/text.constants.js
  ui/helpers/utils/accounts.js
  ui/pages/create-account/create-account.component.js
  ui/pages/create-account/import-account/bottom-buttons.js
  ui/pages/create-account/import-account/bottom-buttons.stories.js
  ui/pages/create-account/import-account/import-account.js
  ui/pages/create-account/import-account/import-account.stories.js
  ui/pages/create-account/import-account/index.js
  ui/pages/create-account/import-account/index.scss
  ui/pages/create-account/import-account/json.js
  ui/pages/create-account/import-account/json.stories.js
  ui/pages/create-account/import-account/private-key.js
  ui/pages/create-account/import-account/private-key.stories.js
  ui/pages/create-account/index.scss
  ui/pages/create-account/new-account.stories.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-key-management

#17939 Fixing FormTextField test
  ui/components/component-library/text-field/text-field.test.js
Labels: type-bug, area-UI, design-system

#17999 fix(17716): increase threshold to include all options for nonce search
  ui/pages/settings/settings-search/settings-search.js
Labels: team-extension-client, team-extension-platform

#18050 [E2E] remove extraneous arg from clickElement
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-confirm.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-error.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-update.spec.js
Labels: team-extension-client, team-extension-platform

#18011 fix(17542): fix fiat currency display in few txn actions
  test/e2e/tests/encrypt-decrypt.spec.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request-original/signature-request-original.container.js
  ui/components/app/signature-request/__snapshots__/signature-request.component.test.js.snap
  ui/components/app/signature-request/signature-request.component.js
  ui/components/app/signature-request/signature-request.component.test.js
  ui/components/app/signature-request/signature-request.container.js
  ui/components/app/signature-request/signature-request.container.test.js
  ui/pages/confirm-decrypt-message/__snapshots__/confirm-decrypt-message.component.test.js.snap
  ui/pages/confirm-decrypt-message/confirm-decrypt-message.component.js
  ui/pages/confirm-decrypt-message/confirm-decrypt-message.component.test.js
  ui/pages/confirm-decrypt-message/confirm-decrypt-message.container.js
  ui/pages/confirm-encryption-public-key/__snapshots__/confirm-encryption-public-key.component.test.js.snap
  ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.component.js
  ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.component.test.js
  ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.container.js
  ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.stories.js
  ui/pages/confirm-signature-request/__snapshots__/index.test.js.snap
Labels: team-extension-client, team-extension-platform

#18036 increment keyring controller version
  package.json
  yarn.lock
Labels: team-extension-client, team-extension-platform

#18009 Adding types file to Box component
  .storybook/main.js
  tsconfig.json
  ui/components/ui/box/box.d.ts
  ui/components/ui/typography/README.mdx
  ui/components/ui/typography/typography.stories.js
  yarn.lock
Labels: area-UI, design-system, stability

#17891 Use tokenList to get token details, when available, in getTokenStanda…
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  coverage-targets.js
  shared/lib/token-util.ts
  ui/components/app/confirm-page-container/confirm-page-container.component.js
  ui/pages/swaps/build-quote/build-quote.js
  ui/pages/swaps/build-quote/build-quote.test.js
  ui/pages/swaps/swaps.util.ts
Labels: team-extension-client, team-extension-platform

#18053 Version v10.26.0 lavamoat patches
  .yarn/patches/@lavamoat-snow-npm-1.4.1-405a48e593.patch
  .yarn/patches/lavamoat-core-npm-12.4.0-cecca1a9b5.patch
  .yarn/patches/lavamoat-core-npm-14.0.0-0f5bdac846.patch
  app/scripts/use-snow.js
  development/build/index.js
  package.json
  yarn.lock
Labels: team-extension-client, team-extension-platform

#17851 Updating AvatarWithBadge to BadgeWrapper
  ui/components/component-library/avatar-with-badge/README.mdx
  ui/components/component-library/avatar-with-badge/__snapshots__/avatar-with-badge.test.js.snap
  ui/components/component-library/avatar-with-badge/avatar-with-badge.constants.js
  ui/components/component-library/avatar-with-badge/avatar-with-badge.js
  ui/components/component-library/avatar-with-badge/avatar-with-badge.scss
  ui/components/component-library/avatar-with-badge/avatar-with-badge.stories.js
  ui/components/component-library/avatar-with-badge/avatar-with-badge.test.js
  ui/components/component-library/avatar-with-badge/index.js
  ui/components/component-library/badge-wrapper/README.mdx
  ui/components/component-library/badge-wrapper/__snapshots__/badge-wrapper.test.tsx.snap
  ui/components/component-library/badge-wrapper/badge-wrapper.scss
  ui/components/component-library/badge-wrapper/badge-wrapper.stories.tsx
  ui/components/component-library/badge-wrapper/badge-wrapper.test.tsx
  ui/components/component-library/badge-wrapper/badge-wrapper.tsx
  ui/components/component-library/badge-wrapper/badge-wrapper.types.ts
  ui/components/component-library/badge-wrapper/index.ts
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/index.js
Labels: area-UI, design-system, IA/NAV

#17822 Extract out confirm-data and confirm-hex-data components from confirm-transaction-base.component.js
  test/e2e/metamask-ui.spec.js
  test/lib/render-helpers.js
  ui/components/app/app-components.scss
  ui/components/app/confirm-data/README.mdx
  ui/components/app/confirm-data/confirm-data.js
  ui/components/app/confirm-data/confirm-data.stories.js
  ui/components/app/confirm-data/confirm-data.test.js
  ui/components/app/confirm-data/index.js
  ui/components/app/confirm-data/index.scss
  ui/components/app/confirm-hexdata/README.mdx
  ui/components/app/confirm-hexdata/confirm-hexdata.js
  ui/components/app/confirm-hexdata/confirm-hexdata.stories.js
  ui/components/app/confirm-hexdata/confirm-hexdata.test.js
  ui/components/app/confirm-hexdata/index.js
  ui/components/app/confirm-page-container/confirm-page-container-content/index.scss
  ui/hooks/useTransactionFunctionType.js
  ui/hooks/useTransactionFunctionType.test.js
  ui/pages/confirm-deploy-contract/confirm-deploy-contract.component.js
  ui/pages/confirm-send-ether/confirm-send-ether.component.js
  ui/pages/confirm-send-ether/confirm-send-ether.container.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: team-confirmations-PR

#17877 UX Icon: Updated Icon for Disclosure
  ui/components/ui/disclosure/disclosure.js
  ui/components/ui/disclosure/disclosure.scss
Labels: design-system, team-extension-client, team-extension-UX

#17694 [FLASK] Add WebAssembly endowment
  app/_locales/en/messages.json
  ui/helpers/utils/permission.js
Labels: flask

#18047 Add e2e tests approval for all for erc1155 token
  test/e2e/nft/erc1155-interaction.spec.js
  test/e2e/nft/erc721-intercation.spec.js
  test/e2e/tests/erc1155.spec.js
Labels: team-extension-client, team-extension-platform

#17727 Updating AvatarAccount objects to enums
  ui/components/component-library/avatar-account/README.mdx
  ui/components/component-library/avatar-account/avatar-account.constants.js
  ui/components/component-library/avatar-account/avatar-account.js
  ui/components/component-library/avatar-account/avatar-account.stories.js
  ui/components/component-library/avatar-account/avatar-account.test.js
  ui/components/component-library/avatar-account/avatar-account.types.ts
  ui/components/component-library/avatar-account/index.js
  ui/components/component-library/index.js
  ui/components/component-library/text-field/text-field.stories.js
Labels: design-system

#18107 Use deployed contracts in fixtures
  test/e2e/fixture-builder.js
  test/e2e/fixture-server.js
  test/e2e/helpers.js
  test/e2e/nft/erc1155-interaction.spec.js
  test/e2e/nft/remove-erc1155.spec.js
  test/e2e/nft/remove-nft.spec.js
  test/e2e/nft/send-nft.spec.js
  test/e2e/nft/view-erc1155-details.spec.js
  test/e2e/nft/view-nft-details.spec.js
  test/e2e/tests/send-eth.spec.js
Labels: team-extension-client, team-extension-platform

#18120 Update chromedriver v111
  .circleci/scripts/chrome-install.sh
  package.json
  yarn.lock
Labels: team-extension-client, team-extension-platform

#18123 UX: Icon: Update buy icon
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/token-overview.js
Labels: team-extension-UX

#17401 NFTs: Remove feature flag for release
  .circleci/config.yml
  .metamaskrc.dist
  app/scripts/metamask-controller.js
  development/build/config.js
  development/build/scripts.js
  package.json
  ui/components/app/wallet-overview/token-overview.js
  ui/components/app/wallet-overview/token-overview.test.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/home/home.component.js
  ui/pages/import-token/import-token.component.js
  ui/pages/import-token/import-token.test.js
  ui/pages/routes/routes.component.js
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/security-tab/security-tab.test.js
Labels: area-NFTs, team-extension-UX

#17935 Convert LoadingScreen into Functional Component and use React.memo
  ui/components/ui/loading-screen/index.scss
  ui/components/ui/loading-screen/loading-screen.component.js
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR

#18141 Master sync for v10.26.1
  CHANGELOG.md
  package.json
Labels: team-extension-client, team-extension-platform

#18055 Move nft e2e tests to main e2e test job
  package.json
  test/e2e/nft/nft.spec.js
  test/e2e/run-all.js
Labels: area-NFTs, team-extension-client, team-extension-platform

#18165 Bump coverage targets to fix develop build
  coverage-targets.js
Labels: team-extension-client, team-extension-platform

#18090 [FLASK] Snaps e2e test stability improvements
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-error.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-update.spec.js
Labels: flask

#18169 [FLASK] Fix overflow issues with text coming from snap UI
  ui/components/app/flask/snap-ui-markdown/snap-ui-markdown.js
  ui/components/app/flask/snap-ui-renderer/snap-ui-renderer.js
Labels: flask

#18160 Box types update
  ui/components/component-library/avatar-base/avatar-base.js
  ui/components/component-library/avatar-favicon/avatar-favicon.js
  ui/components/component-library/avatar-icon/avatar-icon.js
  ui/components/component-library/avatar-network/avatar-network.js
  ui/components/component-library/avatar-token/avatar-token.js
  ui/components/component-library/badge-wrapper/badge-wrapper.stories.tsx
  ui/components/component-library/badge-wrapper/badge-wrapper.types.ts
  ui/components/ui/box/README.mdx
  ui/components/ui/box/box.d.ts
  ui/components/ui/box/box.stories.tsx
  ui/components/ui/box/box.test.tsx
  ui/components/ui/card/README.mdx
  ui/components/ui/card/card.js
  ui/components/ui/card/card.stories.js
  ui/helpers/constants/design-system.ts
Labels: design-system, stability

#18142 [FLASK] `snaps-monorepo@0.31.0`
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-error.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  ui/components/app/flask/install-error/index.js
  ui/components/app/flask/install-error/install-error.js
  ui/components/app/flask/snap-install-warning/snap-install-warning.js
  ui/components/app/flask/snaps-authorship-pill/snaps-authorship-pill.js
  ui/helpers/constants/routes.ts
  ui/helpers/utils/permission.js
  ui/helpers/utils/util.js
  ui/pages/permissions-connect/flask/snap-install/index.scss
  ui/pages/permissions-connect/flask/snap-install/snap-install.js
  ui/pages/permissions-connect/flask/snap-result/index.js
  ui/pages/permissions-connect/flask/snap-result/index.scss
  ui/pages/permissions-connect/flask/snap-result/snap-result.js
  ui/pages/permissions-connect/flask/snap-update/index.scss
  ui/pages/permissions-connect/flask/snap-update/snap-update.js
  ui/pages/permissions-connect/flask/util.js
  ui/pages/permissions-connect/index.scss
  ui/pages/permissions-connect/permissions-connect.component.js
  ui/pages/permissions-connect/permissions-connect.container.js
  ui/selectors/permissions.js
  ui/store/actions.ts
  yarn.lock
Labels: flask

#18203 AvatarBase font-size logic
  ui/components/component-library/avatar-account/__snapshots__/avatar-account.test.js.snap
  ui/components/component-library/avatar-base/README.mdx
  ui/components/component-library/avatar-base/__snapshots__/avatar-base.test.js.snap
  ui/components/component-library/avatar-base/avatar-base.js
  ui/components/component-library/avatar-base/avatar-base.scss
  ui/components/component-library/avatar-base/avatar-base.stories.js
  ui/components/component-library/avatar-base/avatar-base.test.js
  ui/components/component-library/avatar-favicon/__snapshots__/avatar-favicon.test.js.snap
  ui/components/component-library/avatar-icon/__snapshots__/avatar-icon.test.js.snap
  ui/components/component-library/avatar-icon/avatar-icon.test.js
  ui/components/component-library/avatar-network/README.mdx
  ui/components/component-library/avatar-network/__snapshots__/avatar-network.test.js.snap
  ui/components/component-library/avatar-network/avatar-network.stories.js
  ui/components/component-library/avatar-network/avatar-network.test.js
  ui/components/component-library/avatar-token/README.mdx
  ui/components/component-library/avatar-token/__snapshots__/avatar-token.test.js.snap
  ui/components/component-library/avatar-token/avatar-token.stories.js
  ui/components/component-library/avatar-token/avatar-token.test.js
  ui/components/component-library/picker-network/__snapshots__/picker-network.test.js.snap
  ui/components/component-library/tag-url/__snapshots__/tag-url.test.js.snap
Labels: area-UI, design-system, IA/NAV

#18200 Sign in with Ethereum: re-enable warning UI for mismatched domains / disable domain binding
  app/scripts/lib/personal-message-manager.js
  app/scripts/lib/personal-message-manager.test.js
  ui/components/app/signature-request-siwe/index.scss
  ui/components/app/signature-request-siwe/signature-request-siwe.js
Labels: Extension QA Board, team-confirmations-secure-ux-PR

#18225 Ignoring all storybook files from coverage check
  test/merge-coverage.js
Labels: design-system

#17685 [FLASK] Add tooltips to show info about a permission
  app/_locales/en/messages.json
  app/images/icons/ethereum.svg
  coverage-targets.js
  ui/components/app/flask/update-snap-permission-list/index.scss
  ui/components/app/flask/update-snap-permission-list/update-snap-permission-list.js
  ui/components/app/permissions-connect-permission-list/index.scss
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
  ui/helpers/utils/permission.js
Labels: flask

#18231 Updating jest config to ignore all stories files including js and tsx
  jest.config.js
Labels: design-system

#18116 Part of 17670: Replaced Typography with Text component in welcome.js and edit-gas-display.component.js
  ui/components/app/edit-gas-display/edit-gas-display.component.js
  ui/pages/onboarding-flow/welcome/welcome.js
Labels: design-system

#17947 UX: Multichain: Account Menu List
  .metamaskrc.dist
  .storybook/test-data.js
  app/_locales/en/messages.json
  development/build/config.js
  development/build/scripts.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.stories.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.test.js
  ui/components/multichain/account-list-item-menu/index.js
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.stories.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/account-list-item/index.js
  ui/components/multichain/account-list-item/index.scss
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/account-list-menu.stories.js
  ui/components/multichain/account-list-menu/account-list-menu.test.js
  ui/components/multichain/account-list-menu/index.js
  ui/components/multichain/account-list-menu/index.scss
  ui/components/multichain/index.js
  ui/components/multichain/index.scss
  ui/components/ui/menu/menu-item.js
  ui/components/ui/popover/index.scss
  ui/components/ui/popover/popover.component.js
  ui/css/index.scss
  ui/helpers/constants/design-system.ts
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/selectors/permissions.js
Labels: team-extension-client, team-extension-UX

#18020 Extracting out sub title component from confirm-transaction-base
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-summary/confirm-page-container-summary.component.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-summary/index.scss
  ui/components/app/confirm-page-container/confirm-page-container.component.js
  ui/components/app/confirm-subtitle/README.mdx
  ui/components/app/confirm-subtitle/confirm-subtitle.js
  ui/components/app/confirm-subtitle/confirm-subtitle.stories.js
  ui/components/app/confirm-subtitle/confirm-subtitle.test.js
  ui/components/app/confirm-subtitle/index.js
  ui/hooks/useTransactionInfo.js
  ui/hooks/useTransactionInfo.test.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
Labels: team-confirmations-secure-ux-PR

#18278 bump contract metadata package version
  package.json
  yarn.lock
Labels: team-extension-client, team-extension-platform

#18175 Adding ModalContent component
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/index.js
  ui/components/component-library/modal-content/README.mdx
  ui/components/component-library/modal-content/__snapshots__/modal-content.test.tsx.snap
  ui/components/component-library/modal-content/index.ts
  ui/components/component-library/modal-content/modal-content.scss
  ui/components/component-library/modal-content/modal-content.stories.tsx
  ui/components/component-library/modal-content/modal-content.test.tsx
  ui/components/component-library/modal-content/modal-content.tsx
  ui/components/component-library/modal-content/modal-content.types.ts
Labels: area-UI, design-system, IA/NAV

#17859 UX: Multichain: Added TokenList Component
  ui/components/app/asset-list/asset-list.js
  ui/components/app/token-cell/token-cell.js
  ui/components/multichain/detected-token-banner/__snapshots__/detected-token-banner.test.js.snap
  ui/components/multichain/detected-token-banner/detected-token-banner.js
  ui/components/multichain/detected-token-banner/detected-token-banner.stories.js
  ui/components/multichain/detected-token-banner/detected-token-banner.test.js
  ui/components/multichain/detected-token-banner/index.js
  ui/components/multichain/index.js
  ui/components/multichain/index.scss
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/multichain-import-token-link/__snapshots__/multichain-import-token-link.test.js.snap
  ui/components/multichain/multichain-import-token-link/index.js
  ui/components/multichain/multichain-import-token-link/multichain-import-token-link.js
  ui/components/multichain/multichain-import-token-link/multichain-import-token-link.stories.js
  ui/components/multichain/multichain-import-token-link/multichain-import-token-link.test.js
  ui/components/multichain/multichain-token-list-item/__snapshots__/multichain-token-list-item.test.js.snap
  ui/components/multichain/multichain-token-list-item/index.js
  ui/components/multichain/multichain-token-list-item/multichain-token-list-item.js
  ui/components/multichain/multichain-token-list-item/multichain-token-list-item.scss
  ui/components/multichain/multichain-token-list-item/multichain-token-list-item.stories.js
  ui/components/multichain/multichain-token-list-item/multichain-token-list-item.test.js
  ui/components/ui/tooltip/index.scss
  ui/css/index.scss
Labels: team-extension-client, team-extension-UX

#18247 Fix overflowing UI & buttons in Signature Request screens
  ui/components/app/signature-request-original/index.scss
  ui/components/ui/page-container/index.scss
Labels: area-signTypedData, area-signatures, team-confirmations-secure-ux-PR

#18161 Adding ModalOverlay component
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/index.js
  ui/components/component-library/modal-overlay/README.mdx
  ui/components/component-library/modal-overlay/__snapshots__/modal-overlay.test.tsx.snap
  ui/components/component-library/modal-overlay/index.ts
  ui/components/component-library/modal-overlay/modal-overlay.scss
  ui/components/component-library/modal-overlay/modal-overlay.stories.tsx
  ui/components/component-library/modal-overlay/modal-overlay.test.tsx
  ui/components/component-library/modal-overlay/modal-overlay.tsx
  ui/components/component-library/modal-overlay/modal-overlay.types.ts
Labels: area-UI, design-system, IA/NAV

#18299 [FLASK] Update iframe-execution-environment
  app/scripts/metamask-controller.js
Labels: flask

#17991 Extracting out title component from confirm-transaction-base
  test/e2e/metamask-ui.spec.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-summary/confirm-page-container-summary.component.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-summary/index.scss
  ui/components/app/confirm-page-container/confirm-page-container.component.js
  ui/components/app/confirm-subtitle/README.mdx
  ui/components/app/confirm-subtitle/confirm-subtitle.js
  ui/components/app/confirm-subtitle/confirm-subtitle.stories.js
  ui/components/app/confirm-subtitle/confirm-subtitle.test.js
  ui/components/app/confirm-subtitle/index.js
  ui/components/app/confirm-title/README.mdx
  ui/components/app/confirm-title/confirm-title.js
  ui/components/app/confirm-title/confirm-title.stories.js
  ui/components/app/confirm-title/confirm-title.test.js
  ui/components/app/confirm-title/index.js
  ui/hooks/useTransactionInfo.js
  ui/hooks/useTransactionInfo.test.js
  ui/pages/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
Labels: team-confirmations-secure-ux-PR

#18262 [FLASK] Update snap authorship component
  ui/components/app/app-components.scss
  ui/components/app/flask/snap-authorship/index.js
  ui/components/app/flask/snap-authorship/snap-authorship.js
  ui/components/app/flask/snap-authorship/snap-authorship.stories.js
  ui/components/app/flask/snap-avatar/index.js
  ui/components/app/flask/snap-avatar/snap-avatar.js
  ui/components/app/flask/snap-avatar/snap-avatar.stories.js
  ui/components/app/flask/snaps-authorship-pill/index.js
  ui/components/app/flask/snaps-authorship-pill/index.scss
  ui/components/app/flask/snaps-authorship-pill/snaps-authorship-pill.js
  ui/components/app/permissions-connect-header/permissions-connect-header.component.js
  ui/helpers/utils/util.js
  ui/pages/permissions-connect/flask/snap-install/snap-install.js
  ui/pages/permissions-connect/flask/snap-result/snap-result.js
  ui/pages/permissions-connect/flask/snap-update/snap-update.js
  ui/pages/settings/flask/view-snap/view-snap.js
Labels: flask

#18064 Remove isEIP1559Account usage
  ui/selectors/selectors.js
Labels: team-extension-client, team-extension-UX

#18008 Fix Sign-in With Ethereum (SIWE) metametric, add tests, and clean RPC method middleware event logic
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  shared/constants/metametrics.js
Labels: type-bug, area-transactions, team-confirmations-secure-ux-PR

#18336 Revert "fix(18190): add tabs to permission when initializing app"
  app/manifest/v2/_base.json
  app/manifest/v2/chrome.json
  app/manifest/v2/firefox.json
  app/manifest/v3/_base.json
  app/manifest/v3/chrome.json
  app/manifest/v3/firefox.json
Labels: team-extension-client, team-extension-platform

#18370 Fix aria label error on the console
  ui/components/app/account-menu/__snapshots__/account-menu.test.js.snap
  ui/components/ui/box/box.js
Labels: team-extension-client, team-extension-platform

#18371 [FLASK] `snaps-monorepo@0.32.2`
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-update.spec.js
  yarn.lock
Labels: flask

#18346 Introduce action metrics for mv3 service worker restart
  app/scripts/background.js
  app/scripts/controllers/app-state.js
  app/scripts/metamask-controller.js
  package.json
  shared/constants/metametrics.js
  shared/constants/test-flags.js
  test/e2e/fixture-builder.js
  test/e2e/mv3/dapp-interactions.spec.js
  test/e2e/webdriver/driver.js
  ui/store/action-queue/index.test.js
  ui/store/action-queue/index.ts
Labels: team-extension-client, team-extension-platform
