Repository MetaMask/metamask-extension, pull requests merged in 2023-02, with the labels that each got.

#17451 Fix RPC Url editing issue of existing network
  ui/pages/settings/networks-tab/networks-form/networks-form.js
Labels: team-extension-client

#17380 Refactor conf-tx.js
  ui/hooks/useRouting.js
  ui/pages/confirm-transaction/__snapshots__/conf-tx.test.js.snap
  ui/pages/confirm-transaction/conf-tx.js
  ui/pages/confirm-transaction/conf-tx.test.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-confirmations-PR

#17484 Refactoring confirm-transaction-base component
  ui/components/app/confirm-page-container/confirm-page-container.component.js
  ui/components/ui/currency-display/currency-display.component.js
  ui/hooks/useTransactionInsights.js
  ui/pages/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
Labels: team-confirmations-PR

#17478 fix button text props
  ui/components/component-library/button-link/README.mdx
  ui/components/component-library/button-link/button-link.js
  ui/components/component-library/button-link/button-link.stories.js
Labels: area-UI, design-system

#17514 Fixing/extending type definitions for later usage
  app/scripts/controllers/app-state.js
  app/scripts/controllers/transactions/index.js
  app/scripts/lib/buy-url.ts
  shared/constants/app.ts
  shared/constants/gas.ts
  shared/constants/metametrics.js
Labels: team-extension-client

#17499 prefer locale slice for locale state
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/ducks/metamask/metamask.js
  ui/ducks/metamask/metamask.test.js
  ui/pages/onboarding-flow/onboarding-app-header/onboarding-app-header.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.js
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.test.js
Labels: team-extension-client

#17326 🐛 Calldata validation
  app/scripts/controllers/transactions/lib/util.js
  app/scripts/controllers/transactions/lib/util.test.js
  coverage-targets.js
Labels: release-blocker, team-extension-client, team-extension-platform

#17437 Display a warning and gas fee component for token allowance and NFT flow when transaction is expected to fail
  ui/components/app/approve-content-card/approve-content-card.js
  ui/components/app/transaction-alerts/transaction-alerts.js
  ui/components/ui/simulation-error-message/index.js
  ui/components/ui/simulation-error-message/simulation-error-message.js
  ui/components/ui/simulation-error-message/simulation-error-message.test.js
  ui/hooks/useSimulationFailureWarning.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.test.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.stories.js
  ui/pages/confirm-approve/confirm-approve.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/token-allowance/token-allowance.js
Labels: release-blocker

#17325 Fixing yarn version command, adding yarn version plugin
  .circleci/scripts/release-bump-manifest-version.sh
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarnrc.yml
  coverage-targets.js
  nyc.config.js
Labels: team-extension-client

#17442 Convert ui/store/actionConstants.js -> Typescript
  ui/store/actionConstants.ts
Labels: team-extension-client

#17536 NFTs: Remove nft toaster on first autohide
  ui/pages/home/home.component.js
Labels: area-NFTs, team-extension-client, team-extension-UX

#17408 Move confirm-transaction/conf-tx.js to confirm-signature-request
  development/ts-migration-dashboard/files-to-convert.json
  ui/pages/confirm-signature-request/__snapshots__/index.test.js.snap
  ui/pages/confirm-signature-request/index.js
  ui/pages/confirm-signature-request/index.test.js
  ui/pages/confirm-transaction/confirm-transaction.component.js
Labels: team-confirmations-PR

#17456 Detailed document for refactoring signature request pages in extension
  docs/refactoring/signature-request/README.md
  docs/refactoring/signature-request/eth_sign.png
  docs/refactoring/signature-request/footer.png
  docs/refactoring/signature-request/header.png
  docs/refactoring/signature-request/personal_sign.png
  docs/refactoring/signature-request/signature_request_old.png
  docs/refactoring/signature-request/signature_request_proposed.png
  docs/refactoring/signature-request/siwe.png
  docs/refactoring/signature-request/v1.png
  docs/refactoring/signature-request/v3.png
  docs/refactoring/signature-request/v4.png
Labels: team-confirmations-PR

#17470 GasDisplay: fix z-index for Confirm Approve warning
  ui/pages/send/gas-display/index.scss
Labels: area-gas, team-confirmations-PR

#17501 Allow background to handle forgotten password flow
  app/scripts/metamask-controller.js
  ui/ducks/app/app.js
  ui/ducks/app/app.test.js
  ui/pages/home/home.container.js
  ui/pages/unlock-page/unlock-page.container.js
  ui/store/actionConstants.ts
  ui/store/actions.js
  ui/store/actions.test.js
Labels: team-extension-client

#17306 Updating nft autodetection toggle text, css fix
  app/_locales/en/messages.json
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/index.scss
Labels: area-NFTs, team-extension-UX

#17351 updated CollectibleDetail Storybook Coverage
  app/_locales/en/messages.json
  ui/components/app/collectible-details/collectible-details.js
  ui/components/app/collectible-details/collectible-details.stories.js
  ui/components/app/collectible-details/index.scss
Labels: area-NFTs, design-system, team-extension-UX

#17349 Convert confirm-tx.utils.js to typescript
  package.json
  shared/constants/transaction.ts
  ui/helpers/utils/confirm-tx.util.ts
  yarn.lock
Labels: team-extension-client

#17543 Add e2e test: import nft
  test/e2e/nft/import-nft.spec.js
Labels: Extension QA Board, team-extension-client, team-extension-platform

#17509 Convert action-queue to TypeScript
  ui/store/action-queue/index.ts
Labels: team-extension-client

#17511 Add error module for safely handling errors
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/policy-override.json
  lavamoat/build-system/policy-override.json
  shared/modules/error.test.ts
  shared/modules/error.ts
Labels: team-extension-client

#17512 Dead and redundant code removal
  development/states/navigate-txs.json
  ui/components/app/account-menu/account-menu.component.js
  ui/components/app/account-menu/account-menu.container.js
  ui/components/app/account-menu/account-menu.test.js
  ui/ducks/app/app.js
  ui/ducks/app/app.test.js
  ui/ducks/metamask/metamask.js
  ui/ducks/metamask/metamask.test.js
  ui/store/actionConstants.test.js
  ui/store/actionConstants.ts
  ui/store/actions.js
  ui/store/actions.test.js
Labels: team-extension-client

#17547 Fix speed up of 0 max priority fee transactions
  ui/hooks/gasFeeInput/useTransactionFunction.test.js
  ui/hooks/gasFeeInput/useTransactionFunctions.js
Labels: release-blocker

#17454 feature: convert ui/ducks/app/app.ts to typescript
  ui/ducks/app/app.ts
  ui/store/actions.js
Labels: team-extension-client

#17559 Fix display of 0 priority fee in advanced gas edit input
  ui/hooks/gasFeeInput/useMaxPriorityFeePerGasInput.js
  ui/hooks/gasFeeInput/useMaxPriorityFeePerGasInput.test.js
Labels: release-blocker

#17443 Disable fiat conversion in Approve Screen when `Show balance and token price checker` is OFF
  ui/components/app/approve-content-card/approve-content-card.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.test.js
  ui/pages/confirm-approve/confirm-approve.js
  ui/pages/token-allowance/token-allowance.js
Labels: type-bug, privacy

#17446 Convert actions.js to typescript
  development/states/navigate-txs.json
  package.json
  types/global.d.ts
  ui/components/app/gas-timing/gas-timing.component.test.js
  ui/components/app/import-token-link/import-token-link.test.js
  ui/components/app/modals/account-details-modal/account-details-modal.test.js
  ui/components/app/modals/cancel-transaction/cancel-transaction.component.test.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.test.js
  ui/ducks/app/app.test.js
  ui/ducks/app/app.ts
  ui/ducks/locale/locale.js
  ui/ducks/metamask/metamask.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/ducks/swaps/swaps.test.js
  ui/helpers/utils/tx-helper.ts
  ui/pages/keychains/reveal-seed.test.js
  ui/pages/permissions-connect/permissions-connect.component.js
  ui/pages/permissions-connect/permissions-connect.container.js
  ui/pages/send/send-footer/send-footer.test.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/pages/settings/security-tab/security-tab.test.js
  ui/pages/settings/settings-tab/settings-tab.test.js
  ui/pages/unlock-page/unlock-page.test.js
  ui/store/actionConstants.ts
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: team-extension-client

#17569 updated assets and phishing controller packages
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: team-extension-client, team-extension-platform

#17525 [FLASK] Create E2E test for RPC endowment
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-rpc.spec.js
Labels: flask

#17612 Adding docs for layout and spacing for Icon component
  ui/components/component-library/icon/README.mdx
  ui/components/component-library/icon/icon.stories.js
Labels: design-system

#17638 Add e2e test: send nft
  test/e2e/nft/import-nft.spec.js
  test/e2e/nft/send-nft.spec.js
Labels: Extension QA Board, team-extension-client, team-extension-platform

#17473 Refactor ConfirmTransaction to Functional Component
  test/data/mock-state.json
  ui/components/app/signature-request-original/__snapshots__/signature-request-original.test.js.snap
  ui/components/app/signature-request/__snapshots__/signature-request.component.test.js.snap
  ui/pages/confirm-transaction/__snapshots__/confirm-transaction.test.js.snap
  ui/pages/confirm-transaction/confirm-transaction.component.js
  ui/pages/confirm-transaction/confirm-transaction.container.js
  ui/pages/confirm-transaction/confirm-transaction.test.js
  ui/pages/confirm-transaction/index.js
Labels: area-transactions, team-confirmations-PR

#17660 [FLASK] Sort permissions based on weight
  ui/components/app/flask/update-snap-permission-list/update-snap-permission-list.js
  ui/components/app/flask/update-snap-permission-list/update-snap-permission-list.stories.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.stories.js
  ui/helpers/utils/permission.js
Labels: area-snaps, flask, team-snaps

#17535 E2e test insights
  .circleci/config.yml
  package.json
  test/e2e/run-e2e-test.js
  yarn.lock
Labels: team-extension-client, team-extension-platform

#17658 converted collectibles files to nfts
  development/ts-migration-dashboard/files-to-convert.json
  test/e2e/tests/nfts.spec.js
  ui/components/app/app-components.scss
  ui/components/app/collectible-default-image/index.js
  ui/components/app/collectibles-detection-notice/index.js
  ui/components/app/collectibles-items/index.js
  ui/components/app/collectibles-tab/index.js
  ui/components/app/nft-default-image/__snapshots__/nft-default-image.test.js.snap
  ui/components/app/nft-default-image/index.js
  ui/components/app/nft-default-image/index.scss
  ui/components/app/nft-default-image/nft-default-image.js
  ui/components/app/nft-default-image/nft-default-image.stories.js
  ui/components/app/nft-default-image/nft-default-image.test.js
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/index.scss
  ui/components/app/nft-details/nft-details.js
  ui/components/app/nft-details/nft-details.stories.js
  ui/components/app/nft-details/nft-details.test.js
  ui/components/app/nft-options/index.scss
  ui/components/app/nft-options/nft-options.js
  ui/components/app/nft-options/nft-options.test.js
  ui/components/app/nfts-detection-notice/index.js
  ui/components/app/nfts-detection-notice/index.scss
  ui/components/app/nfts-detection-notice/nfts-detection-notice.js
  ui/components/app/nfts-items/index.js
  ui/components/app/nfts-items/index.scss
  ui/components/app/nfts-items/nfts-items.js
  ui/components/app/nfts-items/nfts-items.test.js
  ui/components/app/nfts-tab/index.js
  ui/components/app/nfts-tab/index.scss
  ui/components/app/nfts-tab/nfts-tab.js
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/components/ui/nft-collection-image/nft-collection-image.js
  ui/helpers/utils/nfts.js
  ui/helpers/utils/nfts.test.js
  ui/hooks/useNftsCollections.js
  ui/pages/add-collectible/index.js
  ui/pages/add-nft/add-nft.js
  ui/pages/add-nft/add-nft.test.js
  ui/pages/add-nft/index.js
  ui/pages/add-nft/index.scss
  ui/pages/asset/asset.js
  ui/pages/home/home.component.js
  ui/pages/pages.scss
  ui/pages/routes/routes.component.js
Labels: area-NFTs, team-extension-client, team-extension-UX

#16616 Sign-in with Ethereum Domain Binding
  app/scripts/lib/personal-message-manager.js
  app/scripts/lib/personal-message-manager.test.js
Labels: team-confirmations

#17411 Add testing documentation
  .github/workflows/fitness-functions.yml
  .husky/pre-commit
  README.md
  development/fitness-functions/check-mocha-syntax.js
  development/fitness-functions/index.js
  development/fitness-functions/shared.js
  development/fitness-functions/shared.test.js
  docs/testing.md
  jest.config.js
  package.json
  yarn.lock
Labels: area-documentation, team-extension-client, team-extension-platform

#17674 Removing TEXT_VARIANTS in favour of TextVariant
  docs/design-system.md
  ui/components/component-library/index.js
  ui/components/component-library/text/README.mdx
  ui/components/component-library/text/index.js
  ui/components/component-library/text/text.constants.js
  ui/components/component-library/text/text.js
Labels: area-documentation, area-UI, design-system

#17458 Ensure simulation failure warning is shown on all networks and accounts
  test/e2e/tests/failing-contract.spec.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: team-extension-client, team-extension-platform

#17659 Updated messages/strings to replace Collectibles with NFTs
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/nft/import-nft.spec.js
  ui/ducks/app/app.ts
  ui/helpers/constants/settings.js
  ui/pages/add-nft/add-nft.js
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/import-token/import-token.component.js
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: area-NFTs, team-extension-client, team-extension-UX

#17712 Fix mocha syntax fitness function
  .github/workflows/fitness-functions.yml
  coverage-targets.js
  development/fitness-functions/check-mocha-syntax.js
  development/fitness-functions/shared.js
  development/fitness-functions/shared.test.js
Labels: team-extension-client, team-extension-platform

#17684 feat(17494): add generate-beta-commit
  development/generate-beta-commit.js
  package.json
Labels: team-extension-client, team-extension-platform

#17546 Clean ConfirmTranscationPage component
  ui/pages/confirm-transaction/confirm-transaction.component.js
Labels: team-confirmations-PR

#17704 Fixing prop type errors in components and tests
  ui/components/component-library/avatar-favicon/avatar-favicon.test.js
  ui/components/component-library/help-text/help-text.test.js
  ui/components/component-library/picker-network/picker-network.test.js
  ui/components/component-library/tag-url/tag-url.js
Labels: area-UI, design-system

#14219 Additional incoming transactions support
  app/scripts/controllers/incoming-transactions.js
  app/scripts/controllers/incoming-transactions.test.js
  shared/constants/network.ts
Labels: Extension QA Board, team-confirmations, area-activity

#17709 Chromedriver v110
  .circleci/scripts/chrome-install.sh
  package.json
  yarn.lock
Labels: team-extension-client, team-extension-platform

#17720 UX: Icons: Use proper send icon on wallet and token overview pages
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/token-overview.js
Labels: release-blocker

#17732 Updating TextField component
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/form-text-field/README.mdx
  ui/components/component-library/form-text-field/__snapshots__/form-text-field.test.js.snap
  ui/components/component-library/form-text-field/form-text-field.js
  ui/components/component-library/form-text-field/form-text-field.stories.js
  ui/components/component-library/form-text-field/form-text-field.test.js
  ui/components/component-library/icon/icon.stories.js
  ui/components/component-library/index.js
  ui/components/component-library/label/README.mdx
  ui/components/component-library/label/label.test.js
  ui/components/component-library/text-field-base/__snapshots__/text-field-base.test.js.snap
  ui/components/component-library/text-field-base/index.js
  ui/components/component-library/text-field-base/text-field-base.constants.js
  ui/components/component-library/text-field-base/text-field-base.js
  ui/components/component-library/text-field-base/text-field-base.stories.js
  ui/components/component-library/text-field-base/text-field-base.test.js
  ui/components/component-library/text-field-search/README.mdx
  ui/components/component-library/text-field-search/__snapshots__/text-field-search.test.js.snap
  ui/components/component-library/text-field-search/text-field-search.js
  ui/components/component-library/text-field-search/text-field-search.stories.js
  ui/components/component-library/text-field-search/text-field-search.test.js
  ui/components/component-library/text-field/README.mdx
  ui/components/component-library/text-field/__snapshots__/text-field.test.js.snap
  ui/components/component-library/text-field/text-field.constants.js
  ui/components/component-library/text-field/text-field.js
  ui/components/component-library/text-field/text-field.scss
  ui/components/component-library/text-field/text-field.stories.js
  ui/components/component-library/text-field/text-field.test.js
Labels: area-UI, design-system, IA/NAV

#17705 Update HelpText component
  ui/components/component-library/form-text-field/form-text-field.js
  ui/components/component-library/help-text/README.mdx
  ui/components/component-library/help-text/__snapshots__/help-text.test.js.snap
  ui/components/component-library/help-text/help-text.js
  ui/components/component-library/help-text/help-text.stories.js
  ui/components/component-library/help-text/help-text.test.js
  ui/pages/keychains/reveal-seed.js
Labels: area-UI, design-system, IA/NAV

#17784 fix: fix url for flask build
  development/metamaskbot-build-announce.js
Labels: team-extension-client, team-extension-platform

#17753 Part of 17670: Replace Typography with Text approve-content-card
  ui/components/app/approve-content-card/approve-content-card.js
Labels: design-system

#17804 Cleanup: clearTimeout on useEffect for gas estimation and prevent state update on unmounted ConfirmTransactionBase
  ui/hooks/useShouldAnimateGasEstimations.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: area-transactions, area-gas, team-confirmations, team-confirmations-PR

#17796 Update Firefox binary in ci
  .circleci/scripts/firefox-install.sh
Labels: team-extension-client, team-extension-platform

#17683 Add desktop support
  app/scripts/background.js
  app/scripts/lib/rpc-method-middleware/handlers/desktop/enable-desktop.js
  app/scripts/lib/rpc-method-middleware/handlers/index.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  app/scripts/platforms/extension.js
  development/build/config.js
  development/build/scripts.js
  package.json
  shared/constants/app.ts
  test/e2e/run-e2e-test.js
  yarn.lock
Labels: team-extension-client, team-extension-platform

#17742 Adding details document about confirmation pages frontend refactoring
  docs/refactoring/README.md
  docs/refactoring/confirmation-pages-routing/README.md
  docs/refactoring/confirmation-pages-routing/current.png
  docs/refactoring/confirmation-pages-routing/proposed.png
Labels: team-confirmations-PR

#17664 Adding Input component and updating TextFieldBase
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/form-text-field/__snapshots__/form-text-field.test.js.snap
  ui/components/component-library/index.js
  ui/components/component-library/input/README.mdx
  ui/components/component-library/input/__snapshots__/input.test.js.snap
  ui/components/component-library/input/index.js
  ui/components/component-library/input/input.constants.js
  ui/components/component-library/input/input.js
  ui/components/component-library/input/input.scss
  ui/components/component-library/input/input.stories.js
  ui/components/component-library/input/input.test.js
  ui/components/component-library/text-field-base/README.mdx
  ui/components/component-library/text-field-search/__snapshots__/text-field-search.test.js.snap
  ui/components/component-library/text-field/__snapshots__/text-field.test.js.snap
  ui/components/component-library/text-field/text-field.js
  ui/components/component-library/text-field/text-field.scss
  ui/components/component-library/text/text.js
  ui/pages/keychains/__snapshots__/reveal-seed.test.js.snap
Labels: area-UI, design-system, IA/NAV

#17823 Add e2e test sign in with ethereum
  test/e2e/tests/signin-with-ethereum.spec.js
Labels: Extension QA Board, team-extension-client, team-extension-platform

#17854 always process e2e test results
  .circleci/config.yml
Labels: team-extension-client, team-extension-platform

#16648 Add .vscode settings to the repo
  .gitignore
  .prettierignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: team-key-management

#17828 UX Icon: updated fas-question icon
  ui/components/app/custom-spending-cap/custom-spending-cap-tooltip.js
  ui/components/ui/form-field/form-field.js
  ui/components/ui/form-field/form-field.stories.js
  ui/components/ui/form-field/index.scss
  ui/components/ui/new-network-info/index.scss
  ui/components/ui/new-network-info/new-network-info.js
  ui/components/ui/new-network-info/new-network-info.test.js
  ui/components/ui/review-spending-cap/review-spending-cap.js
Labels: team-extension-client, team-extension-UX

#17797 Fixed PropType error on IconButton
  ui/components/ui/icon-button/icon-button.js
Labels: design-system, team-extension-client, team-extension-UX

#17710 Capture all Error console.log events
  test/e2e/helpers.js
  test/e2e/metamask-ui.spec.js
  test/e2e/mv3-perf-stats/init-load-stats.js
  test/e2e/webdriver/driver.js
Labels: team-extension-client, team-extension-platform

#17835 Update the PhishingController to v2 and update phishing warning page
  app/scripts/contentscript.js
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  app/scripts/migrations/080.test.js
  app/scripts/migrations/080.ts
  app/scripts/migrations/index.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  shared/constants/phishing.js
  test/e2e/mock-e2e.js
  test/e2e/tests/phishing-detection.spec.js
  yarn.lock
Labels: Extension QA Board, team-extension-client, team-extension-platform

#17838 Fix state in confirm transaction
  test/e2e/fixture-builder.js
  test/e2e/tests/multiple-transactions.spec.js
  test/e2e/tests/navigate-transactions.spec.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction/confirm-transaction.component.js
Labels: team-confirmations-PR

#17808 Fix GetEncryptionKey TypeError Cannot destructure property 'msgParams' of 'txData'
  ui/pages/confirm-decrypt-message/confirm-decrypt-message.component.js
  ui/pages/confirm-decrypt-message/confirm-decrypt-message.container.js
  ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.component.js
  ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.container.js
Labels: area-transactions, Extension QA Board, team-confirmations-PR

#17422 Transaction-list-item-details pop up to display the correct token information on token approve item
  test/data/transaction-data.json
  test/e2e/tests/custom-token-add-approve.spec.js
  test/e2e/tests/nfts.spec.js
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
  ui/hooks/useTransactionDisplayData.js
  ui/hooks/useTransactionDisplayData.test.js
Labels: type-bug, Sev2-normal

#17365 [FLASK] Create E2E test for cronjobs
  test/e2e/snaps/test-snap-cronjob.spec.js
Labels: flask

#17923 Add unhappypath test case for importing ERC1155
  test/e2e/nft/import-erc1155.spec.js
  test/e2e/run-all.js
Labels: team-extension-client, team-extension-platform

#17925 Add e2e test remove erc1155 token
  test/e2e/nft/remove-erc1155.spec.js
Labels: team-extension-client, team-extension-platform
