Repository MetaMask/metamask-extension, pull requests merged in 2023-06, with the labels that each got.

#19179 Deep clone signature tx in order to avoid state mutation bug on dev
  ui/pages/confirm-signature-request/index.js
Labels: area-UI, PS-team

#19208 Clean ConfirmTransaction page related code
  ui/components/app/confirm-page-container/confirm-page-container-navigation/confirm-page-container-navigation.component.js
  ui/helpers/utils/tx-helper.test.js
  ui/helpers/utils/tx-helper.ts
  ui/pages/confirm-transaction/confirm-transaction.component.js
Labels: team-confirmations-secure-ux-PR

#19275 ConfirmTxPage: rm redundant unapprovedTxs const
  ui/pages/confirm-transaction/confirm-transaction.component.js
Labels: area-transactions, team-confirmations-secure-ux-PR

#19409 SignatureController: accept approval request first
  .yarn/patches/@metamask-signature-controller-npm-2.0.0-f441f2596e.patch
  package.json
  yarn.lock
Labels: release-10.32.0

#19397 feature(17901): fix flaky tests in send-eth e2e
  test/e2e/tests/send-eth.spec.js
Labels: team-extension-client, team-extension-platform

#19029 Multichain NFT network badges
  ui/components/app/nft-default-image/__snapshots__/nft-default-image.test.js.snap
  ui/components/app/nft-default-image/index.scss
  ui/components/app/nft-default-image/nft-default-image.js
  ui/components/app/nft-default-image/nft-default-image.stories.js
  ui/components/app/nft-default-image/nft-default-image.test.js
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/index.scss
  ui/components/app/nft-details/nft-details.js
  ui/components/app/nfts-items/index.scss
  ui/components/app/nfts-items/nfts-items.js
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/nft-item/index.js
  ui/components/multichain/nft-item/nft-item.js
  ui/components/multichain/nft-item/nft-item.scss
  ui/components/multichain/nft-item/nft-item.stories.js
  ui/components/multichain/nft-item/nft-item.test.js
Labels: area-UI, PS-team, needs-ux-ds-review

#19395 UX: Multichain: Make MetaFox logo more accessible
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/ui/metafox-logo/__snapshots__/metafox-logo.component.test.js.snap
  ui/components/ui/metafox-logo/metafox-logo.component.js
  ui/pages/onboarding-flow/onboarding-app-header/__snapshots__/onboarding-app-header.test.js.snap
Labels: needs-ux-ds-review

#19416 Remove MULTICHAIN flag for NFT badges
  test/e2e/nft/import-erc1155.spec.js
  test/e2e/nft/import-nft.spec.js
  test/e2e/nft/remove-erc1155.spec.js
  test/e2e/nft/remove-nft.spec.js
  test/e2e/nft/send-nft.spec.js
  test/e2e/nft/view-erc1155-details.spec.js
  test/e2e/nft/view-nft-details.spec.js
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/nft-details.js
  ui/components/app/nft-details/nft-details.test.js
  ui/components/app/nfts-items/nfts-items.js
Labels: needs-ux-ds-review

#19377 [FLASK] `snaps@0.34.0-flask.1`
  app/scripts/controllers/permissions/snaps/snap-permissions.js
  app/scripts/controllers/permissions/snaps/snap-permissions.test.js
  app/scripts/controllers/permissions/specifications.js
  app/scripts/controllers/permissions/specifications.test.js
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.test.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  shared/constants/permissions.test.js
  yarn.lock
Labels: flask

#19372 feature(17901): fix import UI error against MV3 Build
  test/e2e/tests/from-import-ui.spec.js
Labels: team-extension-client, team-extension-platform

#19359 Component-Library storybook introduction fix
  ui/components/component-library/COMPONENT-LIBARY.stories.mdx
  ui/components/component-library/COMPONENT-LIBRARY.stories.mdx
  ui/components/component-library/README.md
Labels: design-system

#19414 UX Multichain: Update settings title
  ui/pages/settings/contact-list-tab/index.scss
  ui/pages/settings/index.scss
Labels: team-extension-UX, needs-ux-ds-review

#19447 Part of #18714: Replacing deprecated constants in `add-network` folder
  ui/components/app/add-network/add-network.js
Labels: design-system

#19448 Part of #18714: Replacing deprecated constants in `approve-content-card` folder
  ui/components/app/approve-content-card/approve-content-card.js
Labels: design-system

#19449 [FLASK] Limit notification count display to 99+
  ui/components/multichain/global-menu/global-menu.js
Labels: flask

#19198 UX: Multichain: Restore Flask support link and text
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/global-menu/global-menu.test.js
Labels: needs-ux-ds-review

#19442 [FLASK] Rework Snaps headers and footers
  app/_locales/en/messages.json
  test/data/mock-state.json
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-networkaccess.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  ui/components/app/permissions-connect-header/permissions-connect-header.component.js
  ui/components/app/snaps/snap-authorship-expanded/index.js
  ui/components/app/snaps/snap-authorship-expanded/snap-authorship-expanded.js
  ui/components/app/snaps/snap-authorship-header/index.js
  ui/components/app/snaps/snap-authorship-header/snap-authorship-header.js
  ui/components/app/snaps/snap-authorship-header/snap-authorship-header.stories.js
  ui/components/app/snaps/snap-authorship/index.js
  ui/components/app/snaps/snap-authorship/snap-authorship.stories.js
  ui/components/app/snaps/snap-avatar/snap-avatar.js
  ui/components/app/snaps/snap-delineator/snap-delineator.js
  ui/hooks/useScrollRequired.js
  ui/pages/confirmation/components/confirmation-footer/confirmation-footer.js
  ui/pages/confirmation/confirmation.js
  ui/pages/confirmation/templates/snaps/snap-alert/snap-alert.js
  ui/pages/confirmation/templates/snaps/snap-confirmation/snap-confirmation.js
  ui/pages/confirmation/templates/snaps/snap-prompt/snap-prompt.js
  ui/pages/permissions-connect/permissions-connect.component.js
  ui/pages/permissions-connect/permissions-connect.container.js
  ui/pages/permissions-connect/snaps/snap-install/index.scss
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
  ui/pages/permissions-connect/snaps/snap-install/snap-install.stories.js
  ui/pages/permissions-connect/snaps/snap-result/index.scss
  ui/pages/permissions-connect/snaps/snap-result/snap-result.js
  ui/pages/permissions-connect/snaps/snap-result/snap-result.stories.js
  ui/pages/permissions-connect/snaps/snap-update/index.scss
  ui/pages/permissions-connect/snaps/snap-update/snap-update.js
  ui/pages/permissions-connect/snaps/snap-update/snap-update.stories.js
  ui/pages/settings/snaps/view-snap/view-snap.js
  ui/pages/settings/snaps/view-snap/view-snap.test.js
Labels: flask

#19088 When gas fees suggested by dapp is too high, show warning color and icon
  app/_locales/en/messages.json
  shared/constants/gas.ts
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.js
  ui/components/app/gas-details-item/gas-details-item.js
  ui/components/app/gas-details-item/gas-details-item.test.js
  ui/helpers/constants/gas.js
  ui/hooks/gasFeeInput/useGasFeeInputs.js
Labels: area-UI, team-confirmations-secure-ux-PR, QA Passed

#18103 Added the ability to navigate multiple SIWE notifications
  ui/components/app/signature-request-siwe/__snapshots__/signature-request-siwe.test.js.snap
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request-siwe/signature-request-siwe.test.js
  ui/components/app/signature-request/signature-request.container.test.js
Labels: team-confirmations-secure-ux-PR, QA Passed

#19499 issue-18714: Replaced deprecated constants with enum in EthSignModal and HoldToRevealModal Component
  ui/components/app/modals/eth-sign-modal/eth-sign-modal.js
  ui/components/app/modals/hold-to-reveal-modal/hold-to-reveal-modal.js
  ui/components/app/modals/hold-to-reveal-modal/hold-to-reveal-modal.stories.js
Labels: design-system

#19462 feat(17901): fix network, add-account and mv3 phishing warning issue
  test/e2e/helpers.js
  test/e2e/mv3/phishing-warning-sw-restart.spec.js
  test/e2e/tests/add-account.spec.js
  test/e2e/tests/network-error.spec.js
  test/e2e/tests/send-eth.spec.js
Labels: team-extension-client, team-extension-platform

#19513 update icons with AvatarNetwork for add-network
  ui/components/app/add-network/add-network.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#19363 Adding `Box` component in TS to component-library
  ui/components/component-library/box/README.mdx
  ui/components/component-library/box/box.scss
  ui/components/component-library/box/box.stories.tsx
  ui/components/component-library/box/box.test.tsx
  ui/components/component-library/box/box.tsx
  ui/components/component-library/box/box.types.ts
  ui/components/component-library/box/index.ts
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/index.js
Labels: design-system, stability, needs-ux-ds-review

#19531 feature(19463): fix send-eth flaky test and refactor
  test/e2e/helpers.js
  test/e2e/tests/address-book.spec.js
  test/e2e/tests/from-import-ui.spec.js
  test/e2e/tests/network-error.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/send-hex-address.spec.js
  test/e2e/tests/simple-send.spec.js
Labels: team-extension-client, team-extension-platform

#19547 [FLASK] Align update error state with Figma
  app/_locales/en/messages.json
  ui/pages/permissions-connect/snaps/snap-update/snap-update.js
Labels: flask

#19514 UX Multichain: Updated header to use picker network in popup view
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/app-header.scss
Labels: team-extension-UX, needs-ux-ds-review

#19578 [FLASK] Bump RateLimitController to v3
  app/scripts/metamask-controller.js
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  package.json
  yarn.lock
Labels: flask

#19571 Updating BorderColor enum to prevent proptype error
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/account-picker/account-picker.test.js
  ui/helpers/constants/design-system.ts
Labels: design-system, needs-ux-ds-review

#19575 UX Multichain: updated enums for multichain token list item
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/multichain/multichain-token-list-item/__snapshots__/multichain-token-list-item.test.js.snap
  ui/components/multichain/multichain-token-list-item/multichain-token-list-item.js
Labels: team-extension-UX, needs-ux-ds-review

#19574 UX Multichain: UI fixes for settings page
  ui/pages/settings/index.scss
  ui/pages/settings/settings.component.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#19593 UX Multichain: updated components with Multichain Prefix
  ui/components/app/asset-list/asset-list.js
  ui/components/app/connected-status-indicator/connected-status-indicator.js
  ui/components/app/token-cell/token-cell.js
  ui/components/multichain/connected-site-menu/__snapshots__/connected-site-menu.test.js.snap
  ui/components/multichain/connected-site-menu/connected-site-menu.js
  ui/components/multichain/connected-site-menu/connected-site-menu.stories.js
  ui/components/multichain/connected-site-menu/connected-site-menu.test.js
  ui/components/multichain/connected-site-menu/index.js
  ui/components/multichain/connected-site-menu/index.scss
  ui/components/multichain/import-token-link/__snapshots__/import-token-link.test.js.snap
  ui/components/multichain/import-token-link/import-token-link.js
  ui/components/multichain/import-token-link/import-token-link.stories.js
  ui/components/multichain/import-token-link/import-token-link.test.js
  ui/components/multichain/import-token-link/index.js
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/multichain-connected-site-menu/index.js
  ui/components/multichain/multichain-import-token-link/index.js
  ui/components/multichain/multichain-import-token-link/multichain-import-token-link.stories.js
  ui/components/multichain/multichain-token-list-item/index.js
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/index.js
  ui/components/multichain/token-list-item/token-list-item.js
  ui/components/multichain/token-list-item/token-list-item.scss
  ui/components/multichain/token-list-item/token-list-item.stories.js
  ui/components/multichain/token-list-item/token-list-item.test.js
  ui/pages/routes/routes.component.js
Labels: team-extension-UX, needs-ux-ds-review

#19178 devDeps: degenerator@3.0.1->3.0.4
  yarn.lock
Labels: type-security, area-buildSystem, dependencies

#19556 Deprecate old Popover and Modals
  ui/components/app/modal/modal.component.js
  ui/components/app/modals/modal.js
  ui/components/ui/popover/popover.component.js
  ui/components/ui/popover/popover.stories.js
Labels: design-system, needs-ux-ds-review

#19522 Fix #19439 - Allow Account Picker during Send flow
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/app-header.test.js
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/global-menu/global-menu.test.js
  ui/components/ui/menu/menu-item.js
  ui/components/ui/menu/menu.stories.js
  ui/pages/routes/routes.component.test.js
Labels: needs-ux-ds-review

#19600 feature(19496): eliminate flow e2e flakyness in terms of asserting content for DOM
  test/e2e/tests/import-flow.spec.js
Labels: team-extension-client, team-extension-platform

#19606 feature(19493): eliminate e2e flakyness for eth-sign
  test/e2e/helpers.js
  test/e2e/tests/eth-sign.spec.js
Labels: team-extension-client, team-extension-platform

#19454 Extend `wallet_watchAsset` to support `ERC721` and `ERC1155` tokens
  .storybook/initial-states/approval-screens/add-suggested-token.js
  app/_locales/en/messages.json
  app/scripts/lib/rpc-method-middleware/handlers/watch-asset.js
  app/scripts/metamask-controller.js
  package.json
  test/e2e/fixture-builder.js
  test/e2e/nft/erc721-interaction.spec.js
  test/e2e/nft/import-nft.spec.js
  test/e2e/nft/send-nft.spec.js
  test/e2e/nft/view-nft-details.spec.js
  test/e2e/seeder/ganache-seeder.js
  test/e2e/seeder/smart-contracts.js
  ui/components/app/nft-default-image/nft-default-image.js
  ui/helpers/constants/routes.ts
  ui/helpers/utils/util.js
  ui/pages/confirm-add-suggested-nft/confirm-add-suggested-nft.js
  ui/pages/confirm-add-suggested-nft/confirm-add-suggested-nft.stories.js
  ui/pages/confirm-add-suggested-nft/confirm-add-suggested-nft.test.js
  ui/pages/confirm-add-suggested-nft/index.js
  ui/pages/confirm-add-suggested-nft/index.scss
  ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.js
  ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.stories.js
  ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.test.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.test.js
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/pages.scss
  ui/pages/routes/routes.component.js
  ui/pages/send/send-content/send-asset-row/send-asset-row.test.js
  ui/selectors/approvals.ts
  ui/selectors/permissions.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  yarn.lock
Labels: needs-ux-ds-review

#19620 Fix #19619 - Submit the account creation form when pressing enter
  ui/components/multichain/create-account/create-account.js
Labels: needs-ux-ds-review

#19618 Updated contacts Title and copy changes in Send Flow
  app/_locales/am/messages.json
  app/_locales/ar/messages.json
  app/_locales/bg/messages.json
  app/_locales/bn/messages.json
  app/_locales/ca/messages.json
  app/_locales/cs/messages.json
  app/_locales/da/messages.json
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/et/messages.json
  app/_locales/fa/messages.json
  app/_locales/fi/messages.json
  app/_locales/fil/messages.json
  app/_locales/fr/messages.json
  app/_locales/he/messages.json
  app/_locales/hi/messages.json
  app/_locales/hn/messages.json
  app/_locales/hr/messages.json
  app/_locales/ht/messages.json
  app/_locales/hu/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/kn/messages.json
  app/_locales/ko/messages.json
  app/_locales/lt/messages.json
  app/_locales/lv/messages.json
  app/_locales/ms/messages.json
  app/_locales/nl/messages.json
  app/_locales/no/messages.json
  app/_locales/ph/messages.json
  app/_locales/pl/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ro/messages.json
  app/_locales/ru/messages.json
  app/_locales/sk/messages.json
  app/_locales/sl/messages.json
  app/_locales/sr/messages.json
  app/_locales/sv/messages.json
  app/_locales/sw/messages.json
  app/_locales/ta/messages.json
  app/_locales/th/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/uk/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  ui/pages/send/send-content/add-recipient/__snapshots__/add-recipient.component.test.js.snap
  ui/pages/send/send-content/add-recipient/add-recipient.component.js
Labels: team-extension-UX, needs-ux-ds-review

#19602 Remove Unused CSS: ConnectedStatusIndicator #19587
  ui/components/app/app-components.scss
  ui/components/app/connected-status-indicator/index.scss
Labels: needs-ux-ds-review

#19293 Implement tests for multiple service worker restarts on the mv3 build
  development/build/index.js
  test/e2e/helpers.js
  test/e2e/mv3/multiple-restarts.spec.js
  test/e2e/mv3/phishing-warning-sw-restart.spec.js
  test/e2e/tests/eth-sign.spec.js
  test/e2e/webdriver/driver.js
  yarn.lock
Labels: team-extension-client, team-extension-platform

#19061 feat(action): github action to automatically add label "release-x.y.z" when PRs get merged
  .github/scripts/add-release-label-to-pr-and-linked-issues.ts
  .github/workflows/add-release-label.yml
  development/get-next-semver-version.sh
  package.json
Labels: team-extension-client, team-extension-platform

#19615 Fix #19609 - Prevent rounded corners in account menu
  test/e2e/tests/add-account.spec.js
  test/e2e/user-actions-benchmark.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/account-list-menu.test.js
  ui/components/multichain/account-list-menu/index.scss
Labels: needs-ux-ds-review

#19645 feature(19625): eliminate e2e flakyness for add-account and send-eth
  test/e2e/helpers.js
  test/e2e/tests/add-account.spec.js
  test/e2e/tests/send-eth.spec.js
Labels: team-extension-client, team-extension-platform

#19673 Only show a Swaps notification on a supported chain
  ui/selectors/selectors.js
Labels: release-blocker, release-10.33.0

#19304 Add sonarqube scans to the extension
  .github/workflows/sonar.yml
  sonar-project.properties
Labels: team-extension-client, team-extension-platform

#19283 feat(srp): add a quiz to the SRP reveal
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/reveal-srp.png
  development/verify-locale-strings.js
  package.json
  test/e2e/helpers.js
  test/e2e/tests/settings-security-reveal-srp.spec.js
  test/e2e/webdriver/driver.js
  test/lib/i18n-helpers.js
  ui/components/app/hold-to-reveal-button/hold-to-reveal-button.js
  ui/components/app/modals/modal.js
  ui/components/app/srp-quiz-modal/QuizContent/QuizContent.tsx
  ui/components/app/srp-quiz-modal/QuizContent/index.ts
  ui/components/app/srp-quiz-modal/SRPQuiz/SRPQuiz.stories.tsx
  ui/components/app/srp-quiz-modal/SRPQuiz/SRPQuiz.test.js
  ui/components/app/srp-quiz-modal/SRPQuiz/SRPQuiz.tsx
  ui/components/app/srp-quiz-modal/SRPQuiz/index.ts
  ui/components/app/srp-quiz-modal/index.ts
  ui/components/app/srp-quiz-modal/types.ts
  ui/components/ui/export-text-container/export-text-container.component.js
  ui/helpers/constants/zendesk-url.js
  ui/helpers/utils/ipfs.js
  ui/pages/keychains/reveal-seed.js
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/security-tab/security-tab.test.js
  yarn.lock
Labels: team-accounts, QA Passed

#19639 feat(action): remove labels after PR closed
  .github/workflows/remove-labels-after-pr-closed.yml
Labels: team-extension-client, team-extension-platform, needs-dev-review

#19701 UX Multichain: added extra margin for unlocked state in full view in header
  ui/pages/routes/routes.component.js
Labels: team-extension-UX, needs-ux-ds-review

#19626 Fix #18423 - Ensure token details stay within dropdown
  ui/css/itcss/components/send.scss
  ui/pages/send/gas-display/gas-display.js
  ui/pages/send/send-content/send-asset-row/send-asset-row.component.js
  ui/pages/send/send-content/send-asset-row/send-asset-row.test.js
  ui/pages/send/send-content/send-content.stories.js
Labels: needs-ux-ds-review

#19616 Fix #19608 - Make account name validation more strict
  ui/helpers/utils/accounts.js
  ui/helpers/utils/accounts.test.js
Labels: needs-ux-ds-review

#19716 removed portfolio link from wallet view
  test/e2e/tests/portfolio-site.spec.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/eth-overview.test.js
Labels: release-blocker, team-extension-client, team-extension-UX, needs-ux-ds-review, release-10.33.0

#19728 fix(action): add required permissions to remove labels
  .github/workflows/remove-labels-after-pr-closed.yml
Labels: team-extension-client, team-extension-platform, needs-dev-review

#19694 Security Provider cleanup
  shared/constants/security-provider.ts
  shared/modules/security-provider.utils.test.ts
  shared/modules/security-provider.utils.ts
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.test.js
  ui/components/app/security-provider-banner-message/security-provider-banner-message.constants.js
  ui/components/app/security-provider-banner-message/security-provider-banner-message.js
  ui/components/app/security-provider-banner-message/security-provider-banner-message.test.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request-original/signature-request-original.test.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request/signature-request.component.js
  ui/components/app/signature-request/signature-request.component.test.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/token-allowance/token-allowance.js
Labels: team-confirmations-secure-ux-PR

#19686 Replacing deprecated constants & creating stories
  ui/components/app/confirm-gas-display/confirm-gas-display.stories.js
  ui/components/app/connected-accounts-permissions/connected-account-permissions.stories.js
  ui/components/institutional/compliance-details/__snapshots__/compliance-details.test.js.snap
  ui/components/institutional/compliance-details/compliance-details.js
  ui/components/multichain/product-tour-popover/product-tour-popover.js
Labels: design-system, needs-ux-ds-review

#19724 Add `manageAccounts` RPC method
  .circleci/config.yml
  .github/workflows/remove-labels-after-pr-closed.yml
  .storybook/main.js
  app/scripts/controllers/permissions/snaps/snap-keyring-permissions.js
  app/scripts/controllers/permissions/snaps/snap-permissions.js
  app/scripts/lib/rpc-method-middleware/createMethodMiddleware.js
  app/scripts/metamask-controller.js
  app/scripts/use-snow.js
  development/build/index.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  shared/constants/permissions.test.js
  shared/constants/security-provider.ts
  shared/modules/security-provider.utils.test.ts
  shared/modules/security-provider.utils.ts
  test/e2e/helpers.js
  test/e2e/metrics/signature-approved.spec.js
  test/e2e/run-all.js
  test/e2e/tests/portfolio-site.spec.js
  ui/components/app/confirm-gas-display/confirm-gas-display.stories.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.test.js
  ui/components/app/connected-accounts-permissions/connected-account-permissions.stories.js
  ui/components/app/security-provider-banner-message/security-provider-banner-message.constants.js
  ui/components/app/security-provider-banner-message/security-provider-banner-message.js
  ui/components/app/security-provider-banner-message/security-provider-banner-message.test.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request-original/signature-request-original.test.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request/signature-request.component.js
  ui/components/app/signature-request/signature-request.component.test.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/institutional/compliance-details/__snapshots__/compliance-details.test.js.snap
  ui/components/institutional/compliance-details/compliance-details.js
  ui/components/multichain/product-tour-popover/product-tour-popover.js
  ui/helpers/utils/permission.js
  ui/pages/add-snap-account/new-snap-account-page/__snapshots__/new-snap-account-page.test.tsx.snap
  ui/pages/add-snap-account/new-snap-account-page/new-snap-account-page.test.tsx
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/token-allowance/token-allowance.js
  yarn.lock
Labels: team-accounts

#19740 Fix #847 - Don't show account address on token pages
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/token-overview.js
  ui/components/app/wallet-overview/wallet-overview.js
  ui/pages/asset/components/native-asset.js
  ui/pages/home/home.component.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#19739 Deprecating FormField and fixing console error
  ui/components/app/custom-spending-cap/__snapshots__/custom-spending-cap.test.js.snap
  ui/components/ui/form-field/README.mdx
  ui/components/ui/form-field/form-field.js
  ui/components/ui/form-field/form-field.stories.js
  ui/pages/onboarding-flow/add-network-modal/__snapshots__/add-network-modal.test.js.snap
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
Labels: design-system, needs-ux-ds-review

#19646 UI updates for contacts Page
  app/_locales/am/messages.json
  app/_locales/ar/messages.json
  app/_locales/bg/messages.json
  app/_locales/bn/messages.json
  app/_locales/ca/messages.json
  app/_locales/da/messages.json
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/et/messages.json
  app/_locales/fa/messages.json
  app/_locales/fi/messages.json
  app/_locales/fil/messages.json
  app/_locales/fr/messages.json
  app/_locales/he/messages.json
  app/_locales/hi/messages.json
  app/_locales/hr/messages.json
  app/_locales/hu/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/kn/messages.json
  app/_locales/ko/messages.json
  app/_locales/lt/messages.json
  app/_locales/lv/messages.json
  app/_locales/ms/messages.json
  app/_locales/no/messages.json
  app/_locales/ph/messages.json
  app/_locales/pl/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ro/messages.json
  app/_locales/ru/messages.json
  app/_locales/sk/messages.json
  app/_locales/sl/messages.json
  app/_locales/sr/messages.json
  app/_locales/sv/messages.json
  app/_locales/sw/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/uk/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  test/e2e/tests/address-book.spec.js
  ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js
  ui/pages/settings/contact-list-tab/contact-list-tab.component.js
  ui/pages/settings/contact-list-tab/contact-list-tab.container.js
  ui/pages/settings/contact-list-tab/edit-contact/edit-contact.component.js
  ui/pages/settings/contact-list-tab/index.scss
  ui/pages/settings/contact-list-tab/view-contact/view-contact.component.js
  ui/pages/settings/settings.component.js
Labels: team-extension-UX, needs-ux-ds-review

#19705 UX: Ensure multichain native token name is always shown
  ui/components/app/asset-list/asset-list.js
Labels: needs-ux-ds-review

#19707 UX Multichain: fixed padding for edit screen
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header.js
  ui/pages/routes/routes.component.js
  ui/pages/swaps/index.scss
Labels: team-extension-UX, needs-ux-ds-review

#19731 Update Label component font weight from bold to medium
  ui/components/app/modals/eth-sign-modal/__snapshots__/eth-sign-modal.test.js.snap
  ui/components/app/modals/export-private-key-modal/__snapshots__/export-private-key-modal.test.js.snap
  ui/components/component-library/label/__snapshots__/label.test.js.snap
  ui/components/component-library/label/label.js
  ui/components/institutional/confirm-remove-jwt-modal/__snapshots__/confirm-remove-jwt-modal.test.js.snap
  ui/components/institutional/custody-labels/__snapshots__/custody-labels.test.js.snap
  ui/components/institutional/note-to-trader/__snapshots__/note-to-trader.test.js.snap
  ui/pages/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/institutional/connect-custody/__snapshots__/account-list.test.js.snap
  ui/pages/keychains/__snapshots__/reveal-seed.test.js.snap
  ui/pages/swaps/loading-swaps-quotes/__snapshots__/loading-swaps-quotes-stories-metadata.test.js.snap
Labels: design-system

#18638 Part of #17670: Replace Typography with Text component in CancelSpeedupPopover
  ui/components/app/cancel-speedup-popover/cancel-speedup-popover.js
  ui/components/app/cancel-speedup-popover/cancel-speedup-popover.stories.js
  ui/components/app/cancel-speedup-popover/cancel-speedup-popover.test.js
  ui/components/app/cancel-speedup-popover/index.scss
Labels: design-system

#19433 Issue 17670 replace typography with text
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request/__snapshots__/signature-request.component.test.js.snap
  ui/components/app/signature-request/index.scss
  ui/components/app/signature-request/signature-request-message/signature-request-message.js
  ui/components/app/signature-request/signature-request-message/signature-request-message.stories.js
  ui/components/app/signature-request/signature-request.component.js
  ui/components/app/signature-request/signature-request.stories.js
  ui/components/component-library/popover/popover.stories.tsx
  ui/components/ui/numeric-input/numeric-input.component.js
  ui/pages/confirm-signature-request/__snapshots__/index.test.js.snap
Labels: design-system

#19699 Part of #18714: Replacing deprecated constants in `confirm-subtitle` folder
  ui/components/app/confirm-subtitle/confirm-subtitle.js
Labels: design-system

#18912 Part of #17670: Replace Typography with Text component in: callout.js
  ui/components/ui/callout/callout.js
  ui/pages/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/switch-ethereum-chain.test.js.snap
Labels: design-system

#19702 Updated action list in token, NFTs and activity view
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/nft/import-erc1155.spec.js
  test/e2e/nft/import-nft.spec.js
  ui/components/app/asset-list/asset-list.js
  ui/components/app/nfts-tab/index.scss
  ui/components/app/nfts-tab/nfts-tab.js
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/components/multichain/import-token-link/__snapshots__/import-token-link.test.js.snap
  ui/components/multichain/import-token-link/import-token-link.js
  ui/components/ui/tabs/index.scss
  ui/pages/home/home.component.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review, needs-dev-review

#19279 Update sentry to v7.53.0
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/errors.spec.js
  yarn.lock
Labels: team-extension-client, team-extension-platform, needs-dev-review

#19793 UX: Multichain: Make imports consistent
  ui/components/multichain/account-details/account-details.stories.js
  ui/components/multichain/connected-site-menu/connected-site-menu.stories.js
  ui/components/multichain/connected-site-menu/connected-site-menu.test.js
  ui/components/multichain/detected-token-banner/detected-token-banner.stories.js
  ui/components/multichain/detected-token-banner/detected-token-banner.test.js
  ui/components/multichain/import-token-link/import-token-link.stories.js
  ui/components/multichain/import-token-link/import-token-link.test.js
  ui/components/multichain/nft-item/nft-item.stories.js
  ui/components/multichain/product-tour-popover/product-tour-popover.stories.js
  ui/components/multichain/product-tour-popover/product-tour-popover.test.js
  ui/components/multichain/token-list-item/token-list-item.stories.js
  ui/components/multichain/token-list-item/token-list-item.test.js
Labels: needs-ux-ds-review

#19795 UX: Multichain: Update deprecated variables
  ui/components/multichain/account-details/account-details-authenticate.js
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/account-details/account-details-key.js
  ui/components/multichain/account-details/account-details.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/connected-site-menu/connected-site-menu.js
  ui/components/multichain/network-list-item/network-list-item.js
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: needs-ux-ds-review

#19804 Updated swap and send header for popup view
  ui/components/multichain/app-header/app-header.js
Labels: release-blocker, release-10.33.0

#19788 fix issue where non-standard NFT watchAsset requests result in notification with home screen view
  ui/selectors/selectors.js
Labels: release-blocker, release-10.33.0

#19847 Fix hold to reveal button on mobile browsers
  ui/components/app/hold-to-reveal-button/hold-to-reveal-button.js
  ui/components/app/hold-to-reveal-button/hold-to-reveal-button.test.js
  ui/components/app/modals/export-private-key-modal/export-private-key-modal.component.test.js
  ui/components/app/modals/hold-to-reveal-modal/hold-to-reveal-modal.test.js
  ui/pages/keychains/reveal-seed.test.js
Labels: type-bug
