Repository MetaMask/metamask-extension, pull requests merged in 2023-09, with the labels that each got.

#20680 Sync v10.35.1 with `develop`
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#20685 Fix missing property on snap export metric
  app/scripts/metamask-controller.js
Labels: team-snaps

#20690 Fix v11 RC issues following merge
  app/scripts/lib/setupSentry.js
  lavamoat/browserify/main/policy.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
Labels: team-snaps

#20557 AvatarIcon prod updates and some deprecated fixes
  ui/components/app/permission-cell/permission-cell.js
  ui/components/app/snaps/install-error/install-error.js
  ui/components/app/snaps/snap-avatar/snap-avatar.js
  ui/components/app/snaps/snap-delineator/snap-delineator.js
  ui/components/app/snaps/snap-install-warning/snap-install-warning.js
  ui/components/app/snaps/snap-privacy-warning/snap-privacy-warning.js
  ui/components/app/transaction-icon/transaction-icon.js
  ui/helpers/utils/permission.js
  ui/pages/permissions-connect/snaps/snap-result/snap-result.js
Labels: team-design-system, needs-ux-ds-review

#19498 add whatsnew popup to drop ledger support for firefox
  app/_locales/en/messages.json
  shared/notifications/index.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: DO-NOT-MERGE, needs-qa, team-accounts

#20671 feat: Update Blockaid copies on What's new modal, Settings, and BannerAlert
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/notifications/index.js
  ui/components/app/security-provider-banner-alert/__snapshots__/security-provider-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.js
  ui/components/app/whats-new-popup/whats-new-popup.test.js
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/index.scss
Labels: team-confirmations-secure-ux-PR

#20710 Add resolution for `semver`
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-snaps

#20712 Fix position of a warning triangle icon on Snap Install Warning
  ui/components/app/snaps/snap-install-warning/snap-install-warning.js
Labels: team-snaps

#20686 Add what's new popup for snaps
  app/_locales/en/messages.json
  app/images/introducing-snaps.svg
  shared/notifications/index.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: team-snaps

#20523 Use transactions array in frontend
  .storybook/test-data.js
  app/scripts/background.js
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/lib/setupSentry.js
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/jest/mock-store.js
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.test.js
  ui/components/app/signature-request-siwe/signature-request-siwe.test.js
  ui/components/app/transaction-list/transaction-list.test.js
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/global-menu/global-menu.test.js
  ui/ducks/app/app.test.js
  ui/ducks/confirm-transaction/confirm-transaction.duck.test.js
  ui/ducks/metamask/metamask.js
  ui/ducks/metamask/metamask.test.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/index.js
  ui/pages/confirm-approve/confirm-approve.stories-to-do.js
  ui/pages/confirm-send-ether/confirm-send-ether.stories.js
  ui/pages/confirm-send-ether/confirm-send-ether.test.js
  ui/pages/confirm-signature-request/index.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirm-transaction-switch/confirm-transaction-switch.container.js
  ui/pages/confirm-transaction/confirm-transaction.test.js
  ui/pages/confirm-transaction/confirm-transaction.transaction.test.js
  ui/pages/confirmation/templates/success.test.js
  ui/pages/confirmation/templates/switch-ethereum-chain.test.js
  ui/pages/send/gas-display/gas-display.js
  ui/pages/send/send-content/add-recipient/add-recipient.container.js
  ui/pages/send/send-content/add-recipient/add-recipient.container.test.js
  ui/pages/send/send.test.js
  ui/pages/swaps/index.js
  ui/pages/token-allowance/token-allowance.test.js
  ui/selectors/confirm-transaction.js
  ui/selectors/nonce-sorted-transactions-selector.test.js
  ui/selectors/selectors.js
  ui/selectors/transactions.js
  ui/selectors/transactions.test.js
  ui/selectors/util.js
  ui/store/actions.ts
  ui/store/institutional/institution-actions.test.js
  ui/store/institutional/institution-actions.ts
  ui/store/store.ts
Labels: team-confirmations-system, QA Passed

#20715 Added Specification for opBNB as a multilayer network
  shared/constants/network.ts
  ui/selectors/selectors.js
Labels: team-confirmations-secure-ux

#20566 Reverting ppom.js file to old version
  app/scripts/lib/ppom/ppom.js
Labels: team-confirmations-secure-ux

#20735 Add missing derivation path names
  shared/constants/snaps.ts
Labels: team-snaps

#20737 fix(20548): fix warning levels in migration file
  app/scripts/migrations/088.test.ts
  app/scripts/migrations/088.ts
Labels: team-extension-client, team-extension-platform

#20713 fix(readme): yarn v3 no longer required
  README.md
Labels: team-extension-client, team-extension-platform

#20741 Update Snap privacy warning content
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/constants/terms.js
  ui/components/app/snaps/snap-privacy-warning/snap-privacy-warning.test.js
Labels: team-snaps

#20738 Update PPOM Validator
  package.json
  yarn.lock
Labels: team-confirmations-secure-ux-PR

#20744 Sync v11.0.0 with `develop`
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#20742 fix(20316): enrich error message for fetch-with-cache
  app/scripts/controllers/swaps.js
  shared/lib/fetch-with-cache.test.js
  shared/lib/fetch-with-cache.ts
  shared/lib/swaps-utils.js
  ui/components/app/transaction-decoding/transaction-decoding.component.js
  ui/components/ui/new-network-info/new-network-info.js
  ui/components/ui/new-network-info/new-network-info.test.js
  ui/helpers/utils/transactions.util.js
  ui/pages/confirmation/templates/add-ethereum-chain.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/swaps/swaps.util.ts
Labels: team-extension-client, team-extension-platform

#20754 [MMI] Added code fences to hide emojis just for MMI build
  ui/components/app/edit-gas-fee-button/edit-gas-fee-button.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.js
Labels: team-mmi

#20748 fix: "Allow quick Add Account name based on default name" (20168)
  ui/components/multichain/create-account/create-account.js
Labels: team-accounts

#20756 Updating ppom validator
  package.json
  yarn.lock
Labels: team-confirmations-secure-ux

#20636 Fix #682 - Show connected app favicon in bottom bar
  ui/components/multichain/app-footer/app-footer.js
  ui/components/multichain/app-footer/app-footer.stories.js
Labels: team-extension-UX, needs-ux-ds-review

#20783 Add MMI builds to metamaskbot comment
  .circleci/config.yml
  development/metamaskbot-build-announce.js
Labels: release-blocker, team-extension-platform

#20692 Throw error if mock server port is busy
  package.json
  test/e2e/helpers.js
  yarn.lock
Labels: team-snaps

#20767 [MMI] Shows Stake & Portfolio buttons and hides the Buy and Bridge buttons
  ui/components/app/wallet-overview/token-overview.js
  ui/components/app/wallet-overview/token-overview.test.js
Labels: team-mmi, release-11.1.0

#20807 Fix broken `approveTokenDescriptionWithoutSymbol` translation key
  app/_locales/fr/messages.json
Labels: team-snaps

#20755 Ux Multichain : Updated Select Action Modal
  app/_locales/en/messages.json
  ui/components/multichain/select-action-modal-item/__snapshots__/select-action-item.test.js.snap
  ui/components/multichain/select-action-modal-item/select-action-modal-item.js
  ui/components/multichain/select-action-modal/select-action-modal.js
Labels: team-extension-UX

#20729 Remove `nonceDetails` from `TransactionMeta`
  .storybook/initial-states/transactions.js
  .storybook/test-data.js
  app/scripts/controllers/transactions/README.md
  app/scripts/controllers/transactions/index.js
  app/scripts/migrations/097.test.ts
  app/scripts/migrations/097.ts
  app/scripts/migrations/index.js
  shared/constants/transaction.ts
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/data/mock-tx-history.json
  test/data/transaction-data.json
  test/e2e/fixture-builder.js
  test/stub/tx-meta-stub.js
  ui/components/app/transaction-activity-log/transaction-activity-log.util.test.js
Labels: team-confirmations-system

#20781 UX: Fix errant global menu event
  ui/components/multichain/app-header/app-header.js
Labels: team-extension-UX

#20696 Migrate MetaMaskController from mocha to jest
  .eslintrc.js
  .mocharc.js
  app/scripts/controllers/app-state.js
  app/scripts/controllers/metametrics.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  jest.config.js
Labels: team-devex

#20786 Move the `saveSnapKeyring` callback to the `SnapKeyring` constructor
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: team-accounts

#20769 Adding env vars for blockaid to build file
  builds.yml
Labels: release-blocker, team-confirmations-secure-ux-PR, release-11.1.0

#20826 Revert ppom.js exactly to audited version
  app/scripts/lib/ppom/ppom.js
Labels: team-confirmations-secure-ux-PR

#20768 Fix: Change style object key format kebab -> camelCase and fix title param type
  ui/components/ui/metafox-logo/horizontal-logo.js
  ui/components/ui/review-spending-cap/review-spending-cap.js
  ui/pages/swaps/searchable-item-list/item-list/item-list.component.js
Labels: team-confirmations-secure-ux-PR

#20830 [MMI] Show the NFT tab content for mmi
  app/_locales/en/messages.json
  ui/components/app/nfts-detection-notice/nfts-detection-notice.js
  ui/pages/home/home.component.js
Labels: team-mmi, release-11.1.0

#20796 fix: fix nft order
  ui/pages/confirm-add-suggested-nft/confirm-add-suggested-nft.js
  ui/pages/send/send-content/send-asset-row/send-asset-row.component.js
Labels: team-extension-UX, needs-ux-ds-review

#20821 Integrate `SelectedNetworkController`
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: team-devex

#20626 fix: error during persisted transaction approval
  app/scripts/controllers/transactions/index.js
Labels: team-confirmations-system

#20850 Only show enabled insight snaps on the confirmation screen
  ui/selectors/selectors.js
Labels: team-snaps

#20851 Use first non-symbol character as snap fallback icon
  ui/components/app/snaps/snap-avatar/snap-avatar.js
Labels: team-snaps

#20740 Require Flask Snaps E2E to pass for CI pass
  .circleci/config.yml
Labels: team-snaps

#20854 Fix spacing on connected sites in the snap details page
  ui/components/app/connected-sites-list/connected-sites-list.component.js
  ui/pages/settings/snaps/view-snap/index.scss
  ui/pages/settings/snaps/view-snap/view-snap.js
Labels: team-snaps

#20409 Make permissions modal scrollable
  ui/components/app/connected-accounts-permissions/index.scss
  ui/pages/connected-accounts/index.scss
Labels: external-contributor

#20714 Add extra confirmation when removing keyring snap
  app/_locales/en/messages.json
  test/data/mock-send-state.json
  ui/components/app/snaps/keyring-snap-removal-warning/index.ts
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-account-list-item.tsx
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.stories.js
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.test.tsx
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.tsx
  ui/components/app/snaps/snap-removal-result/index.ts
  ui/components/app/snaps/snap-removal-result/snap-removal-result.tsx
  ui/components/app/snaps/snap-remove-warning/snap-remove-warning.js
  ui/components/app/snaps/snap-remove-warning/snap-remove-warning.stories.js
  ui/components/app/snaps/snap-remove-warning/snap-remove-warning.test.tsx
  ui/pages/settings/snaps/view-snap/view-snap.js
  ui/store/actions.ts
Labels: team-accounts

#20567 [FLASK] Bump snaps packages
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/permissions.test.js
  shared/constants/permissions.ts
  shared/constants/snaps/permissions.ts
  ui/helpers/utils/permission.js
  yarn.lock
Labels: flask, team-snaps

#20683 build: add "test:unit:jest:watch" script to package.json to run jest tests on a node server
  docs/tests/jest.md
  package.json
Labels: team-confirmations-secure-ux-PR

#20809 Enable zkSync Era in Swaps
  app/_locales/en/messages.json
  shared/constants/network.ts
  shared/constants/swaps.ts
  ui/hooks/useTokensToSearch.js
  ui/pages/swaps/fee-card/fee-card.js
  ui/pages/swaps/prepare-swap-page/review-quote.js
  ui/pages/swaps/swaps.util.test.js
  ui/pages/swaps/swaps.util.ts
Labels: area-swaps, team-swaps

#20810 fix: add new account after an account management snap is re-installed
  app/scripts/metamask-controller.js
Labels: type-bug, team-accounts, QA Passed

#20842 Adding storybook files for the StepProgressBar
  ui/components/app/step-progress-bar/step-progress-bar.stories.js
Labels: team-design-system, needs-ux-ds-review

#20818 Update chromedriver version
  .circleci/scripts/chrome-install.sh
  package.json
  yarn.lock
Labels: team-extension-client, team-extension-platform

#20833 [MMI] Added institutional selectors unit tests
  ui/components/institutional/wrong-network-notification/wrong-network-notification.test.js
  ui/selectors/institutional/selectors.js
  ui/selectors/institutional/selectors.test.js
Labels: team-mmi

#20855 [MMI] Added Institution-background unit test
  ui/store/institutional/institution-background.test.js
Labels: team-mmi

#20884 [MMI] Changed the wrong privacy policy URL to the good one
  ui/pages/settings/info-tab/info-tab.component.js
Labels: team-mmi

#20880 Update send native token origin MM.csv
  test/scenarios/3. transactions/send native token origin MM.csv
Labels: area-documentation, team-extension-platform

#20858 UX: Set initial background color to system theme
  ui/css/base-styles.scss
Labels: team-extension-UX, needs-ux-ds-review

#20889 Update `useScrollRequired` logic
  ui/hooks/useScrollRequired.js
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
Labels: team-snaps

#20899 Fix undefined getCurrentNetworkTransactions on speed up
  ui/store/actions.ts
Labels: type-bug, release-blocker, regression-RC, team-confirmations-system, QA Passed, release-11.1.0

#20728 Remove `keyringMemStore` from `DetectTokensController`
  app/scripts/controllers/detect-tokens.js
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/metamask-controller.js
Labels: team-shared-libraries

#20813 update sentry documentation
  development/README.md
Labels: team-extension-platform

#20798 Add name component
  app/_locales/en/messages.json
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/app/app-components.scss
  ui/components/app/name/__snapshots__/name.test.tsx.snap
  ui/components/app/name/index.scss
  ui/components/app/name/index.ts
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/name/name-details/index.scss
  ui/components/app/name/name-details/index.ts
  ui/components/app/name/name-details/name-details.test.tsx
  ui/components/app/name/name-details/name-details.tsx
  ui/components/app/name/name.stories.tsx
  ui/components/app/name/name.test.tsx
  ui/components/app/name/name.tsx
  ui/components/ui/form-combo-field/__snapshots__/form-combo-field.test.tsx.snap
  ui/components/ui/form-combo-field/form-combo-field.stories.tsx
  ui/components/ui/form-combo-field/form-combo-field.test.tsx
  ui/components/ui/form-combo-field/form-combo-field.tsx
  ui/components/ui/form-combo-field/index.scss
  ui/components/ui/form-combo-field/index.ts
  ui/components/ui/ui-components.scss
  ui/hooks/useName.test.ts
  ui/hooks/useName.ts
  ui/selectors/selectors.js
  ui/store/actions.ts
  yarn.lock
Labels: team-confirmations-system

#20812 MMI: core `KeyringController` instead of `eth-keyring-controller`
  app/scripts/controllers/mmi-controller.js
  app/scripts/controllers/mmi-controller.test.js
  app/scripts/metamask-controller.js
Labels: team-shared-libraries

#20835 chore: add mmi e2e test trigger workflow
  .github/workflows/trigger-metamask-institutional-e2e-ci.yml
Labels: team-mmi

#20808 Remove eth-keyring-controller from DecryptMessageController
  .yarn/patches/@metamask-keyring-controller-npm-7.4.0-5dd5df31c7.patch
  app/scripts/controllers/decrypt-message.test.ts
  app/scripts/controllers/decrypt-message.ts
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: team-shared-libraries

#20454 [e2e]: blockaid toggle settings
  package.json
  test/e2e/run-all.js
  test/e2e/snaps/ppom-toggle-settings.spec.js
  ui/components/app/security-provider-banner-alert/__snapshots__/security-provider-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.js
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
Labels: team-confirmations-secure-ux-PR

#20747 Fixes for converting an ERC-20 token to an NFT
  test/data/mock-send-state.json
  test/data/mock-state.json
  ui/components/app/modals/convert-token-to-nft-modal/convert-token-to-nft-modal.js
  ui/components/multichain/import-nfts-modal/import-nfts-modal.js
  ui/components/multichain/import-nfts-modal/import-nfts-modal.test.js
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
  ui/ducks/app/app.ts
  ui/pages/routes/routes.container.js
  ui/store/actions.ts
Labels: team-extension-UX

#20887 fix: tweak fitness function rule for mocha tests
  development/fitness-functions/common/shared.ts
  development/fitness-functions/rules/sinon-assert-syntax.test.ts
  development/fitness-functions/rules/sinon-assert-syntax.ts
Labels: team-extension-client, team-extension-platform

#20651 feat(templates): new templates for issues and PRs
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/general-issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/guidelines/CODING_GUIDELINES.md
  .github/guidelines/LABELING_GUIDELINES.md
  .github/pull-request-template.md
Labels: team-extension-client, team-extension-platform

#20935 Stabilize e2e test - Creates multiple queued transactions, then confirm
  test/e2e/tests/multiple-transactions.spec.js
Labels: team-extension-client, team-extension-platform

#20831 Use name component in signature requests
  app/scripts/metamask-controller.js
  builds.yml
  test/e2e/fixture-builder.js
  test/e2e/mock-e2e.js
  test/e2e/run-all.js
  test/e2e/snaps/petnames.spec.js
  test/e2e/webdriver/driver.js
  test/jest/setup.js
  ui/components/app/modals/contract-details-modal/contract-details-modal.js
  ui/components/app/signature-request/signature-request-data/index.scss
  ui/components/app/signature-request/signature-request-data/signature-request-data.js
  ui/hooks/usePetnamesEnabled.ts
Labels: team-confirmations-system

#20890 Add verifiedOnBlockchain property to transaction meta
  app/scripts/controllers/transactions/EtherscanRemoteTransactionSource.test.ts
  app/scripts/controllers/transactions/EtherscanRemoteTransactionSource.ts
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/pending-tx-tracker.js
  app/scripts/controllers/transactions/tx-state-manager.js
  app/scripts/migrations/098.test.ts
  app/scripts/migrations/098.ts
  app/scripts/migrations/index.js
  shared/constants/transaction.ts
Labels: team-confirmations-system

#20387 [MMI] updates the "connect custodian account" flow
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  builds.yml
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/helpers/utils/institutional/find-by-custodian-name.test.ts
  ui/helpers/utils/institutional/find-by-custodian-name.ts
  ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.js
  ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.test.js
  ui/pages/institutional/confirm-connect-custodian-modal/confirm-connect-custodian-modal.js
  ui/pages/institutional/confirm-connect-custodian-modal/confirm-connect-custodian-modal.stories.js
  ui/pages/institutional/confirm-connect-custodian-modal/confirm-connect-custodian-modal.test.js
  ui/pages/institutional/confirm-connect-custodian-modal/index.js
  ui/pages/institutional/custody/custody.js
  ui/pages/institutional/custody/custody.test.js
  ui/pages/institutional/institutional-entity-done-page/institutional-entity-done-page.js
  yarn.lock
Labels: team-mmi

#20960 fix(20908): use background state as default privacy value in onboarding flow
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
Labels: team-extension-client, team-extension-platform, release-11.1.0

#20920 fix: catch the rejection if you submit an incorrect password to "Show private key"
  ui/components/multichain/account-details/account-details-authenticate.js
  ui/pages/keychains/__snapshots__/reveal-seed.test.js.snap
  ui/pages/keychains/reveal-seed.js
Labels: team-accounts

#20929 fix: Copy and add 3rd party API links
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/constants/network.ts
  ui/components/app/incoming-trasaction-toggle/__snapshots__/incoming-transaction-toggle.test.js.snap
  ui/components/app/incoming-trasaction-toggle/incoming-transaction-toggle.tsx
  ui/components/app/incoming-trasaction-toggle/network-toggle.tsx
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: release-blocker, team-extension-client, team-extension-platform, in-progress

#20946 Bump Browserify
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-snaps

#20968 Fix Solana derivation paths for snaps
  shared/constants/snaps.ts
Labels: team-snaps

#20932 Move token detection to top of assets
  ui/components/app/asset-list/asset-list.js
Labels: team-extension-UX, needs-ux-ds-review

#20907 Add Custody component unit tests
  app/scripts/controllers/mmi-controller.js
  ui/components/ui/pulse-loader/pulse-loader.js
  ui/helpers/utils/institutional/find-by-custodian-name.ts
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/institutional/confirm-connect-custodian-modal/confirm-connect-custodian-modal.js
  ui/pages/institutional/custody/__snapshots__/custody.test.js.snap
  ui/pages/institutional/custody/custody.js
  ui/pages/institutional/custody/custody.test.js
  ui/pages/institutional/interactive-replacement-token-page/__snapshots__/interactive-replacement-token-page.test.js.snap
  ui/selectors/institutional/selectors.js
  ui/selectors/institutional/selectors.test.js
Labels: team-mmi

#20983 Fix an issue with disconnecting a single dapp from a snap
  ui/pages/settings/snaps/view-snap/view-snap.js
Labels: team-snaps

#20982 [MMI] Updates custody-keyring package
  package.json
  ui/pages/institutional/custody/custody.js
  yarn.lock
Labels: team-mmi, release-11.3.0

#20927 UX: updated placeholder for erc-1155 image
  ui/components/app/nft-default-image/nft-default-image.js
  ui/components/app/nft-default-image/nft-default-image.stories.js
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/nft-details.js
  ui/components/app/nfts-items/nfts-items.js
  ui/components/multichain/nft-item/nft-item.js
Labels: release-blocker, team-extension-client, team-extension-UX, release-11.1.0

#20976 [FLASK] Bump snaps packages
  app/scripts/metamask-controller.js
  builds.yml
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  package.json
  yarn.lock
Labels: team-snaps

#20986 Fix `updateCaveat` not being exposed in the background API
  app/scripts/metamask-controller.js
Labels: team-snaps

#20987 Stabilize e2e test for IPFS toggle
  test/e2e/tests/ipfs-toggle.spec.js
Labels: team-extension-client, team-extension-platform

#20915 Fix #20910 - Turn off ENS resolution if IPFS is turned off
  app/scripts/lib/ens-ipfs/setup.js
  test/e2e/tests/ipfs-ens-resolution.spec.js
Labels: release-blocker, team-extension-client, team-extension-UX, needs-ux-ds-review, release-11.1.0

#20877 Bump LavaMoat and SES
  .yarn/patches/lavamoat-core-npm-14.4.1-c4e8bbb016.patch
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: release-blocker, team-lavamoat, release-11.1.0

#20991 Bump `@metamask/network-controller` to v12.2.0
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-devex

#20978 Fix autodetect tokens link not jumping to section in settings
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
Labels: team-extension-UX

#20964 fix: add tooltip description to manageAccounts method
  app/_locales/en/messages.json
  ui/helpers/utils/permission.js
Labels: team-accounts, needs-dev-review

#20974 Hide 'Add snap account' button behind an experimental setting
  app/_locales/en/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  test/data/mock-state.json
  test/e2e/run-all.js
  test/e2e/tests/settings-add-snap-account-toggle.spec.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/account-list-menu.test.js
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.container.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-accounts, QA Passed

#20865 Update `eth-snap-keyring` to 0.2.x to use the `keyring-api` 0.2.x
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-manageAccount.spec.js
  yarn.lock
Labels: flask, team-accounts, QA Passed

#20990 [MMI] clean up MMI Portfolio Dashboard URLs
  shared/constants/swaps.ts
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/app/wallet-overview/token-overview.js
  ui/components/multichain/select-action-modal/select-action-modal.js
  ui/helpers/constants/common.ts
Labels: team-mmi, release-11.2.0, release-11.3.0

#20973 fix: Incoming tx on activity tab when transfering funds between wallets on the same client
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  ui/components/app/transaction-list/transaction-list.component.js
Labels: release-blocker, team-extension-client, team-extension-platform, release-11.1.0

#21004 [MMI] fix property name and filter out custodian
  ui/helpers/utils/institutional/find-by-custodian-name.ts
  ui/pages/institutional/custody/custody.js
  ui/pages/institutional/custody/custody.test.js
Labels: team-mmi, release-11.2.0

#20922 Updating ModalContent to use TS version of Box
  ui/components/component-library/modal-content/README.mdx
  ui/components/component-library/modal-content/modal-content.stories.tsx
  ui/components/component-library/modal-content/modal-content.tsx
  ui/components/component-library/modal-content/modal-content.types.ts
Labels: team-design-system, needs-ux-ds-review

#20931 Feat/add mm e2e mmi build
  .circleci/config.yml
  README.md
  package.json
  test/e2e/metrics/permissions-approved.spec.js
  test/e2e/metrics/signature-approved.spec.js
  test/e2e/metrics/swaps.spec.js
  test/e2e/metrics/transaction-finalized.spec.js
  test/e2e/metrics/wallet-created.spec.js
  test/e2e/nft/erc1155-interaction.spec.js
  test/e2e/nft/erc721-interaction.spec.js
  test/e2e/run-all.js
  test/e2e/run-e2e-test.js
  test/e2e/swaps/swap-eth.spec.js
  test/e2e/swaps/swaps-notifications.spec.js
  test/e2e/tests/add-account.spec.js
  test/e2e/tests/chain-interactions.spec.js
  test/e2e/tests/custom-token-add-approve.spec.js
  test/e2e/tests/edit-gas-fee.spec.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/incremental-security.spec.js
  test/e2e/tests/portfolio-site.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/signature-request.spec.js
  test/e2e/tests/simple-send.spec.js
  test/e2e/tests/terms-of-use.spec.js
Labels: team-mmi

#21005 [MMI] Add Jwt-url-form component unit test
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/institutional/jwt-url-form/__snapshots__/jwt-url-form.test.js.snap
  ui/components/institutional/jwt-url-form/jwt-url-form.js
  ui/components/institutional/jwt-url-form/jwt-url-form.test.js
Labels: team-mmi

#20977 fix(20853): improve the logic to handle fetch
  ui/components/ui/new-network-info/new-network-info.js
  ui/components/ui/new-network-info/new-network-info.test.js
Labels: team-extension-client, team-extension-platform, needs-dev-review

#21012 feat(1120): remove toggle all in incoming-transaction-toggle
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/fixture-builder.js
  ui/components/app/incoming-trasaction-toggle/__snapshots__/incoming-transaction-toggle.test.js.snap
  ui/components/app/incoming-trasaction-toggle/incoming-transaction-toggle.test.js
  ui/components/app/incoming-trasaction-toggle/incoming-transaction-toggle.tsx
  ui/components/app/incoming-trasaction-toggle/network-toggle.tsx
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: team-extension-client, team-extension-platform

#20981 fix: Tweak banner copy
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/nfts-detection-notice-import-nfts/index.js
  ui/components/app/nfts-detection-notice-import-nfts/nfts-detection-notice-import-nfts.js
  ui/components/app/nfts-detection-notice-import-nfts/nfts-detection-notice-import-nfts.stories.js
  ui/components/app/nfts-detection-notice-nfts-tab/index.js
  ui/components/app/nfts-detection-notice-nfts-tab/nfts-detection-notice-nfts-tab.js
  ui/components/app/nfts-detection-notice-nfts-tab/nfts-detection-notice.stories.js
  ui/components/app/nfts-detection-notice/index.js
  ui/components/app/nfts-tab/nfts-tab.js
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/components/multichain/import-nfts-modal/import-nfts-modal.js
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
Labels: release-blocker, team-extension-client, team-extension-platform, release-11.1.0

#20843 UX: Load the extension HTML pages and background with async JavaScript
  app/background.html
  app/home.html
  app/notification.html
  app/popup.html
  app/scripts/load-app.js
  development/build/scripts.js
  development/build/static.js
  test/e2e/webdriver/driver.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20913 UX: Snaps: Only display Notification in Global Menu if enabled snap uses that permission
  ui/components/multichain/global-menu/global-menu.js
  ui/selectors/selectors.js
Labels: team-extension-UX, needs-ux-ds-review

#20881 Update cancel transaction.csv
  test/scenarios/3. transactions/cancel transaction.csv
Labels: area-documentation, team-extension-platform

#20895 UX: Show Network Logo Based on Chain ID
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20822 Get infuraBlocked from network state
  .storybook/test-data.js
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/controllers/mmi-controller.test.js
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/lib/backup.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/e2e/fixture-builder.js
  test/e2e/restore/MetaMaskUserData.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  yarn.lock
Labels: team-devex

#20970 [MMI] adds Snaps support to MMI build
  builds.yml
  lavamoat/browserify/mmi/policy.json
Labels: team-mmi, release-11.2.0

#21019 fix: filteredTests problem from #20974
  .circleci/config.yml
  test/e2e/helpers.js
  test/e2e/run-all.js
Labels: team-accounts, needs-dev-review

#21009 Updating ppom package
  package.json
  yarn.lock
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#20984 Bump snaps packages and remove `-flask` versions
  .depcheckrc.yml
  app/scripts/controllers/permissions/specifications.test.js
  builds.yml
  development/build/scripts.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  shared/constants/permissions.test.js
  shared/constants/snaps/permissions.ts
  test/e2e/run-all.js
  yarn.lock
Labels: team-snaps

#20883 Update speed up transaction.csv
  test/scenarios/3. transactions/speed up transaction.csv
Labels: area-documentation, team-extension-client, team-extension-platform

#21015 UX: Faster perceived performance of popup
  app/scripts/load-app.js
Labels: team-extension-UX, needs-ux-ds-review

#20897 fix: the Snap npm link now leads to a specific version of the npm package
  ui/components/app/snaps/snap-authorship-expanded/snap-authorship-expanded.js
  ui/components/app/snaps/snap-authorship-header/snap-authorship-header.js
Labels: team-accounts, needs-dev-review

#20879 Update send erc721 token origin MM.csv
  test/scenarios/3. transactions/send erc721 token origin MM.csv
Labels: area-documentation, team-extension-client, team-extension-platform

#20878 Update send erc20 token origin MM.csv
  test/scenarios/3. transactions/send erc20 token origin MM.csv
Labels: area-documentation, team-extension-client, team-extension-platform

#21002 [MMI] Add confirm add custodian token component unit test
  ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.js
  ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.test.js
Labels: team-mmi

#21032 fix(000): convert backup.test to jest
  app/scripts/lib/backup.test.js
Labels: team-extension-client, team-extension-platform

#21022 Fix dropdown for multiple transaction insight snaps
  ui/components/ui/tabs/snaps/dropdown-tab/dropdown-tab.js
  ui/components/ui/tabs/snaps/dropdown-tab/dropdown-tab.test.js
Labels: team-snaps

#21018 UX: Multichain: Ensure all components have proptype docs
  ui/components/multichain/account-details/account-details-authenticate.js
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/account-details/account-details-key.js
  ui/components/multichain/account-details/account-details.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/activity-list-item/activity-list-item.js
  ui/components/multichain/create-account/create-account.js
  ui/components/multichain/import-account/bottom-buttons.js
  ui/components/multichain/import-account/import-account.js
  ui/components/multichain/import-account/json.js
  ui/components/multichain/import-account/private-key.js
  ui/components/multichain/import-nfts-modal/import-nfts-modal.js
  ui/components/multichain/import-tokens-modal/import-tokens-modal-confirm.js
  ui/components/multichain/menu-items/account-details-menu-item.js
  ui/components/multichain/menu-items/view-explorer-menu-item.js
  ui/components/multichain/nft-item/nft-item.js
Labels: team-extension-UX, needs-ux-ds-review

#21035 update ethjs-query to @metamask/ethjs-query
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/pending-tx-tracker.js
  app/scripts/controllers/transactions/tx-gas-utils.js
  app/scripts/lib/ens-ipfs/resolver.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/modules/transaction.utils.test.js
  yarn.lock
Labels: team-extension-platform

#21046 chore: Prevent reusing Yarn cache across Yarn versions
  .circleci/config.yml
Labels: team-extension-platform

#20502 Use `QRKeyring` from `KeyringController`
  .yarn/patches/@metamask-keyring-controller-npm-8.0.0-806630ae4e.patch
  app/scripts/controllers/app-state.js
  app/scripts/controllers/app-state.test.js
  app/scripts/controllers/mmi-controller.test.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-shared-libraries

#20749 feat: CircleCI is now storing builds-test and builds-test-flask
  .circleci/config.yml
  development/metamaskbot-build-announce.js
Labels: team-accounts, needs-dev-review

#20965 Ramps buy/sell button What's New
  app/_locales/en/messages.json
  app/images/sell_button_whatsnew.png
  shared/notifications/index.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21033 Render Default Image when NFT Display Media is Off
  app/_locales/en/messages.json
  test/e2e/tests/ipfs-toggle.spec.js
  ui/components/app/nft-details/nft-details.js
  ui/components/app/nfts-items/nfts-items.js
  ui/components/multichain/nft-item/nft-item.js
  ui/components/multichain/nft-item/nft-item.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: team-extension-UX, needs-ux-ds-review

#20800 Update changelog v11.1.0
  CHANGELOG.md
Labels: team-extension-client, team-extension-platform

#21021 E2E coverage on Snap Accounts and Snap Simple Keyring
  package.json
  test/e2e/accounts/test-snap-accounts.spec.js
  test/e2e/accounts/utils.ts
  test/e2e/fixture-builder.js
  test/e2e/helpers.js
  test/e2e/metrics/signature-approved.spec.js
  test/e2e/run-all.js
  test/e2e/webdriver/driver.js
Labels: team-accounts

#20861 [FLASK] Create new E2E test for snap_getLocale
  test/e2e/run-all.js
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-get-locale.spec.js
Labels: flask, team-snaps

#20951 [FLASK] Remove long-running Snap permission
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/constants/permissions.test.js
  shared/constants/snaps/permissions.ts
  ui/helpers/utils/permission.js
Labels: team-snaps

#21054 build: Remove duplicate @ethersproject/bignumber npm pkg and update to ^5.7.0
  package.json
Labels: dependencies, team-confirmations-secure-ux-PR

#20952 Refactor to use UUID instead of random number for txId
  app/scripts/controllers/transactions/EtherscanRemoteTransactionSource.test.ts
  app/scripts/controllers/transactions/EtherscanRemoteTransactionSource.ts
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/tx-state-manager.js
  app/scripts/migrations/099.test.ts
  app/scripts/migrations/099.ts
  app/scripts/migrations/index.js
  shared/constants/transaction.ts
  test/e2e/fixture-builder.js
  ui/ducks/app/app.ts
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirm-transaction-switch/confirm-transaction-switch.container.js
  ui/pages/confirm-transaction/confirm-transaction.component.js
  ui/pages/swaps/awaiting-swap/awaiting-swap.js
  ui/store/actions.ts
  ui/store/store.ts
Labels: team-confirmations-system, QA Passed

#20999 Fixing metrics for token approval amount type
  app/scripts/controllers/transactions/index.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#20950 Add blockaid related event parameters to signature request metrics
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#21058 [MMI] Add Signature-request unit test
  ui/components/app/signature-request/signature-request.js
  ui/components/app/signature-request/signature-request.test.js
Labels: team-mmi

#20839 feat(ramp): remove sepolia faucet reference
  ui/hooks/experiences/useRamps.test.js
  ui/hooks/experiences/useRamps.ts
Labels: team-ramp, needs-ux-ds-review

#21057 [MMI] Add Pending-tx-tracker unit test
  app/scripts/controllers/transactions/pending-tx-tracker.test.js
Labels: team-mmi

#21016 Fix #20934 - Show network icon in New Network popover
  ui/components/ui/new-network-info/new-network-info.js
Labels: team-extension-UX, needs-ux-ds-review

#20941 UX: Display total fiat balance on home screen
  shared/modules/conversion.utils.test.js
  shared/modules/conversion.utils.ts
  ui/components/app/asset-list/__snapshots__/asset-list.test.js.snap
  ui/components/app/asset-list/asset-list.js
  ui/components/app/asset-list/asset-list.test.js
  ui/components/app/token-list/token-list.js
  ui/components/multichain/balance-overview/__snapshots__/balance-overview.test.js.snap
  ui/components/multichain/balance-overview/balance-overview.js
  ui/components/multichain/balance-overview/balance-overview.stories.js
  ui/components/multichain/balance-overview/balance-overview.test.js
  ui/selectors/selectors.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21075 Master sync following v11.1.0
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#21059 Update snaps packages
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  builds.yml
  package.json
  shared/constants/permissions.test.js
  shared/constants/snaps/permissions.ts
  test/e2e/snaps/enums.js
  ui/helpers/utils/permission.js
  yarn.lock
Labels: team-snaps

#21082 chore: cleanup unused code after #21021
  test/e2e/run-all.js
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-manageAccount.spec.js
Labels: team-accounts, needs-dev-review

#20963 Adds e2e json rpc method tests.
  test/e2e/fixture-builder.js
  test/e2e/json-rpc/eth_accounts.spec.js
  test/e2e/json-rpc/eth_estimateGas.spec.js
  test/e2e/json-rpc/eth_gasPrice.spec.js
  test/e2e/json-rpc/eth_newBlockFilter.spec.js
Labels: area-testSuite, team-devex

#21063 [MMI] Add Selected-account.component unit test
  ui/components/app/selected-account/__snapshots__/selected-account-component.test.js.snap
  ui/components/app/selected-account/selected-account-component.test.js
  ui/components/app/selected-account/selected-account.component.js
Labels: team-mmi

#20816 Give the user the ability to opt out of 3rd party network validation when adding a new network
  app/_locales/en/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/e2e/tests/add-custom-network.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/pages/confirmation/confirmation.js
  ui/pages/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
  ui/pages/confirmation/templates/add-ethereum-chain.js
  ui/pages/confirmation/templates/index.js
  ui/pages/onboarding-flow/add-network-modal/add-network-modal.test.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/settings/networks-tab/networks-form/networks-form.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/security-tab/security-tab.test.js
  ui/selectors/selectors.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-extension-client, team-extension-platform, needs-dev-review

#21076 Fix custom headers in result pages
  ui/pages/confirmation/confirmation.js
  ui/pages/confirmation/templates/__snapshots__/error.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/success.test.js.snap
  ui/pages/confirmation/templates/error.js
  ui/pages/confirmation/templates/error.test.js
  ui/pages/confirmation/templates/success.js
  ui/pages/confirmation/templates/success.test.js
  ui/pages/confirmation/util.test.ts
  ui/pages/confirmation/util.ts
Labels: team-confirmations-system

#21088 Only get snap name if it's a snap dialog
  ui/pages/confirmation/confirmation.js
Labels: area-snaps, team-snaps

#21044 fix(000): fix lint for confirm-signature-request
  ui/pages/confirm-signature-request/index.js
Labels: team-extension-client

#21089 fix(000): fix lint for signature-request-siwe and metametrics
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/component-library/box/box.types.ts
  ui/contexts/metametrics.js
Labels: team-extension-client, team-extension-platform

#20959 Add snaps name provider
  app/scripts/lib/SnapsNameProvider.test.ts
  app/scripts/lib/SnapsNameProvider.ts
  app/scripts/metamask-controller.js
  shared/constants/names.ts
  shared/constants/snaps/permissions.ts
  test/e2e/snaps/petnames.spec.js
  ui/components/app/modals/contract-details-modal/contract-details-modal.js
  ui/components/app/name/name-details/name-details.tsx
  ui/components/app/name/name.tsx
  ui/components/app/signature-request/signature-request-data/signature-request-data.js
Labels: team-confirmations-system, QA Passed

#20736 fix: rename anonymous transaction events.
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
  shared/constants/transaction.ts
  test/e2e/helpers.js
  test/e2e/metrics/transaction-finalized.spec.js
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR, needs-dev-review
