Repository MetaMask/metamask-extension, pull requests merged in 2023-05, with the labels that each got.

#18894 Part of #17670 Replace Typography with Text component in: nft-default-image.js
  ui/components/app/nft-default-image/__snapshots__/nft-default-image.test.js.snap
  ui/components/app/nft-default-image/nft-default-image.js
Labels: design-system

#18877 Part of #17670 Replace Typography with Text component in: pin-extension.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.js
Labels: design-system

#18752 Part of #17670 , #18714 & #18651 for 3 files.
  ui/components/app/approve-content-card/approve-content-card.js
  ui/pages/swaps/awaiting-signatures/awaiting-signatures.js
  ui/pages/swaps/build-quote/build-quote.js
Labels: design-system

#18899 Transaction cleanup and fix TransactionDetailItem key not unique bug
  ui/components/app/approve-content-card/approve-content-card.js
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js
  ui/components/app/gas-details-item/gas-details-item.js
  ui/components/app/multilayer-fee-message/multi-layer-fee-message.js
  ui/components/app/transaction-detail-item/transaction-detail-item.component.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/send/gas-display/gas-display.js
Labels: area-transactions, team-confirmations-secure-ux-PR

#18839 Part of #17670: Replace Typography with Text component for 'review-spending-cap' & 'tooltip.stories'.
  ui/components/ui/review-spending-cap/review-spending-cap.js
  ui/components/ui/tooltip/tooltip.stories.js
Labels: design-system

#18908 Adding deprecation notice to old Button component
  ui/components/ui/button/button.component.js
  ui/components/ui/button/button.stories.js
Labels: design-system

#18910 Improving code formatting in component-library readme
  ui/components/component-library/README.md
Labels: design-system

#18880 UX: Multichain: Provide localization for the network menu
  app/_locales/en/messages.json
  ui/components/multichain/app-header/app-header.js
Labels: needs-ux-ds-review

#18879 UX: Multichain: Add maximum width for network picker in full screen mode
  ui/components/multichain/app-header/app-header.js
Labels: needs-ux-ds-review

#18846 fix: prevent cancel and speedup transactions to call accept approval
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
Labels: v10.30.0

#18824 fix ff diff generation
  .github/workflows/fitness-functions.yml
Labels: team-extension-client, team-extension-platform

#18978 Fixing broken responsive box background color prop and color fix
  ui/components/ui/box/box.scss
  ui/components/ui/box/box.stories.tsx
  ui/helpers/constants/design-system.ts
Labels: type-bug, design-system, needs-ux-ds-review

#18948 Part of #17670: Replace Typography with Text component in cancel-speedup-popover.js
  ui/components/app/cancel-speedup-popover/cancel-speedup-popover.js
Labels: design-system

#18989 add scuttle exceptions for JSON and Date
  development/build/index.js
Labels: team-extension-client, team-extension-platform

#18981 UX Multichain: Fixed NaN USD issue under Eth when using Fiat
  ui/components/multichain/multichain-token-list-item/__snapshots__/multichain-token-list-item.test.js.snap
  ui/components/multichain/multichain-token-list-item/multichain-token-list-item.js
  ui/components/multichain/multichain-token-list-item/multichain-token-list-item.stories.js
Labels: team-extension-UX, needs-ux-ds-review

#18959 UX Multichain: Removed top border from activity list item
  ui/components/app/transaction-list-item/index.scss
Labels: team-extension-UX, needs-ux-ds-review

#18963 UX Multichain: Account List Search Fix
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-menu/account-list-menu.js
Labels: team-extension-UX, area-multichain, needs-ux-ds-review

#18811 UX: Multichain: Implement Account Details Popover
  app/_locales/en/messages.json
  shared/constants/metametrics.ts
  ui/components/component-library/header-base/header-base.tsx
  ui/components/multichain/account-details/account-details-authenticate.js
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/account-details/account-details-key.js
  ui/components/multichain/account-details/account-details.js
  ui/components/multichain/account-details/account-details.stories.js
  ui/components/multichain/account-details/account-details.test.js
  ui/components/multichain/account-details/index.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/address-copy-button/address-copy-button.js
  ui/components/multichain/index.js
  ui/components/ui/qr-code/qr-code.js
  ui/ducks/app/app.ts
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: team-extension-UX, area-multichain, needs-ux-ds-review

#18843 Fix popover hiding
  ui/components/app/terms-of-use-popup/terms-of-use-popup.js
  ui/components/ui/popover/popover.component.js
Labels: needs-ux-ds-review

#18494 Migrates avatar base to TypeScript
  ui/components/component-library/avatar-base/README.mdx
  ui/components/component-library/avatar-base/__snapshots__/avatar-base.test.tsx.snap
  ui/components/component-library/avatar-base/avatar-base.constants.js
  ui/components/component-library/avatar-base/avatar-base.js
  ui/components/component-library/avatar-base/avatar-base.stories.tsx
  ui/components/component-library/avatar-base/avatar-base.test.tsx
  ui/components/component-library/avatar-base/avatar-base.tsx
  ui/components/component-library/avatar-base/avatar-base.types.ts
  ui/components/component-library/avatar-base/index.js
  ui/components/component-library/avatar-base/index.ts
Labels: design-system

#18347 e2e test for action metrics
  app/scripts/metamask-controller.js
  package.json
  test/e2e/mv3/service-worker-restart.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/webdriver/chrome.js
  test/e2e/webdriver/index.js
Labels: team-extension-client, team-extension-platform

#18742 Part of #17670 & #18714: Replace Typography with Text component: token-allowance.js
  ui/pages/token-allowance/token-allowance.js
Labels: design-system

#19011 [FLASK] Disable RPC test
  test/e2e/snaps/test-snap-rpc.spec.js
Labels: flask

#19010 feature(17946): implement mv3 e2e for popup consistency after service worker restarted
  test/e2e/mv3/service-worker-restart.spec.js
  test/e2e/webdriver/driver.js
Labels: MV3, team-extension-client, team-extension-platform

#18996 UX: Multichain: Focus on test networks when setting is flipped on
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: needs-ux-ds-review

#19006 UX Multichain: Fixed UI updates for header
  ui/components/app/connected-status-indicator/connected-status-indicator.js
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/multichain-connected-site-menu/__snapshots__/multichain-connected-site-menu.test.js.snap
  ui/components/multichain/multichain-connected-site-menu/index.scss
  ui/components/multichain/multichain-connected-site-menu/multichain-connected-site-menu.js
Labels: team-extension-UX, needs-ux-ds-review

#19003 Part of #18714 Replace deprecated design system typography consts with enums for: interactive-replacement-token-modal.js
  ui/components/institutional/interactive-replacement-token-modal/interactive-replacement-token-modal.js
Labels: design-system

#18793 Part of #17670 Replace Typography with Text component for 4 files.
  ui/components/app/modals/customize-nonce/__snapshots__/customize-nonce.test.js.snap
  ui/components/app/modals/customize-nonce/customize-nonce.component.js
  ui/components/app/network-account-balance-header/network-account-balance-header.js
  ui/components/app/signature-request-original/__snapshots__/signature-request-original.test.js.snap
  ui/components/app/signature-request/__snapshots__/signature-request.component.test.js.snap
  ui/components/ui/callout/callout.stories.js
  ui/pages/confirm-signature-request/__snapshots__/index.test.js.snap
Labels: design-system

#18743 Part of #17670: Replace Typography with Text component in smart-transaction-status.js
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.js
Labels: design-system

#19013 Part of #18714: Replacing typography consts with enums
  ui/components/app/asset-list/asset-list.js
Labels: design-system

#19015 chore: refactor connect to dapp action in e2e
  test/e2e/fixture-builder.js
  test/e2e/helpers.js
  test/e2e/metamask-ui.spec.js
  test/e2e/mv3/dapp-interactions.spec.js
  test/e2e/mv3/service-worker-restart.spec.js
  test/e2e/nft/erc1155-interaction.spec.js
  test/e2e/nft/erc721-interaction.spec.js
  test/e2e/tests/add-custom-network.spec.js
  test/e2e/tests/chain-interactions.spec.js
  test/e2e/tests/contract-interactions.spec.js
  test/e2e/tests/custom-token-add-approve.spec.js
  test/e2e/tests/dapp-interactions.spec.js
  test/e2e/tests/dapp-tx-edit.spec.js
  test/e2e/tests/edit-gas-fee.spec.js
  test/e2e/tests/encrypt-decrypt.spec.js
  test/e2e/tests/eth-sign.spec.js
  test/e2e/tests/eth-subscribe.spec.js
  test/e2e/tests/failing-contract.spec.js
  test/e2e/tests/incremental-security.spec.js
  test/e2e/tests/navigate-transactions.spec.js
  test/e2e/tests/permissions.spec.js
  test/e2e/tests/personal-sign.spec.js
  test/e2e/tests/phishing-detection.spec.js
  test/e2e/tests/provider-api.spec.js
  test/e2e/tests/security-provider.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/signature-request.spec.js
  test/e2e/tests/signin-with-ethereum.spec.js
  test/e2e/tests/switch-custom-network.spec.js
Labels: team-extension-client, team-extension-platform

#19000 Fix #18984 - UX: Multichain - Network connection fixes
  app/_locales/en/messages.json
  ui/components/app/loading-network-screen/loading-network-screen.component.js
  ui/components/app/loading-network-screen/loading-network-screen.container.js
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/selectors/selectors.js
Labels: needs-ux-ds-review

#19050 Fix fail to reject/approve multiple approval requests
  app/scripts/metamask-controller.js
Labels: area-UI, PS-team, v10.30.0

#19035 Part of #18714 Replace deprecated design system typography consts with enums in: slider.component.js
  ui/components/ui/slider/slider.component.js
Labels: design-system

#19041 Part of #18714: Replace deprecated design system typography consts with enums
  ui/components/app/confirm-data/confirm-data.js
  ui/components/app/confirm-hexdata/confirm-hexdata.js
Labels: design-system

#18988 UX Multichain: Added extra margin for native token
  ui/pages/home/home.component.js
Labels: team-extension-UX, needs-ux-ds-review

#18633 Working on some lint issues in 2 files.
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js
  ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js
Labels: design-system

#18999 UX: Multichain: Account Details Fixes
  ui/components/app/modals/account-details-modal/account-details-modal.test.js
  ui/components/multichain/account-details/account-details-authenticate.js
  ui/components/multichain/account-details/account-details.js
  ui/components/multichain/account-details/account-details.test.js
  ui/components/ui/editable-label/editable-label.js
  ui/components/ui/editable-label/index.scss
  ui/components/ui/ui-components.scss
  ui/helpers/utils/accounts.js
Labels: needs-ux-ds-review

#18771 Part of #17670 & #18714: Replace Typography with Text component: nft-details.js
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/nft-details.js
Labels: design-system

#18962 Fix #18916 - UX: Multichain: Network picker design updates
  ui/components/multichain/network-list-item/network-list-item.js
  ui/components/multichain/network-list-menu/index.scss
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: needs-ux-ds-review

#18974 UX: Multichain: Ensure network picker renders properly for long and short names
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/app-header.scss
Labels: needs-ux-ds-review

#19038 Part of #18714: Replace deprecated design system typography consts with enums in:custody-labels.js
  ui/components/institutional/custody-labels/custody-labels.js
Labels: design-system

#18909 UX: Multichain: Disable network and account picker when necessary
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/app-header.stories.js
  ui/components/multichain/app-header/app-header.test.js
  ui/pages/routes/routes.component.js
Labels: needs-ux-ds-review

#19058 UX: Multichain: Update deprecated variables
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/multichain-token-list-item/multichain-token-list-item.js
Labels: needs-ux-ds-review

#19063 Fix #19059 - Show network picker when locked
  ui/components/multichain/app-header/app-header.js
Labels: team-extension-client, team-extension-UX, area-multichain

#19062 Fix #19060 - Ensure there's multiple accounts before focusing search
  ui/components/multichain/account-list-menu/account-list-menu.js
Labels: team-extension-client, team-extension-UX, area-multichain, needs-ux-ds-review

#19071 UX Multichain: updated margin top for assets tab
  ui/pages/home/home.component.js
Labels: area-multichain, needs-ux-ds-review

#17539 Replaced all fa-icon-circle with INFO icon
  ui/components/app/advanced-gas-inputs/advanced-gas-inputs.component.js
  ui/components/app/advanced-gas-inputs/index.scss
  ui/components/app/alerts/unconnected-account-alert/unconnected-account-alert.js
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-warning/confirm-page-container-warning.component.js
  ui/components/app/home-notification/home-notification.component.js
  ui/components/app/home-notification/index.scss
  ui/components/app/nfts-detection-notice/nfts-detection-notice.js
  ui/components/app/tab-bar/tab-bar.stories.js
  ui/components/app/transaction-decoding/components/ui/accreditation/accrediation.component.stories.js
  ui/components/app/transaction-decoding/components/ui/accreditation/accreditation.component.js
  ui/components/app/transaction-detail-item/transaction-detail-item.stories.js
  ui/components/app/transaction-detail/transaction-detail.stories.js
  ui/components/ui/account-list/account-list.js
  ui/components/ui/account-list/index.scss
  ui/components/ui/definition-list/definition-list.js
  ui/components/ui/definition-list/definition-list.scss
  ui/components/ui/deprecated-test-networks/deprecated-test-networks.js
  ui/components/ui/deprecated-test-networks/index.scss
  ui/components/ui/tooltip/tooltip.stories.js
  ui/helpers/constants/settings.js
  ui/pages/send/send-content/send-gas-row/__snapshots__/send-gas-row.test.js.snap
  ui/pages/settings/alerts-tab/alerts-tab.js
  ui/pages/settings/alerts-tab/alerts-tab.stories.js
  ui/pages/settings/settings.component.js
  ui/pages/swaps/view-quote/__snapshots__/view-quote-price-difference.test.js.snap
  ui/pages/swaps/view-quote/view-quote-price-difference.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#19034 Modal sub component small updates
  ui/components/component-library/modal-header/__snapshots__/modal-header.test.tsx.snap
  ui/components/component-library/modal-header/modal-header.tsx
  ui/components/component-library/modal-overlay/__snapshots__/modal-overlay.test.tsx.snap
  ui/components/component-library/modal-overlay/modal-overlay.scss
  ui/components/component-library/modal-overlay/modal-overlay.tsx
  ui/components/component-library/text/text.types.ts
  ui/components/ui/popover/index.scss
  ui/css/design-system/z-index.scss
Labels: design-system, needs-ux-ds-review

#18979 Adding ModalFocus component
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy.json
  package.json
  ui/components/component-library/index.js
  ui/components/component-library/modal-focus/README.mdx
  ui/components/component-library/modal-focus/index.ts
  ui/components/component-library/modal-focus/modal-focus.stories.tsx
  ui/components/component-library/modal-focus/modal-focus.test.tsx
  ui/components/component-library/modal-focus/modal-focus.tsx
  ui/components/component-library/modal-focus/modal-focus.types.ts
  yarn.lock
Labels: design-system, needs-ux-ds-review

#19037 Part of #18714: Replace deprecated design system typography consts with enums in: edit-gas-display.component.js
  ui/components/app/edit-gas-display/edit-gas-display.component.js
Labels: design-system

#18741 Part of #17670 & #18714: Replace Typography with Text component in token-details-page.js
  ui/pages/token-details/token-details-page.js
Labels: design-system

#18567 Adopt ApprovalType from core
  app/scripts/background.js
  app/scripts/controllers/app-state.js
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
  ui/components/app/add-network/add-network.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/pages/confirmation/confirmation.js
  ui/pages/confirmation/templates/index.js
  ui/selectors/selectors.js
Labels: area-UI, PS-team

#19087 removed mmi fencing from copy icon in header
  ui/components/app/selected-account/__snapshots__/selected-account-component.test.js.snap
  ui/components/app/selected-account/selected-account.component.js
Labels: needs-ux-ds-review

#18796 feat: Refactor Transaction Confirmation selector
  app/scripts/background.js
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  ui/helpers/utils/confirm-tx.util.ts
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/selectors/approvals.test.ts
  ui/selectors/approvals.ts
  ui/selectors/confirm-transaction.js
  ui/selectors/confirm-transaction.test.js
  ui/selectors/transactions.js
  ui/selectors/transactions.test.js
  ui/store/actions.ts
Labels: area-UI, PS-team

#19078 Add `getCurrentChainId` argument to `SignatureController`
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: area-UI, PS-team

#19105 Update useDraftTransactionGasValues
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js
  ui/components/app/gas-details-item/gas-details-item.js
  ui/hooks/useDraftTransactionWithTxParams.js
Labels: area-UI, PS-team

#18913 [FLASK] `snaps-monorepo@0.33.1-flask.1`
  .yarn/patches/@babel-core-npm-7.21.5-c72c337956.patch
  app/scripts/metamask-controller.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy.json
  package.json
  test/e2e/snaps/test-snap-rpc.spec.js
  test/env.js
  yarn.lock
Labels: flask

#19156 Support hex and number `net_version` responses
  app/scripts/controllers/network/network-controller.test.ts
  app/scripts/controllers/network/network-controller.ts
Labels: type-bug

#19115 Part of #18714 and #17670:set-approval-for-all-warnings
  ui/components/app/set-approval-for-all-warning/index.scss
  ui/components/app/set-approval-for-all-warning/set-approval-for-all-warning.js
  ui/components/component-library/text/text.scss
Labels: design-system

#19144 UX Multichain: updated assets to tokens in home page
  .storybook/test-data.js
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/ph/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  test/e2e/metamask-ui.spec.js
  test/e2e/tests/add-hide-token.spec.js
  test/e2e/tests/custom-token-add-approve.spec.js
  ui/pages/home/home.component.js
Labels: area-multichain, needs-ux-ds-review

#18976 UX: Multichain: Ensure percentage of account name always shown
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/index.scss
Labels: needs-ux-ds-review

#19188 UX: Multichain: Fix prop error from invalid Box prop
  ui/components/multichain/multichain-token-list-item/multichain-token-list-item.js
Labels: needs-ux-ds-review

#19150 UX: Multichain: Don't filter out custom Mainnet RPCs
  test/data/mock-state.json
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/selectors/selectors.js
Labels: needs-ux-ds-review

#19133 Migrate remaining design system constants to enums
  ui/components/ui/box/README.mdx
  ui/components/ui/box/box.d.ts
  ui/components/ui/box/box.js
  ui/components/ui/box/box.stories.tsx
  ui/components/ui/box/box.test.tsx
  ui/helpers/constants/design-system.ts
Labels: design-system

#19185 disable pr labeler
  .github/workflows/label-prs.yml
Labels: team-extension-client, team-extension-platform

#17610 Disable Previous Button on First Page
  ui/pages/create-account/connect-hardware/account-list.js
  ui/pages/create-account/connect-hardware/account-list.test.js
  ui/pages/create-account/connect-hardware/index.js
Labels: area-hardware, team-key-management

#18863 [Bug]: Enabling the display of token total in SetApprovalForAll
  ui/components/app/confirm-page-container/confirm-page-container.component.js
Labels: type-bug, team-confirmations-secure-ux-PR

#19160 Cleanup PR: Renaming getNetworkName and moving that to utils file
  ui/components/app/dropdowns/network-dropdown.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request/signature-request.component.js
  ui/helpers/utils/util.js
  ui/helpers/utils/util.test.js
Labels: team-confirmations-secure-ux-PR

#19191 [FLASK] Create E2E test for ethereum_provider endowment
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-ethprovider.spec.js
Labels: flask

#18855 Fix contract interaction recipient and contract address
  shared/modules/hexstring-utils.ts
  ui/pages/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/swaps/fee-card/fee-card.js
Labels: type-bug, area-transactions, team-confirmations-secure-ux, team-confirmations-secure-ux-PR, QA Passed

#19196 feature(16691): mv3 e2e test for phishing warning page when sw restarts
  test/e2e/helpers.js
  test/e2e/mv3/dapp-interactions.spec.js
  test/e2e/mv3/phishing-warning-sw-restart.spec.js
  test/e2e/mv3/service-worker-restart.spec.js
  test/e2e/tests/phishing-detection.spec.js
  test/e2e/webdriver/driver.js
Labels: area-UI, PS-team, team-extension-client, team-extension-platform

#18983 fix: support alerts confirmation page without pending transactions
  coverage-targets.js
  ui/pages/confirmation/confirmation.js
  ui/pages/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/switch-ethereum-chain.test.js.snap
  ui/pages/confirmation/templates/add-ethereum-chain.js
  ui/pages/confirmation/templates/add-ethereum-chain.test.js
  ui/pages/confirmation/templates/index.js
  ui/pages/confirmation/templates/switch-ethereum-chain.js
  ui/pages/confirmation/templates/switch-ethereum-chain.test.js
Labels: area-UI, PS-team

#19020 Adding Modal component
  ui/components/component-library/index.js
  ui/components/component-library/modal-content/README.mdx
  ui/components/component-library/modal-content/__snapshots__/modal-content.test.tsx.snap
  ui/components/component-library/modal-content/modal-content.scss
  ui/components/component-library/modal-content/modal-content.stories.tsx
  ui/components/component-library/modal-content/modal-content.test.tsx
  ui/components/component-library/modal-content/modal-content.tsx
  ui/components/component-library/modal-content/modal-content.types.ts
  ui/components/component-library/modal/README.mdx
  ui/components/component-library/modal/__snapshots__/modal.test.tsx.snap
  ui/components/component-library/modal/index.ts
  ui/components/component-library/modal/modal.context.ts
  ui/components/component-library/modal/modal.stories.tsx
  ui/components/component-library/modal/modal.test.tsx
  ui/components/component-library/modal/modal.tsx
  ui/components/component-library/modal/modal.types.ts
Labels: area-UI, design-system, needs-ux-ds-review

#19213 [FLASK] Create E2E test for snaps network_access endowment
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-networkaccess.spec.js
Labels: flask

#19176 UX Multichain: updated border top for activity list
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/ui/list-item/__snapshots__/list-item.component.test.js.snap
  ui/components/ui/list-item/index.scss
  ui/components/ui/list-item/list-item.component.js
Labels: type-bug, team-extension-UX, area-multichain, v10.31.0, needs-ux-ds-review

#19240 Moving `RESIZE` constant to textarea component folder
  ui/components/ui/textarea/textarea.constants.js
  ui/components/ui/textarea/textarea.js
  ui/components/ui/textarea/textarea.stories.js
  ui/components/ui/textarea/textarea.test.js
  ui/helpers/constants/design-system.ts
Labels: design-system

#19204 Multichain: UX: Snaps: Add Notifications to Global Menu
  ui/components/multichain/global-menu/global-menu.js
Labels: needs-ux-ds-review

#19236 UX: Multichain: Only show the account picker with a selected identity
  ui/components/multichain/app-header/app-header.js
Labels: needs-ux-ds-review

#19132 feat(accounts): import account without password
  app/_locales/en/messages.json
  ui/pages/create-account/import-account/__snapshots__/json.test.tsx.snap
  ui/pages/create-account/import-account/json.js
  ui/pages/create-account/import-account/json.test.tsx
Labels: type-bug, Sev1-high, team-key-management

#19280 feature(17901): fix test/e2e/tests/add-account.spec.js
  test/e2e/helpers.js
  test/e2e/tests/add-account.spec.js
  test/e2e/tests/from-import-ui.spec.js
  test/e2e/tests/simple-send.spec.js
Labels: team-extension-client, team-extension-platform

#19269 UX Multichain: Added Tooltip for AvatarNetwork in Header
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/app-header.scss
Labels: team-extension-UX, area-multichain, needs-ux-ds-review

#19287 feature(17901): disable hardware wallet test with trezor in mv3
  test/e2e/helpers.js
  test/e2e/metamask-ui.spec.js
  test/e2e/tests/add-account.spec.js
  test/e2e/tests/from-import-ui.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/tests/onboarding.spec.js
Labels: team-extension-client, team-extension-platform

#19245 Part of #18714: Replacing deprecated constants in `Popover` folder
  ui/components/component-library/popover/popover.stories.tsx
  ui/components/component-library/popover/popover.tsx
Labels: design-system

#19330 feature(17901): fix address-book `Sends to an address book entry` e2e against MV3 build
  test/e2e/helpers.js
  test/e2e/tests/address-book.spec.js
  test/e2e/tests/contract-interactions.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/tests/navigate-transactions.spec.js
  test/e2e/tests/onboarding.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/send-hex-address.spec.js
  test/e2e/tests/simple-send.spec.js
Labels: team-extension-client, team-extension-platform

#19292 feature(17901): fix failing network error and remove duplicated e2e for mv3
  test/e2e/mv3/dapp-interactions.spec.js
  test/e2e/tests/network-error.spec.js
Labels: team-extension-client, team-extension-platform

#18835 [FLASK] Add Snaps privacy warning on snap install
  app/_locales/en/messages.json
  app/scripts/controllers/app-state.js
  app/scripts/controllers/app-state.test.js
  app/scripts/metamask-controller.js
  test/e2e/fixture-builder.js
  ui/components/app/permission-page-container/permission-page-container.component.js
  ui/components/app/snaps/snap-privacy-warning/index.js
  ui/components/app/snaps/snap-privacy-warning/snap-privacy-warning.js
  ui/components/app/snaps/snap-privacy-warning/snap-privacy-warning.stories.js
  ui/components/app/snaps/snap-privacy-warning/snap-privacy-warning.test.js
  ui/ducks/app/app.ts
  ui/pages/permissions-connect/permissions-connect.component.js
  ui/pages/permissions-connect/permissions-connect.container.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: flask, team-snaps

#19339 Part of #18714: Replacing deprecated constants in `Modal-Header` folder
  ui/components/component-library/modal-header/modal-header.stories.tsx
Labels: design-system
