Repository MetaMask/metamask-extension, pull requests merged in 2023-10, with the labels that each got.

#21061 Update Snaps list UI
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/pages/settings/snaps/snaps-list-tab/index.scss
  ui/pages/settings/snaps/snaps-list-tab/snap-list-tab.js
Labels: team-snaps

#21138 [MMI] Add Account-list-item-menu unit test
  test/data/mock-state.json
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.test.js
  ui/components/multichain/account-list-menu/account-list-menu.test.js
  ui/components/multichain/create-account/create-account.test.js
  ui/pages/send/send-content/add-recipient/__snapshots__/add-recipient.component.test.js.snap
  ui/selectors/selectors.test.js
Labels: team-mmi

#21148 [MMI] Add Confirm-approve-content.component unit test
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.test.js
Labels: team-mmi

#21049 Fix #19371 - Provide conversion buttons for empty accounts
  app/_locales/en/messages.json
  app/images/token-list-buy-background.png
  app/images/token-list-nfts-background.png
  app/images/token-list-receive-background.png
  ui/components/app/asset-list/__snapshots__/asset-list.test.js.snap
  ui/components/app/asset-list/asset-list.buy-receive.test.js
  ui/components/app/asset-list/asset-list.js
  ui/components/app/asset-list/asset-list.test.js
  ui/components/app/nfts-tab/nfts-tab.js
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/components/multichain/asset-list-conversion-button/asset-list-conversion-button.js
  ui/components/multichain/asset-list-conversion-button/asset-list-conversion-button.scss
  ui/components/multichain/asset-list-conversion-button/asset-list-conversion-button.stories.js
  ui/components/multichain/asset-list-conversion-button/index.js
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/receive-modal/index.js
  ui/components/multichain/receive-modal/receive-modal.js
  ui/components/multichain/receive-modal/receive-modal.stories.js
  ui/components/multichain/receive-modal/receive-modal.test.js
Labels: team-extension-UX, needs-ux-ds-review

#21091 fix: display warning when sending zero tokens
  app/_locales/en/messages.json
  ui/components/app/transaction-alerts/transaction-alerts.js
  ui/components/app/transaction-alerts/transaction-alerts.stories.js
  ui/components/app/transaction-alerts/transaction-alerts.test.js
  ui/pages/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: team-extension-UX, needs-ux-ds-review

#20834 [MMI] Deletes unnecessary logic for mmi
  app/scripts/controllers/mmi-controller.js
  app/scripts/lib/rpc-method-middleware/handlers/index.js
  app/scripts/lib/rpc-method-middleware/handlers/institutional/mmi-open-swaps.js
  app/scripts/metamask-controller.js
Labels: team-mmi

#21045 Add privacy setting to disable external name sources
  app/_locales/en/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/metamask-controller.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/store/actions.ts
  yarn.lock
Labels: team-confirmations-system

#21164 [MMI] - Updates the mmi packages, containing a small fix
  app/_locales/en/messages.json
  package.json
  yarn.lock
Labels: team-mmi, release-11.2.0

#21165 Bump snaps packages
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: team-snaps

#21119 fix(action): update fetch-depth parameter to fetch only the last commit
  .github/workflows/check-pr-labels.yml
Labels: team-extension-client, team-extension-platform

#21152 Stabilize e2e tests for phishing detection
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
Labels: team-extension-client, team-extension-platform, in-progress

#20916 bump `@metamask/assets-controllers` to ^13.0.0
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/lib/rpc-method-middleware/handlers/watch-asset.js
  app/scripts/lib/rpc-method-middleware/handlers/watch-asset.test.js
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/app/detected-token/detected-token.js
  ui/components/app/nfts-items/nfts-items.js
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
  ui/ducks/swaps/swaps.js
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: team-devex

#21159 Wait for Snap accounts to be removed before removing the snap
  .yarn/patches/@metamask-eth-keyring-controller-npm-13.0.1-06ff83faad.patch
  package.json
  ui/store/actions.ts
  yarn.lock
Labels: type-bug, team-accounts

#21177 Revert test additions from 16a0d16ea
  test/e2e/tests/ipfs-toggle.spec.js
Labels: team-extension-platform

#21084 Synchronise address book and name controller
  app/scripts/lib/AddressBookPetnamesBridge.test.ts
  app/scripts/lib/AddressBookPetnamesBridge.ts
  app/scripts/metamask-controller.js
  app/scripts/migrations/100.test.ts
  app/scripts/migrations/100.ts
  app/scripts/migrations/index.js
Labels: team-confirmations-system

#21120 documenting network scenarios
  test/scenarios/7. network/add custom network from dApp.csv
  test/scenarios/7. network/add custom network manually.csv
  test/scenarios/7. network/add network from the list of popular networks.csv
  test/scenarios/7. network/delete networks from the dropdown list.csv
  test/scenarios/7. network/delete networks in Settings.csv
  test/scenarios/7. network/switching networks.csv
  test/scenarios/7. network/update networks.csv
Labels: team-extension-client, team-extension-platform

#21182 Ignored ripple-lib deprecation advisory, as we do not depend on it in MetaMask
  .yarnrc.yml
Labels: team-extension-platform

#21077 Add logs on new extension version updates and put them in state logs
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  shared/constants/logs.ts
  ui/index.js
Labels: team-confirmations-system

#21167 Add Snaps directory link to the banner when at least one Snap is installed
  ui/pages/settings/snaps/snaps-list-tab/snap-list-tab.js
Labels: team-snaps

#21101 fix: add missing update available and arrow icon
  ui/pages/keyring-snaps/index.scss
  ui/pages/keyring-snaps/new-snap-account-page/new-snap-account-page.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/header.tsx
  ui/pages/keyring-snaps/snap-card/__snapshots__/snap-card.test.tsx.snap
  ui/pages/keyring-snaps/snap-card/snap-card.scss
  ui/pages/keyring-snaps/snap-card/snap-card.test.tsx
  ui/pages/keyring-snaps/snap-card/snap-card.tsx
Labels: team-accounts

#21095 Add Snap website field to Snap settings page and make UI changes
  app/scripts/metamask-controller.js
  test/data/mock-state.json
  ui/components/app/snaps/snap-authorship-expanded/snap-authorship-expanded.js
  ui/pages/settings/snaps/view-snap/index.scss
  ui/pages/settings/snaps/view-snap/view-snap.test.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: team-snaps

#20856 flow to report false positive for blockaid
  app/_locales/en/messages.json
  ui/components/app/security-provider-banner-alert/__snapshots__/security-provider-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.js
  ui/components/app/signature-request/signature-request.js
  ui/components/app/transaction-alerts/transaction-alerts.js
  ui/helpers/constants/zendesk-url.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
Labels: team-confirmations-secure-ux-PR, QA Passed

#21170 Version v11.1.2
  .yarnrc.yml
  CHANGELOG.md
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/ipfs-toggle.spec.js
  ui/components/app/nfts-items/nfts-items.js
  ui/pages/institutional/custody/custody.js
  yarn.lock
Labels: team-mmi

#21141 Rename `coreKeyringController` to `keyringController`
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-shared-libraries

#21197 Fix TokenRatesController polling no longer starting automatically
  app/scripts/metamask-controller.js
Labels: team-devex, team-assets

#21215 add audit exclusion for ethereum-cryptography (deprecation)
  .yarnrc.yml
Labels: team-extension-platform

#21214 Fix next button key event handling on token approval page
  ui/components/app/desktop-enable-button/__snapshots__/desktop-enable-button.component.test.js.snap
  ui/components/app/modal/__snapshots__/modal.component.test.js.snap
  ui/components/app/modals/confirm-delete-network/__snapshots__/confirm-delete-network.test.js.snap
  ui/components/app/modals/confirm-remove-account/__snapshots__/confirm-remove-account.test.js.snap
  ui/components/app/modals/confirm-reset-account/__snapshots__/confirm-reset-account.test.js.snap
  ui/components/app/modals/customize-nonce/__snapshots__/customize-nonce.test.js.snap
  ui/components/app/modals/hide-token-confirmation-modal/__snapshots__/hide-token-confirmation-modal.test.js.snap
  ui/components/app/modals/reject-transactions/__snapshots__/reject-transactions.test.js.snap
  ui/components/app/modals/transaction-confirmed/__snapshots__/transaction-confirmed.test.js.snap
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/signature-request-original/__snapshots__/signature-request-original.test.js.snap
  ui/components/app/signature-request-siwe/__snapshots__/signature-request-siwe.test.js.snap
  ui/components/app/signature-request/__snapshots__/signature-request.test.js.snap
  ui/components/app/transaction-breakdown/transaction-breakdown-row/__snapshots__/transaction-breakdown-row.component.test.js.snap
  ui/components/ui/button/button.component.js
  ui/components/ui/page-container/page-container-footer/__snapshots__/page-container-footer.component.test.js.snap
  ui/pages/confirm-add-suggested-nft/__snapshots__/confirm-add-suggested-nft.test.js.snap
  ui/pages/confirm-decrypt-message/__snapshots__/confirm-decrypt-message.component.test.js.snap
  ui/pages/confirm-encryption-public-key/__snapshots__/confirm-encryption-public-key.component.test.js.snap
  ui/pages/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirm-signature-request/__snapshots__/index.test.js.snap
  ui/pages/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/create-snap-account.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/error.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/success.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/switch-ethereum-chain.test.js.snap
  ui/pages/desktop-error/__snapshots__/desktop-error.test.js.snap
  ui/pages/onboarding-flow/add-network-modal/__snapshots__/add-network-modal.test.js.snap
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
  ui/pages/onboarding-flow/metametrics/__snapshots__/metametrics.test.js.snap
  ui/pages/onboarding-flow/recovery-phrase/__snapshots__/review-recovery-phrase.test.js.snap
  ui/pages/send/send-footer/__snapshots__/send-footer.test.js.snap
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/swaps/swaps-footer/__snapshots__/swaps-footer.test.js.snap
  ui/pages/token-allowance/__snapshots__/token-allowance.test.js.snap
  ui/pages/unlock-page/__snapshots__/unlock-page.test.js.snap
Labels: team-confirmations-secure-ux, release-blocker, needs-dev-review, release-11.3.0

#21186 [MMI] Removing unused assets and changed mmi logo with orange beard
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/build-types/mmi/images/check-green-solid.svg
  app/build-types/mmi/images/close-red-solid.svg
  app/build-types/mmi/images/custodialWallet.svg
  app/build-types/mmi/images/icon-128.png
  app/build-types/mmi/images/icon-16.png
  app/build-types/mmi/images/icon-19.png
  app/build-types/mmi/images/icon-32.png
  app/build-types/mmi/images/icon-38.png
  app/build-types/mmi/images/icon-48.png
  app/build-types/mmi/images/icon-512.png
  app/build-types/mmi/images/icon-64.png
  app/build-types/mmi/images/icons/portfolio-dashboard.svg
  app/build-types/mmi/images/info-logo.png
  app/build-types/mmi/images/jupiter.svg
  app/build-types/mmi/images/mmi-mascot.json
  app/build-types/mmi/images/mmi-swaps.svg
  app/build-types/mmi/images/portfolio.svg
  app/build-types/mmi/mmi-mascot.json
  app/scripts/metamask-controller.js
  package.json
  shared/notifications/institutional/index.js
  ui/components/component-library/icon/icon.types.ts
  ui/helpers/utils/build-types.js
  yarn.lock
Labels: team-mmi

#21233 Fix SnapDelineator Proptype Error
  ui/components/app/snaps/snap-delineator/snap-delineator.js
Labels: team-accounts

#21172 Add privacy snapshot and fail E2E test on new host requested
  privacy-snapshot.json
  test/e2e/helpers.js
  test/e2e/mock-e2e.js
  test/e2e/run-all.js
  test/e2e/run-e2e-test.js
Labels: team-extension-platform

#21226 Feature: Set different Keyring Snap Registry for Main and Flask builds
  builds.yml
Labels: team-accounts

#21212 backup and restore testing scenarios documentation
  test/scenarios/8. backup/backup user data.csv
  test/scenarios/8. backup/restore user data.csv
Labels: team-extension-platform, needs-dev-review

#21211 metrics testing scenarios documentation
  test/scenarios/9. metrics/send event metrics.csv
Labels: team-extension-platform, needs-dev-review

#21210 address book testing scenarios documentation
  test/scenarios/10. address-book/add a contact to the address book.csv
  test/scenarios/10. address-book/remove a contact from the address book.csv
  test/scenarios/10. address-book/update a contact in the address book.csv
Labels: team-extension-platform, needs-dev-review

#21229 Fix/ap 63/add message to loading for hw and snap accounts
  app/_locales/en/messages.json
  ui/components/ui/loading-screen/loading-screen.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirm-transaction/__snapshots__/confirm-transaction.test.js.snap
  ui/store/actions.ts
Labels: team-accounts

#21199 [FLASK] Create E2E for revoking snap permission
  test/e2e/snaps/test-snap-revoke-perm.spec.js
  ui/components/app/permission-cell/permission-cell-options.js
Labels: flask, team-snaps

#20917 Bump @metamask/providers to v13.0.0
  package.json
  yarn.lock
Labels: dependencies, team-devex

#21204 [MMI] Adding break word CSS to long names
  ui/components/app/connected-accounts-list/index.scss
  ui/components/ui/editable-label/editable-label.js
Labels: ux-enhancement, team-extension-UX, needs-ux-ds-review, team-mmi

#21110 fix: improve the flakiest e2e tests
  test/e2e/flask/petnames.spec.js
  test/e2e/helpers.js
  test/e2e/metrics/transaction-finalized.spec.js
  test/e2e/mv3/phishing-warning-sw-restart.spec.js
  test/e2e/swaps/swaps-notifications.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/tests/multiple-transactions.spec.js
  test/e2e/tests/onboarding.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/send-hex-address.spec.js
Labels: team-accounts

#21230 Improve snap export metrics throttling
  app/scripts/metamask-controller.js
Labels: team-snaps

#21235 Block explorer e2e
  privacy-snapshot.json
  test/e2e/fixture-builder.js
  test/e2e/mock-e2e.js
  test/e2e/tests/block-explorer.spec.js
Labels: team-extension-platform

#21074 Change in experimental settings designs for enabling blockaid and opensea
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#21254 Remove usage of `subject-metadata-controller` package
  app/scripts/metamask-controller.js
  app/scripts/migrations/069.js
  app/scripts/migrations/069.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/app/permissions-connect-header/permissions-connect-header.component.js
  ui/hooks/useOriginMetadata.js
  ui/pages/permissions-connect/permissions-connect.component.js
  ui/pages/permissions-connect/permissions-connect.container.js
  ui/selectors/selectors.js
  yarn.lock
Labels: team-snaps

#21222 feat: update snap label to include "Beta" keyword
  test/e2e/accounts/test-snap-accounts.spec.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.test.js
Labels: type-enhancement, team-accounts, high-priority

#21232 fix: make snap card clickable
  ui/pages/keyring-snaps/snap-card/snap-card.test.tsx
  ui/pages/keyring-snaps/snap-card/snap-card.tsx
Labels: team-accounts

#21252 feat: show checksum address when removing snap account
  ui/pages/remove-snap-account/remove-snap-account.test.tsx
  ui/pages/remove-snap-account/remove-snap-account.tsx
Labels: team-accounts

#21260 network details validation for json rpc req
  test/e2e/tests/add-custom-network.spec.js
  ui/pages/confirmation/templates/add-ethereum-chain.js
Labels: team-extension-client, team-extension-platform

#20998 Add keyring snap removal confirmation
  app/_locales/en/messages.json
  test/e2e/accounts/test-remove-accounts-snap.spec.js
  test/e2e/accounts/test-snap-accounts.spec.js
  ui/components/app/modals/keyring-snap-removal-modal/index.ts
  ui/components/app/modals/keyring-snap-removal-modal/keyring-snap-removal-result-modal.test.tsx
  ui/components/app/modals/keyring-snap-removal-modal/keyring-snap-removal-result-modal.tsx
  ui/components/app/snaps/keyring-snap-removal-warning/index.ts
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-account-list-item.tsx
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.stories.js
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.test.tsx
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.tsx
  ui/components/app/snaps/snap-settings-card/snap-settings-card.js
  ui/ducks/app/app.ts
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/pages/settings/snaps/view-snap/constants.ts
  ui/pages/settings/snaps/view-snap/view-snap.js
  ui/selectors/selectors.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: DO-NOT-MERGE, team-accounts, QA'd but questions, high-priority

#21181 Fix #21179 - Change Optimism chain name to OP Mainnet
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/constants/network.ts
  ui/pages/swaps/fee-card/fee-card.js
  ui/pages/swaps/prepare-swap-page/review-quote.js
Labels: team-extension-UX, needs-ux-ds-review

#21267 Fix: Select snap account after being added
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/metamask-controller.js
  test/e2e/accounts/test-create-snap-account.spec.js
Labels: team-accounts

#21253 [MMI] Auto-switching to the first custodian wallet when importing accounts
  ui/pages/institutional/custody/custody.js
Labels: team-mmi

#21255 Bump snaps packages
  .yarn/patches/lavamoat-core-npm-14.4.1-c4e8bbb016.patch
  .yarn/patches/typescript-npm-4.4.4-3fedcc07a3.patch
  app/scripts/controllers/permissions/specifications.test.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/snaps/permissions.ts
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/components/app/snaps/snap-ui-image/index.ts
  ui/components/app/snaps/snap-ui-image/snap-ui-image.tsx
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  yarn.lock
Labels: team-snaps

#21262 [MMI] Sorts list elements alphabetically
  ui/pages/institutional/connect-custody/account-list.js
Labels: team-mmi

#21086 test:e2e: create Security Alert Blockaid tests for eth_sendTransaction requests and no PPOM response request
  test/e2e/fixture-builder.js
  test/e2e/flask/ppom-toggle-settings.spec.js
  test/e2e/mock-server-json-rpc.ts
  test/e2e/run-all.js
  test/e2e/snaps/ppom-blockaid-alert.spec.js
  test/e2e/snaps/ppom-malicious-erc20-approval.spec.js
  test/e2e/snaps/ppom-malicious-erc20-transfer.spec.js
  test/e2e/tests/ens.spec.js
  test/mocks/json-rpc-result.ts
Labels: area-testSuite, area-transactions, team-confirmations-secure-ux-PR

#21294 Bump `metamask/slip44`
  package.json
  yarn.lock
Labels: team-snaps

#21283 [MMI] Hides the whatsNewPopup for mmi
  ui/pages/home/home.component.js
Labels: team-mmi

#21097 Adding security alert setting to setting search
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/tests/settings-search.spec.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/helpers/constants/settings.js
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
Labels: team-confirmations-secure-ux, needs-dev-review

#21223 UX: Multichain: Add separator under 'View on Explorer'
  ui/components/multichain/global-menu/global-menu.js
Labels: team-extension-UX, needs-ux-ds-review

#21241 ci(codeowners): add privacy reviewers to codeowners
  .github/CODEOWNERS
Labels: team-extension-platform

#21246 Add `getAllowedKeyringMethods` hook for Account Snaps
  app/scripts/lib/keyring-snaps-permissions.test.ts
  app/scripts/lib/keyring-snaps-permissions.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  package.json
  shared/constants/snaps/permissions.ts
  test/e2e/accounts/settings-add-snap-account-toggle.spec.js
  test/e2e/accounts/utils.ts
  yarn.lock
Labels: type-enhancement, team-accounts, high-priority

#21153 fix: rm not supported currencies
  ui/helpers/constants/available-conversions.json
Labels: team-extension-UX, needs-ux-ds-review

#21205 fix: display network icon
  ui/components/app/confirm-page-container/confirm-detail-row/__snapshots__/confirm-detail-row.component.test.js.snap
  ui/components/app/confirm-page-container/confirm-detail-row/confirm-detail-row.component.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-fee-popover.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.test.js
  ui/components/app/modals/cancel-transaction/cancel-transaction-gas-fee/cancel-transaction-gas-fee.component.test.js
  ui/components/app/transaction-breakdown/transaction-breakdown.test.js
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.test.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/pages/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/routes/routes.component.test.js
  ui/pages/send/send-content/send-content.component.test.js
  ui/pages/send/send.test.js
Labels: team-extension-UX, needs-ux-ds-review

#21147 fix: send tokens with decimals > 20
  app/scripts/controllers/swaps.test.js
  shared/modules/Numeric.test.ts
  shared/modules/Numeric.ts
Labels: team-extension-UX

#21239 [MMI] fix custody confirm link missing locale and variable
  app/_locales/en/messages.json
  app/scripts/controllers/mmi-controller.js
  ui/components/institutional/custody-confirm-link-modal/custody-confirm-link-modal.js
  ui/components/institutional/interactive-replacement-token-modal/interactive-replacement-token-modal.js
  ui/pages/home/home.container.js
  ui/pages/institutional/custody/custody.js
  ui/pages/institutional/interactive-replacement-token-page/interactive-replacement-token-page.js
  ui/pages/institutional/interactive-replacement-token-page/interactive-replacement-token-page.test.js
Labels: team-mmi, release-11.4.0

#21298 Remove snap errors from home component
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/metamask-controller.js
  test/e2e/snaps/test-snap-error.spec.js
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/store/actions.ts
Labels: team-snaps

#21318 Master sync following v11.1.1 and v11.1.2
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#21319 fix: center messages for loading spinner
  ui/components/ui/loading-screen/loading-screen.component.js
  ui/pages/confirm-transaction/__snapshots__/confirm-transaction.test.js.snap
Labels: team-accounts

#21151 It should not be possible for user to enable both openSea and blockaid security providers
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#21269 fix: Error prompt when canceling a transaction
  ui/store/actions.ts
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR, needs-dev-review

#21231 Update transaction insights dropdown
  ui/components/ui/tabs/snaps/dropdown-tab/dropdown-tab.js
  ui/components/ui/tabs/snaps/dropdown-tab/dropdown-tab.test.js
  ui/components/ui/tabs/snaps/dropdown-tab/index.scss
  ui/components/ui/ui-components.scss
Labels: team-snaps

#21264 fix: reset asset state on selectAccountChanged
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
Labels: team-extension-UX, needs-ux-ds-review

#21202 UX: Multichain: Display total account balance in account menu
  ui/components/app/asset-list/__snapshots__/asset-list.test.js.snap
  ui/components/app/asset-list/asset-list.js
  ui/components/app/asset-list/asset-list.test.js
  ui/components/app/detected-token/detected-token-values/detected-token-values.js
  ui/components/app/token-list-display/token-list-display.js
  ui/components/app/wallet-overview/token-overview.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/balance-overview/__snapshots__/balance-overview.test.js.snap
  ui/components/multichain/balance-overview/balance-overview.js
  ui/components/multichain/balance-overview/balance-overview.stories.js
  ui/components/multichain/balance-overview/balance-overview.test.js
  ui/components/ui/token-balance/token-balance.js
  ui/hooks/useAccountTotalFiatBalance.js
  ui/hooks/useAccountTotalFiatBalance.test.js
  ui/hooks/useAssetDetails.js
  ui/hooks/useTokenTracker.js
  ui/pages/swaps/build-quote/build-quote.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
  ui/pages/swaps/prepare-swap-page/review-quote.js
  ui/pages/swaps/view-quote/view-quote.js
  ui/pages/token-details/token-details-page.js
  ui/selectors/selectors.js
Labels: team-extension-UX, needs-ux-ds-review

#21274 feat: accounts API feedback
  app/_locales/en/messages.json
  ui/pages/keyring-snaps/constants.ts
  ui/pages/keyring-snaps/new-snap-account-page/new-snap-account-page.scss
  ui/pages/keyring-snaps/new-snap-account-page/new-snap-account-page.tsx
  ui/pages/keyring-snaps/snap-card/__snapshots__/snap-card.test.tsx.snap
  ui/pages/keyring-snaps/snap-card/snap-card.scss
  ui/pages/keyring-snaps/snap-card/snap-card.tsx
Labels: team-accounts

#20751 UX Multichain: Added Footer to the home screen
  ui/components/app/multiple-notifications/index.scss
  ui/components/app/multiple-notifications/multiple-notifications.component.js
  ui/components/multichain/app-footer/__snapshots__/app-footer.test.js.snap
  ui/components/multichain/app-footer/app-footer.js
  ui/components/multichain/app-footer/app-footer.scss
  ui/components/multichain/app-footer/app-footer.test.js
  ui/css/itcss/components/newui-sections.scss
  ui/pages/routes/routes.component.js
Labels: team-extension-UX, needs-ux-ds-review

#21295 Test scenarios documentation update
  test/scenarios/3. transactions/cancel transaction.csv
  test/scenarios/3. transactions/send erc20 token origin MM.csv
  test/scenarios/3. transactions/send erc721 token origin MM.csv
  test/scenarios/3. transactions/send native token origin MM.csv
  test/scenarios/3. transactions/speed up transaction.csv
  test/scenarios/4. tokens/import erc1155 token origin MM.csv
  test/scenarios/4. tokens/import erc20 token origin MM.csv
  test/scenarios/4. tokens/import erc721 token origin MM.csv
  test/scenarios/5. ens/name resolution.csv
  test/scenarios/9. metrics/send event metrics.csv
Labels: area-documentation, team-extension-platform, release-11.4.0

#21324 Fix breaking jest test for asset-list
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/hooks/useAccountTotalFiatBalance.test.js
Labels: team-extension-UX, needs-ux-ds-review

#19908 Add EIP-6963 Provider
  app/scripts/inpage.js
  builds.yml
  development/build/manifest.js
  development/build/scripts.js
  development/build/utils.js
  package.json
  test/e2e/provider/eip-6963.spec.js
  yarn.lock
Labels: team-devex

#21271 fix: flaky E2E "tests notifications for verified token on 1 source and price difference"
  test/e2e/swaps/swaps-notifications.spec.js
Labels: team-accounts

#21184 Github action to check issue body matches issues templates and add labels to issue when needed
  .github/scripts/check-issue-template-and-add-labels.ts
  .github/workflows/check-issue-template-and-add-labels.yml
  package.json
Labels: team-extension-client, team-extension-platform, needs-dev-review

#21321 adding new test scenarios
  test/scenarios/4. tokens/import erc20 token origin dapp.csv
  test/scenarios/4. tokens/importing erc721 token origin dapp.csv
  test/scenarios/9. metrics/send event metrics.csv
Labels: area-documentation, team-extension-client, team-extension-platform, release-11.4.0

#21322 Update copy for account snaps
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/accounts/settings-add-snap-account-toggle.spec.js
  ui/pages/keyring-snaps/add-snap-account-modal/add-snap-account-modal.tsx
  ui/pages/keyring-snaps/new-snap-account-page/new-snap-account-page.scss
  ui/pages/keyring-snaps/new-snap-account-page/new-snap-account-page.test.tsx
  ui/pages/keyring-snaps/new-snap-account-page/new-snap-account-page.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/__snapshots__/snap-account-detail-page.test.tsx.snap
  ui/pages/keyring-snaps/snap-card/__snapshots__/snap-card.test.tsx.snap
  ui/pages/keyring-snaps/snap-card/snap-card.scss
  ui/pages/keyring-snaps/snap-card/snap-card.tsx
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
Labels: team-accounts

#21244 Add Account Snap MetaMetrics data to transactions and signatures
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/snap-keyring/metrics.ts
  app/scripts/metamask-controller.js
  test/e2e/metrics/signature-approved.spec.js
Labels: team-accounts, needs-dev-review

#21341 [MMI] Updates mmi packages to latest version
  package.json
  yarn.lock
Labels: team-mmi, release-11.3.0

#21193 Adding alerts for transaction inside deprecation
  app/_locales/en/messages.json
  ui/components/app/confirm-data/confirm-data.js
  ui/components/app/confirm-data/index.scss
  ui/components/app/confirm-data/transaction-insights-deprecation-alert.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#21353 Update ppom validator package
  package.json
  yarn.lock
Labels: team-confirmations-secure-ux, needs-dev-review

#21314 Use getIsUnlocked instead of inline selector
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/pages/routes/routes.container.js
Labels: team-extension-UX, needs-ux-ds-review

#21312 feat: Snap account async transaction redirect
  app/_locales/en/messages.json
  app/scripts/background.js
  app/scripts/lib/keyring-snaps-permissions.test.ts
  app/scripts/lib/keyring-snaps-permissions.ts
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/lib/snap-keyring/utils/isBlockedUrl.test.ts
  app/scripts/lib/snap-keyring/utils/isBlockedUrl.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  package.json
  privacy-snapshot.json
  shared/constants/app.ts
  test/e2e/accounts/test-snap-accounts.spec.js
  test/e2e/accounts/utils.ts
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/pages/confirmation/components/confirmation-footer/confirmation-footer.js
  ui/pages/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/confirmation/templates/index.js
  ui/pages/confirmation/templates/snap-account-redirect.js
  ui/pages/confirmation/templates/snap-account-redirect.test.js
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
  ui/pages/snap-account-redirect/components/index.ts
  ui/pages/snap-account-redirect/components/redirect-url-icon.tsx
  ui/pages/snap-account-redirect/components/snap-account-redirect-context.tsx
  ui/pages/snap-account-redirect/components/snap-account-redirect-message.tsx
  ui/pages/snap-account-redirect/components/url-display-box.tsx
  ui/pages/snap-account-redirect/create-snap-redirect.test.tsx
  ui/pages/snap-account-redirect/index.ts
  ui/pages/snap-account-redirect/snap-account-redirect.stories.tsx
  ui/pages/snap-account-redirect/snap-account-redirect.tsx
  yarn.lock
Labels: needs-qa, team-accounts, QA Passed

#21272 feat: enable account Snaps in stable
  app/_locales/en/messages.json
  app/scripts/lib/setupSentry.js
  builds.yml
  lavamoat/browserify/main/policy.json
  package.json
  shared/constants/snaps/permissions.ts
  test/e2e/accounts/settings-add-snap-account-toggle.spec.js
  test/e2e/accounts/utils.ts
  test/e2e/helpers.js
  test/e2e/run-all.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/helpers/utils/permission.js
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  yarn.lock
Labels: needs-qa, team-accounts, QA Passed, high-priority

#21221 feat: add "Add Snap accounts" time-based feature flag
  builds.yml
  shared/modules/snap-accounts.test.ts
  shared/modules/snap-accounts.ts
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
Labels: team-accounts

#21301 Picker network updates
  test/e2e/tests/add-custom-network.spec.js
  test/e2e/tests/custom-rpc-history.spec.js
  test/e2e/tests/switch-custom-network.spec.js
  ui/components/component-library/picker-network/README.mdx
  ui/components/component-library/picker-network/__snapshots__/picker-network.test.tsx.snap
  ui/components/component-library/picker-network/picker-network.scss
  ui/components/component-library/picker-network/picker-network.stories.tsx
  ui/components/component-library/picker-network/picker-network.test.tsx
  ui/components/component-library/picker-network/picker-network.tsx
  ui/components/component-library/picker-network/picker-network.types.ts
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/ui/new-network-info/new-network-info.js
  ui/components/ui/new-network-info/new-network-info.stories.js
Labels: team-design-system, needs-ux-ds-review

#21337 Add `data-testid` for toggle button
  ui/components/ui/toggle-button/toggle-button.component.js
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
Labels: team-accounts

#21333 UX: Multichain: Use contants for AssetListConversionButton variants
  ui/components/app/asset-list/asset-list.js
  ui/components/app/nfts-tab/nfts-tab.js
  ui/components/multichain/asset-list-conversion-button/asset-list-conversion-button.js
  ui/components/multichain/asset-list-conversion-button/asset-list-conversion-button.stories.js
Labels: team-extension-UX, needs-ux-ds-review

#21370 Fixing truncation and alignment in the network toggle component
  ui/components/app/app-components.scss
  ui/components/app/incoming-trasaction-toggle/__snapshots__/incoming-transaction-toggle.test.js.snap
  ui/components/app/incoming-trasaction-toggle/network-toggle.scss
  ui/components/app/incoming-trasaction-toggle/network-toggle.stories.tsx
  ui/components/app/incoming-trasaction-toggle/network-toggle.tsx
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: team-design-system, needs-ux-ds-review

#21367 [MMI] updates metamask/keyring-controller package to latest version
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: release-blocker, team-mmi, release-11.4.0

#21357 fix(21300): bring back appInstalled event when opt in
  app/scripts/background.js
Labels: release-blocker, team-extension-platform

#21094 fix(000): fix lint for account-list-item-menu and token-allowance
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
Labels: team-extension-platform

#21374 UX: Fixed network picker in header
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/app-header.scss
Labels: team-extension-UX, needs-ux-ds-review

#21317 Add min-width support to Box DS component; Fix Blockaid Security Alert overflow issue; Fix missing Box width-max breakpoint styles
  ui/components/app/ledger-instruction-field/__snapshots__/ledger-instruction-field.test.js.snap
  ui/components/app/modals/eth-sign-modal/__snapshots__/eth-sign-modal.test.js.snap
  ui/components/app/security-provider-banner-alert/__snapshots__/security-provider-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/component-library/banner-alert/__snapshots__/banner-alert.test.tsx.snap
  ui/components/component-library/banner-base/__snapshots__/banner-base.test.tsx.snap
  ui/components/component-library/banner-base/banner-base.tsx
  ui/components/component-library/banner-tip/__snapshots__/banner-tip.test.tsx.snap
  ui/components/component-library/box/box.scss
  ui/components/component-library/box/box.stories.tsx
  ui/components/component-library/box/box.test.tsx
  ui/components/component-library/box/box.tsx
  ui/components/component-library/box/box.types.ts
  ui/components/multichain/detected-token-banner/__snapshots__/detected-token-banner.test.js.snap
  ui/css/design-system/attributes.scss
  ui/helpers/constants/design-system.ts
  ui/pages/confirm-add-suggested-nft/confirm-add-suggested-nft.js
  ui/pages/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/keychains/__snapshots__/reveal-seed.test.js.snap
Labels: team-design-system, team-confirmations-secure-ux-PR, needs-ux-ds-review

#21342 UX Multichain: Added avatar group component
  ui/components/multichain/avatar-group/__snapshots__/avatar-group.test.tsx.snap
  ui/components/multichain/avatar-group/avatar-group.stories.tsx
  ui/components/multichain/avatar-group/avatar-group.test.tsx
  ui/components/multichain/avatar-group/avatar-group.tsx
  ui/components/multichain/avatar-group/avatar-group.types.tsx
  ui/components/multichain/avatar-group/index.ts
  ui/components/multichain/index.js
Labels: team-extension-UX, needs-ux-ds-review

#21359 UX: Multichain: Fix useAccountTotalFiatBalance when getWeiHexFromDecimalValue returns "NaN"
  ui/hooks/useAccountTotalFiatBalance.js
Labels: team-extension-UX, needs-ux-ds-review

#21185 fix: display conversion rate
  ui/components/ui/token-input/token-input.component.js
  ui/components/ui/token-input/token-input.component.test.js
  ui/components/ui/token-input/token-input.container.js
Labels: team-extension-UX, needs-ux-ds-review

#21338 Token amount sent displays 0 when input contains no decimals
  ui/hooks/useTokenDisplayValue.js
  ui/hooks/useTokenDisplayValue.test.js
Labels: team-extension-UX, needs-ux-ds-review

#21174 Fix gas calculation checking wrong account balance
  ui/components/app/edit-gas-fee-popover/edit-gas-fee-popover.test.js
  ui/hooks/gasFeeInput/test-utils.js
  ui/hooks/gasFeeInput/useGasFeeErrors.js
  ui/hooks/gasFeeInput/useGasFeeErrors.test.js
  ui/hooks/gasFeeInput/useGasFeeInputs.test.js
Labels: team-confirmations-secure-ux-PR, needs-ux-ds-review

#21365 Master sync PR following v11.2.0
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#21250 UX: Multichain: Send flow: Send page skeleton
  app/_locales/en/messages.json
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/pages/index.scss
  ui/components/multichain/pages/page/components/index.scss
  ui/components/multichain/pages/page/index.scss
  ui/components/multichain/pages/send/index.js
  ui/components/multichain/pages/send/index.scss
  ui/components/multichain/pages/send/send.js
  ui/components/multichain/pages/send/send.stories.js
  ui/pages/routes/routes.component.js
Labels: team-extension-UX, needs-ux-ds-review

#21320 fix(000): fix mv3 build
  app/scripts/controllers/metametrics.js
  app/scripts/metamask-controller.test.js
Labels: team-extension-client, team-extension-platform

#21358 Bump test-dapp to v7.2.0
  package.json
  test/e2e/metamask-ui.spec.js
  test/e2e/tests/provider-api.spec.js
  yarn.lock
Labels: team-confirmations-secure-ux-PR

#20939 fix: don't render attribute `aria-invalid="false"`
  ui/components/component-library/input/input.tsx
  ui/components/component-library/text-field/text-field.js
  ui/pages/keychains/__snapshots__/reveal-seed.test.js.snap
Labels: team-accounts, needs-dev-review

#21207 Adopt new version of `@metamask/signature-controller` to add signature operation logs
  .yarn/patches/@metamask-signature-controller-npm-6.0.0-90e8e479a9.patch
  .yarn/patches/@metamask-signature-controller-npm-6.1.2-f60d8a4960.patch
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-confirmations-system

#21336 fix: Hex data should be cleared out during ERC20 Send
  test/jest/mocks.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
Labels: team-extension-UX

#21386 chore: Blockaid remove unfair_trade reason type
  shared/constants/security-provider.ts
  test/e2e/flask/ppom-blockaid-alert.spec.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
Labels: team-confirmations-secure-ux-PR

#21387 Fix #21169 - Ensure Copy format is plain text
  shared/constants/copy.ts
  ui/components/app/nft-details/nft-details.test.js
  ui/components/app/selected-account/selected-account-component.test.js
  ui/components/app/selected-account/selected-account.component.js
  ui/components/app/transaction-decoding/components/decoding/address/address.component.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
  ui/components/ui/sender-to-recipient/sender-to-recipient.component.js
  ui/hooks/useCopyToClipboard.js
  ui/index.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-decrypt-message/confirm-decrypt-message.component.js
Labels: team-extension-UX, needs-ux-ds-review

#21390 Security provider metrics fix
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#21352 Enable blockaid in main build
  app/scripts/lib/setupSentry.js
  builds.yml
  lavamoat/browserify/main/policy.json
  package.json
  privacy-snapshot.json
  test/e2e/metrics/signature-approved.spec.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/pages/settings/experimental-tab/experimental-tab.component.js
Labels: team-confirmations-secure-ux-PR

#21422 Await account render after unlock before checking for mocked endpoint…
  test/e2e/metrics/unlock-wallet.spec.js
Labels: team-extension-platform

#21406 Remove CODEOWNERS entry for Flask files
  .github/CODEOWNERS
Labels: team-snaps

#21397 deps/devDeps: Bump babel and storybook packages to latest
  .yarn/patches/@babel-core-npm-7.21.5-c72c337956.patch
  .yarn/patches/@babel-core-npm-7.23.2-b93f586907.patch
  .yarn/patches/@babel-runtime-npm-7.23.2-d013d6cf7e.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: type-security, dependencies, team-security

#21379 test:fix:e2e Fix flaky PPOM Blockaid tests by adding more mock JSON-API requests
  test/e2e/flask/ppom-blockaid-alert-erc20-approval.spec.js
  test/e2e/flask/ppom-blockaid-alert-erc20-transfer.spec.js
  test/e2e/flask/ppom-blockaid-alert.spec.js
  test/mocks/json-rpc-result.ts
Labels: team-confirmations-secure-ux-PR

#21427 Fix NEAR protocol path
  shared/constants/snaps.ts
Labels: team-snaps

#21435 Fix cannot read `code` property of undefined
  app/scripts/controllers/transactions/index.js
Labels: team-confirmations-system

#21401 fix: ERC20 Custom Token shows incorrect name
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/app/token-cell/token-cell.js
  ui/components/app/token-cell/token-cell.test.js
Labels: team-extension-UX

#21389 Fix: metrics details for toggling blockaid settings
  shared/constants/metametrics.ts
  ui/pages/settings/experimental-tab/experimental-tab.component.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#21424 test: move ppom e2e tests to run against the main build
  package.json
  test/e2e/run-all.js
  test/e2e/tests/ppom-blockaid-alert-erc20-approval.spec.js
  test/e2e/tests/ppom-blockaid-alert-erc20-transfer.spec.js
  test/e2e/tests/ppom-blockaid-alert.spec.js
  test/e2e/tests/ppom-toggle-settings.spec.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#21329 Add Snaps to three dots menu and refactor
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/accounts/test-remove-accounts-snap.spec.js
  test/e2e/accounts/test-snap-accounts.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-revoke-perm.spec.js
  ui/components/app/app-components.scss
  ui/components/app/snaps/snap-list-item/index.js
  ui/components/app/snaps/snap-list-item/index.scss
  ui/components/app/snaps/snap-list-item/snap-list-item.js
  ui/components/app/snaps/snap-list-item/snap-list-item.stories.js
  ui/components/app/snaps/snap-list-item/snap-list-item.test.js
  ui/components/app/snaps/snap-settings-card/index.js
  ui/components/app/snaps/snap-settings-card/index.scss
  ui/components/multichain/global-menu/global-menu.js
  ui/helpers/constants/routes.ts
  ui/helpers/constants/settings.js
  ui/pages/pages.scss
  ui/pages/routes/routes.component.js
  ui/pages/settings/index.scss
  ui/pages/settings/settings-search/settings-search.js
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
  ui/pages/settings/settings.stories.js
  ui/pages/settings/snaps/snaps-list-tab/index.js
  ui/pages/settings/snaps/snaps-list-tab/index.scss
  ui/pages/settings/snaps/snaps-list-tab/snap-list-tab.js
  ui/pages/settings/snaps/view-snap/index.js
  ui/pages/settings/snaps/view-snap/index.scss
  ui/pages/settings/snaps/view-snap/view-snap.js
  ui/pages/snaps/snap-view/constants.ts
  ui/pages/snaps/snap-view/index.js
  ui/pages/snaps/snap-view/index.scss
  ui/pages/snaps/snap-view/snap-view.js
  ui/pages/snaps/snap-view/snap-view.test.js
  ui/pages/snaps/snaps-list/index.js
  ui/pages/snaps/snaps-list/index.scss
  ui/pages/snaps/snaps-list/snap-list.js
  ui/pages/snaps/snaps-list/snap-list.stories.js
Labels: team-snaps

#21447 Revert e471f0adec and then replace onInstalled event with check for existing localStore
  app/scripts/background.js
Labels: release-blocker, team-mobile-platform, release-11.3.0

#21330 Decouple `MetaMetricsController` from `TxController`
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/snap-keyring/metrics.ts
  app/scripts/lib/transaction-metrics.test.ts
  app/scripts/lib/transaction-metrics.ts
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  shared/constants/transaction.ts
  ui/hooks/useTransactionEventFragment.js
  ui/store/actions.ts
Labels: team-confirmations-system

#21439 feat(20169): remove service worker restart related e2e tests
  test/e2e/helpers.js
  test/e2e/mv3/multiple-restarts.spec.js
  test/e2e/mv3/phishing-warning-sw-restart.spec.js
  test/e2e/mv3/service-worker-restart.spec.js
Labels: team-extension-platform

#21414 fix(issue template): placeholder text
  .github/ISSUE_TEMPLATE/general-issue.yml
Labels: team-extension-client

#21410 feat(21068): remove action queue for new MV3
  .storybook/preview.js
  test/jest/background.js
  test/jest/index.js
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
  ui/ducks/send/send.test.js
  ui/index.js
  ui/pages/confirm-send-ether/confirm-send-ether.test.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirm-transaction/confirm-transaction.test.js
  ui/pages/confirm-transaction/confirm-transaction.transaction.test.js
  ui/pages/institutional/onboarding-successful/onboarding-successful.test.js
  ui/pages/onboarding-flow/creation-successful/creation-successful.test.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/send/send.test.js
  ui/pages/swaps/awaiting-swap/awaiting-swap.test.js
  ui/pages/swaps/build-quote/build-quote.test.js
  ui/pages/swaps/create-new-swap/create-new-swap.test.js
  ui/pages/swaps/fee-card/fee-card.test.js
  ui/pages/swaps/index.test.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.test.js
  ui/pages/swaps/prepare-swap-page/review-quote.test.js
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.test.js
  ui/pages/swaps/view-quote/view-quote.test.js
  ui/store/action-queue/index.test.js
  ui/store/action-queue/index.ts
  ui/store/action-queue/queue.integration.test.js
  ui/store/actions.test.js
  ui/store/actions.ts
  ui/store/background-connection.ts
  ui/store/institutional/institution-actions.test.js
  ui/store/institutional/institution-background.test.js
  ui/store/institutional/institution-background.ts
Labels: team-extension-client, team-extension-platform

#21455 Simplify notifications implementation
  ui/components/app/connected-sites-list/connected-snaps.js
  ui/components/app/snaps/snap-content-footer/snap-content-footer.js
  ui/helpers/utils/util.js
  ui/pages/keyring-snaps/snap-account-detail-page/snap-account-detail-page.tsx
  ui/pages/notifications/notification.test.js
  ui/pages/notifications/notifications.js
  ui/pages/snaps/snaps-list/snap-list.js
  ui/selectors/selectors.js
Labels: team-snaps

#21446 UX: Remove unused KeyringLabel and allcaps style
  development/ts-migration-dashboard/files-to-convert.json
  ui/components/app/account-menu/keyring-label.js
  ui/css/base-styles.scss
Labels: team-extension-UX, needs-ux-ds-review

#21450 UX: Remove PickerNetwork active background color change when disabled
  ui/components/component-library/picker-network/picker-network.scss
Labels: team-extension-UX, needs-ux-ds-review

#21459 fix(21069): remove sleepSeconds
  test/e2e/helpers.js
Labels: team-extension-client, team-extension-platform

#21457 Update e2e snapshot
  .circleci/config.yml
  README.md
  package.json
  privacy-snapshot.json
  test/e2e/mock-e2e.js
  test/e2e/run-all.js
  test/e2e/tests/import-flow.spec.js
  test/e2e/tests/portfolio-site.spec.js
Labels: team-extension-platform

#21415 ci(privacy): add mozilla.org to privacy ignore list
  privacy-snapshot.json
  test/e2e/mock-e2e.js
Labels: area-privacy, team-extension-platform

#21356 [e2e] Switch ethereum chain multiple dapps
  test/e2e/fixture-builder.js
  test/e2e/json-rpc/switchEthereumChain.spec.js
Labels: area-testSuite, team-devex

#21347 test: add unit tests to `getSnapAndHardwareInfoForMetrics` method
  app/scripts/lib/snap-keyring/metrics.test.ts
Labels: team-accounts, needs-dev-review

#21469 test: fix `getSnapAndHardwareInfoForMetrics` unit test
  app/scripts/lib/snap-keyring/metrics.test.ts
Labels: team-accounts

#21380 Update assets controllers to version 16
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-extension-client, team-extension-platform

#21344 Add new test scenarios
  test/scenarios/3. transactions/send erc20 token origin dapp.csv
  test/scenarios/3. transactions/send erc721 token origin dapp.csv
  test/scenarios/3. transactions/send native token origin dapp.csv
Labels: area-documentation, team-extension-client, team-extension-platform

#21472 chore(000): update chrome driver version to 118
  .circleci/scripts/chrome-install.sh
  package.json
  yarn.lock
Labels: team-extension-client, team-extension-platform

#21104 Enable Linea
  app/_locales/en/messages.json
  shared/constants/swaps.ts
  ui/hooks/useTokensToSearch.js
  ui/pages/swaps/fee-card/fee-card.js
  ui/pages/swaps/swaps.util.test.js
  ui/pages/swaps/swaps.util.ts
Labels: area-swaps, team-swaps

#21475 Fix/issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/scripts/check-issue-template-and-add-labels.ts
Labels: team-extension-client, team-extension-platform

#20698 fix(linea): enable token detection for Linea mainnet and testnet
  shared/modules/network.utils.ts
  ui/selectors/selectors.js
Labels: type-bug, release-blocker, team-extension-client, regression-RC, team-extension-platform, QA Passed, team-linea, release-11.4.0

#21443 UX: Reduce setMouseUserState calls to prevent re-renders
  .storybook/test-data.js
  ui/css/base-styles.scss
  ui/ducks/app/app.test.js
  ui/ducks/app/app.ts
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.component.test.js
  ui/pages/routes/routes.container.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: team-extension-UX, needs-ux-ds-review

#21451 UX: Remove AccountPicker hover styling when disabled
  ui/components/multichain/account-picker/index.scss
Labels: team-extension-UX, needs-ux-ds-review

#21395 Multichain send page components
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/send.js
  ui/components/multichain/pages/send/send.test.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21464 Fix flakiness of import-flow.spec.js and swaps-notifications.spec.js
  test/e2e/swaps/shared.js
  test/e2e/tests/import-flow.spec.js
Labels: team-extension-platform

#21385 Simplify keep alive logic
  app/scripts/background.js
  app/scripts/contentscript.js
  app/scripts/lib/stream-utils.js
  app/scripts/ui.js
  package.json
Labels: team-extension-client, team-extension-platform, needs-dev-review

#21381 E2e multiple erc20 watch asset
  test/e2e/tests/add-multiple-tokens.spec.js
Labels: area-testSuite, team-devex
