Repository MetaMask/metamask-extension, pull requests merged in 2023-12, with the labels that each got.

#22079 Fix nonces in smart swaps requiring approval
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: team-confirmations-system

#22114 Cherry pick: Update content in Swaps (#22105)
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/pages/swaps/slippage-buttons/slippage-buttons.js
  ui/pages/swaps/slippage-buttons/slippage-buttons.test.js
  ui/pages/swaps/transaction-settings/transaction-settings.js
  ui/pages/swaps/transaction-settings/transaction-settings.test.js
Labels: release-blocker, team-swaps, INVALID-PR-TEMPLATE, release-11.7.0

#22078 Add snap category to event properties
  app/scripts/metamask-controller.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22067 feat: [MULTI-CHAIN] Add in NFT Selector design for multichain
  ui/components/multichain/asset-picker-amount/asset-picker-amount.stories.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-amount.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx
Labels: team-extension-UX, area-multichain

#22129 Fix custom nonce support + incoming transaction display
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#22085 Warning for ChainId/CurrencySymbol mismatch (Dapp Initiated) Follow-Up
  ui/pages/confirmation/confirmation.js
  ui/pages/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
  ui/pages/confirmation/templates/add-ethereum-chain.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
Labels: team-extension-UX, needs-ux-ds-review

#21868 Add polling by `networkClientId` to `AccountTracker`
  .storybook/test-data.js
  app/scripts/background.js
  app/scripts/constants/contracts.ts
  app/scripts/lib/account-tracker.js
  app/scripts/lib/account-tracker.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/ducks/metamask/metamask.js
  ui/ducks/metamask/metamask.test.js
Labels: team-devex

#22138 [MMI] typo fix for variable: selectedAddress
  app/scripts/controllers/metametrics.js
Labels: team-mmi

#22113 test:e2e: skip benign ppom blockaid alert
  test/e2e/tests/ppom-blockaid-alert.spec.js
Labels: team-confirmations-secure-ux-PR

#21013 Fix #21839 a bug where settings search only supported English and numbers
  ui/pages/settings/settings-search/settings-search.js
Labels: needs-ux-ds-review, external-contributor

#22145 [MMI] skip e2e test temporarily
  test/e2e/mmi/specs/dapp.spec.ts
Labels: team-mmi

#22144 Fix tooltip icon coloring in row component
  ui/components/app/confirm/shared/info/row/row.tsx
Labels: team-snaps, INVALID-PR-TEMPLATE

#22117 Bump @metamask/assets-controllers version to v19.0.0
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/nft/erc1155-interaction.spec.js
  yarn.lock
Labels: team-devex

#22127 Update calculation for the Smart Swaps' Max fee
  ui/pages/swaps/prepare-swap-page/review-quote.js
Labels: team-swaps, INVALID-PR-TEMPLATE

#22149 CherryPick: Warning for ChainId/CurrencySymbol mismatch (Dapp Initiated) (#21924)
  ui/components/ui/definition-list/definition-list.js
  ui/components/ui/truncated-definition-list/truncated-definition-list.js
  ui/pages/confirmation/confirmation.js
  ui/pages/confirmation/templates/add-ethereum-chain.js
  ui/pages/confirmation/templates/index.js
Labels: INVALID-PR-TEMPLATE

#22137 Update Snap Avatar background color
  ui/components/app/snaps/snap-avatar/snap-avatar.js
Labels: team-snaps

#21937 Remove transaction insight deprecation component
  app/_locales/en/messages.json
  ui/components/app/confirm-data/transaction-insights-deprecation-alert.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22164 [MMI] allow for non custodial accounts to cancel and speed up
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
Labels: team-mmi

#22151 feat(22139): add header to requests going to CoinGecko
  .yarn/patches/@metamask-assets-controllers-npm-19.0.0-38db9af3ac.patch
  package.json
  ui/pages/swaps/swaps.util.ts
  yarn.lock
Labels: team-extension-client, team-extension-platform

#22169 [MMI] updates e2e snapshot
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-list-mmi-visual-linux.png
Labels: team-mmi

#22167 CherryPick: Fix Ledger legacy transactions (#22136)
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#22168 CherryPick: Warning for ChainId/CurrencySymbol mismatch (Dapp Initiated) Follow-U…
  ui/pages/confirmation/confirmation.js
  ui/pages/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
  ui/pages/confirmation/templates/add-ethereum-chain.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
Labels: INVALID-PR-TEMPLATE

#22173 Add success property to snap export used event
  app/scripts/metamask-controller.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22175 fix(22139): change the header key to coinGecko calls
  .yarn/patches/@metamask-assets-controllers-npm-19.0.0-38db9af3ac.patch
  ui/pages/swaps/swaps.util.ts
  yarn.lock
Labels: release-blocker, team-extension-client, team-extension-platform

#22174 Cherry pick coingecko pulling improvement to 11.7.0
  .yarn/patches/@metamask-assets-controllers-npm-18.0.0-48bf74a7fa.patch
  app/scripts/metamask-controller.js
  package.json
  ui/pages/swaps/swaps.util.ts
  yarn.lock
Labels: team-extension-platform

#21436 Update blockaid dependency and ppom.js
  app/scripts/lib/ppom/ppom.js
  package.json
  test/e2e/tests/ppom-blockaid-alert.spec.js
  yarn.lock
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR

#22165 E2E test: Add check for snap intalled event metrics
  test/e2e/snaps/test-snap-installed.spec.js
Labels: team-extension-client, team-extension-platform

#22181 [MMI] updates e2e snapshot
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-connection-info-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-list-mmi-visual-linux.png
Labels: team-mmi

#22152 Bump @metamask/assets-controller to v20.0.0
  .yarn/patches/@metamask-assets-controllers-npm-19.0.0-38db9af3ac.patch
  app/scripts/background.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: team-devex

#22177 feat(1463): introduce dapp viewed metrics events when connected to a dapp
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.js
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  test/e2e/helpers.js
  test/e2e/tests/metrics/dapp-viewed.spec.js
Labels: team-extension-client, team-extension-platform

#22182 Bump snaps packages
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#22096 refactor: move ConfirmInfoRow files out of shared directory
  ui/components/app/confirm/info/row/address.stories.tsx
  ui/components/app/confirm/info/row/address.tsx
  ui/components/app/confirm/info/row/hook.ts
  ui/components/app/confirm/info/row/index.ts
  ui/components/app/confirm/info/row/row.stories.tsx
  ui/components/app/confirm/info/row/row.tsx
  ui/components/app/confirm/info/row/value-double.stories.tsx
  ui/components/app/confirm/info/row/value-double.tsx
  ui/components/app/metamask-template-renderer/safe-component-list.js
Labels: type-refactor, team-confirmations-secure-ux-PR, confirmation-redesign

#21680 Change window title from "MetaMask Notification" to "MetaMask Dialog"
  app/notification.html
  test/e2e/accounts/common.ts
  test/e2e/helpers.js
  test/e2e/json-rpc/eth_sendTransaction.spec.js
  test/e2e/mmi/scripts/run-visual-test.sh
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/snaps/test-snap-get-file.spec.js
  test/e2e/snaps/test-snap-get-locale.spec.js
  test/e2e/snaps/test-snap-getentropy.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-lifecycle.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-networkaccess.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-txinsights-v2.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-wasm.spec.js
  test/e2e/tests/4byte-directory.spec.js
  test/e2e/tests/add-custom-network.spec.js
  test/e2e/tests/add-hide-token.spec.js
  test/e2e/tests/chain-interactions.spec.js
  test/e2e/tests/contract-interactions.spec.js
  test/e2e/tests/custom-token-add-approve.spec.js
  test/e2e/tests/dapp-interactions.spec.js
  test/e2e/tests/dapp-tx-edit.spec.js
  test/e2e/tests/encrypt-decrypt.spec.js
  test/e2e/tests/eth-sign.spec.js
  test/e2e/tests/failing-contract.spec.js
  test/e2e/tests/nft/erc1155-interaction.spec.js
  test/e2e/tests/nft/erc721-interaction.spec.js
  test/e2e/tests/permissions.spec.js
  test/e2e/tests/personal-sign.spec.js
  test/e2e/tests/ppom-blockaid-alert-erc20-approval.spec.js
  test/e2e/tests/ppom-blockaid-alert-erc20-transfer.spec.js
  test/e2e/tests/ppom-blockaid-alert-trade-order-farming.spec.js
  test/e2e/tests/ppom-blockaid-setApprovalForAll-farming.spec.js
  test/e2e/tests/security-provider.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/signature-request.spec.js
  test/e2e/tests/signin-with-ethereum.spec.js
  test/e2e/tests/switch-custom-network.spec.js
  test/scenarios/11. gas fee/EIP-1559 gas.csv
  test/scenarios/11. gas fee/legacy gas.csv
  test/scenarios/15. swap/swap eth.csv
Labels: team-extension-UX, INVALID-PR-TEMPLATE

#22158 Feat/19128/update text field search to ts
  ui/components/app/import-token/token-search/token-search.component.js
  ui/components/component-library/index.js
  ui/components/component-library/modal/modal.stories.tsx
  ui/components/component-library/text-field-search/__snapshots__/text-field-search.test.tsx.snap
  ui/components/component-library/text-field-search/deprecated/index.js
  ui/components/component-library/text-field-search/deprecated/text-field-search.js
  ui/components/component-library/text-field-search/index.ts
  ui/components/component-library/text-field-search/text-field-search.stories.tsx
  ui/components/component-library/text-field-search/text-field-search.test.tsx
  ui/components/component-library/text-field-search/text-field-search.tsx
  ui/components/component-library/text-field-search/text-field-search.types.ts
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/pages/swaps/list-with-search/list-with-search.js
Labels: area-UI, team-design-system

#22183 Adding test scenario for importing 1155 tokens
  test/scenarios/4. tokens/import erc1155 token origin dapp.csv
Labels: area-documentation, team-extension-platform, extension-delivery

#22090 Fix EIP-6963 Prod Build names
  development/build/utils.js
Labels: team-extension-platform, team-devex

#22213 11.7.0 cherry pick 783a284 (#21578)
  app/scripts/contentscript.js
  test/e2e/synchronous-injection/index.html
  test/e2e/synchronous-injection/synchronous-injection.spec.js
Labels: INVALID-PR-TEMPLATE

#21399 feat: e2e tests for blockaid metrics
  test/e2e/tests/ppom-blockaid-alert-metrics.spec.js
  test/e2e/tests/ppom-blockaid-toggle-metrics.spec.js
Labels: area-metrics, team-confirmations-secure-ux-PR, needs-dev-review, INVALID-PR-TEMPLATE

#21918 UX: Provide entrypoint for survey
  app/_locales/en/messages.json
  app/scripts/controllers/app-state.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/helpers/constants/survey.ts
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/home/index.scss
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#22185 Create Container component
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/container/README.mdx
  ui/components/component-library/container/__snapshots__/container.test.tsx.snap
  ui/components/component-library/container/container.scss
  ui/components/component-library/container/container.stories.tsx
  ui/components/component-library/container/container.test.tsx
  ui/components/component-library/container/container.tsx
  ui/components/component-library/container/container.types.ts
  ui/components/component-library/container/index.ts
  ui/components/component-library/index.js
Labels: team-design-system

#22220 Build types can now override build name
  builds.yml
  development/build/utils.js
  development/lib/build-type.js
Labels: team-extension-platform, team-devex

#22215 fix(action): be more restrictive on the release branch format
  .github/workflows/create-bug-report.yml
Labels: team-extension-client, team-extension-platform, needs-dev-review

#22196 E2E tests: transfer custom tokens
  test/e2e/tests/custom-token-send-transfer.spec.js
Labels: team-extension-client, team-extension-platform, needs-dev-review

#22210 Update `Snap Export Used` event
  app/scripts/metamask-controller.js
Labels: team-snaps

#22243 test: disable failing ppom metrics test
  test/e2e/tests/ppom-blockaid-alert-metrics.spec.js
Labels: team-confirmations-secure-ux-PR

#21852 feat: [MULTI-CHAIN] Send Flow: Token picker modal component
  app/_locales/en/messages.json
  test/data/mock-send-state.json
  test/data/mock-state.json
  ui/components/app/nfts-items/nfts-items.js
  ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.stories.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/index.scss
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
  ui/components/multichain/asset-picker-amount/max-clear-button.tsx
  ui/components/multichain/multichain-components.scss
  ui/selectors/selectors.js
Labels: team-extension-UX, area-multichain

#22241 Fix issue with calling `getUnlockPromise` multiple times
  app/scripts/controllers/app-state.js
Labels: team-confirmations-system, INVALID-PR-TEMPLATE

#21765 feat(mv3): hardware wallet support for trezor
  .yarnrc.yml
  app/manifest/v3/chrome.json
  app/scripts/lib/offscreen-bridge/trezor-offscreen-bridge.ts
  app/scripts/metamask-controller.js
  development/build/scripts.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  offscreen/offscreen.html
  offscreen/scripts/trezor-iframe.ts
  offscreen/trezor-iframe.html
  package.json
  shared/constants/offscreen-communication.ts
  types/global.d.ts
  ui/pages/create-account/connect-hardware/select-hardware.js
  yarn.lock
Labels: team-extension-platform, needs-dev-review

#21970 Implement routing for new confirmation components
  development/build/transforms/README.md
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/ducks/confirm/confirm.test.js
  ui/ducks/confirm/confirm.ts
  ui/ducks/index.js
  ui/hooks/confirm/setCurrentConfirmation.test.tsx
  ui/hooks/confirm/setCurrentConfirmation.ts
  ui/hooks/confirm/syncConfirmPath.test.ts
  ui/hooks/confirm/syncConfirmPath.ts
  ui/hooks/confirm/useCurrentConfirmation.test.ts
  ui/hooks/confirm/useCurrentConfirmation.ts
  ui/pages/confirm-transaction/confirm-transaction.component.js
  ui/pages/confirm/confirm.test.ts
  ui/pages/confirm/confirm.tsx
  ui/selectors/approvals.test.ts
  ui/selectors/approvals.ts
  ui/selectors/confirm.test.ts
  ui/selectors/confirm.ts
  ui/selectors/index.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#21865 UX: Added Account list pinning and Unpinning
  .storybook/test-data.js
  app/_locales/en/messages.json
  app/images/icons/pin.svg
  app/images/icons/unpin.svg
  app/scripts/controllers/account-order.ts
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  builds.yml
  test/data/mock-state.json
  test/e2e/fixture-builder.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/components/component-library/icon/icon.types.ts
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: team-extension-client, team-extension-UX

#22071 Restore accounts with tokens
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-accounts

#22247 feat(22244): update pricing api from coingekco to our own ones
  test/e2e/tests/send-eth.spec.js
  ui/pages/swaps/swaps.util.ts
Labels: team-extension-client, team-extension-platform

#22250 UX: set notification popup title differently on test builds
  app/notification.html
  development/build/scripts.js
Labels: team-extension-UX

#22199 UX: Release the empty asset banners
  ui/components/app/asset-list/asset-list.js
  ui/components/app/nfts-tab/nfts-tab.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#22240 Fix: PPOM e2e infura calls failure
  test/e2e/tests/ppom-blockaid-alert-metrics.spec.js
  test/e2e/tests/send-eth.spec.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22281 [MMI] - fixes visual snapshot
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-remove-token-mmi-visual-linux.png
Labels: team-mmi

#22246 Enable ppom by default
  app/scripts/controllers/preferences.js
  app/scripts/migrations/106.js
  app/scripts/migrations/106.test.js
  app/scripts/migrations/index.js
  test/e2e/tests/ppom-toggle-settings.spec.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22280 [E2E test] Remove old metamask-ui.spec.js test file
  test/e2e/metamask-ui.spec.js
  test/e2e/run-all.js
Labels: team-extension-client, team-extension-platform

#22261 Nit Fix: Removed console statement
  ui/components/multichain/account-list-menu/account-list-menu.js
Labels: team-extension-UX, needs-ux-ds-review, INVALID-PR-TEMPLATE

#22095 chore: Update `@metamask/base-controller` to v4
  app/scripts/controllers/account-order.ts
  app/scripts/controllers/decrypt-message.ts
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/controllers/encryption-public-key.ts
  app/scripts/controllers/network-order.ts
  app/scripts/lib/ComposableObservableStore.test.js
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-shared-libraries

#21607 Adding Textarea component
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/textarea/README.mdx
  ui/components/component-library/textarea/__snapshots__/textarea.test.tsx.snap
  ui/components/component-library/textarea/index.ts
  ui/components/component-library/textarea/textarea.scss
  ui/components/component-library/textarea/textarea.stories.tsx
  ui/components/component-library/textarea/textarea.test.tsx
  ui/components/component-library/textarea/textarea.tsx
  ui/components/component-library/textarea/textarea.types.ts
  ui/components/ui/textarea/textarea.js
Labels: team-design-system, needs-ux-ds-review

#22276 Remove redundant cachedBalancesController and replace cachedBalances with accountsByChainId state
  .storybook/test-data.js
  app/scripts/controllers/cached-balances.js
  app/scripts/controllers/cached-balances.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/e2e/fixture-builder.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/jest/mock-store.js
  ui/components/app/alerts/unconnected-account-alert/unconnected-account-alert.test.js
  ui/components/app/asset-list/asset-list.buy-receive.test.js
  ui/components/app/asset-list/asset-list.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-fee-popover.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-item/edit-gas-item.test.js
  ui/components/app/edit-gas-fee-popover/edit-gas-tooltip/edit-gas-tooltip.test.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/institutional/wrong-network-notification/wrong-network-notification.stories.js
  ui/components/institutional/wrong-network-notification/wrong-network-notification.test.js
  ui/components/multichain/select-action-modal/select-action-modal.test.js
  ui/ducks/metamask/metamask.test.js
  ui/ducks/send/send.test.js
  ui/hooks/useAccountTotalFiatBalance.test.js
  ui/pages/confirm-signature-request/index.test.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/send/send.test.js
  ui/pages/token-allowance/token-allowance.test.js
  ui/selectors/permissions.test.js
  ui/selectors/selectors.js
  ui/store/actions.test.js
  ui/store/institutional/institution-actions.test.js
Labels: team-devex

#22116 [Snaps] Create E2E test for updating via Snap View
  test/e2e/snaps/test-snap-update-component.spec.js
Labels: area-snaps, team-snaps

#22166 feat: use Snaps directory to list Account Management Snaps
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/metamask-controller.js
  builds.yml
  shared/constants/app.ts
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/account-list-menu.test.js
  ui/helpers/constants/routes.ts
  ui/pages/keyring-snaps/add-snap-account-modal/add-snap-account-modal.stories.tsx
  ui/pages/keyring-snaps/add-snap-account-modal/add-snap-account-modal.tsx
  ui/pages/keyring-snaps/add-snap-account-modal/index.ts
  ui/pages/keyring-snaps/add-snap-account.tsx
  ui/pages/keyring-snaps/constants.ts
  ui/pages/keyring-snaps/index.scss
  ui/pages/keyring-snaps/index.ts
  ui/pages/keyring-snaps/new-snap-account-page/index.ts
  ui/pages/keyring-snaps/new-snap-account-page/new-snap-account-page.scss
  ui/pages/keyring-snaps/new-snap-account-page/new-snap-account-page.test.tsx
  ui/pages/keyring-snaps/new-snap-account-page/new-snap-account-page.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/__snapshots__/snap-account-detail-page.test.tsx.snap
  ui/pages/keyring-snaps/snap-account-detail-page/detail.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/header.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/index.ts
  ui/pages/keyring-snaps/snap-account-detail-page/snap-account-detail-page.scss
  ui/pages/keyring-snaps/snap-account-detail-page/snap-account-detail-page.test.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/snap-account-detail-page.tsx
  ui/pages/keyring-snaps/snap-account-detail-page/snap-detail-tag.tsx
  ui/pages/keyring-snaps/snap-card/__snapshots__/snap-card.test.tsx.snap
  ui/pages/keyring-snaps/snap-card/index.ts
  ui/pages/keyring-snaps/snap-card/snap-card.scss
  ui/pages/keyring-snaps/snap-card/snap-card.stories.tsx
  ui/pages/keyring-snaps/snap-card/snap-card.test.tsx
  ui/pages/keyring-snaps/snap-card/snap-card.tsx
  ui/pages/pages.scss
  ui/pages/routes/routes.component.js
  ui/store/actions.ts
Labels: team-accounts

#22264 Implement goerli deprecation warning
  app/_locales/en/messages.json
  test/e2e/tests/deprecated-networks.spec.js
  ui/components/ui/deprecated-networks/deprecated-networks.js
Labels: team-extension-client, team-extension-platform

#22230 fix: Remove Metamask Fees line from fee details component.
  app/_locales/en/messages.json
  ui/components/app/fee-details-component/fee-details-component.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22303 [MMI] Fixes MMI PW tests
  test/e2e/mmi/pageObjects/mmi-mainMenu-page.ts
  test/e2e/mmi/scripts/run-visual-test.sh
  test/e2e/mmi/specs/extension.visual.spec.ts
  test/e2e/mmi/specs/transactions.spec.ts
  test/e2e/mmi/specs/visual.spec.ts
Labels: team-mmi

#22272 UX: Release the AvatarGroup for Account Menu List Items
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#22297 fix(22160): temp fix to enable sending txn via QR
  .yarnrc.yml
  app/_locales/am/messages.json
  app/_locales/ar/messages.json
  app/_locales/bg/messages.json
  app/_locales/bn/messages.json
  app/_locales/ca/messages.json
  app/_locales/da/messages.json
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/et/messages.json
  app/_locales/fa/messages.json
  app/_locales/fi/messages.json
  app/_locales/fil/messages.json
  app/_locales/fr/messages.json
  app/_locales/he/messages.json
  app/_locales/hi/messages.json
  app/_locales/hr/messages.json
  app/_locales/ht/messages.json
  app/_locales/hu/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/kn/messages.json
  app/_locales/ko/messages.json
  app/_locales/lt/messages.json
  app/_locales/lv/messages.json
  app/_locales/ms/messages.json
  app/_locales/no/messages.json
  app/_locales/ph/messages.json
  app/_locales/pl/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ro/messages.json
  app/_locales/ru/messages.json
  app/_locales/sk/messages.json
  app/_locales/sl/messages.json
  app/_locales/sr/messages.json
  app/_locales/sv/messages.json
  app/_locales/sw/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/uk/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/app/modals/qr-scanner/qr-scanner.component.js
  ui/components/app/qr-hardware-popover/base-reader.js
  yarn.lock
Labels: team-extension-client, team-extension-platform

#22260 feat: re-add account Snaps toggle to experimental tab
  test/e2e/accounts/snap-account-settings.spec.ts
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
Labels: team-accounts

#22295 fix: fix tokenRatesController
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  yarn.lock
Labels: team-extension-UX, team-devex

#22309 Fix incorrect warnings when adding a chain from a dapp
  ui/pages/confirmation/confirmation.js
  ui/pages/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
Labels: team-extension-client, team-extension-platform

#22307 Ensure user is prompted for password during reminder based backup
  .yarn/patches/@metamask-keyring-controller-npm-9.0.0-f57ed3ebea.patch
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  package.json
  test/e2e/tests/incremental-security.spec.js
  ui/components/app/reveal-SRP-modal/index.js
  ui/components/app/reveal-SRP-modal/reveal-SRP-modal.js
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#22326 Remove CurrencyRateController start in background constructor
  app/scripts/metamask-controller.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: team-devex

#22217 Update AccountTracker methods to be #private
  .eslintrc.js
  app/scripts/lib/account-tracker.js
  app/scripts/lib/account-tracker.test.js
  test/lib/tick.js
  test/lib/timer-helpers.js
  ui/components/app/alerts/unconnected-account-alert/unconnected-account-alert.test.js
  ui/pages/desktop-pairing/desktop-pairing.test.js
Labels: team-devex

#22324 Update assets controllers to version 22 - OpenSea V2
  app/scripts/metamask-controller.js
  package.json
  test/e2e/tests/nft/mocks.js
  yarn.lock
Labels: team-assets

#22195 Snow 2.0.1
  app/loading.html
  app/manifest/v2/chrome.json
  app/manifest/v3/chrome.json
  app/trezor-usb-permissions.html
  package.json
  yarn.lock
Labels: team-extension-client, team-extension-platform, team-lavamoat, QA Passed

#22330 patch: Update eth-snap-keyring to 2.1.1
  app/scripts/lib/snap-keyring/snap-keyring.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-accounts

#21554 feat: update selectors to include internal accounts
  app/scripts/controllers/mmi-controller.js
  app/scripts/lib/account-tracker.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/e2e/accounts/create-snap-account.spec.ts
  test/e2e/tests/import-flow.spec.js
  test/jest/mock-store.js
  ui/components/app/modals/edit-approval-permission/edit-approval-permission.component.js
  ui/components/app/modals/edit-approval-permission/edit-approval-permission.container.js
  ui/components/app/nft-details/nft-details.js
  ui/components/app/nft-details/nft-details.test.js
  ui/components/app/selected-account/selected-account-component.test.js
  ui/components/app/selected-account/selected-account.component.js
  ui/components/app/selected-account/selected-account.container.js
  ui/components/app/signature-request-original/signature-request-original.container.js
  ui/components/app/signature-request-original/signature-request-original.test.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.container.js
  ui/components/app/transaction-status-label/transaction-status-label.test.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/app/wallet-overview/token-overview.test.js
  ui/components/app/wallet-overview/wallet-overview.js
  ui/components/institutional/interactive-replacement-token-notification/interactive-replacement-token-notification.test.js
  ui/components/institutional/wrong-network-notification/wrong-network-notification.test.js
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/connected-site-menu/connected-site-menu.js
  ui/components/multichain/connected-site-menu/connected-site-menu.test.js
  ui/components/multichain/select-action-modal/select-action-modal.test.js
  ui/ducks/send/send.test.js
  ui/ducks/swaps/swaps.test.js
  ui/pages/asset/components/native-asset.js
  ui/pages/asset/components/token-asset.js
  ui/pages/confirm-add-suggested-nft/confirm-add-suggested-nft.js
  ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.test.js
  ui/pages/confirm-signature-request/index.test.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/onboarding-flow/create-password/create-password.test.js
  ui/pages/onboarding-flow/import-srp/import-srp.test.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/welcome/welcome.test.js
  ui/selectors/institutional/selectors.js
  ui/selectors/institutional/selectors.test.js
  ui/selectors/nonce-sorted-transactions-selector.test.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-accounts, QA Passed

#22310 Configure title and icon in standard result pages
  ui/components/app/metamask-template-renderer/metamask-template-renderer.js
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/hooks/useEventFragment.test.js
  ui/pages/confirmation/ResultTemplate.test.ts
  ui/pages/confirmation/ResultTemplate.ts
  ui/pages/confirmation/confirmation.scss
  ui/pages/confirmation/stories/add-ethereum-chain.stories.js
  ui/pages/confirmation/stories/create-snap-account.stories.js
  ui/pages/confirmation/stories/error.stories.js
  ui/pages/confirmation/stories/remove-snap-account.stories.js
  ui/pages/confirmation/stories/snap-account-redirect.stories.js
  ui/pages/confirmation/stories/success.stories.js
  ui/pages/confirmation/stories/switch-ethereum-chain.stories.js
  ui/pages/confirmation/stories/util.js
  ui/pages/confirmation/templates/__snapshots__/error.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/success.test.js.snap
  ui/pages/confirmation/templates/error.js
  ui/pages/confirmation/templates/success.js
  ui/pages/confirmation/util.ts
  ui/pages/routes/routes.component.test.js
Labels: team-confirmations-system

#22081 feature: confirm re-design header component implementation
  ui/components/app/app-components.scss
  ui/components/app/confirm/header/__snapshots__/header.test.tsx.snap
  ui/components/app/confirm/header/header.scss
  ui/components/app/confirm/header/header.stories.tsx
  ui/components/app/confirm/header/header.test.tsx
  ui/components/app/confirm/header/header.tsx
  ui/components/component-library/component-library-components.scss
  ui/hooks/confirm/syncConfirmPath.ts
  ui/hooks/confirm/useConfirmationNetworkInfo.test.ts
  ui/hooks/confirm/useConfirmationNetworkInfo.ts
  ui/hooks/confirm/useConfirmationRecipientInfo.test.ts
  ui/hooks/confirm/useConfirmationRecipientInfo.ts
  ui/hooks/confirm/useDummy.ts
  ui/pages/confirm/confirm.tsx
  ui/selectors/confirm.ts
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#22293 feat: create ConfirmInfoRowUrl
  ui/components/app/confirm/info/row/__snapshots__/url.test.tsx.snap
  ui/components/app/confirm/info/row/index.ts
  ui/components/app/confirm/info/row/url.stories.tsx
  ui/components/app/confirm/info/row/url.test.tsx
  ui/components/app/confirm/info/row/url.tsx
Labels: team-confirmations-secure-ux-PR, confirmation-redesign

#22294 UX: Multichain: Send flow: Implement Textarea for Hex data
  ui/components/multichain/pages/send/components/hex.tsx
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#22319 Fix incorrect transaction statuses
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: team-confirmations-system, QA Passed

#22335 Master sync following v11.7.1
  CHANGELOG.md
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#22233 Cleanup AccountTracker test setup
  app/scripts/lib/account-tracker.test.js
Labels: team-devex

#22342 feat: display snap account name
  test/data/mock-state.json
  test/e2e/accounts/common.ts
  ui/components/app/wallet-overview/wallet-overview.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.stories.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/account-list-menu.test.js
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/helpers/utils/accounts.js
  ui/helpers/utils/accounts.test.js
Labels: area-UI, area-snaps, team-accounts, snap-keyring-epic

#22193 feat: Create ConfirmInfo
  ui/components/app/confirm/info/__snapshots__/info.test.tsx.snap
  ui/components/app/confirm/info/index.ts
  ui/components/app/confirm/info/index.tsx
  ui/components/app/confirm/info/info.stories.tsx
  ui/components/app/confirm/info/info.test.tsx
  ui/components/app/confirm/info/info.tsx
  ui/components/app/confirm/info/row/__snapshots__/divider.test.tsx.snap
  ui/components/app/confirm/info/row/divider.test.tsx
  ui/components/app/confirm/info/row/divider.tsx
  ui/components/app/confirm/info/row/index.ts
  ui/components/app/confirm/info/row/row.tsx
Labels: area-transactions, team-confirmations-secure-ux-PR, confirmation-redesign

#22228 Feat: Add send/receive support for ERC 1155s
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  shared/lib/token-util.ts
  shared/modules/Numeric.test.ts
  shared/modules/Numeric.ts
  test/e2e/tests/nft/send-nft.spec.js
  ui/components/app/nft-details/nft-details.js
  ui/components/app/nft-details/nft-details.test.js
  ui/ducks/send/helpers.js
  ui/ducks/send/helpers.test.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/hooks/useDraftTransactionWithTxParams.js
  ui/hooks/useNftsCollections.js
  ui/pages/confirm-transaction/confirm-token-transaction-switch.js
  ui/pages/send/send-content/send-amount-row/send-amount-row.component.js
  ui/pages/send/send-content/send-amount-row/send-amount-row.test.js
  ui/pages/send/send-content/send-asset-row/send-asset-row.component.js
  ui/pages/send/send-content/send-row-wrapper/send-row-wrapper.component.js
  ui/pages/send/send.constants.js
  ui/pages/send/send.utils.js
  ui/pages/send/send.utils.test.js
Labels: team-extension-UX

#22225 feat(1463): introduce Dapp Viewed track when user revisits a dapp
  app/scripts/background.js
  shared/constants/app.ts
  test/e2e/helpers.js
  test/e2e/tests/dapp-interactions.spec.js
  test/e2e/tests/metrics/dapp-viewed.spec.js
  test/e2e/tests/metrics/permissions-approved.spec.js
  test/e2e/tests/metrics/unlock-wallet.spec.js
  test/e2e/webdriver/driver.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/create-account/create-account.js
  ui/components/ui/account-list/account-list.js
Labels: team-extension-client, team-extension-platform

#21638 feat: Creating a reusable footer component for confirmation pages
  ui/components/app/confirm/footer/__snapshots__/footer.test.tsx.snap
  ui/components/app/confirm/footer/footer.stories.tsx
  ui/components/app/confirm/footer/footer.test.tsx
  ui/components/app/confirm/footer/footer.tsx
  ui/pages/confirm/confirm.tsx
Labels: team-confirmations-secure-ux-PR, needs-ux-ds-review, needs-dev-review

#22274 fix: Blockaid false positive report
  app/_locales/en/messages.json
  shared/constants/security-provider.ts
  ui/components/app/security-provider-banner-alert/__snapshots__/security-provider-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.stories.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-utils.js
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.js
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.test.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request/signature-request.js
  ui/components/app/transaction-alerts/transaction-alerts.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/token-allowance/token-allowance.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22336 Version v11.7.2
  CHANGELOG.md
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: QA Passed, INVALID-PR-TEMPLATE

#22323 Add loading message to deprecated networks
  app/_locales/en/messages.json
  shared/constants/network.ts
  test/e2e/tests/deprecated-networks.spec.js
  ui/components/app/loading-network-screen/loading-network-screen.component.js
  ui/components/ui/deprecated-networks/deprecated-networks.js
Labels: team-extension-client, team-extension-platform

#22371 fix: fix css
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
  ui/components/multichain/import-tokens-modal/index.scss
Labels: team-extension-UX, INVALID-PR-TEMPLATE

#22376 fix: OpenSea supply -> total_supply
  .yarn/patches/@metamask-assets-controllers-npm-22.0.0-6af3715fb2.patch
  package.json
  yarn.lock
Labels: team-assets

#22331 feat: 22271 add hex data test
  test/e2e/tests/show-hex-data.spec.js
Labels: team-extension-platform

#21890 fix: JSDoc in preferences-controller
  app/scripts/controllers/preferences.js
Labels: team-accounts, needs-dev-review

#22275 feat(mv3): Ledger MV3 support
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/lib/offscreen-bridge/ledger-offscreen-bridge.ts
  app/scripts/metamask-controller.js
  development/build/scripts.js
  offscreen/ledger-iframe.html
  offscreen/offscreen.html
  offscreen/scripts/callback-processor.ts
  offscreen/scripts/ledger-iframe.ts
  shared/constants/offscreen-communication.ts
  types/global.d.ts
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/create-account/connect-hardware/select-hardware.js
  ui/pages/settings/advanced-tab/advanced-tab.stories.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-extension-platform, needs-dev-review

#22302 Migrate FormTextField to TS
  ui/components/app/modals/eth-sign-modal/eth-sign-modal.js
  ui/components/app/name/name-details/name-details.tsx
  ui/components/component-library/form-text-field/__snapshots__/form-text-field.test.tsx.snap
  ui/components/component-library/form-text-field/deprecated/form-text-field.js
  ui/components/component-library/form-text-field/deprecated/index.js
  ui/components/component-library/form-text-field/form-text-field.stories.tsx
  ui/components/component-library/form-text-field/form-text-field.test.tsx
  ui/components/component-library/form-text-field/form-text-field.tsx
  ui/components/component-library/form-text-field/form-text-field.types.ts
  ui/components/component-library/form-text-field/index.ts
  ui/components/component-library/index.js
  ui/components/component-library/text-field/text-field.tsx
  ui/components/component-library/text-field/text-field.types.ts
  ui/components/multichain/account-details/account-details-authenticate.js
  ui/components/multichain/create-account/create-account.js
  ui/components/multichain/import-account/json.js
  ui/components/multichain/import-account/private-key.js
  ui/components/multichain/import-nfts-modal/import-nfts-modal.js
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
  ui/components/ui/editable-label/editable-label.js
  ui/components/ui/form-combo-field/form-combo-field.tsx
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/swaps/import-token/import-token.js
Labels: team-design-system

#22372 Fix tokensControllers instantiation
  app/scripts/metamask-controller.js
  privacy-snapshot.json
Labels: team-extension-platform

#22354 Version v11.7.3
  .yarn/patches/@metamask-assets-controllers-npm-18.0.0-48bf74a7fa.patch
  .yarn/patches/@metamask-assets-controllers-npm-22.0.0-6af3715fb2.patch
  CHANGELOG.md
  app/scripts/background.js
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  test/e2e/tests/nft/erc1155-interaction.spec.js
  test/e2e/tests/nft/mocks.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/pages/swaps/swaps.util.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE
