Repository MetaMask/metamask-extension, pull requests merged in 2023-07, with the labels that each got.

#19836 Fix #19835 - Update BNB Chain name
  shared/constants/network.ts
Labels: needs-ux-ds-review

#19787 Render correct image in the asset dropdown while sending an NFT
  ui/pages/send/send-content/send-asset-row/send-asset-row.component.js
Labels: team-extension-UX

#19794 Fix #19833 - UX: Multichain: Use new Box component
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/multichain/account-details/account-details-authenticate.js
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/account-details/account-details-key.js
  ui/components/multichain/account-details/account-details.js
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/create-account/create-account.js
  ui/components/multichain/import-account/__snapshots__/json.test.tsx.snap
  ui/components/multichain/import-account/bottom-buttons.js
  ui/components/multichain/import-account/import-account.js
  ui/components/multichain/import-token-link/__snapshots__/import-token-link.test.js.snap
  ui/components/multichain/import-token-link/import-token-link.js
  ui/components/multichain/network-list-item/__snapshots__/network-list-item.test.js.snap
  ui/components/multichain/network-list-item/network-list-item.js
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/nft-item/nft-item.js
Labels: needs-ux-ds-review

#19725 feature(19457): fix encrypt-decrypt.spec.js flaky tests
  test/e2e/tests/encrypt-decrypt.spec.js
Labels: team-extension-client, team-extension-platform

#19812 Fix #19832 - UX: Multichain: Move location of test networks
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: needs-ux-ds-review

#19811 UX: Multichain: Convert AccountDetails Popover to Modal
  test/e2e/tests/import-flow.spec.js
  test/e2e/tests/incremental-security.spec.js
  ui/components/multichain/account-details/account-details.js
Labels: needs-ux-ds-review

#19306 [FLASK] Allow Snaps to use `eth_accounts` as a revokable permission
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  shared/constants/snaps/permissions.ts
  ui/components/app/permission-cell/permission-cell-options.js
  ui/components/app/permission-cell/permission-cell.js
  ui/components/app/permission-cell/permission-cell.test.js
  ui/components/app/permission-page-container/index.scss
  ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js
  ui/components/app/permission-page-container/permission-page-container.component.js
  ui/components/app/permissions-connect-header/permissions-connect-header.component.js
  ui/components/app/snaps/snap-authorship-header/snap-authorship-header.js
  ui/components/app/snaps/snap-permissions-list/snap-permissions-list.js
  ui/components/app/snaps/snap-version/snap-version.js
  ui/components/app/snaps/snap-version/snap-version.test.js
  ui/components/app/snaps/update-snap-permission-list/update-snap-permission-list.js
  ui/pages/permissions-connect/choose-account/choose-account.js
  ui/pages/permissions-connect/permissions-connect.component.js
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
  ui/pages/settings/snaps/view-snap/view-snap.js
  ui/pages/settings/snaps/view-snap/view-snap.test.js
  ui/store/actions.ts
Labels: flask, team-snaps

#19759 Add stale bot to extension
  .github/workflows/stale-issues-pr.yml
Labels: team-extension-client, team-extension-platform

#19919 [FLASK] Fix Snaps UI divider
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/components/app/snaps/snap-ui-renderer/index.scss
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
Labels: flask

#19891 Ux Multichain: updated Permission Icon in Header
  ui/components/multichain/connected-site-menu/__snapshots__/connected-site-menu.test.js.snap
  ui/components/multichain/connected-site-menu/connected-site-menu.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#19809 UX: Multichain: Use Modal for AccountListMenu
  ui/components/multichain/account-list-menu/account-list-menu.js
Labels: team-extension-UX, needs-ux-ds-review

#19803 UX: Multichain: Convert Networks Menu to Modal
  ui/components/multichain/network-list-item/__snapshots__/network-list-item.test.js.snap
  ui/components/multichain/network-list-item/network-list-item.js
  ui/components/multichain/network-list-menu/index.scss
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: team-extension-UX, needs-ux-ds-review

#19939 [FLASK] `snaps@0.36.1-flask.1`
  builds.yml
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  package.json
  test/env.js
  yarn.lock
Labels: flask

#19953 UX: Ensure NFT Options Menu is Same Size as Tokens
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-options/nft-options.js
Labels: team-extension-UX, needs-ux-ds-review

#19666 Token allowance flow update
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/tests/custom-token-add-approve.spec.js
  ui/components/app/custom-spending-cap/__snapshots__/custom-spending-cap.test.js.snap
  ui/components/app/custom-spending-cap/custom-spending-cap.js
  ui/components/app/custom-spending-cap/custom-spending-cap.stories.js
  ui/components/app/custom-spending-cap/custom-spending-cap.test.js
  ui/components/ui/review-spending-cap/review-spending-cap.js
  ui/helpers/constants/zendesk-url.js
  ui/pages/token-allowance/__snapshots__/token-allowance.test.js.snap
  ui/pages/token-allowance/token-allowance.js
  ui/pages/token-allowance/token-allowance.test.js
Labels: team-confirmations-secure-ux-PR, QA Passed

#19952 Fix #19393 - Add indicator for Refresh list on tokens screen
  ui/components/multichain/import-token-link/import-token-link.js
  ui/components/multichain/import-token-link/import-token-link.test.js
  ui/store/actions.ts
Labels: team-extension-UX, needs-ux-ds-review

#19962 feat(19464): fix flaky test in MV3 Deploy contract and call contract methods
  test/e2e/tests/contract-interactions.spec.js
  test/e2e/webdriver/driver.js
Labels: team-extension-client, team-extension-platform

#19938 Show product tour only on home page
  ui/components/multichain/app-header/app-header.js
Labels: team-extension-UX, needs-ux-ds-review

#19511 Integrating ppom-validator with extension
  app/manifest/v2/chrome.json
  app/scripts/lib/indexed-db-backend.test.ts
  app/scripts/lib/indexed-db-backend.ts
  app/scripts/metamask-controller.js
  builds.yml
  development/build/static.js
  package.json
  yarn.lock
Labels: team-confirmations-secure-ux-PR

#19948 Fix #19548 - Increase address copy to clipboard time
  ui/components/multichain/address-copy-button/address-copy-button.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#19858 Part of #18714: Replacing deprecated constants
  ui/components/app/detected-token/detected-token-aggregators/detected-token-aggregators.js
  ui/components/app/detected-token/detected-token-aggregators/detected-token-aggregators.stories.js
  ui/components/app/detected-token/detected-token-details/detected-token-details.js
  ui/components/app/detected-token/detected-token-details/detected-token-details.stories.js
  ui/components/app/detected-token/detected-token-values/detected-token-values.js
Labels: design-system

#19964 UX Multichain: Replace badge icon with current network image
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/token-list-item.js
  ui/components/multichain/token-list-item/token-list-item.stories.js
Labels: team-extension-UX

#19708 fix flakiness in mv3 multiple restart test
  test/e2e/helpers.js
  test/e2e/mv3/multiple-restarts.spec.js
  test/e2e/webdriver/driver.js
Labels: team-extension-client, team-extension-platform

#17945 Added customize tx nonce on ERC20 approve screen when feature is enabled
  ui/components/app/app-components.scss
  ui/components/app/custom-nonce/custom-nonce.js
  ui/components/app/custom-nonce/custom-nonce.test.js
  ui/components/app/custom-nonce/index.js
  ui/components/app/custom-nonce/index.scss
  ui/components/app/modals/customize-nonce/__snapshots__/customize-nonce.test.js.snap
  ui/components/app/modals/customize-nonce/customize-nonce.component.js
  ui/components/app/modals/customize-nonce/index.scss
  ui/pages/confirm-approve/confirm-approve-content/__snapshots__/confirm-approve-content.component.test.js.snap
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-approve/confirm-approve-content/index.scss
  ui/pages/confirm-approve/confirm-approve.js
  ui/pages/token-allowance/__snapshots__/token-allowance.test.js.snap
  ui/pages/token-allowance/index.scss
  ui/pages/token-allowance/token-allowance.js
  ui/pages/token-allowance/token-allowance.test.js
Labels: team-confirmations-secure-ux-PR

#19997 feat(19726): fix flaky test in Dapp interactions caused by home-container rerender
  test/e2e/tests/dapp-interactions.spec.js
  ui/components/institutional/interactive-replacement-token-notification/interactive-replacement-token-notification.js
  ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.js
Labels: team-extension-client, team-extension-platform

#19988 UX: Remove Portfolio from Token Overview Page
  ui/components/app/wallet-overview/token-overview.js
  ui/components/app/wallet-overview/token-overview.test.js
Labels: needs-ux-ds-review

#19920 fixed button in wallet-overview
  ui/components/ui/icon-button/icon-button.js
  ui/components/ui/icon-button/icon-button.scss
Labels: release-blocker, team-extension-client, team-extension-UX, release-10.34.0

#19947 Fix #19941 - Correctly show network name and selection when chainIds collide
  test/data/mock-state.json
  test/e2e/fixture-builder.js
  test/e2e/tests/custom-rpc-history.spec.js
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/nft-details.test.js
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: needs-ux-ds-review

#19770 Add alternative summary UI with arrow icon to the Disclosure component
  ui/components/ui/disclosure/disclosure.constants.ts
  ui/components/ui/disclosure/disclosure.js
  ui/components/ui/disclosure/disclosure.scss
  ui/components/ui/disclosure/disclosure.stories.js
Labels: design-system, team-confirmations-secure-ux-PR

#19951 UX: Network Menu: Disable testnet toggle when on testnet
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
Labels: team-extension-client, team-extension-UX

#20026 Updated button label to "Add hardware wallet" in the Accounts Menu list
  app/_locales/en/messages.json
  test/e2e/tests/import-flow.spec.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/account-list-menu.test.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#19806 Move "Import NFTs" to Modal
  development/ts-migration-dashboard/files-to-convert.json
  test/e2e/nft/import-erc1155.spec.js
  test/e2e/nft/import-nft.spec.js
  ui/components/app/modals/convert-token-to-nft-modal/convert-token-to-nft-modal.js
  ui/components/app/nfts-detection-notice/index.scss
  ui/components/app/nfts-tab/nfts-tab.js
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/components/multichain/import-nfts-modal/import-nfts-modal.js
  ui/components/multichain/import-nfts-modal/import-nfts-modal.stories.js
  ui/components/multichain/import-nfts-modal/import-nfts-modal.test.js
  ui/components/multichain/import-nfts-modal/index.js
  ui/components/multichain/import-nfts-modal/index.scss
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
  ui/ducks/app/app.ts
  ui/helpers/constants/routes.ts
  ui/pages/add-nft/add-nft.js
  ui/pages/add-nft/index.js
  ui/pages/home/home.component.js
  ui/pages/import-token/import-token.component.js
  ui/pages/import-token/import-token.container.js
  ui/pages/pages.scss
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20030 Show a balance for the Token To, update position of the MM fee, removes a link
  app/_locales/en/messages.json
  test/e2e/swaps/shared.js
  ui/pages/swaps/exchange-rate-display/__snapshots__/exchange-rate-display.test.js.snap
  ui/pages/swaps/exchange-rate-display/exchange-rate-display.js
  ui/pages/swaps/exchange-rate-display/index.scss
  ui/pages/swaps/loading-swaps-quotes/__snapshots__/loading-swaps-quotes-stories-metadata.test.js.snap
  ui/pages/swaps/main-quote-summary/__snapshots__/main-quote-summary.test.js.snap
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
  ui/pages/swaps/prepare-swap-page/review-quote.js
  ui/pages/swaps/prepare-swap-page/review-quote.test.js
  ui/pages/swaps/view-quote/__snapshots__/view-quote.test.js.snap
Labels: needs-ux-ds-review

#19769 Updating BadgeWrapper to use TS version of Box
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/component-library/badge-wrapper/__snapshots__/badge-wrapper.test.tsx.snap
  ui/components/component-library/badge-wrapper/badge-wrapper.test.tsx
  ui/components/component-library/badge-wrapper/badge-wrapper.tsx
  ui/components/component-library/badge-wrapper/badge-wrapper.types.ts
  ui/components/multichain/connected-site-menu/__snapshots__/connected-site-menu.test.js.snap
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
Labels: design-system, needs-ux-ds-review

#20053 UX: Updated nfts detection notice to use Banner
  ui/components/app/app-components.scss
  ui/components/app/nfts-detection-notice/index.scss
  ui/components/app/nfts-detection-notice/nfts-detection-notice.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20048 Direct users to testnet toggle on dapp requests
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: team-extension-client, team-extension-UX

#20032 UX Multichain: Added background color of test networks
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/nft-item/nft-item.js
  ui/components/multichain/nft-item/nft-item.test.js
  ui/components/multichain/token-list-item/token-list-item.js
  ui/selectors/selectors.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20036 UX: Avoid Popover Footer when No Connected Sites
  ui/pages/connected-accounts/connected-accounts.component.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20059 UX: Make 'Done' button a block in Account Details
  ui/components/multichain/account-details/account-details-key.js
Labels: team-extension-UX, needs-ux-ds-review

#20061 Update Text import paths: /multichain
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/app/token-cell/token-cell.stories.js
  ui/components/multichain/account-details/account-details-authenticate.js
  ui/components/multichain/account-details/account-details-key.js
  ui/components/multichain/account-details/account-details.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/import-account/__snapshots__/json.test.tsx.snap
  ui/components/multichain/import-account/import-account.js
  ui/components/multichain/import-account/json.js
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/product-tour-popover/product-tour-popover.js
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/token-list-item.js
Labels: design-system, needs-ux-ds-review

#20065 UX: Remove unwanted async callback
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: needs-ux-ds-review

#20068 UX Multichain: Added background color of test network to activity screen
  ui/components/app/transaction-list-item/transaction-list-item.component.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20064 Update Text import paths: /institutional
  ui/components/institutional/compliance-details/__snapshots__/compliance-details.test.js.snap
  ui/components/institutional/compliance-details/compliance-details.js
  ui/components/institutional/compliance-modal/__snapshots__/compliance-modal.test.js.snap
  ui/components/institutional/compliance-modal/compliance-modal.js
  ui/components/institutional/compliance-settings/__snapshots__/compliance-settings.test.js.snap
  ui/components/institutional/compliance-settings/compliance-settings.js
  ui/components/institutional/custody-labels/__snapshots__/custody-labels.test.js.snap
  ui/components/institutional/custody-labels/custody-labels.js
  ui/components/institutional/interactive-replacement-token-notification/interactive-replacement-token-notification.js
  ui/components/institutional/jwt-dropdown/__snapshots__/jwt-dropdown.test.js.snap
  ui/components/institutional/jwt-dropdown/jwt-dropdown.js
  ui/components/institutional/jwt-url-form/__snapshots__/jwt-url-form.test.js.snap
  ui/components/institutional/jwt-url-form/jwt-url-form.js
  ui/components/institutional/note-to-trader/__snapshots__/note-to-trader.test.js.snap
  ui/components/institutional/note-to-trader/note-to-trader.js
  ui/components/institutional/wrong-network-notification/wrong-network-notification.js
Labels: design-system

#20013 Fix #20006 - Add Address Details and View on Explorer to Global Menu
  test/e2e/tests/permissions.spec.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.stories.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.test.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/global-menu/global-menu.test.js
  ui/components/multichain/index.js
  ui/components/multichain/menu-items/account-details-menu-item.js
  ui/components/multichain/menu-items/account-details-menu-item.test.js
  ui/components/multichain/menu-items/index.js
  ui/components/multichain/menu-items/view-explorer-menu-item.js
  ui/components/multichain/menu-items/view-explorer-menu-item.test.js
Labels: team-extension-UX, needs-ux-ds-review

#20009 UX: Increase network name threshold before showing tooltip
  ui/components/multichain/network-list-item/network-list-item.js
Labels: needs-ux-ds-review

#20070 Part of #18714: Replacing deprecated constants and components
  ui/components/app/signature-request-original/signature-request-original-warning/signature-request-original-warning.js
  ui/components/app/signature-request-original/signature-request-original-warning/signature-request-original-warning.stories.js
Labels: design-system

#20003 Part of #18714: Replacing deprecated constants
  ui/components/app/qr-hardware-popover/qr-hardware-sign-request/player.js
  ui/components/app/qr-hardware-popover/qr-hardware-sign-request/player.stories.js
  ui/components/app/signature-request-siwe/signature-request-siwe-icon/index.js
  ui/components/app/signature-request-siwe/signature-request-siwe-tag/index.js
  ui/components/app/tab-bar/tab-bar.js
Labels: design-system

#20069 [FLASK] `snaps@0.37.1-flask.1`
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/app/snaps/snap-ui-markdown/snap-ui-markdown.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  yarn.lock
Labels: flask

#20078 fix(lint): Change endOfLine rules to better support linting on Windows
  .eslintrc.base.js
  .prettierrc.yml
  package.json
Labels: team-accounts

#20101 feat(882): Optimize metrics function usage during onboarding flow
  test/e2e/helpers.js
  test/e2e/metrics/permissions-approved.spec.js
  test/e2e/metrics/unlock-wallet.spec.js
  test/e2e/metrics/wallet-created.spec.js
  ui/pages/onboarding-flow/welcome/welcome.js
Labels: team-extension-client, team-extension-platform

#19104 Signature-Request refactor
  test/e2e/tests/eth-sign.spec.js
  test/e2e/tests/personal-sign.spec.js
  test/e2e/tests/signature-request.spec.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request/__snapshots__/signature-request.test.js.snap
  ui/components/app/signature-request/index.js
  ui/components/app/signature-request/index.scss
  ui/components/app/signature-request/signature-request.component.js
  ui/components/app/signature-request/signature-request.constants.js
  ui/components/app/signature-request/signature-request.container.js
  ui/components/app/signature-request/signature-request.container.test.js
  ui/components/app/signature-request/signature-request.js
  ui/components/app/signature-request/signature-request.stories.js
  ui/components/app/signature-request/signature-request.test.js
  ui/hooks/useMMICustodySignMessage.js
  ui/hooks/useRejectTransactionModal.js
  ui/pages/confirm-signature-request/__snapshots__/index.test.js.snap
  ui/pages/confirm-signature-request/index.test.js
Labels: team-confirmations-secure-ux-PR, QA Passed

#20107 fix ts spread props issue
  ui/components/component-library/text/text.tsx
Labels: design-system, needs-ux-ds-review

#20067 UX: Use classNames in ConnectedSitesMenu
  ui/components/multichain/connected-site-menu/__snapshots__/connected-site-menu.test.js.snap
  ui/components/multichain/connected-site-menu/connected-site-menu.js
Labels: needs-ux-ds-review

#19825 New SecurityProviderBannerAlert component
  app/_locales/en/messages.json
  shared/constants/security-provider.ts
  ui/components/app/security-provider-banner-alert/__snapshots__/security-provider-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/index.js
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.js
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.stories.js
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.test.js
Labels: team-confirmations-secure-ux-PR

#19998 [FLASK] Unblock `personal_sign` for snaps
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/snaps/snap-legacy-authorship-header/index.js
  ui/components/app/snaps/snap-legacy-authorship-header/snap-legacy-authorship-header.js
  ui/components/app/snaps/snap-legacy-authorship-header/snap-legacy-authorship-header.stories.js
  ui/pages/confirm-signature-request/index.js
Labels: flask

#20119 Removing unused deprecated `Text` component
  ui/components/component-library/text/deprecated/__snapshots__/text.test.tsx.snap
  ui/components/component-library/text/deprecated/index.ts
  ui/components/component-library/text/deprecated/text.test.tsx
  ui/components/component-library/text/deprecated/text.tsx
  ui/components/component-library/text/deprecated/text.types.ts
Labels: team-design-system, needs-ux-ds-review

#20005 Fix snaps E2Es to be compatible with new monorepo-based test-snaps
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-error.spec.js
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/snaps/test-snap-getentropy.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-manageAccount.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-networkaccess.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  test/e2e/snaps/test-snap-wasm.spec.js
  test/e2e/webdriver/driver.js
Labels: flask

#20051 New BlockaidBannerAlert component
  app/_locales/en/messages.json
  shared/constants/security-provider.ts
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.stories.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/index.js
Labels: team-confirmations-secure-ux-PR

#20136 [FLASK] Filter out snaps source code and state from UI state
  app/scripts/metamask-controller.js
Labels: flask

#20134 UX: Remove height from loading block, use modern components
  ui/components/app/token-list/token-list.js
Labels: needs-ux-ds-review

#20131 UX: Fix display block value
  ui/pages/settings/settings.component.js
Labels: needs-ux-ds-review

#20133 UX: Fix TextColor value casing
  ui/components/app/approve-content-card/approve-content-card.js
  ui/components/app/ledger-instruction-field/__snapshots__/ledger-instruction-field.test.js.snap
  ui/components/app/ledger-instruction-field/ledger-instruction-field.js
Labels: needs-ux-ds-review

#20038 Part of #18714 for 2 files in ui\components\component-library\avatar-icon
  ui/components/component-library/avatar-icon/avatar-icon.js
  ui/components/component-library/avatar-icon/avatar-icon.stories.js
Labels: team-design-system, needs-ux-ds-review

#20152 Fix #20140 - Ensure only one network displays as selected in the network picker when chain IDs collide
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
Labels: needs-ux-ds-review

#20146 fix: remove unused useMethodData code
  ui/hooks/useMethodData.js
Labels: team-extension-client, team-extension-platform

#20144 UX: Ensure block explorer link is for desired account
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/menu-items/view-explorer-menu-item.js
  ui/components/multichain/menu-items/view-explorer-menu-item.test.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#19171 Restructure CurrencyDisplay to use Design System
  ui/components/app/confirm-gas-display/__snapshots__/confirm-gas-display.test.js.snap
  ui/components/app/confirm-gas-display/confirm-legacy-gas-display/__snapshots__/confirm-legacy-gas-display.test.js.snap
  ui/components/app/confirm-page-container/confirm-detail-row/__snapshots__/confirm-detail-row.component.test.js.snap
  ui/components/app/currency-input/__snapshots__/currency-input.test.js.snap
  ui/components/app/modals/cancel-transaction/cancel-transaction-gas-fee/__snapshots__/cancel-transaction-gas-fee.component.test.js.snap
  ui/components/app/multilayer-fee-message/__snapshots__/multi-layer-fee-message.test.js.snap
  ui/components/app/user-preferenced-currency-display/__snapshots__/user-preferenced-currency-display.test.js.snap
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/ui/currency-display/__snapshots__/currency-display.component.test.js.snap
  ui/components/ui/currency-display/currency-display.component.js
  ui/components/ui/currency-display/currency-display.stories.js
  ui/components/ui/currency-display/index.scss
  ui/components/ui/ui-components.scss
  ui/pages/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/send/send-content/__snapshots__/send-content.component.test.js.snap
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#19563 Replacing deprecated constants and adding new stories
  ui/components/app/app-components.scss
  ui/components/app/snaps/snap-remove-warning/index.scss
  ui/components/app/snaps/snap-remove-warning/snap-remove-warning.js
  ui/components/app/snaps/snap-remove-warning/snap-remove-warning.stories.js
  ui/components/app/snaps/snap-ui-markdown/snap-ui-markdown.js
  ui/components/app/snaps/snap-ui-markdown/snap-ui-markdown.stories.js
  ui/pages/settings/snaps/view-snap/view-snap.js
Labels: team-design-system

#19559 Issue 18896 Replace deprecated Button component with new Button component
  test/e2e/swaps/swaps-notifications.spec.js
  ui/components/component-library/modal-content/__snapshots__/modal-content.test.tsx.snap
  ui/components/component-library/modal-content/modal-content.tsx
  ui/components/component-library/modal-content/modal-content.types.ts
  ui/components/ui/url-icon/url-icon.js
  ui/pages/swaps/dropdown-search-list/dropdown-search-list.js
  ui/pages/swaps/import-token/import-token.js
  ui/pages/swaps/import-token/import-token.stories.js
  ui/pages/swaps/import-token/import-token.test.js
  ui/pages/swaps/import-token/index.scss
  ui/pages/swaps/index.scss
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
Labels: team-design-system

#20135 UX: Show Checksum Addresses in Account Menu
  ui/components/multichain/account-details/account-details.test.js
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/address-copy-button/address-copy-button.js
  ui/components/multichain/address-copy-button/address-copy-button.test.js
  ui/components/multichain/menu-items/view-explorer-menu-item.js
  ui/components/ui/qr-code/qr-code.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20166 UX: Ensure currently selected account displays when Account Menu opens
  ui/components/multichain/account-list-item/account-list-item.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20168 UX: Allow quick Add Account name based on default name
  ui/components/multichain/create-account/create-account.js
  ui/components/ui/editable-label/editable-label.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20183 Improve Account Details E2E tests
  test/e2e/tests/account-details.spec.js
  ui/components/multichain/account-details/account-details-key.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20235 deps: Bump semver
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: dependencies

#18213 JSON-RPC e2e test POC
  .circleci/config.yml
  package.json
  test/e2e/json-rpc/eth_call.spec.js
  test/e2e/json-rpc/eth_chainId.spec.js
  test/e2e/json-rpc/eth_sendTransaction.spec.js
  test/e2e/run-all.js
Labels: team-extension-client, team-extension-platform

#20102 Allow user to turn off ENS DNS resolution
  app/_locales/en/messages.json
  app/scripts/background.js
  app/scripts/controllers/preferences.js
  app/scripts/lib/ens-ipfs/setup.js
  app/scripts/metamask-controller.js
  test/e2e/helpers.js
  test/e2e/tests/ipfs-ens-resolution.spec.js
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/store/actions.ts
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#19985 Implement Network Menu Search
  app/_locales/en/messages.json
  ui/components/multichain/network-list-item/network-list-item.js
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#20263 Document keyring test scenarios
  test/scenarios/2. keyring/reset a wallet.csv
Labels: team-extension-client, team-extension-platform

#20262 Document onboarding test scenarios
  test/scenarios/1. onboarding/create a wallet.csv
  test/scenarios/1. onboarding/import a wallet.csv
Labels: team-extension-client, team-extension-platform

#20225 UX: Autofocus the Address field in Import NFT modal
  ui/components/multichain/import-nfts-modal/import-nfts-modal.js
Labels: needs-ux-ds-review

#20049 Update transaction status to not be considered anonymous
  app/scripts/controllers/transactions/index.js
  app/scripts/controllers/transactions/index.test.js
  test/e2e/metrics/transaction-finalized.spec.js
Labels: needs-qa, team-confirmations-secure-ux-PR

#19984 feat: github action to check if PR has requested labels before being merged
  .github/scripts/check-pr-has-required-labels.ts
  .github/workflows/check-pr-labels.yml
  .github/workflows/do-not-merge.yml
  package.json
Labels: team-extension-client, team-extension-platform

#20129 feat: implement swap event metric e2e test
  .eslintrc.js
  .mocharc.js
  app/scripts/controllers/transactions/index.js
  jest.config.js
  shared/constants/metametrics.ts
  test/e2e/helpers.js
  test/e2e/helpers.test.js
  test/e2e/metrics/mock-data.js
  test/e2e/metrics/swaps.spec.js
  test/e2e/mv3/multiple-restarts.spec.js
  ui/ducks/swaps/swaps.js
Labels: team-extension-client, team-extension-platform, needs-dev-review

#20137 Part of #17670 for: ui\components\app\snaps\snap-content-footer\snap-content-footer.js
  ui/components/app/snaps/snap-content-footer/index.scss
  ui/components/app/snaps/snap-content-footer/snap-content-footer.js
  ui/components/app/snaps/snap-content-footer/snap-content-footer.stories.js
Labels: team-design-system

#20220 Fix #19950 - Use removable property to determine if network should be removable in Network Menu List
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: needs-ux-ds-review

#18840 Update @metamask/phishing-controller to v4.0.0
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.test.js
  app/scripts/migrations/090.test.js
  app/scripts/migrations/090.ts
  app/scripts/migrations/index.js
  package.json
  test/e2e/helpers.js
  test/e2e/mock-e2e.js
  test/e2e/mv3/phishing-warning-sw-restart.spec.js
  test/e2e/run-all.js
  test/e2e/tests/phishing-controller/helpers.js
  test/e2e/tests/phishing-controller/mocks.js
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
  yarn.lock
Labels: release-blocker, needs-dev-review, release-10.32.2

#20264 Document phishing test scenarios
  test/scenarios/6. phishing/warning page.csv
Labels: team-extension-client, team-extension-platform

#20260 Document token test scenarios
  test/scenarios/4. tokens/import erc1155 token origin MM.csv
  test/scenarios/4. tokens/import erc20 token origin MM.csv
  test/scenarios/4. tokens/import erc721 token origin MM.csv
Labels: team-extension-client, team-extension-platform

#20259 Document transaction test scenarios
  test/scenarios/3. transactions/cancel transaction.csv
  test/scenarios/3. transactions/send erc20 token origin MM.csv
  test/scenarios/3. transactions/send erc721 token origin MM.csv
  test/scenarios/3. transactions/send native token origin MM.csv
  test/scenarios/3. transactions/speed up transaction.csv
Labels: team-extension-client, team-extension-platform
