Repository MetaMask/metamask-extension, pull requests merged in 2024-03, with the labels that each got.

#23265 fix: Updated avatar for non multichain fix
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#23221 fix: Add missing scss file in `pages.scss`
  ui/pages/pages.scss
Labels: team-confirmations-secure-ux

#23249 fix: Fix broken Multichain send jest tests
  test/data/mock-state.json
  ui/components/multichain/pages/send/send.test.js
Labels: team-wallet-ux, needs-assets-ux-review

#23182 feat: remove PermissionLogController in favor of core implementation
  app/scripts/controllers/permissions/enums.js
  app/scripts/controllers/permissions/index.js
  app/scripts/controllers/permissions/permission-log.js
  app/scripts/controllers/permissions/permission-log.test.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/mocks/permissions.js
  yarn.lock
Labels: team-shared-libraries, INVALID-PR-TEMPLATE

#23224 feat: replace EnsController with core implementation
  app/scripts/controllers/ens/ens.js
  app/scripts/controllers/ens/index.js
  app/scripts/controllers/ens/index.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: team-shared-libraries, INVALID-PR-TEMPLATE

#23007 refactor(snap-keyring): refactor confirmation dialogs
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/lib/snap-keyring/types.ts
  app/scripts/lib/snap-keyring/utils/getSnapName.test.ts
  app/scripts/lib/snap-keyring/utils/getSnapName.ts
  app/scripts/lib/snap-keyring/utils/showResult.ts
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/pages/confirmations/components/snap-account-error-message/SnapAccountErrorMessage.test.tsx
  ui/pages/confirmations/components/snap-account-error-message/SnapAccountErrorMessage.tsx
  ui/pages/confirmations/components/snap-account-error-message/index.tsx
  ui/pages/confirmations/components/snap-account-success-message/SnapAccountSuccessMessage.test.tsx
  ui/pages/confirmations/components/snap-account-success-message/SnapAccountSuccessMessage.tsx
  ui/pages/confirmations/components/snap-account-success-message/index.tsx
Labels: area-accounts, area-snaps, team-accounts

#23191 feat: add palm svg icon
  app/images/palm.svg
Labels: team-extension-ux, needs-dev-review, team-assets, team-wallet-ux

#23259 fix(22937): fix frozen wallet when switching network locally
  ui/components/ui/new-network-info/new-network-info.js
Labels: team-extension-platform, needs-dev-review

#23229 refactor: align variable use in fonts.scss to use same format as elsewhere
  ui/css/utilities/fonts.scss
Labels: team-extension-platform

#23130 fix: removes extra domains from `SelectedNetworkController` domain state
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  app/scripts/migrations/111.test.ts
  app/scripts/migrations/111.ts
  app/scripts/migrations/index.js
  package.json
  test/e2e/fixture-builder.js
  test/e2e/tests/request-queuing/multiple-networks-dapps-txs.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/e2e/webdriver/driver.js
  yarn.lock
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE, team-wallet-ux

#23209 chore: document our `package.json` via JSON Schema – for contributors using VSCode
  .vscode/package.json-schema.json
  .vscode/settings.json
Labels: team-extension-platform, needs-dev-review

#23238 test: add scenario set custom spending cap for custom token
  test/scenarios/13. sign/sign typed data v4 with hardware wallet.csv
  test/scenarios/4. tokens/approve erc20 custom amount.csv
Labels: team-confirmations-system, release-11.12.0

#23250 fix: remove duplicate html `<title>` tag in `home.html` (#23218)
  app/home.html
  development/build/scripts.js
Labels: team-extension-platform, needs-dev-review

#23232 feat: added menu types to render in account list item
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.stories.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/account-list-item/account-list-item.types.js
  ui/components/multichain/account-list-item/index.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/hidden-account-list.js
  ui/components/multichain/connected-status/connected-status.tsx
  ui/components/multichain/index.js
  ui/components/multichain/pages/connections/connections.tsx
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23266 chore: [MMI] Adds mmi controllers to MM state object (Sentry)
  app/scripts/lib/setupSentry.js
  test/e2e/tests/errors.spec.js
Labels: team-mmi

#23267 fix: SnapUIRenderer rendering an empty delineator when loading
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#23214 Fix: remove top styling for icon inherit
  ui/components/component-library/button-base/button-base.types.ts
  ui/components/component-library/button-link/button-link.scss
  ui/components/component-library/button-link/button-link.tsx
Labels: type-bug, team-design-system

#23215 build: replace `squirrelly` with `eta`
  .gitattributes
  .vscode/extensions.json
  .vscode/settings.json
  .yarn/patches/squirrelly-npm-9.0.0-3cf710c7bb.patch
  app/home.html
  app/notification.html
  development/build/scripts.js
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#23046 Fix: PetNamesBridge to use InternalAccounts
  app/scripts/lib/AbstractPetnamesBridge.ts
  app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts
  app/scripts/lib/AccountIdentitiesPetnamesBridge.ts
  app/scripts/lib/AddressBookPetnamesBridge.ts
  app/scripts/metamask-controller.js
  test/jest/mocks.js
Labels: team-accounts

#22103 test: Add dapp interaction of wallet_revokePermissions for eth_accounts
  test/e2e/tests/revoke-permissions.spec.js
Labels: area-testSuite, team-wallet-api-platform, needs-dev-review, e2e-test

#23300 fix: flaky "Send ETH from inside MetaMask finds the transaction..."
  test/e2e/tests/send-eth.spec.js
Labels: team-extension-platform, needs-dev-review

#23298 feat: Add sepolia and update ppom
  app/scripts/lib/ppom/ppom-middleware.ts
  package.json
  yarn.lock
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#23297 feat: enable erc1155 multichain
  test/e2e/tests/nft/send-nft.spec.js
  ui/components/multichain/asset-picker-amount/asset-picker-amount.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx
  ui/components/multichain/asset-picker-amount/index.scss
Labels: team-mobile-ux, team-assets, team-wallet-ux, needs-assets-ux-review

#23308 fix: dynamic UI cherry-picks for RC
  ui/components/app/snaps/snap-ui-renderer/components/types.ts
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/components/app/snaps/snap-ui-renderer/utils.ts
  ui/pages/confirmations/confirmation/templates/index.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22822 fix: Can't call setApprovalForAll on certain NFTs
  ui/pages/confirmations/confirm-approve/confirm-approve.js
Labels: needs-dev-review, team-assets

#23178 fix: disable UI buttons for accounts that cannot sign
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/selectors/selectors.test.js
Labels: type-bug, area-UI, team-accounts

#23277 bump selected network controller to 9.0.0
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  app/scripts/migrations/112.test.ts
  app/scripts/migrations/112.ts
  app/scripts/migrations/index.js
  package.json
  test/e2e/fixture-builder.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  yarn.lock
Labels: team-wallet-api-platform

#23327 fix: asset list showing fiat symbol instead of native
  ui/components/app/asset-list/asset-list.js
Labels: INVALID-PR-TEMPLATE

#23324 fix: update stake image
  app/images/portfolio-stake-notification-light-mode.png
  app/images/staking-light-mode-preview.png
  shared/notifications/index.js
Labels: team-extension-ux, team-portfolio, INVALID-PR-TEMPLATE

#23330 fix: update stake image (#23324)
  app/images/portfolio-stake-notification-light-mode.png
  app/images/staking-light-mode-preview.png
  shared/notifications/index.js
Labels: INVALID-PR-TEMPLATE

#23240 fix: update PPOM CDN
  builds.yml
  package.json
  privacy-snapshot.json
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#23311 feat: bump snaps packages and support `InputChangeEvent` for dynamic UI
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  ui/components/app/snaps/snap-ui-button/snap-ui-button.tsx
  ui/components/app/snaps/snap-ui-form/snap-ui-form.tsx
  ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx
  ui/components/app/snaps/snap-ui-renderer/components/input.ts
  ui/components/app/snaps/snap-ui-renderer/components/types.ts
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/components/app/snaps/snap-ui-renderer/utils.ts
  ui/contexts/snaps/snap-interface.tsx
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#22902 Introduce LavaDome latest addressing React security concern
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/multichain/account-details/account-details-key.js
  yarn.lock
Labels: type-security, dependencies, team-lavamoat, INVALID-PR-TEMPLATE

#23087 refactor(replace deprecated components) Refactor usage of design-system components in Snaps features
  ui/components/app/permission-cell/permission-cell.js
  ui/components/app/snaps/snap-install-warning/index.scss
  ui/components/app/snaps/snap-install-warning/snap-install-warning.js
  ui/components/app/snaps/snap-permissions-list/snap-permissions-list.js
  ui/components/app/snaps/snap-privacy-warning/index.scss
  ui/components/app/snaps/snap-privacy-warning/snap-privacy-warning.js
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
  ui/pages/permissions-connect/snaps/snap-update/snap-update.js
Labels: team-snaps-platform

#23247 fix: removal of account permissions when removing account
  app/scripts/controllers/permissions/caveat-mutators.js
  app/scripts/controllers/permissions/caveat-mutators.test.js
  test/data/mock-state.json
  ui/components/multichain/pages/send/components/recipient.test.tsx
  ui/components/multichain/pages/send/components/your-accounts.test.tsx
  ui/components/multichain/pages/send/send.test.js
Labels: team-accounts

#23342 fix: set isSigningOrSubmitting to false for MMI
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
Labels: team-confirmations-system

#23260 feat: adding currency value component
  ui/components/app/confirm/info/row/__snapshots__/currency.test.tsx.snap
  ui/components/app/confirm/info/row/currency.stories.tsx
  ui/components/app/confirm/info/row/currency.test.tsx
  ui/components/app/confirm/info/row/currency.tsx
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/components/ui/currency-display/currency-display.component.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22766 Confirmation redesign: add message section to personal sign page
  app/_locales/en/messages.json
  test/data/confirmations/personal_sign.ts
  ui/components/app/confirm/info/__snapshots__/info.test.tsx.snap
  ui/components/app/confirm/info/info.stories.tsx
  ui/components/app/confirm/info/info.tsx
  ui/components/app/confirm/info/row/__snapshots__/url.test.tsx.snap
  ui/components/app/confirm/info/row/index.ts
  ui/components/app/confirm/info/row/text.stories.tsx
  ui/components/app/confirm/info/row/text.tsx
  ui/components/app/confirm/info/row/url.tsx
  ui/components/app/confirm/info/row/value-double.tsx
  ui/helpers/utils/util.js
  ui/helpers/utils/util.test.js
  ui/pages/confirmations/components/confirm/info/info.test.tsx
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/personalSign.test.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/personalSign.tsx
  ui/pages/confirmations/components/confirm/signature-message/index.ts
  ui/pages/confirmations/components/confirm/signature-message/signature-message.stories.tsx
  ui/pages/confirmations/components/confirm/signature-message/signature-message.test.tsx
  ui/pages/confirmations/components/confirm/signature-message/signature-message.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/components/signature-request-original/signature-request-original.component.js
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/confirm.test.tsx
  ui/pages/confirmations/confirm/confirm.tsx
  ui/selectors/confirm.ts
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#23345 fix: update PPOM to v1.4.4
  package.json
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  yarn.lock
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#23301 test: improve request queuing e2e methods
  test/e2e/tests/request-queuing/switch-network.spec.js
Labels: area-testSuite, team-wallet-api-platform, INVALID-PR-TEMPLATE, e2e-test

#23310 Version v11.11.2
  CHANGELOG.md
  app/images/portfolio-stake-notification-light-mode.png
  app/images/staking-light-mode-preview.png
  package.json
  shared/notifications/index.js
  ui/components/app/asset-list/asset-list.js
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/token-list-item.js
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE, release-11.11.2

#23354 test: Wait for connection dialog to close
  test/e2e/tests/request-queuing/switch-network.spec.js
Labels: area-testSuite, team-extension-platform, team-wallet-api-platform, needs-dev-review, e2e-test

#23274 fix: Fix #23255 - Prevent NewNetworkInfo popover from displaying during send flow
  ui/pages/routes/routes.component.js
Labels: needs-dev-review, team-wallet-ux, needs-assets-ux-review

#23358 feat: support bulk balance checks on blast
  app/scripts/constants/contracts.ts
  shared/constants/network.ts
Labels: team-assets

#23133 test: [Snaps E2E] Create test for Signature Insights
  test/e2e/run-all.js
  test/e2e/snaps/test-snap-siginsights.spec.js
  ui/components/app/snaps/insight-warnings/insight-warnings.js
Labels: area-snaps, team-snaps-platform

#23362 Version v11.11.3
  CHANGELOG.md
  app/scripts/constants/contracts.ts
  package.json
  shared/constants/network.ts
Labels: INVALID-PR-TEMPLATE, release-11.11.3

#23258 feat: Implement ConnectedAccountsMenu buttons
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/connected-accounts-menu/connected-accounts-menu.test.tsx
  ui/components/multichain/connected-accounts-menu/connected-accounts-menu.tsx
  ui/components/multichain/connected-accounts-menu/connected-accounts-menu.types.ts
  ui/components/multichain/connected-accounts-menu/index.scss
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/pages/connections/connections.tsx
Labels: team-wallet-ux, needs-assets-ux-review

#23113 feat(snap-keyring): more snap account metrics
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/metamask-controller.js
  docs/confirmations.md
  shared/constants/metametrics.ts
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirmations/confirmation/confirmation.js
  ui/pages/confirmations/confirmation/templates/create-snap-account.js
  ui/pages/confirmations/confirmation/templates/index.js
  ui/pages/confirmations/confirmation/templates/remove-snap-account.js
  ui/pages/confirmations/confirmation/templates/snap-account-redirect.js
  ui/pages/snap-account-transaction-loading-screen/index.ts
  ui/pages/snap-account-transaction-loading-screen/snap-account-transaction-loading-screen.tsx
Labels: area-accounts, area-snaps, team-accounts

#23369 fix: use gap for Snap UI spacing
  ui/components/app/snaps/snap-ui-button/snap-ui-button.tsx
  ui/components/app/snaps/snap-ui-form/snap-ui-form.tsx
  ui/components/app/snaps/snap-ui-image/snap-ui-image.tsx
  ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx
  ui/components/app/snaps/snap-ui-markdown/snap-ui-markdown.js
  ui/components/app/snaps/snap-ui-renderer/components/copyable.ts
  ui/components/app/snaps/snap-ui-renderer/components/divider.ts
  ui/components/app/snaps/snap-ui-renderer/components/heading.ts
  ui/components/app/snaps/snap-ui-renderer/components/row.ts
  ui/components/app/snaps/snap-ui-renderer/index.scss
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#23278 build: remove static copy of `react-responsive-carousel` styles as it is no longer used statically
  development/build/static.js
Labels: team-extension-platform

#23264 fix: asset picker touch ups
  shared/constants/tokens.js
  ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
Labels: team-assets, needs-assets-ux-review

#23189 feat: MCv1 Permissions: Site Connections Tooltip
  app/_locales/en/messages.json
  ui/components/multichain/pages/permissions-page/__snapshots__/permissions-page.test.js.snap
  ui/components/multichain/pages/permissions-page/connection-list-item.js
  ui/components/multichain/pages/permissions-page/connection-list-item.stories.js
  ui/components/multichain/pages/permissions-page/connection-list-item.test.js
  ui/components/multichain/pages/permissions-page/connection-list-tooltip/connection-list-tooltip.js
  ui/components/multichain/pages/permissions-page/connection-list-tooltip/connection-list-tooltip.stories.js
  ui/selectors/selectors.js
Labels: team-extension-ux, needs-ux-ds-review, needs-dev-review, team-wallet-ux, needs-assets-ux-review

#23382 fix: cherry-pick snaps hotfix to RC
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#23383 fix: enable Snaps home pages in stable
  shared/constants/permissions.test.js
  shared/constants/snaps/permissions.ts
  test/e2e/run-all.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#23371 feat: reveal and hide private keys
  app/_locales/en/messages.json
  ui/components/multichain/import-account/private-key.js
  ui/components/ui/show-hide-toggle/index.scss
Labels: team-accounts, needs-dev-review

#23381 v11.11.4
  CHANGELOG.md
  package.json
  shared/constants/permissions.test.js
  shared/constants/snaps/permissions.ts
  test/e2e/run-all.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#23309 docs: [E2E] Update readme for e2e tests
  README.md
Labels: area-documentation, team-extension-platform, needs-dev-review, e2e-test

#23010 Replace useSafeGasEstimatePolling with usePolling
  app/scripts/metamask-controller.js
  development/ts-migration-dashboard/files-to-convert.json
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/e2e/snaps/test-snap-txinsights-v2.spec.js
  ui/components/app/cancel-speedup-popover/cancel-speedup-popover.test.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.test.js
  ui/components/multichain/pages/send/send.test.js
  ui/ducks/metamask/metamask.js
  ui/helpers/utils/gas.js
  ui/hooks/useGasFeeEstimates.js
  ui/hooks/useGasFeeEstimates.test.js
  ui/hooks/usePolling.test.js
  ui/hooks/usePolling.ts
  ui/hooks/useSafeGasEstimatePolling.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.test.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.test.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-input-subtext/advanced-gas-fee-input-subtext.test.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.test.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.test.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-popover.test.js
  ui/pages/confirmations/components/confirm-gas-display/confirm-gas-display.test.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-container.test.js
  ui/pages/confirmations/components/edit-gas-fee-button/edit-gas-fee-button.test.js
  ui/pages/confirmations/components/edit-gas-fee-icon/edit-gas-fee-icon.test.js
  ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-fee-popover.test.js
  ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-item/edit-gas-item.test.js
  ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-item/useGasItemFeeDetails.js
  ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-tooltip/edit-gas-tooltip.test.js
  ui/pages/confirmations/components/fee-details-component/fee-details-component.test.js
  ui/pages/confirmations/components/gas-details-item/gas-details-item.test.js
  ui/pages/confirmations/components/gas-timing/gas-timing.component.js
  ui/pages/confirmations/components/transaction-detail/transaction-detail.component.test.js
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirmations/confirm-send-ether/confirm-send-ether.test.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmations/confirm-transaction/confirm-transaction.component.js
  ui/pages/confirmations/confirm-transaction/confirm-transaction.test.js
  ui/pages/confirmations/confirm-transaction/confirm-transaction.transaction.test.js
  ui/pages/confirmations/hooks/test-utils.js
  ui/pages/confirmations/hooks/useGasEstimates.js
  ui/pages/confirmations/hooks/useGasFeeInputs.js
  ui/pages/confirmations/hooks/useIncrementedGasFees.js
  ui/pages/confirmations/hooks/useTransactionFunctions.js
  ui/pages/confirmations/send/send-content/__snapshots__/send-content.component.test.js.snap
  ui/pages/confirmations/send/send-content/send-content.component.test.js
  ui/pages/confirmations/token-allowance/token-allowance.test.js
  ui/pages/routes/routes.component.test.js
  ui/pages/swaps/index.test.js
  ui/pages/swaps/prepare-swap-page/review-quote.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#23396 fix: AvatarGroup usage in TokenList
  ui/components/multichain/account-list-item/account-list-item.js
Labels: needs-ux-ds-review, team-wallet-ux, needs-assets-ux-review

#23386 fix: filter and subscribe when using requestQueueing
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  types/eth-json-rpc-filters/index.d.ts
  types/eth-json-rpc-filters/subscriptionManager.d.ts
  yarn.lock
Labels: team-wallet-api-platform

#23400 build: add missing extensions to `devcontainer.json`
  .devcontainer/devcontainer.json
Labels: team-extension-platform

#23347 chore: [MMI] move mmi controller to ts
  .eslintrc.js
  .mocharc.js
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/controllers/mmi-controller.ts
  app/scripts/controllers/preferences.d.ts
  app/scripts/metamask-controller.js
  jest.config.js
  shared/constants/mmi-controller.ts
Labels: team-mmi

#23315 Adding info row component for typed sign data
  app/_locales/en/messages.json
  test/data/confirmations/typed_sign.ts
  ui/pages/confirmations/components/confirm/row/typed-sign-data/__snapshots__/typedSignData.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data/dataTree.tsx
  ui/pages/confirmations/components/confirm/row/typed-sign-data/typedSignData.stories.tsx
  ui/pages/confirmations/components/confirm/row/typed-sign-data/typedSignData.test.tsx
  ui/pages/confirmations/components/confirm/row/typed-sign-data/typedSignData.tsx
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#23032 feat: UX - Multichain - Disconnect All Modal
  app/_locales/en/messages.json
  ui/components/multichain/disconnect-all-modal/__snapshots__/disconnect-all-modal.test.tsx.snap
  ui/components/multichain/disconnect-all-modal/disconnect-all-modal.stories.tsx
  ui/components/multichain/disconnect-all-modal/disconnect-all-modal.test.tsx
  ui/components/multichain/disconnect-all-modal/disconnect-all-modal.tsx
  ui/components/multichain/disconnect-all-modal/index.ts
Labels: team-wallet-ux, needs-assets-ux-review

#23359 feat: Add MetaMask Portfolio What's New notification
  app/_locales/en/messages.json
  app/images/portfolio-v2-whatsnew-banner.png
  shared/notifications/index.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: needs-ux-ds-review, team-wallet-ux, needs-assets-ux-review

#23425 fix: smart swaps missing chain ID
  ui/ducks/swaps/swaps.js
Labels: team-confirmations-system, QA Passed

#22807 Porting existing MMI section to new page
  ui/pages/confirmations/components/confirm/mmi-signature-mismatch-banner/index.ts
  ui/pages/confirmations/components/confirm/mmi-signature-mismatch-banner/mmi-signature-mismatch-banner.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/confirm.tsx
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#23437 feat: add cross chain swaps link in extension
  app/_locales/en/messages.json
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.test.js
Labels: team-bridge

#23423 chore: bump snaps packages
  app/scripts/lib/setupSentry.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#23440 test: set `snap-account-abstraction-keyring` to a fixed version
  test/e2e/constants.ts
Labels: team-accounts, team-confirmations-system

#23111 docs: add approval flows and result pages to confirmations documentation
  docs/assets/approval_template.png
  docs/assets/confirmation.png
  docs/assets/success_approval.png
  docs/assets/success_approval_templates.png
  docs/confirmations.md
Labels: team-confirmations-system

#23450 test: fix flaky test in account-token-list.spec.js
  test/e2e/tests/settings/account-token-list.spec.js
Labels: team-extension-platform, needs-dev-review, e2e-test, flaky tests

#23455 ci: Update validate-conventional-commits.yml
  .github/workflows/validate-conventional-commits.yml
Labels: team-extension-platform

#22809 feat: add logic to cancel submit approvals buttons
  test/data/mock-state.json
  ui/pages/confirmations/components/confirm/footer/__snapshots__/footer.test.tsx.snap
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/mock-data.ts
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#23445 feat(23012): convert 2 level 19 files to ts
  app/scripts/lib/transaction/metrics.ts
  shared/modules/contract-utils.ts
  shared/modules/transaction.utils.ts
  shared/notifications/index.ts
Labels: team-extension-platform, needs-dev-review

#23447 fix: remove banner in account list menu component
  app/_locales/en/messages.json
  ui/components/multichain/account-list-menu/account-list-menu.js
Labels: team-accounts

#23268 v11.12.0 changelog
  CHANGELOG.md
Labels: team-extension-platform, release-11.12.0

#23452 feat: adding support for base network
  app/_locales/en/messages.json
  app/scripts/lib/ppom/ppom-middleware.ts
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#23444 test: improve "Snap Account Signatures" and "User Operations from send transaction"
  test/e2e/accounts/common.ts
  test/e2e/accounts/create-snap-account.spec.ts
  test/e2e/constants.ts
  test/e2e/flask/user-operations.spec.ts
  test/e2e/helpers.js
  test/e2e/webdriver/driver.js
  ui/helpers/constants/common.ts
  ui/pages/snap-account-redirect/create-snap-redirect.test.tsx
  ui/pages/snap-account-redirect/snap-account-redirect.stories.tsx
Labels: team-accounts, team-extension-platform

#23458 feat: update style of missing petnames
  ui/components/app/name/index.scss
Labels: team-confirmations-system

#23463 chore: bump `@metamask/test-dapp` to `^8.3.0`
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#23414 ci: fix prep-deps in PRs from external contributors
  .circleci/config.yml
Labels: area-CI, team-extension-platform

#23374 build: fix `loadBuildTypesConfig` memoization
  development/lib/build-type.js
Labels: team-extension-platform

#23402 build: use `yaml` instead of `js-yaml`
  development/lib/build-type.js
  lavamoat/build-system/policy.json
  package.json
  test/merge-coverage.js
  yarn.lock
Labels: team-mobile-platform

#23417 docs: update readme about `yarn lavamoat:webapp:auto`
  README.md
Labels: area-documentation, team-lavamoat, needs-dev-review

#23443 fix: improve hww import copy
  app/_locales/en/messages.json
Labels: team-unkown, INVALID-PR-TEMPLATE

#23485 fix: stop updating registry if user only has preinstalled Snaps
  app/scripts/background.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#23490 cherry-pick feat: update style of missing petnames
  ui/components/app/name/index.scss
Labels: team-confirmations-system, INVALID-PR-TEMPLATE

#23248 fix: minor insights v2 tweaks
  app/_locales/en/messages.json
  ui/components/app/snaps/insight-warnings/insight-warnings.js
  ui/components/app/snaps/snap-delineator/snap-delineator.js
  ui/helpers/constants/snaps/insights.ts
  ui/pages/confirmations/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
Labels: team-snaps-platform

#22192 Fix placeholder text for Flask send screen
  app/_locales/en/messages.json
  ui/helpers/utils/util.js
  ui/pages/confirmations/send/send-content/add-recipient/domain-input.component.js
  ui/pages/confirmations/send/send.test.js
Labels: flask, team-snaps-platform

#23193 feat: Connect More Accounts Flow
  app/_locales/en/messages.json
  app/scripts/controllers/permissions/background-api.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.stories.js
  ui/components/multichain/connect-accounts-modal/connect-account-modal.types.ts
  ui/components/multichain/connect-accounts-modal/connect-accounts-modal-list.tsx
  ui/components/multichain/connect-accounts-modal/connect-accounts-modal.stories.tsx
  ui/components/multichain/connect-accounts-modal/connect-accounts-modal.test.tsx
  ui/components/multichain/connect-accounts-modal/connect-accounts-modal.tsx
  ui/components/multichain/connect-accounts-modal/index.ts
  ui/components/multichain/pages/connections/connections.tsx
  ui/selectors/selectors.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: needs-dev-review, INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23314 test: add scenario for personal sign using hardware wallet
  test/scenarios/13. sign/personal sign with hardware wallet.csv
Labels: area-testSuite, team-confirmations-secure-ux-PR, needs-dev-review

#22928 refactor: Replace `DetectTokensController` with core monorepo's `TokenDetectionController`
  .eslintrc.js
  .mocharc.js
  .yarn/patches/@metamask-accounts-controller-npm-10.0.0-247993ca9a.patch
  .yarn/patches/@metamask-assets-controllers-npm-24.0.0-dfef136464.patch
  .yarn/patches/@metamask-keyring-controller-npm-12.2.0-2b196324d1.patch
  app/scripts/controllers/detect-tokens.js
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/controllers/preferences.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  development/ts-migration-dashboard/files-to-convert.json
  jest.config.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/metrics/swaps.spec.js
  ui/components/multichain/account-details/account-details.test.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/address-copy-button/address-copy-button.js
  ui/components/multichain/address-copy-button/address-copy-button.test.js
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/import-token-link/import-token-link.test.js
  ui/components/multichain/import-token-link/import-token-link.tsx
  ui/components/multichain/menu-items/view-explorer-menu-item.js
  ui/components/multichain/notification-detail-address/notification-detail-address.tsx
  ui/components/multichain/notification-detail-copy-button/notification-detail-copy-button.stories.tsx
  ui/components/multichain/receive-modal/receive-modal.test.js
  ui/store/actions.ts
  yarn.lock
Labels: type-refactor, area-tokens, area-balances, team-shared-libraries, needs-dev-review

#23349 fix: UX: Multichain: Send flow: Remove NetworkPicker
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/send.js
  ui/components/multichain/pages/send/send.test.js
Labels: team-wallet-ux, needs-assets-ux-review

#23387 fix: Fix #23290 - Remove gas display from Multichain send screen
  test/e2e/tests/transaction/send-eth.spec.js
  ui/components/multichain/pages/send/components/content.tsx
Labels: team-wallet-ux, needs-assets-ux-review

#23477 ci: fix "Open in GitHub Codespaces" on forked repos
  .github/workflows/codespaces-update-badge.yml
  .github/workflows/fitness-functions.yml
Labels: team-extension-platform

#23502 fix: lint errors
  shared/notifications/index.ts
  ui/components/multichain/connect-accounts-modal/connect-account-modal.types.ts
Labels: team-extension-platform

#23489 v11.12.1
  CHANGELOG.md
  package.json
  ui/components/app/name/index.scss
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#22508 feat: new asset page
  app/_locales/en/messages.json
  app/images/chart.webp
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  shared/lib/fetch-with-cache.ts
  test/e2e/tests/tokens/add-hide-token.spec.js
  test/e2e/tests/tokens/custom-token-send-transfer.spec.js
  test/e2e/tests/tokens/send-erc20-to-contract.spec.js
  test/e2e/tests/tokens/token-details.spec.js
  test/e2e/tests/transaction/send-hex-address.spec.js
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/app/token-cell/token-cell.js
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/index.scss
  ui/components/multichain/token-list-item/token-list-item.js
  ui/helpers/utils/confirm-tx.util.test.js
  ui/helpers/utils/confirm-tx.util.ts
  ui/pages/asset/asset.js
  ui/pages/asset/asset.scss
  ui/pages/asset/components/asset-chart.tsx
  ui/pages/asset/components/asset-header.tsx
  ui/pages/asset/components/asset-options.js
  ui/pages/asset/components/asset-price.tsx
  ui/pages/asset/components/asset-v2.tsx
  ui/pages/asset/components/buttons/asset-bridge-button.tsx
  ui/pages/asset/components/buttons/asset-buy-button.tsx
  ui/pages/asset/components/buttons/asset-send-button.tsx
  ui/pages/asset/components/buttons/asset-swap-button.tsx
  ui/pages/asset/components/chart-tooltip.tsx
  ui/pages/asset/components/native-asset-v2.tsx
  ui/pages/asset/components/native-asset.js
  ui/pages/asset/components/token-asset-v2.tsx
  ui/pages/asset/components/token-asset.js
  ui/pages/asset/useHistoricalPrices.ts
  ui/pages/asset/util.ts
  ui/pages/home/home.component.js
  ui/pages/routes/routes.component.js
  ui/pages/token-details/token-details-page.js
  yarn.lock
Labels: needs-ux-ds-review, team-assets, needs-assets-ux-review

#23511 fix: Fix confirmation tx totals on layer 2 networks and for erc20 transfers
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
Labels: team-confirmations-secure-ux-PR, INVALID-PR-TEMPLATE

#23449 chore: Master sync following v11.11.X
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#23494 chore: MMI adds fallback property when environment key doesnt exist
  ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.js
Labels: team-mmi

#23438 feat: show default petnames for watched NFTs
  ui/components/ui/identicon/__snapshots__/identicon.component.test.js.snap
  ui/components/ui/identicon/identicon.component.js
  ui/components/ui/identicon/identicon.component.test.js
  ui/components/ui/identicon/identicon.container.js
  ui/components/ui/identicon/identicon.stories.js
  ui/hooks/useDisplayName.test.ts
  ui/hooks/useDisplayName.ts
  ui/pages/confirmations/send/send-content/add-recipient/add-recipient.container.test.js
  ui/selectors/nft.test.ts
  ui/selectors/nft.ts
Labels: team-confirmations-system

#23517 fix: fix overflow in Snaps list
  ui/components/app/snaps/snap-list-item/snap-list-item.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#23518 fix: saving file to storage for blockaid
  package.json
  yarn.lock
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#23462 chore: adds message check for contract calls
  test/e2e/mmi/helpers/dapps-helpers.ts
  test/e2e/mmi/pageObjects/mmi-dummyApp-page.ts
  test/e2e/mmi/pageObjects/mmi-main-page.ts
  test/e2e/mmi/specs/dapp.signature.spec.ts
  test/e2e/mmi/specs/dapp.spec.ts
Labels: team-mmi

#21909 Add support for localised Snap manifests
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/lib/snap-keyring/utils/getSnapName.test.ts
  app/scripts/lib/snap-keyring/utils/getSnapName.ts
  app/scripts/metamask-controller.js
  shared/constants/snaps.ts
  test/data/mock-state.json
  ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
  ui/components/app/snaps/snap-authorship-expanded/snap-authorship-expanded.js
  ui/components/app/snaps/snap-authorship-header/snap-authorship-header.js
  ui/components/app/snaps/snap-avatar/snap-avatar.js
  ui/components/app/snaps/snap-connect-cell/snap-connect-cell.js
  ui/components/app/snaps/snap-connect-cell/snap-connect-cell.stories.js
  ui/components/app/snaps/snap-home-page/snap-home-renderer.js
  ui/components/app/snaps/snap-insight/snap-insight.js
  ui/components/app/snaps/snap-legacy-authorship-header/snap-legacy-authorship-header.js
  ui/components/app/snaps/snap-metadata-modal/snap-metadata-modal.js
  ui/components/app/snaps/snap-permissions-list/snap-permissions-list.js
  ui/components/app/snaps/snap-permissions-list/snap-permissions-list.test.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/components/app/snaps/update-snap-permission-list/update-snap-permission-list.js
  ui/components/multichain/pages/permissions-page/__snapshots__/permissions-page.test.js.snap
  ui/ducks/domains.js
  ui/helpers/utils/permission.js
  ui/helpers/utils/util.js
  ui/hooks/useTransactionInsights.js
  ui/pages/confirmations/confirmation/confirmation.js
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.test.js
  ui/pages/confirmations/confirmation/templates/error.test.js
  ui/pages/confirmations/confirmation/templates/snap-account-redirect.test.js
  ui/pages/confirmations/confirmation/templates/success.test.js
  ui/pages/confirmations/confirmation/templates/switch-ethereum-chain.test.js
  ui/pages/notifications/notification.test.js
  ui/pages/notifications/notifications.js
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
  ui/pages/permissions-connect/snaps/snap-result/snap-result.js
  ui/pages/permissions-connect/snaps/snap-update/snap-update.js
  ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js
  ui/pages/permissions-connect/snaps/util.js
  ui/pages/snaps/snap-view/snap-settings.js
  ui/pages/snaps/snap-view/snap-view.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-snaps-platform

#23524 fix: Gas display fixes on confirmation screen
  ui/pages/confirmations/components/fee-details-component/fee-details-component.js
  ui/pages/confirmations/components/fee-details-component/fee-details-component.test.js
  ui/pages/confirmations/confirm-approve/confirm-approve-content/__snapshots__/confirm-approve-content.component.test.js.snap
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirmations/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
Labels: team-confirmations-secure-ux-PR

#23523 fix: Revert "Set FONTCONFIG_PATH on CircleCI containers (#22657)"
  .circleci/config.yml
Labels: team-shared-libraries

#23492 feat: added search functionality to custody view
  ui/pages/institutional/custody/custody.js
  ui/pages/institutional/custody/custody.test.js
Labels: team-mmi

#23510 Version v11.12.2
  CHANGELOG.md
  package.json
  ui/pages/confirmations/components/confirm-gas-display/__snapshots__/confirm-gas-display.test.js.snap
  ui/pages/confirmations/components/fee-details-component/fee-details-component.js
  ui/pages/confirmations/components/fee-details-component/fee-details-component.test.js
  ui/pages/confirmations/components/gas-details-item/gas-details-item.js
  ui/pages/confirmations/confirm-approve/confirm-approve-content/__snapshots__/confirm-approve-content.component.test.js.snap
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirmations/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
Labels: INVALID-PR-TEMPLATE, release-11.12.2

#23516 chore: adds a needed code fence and blockaid to MMI build
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  builds.yml
  lavamoat/browserify/mmi/policy.json
Labels: team-mmi

#23454 feat(upgrade-permission-cell): Add updates to permission cell to handle displaying accounts
  app/_locales/en/messages.json
  ui/components/app/permission-cell/index.scss
  ui/components/app/permission-cell/permission-cell-status.js
  ui/components/app/permission-cell/permission-cell.js
  ui/components/app/permission-cell/permission-cell.stories.js
Labels: team-snaps-platform

#23520 test: [E2E] Fix sentry e2e flaky tests
  test/e2e/fixture-builder.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
Labels: team-extension-platform, needs-dev-review, e2e-test, flaky tests

#23313 test: add scenario for eth sign using hardware wallet
  test/scenarios/13. sign/eth sign with hardware wallet.csv
Labels: area-testSuite, team-confirmations-secure-ux-PR, needs-dev-review

#23548 fix: desktop build lint error
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
Labels: team-mmi

#23461 refactor: Typescript conversion of onboarding controller
  app/scripts/controllers/onboarding.js
  app/scripts/controllers/onboarding.ts
  shared/constants/onboarding.ts
Labels: team-extension-platform, needs-dev-review

#23542 fix: update fuse mainnet logo
  app/images/fuse-mainnet.jpeg
  app/images/fuse-mainnet.jpg
  shared/constants/network.ts
Labels: needs-dev-review, team-assets, needs-assets-ux-review

#23252 chore: Bump `@metamask/transaction-controller` to 25.1.0 (along with related packages)
  .yarn/patches/@babel-runtime-npm-7.24.0-7eb1dd11a2.patch
  .yarn/patches/@metamask-controller-utils-npm-8.0.4-077edd6162.patch
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/modules/transaction.utils.ts
  test/e2e/helpers.js
  test/e2e/tests/settings/show-hex-data.spec.js
  yarn.lock
Labels: team-shared-libraries

#23567 chore: fix lock file
  yarn.lock
Labels: team-extension-platform

#22863 chore: Bump `@metamask/address-book-controller`
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-security, needs-dev-review

#23547 Version v11.12.3
  CHANGELOG.md
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  builds.yml
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.js
Labels: team-mmi, release-11.12.3

#23220 Normalize transaction parameters before PPOM validation
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/ppom/ppom-util.test.ts
  app/scripts/lib/ppom/ppom-util.ts
  app/scripts/lib/transaction/util.test.ts
  app/scripts/lib/transaction/util.ts
Labels: team-confirmations-system

#23292 chore: update Keystone and NGRAVE dependencies
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: dependencies, external-contributor, team-hardware-wallets

#22942 Add reject all option to personal sign header
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-navigation/confirm-page-container-navigation.component.js
  ui/pages/confirmations/components/confirm/footer/footer.stories.tsx
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/nav/__snapshots__/nav.test.tsx.snap
  ui/pages/confirmations/components/confirm/nav/index.tsx
  ui/pages/confirmations/components/confirm/nav/nav.scss
  ui/pages/confirmations/components/confirm/nav/nav.stories.tsx
  ui/pages/confirmations/components/confirm/nav/nav.test.tsx
  ui/pages/confirmations/components/confirm/nav/nav.tsx
  ui/pages/confirmations/components/index.scss
  ui/pages/confirmations/confirm/confirm.tsx
  ui/pages/confirmations/hooks/syncConfirmPath.ts
  ui/pages/confirmations/hooks/useCurrentConfirmation.ts
  ui/selectors/confirm.ts
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#23418 test: add scenario check custom nonce toggle works correctly.
  test/scenarios/17. settings/advanced/check custom nonce toggle.csv
Labels: team-confirmations-system, release-11.13.0

#23569 test: add scenario navigate through multiple unapproved transactions.
  test/scenarios/3. transactions/navigate multiple transactions.csv
Labels: team-confirmations-system, release-11.14.0

#23536 test: add scenario deploy contract, deposit and withdraw
  test/scenarios/3. transactions/deposit and withdraw.csv
Labels: team-confirmations-system, release-11.4.0

#23501 chore(ts): Use FirstTimeFlowType enum
  .storybook/test-data.js
  test/e2e/fixture-builder.js
  ui/helpers/constants/onboarding.js
  ui/pages/home/home.component.js
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/create-password/create-password.test.js
  ui/pages/onboarding-flow/metametrics/metametrics.js
  ui/pages/onboarding-flow/metametrics/metametrics.test.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.js
  ui/pages/onboarding-flow/welcome/welcome.js
  ui/pages/onboarding-flow/welcome/welcome.test.js
  ui/selectors/first-time-flow.js
  ui/store/actions.ts
Labels: team-extension-platform

#23047 feat: port MMI related logic to personal sign page
  ui/hooks/useMMIConfirmations.ts
  ui/pages/confirmations/components/confirm/footer/footer.stories.tsx
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/nav/nav.tsx
  ui/pages/confirmations/hooks/syncConfirmPath.ts
  ui/pages/confirmations/selectors/confirm.test.ts
  ui/pages/confirmations/selectors/confirm.ts
  ui/pages/confirmations/selectors/index.ts
  ui/pages/confirmations/types/confirm.ts
  ui/pages/confirmations/utils/confirm.test.ts
  ui/pages/confirmations/utils/confirm.ts
  ui/pages/confirmations/utils/index.ts
  ui/selectors/index.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#23546 feat: change in security settings - removing opensea provider and design changes
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/lib/ui-utils.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/security-tab/security-tab.test.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#23488 feat: disconnect all modal flow
  ui/components/multichain/disconnect-all-modal/disconnect-all-modal.tsx
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/connections/components/connections.types.tsx
  ui/components/multichain/pages/connections/connections.test.tsx
  ui/components/multichain/pages/connections/connections.tsx
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23587 chore: updates mmi extension package
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-mmi

#23487 feat(conf-redesign): Implements PetNames on `ConfirmInfoRowAddress` component
  ui/components/app/confirm/info/__snapshots__/info.test.tsx.snap
  ui/components/app/confirm/info/info.test.tsx
  ui/components/app/confirm/info/row/__snapshots__/address.test.tsx.snap
  ui/components/app/confirm/info/row/address.stories.tsx
  ui/components/app/confirm/info/row/address.test.tsx
  ui/components/app/confirm/info/row/address.tsx
  ui/components/app/confirm/info/row/constants.ts
  ui/components/app/confirm/info/row/hook.ts
  ui/components/app/snaps/snap-ui-renderer/components/address.ts
  ui/pages/confirmations/components/confirm/row/typed-sign-data/__snapshots__/typedSignData.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data/typedSignData.test.tsx
  ui/selectors/nft.ts
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR, confirmation-redesign, confirmation-re-design

#23584 feat: allow redirection to Snap confirmations from home page
  ui/components/app/snaps/snap-home-page/snap-home-renderer.js
  ui/helpers/constants/routes.ts
  ui/pages/confirmations/confirmation/confirmation.js
  ui/pages/routes/routes.component.js
  ui/selectors/selectors.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#23491 fix(swaps): fix review quote on multi layer fees
  ui/pages/swaps/prepare-swap-page/review-quote.js
Labels: team-swaps, INVALID-PR-TEMPLATE

#23606 test: Test scenario, deploy contract, mint and import NFT
  test/scenarios/18. contract/deploy contract, mint and import NFT with hardware wallet.csv
Labels: area-testSuite, team-confirmations-secure-ux-PR, needs-dev-review

#23609 test: Test scenario hardware wallet send token
  test/scenarios/18. contract/send token with hardware wallet.csv
Labels: area-testSuite, team-confirmations-secure-ux-PR, needs-dev-review

#23603 fix: update @blockaid/ppom_release package to 1.4.5
  package.json
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  yarn.lock
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#23545 fix(swaps): fix max gas estimation and gas limit used for swaps tx
  test/e2e/tests/metrics/swaps.spec.js
  ui/ducks/swaps/swaps.js
  ui/pages/swaps/prepare-swap-page/review-quote.js
Labels: team-swaps, INVALID-PR-TEMPLATE

#23614 fix: revert aggregated fiat balance on home page
  test/e2e/helpers.js
  test/e2e/tests/contract-interactions.spec.js
  test/e2e/tests/incremental-security.spec.js
  test/e2e/tests/localization.spec.js
  test/e2e/tests/lock-account.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/tests/migrate-old-vault.spec.js
  test/e2e/tests/settings/account-token-list.spec.js
  test/e2e/tests/transaction/send-eth.spec.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/eth-overview.test.js
Labels: team-assets, needs-assets-ux-review

#23617 fix: revert aggregated fiat balance on home page (#23614)
  test/e2e/helpers.js
  test/e2e/tests/account-token-list.spec.js
  test/e2e/tests/contract-interactions.spec.js
  test/e2e/tests/incremental-security.spec.js
  test/e2e/tests/localization.spec.js
  test/e2e/tests/lock-account.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/tests/migrate-old-vault.spec.js
  test/e2e/tests/send-eth.spec.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/eth-overview.test.js
Labels: INVALID-PR-TEMPLATE

#23618 fix: fix typo in snap install rejected metric
  shared/constants/metametrics.ts
Labels: area-snaps, INVALID-PR-TEMPLATE, team-snaps-platform

#23616 Version v11.12.4
  CHANGELOG.md
  package.json
  shared/constants/metametrics.ts
  test/e2e/helpers.js
  test/e2e/tests/account-token-list.spec.js
  test/e2e/tests/contract-interactions.spec.js
  test/e2e/tests/incremental-security.spec.js
  test/e2e/tests/localization.spec.js
  test/e2e/tests/lock-account.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/tests/migrate-old-vault.spec.js
  test/e2e/tests/send-eth.spec.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/eth-overview.test.js
Labels: INVALID-PR-TEMPLATE, release-11.12.4

#20702 chore(devDeps): madge@^6.1.0 -> @lgbot/madge@^6.2.0
  development/ts-migration-dashboard/common/build-module-partitions.ts
  development/ts-migration-dashboard/scripts/write-list-of-files-to-convert.ts
  lavamoat/build-system/policy-override.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-security, INVALID-PR-TEMPLATE

#23602 chore: skips temporarily a test and fixes an other
  test/e2e/mmi/specs/dapp.spec.ts
  test/e2e/mmi/specs/navigation.spec.ts
Labels: team-mmi

#22349 feat: Add Confirm ScrollToBottom component and update ConfirmPage
  ui/ducks/confirm/confirm.ts
  ui/hooks/useScrollRequired.js
  ui/pages/confirmations/components/confirm/footer/__snapshots__/footer.test.tsx.snap
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/index.scss
  ui/pages/confirmations/components/confirm/scroll-to-bottom/index.ts
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.stories.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.test.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.tsx
  ui/pages/confirmations/components/index.scss
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/confirm.stories.tsx
  ui/pages/confirmations/confirm/confirm.test.tsx
  ui/pages/confirmations/confirm/confirm.tsx
  ui/pages/confirmations/selectors/confirm.ts
  ui/pages/confirmations/types/confirm.ts
Labels: team-confirmations-secure-ux-PR, INVALID-PR-TEMPLATE

#23608 chore: Master sync following v11.12.X
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#22865 feat: Add `QueuedRequestController` batching
  app/scripts/background.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/request-queuing/multiple-networks-dapps-txs.spec.js
  test/e2e/tests/request-queuing/switch-network.spec.js
  yarn.lock
Labels: team-shared-libraries, team-wallet-api-platform

#20716 fix: remove linea mainnet feature toggle
  app/scripts/controllers/preferences.js
  app/scripts/lib/setupSentry.js
  app/scripts/migrations/113.test.ts
  app/scripts/migrations/113.ts
  app/scripts/migrations/index.js
  shared/modules/network.utils.ts
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
  ui/ducks/metamask/metamask.js
  ui/pages/settings/networks-tab/networks-tab.js
Labels: team-extension-ux, team-linea, needs-dev-review, team-assets
