Repository MetaMask/metamask-extension, pull requests merged in 2024-11, with the labels that each got.

#27644 refactor: move `getSelectedInternalAccount` from `selectors.js` to `accounts.ts`
  test/data/mock-state.json
  ui/components/app/selected-account/selected-account-component.test.js
  ui/components/institutional/interactive-replacement-token-modal/interactive-replacement-token-modal.tsx
  ui/components/institutional/interactive-replacement-token-notification/interactive-replacement-token-notification.tsx
  ui/ducks/bridge/selectors.ts
  ui/ducks/metamask/metamask.js
  ui/hooks/bridge/useBridging.ts
  ui/hooks/useMultichainSelector.ts
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/institutional/interactive-replacement-token-page/interactive-replacement-token-page.tsx
  ui/pages/settings/security-tab/security-tab.container.js
  ui/selectors/accounts.test.ts
  ui/selectors/accounts.ts
  ui/selectors/index.js
  ui/selectors/institutional/selectors.ts
  ui/selectors/multichain.ts
  ui/selectors/permissions.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/selectors/transactions.js
Labels: team-extension-platform, team-tiger

#28222 chore: Master sync
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#28237 chore: Modify changelog title to fix ci job
  CHANGELOG.md
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#28233 chore: improve token lookup performance in `useAccountTotalFiatBalance`
  ui/hooks/useAccountTotalFiatBalance.js
Labels: team-assets

#26999 fix: Error handling for the state log download failure
  ui/ducks/app/app.test.js
  ui/ducks/app/app.ts
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
  ui/pages/settings/advanced-tab/advanced-tab.stories.js
  ui/store/actionConstants.ts
Labels: team-extension-platform, external-contributor

#28232 chore: remove broken link in docs
  ui/components/component-library/README.md
  ui/components/component-library/text/README.mdx
Labels: team-design-system

#28084 chore: Adding installType to Sentry Tags for easy filtering
  app/scripts/lib/setupSentry.js
Labels: team-extension-platform

#27968 chore: Remove obsolete preview build support
  .circleci/config.yml
  .circleci/scripts/install-dependencies.sh
  .yarnrc.yml
Labels: team-wallet-framework, team-extension-platform, needs-dev-review

#27759 feat: add token verification source count and link to block explorer
  app/_locales/en/messages.json
  shared/constants/common.ts
  shared/constants/swaps.ts
  ui/components/app/assets/nfts/nft-details/nft-details.tsx
  ui/pages/institutional/account-list/account-list.tsx
  ui/pages/institutional/interactive-replacement-token-page/interactive-replacement-token-page.test.tsx
  ui/pages/institutional/interactive-replacement-token-page/interactive-replacement-token-page.tsx
  ui/pages/swaps/awaiting-swap/awaiting-swap.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.test.js
  ui/pages/swaps/searchable-item-list/item-list/item-list.component.js
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.js
Labels: team-swaps

#27916 fix: margin on asset chart min/max indicators
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/asset/components/chart/chart-tooltip.tsx
Labels: team-assets

#28167 refactor: remove global network usage from signatures
  test/data/confirmations/personal_sign.ts
  test/data/confirmations/typed_sign.ts
  test/integration/confirmations/signatures/permit.test.tsx
  test/integration/confirmations/signatures/personalSign.test.tsx
  ui/hooks/useName.test.ts
  ui/hooks/useNftCollectionsMetadata.test.ts
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/value-display/value-display.tsx
  ui/pages/confirmations/components/confirm/network-change-toast/network-change-toast-legacy.tsx
  ui/pages/confirmations/components/contract-details-modal/contract-details-modal.js
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/pages/confirmations/components/signature-request-header/signature-request-header.js
  ui/pages/confirmations/components/signature-request-header/signature-request-header.stories.js
  ui/pages/confirmations/components/signature-request-header/signature-request-header.test.js
  ui/pages/confirmations/components/signature-request-original/signature-request-original.stories.js
  ui/pages/confirmations/components/signature-request-original/signature-request-original.test.js
  ui/pages/confirmations/components/signature-request-siwe/__snapshots__/signature-request-siwe.test.js.snap
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe.stories.js
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe.test.js
  ui/pages/confirmations/components/signature-request/__snapshots__/signature-request.test.js.snap
  ui/pages/confirmations/components/signature-request/signature-request.js
  ui/pages/confirmations/components/signature-request/signature-request.stories.js
  ui/pages/confirmations/components/signature-request/signature-request.test.js
  ui/pages/confirmations/confirm-signature-request/index.test.js
  ui/pages/confirmations/hooks/alerts/useBlockaidAlerts.ts
  ui/pages/confirmations/hooks/useConfirmationNetworkInfo.ts
  ui/pages/confirmations/hooks/useTrackERC20WithoutDecimalInformation.test.ts
  ui/pages/confirmations/hooks/useTrackERC20WithoutDecimalInformation.ts
  ui/selectors/selectors.js
Labels: QA Passed, team-confirmations

#28161 test: [POM] Migrate edit network rpc e2e tests and create related page class functions
  test/e2e/page-objects/pages/dialog/edit-network.ts
  test/e2e/page-objects/pages/dialog/select-network.ts
  test/e2e/page-objects/pages/homepage.ts
  test/e2e/page-objects/pages/onboarding/onboarding-privacy-settings-page.ts
  test/e2e/tests/network/multi-rpc.spec.ts
Labels: team-extension-platform, e2e-test, area-qa

#28192 fix: Prevent coercing symbols to zero in the edit spending cap modal
  app/_locales/en/messages.json
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
Labels: team-confirmations

#27492 fix: Add different copy for tooltip when a snap is requesting a signature
  app/_locales/en/messages.json
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#27645 refactor: move `getInternalAccounts` from `selectors.js` to `accounts.ts`
  ui/pages/institutional/interactive-replacement-token-page/interactive-replacement-token-page.tsx
  ui/pages/notifications-settings/notifications-settings.tsx
  ui/selectors/accounts.test.ts
  ui/selectors/accounts.ts
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/selectors/snaps/accounts.ts
Labels: team-extension-platform, team-tiger

#28158 feat: multi chain polling for token prices
  .yarn/patches/@metamask-assets-controllers-npm-42.0.0-57b3d695bb.patch
  app/scripts/metamask-controller.js
  package.json
  ui/contexts/assetPolling.tsx
  ui/contexts/currencyRate.js
  ui/hooks/useMultiPolling.ts
  ui/hooks/useTokenRatesPolling.ts
  ui/pages/index.js
  ui/selectors/selectors.js
  ui/store/actions.ts
  yarn.lock
Labels: team-assets, needs-assets-ux-review

#28190 feat: adds the experimental toggle for Solana
  app/_locales/en/messages.json
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  ui/pages/settings/experimental-tab/experimental-tab.component.tsx
  ui/pages/settings/experimental-tab/experimental-tab.container.ts
  ui/pages/settings/experimental-tab/experimental-tab.test.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-sol

#28244 fix: Fix alignment of long RPC labels in Networks menu
  ui/components/multichain/network-list-item/index.scss
  ui/components/multichain/network-list-item/network-list-item.tsx
Labels: team-wallet-ux

#28254 chore: use accounts api for token detection
  app/scripts/metamask-controller.js
Labels: team-assets, needs-assets-ux-review

#28271 fix: notification settings type
  ui/pages/notifications-settings/notifications-settings.tsx
Labels: team-notifications

#28030 fix: ignore error when getTokenStandardAndDetails fails
  ui/ducks/send/send.js
Labels: team-assets, needs-assets-ux-review

#28193 feat: add native tokens to multichain token list
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/asset-list/native-token/native-token.tsx
  ui/components/app/assets/token-cell/token-cell.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/multichain/token-list-item/token-list-item.tsx
  ui/pages/asset/asset.tsx
  ui/pages/asset/components/asset-page.tsx
  ui/pages/asset/components/token-asset.tsx
  ui/pages/asset/util.ts
  ui/selectors/multichain.ts
  ui/selectors/selectors.js
Labels: team-wallet-ux

#28142 fix: Permit message, dataTree value incorrectly using default ERC20 decimals for non-ERC20 token values
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/hooks/useGetTokenStandardAndDetails.ts
Labels: team-confirmations

#28031 chore: display bridge quotes
  app/_locales/en/messages.json
  test/jest/mock-store.js
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
  ui/hooks/bridge/useCountdownTimer.test.ts
  ui/hooks/bridge/useCountdownTimer.ts
  ui/pages/bridge/__snapshots__/index.test.tsx.snap
  ui/pages/bridge/index.scss
  ui/pages/bridge/prepare/__snapshots__/prepare-bridge-page.test.tsx.snap
  ui/pages/bridge/prepare/bridge-cta-button.test.tsx
  ui/pages/bridge/prepare/bridge-cta-button.tsx
  ui/pages/bridge/prepare/bridge-input-group.tsx
  ui/pages/bridge/prepare/index.scss
  ui/pages/bridge/prepare/prepare-bridge-page.test.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/quotes/__snapshots__/bridge-quote-card.test.tsx.snap
  ui/pages/bridge/quotes/__snapshots__/bridge-quotes-modal.test.tsx.snap
  ui/pages/bridge/quotes/bridge-quote-card.test.tsx
  ui/pages/bridge/quotes/bridge-quote-card.tsx
  ui/pages/bridge/quotes/bridge-quotes-modal.test.tsx
  ui/pages/bridge/quotes/bridge-quotes-modal.tsx
  ui/pages/bridge/quotes/index.scss
  ui/pages/bridge/quotes/quote-info-row.tsx
  ui/pages/bridge/utils/quote.ts
  ui/pages/routes/utils.js
Labels: team-bridge

#28219 fix: Hide fiat values on test networks
  test/integration/confirmations/transactions/contract-deployment.test.tsx
  test/integration/confirmations/transactions/contract-interaction.test.tsx
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-row/gas-fees-row.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-row/gas-fees-row.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-row/gas-fees-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/native-send-heading/native-send-heading.tsx
  ui/pages/confirmations/components/confirm/info/shared/send-heading/send-heading.tsx
Labels: team-confirmations

#27941 fix: unit flaky test `AddContact component › should disable submit button when input is not a valid address`
  ui/pages/settings/contact-list-tab/add-contact/add-contact.test.js
Labels: team-extension-platform, flaky tests, area-qa

#28273 fix: smart transactions in redesigned confirmations
  test/data/confirmations/helper.ts
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/hooks/useSmartTransactionFeatureFlags.test.ts
  ui/pages/confirmations/hooks/useSmartTransactionFeatureFlags.ts
Labels: team-confirmations

#28240 feat: Add simulation metrics to "Transaction Submitted" and "Transaction Finalized" events
  app/scripts/controllers/metametrics.test.ts
  app/scripts/controllers/metametrics.ts
  app/scripts/lib/transaction/metrics.ts
  shared/constants/metametrics.ts
  ui/pages/confirmations/hooks/useTransactionEventFragment.js
Labels: team-confirmations

#28215 chore: Bump Snaps packages
  app/scripts/metamask-controller.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/snaps/enums.js
  ui/components/app/snaps/snap-ui-address/__snapshots__/snap-ui-address.test.tsx.snap
  ui/components/app/snaps/snap-ui-address/snap-ui-address.tsx
  ui/components/app/snaps/snap-ui-renderer/components/address.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#28306 chore: Add gravity logo and image mappings
  app/images/gravity.svg
  shared/constants/network.ts
Labels: team-assets

#27910 fix: remove scroll-to-bottom requirement in redesigned transaction confirmations
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.test.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.tsx
Labels: team-confirmations

#27986 feat: btc e2e tests
  test/e2e/constants.ts
  test/e2e/flask/btc/btc-send.spec.ts
  test/e2e/flask/btc/common-btc.ts
  ui/components/app/wallet-overview/coin-buttons.tsx
Labels: team-accounts

#28295 chore: add the gas_included prop into Quotes Received event
  ui/ducks/swaps/swaps.js
Labels: team-transactions

#28272 fix: use transaction address to get lock for custom nonce
  ui/hooks/useMMICustodySendTransaction.ts
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/approve-static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.tsx
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
  ui/pages/confirmations/components/confirm/info/approve/revoke-static-simulation/revoke-static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/approve/spending-cap/spending-cap.tsx
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/advanced-details.tsx
  ui/pages/confirmations/confirm-approve/confirm-approve.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirmations/token-allowance/token-allowance.js
  ui/store/actions.ts
Labels: QA Passed, team-confirmations

#28281 fix: GasDetailItem invalid paddingStart prop
  ui/pages/confirmations/components/confirm-gas-display/__snapshots__/confirm-gas-display.test.js.snap
  ui/pages/confirmations/components/gas-details-item/gas-details-item.js
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
Labels: team-confirmations

#28280 feat: Enable simulation metrics for redesign transactions
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.tsx
  ui/pages/confirmations/components/confirm/info/native-transfer/native-transfer.tsx
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/nft-token-transfer.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/token-transfer.tsx
Labels: team-confirmations

#28004 chore: adding e2e tests for NFT permit
  package.json
  privacy-snapshot.json
  test/e2e/tests/confirmations/signatures/nft-permit.spec.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  test/e2e/tests/tokens/add-multiple-tokens.spec.js
  yarn.lock
Labels: team-confirmations

#28206 chore: e2e quality gate enhancement
  .circleci/scripts/git-diff-develop.ts
Labels: team-extension-platform, area-qa

#28323 chore: revert commit `3da34f4` (feat: btc e2e tests (#27986))
  test/e2e/constants.ts
  test/e2e/flask/btc/btc-send.spec.ts
  test/e2e/flask/btc/common-btc.ts
  ui/components/app/wallet-overview/coin-buttons.tsx
Labels: team-accounts

#28291 chore: Remove STX opt in modal
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/lib/backup.test.js
  shared/modules/selectors/index.test.ts
  shared/modules/selectors/smart-transactions.ts
  test/data/mock-state.json
  test/e2e/default-fixture.js
  test/e2e/fixture-builder.js
  test/e2e/restore/MetaMaskUserData.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/integration/data/integration-init-state.json
  test/integration/data/onboarding-completion-route.json
  ui/ducks/metamask/metamask.js
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/smart-transactions/components/__snapshots__/smart-transactions-opt-in-modal.test.tsx.snap
  ui/pages/smart-transactions/components/index.scss
  ui/pages/smart-transactions/components/smart-transactions-opt-in-modal.test.tsx
  ui/pages/smart-transactions/components/smart-transactions-opt-in-modal.tsx
  ui/pages/smart-transactions/index.scss
Labels: team-transactions

#28269 chore: add Solana shared utilities and constants
  app/images/solana-logo.svg
  development/build/scripts.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/multichain/assets.ts
  shared/constants/multichain/networks.ts
  shared/lib/multichain.test.ts
  shared/lib/multichain.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-sol

#28225 build(webpack): fix cache issues in webpack build by updating `html-bundler-webpack-plugin` to v4.4.1
  package.json
  yarn.lock
Labels: contributor experience, team-extension-platform, webpack

#28320 feat: adds solana feature, code fence
  app/scripts/controllers/preferences-controller.ts
  app/scripts/metamask-controller.js
  builds.yml
  ui/pages/settings/experimental-tab/experimental-tab.component.tsx
  ui/pages/settings/experimental-tab/experimental-tab.container.ts
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-sol

#28248 fix: Negate privacy mode in Send screen
  ui/components/app/currency-input/currency-input.js
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.d.ts
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/components/multichain/asset-picker-amount/asset-balance/asset-balance-text.tsx
  ui/components/ui/currency-display/currency-display.component.d.ts
  ui/components/ui/currency-display/currency-display.component.js
  ui/pages/asset/components/asset-page.tsx
Labels: release-blocker, team-wallet-ux, release-12.7.0

#28231 feat: Show network badge in detected tokens modal
  ui/components/app/detected-token/detected-token-details/detected-token-details.js
Labels: team-wallet-ux, portfolio-view

#28141 chore: adds Solana snap to preinstall list
  app/scripts/snaps/preinstalled-snaps.ts
  package.json
  shared/lib/accounts/solana-wallet-snap.ts
  yarn.lock
Labels: team-sol

#28337 refactor: rename SECURITY_PROVIDER_SUPPORTED_CHAIN_IDS_FALLBACK_LIST
  app/scripts/lib/ppom/ppom-util.ts
  shared/constants/security-provider.ts
  test/e2e/mock-e2e.js
Labels: team-confirmations

#28107 fix: Updates to the simulations component
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/tests/simulation-details/simulation-details.spec.ts
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
  ui/pages/confirmations/components/simulation-details/fiat-display.test.tsx
  ui/pages/confirmations/components/simulation-details/fiat-display.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.test.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
  ui/pages/confirmations/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
Labels: team-confirmations

#28353 cherry pick: fix: smart transactions in redesigned confirmations
  test/data/confirmations/helper.ts
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/hooks/useSmartTransactionFeatureFlags.test.ts
  ui/pages/confirmations/hooks/useSmartTransactionFeatureFlags.ts
Labels: team-confirmations, team-transactions, release-12.7.0

#28351 cherry pick: chore: add the gas_included prop into Quotes Received event
  ui/ducks/swaps/swaps.js
Labels: team-transactions, release-12.7.0

#28324 Cherrypick v12.7.0 feat: Enable simulation metrics for redesign transactions
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.tsx
  ui/pages/confirmations/components/confirm/info/native-transfer/native-transfer.tsx
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/nft-token-transfer.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/token-transfer.tsx
Labels: team-confirmations, release-12.7.0

#28314 Cherrypick v12.7.0 feat: Add simulation metrics to "Transaction Submitted" and "Transaction Finalized" events
  app/scripts/controllers/metametrics.test.ts
  app/scripts/controllers/metametrics.ts
  app/scripts/lib/transaction/metrics.ts
  shared/constants/metametrics.ts
  ui/pages/confirmations/hooks/useTransactionEventFragment.js
Labels: team-confirmations, release-12.7.0

#28359 fix: disable account syncing
  app/scripts/metamask-controller.js
Labels: team-notifications

#28361 fix (Cherrypick v12.7.0 ): disable account syncing
  app/scripts/metamask-controller.js
Labels: team-notifications, release-12.7.0

#28360 fix: Revert "fix: Negate privacy mode in Send screen"
  ui/components/app/currency-input/currency-input.js
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.d.ts
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/components/multichain/asset-picker-amount/asset-balance/asset-balance-text.tsx
  ui/components/ui/currency-display/currency-display.component.d.ts
  ui/components/ui/currency-display/currency-display.component.js
  ui/pages/asset/components/asset-page.tsx
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#28367 fix: Bug 28347 - Privacy mode tweaks
  ui/components/app/assets/token-cell/token-cell.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.d.ts
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/ui/currency-display/currency-display.component.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
Labels: team-assets

#28365 build: update yarn to v4.5.1
  development/generate-attributions/package.json
  lavamoat/build-system/policy.json
  package.json
Labels: team-tiger

#28327 fix: gas limit estimation
  package.json
  test/e2e/flask/user-operations.spec.ts
  test/e2e/tests/transaction/edit-gas-fee.spec.js
  test/e2e/tests/transaction/multiple-transactions.spec.js
  yarn.lock
Labels: QA Passed, team-confirmations

#28236 refactor: remove global network usage from transaction confirmations
  .eslintrc.js
  .storybook/preview.js
  test/data/confirmations/contract-interaction.ts
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.test.js
  ui/pages/confirmations/components/confirm-hexdata/confirm-hexdata.test.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container.component.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container.container.js
  ui/pages/confirmations/components/confirm-subtitle/confirm-subtitle.test.js
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/approve-static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.tsx
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
  ui/pages/confirmations/components/confirm/info/approve/spending-cap/spending-cap.tsx
  ui/pages/confirmations/components/confirm/info/hooks/use-token-values.ts
  ui/pages/confirmations/components/confirm/info/hooks/useFeeCalculations.ts
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/advanced-details.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/native-send-heading/native-send-heading.tsx
  ui/pages/confirmations/components/confirm/info/shared/nft-send-heading/nft-send-heading.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.stories.tsx
  ui/pages/confirmations/components/confirm/title/hooks/useCurrentSpendingCap.ts
  ui/pages/confirmations/components/contract-details-modal/contract-details-modal.js
  ui/pages/confirmations/components/contract-token-values/contract-token-values.js
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.test.ts
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
  ui/pages/confirmations/components/transaction-alerts/transaction-alerts.js
  ui/pages/confirmations/components/transaction-alerts/transaction-alerts.stories.js
  ui/pages/confirmations/components/transaction-alerts/transaction-alerts.test.js
  ui/pages/confirmations/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirmations/confirm-approve/confirm-approve.js
  ui/pages/confirmations/confirm-send-token/confirm-send-token.js
  ui/pages/confirmations/confirm-token-transaction-base/confirm-token-transaction-base.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js
  ui/pages/confirmations/confirm/stories/transactions/contract-interaction.stories.tsx
  ui/pages/confirmations/confirm/stories/utils.tsx
  ui/pages/confirmations/hooks/test-utils.js
  ui/pages/confirmations/hooks/useAssetDetails.js
  ui/pages/confirmations/hooks/useTransactionFunctionType.js
  ui/pages/confirmations/hooks/useTransactionFunctionType.test.js
  ui/pages/confirmations/hooks/useTransactionInfo.js
  ui/pages/confirmations/hooks/useTransactionInfo.test.js
  ui/pages/confirmations/send/gas-display/gas-display.js
  ui/pages/confirmations/token-allowance/__snapshots__/token-allowance.test.js.snap
  ui/pages/confirmations/token-allowance/token-allowance.js
  ui/pages/confirmations/token-allowance/token-allowance.test.js
  ui/selectors/selectors.js
Labels: QA Passed, team-confirmations

#28212 fix: Address design review for ERC20 token send
  ui/components/app/confirm/info/row/__snapshots__/row.test.tsx.snap
  ui/components/app/confirm/info/row/row.tsx
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/name/name-details/name-details.test.tsx
  ui/hooks/useDisplayName.test.ts
  ui/hooks/useDisplayName.ts
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/native-transfer/native-transfer.test.tsx
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/nft-token-transfer.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/__snapshots__/transaction-data.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-details-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/token-details-section.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/token-transfer.test.tsx
Labels: team-confirmations

#28341 fix: disable buy for btc testnet accounts
  ui/components/app/wallet-overview/btc-overview.test.tsx
  ui/components/app/wallet-overview/btc-overview.tsx
Labels: team-accounts

#27857 feat(1852): Implement sentry user report on error screen
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/ph/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  privacy-snapshot.json
  shared/constants/metametrics.ts
  shared/modules/i18n.test.ts
  shared/modules/i18n.ts
  test/data/mock-state.json
  test/e2e/helpers.js
  test/e2e/page-objects/pages/developer-options-page.ts
  test/e2e/page-objects/pages/error-page.ts
  test/e2e/page-objects/pages/settings-page.ts
  test/e2e/tests/metrics/developer-options-sentry.spec.ts
  test/e2e/tests/metrics/errors.spec.js
  ui/ducks/locale/locale.js
  ui/ducks/locale/locale.test.ts
  ui/ducks/locale/locale.ts
  ui/pages/error-page/error-component.test.tsx
  ui/pages/error-page/error-page.component.tsx
  ui/pages/error-page/index.scss
  ui/pages/error-page/index.ts
  ui/pages/error/error.component.js
  ui/pages/error/index.js
  ui/pages/error/index.scss
  ui/pages/index.js
  ui/pages/pages.scss
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/developer-options-tab/developer-options-tab.tsx
  ui/pages/settings/developer-options-tab/sentry-test.tsx
  ui/pages/settings/settings.component.js
Labels: team-extension-platform

#28325 test: [POM] Refactor import account e2e tests to use Page Object Model
  test/e2e/helpers.js
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/page-objects/flows/send-transaction.flow.ts
  test/e2e/page-objects/pages/account-list-page.ts
  test/e2e/page-objects/pages/onboarding/onboarding-srp-page.ts
  test/e2e/page-objects/pages/send/send-token-page.ts
  test/e2e/tests/account/add-account.spec.js
  test/e2e/tests/account/add-account.spec.ts
  test/e2e/tests/account/import-flow.spec.js
  test/e2e/tests/account/import-flow.spec.ts
  test/e2e/tests/account/snap-account-transfers.spec.ts
  test/e2e/tests/confirmations/transactions/erc20-token-send-redesign.spec.ts
  test/e2e/tests/hardware-wallets/lattice-connect.spec.ts
  test/e2e/tests/privacy/basic-functionality.spec.js
  test/e2e/tests/transaction/simple-send.spec.ts
Labels: team-extension-platform

#28371 cherry-pick: bump `@metamask/queued-request-controller` with patch fix (#28355)
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#28382 fix: Return to send page with different asset types
  ui/pages/confirmations/components/confirm/header/wallet-initiated-header.tsx
Labels: team-confirmations

#28270 feat(Solana): add "Add a new Solana account" link to the account creation dialog
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/constants.ts
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/hooks/accounts/useBitcoinWalletSnapClient.test.ts
  ui/hooks/accounts/useMultichainWalletSnapClient.test.ts
  ui/hooks/accounts/useMultichainWalletSnapClient.ts
Labels: team-sol

#28387 chore: add unit test for `useMultiPolling`
  ui/hooks/useMultiPolling.test.ts
  ui/hooks/useMultiPolling.ts
Labels: team-assets

#28267 feat: change expand icon per new design
  ui/components/app/confirm/info/row/__snapshots__/expandable-row.test.tsx.snap
  ui/components/app/confirm/info/row/expandable-row.tsx
  ui/components/app/confirm/info/row/index.scss
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/__snapshots__/transaction-data.test.tsx.snap
Labels: team-confirmations

#28113 feat: migrate MetaMetricsController to BaseControllerV2
  app/scripts/controllers/metametrics-controller.test.ts
  app/scripts/controllers/metametrics-controller.ts
  app/scripts/controllers/metametrics-data-deletion/metametrics-data-deletion.test.ts
  app/scripts/controllers/metametrics-data-deletion/metametrics-data-deletion.ts
  app/scripts/controllers/metametrics.test.ts
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/controllers/mmi-controller.ts
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  shared/constants/mmi-controller.ts
  ui/contexts/metametrics.js
Labels: team-wallet-framework

#28384 fix: cherry-pick: Return to send page with different asset types
  ui/pages/confirmations/components/confirm/header/wallet-initiated-header.tsx
Labels: team-confirmations

#28377 fix(snaps): Patch `@metamask/snaps-utils`
  .yarn/patches/@metamask-snaps-utils-npm-8.4.1-90481bac4b.patch
  package.json
  yarn.lock
Labels: team-snaps-platform

#28405 fix (cherry-pick): gas limit estimation (#28327)
  package.json
  test/e2e/flask/user-operations.spec.ts
  test/e2e/tests/transaction/edit-gas-fee.spec.js
  test/e2e/tests/transaction/multiple-transactions.spec.js
  yarn.lock
Labels: team-confirmations

#28410 chore: update changelog
  CHANGELOG.md
Labels: team-confirmations

#28392 fix: Properly ellipsize long token names
  ui/components/multichain/token-list-item/token-list-item.tsx
Labels: team-wallet-ux

#28335 fix: Add metric trait for privacy mode
  app/scripts/controllers/metametrics-controller.test.ts
  app/scripts/controllers/metametrics-controller.ts
  shared/constants/metametrics.ts
Labels: team-wallet-ux, portfolio-view

#28354 test: [POM] Migrate reveal account srp e2e tests to use Page Object Model
  test/e2e/helpers.js
  test/e2e/page-objects/pages/error-page.ts
  test/e2e/page-objects/pages/settings/experimental-settings.ts
  test/e2e/page-objects/pages/settings/privacy-settings.ts
  test/e2e/page-objects/pages/settings/settings-page.ts
  test/e2e/tests/account/snap-account-settings.spec.ts
  test/e2e/tests/account/snap-account-signatures-and-disconnects.spec.ts
  test/e2e/tests/account/snap-account-signatures.spec.ts
  test/e2e/tests/metrics/developer-options-sentry.spec.ts
  test/e2e/tests/settings/settings-security-reveal-srp.spec.js
  test/e2e/tests/settings/settings-security-reveal-srp.spec.ts
Labels: team-extension-platform

#28418 fix: use `updateSecurityResponse`
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/ppom/ppom-util.test.ts
  app/scripts/lib/ppom/ppom-util.ts
  app/scripts/lib/transaction/util.test.ts
  app/scripts/lib/transaction/util.ts
Labels: team-confirmations

#28313 fix: get `supportedChains` to avoid blocking the confirmation process
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/ppom/ppom-util.test.ts
  app/scripts/lib/ppom/ppom-util.ts
  app/scripts/lib/ppom/types.ts
  app/scripts/lib/transaction/util.test.ts
  app/scripts/lib/transaction/util.ts
  shared/constants/security-provider.ts
  test/e2e/tests/confirmations/signatures/malicious-signatures.spec.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  test/e2e/tests/confirmations/signatures/siwe.spec.ts
  test/e2e/tests/metrics/signature-approved.spec.js
Labels: team-confirmations

#28011 feat: add `account_type`/`snap_id` for buy/send metrics
  ui/components/app/wallet-overview/btc-overview.test.tsx
  ui/components/app/wallet-overview/btc-overview.tsx
  ui/components/app/wallet-overview/coin-buttons.stories.js
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/pages/asset/components/asset-page.tsx
Labels: team-accounts

#28363 fix: `Test Snap Cronjob can trigger a cronjob to open a di...` flaky tests
  test/e2e/snaps/test-snap-cronjob.spec.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE, area-qa

#28413 ci: Fix `attributions:check` silent failure
  development/attributions-check.sh
Labels: team-wallet-framework

#27237 chore: limit bridge quote request frequency and cancel requests
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/bridge/bridge-controller.test.ts
  app/scripts/controllers/bridge/bridge-controller.ts
  app/scripts/controllers/bridge/constants.ts
  app/scripts/controllers/bridge/types.ts
  app/scripts/metamask-controller.js
  shared/modules/bridge-utils/balance.test.ts
  shared/modules/bridge-utils/balance.ts
  shared/modules/fetch-with-timeout.test.ts
  shared/modules/fetch-with-timeout.ts
  test/e2e/tests/metrics/errors.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
  ui/hooks/bridge/useCountdownTimer.test.ts
  ui/hooks/bridge/useCountdownTimer.ts
  ui/hooks/bridge/useLatestBalance.test.ts
  ui/hooks/bridge/useLatestBalance.ts
  ui/pages/bridge/bridge.util.test.ts
  ui/pages/bridge/bridge.util.ts
  ui/pages/bridge/index.test.tsx
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.test.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/quotes/bridge-quote-card.test.tsx
  ui/pages/bridge/quotes/bridge-quote-card.tsx
Labels: team-bridge, team-swaps

#27688 chore(deps): bump `@metamask/eth-ledger-bridge-keyring` to `^5.0.1`
  .yarn/patches/@ledgerhq-evm-tools-npm-1.2.3-414f44baa9.patch
  .yarn/patches/@ledgerhq-hw-app-eth-npm-6.39.0-866309bbbe.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-wallet-framework

#28383 test: [POM] Migrate autodetect and import nft e2e tests to use Page Object Model
  test/e2e/page-objects/pages/homepage.ts
  test/e2e/page-objects/pages/settings/privacy-settings.ts
  test/e2e/page-objects/pages/settings/settings-page.ts
  test/e2e/tests/confirmations/transactions/nft-token-send-redesign.spec.ts
  test/e2e/tests/tokens/nft/auto-detect-nft.spec.js
  test/e2e/tests/tokens/nft/auto-detect-nft.spec.ts
  test/e2e/tests/tokens/nft/import-nft.spec.js
  test/e2e/tests/tokens/nft/import-nft.spec.ts
Labels: team-extension-platform

#28421 test: fix state fixtures race condition
  test/e2e/helpers.js
Labels: team-extension-platform, flaky tests, area-qa

#28340 feat: btc send flow e2e
  test/e2e/constants.ts
  test/e2e/flask/btc/btc-send.spec.ts
  test/e2e/flask/btc/common-btc.ts
  ui/components/app/wallet-overview/coin-buttons.tsx
Labels: team-accounts

#28426 fix: fix network client ID used on the useGasFeeInputs hook (#28391)
  ui/pages/confirmations/hooks/test-utils.js
  ui/pages/confirmations/hooks/useGasFeeInputs.js
  ui/pages/confirmations/hooks/useGasFeeInputs.test.js
  ui/selectors/selectors.js
Labels: team-assets

#28086 perf: Create custom spans for account overview tabs
  app/scripts/controllers/app-state-controller.test.ts
  app/scripts/controllers/app-state-controller.ts
  shared/constants/app-state.ts
  shared/lib/trace.ts
  ui/components/app/assets/nfts/nfts-tab/nfts-tab.js
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/account-overview/account-overview-btc.test.tsx
  ui/components/multichain/account-overview/account-overview-eth.test.tsx
  ui/components/multichain/account-overview/account-overview-tabs.tsx
  ui/components/multichain/account-overview/account-overview-unknown.test.tsx
  ui/components/multichain/account-overview/common.ts
  ui/components/ui/tabs/tabs.component.js
  ui/selectors/selectors.js
Labels: area-Sentry, area-performance, team-wallet-framework, team-tiger

#28402 Multichain debug
  test/e2e/helpers.js
  test/e2e/mock-balance-polling/mock-balance-polling.ts
  test/e2e/mock-e2e.js
  test/e2e/page-objects/flows/login.flow.ts
  test/e2e/tests/ppom/ppom-blockaid-alert-simple-send.spec.js
  test/e2e/tests/smart-transactions/mock-requests-for-swap-test.ts
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
  test/e2e/tests/transaction/ens.spec.ts
  ui/hooks/useAccountTrackerPolling.ts
Labels: team-extension-platform

#28446 fix: Update PortfolioView flag
  builds.yml
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
Labels: team-assets, team-wallet-ux

#28397 feat: update signature controller and integrate decoding api
  app/scripts/controllers/mmi-controller.ts
  app/scripts/metamask-controller.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-confirmations

#28429 chore: Begin introducing patterns for Multichain AssetList
  test/e2e/tests/tokens/add-hide-token.spec.js
  test/e2e/tests/tokens/custom-token-add-approve.spec.js
  test/e2e/tests/tokens/token-details.spec.ts
  test/e2e/tests/tokens/token-list.spec.ts
  test/e2e/tests/tokens/token-sort.spec.ts
  ui/components/app/assets/asset-list/asset-list-control-bar/index.scss
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/asset-list/import-control/import-control.tsx
  ui/components/app/assets/asset-list/native-token/native-token.tsx
  ui/components/app/assets/asset-list/sort-control/index.scss
  ui/components/app/assets/token-cell/token-cell.test.tsx
  ui/components/app/assets/token-cell/token-cell.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/multichain/account-overview/account-overview-tabs.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/Asset.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx
  ui/components/multichain/import-token-link/import-token-link.test.js
  ui/components/multichain/token-list-item/token-list-item.test.tsx
  ui/components/multichain/token-list-item/token-list-item.tsx
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/asset/components/asset-page.tsx
  ui/pages/asset/util.test.ts
  ui/pages/asset/util.ts
  ui/selectors/multichain.ts
Labels: team-assets

#28409 fix: Hide "interacting with" when simulated balance changes are shown
  ui/pages/confirmations/components/confirm/info/token-transfer/token-details-section.tsx
Labels: team-confirmations

#28301 fix: Remove multiple overlapping spinners
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts
  ui/pages/confirmations/components/confirm/info/hooks/use-token-values.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/use-token-values.ts
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/confirm-loader/__snapshots__/confirm-loader.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/confirm-loader/confirm-loader.tsx
  ui/pages/confirmations/components/confirm/info/shared/native-send-heading/native-send-heading.tsx
  ui/pages/confirmations/components/confirm/info/shared/send-heading/__snapshots__/send-heading.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/send-heading/send-heading.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/transaction-flow-section.tsx
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
Labels: team-confirmations

#28454 Change device ID to use hexadecimal
  ui/components/app/snaps/snap-device-modal/snap-device-list-item.tsx
  ui/pages/snaps/snap-device-pairing/snap-device-pairing.tsx
Labels: team-snaps-platform

#28443 fix: ui customizations for redesigned transactions
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
Labels: INVALID-PR-TEMPLATE, team-confirmations

#27532 test: Improve test for signatures
  test/e2e/tests/confirmations/signatures/personal-sign.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v3.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data.spec.ts
  test/e2e/tests/confirmations/signatures/siwe.spec.ts
Labels: team-confirmations

#28415 fix: Fix attribution generation
  .depcheckrc.yml
  development/clear-webpack-cache.js
  development/generate-attributions.sh
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-wallet-framework, team-extension-platform

#28427 feat: add simulation metrics when simulation UI is not visible
  ui/pages/confirmations/components/confirm/info/native-transfer/native-transfer.tsx
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/nft-token-transfer.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/token-transfer.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.test.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
Labels: team-confirmations

#28457 fix: ui customizations for redesigned transactions (#28443)
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
Labels: INVALID-PR-TEMPLATE, team-confirmations

#28461 fix (cherry-pick): add simulation metrics when simulation UI is not visible (#28427)
  ui/pages/confirmations/components/confirm/info/native-transfer/native-transfer.tsx
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/nft-token-transfer.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/token-transfer.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.test.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
Labels: team-confirmations

#28448 fix: Allow outerclick to close import modal
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
Labels: team-wallet-ux

#28465 fix: dont poll token prices during onboarding or when locked
  ui/hooks/useCurrencyRatePolling.ts
  ui/hooks/useTokenRatesPolling.ts
Labels: team-assets

#28468 chore: Resolve conflicts v12.7.0 with latest master
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#28458 chore: V12.7.0 changelog
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#28419 test: [POM] Migrate vault decryption e2e tests to TS and Page Object Model
  test/e2e/helpers.js
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/page-objects/pages/settings/privacy-settings.ts
  test/e2e/page-objects/pages/vault-decryptor-page.ts
  test/e2e/tests/notifications/account-syncing/onboarding-with-opt-out.spec.ts
  test/e2e/tests/privacy/onboarding-infura-call-privacy.spec.ts
  test/e2e/tests/settings/settings-security-reveal-srp.spec.ts
  test/e2e/vault-decryption-chrome.spec.js
  test/e2e/vault-decryption-chrome.spec.ts
Labels: team-extension-platform

#28453 chore: Fix flaky ERC20 transfer blockaid e2e
  test/e2e/tests/ppom/ppom-blockaid-alert-erc20-transfer.spec.js
Labels: confirmation-redesign, team-confirmations

#28482 chore: fix test path on CI
  .circleci/config.yml
Labels: team-extension-platform

#28487 fix: Fix race condition validating ERC20 transfer (blockaid)
  app/scripts/lib/ppom/security-alerts-api.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/ppom/ppom-blockaid-alert-erc20-transfer.spec.js
Labels: team-confirmations

#28379 fix: display btc account creation while in settings
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
Labels: team-accounts

#28447 feat: Upgrade assets controllers to 43 with multichain polling for token lists + detection
  .yarn/patches/@metamask-assets-controllers-npm-43.1.1-c223d56176.patch
  .yarn/patches/@metamask-assets-controllers-patch-9e00573eb4.patch
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/tokens/add-hide-token.spec.js
  test/e2e/tests/tokens/import-tokens.spec.js
  ui/contexts/assetPolling.tsx
  ui/hooks/useTokenDetectionPolling.ts
  ui/hooks/useTokenListPolling.test.ts
  ui/hooks/useTokenListPolling.ts
  ui/pages/asset/useHistoricalPrices.ts
  ui/pages/onboarding-flow/pin-extension/pin-extension.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.test.js
  ui/selectors/selectors.js
  ui/store/actions.ts
  yarn.lock
Labels: team-assets

#28500 fix (cherry-pick): Fix race condition validating ERC20 transfer (blockaid) (#28487)
  CHANGELOG.md
  app/scripts/lib/ppom/security-alerts-api.ts
  app/scripts/metamask-controller.js
Labels: team-extension-platform

#28459 chore: Master sync
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#28505 chore: Fix changelog title v12.8.0
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#28472 feat: upgrade assets controllers to version 44
  .yarn/patches/@metamask-assets-controllers-npm-44.0.0-c223d56176.patch
  app/scripts/constants/sentry-state.ts
  app/scripts/metamask-controller.js
  package.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/app/assets/asset-list/asset-list.test.tsx
  ui/components/app/wallet-overview/btc-overview.test.tsx
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/multichain/account-overview/account-overview-btc.test.tsx
  ui/components/multichain/account-overview/account-overview-eth.test.tsx
  ui/ducks/metamask/metamask.js
  ui/hooks/useAccountTotalFiatBalance.js
  ui/hooks/useAccountTotalFiatBalance.test.js
  ui/hooks/useMultichainAccountTotalFiatBalance.test.tsx
  ui/hooks/useMultichainAccountTotalFiatBalance.ts
  ui/hooks/useTokenBalances.ts
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/routes/routes.component.test.js
  ui/store/actions.ts
  yarn.lock
Labels: team-assets

#28526 chore: Update changelog for v12.6.2
  CHANGELOG.md
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#28530 [cherry-pick] Update `cross spawn`
  package.json
  yarn.lock
Labels: team-wallet-framework

#28502 fix: PortfolioView: Selector to determine networks to poll
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-wallet-ux

#28521 fix: Make QR scanner more strict
  ui/components/app/modals/qr-scanner/qr-scanner.component.js
Labels: team-wallet-framework

#28531 fix: Make QR scanner more strict (#28521)
  ui/components/app/modals/qr-scanner/qr-scanner.component.js
Labels: team-wallet-framework

#28479 test: improve logs for e2e errors
  test/e2e/snaps/test-snap-metrics.spec.js
  test/e2e/tests/account/lockdown.spec.ts
  test/e2e/webdriver/driver.js
Labels: team-extension-platform, flaky tests, area-qa

#28424 test: [POM] Migrate onboarding metrics e2e tests to TS and Page Object Model to reduce flakiness
  test/e2e/helpers.js
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/page-objects/pages/onboarding/onboarding-metrics-page.ts
  test/e2e/tests/metrics/app-installed.spec.ts
  test/e2e/tests/metrics/nft-detection-metrics.spec.ts
  test/e2e/tests/metrics/token-detection-metrics.spec.ts
  test/e2e/tests/metrics/wallet-created.spec.ts
  test/e2e/tests/notifications/account-syncing/new-user-sync.spec.ts
  test/e2e/tests/onboarding/onboarding.spec.ts
  test/e2e/vault-decryption-chrome.spec.ts
Labels: team-extension-platform

#26554 perf: optimize fonts by using woff2 instead of ttf
  .vscode/cspell.json
  development/build/styles.js
  development/webpack/utils/plugins/ManifestPlugin/index.ts
  development/webpack/webpack.config.ts
  lavamoat/build-system/policy.json
  package.json
  types/postcss-discard-font-face.d.ts
  ui/css/utilities/fonts.scss
  ui/css/utilities/fonts/Euclid/EuclidCircularB-Bold-WebXL.ttf
  ui/css/utilities/fonts/Euclid/EuclidCircularB-Bold-WebXL.woff2
  ui/css/utilities/fonts/Euclid/EuclidCircularB-Medium-WebXL.woff2
  ui/css/utilities/fonts/Euclid/EuclidCircularB-Medium.ttf
  ui/css/utilities/fonts/Euclid/EuclidCircularB-Regular-WebXL.ttf
  ui/css/utilities/fonts/Euclid/EuclidCircularB-Regular-WebXL.woff2
  ui/css/utilities/fonts/Euclid/EuclidCircularB-RegularItalic-WebXL.ttf
  ui/css/utilities/fonts/Euclid/EuclidCircularB-RegularItalic-WebXL.woff2
  yarn.lock
Labels: area-performance, team-extension-platform, team-tiger

#28277 fix: account tracker controller with useMultiPolling
  app/scripts/metamask-controller.js
  test/e2e/mock-balance-polling/mock-balance-polling.ts
  test/e2e/mock-e2e.js
  test/e2e/tests/ppom/ppom-blockaid-alert-simple-send.spec.js
  test/e2e/tests/smart-transactions/mock-requests-for-swap-test.ts
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
  test/e2e/tests/transaction/ens.spec.ts
  ui/contexts/assetPolling.tsx
  ui/hooks/useAccountTrackerPolling.ts
  ui/store/actions.ts
Labels: team-assets, needs-assets-ux-review

#28525 chore: Reduce E2E test jobs run on PRs
  .circleci/config.yml
Labels: team-wallet-framework, team-extension-platform

#28366 feat: display ERC20 and ERC721 token details returns by decoding api
  app/_locales/en/messages.json
  ui/pages/confirmations/components/confirm/info/shared/static-simulation/static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/decoded-simulation/__snapshots__/decoded-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/decoded-simulation/decoded-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/decoded-simulation/decoded-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/value-display/value-display.tsx
Labels: team-confirmations

#28556 test: add token price privacy spec
  test/e2e/tests/privacy/onboarding-token-price-call-privacy.spec.ts
Labels: team-extension-platform, e2e-test, area-qa

#28539 feat(snaps): Add support for `Address` in `Card` title
  ui/components/app/snaps/snap-ui-card/snap-ui-card.tsx
  ui/components/app/snaps/snap-ui-renderer/components/card.ts
Labels: team-snaps-platform

#28433 fix: Address design review for NFT token send
  ui/ducks/metamask/metamask.js
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/approve-static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.test.ts
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts
  ui/pages/confirmations/components/confirm/info/approve/spending-cap/spending-cap.tsx
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/native-send-heading/native-send-heading.tsx
  ui/pages/confirmations/components/confirm/info/shared/nft-send-heading/__snapshots__/nft-send-heading.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/nft-send-heading/nft-send-heading.tsx
Labels: team-confirmations

#28456 feat: cross chain aggregated balance
  app/_locales/en/messages.json
  privacy-snapshot.json
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/e2e/default-fixture.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/e2e/tests/settings/account-token-list.spec.js
  test/integration/data/integration-init-state.json
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
  ui/components/app/wallet-overview/__snapshots__/aggregated-percentage-overview-cross-chains.test.tsx.snap
  ui/components/app/wallet-overview/aggregated-percentage-overview-cross-chains.test.tsx
  ui/components/app/wallet-overview/aggregated-percentage-overview-cross-chains.tsx
  ui/components/app/wallet-overview/btc-overview.test.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/pages/send/send.test.js
  ui/ducks/metamask/metamask.js
  ui/hooks/useAccountTotalCrossChainFiatBalance.test.ts
  ui/hooks/useAccountTotalCrossChainFiatBalance.ts
  ui/hooks/useGetFormattedTokensPerChain.test.ts
  ui/hooks/useGetFormattedTokensPerChain.ts
  ui/hooks/useTokenBalances.ts
  ui/pages/routes/routes.component.test.js
  ui/selectors/selectors.js
Labels: team-assets, needs-assets-ux-review

#28557 chore: Bump Snaps packages
  app/scripts/metamask-controller.js
  builds.yml
  package.json
  ui/components/app/snaps/snap-ui-card/snap-ui-card.tsx
  ui/components/app/snaps/snap-ui-renderer/components/card.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#28541 feat: account syncing various updates
  app/scripts/constants/sentry-state.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/metametrics.ts
  test/e2e/helpers/user-storage/userStorageMockttpController.test.ts
  test/e2e/helpers/user-storage/userStorageMockttpController.ts
  test/e2e/page-objects/pages/homepage.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/notifications/account-syncing/importing-private-key-account.spec.ts
  test/e2e/tests/notifications/account-syncing/new-user-sync.spec.ts
  test/e2e/tests/notifications/account-syncing/onboarding-with-opt-out.spec.ts
  test/e2e/tests/notifications/account-syncing/sync-after-adding-account.spec.ts
  test/e2e/tests/notifications/account-syncing/sync-after-modifying-account-name.spec.ts
  test/e2e/tests/notifications/account-syncing/sync-after-onboarding.spec.ts
  test/e2e/tests/notifications/mocks.ts
  test/integration/notifications&auth/data/notification-state.ts
  ui/hooks/metamask-notifications/useProfileSyncing/profileSyncing.test.tsx
  ui/hooks/metamask-notifications/useProfileSyncing/profileSyncing.ts
  ui/selectors/metamask-notifications/profile-syncing.test.ts
  ui/selectors/metamask-notifications/profile-syncing.ts
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: team-identity

#28249 fix: contact names should not allow duplication
  app/_locales/en/messages.json
  test/data/mock-data.js
  ui/components/app/contact-list/contact-list.component.js
  ui/components/app/contact-list/contact-list.test.js
  ui/components/app/contact-list/recipient-group/recipient-group.component.js
  ui/components/app/contact-list/utils.ts
  ui/components/multichain/address-list-item/__snapshots__/address-list-item.test.tsx.snap
  ui/components/multichain/address-list-item/address-list-item.test.tsx
  ui/components/multichain/address-list-item/address-list-item.tsx
  ui/components/multichain/address-list-item/index.scss
  ui/components/multichain/pages/send/components/address-book.tsx
  ui/components/multichain/pages/send/components/domain-input-resolution-cell.tsx
  ui/pages/confirmations/send/send.scss
  ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js
  ui/pages/settings/contact-list-tab/add-contact/add-contact.container.js
  ui/pages/settings/contact-list-tab/add-contact/add-contact.test.js
  ui/pages/settings/contact-list-tab/contact-list-tab.component.js
  ui/pages/settings/contact-list-tab/contact-list-tab.container.js
  ui/pages/settings/contact-list-tab/contact-list-tab.stories.js
  ui/pages/settings/contact-list-tab/edit-contact/edit-contact.component.js
  ui/pages/settings/contact-list-tab/edit-contact/edit-contact.container.js
  ui/pages/settings/contact-list-tab/edit-contact/edit-contact.test.js
Labels: team-identity

#28573 fix(sentry sampling): divide by 2 our sentry trace sample rate to avoid exceeding our quota
  app/scripts/lib/setupSentry.js
Labels: area-performance, team-extension-platform

#28569 fix: fix coin-overview display when price setting is off
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/multichain/account-list-item/account-list-item.js
Labels: team-assets

#28579 fix: use PORTFOLIO_VIEW flag to determine token list polling
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/hooks/useTokenListPolling.test.ts
  ui/hooks/useTokenListPolling.ts
Labels: team-assets

#27509 fix: Gracefully handle bad responses from `net_version` calls to RPC endpoint when getting Provider Network State
  app/scripts/metamask-controller.js
  shared/modules/network.utils.test.ts
  shared/modules/network.utils.ts
Labels: team-wallet-api-platform

#28575 refactor: Cherry pick asset-list-control-bar updates
  .storybook/test-data.js
  app/scripts/constants/sentry-state.ts
  test/e2e/fixture-builder.js
  test/e2e/tests/confirmations/transactions/erc20-approve-redesign.spec.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/e2e/tests/privacy/basic-functionality.spec.js
  test/e2e/tests/tokens/add-hide-token.spec.js
  test/e2e/tests/tokens/custom-token-add-approve.spec.js
  test/e2e/tests/tokens/import-tokens.spec.js
  test/e2e/tests/tokens/token-details.spec.ts
  test/e2e/tests/tokens/token-list.spec.ts
  test/e2e/tests/tokens/token-sort.spec.ts
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/asset-list/asset-list-control-bar/index.scss
  ui/components/app/assets/asset-list/asset-list.test.tsx
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/asset-list/import-control/import-control.tsx
  ui/components/app/assets/asset-list/sort-control/sort-control.tsx
  ui/components/multichain/account-overview/account-overview-btc.test.tsx
  ui/components/multichain/account-overview/account-overview-eth.test.tsx
  ui/components/multichain/import-token-link/__snapshots__/import-token-link.test.js.snap
  ui/components/multichain/import-token-link/import-token-link.stories.tsx
  ui/components/multichain/import-token-link/import-token-link.test.js
  ui/components/multichain/import-token-link/import-token-link.tsx
  ui/components/multichain/import-token-link/import-token-link.types.ts
  ui/components/multichain/import-token-link/index.ts
  ui/components/multichain/index.js
  ui/pages/routes/routes.component.test.js
Labels: team-assets

#28552 fix: PortfolioView: Remove pausedChainIds from selector
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-wallet-ux

#28560 feat: Better handle very long names in the name component
  ui/components/app/name/__snapshots__/name.test.tsx.snap
  ui/components/app/name/name.test.tsx
  ui/components/app/name/name.tsx
Labels: team-confirmations

#28598 fix: fix account list item for portfolio view
  test/e2e/tests/settings/account-token-list.spec.js
  ui/components/multichain/account-list-item/account-list-item.js
Labels: team-assets, needs-assets-ux-review

#28583 Cherry pick d5c0aaa to 12.7.1
  .circleci/config.yml
  package.json
Labels: team-extension-platform

#28452 chore: upgrade transaction controller to increase polling rate
  package.json
  yarn.lock
Labels: QA Passed, team-confirmations

#28612 fix: fix display amount when price checker off
  ui/components/app/wallet-overview/coin-overview.tsx
Labels: team-assets

#28618 Update CHANGELOG.md for v12.7.1
  CHANGELOG.md
Labels: team-extension-platform

#27262 feat: cross chain swaps - tx submit
  app/_locales/en/messages.json
  app/scripts/controllers/bridge/bridge-controller.test.ts
  app/scripts/controllers/bridge/bridge-controller.ts
  app/scripts/controllers/bridge/constants.ts
  app/scripts/controllers/bridge/types.ts
  app/scripts/metamask-controller.js
  shared/constants/bridge.ts
  shared/constants/metametrics.ts
  shared/constants/security-provider.ts
  test/data/bridge/dummy-quotes.ts
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/selectors.ts
  ui/ducks/bridge/utils.ts
  ui/hooks/useTransactionDisplayData.js
  ui/pages/bridge/bridge.util.ts
  ui/pages/bridge/hooks/useAddToken.ts
  ui/pages/bridge/hooks/useHandleApprovalTx.ts
  ui/pages/bridge/hooks/useHandleBridgeTx.ts
  ui/pages/bridge/hooks/useHandleTx.ts
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.test.tsx
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/bridge-cta-button.tsx
  ui/pages/bridge/types.ts
  ui/pages/swaps/hooks/useSwapsFeatureFlags.ts
  ui/pages/swaps/swaps.util.ts
  ui/store/actions.ts
Labels: team-bridge

#27607 feat: Hook in Portfolio Entry Points
  app/_locales/en/messages.json
  ui/pages/asset/asset.scss
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/asset/components/asset-page.tsx
Labels: team-portfolio, INVALID-PR-TEMPLATE

#28620 fix: replace unreliable setTimeout usage with waitFor
  ui/pages/settings/contact-list-tab/add-contact/add-contact.test.js
Labels: team-identity

#28593 feat: `PortfolioView`
  app/_locales/en/messages.json
  shared/constants/network.ts
  test/data/mock-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/privacy-mode/privacy-mode.spec.js
  test/e2e/tests/tokens/token-sort.spec.ts
  test/jest/mock-store.js
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/asset-list/asset-list.ramps-card.test.js
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/asset-list/native-token/native-token.tsx
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
  ui/components/app/assets/nfts/nfts-items/nfts-items.js
  ui/components/app/assets/nfts/nfts-items/nfts-items.test.js
  ui/components/app/assets/token-cell/__snapshots__/token-cell.test.tsx.snap
  ui/components/app/assets/token-cell/token-cell.test.tsx
  ui/components/app/assets/token-cell/token-cell.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/app/assets/util/calculateTokenBalance.ts
  ui/components/app/assets/util/calculateTokenFiatAmount.ts
  ui/components/app/toast-master/toast-master.js
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/components/app/wallet-overview/btc-overview.test.tsx
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/multichain/account-overview/account-overview-tabs.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
  ui/components/multichain/network-list-menu/network-list-menu.test.js
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/components/multichain/pages/send/components/recipient-content.tsx
  ui/components/multichain/pages/send/send.js
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.tsx.snap
  ui/components/multichain/token-list-item/token-list-item.test.tsx
  ui/components/multichain/token-list-item/token-list-item.tsx
  ui/hooks/useAccountTotalFiatBalance.test.js
  ui/hooks/useMultichainAccountTotalFiatBalance.test.tsx
  ui/pages/asset/asset.tsx
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/asset/components/asset-page.tsx
  ui/pages/asset/components/native-asset.tsx
  ui/pages/asset/components/token-asset.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/asset/util.test.ts
  ui/pages/asset/util.ts
  ui/pages/routes/routes.component.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-assets, team-wallet-ux

#28275 feat(SwapsController): Remove reliance on global network
  app/scripts/controllers/swaps/index.ts
  app/scripts/controllers/swaps/swaps.test.ts
  app/scripts/controllers/swaps/swaps.types.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/stub/provider.js
  ui/ducks/swaps/swaps.js
  ui/selectors/selectors.js
  yarn.lock
Labels: team-wallet-framework
