Repository MetaMask/metamask-extension, pull requests merged in 2024-02, with the labels that each got.

#22381 Integrate LavaDome private key protection
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/account-menu/account-details.spec.js
  ui/components/multichain/account-details/account-details-key.js
  ui/components/multichain/account-details/account-details.test.js
  yarn.lock
Labels: type-security, dependencies, team-lavamoat, QA Passed, needs-dev-review

#22631 [Bug|Feat] blockaid external link clicked metric update
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  shared/constants/metametrics.ts
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request/signature-request.js
  ui/components/app/terms-of-use-popup/terms-of-use-popup.test.js
  ui/components/app/transaction-alerts/transaction-alerts.js
  ui/helpers/utils/metric.test.js
  ui/helpers/utils/metrics.js
  ui/helpers/utils/metrics.test.js
  ui/hooks/useTransactionEventFragment.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/token-allowance/token-allowance.js
Labels: type-bug, area-metrics, team-confirmations-secure-ux-PR

#22755 chore: update Node.js to v20
  .circleci/config.yml
  .nvmrc
  README.md
  package.json
  test/e2e/mmi/Dockerfile
  yarn.lock
Labels: team-unkown

#22600 Petnames: Addition of shouldSyncPetname Method for Petnames Synchronization Control
  app/scripts/lib/AbstractPetnamesBridge.test.ts
  app/scripts/lib/AbstractPetnamesBridge.ts
  app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts
  app/scripts/lib/AccountIdentitiesPetnamesBridge.ts
Labels: team-confirmations-system

#22765 LavaDome minor fixes
  app/_locales/en/messages.json
  ui/components/multichain/account-details/account-details-key.js
  ui/components/multichain/account-details/account-details.test.js
Labels: team-design-system, INVALID-PR-TEMPLATE

#22384 [MMI] hides the new buy & receive button
  ui/components/app/asset-list/asset-list.js
Labels: team-mmi

#22648 Revise warning copy when adding custom network with existing currency symbol (v2)
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/pages/settings/networks-tab/networks-form/networks-form.js
Labels: team-extension-ux, needs-ux-ds-review

#20396 Disable MetaMask on Battle.net
  shared/modules/provider-injection.js
Labels: team-extension-platform

#22764 e2e: Add more information to error messages in CircleCI
  test/e2e/helpers.js
Labels: area-testSuite, team-extension-platform, flaky tests

#21648 UX: Send Flow: Unit tests
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/account-picker.test.tsx.snap
  ui/components/multichain/pages/send/components/__snapshots__/network-picker.test.tsx.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/components/multichain/pages/send/components/account-picker.test.tsx
  ui/components/multichain/pages/send/components/account-picker.tsx
  ui/components/multichain/pages/send/components/index.ts
  ui/components/multichain/pages/send/components/network-picker.test.tsx
  ui/components/multichain/pages/send/components/recipient.test.tsx
  ui/components/multichain/pages/send/components/recipient.tsx
  ui/components/multichain/pages/send/components/your-accounts.test.tsx
  ui/components/multichain/pages/send/components/your-accounts.tsx
  ui/components/multichain/pages/send/send.test.js
Labels: team-extension-client, team-extension-ux, needs-ux-ds-review, needs-dev-review

#22523 chore: remove invalid `as` type from `props`
  ui/components/component-library/badge-wrapper/badge-wrapper.tsx
  ui/components/component-library/badge-wrapper/badge-wrapper.types.ts
  ui/components/component-library/checkbox/checkbox.tsx
  ui/components/component-library/index.ts
Labels: team-extension-client

#22625 Refactor and update blockaid banner alert
  shared/constants/security-provider.ts
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.stories.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-utils.js
  ui/components/app/security-provider-banner-alert/security-provider-banner-alert.js
Labels: team-confirmations-secure-ux

#22805 Dont dispatch setUseRequestQueue
  ui/pages/settings/experimental-tab/experimental-tab.container.js
Labels: team-devex, needs-dev-review

#22749 Confirmation redesign: adding title to personal sign component
  test/data/mock-state.json
  ui/pages/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirm/confirm.test.ts
  ui/pages/confirm/confirm.test.tsx
  ui/pages/confirm/confirm.tsx
  ui/pages/confirm/mock-data.ts
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#22627 fix: IPFS NFTs fetching
  app/scripts/controllers/preferences.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/app/nft-default-image/toggle-ipfs-modal.js
  ui/components/app/nfts-items/nfts-items.js
  ui/pages/settings/advanced-tab/advanced-tab.stories.js
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/store/actions.ts
Labels: team-assets

#22742 feat: BlockaidBannerAlert update Failed type false positive support
  shared/constants/security-provider.ts
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
Labels: team-confirmations-secure-ux-PR

#22829 [test] PPOM - Run Simple Send Eth test against Multichain build
  test/e2e/helpers.js
  test/e2e/tests/ppom-blockaid-alert-simple-send.spec.js
Labels: team-confirmations-secure-ux

#22529 refactor: remove `globalThis` as all build targets support it natively now
  app/manifest/v2/_base.json
  app/manifest/v3/_base.json
  app/scripts/app-init.js
  development/build/index.js
  development/build/scripts.js
  development/build/static.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  test/e2e/mv3-perf-stats/bundle-size.js
  yarn.lock
Labels: team-extension-platform

#22526 refactor: combine RTL and LTR stylesheets
  app/background.html
  app/home.html
  app/loading.html
  app/notification.html
  app/popup.html
  app/trezor-usb-permissions.html
  development/build/styles.js
  lavamoat/build-system/policy.json
  package.json
  shared/lib/switch-direction.js
  ui/index.js
  ui/store/actions.ts
  yarn.lock
Labels: area-UI, area-translation, team-extension-ux, team-extension-platform, needs-assets-ux-review

#22801 e2e: remove failOnConsoleError and replace with ignoredConsoleErrors
  test/e2e/accounts/common.ts
  test/e2e/accounts/create-snap-account.spec.ts
  test/e2e/accounts/remove-account-snap.spec.ts
  test/e2e/accounts/snap-account-settings.spec.ts
  test/e2e/accounts/snap-account-signatures-and-disconnects.spec.ts
  test/e2e/helpers.js
  test/e2e/mv3-perf-stats/init-load-stats.js
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/snaps/test-snap-get-file.spec.js
  test/e2e/snaps/test-snap-get-locale.spec.js
  test/e2e/snaps/test-snap-getentropy.spec.js
  test/e2e/snaps/test-snap-homepage.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-lifecycle.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-namelookup.spec.js
  test/e2e/snaps/test-snap-networkaccess.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-revoke-perm.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-txinsights-v2.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-update-component.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  test/e2e/snaps/test-snap-wasm.spec.js
  test/e2e/tests/account-menu/account-details.spec.js
  test/e2e/tests/account-menu/add-account.spec.js
  test/e2e/tests/backup-restore.spec.js
  test/e2e/tests/change-language.spec.js
  test/e2e/tests/custom-rpc-history.spec.js
  test/e2e/tests/errors.spec.js
  test/e2e/tests/full-size-view-settings.spec.js
  test/e2e/tests/import-flow.spec.js
  test/e2e/tests/incremental-security.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/tests/nft/erc1155-interaction.spec.js
  test/e2e/tests/nft/erc721-interaction.spec.js
  test/e2e/tests/onboarding.spec.js
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
  test/e2e/tests/provider-api.spec.js
  test/e2e/tests/security-provider.spec.js
  test/e2e/tests/send-edit.spec.js
  test/e2e/tests/send-hex-address.spec.js
  test/e2e/tests/send-to-contract.spec.js
  test/e2e/tests/settings-security-reveal-srp.spec.js
  test/e2e/tests/state-logs.spec.js
  test/e2e/tests/swaps/swap-eth.spec.js
  test/e2e/tests/switch-custom-network.spec.js
  test/e2e/vault-decryption-chrome.spec.js
  test/e2e/webdriver/driver.js
  ui/helpers/utils/permission.js
Labels: area-testSuite, team-extension-platform

#22813 Move security alerts out of Experimental settings on Extension
  test/e2e/tests/ppom-blockaid-toggle-metrics.spec.js
  test/e2e/tests/ppom-toggle-settings.spec.js
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.container.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/security-tab/security-tab.test.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22694 Fix `send max` issue
  ui/ducks/confirm-transaction/confirm-transaction.duck.js
  ui/ducks/confirm-transaction/confirm-transaction.duck.test.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
Labels: team-confirmations-system, QA Passed

#22730 [MMI] patch to 11.9 fixing issues with transacction promise resolution (no cherry-pick)
  .yarn/patches/@metamask-transaction-controller-npm-19.0.0-4a98d488b2.patch
  package.json
  yarn.lock
Labels: team-mmi, INVALID-PR-TEMPLATE

#22845 Fix `getIsLocked` hook
  app/scripts/metamask-controller.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22752 Master sync following v11.7.5 and v11.8.0
  CHANGELOG.md
  package.json
Labels: extension-delivery

#22825 [MMI] Refactored the way we are showing the user the deep custodian link.
  app/scripts/controllers/app-state.js
  app/scripts/controllers/app-state.test.js
  app/scripts/controllers/mmi-controller.js
  app/scripts/metamask-controller.js
  ui/components/app/signature-request-original/signature-request-original.container.js
  ui/components/app/signature-request/signature-request.js
  ui/components/app/signature-request/signature-request.test.js
  ui/hooks/useMMICustodySignMessage.js
  ui/hooks/useMMICustodySignMessage.test.js
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/selectors/institutional/selectors.js
  ui/selectors/institutional/selectors.test.js
  ui/store/institutional/institution-background.test.js
  ui/store/institutional/institution-background.ts
Labels: team-mmi

#22855 Fix `useTransactionInsightSnaps`
  ui/hooks/snaps/useTransactionInsightSnaps.js
Labels: flask, team-snaps

#22731 fix: disable smart swaps for Snap accounts
  test/e2e/accounts/smart-swap-disabled.spec.ts
  test/jest/mock-store.js
  ui/ducks/swaps/swaps.js
  ui/ducks/swaps/swaps.test.js
  ui/pages/swaps/transaction-settings/transaction-settings.js
  ui/selectors/selectors.js
Labels: team-accounts, needs-dev-review

#22779 e2e: Writing new test for settings about metamask section
  test/e2e/tests/settings/about-metamask/ui-validation.spec.ts
  test/scenarios/17. settings/about-metamask/ui-validation.csv
Labels: team-extension-platform, INVALID-PR-TEMPLATE, e2e-test

#22852 chore: Update `@metamask/keyring-controller` to v12
  .yarn/patches/@metamask-keyring-controller-npm-12.2.0-2b196324d1.patch
  app/scripts/controllers/mmi-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#22850 Simplify permissions page logic
  ui/components/app/permission-page-container/permission-page-container.component.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22858 Cherry-picks 7a3d9e2 (#22676) into Version-v11.10.0
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/data/mock-pending-transaction-data.json
  ui/components/app/cancel-button/cancel-button.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.test.js
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
  ui/components/app/transaction-status-label/__snapshots__/transaction-status-label.test.js.snap
  ui/components/app/transaction-status-label/index.scss
  ui/components/app/transaction-status-label/transaction-status-label.js
  ui/components/app/transaction-status-label/transaction-status-label.test.js
  ui/helpers/constants/error-keys.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/selectors/transactions.js
  ui/selectors/transactions.test.js
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: QA Passed

#22873 Simplify logic to disconnect from a snap
  app/scripts/metamask-controller.js
  ui/components/app/connected-sites-list/connected-snaps.js
  ui/pages/snaps/snap-view/snap-settings.js
  ui/pages/snaps/snap-view/snap-view.test.js
  ui/store/actions.ts
Labels: team-snaps, INVALID-PR-TEMPLATE

#22846 Version v11.9.1
  .yarn/patches/@metamask-transaction-controller-npm-19.0.0-4a98d488b2.patch
  CHANGELOG.md
  app/scripts/controllers/metametrics.js
  package.json
  test/e2e/tests/errors.spec.js
  yarn.lock
Labels: team-mmi

#22824 UX: Show names for the accounts in Send Flow
  test/e2e/tests/address-book.spec.js
  ui/components/multichain/address-list-item/__snapshots__/address-list-item.test.tsx.snap
  ui/components/multichain/address-list-item/address-list-item.stories.tsx
  ui/components/multichain/address-list-item/address-list-item.test.tsx
  ui/components/multichain/address-list-item/address-list-item.tsx
  ui/components/multichain/pages/send/components/recipient.tsx
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#22637 UX Multichain: Updated app header account picker and address button
  test/e2e/tests/account-menu/add-account.spec.js
  test/e2e/tests/import-flow.spec.js
  ui/components/app/wallet-overview/wallet-overview.js
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/account-picker/account-picker.test.js
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/index.scss
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/account-picker.test.tsx.snap
Labels: team-extension-client, team-extension-ux, needs-ux-ds-review, INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#22881 chore: Update LavaMoat
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#22861 chore: Update `@metamask/signature-controller` and related packages
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#22524 refactor: make `inpage.js` inject itself into the MAIN world (manifest v2 only)
  app/manifest/v2/_base.json
  app/scripts/contentscript.js
  development/build/scripts.js
  development/build/utils.js
  development/sourcemap-validator.js
Labels: team-extension-platform, team-security

#22854 Remove clashing published files from lavadome
  package.json
  yarn.lock
Labels: dependencies, team-lavamoat, INVALID-PR-TEMPLATE

#22882 Version 11.9.2
  .yarn/patches/@metamask-accounts-controller-npm-4.0.0-3127b56d14.patch
  CHANGELOG.md
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-mmi

#22654 UX: Add event tracking for empty banner displays
  shared/constants/metametrics.ts
  ui/components/app/asset-list/asset-list.buy-receive.test.js
  ui/components/app/asset-list/asset-list.js
  ui/components/app/asset-list/asset-list.test.js
  ui/components/app/nfts-tab/nfts-tab.js
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/pages/routes/routes.component.test.js
Labels: team-extension-client, team-extension-ux, needs-ux-ds-review, needs-assets-ux-review

#22821 [Snaps E2E] Remove / Replace superflous arbitrary delays in snaps E2E tests
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/snaps/test-snap-get-file.spec.js
  test/e2e/snaps/test-snap-get-locale.spec.js
  test/e2e/snaps/test-snap-getentropy.spec.js
  test/e2e/snaps/test-snap-homepage.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-lifecycle.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-namelookup.spec.js
  test/e2e/snaps/test-snap-networkaccess.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-revoke-perm.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-txinsights-v2.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-update-component.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  test/e2e/snaps/test-snap-wasm.spec.js
Labels: area-snaps, team-snaps

#22883 [MMI] Fixes PW e2e tests (snapshots)
  test/e2e/mmi/pageObjects/mmi-accountMenu-page.ts
  test/e2e/mmi/specs/extension.visual.spec.ts-snapshots/token-replacement-notification-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-connection-info-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-list-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-remove-token-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custody-accounts-selection-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/mainWindow-custodian-selected-mmi-visual-linux.png
Labels: team-mmi

#22843 e2e: Reduce CircleCI credit usage
  .circleci/config.yml
Labels: area-testSuite, team-extension-platform, needs-dev-review

#22890 fix: gas fee editing should not be hidden if user has disabled currency rate check
  ui/pages/confirmations/components/gas-details-item/gas-details-item.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22853 Add deprecated comment on `displayWarning`
  ui/store/actions.ts
Labels: team-extension-platform

#22910 fix: fix deps
  package.json
  yarn.lock
Labels: team-assets, team-wallet-ux

#22814 Fix detected tokens added to wrong network
  app/scripts/controllers/detect-tokens.js
Labels: team-assets, needs-assets-ux-review

#22760 fix: asset list showing fiat symbol instead of native
  ui/components/app/asset-list/asset-list.js
Labels: team-extension-ux, team-assets, needs-assets-ux-review

#22915 Fixes an issue cancelling a permission request
  ui/components/app/permission-page-container/permission-page-container.component.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22909 Update discover snaps CTA link
  ui/pages/snaps/snaps-list/snap-list.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22907 test: wait for PPOM loading spinner to disappear
  test/e2e/tests/ppom-blockaid-alert-erc20-approval.spec.js
  test/e2e/tests/ppom-blockaid-alert-erc20-transfer.spec.js
  test/e2e/tests/ppom-blockaid-alert-networks-support.spec.js
  test/e2e/tests/ppom-blockaid-alert-trade-order-farming.spec.js
  test/e2e/tests/ppom-blockaid-alert.spec.js
  test/e2e/tests/ppom-blockaid-setApprovalForAll-farming.spec.js
Labels: team-confirmations-secure-ux-PR

#22924 Version v11.9.4
  CHANGELOG.md
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#22678 Remove unused notifications, their messages, and images
  .storybook/test-data.js
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/ph/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/blockaid-security-provider.png
  app/images/darkmode-banner.png
  app/images/global-menu-block-explorer.svg
  app/images/mobile-link-qr.svg
  app/images/nfts.svg
  app/images/open-sea-security-provider.svg
  app/images/source-logos-bsc.svg
  app/images/swaps-redesign.svg
  app/images/token-detection.svg
  app/images/txinsights.png
  shared/notifications/index.js
  test/e2e/fixture-builder.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: team-extension-platform, QA Passed, needs-dev-review

#22856 fix: fix selectedAddress and nftController instantiation
  app/scripts/metamask-controller.js
  test/e2e/tests/nft/import-nft.spec.js
  ui/ducks/metamask/metamask.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-wallet-ux, needs-assets-ux-review

#22832 Fix issue with manually added networks
  test/e2e/tests/custom-rpc-history.spec.js
  test/e2e/tests/onboarding.spec.js
  ui/pages/onboarding-flow/add-network-modal/index.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
Labels: team-extension-ux, team-devex, INVALID-PR-TEMPLATE, needs-assets-ux-review

#22550 Minor language fixes in messages.json-en
  app/_locales/en/messages.json
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
Labels: external-contributor

#22762 22542 add e2e test for update network
  test/e2e/tests/network/update-network.spec.ts
  ui/pages/onboarding-flow/add-network-modal/__snapshots__/add-network-modal.test.js.snap
  ui/pages/settings/networks-tab/networks-form/networks-form.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE, e2e-test

#22186 UX: Show Total Account Balances
  shared/constants/network.ts
  test/e2e/ganache.ts
  test/e2e/helpers.js
  test/e2e/tests/account-token-list.spec.js
  test/e2e/tests/advanced-settings.spec.js
  test/e2e/tests/contract-interactions.spec.js
  test/e2e/tests/incremental-security.spec.js
  test/e2e/tests/localization.spec.js
  test/e2e/tests/lock-account.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/tests/migrate-old-vault.spec.js
  test/e2e/tests/send-eth.spec.js
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/components/multichain/pages/send/send.test.js
  ui/hooks/useUserPreferencedCurrency.js
  ui/hooks/useUserPreferencedCurrency.test.js
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/remove-snap-account.test.js
Labels: team-extension-ux, team-wallet-ux, needs-assets-ux-review

#22944 Fix memoisation base transaction confirmation container
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  ui/selectors/selectors.js
Labels: team-snaps, team-confirmations-system

#22946 Revert "22542 add e2e test for update network"
  test/e2e/tests/network/update-network.spec.ts
  ui/pages/onboarding-flow/add-network-modal/__snapshots__/add-network-modal.test.js.snap
  ui/pages/settings/networks-tab/networks-form/networks-form.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#22898 Add networkClientId to DetectTokensController.detectNewTokens()
  app/scripts/controllers/detect-tokens.js
  app/scripts/controllers/detect-tokens.test.js
Labels: team-devex

#22961 fix(e2e): PR blocker "Send ETH from inside MetaMask..." on test-e2e-chrome-mmi
  test/e2e/tests/send-eth.spec.js
Labels: team-extension-platform

#22960 fix: Remove unnecessary resolution for socks
  package.json
  yarn.lock
Labels: team-wallet-ux

#22880 fix: switch e2e test to mainnet instead of ganache
  test/e2e/fixture-builder.js
  test/e2e/tests/add-hide-token.spec.js
Labels: team-wallet-ux, needs-assets-ux-review

#22968 [MMI] Moving mmi keyrings outside if else logic in order to have them in mv3 version
  app/scripts/metamask-controller.js
Labels: team-mmi

#22954 Updated GasFeeController to latest package version
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-devex, INVALID-PR-TEMPLATE

#22530 chore: update typescript to ~v5.3.3
  .depcheckrc.yml
  .eslintrc.base.js
  .eslintrc.js
  .gitignore
  .prettierignore
  app/scripts/lib/SnapsNameProvider.ts
  app/scripts/lib/snap-keyring/metrics.ts
  development/build/index.js
  lavamoat/build-system/policy.json
  package.json
  shared/constants/network.ts
  shared/modules/object.utils.js
  tsconfig.json
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.tsx
  ui/ducks/send/send.js
  ui/store/actions.ts
  yarn.lock
Labels: team-extension-platform

#22816 Revert remove staking link
  app/_locales/en/messages.json
  app/images/icons/stake.svg
  app/images/portfolio-stake-notification-light-mode.png
  shared/constants/metametrics.ts
  shared/notifications/index.js
  test/e2e/tests/add-hide-token.spec.js
  test/e2e/tests/add-multiple-tokens.spec.js
  ui/components/app/asset-list/asset-list.js
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/token-list-item.js
  ui/components/multichain/token-list-item/token-list-item.stories.js
  ui/components/multichain/token-list-item/token-list-item.test.js
  ui/selectors/selectors.js
Labels: team-extension-ux, team-portfolio, needs-ux-ds-review, INVALID-PR-TEMPLATE

#22867 Fix/password not present after tapping back
  ui/components/app/hold-to-reveal-button/hold-to-reveal-button.js
  ui/components/app/modals/hold-to-reveal-modal/hold-to-reveal-modal.tsx
  ui/components/multichain/account-details/account-details.js
Labels: team-accounts

#22977 chore: support code fencing of .tsx files
  development/build/transforms/remove-fenced-code.js
Labels: team-extension-platform

#22975 test: optimize memory usage when building storybook by using swc
  .storybook/main.js
  ui/components/ui/icon/README.mdx
  ui/components/ui/icon/icon.stories.js
  ui/components/ui/logo/logo.stories.js
Labels: team-extension-platform

#22978 fix: Update ppom_release to fix fail ppom security validation checks
  package.json
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
  yarn.lock
Labels: team-confirmations-secure-ux

#22955 Bump eth-snap-keyring to v2.1.2
  package.json
  yarn.lock
Labels: team-extension-platform, needs-dev-review

#22983 Version v11.9.5
  CHANGELOG.md
  package.json
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
  yarn.lock
Labels: team-extension-platform, team-confirmations-secure-ux-PR, INVALID-PR-TEMPLATE

#22897 chore: upgrading design tokens to v2
  package.json
  yarn.lock
Labels: team-design-system, needs-ux-ds-review

#22888 Fix storybook path of confirmation components
  ui/pages/confirmations/components/advanced-gas-controls/advanced-gas-controls.stories.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.stories.js
  ui/pages/confirmations/components/approve-content-card/approve-content-card.stories.js
  ui/pages/confirmations/components/confirm-gas-display/confirm-gas-display.stories.js
  ui/pages/confirmations/components/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.stories.js
  ui/pages/confirmations/components/confirm-hexdata/confirm-hexdata.stories.js
  ui/pages/confirmations/components/confirm-page-container/confirm-detail-row/confirm-detail-row.stories.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-content/confirm-page-container-summary/confirm-page-container-summary.stories.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-header/confirm-page-container-header.stories.js
  ui/pages/confirmations/components/confirm-subtitle/confirm-subtitle.stories.js
  ui/pages/confirmations/components/confirm-title/confirm-title.stories.js
  ui/pages/confirmations/components/confirm/footer/footer.stories.tsx
  ui/pages/confirmations/components/confirm/header/header.stories.tsx
  ui/pages/confirmations/components/confirmation-warning-modal/confirm-warning-modal.stories.js
  ui/pages/confirmations/components/contract-details-modal/contract-details-modal.stories.js
  ui/pages/confirmations/components/custom-spending-cap/custom-spending-cap.stories.js
  ui/pages/confirmations/components/edit-gas-display/edit-gas-display.stories.js
  ui/pages/confirmations/components/edit-gas-fee-icon/edit-gas-fee-icon.stories.js
  ui/pages/confirmations/components/edit-gas-popover/edit-gas-popover.stories.js
  ui/pages/confirmations/components/fee-details-component/fee-details-component.stories.js
  ui/pages/confirmations/components/gas-details-item/gas-details-item.stories.js
  ui/pages/confirmations/components/ledger-instruction-field/ledger-instruction-field.stories.js
  ui/pages/confirmations/components/multilayer-fee-message/multi-layer-fee-message.stories.js
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.stories.js
  ui/pages/confirmations/components/security-provider-banner-alert/security-provider-banner-alert.stories.js
  ui/pages/confirmations/components/set-approval-for-all-warning/set-approval-for-all-warning.stories.js
  ui/pages/confirmations/components/signature-request-header/signature-request-header.stories.js
  ui/pages/confirmations/components/signature-request-original/signature-request-original-warning/signature-request-original-warning.stories.js
  ui/pages/confirmations/components/signature-request-original/signature-request-original.stories.js
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe-header/signature-request-siwe-header.stories.js
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe-icon/signature-request-siwe-icon.stories.js
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe-message/signature-request-siwe-message.stories.js
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe-tag/signature-request-siwe-tag.stories.js
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe.stories.js
  ui/pages/confirmations/components/signature-request/signature-request-data/signature-request-data.stories.js
  ui/pages/confirmations/components/signature-request/signature-request-header/signature-request-header.stories.js
  ui/pages/confirmations/components/signature-request/signature-request-message/signature-request-message.stories.js
  ui/pages/confirmations/components/signature-request/signature-request.stories.js
  ui/pages/confirmations/components/transaction-alerts/transaction-alerts.stories.js
  ui/pages/confirmations/components/transaction-detail-item/transaction-detail-item.stories.js
  ui/pages/confirmations/components/transaction-detail/transaction-detail.stories.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22763 Personal sign origin
  ui/components/app/confirm/info/info.tsx
  ui/components/app/confirm/title/index.ts
  ui/pages/confirmations/components/confirm/footer/__snapshots__/footer.test.tsx.snap
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/info/index.ts
  ui/pages/confirmations/components/confirm/info/info.stories.tsx
  ui/pages/confirmations/components/confirm/info/info.test.tsx
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/components/confirm/title/index.ts
  ui/pages/confirmations/components/confirm/title/title.stories.tsx
  ui/pages/confirmations/components/confirm/title/title.test.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/confirm.tsx
  ui/selectors/confirm.ts
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#22052 Adds 'yarn master-sync' command to automatically generate a PR-ready master-sync branch
  development/master-sync.js
  package.json
Labels: team-extension-platform

#22874 fix: for realease blocker bugs
  app/scripts/controllers/app-state.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/transaction/util.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/signature-approved.spec.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22993 Master sync following v11.9.X
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#22984 Fix + Clean: "Security & Privacy" Settings Search routes
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/contact-list-tab/contact-list-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/info-tab/info-tab.component.js
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/settings-tab/settings-tab.component.js
Labels: area-settings, team-confirmations-secure-ux-PR

#22827 V11.10.0 changelog
  CHANGELOG.md
Labels: team-extension-platform, INVALID-PR-TEMPLATE, release-11.10.0

#23022 Cherry pick 2 metric PRs for Blockaid
  app/scripts/controllers/app-state.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/lib/transaction/util.ts
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  test/e2e/tests/metrics/signature-approved.spec.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request/signature-request.js
  ui/components/app/terms-of-use-popup/terms-of-use-popup.test.js
  ui/components/app/transaction-alerts/transaction-alerts.js
  ui/helpers/utils/metric.test.js
  ui/helpers/utils/metrics.js
  ui/helpers/utils/metrics.test.js
  ui/hooks/useTransactionEventFragment.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/token-allowance/token-allowance.js
Labels: team-confirmations-secure-ux-PR

#22889 fix: push the menu up if there isn't enough space at the bottom
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
Labels: team-accounts, needs-assets-ux-review

#22951 Fix #22940 - Remove inline gas components from new send flow
  ui/components/multichain/pages/send/components/content.tsx
Labels: team-wallet-ux, needs-assets-ux-review

#22877 test/e2e: allow overriding some browser settings via env vars
  .metamaskrc.dist
  test/e2e/webdriver/chrome.js
  test/e2e/webdriver/firefox.js
Labels: team-security, needs-dev-review, e2e-test

#22790 fix: handle low numbers when saving default advanced gas fees
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.test.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.test.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.test.js
  ui/store/actions.ts
Labels: team-confirmations-system

#22950 [MMI] 4564 - fix the way get custody type was being done
  app/scripts/controllers/mmi-controller.js
Labels: team-mmi

#23044 Add additional snap installation metrics
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
Labels: team-snaps, INVALID-PR-TEMPLATE

#23031 nit: Localize LavaDome copy warning
  app/_locales/en/messages.json
  ui/components/multichain/account-details/account-details-key.js
Labels: team-wallet-ux, needs-assets-ux-review

#23030 nit: useAccountTotalBalance code improvement
  ui/hooks/useAccountTotalFiatBalance.js
Labels: team-wallet-ux, needs-assets-ux-review

#23033 Fix #22987 - UX - Multichain - Send flow - Select NFTs tab in Asset Picker when an NFT is selected
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
Labels: team-wallet-ux, needs-assets-ux-review

#23052 test: fix several ppom testcases due to description change
  test/e2e/tests/ppom-blockaid-alert-erc20-approval.spec.js
  test/e2e/tests/ppom-blockaid-alert-erc20-transfer.spec.js
  test/e2e/tests/ppom-blockaid-alert-networks-support.spec.js
  test/e2e/tests/ppom-blockaid-alert.spec.js
  test/e2e/tests/ppom-blockaid-setApprovalForAll-farming.spec.js
Labels: team-confirmations-secure-ux-PR

#22998 test: Added manual test for hex data toggle and corrected the change language format
  test/scenarios/17. settings/advanced/show-hex-data.csv
  test/scenarios/17. settings/general/change-language.csv
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#22358 Hackathon project: Codespaces
  .circleci/config.yml
  .depcheckrc.yml
  .devcontainer/devcontainer.json
  .devcontainer/download-builds.ts
  .devcontainer/first-run-notice.txt
  .devcontainer/install.sh
  .devcontainer/launch-firefox.ts
  .devcontainer/setup-browsers.ts
  .github/CODEOWNERS
  .github/pull-request-template.md
  .github/workflows/codespaces.yml
  .github/workflows/fitness-functions.yml
  .gitignore
  README.md
  package.json
  test/e2e/webdriver/chrome.js
  yarn.lock
Labels: team-extension-platform

#23064 MMI skipping until we move to sepolia
  test/e2e/mmi/specs/extension.visual.spec.ts
  test/e2e/mmi/specs/transactions.spec.ts
Labels: team-mmi

#22967 Fix: settings search for Security Alerts; Feat: Add Blockaid and OpenSea "Security & privacy" settings search; Feat: Add Nicknames and Snaps "Experimental" settings search
  test/e2e/tests/settings-search.spec.js
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
Labels: area-settings, team-confirmations-secure-ux-PR

#22932 fix: Blockaid disable disclosure scrollToBottom
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
  ui/components/ui/disclosure/__snapshots__/disclosure.test.js.snap
  ui/components/ui/disclosure/disclosure.js
  ui/components/ui/disclosure/disclosure.test.js
  ui/pages/confirmations/components/security-provider-banner-alert/__snapshots__/security-provider-banner-alert.test.js.snap
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
Labels: area-settings, team-confirmations-secure-ux-PR

#22982 style:fix: Remove background behind setting icons
  ui/pages/settings/index.scss
Labels: area-settings, team-confirmations-secure-ux-PR

#23043 test: add scenario sign typed v4 with hardware wallet
  test/scenarios/13. sign/sign typed data v4 with hardware wallet.csv
  test/scenarios/2. keyring/connect hardware wallet.csv
Labels: team-confirmations-secure-ux-PR

#22994 [MMI] Adding capture exceptions to MMI controllers
  app/scripts/controllers/mmi-controller.js
  app/scripts/metamask-controller.js
  builds.yml
  package.json
  yarn.lock
Labels: team-mmi

#23004 Confirm button should be red when request is flagged as malicious on extension
  ui/components/ui/page-container/page-container-footer/page-container-footer.component.test.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container.component.js
  ui/pages/confirmations/components/signature-request-original/signature-request-original.component.js
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe.js
  ui/pages/confirmations/components/signature-request/signature-request-footer/signature-request-footer.component.js
  ui/pages/confirmations/components/signature-request/signature-request.js
  ui/pages/confirmations/token-allowance/token-allowance.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22728 fix: Capture more details of ppom errors
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/transaction/util.ts
  shared/constants/metametrics.ts
  shared/constants/security-provider.ts
  test/e2e/helpers.js
  test/e2e/tests/ppom-blockaid-alert-simple-send.spec.js
  ui/helpers/utils/metrics.js
  ui/helpers/utils/metrics.test.js
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review, INVALID-PR-TEMPLATE

#23063 test: add scenario sign typed v3 with hardware wallet
  test/scenarios/13. sign/sign typed data v3 with hardware wallet.csv
Labels: team-confirmations-secure-ux-PR

#23075 Master sync following v11.10.0
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#23059 UX: Show same balance on eth overview and account list item
  test/e2e/tests/account-token-list.spec.js
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/selectors/selectors.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23076 Fix test failure caused by previous revert - 22946
  test/e2e/tests/network/update-network.spec.ts
  ui/pages/onboarding-flow/add-network-modal/__snapshots__/add-network-modal.test.js.snap
  ui/pages/settings/networks-tab/networks-form/networks-form.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#22941 UX MULTICHAIN: added connect account in account list menu item
  app/_locales/en/messages.json
  app/images/icons/user-circle-link.svg
  test/data/mock-state.json
  ui/components/component-library/icon/icon.types.ts
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.test.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.stories.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/pages/send/send.test.js
  ui/pages/confirmations/confirmation/templates/remove-snap-account.test.js
Labels: needs-ux-ds-review, INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23082 patch: nft detection running too many times
  .yarn/patches/@metamask-assets-controllers-npm-24.0.0-dfef136464.patch
  package.json
  yarn.lock
Labels: team-assets

#23028 Fixes #23026 - UX - Multichain - Send flow - Fix tabs in popup
  ui/components/multichain/pages/send/index.scss
Labels: team-wallet-ux, needs-assets-ux-review

#23103 test: disable ppom e2e tests temporarily
  test/e2e/tests/ppom-blockaid-alert-erc20-approval.spec.js
  test/e2e/tests/ppom-blockaid-alert-erc20-transfer.spec.js
  test/e2e/tests/ppom-blockaid-alert-networks-support.spec.js
  test/e2e/tests/ppom-blockaid-alert-simple-send.spec.js
  test/e2e/tests/ppom-blockaid-alert-trade-order-farming.spec.js
  test/e2e/tests/ppom-blockaid-setApprovalForAll-farming.spec.js
  test/e2e/tests/ppom-blockaid-toggle-metrics.spec.js
  test/e2e/tests/ppom-toggle-settings.spec.js
Labels: team-confirmations-secure-ux-PR

#23101 chore: upgrading design tokens package that includes dynamic theming
  package.json
  yarn.lock
Labels: team-design-system, needs-ux-ds-review

#23102 fix: removing opacity from deprecated popover overlay
  ui/components/ui/popover/index.scss
Labels: team-design-system, needs-ux-ds-review

#22972 UX Multichain: added badge status component
  ui/components/multichain/badge-status/__snapshots__/badge-status.test.js.snap
  ui/components/multichain/badge-status/badge-status.stories.tsx
  ui/components/multichain/badge-status/badge-status.test.js
  ui/components/multichain/badge-status/badge-status.tsx
  ui/components/multichain/badge-status/badge-status.types.tsx
  ui/components/multichain/badge-status/index.scss
  ui/components/multichain/badge-status/index.ts
  ui/components/multichain/multichain-components.scss
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23001 feat: PPOM version update to fetch files only when transaction is received
  app/scripts/lib/setupSentry.js
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: team-confirmations-secure-ux-PR

#23071 Feat: add optimism arbitrum goerli deprecation warning
  shared/constants/network.ts
  test/e2e/tests/deprecated-networks.spec.js
  ui/components/ui/deprecated-networks/deprecated-networks.js
Labels: needs-ux-ds-review, needs-dev-review, team-assets, team-wallet-ux, needs-assets-ux-review

#23096 Fix #23095 - Fix long account name ellipsizing
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header.js
Labels: team-wallet-ux, needs-assets-ux-review

#23100 Fix NaN issue in Product Tour Popover
  ui/components/multichain/product-tour-popover/product-tour-popover.js
  ui/components/multichain/product-tour-popover/product-tour-popover.test.js
Labels: team-extension-ux, needs-ux-ds-review, team-wallet-ux, needs-assets-ux-review

#23126 UX: fixed badge color when no account is connected
  ui/components/multichain/connected-site-menu/__snapshots__/connected-site-menu.test.js.snap
  ui/components/multichain/connected-site-menu/connected-site-menu.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23081 Fix incorrect gas estimate mock and specs
  ui/pages/confirmations/components/confirm-gas-display/__snapshots__/confirm-gas-display.test.js.snap
  ui/pages/confirmations/components/confirm-gas-display/confirm-gas-display.test.js
  ui/pages/confirmations/components/edit-gas-fee-button/edit-gas-fee-button.test.js
  ui/pages/confirmations/components/gas-details-item/gas-details-item.test.js
  ui/pages/confirmations/components/transaction-detail/transaction-detail.component.test.js
Labels: team-extension-platform, team-wallet-api-platform, team-confirmations-system

#22683 chore(test/e2e/tests): some proofreading
  test/e2e/tests/add-multiple-tokens.spec.js
  test/e2e/tests/auto-lock.spec.js
  test/e2e/tests/dapp-tx-edit.spec.js
  test/e2e/tests/nft/erc721-interaction.spec.js
  test/e2e/tests/onboarding.spec.js
  test/e2e/webdriver/driver.js
Labels: external-contributor

#19229 ci(action): GH action to validate PR title against conventional commit standard
  .github/CONTRIBUTING.md
  .github/workflows/validate-conventional-commits.yml
Labels: team-extension-platform

#22914 Restore frame-ancestors: none
  app/manifest/v3/chrome.json
  app/scripts/app-init.js
  app/scripts/lib/offscreen-bridge/lattice-offscreen-keyring.ts
  app/scripts/lib/offscreen-bridge/ledger-offscreen-bridge.ts
  app/scripts/lib/offscreen-bridge/trezor-offscreen-bridge.ts
  development/build/scripts.js
  offscreen/lattice-iframe.html
  offscreen/ledger-iframe.html
  offscreen/offscreen.html
  offscreen/scripts/lattice-iframe.ts
  offscreen/scripts/lattice.ts
  offscreen/scripts/ledger-iframe.ts
  offscreen/scripts/ledger.ts
  offscreen/scripts/offscreen.ts
  offscreen/scripts/trezor-iframe.ts
  offscreen/scripts/trezor.ts
  offscreen/trezor-iframe.html
Labels: team-extension-platform, ready-for-dev

#23027 feat: show error if user attempts to deploy a contract with a user op
  app/_locales/en/messages.json
  ui/helpers/constants/error-keys.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.test.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
Labels: team-confirmations-system

#23092 feat: add useFirstPartyContractName hook and use it in useDisplayName
  shared/constants/first-party-contracts.ts
  ui/hooks/useDisplayName.test.ts
  ui/hooks/useDisplayName.ts
  ui/hooks/useFirstPartyContractName.test.ts
  ui/hooks/useFirstPartyContractName.ts
Labels: team-confirmations-system, QA Passed

#23139 fix: duplicate React keys in dynamic UI causing artifacts
  ui/components/app/snaps/snap-ui-renderer/components/types.ts
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/components/app/snaps/snap-ui-renderer/utils.ts
Labels: team-snaps, INVALID-PR-TEMPLATE

#23147 fix: Properly remove `setInputState` from confirmation template
  ui/pages/confirmations/confirmation/templates/index.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22949 `PreferencesController` reacts to `KeyringController` state changes
  app/scripts/controllers/detect-tokens.test.js
  app/scripts/controllers/mmi-controller.test.js
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/metamask-controller.js
Labels: team-shared-libraries

#23128 MMI - updates snapshots
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-connection-info-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-list-mmi-visual-linux.png
Labels: team-mmi

#23153 fix(Snaps): Add label prop to Snap UI input
  ui/components/app/snaps/snap-ui-renderer/components/input.ts
Labels: team-snaps, INVALID-PR-TEMPLATE

#22995 feat: deprecate goerli network
  .storybook/test-data.js
  app/_locales/en/messages.json
  app/scripts/controllers/mmi-controller.js
  app/scripts/metamask-controller.js
  app/scripts/migrations/055.test.js
  app/scripts/migrations/110.test.ts
  app/scripts/migrations/110.ts
  app/scripts/migrations/index.js
  shared/constants/network.ts
  shared/constants/swaps.ts
  test/e2e/mmi/helpers/utils.ts
  test/e2e/mmi/pageObjects/mmi-accountMenu-page.ts
  test/e2e/mmi/specs/dapp.spec.ts
  test/e2e/mmi/specs/extension.visual.spec.ts
  test/e2e/mmi/specs/transactions.spec.ts
  test/e2e/mmi/specs/visual.spec.ts
  test/e2e/mmi/specs/visual.spec.ts-snapshots/connect-custodian-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-connection-info-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-list-mmi-visual-linux.png
  test/e2e/tests/deprecated-networks.spec.js
  ui/components/multichain/network-list-item/__snapshots__/network-list-item.test.js.snap
  ui/components/multichain/network-list-item/network-list-item.js
  ui/ducks/app/app.ts
  ui/helpers/constants/zendesk-url.js
  ui/hooks/useTokensToSearch.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/pages/settings/deprecated-network-modal/DeprecatedNetworkModal.tsx
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/settings/networks-tab/networks-list-item/networks-list-item.test.js
  ui/pages/settings/networks-tab/networks-list/networks-list.test.js
  ui/pages/settings/networks-tab/networks-tab-content/networks-tab-content.test.js
  ui/pages/settings/networks-tab/networks-tab.constants.js
  ui/pages/settings/networks-tab/networks-tab.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/selectors/selectors.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: needs-ux-ds-review, needs-dev-review, team-assets, team-wallet-ux, needs-assets-ux-review

#22943 Show modal when user tries to cancel confirmed transaction
  app/_locales/en/messages.json
  ui/components/app/modals/modal.js
  ui/components/app/modals/transaction-already-confirmed/__snapshots__/transaction-already-confirmed.test.tsx.snap
  ui/components/app/modals/transaction-already-confirmed/index.ts
  ui/components/app/modals/transaction-already-confirmed/transaction-already-confirmed.test.tsx
  ui/components/app/modals/transaction-already-confirmed/transaction-already-confirmed.tsx
  ui/hooks/useModalProps.test.ts
  ui/hooks/useModalProps.ts
  ui/pages/onboarding-flow/creation-successful/creation-successful.test.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-confirmations-system, QA Passed

#23136 test: update tests with types, include tests in linting
  app/scripts/controllers/decrypt-message.test.ts
  app/scripts/lib/SnapsNameProvider.test.ts
  app/scripts/lib/notification-manager.test.ts
  app/scripts/lib/snap-keyring/metrics.test.ts
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/util.test.ts
  package.json
  tsconfig.json
  ui/components/app/configure-snap-popup/configure-snap-popup.test.tsx
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.test.tsx
  ui/components/component-library/avatar-account/avatar-account.test.tsx
  ui/components/component-library/avatar-base/avatar-base.test.tsx
  ui/components/component-library/avatar-favicon/avatar-favicon.test.tsx
  ui/components/component-library/avatar-icon/avatar-icon.test.tsx
  ui/components/component-library/box/box.test.tsx
  ui/components/component-library/button-base/button-base.test.tsx
  ui/components/component-library/button/button.test.tsx
  ui/components/component-library/checkbox/checkbox.test.tsx
  ui/components/component-library/form-text-field/form-text-field.test.tsx
  ui/components/component-library/form-text-field/form-text-field.tsx
  ui/components/component-library/input/input.test.tsx
  ui/components/component-library/modal-header/modal-header.test.tsx
  ui/components/component-library/picker-network/picker-network.test.tsx
  ui/components/component-library/popover-header/popover-header.test.tsx
  ui/components/component-library/select-wrapper/select-wrapper.test.tsx
  ui/components/component-library/tag-url/tag-url.test.tsx
  ui/components/component-library/text-field/text-field.test.tsx
  ui/components/multichain/address-list-item/address-list-item.test.tsx
  ui/components/ui/box/box.d.ts
  ui/components/ui/form-combo-field/form-combo-field.test.tsx
  ui/hooks/useDisplayName.test.ts
  ui/hooks/useFirstPartyContractName.test.ts
  ui/pages/confirmations/confirmation/util.test.ts
  ui/pages/confirmations/confirmation/util.ts
  ui/pages/confirmations/hooks/setCurrentConfirmation.test.tsx
  ui/pages/snap-account-redirect/create-snap-redirect.test.tsx
  ui/selectors/confirm.test.ts
  ui/selectors/confirm.ts
  yarn.lock
Labels: team-extension-platform, needs-dev-review

#23104 fix: download-builds improvements
  .devcontainer/download-builds.ts
Labels: team-extension-platform

#22911 test: Writing new test about metamask section links
  test/e2e/tests/settings/about-metamask/ui-validation.spec.ts
  test/env.js
  test/scenarios/17. settings/about-metamask/ui-validation.csv
  ui/components/app/modals/transaction-already-confirmed/transaction-already-confirmed.test.tsx
  ui/hooks/useModalProps.test.ts
  ui/pages/settings/info-tab/info-tab.test.tsx
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#23167 fix: hide preinstalled Snaps from the list view
  ui/selectors/selectors.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#23160 chore: update @metamask/user-operation-controller to v4
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/browserify/policy-override.json
  package.json
  yarn.lock
Labels: team-confirmations-system

#23080 MCv1 Permissions: Site Connections
  app/_locales/en/messages.json
  ui/components/multichain/avatar-group/avatar-group.stories.tsx
  ui/components/multichain/avatar-group/avatar-group.test.tsx
  ui/components/multichain/avatar-group/avatar-group.tsx
  ui/components/multichain/avatar-group/avatar-group.types.tsx
  ui/components/multichain/pages/permissions-page/__snapshots__/permissions-page.test.js.snap
  ui/components/multichain/pages/permissions-page/connection-list-item.js
  ui/components/multichain/pages/permissions-page/connection-list-item.stories.js
  ui/components/multichain/pages/permissions-page/permissions-page.js
Labels: team-extension-ux, needs-ux-ds-review, team-wallet-ux, needs-assets-ux-review

#23025 Fixes #22986 - UX - Multichain - Send flow - Show address in account …
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/account-picker/account-picker.test.js
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/account-picker.test.tsx.snap
Labels: team-wallet-ux, needs-assets-ux-review

#23024 Fix #22938 - UX - Multichain - Send Flow - Update ENS address upon network change
  ui/ducks/domains.js
  ui/ducks/send/send.js
  ui/pages/confirmations/send/send-content/add-recipient/domain-input.component.js
  ui/pages/confirmations/send/send-content/add-recipient/domain-input.container.js
Labels: team-wallet-ux, needs-assets-ux-review

#23184 fix: Update avatarType prop to be optional
  ui/components/multichain/avatar-group/avatar-group.types.tsx
Labels: team-extension-ux, needs-ux-ds-review, team-wallet-ux, needs-assets-ux-review

#23006 UX: added badge status in account list
  app/_locales/en/messages.json
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/account-list-menu.test.js
  ui/components/multichain/badge-status/__snapshots__/badge-status.test.js.snap
  ui/components/multichain/badge-status/badge-status.tsx
  ui/components/multichain/badge-status/index.scss
  ui/components/multichain/connected-status/connected-status.tsx
  ui/components/multichain/connected-status/index.ts
  ui/components/multichain/index.js
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/components/multichain/pages/send/components/account-picker.test.tsx
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#22918 Support updated Linea gas fee estimation
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/ducks/metamask/metamask.js
  ui/ducks/metamask/metamask.test.js
  yarn.lock
Labels: team-confirmations-system, QA Passed

#23169 fix: suggested symbol is duplicated
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/settings/networks-tab/networks-form/networks-form.test.js
Labels: team-extension-ux, team-assets, team-wallet-ux

#23200 fix: cherry-pick bug fix to RC
  ui/components/app/permission-page-container/permission-page-container.component.js
Labels: INVALID-PR-TEMPLATE

#23070 UX Multichain: Added connections page
  app/_locales/en/messages.json
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/pages/connections/components/__snapshots__/no-connections.test.tsx.snap
  ui/components/multichain/pages/connections/components/no-connection.tsx
  ui/components/multichain/pages/connections/components/no-connections.test.tsx
  ui/components/multichain/pages/connections/connections.js
  ui/components/multichain/pages/connections/connections.tsx
  ui/components/multichain/pages/connections/index.scss
  ui/components/multichain/pages/index.scss
  ui/pages/routes/routes.component.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23195 fix: PPOM - Report False Positives - missing Chain Name
  shared/constants/network.test.ts
  shared/constants/network.ts
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#23196 Version v11.10.1
  CHANGELOG.md
  app/images/velas.svg
  app/scripts/migrations/105.test.ts
  app/scripts/migrations/105.ts
  package.json
  shared/constants/network.test.ts
  shared/constants/network.ts
  test/e2e/tests/ppom-blockaid-alert-erc20-approval.spec.js
  test/e2e/tests/ppom-blockaid-alert-erc20-transfer.spec.js
  test/e2e/tests/ppom-blockaid-alert-simple-send.spec.js
  test/e2e/tests/ppom-blockaid-alert-trade-order-farming.spec.js
  test/e2e/tests/ppom-blockaid-alert.spec.js
  test/e2e/tests/ppom-blockaid-setApprovalForAll-farming.spec.js
  test/e2e/tests/ppom-blockaid-toggle-metrics.spec.js
  test/e2e/tests/ppom-toggle-settings.spec.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE, release-11.10.1
