Repository MetaMask/metamask-extension, pull requests merged in 2024-12, with the labels that each got.

#28822 fix: fix asset-list e2e test
  test/e2e/fixture-builder.js
  test/e2e/tests/multichain/asset-list.spec.ts
Labels: team-assets

#28804 chore: accept regex expression for rerun-from-failed trigger from circle ci UI, so we can add multiple triggers following the name convention
  .circleci/config.yml
Labels: team-extension-platform, area-qa

#28821 chore: Rename `develop` to `main`
  .circleci/config.yml
  .circleci/scripts/bundle-stats-commit.sh
  .circleci/scripts/check_mmi_trigger.sh
  .circleci/scripts/git-diff-develop.ts
  .circleci/scripts/rerun-ci-workflow-from-failed.ts
  .devcontainer/download-builds.ts
  .github/CONTRIBUTING.md
  .github/guidelines/LABELING_GUIDELINES.md
  .github/pull-request-template.md
  .github/scripts/check-pr-has-required-labels.ts
  .github/scripts/check-template-and-add-labels.ts
  .github/workflows/add-mmi-reviewer-and-notify.yml
  .github/workflows/add-release-label.yml
  .github/workflows/check-pr-labels.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/codespaces.yml
  .github/workflows/crowdin-action.yml
  .github/workflows/main.yml
  .github/workflows/security-code-scanner.yml
  .github/workflows/update-coverage.yml
  .github/workflows/validate-conventional-commits.yml
  README.md
  app/scripts/lib/setupSentry.js
  development/build/README.md
  development/build/utils.js
  development/fitness-functions/rules/index.ts
  development/highlights/index.js
  development/master-sync.js
  docs/QA_MIGRATIONS_GUIDE.md
  docs/confirmation-refactoring/confirmation-backend-architecture/README.md
  docs/confirmation-refactoring/confirmation-page-structure/README.md
  docs/confirmation-refactoring/confirmation-pages-routing/README.md
  docs/confirmation-refactoring/confirmation-state-management/README.md
  docs/confirmation-refactoring/signature-request/README.md
  docs/publishing.md
  test/e2e/flask/README.md
  test/manual-scenarios/upgrade-testing/upgrade-testing.md
  ui/components/ui/box/README.mdx
  ui/hooks/useTransactionInsights.js
Labels: team-wallet-framework, team-extension-platform

#28841 fix: fix asset-list e2e test (#28822)
  test/e2e/fixture-builder.js
  test/e2e/tests/multichain/asset-list.spec.ts
Labels: team-assets, needs-assets-ux-review

#28645 fix: Replace `AvatarAccount` with `Identicon`
  ui/components/app/confirm/info/row/__snapshots__/address.test.tsx.snap
  ui/components/app/confirm/info/row/address.tsx
  ui/pages/confirmations/components/confirm/header/header-info.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/base-transaction-info/__snapshots__/base-transaction-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/__snapshots__/personal-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/__snapshots__/set-approval-for-all-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/__snapshots__/transaction-data.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/__snapshots__/transaction-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-details-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/transaction-flow-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/__snapshots__/dataTree.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data/__snapshots__/typedSignData.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: team-confirmations

#28689 chore: Reduce MMI trigger machine size
  .circleci/config.yml
Labels: team-wallet-framework, team-extension-platform, team-mmi

#28810 fix: optimize helper methods for signature e2e
  test/e2e/tests/confirmations/helpers.ts
  test/e2e/tests/confirmations/signatures/nft-permit.spec.ts
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  test/e2e/tests/confirmations/signatures/siwe.spec.ts
Labels: team-confirmations

#28744 test: Allow token balance to populate after swap
  test/e2e/playwright/shared/pageObjects/wallet-page.ts
  test/e2e/playwright/swap/specs/swap.spec.ts
Labels: team-swaps, QA Passed

#28692 chore: Changelog v12.8.0
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#28578 fix(cherry-pick): use PORTFOLIO_VIEW flag to determine chain polling
  ui/hooks/useTokenDetectionPolling.ts
  ui/hooks/useTokenRatesPolling.ts
Labels: release-blocker, team-assets, INVALID-PR-TEMPLATE

#28657 feat: cross chain swaps - tx status - UI
  .storybook/test-data.js
  app/_locales/en/messages.json
  app/images/hollow-circle.svg
  shared/types/bridge-status.ts
  test/jest/mock-store.js
  ui/components/app/selected-account/selected-account-component.test.js
  ui/components/app/transaction-breakdown/transaction-breakdown-utils.ts
  ui/components/app/transaction-breakdown/transaction-breakdown.container.js
  ui/components/app/transaction-icon/transaction-icon.js
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/multichain/activity-list-item/__snapshots__/activity-list-item.test.js.snap
  ui/components/multichain/activity-list-item/activity-list-item.js
  ui/ducks/bridge-status/actions.ts
  ui/ducks/bridge-status/selectors.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/selectors.test.ts
  ui/helpers/constants/routes.ts
  ui/hooks/bridge/useBridgeChainInfo.ts
  ui/hooks/bridge/useBridgeTxHistoryData.ts
  ui/hooks/bridge/useCountdownTimer.test.ts
  ui/hooks/useTransactionDisplayData.js
  ui/pages/bridge/hooks/useAddToken.ts
  ui/pages/bridge/hooks/useHandleApprovalTx.ts
  ui/pages/bridge/hooks/useHandleBridgeTx.ts
  ui/pages/bridge/hooks/useHandleTx.ts
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.test.tsx
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  ui/pages/bridge/index.scss
  ui/pages/bridge/index.test.tsx
  ui/pages/bridge/prepare/bridge-cta-button.test.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.test.tsx
  ui/pages/bridge/quotes/bridge-quote-card.test.tsx
  ui/pages/bridge/quotes/bridge-quotes-modal.test.tsx
  ui/pages/bridge/transaction-details/bridge-activity-item-tx-segments.tsx
  ui/pages/bridge/transaction-details/bridge-explorer-links.tsx
  ui/pages/bridge/transaction-details/bridge-step-description.tsx
  ui/pages/bridge/transaction-details/bridge-step-list.stories.tsx
  ui/pages/bridge/transaction-details/bridge-step-list.tsx
  ui/pages/bridge/transaction-details/hollow-circle.tsx
  ui/pages/bridge/transaction-details/index.scss
  ui/pages/bridge/transaction-details/pulsing-circle.tsx
  ui/pages/bridge/transaction-details/segment.stories.tsx
  ui/pages/bridge/transaction-details/segment.tsx
  ui/pages/bridge/transaction-details/step-progress-bar-item.tsx
  ui/pages/bridge/transaction-details/transaction-detail-row.tsx
  ui/pages/bridge/transaction-details/transaction-details.tsx
  ui/pages/create-account/connect-hardware/index.test.tsx
  ui/pages/routes/routes.component.js
Labels: team-bridge, team-swaps

#28779 ci: pin image versions used in CI so it remains deterministic
  .circleci/config.yml
Labels: team-extension-platform

#28585 fix(cherry-pick): use PORTFOLIO_VIEW flag to determine token list polling
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/hooks/useTokenListPolling.test.ts
  ui/hooks/useTokenListPolling.ts
Labels: release-blocker, team-assets, INVALID-PR-TEMPLATE

#28844 chore: cleanup on some names and scripts in ci
  .circleci/config.yml
  .circleci/scripts/git-diff-default-branch.ts
  .circleci/scripts/rerun-ci-workflow-from-failed.ts
  package.json
Labels: team-extension-platform

#28797 test: [POM] improve homepage class implementation
  test/e2e/page-objects/flows/login.flow.ts
  test/e2e/page-objects/flows/send-transaction.flow.ts
  test/e2e/page-objects/flows/transaction.ts
  test/e2e/page-objects/pages/asset-list.ts
  test/e2e/page-objects/pages/home/activity-list.ts
  test/e2e/page-objects/pages/home/asset-list.ts
  test/e2e/page-objects/pages/home/homepage.ts
  test/e2e/page-objects/pages/home/nft-list.ts
  test/e2e/page-objects/pages/homepage.ts
  test/e2e/tests/account/add-account.spec.ts
  test/e2e/tests/account/forgot-password.spec.ts
  test/e2e/tests/account/import-flow.spec.ts
  test/e2e/tests/account/lock-account.spec.ts
  test/e2e/tests/account/migrate-old-vault.spec.ts
  test/e2e/tests/account/snap-account-contract-interaction.spec.ts
  test/e2e/tests/account/snap-account-transfers.spec.ts
  test/e2e/tests/confirmations/transactions/erc20-token-send-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/native-send-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/nft-token-send-redesign.spec.ts
  test/e2e/tests/multichain/aggregated-balances.spec.ts
  test/e2e/tests/multichain/asset-list.spec.ts
  test/e2e/tests/network/multi-rpc.spec.ts
  test/e2e/tests/network/switch-network.spec.ts
  test/e2e/tests/notifications/account-syncing/importing-private-key-account.spec.ts
  test/e2e/tests/notifications/account-syncing/new-user-sync.spec.ts
  test/e2e/tests/notifications/account-syncing/onboarding-with-opt-out.spec.ts
  test/e2e/tests/notifications/account-syncing/sync-after-adding-account.spec.ts
  test/e2e/tests/notifications/account-syncing/sync-after-modifying-account-name.spec.ts
  test/e2e/tests/notifications/account-syncing/sync-after-onboarding.spec.ts
  test/e2e/tests/notifications/account-syncing/sync-with-account-balances.spec.ts
  test/e2e/tests/onboarding/onboarding.spec.ts
  test/e2e/tests/privacy/account-tracker-api-usage.spec.ts
  test/e2e/tests/privacy/onboarding-infura-call-privacy.spec.ts
  test/e2e/tests/privacy/onboarding-token-price-call-privacy.spec.ts
  test/e2e/tests/privacy/polling.spec.ts
  test/e2e/tests/settings/change-language.spec.ts
  test/e2e/tests/settings/settings-security-reveal-srp.spec.ts
  test/e2e/tests/tokens/add-hide-token.spec.ts
  test/e2e/tests/tokens/add-token-using-search.ts
  test/e2e/tests/tokens/nft/auto-detect-nft.spec.ts
  test/e2e/tests/tokens/nft/import-nft.spec.ts
  test/e2e/tests/tokens/watch-asset-call-add-token.ts
  test/e2e/tests/transaction/ens.spec.ts
  test/e2e/tests/transaction/simple-send.spec.ts
  test/e2e/tests/transaction/stuck-approved-transaction.spec.ts
  test/e2e/vault-decryption-chrome.spec.ts
Labels: team-extension-platform, skip-e2e-quality-gate

#28684 feat(27256): implement remote feature flag feature
  app/scripts/background.js
  app/scripts/constants/sentry-state.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  test/e2e/fixture-builder.js
  test/e2e/mock-e2e.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/remote-feature-flag/mock-data.ts
  test/e2e/tests/remote-feature-flag/remote-feature-flag.spec.ts
  ui/pages/settings/info-tab/info-tab.component.js
  ui/pages/settings/info-tab/info-tab.stories.js
  ui/pages/settings/info-tab/info-tab.test.tsx
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
  ui/pages/settings/settings.stories.js
  ui/pages/settings/settings.test.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  yarn.lock
Labels: team-extension-platform

#28874 fix: check if a user is signed in before attempting to sign them out
  ui/hooks/metamask-notifications/useMetametrics.ts
Labels: team-identity

#28897 fix: updated analytics preferences to be logged during onboarding
  ui/pages/onboarding-flow/metametrics/metametrics.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#28921 fix: decoding data display for ERC-1155 tokens
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx
Labels: team-confirmations

#28924 cherry-pick: Fix decoding data display for ERC-1155 tokens
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx
Labels: team-confirmations, release-12.9.0

#28934 chore: Update a mock for tests
  test/e2e/tests/smart-transactions/mock-requests-for-swap-test.ts
Labels: team-transactions

#28937 replace snaps eth_accounts references
  shared/constants/snaps/permissions.ts
  ui/helpers/utils/permission.js
Labels: team-wallet-api-platform

#28855 Jl/caip25 permission migration/fix locked wallet behavior
  app/scripts/lib/rpc-method-middleware/handlers/eth-accounts.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/eth-accounts.ts
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-getPermissions.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-getPermissions.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-requestPermissions.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-requestPermissions.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  test/e2e/fixture-builder.js
  test/e2e/json-rpc/eth_accounts.spec.ts
  test/e2e/tests/tokens/increase-token-allowance.spec.js
Labels: team-wallet-api-platform

#28926 chore: force `@solana/web3.js` version resolution
  .yarnrc.yml
  package.json
  yarn.lock
Labels: team-wallet-framework

#28901 chore: change ownership of profile sync from notifications to identity
  .github/CODEOWNERS
  ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
  ui/components/app/modals/confirm-turn-off-profile-syncing/confirm-turn-off-profile-syncing.test.tsx
  ui/components/app/modals/turn-on-metamask-notifications/turn-on-metamask-notifications.tsx
  ui/components/multichain/global-menu/global-menu.js
  ui/contexts/metamask-notifications/metamask-notifications.tsx
  ui/hooks/identity/useCreateSession.test.ts
  ui/hooks/identity/useCreateSession.ts
  ui/hooks/identity/useMetametrics.test.tsx
  ui/hooks/identity/useMetametrics.ts
  ui/hooks/identity/useProfileSyncing/accountSyncing.test.tsx
  ui/hooks/identity/useProfileSyncing/accountSyncing.ts
  ui/hooks/identity/useProfileSyncing/index.ts
  ui/hooks/identity/useProfileSyncing/profileSyncing.test.tsx
  ui/hooks/identity/useProfileSyncing/profileSyncing.ts
  ui/hooks/metamask-notifications/useNotifications.test.tsx
  ui/pages/notifications-settings/notifications-settings-allow-notifications.tsx
  ui/pages/onboarding-flow/creation-successful/creation-successful.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/developer-options-tab/profile-sync.tsx
  ui/pages/settings/security-tab/metametrics-toggle/metametrics-toggle.test.tsx
  ui/pages/settings/security-tab/metametrics-toggle/metametrics-toggle.tsx
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.test.tsx
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.tsx
  ui/selectors/identity/authentication.test.ts
  ui/selectors/identity/authentication.ts
  ui/selectors/identity/profile-syncing.test.ts
  ui/selectors/identity/profile-syncing.ts
Labels: team-identity

#28784 feat: migrate `AppStateController` to inherit from BaseController V2
  app/scripts/background.js
  app/scripts/controllers/app-state-controller.test.ts
  app/scripts/controllers/app-state-controller.ts
  app/scripts/controllers/metametrics-controller.ts
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  app/scripts/metamask-controller.js
Labels: team-wallet-framework

#28905 chore: update controllers as of core release v244
  .yarn/patches/@metamask-network-controller-npm-21.0.0-559aa8e395.patch
  .yarn/patches/@metamask-network-controller-npm-22.1.0-621c281f70.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-wallet-framework

#28918 feat: Adding production URL for signature decoding
  builds.yml
  privacy-snapshot.json
  test/e2e/tests/confirmations/helpers.ts
Labels: team-confirmations

#28943 chore: Skip flaky smart-transactions.spec.ts until we determine the root cau…
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
Labels: team-extension-platform

#28870 fix: fix check for undefined marketData
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/hooks/useTokenFiatAmount.js
Labels: release-blocker, team-assets, release-12.9.0

#28913 test: Fixed e2e swap tests test failures
  test/e2e/playwright/shared/pageObjects/network-controller-page.ts
  test/e2e/playwright/shared/pageObjects/wallet-page.ts
  test/e2e/playwright/swap/specs/swap.spec.ts
Labels: team-swaps, QA Passed

#28616 test: Add integration test for signing and submitting alert and fix b…
  test/integration/confirmations/transactions/alerts.test.tsx
Labels: team-confirmations

#28923 test: fix flaky ppom test
  test/e2e/tests/ppom/ppom-blockaid-alert-trade-order-farming.spec.js
Labels: team-confirmations

#28773 fix: Capture raw 4byte hex
  app/scripts/lib/transaction/metrics.ts
Labels: team-confirmations

#28919 feat: Add 'transaction_internal_id' property on all transaction events
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
Labels: team-confirmations

#28922 chore: Bump Snaps packages
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-metrics.spec.js
  ui/components/app/snaps/snap-ui-renderer/components/text.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#28930 fix: updated analytics preferences to be logged during onboarding (cherrypick-28897)
  ui/pages/onboarding-flow/metametrics/metametrics.js
Labels: Sev1-high, team-wallet-ux, release-12.9.0

#28933 chore: adds ramp-dev-team to codeowners
  .github/CODEOWNERS
Labels: team-ramp

#28780 feat: Migrate remaining e2e tests to redesigned confirmations
  test/e2e/json-rpc/eth_sendTransaction.spec.js
  test/e2e/page-objects/flows/send-transaction.flow.ts
  test/e2e/page-objects/pages/confirmations/redesign/confirmation.ts
  test/e2e/tests/account/add-account.spec.ts
  test/e2e/tests/petnames/petnames-helpers.js
  test/e2e/tests/petnames/petnames-transactions.spec.js
  test/e2e/tests/ppom/ppom-blockaid-alert-simple-send.spec.js
  test/e2e/tests/responsive-ui/metamask-responsive-ui.spec.js
  test/e2e/tests/tokens/custom-token-send-transfer.spec.js
  test/e2e/tests/tokens/nft/erc721-interaction.spec.js
  test/e2e/tests/transaction/change-assets.spec.js
  test/e2e/tests/transaction/edit-gas-fee.spec.js
  test/e2e/tests/transaction/gas-estimates.spec.js
  test/e2e/tests/transaction/multiple-transactions.spec.js
  test/e2e/tests/transaction/navigate-transactions.spec.js
  test/e2e/tests/transaction/send-edit.spec.js
  test/e2e/tests/transaction/send-eth.spec.js
  test/e2e/tests/transaction/send-hex-address.spec.js
  ui/pages/confirmations/components/confirm/info/hooks/use-token-values.ts
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/transaction-flow-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/transaction-flow-section.tsx
  ui/pages/confirmations/components/confirm/nav/__snapshots__/nav.test.tsx.snap
  ui/pages/confirmations/components/confirm/nav/nav.tsx
Labels: team-confirmations, skip-e2e-quality-gate

#28898 fix: sanitizes the token marketplace URL
  ui/hooks/ramps/useRamps/useRamps.test.tsx
  ui/hooks/ramps/useRamps/useRamps.ts
Labels: team-ramp

#28951 cherry-pick: Adding production URL for signature decoding
  builds.yml
  privacy-snapshot.json
  test/e2e/tests/confirmations/helpers.ts
Labels: team-confirmations, release-12.9.0

#28965 chore: cherry pick merge of #28898
  ui/hooks/ramps/useRamps/useRamps.test.tsx
  ui/hooks/ramps/useRamps/useRamps.ts
Labels: team-ramp

#28941 chore: Update CODEOWNERS to remove ownership from most
  .github/CODEOWNERS
Labels: team-wallet-framework, team-extension-platform

#28460 feat: cross chain swap STX
  .gitignore
  app/_locales/en/messages.json
  app/scripts/controllers/bridge-status/__snapshots__/bridge-status-controller.test.ts.snap
  app/scripts/controllers/bridge-status/bridge-status-controller.test.ts
  app/scripts/controllers/bridge-status/bridge-status-controller.ts
  app/scripts/controllers/bridge-status/mocks.ts
  app/scripts/controllers/bridge-status/types.ts
  app/scripts/controllers/bridge-status/utils.ts
  app/scripts/lib/transaction/smart-transactions-mocks.ts
  app/scripts/lib/transaction/smart-transactions.ts
  app/scripts/metamask-controller.js
  shared/types/bridge-status.ts
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
  ui/helpers/utils/token-util.js
  ui/hooks/bridge/useBridgeChainInfo.ts
  ui/hooks/bridge/useBridgeTxHistoryData.ts
  ui/hooks/useTransactionDisplayData.js
  ui/pages/bridge/hooks/useHandleApprovalTx.ts
  ui/pages/bridge/hooks/useHandleBridgeTx.ts
  ui/pages/bridge/hooks/useHandleTx.ts
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.test.tsx
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  ui/pages/bridge/prepare/bridge-cta-button.tsx
  ui/pages/bridge/transaction-details/bridge-activity-item-tx-segments.tsx
  ui/pages/bridge/transaction-details/bridge-explorer-links.tsx
  ui/pages/bridge/transaction-details/bridge-step-description.tsx
  ui/pages/bridge/transaction-details/bridge-step-list.tsx
  ui/pages/bridge/transaction-details/step-progress-bar-item.tsx
  ui/pages/bridge/transaction-details/transaction-details.tsx
  ui/pages/routes/routes.component.js
  ui/store/actions.ts
Labels: team-bridge, team-swaps

#28960 chore: bump `@metamask/preferences-controller` to `15.0.1`
  package.json
  yarn.lock
Labels: team-wallet-framework

#28111 fix: remove extension from webpack config import
  development/webpack/build.ts
Labels: team-extension-platform, webpack

#28958 chore: bump `@metamask/ppom-validator` to `0.36.0`
  .yarn/patches/@metamask-ppom-validator-npm-0.32.0-f677deea54.patch
  package.json
  yarn.lock
Labels: team-wallet-framework, INVALID-PR-TEMPLATE

#28915 chore: bump `@metamask/account-watcher` to `^4.2.2`
  package.json
  yarn.lock
Labels: team-accounts

#28775 test: fix flaky erc20 send token e2e
  test/e2e/tests/confirmations/transactions/erc20-token-send-redesign.spec.ts
Labels: team-confirmations

#28974 feat: migrate base mainnet rpc to infura
  app/scripts/migrations/135.test.ts
  app/scripts/migrations/135.ts
  app/scripts/migrations/index.js
  shared/constants/network.test.ts
  shared/constants/network.ts
Labels: team-assets

#28970 fix: Fix create metric fragment
  app/scripts/controllers/metametrics-controller.test.ts
  app/scripts/controllers/metametrics-controller.ts
Labels: team-wallet-framework, team-extension-platform

#27778 feat: add B3 logo svg
  app/images/b3.svg
  shared/constants/network.ts
Labels: external-contributor

#28979 chore: Renumber migration 135 to 131.1
  app/scripts/migrations/131.1.test.ts
  app/scripts/migrations/131.1.ts
  app/scripts/migrations/index.js
Labels: team-extension-platform

#28981 Cherry pick 4fc45f0bf4 to v12.8.1
  CHANGELOG.md
  app/scripts/migrations/131.1.test.ts
  app/scripts/migrations/131.1.ts
  app/scripts/migrations/index.js
  shared/constants/network.test.ts
  shared/constants/network.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#28982 Cherry pick aa2823f9 to v12.8.1
  app/scripts/controllers/metametrics-controller.test.ts
  app/scripts/controllers/metametrics-controller.ts
Labels: team-extension-platform

#28936 fix: Add origin row to transfer confirmations
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.tsx
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/native-transfer/native-transfer.tsx
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/nft-token-transfer.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-details-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/token-details-section.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/token-transfer.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
Labels: team-confirmations

#28988 chore: Update signature controller
  package.json
  yarn.lock
Labels: team-confirmations

#28989 fix: cherry-pick: Add origin row to transfer confirmations
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.tsx
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/native-transfer/native-transfer.tsx
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/nft-token-transfer.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-details-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/token-details-section.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/token-transfer.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
Labels: team-confirmations

#28990 fix: hide first time interaction alert if internal account
  ui/pages/confirmations/hooks/alerts/transactions/useFirstTimeInteractionAlert.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useFirstTimeInteractionAlert.ts
Labels: QA Passed, team-confirmations

#28998 fix (cherry-pick): hide first time interaction alert if internal account (#28990)
  ui/pages/confirmations/hooks/alerts/transactions/useFirstTimeInteractionAlert.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useFirstTimeInteractionAlert.ts
Labels: team-confirmations

#29001 Jl/caip multichain/filter unsupported methods notifications
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.ts
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#28992 cherry-pick: Update signature controller
  package.json
  yarn.lock
Labels: team-confirmations, release-12.9.0

#28858 chore: Merge master as of v12.8.0 into v12.9.0
  CHANGELOG.md
  attribution.txt
  package.json
  yarn.lock
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#28869 fix: Support decimal point on advanced gas modal on mac
  ui/components/app/modals/customize-nonce/customize-nonce.component.js
  ui/components/ui/numeric-input/numeric-input.component.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js
  ui/pages/confirmations/components/edit-gas-display/edit-gas-display.component.js
  ui/pages/confirmations/hooks/useGasFeeErrors.js
Labels: team-confirmations

#28877 feat: bump @metamask/message-signing-snap to ^0.6.0
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-identity

#28726 fix: add source when local PPOM fails
  app/scripts/lib/ppom/ppom-util.test.ts
  app/scripts/lib/ppom/ppom-util.ts
Labels: team-confirmations

#28984 fix: only display `Signing in with` for SIWE
  app/_locales/en/messages.json
  ui/components/app/confirm/info/row/alert-row/alert-row.test.tsx
  ui/components/app/confirm/info/row/alert-row/alert-row.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/base-transaction-info/__snapshots__/base-transaction-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/__snapshots__/personal-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/__snapshots__/set-approval-for-all-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/sign-in-with-row/sign-in-with-row.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/sign-in-with-row/sign-in-with-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/__snapshots__/transaction-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: team-confirmations

#29011 chore: Branch off of "New Crowdin translations by Github Action"
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
Labels: team-extension-platform, release-12.10.0

#29022 feat: various profile syncing improvements
  ui/contexts/identity/index.tsx
  ui/contexts/metamask-notifications/metamask-notifications.tsx
  ui/hooks/identity/useCreateSession.ts
  ui/hooks/identity/useProfileSyncing/accountSyncing.test.tsx
  ui/hooks/identity/useProfileSyncing/accountSyncing.ts
  ui/hooks/identity/useProfileSyncing/index.ts
  ui/hooks/identity/useProfileSyncing/profileSyncing.test.tsx
  ui/hooks/identity/useProfileSyncing/profileSyncing.ts
  ui/hooks/metamask-notifications/useNotifications.test.tsx
  ui/pages/index.js
  ui/pages/settings/developer-options-tab/profile-sync.test.tsx
  ui/pages/settings/developer-options-tab/profile-sync.tsx
Labels: team-identity

#28570 chore: eliminate direct `cross-spawn` dependency
  attribution.txt
  development/build/task.js
  development/lib/run-command.js
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: needs-dev-review, team-tiger

#29000 fix: wiping txHistory on both source and dest chains
  app/scripts/controllers/bridge-status/bridge-status-controller.ts
Labels: team-bridge, team-swaps

#28902 chore: hide cancel button if bridge tx
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/app/transaction-list/index.scss
Labels: team-bridge, team-swaps

#28849 feat: show banner for delayed bridge tx
  app/_locales/en/messages.json
  shared/types/bridge-status.ts
  ui/pages/bridge/transaction-details/transaction-details.test.tsx
  ui/pages/bridge/transaction-details/transaction-details.tsx
Labels: team-bridge, team-swaps

#29025 fix (cherry-pick): only display Signing in with for SIWE #28984
  app/_locales/en/messages.json
  ui/components/app/confirm/info/row/alert-row/alert-row.test.tsx
  ui/components/app/confirm/info/row/alert-row/alert-row.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/base-transaction-info/__snapshots__/base-transaction-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/__snapshots__/personal-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/__snapshots__/set-approval-for-all-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/sign-in-with-row/sign-in-with-row.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/sign-in-with-row/sign-in-with-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/__snapshots__/transaction-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: team-confirmations, release-12.9.0

#29036 Merge master v12.8.1 to v12.9.0
  CHANGELOG.md
  app/scripts/controllers/metametrics-controller.test.ts
  app/scripts/controllers/metametrics-controller.ts
  app/scripts/migrations/131.1.test.ts
  app/scripts/migrations/131.1.ts
  app/scripts/migrations/index.js
  attribution.txt
  shared/constants/network.test.ts
  shared/constants/network.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#29039 chore: Skip flaky smart-transactions.spec.ts until we determine the r…
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#29017 fix: Copy change on NFT approve confirmation title
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/tests/confirmations/transactions/erc721-approve-redesign.spec.ts
  test/integration/confirmations/transactions/erc721-approve.test.tsx
  ui/pages/confirmations/components/confirm/title/title.test.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
Labels: team-confirmations

#28597 feat: upgrade transaction controller to get incoming transactions using accounts API
  app/scripts/metamask-controller.js
  package.json
  test/e2e/fixture-builder.js
  test/e2e/page-objects/pages/home/activity-list.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/transaction/incoming-transactions.spec.ts
  ui/pages/bridge/hooks/useHandleBridgeTx.ts
  yarn.lock
Labels: team-confirmations

#29027 feat: Add new gas_fee_selected property on Transaction * events
  app/scripts/lib/transaction/metrics.ts
Labels: team-confirmations

#29050 test: fix flaky send eth transaction test
  test/e2e/tests/transaction/send-eth.spec.js
Labels: team-confirmations

#28939 fix: cross chain swap tx order
  ui/pages/bridge/hooks/useHandleTx.ts
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.test.tsx
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
Labels: team-bridge, team-swaps

#28983 refactor: decouple extension config from bridge API feature flags
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/bridge/bridge-controller.test.ts
  app/scripts/controllers/bridge/constants.ts
  app/scripts/controllers/bridge/types.ts
  shared/types/bridge.ts
  test/e2e/default-fixture.js
  test/e2e/fixture-builder.js
  test/e2e/tests/bridge/bridge-button-routing.spec.ts
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/bridge/constants.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/integration/data/onboarding-completion-route.json
  test/jest/mock-store.js
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
  ui/hooks/bridge/useBridging.test.ts
  ui/pages/bridge/bridge.util.test.ts
  ui/pages/bridge/bridge.util.ts
  ui/pages/bridge/index.test.tsx
  ui/pages/bridge/prepare/bridge-cta-button.test.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.test.tsx
  ui/pages/bridge/quotes/bridge-quote-card.test.tsx
  ui/pages/bridge/types.ts
  ui/pages/bridge/utils/validators.ts
  ui/selectors/selectors.js
Labels: team-swaps, e2e-test

#28899 fix: incorrect cross chain swaps activity item values
  shared/types/bridge-status.ts
  ui/hooks/bridge/useBridgeTxHistoryData.ts
  ui/hooks/useTransactionDisplayData.js
  ui/pages/bridge/hooks/useBridgeTokenDisplayData.ts
  ui/pages/bridge/transaction-details/bridge-activity-item-tx-segments.tsx
  ui/pages/bridge/types.ts
Labels: team-bridge, team-swaps

#29061 fix: fix sticky autodetection banner
  ui/components/app/detected-token/detected-token-ignored-popover/__snapshots__/detected-token-ignored-popover.test.tsx.snap
  ui/components/app/detected-token/detected-token-ignored-popover/detected-token-ignored-popover.js
  ui/components/app/detected-token/detected-token-ignored-popover/detected-token-ignored-popover.test.tsx
  ui/components/app/detected-token/detected-token.js
Labels: team-assets, regression-prod-*

#28713 chore: emit cross-chain swaps metrics + validation error logic
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/bridge/bridge-controller.test.ts
  app/scripts/controllers/bridge/bridge-controller.ts
  app/scripts/controllers/bridge/constants.ts
  app/scripts/controllers/bridge/types.ts
  shared/constants/bridge.ts
  shared/constants/metametrics.ts
  test/e2e/tests/metrics/errors.spec.js
  test/jest/mock-store.js
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/bridge.ts
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
  ui/ducks/bridge/utils.ts
  ui/helpers/constants/routes.ts
  ui/hooks/bridge/events/types.ts
  ui/hooks/bridge/events/useConvertedUsdAmounts.ts
  ui/hooks/bridge/events/useQuoteProperties.ts
  ui/hooks/bridge/events/useRequestMetadataProperties.ts
  ui/hooks/bridge/events/useRequestProperties.ts
  ui/hooks/bridge/events/useTradeProperties.ts
  ui/hooks/bridge/useBridgeExchangeRates.ts
  ui/hooks/bridge/useBridging.ts
  ui/hooks/bridge/useCrossChainSwapsEventTracker.ts
  ui/hooks/bridge/useIsTxSubmittable.ts
  ui/hooks/bridge/useLatestBalance.ts
  ui/hooks/bridge/useQuoteFetchEvents.ts
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/__snapshots__/prepare-bridge-page.test.tsx.snap
  ui/pages/bridge/prepare/bridge-cta-button.tsx
  ui/pages/bridge/prepare/bridge-input-group.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.test.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/quotes/bridge-quote-card.tsx
  ui/pages/bridge/quotes/bridge-quotes-modal.tsx
  ui/pages/bridge/types.ts
  ui/pages/bridge/utils/quote.test.ts
  ui/pages/bridge/utils/quote.ts
  ui/selectors/selectors.js
Labels: team-bridge

#29068 refactor: Init getTokenNetworkFilter selector
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js
  ui/components/app/detected-token/detected-token.js
  ui/components/multichain/detected-token-banner/detected-token-banner.js
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/selectors/selectors.js
Labels: team-assets, portfolio-view

#29058 fix: Token list should respect hidezerobalance setting
  ui/components/app/assets/token-list/token-list.tsx
Labels: team-assets, portfolio-view, regression-RC-12.9

#29078 fix: [cherry-pick] fix sticky autodetection banner (#29061)
  ui/components/app/detected-token/detected-token-ignored-popover/__snapshots__/detected-token-ignored-popover.test.tsx.snap
  ui/components/app/detected-token/detected-token-ignored-popover/detected-token-ignored-popover.js
  ui/components/app/detected-token/detected-token-ignored-popover/detected-token-ignored-popover.test.tsx
  ui/components/app/detected-token/detected-token.js
Labels: team-assets, portfolio-view

#29080 refactor: [cherry-pick] Init getTokenNetworkFilter selector (#29068)
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js
  ui/components/app/detected-token/detected-token.js
  ui/components/multichain/detected-token-banner/detected-token-banner.js
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/selectors/selectors.js
Labels: team-assets

#29071 feat: only poll popular networks
  app/_locales/en/messages.json
  shared/constants/network.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/pages/asset/components/asset-page.tsx
  ui/selectors/selectors.js
Labels: team-assets, portfolio-view

#29028 fix: replace hardcoded slippage + expire bridge quotes
  app/_locales/en/messages.json
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  ui/pages/bridge/prepare/bridge-cta-button.tsx
Labels: team-bridge

#29103 chore(cherry-pick): only poll popular networks
  app/_locales/en/messages.json
  shared/constants/network.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/pages/asset/components/asset-page.tsx
  ui/selectors/selectors.js
Labels: team-assets, INVALID-PR-TEMPLATE

#28935 chore: pass the Extension Version to the Uninstall URL
  app/scripts/controllers/metametrics-controller.test.ts
  app/scripts/controllers/metametrics-controller.ts
Labels: team-extension-platform

#28976 chore: change default network avatar style
  app/images/arbitrum.svg
  app/images/avax-token.svg
  app/images/base.svg
  app/images/bnb.svg
  app/images/eth_logo.svg
  app/images/linea-logo-mainnet.svg
  app/images/optimism.svg
  app/images/pol-token.svg
  app/images/zk-sync.svg
  ui/components/app/assets/nfts/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/assets/nfts/nft-details/__snapshots__/nft-full-image.test.js.snap
  ui/components/app/assets/token-cell/__snapshots__/token-cell.test.tsx.snap
  ui/components/app/incoming-trasaction-toggle/__snapshots__/incoming-transaction-toggle.test.js.snap
  ui/components/app/multi-rpc-edit-modal/__snapshots__/multi-rpc-edit-modal.test.tsx.snap
  ui/components/app/multi-rpc-edit-modal/network-list-item/__snapshots__/network-list-item.test.tsx.snap
  ui/components/app/transaction-list-item/smart-transaction-list-item.component.js
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/component-library/avatar-network/__snapshots__/avatar-network.test.tsx.snap
  ui/components/component-library/avatar-network/avatar-network.tsx
  ui/components/component-library/badge-wrapper/__snapshots__/badge-wrapper.test.tsx.snap
  ui/components/component-library/badge-wrapper/badge-wrapper.scss
  ui/components/component-library/badge-wrapper/badge-wrapper.test.tsx
  ui/components/component-library/badge-wrapper/badge-wrapper.tsx
  ui/components/component-library/picker-network/__snapshots__/picker-network.test.tsx.snap
  ui/components/component-library/picker-network/picker-network.tsx
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/asset-picker-amount/asset-picker-modal/__snapshots__/asset-picker-modal-network.test.tsx.snap
  ui/components/multichain/asset-picker-amount/asset-picker/__snapshots__/asset-picker.test.tsx.snap
  ui/components/multichain/network-list-item/__snapshots__/network-list-item.test.js.snap
  ui/components/multichain/network-list-menu/__snapshots__/network-list-menu.test.js.snap
  ui/components/multichain/network-list-menu/select-rpc-url-modal/__snapshots__/select-rpc-url-modal.test.tsx.snap
  ui/components/multichain/pages/send/components/__snapshots__/network-picker.test.tsx.snap
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.tsx.snap
  ui/components/multichain/token-list-item/index.scss
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/bridge/prepare/__snapshots__/prepare-bridge-page.test.tsx.snap
  ui/pages/bridge/prepare/index.scss
  ui/pages/confirmations/components/confirm-page-container/confirm-detail-row/__snapshots__/confirm-detail-row.component.test.js.snap
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-header/__snapshots__/confirm-page-container-header.component.test.js.snap
  ui/pages/confirmations/components/confirm/header/__snapshots__/header.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/nft-send-heading/__snapshots__/nft-send-heading.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-details-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
  ui/pages/confirmations/components/signature-request/signature-request-header/__snapshots__/signature-request-header.component.test.js.snap
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/switch-ethereum-chain.test.js.snap
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: team-bridge

#29088 chore: bump {profile-sync,notification-services}-controller
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-wallet-framework

#29104 test: fix flaky confirmation E2E tests
  test/e2e/fixture-builder.js
  test/e2e/json-rpc/switchEthereumChain.spec.js
  test/e2e/page-objects/pages/test-snaps.ts
Labels: team-confirmations

#28782 feat: add websocket support for c2 detection
  app/manifest/v2/_base.json
  app/manifest/v3/_base.json
  app/scripts/background.js
  privacy-snapshot.json
  test/e2e/helpers.js
  test/e2e/tests/phishing-controller/mocks.js
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
Labels: team-product-safety

#29108 fix: token detection across multiple networks
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
  ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js
  ui/components/app/detected-token/detected-token.js
  ui/components/multichain/detected-token-banner/detected-token-banner.js
  ui/selectors/selectors.test.js
Labels: team-assets

#29065 fix: token.icon possibly null, update validators and types
  app/scripts/controllers/bridge-status/validators.test.ts
  app/scripts/controllers/bridge-status/validators.ts
  shared/types/bridge-status.ts
Labels: team-swaps

#29029 chore: update CODEOWNERS for bridge related code
  .github/CODEOWNERS
Labels: team-bridge, team-swaps

#29114 fix: [cherry-pick] add websocket support for c2 detection (#28782)
  app/manifest/v2/_base.json
  app/manifest/v3/_base.json
  app/scripts/background.js
  privacy-snapshot.json
  test/e2e/helpers.js
  test/e2e/tests/phishing-controller/mocks.js
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
Labels: team-product-safety

#29115 chore(cherry-pick): token detection across multiple networks
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
  ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js
  ui/components/app/detected-token/detected-token.js
  ui/components/multichain/detected-token-banner/detected-token-banner.js
  ui/selectors/selectors.test.js
Labels: team-assets, INVALID-PR-TEMPLATE

#28956 feat: carousel component
  .storybook/test-data.js
  app/_locales/en/messages.json
  app/images/slide-bridge-icon.svg
  app/images/slide-card-icon.svg
  app/images/slide-fund-icon.svg
  app/images/slide-sell-icon.svg
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/app-state-controller.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/app-state.ts
  test/e2e/flask/create-watch-account.spec.ts
  test/e2e/page-objects/pages/account-list-page.ts
  test/e2e/tests/account/incremental-security.spec.js
  test/e2e/tests/carousel/carousel.spec.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/tokens/token-details.spec.ts
  test/integration/data/integration-init-state.json
  test/integration/data/onboarding-completion-route.json
  ui/components/app/incoming-trasaction-toggle/__snapshots__/incoming-transaction-toggle.test.js.snap
  ui/components/component-library/banner-base/banner-base.types.ts
  ui/components/multichain/account-overview/account-overview-eth.test.tsx
  ui/components/multichain/account-overview/account-overview-layout.tsx
  ui/components/multichain/account-overview/account-overview-non-evm.test.tsx
  ui/components/multichain/account-overview/constants.ts
  ui/components/multichain/carousel/carousel.stories.tsx
  ui/components/multichain/carousel/carousel.test.tsx
  ui/components/multichain/carousel/carousel.tsx
  ui/components/multichain/carousel/carousel.types.ts
  ui/components/multichain/carousel/constants.ts
  ui/components/multichain/carousel/helpers.ts
  ui/components/multichain/carousel/index.scss
  ui/components/multichain/carousel/index.ts
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/network-list-menu/__snapshots__/network-list-menu.test.js.snap
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/selectors/selectors.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
  yarn.lock
Labels: team-wallet-ux

#29112 fix: Specify popular network icons in token network filter
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
Labels: team-assets

#29118 chore: add autofocus prop to AssetPicker
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
Labels: team-bridge

#29077 fix: (MMS-1789) bridge api called when external services disabled
  ui/hooks/bridge/useBridging.ts
Labels: team-bridge, team-swaps

#29119 fix (cherry-pick): Specify popular network icons in token network filter (#29112)
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
Labels: team-assets

#29122 chore: Revert "feat: add websocket support for c2 detection (#28782)"
  app/manifest/v2/_base.json
  app/manifest/v3/_base.json
  app/scripts/background.js
  privacy-snapshot.json
  test/e2e/helpers.js
  test/e2e/tests/phishing-controller/mocks.js
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
Labels: team-extension-platform

#28721 feat: Add link to pending transaction alert
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  jest.integration.config.js
  test/integration/confirmations/transactions/alerts.test.tsx
  ui/components/app/alert-system/alert-modal/alert-modal.tsx
  ui/components/app/alert-system/general-alert/general-alert.tsx
  ui/ducks/confirm-alerts/confirm-alerts.ts
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/hooks/alerts/transactions/PendingTransactionAlertMessage.tsx
  ui/pages/confirmations/hooks/alerts/transactions/usePendingTransactionAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/usePendingTransactionAlerts.ts
Labels: team-confirmations

#29042 fix: send up requestId for squid
  app/scripts/controllers/bridge-status/utils.ts
  shared/types/bridge-status.ts
Labels: team-bridge, team-swaps

#29130 Cherry pick #28782 to v12.9.1
  app/manifest/v2/_base.json
  app/manifest/v3/_base.json
  app/scripts/background.js
  privacy-snapshot.json
  test/e2e/helpers.js
  test/e2e/tests/phishing-controller/mocks.js
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
Labels: INVALID-PR-TEMPLATE

#29054 fix: solana balance on accounts selector
  package.json
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  yarn.lock
Labels: team-sol

#29131 fix: Change visibility of `AmountRow` in contract interaction
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
  ui/pages/confirmations/components/confirm/info/utils.test.ts
  ui/pages/confirmations/components/confirm/info/utils.ts
Labels: team-confirmations

#29020 fix: Fix in label displayed for state change in signature decoding section
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx
Labels: team-confirmations

#29136 Cherry pick 2e8ef0237 (#29125) to v12.9.1
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#28966 feat: Permission page tour removal
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/tests/connections/connect-with-metamask.spec.js
  test/e2e/tests/connections/edit-account-flow.spec.js
  test/e2e/tests/connections/edit-networks-flow.spec.js
  test/e2e/tests/connections/review-permissions-page.spec.js
  test/e2e/tests/dapp-interactions/dapp-interactions.spec.js
  test/e2e/tests/dapp-interactions/permissions.spec.js
  test/e2e/tests/metrics/dapp-viewed.spec.js
  test/e2e/tests/multichain/all-permissions-page.spec.js
  test/e2e/tests/multichain/permission-page.spec.js
  ui/components/multichain/pages/permissions-page/permissions-page.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#29137 fix: design related fixes in confirmation pages
  ui/components/app/confirm/info/row/text.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/spending-cap/__snapshots__/spending-cap.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/base-transaction-info/__snapshots__/base-transaction-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/__snapshots__/set-approval-for-all-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/__snapshots__/edit-gas-fees-row.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/__snapshots__/gas-fees-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/__snapshots__/gas-fees-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
Labels: team-confirmations

#28768 test: [POM] Migrate hardware wallet e2e tests to follow Page Object Model
  test/e2e/page-objects/pages/account-list-page.ts
  test/e2e/page-objects/pages/hardware-wallet/connect-hardware-wallet-page.ts
  test/e2e/page-objects/pages/hardware-wallet/select-trezor-account-page.ts
  test/e2e/page-objects/pages/home/asset-list.ts
  test/e2e/page-objects/pages/snap-simple-keyring-page.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/hardware-wallets/lattice-connect.spec.ts
  test/e2e/tests/hardware-wallets/trezor-account.spec.js
  test/e2e/tests/hardware-wallets/trezor-account.spec.ts
  test/e2e/tests/hardware-wallets/trezor-send.spec.ts
  test/e2e/tests/hardware-wallets/trezor-sign.spec.ts
Labels: team-extension-platform

#29134 feat: Add new metric sending_value to Transaction * events
  ui/pages/confirmations/components/confirm/info/hooks/use-token-values.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/use-token-values.ts
  ui/pages/confirmations/components/confirm/info/hooks/useSendingValueMetric.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useSendingValueMetric.ts
  ui/pages/confirmations/components/confirm/info/shared/native-send-heading/native-send-heading.tsx
  ui/pages/confirmations/components/confirm/info/shared/send-heading/send-heading.tsx
Labels: team-confirmations

#28927 chore: Add App Opened Metric Event
  app/scripts/background.js
  shared/constants/metametrics.ts
  test/e2e/tests/metrics/app-opened.spec.ts
Labels: team-extension-platform

#29053 feat: Remove scroll to the bottom requirement for all personal sign requests
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
Labels: team-confirmations

#29075 feat: update bridge tx details
  app/_locales/en/messages.json
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/hooks/bridge/useBridgeTxHistoryData.ts
  ui/pages/bridge/transaction-details/transaction-details.tsx
  ui/pages/bridge/types.ts
Labels: team-bridge, team-swaps

#29121 fix: Use correct selector to pull name from non-popular networks
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
  ui/components/multichain/token-list-item/token-list-item.tsx
Labels: team-assets

#29109 chore: delay linea bridge tx to make it less flaky
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  ui/pages/bridge/prepare/bridge-cta-button.tsx
Labels: team-bridge, team-swaps

#28686 refactor: Refactor how manifest flags are set
  app/scripts/lib/manifestFlags.ts
  development/lib/get-manifest-flag.ts
  test/e2e/helpers.js
  test/e2e/set-manifest-flags.ts
Labels: team-wallet-framework, team-extension-platform

#29113 feat: hardware wallet confirmation screen
  app/_locales/en/messages.json
  test/jest/mock-store.js
  ui/hooks/bridge/useBridging.ts
  ui/pages/bridge/__snapshots__/index.test.tsx.snap
  ui/pages/bridge/awaiting-signatures/awaiting-signatures-cancel-button.tsx
  ui/pages/bridge/awaiting-signatures/awaiting-signatures.tsx
  ui/pages/bridge/awaiting-signatures/index.scss
  ui/pages/bridge/awaiting-signatures/index.ts
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  ui/pages/bridge/index.scss
  ui/pages/bridge/index.test.tsx
  ui/pages/bridge/index.tsx
Labels: team-swaps

#29043 ci: Only check attributions on release candidates
  .github/workflows/check-attributions.yml
Labels: team-wallet-framework, team-extension-platform

#29149 chore: disable button while submiting, use finally set submitting to …
  ui/pages/bridge/prepare/bridge-cta-button.tsx
Labels: team-bridge, team-swaps

#29153 fix: show only 6 decimals max to reduce text cutoff in activity item
  ui/hooks/useTransactionDisplayData.js
Labels: team-bridge, team-swaps

#29168 refactor: Robustify migration 135
  app/scripts/migrations/135.test.ts
  app/scripts/migrations/135.ts
Labels: INVALID-PR-TEMPLATE

#29082 feat: Adding Skeleton component to component-library
  ui/components/component-library/component-library-components.scss
  ui/components/component-library/skeleton/README.mdx
  ui/components/component-library/skeleton/__snapshots__/skeleton.test.tsx.snap
  ui/components/component-library/skeleton/index.ts
  ui/components/component-library/skeleton/skeleton.scss
  ui/components/component-library/skeleton/skeleton.stories.tsx
  ui/components/component-library/skeleton/skeleton.test.tsx
  ui/components/component-library/skeleton/skeleton.tsx
  ui/components/component-library/skeleton/skeleton.types.ts
  ui/helpers/constants/design-system.ts
Labels: team-design-system

#29117 feat: add background-muted color to design system
  ui/components/component-library/box/box.stories.tsx
  ui/css/design-system/_colors.scss
  ui/helpers/constants/design-system.ts
Labels: team-design-system, INVALID-PR-TEMPLATE

#29150 feat: add websocket support for c2 detection
  app/manifest/v2/_base.json
  app/manifest/v3/_base.json
  app/scripts/background.js
  privacy-snapshot.json
  test/e2e/helpers.js
  test/e2e/tests/phishing-controller/mocks.js
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
Labels: team-product-safety

#29174 Jl/caip25 permission migration/bind origin to method hooks
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.ts
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/wallet-requestPermissions.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-requestPermissions.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#28912 chore: Master sync PR following v12.8.0 and v12.9.0
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#29169 fix: send user to native bridge experience rather than portfolio when…
  ui/components/multichain/account-overview/account-overview-layout.tsx
Labels: team-bridge, team-swaps

#28963 feat: display other currencies for non evm accounts.
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  ui/components/app/assets/asset-list/native-token/use-native-token-balance.ts
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/pages/send/send.test.js
  ui/hooks/useCurrencyDisplay.js
  ui/selectors/multichain.test.ts
  ui/selectors/multichain.ts
  ui/selectors/selectors.js
Labels: team-accounts

#29111 Implement Wallet Discovery For Multichain API #2970
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#29186 chore: fix changelog lint 12.10.0
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery

#29185 chore: cherry-pick `29131`
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
  ui/pages/confirmations/components/confirm/info/utils.test.ts
  ui/pages/confirmations/components/confirm/info/utils.ts
Labels: team-confirmations

#29140 fix: increase signing or submitting alert severity to danger
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/integration/confirmations/transactions/alerts.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/hooks/alerts/transactions/useSigningOrSubmittingAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useSigningOrSubmittingAlerts.ts
Labels: team-confirmations

#29143 fix: Swap out Spinner component exposed to Snaps
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/components/app/snaps/snap-ui-renderer/components/spinner.ts
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#29173 fix: [cherry-pick] add websocket support for c2 detection (#28782)
  app/manifest/v2/_base.json
  app/manifest/v3/_base.json
  app/scripts/background.js
  privacy-snapshot.json
  test/e2e/helpers.js
  test/e2e/tests/phishing-controller/mocks.js
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
Labels: team-product-safety

#29164 chore(cherry-pick): Use correct selector to pull name from non-popular networks
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
  ui/components/multichain/token-list-item/token-list-item.tsx
Labels: INVALID-PR-TEMPLATE

#29023 feat: Migrate signature e2e tests for redesigned screens
  test/e2e/helpers.js
  test/e2e/snaps/test-snap-siginsights.spec.js
  test/e2e/tests/dapp-interactions/signin-with-ethereum.spec.js
  test/e2e/tests/metrics/signature-approved.spec.js
  test/e2e/tests/petnames/petnames-signatures.spec.js
  test/e2e/tests/signature/personal-sign.spec.js
  test/e2e/tests/signature/signature-request.spec.js
Labels: team-confirmations

#29052 fix: Fix not set `estimate_type` and rename `dappSuggested` transaction metric property value
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  shared/constants/metametrics.ts
Labels: team-confirmations

#29142 fix: Disable link out modal for preinstalled Snap links
  ui/components/app/snaps/snap-ui-link/snap-ui-link.js
  ui/selectors/selectors.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#29003 Jl/caip multichain/flask
  .circleci/config.yml
  app/build-types/flask/manifest/_base.json
  app/manifest/v2/_barad_dur.json
  app/manifest/v3/_barad_dur.json
  app/scripts/background.js
  app/scripts/metamask-controller.js
  builds.yml
  development/build/manifest.js
Labels: team-wallet-api-platform

#29162 chore: bridge, show max gas
  ui/ducks/bridge/selectors.test.ts
  ui/pages/bridge/quotes/__snapshots__/bridge-quote-card.test.tsx.snap
  ui/pages/bridge/quotes/bridge-quote-card.tsx
Labels: team-bridge, team-swaps

#29198 feat: show info message when a HW user declines a tx
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/bridge.ts
  ui/ducks/bridge/selectors.ts
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/bridge-tx-declined-message.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps
