Repository MetaMask/metamask-extension, pull requests merged in 2024-04, with the labels that each got.

#22603 chore: sonar integration
  .github/workflows/sonar.yml
  sonar-project.properties
Labels: team-extension-platform, needs-dev-review

#23768 fix: wrap, ellipsify-with-tooltip long names and amounts in simulation details
  ui/components/ui/tooltip/tooltip.js
  ui/pages/confirmations/components/simulation-details/amount-pill.test.tsx
  ui/pages/confirmations/components/simulation-details/amount-pill.tsx
  ui/pages/confirmations/components/simulation-details/asset-pill.tsx
  ui/pages/confirmations/components/simulation-details/balance-change-row.tsx
  ui/pages/confirmations/components/simulation-details/fiat-display.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.stories.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
Labels: team-confirmations-system

#23827 chore: updates package and RPC middleware methods
  app/scripts/lib/rpc-method-middleware/handlers/institutional/mmi-open-add-hardware-wallet.js
  app/scripts/lib/rpc-method-middleware/handlers/institutional/mmi-portfolio.js
  app/scripts/lib/rpc-method-middleware/handlers/institutional/mmi-set-account-and-network.js
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-mmi

#23826 chore: adds MMI Sentry DSN key to VARIABLES_REQUIRED_IN_PRODUCTION
  development/build/config.js
Labels: team-mmi

#23840 fix(snaps): Use MarkDown styling in links
  ui/components/app/snaps/snap-ui-markdown/index.scss
  ui/components/app/snaps/snap-ui-markdown/snap-ui-markdown.js
Labels: area-snaps, team-snaps-platform

#23846 fix: add display warning for mumbai
  shared/constants/network.ts
  test/e2e/tests/network/deprecated-networks.spec.js
  ui/components/ui/deprecated-networks/deprecated-networks.js
Labels: team-assets, needs-assets-ux-review

#23843 Version v11.13.2
  CHANGELOG.md
  app/scripts/lib/rpc-method-middleware/handlers/institutional/mmi-open-add-hardware-wallet.js
  app/scripts/lib/rpc-method-middleware/handlers/institutional/mmi-portfolio.js
  app/scripts/lib/rpc-method-middleware/handlers/institutional/mmi-set-account-and-network.js
  development/build/config.js
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-mmi, release-11.13.2

#23831 ci: conditionally run optional MMI test
  .circleci/config.yml
Labels: team-extension-platform

#23842 fix: add role img to app header picker network
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header.js
Labels: accessibility, team-design-system, team-wallet-ux

#23798 fix: token detection and import
  .yarn/patches/@metamask-assets-controllers-npm-26.0.0-17c0e9432c.patch
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: team-assets

#23881 cherry-pick: display native ticker and logo for current chain and render near-zero amounts in simulations (#23711)
  shared/modules/Numeric.test.ts
  shared/modules/Numeric.ts
  test/e2e/tests/simulation-details/simulation-details.spec.ts
  ui/hooks/useCurrencyDisplay.js
  ui/pages/confirmations/components/simulation-details/amount-pill.test.tsx
  ui/pages/confirmations/components/simulation-details/amount-pill.tsx
  ui/pages/confirmations/components/simulation-details/asset-pill.test.tsx
  ui/pages/confirmations/components/simulation-details/asset-pill.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.stories.tsx
  ui/pages/confirmations/components/simulation-details/types.ts
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
Labels: INVALID-PR-TEMPLATE

#23867 fix: update input validation (#23808)
  ui/components/app/currency-input/__snapshots__/currency-input.test.js.snap
  ui/components/app/currency-input/currency-input.js
  ui/components/app/currency-input/hooks/useProcessNewDecimalValue.test.tsx
  ui/components/app/currency-input/hooks/useProcessNewDecimalValue.tsx
  ui/components/multichain/asset-picker-amount/nft-input/nft-input.tsx
  ui/components/ui/unit-input/unit-input.component.js
  ui/ducks/send/send.js
Labels: INVALID-PR-TEMPLATE

#23773 fix: BlockaidBannerAlert LoadingIndicator position
  ui/components/app/network-display/index.scss
  ui/components/ui/loading-indicator/loading-indicator.js
  ui/components/ui/loading-indicator/loading-indicator.scss
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
Labels: team-confirmations-secure-ux-PR

#23787 chore: MMI hide pending transaction warning
  ui/pages/confirmations/components/transaction-alerts/transaction-alerts.js
Labels: team-mmi

#23879 fix: adds mmi sentry variable to builds yml
  builds.yml
Labels: team-mmi

#23871 fix: token detection and import (#23798)
  .yarn/patches/@metamask-assets-controllers-npm-26.0.0-17c0e9432c.patch
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#23869 fix: check if array of PRs is empty
  .circleci/config.yml
Labels: team-mmi

#23891 Version v11.13.3
  CHANGELOG.md
  builds.yml
  package.json
Labels: team-mmi, release-11.13.3

#23868 chore: MMI adds Sentry to MMI custody keyring
  app/scripts/metamask-controller.js
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-mmi

#23882 cherry-pick: skip simulation metrics if simulation disabled or chain not supported (#23713)
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/pages/confirmations/components/simulation-details/simulation-details.stories.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.test.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
  ui/pages/confirmations/components/simulation-details/useSimulationMetrics.test.ts
  ui/pages/confirmations/components/simulation-details/useSimulationMetrics.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#23909 cherry-pick: display correct asset icon and sizing for simulation details (#23760)
  ui/components/app/confirm/info/row/__snapshots__/address.test.tsx.snap
  ui/components/app/name/__snapshots__/name.test.tsx.snap
  ui/components/app/name/index.scss
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/name/name.tsx
  ui/pages/confirmations/components/simulation-details/asset-pill.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.stories.tsx
Labels: team-confirmations-system, INVALID-PR-TEMPLATE

#23880 feat: update popular network list
  shared/constants/network.test.ts
  shared/constants/network.ts
Labels: team-assets, needs-assets-ux-review

#23815 fix: UX: Multichain: Remove tabs from Connections view
  app/_locales/en/messages.json
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/connections/connections.tsx
Labels: team-wallet-ux, needs-assets-ux-review

#23807 test: Added unit test for onboarding controller 23461
  app/scripts/controllers/onboarding.test.ts
  jest.config.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#23828 fix: track remove NFT event
  app/_locales/en/messages.json
  shared/constants/metametrics.ts
  test/e2e/tests/tokens/nft/remove-nft.spec.js
  ui/components/app/nft-details/nft-details.js
  ui/components/app/nft-details/nft-details.test.js
  ui/pages/home/home.component.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-assets, needs-assets-ux-review

#23897 fix: Fix `increaseAllowance` bugs
  app/_locales/en/messages.json
  shared/lib/metamask-controller-utils.js
  test/e2e/tests/tokens/increase-token-allowance.spec.js
  ui/pages/confirmations/components/approve-content-card/approve-content-card.js
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR

#23814 fix: UX: Multichain: Only show pointer cursor for AccountListItem when clickable
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/index.scss
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
Labels: team-wallet-ux, needs-assets-ux-review

#23926 fix: Bump tar to 6.2.1
  yarn.lock
Labels: team-unkown, release-11.15.0

#23918 fix: revert the revert base network support for blockaid validations (#2…
  app/_locales/en/messages.json
  app/scripts/lib/ppom/ppom-middleware.ts
Labels: team-confirmations-secure-ux-PR

#23915 fix: display balance changes for wrapped ERC-20 and legacy ERC-721
  package.json
  test/e2e/tests/simulation-details/mock-request-buy-erc721.ts
  yarn.lock
Labels: team-confirmations-system, QA Passed

#23928 fix: Fix a crash in the connected accounts modal
  ui/components/app/connected-accounts-permissions/connected-accounts-permissions.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#23911 cherry-pick: wrap, ellipsify-with-tooltip long names and amounts in simulation details (#23768)
  ui/components/ui/tooltip/tooltip.js
  ui/pages/confirmations/components/simulation-details/amount-pill.test.tsx
  ui/pages/confirmations/components/simulation-details/amount-pill.tsx
  ui/pages/confirmations/components/simulation-details/asset-pill.tsx
  ui/pages/confirmations/components/simulation-details/balance-change-row.tsx
  ui/pages/confirmations/components/simulation-details/fiat-display.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.stories.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
Labels: team-confirmations-system, INVALID-PR-TEMPLATE

#23930 cherry-pick: Fix a crash in the connected accounts modal (#23928)
  ui/components/app/connected-accounts-permissions/connected-accounts-permissions.js
Labels: INVALID-PR-TEMPLATE

#23927 fix: BlockaidBannerAlert LoadingIndicator overlap on TransactionAlerts
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
Labels: team-confirmations-secure-ux-PR

#23907 refactor(notifications): update prod authentication endpoints
  app/scripts/controllers/authentication/authentication-controller.ts
  app/scripts/controllers/authentication/services.ts
  builds.yml
Labels: needs-dev-review, team-notifications

#23934 cherry-pick: add learn more link to simulations toggle (#23890)
  app/_locales/en/messages.json
  shared/lib/ui-utils.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
Labels: team-confirmations-system, INVALID-PR-TEMPLATE

#23932 cherry-pick: Revert "feat: Remove powered by blockaid line" (#23925)
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/constants/security-provider.ts
  ui/pages/confirmations/components/security-provider-banner-alert/__snapshots__/security-provider-banner-alert.test.js.snap
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/pages/confirmations/components/security-provider-banner-alert/security-provider-banner-alert.js
  ui/pages/confirmations/components/signature-request-original/signature-request-original.component.js
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe.js
  ui/pages/confirmations/components/signature-request/signature-request.js
  ui/pages/confirmations/components/transaction-alerts/transaction-alerts.js
  ui/pages/confirmations/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirmations/token-allowance/token-allowance.js
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR

#23929 cherry-pick: Fix `increaseAllowance` bugs
  app/_locales/en/messages.json
  shared/lib/metamask-controller-utils.js
  test/e2e/tests/tokens/increase-token-allowance.spec.js
  ui/pages/confirmations/components/approve-content-card/approve-content-card.js
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR

#23931 chore: make learn more articles generic
  test/e2e/mmi/specs/navigation.spec.ts
Labels: team-mmi

#23771 feat: UX: Multichain: Close other popups when new popup is opened
  app/scripts/controllers/app-state.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/index.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/store/actions.ts
Labels: team-wallet-ux, needs-assets-ux-review

#23774 fix: Prevent NFT banner from tracking more than once
  ui/components/app/nfts-tab/nfts-tab.js
Labels: team-wallet-ux, needs-assets-ux-review

#23775 fix: Memoize network selectors to improve performance
  ui/selectors/selectors.js
Labels: team-wallet-ux, needs-assets-ux-review

#23733 fix: UX: Multichain: Only show connection toast on the home screen
  ui/pages/routes/routes.component.js
Labels: team-wallet-ux, needs-assets-ux-review

#23939 cherry-pick: display balance changes for wrapped ERC-20 and legacy ERC-721 (#23915)
  package.json
  test/e2e/tests/simulation-details/mock-request-buy-erc721.ts
  yarn.lock
Labels: team-confirmations-system, INVALID-PR-TEMPLATE

#23941 fix: Ensure selector functions are in correct order
  ui/selectors/selectors.js
Labels: team-wallet-ux

#23899 fix: hide totals if simulation successful
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirmations/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
Labels: team-confirmations-system, QA Passed

#23940 chore: remove old announcements
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/introducing-snaps.svg
  app/images/sell_button_whatsnew.png
  shared/notifications/index.ts
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: team-wallet-ux, team-snaps-platform

#23958 fix: host permissions for cx.metamask.io
  app/manifest/v2/_base.json
Labels: team-confirmations-secure-ux

#23573 fix(browser-passworder): `isVaultUpdated` should not return promise
  app/scripts/lib/encryptor-factory.test.ts
  app/scripts/lib/encryptor-factory.ts
Labels: team-shared-libraries

#23954 cherry-pick: hide totals if simulation successful (#23899)
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirmations/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
Labels: team-confirmations-system, INVALID-PR-TEMPLATE

#23969 fix: update arbitrum logo
  app/images/arbitrum.svg
Labels: team-assets, needs-assets-ux-review

#23919 fix: always use remote token list for default petnames
  app/scripts/controllers/preferences.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  test/e2e/mock-e2e.js
  ui/components/app/name/name.test.tsx
  ui/hooks/useDisplayName.ts
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/selectors/selectors.js
Labels: team-confirmations-system, QA Passed

#23903 fix(23804): unable to add QR code account
  .yarn/patches/@metamask-keyring-controller-npm-13.0.0-d94816a680.patch
  package.json
  yarn.lock
Labels: Sev1-high, release-blocker, QA Passed, needs-dev-review, team-hardware-wallets, e2e-test

#23963 feat: Small updates for Smart Transactions
  app/_locales/en/messages.json
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/lib/transaction/smart-transactions.test.ts
  app/scripts/lib/transaction/smart-transactions.ts
  app/scripts/metamask-controller.js
  package.json
  shared/modules/metametrics.test.ts
  shared/modules/metametrics.ts
  ui/components/app/add-network/add-network.test.js
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirmations/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/smart-transactions/smart-transaction-status-page/__snapshots__/smart-transactions-status-page.test.js.snap
  ui/pages/smart-transactions/smart-transaction-status-page/index.scss
  ui/pages/smart-transactions/smart-transaction-status-page/smart-transaction-status-page.tsx
  yarn.lock
Labels: team-swaps, release-11.15.0

#23984 cherry-pick: always use remote token list for default petnames (#23919)
  app/scripts/controllers/preferences.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  test/e2e/mock-e2e.js
  ui/components/app/name/name.test.tsx
  ui/hooks/useDisplayName.ts
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/selectors/selectors.js
Labels: team-confirmations-system, INVALID-PR-TEMPLATE

#23783 test: Add ability to have any number of ganache servers for e2e
  test/e2e/helpers.js
  test/e2e/json-rpc/switchEthereumChain.spec.js
  test/e2e/tests/custom-rpc-history.spec.js
  test/e2e/tests/dapp-interactions/dapp-interactions.spec.js
  test/e2e/tests/network/chain-interactions.spec.js
  test/e2e/tests/network/switch-custom-network.spec.js
  test/e2e/tests/onboarding/onboarding.spec.js
  test/e2e/tests/request-queuing/multiple-networks-dapps-txs.spec.js
  test/e2e/tests/request-queuing/switch-network.spec.js
Labels: area-testSuite, team-wallet-api-platform, e2e-test

#23981 cherry-pick: unable to add QR code account (#23903)
  .yarn/patches/@metamask-keyring-controller-npm-13.0.0-d94816a680.patch
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-hardware-wallets, release-11.14.0

#23990 cherry-pick: remove old announcements (#23940)
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/introducing-snaps.svg
  app/images/sell_button_whatsnew.png
  shared/notifications/index.ts
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, team-snaps-platform

#23844 fix: Added connections logic specific to dapp
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/connect-accounts-modal/connect-account-modal.types.ts
  ui/components/multichain/connect-accounts-modal/connect-accounts-modal-list.tsx
  ui/components/multichain/connect-accounts-modal/connect-accounts-modal.test.tsx
  ui/components/multichain/connect-accounts-modal/connect-accounts-modal.tsx
  ui/components/multichain/connected-accounts-menu/connected-accounts-menu.test.tsx
  ui/components/multichain/connected-accounts-menu/connected-accounts-menu.tsx
  ui/components/multichain/pages/connections/connections.test.tsx
  ui/components/multichain/pages/connections/connections.tsx
  ui/components/multichain/pages/permissions-page/permissions-page.js
  ui/selectors/permissions.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23992 fix: simulation metrics performance
  ui/pages/confirmations/hooks/useTransactionEventFragment.js
Labels: team-confirmations-system

#23998 cherry-pick: simulation metrics performance (#23992)
  ui/pages/confirmations/hooks/useTransactionEventFragment.js
Labels: team-confirmations-system, INVALID-PR-TEMPLATE

#23917 chore: Adding Version-v11.14.0 changelog
  CHANGELOG.md
Labels: INVALID-PR-TEMPLATE

#23352 feat: adds a ramps banner to home pages when users have zero balance
  app/_locales/en/messages.json
  app/images/ramps-card-activity-illustration.png
  app/images/ramps-card-nft-illustration.png
  app/images/ramps-card-token-illustration.png
  ui/components/app/asset-list/asset-list.js
  ui/components/app/asset-list/asset-list.ramps-card.test.js
  ui/components/app/asset-list/asset-list.test.js
  ui/components/app/nfts-tab/nfts-tab.js
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/multichain/asset-list-conversion-button/asset-list-conversion-button.js
  ui/components/multichain/asset-list-conversion-button/asset-list-conversion-button.stories.js
  ui/components/multichain/asset-list-conversion-button/index.js
  ui/components/multichain/asset-list-conversion-button/index.scss
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/ramps-card/index.js
  ui/components/multichain/ramps-card/index.scss
  ui/components/multichain/ramps-card/ramps-card.js
  ui/components/multichain/ramps-card/ramps-card.stories.js
  ui/components/multichain/receive-token-link/index.ts
  ui/components/multichain/receive-token-link/receive-token-link.tsx
  ui/hooks/experiences/useRamps.test.js
  ui/hooks/experiences/useRamps.ts
Labels: team-ramp, needs-dev-review

#24010 chore: Master sync following v11.14.0
  CHANGELOG.md
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#23988 fix: new-network button label colors are not readable in light mode
  ui/components/ui/new-network-info/index.scss
  ui/components/ui/new-network-info/new-network-info.js
Labels: regression-RC, team-bridge, release-11.14.0

#23935 fix: Updated avatar favicon props for single account disconnect toast
  ui/components/multichain/pages/connections/connections.tsx
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23999 fix: cache subject metadata for redirect
  ui/components/ui/icon-with-fallback/icon-with-fallback.component.js
  ui/pages/confirm-add-suggested-nft/__snapshots__/confirm-add-suggested-nft.test.js.snap
  ui/pages/confirmations/components/signature-request-header/__snapshots__/signature-request-header.test.js.snap
  ui/pages/confirmations/components/signature-request-original/__snapshots__/signature-request-original.test.js.snap
  ui/pages/confirmations/components/signature-request-siwe/__snapshots__/signature-request-siwe.test.js.snap
  ui/pages/confirmations/components/signature-request/__snapshots__/signature-request.test.js.snap
  ui/pages/confirmations/confirm-signature-request/__snapshots__/index.test.js.snap
  ui/pages/confirmations/token-allowance/__snapshots__/token-allowance.test.js.snap
  ui/pages/permissions-connect/redirect/permissions-redirect.component.js
Labels: needs-dev-review, INVALID-PR-TEMPLATE, team-wallet-ux

#23796 test: [Snaps E2E] add more snaps localization testing
  test/e2e/snaps/test-snap-get-locale.spec.js
Labels: area-snaps, e2e-test, team-snaps-platform

#23630 feat: Release Transaction Insights V2 & Signature Insights to stable
  shared/constants/permissions.test.js
  shared/constants/snaps/permissions.ts
  test/e2e/run-all.js
  test/e2e/snaps/test-snap-siginsights.spec.js
  ui/components/app/snaps/snap-insight/snap-insight.js
  ui/helpers/constants/snaps/delineator.ts
  ui/helpers/utils/permission.js
  ui/hooks/snaps/useTransactionInsightSnaps.js
  ui/hooks/useTransactionInsights.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container.component.js
  ui/pages/confirmations/components/signature-request-original/signature-request-original.component.js
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe.js
  ui/pages/confirmations/components/signature-request/signature-request.js
  ui/pages/confirmations/confirm-signature-request/index.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#22739 test: [Snaps E2E] Create E2E test for UI links
  privacy-snapshot.json
  test/e2e/snaps/test-snap-uilinks.spec.js
Labels: area-snaps, team-snaps-platform

#24005 fix: checkmark icon missing after token import
  ui/pages/home/index.scss
Labels: team-assets, needs-assets-ux-review

#23820 ci: update `github/codeql-action` to v3
  .github/workflows/codeql-analysis.yml
Labels: team-extension-platform

#23822 ci: update `actions/checkout` to v4
  .github/workflows/add-release-label.yml
  .github/workflows/check-pr-labels.yml
  .github/workflows/check-template-and-add-labels.yml
  .github/workflows/close-bug-report.yml
  .github/workflows/main.yml
  .github/workflows/sonar.yml
  .github/workflows/update-lavamoat-policies.yml
Labels: team-extension-platform

#24000 build: remove `brfs` from build processes
  development/build/scripts.js
  development/ts-migration-dashboard/common/partitions-file.ts
  development/ts-migration-dashboard/scripts/build-app.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#23986 fix: Updated selector for the test networks
  ui/components/multichain/pages/permissions-page/connection-list-item.js
  ui/selectors/selectors.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#24023 fix: fixed wallet view bugs for connections and permissions screen
  app/_locales/en/messages.json
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/account-list-item-menu/account-list-item-menu.test.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/hidden-account-list.js
  ui/components/multichain/pages/connections/connections.tsx
Labels: team-wallet-ux, needs-assets-ux-review

#24039 feat: add filecoin logo svg
  app/images/filecoin.svg
  shared/constants/network.ts
Labels: team-assets, needs-assets-ux-review

#22382 feat: create Developer Options Setting Page
  .metamaskrc.dist
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/browserify/policy-override.json
  package.json
  ui/ducks/metamask/metamask.js
  ui/helpers/constants/routes.ts
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/developer-options-tab/developer-options-tab.js
  ui/pages/settings/developer-options-tab/index.js
  ui/pages/settings/developer-options-tab/index.scss
  ui/pages/settings/index.scss
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
  yarn.lock
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#23912 chore: MMI adds custodian icons
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/index.scss
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/address-copy-button/index.scss
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/account-picker.test.tsx.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
Labels: team-mmi

#24053 feat: Update UI / content for the Smart Transactions Opt In modal, renaming
  app/_locales/en/messages.json
  app/images/smart-transactions/smart-transactions-opt-in-background.svg
  ui/components/app/smart-transactions/index.scss
  ui/components/app/smart-transactions/smart-transactions-opt-in-modal.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirmations/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
Labels: team-swaps, release-11.15.0

#23933 fix: improve performance in account list and account connection components
  ui/components/app/connected-status-indicator/connected-status-indicator.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/connected-status/connected-status.tsx
  ui/pages/confirmations/components/snap-account-success-message/SnapAccountSuccessMessage.test.tsx
  ui/pages/confirmations/confirmation/stories/util.js
  ui/selectors/permissions.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23695 fix: deprecating more networks
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/migrations/115.test.ts
  app/scripts/migrations/115.ts
  app/scripts/migrations/index.js
  shared/constants/network.ts
  ui/helpers/utils/i18n-helper.tsx
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.js
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js
  ui/pages/settings/networks-tab/networks-tab.constants.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-assets, needs-assets-ux-review

#24021 fix: token rates controller start / stop logic
  app/scripts/metamask-controller.js
Labels: team-assets, needs-assets-ux-review

#23957 chore: bump snaps packages
  app/scripts/lib/encryptor-factory.test.ts
  app/scripts/lib/encryptor-factory.ts
  app/scripts/metamask-controller.js
  builds.yml
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#23855 fix(labeling guidelines): Add definition of regression-develop label
  .github/guidelines/LABELING_GUIDELINES.md
Labels: team-extension-platform, needs-dev-review

#23993 feat: prevent pasting of Snap name during Snap removal
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.test.tsx
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.tsx
Labels: team-accounts

#23778 chore: adds GH action for MMI
  .github/workflows/add-mmi-reviewer-and-notify.yml
Labels: needs-dev-review, team-mmi

#23886 fix: Gas Estimation failure displays 2 duplicated Warnings
  ui/pages/confirmations/components/simulation-error-message/simulation-error-message.js
  ui/pages/confirmations/components/transaction-alerts/transaction-alerts.js
  ui/pages/confirmations/components/transaction-alerts/transaction-alerts.test.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
Labels: team-confirmations-secure-ux-PR

#24045 refactor: Extract `BlockaidUnavailableBannerAlert` component
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/__snapshots__/blockaid-unavailable-banner-alert.test.tsx.snap
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/blockaid-unavailable-banner-alert.stories.tsx
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/blockaid-unavailable-banner-alert.test.tsx
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/blockaid-unavailable-banner-alert.tsx
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/index.ts
  ui/pages/confirmations/components/signature-request-original/signature-request-original.component.js
  ui/pages/confirmations/components/signature-request-original/signature-request-original.container.js
  ui/pages/confirmations/components/signature-request/signature-request.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirmations/token-allowance/token-allowance.js
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR

#23780 fix: signature request using ledger on new designed confirmation pages
  types/global.d.ts
  ui/pages/confirmations/components/confirm/ledger-info/__snapshots__/ledger-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/ledger-info/index.ts
  ui/pages/confirmations/components/confirm/ledger-info/ledger-info.stories.tsx
  ui/pages/confirmations/components/confirm/ledger-info/ledger-info.test.tsx
  ui/pages/confirmations/components/confirm/ledger-info/ledger-info.tsx
  ui/pages/confirmations/confirm/confirm.tsx
  ui/pages/confirmations/hooks/useLedgerConnection.ts
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#24075 feat: Show simulation details on the Smart Transactions status page for native balance changes
  ui/pages/smart-transactions/smart-transaction-status-page/index.scss
  ui/pages/smart-transactions/smart-transaction-status-page/smart-transaction-status-page.tsx
Labels: team-swaps, release-11.15.0

#24073 chore: updates mmi package to latest version
  package.json
  yarn.lock
Labels: team-mmi

#24059 fix(mv3): fix file paths passed to `app-init.js`
  app/scripts/app-init.js
  development/build/scripts.js
Labels: team-extension-platform

#24078 feat: Show simulation details on the Smart Transactions status page for native balance changes (cherry pick)
  ui/pages/smart-transactions/smart-transaction-status-page/index.scss
  ui/pages/smart-transactions/smart-transaction-status-page/smart-transaction-status-page.tsx
Labels: team-swaps, release-11.15.0

#24068 fix: Intl.NumberFormat locale RangeError related to Simulation Details
  ui/ducks/locale/locale.js
  ui/ducks/locale/locale.test.ts
  ui/hooks/useFiatFormatter.test.ts
  ui/hooks/useFiatFormatter.ts
Labels: team-confirmations-system

#24065 fix: replace last usages of legacy gas fee polling with polling by networkClientId
  app/scripts/metamask-controller.js
  ui/components/app/cancel-speedup-popover/cancel-speedup-popover.test.js
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-input-subtext/advanced-gas-fee-input-subtext.test.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-container.test.js
  ui/pages/confirmations/confirm-send-ether/confirm-send-ether.test.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmations/confirm-transaction/confirm-transaction.test.js
  ui/pages/confirmations/confirm-transaction/confirm-transaction.transaction.test.js
  ui/pages/confirmations/send/send.test.js
  ui/pages/confirmations/token-allowance/token-allowance.test.js
  ui/pages/swaps/fee-card/fee-card.test.js
  ui/pages/swaps/prepare-swap-page/review-quote.test.js
  ui/pages/swaps/view-quote/view-quote.test.js
  ui/store/actions.ts
Labels: team-wallet-api-platform, team-confirmations-system

#24061 Zb/update queued request controller
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/methods-tags.ts
  yarn.lock
Labels: team-wallet-api-platform, amon-hen-blocker

#24085 fix: Fix back navigation from connected accounts
  ui/components/multichain/pages/connections/connections.tsx
Labels: team-wallet-ux

#23712 test: [E2E] edit account name
  test/e2e/accounts/account-custom-name.spec.ts
  ui/components/ui/editable-label/editable-label.js
Labels: team-accounts, needs-dev-review, e2e-test

#24094 fix(deps): @solana/web3.js 1.91.6
  yarn.lock
Labels: dependencies, team-extension-platform, team-security

#24092 fix: updated connections page to use getPermittedAccountsForSelectedTab
  ui/components/multichain/pages/connections/connections.tsx
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23974 fix: fix migration 105 to recover from undefined selected address
  app/scripts/migrations/105.test.ts
  app/scripts/migrations/105.ts
Labels: team-accounts

#24051 feat: Removed product tour from home page
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/controllers/app-state.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  app/scripts/migrations/116.test.ts
  app/scripts/migrations/116.ts
  app/scripts/migrations/index.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/app-header/app-header.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#24074 ci: add `create-cherry-pick-pr` github action
  .circleci/scripts/create-cherry-pick-pr.sh
  .github/workflows/create-cherry-pick-pr.yml
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR, needs-dev-review

#24084 fix: Disable button in case all accounts are connected
  ui/components/multichain/connect-accounts-modal/connect-accounts-modal.tsx
  ui/components/multichain/pages/connections/connections.tsx
  ui/selectors/selectors.js
Labels: team-wallet-ux, needs-assets-ux-review

#24107 chore: bump-metamask-controllers-util-to-9.1.0
  package.json
  yarn.lock
Labels: team-confirmations-secure-ux-PR

#24080 chore: MMI adds SRP screen during onboarding
  app/_locales/en/messages.json
  ui/helpers/constants/routes.ts
  ui/pages/institutional/remind-srp/__snapshots__/remind-srp.test.tsx.snap
  ui/pages/institutional/remind-srp/index.scss
  ui/pages/institutional/remind-srp/remind-srp.test.tsx
  ui/pages/institutional/remind-srp/remind-srp.tsx
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/pages.scss
Labels: team-mmi

#24103 fix: Use cached version of 'chrome' in app-init.js
  app/scripts/app-init.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24086 fix: simulation details should show fiat values for most erc20 tokens
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.test.ts
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
Labels: team-confirmations-system

#24090 chore: replace static hex with design tokens in toggle button
  ui/components/app/incoming-trasaction-toggle/__snapshots__/incoming-transaction-toggle.test.js.snap
  ui/components/ui/toggle-button/toggle-button.component.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: team-design-system

#24109 Cherry-pick 50310db (PR #24086) to v11.14.1
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.test.ts
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
Labels: INVALID-PR-TEMPLATE

#23708 UX: Multichain: Send Flow: Disable account picker for edits
  ui/components/multichain/pages/send/components/account-picker.test.tsx
  ui/components/multichain/pages/send/components/account-picker.tsx
Labels: team-wallet-ux, needs-assets-ux-review, swap-send-blocker

#24083 fix(offscreen): Fix error loading offscreen document in prod
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/browserify/policy-override.json
  offscreen/offscreen.html
  offscreen/scripts/ledger.ts
Labels: team-extension-platform, needs-dev-review

#24116 fix: simulation erc20 decimals error
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.test.ts
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
Labels: team-confirmations-system

#23700 feat: set token autodetection to true for new …
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/metamask-controller.js
Labels: team-assets, needs-assets-ux-review

#24052 Add experimental setting option for redesigned pages
  app/_locales/en/messages.json
  app/scripts/controllers/preferences.js
  ui/helpers/constants/settings.js
  ui/pages/confirmations/hooks/useCurrentConfirmation.test.ts
  ui/pages/confirmations/hooks/useCurrentConfirmation.ts
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.container.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#24124 feat: set default 4337 entrypoint in flask
  builds.yml
  development/build/set-environment-variables.js
Labels: team-accounts

#24112 chore: cherry pick - MMI adds SRP screen during onboarding (#24080)
  app/_locales/en/messages.json
  ui/helpers/constants/routes.ts
  ui/pages/institutional/remind-srp/__snapshots__/remind-srp.test.tsx.snap
  ui/pages/institutional/remind-srp/index.scss
  ui/pages/institutional/remind-srp/remind-srp.test.tsx
  ui/pages/institutional/remind-srp/remind-srp.tsx
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/pages.scss
Labels: team-mmi

#24081 chore: Version v11.15.0 MMI cherry pick
  package.json
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/index.scss
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/address-copy-button/index.scss
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/account-picker.test.tsx.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  yarn.lock
Labels: team-mmi

#24119 cherry-pick e83d28b34c fix: simulation erc20 decimals error (#24116) into Version-v11.14.1
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.test.ts
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
Labels: INVALID-PR-TEMPLATE

#24115 fix: ensure ppom works on mv3 builds
  app/manifest/v3/chrome.json
  development/build/static.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24076 Version-v11.14.1
  CHANGELOG.md
  app/scripts/metamask-controller.js
  package.json
  ui/components/app/cancel-speedup-popover/cancel-speedup-popover.test.js
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
  ui/ducks/locale/locale.js
  ui/ducks/locale/locale.test.ts
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/hooks/useFiatFormatter.test.ts
  ui/hooks/useFiatFormatter.ts
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-input-subtext/advanced-gas-fee-input-subtext.test.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-container.test.js
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.test.ts
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
  ui/pages/confirmations/confirm-send-ether/confirm-send-ether.test.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmations/confirm-transaction/confirm-transaction.test.js
  ui/pages/confirmations/confirm-transaction/confirm-transaction.transaction.test.js
  ui/pages/confirmations/send/send.test.js
  ui/pages/confirmations/token-allowance/token-allowance.test.js
  ui/pages/swaps/fee-card/fee-card.test.js
  ui/pages/swaps/prepare-swap-page/review-quote.test.js
  ui/pages/swaps/view-quote/view-quote.test.js
  ui/store/actions.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#24029 fix: add patch for fetching tokenURI for ERC404
  .yarn/patches/@metamask-assets-controllers-patch-0f46262fea.patch
  package.json
  yarn.lock
Labels: team-assets, needs-assets-ux-review

#23991 feat: display layer 1 gas fees on scroll network
  app/_locales/en/messages.json
  app/images/scroll.svg
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/network.ts
  test/data/mock-send-state.json
  ui/components/app/transaction-breakdown/transaction-breakdown.component.js
  ui/components/app/transaction-breakdown/transaction-breakdown.container.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/pages/confirmations/components/approve-content-card/approve-content-card.stories.js
  ui/pages/confirmations/components/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js
  ui/pages/confirmations/components/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.test.js
  ui/pages/confirmations/components/fee-details-component/fee-details-component.js
  ui/pages/confirmations/components/fee-details-component/fee-details-component.test.js
  ui/pages/confirmations/components/gas-details-item/gas-details-item.js
  ui/pages/confirmations/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirmations/confirm-approve/confirm-approve-content/confirm-approve-content.stories.js
  ui/pages/confirmations/confirm-approve/confirm-approve.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmations/send/send-content/send-content.component.js
  ui/pages/confirmations/send/send-content/send-content.container.js
  ui/pages/confirmations/token-allowance/token-allowance.js
  ui/pages/confirmations/token-allowance/token-allowance.stories-to-do.js
  ui/pages/confirmations/token-allowance/token-allowance.stories.js
  ui/pages/confirmations/token-allowance/token-allowance.test.js
  ui/pages/swaps/prepare-swap-page/review-quote.js
  ui/pages/swaps/view-quote/view-quote.js
  ui/selectors/selectors.js
  yarn.lock
Labels: team-confirmations-system, QA Passed

#24095 feat: add Signature Redesign "Account Details Opened" event
  shared/constants/metametrics.ts
  ui/components/multichain/menu-items/account-details-menu-item.js
  ui/pages/confirmations/components/confirm/header/header-info.test.tsx
  ui/pages/confirmations/components/confirm/header/header-info.tsx
Labels: team-confirmations-secure-ux

#24070 test: UX: Multichain: Add E2E for RPC queueing UI
  test/e2e/tests/request-queuing/ui.spec.js
Labels: team-wallet-ux, needs-assets-ux-review

#23872 test: add scenario 'Cancel transaction by sending subsequent transaction with the same nonce'
  test/scenarios/3. transactions/cancel transaction using same nonce.csv
Labels: area-documentation, team-confirmations-system, release-11.15.0

#23257 feat: Change RPC Method Middleware default rate limit to random sampling and add global rate limit
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
Labels: team-wallet-api-platform, team-data-and-analytics

#23714 test: add scenario send transactions with custom nonce
  test/scenarios/3. transactions/send transactions with custom nonce.csv
Labels: area-documentation, team-confirmations-system, release-11.5.0

#24079 chore: MMI enable Sentry logging for mmi build type
  app/scripts/lib/setupSentry.js
  builds.yml
Labels: team-mmi

#23353 feat: notifications - user storage controller
  app/scripts/controllers/authentication/authentication-controller.test.ts
  app/scripts/controllers/authentication/authentication-controller.ts
  app/scripts/controllers/user-storage/encryption.test.ts
  app/scripts/controllers/user-storage/encryption.ts
  app/scripts/controllers/user-storage/mocks/mockServices.ts
  app/scripts/controllers/user-storage/mocks/mockStorage.ts
  app/scripts/controllers/user-storage/schema.test.ts
  app/scripts/controllers/user-storage/schema.ts
  app/scripts/controllers/user-storage/services.test.ts
  app/scripts/controllers/user-storage/services.ts
  app/scripts/controllers/user-storage/user-storage-controller.test.ts
  app/scripts/controllers/user-storage/user-storage-controller.ts
  app/scripts/metamask-controller.js
  builds.yml
  jest.config.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/env.js
  yarn.lock
Labels: team-notifications

#24127 feat: Added e2e for permissions page
  test/e2e/tests/multichain/permission-page.spec.js
  ui/selectors/selectors.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#24098 fix: Fix tooltip distance
  ui/components/multichain/connect-accounts-modal/connect-accounts-modal-list.tsx
  ui/components/ui/tooltip/tooltip.js
Labels: team-wallet-ux, needs-assets-ux-review

#24163 fix: needs to be always true for MMI
  app/scripts/lib/setupSentry.js
  builds.yml
Labels: team-mmi

#24139 Fix #24125 - Maximize AccountPicker space in header
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/index.scss
Labels: team-wallet-ux, needs-assets-ux-review

#24176 feat: Hide the "retry" button for Smart Transactions, show cancelled STX only for Swaps
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/selectors/transactions.js
Labels: team-swaps, release-11.15.0

#24179 feat: Hide the "retry" button for Smart Transactions, show cancelled STX only for Swaps (cherry pick)
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/selectors/transactions.js
Labels: team-swaps, release-11.15.0

#24174 Cherry-pick b75e313 and cc928f6 to v11.15.0
  app/scripts/lib/setupSentry.js
Labels: team-mmi

#23717 feat: use Infura gas API
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  shared/constants/swaps.ts
  shared/lib/swaps-utils.js
  test/e2e/mock-e2e.js
  test/jest/constants.js
  ui/pages/swaps/swaps.util.ts
  yarn.lock
Labels: team-confirmations-system, QA Passed

#24192 fix: adds default empty value
  builds.yml
Labels: team-mmi

#24027 fix: add migration for stuck transactions
  app/scripts/migrations/117.test.ts
  app/scripts/migrations/117.ts
  app/scripts/migrations/index.js
Labels: team-confirmations-system

#23393 feat: metamask notifications controller
  app/scripts/controllers/metamask-notifications/constants/constants.ts
  app/scripts/controllers/metamask-notifications/constants/notification-schema.ts
  app/scripts/controllers/metamask-notifications/metamask-notifications.test.ts
  app/scripts/controllers/metamask-notifications/metamask-notifications.ts
  app/scripts/controllers/metamask-notifications/mocks/mock-feature-announcements.ts
  app/scripts/controllers/metamask-notifications/mocks/mock-notification-trigger.ts
  app/scripts/controllers/metamask-notifications/mocks/mock-notification-user-storage.ts
  app/scripts/controllers/metamask-notifications/mocks/mock-onchain-notifications.ts
  app/scripts/controllers/metamask-notifications/mocks/mock-raw-notifications.ts
  app/scripts/controllers/metamask-notifications/processors/process-feature-announcement.test.ts
  app/scripts/controllers/metamask-notifications/processors/process-feature-announcement.ts
  app/scripts/controllers/metamask-notifications/processors/process-notifications.test.ts
  app/scripts/controllers/metamask-notifications/processors/process-notifications.ts
  app/scripts/controllers/metamask-notifications/processors/process-onchain-notifications.test.ts
  app/scripts/controllers/metamask-notifications/processors/process-onchain-notifications.ts
  app/scripts/controllers/metamask-notifications/services/feature-announcements.test.ts
  app/scripts/controllers/metamask-notifications/services/feature-announcements.ts
  app/scripts/controllers/metamask-notifications/services/onchain-notifications.test.ts
  app/scripts/controllers/metamask-notifications/services/onchain-notifications.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/feature-announcement.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/type-action.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/type-feature-announcement.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/type-link.ts
  app/scripts/controllers/metamask-notifications/types/notification/notification.ts
  app/scripts/controllers/metamask-notifications/types/on-chain-notification/on-chain-notification.ts
  app/scripts/controllers/metamask-notifications/types/on-chain-notification/schema.d.ts
  app/scripts/controllers/metamask-notifications/types/type-utils.ts
  app/scripts/controllers/metamask-notifications/types/types.ts
  app/scripts/controllers/metamask-notifications/types/user-storage/user-storage.ts
  app/scripts/controllers/metamask-notifications/utils/utils.test.ts
  app/scripts/controllers/metamask-notifications/utils/utils.ts
  builds.yml
  jest.config.js
  package.json
  test/env.js
  yarn.lock
Labels: team-notifications

#24167 fix: duplicate simulation metrics
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
  ui/pages/confirmations/components/simulation-details/useLoadingTime.test.ts
  ui/pages/confirmations/components/simulation-details/useLoadingTime.ts
  ui/pages/confirmations/components/simulation-details/useSimulationMetrics.test.ts
  ui/pages/confirmations/components/simulation-details/useSimulationMetrics.ts
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
Labels: team-confirmations-system

#23870 feat: Add updated UI for Snap install and update flows
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/accounts/common.ts
  test/e2e/accounts/create-snap-account.spec.ts
  test/e2e/flask/user-operations.spec.ts
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-clientstatus.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/snaps/test-snap-get-file.spec.js
  test/e2e/snaps/test-snap-get-locale.spec.js
  test/e2e/snaps/test-snap-getentropy.spec.js
  test/e2e/snaps/test-snap-homepage.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-lifecycle.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-namelookup.spec.js
  test/e2e/snaps/test-snap-networkaccess.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-revoke-perm.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-siginsights.spec.js
  test/e2e/snaps/test-snap-txinsights-v2.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-uilinks.spec.js
  test/e2e/snaps/test-snap-update-component.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  test/e2e/snaps/test-snap-wasm.spec.js
  ui/components/app/snaps/snap-install-warning/snap-install-warning.js
  ui/components/app/snaps/snap-permissions-list/snap-permissions-list.js
  ui/components/app/snaps/update-snap-permission-list/update-snap-permission-list.js
  ui/pages/permissions-connect/snaps/snap-install/index.scss
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
  ui/pages/permissions-connect/snaps/snap-result/snap-result.js
  ui/pages/permissions-connect/snaps/snap-update/index.scss
  ui/pages/permissions-connect/snaps/snap-update/snap-update.js
  ui/pages/snaps/snap-view/snap-settings.js
Labels: team-snaps-platform

#24093 fix: issue where per dapp selected network proxies are not synced correct across preference toggle
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE, amon-hen-blocker

#24147 fix: hover styles of scroll to bottom button
  ui/pages/confirmations/components/confirm/scroll-to-bottom/index.scss
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#24171 chore: Update ppom package
  package.json
  test/e2e/snaps/test-snap-clientstatus.spec.js
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  yarn.lock
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR

#24135 fix: address UI review feedbacks on signature request re-designed pages
  ui/components/app/confirm/info/row/row.tsx
  ui/pages/confirmations/components/confirm/header/__snapshots__/header.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/header-info.tsx
  ui/pages/confirmations/components/confirm/header/header.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/__snapshots__/personal-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#24173 fix: transaction created after a pending signature request does not load on page and show continuous spinner
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-navigation/confirm-page-container-navigation.component.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#24197 chore: disable sonarcloud in github actions
  .github/workflows/sonar.yml
Labels: team-extension-platform, needs-dev-review
