Repository MetaMask/metamask-extension, pull requests merged in 2024-10, with the labels that each got.

#27391 feat: Custom header for wallet initiated confirmations
  app/_locales/en/messages.json
  test/data/confirmations/contract-interaction.ts
  test/data/confirmations/helper.ts
  test/data/confirmations/set-approval-for-all.ts
  test/data/confirmations/token-approve.ts
  test/data/confirmations/token-transfer.ts
  ui/pages/confirmations/components/confirm/header/__snapshots__/header.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/__snapshots__/wallet-initiated-header.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/header.test.tsx
  ui/pages/confirmations/components/confirm/header/header.tsx
  ui/pages/confirmations/components/confirm/header/wallet-initiated-header.test.tsx
  ui/pages/confirmations/components/confirm/header/wallet-initiated-header.tsx
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-received-token.test.ts
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/token-transfer.stories.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/token-transfer.test.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/token-transfer.tsx
  ui/pages/confirmations/components/confirm/nav/nav.tsx
  ui/pages/confirmations/components/confirm/title/hooks/useCurrentSpendingCap.test.ts
  ui/pages/confirmations/utils/confirm.ts
Labels: team-confirmations

#27478 fix: updated ui for connect and review page
  app/_locales/en/messages.json
  ui/components/multichain/pages/review-permissions-page/site-cell/__snapshots__/site-cell-connection-list-item.test.js.snap
  ui/components/multichain/pages/review-permissions-page/site-cell/site-cell-connection-list-item.js
  ui/components/multichain/pages/review-permissions-page/site-cell/site-cell-connection-list-item.test.js
  ui/components/multichain/pages/review-permissions-page/site-cell/site-cell.tsx
  ui/pages/permissions-connect/connect-page/__snapshots__/connect-page.test.tsx.snap
  ui/pages/permissions-connect/connect-page/connect-page.test.tsx
  ui/pages/permissions-connect/connect-page/connect-page.tsx
  ui/pages/permissions-connect/index.scss
  ui/pages/routes/routes.component.js
Labels: team-wallet-ux, needs-assets-ux-review

#27488 fix: Allow state updates in Snaps interfaces to state values that are falsy
  ui/components/app/snaps/snap-ui-dropdown/snap-ui-dropdown.tsx
  ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx
  ui/components/app/snaps/snap-ui-selector/snap-ui-selector.tsx
  ui/contexts/snaps/snap-interface.tsx
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#27429 fix(snaps): Keep focus on input if interface re-renders
  ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx
  ui/contexts/snaps/snap-interface.tsx
Labels: team-snaps-platform

#27530 fix: genUnapprovedApproveConfirmation import path
  ui/pages/confirmations/hooks/useLedgerConnection.test.ts
Labels: team-confirmations

#27529 fix(NOTIFY-1171): account syncing performance and bug fixes
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-notifications

#27538 chore: Master sync following v12.3.1
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#27531 fix(snaps): Fix custom UI buttons submitting forms
  ui/components/app/snaps/snap-ui-button/snap-ui-button.tsx
Labels: team-snaps-platform

#27541 chore: Resolve conflict v12.4.0
  CHANGELOG.md
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/nft-detection-metrics.spec.js
  test/e2e/tests/metrics/token-detection-metrics.spec.js
  test/e2e/tests/metrics/wallet-created.spec.js
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/notification-detail-button/notification-detail-button.tsx
  ui/pages/onboarding-flow/creation-successful/creation-successful.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
Labels: team-extension-platform

#27427 feat: Enable gas included swaps
  app/_locales/en/messages.json
  app/scripts/controllers/swaps/swaps.test.ts
  app/scripts/controllers/swaps/swaps.types.ts
  shared/lib/swaps-utils.js
  shared/lib/swaps-utils.test.js
  test/jest/mock-store.js
  ui/ducks/swaps/swaps.js
  ui/ducks/swaps/swaps.test.js
  ui/helpers/constants/zendesk-url.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
  ui/pages/swaps/prepare-swap-page/review-quote.js
  ui/pages/swaps/prepare-swap-page/review-quote.test.js
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.js
  ui/pages/swaps/view-quote/view-quote.js
  ui/store/actions.ts
Labels: team-transactions

#27264 feat: remove squiggle animation from swaps smart transactions
  ui/pages/swaps/smart-transaction-status/index.scss
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.js
Labels: team-swaps, INVALID-PR-TEMPLATE

#27534 fix: [cherry-pick][V12.5.0] account syncing fixes
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/metametrics.ts
  yarn.lock
Labels: team-notifications, release-12.5.0

#27192 test: merge queue 2
  test/e2e/tests/account/account-hide-unhide.spec.js
Labels: team-extension-platform

#27489 feat(snaps): Connect `getCurrencyRate` hook to `multichainRateController`
  app/scripts/metamask-controller.js
Labels: team-snaps-platform

#27560 fix: flaky test `4byte setting does not try to get contract method name from 4byte when the setting is off`
  test/e2e/tests/settings/4byte-directory.spec.js
Labels: team-extension-platform, flaky tests, area-qa

#27564 fix: Apply flex to Snaps buttons only when containing images and icons
  ui/components/app/snaps/snap-ui-button/index.scss
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#27565 fix: flaky test `Backup and Restore should backup the account settings`
  test/e2e/tests/settings/backup-restore.spec.js
Labels: team-extension-platform, flaky tests, area-qa

#27518 fix: AmonHenV2 connection flow incremental permitted chain approval and account address case comparison
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
Labels: team-wallet-api-platform

#27185 chore: start upgrade to React Router v6
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/app/assets/nfts/nft-details/nft-full-image.tsx
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/pages/connections/connections.test.tsx
  ui/components/multichain/pages/connections/connections.tsx
  ui/components/multichain/pages/review-permissions-page/review-permissions-page.tsx
  ui/pages/asset/asset.tsx
  ui/pages/bridge/index.tsx
  ui/pages/confirmations/confirm/stories/utils.tsx
  ui/pages/index.js
  yarn.lock
Labels: team-tiger

#27543 feat: codefence Account Watcher for flask
  app/scripts/controllers/preferences-controller.ts
  app/scripts/lib/snap-keyring/account-watcher-snap.ts
  app/scripts/metamask-controller.js
  app/scripts/snaps/preinstalled-snaps.ts
  shared/constants/metametrics.ts
  test/e2e/flask/create-watch-account.spec.ts
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/pages/settings/experimental-tab/experimental-tab.component.tsx
Labels: flask, team-accounts, INVALID-PR-TEMPLATE

#27520 Do not assert unsupported required scopes
  app/scripts/lib/multichain-api/wallet-createSession/handler.js
  app/scripts/lib/multichain-api/wallet-createSession/handler.test.js
Labels: team-wallet-api-platform

#27574 fix: mock locale in unit test
  ui/components/app/assets/token-cell/token-cell.test.tsx
Labels: team-assets

#27577 Cherry-pick ab37660 (PR ##27543) to V12.4.0
  app/scripts/controllers/preferences.js
  app/scripts/lib/snap-keyring/account-watcher-snap.ts
  app/scripts/metamask-controller.js
  app/scripts/snaps/preinstalled-snaps.ts
  shared/constants/metametrics.ts
  test/e2e/flask/create-watch-account.spec.ts
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/pages/settings/experimental-tab/experimental-tab.component.tsx
Labels: team-accounts, INVALID-PR-TEMPLATE, release-12.4.0

#27559 chore: Use "gas_included" event prop
  shared/modules/metametrics.test.ts
  shared/modules/metametrics.ts
  ui/ducks/swaps/swaps.js
Labels: team-transactions

#27557 fix: flaky test `Address Book Edit entry in address book` due to race condition with mmi menu
  test/e2e/page-objects/pages/header-navbar.ts
  test/e2e/tests/settings/address-book.spec.js
  test/e2e/tests/settings/auto-lock.spec.js
  test/e2e/tests/settings/backup-restore.spec.js
  test/e2e/tests/settings/clear-activity.spec.js
  test/e2e/tests/settings/ipfs-ens-resolution.spec.js
  test/e2e/tests/settings/ipfs-toggle.spec.js
  test/e2e/tests/settings/settings-general.spec.js
  test/e2e/tests/settings/state-logs.spec.js
  test/e2e/tests/tokens/nft/auto-detect-nft.spec.js
Labels: team-extension-platform, flaky tests, area-qa

#27432 fix(27428): fix if we type enter anything followed by a \ in settings search
  ui/helpers/utils/settings-search.js
  ui/helpers/utils/settings-search.test.js
Labels: team-extension-platform

#27567 fix: flaky test `Import flow allows importing multiple tokens from search`
  test/e2e/tests/tokens/import-tokens.spec.js
Labels: team-extension-platform, flaky tests, area-qa

#27600 fix(snaps): `Copyable` more button color
  ui/components/app/snaps/copyable/index.scss
  ui/components/app/snaps/show-more/show-more.js
Labels: team-snaps-platform

#27599 fix: flaky test `Block Explorer links to the token tracker in the explorer`
  test/e2e/tests/dapp-interactions/block-explorer.spec.js
Labels: team-extension-platform, flaky tests, area-qa

#27596 fix: Recreate offscreen document if it already exists
  app/scripts/offscreen.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE, team-snaps-platform

#27361 feat: add power users survey support
  app/scripts/controllers/app-state.js
  app/scripts/metamask-controller.js
  builds.yml
  privacy-snapshot.json
  shared/constants/accounts.ts
  shared/constants/metametrics.ts
  test/e2e/mock-e2e.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/survey/survey.spec.js
  ui/components/multichain/toast/toast.tsx
  ui/components/ui/survey-toast/__snapshots__/survey-toast.test.tsx.snap
  ui/components/ui/survey-toast/index.ts
  ui/components/ui/survey-toast/survey-toast.test.tsx
  ui/components/ui/survey-toast/survey-toast.tsx
  ui/pages/routes/routes.component.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-wallet-ux

#27573 fix: Max approval and array value spending cap bugs
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts
Labels: team-confirmations

#27471 Jl/caip multichain/fix connection flow for permitted chains
  app/scripts/controllers/permissions/background-api.js
  app/scripts/controllers/permissions/background-api.test.js
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-permittedChains.test.ts
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-permittedChains.ts
  app/scripts/lib/multichain-api/wallet-createSession/handler.js
  app/scripts/lib/multichain-api/wallet-createSession/handler.test.js
  app/scripts/lib/multichain-api/wallet-createSession/helpers.test.ts
  app/scripts/lib/multichain-api/wallet-createSession/helpers.ts
  app/scripts/lib/multichain-api/wallet-requestPermissions.js
  app/scripts/lib/multichain-api/wallet-requestPermissions.test.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.test.js
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.js
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.test.js
  app/scripts/metamask-controller.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.tsx
  ui/components/multichain/pages/review-permissions-page/site-cell/site-cell.tsx
  ui/pages/permissions-connect/connect-page/connect-page.tsx
Labels: team-wallet-api-platform

#27549 Handle getCaveat missing permission throws properly
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-middleware.js
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-middleware.test.js
  app/scripts/lib/multichain-api/wallet-getSession.js
  app/scripts/lib/multichain-api/wallet-getSession.test.js
  app/scripts/lib/multichain-api/wallet-invokeMethod.js
  app/scripts/lib/multichain-api/wallet-invokeMethod.test.js
Labels: team-wallet-api-platform

#27620 chore: fix deps audit
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  yarn.lock
Labels: team-extension-platform

#27381 fix: "Dapp viewed Event @no-mmi is sent when refreshing da..." flaky test
  test/e2e/tests/metrics/dapp-viewed.spec.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE, area-qa

#27594 fix: add amount row for contract deployment
  test/data/confirmations/contract-interaction.ts
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
Labels: QA Passed, team-confirmations

#27583 fix: revert jest collect coverage patterns
  jest.config.js
Labels: INVALID-PR-TEMPLATE, team-confirmations

#27586 fix: disable transaction data decode if deployment
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.ts
  ui/pages/confirmations/components/confirm/info/hooks/useFourByte.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useFourByte.ts
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.test.tsx
Labels: QA Passed, team-confirmations

#27258 feat: Migrate AccountTrackerController to BaseController v2
  app/scripts/controllers/account-tracker-controller.test.ts
  app/scripts/controllers/account-tracker-controller.ts
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/controllers/mmi-controller.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  development/ts-migration-dashboard/files-to-convert.json
  shared/constants/mmi-controller.ts
Labels: team-wallet-framework

#27404 CAIP Multichain: deep clone flattened scopeObjects
  app/scripts/lib/multichain-api/scope/transform.test.ts
  app/scripts/lib/multichain-api/scope/transform.ts
Labels: team-wallet-api-platform

#27604 fix: fix reading address from market data
  ui/components/app/wallet-overview/aggregated-percentage-overview.tsx
Labels: team-assets

#27633 fix (cherry-pick): disable transaction data decode if deployment (#27586)
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.ts
  ui/pages/confirmations/components/confirm/info/hooks/useFourByte.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useFourByte.ts
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.test.tsx
Labels: team-confirmations

#27627 fix (cherry-pick): add amount row for contract deployment (#27594)
  test/data/confirmations/contract-interaction.ts
  ui/pages/confirmations/components/confirm/info/approve/approve-details/approve-details.stories.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.stories.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
Labels: team-confirmations

#27377 feat: Integrate MetaMask links into Snaps `Link` component
  app/scripts/metamask-controller.js
  ui/components/app/snaps/snap-ui-link/snap-ui-link.js
  ui/hooks/snaps/useSnapNavigation.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26213 chore: set bridge dest network, tokens and top assets
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/bridge/bridge-controller.test.ts
  app/scripts/controllers/bridge/bridge-controller.ts
  app/scripts/controllers/bridge/constants.ts
  app/scripts/controllers/bridge/types.ts
  app/scripts/metamask-controller.js
  test/e2e/default-fixture.js
  test/e2e/fixture-builder.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/jest/mock-store.js
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/bridge.ts
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
  ui/pages/bridge/bridge.util.test.ts
  ui/pages/bridge/bridge.util.ts
  ui/pages/swaps/swaps.util.test.js
  ui/pages/swaps/swaps.util.ts
Labels: team-bridge, INVALID-PR-TEMPLATE

#27521 test: [Snaps E2E] add delay to installed snaps test to reduce flaking
  test/e2e/snaps/test-snap-installed.spec.js
Labels: area-snaps, e2e-test, flaky tests, team-snaps-platform

#26214 chore: set bridge src network, tokens and top assets
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/bridge/bridge-controller.test.ts
  app/scripts/controllers/bridge/bridge-controller.ts
  app/scripts/controllers/bridge/constants.ts
  app/scripts/controllers/bridge/types.ts
  app/scripts/metamask-controller.js
  test/e2e/default-fixture.js
  test/e2e/fixture-builder.js
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
  ui/hooks/bridge/useBridging.test.ts
  ui/hooks/bridge/useBridging.ts
  ui/pages/bridge/index.test.tsx
  ui/pages/bridge/index.tsx
Labels: team-bridge

#27284 chore: update accounts related packages
  package.json
  test/data/mock-state.json
  test/e2e/constants.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
  yarn.lock
Labels: team-accounts, QA Passed, needs-dev-review

#27636 fix(btc): disable balanceIsCached flag
  ui/components/app/wallet-overview/btc-overview.test.tsx
  ui/components/app/wallet-overview/btc-overview.tsx
Labels: team-accounts

#27582 fix: fix sentry reading null
  app/scripts/metamask-controller.js
Labels: team-assets

#27584 fix: fix sentry reading undefined
  ui/components/app/assets/nfts/nfts-items/nfts-items.js
Labels: team-assets

#27653 cherry-pick: Recreate offscreen document if it already exists
  app/scripts/offscreen.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE, team-snaps-platform

#27606 test: removing race condition for asserting inner values (PR-#1)
  test/e2e/tests/account/account-details.spec.js
  test/e2e/tests/confirmations/alerts/insufficient-funds.spec.ts
  test/e2e/tests/confirmations/navigation.spec.ts
  test/e2e/tests/confirmations/signatures/malicious-signatures.spec.ts
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  test/e2e/tests/confirmations/signatures/personal-sign.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v3.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v4.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data.spec.ts
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
  test/e2e/tests/portfolio/portfolio-site.spec.js
  test/e2e/tests/settings/terms-of-use.spec.js
Labels: team-extension-platform, flaky tests, area-qa

#27605 fix: Design papercuts for redesigned transactions
  test/integration/confirmations/signatures/permit.test.tsx
  test/integration/confirmations/signatures/personalSign.test.tsx
  ui/components/app/confirm/info/row/__snapshots__/address.test.tsx.snap
  ui/components/app/confirm/info/row/__snapshots__/expandable-row.test.tsx.snap
  ui/components/app/confirm/info/row/__snapshots__/row.test.tsx.snap
  ui/components/app/confirm/info/row/alert-row/__snapshots__/alert-row.test.tsx.snap
  ui/components/app/confirm/info/row/row.tsx
  ui/components/app/name/__snapshots__/name.test.tsx.snap
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/name/name.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-details/__snapshots__/approve-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-details/approve-details.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/__snapshots__/approve-static-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve.tsx
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/__snapshots__/edit-spending-cap-modal.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
  ui/pages/confirmations/components/confirm/info/approve/spending-cap/__snapshots__/spending-cap.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/base-transaction-info/__snapshots__/base-transaction-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/info.test.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/__snapshots__/personal-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/__snapshots__/siwe-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/__snapshots__/set-approval-for-all-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/revoke-set-approval-for-all-static-simulation/__snapshots__/revoke-set-approval-for-all-static-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/set-approval-for-all-info.test.tsx
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/set-approval-for-all-info.tsx
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/set-approval-for-all-static-simulation/__snapshots__/set-approval-for-all-static-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/__snapshots__/advanced-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/confirm-loader/__snapshots__/confirm-loader.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/confirm-loader/confirm-loader.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/confirm-loader/confirm-loader.tsx
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/__snapshots__/edit-gas-fees-row.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/__snapshots__/gas-fees-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-row/__snapshots__/gas-fees-row.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/__snapshots__/gas-fees-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/__snapshots__/transaction-data.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/__snapshots__/transaction-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/value-display/__snapshots__/value-display.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/__snapshots__/dataTree.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data-v1/__snapshots__/typedSignDataV1.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data/__snapshots__/typedSignData.test.tsx.snap
  ui/pages/confirmations/components/confirm/title/hooks/useCurrentSpendingCap.ts
  ui/pages/confirmations/components/confirm/title/title.test.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/confirm.test.tsx
Labels: team-confirmations

#27603 feat: change survey timeout time from a week to a day
  ui/components/ui/survey-toast/survey-toast.tsx
Labels: team-wallet-ux

#27611 feat: support Etherscan API keys
  .metamaskrc.dist
  app/scripts/metamask-controller.js
  builds.yml
  package.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/index.js
  yarn.lock
Labels: QA Passed, team-confirmations

#27637 fix(btc): do not show percentage for tokens
  ui/components/app/assets/token-cell/token-cell.test.tsx
  ui/components/multichain/token-list-item/token-list-item.tsx
Labels: team-accounts

#27585 fix: bump api-specs on caip-multichain feature branch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#27632 build: add lottie-web dependency to extension
  jest.config.js
  package.json
  test/jest/setup.js
  ui/components/component-library/lottie-animation/index.ts
  ui/components/component-library/lottie-animation/lottie-animation.test.tsx
  ui/components/component-library/lottie-animation/lottie-animation.tsx
  yarn.lock
Labels: team-transactions

#27663 feat: Double Sentry performance trace sample rate (#27468)
  app/scripts/lib/setupSentry.js
Labels: team-wallet-framework, team-extension-platform

#27673 chore: fix deps audit (#27620)
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  yarn.lock
Labels: team-wallet-framework

#27674 chore: Merge v12.4.0 into v12.5.0
  CHANGELOG.md
  app/scripts/controllers/preferences-controller.ts
  app/scripts/controllers/swaps/swaps.test.ts
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/setupSentry.js
  app/scripts/lib/snap-keyring/account-watcher-snap.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
  app/scripts/snaps/preinstalled-snaps.ts
  shared/constants/metametrics.ts
  test/data/confirmations/contract-interaction.ts
  test/e2e/flask/create-watch-account.spec.ts
  test/e2e/tests/transaction/send-edit.spec.js
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.ts
  ui/pages/confirmations/components/confirm/info/hooks/useFourByte.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useFourByte.ts
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.test.tsx
  ui/pages/settings/experimental-tab/experimental-tab.component.tsx
  ui/selectors/accounts.test.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24571 feat: Adding delete metametrics data to security and privacy tab
  app/_locales/en/messages.json
  privacy-snapshot.json
  shared/constants/metametrics.ts
  test/e2e/tests/metrics/delete-metametrics-data.spec.ts
  test/e2e/webdriver/driver.js
  test/e2e/webdriver/types.ts
  ui/components/app/clear-metametrics-data/clear-metametrics-data.test.tsx
  ui/components/app/clear-metametrics-data/clear-metametrics-data.tsx
  ui/components/app/clear-metametrics-data/index.ts
  ui/components/app/data-deletion-error-modal/data-deletion-error-modal.test.tsx
  ui/components/app/data-deletion-error-modal/data-deletion-error-modal.tsx
  ui/components/app/data-deletion-error-modal/index.ts
  ui/ducks/app/app.test.js
  ui/ducks/app/app.ts
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/delete-metametrics-data-button/delete-metametrics-data-button.test.tsx
  ui/pages/settings/security-tab/delete-metametrics-data-button/delete-metametrics-data-button.tsx
  ui/pages/settings/security-tab/delete-metametrics-data-button/index.ts
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/security-tab/security-tab.test.js
  ui/selectors/metametrics.js
  ui/selectors/metametrics.test.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actionConstants.ts
Labels: team-extension-platform, marketing-consent

#27078 refactor: routes constants
  ui/helpers/constants/routes.ts
Labels: team-tiger

#27339 fix: banner alert to render multiple general alerts
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/alert-system/alert-modal/alert-modal.tsx
  ui/components/app/alert-system/alert-modal/index.scss
  ui/components/app/alert-system/confirm-alert-modal/confirm-alert-modal.tsx
  ui/components/app/alert-system/general-alert/general-alert.tsx
  ui/components/app/alert-system/multiple-alert-modal/multiple-alert-modal.test.tsx
  ui/components/app/alert-system/multiple-alert-modal/multiple-alert-modal.tsx
  ui/hooks/useAlerts.test.ts
  ui/hooks/useAlerts.ts
  ui/pages/confirmations/components/confirm/title/title.test.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
Labels: team-confirmations

#27690 fix(btc): fix address validation
  package.json
  shared/lib/multichain.test.ts
  shared/lib/multichain.ts
  yarn.lock
Labels: team-accounts

#27664 test: removing race condition for asserting inner values (PR-#2)
  test/e2e/flask/btc/create-btc-account.spec.ts
  test/e2e/tests/confirmations/signatures/malicious-signatures.spec.ts
  test/e2e/tests/confirmations/signatures/personal-sign.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v3.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v4.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data.spec.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  test/e2e/tests/confirmations/signatures/siwe.spec.ts
  test/e2e/tests/dapp-interactions/dapp-tx-edit.spec.js
  test/e2e/tests/dapp-interactions/encrypt-decrypt.spec.js
  test/e2e/tests/dapp-interactions/failing-contract.spec.js
Labels: team-extension-platform, flaky tests, area-qa

#27677 Get session revoke session should not throw
  app/scripts/lib/multichain-api/wallet-createSession/handler.js
  app/scripts/lib/multichain-api/wallet-createSession/handler.test.js
  app/scripts/lib/multichain-api/wallet-getSession.js
  app/scripts/lib/multichain-api/wallet-getSession.test.js
  app/scripts/lib/multichain-api/wallet-revokeSession.js
  app/scripts/lib/multichain-api/wallet-revokeSession.test.js
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#27634 fix: issue with default nonce value being wrong when switching networks between transactions
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
Labels: team-confirmations, release-12.4.0

#23732 refactor: Typescript conversion of log-web3-shim-usage.js
  app/scripts/lib/rpc-method-middleware/handlers/get-provider-state.ts
  app/scripts/lib/rpc-method-middleware/handlers/log-web3-shim-usage.js
  app/scripts/lib/rpc-method-middleware/handlers/log-web3-shim-usage.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/log-web3-shim-usage.ts
  app/scripts/lib/rpc-method-middleware/handlers/types.ts
Labels: team-extension-platform

#27666 feat(NOTIFY-1193): add profile sync dev menu
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/hooks/metamask-notifications/useProfileSyncing.test.tsx
  ui/hooks/metamask-notifications/useProfileSyncing.ts
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/developer-options-tab/developer-options-tab.tsx
  ui/pages/settings/developer-options-tab/profile-sync.tsx
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: team-notifications

#27226 fix: Disable redirecting Extension users using beta & flask build and dev env to the existing offboarding page
  app/scripts/controllers/metametrics.js
Labels: team-extension-platform

#27550 perf: add tags to UI startup trace
  app/scripts/lib/setupSentry.js
  package.json
  shared/lib/trace.test.ts
  shared/lib/trace.ts
  ui/helpers/utils/tags.test.ts
  ui/helpers/utils/tags.ts
  ui/index.js
  ui/selectors/nft.test.ts
  ui/selectors/nft.ts
  ui/selectors/selectors.js
  ui/store/store.ts
  yarn.lock
Labels: team-extension-platform, needs-dev-review, team-confirmations, team-tiger

#27558 chore: Fix changelog for v12.4.0
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery

#27117 fix: allow getAddTransactionRequest to pass through other params
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-swaps, team-extension-platform

#27659 test: Convert json-rpc e2e tests to TypeScript
  test/e2e/json-rpc/eth_accounts.spec.ts
  test/e2e/json-rpc/eth_call.spec.ts
  test/e2e/json-rpc/eth_chainId.spec.js
  test/e2e/json-rpc/eth_chainId.spec.ts
  test/e2e/json-rpc/eth_coinbase.spec.ts
  test/e2e/json-rpc/eth_estimateGas.spec.ts
  test/e2e/json-rpc/eth_gasPrice.spec.js
  test/e2e/json-rpc/eth_gasPrice.spec.ts
  test/e2e/json-rpc/eth_newBlockFilter.spec.ts
  test/e2e/json-rpc/eth_requestAccounts.spec.ts
  test/e2e/json-rpc/eth_subscribe.spec.js
  test/e2e/json-rpc/eth_subscribe.spec.ts
  test/e2e/page-objects/flows/login.flow.ts
  test/e2e/page-objects/pages/homepage.ts
Labels: team-extension-platform, team-ai

#27268 ci: make git-diff-develop work for PRs from foreign repos
  .circleci/config.yml
  .circleci/scripts/git-diff-develop.ts
Labels: team-lavamoat, INVALID-PR-TEMPLATE

#27184 feat: Sort/Import Tokens in Extension
  .storybook/test-data.js
  app/_locales/en/messages.json
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
  app/scripts/controllers/preferences-controller.ts
  app/scripts/migrations/130.test.ts
  app/scripts/migrations/130.ts
  app/scripts/migrations/index.js
  shared/constants/metametrics.ts
  test/data/mock-state.json
  test/e2e/default-fixture.js
  test/e2e/fixture-builder.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/e2e/tests/tokens/add-hide-token.spec.js
  test/e2e/tests/tokens/custom-token-add-approve.spec.js
  test/e2e/tests/tokens/custom-token-send-transfer.spec.js
  test/e2e/tests/tokens/token-details.spec.ts
  test/e2e/tests/tokens/token-list.spec.ts
  test/e2e/tests/tokens/token-sort.spec.ts
  test/e2e/tests/transaction/change-assets.spec.js
  ui/components/app/app-components.scss
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/asset-list/asset-list-control-bar/index.scss
  ui/components/app/assets/asset-list/asset-list-control-bar/index.ts
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/asset-list/import-control/import-control.tsx
  ui/components/app/assets/asset-list/import-control/index.ts
  ui/components/app/assets/asset-list/native-token/index.ts
  ui/components/app/assets/asset-list/native-token/native-token.tsx
  ui/components/app/assets/asset-list/native-token/use-native-token-balance.ts
  ui/components/app/assets/asset-list/sort-control/index.scss
  ui/components/app/assets/asset-list/sort-control/index.ts
  ui/components/app/assets/asset-list/sort-control/sort-control.test.tsx
  ui/components/app/assets/asset-list/sort-control/sort-control.tsx
  ui/components/app/assets/token-cell/token-cell.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/app/assets/util/sort.test.ts
  ui/components/app/assets/util/sort.ts
  ui/components/multichain/account-overview/account-overview-btc.test.tsx
  ui/components/multichain/import-token-link/__snapshots__/import-token-link.test.js.snap
  ui/components/multichain/import-token-link/import-token-link.test.js
  ui/components/multichain/import-token-link/import-token-link.tsx
  ui/components/multichain/ramps-card/index.scss
  ui/css/design-system/_colors.scss
  ui/helpers/constants/design-system.ts
  ui/helpers/utils/common.util.js
  ui/hooks/useAccountTotalFiatBalance.js
  ui/hooks/useAccountTotalFiatBalance.test.js
  ui/hooks/useMultichainAccountTotalFiatBalance.test.tsx
  ui/pages/routes/routes.component.test.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: team-assets

#27705 fix (cherry-pick): change survey timeout time from a week to a day (#27603)
  ui/components/ui/survey-toast/survey-toast.tsx
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#27714 fix: UI startup with no Sentry DSN
  shared/lib/trace.test.ts
  shared/lib/trace.ts
Labels: team-confirmations, team-tiger

#27715 test: batch tx mmi
  test/e2e/tests/request-queuing/batch-txs-per-dapp-extra-tx.spec.js
Labels: team-extension-platform

#27628 fix(btc): fetch btc balance right after account creation
  app/scripts/lib/accounts/BalancesController.ts
  app/scripts/lib/accounts/BalancesTracker.ts
  app/scripts/lib/snap-keyring/bitcoin-wallet-snap.ts
  shared/lib/accounts/bitcoin-wallet-snap.ts
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/hooks/accounts/useBitcoinWalletSnapClient.test.ts
  ui/hooks/accounts/useBitcoinWalletSnapClient.ts
Labels: team-accounts

#27693 fix: Prefer token symbol to token name
  ui/components/app/confirm/info/row/address.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/approve-static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/approve/revoke-static-simulation/revoke-static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/revoke-set-approval-for-all-static-simulation/revoke-set-approval-for-all-static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/set-approval-for-all-static-simulation/set-approval-for-all-static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/value-display/value-display.tsx
Labels: team-confirmations

#27718 test: multi dapp
  test/e2e/tests/request-queuing/multi-dapp-sendTx-revokePermission.spec.js
  test/e2e/tests/request-queuing/ui.spec.js
Labels: team-extension-platform

#27725 test: chainid, switch custom net, batch tx diff, snaps
  test/e2e/snaps/test-snap-txinsights-v2.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/tests/network/switch-custom-network.spec.js
  test/e2e/tests/request-queuing/batch-txs-per-dapp-diff-network.spec.js
  test/e2e/tests/request-queuing/chainid-check.spec.js
Labels: team-extension-platform

#27672 fix: Limit amount of decimals on spending cap modal
  app/_locales/en/messages.json
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
Labels: team-confirmations

#27734 test: should switch to the dapps network automatically when handling sendTransaction calls
  test/e2e/tests/request-queuing/multiple-networks-dapps-txs.spec.js
Labels: team-extension-platform

#27726 fix(multichain): fix getMultichainCurrentCurrency selector
  ui/selectors/multichain.ts
Labels: team-accounts

#27729 chore: Master sync
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#27708 fix: trying to access an undefined object in swaps review quote compo…
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
Labels: area-swaps, team-bridge, team-swaps, INVALID-PR-TEMPLATE

#27669 fix: fix api spec multichain bump issues
  .circleci/config.yml
  package.json
  test/e2e/api-specs/ConfirmationRejectionRule.ts
  test/e2e/api-specs/MultichainAuthorizationConfirmation.ts
  test/e2e/api-specs/MultichainAuthorizationConfirmationErrors.ts
  test/e2e/run-api-specs-multichain.ts
  test/e2e/run-openrpc-api-test-coverage.ts
  yarn.lock
Labels: team-wallet-api-platform

#27741 fix: get wallet_getSession/revokeSession passing
  test/e2e/api-specs/ConfirmationRejectionRule.ts
  test/e2e/helpers.js
  test/e2e/run-api-specs-multichain.ts
Labels: team-wallet-api-platform

#27745 Multichain: Lint
  app/scripts/lib/multichain-api/MultichainMiddlewareManager.test.ts
  app/scripts/lib/multichain-api/MultichainSubscriptionManager.ts
  app/scripts/lib/multichain-api/scope/supported.test.ts
  app/scripts/migrations/131.test.ts
  ui/pages/permissions-connect/connect-page/connect-page.tsx
  yarn.lock
Labels: team-wallet-api-platform

#27743 fix: remove old phishfort list from clients
  app/scripts/migrations/126.1.test.ts
  app/scripts/migrations/126.1.ts
  app/scripts/migrations/index.js
Labels: INVALID-PR-TEMPLATE, team-product-safety

#27548 ci: followup to CircleCI Sentry reporting
  .circleci/scripts/git-diff-develop.ts
  app/scripts/lib/manifestFlags.ts
  app/scripts/lib/setupSentry.js
  test/e2e/set-manifest-flags.ts
  test/e2e/tests/metrics/errors.spec.js
  test/e2e/tests/metrics/sessions.spec.ts
  test/e2e/tests/metrics/traces.spec.ts
Labels: team-tiger

#27629 feat: upgrade assets-controllers to v38.2.0
  .yarn/patches/@metamask-assets-controllers-npm-38.2.0-40af2afaa7.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-assets, needs-assets-ux-review

#27746 fix: remove old phishfort list from clients (#27743)
  app/scripts/migrations/126.1.test.ts
  app/scripts/migrations/126.1.ts
  app/scripts/migrations/index.js
Labels: INVALID-PR-TEMPLATE, team-product-safety

#27749 chore: bump profile-sync-controller to 0.9.7
  package.json
  yarn.lock
Labels: team-notifications

#27757 fix: cherry pick swaps undefined object access crash hotfix into v12.4.1 RC
  CHANGELOG.md
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
Labels: team-bridge, team-swaps, INVALID-PR-TEMPLATE, release-12.4.1

#26559 feat: add network picker to AssetPicker
  app/_locales/en/messages.json
  test/e2e/tests/multichain/asset-picker-send.spec.ts
  ui/components/multichain/asset-picker-amount/asset-picker-modal/Asset.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/Asset.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/__snapshots__/asset-picker-modal-network.test.tsx.snap
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-network.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-network.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/index.scss
  ui/components/multichain/asset-picker-amount/asset-picker/__snapshots__/asset-picker.test.tsx.snap
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.stories.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/index.scss
  ui/components/multichain/token-list-item/token-list-item.tsx
Labels: team-bridge

#27662 fix(btc): fix jazzicons generations
  package.json
  shared/lib/multichain.test.ts
  shared/lib/multichain.ts
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/ui/jazzicon/jazzicon.component.tsx
  yarn.lock
Labels: team-accounts

#27656 fix: updated toasts component and copy
  app/_locales/en/messages.json
  ui/components/multichain/pages/review-permissions-page/review-permissions-page.tsx
  ui/components/multichain/toast/__snapshots__/toast.test.tsx.snap
  ui/components/multichain/toast/index.scss
  ui/components/multichain/toast/toast.tsx
  ui/components/ui/survey-toast/__snapshots__/survey-toast.test.tsx.snap
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#27754 fix: SIWE signature page displays parsed URI instead of domain
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/__snapshots__/siwe-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/siwe-sign.tsx
Labels: team-confirmations

#27752 fix: issue with Snap title in Snap Authorship Header
  ui/components/app/snaps/snap-authorship-header/snap-authorship-header.js
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
Labels: team-snaps-platform

#27762 fix: Replace 'transaction fees' with 'network fees' in the insufficie…
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/tests/confirmations/alerts/insufficient-funds.spec.ts
  ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.ts
Labels: team-confirmations

#26692 docs: remove outdated Medium link, update "Twitter" to "X"
  README.md
Labels: team-extension-platform

#27709 chore(3212): remove alert settings
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/ph/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  development/ts-migration-dashboard/files-to-convert.json
  test/e2e/tests/settings/settings-search.spec.js
  ui/helpers/constants/routes.ts
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/alerts-tab/alerts-tab.js
  ui/pages/settings/alerts-tab/alerts-tab.scss
  ui/pages/settings/alerts-tab/alerts-tab.stories.js
  ui/pages/settings/alerts-tab/alerts-tab.test.js
  ui/pages/settings/alerts-tab/index.js
  ui/pages/settings/index.scss
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
  ui/pages/settings/settings.stories.js
Labels: team-wallet-ux

#24562 feat: adds the new default settings view to onboarding
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/constants/metametrics.ts
  test/e2e/helpers.js
  test/e2e/tests/network/multi-rpc.spec.ts
  test/e2e/tests/onboarding/onboarding.spec.js
  test/e2e/tests/privacy/basic-functionality.spec.js
  test/integration/onboarding/wallet-created.test.tsx
  ui/components/app/incoming-trasaction-toggle/__snapshots__/incoming-transaction-toggle.test.js.snap
  ui/components/app/incoming-trasaction-toggle/incoming-transaction-toggle.tsx
  ui/pages/onboarding-flow/creation-successful/creation-successful.js
  ui/pages/onboarding-flow/creation-successful/creation-successful.test.js
  ui/pages/onboarding-flow/creation-successful/index.scss
  ui/pages/onboarding-flow/pin-extension/pin-extension.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.test.js
  ui/pages/onboarding-flow/privacy-settings/index.scss
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/onboarding-flow/privacy-settings/setting.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: team-wallet-ux, needs-assets-ux-review, design-qa

#27775 Update CHANGELOG.md for v12.4.1
  CHANGELOG.md
Labels: team-extension-platform

#27771 Move sign methods back into eip155:x
  app/scripts/lib/multichain-api/scope/scope.ts
  test/e2e/run-api-specs-multichain.ts
Labels: team-wallet-api-platform

#27682 Multichain: Fix Subscriptions
  app/scripts/lib/multichain-api/MultichainMiddlewareManager.test.ts
  app/scripts/lib/multichain-api/MultichainMiddlewareManager.ts
  app/scripts/lib/multichain-api/MultichainSubscriptionManager.test.ts
  app/scripts/lib/multichain-api/MultichainSubscriptionManager.ts
  app/scripts/lib/multichain-api/scope/scope.ts
  app/scripts/lib/multichain-api/wallet-createSession/handler.test.js
  app/scripts/metamask-controller.js
  shared/modules/caip-stream.test.ts
  shared/modules/caip-stream.ts
  test/e2e/run-api-specs-multichain.ts
Labels: team-wallet-api-platform

#27777 Assign eth accounts to wallets
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-eth-accounts.test.ts
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-eth-accounts.ts
  test/e2e/run-api-specs-multichain.ts
Labels: team-wallet-api-platform

#27727 perf (cherry-pick): add tags to UI startup trace (#27550)
  app/scripts/lib/setupSentry.js
  package.json
  shared/lib/trace.test.ts
  shared/lib/trace.ts
  ui/helpers/utils/tags.test.ts
  ui/helpers/utils/tags.ts
  ui/index.js
  ui/selectors/nft.test.ts
  ui/selectors/nft.ts
  ui/selectors/selectors.js
  ui/store/store.ts
  yarn.lock
Labels: team-confirmations, team-tiger, release-12.5.0

#27612 feat: support gas fee flows in standard swaps
  app/scripts/metamask-controller.js
  ui/ducks/swaps/swaps.js
  ui/pages/swaps/prepare-swap-page/review-quote.js
  ui/pages/swaps/prepare-swap-page/review-quote.test.js
  ui/pages/swaps/swaps.util.test.js
  ui/pages/swaps/swaps.util.ts
  ui/store/actions.ts
Labels: QA Passed, team-confirmations

#27779 test: Onboarding: Fix vault-decryption-chrome.spec.js
  test/e2e/helpers.js
Labels: team-wallet-ux

#27761 fix: [cherry-pick][V12.5.0] account syncing bugfix
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-notifications, release-12.5.0

#27721 feat(snaps): Add `size` prop to `Heading`
  ui/components/app/snaps/snap-ui-renderer/components/heading.ts
Labels: INVALID-PR-TEMPLATE

#27753 fix(snaps): Restore confirmation switching on routed confirmation
  ui/pages/confirmations/confirmation/confirmation.js
Labels: team-snaps-platform

#27760 test: [POM] Migrate transaction with snap account e2e tests to page object modal
  test/e2e/accounts/snap-account-contract-interaction.spec.ts
  test/e2e/accounts/snap-account-eth-swap.spec.ts
  test/e2e/accounts/snap-account-transfers.spec.ts
  test/e2e/page-objects/flows/send-transaction.flow.ts
  test/e2e/page-objects/flows/snap-simple-keyring.flow.ts
  test/e2e/page-objects/pages/account-list-page.ts
  test/e2e/page-objects/pages/header-navbar.ts
  test/e2e/page-objects/pages/homepage.ts
  test/e2e/page-objects/pages/snap-simple-keyring-page.ts
  test/e2e/tests/account/snap-account-transfers.spec.ts
  test/e2e/tests/transaction/simple-send.spec.ts
Labels: team-extension-platform

#27112 chore: update Trezor Connect to v9.4.0, remove workarounds
  .yarn/patches/@trezor-connect-web-npm-9.3.0-040ab10d9a.patch
  app/manifest/v2/_base.json
  app/manifest/v3/_base.json
  lavamoat/build-system/policy.json
  offscreen/scripts/trezor.ts
  package.json
  yarn.lock
Labels: team-extension-platform

#27772 chore: remove token list display component
  ui/components/app/app-components.scss
  ui/components/app/assets/token-list-display/index.js
  ui/components/app/assets/token-list-display/token-list-display.js
  ui/components/app/assets/token-list-display/token-list-display.scss
Labels: team-assets

#27774 chore: remove old token details page
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/helpers/constants/routes.ts
  ui/pages/pages.scss
  ui/pages/routes/routes.component.js
  ui/pages/token-details/index.js
  ui/pages/token-details/index.scss
  ui/pages/token-details/token-details-page.js
  ui/pages/token-details/token-details-page.test.js
Labels: team-assets

#27794 test: Fix Vault Decryptor Page e2e test on develop branch
  test/e2e/helpers.js
Labels: team-extension-platform

#26580 ci: Improve validation for `sentry:publish` script
  development/sentry-publish.js
Labels: team-wallet-framework, team-extension-platform, needs-dev-review

#27763 fix: disable balance checker for Sepolia in account tracker
  app/scripts/constants/contracts.ts
Labels: team-wallet-framework

#27799 fix: sticky footer UI issue on Snaps Home Page in extended view
  ui/components/app/snaps/snap-ui-renderer/index.scss
Labels: type-bug, area-UI, team-snaps-platform, regression-develop, regression-RC-12.5.0

#27827 ci: Revert minimum E2E timeout to 20 minutes
  .circleci/scripts/test-run-e2e-timeout-minutes.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE, team-snaps-platform

#27817 fix: Fix Snaps usage of PhishingController
  .yarn/patches/@metamask-snaps-utils-npm-8.1.1-7d5dd6a26a.patch
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#27820 feat: Added metrics for edit networks and accounts
  shared/constants/metametrics.ts
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.tsx
  ui/components/multichain/edit-networks-modal/edit-networks-modal.js
  ui/components/multichain/pages/review-permissions-page/site-cell/site-cell.tsx
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#27803 Multichain: Fix snaps connection
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-eth-accounts.test.ts
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-eth-accounts.ts
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/wallet-getPermissions.js
  app/scripts/lib/multichain-api/wallet-requestPermissions.js
  app/scripts/lib/multichain-api/wallet-requestPermissions.test.js
  app/scripts/lib/multichain-api/wallet-revokePermissions.js
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.js
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.test.js
  app/scripts/metamask-controller.js
  test/e2e/tests/request-queuing/ui.spec.js
  ui/components/app/permission-page-container/permission-page-container.component.js
Labels: team-wallet-api-platform

#27570 revert: use networkClientId to resolve chainId in PPOM Middleware
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#27845 upsert empty wallet:eip155 on add
  app/scripts/controllers/permissions/background-api.test.js
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-permittedChains.test.ts
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-permittedChains.ts
  app/scripts/lib/multichain-api/caip25permissions.test.ts
  app/scripts/lib/multichain-api/wallet-createSession/handler.test.js
  yarn.lock
Labels: team-wallet-api-platform

#27848 cherry-pick: "revert: use networkClientId to resolve chainId in PPOM Middleware (#27570)"
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#27856 chore: Add react-beautiful-dnd to deprecated packages list
  .yarnrc.yml
Labels: team-extension-platform, INVALID-PR-TEMPLATE, team-snaps-platform

#27833 cherry-pick: Fix Snaps usage of PhishingController
  .yarn/patches/@metamask-snaps-utils-npm-8.1.1-7d5dd6a26a.patch
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#27566 fix(multichain): fix eth send flow (from dapp) when a btc account is selected
  test/jest/mocks.ts
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.d.ts
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/helpers/utils/util.js
  ui/helpers/utils/util.test.js
  ui/selectors/multichain.ts
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-accounts

#27789 fix: Reset nonce as network is switched
  ui/components/multichain/network-list-menu/network-list-menu.test.js
  ui/components/multichain/network-list-menu/network-list-menu.tsx
Labels: team-confirmations

#27830 fix: [cherry-pick][V12.5.0] sticky footer UI issue on Snaps Home Page…
  ui/components/app/snaps/snap-ui-renderer/index.scss
Labels: type-bug, team-snaps-platform, regression-RC-12.5.0

#27858 fix: flaky test `MultiRpc: should select rpc from settings @no-mmi`
  test/e2e/tests/network/multi-rpc.spec.ts
Labels: team-extension-platform

#27810 fix: hackily wait longer for linea swap approval tx to increase chance of success
  ui/ducks/swaps/swaps.js
  ui/pages/swaps/awaiting-swap/awaiting-swap.js
Labels: team-swaps

#27834 fix: flaky test `Add account should not affect public address when using secret recovery phrase to recover account with non-zero balance @no-mmi`
  test/e2e/tests/account/add-account.spec.js
Labels: team-extension-platform

#27849 Multichain: Do not add permittedChain scope for snaps. Use new networkConfigurationsByChainId property
  app/scripts/migrations/131.test.ts
  app/scripts/migrations/131.ts
Labels: team-wallet-api-platform

#27658 fix: updated permissions flow copy changes
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/multichain/disconnect-all-modal/disconnect-all-modal.tsx
  ui/components/multichain/pages/connections/components/__snapshots__/no-connections.test.tsx.snap
  ui/components/multichain/pages/connections/components/no-connection.tsx
  ui/components/multichain/pages/permissions-page/__snapshots__/permissions-page.test.js.snap
  ui/components/multichain/pages/permissions-page/connection-list-item.js
  ui/components/multichain/pages/review-permissions-page/__snapshots__/review-permissions-page.test.tsx.snap
  ui/components/multichain/pages/review-permissions-page/review-permissions-page.tsx
  ui/components/multichain/pages/review-permissions-page/site-cell/__snapshots__/site-cell-connection-list-item.test.js.snap
  ui/components/multichain/pages/review-permissions-page/site-cell/site-cell-connection-list-item.js
  ui/pages/permissions-connect/connect-page/__snapshots__/connect-page.test.tsx.snap
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#27821 feat: update copy for 'Default settings'
  app/_locales/en/messages.json
  test/e2e/helpers.js
  test/e2e/tests/network/multi-rpc.spec.ts
  test/e2e/tests/onboarding/onboarding.spec.js
  test/e2e/tests/privacy/basic-functionality.spec.js
  ui/pages/onboarding-flow/creation-successful/creation-successful.test.js
Labels: team-wallet-ux

#27711 feat: use messenger in AccountTracker to get Preferences state
  .eslintrc.js
  app/scripts/controllers/account-tracker-controller.test.ts
  app/scripts/controllers/account-tracker-controller.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-framework

#27846 fix: phishing test to not check c2 domains
  app/scripts/background.js
Labels: INVALID-PR-TEMPLATE, team-product-safety

#27874 fix: nonce value when there are multiple transactions in parallel
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
Labels: team-confirmations

#27852 cherry-pick: issue with nonce not updating correctly where there are multiple parallel transactions
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
Labels: team-confirmations

#27755 feat: upgrade assets-controllers to v38.3.0
  .yarn/patches/@metamask-assets-controllers-npm-38.3.0-57b3d695bb.patch
  package.json
  yarn.lock
Labels: accessibility, team-assets
