Repository MetaMask/metamask-extension, pull requests merged in 2024-01, with the labels that each got.

#22405 Fix issue connecting to dapps that dont use eth_accounts
  app/scripts/background.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#21841 Support token detection on Arbitrum, Optimism, Base, and zkSync
  shared/modules/network.utils.ts
  ui/selectors/selectors.js
Labels: team-assets

#22406 [Snaps E2E] Fix descriptions and comments
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/snaps/test-snap-get-file.spec.js
  test/e2e/snaps/test-snap-get-locale.spec.js
  test/e2e/snaps/test-snap-getentropy.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-lifecycle.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-networkaccess.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-revoke-perm.spec.js
  test/e2e/snaps/test-snap-txinsights-v2.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-update-component.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  test/e2e/snaps/test-snap-wasm.spec.js
Labels: area-snaps, team-snaps

#22298 Improve confirmation screens for account management snaps
  app/_locales/en/messages.json
  app/images/icons/user-circle-remove.svg
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/accounts/create-snap-account.spec.ts
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/components/component-library/icon/icon.types.ts
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/pages/confirmation/ResultTemplate.ts
  ui/pages/confirmation/confirmation.js
  ui/pages/confirmation/stories/remove-snap-account.stories.js
  ui/pages/confirmation/stories/util.js
  ui/pages/confirmation/templates/__snapshots__/create-snap-account.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/error.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/confirmation/templates/__snapshots__/success.test.js.snap
  ui/pages/confirmation/templates/create-snap-account.test.js
  ui/pages/confirmation/templates/remove-snap-account.test.js
  ui/pages/confirmation/templates/snap-account-redirect.js
  ui/pages/create-snap-account/components/create-snap-account-content.stories.tsx
  ui/pages/create-snap-account/components/create-snap-account-content.tsx
  ui/pages/create-snap-account/components/index.ts
  ui/pages/create-snap-account/create-snap-account.tsx
  ui/pages/pages.scss
  ui/pages/remove-snap-account/components/index.ts
  ui/pages/remove-snap-account/components/remove-snap-account-content.stories.tsx
  ui/pages/remove-snap-account/components/remove-snap-account-content.tsx
  ui/pages/remove-snap-account/components/view-account-on-block-explorer.tsx
  ui/pages/remove-snap-account/index.scss
  ui/pages/remove-snap-account/index.ts
  ui/pages/remove-snap-account/remove-snap-account.stories.tsx
  ui/pages/remove-snap-account/remove-snap-account.test.tsx
  ui/pages/remove-snap-account/remove-snap-account.tsx
  ui/pages/remove-snap-account/snap-account-card.tsx
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
  ui/pages/snap-account-redirect/create-snap-redirect.test.tsx
  ui/pages/snap-account-redirect/snap-account-redirect.tsx
  yarn.lock
Labels: team-accounts, team-snaps, INVALID-PR-TEMPLATE

#22416 Added launch.json configuration to debug Jest
  .vscode/launch.json
Labels: team-confirmations-system

#22408 Bump snaps packages
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#22433 Update Flask feedback link
  ui/pages/home/flask/flask-home-footer.component.js
Labels: flask, team-snaps, INVALID-PR-TEMPLATE

#22420 Update Extension to NameController v4
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-confirmations-system

#22412 consensys.net -> consensys.io
  shared/lib/ui-utils.js
  test/data/mock-state.json
  ui/components/app/signature-request-original/signature-request-original-warning/signature-request-original-warning.js
  ui/components/app/terms-of-use-popup/terms-of-use-popup.js
  ui/pages/onboarding-flow/metametrics/__snapshots__/metametrics.test.js.snap
  ui/pages/onboarding-flow/metametrics/metametrics.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: needs-content, needs-ux-ds-review, team-marketing

#22436 [Snaps E2E] Create test for snaps home page
  test/e2e/run-all.js
  test/e2e/snaps/test-snap-homepage.spec.js
Labels: area-snaps, team-snaps

#22317 Add test for vault decryptor
  .circleci/config.yml
  test/e2e/helpers.js
  test/e2e/vault-decryption-chrome.spec.js
Labels: team-shared-libraries

#22398 feat: bump assets controllers
  .yarn/patches/@metamask-assets-controllers-npm-22.0.0-6af3715fb2.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-UX, needs-ux-ds-review, INVALID-PR-TEMPLATE

#22432 Renaming index.js to index.ts and exporting types from component-library
  ui/components/component-library/README.md
  ui/components/component-library/button/index.ts
  ui/components/component-library/container/README.mdx
  ui/components/component-library/container/container.scss
  ui/components/component-library/container/container.types.ts
  ui/components/component-library/container/index.ts
  ui/components/component-library/form-text-field/index.ts
  ui/components/component-library/index.ts
Labels: team-design-system, needs-ux-ds-review

#22451 Fixing deprecation messages for BUTTON_VARIANT and BUTTON_SIZES
  ui/components/component-library/button/index.ts
Labels: team-design-system, needs-ux-ds-review

#22448 Master sync following v11.7.2 and v11.7.3
  CHANGELOG.md
  package.json
Labels: INVALID-PR-TEMPLATE

#22279 Bump test dapp v7.3.1
  package.json
  yarn.lock
Labels: area-testSuite, team-devex, needs-dev-review, INVALID-PR-TEMPLATE

#22461 fix: fix enable token detection
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
Labels: team-extension-UX

#22347 Add Staking entrypoint for Mainnet on Token List Item
  app/images/icons/stake.svg
  shared/constants/metametrics.ts
  test/e2e/tests/add-hide-token.spec.js
  test/e2e/tests/add-multiple-tokens.spec.js
  ui/components/app/asset-list/asset-list.js
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/token-list-item.js
  ui/components/multichain/token-list-item/token-list-item.stories.js
  ui/components/multichain/token-list-item/token-list-item.test.js
Labels: team-extension-UX, needs-ux-ds-review

#22399 e2e: 22366-change-language
  test/e2e/tests/change-language.spec.js
  test/scenarios/17. settings/general/change-language.csv
Labels: team-extension-platform

#22190 Add Petnames Name Component to Transaction Approval Screen
  test/e2e/flask/petnames-helpers.js
  test/e2e/flask/petnames-signatures.spec.js
  test/e2e/flask/petnames-transactions.spec.js
  ui/components/ui/sender-to-recipient/sender-to-recipient.component.js
Labels: team-confirmations-system

#22431 Make `lint:changed` support typescript files
  package.json
Labels: team-extension-client

#22467 Fix overflowing snap UI
  ui/components/app/snaps/snap-ui-markdown/snap-ui-markdown.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22374 Fix: use estimate gas instead of fixed gas
  package.json
  yarn.lock
Labels: team-confirmations-system, QA Passed

#22403 fx: update blockaid false positive report url.
  shared/constants/security-provider.ts
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22442 Bump snaps packages
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#22291 Adds "What's New" popup for staking
  app/_locales/en/messages.json
  app/images/portfolio-stake-notification-light-mode.png
  shared/notifications/index.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: team-extension-client, team-extension-UX, team-portfolio, needs-dev-review, INVALID-PR-TEMPLATE

#22477 fix(22476): fix flaky dapp viewed with two accounts e2e test
  test/e2e/tests/metrics/dapp-viewed.spec.js
Labels: team-extension-client, team-extension-platform

#22478 Bump assets controllers to v24
  package.json
  yarn.lock
Labels: team-assets

#22441 Show total fees when simulaton fails.
  ui/components/app/transaction-detail-item/index.scss
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22472 feat(22160): bump @zxing package and maintain the sending txn via qr code san flow
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/send-eth.spec.js
  ui/components/app/modals/qr-scanner/qr-scanner.component.js
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/pages/send/send-content/add-recipient/domain-input.component.js
  yarn.lock
Labels: team-extension-client, team-extension-platform

#22404 fix: display gas details section for legacy transactions
  ui/components/app/fee-details-component/fee-details-component.js
  ui/components/app/fee-details-component/fee-details-component.test.js
  ui/pages/confirm-approve/confirm-approve-content/__snapshots__/confirm-approve-content.component.test.js.snap
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/token-allowance/token-allowance.js
Labels: team-confirmations-secure-ux-PR

#22338 feat: add announcement for users that blockaid will be enabled by default
  app/_locales/en/messages.json
  shared/notifications/index.js
  test/e2e/fixture-builder.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/components/app/whats-new-popup/whats-new-popup.test.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
  ui/selectors/selectors.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22283 [e2e] Add wallet_revokePermissions request e2e test
  test/e2e/json-rpc/wallet_revokePermissions.spec.js
Labels: area-testSuite, team-devex, needs-dev-review

#22482 fix: accounts name in send flow
  ui/components/app/alerts/unconnected-account-alert/unconnected-account-alert.js
  ui/components/app/alerts/unconnected-account-alert/unconnected-account-alert.test.js
  ui/pages/connected-accounts/connected-accounts.container.js
  ui/pages/send/send-content/add-recipient/__snapshots__/add-recipient.component.test.js.snap
  ui/pages/send/send-content/add-recipient/add-recipient.container.js
  ui/pages/send/send-content/add-recipient/add-recipient.container.test.js
  ui/pages/send/send.test.js
Labels: team-accounts, needs-dev-review

#22497 e2e: stabilize flaky Snap Account Transfers
  test/e2e/accounts/snap-account-transfers.spec.ts
Labels: team-accounts, team-devex

#22510 UX: Updated op token to ETH
  shared/constants/network.ts
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review, INVALID-PR-TEMPLATE

#22513 Fix missing snaps RPC method hook
  app/scripts/metamask-controller.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22501 chore: Upgrade `@metamask/eth-query` to `v4.0.0`
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#22503 chore: Upgrade `@metamask/etherscan-link` to `v3.0.0`
  package.json
  yarn.lock
Labels: team-extension-platform

#22383 New Settings: Show extension in full size view
  app/_locales/en/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/lib/backup.test.js
  app/scripts/lib/setupSentry.js
  test/data/mock-state.json
  test/e2e/fixture-builder.js
  test/e2e/restore/MetaMaskUserData.json
  test/e2e/tests/full-size-view-settings.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/e2e/webdriver/driver.js
  ui/ducks/metamask/metamask.js
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: area-settings, team-swaps, release-11.9.0

#22511 chore: disable link to portfolio staking in MMI
  ui/components/app/asset-list/asset-list.js
Labels: team-mmi

#22499 chore: Upgrade `@metamask/announcement-controller` to v5.0.1
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#22460 fix: QR/Keystone notification window disappears
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-accounts

#22495 Added launch.json configuration to run E2E tests
  .vscode/launch.json
Labels: team-devex

#22443 Fix snaps custom UI styling issues
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/components/app/snaps/copyable/copyable.js
  ui/components/app/snaps/snap-ui-image/snap-ui-image.tsx
  ui/components/app/snaps/snap-ui-markdown/snap-ui-markdown.js
  ui/components/app/snaps/snap-ui-renderer/index.scss
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/pages/confirmation/templates/snaps/snap-alert/snap-alert.js
  ui/pages/confirmation/templates/snaps/snap-confirmation/snap-confirmation.js
  ui/pages/confirmation/templates/snaps/snap-prompt/snap-prompt.js
Labels: team-snaps, INVALID-PR-TEMPLATE

#22473 Replace RGBA static values
  ui/components/app/signature-request-siwe/index.scss
  ui/components/app/snaps/copyable/index.scss
  ui/components/app/snaps/show-more/index.scss
  ui/components/app/snaps/show-more/show-more.js
  ui/components/app/token-list-display/token-list-display.scss
  ui/components/multichain/asset-picker-amount/asset-picker-modal/index.scss
  ui/css/design-system/index.scss
  ui/css/design-system/pending-colors.scss
  ui/pages/send/send.scss
Labels: team-design-system

#22540 Add missing env variables to `build:test:flask` script
  package.json
Labels: team-snaps, INVALID-PR-TEMPLATE

#22504 chore: Upgrade various controllers to latest versions
  app/scripts/controllers/detect-tokens.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#22493 fix: BlockaidBannerAlert other/fallback description i18n
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
Labels: team-confirmations-secure-ux-PR

#22465 UX: Added e2e for list management and removed feature flag
  app/_locales/en/messages.json
  app/images/dragging-animation.svg
  app/images/icons/drag-drop.svg
  app/images/pinning-animation.svg
  app/scripts/controllers/app-state.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  builds.yml
  test/e2e/tests/account-details.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/component-library/icon/icon.types.ts
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/hidden-account-list.js
  ui/components/multichain/account-list-menu/index.scss
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review, INVALID-PR-TEMPLATE

#20701 Replace deprecated components for <ConfirmationNetworkSwitch/>. Refactor code to abstract styles to .scss and reduce repeating code.
  .storybook/test-data.js
  ui/pages/confirmation/components/confirmation-network-switch/confirmation-network-switch.js
  ui/pages/confirmation/components/confirmation-network-switch/confirmation-network-switch.stories.js
  ui/pages/confirmation/components/confirmation-network-switch/index.scss
  ui/pages/confirmation/templates/__snapshots__/switch-ethereum-chain.test.js.snap
Labels: team-design-system, needs-ux-ds-review

#22548 fix(22547): fix e2e test import token and prevent interaction before modal is closed
  test/e2e/tests/import-tokens.spec.js
  ui/components/app/import-token/token-search/token-search.component.js
Labels: team-extension-platform

#22469 Add user operation support
  app/_locales/en/messages.json
  app/scripts/controllers/decrypt-message.test.ts
  app/scripts/controllers/permissions/selectors.js
  app/scripts/lib/keyring-snaps-permissions.test.ts
  app/scripts/lib/setupSentry.js
  app/scripts/lib/transaction/util.test.ts
  app/scripts/lib/transaction/util.ts
  app/scripts/metamask-controller.js
  builds.yml
  development/build/scripts.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/browserify/policy-override.json
  package.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/app/transaction-alerts/transaction-alerts.js
  ui/components/app/transaction-alerts/transaction-alerts.test.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/selectors/account-abstraction.test.ts
  ui/selectors/account-abstraction.ts
  yarn.lock
Labels: team-confirmations-system

#22578 Set max timeout for e2e tests to 20m per job
  .circleci/config.yml
Labels: team-shared-libraries

#22558 fix(CI): Fix shallow checkout
  .circleci/config.yml
Labels: team-extension-platform

#22498 chore: Update `@metamask/accounts-controller` to v5
  .yarn/patches/@metamask-accounts-controller-npm-5.0.0-f877105fa0.patch
  package.json
  yarn.lock
Labels: team-extension-platform

#22584 chore: Upgrade Yarn to v4.0.2
  .yarn/releases/yarn-4.0.0-rc.48.cjs
  .yarn/releases/yarn-4.0.2.cjs
  .yarnrc.yml
  package.json
Labels: team-extension-platform

#22583 fix: Clicking on the redirection link doesn't close the notification
  ui/pages/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/confirmation/templates/snap-account-redirect.js
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
  ui/pages/snap-account-redirect/components/redirect-url-icon.tsx
  ui/pages/snap-account-redirect/components/snap-account-redirect-context.tsx
  ui/pages/snap-account-redirect/components/snap-account-redirect-message.tsx
  ui/pages/snap-account-redirect/components/url-display-box.tsx
  ui/pages/snap-account-redirect/create-snap-redirect.test.tsx
  ui/pages/snap-account-redirect/snap-account-redirect.tsx
Labels: team-accounts

#22407 [Snaps] Add test for name lookup
  test/e2e/run-all.js
  test/e2e/snaps/test-snap-namelookup.spec.js
Labels: area-snaps, team-snaps

#22538 chore: minor performance improvement in accounts list pages
  ui/components/app/alerts/unconnected-account-alert/unconnected-account-alert.js
  ui/pages/connected-accounts/connected-accounts.container.js
Labels: team-accounts

#22586 Changed drop down element to findelement by css selector
  test/e2e/tests/change-language.spec.js
Labels: team-extension-platform

#22582 chore: Update `@metamask/approval-controller` to `^5.1.1`
  package.json
  yarn.lock
Labels: team-extension-platform

#22539 fix: Blockaid What's New image missing transparent background
  app/images/blockaid-security-provider.png
  app/images/blockaid-security-provider.svg
  shared/notifications/index.js
Labels: team-confirmations-secure-ux-PR

#22562 update modal header element to header
  ui/components/component-library/modal-header/__snapshots__/modal-header.test.tsx.snap
  ui/components/component-library/modal-header/modal-header.tsx
Labels: team-design-system

#22590 Bump LavaMoat and SES
  .yarn/patches/@lavamoat-lavapack-npm-3.1.0-34c65d233b.patch
  .yarn/patches/lavamoat-core-npm-14.4.1-c4e8bbb016.patch
  .yarn/patches/lavamoat-core-npm-15.1.1-51fbe39988.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-lavamoat, INVALID-PR-TEMPLATE

#22581 UX: Update date for survey
  ui/helpers/constants/survey.ts
Labels: team-extension-client, needs-ux-ds-review

#22528 feat(mv3): support lattice
  app/scripts/lib/offscreen-bridge/lattice-offscreen-keyring.ts
  app/scripts/metamask-controller.js
  builds.yml
  development/build/scripts.js
  offscreen/lattice-iframe.html
  offscreen/offscreen.html
  offscreen/scripts/lattice-iframe.ts
  offscreen/scripts/ledger-iframe.ts
  shared/constants/offscreen-communication.ts
  types/eth-lattice-keyring.d.ts
  types/global.d.ts
  ui/pages/create-account/connect-hardware/select-hardware.js
Labels: team-extension-platform, needs-dev-review, team-hardware-wallets

#20377 Fix: typos
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  app/scripts/migrations/074.js
  test/scenarios/3. transactions/cancel transaction.csv
  test/scenarios/3. transactions/speed up transaction.csv
  ui/components/component-library/text-field/README.mdx
  ui/components/component-library/text-field/text-field.types.ts
Labels: external-contributor

#22507 fix: typos
  ui/components/component-library/text/README.mdx
  ui/components/component-library/text/text.stories.tsx
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/token-list-item/token-list-item.js
Labels: external-contributor, INVALID-PR-TEMPLATE

#22602 Patch tar-stream to fix a race condition when installing snaps
  .yarn/patches/tar-stream-npm-3.1.6-ce3ac17e49.patch
  package.json
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#22557 fix: close banner to avoid error with e2e tests
  test/e2e/mmi/Dockerfile
  test/e2e/mmi/pageObjects/mmi-accountMenu-page.ts
  test/e2e/mmi/specs/visual.spec.ts
Labels: team-mmi, e2e-test

#22588 Fix code issues causing test case to break
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/multichain/app-header/app-header.js
  ui/hooks/useTransactionDisplayData.js
Labels: area-testSuite, team-confirmations-secure-ux-PR, flaky tests

#22595 Bump snaps packages
  app/scripts/controllers/permissions/specifications.test.js
  app/scripts/lib/keyring-snaps-permissions.test.ts
  app/scripts/lib/keyring-snaps-permissions.ts
  app/scripts/metamask-controller.js
  builds.yml
  package.json
  shared/constants/snaps/permissions.ts
  yarn.lock
Labels: team-snaps, INVALID-PR-TEMPLATE

#22521 chore: update browserlist and babel targets to chrome/firefox 89
  .browserslistrc
  .depcheckrc.yml
  .yarn/patches/lavamoat-core-npm-15.1.1-51fbe39988.patch
  app/manifest/v2/chrome.json
  app/manifest/v2/firefox.json
  app/manifest/v3/chrome.json
  app/manifest/v3/firefox.json
  babel.config.js
  lavamoat/build-system/policy-override.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-extension-client, team-lavamoat

#22455 Version v11.7.4
  .yarn/patches/@metamask-eth-keyring-controller-npm-13.0.1-06ff83faad.patch
  .yarn/patches/@metamask-keyring-controller-npm-9.0.0-f57ed3ebea.patch
  CHANGELOG.md
  app/scripts/lib/encryptor-factory.ts
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/accounts/snap-account-transfers.spec.ts
  test/e2e/fixture-builder.js
  test/e2e/helpers.js
  test/e2e/tests/account-details.spec.js
  test/e2e/tests/dapp-interactions.spec.js
  test/e2e/tests/migrate-old-vault.spec.js
  test/lib/mock-encryptor.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE, release-11.7.4

#22611 Added addition wait to fix the flaky test for change language
  test/e2e/tests/change-language.spec.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#22515 Petnames: Add more e2e tests
  test/e2e/flask/petnames-helpers.js
  test/e2e/flask/petnames-signatures.spec.js
  test/e2e/flask/petnames-transactions.spec.js
  test/e2e/mock-e2e.js
  test/e2e/run-all.js
  ui/components/ui/sender-to-recipient/sender-to-recipient.component.js
Labels: team-confirmations-system

#22553 fix: Blockaid send `External Link Clicked` metric for missing tx types
  ui/components/app/signature-request-original/signature-request-original.component.js
  ui/components/app/signature-request-siwe/signature-request-siwe.js
  ui/components/app/signature-request/signature-request.js
  ui/components/app/transaction-alerts/transaction-alerts.js
  ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
  ui/pages/token-allowance/token-allowance.js
Labels: team-confirmations-secure-ux-PR

#22612 Fix #22571 - Prevent flakiness in Import test
  test/e2e/tests/import-tokens.spec.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#22517 docs: add schema validation for manifest json files
  .vscode/settings.json
Labels: team-extension-platform

#22483 fix(14311): display explorer domain instead of hardcoded Etherscan explorer name
  app/_locales/en/messages.json
  app/_locales/fr/messages.json
  ui/pages/create-account/connect-hardware/account-list.js
  ui/pages/create-account/connect-hardware/account-list.test.js
Labels: team-hardware-wallets

#22617 test: fix flaky test PPOM Blockaid Alert for ERC20 Approve by adding missing mocks
  test/e2e/tests/ppom-blockaid-alert-erc20-approval.spec.js
  test/mocks/json-rpc-result.ts
Labels: team-confirmations-secure-ux-PR

#22613 fix:feat: support Blockaid What's New Dark Theme and add useTheme util
  app/images/blockaid-whats-new-theme-dark.svg
  app/images/blockaid-whats-new.svg
  shared/notifications/index.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/hooks/useTheme.test.ts
  ui/hooks/useTheme.ts
Labels: team-confirmations-secure-ux-PR

#22622 Added wait for the overlay spinner before the click was performed
  test/e2e/tests/change-language.spec.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#22481 Adding metametrics to primary currency setting
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
  shared/constants/metametrics.ts
  ui/pages/settings/settings-tab/settings-tab.component.js
Labels: team-extension-UX, needs-ux-ds-review

#22645 fix: Fix phishing warning page unresponsiveness
  package.json
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
  yarn.lock
Labels: team-extension-platform

#22351 deps: eth-method-registry@^2.0.0->^3.0.0
  app/scripts/lib/ens-ipfs/resolver.js
  app/scripts/ui.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/helpers/utils/optimism/fetchEstimatedL1Fee.test.js
  ui/helpers/utils/transactions.util.test.js
  yarn.lock
Labels: dependencies, team-security

#22601 Move native token value below Fiat within Token list
  ui/components/app/asset-list/asset-list.js
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/app/token-cell/token-cell.test.js
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/token-list-item.js
Labels: team-extension-UX, needs-ux-ds-review

#20422 Fixing Broken TokenAllowance Story
  ui/pages/token-allowance/token-allowance.stories.js
Labels: team-design-system, needs-ux-ds-review

#22352 deps: @metamask/eth-token-tracker@^4.0.0->^7.0.1
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: type-security, dependencies, team-security

#20599 Part of #20163 for file ui\components\app\modals\eth-sign-modal\eth-sign-modal.js
  ui/components/app/modals/eth-sign-modal/__snapshots__/eth-sign-modal.test.js.snap
  ui/components/app/modals/eth-sign-modal/eth-sign-modal.js
Labels: team-design-system

#22635 Account list e2e test: split account details e2e tests into multiple files and improve test names
  test/e2e/tests/account-menu/account-details.spec.js
  test/e2e/tests/account-menu/account-hide-unhide.spec.js
  test/e2e/tests/account-menu/account-pin-unpin.spec.js
  test/e2e/tests/account-menu/add-account.spec.js
Labels: team-extension-client, team-extension-platform

#20618 Part of #20163 for file ui\components\app\terms-of-use-popup\terms-of-use-popup.js
  ui/components/app/snaps/install-error/install-error.stories.js
  ui/components/app/terms-of-use-popup/terms-of-use-popup.js
Labels: team-design-system

#22618 FEAT: Update what's new and settings copy to communicate additional network coverage on extension
  app/_locales/en/messages.json
  shared/notifications/index.js
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
Labels: team-confirmations-secure-ux-PR, needs-dev-review, INVALID-PR-TEMPLATE

#22649 fix: Blockaid What's New os theme -> dark mode
  ui/hooks/useTheme.ts
Labels: team-confirmations-secure-ux-PR

#22551 UX: Send Flow: Add 'Sent to Contract' warning to new send page
  ui/components/multichain/pages/send/components/content.tsx
  ui/components/multichain/pages/send/send.js
  ui/components/multichain/pages/send/send.test.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#21038 feat: check for ledger error codes in the message and display a more …
  app/_locales/en/messages.json
  ui/pages/create-account/connect-hardware/index.js
Labels: team-hardware-wallets

#22500 chore: Upgrade `@metamask/controller-utils` to `v8.0.1`
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#22633 feat: Enable ppom on other chains
  app/scripts/lib/createStreamSink.js
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  test/e2e/tests/errors.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/component-library/icon/icon.types.ts
  yarn.lock
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#21804 Add imToken Wallet support with EIP-4527
  .github/ISSUE_TEMPLATE/bug-report.yml
  app/_locales/en/messages.json
  shared/constants/hardware-wallets.ts
  ui/pages/create-account/connect-hardware/index.test.tsx
  ui/pages/create-account/connect-hardware/select-hardware.js
Labels: external-contributor, team-hardware-wallets

#22321 feat: Add PPOM Validation to normal send.
  app/scripts/lib/transaction/util.test.ts
  app/scripts/lib/transaction/util.ts
  app/scripts/metamask-controller.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.test.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#22655 [fix] cherry picks for fixing Whats New style - Blockaid
  app/images/blockaid-security-provider.png
  app/images/blockaid-security-provider.svg
  app/images/blockaid-whats-new-theme-dark.svg
  app/images/blockaid-whats-new.svg
  shared/notifications/index.js
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/hooks/useTheme.test.ts
  ui/hooks/useTheme.ts
Labels: release-blocker, team-confirmations-secure-ux-PR, release-11.9.0

#22591 fix: Trezor connect - update to v9 in trezor-usb-permissions
  app/trezor-usb-permissions.html
Labels: area-hardware, hardware-trezor, external-contributor, INVALID-PR-TEMPLATE

#22544 Update Gas API URL
  privacy-snapshot.json
  shared/constants/swaps.ts
  test/e2e/mock-e2e.js
  test/e2e/tests/gas-estimates.spec.js
  test/e2e/tests/metrics/swaps.spec.js
  test/e2e/tests/network-error.spec.js
  test/jest/constants.js
Labels: team-swaps, INVALID-PR-TEMPLATE

#22652 E2E test: Improve fill method in driver
  test/e2e/helpers.js
  test/e2e/tests/custom-token-add-approve.spec.js
  test/e2e/tests/custom-token-send-transfer.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/webdriver/driver.js
Labels: team-extension-client, team-extension-platform

#22672 e2e: Wait for the loading overlay to disappear before clicking
  test/e2e/webdriver/driver.js
Labels: area-testSuite, team-extension-platform, flaky tests

#22456 Petnames: code fence removal; experimental toggle
  app/_locales/en/messages.json
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/preferences.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  app/scripts/migrations/108.test.ts
  app/scripts/migrations/108.ts
  app/scripts/migrations/index.js
  shared/constants/metametrics.ts
  test/data/mock-state.json
  test/e2e/fixture-builder.js
  test/e2e/flask/README.md
  test/e2e/run-all.js
  test/e2e/tests/petnames-helpers.js
  test/e2e/tests/petnames-signatures.spec.js
  test/e2e/tests/petnames-transactions.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/send-hex-address.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/ducks/metamask/metamask.js
  ui/hooks/usePetnamesEnabled.test.ts
  ui/hooks/usePetnamesEnabled.ts
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.container.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: team-confirmations-system

#22522 chore: add types for `submitRequestToBackground` fn in `ui/store/actions.ts`
  ui/store/actions.ts
Labels: team-extension-client

#22670 Version v11.7.5
  .yarn/patches/@lavamoat-lavapack-npm-3.1.0-34c65d233b.patch
  .yarn/patches/lavamoat-core-npm-14.4.1-c4e8bbb016.patch
  .yarn/patches/lavamoat-core-npm-15.1.1-51fbe39988.patch
  CHANGELOG.md
  builds.yml
  lavamoat/build-system/policy.json
  package.json
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#21956 Use account identities as default petnames
  app/scripts/controllers/preferences.d.ts
  app/scripts/lib/AbstractPetnamesBridge.test.ts
  app/scripts/lib/AbstractPetnamesBridge.ts
  app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts
  app/scripts/lib/AccountIdentitiesPetnamesBridge.ts
  app/scripts/lib/AddressBookPetnamesBridge.test.ts
  app/scripts/lib/AddressBookPetnamesBridge.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/metamask-controller.js
  app/scripts/migrations/109.test.ts
  app/scripts/migrations/109.ts
  app/scripts/migrations/index.js
  package.json
  ui/hooks/useName.test.ts
  ui/hooks/useName.ts
  yarn.lock
Labels: team-confirmations-system

#22692 fix: Create patch for custody keyring type in accounts controller
  .yarn/patches/@metamask-accounts-controller-npm-10.0.0-247993ca9a.patch
  .yarn/patches/@metamask-accounts-controller-npm-5.0.0-f877105fa0.patch
  package.json
  yarn.lock
Labels: team-accounts

#22691 test: adds blockaid multiple network support test
  test/e2e/mock-e2e.js
  test/e2e/tests/ppom-blockaid-alert-networks-support.spec.js
Labels: team-confirmations-secure-ux-PR

#22673 Add script to generate RC commits
  development/generate-rc-commits.js
  package.json
  yarn.lock
Labels: team-extension-client, team-extension-UX, extension-delivery

#22628 UX: Add 'Add' icon to Add Network button
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#22520 docs: tell vscode to use our workspace's typescript version for typechecks/hints
  .vscode/settings.json
Labels: team-extension-client

#22634 UX: Updated connections icon
  ui/components/multichain/connected-site-menu/__snapshots__/connected-site-menu.test.js.snap
  ui/components/multichain/connected-site-menu/connected-site-menu.js
  ui/components/multichain/connected-site-menu/connected-site-menu.test.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review, INVALID-PR-TEMPLATE

#22658 Updating design tokens to 1.13 includes accessibility updates
  package.json
  yarn.lock
Labels: team-design-system, needs-ux-ds-review

#22668 chore(22552): refactor modal selector in e2e tests
  test/e2e/tests/add-hide-token.spec.js
  test/e2e/tests/custom-rpc-history.spec.js
  test/e2e/tests/import-flow.spec.js
  test/e2e/tests/incremental-security.spec.js
  test/e2e/tests/onboarding.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/webdriver/driver.js
  ui/components/app/modal/modal.component.js
  ui/components/app/modals/confirm-delete-network/__snapshots__/confirm-delete-network.test.js.snap
  ui/components/app/modals/confirm-delete-network/confirm-delete-network.component.js
  ui/components/app/modals/fade-modal.js
  ui/components/app/modals/hide-token-confirmation-modal/__snapshots__/hide-token-confirmation-modal.test.js.snap
  ui/components/app/modals/hide-token-confirmation-modal/hide-token-confirmation-modal.js
  ui/components/app/modals/modal.js
  ui/components/app/reveal-SRP-modal/reveal-SRP-modal.js
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/account-details/account-details.js
  ui/components/multichain/receive-modal/receive-modal.js
  ui/components/ui/qr-code-view/index.js
  ui/components/ui/qr-code-view/index.scss
  ui/components/ui/qr-code-view/qr-code-view.js
  ui/components/ui/qr-code-view/qr-code-view.stories.js
  ui/components/ui/qr-code/index.js
  ui/components/ui/ui-components.scss
Labels: team-extension-platform

#22674 chore: Upgrade @metamask/transaction-controller to v21.0.1
  package.json
  yarn.lock
Labels: team-confirmations-system

#22623 UX: Multichain: Remove bottom navigation
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/helpers.js
  test/e2e/tests/account-token-list.spec.js
  test/e2e/tests/localization.spec.js
  test/e2e/tests/lock-account.spec.js
  test/e2e/tests/metamask-responsive-ui.spec.js
  test/e2e/tests/migrate-old-vault.spec.js
  test/e2e/tests/portfolio-site.spec.js
  test/e2e/tests/send-eth.spec.js
  test/e2e/tests/swaps/shared.js
  ui/components/app/asset-list/asset-list.js
  ui/components/app/asset-list/asset-list.test.js
  ui/components/multichain/app-footer/__snapshots__/app-footer.test.js.snap
  ui/components/multichain/app-footer/app-footer-actions.tsx
  ui/components/multichain/app-footer/app-footer.js
  ui/components/multichain/app-footer/app-footer.stories.js
  ui/components/multichain/app-footer/app-footer.test.js
  ui/components/multichain/app-footer/index.js
  ui/components/multichain/app-footer/index.scss
  ui/components/multichain/balance-overview/__snapshots__/balance-overview.test.js.snap
  ui/components/multichain/balance-overview/balance-overview.js
  ui/components/multichain/balance-overview/balance-overview.stories.js
  ui/components/multichain/balance-overview/balance-overview.test.js
  ui/components/multichain/balance-overview/index.js
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/select-action-modal-item/__snapshots__/select-action-item.test.js.snap
  ui/components/multichain/select-action-modal-item/index.js
  ui/components/multichain/select-action-modal-item/index.scss
  ui/components/multichain/select-action-modal-item/select-action-item.test.js
  ui/components/multichain/select-action-modal-item/select-action-modal-item.js
  ui/components/multichain/select-action-modal-item/select-action-modal-item.stories.js
  ui/components/multichain/select-action-modal/index.js
  ui/components/multichain/select-action-modal/select-action-modal.js
  ui/components/multichain/select-action-modal/select-action-modal.stories.js
  ui/components/multichain/select-action-modal/select-action-modal.test.js
  ui/ducks/app/app.ts
  ui/pages/home/home.component.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/store/actionConstants.ts
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review

#22270 feat: create ConfirmTitle component
  app/_locales/en/messages.json
  ui/components/app/confirm/title/index.ts
  ui/components/app/confirm/title/title.stories.tsx
  ui/components/app/confirm/title/title.test.tsx
  ui/components/app/confirm/title/title.tsx
  ui/selectors/confirm.test.ts
  ui/selectors/confirm.ts
Labels: team-confirmations-secure-ux-PR, confirmation-redesign

#22693 UX: Updated Custom network displayed for selectable in network selection
  app/scripts/controllers/network-order.ts
  shared/constants/network.ts
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: team-extension-client, team-extension-UX, needs-ux-ds-review, INVALID-PR-TEMPLATE

#20921 deps: force js-sha3 to ^0.9.2 by resolutions
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-security

#22669 Revert stake button and announcement
  app/_locales/en/messages.json
  app/images/icons/stake.svg
  app/images/portfolio-stake-notification-light-mode.png
  shared/constants/metametrics.ts
  shared/notifications/index.js
  test/e2e/tests/add-hide-token.spec.js
  test/e2e/tests/add-multiple-tokens.spec.js
  ui/components/app/asset-list/asset-list.js
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/token-list-item.js
  ui/components/multichain/token-list-item/token-list-item.stories.js
  ui/components/multichain/token-list-item/token-list-item.test.js
  ui/selectors/selectors.js
Labels: release-blocker, team-extension-UX, release-11.9.0

#20947 add progress of scanning QR code
  ui/components/app/modals/qr-scanner/index.scss
  ui/components/app/qr-hardware-popover/base-reader.js
  ui/components/app/qr-hardware-popover/base-reader.test.js
Labels: team-hardware-wallets

#22750 cherry pick: UX: Updated Custom network displayed for selectable in network selection
  app/scripts/controllers/network-order.ts
  shared/constants/network.ts
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: team-extension-UX, release-11.9.0

#22741 Fixing sign button color and replacing deprecated components in SignatureRequestOriginalWarning
  test/e2e/tests/eth-sign.spec.js
  test/e2e/tests/metrics/signature-approved.spec.js
  ui/components/app/app-components.scss
  ui/components/app/signature-request-original/signature-request-original-warning/index.scss
  ui/components/app/signature-request-original/signature-request-original-warning/signature-request-original-warning.js
Labels: team-design-system, needs-ux-ds-review

#22676 Cancel transaction signing from activity list
  app/_locales/en/messages.json
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/data/mock-pending-transaction-data.json
  ui/components/app/cancel-button/cancel-button.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.test.js
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
  ui/components/app/transaction-status-label/__snapshots__/transaction-status-label.test.js.snap
  ui/components/app/transaction-status-label/index.scss
  ui/components/app/transaction-status-label/transaction-status-label.js
  ui/components/app/transaction-status-label/transaction-status-label.test.js
  ui/helpers/constants/error-keys.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirm-transaction-base/confirm-transaction-base.container.js
  ui/selectors/transactions.js
  ui/selectors/transactions.test.js
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: team-accounts, team-confirmations-system, QA Passed, high-priority

#22756 Adding missing modal overlay to signature request original warning
  ui/components/app/signature-request-original/signature-request-original-warning/signature-request-original-warning.js
Labels: team-design-system

#22682 v11.9.0 changelog
  CHANGELOG.md
Labels: team-extension-client, INVALID-PR-TEMPLATE, release-11.9.0

#21767 devDeps: @storybook/test-runner@^0.10.0->^0.14.0
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-security, INVALID-PR-TEMPLATE
