Repository MetaMask/metamask-extension, pull requests merged in 2024-06, with the labels that each got.

#22434 fix: misleading gas fee label in UI
  ui/pages/confirmations/components/edit-gas-fee-button/edit-gas-fee-button.js
Labels: DO-NOT-MERGE, team-confirmations-secure-ux, team-confirmations-planning, needs-dev-review, external-contributor

#24973 chore(ci): use yarn v4 in GitHub Actions
  .github/workflows/add-release-label.yml
  .github/workflows/check-pr-labels.yml
  .github/workflows/check-template-and-add-labels.yml
  .github/workflows/close-bug-report.yml
  .github/workflows/codespaces.yml
  .github/workflows/fitness-functions.yml
  .github/workflows/update-lavamoat-policies.yml
Labels: area-CI, team-security

#24980 fix(deps): rpc-websockets@7.11.0->7.11.1
  yarn.lock
Labels: dependencies, team-security

#24826 refactor: rn isEthGasPrice -> isEthGasPriceFetched
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirmations/send/send-content/send-content.component.js
  ui/pages/confirmations/send/send-content/send-content.stories.js
Labels: team-confirmations

#24909 chore: update CODEOWNERS to include specific notifications paths
  .github/CODEOWNERS
Labels: team-notifications

#24992 chore: adds to allowlist AccountsController:getSelectedAccount and other
  app/scripts/metamask-controller.js
Labels: team-mmi

#24130 chore(deps): bump accounts-controller to ^14.0.0
  .storybook/test-data.js
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/controllers/permissions/specifications.test.js
  app/scripts/lib/backup.test.js
  app/scripts/metamask-controller.test.js
  app/scripts/migrations/105.test.ts
  app/scripts/migrations/105.ts
  app/scripts/migrations/119.test.ts
  app/scripts/migrations/119.ts
  app/scripts/migrations/index.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/eth-methods.ts
  test/e2e/accounts/common.ts
  test/jest/mock-store.js
  test/jest/mocks.js
  ui/components/app/account-list-item/account-list-item-component.test.js
  ui/components/app/account-list-item/account-list-item.stories.js
  ui/components/app/connected-accounts-list/connected-accounts-list.stories.js
  ui/components/app/modals/confirm-remove-account/confirm-remove-account.stories.js
  ui/components/app/modals/confirm-remove-account/confirm-remove-account.test.js
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/components/app/transaction-status-label/transaction-status-label.test.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/app/wallet-overview/token-overview.test.js
  ui/components/institutional/interactive-replacement-token-notification/interactive-replacement-token-notification.test.js
  ui/components/institutional/wrong-network-notification/wrong-network-notification.test.js
  ui/components/multichain/account-list-menu/account-list-menu.test.js
  ui/components/multichain/connected-site-menu/connected-site-menu.test.js
  ui/components/multichain/pages/send/send.test.js
  ui/ducks/metamask/metamask.test.js
  ui/ducks/send/send.test.js
  ui/hooks/useAddressDetails.test.js
  ui/hooks/useAssetDetails.test.js
  ui/pages/confirm-add-suggested-token/confirm-add-suggested-token.test.js
  ui/pages/confirm-decrypt-message/confirm-decrypt-message.component.test.js
  ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.component.test.js
  ui/pages/confirmations/components/edit-gas-fee-popover/edit-gas-fee-popover.test.js
  ui/pages/confirmations/components/signature-request-original/signature-request-original.test.js
  ui/pages/confirmations/components/signature-request/signature-request-data/signature-request-data.test.js
  ui/pages/confirmations/components/signature-request/signature-request-header/signature-request-header.component.test.js
  ui/pages/confirmations/components/signature-request/signature-request.test.js
  ui/pages/confirmations/confirm-signature-request/index.test.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmations/hooks/useBalance.test.js
  ui/pages/confirmations/send/send.test.js
  ui/pages/confirmations/token-allowance/token-allowance.test.js
  ui/pages/connected-accounts/connected-accounts.stories.js
  ui/pages/token-details/token-details-page.test.js
  ui/selectors/institutional/selectors.test.js
  ui/selectors/nonce-sorted-transactions-selector.test.js
  ui/selectors/permissions.test.js
  ui/selectors/selectors.test.js
  ui/selectors/transactions.test.js
  ui/store/actions.test.js
  yarn.lock
Labels: team-accounts

#25002 chore: Master sync
  CHANGELOG.md
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24983 fix: Update file path for fetching locales, to match mv3 folder structure
  shared/modules/i18n.test.ts
  shared/modules/i18n.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24920 fix: `wallet_addEthereumChain` validation: `iconUrls` should be an expected param
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
Labels: type-bug, team-wallet-api-platform

#25006 Turn off smart tx in 11.16.4
  ui/pages/home/home.component.js
Labels: INVALID-PR-TEMPLATE

#24936 chore: Fix bundle-stats-commit.sh
  .circleci/scripts/bundle-stats-commit.sh
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#25007 v11.16.4
  CHANGELOG.md
  package.json
  ui/pages/home/home.component.js
Labels: INVALID-PR-TEMPLATE

#24844 test: Enable type checking of tests
  app/scripts/controllers/encryption-public-key.test.ts
  app/scripts/controllers/metamask-notifications/processors/process-onchain-notifications.test.ts
  app/scripts/controllers/user-storage/user-storage-controller.test.ts
  app/scripts/lib/AccountIdentitiesPetnamesBridge.test.ts
  app/scripts/lib/keyring-snaps-permissions.test.ts
  app/scripts/lib/rpc-method-middleware/createUnsupportedMethodMiddleware.test.ts
  app/scripts/lib/snap-keyring/utils/isBlockedUrl.test.ts
  app/scripts/migrations/095.test.ts
  test/data/confirmations/personal_sign.ts
  test/e2e/accounts/remove-account-snap.spec.ts
  test/e2e/flask/user-operations.spec.ts
  test/e2e/mmi/custodian-hooks/ICustodianTestClient.ts
  test/e2e/mmi/custodian-hooks/hooks.ts
  test/e2e/mmi/helpers/custodian-helper.ts
  test/e2e/mmi/helpers/dapps-helpers.ts
  test/e2e/mmi/pageObjects/mmi-accountMenu-page.ts
  test/e2e/mmi/pageObjects/mmi-main-page.ts
  test/e2e/mmi/pageObjects/mmi-mainMenu-page.ts
  test/e2e/mmi/specs/navigation.spec.ts
  test/e2e/mmi/specs/qrCode.spec.ts
  test/e2e/mmi/specs/transactions.spec.ts
  test/e2e/seeder/ganache.ts
  test/e2e/tests/confirmations/helpers.ts
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  test/e2e/tests/confirmations/signatures/personal-sign.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v3.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v4.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data.spec.ts
  test/e2e/tests/ppom/mocks/json-rpc-result.ts
  test/e2e/tests/ppom/mocks/mock-server-json-rpc.ts
  test/e2e/tests/settings/change-language.spec.ts
  test/e2e/tests/simulation-details/mock-request-buy-erc1155.ts
  test/e2e/tests/simulation-details/mock-request-buy-erc20.ts
  test/e2e/tests/simulation-details/mock-request-buy-erc721.ts
  test/e2e/tests/simulation-details/mock-request-error-insuffient-gas.ts
  test/e2e/tests/simulation-details/mock-request-error-malformed-transaction.ts
  test/e2e/tests/simulation-details/mock-request-no-changes.ts
  test/e2e/tests/simulation-details/mock-request-send-eth.ts
  test/e2e/tests/simulation-details/simulation-details.spec.ts
  test/e2e/tests/simulation-details/types.ts
  test/e2e/tests/swap-send/mocks/erc20-data.ts
  test/e2e/tests/swap-send/mocks/eth-data.ts
  test/e2e/tests/swap-send/swap-send-erc20.spec.ts
  test/e2e/tests/swap-send/swap-send-eth.spec.ts
  test/e2e/tests/swap-send/swap-send-test-utils.ts
  tsconfig.json
  ui/components/app/alert-system/utils.test.ts
  ui/components/app/name/name.test.tsx
  ui/ducks/locale/locale.test.ts
  ui/pages/confirmations/components/simulation-details/amount-pill.test.tsx
  ui/pages/confirmations/components/simulation-details/asset-pill.test.tsx
  ui/pages/confirmations/components/simulation-details/fiat-display.test.tsx
  ui/pages/confirmations/components/simulation-details/formatAmount.test.ts
  ui/pages/confirmations/components/simulation-details/sortBalanceChanges.test.ts
  ui/pages/confirmations/components/simulation-details/useSimulationMetrics.test.ts
  ui/pages/confirmations/hooks/alerts/utils.test.ts
Labels: team-extension-platform

#25008 Version v11.16.5
  CHANGELOG.md
  package.json
  ui/pages/home/home.component.js
Labels: INVALID-PR-TEMPLATE

#25000 fix: update insights metrics fencing
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  ui/store/actions.ts
Labels: team-snaps-platform

#24999 fix: GasDetailItem Danger Icon alignment
  ui/pages/confirmations/components/gas-details-item/gas-details-item.js
  ui/pages/confirmations/components/gas-details-item/index.scss
Labels: team-confirmations

#24860 feat: disable some gas warnings and errors for Mantle network
  shared/constants/network.ts
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js
  ui/pages/confirmations/constants/index.ts
Labels: area-gas, needs-dev-review, team-confirmations

#24865 feat: simulation section for SIWE personal signature requests
  app/_locales/en/messages.json
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
Labels: needs-dev-review, confirmation-redesign, team-confirmations

#24808 feat: changes in info section of permit signature types
  app/_locales/en/messages.json
  test/data/confirmations/typed_sign.ts
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/components/confirm/row/typed-sign-data/typedSignData.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/constants/index.ts
  ui/pages/confirmations/utils/confirm.test.ts
  ui/pages/confirmations/utils/confirm.ts
Labels: needs-dev-review, confirmation-redesign, team-confirmations

#24403 feat: Add UI for Snaps pre-approved connections
  app/_locales/en/messages.json
  shared/constants/permissions.ts
  test/data/mock-state.json
  ui/components/app/permission-cell/permission-cell-status.js
  ui/components/app/permission-cell/permission-cell.js
  ui/components/app/permission-cell/permission-cell.test.js
  ui/components/app/snaps/snap-permission-cell/index.js
  ui/components/app/snaps/snap-permission-cell/snap-permission-cell.js
  ui/components/app/snaps/snap-permission-cell/snap-permission-cell.test.js
  ui/components/app/snaps/snap-permissions-list/snap-permissions-list.js
  ui/components/app/snaps/snap-permissions-list/snap-permissions-list.test.js
  ui/components/app/snaps/update-snap-permission-list/update-snap-permission-list.js
  ui/helpers/utils/permission.js
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
  ui/pages/permissions-connect/snaps/snap-update/snap-update.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-snaps-platform

#24970 chore: updating old button and removing deprecated disabled colors
  .storybook/3.COLORS.stories.mdx
  ui/components/ui/button/buttons.scss
  ui/css/design-system/_colors.scss
  ui/helpers/constants/design-system.ts
Labels: team-design-system

#24876 feat: bypass add account confirmations for preinstalled snaps
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/metamask-controller.js
Labels: area-UI, team-accounts

#24883 Cherry pick basic functionality toggle to v11.16.3
  app/_locales/en/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  test/e2e/fixture-builder.js
  test/e2e/helpers.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/e2e/tests/onboarding/onboarding.spec.js
  test/e2e/tests/privacy/basic-functionality.spec.js
  ui/components/app/basic-configuration-modal/basic-configuration-modal.stories.tsx
  ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
  ui/components/app/basic-configuration-modal/index.ts
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/ui/new-network-info/new-network-info.js
  ui/components/ui/new-network-info/new-network-info.test.js
  ui/ducks/app/app.ts
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/onboarding-flow/privacy-settings/setting.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/selectors/selectors.js
  ui/store/actionConstants.ts
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: INVALID-PR-TEMPLATE

#25022 feat(multichain): normalize address helpers
  app/scripts/lib/multichain/address.test.ts
  app/scripts/lib/multichain/address.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/app/account-list-item/__snapshots__/account-list-item-component.test.js.snap
  ui/components/app/account-list-item/account-list-item-component.test.js
  ui/components/app/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.js
  yarn.lock
Labels: team-accounts

#24947 fix: upgrade transaction-controller to 32.0.0 to fix mmi
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-transactions

#25031 fix(mmi): improve mmi controller unit tests
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/controllers/mmi-controller.ts
Labels: team-mmi

#25051 fix: iframe injection in MV3
  app/scripts/app-init.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#25056 fix(cherry-pick): iframe injection in MV3 (#25051)
  app/scripts/app-init.js
Labels: INVALID-PR-TEMPLATE

#25055 fix: flaky test `vault-decryption-chrome` due to new announcement
  test/e2e/vault-decryption-chrome.spec.js
Labels: team-extension-platform, flaky tests

#24952 chore: Update defunct, potentially risky QR dependency
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/institutional/qr-code-modal/qr-code-modal.tsx
  yarn.lock
Labels: QA Passed, external-contributor, INVALID-PR-TEMPLATE

#24998 fix(24641): fix flaky test "Create" token, approve token and approve token without gas approves an already created token and displays the token approval data @no-mmi"
  test/e2e/tests/tokens/custom-token-add-approve.spec.js
Labels: team-extension-platform

#24693 chore: update CODEOWNERS for snap-keyring dir
  .github/CODEOWNERS
Labels: team-accounts

#25037 feat: new notifications account detail
  app/scripts/controllers/metamask-notifications/mocks/mock-raw-notifications.ts
  app/scripts/controllers/metamask-notifications/types/on-chain-notification/schema.d.ts
  ui/pages/notification-details/notification-details-body/notification-details-body.tsx
  ui/pages/notifications/notification-components/lido-stake-ready-to-be-withdrawn/lido-stake-ready-to-be-withdrawn.tsx
  ui/pages/notifications/notification-components/lido-withdrawal-requested/lido-withdrawal-requested.tsx
  ui/pages/notifications/notification-components/stake/stake.tsx
  ui/pages/notifications/notification-components/swap-completed/swap-completed.tsx
  ui/selectors/metamask-notifications/metamask-notifications.test.ts
Labels: team-notifications

#24913 fix: bump assets controller to 30.0.0
  .storybook/test-data.js
  .yarn/patches/@metamask-assets-controllers-npm-26.0.0-17c0e9432c.patch
  .yarn/patches/@metamask-assets-controllers-npm-30.0.0-8747c20871.patch
  .yarn/patches/@metamask-assets-controllers-patch-0f46262fea.patch
  .yarn/patches/@metamask-assets-controllers-patch-7616cc1669.patch
  app/scripts/background.js
  app/scripts/controllers/swaps.js
  app/scripts/controllers/swaps.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  app/scripts/migrations/120.test.ts
  app/scripts/migrations/120.ts
  app/scripts/migrations/index.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  shared/constants/tokens.js
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/e2e/default-fixture.js
  test/e2e/mock-e2e.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/swaps.spec.js
  test/e2e/tests/privacy/basic-functionality.spec.js
  test/e2e/tests/swap-send/swap-send-test-utils.ts
  test/jest/mock-store.js
  ui/components/app/asset-list/asset-list.test.js
  ui/components/app/currency-input/currency-input.test.js
  ui/components/app/currency-input/hooks/useTokenExchangeRate.test.tsx
  ui/components/app/currency-input/hooks/useTokenExchangeRate.tsx
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/components/app/token-cell/token-cell.js
  ui/components/app/token-cell/token-cell.test.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/app/wallet-overview/token-overview.test.js
  ui/components/multichain/asset-picker-amount/asset-picker-amount.stories.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.test.tsx
  ui/components/multichain/asset-picker-amount/swappable-currency-input/swappable-currency-input.test.tsx
  ui/components/ui/new-network-info/new-network-info.test.js
  ui/ducks/metamask/metamask.js
  ui/hooks/useAccountTotalFiatBalance.test.js
  ui/hooks/useIsOriginalTokenSymbol.js
  ui/selectors/confirm-transaction.js
  ui/selectors/confirm-transaction.test.js
  ui/selectors/selectors.js
  yarn.lock
Labels: team-assets, needs-assets-ux-review

#25046 Version-v11.6.6: patch @metamask/selected-network-controller 12.0.1
  .yarn/patches/@metamask-selected-network-controller-npm-12.0.1-34b2edf62d.patch
  package.json
  ui/selectors/selectors.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#24951 chore(sentry): enable performance monitoring
  app/scripts/lib/setupSentry.js
Labels: area-Sentry, team-extension-platform

#24873 fix: prevent infinite API calls in Notification components
  ui/components/multichain/notification-detail-network-fee/notification-detail-network-fee.tsx
  ui/pages/notification-details/notification-details.tsx
  ui/selectors/metamask-notifications/metamask-notifications.ts
Labels: team-notifications

#25030 fix: @metamask/smart-transactions-controller@^10.0.1->^10.1.1
  package.json
  yarn.lock
Labels: dependencies, team-security

#25001 fix(notifications): :speech_balloon: update profile syncing privacy links
  ui/components/app/modals/turn-on-metamask-notifications/turn-on-metamask-notifications.tsx
  ui/pages/notifications-settings/notifications-settings-allow-notifications.tsx
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.tsx
Labels: team-notifications

#25004 chore: Master-sync script updated
  development/master-sync.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#25066 Version v11.16.7
  .yarn/patches/@metamask-selected-network-controller-npm-12.0.1-34b2edf62d.patch
  CHANGELOG.md
  app/scripts/lib/setupSentry.js
  package.json
  ui/selectors/selectors.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE, release-11.16.7

#24788 refactor(ui): make CreateAccount generic + add CreateEthAccount
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/create-account/create-account.js
  ui/components/multichain/create-account/create-account.stories.js
  ui/components/multichain/create-account/create-account.tsx
  ui/components/multichain/create-eth-account/create-eth-account.js
  ui/components/multichain/create-eth-account/create-eth-account.stories.js
  ui/components/multichain/create-eth-account/create-eth-account.test.js
  ui/components/multichain/create-eth-account/index.js
  ui/components/multichain/index.js
  ui/store/actions.ts
  yarn.lock
Labels: team-accounts

#24390 feat: Implement New Attributions Update Workflow via GitHub Actions
  .github/workflows/check-attributions.yml
  .github/workflows/update-attributions.yml
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
  README.md
  attribution.txt
  development/attributions-check.sh
  development/generate-attributions.sh
  development/generate-attributions/package.json
  development/generate-attributions/yarn.lock
  package.json
  test/e2e/mmi/specs/navigation.spec.ts
  test/manual-scenarios/settings/about-metamask/ui-validation.csv
  ui/pages/settings/info-tab/info-tab.component.js
  ui/pages/settings/info-tab/info-tab.test.tsx
Labels: type-bug, area-documentation, Sev3-low, team-wallet-framework

#25079 feat: add icon for sei network
  app/images/sei.svg
  shared/constants/network.ts
Labels: team-assets

#24872 fix: relax network symbol length validation
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
Labels: team-assets, needs-assets-ux-review

#24858 chore(deps): react-redux@^7.2.0->^7.2.9
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-security

#25084 Tx verification updates
  app/scripts/lib/tx-verification/tx-verification-middleware.ts
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#24748 fix: Memoize AccountListMenu selectors
  ui/selectors/permissions.js
  ui/selectors/selectors.js
Labels: team-wallet-ux, needs-assets-ux-review

#25028 fix: flaky test `Test Snap Signature Insights tests Signature Insights functionality`
  test/e2e/accounts/common.ts
  test/e2e/helpers.js
  test/e2e/snaps/test-snap-siginsights.spec.js
  test/e2e/tests/metrics/signature-approved.spec.js
Labels: team-extension-platform, flaky tests

#24814 fix: set on-chain notifications as read if the user clicks on the dedicated button
  app/scripts/controllers/metamask-notifications/metamask-notifications.ts
Labels: team-notifications

#25027 fix: fix amount in the ready to be withdrawn notification
  ui/pages/notifications/notification-components/lido-stake-ready-to-be-withdrawn/lido-stake-ready-to-be-withdrawn.tsx
Labels: team-notifications

#25024 fix: notification fix the value of the eth/usd amount
  ui/pages/notifications/notification-components/eth-sent-received/eth-sent-received.tsx
Labels: team-notifications

#25065 test(notifications): Add notification services e2e mocks
  app/scripts/controllers/authentication/authentication-controller.test.ts
  app/scripts/controllers/authentication/mocks/mockResponses.ts
  app/scripts/controllers/authentication/mocks/mockServices.ts
  app/scripts/controllers/authentication/services.test.ts
  app/scripts/controllers/metamask-notifications/metamask-notifications.test.ts
  app/scripts/controllers/metamask-notifications/mocks/mock-feature-announcements.ts
  app/scripts/controllers/metamask-notifications/mocks/mock-onchain-notifications.ts
  app/scripts/controllers/metamask-notifications/mocks/mock-raw-notifications.ts
  app/scripts/controllers/metamask-notifications/mocks/mockResponses.ts
  app/scripts/controllers/metamask-notifications/mocks/mockServices.ts
  app/scripts/controllers/metamask-notifications/services/feature-announcements.test.ts
  app/scripts/controllers/metamask-notifications/services/feature-announcements.ts
  app/scripts/controllers/metamask-notifications/services/onchain-notifications.test.ts
  app/scripts/controllers/push-platform-notifications/mocks/mockResponse.ts
  app/scripts/controllers/push-platform-notifications/mocks/mockServices.ts
  app/scripts/controllers/push-platform-notifications/services/endpoints.ts
  app/scripts/controllers/push-platform-notifications/services/services.test.ts
  app/scripts/controllers/push-platform-notifications/services/services.ts
  app/scripts/controllers/user-storage/mocks/mockResponses.ts
  app/scripts/controllers/user-storage/mocks/mockServices.ts
  test/e2e/mock-e2e.js
  test/e2e/tests/notifications/mocks.ts
  test/env.js
Labels: team-notifications

#25089 test: remove unnecessary connect steps and use fixture instead
  test/e2e/tests/request-queuing/sendTx-revokePermissions.spec.js
  test/e2e/tests/request-queuing/sendTx-switchChain-sendTx.spec.js
  test/e2e/tests/request-queuing/switch-network.spec.js
  test/e2e/tests/request-queuing/switchChain-sendTx.spec.js
  test/e2e/tests/request-queuing/watchAsset-switchChain-watchAsset.spec.js
Labels: team-extension-platform, flaky tests

#24698 fix: Migrate API usage from *.metafi and *.metaswap subdomains to *.api.cx.metamask.io
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  shared/constants/swaps.ts
  shared/lib/swaps-utils.test.js
  test/data/mock-data.js
  test/e2e/fixture-builder.js
  test/e2e/mock-cdn/update-mock-cdn-files.js
  test/e2e/mock-e2e.js
  test/e2e/tests/metrics/swaps.spec.js
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
  test/e2e/tests/swaps/swaps-notifications.spec.js
  test/e2e/tests/tokens/add-hide-token.spec.js
  test/e2e/tests/tokens/import-tokens.spec.js
  test/jest/constants.js
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/name/name-details/name-details.test.tsx
  ui/components/app/name/name.stories.tsx
  ui/components/component-library/avatar-token/README.mdx
  ui/components/component-library/avatar-token/avatar-token.stories.tsx
  ui/components/multichain/import-tokens-modal/import-tokens-modal-confirm.stories.js
  ui/components/multichain/notification-detail-asset/notification-detail-asset.stories.tsx
  ui/components/multichain/notification-detail-asset/notification-detail-asset.tests.tsx
  ui/components/multichain/notification-detail-collection/notification-detail-collection.stories.tsx
  ui/components/multichain/notification-detail-nft/notification-detail-nft.stories.tsx
  ui/components/multichain/notification-detail-nft/notification-detail-nft.test.tsx
  ui/ducks/swaps/swaps.test.js
  ui/pages/confirmations/components/simulation-details/simulation-details.stories.tsx
  ui/pages/swaps/swaps-util-test-constants.js
  ui/pages/swaps/swaps.util.test.js
  ui/pages/swaps/swaps.util.ts
  yarn.lock
Labels: team-wallet-framework

#25091 fix: release testing issues
  .github/guidelines/LABELING_GUIDELINES.md
  .github/scripts/check-template-and-add-labels.ts
  .github/workflows/create-bug-report.yml
Labels: team-extension-platform

#25077 chore: update first party contract names for MM pooled staking and liquid staking
  shared/constants/first-party-contracts.ts
Labels: team-portfolio

#25014 test: Fix `EncryptionPublicKeyController` tests
  app/scripts/controllers/encryption-public-key.test.ts
  jest.config.js
Labels: team-extension-platform

#25012 test: Fix `AppMetadataController` tests
  app/scripts/controllers/app-metadata.test.ts
  jest.config.js
Labels: team-extension-platform

#25058 feat: Improve content of banner for errors and warning
  app/_locales/en/messages.json
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.test.js
Labels: team-confirmations

#25059 refactor(ui): add new AccountOverview
  app/_locales/en/messages.json
  test/e2e/flask/user-operations.spec.ts
  test/e2e/helpers.js
  test/e2e/tests/account/import-flow.spec.js
  test/e2e/tests/account/metamask-responsive-ui.spec.js
  test/e2e/tests/dapp-interactions/block-explorer.spec.js
  test/e2e/tests/request-queuing/dapp1-switch-dapp2-send.spec.js
  test/e2e/tests/request-queuing/multiple-networks-dapps-txs.spec.js
  test/e2e/tests/settings/account-token-list.spec.js
  test/e2e/tests/settings/address-book.spec.js
  test/e2e/tests/settings/change-language.spec.ts
  test/e2e/tests/settings/clear-activity.spec.js
  test/e2e/tests/settings/ipfs-toggle.spec.js
  test/e2e/tests/swaps/shared.js
  test/e2e/tests/tokens/add-hide-token.spec.js
  test/e2e/tests/tokens/custom-token-add-approve.spec.js
  test/e2e/tests/tokens/nft/auto-detect-nft.spec.js
  test/e2e/tests/tokens/nft/erc1155-interaction.spec.js
  test/e2e/tests/tokens/nft/erc721-interaction.spec.js
  test/e2e/tests/tokens/nft/import-erc1155.spec.js
  test/e2e/tests/tokens/nft/import-nft.spec.js
  test/e2e/tests/tokens/nft/remove-erc1155.spec.js
  test/e2e/tests/tokens/nft/remove-nft.spec.js
  test/e2e/tests/tokens/nft/send-nft.spec.js
  test/e2e/tests/tokens/nft/view-erc1155-details.spec.js
  test/e2e/tests/tokens/nft/view-nft-details.spec.js
  test/e2e/tests/tokens/send-erc20-to-contract.spec.js
  test/e2e/tests/tokens/token-details.spec.js
  test/e2e/tests/transaction/change-assets.spec.js
  test/e2e/tests/transaction/edit-gas-fee.spec.js
  test/e2e/tests/transaction/multiple-transactions.spec.js
  test/e2e/tests/transaction/send-edit.spec.js
  test/e2e/tests/transaction/send-eth.spec.js
  test/e2e/tests/transaction/send-hex-address.spec.js
  test/e2e/tests/transaction/stuck-approved-transaction.spec.js
  test/e2e/user-actions-benchmark.js
  types/global.d.ts
  ui/components/multichain/account-overview/account-overview-eth.stories.tsx
  ui/components/multichain/account-overview/account-overview-eth.test.tsx
  ui/components/multichain/account-overview/account-overview-eth.tsx
  ui/components/multichain/account-overview/account-overview-layout.tsx
  ui/components/multichain/account-overview/account-overview-tabs.tsx
  ui/components/multichain/account-overview/account-overview-unknown.stories.tsx
  ui/components/multichain/account-overview/account-overview-unknown.test.tsx
  ui/components/multichain/account-overview/account-overview-unknown.tsx
  ui/components/multichain/account-overview/account-overview.tsx
  ui/components/multichain/account-overview/common.ts
  ui/components/multichain/account-overview/index.js
  ui/components/multichain/account-overview/index.scss
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
  ui/components/ui/tabs/tab/tab.component.js
  ui/pages/home/home.component.js
  ui/pages/home/index.scss
  ui/selectors/accounts.test.ts
  ui/selectors/accounts.ts
Labels: team-accounts

#25040 chore: Master sync
  CHANGELOG.md
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#25095 feat: contributor docs
  .github/pull-request-template.md
  README.md
Labels: team-extension-platform

#25112 fix: Add resolution for rpc-websockets to handle deps audit failure
  package.json
  yarn.lock
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#25094 chore: bump Snaps packages
  builds.yml
  package.json
  ui/components/app/snaps/snap-ui-renderer/components/bold.ts
  ui/components/app/snaps/snap-ui-renderer/components/box.ts
  ui/components/app/snaps/snap-ui-renderer/components/form.ts
  ui/components/app/snaps/snap-ui-renderer/components/italic.ts
  ui/components/app/snaps/snap-ui-renderer/components/link.ts
  ui/components/app/snaps/snap-ui-renderer/components/text.ts
  ui/components/app/snaps/snap-ui-renderer/utils.ts
  ui/pages/snaps/snap-view/snap-settings.js
  ui/pages/snaps/snap-view/snap-view.js
  ui/selectors/selectors.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#24717 refactor: remove account pill from wallet overview
  ui/components/app/wallet-overview/wallet-overview.js
Labels: team-accounts

#25113 fix: Include missing files in Sentry release artifact upload
  development/sentry-upload-artifacts.sh
Labels: team-extension-platform, needs-dev-review

#25128 chore: Revert master sync PR #25040
  CHANGELOG.md
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#25114 test: Add tx verification middleware validation tests
  app/scripts/lib/tx-verification/tx-verification-middleware.test.ts
  app/scripts/lib/tx-verification/tx-verification-middleware.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  shared/constants/bridge.ts
Labels: INVALID-PR-TEMPLATE

#24499 chore(refactor:test): unify environment variables for setting headless modes
  playwright.config.ts
  test/e2e/mmi/helpers/extension-loader.ts
  test/e2e/webdriver/chrome.js
  test/e2e/webdriver/firefox.js
  test/helpers/env.ts
Labels: team-security, e2e-test

#25129 chore: Master sync following v11.16.4 - v11.16.7
  CHANGELOG.md
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#25108 fix: bug report template - remove reference to recordit
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: team-extension-platform

#25088 feat(mmi): improve custody icons when dark/light mode
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/index.scss
Labels: team-mmi

#24994 fix: deprecating more networks
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/migrations/121.test.ts
  app/scripts/migrations/121.ts
  app/scripts/migrations/index.js
  shared/constants/network.ts
  ui/helpers/utils/i18n-helper.tsx
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.js
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js
  ui/pages/settings/networks-tab/networks-tab.constants.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-assets, needs-assets-ux-review, team-confirmations

#25137 fix: flaky test `Sentry errors after initialization, after opting into metrics @no-mmi should capture UI application state`
  test/e2e/tests/metrics/errors.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: team-extension-platform, flaky tests

#25127 Version v11.16.8 alternative - patch selected network controller
  .yarn/patches/@metamask-selected-network-controller-npm-12.0.1-34b2edf62d.patch
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#25099 fix: Avoid to send the snap notification id to the notifications server
  ui/pages/notifications/notifications-list-read-all-button.tsx
Labels: team-notifications

#24708 fix: Notifications platform links
  app/_locales/en/messages.json
  app/scripts/controllers/metamask-notifications/mocks/mock-feature-announcements.ts
  app/scripts/controllers/metamask-notifications/services/feature-announcements.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/feature-announcement.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/type-action.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/type-extension-link.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/type-feature-announcement.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/type-link.ts
  app/scripts/controllers/push-platform-notifications/utils/get-notification-message.ts
  ui/components/multichain/index.js
  ui/components/multichain/notification-detail-block-explorer-button/index.ts
  ui/components/multichain/notification-detail-block-explorer-button/notification-detail-block-explorer-button.test.tsx
  ui/components/multichain/notification-detail-block-explorer-button/notification-detail-block-explorer-button.tsx
  ui/components/multichain/notification-detail-button/notification-detail-button.tsx
  ui/pages/notification-details/notification-details-footer/notification-details-footer.tsx
  ui/pages/notifications/notification-components/erc1155-sent-received/erc1155-sent-received.tsx
  ui/pages/notifications/notification-components/erc20-sent-received/erc20-sent-received.tsx
  ui/pages/notifications/notification-components/erc721-sent-received/erc721-sent-received.tsx
  ui/pages/notifications/notification-components/eth-sent-received/eth-sent-received.tsx
  ui/pages/notifications/notification-components/feature-announcement/feature-announcement.tsx
  ui/pages/notifications/notification-components/lido-stake-ready-to-be-withdrawn/lido-stake-ready-to-be-withdrawn.tsx
  ui/pages/notifications/notification-components/lido-withdrawal-requested/lido-withdrawal-requested.tsx
  ui/pages/notifications/notification-components/stake/stake.tsx
  ui/pages/notifications/notification-components/swap-completed/swap-completed.tsx
  ui/pages/notifications/notification-components/types/notifications/notifications.ts
Labels: team-notifications

#25096 refactor: coin-overview
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/index.scss
  ui/components/multichain/account-overview/account-overview-eth.tsx
  ui/components/ui/icon-button/icon-button.js
  ui/hooks/useIsOriginalNativeTokenSymbol.js
Labels: team-accounts

#25109 fix: Fix types associated with auto lock timer call
  app/scripts/controllers/app-state.js
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/store/actions.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24540 fix: Update filtering of STX for the Activity list
  ui/selectors/transactions.js
  ui/selectors/transactions.test.js
Labels: team-transactions

#25122 chore: remove deprecated success colors
  .storybook/3.COLORS.stories.mdx
  ui/components/component-library/header-base/header-base.stories.tsx
  ui/components/multichain/pages/page/page.stories.tsx
  ui/css/design-system/_colors.scss
  ui/helpers/constants/design-system.ts
  ui/pages/onboarding-flow/create-password/index.scss
Labels: team-design-system, needs-assets-ux-review

#25048 fix: Remove old What's New messages
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/blockaid-whats-new-theme-dark.svg
  app/images/blockaid-whats-new.svg
  app/images/petnames-whatsnew-banner.svg
  app/images/simulations-whatsnew-banner-dark.svg
  app/images/simulations-whatsnew-banner.svg
  shared/notifications/index.ts
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/components/app/whats-new-popup/whats-new-popup.test.js
  ui/pages/home/home.container.js
  ui/selectors/selectors.js
Labels: team-wallet-ux, needs-assets-ux-review

#24831 fix: Remove unwanted MULTICHAIN feature usages in tests
  test/e2e/flask/user-operations.spec.ts
  test/e2e/tests/account/add-account.spec.js
  test/e2e/tests/account/import-flow.spec.js
  test/e2e/tests/settings/change-language.spec.ts
  test/e2e/tests/tokens/increase-token-allowance.spec.js
  test/e2e/tests/transaction/change-assets.spec.js
  ui/components/app/multiple-notifications/multiple-notifications.component.js
Labels: team-wallet-ux, needs-assets-ux-review

#24837 chore: update swaps blockedList api url
  privacy-snapshot.json
  shared/constants/swaps.ts
  shared/lib/swaps-utils.js
  ui/ducks/send/send.js
  ui/hooks/useUpdateSwapsState.test.ts
  ui/hooks/useUpdateSwapsState.ts
Labels: team-bridge, release-12.0.0

#25124 chore: removing deprecated info colors from codebase
  .storybook/3.COLORS.stories.mdx
  ui/css/design-system/_colors.scss
  ui/helpers/constants/design-system.ts
Labels: team-design-system, needs-assets-ux-review

#24931 fix: yarn download-builds stopped working
  .devcontainer/download-builds.ts
Labels: team-contributor-experience

#25104 fix: Remove MULTICHAIN flag and CI job
  .circleci/config.yml
  builds.yml
Labels: team-wallet-ux

#24882 fix: re-enable swap-send-eth e2e test
  test/e2e/tests/swap-send/swap-send-eth.spec.ts
  test/e2e/tests/swap-send/swap-send-test-utils.ts
  ui/components/component-library/text-field-search/text-field-search.tsx
Labels: team-bridge, release-12.0.0

#25090 Version v11.16.8
  .yarn/patches/@metamask-selected-network-controller-npm-12.0.1-34b2edf62d.patch
  .yarn/patches/@metamask-transaction-controller-npm-29.1.0-22871eb356.patch
  CHANGELOG.md
  app/_locales/en/messages.json
  app/scripts/app-init.js
  app/scripts/controllers/app-state.js
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/metamask-controller.js
  development/sentry-upload-artifacts.sh
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/modules/mv3.utils.js
  test/e2e/mmi/pageObjects/mmi-dummyApp-page.ts
  ui/helpers/constants/common.ts
  ui/helpers/utils/util.test.js
  ui/pages/home/home.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/store/actions.ts
  yarn.lock
Labels: release-11.16.8

#25078 chore: add swap+send analytics
  shared/constants/metametrics.ts
  test/data/mock-send-state.json
  test/jest/mocks.js
  ui/components/app/nfts-items/nfts-items.js
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
  ui/components/multichain/asset-picker-amount/max-clear-button.tsx
  ui/components/multichain/pages/send/components/address-book.tsx
  ui/components/multichain/pages/send/components/quote-card/index.tsx
  ui/components/multichain/pages/send/components/recipient-content.tsx
  ui/components/multichain/pages/send/components/recipient-input.tsx
  ui/components/multichain/pages/send/components/recipient.tsx
  ui/components/multichain/pages/send/components/your-accounts.tsx
  ui/components/multichain/pages/send/send.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
Labels: team-bridge

#25011 chore: refactoring institutional qr code modal
  ui/components/institutional/institutional-components.scss
  ui/components/institutional/qr-code-modal/qr-code-modal.scss
  ui/components/institutional/qr-code-modal/qr-code-modal.stories.tsx
  ui/components/institutional/qr-code-modal/qr-code-modal.tsx
  ui/components/ui/spinner/spinner.component.js
  ui/components/ui/spinner/spinner.stories.js
Labels: team-design-system, needs-assets-ux-review

#25010 chore: removing warning alternative color from codebase
  .storybook/3.COLORS.stories.mdx
  ui/components/app/confirm/info/row/row.tsx
  ui/components/app/confirm/info/row/value-double.tsx
  ui/components/component-library/header-base/header-base.stories.tsx
  ui/components/multichain/pages/page/page.stories.tsx
  ui/components/ui/button/buttons.scss
  ui/css/design-system/_colors.scss
  ui/helpers/constants/design-system.ts
  ui/pages/onboarding-flow/create-password/index.scss
Labels: team-design-system, needs-assets-ux-review

#25125 chore: removing deprecated button color css variables
  .storybook/4.SHADOW.stories.mdx
  ui/components/component-library/button-primary/button-primary.scss
  ui/components/component-library/button-secondary/button-secondary.scss
Labels: team-design-system, needs-assets-ux-review

#25100 fix: resolve all known swap+send bugs
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/send.js
  ui/ducks/send/helpers.js
  ui/ducks/send/send.js
Labels: team-bridge, release-12.0.0

#25145 fix: flaky test `chrome-vault-decryption`
  test/e2e/webdriver/driver.js
Labels: team-extension-platform, flaky tests

#25083 chore: adding storybook stories
  ui/components/app/app-loading-spinner/app-loading-spinner.stories.js
  ui/components/app/wallet-overview/eth-overview.stories.js
  ui/components/ui/loading-screen/loading-screen.stories.js
Labels: team-design-system, needs-assets-ux-review

#25136 fix: Update PPOM controller to fix handling of HTTP status codes
  app/scripts/lib/setupSentry.js
  package.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: needs-dev-review, team-confirmations

#25076 docs: Updated the steps to trigger error and settings
  development/README.md
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#25070 fix(notifications): Ensure notifications feature is disabled/hidden when no basic functionality
  test/e2e/helpers.js
  ui/components/multichain/global-menu/global-menu.js
  ui/contexts/metamask-notifications/metamask-notifications.tsx
  ui/hooks/metamask-notifications/useProfileSyncing.ts
  ui/hooks/metamask-notifications/useSwitchNotifications.test.tsx
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/setting.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.test.tsx
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.tsx
Labels: team-notifications

#24522 feat: new asset details page
  app/_locales/en/messages.json
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/lib/fetch-with-cache.ts
  test/e2e/tests/tokens/add-hide-token.spec.js
  test/e2e/tests/tokens/send-erc20-to-contract.spec.js
  test/e2e/tests/tokens/token-details.spec.js
  test/e2e/tests/tokens/token-details.spec.ts
  test/e2e/tests/transaction/send-hex-address.spec.js
  ui/components/app/token-cell/__snapshots__/token-cell.test.js.snap
  ui/components/app/token-cell/token-cell.js
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/app/wallet-overview/index.js
  ui/components/app/wallet-overview/token-overview.js
  ui/components/app/wallet-overview/token-overview.test.js
  ui/components/multichain/account-overview/account-overview-tabs.tsx
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/index.scss
  ui/components/multichain/token-list-item/token-list-item.js
  ui/components/multichain/token-list-item/token-list-item.test.js
  ui/helpers/utils/confirm-tx.util.test.js
  ui/helpers/utils/confirm-tx.util.ts
  ui/pages/asset/asset.scss
  ui/pages/asset/asset.tsx
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/asset/components/asset-options.js
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/asset/components/asset-page.tsx
  ui/pages/asset/components/asset-price.tsx
  ui/pages/asset/components/chart/asset-chart.tsx
  ui/pages/asset/components/chart/chart-tooltip.tsx
  ui/pages/asset/components/chart/crosshair-plugin.ts
  ui/pages/asset/components/native-asset.js
  ui/pages/asset/components/native-asset.tsx
  ui/pages/asset/components/token-asset.js
  ui/pages/asset/components/token-asset.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/asset/useHistoricalPrices.ts
  ui/pages/asset/util.ts
  ui/pages/token-details/token-details-page.js
  yarn.lock
Labels: team-assets, INVALID-PR-TEMPLATE

#25039 fix: hardware wallet e2e test mv3 support
  test/e2e/tests/account/import-flow.spec.js
Labels: external-contributor

#25158 chore: refactoring opacity tokens and removing and adding some colors
  .storybook/3.COLORS.stories.mdx
  ui/components/component-library/component-library-components.scss
  ui/css/design-system/_colors.scss
  ui/css/index.scss
  ui/css/utilities/opacity.scss
  ui/helpers/constants/design-system.ts
Labels: team-design-system, needs-assets-ux-review

#24971 chore: removing deprecated secondary colors from codebase
  .storybook/3.COLORS.stories.mdx
  ui/components/app/app-loading-spinner/app-loading-spinner.js
  ui/components/app/modals/qr-scanner/qr-scanner.component.js
  ui/components/app/qr-hardware-popover/enhanced-reader.js
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/ui/loading-screen/loading-screen.component.js
  ui/pages/confirmations/confirm-transaction/__snapshots__/confirm-transaction.test.js.snap
Labels: team-design-system

#25164 fix: flaky test `lockdown the UI and background environments are locked down`
  test/e2e/tests/account/lockdown.spec.js
  test/e2e/webdriver/driver.js
Labels: team-extension-platform, flaky tests

#25199 fix(deps): bump `grpc-js` from 1.9.14 to 1.9.15
  yarn.lock
Labels: team-security

#25179 chore: Add ability to have front-end, local feature flags
  .storybook/preview.js
  app/_locales/en/messages.json
  builds.yml
  ui/helpers/utils/feature-flags.js
  ui/index.js
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/developer-options-tab/developer-options-tab.test.tsx
  ui/pages/settings/developer-options-tab/developer-options-tab.tsx
Labels: team-assets, needs-assets-ux-review

#25139 test: improve logInWithBalanceValidation function in e2e test
  test/e2e/helpers.js
Labels: team-extension-platform, flaky tests

#25201 chore(deps): bump accounts-controller to version 16.0.0
  package.json
  yarn.lock
Labels: team-accounts

#25163 fix: addressing feedbacks in typed sign alerts
  app/_locales/en/messages.json
  ui/components/app/alert-system/alert-modal/alert-modal.tsx
  ui/components/app/alert-system/general-alert/general-alert.tsx
  ui/hooks/useAlerts.ts
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
Labels: needs-dev-review, confirmation-redesign, team-confirmations

#25209 fix: Disable MV3 for MV2 Flask production build
  .circleci/config.yml
  .circleci/scripts/release-create-gh-release.sh
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#25061 feat: adding pluggable section to confirmation page
  ui/pages/confirmations/components/confirm/pluggable-section/index.ts
  ui/pages/confirmations/components/confirm/pluggable-section/pluggable-section.test.tsx
  ui/pages/confirmations/components/confirm/pluggable-section/pluggable-section.tsx
  ui/pages/confirmations/confirm/confirm.tsx
Labels: needs-dev-review, confirmation-redesign, team-confirmations

#25053 fix: updates MMI e2e confirm transaction flow
  test/e2e/mmi/pageObjects/mmi-main-page.ts
Labels: team-mmi

#25205 feat(multichain): add new selectors
  app/images/bitcoin-logo.svg
  shared/constants/multichain/networks.ts
  test/data/mock-accounts.ts
  ui/selectors/accounts.test.ts
  ui/selectors/multichain.test.ts
  ui/selectors/multichain.ts
Labels: team-accounts

#25041 fix: Swap-Send flaky test fix
  test/e2e/tests/swap-send/swap-send-test-utils.ts
  test/e2e/webdriver/driver.js
  ui/components/app/currency-input/currency-input.js
  ui/components/multichain/asset-picker-amount/swappable-currency-input/swappable-currency-input.tsx
Labels: team-extension-platform

#24953 chore: upgrading to design tokens v4
  .storybook/3.COLORS.stories.mdx
  .storybook/4.SHADOW.stories.mdx
  package.json
  ui/components/app/incoming-trasaction-toggle/__snapshots__/incoming-transaction-toggle.test.js.snap
  ui/components/component-library/button-primary/button-primary.scss
  ui/components/component-library/button-secondary/button-secondary.scss
  ui/components/multichain/address-copy-button/index.scss
  ui/components/multichain/ramps-card/index.scss
  ui/components/ui/button/buttons.scss
  ui/css/base-styles.scss
  ui/css/utilities/colors.scss
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/unlock-page/index.scss
  yarn.lock
Labels: team-design-system, needs-assets-ux-review

#25160 feat: add popular network list modal
  app/_locales/en/messages.json
  shared/constants/metametrics.ts
  ui/components/multichain/network-list-menu/network-confirmation-popover/__snapshots__/network-confirmation-popover.test.tsx.snap
  ui/components/multichain/network-list-menu/network-confirmation-popover/network-confirmation-popover.test.tsx
  ui/components/multichain/network-list-menu/network-confirmation-popover/network-confirmation-popover.tsx
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
  ui/components/multichain/network-list-menu/popular-network-list/PopularNetworkList.stories.js
  ui/components/multichain/network-list-menu/popular-network-list/__snapshots__/popular-network-list.test.tsx.snap
  ui/components/multichain/network-list-menu/popular-network-list/popular-network-list.test.tsx
  ui/components/multichain/network-list-menu/popular-network-list/popular-network-list.tsx
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.component.test.js
  ui/pages/routes/routes.container.js
Labels: team-assets, needs-assets-ux-review

#25216 fix: add deprecated tag back to callBackgroundMethod
  ui/store/background-connection.ts
Labels: team-extension-platform

#25184 v12.0.0 Cherry-Pick Notifications Feature Disabled when Basic Functionality Off
  test/e2e/helpers.js
  ui/components/multichain/global-menu/global-menu.js
  ui/contexts/metamask-notifications/metamask-notifications.tsx
  ui/hooks/metamask-notifications/useProfileSyncing.ts
  ui/hooks/metamask-notifications/useSwitchNotifications.test.tsx
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/setting.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.test.tsx
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.tsx
Labels: team-notifications

#25195 fix: UX: NetworkList: Consolidate NetworkListItem usages
  ui/components/multichain/network-list-menu/network-list-menu.js
Labels: team-wallet-ux, needs-assets-ux-review

#25054 feat: Support various redesign signatures in ConfirmPage Storybook
  ui/pages/confirmations/confirm/confirm.stories.tsx
Labels: team-confirmations

#25218 fix: addressing feedbacks in typed sign alerts
  app/_locales/en/messages.json
  ui/components/app/alert-system/alert-modal/alert-modal.tsx
  ui/components/app/alert-system/general-alert/general-alert.tsx
  ui/hooks/useAlerts.ts
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
Labels: team-confirmations, release-12.0.0

#25253 fix: Capture Segment errors during initialization
  app/scripts/controllers/metametrics.js
Labels: team-extension-platform

#25254 Version v11.16.10
  .circleci/config.yml
  .circleci/scripts/release-create-gh-release.sh
  CHANGELOG.md
  app/scripts/controllers/metametrics.js
  package.json
Labels: release-11.16.10

#24975 feat: permit signature copy changes
  app/_locales/en/messages.json
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/components/confirm/title/title.test.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/constants/index.ts
  ui/pages/confirmations/utils/confirm.test.ts
  ui/pages/confirmations/utils/confirm.ts
Labels: needs-dev-review, confirmation-redesign, team-confirmations

#25143 refactor: app header
  shared/constants/multichain/networks.ts
  ui/components/app/connected-status-indicator/connected-status-indicator.js
  ui/components/multichain/app-header/app-header-container.tsx
  ui/components/multichain/app-header/app-header-locked-content.tsx
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/connected-site-menu/connected-site-menu.js
  ui/components/multichain/connected-site-menu/index.scss
  ui/selectors/multichain.test.ts
  ui/selectors/multichain.ts
Labels: team-accounts

#23697 feat: Integrate SIP-12 update
  app/_locales/en/messages.json
  test/e2e/snaps/test-snap-namelookup.spec.js
  test/e2e/tests/settings/address-book.spec.js
  test/e2e/tests/transaction/ens.spec.js
  ui/components/component-library/badge-wrapper/badge-wrapper.tsx
  ui/components/multichain/address-list-item/__snapshots__/address-list-item.test.tsx.snap
  ui/components/multichain/address-list-item/address-list-item.tsx
  ui/components/multichain/pages/send/components/domain-input-resolution-cell.stories.tsx
  ui/components/multichain/pages/send/components/domain-input-resolution-cell.tsx
  ui/components/multichain/pages/send/components/index.ts
  ui/components/multichain/pages/send/components/recipient.tsx
  ui/components/multichain/pages/send/index.scss
  ui/components/ui/confusable/confusable.component.js
  ui/ducks/domains.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/pages/confirmations/send/send-content/add-recipient/domain-input.component.js
  ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js
  ui/pages/settings/contact-list-tab/add-contact/add-contact.container.js
  ui/pages/settings/contact-list-tab/edit-contact/edit-contact.component.js
  ui/pages/settings/contact-list-tab/index.scss
  ui/pages/settings/contact-list-tab/view-contact/view-contact.component.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: flask, INVALID-PR-TEMPLATE, needs-assets-ux-review, team-snaps-platform

#25241 chore: add Non-EVM feature flag
  builds.yml
Labels: team-accounts

#25215 v12.0.0 Cherry-Pick fix: Avoid to send the snap notification id to the notifications serv…
  ui/pages/notifications/notifications-list-read-all-button.tsx
Labels: team-notifications

#25214 v12.0.0 Cherry-Pick fix: Notifications platform links (#24708)
  app/_locales/en/messages.json
  app/scripts/controllers/metamask-notifications/mocks/mock-feature-announcements.ts
  app/scripts/controllers/metamask-notifications/services/feature-announcements.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/feature-announcement.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/type-action.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/type-extension-link.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/type-feature-announcement.ts
  app/scripts/controllers/metamask-notifications/types/feature-announcement/type-link.ts
  app/scripts/controllers/push-platform-notifications/utils/get-notification-message.ts
  ui/components/multichain/index.js
  ui/components/multichain/notification-detail-block-explorer-button/index.ts
  ui/components/multichain/notification-detail-block-explorer-button/notification-detail-block-explorer-button.test.tsx
  ui/components/multichain/notification-detail-block-explorer-button/notification-detail-block-explorer-button.tsx
  ui/components/multichain/notification-detail-button/notification-detail-button.tsx
  ui/pages/notification-details/notification-details-footer/notification-details-footer.tsx
  ui/pages/notifications/notification-components/erc1155-sent-received/erc1155-sent-received.tsx
  ui/pages/notifications/notification-components/erc20-sent-received/erc20-sent-received.tsx
  ui/pages/notifications/notification-components/erc721-sent-received/erc721-sent-received.tsx
  ui/pages/notifications/notification-components/eth-sent-received/eth-sent-received.tsx
  ui/pages/notifications/notification-components/feature-announcement/feature-announcement.tsx
  ui/pages/notifications/notification-components/lido-stake-ready-to-be-withdrawn/lido-stake-ready-to-be-withdrawn.tsx
  ui/pages/notifications/notification-components/lido-withdrawal-requested/lido-withdrawal-requested.tsx
  ui/pages/notifications/notification-components/stake/stake.tsx
  ui/pages/notifications/notification-components/swap-completed/swap-completed.tsx
  ui/pages/notifications/notification-components/types/notifications/notifications.ts
Labels: team-notifications

#25220 fix: flaky test `Change assets changes to native currency when switching accounts during a NFT send`
  test/e2e/tests/transaction/change-assets.spec.js
Labels: team-extension-platform, flaky tests

#25206 test: add missing mocks for aggregator metadata, block list and include blocked tokens in all tests
  test/e2e/mock-e2e.js
  test/e2e/mock-response-data/aggregator-metadata.json
  test/e2e/mock-response-data/token-blocklist.json
Labels: team-extension-platform, flaky tests

#25261 chore: updating failing snapshot in develop
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: team-design-system

#25105 fix: add metrics ui_customizations: permit for permit signature types
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  shared/constants/metametrics.ts
  shared/constants/transaction.ts
  shared/modules/transaction.utils.test.js
  shared/modules/transaction.utils.ts
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/utils/confirm.test.ts
  ui/pages/confirmations/utils/confirm.ts
Labels: needs-dev-review, confirmation-redesign, team-confirmations

#24142 fix: Retry requests from provider after connection is ready, on all builds
  app/scripts/contentscript.js
  app/scripts/metamask-controller.js
Labels: team-extension-platform, team-wallet-api-platform

#25217 fix: hide privacy policy toast during onboarding, and for onboarded users
  app/scripts/controllers/app-state.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.component.test.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: team-wallet-ux

#24209 chore(deps): Bump base-controller to ^5.0.1
  app/scripts/controllers/authentication/authentication-controller.test.ts
  app/scripts/controllers/push-platform-notifications/push-platform-notifications.test.ts
  app/scripts/controllers/user-storage/user-storage-controller.test.ts
  app/scripts/lib/snap-keyring/utils/isBlockedUrl.test.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-wallet-framework

#25157 fix (cherry-pick): Remove old What's New messages (#25048) for 12.0.0
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/blockaid-whats-new-theme-dark.svg
  app/images/blockaid-whats-new.svg
  app/images/petnames-whatsnew-banner.svg
  app/images/simulations-whatsnew-banner-dark.svg
  app/images/simulations-whatsnew-banner.svg
  shared/notifications/index.ts
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/components/app/whats-new-popup/whats-new-popup.test.js
  ui/pages/home/home.container.js
  ui/selectors/selectors.js
Labels: team-wallet-ux, needs-assets-ux-review

#25269 fix: issue where user rejected request errors are not correctly handled in either wallet_switchEthereumChain nor wallet_addEthereumChain calls
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
Labels: team-wallet-api-platform

#25255 fix: Cherry pick #25199 to v12
  yarn.lock
Labels: dependencies, team-extension-platform

#25275 fix: swap+send e2e tests
  test/e2e/tests/swap-send/swap-send-erc20.spec.ts
  test/e2e/tests/swap-send/swap-send-eth.spec.ts
  test/e2e/tests/swap-send/swap-send-test-utils.ts
Labels: team-bridge

#25106 fix: bump `SelectedNetworkController` to fix issue where selected network domain is incorrectly set
  .yarn/patches/@metamask-network-controller-npm-19.0.0-a5e0d1fe14.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#25258 fix: fix typo in pre-build-mv2 and changed value of ENABLE_CONFIRMATION_REDESIGN
  .circleci/config.yml
Labels: team-extension-platform

#25186 fix: Simulations on signature pages should be displayed only if preference is enabled
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/selectors/preferences.test.ts
  ui/pages/confirmations/selectors/preferences.ts
Labels: confirmation-redesign, team-confirmations

#25148 fix: notification dates edge case
  ui/helpers/utils/notification.util.ts
  ui/helpers/utils/notification.utils.test.ts
Labels: team-notifications

#25248 fix: flaky test `ENS domain resolves to a correct address`
  test/e2e/tests/transaction/ens.spec.js
Labels: team-extension-platform, flaky tests

#25289 fix: flaky test `Send NFT should not be able to send ERC1155 NFT with invalid amount`
  test/e2e/tests/tokens/nft/send-nft.spec.js
Labels: team-extension-platform, flaky tests

#24997 feat: SIWE sign message section
  app/_locales/en/messages.json
  package.json
  test/data/confirmations/personal_sign.ts
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/__snapshots__/siwe-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/index.ts
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/siwe-sign.stories.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/siwe-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/siwe-sign.tsx
  ui/pages/confirmations/components/confirm/utils.test.ts
  ui/pages/confirmations/types/confirm.ts
  ui/pages/confirmations/utils/date.test.ts
  ui/pages/confirmations/utils/date.ts
  yarn.lock
Labels: needs-dev-review, confirmation-redesign, team-confirmations

#25287 chore: bump keyring-api and eth-snap-keyring
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-accounts
