Repository MetaMask/metamask-extension, pull requests merged in 2024-07, with the labels that each got.

#24556 chore: adds quality gate for rerunning e2e spec files that are new or have been modified
  .circleci/config.yml
  .circleci/scripts/git-diff-develop.ts
  development/lib/retry.js
  test/e2e/changedFilesUtil.js
  test/e2e/run-all.js
  test/e2e/run-e2e-test.js
Labels: team-extension-platform

#25607 fix: failingt e2e `Click bridge button from asset page @no-mmi loads portfolio tab when flag is turned off`
  test/e2e/tests/bridge/bridge-click-from-asset-overview.spec.ts
  test/e2e/tests/bridge/bridge-test-utils.ts
Labels: team-extension-platform, flaky tests

#25556 feat: Remove blockaid migration BannerAlert
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/ppom/migrate-opensea-to-blockaid-banner.spec.js
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/__snapshots__/blockaid-unavailable-banner-alert.test.tsx.snap
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/blockaid-unavailable-banner-alert.stories.tsx
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/blockaid-unavailable-banner-alert.test.tsx
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/blockaid-unavailable-banner-alert.tsx
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/index.ts
  ui/pages/confirmations/components/signature-request-original/signature-request-original.component.js
  ui/pages/confirmations/components/signature-request/signature-request.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/token-allowance/token-allowance.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-confirmations

#25583 fix(snaps): Fix alignment of install origin is `snap-authorship-expanded`
  ui/components/app/snaps/snap-authorship-expanded/snap-authorship-expanded.js
Labels: team-snaps-platform

#25576 fix: tweak spacing in send asset picker
  ui/components/multichain/asset-picker-amount/asset-picker/__snapshots__/asset-picker.test.tsx.snap
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
Labels: team-bridge, release-12.1.0

#25284 chore: Create a story for RestoreVaultPage component
  ui/pages/keychains/restore-vault.stories.tsx
Labels: team-design-system, external-contributor

#25227 refactor: Replace deprecated mixins with Text component in unlock-page.component.js
  test/e2e/tests/settings/auto-lock.spec.js
  ui/pages/unlock-page/__snapshots__/unlock-page.test.js.snap
  ui/pages/unlock-page/index.scss
  ui/pages/unlock-page/unlock-page.component.js
Labels: team-design-system, external-contributor

#25262 refactor: Replace deprecated mixins with Text component in selected-account.component.js
  ui/components/app/selected-account/index.scss
  ui/components/app/selected-account/selected-account.component.js
Labels: team-design-system, external-contributor

#25587 fix: create all approval requests prior to user prompt
  .circleci/config.yml
  .circleci/scripts/git-diff-develop.ts
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/lib/snap-keyring/snap-keyring.test.ts
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  development/lib/retry.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/changedFilesUtil.js
  test/e2e/run-all.js
  test/e2e/run-e2e-test.js
  test/e2e/tests/bridge/bridge-click-from-asset-overview.spec.ts
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/ppom/migrate-opensea-to-blockaid-banner.spec.js
  ui/components/app/snaps/snap-authorship-expanded/snap-authorship-expanded.js
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/__snapshots__/blockaid-unavailable-banner-alert.test.tsx.snap
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/blockaid-unavailable-banner-alert.stories.tsx
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/blockaid-unavailable-banner-alert.test.tsx
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/blockaid-unavailable-banner-alert.tsx
  ui/pages/confirmations/components/blockaid-unavailable-banner-alert/index.ts
  ui/pages/confirmations/components/signature-request-original/signature-request-original.component.js
  ui/pages/confirmations/components/signature-request/signature-request.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/token-allowance/token-allowance.js
  ui/selectors/selectors.js
  ui/store/actions.ts
  yarn.lock
Labels: team-accounts

#25373 test: Initial PR for integrating the Page Object Model (POM) into e2e test suite
  test/e2e/constants.ts
  test/e2e/helpers.js
  test/e2e/page-objects/pages/header-navbar.ts
  test/e2e/page-objects/pages/homepage.ts
  test/e2e/page-objects/pages/login-page.ts
  test/e2e/page-objects/pages/send/confirm-tx-page.ts
  test/e2e/page-objects/pages/send/send-token-page.ts
  test/e2e/page-objects/processes/login.process.ts
  test/e2e/page-objects/processes/send-transaction.process.ts
  test/e2e/tests/transaction/ens.spec.js
  test/e2e/tests/transaction/ens.spec.ts
  test/e2e/tests/transaction/simple-send.spec.js
  test/e2e/tests/transaction/simple-send.spec.ts
  test/e2e/tests/transaction/stuck-approved-transaction.spec.js
  test/e2e/tests/transaction/stuck-approved-transaction.spec.ts
  test/e2e/webdriver/README.md
  test/e2e/webdriver/driver.js
  ui/components/multichain/pages/send/components/domain-input-resolution-cell.tsx
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/send/send-content/add-recipient/domain-input.component.js
Labels: team-extension-platform, e2e-test

#25624 fix: page object selector not found
  test/e2e/page-objects/pages/login-page.ts
Labels: team-extension-platform, team-confirmations

#25606 chore: [Delivery] Update author mapping list for PR
  development/generate-rc-commits.js
Labels: team-extension-platform, extension-delivery

#25500 fix: account missing in connection page
  test/e2e/helpers.js
  test/e2e/tests/multichain/connection-page.spec.js
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
  ui/components/multichain/connected-site-menu/connected-site-menu.js
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
Labels: team-accounts

#25605 chore: exclude running git diff job for the e2e quality gate in `develop`, `master` and release branches
  .circleci/config.yml
  test/e2e/changedFilesUtil.js
Labels: team-extension-platform

#25462 fix: Fix issue 22837 about unknown error during ledger pair
  .yarn/patches/@metamask-eth-ledger-bridge-keyring-npm-2.0.1-7a5d815b2d.patch
  package.json
  yarn.lock
Labels: team-accounts, QA Passed, needs-dev-review, e2e-test

#25611 chore: Update @metamask/smart-transactions-controller from 10.1.2 to 10.1.6
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-transactions

#25615 feat: added BTC variant to ramps-card and illustration image
  app/images/ramps-card-btc-illustration.png
  ui/components/multichain/ramps-card/ramps-card.js
  ui/components/multichain/ramps-card/ramps-card.stories.js
  ui/hooks/ramps/useRamps/useRamps.ts
Labels: area-UI, team-accounts

#25410 fix: decimal places displayed on token value on permit pages
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/components/confirm/row/dataTree.tsx
  ui/pages/confirmations/components/confirm/row/typed-sign-data/typedSignData.tsx
  ui/pages/confirmations/components/confirm/utils.test.ts
  ui/pages/confirmations/components/confirm/utils.ts
Labels: confirmation-redesign, team-confirmations

#25617 Jl/caip multichain/scopes merger
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/provider-authorize.js
  app/scripts/lib/multichain-api/provider-request.js
  app/scripts/lib/multichain-api/scope.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#25618 feat: update Permit Signature Redesign "Spending cap" copy
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
Labels: team-confirmations

#25526 fix: support multichain in blockexplorer and qr code
  app/scripts/lib/accounts/BalancesController.test.ts
  shared/constants/multichain/networks.ts
  test/e2e/tests/dapp-interactions/block-explorer.spec.js
  test/jest/mocks.js
  ui/components/app/modals/confirm-remove-account/__snapshots__/confirm-remove-account.test.js.snap
  ui/components/app/modals/confirm-remove-account/confirm-remove-account.component.js
  ui/components/app/modals/confirm-remove-account/confirm-remove-account.container.js
  ui/components/app/modals/confirm-remove-account/confirm-remove-account.test.js
  ui/components/app/modals/nickname-popovers/__snapshots__/nickname-popovers.component.test.tsx.snap
  ui/components/app/modals/nickname-popovers/nickname-popovers.component.js
  ui/components/app/modals/nickname-popovers/nickname-popovers.component.test.tsx
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/address-copy-button/address-copy-button.js
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/menu-items/view-explorer-menu-item.test.js
  ui/components/multichain/menu-items/view-explorer-menu-item.test.tsx
  ui/components/multichain/menu-items/view-explorer-menu-item.tsx
  ui/components/ui/qr-code-view/qr-code-view.test.tsx
  ui/components/ui/qr-code-view/qr-code-view.tsx
  ui/helpers/utils/multichain/blockExplorer.test.ts
  ui/helpers/utils/multichain/blockExplorer.ts
  ui/helpers/utils/util.js
  ui/hooks/useMultichainAccountTotalFiatBalance.test.tsx
  ui/selectors/multichain.ts
  ui/store/store.ts
Labels: team-accounts

#25613 feat: add SIWE mismatch account warning alert
  app/_locales/en/messages.json
  ui/components/app/confirm/info/row/constants.ts
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
  ui/pages/confirmations/hooks/alerts/signatures/useAccountMismatchAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/signatures/useAccountMismatchAlerts.ts
  ui/pages/confirmations/hooks/useConfirmationAlerts.ts
Labels: team-confirmations

#25565 chore: flaky E2E tests improved
  test/e2e/mmi/pageObjects/mmi-accountMenu-page.ts
  test/e2e/mmi/specs/navigation.spec.ts
  test/e2e/mmi/specs/qrCode.spec.ts
Labels: team-mmi

#25633 feat: define which keyring methods Portfolio can call
  app/scripts/lib/snap-keyring/keyring-snaps-permissions.test.ts
  app/scripts/lib/snap-keyring/keyring-snaps-permissions.ts
Labels: team-accounts

#25614 fix: Multichain: UX: Check for transactions on all networks and QueuedRequestCount
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/selectors/transactions.js
  ui/selectors/util.js
Labels: team-wallet-ux

#25555 feat: Add support for security alerts on zkSync, Berachain, Scroll and Metachain One on extension
  package.json
  shared/constants/network.ts
  shared/constants/security-provider.ts
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  yarn.lock
Labels: team-confirmations

#25612 fix: Skip blockaid validation for SIWE signature types
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
Labels: team-confirmations

#25648 fix: flaky test `Test Snap Get Locale test snap_getLocale functionality`
  test/e2e/snaps/test-snap-get-locale.spec.js
Labels: team-extension-platform, flaky tests

#25631 chore: updates MMI custody controller
  package.json
  yarn.lock
Labels: team-mmi

#25643 Sj/caip 25 poc mutator
  app/scripts/lib/multichain-api/caip25permissions.test.ts
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/scope.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#25634 fix: UX: Multichain: Add safeguard to throw error when confirmation chainId doesn't match current chainId
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
Labels: team-wallet-ux

#25647 Jl/caip multichain/permission validation
  app/scripts/controllers/permissions/specifications.js
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/provider-authorize.js
  app/scripts/lib/multichain-api/provider-request.js
  app/scripts/lib/multichain-api/scope.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#25060 test: add swap e2e tests on Tenderly network
  .circleci/config.yml
  .gitignore
  package.json
  playwright.config.ts
  test/e2e/playwright/mmi/.env.example
  test/e2e/playwright/mmi/Dockerfile
  test/e2e/playwright/mmi/README.md
  test/e2e/playwright/mmi/custodian-hooks/ICustodianTestClient.ts
  test/e2e/playwright/mmi/custodian-hooks/hooks.ts
  test/e2e/playwright/mmi/env.ts
  test/e2e/playwright/mmi/helpers/custodian-helper.ts
  test/e2e/playwright/mmi/helpers/dapps-helpers.ts
  test/e2e/playwright/mmi/helpers/extension-loader.ts
  test/e2e/playwright/mmi/helpers/oauth-api-helper.ts
  test/e2e/playwright/mmi/helpers/saturn-api-helper.ts
  test/e2e/playwright/mmi/helpers/utils.ts
  test/e2e/playwright/mmi/pageObjects/mmi-accountMenu-page.ts
  test/e2e/playwright/mmi/pageObjects/mmi-auth0-page.ts
  test/e2e/playwright/mmi/pageObjects/mmi-dummyApp-page.ts
  test/e2e/playwright/mmi/pageObjects/mmi-extension-page.ts
  test/e2e/playwright/mmi/pageObjects/mmi-main-page.ts
  test/e2e/playwright/mmi/pageObjects/mmi-mainMenu-page.ts
  test/e2e/playwright/mmi/pageObjects/mmi-network-page.ts
  test/e2e/playwright/mmi/pageObjects/mmi-saturn-page.ts
  test/e2e/playwright/mmi/pageObjects/mmi-saturn-ui-page.ts
  test/e2e/playwright/mmi/pageObjects/mmi-signup-page.ts
  test/e2e/playwright/mmi/resources/circleci-artifact-screnshot.png
  test/e2e/playwright/mmi/resources/trace.png
  test/e2e/playwright/mmi/scripts/run-visual-test.sh
  test/e2e/playwright/mmi/specs/dapp.signature.spec.ts
  test/e2e/playwright/mmi/specs/dapp.spec.ts
  test/e2e/playwright/mmi/specs/extension.visual.spec.ts
  test/e2e/playwright/mmi/specs/extension.visual.spec.ts-snapshots/popop-token-remove-approve-mmi-visual-linux.png
  test/e2e/playwright/mmi/specs/extension.visual.spec.ts-snapshots/token-replacement-notification-mmi-visual-linux.png
  test/e2e/playwright/mmi/specs/navigation.spec.ts
  test/e2e/playwright/mmi/specs/qrCode.spec.ts
  test/e2e/playwright/mmi/specs/transactions.spec.ts
  test/e2e/playwright/mmi/specs/visual.spec.ts
  test/e2e/playwright/mmi/specs/visual.spec.ts-snapshots/MMI-visual-Full-visual-e2e-1-mmi-visual-linux.png
  test/e2e/playwright/mmi/specs/visual.spec.ts-snapshots/connect-custodian-mmi-visual-linux.png
  test/e2e/playwright/mmi/specs/visual.spec.ts-snapshots/custodian-connection-info-mmi-visual-linux.png
  test/e2e/playwright/mmi/specs/visual.spec.ts-snapshots/custodian-list-mmi-visual-linux.png
  test/e2e/playwright/mmi/specs/visual.spec.ts-snapshots/custodian-remove-token-mmi-visual-linux.png
  test/e2e/playwright/mmi/specs/visual.spec.ts-snapshots/custody-accounts-selection-mmi-visual-linux.png
  test/e2e/playwright/mmi/specs/visual.spec.ts-snapshots/mainWindow-custodian-selected-mmi-visual-linux.png
  test/e2e/playwright/shared/pageObjects/activity-list-page.ts
  test/e2e/playwright/shared/pageObjects/extension-page.ts
  test/e2e/playwright/shared/pageObjects/network-controller-page.ts
  test/e2e/playwright/shared/pageObjects/signup-page.ts
  test/e2e/playwright/shared/pageObjects/wallet-page.ts
  test/e2e/playwright/swap/README.md
  test/e2e/playwright/swap/pageObjects/swap-page.ts
  test/e2e/playwright/swap/specs/swap.spec.ts
  ui/components/app/add-network/add-network.js
Labels: team-swaps

#25601 fix: asset picker bug
  test/e2e/tests/multichain/asset-picker-send.spec.ts
  ui/components/app/asset-list/asset-list.js
  ui/components/app/token-cell/token-cell.js
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/index.scss
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/token-list-item.js
  ui/components/multichain/token-list-item/token-list-item.test.js
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
Labels: team-assets, needs-assets-ux-review

#25211 chore: restore bot workflow to update attributions
  .github/workflows/update-attributions.yml
Labels: team-wallet-framework

#25425 fix: UX: Multichain: Fix dead network problem when switching tabs
  app/scripts/metamask-controller.js
  test/e2e/tests/request-queuing/ui.spec.js
  ui/store/actions.ts
Labels: team-wallet-ux, needs-assets-ux-review

#25438 feat: improvement for how we display big and small numbers
  ui/components/app/confirm/info/row/text.stories.tsx
  ui/components/app/confirm/info/row/text.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/row/__snapshots__/dataTree.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/dataTree.test.tsx
  ui/pages/confirmations/components/confirm/row/dataTree.tsx
  ui/pages/confirmations/components/confirm/utils.test.ts
Labels: confirmation-redesign, team-confirmations

#25646 fix: set network client id for domain
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
Labels: team-assets, needs-assets-ux-review

#25626 fix: changed logic to use the new banner alert
  ui/components/app/mmi-signature-mismatch-banner/index.ts
  ui/components/institutional/signature-mismatch-banner/index.ts
  ui/components/institutional/signature-mismatch-banner/signature-mismatch-banner.stories.tsx
  ui/components/institutional/signature-mismatch-banner/signature-mismatch-banner.test.tsx
  ui/components/institutional/signature-mismatch-banner/signature-mismatch-banner.tsx
  ui/pages/confirmations/confirm/confirm.tsx
Labels: team-mmi

#25628 fix: show connected toast only for EVM accounts
  ui/components/multichain/toast/toast.tsx
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.component.test.js
Labels: team-accounts

#25642 feat: added check for if the selected account is btc in transaction-list
  app/_locales/en/messages.json
  ui/components/app/transaction-list/index.scss
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/app/transaction-list/transaction-list.test.js
  ui/components/multichain/menu-items/view-explorer-menu-item.tsx
Labels: area-UI, team-accounts

#25659 fix: allow ramps dev environment on Flask
  app/scripts/lib/snap-keyring/keyring-snaps-permissions.test.ts
  app/scripts/lib/snap-keyring/keyring-snaps-permissions.ts
Labels: team-accounts

#25686 feat(ramps): add flag to ensure ramp networks are only fetched once
  ui/ducks/ramps/ramps.test.ts
  ui/ducks/ramps/ramps.ts
Labels: team-ramp

#25629 fix: confirmation when transaction (STX) is pending cross-network
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/hooks/alerts/transactions/useSigningOrSubmittingAlerts.test.ts
  ui/selectors/transactions.js
  ui/selectors/transactions.test.js
Labels: team-confirmations

#25544 feat: support security alerts API
  .metamaskrc.dist
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/ppom/ppom-util.test.ts
  app/scripts/lib/ppom/ppom-util.ts
  app/scripts/lib/ppom/security-alerts-api.test.ts
  app/scripts/lib/ppom/security-alerts-api.ts
  app/scripts/lib/ppom/types.ts
  app/scripts/lib/transaction/util.ts
  builds.yml
  shared/constants/security-provider.ts
  ui/helpers/utils/metrics.js
  ui/helpers/utils/metrics.test.js
  ui/pages/confirmations/components/confirm/blockaid-loading-indicator/blockaid-loading-indicator.test.tsx
  ui/pages/confirmations/hooks/alerts/useBlockaidAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/useBlockaidAlerts.ts
  ui/pages/confirmations/hooks/alerts/utils.test.ts
  ui/pages/confirmations/hooks/alerts/utils.ts
  ui/pages/confirmations/types/confirm.ts
Labels: team-confirmations

#25652 test: add e2e tests for navigation
  test/e2e/tests/confirmations/navigation.spec.ts
  ui/pages/confirmations/components/confirm/nav/__snapshots__/nav.test.tsx.snap
  ui/pages/confirmations/components/confirm/nav/nav.tsx
Labels: team-confirmations

#25632 test: e2e metrics test and refactor
  test/e2e/tests/confirmations/header.spec.js
  test/e2e/tests/confirmations/helpers.ts
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  test/e2e/tests/confirmations/signatures/personal-sign.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v3.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v4.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data.spec.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  ui/pages/confirmations/components/confirm/header/header-info.tsx
Labels: team-confirmations

#25689 fix: (cherry-pick Version v12.0.0) confirmation when transaction (STX) is pending cross-network
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/selectors/transactions.js
  ui/selectors/transactions.test.js
Labels: team-confirmations

#25570 feat: move unit tests from Circleci to Github actions
  .circleci/config.yml
  .github/actions/setup-environment/action.yml
  .github/workflows/run-unit-tests.yml
Labels: team-extension-platform

#25701 fix: version v12.1.0 cherry pick 90d89
  test/e2e/tests/multichain/asset-picker-send.spec.ts
  ui/components/app/asset-list/asset-list.js
  ui/components/app/token-cell/token-cell.js
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/index.scss
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.js.snap
  ui/components/multichain/token-list-item/token-list-item.js
  ui/components/multichain/token-list-item/token-list-item.test.js
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
Labels: team-assets, needs-assets-ux-review

#25675 fix: flaky test `Request-queue UI changes handles three confirmations on three confirmations concurrently`
  test/e2e/tests/request-queuing/ui.spec.js
  test/e2e/webdriver/driver.js
Labels: team-extension-platform, flaky tests

#25660 feat: Enable SIWE Signature Redesign
  ui/pages/confirmations/hooks/useCurrentConfirmation.test.ts
  ui/pages/confirmations/hooks/useCurrentConfirmation.ts
Labels: team-confirmations

#25706 fix: flaky test `Create token, approve token and approve token without gas approves an already created token and displays the token approval data`
  test/e2e/tests/tokens/custom-token-add-approve.spec.js
Labels: team-extension-platform, flaky tests

#25662 fix: Hide MMI Account Mistmatch BannerAlert from Sign-in with Ethereum (SIWE) Redesign Page
  ui/components/institutional/signature-mismatch-banner/signature-mismatch-banner.test.tsx
  ui/components/institutional/signature-mismatch-banner/signature-mismatch-banner.tsx
Labels: team-confirmations

#25153 fix: protect against phishing domain redirects in main/sub frames for http(s) requests
  app/manifest/v2/_base.json
  app/scripts/background.js
  app/scripts/metamask-controller.js
  development/build/set-environment-variables.js
  test/e2e/tests/phishing-controller/mock-page-with-iframe-but-disable-early-detection/index.html
  test/e2e/tests/phishing-controller/mock-page-with-iframe/index.html
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
Labels: team-extension-platform, team-security

#25715 feat: bundle pre-installed Bitcoin Wallet Snap
  app/scripts/snaps/preinstalled-snaps.ts
  package.json
  yarn.lock
Labels: team-accounts

#25668 Jl/caip multichain/scope helper specs
  app/scripts/lib/multichain-api/scope.test.ts
  app/scripts/lib/multichain-api/scope.ts
Labels: team-wallet-api-platform

#25722 chore: Revert "test: e2e metrics test and refactor"
  test/e2e/tests/confirmations/header.spec.js
  test/e2e/tests/confirmations/helpers.ts
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  test/e2e/tests/confirmations/signatures/personal-sign.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v3.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v4.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data.spec.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  ui/pages/confirmations/components/confirm/header/header-info.tsx
Labels: INVALID-PR-TEMPLATE, team-confirmations

#25725 fix: revert "test: add e2e tests for navigation (#25652)"
  test/e2e/tests/confirmations/navigation.spec.ts
  ui/pages/confirmations/components/confirm/nav/__snapshots__/nav.test.tsx.snap
  ui/pages/confirmations/components/confirm/nav/nav.tsx
Labels: team-confirmations

#25712 Sj/caip 25 poc add method call validator
  .yarn/patches/@json-schema-spec-json-pointer-npm-0.1.2-3d06119887.patch
  .yarn/patches/@json-schema-tools-reference-resolver-npm-1.2.6-4e1497c16d.patch
  app/scripts/lib/multichain-api/multichainMethodCallValidator.ts
  app/scripts/lib/multichain-api/provider-request.js
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#24428 test: Add UI integration tests
  .github/workflows/run-integration-tests.yml
  .vscode/launch.json
  jest.integration.config.js
  package.json
  test/e2e/tests/confirmations/header.spec.js
  test/helpers/setup-after-helper.js
  test/helpers/setup-helper.js
  test/integration/config/env.js
  test/integration/config/setup.js
  test/integration/config/setupAfter.js
  test/integration/confirmations/signatures/personalSign.test.tsx
  test/integration/data/integration-init-state.json
  test/integration/data/onboarding-completion-route.json
  test/integration/onboarding/wallet-created.test.tsx
  test/jest/setup.js
  test/lib/render-helpers.js
  test/setup.js
  ui/__mocks__/react-router-dom.js
  ui/components/app/confirm/info/row/currency.tsx
  ui/components/app/nfts-tab/nfts-tab.test.js
  ui/components/app/smart-transactions/smart-transactions-opt-in-modal.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.test.js
  ui/index.js
  ui/pages/confirmations/components/confirm/header/__snapshots__/header-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/__snapshots__/header.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/header-info.tsx
  ui/pages/confirmations/components/confirm/header/header.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/hooks/useCurrentConfirmation.test.ts
  ui/pages/keychains/reveal-seed.test.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.test.js
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.test.js
  ui/pages/swaps/index.test.js
Labels: INVALID-PR-TEMPLATE, team-confirmations

#25739 fix: caveat mutations for non-EVM accounts
  app/scripts/controllers/permissions/caveat-mutators.js
  app/scripts/controllers/permissions/caveat-mutators.test.js
  ui/selectors/multichain.ts
Labels: team-accounts

#25731 fix: use LAVAMOAT_UPDATE_TOKEN in attributions workflow
  .github/workflows/update-attributions.yml
Labels: team-wallet-framework

#25676 chore(deps): bump @metamask/accounts-controller from ^17.0.0 to ^17.2.0
  package.json
  yarn.lock
Labels: team-accounts

#25702 fix: blockaid report url in redesigned pages
  app/scripts/lib/ppom/types.ts
  ui/ducks/confirm-alerts/confirm-alerts.ts
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/hooks/alerts/useBlockaidAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/useBlockaidAlerts.ts
  ui/pages/confirmations/hooks/alerts/utils.ts
  ui/pages/confirmations/types/confirm.ts
Labels: confirmation-redesign, team-confirmations

#25709 Jl/caip multichain/provider request spec
  app/scripts/lib/multichain-api/provider-request.js
  app/scripts/lib/multichain-api/provider-request.test.js
Labels: team-wallet-api-platform

#25713 Jl/caip multichain/provider authorize specs
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/provider-authorize.js
  app/scripts/lib/multichain-api/provider-authorize.test.js
  app/scripts/lib/multichain-api/provider-request.js
  app/scripts/lib/multichain-api/scope.test.ts
  app/scripts/lib/multichain-api/scope.ts
  app/scripts/lib/multichain-api/scope/assert.test.ts
  app/scripts/lib/multichain-api/scope/assert.ts
  app/scripts/lib/multichain-api/scope/authorization.test.ts
  app/scripts/lib/multichain-api/scope/authorization.ts
  app/scripts/lib/multichain-api/scope/index.ts
  app/scripts/lib/multichain-api/scope/scope.test.ts
  app/scripts/lib/multichain-api/scope/scope.ts
  app/scripts/lib/multichain-api/scope/supported.test.ts
  app/scripts/lib/multichain-api/scope/supported.ts
  app/scripts/lib/multichain-api/scope/transform.test.ts
  app/scripts/lib/multichain-api/scope/transform.ts
  app/scripts/lib/multichain-api/scope/validation.test.ts
  app/scripts/lib/multichain-api/scope/validation.ts
Labels: team-wallet-api-platform

#25743 cherry-pick: fix blockaid report url in redesigned pages
  app/scripts/lib/ppom/types.ts
  ui/ducks/confirm-alerts/confirm-alerts.ts
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/hooks/alerts/useBlockaidAlert.test.ts
  ui/pages/confirmations/hooks/alerts/useBlockaidAlert.ts
  ui/pages/confirmations/hooks/alerts/utils.ts
  ui/pages/confirmations/types/confirm.ts
Labels: confirmation-redesign, team-confirmations, release-12.0.0

#25744 fix: flaky test `Test Snap Metrics test snap update rejected metric`
  test/e2e/snaps/test-snap-metrics.spec.js
Labels: team-extension-platform, flaky tests

#25625 feat(btc): add BTC account creation menu entry
  app/_locales/en/messages.json
  app/scripts/lib/snap-keyring/bitcoin-wallet-snap.ts
  test/e2e/accounts/snap-account-settings.spec.ts
  test/e2e/tests/account/import-flow.spec.js
  test/e2e/tests/tokens/nft/import-nft.spec.js
  test/manual-scenarios/incoming-transactions/receive native token.csv
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/account-list-menu/account-list-menu.test.js
  ui/components/multichain/create-btc-account/create-btc-account.stories.js
  ui/components/multichain/create-btc-account/create-btc-account.test.tsx
  ui/components/multichain/create-btc-account/create-btc-account.tsx
  ui/components/multichain/create-btc-account/index.ts
  ui/components/multichain/create-eth-account/create-eth-account.stories.js
  ui/components/multichain/index.js
  ui/pages/home/home.container.js
  ui/selectors/accounts.test.ts
  ui/selectors/accounts.ts
  ui/store/actions.ts
Labels: team-accounts

#25719 fix: show correct asset and balance when BTC account is the selected account
  test/data/mock-state.json
  test/jest/mock-store.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/ui/account-list/account-list.js
  ui/components/ui/account-list/account-list.stories.js
  ui/components/ui/account-list/account-list.test.js
  ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.test.ts
  ui/pages/permissions-connect/permissions-connect.stories.js
  ui/selectors/selectors.js
Labels: team-accounts

#25672 feat: add BTC experimental toggle
  app/_locales/en/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  test/data/mock-state.json
  test/e2e/json-rpc/switchEthereumChain.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/request-queuing/enable-queuing.spec.js
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.component.tsx
  ui/pages/settings/experimental-tab/experimental-tab.container.ts
  ui/pages/settings/experimental-tab/experimental-tab.test.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-accounts

#25574 fix: Fix issue 25285 max insufficient funds for gas
  ui/components/multichain/asset-picker-amount/asset-picker-amount.stories.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-amount.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx
  ui/ducks/send/send.js
Labels: QA Passed, team-confirmations, send-swap

#25718 cherry-pick: fix decimal places displayed on token value on permit pages
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/components/confirm/row/dataTree.tsx
  ui/pages/confirmations/components/confirm/row/typed-sign-data/typedSignData.tsx
  ui/pages/confirmations/components/confirm/utils.test.ts
  ui/pages/confirmations/components/confirm/utils.ts
Labels: confirmation-redesign, team-confirmations, release-12.1.0

#25621 feat(ramps): update isNativeTokenBuyable to include BTC
  ui/components/app/asset-list/asset-list.js
  ui/components/app/wallet-overview/btc-overview.test.tsx
  ui/components/app/wallet-overview/btc-overview.tsx
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/ducks/ramps/ramps.test.ts
  ui/ducks/ramps/ramps.ts
  ui/ducks/ramps/types.ts
  ui/helpers/ramps/rampApi/rampAPI.ts
  ui/selectors/multichain.test.ts
  ui/selectors/multichain.ts
Labels: team-ramp

#25610 feat: add `Delineator` component
  ui/components/ui/delineator/delineator.stories.tsx
  ui/components/ui/delineator/delineator.test.tsx
  ui/components/ui/delineator/delineator.tsx
  ui/components/ui/delineator/delineator.types.ts
  ui/components/ui/delineator/index.scss
  ui/components/ui/delineator/index.ts
  ui/components/ui/delineator/utils.ts
  ui/components/ui/ui-components.scss
Labels: team-confirmations

#25720 cherry-pick: feat improvement for how we display big and small numbers
  ui/components/app/confirm/info/row/text.stories.tsx
  ui/components/app/confirm/info/row/text.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/row/__snapshots__/dataTree.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/dataTree.test.tsx
  ui/pages/confirmations/components/confirm/row/dataTree.tsx
  ui/pages/confirmations/components/confirm/utils.test.ts
Labels: confirmation-redesign, team-confirmations, release-12.1.0

#25760 fix: fine-tune for `Delineator` component styles
  ui/components/ui/delineator/delineator.stories.tsx
  ui/components/ui/delineator/delineator.tsx
  ui/components/ui/delineator/index.scss
Labels: team-confirmations

#25581 chore: Update Snaps codeowners list
  .github/CODEOWNERS
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#25738 Cherry pick 574f819 into v12
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#25639 fix: Fix page width for fullscreen mode send page
  ui/components/multichain/pages/send/index.scss
Labels: team-extension-platform, needs-assets-ux-review

#25773 fix: remove accounts validation and get the accounts from requestPerm…
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/provider-authorize.js
  app/scripts/lib/multichain-api/provider-authorize.test.js
  app/scripts/lib/multichain-api/scope/validation.ts
Labels: team-wallet-api-platform

#25767 feat: add more whitelisted portfolio URLs
  app/scripts/lib/snap-keyring/keyring-snaps-permissions.ts
Labels: team-accounts

#25708 Jl/caip multichain/handle accounts provider authorize
  app/scripts/controllers/permissions/specifications.js
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/provider-authorize.js
  app/scripts/lib/multichain-api/provider-authorize.test.js
  app/scripts/lib/multichain-api/provider-request.js
  app/scripts/lib/multichain-api/scope.ts
  app/scripts/lib/multichain-api/scope/assert.test.ts
  app/scripts/lib/multichain-api/scope/assert.ts
  app/scripts/lib/multichain-api/scope/authorization.test.ts
  app/scripts/lib/multichain-api/scope/authorization.ts
  app/scripts/lib/multichain-api/scope/index.ts
  app/scripts/lib/multichain-api/scope/scope.test.ts
  app/scripts/lib/multichain-api/scope/scope.ts
  app/scripts/lib/multichain-api/scope/supported.test.ts
  app/scripts/lib/multichain-api/scope/supported.ts
  app/scripts/lib/multichain-api/scope/transform.test.ts
  app/scripts/lib/multichain-api/scope/transform.ts
  app/scripts/lib/multichain-api/scope/validation.test.ts
  app/scripts/lib/multichain-api/scope/validation.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#25774 Chore: cherry pick PR for flaky test vault-decrypt
  development/build/index.js
  test/e2e/vault-decryption-chrome.spec.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#25775 chore: update @metamask/bitcoin-wallet-snap to 0.2.3
  package.json
  yarn.lock
Labels: team-accounts

#25776 chore: remove `BTC_BETA_SUPPORT` flag
  builds.yml
Labels: team-accounts

#25735 test: add e2e tests for navigation (#25652)
  test/e2e/tests/confirmations/navigation.spec.ts
  ui/pages/confirmations/components/confirm/nav/__snapshots__/nav.test.tsx.snap
  ui/pages/confirmations/components/confirm/nav/nav.tsx
Labels: INVALID-PR-TEMPLATE, team-confirmations

#25736 feat: Add `ui_customizations` metric for transactions
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
  shared/modules/metametrics.test.ts
  test/e2e/tests/confirmations/transactions/contract-interaction-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/metrics.spec.ts
  test/e2e/tests/confirmations/transactions/shared.ts
Labels: confirmation-redesign, confirmation-re-design, team-confirmations

#25741 fix: Error: new BigNumber() more than 15 digits feat: apply ellipsis
  shared/modules/transaction.utils.test.js
  shared/modules/transaction.utils.ts
  ui/components/app/confirm/info/row/text.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/__snapshots__/personal-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/__snapshots__/siwe-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/__snapshots__/advanced-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/__snapshots__/transaction-data.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/row/__snapshots__/dataTree.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/dataTree.tsx
  ui/pages/confirmations/components/confirm/row/typed-sign-data-v1/__snapshots__/typedSignDataV1.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data/__snapshots__/typedSignData.test.tsx.snap
  ui/pages/confirmations/components/simulation-details/formatAmount.test.ts
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/stories/utils.tsx
Labels: team-confirmations

#25758 revert: un-revert metrics and signature refactor test
  test/e2e/tests/confirmations/header.spec.js
  test/e2e/tests/confirmations/helpers.ts
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  test/e2e/tests/confirmations/signatures/personal-sign.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v3.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v4.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data.spec.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
Labels: team-confirmations

#25726 feat: Make Jest unit tests run faster in GitHub actions
  .github/workflows/run-unit-tests.yml
  development/build/transforms/remove-fenced-code.test.js
  development/build/transforms/utils.test.js
  development/jest.config.js
  jest.config.js
  package.json
  test/run-unit-tests.js
Labels: team-extension-platform

#25784 fix: add caip25 caveat mutator for removeAccounts
  app/scripts/lib/multichain-api/caip25permissions.test.ts
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/provider-authorize.js
  app/scripts/lib/multichain-api/provider-request.js
  app/scripts/lib/multichain-api/scope/validation.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#25798 chore: removed unused getCustodianAccountsByAddress method
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/controllers/mmi-controller.ts
  app/scripts/metamask-controller.js
  ui/store/institutional/institution-background.test.js
  ui/store/institutional/institution-background.ts
Labels: team-mmi

#25801 Version v12.0.0 beta.0
  .circleci/config.yml
  development/metamaskbot-build-announce.js
Labels: INVALID-PR-TEMPLATE

#25808 chore: update @metamask/bitcoin-wallet-snap to 0.2.4
  package.json
  yarn.lock
Labels: team-accounts

#25684 chore: refactor custody component
  ui/pages/institutional/custodian-accounts-connected/__snapshots__/custodian-accounts-connected.test.tsx.snap
  ui/pages/institutional/custodian-accounts-connected/custodian-accounts-connected.test.tsx
  ui/pages/institutional/custodian-accounts-connected/custodian-accounts-connected.tsx
  ui/pages/institutional/custodian-accounts-connected/index.ts
  ui/pages/institutional/custodian-list-view/__snapshots__/custodian-list-view.test.tsx.snap
  ui/pages/institutional/custodian-list-view/custodian-list-view.test.tsx
  ui/pages/institutional/custodian-list-view/custodian-list-view.tsx
  ui/pages/institutional/custodian-list-view/index.ts
  ui/pages/institutional/custody/__snapshots__/custody.test.js.snap
  ui/pages/institutional/custody/custody.js
  ui/pages/institutional/manual-connect-custodian/index.ts
  ui/pages/institutional/manual-connect-custodian/manual-connect-custodian.tsx
Labels: team-mmi

#25695 fix: skip blockaid validations for users internal accounts
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/transaction/util.test.ts
  app/scripts/lib/transaction/util.ts
  app/scripts/metamask-controller.js
Labels: team-confirmations

#25682 feat: add option of copy to info row component
  ui/components/app/confirm/info/__snapshots__/info.test.tsx.snap
  ui/components/app/confirm/info/row/__snapshots__/copy-icon.test.tsx.snap
  ui/components/app/confirm/info/row/__snapshots__/expandable-row.test.tsx.snap
  ui/components/app/confirm/info/row/__snapshots__/row.test.tsx.snap
  ui/components/app/confirm/info/row/alert-row/__snapshots__/alert-row.test.tsx.snap
  ui/components/app/confirm/info/row/copy-icon.test.tsx
  ui/components/app/confirm/info/row/copy-icon.tsx
  ui/components/app/confirm/info/row/row.stories.tsx
  ui/components/app/confirm/info/row/row.test.tsx
  ui/components/app/confirm/info/row/row.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/contract-interaction/__snapshots__/contract-interaction.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/__snapshots__/personal-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/__snapshots__/siwe-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/__snapshots__/advanced-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/__snapshots__/edit-gas-fees-row.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/__snapshots__/gas-fees-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-row/__snapshots__/gas-fees-row.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/__snapshots__/gas-fees-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/__snapshots__/transaction-data.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/__snapshots__/transaction-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/__snapshots__/dataTree.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data-v1/__snapshots__/typedSignDataV1.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data/__snapshots__/typedSignData.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: confirmation-redesign, team-confirmations

#25823 chore: Patch security issue in snaps-utils
  .yarn/patches/@metamask-snaps-utils-npm-7.6.0-5569b09766.patch
  package.json
  yarn.lock
Labels: release-blocker, INVALID-PR-TEMPLATE

#25827 chore: Patch security issue in snaps-utils
  .yarn/patches/@metamask-snaps-utils-npm-7.7.0-2cc1f044af.patch
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#25834 chore: update @metamask/bitcoin-wallet-snap to 0.2.4 (#25808)
  package.json
  yarn.lock
Labels: team-accounts

#25826 fix: edit path to dist folder
  playwright.config.ts
  test/e2e/playwright/mmi/helpers/extension-loader.ts
  test/e2e/playwright/mmi/scripts/run-visual-test.sh
  test/e2e/playwright/mmi/specs/extension.visual.spec.ts
  test/e2e/playwright/mmi/specs/extension.visual.spec.ts-snapshots/popop-token-remove-approve-mmi-visual-linux.png
  test/e2e/playwright/swap/pageObjects/swap-page.ts
  test/e2e/playwright/swap/specs/swap.spec.ts
Labels: team-mmi

#25264 feat: Add fuzzy matching for name lookup
  ui/components/multichain/pages/send/components/recipient.tsx
  ui/ducks/domains.js
  ui/pages/confirmations/send/send-content/add-recipient/domain-input.component.js
  ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js
Labels: area-snaps, INVALID-PR-TEMPLATE, team-snaps-platform

#25836 Sj/caip multichain getinternal
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/provider-authorize.js
  app/scripts/lib/multichain-api/provider-authorize.test.js
  app/scripts/lib/multichain-api/scope/assert.test.ts
  app/scripts/lib/multichain-api/scope/assert.ts
  app/scripts/lib/multichain-api/scope/authorization.test.ts
  app/scripts/lib/multichain-api/scope/authorization.ts
  app/scripts/lib/multichain-api/scope/supported.test.ts
  app/scripts/lib/multichain-api/scope/validation.ts
Labels: team-wallet-api-platform

#25787 fix: password reset
  .yarn/patches/@metamask-keyring-controller-npm-15.0.0-fa070ce311.patch
  package.json
  yarn.lock
Labels: team-accounts

#25524 feat: NFT details new design
  .yarn/patches/@metamask-assets-controllers-npm-34.0.0-ea790e90a1.patch
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/tokens/nft/send-nft.spec.js
  test/e2e/tests/tokens/nft/view-erc1155-details.spec.js
  test/e2e/tests/tokens/nft/view-nft-details.spec.js
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/index.scss
  ui/components/app/nft-details/nft-detail-description.stories.js
  ui/components/app/nft-details/nft-detail-description.tsx
  ui/components/app/nft-details/nft-detail-information-frame.stories.js
  ui/components/app/nft-details/nft-detail-information-frame.tsx
  ui/components/app/nft-details/nft-detail-information-row.stories.js
  ui/components/app/nft-details/nft-detail-information-row.tsx
  ui/components/app/nft-details/nft-details.js
  ui/components/app/nft-details/nft-details.test.js
  ui/components/app/nft-details/nft-details.tsx
  ui/components/app/nft-details/nft-full-image.tsx
  ui/components/app/nft-options/nft-options.js
  ui/components/app/snaps/show-more/show-more.js
  ui/components/multichain/nft-item/index.scss
  ui/components/multichain/nft-item/nft-item.js
  ui/components/multichain/pages/page/components/header/header.tsx
  ui/helpers/constants/routes.ts
  ui/helpers/utils/util.js
  ui/pages/asset/components/asset-breadcrumb.js
  ui/pages/asset/util.ts
  ui/pages/routes/routes.component.js
  yarn.lock
Labels: team-assets, needs-assets-ux-review

#25663 feat(tests): add btc e2e tests
  privacy-snapshot.json
  test/e2e/accounts/common.ts
  test/e2e/accounts/create-snap-account.spec.ts
  test/e2e/fixture-builder.js
  test/e2e/flask/btc/btc-account-overview.spec.ts
  test/e2e/flask/btc/btc-dapp-connection.spec.ts
  test/e2e/flask/btc/btc-experimental-settings.spec.ts
  test/e2e/flask/btc/create-btc-account.spec.ts
  test/e2e/helpers.js
  ui/pages/settings/experimental-tab/experimental-tab.component.tsx
Labels: team-accounts

#25828 fix: use of an header in a dedicated call
  ui/helpers/utils/notification.util.ts
Labels: team-notifications

#25772 feat: support creation of Bitcoin testnet accounts
  app/_locales/en/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  test/data/mock-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/account-list-menu/account-list-menu.js
  ui/components/multichain/create-btc-account/create-btc-account.stories.js
  ui/components/multichain/create-btc-account/create-btc-account.test.tsx
  ui/components/multichain/create-btc-account/create-btc-account.tsx
  ui/pages/settings/experimental-tab/experimental-tab.component.tsx
  ui/pages/settings/experimental-tab/experimental-tab.container.ts
  ui/pages/settings/experimental-tab/experimental-tab.test.js
  ui/selectors/accounts.test.ts
  ui/selectors/accounts.ts
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-accounts

#25841 remove methods from multichain API
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/scope/assert.test.ts
  app/scripts/lib/multichain-api/scope/assert.ts
  app/scripts/lib/rpc-method-middleware/createMethodMiddleware.js
  app/scripts/lib/rpc-method-middleware/createMethodMiddleware.test.js
  app/scripts/lib/rpc-method-middleware/handlers/index.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-wallet-api-platform

#25861 fix: flaky test `Create BTC Account cannot create multiple BTC accounts...`
  test/e2e/accounts/common.ts
Labels: team-extension-platform, flaky tests, area-qa

#25854 fix: flaky test `ERC721 NFTs testdapp interaction`
  test/e2e/tests/tokens/nft/erc721-interaction.spec.js
Labels: team-extension-platform, flaky tests, area-qa

#25759 fix: contract data in metrics
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/lib/util.test.js
  app/scripts/lib/util.ts
  app/scripts/metamask-controller.js
  shared/lib/four-byte.test.ts
  shared/lib/four-byte.ts
  shared/lib/index.d.ts
  shared/lib/transaction-controller-utils.test.js
  shared/lib/transactions-controller-utils.js
  shared/modules/metametrics.test.ts
  types/global.d.ts
  ui/helpers/utils/transactions.util.js
  ui/helpers/utils/transactions.util.test.js
  ui/store/actions.ts
Labels: type-bug, team-confirmations

#25816 chore: Master sync
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#25691 feat: regression label
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/scripts/check-template-and-add-labels.ts
Labels: team-extension-platform

#25456 fix: update build version to align with firefox's newer version restrictions
  app/scripts/lib/setup-initial-state-hooks.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  app/scripts/platforms/extension.js
  app/scripts/platforms/extension.test.js
  builds.yml
  development/build/utils.js
  development/lib/build-type.js
  ui/index.js
  ui/pages/settings/info-tab/info-tab.component.js
Labels: team-extension-platform

#25849 fix: add name to scuttling exception list
  development/build/index.js
Labels: team-lavamoat, INVALID-PR-TEMPLATE

#25857 chore: bump assets-controllers to v36.0.0
  .yarn/patches/@metamask-assets-controllers-npm-34.0.0-ea790e90a1.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-assets, needs-assets-ux-review

#25804 fix: (cherry-pick)(Version v12.1.0) Error: new BigNumber() more than 15 digits feat: apply ellipsis #25741
  shared/modules/transaction.utils.test.js
  shared/modules/transaction.utils.ts
  ui/components/app/confirm/info/row/text.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/__snapshots__/personal-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/__snapshots__/siwe-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/__snapshots__/advanced-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/row/__snapshots__/dataTree.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/dataTree.tsx
  ui/pages/confirmations/components/confirm/row/typed-sign-data-v1/__snapshots__/typedSignDataV1.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data/__snapshots__/typedSignData.test.tsx.snap
  ui/pages/confirmations/components/simulation-details/formatAmount.test.ts
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/stories/utils.tsx
Labels: type-bug, release-blocker, team-confirmations, release-12.1.0, regression-RC-12.1.0

#25848 feat: Replace "Manage in settings" with "No thanks" in the STX Opt In modal, only show the modal for non-zero balances
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/modules/selectors/index.test.ts
  shared/modules/selectors/smart-transactions.ts
  test/e2e/playwright/swap/pageObjects/swap-page.ts
  ui/components/app/smart-transactions/smart-transactions-opt-in-modal.test.tsx
  ui/components/app/smart-transactions/smart-transactions-opt-in-modal.tsx
  ui/pages/onboarding-flow/metametrics/metametrics.js
  ui/pages/onboarding-flow/metametrics/metametrics.test.js
Labels: team-transactions

#25893 Cherry pick: feat: Replace "Manage in settings" with "No thanks" in the STX Opt In modal, only show the modal for non-zero balances
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/modules/selectors/index.test.ts
  shared/modules/selectors/smart-transactions.ts
  ui/components/app/smart-transactions/smart-transactions-opt-in-modal.test.tsx
  ui/components/app/smart-transactions/smart-transactions-opt-in-modal.tsx
  ui/pages/onboarding-flow/metametrics/metametrics.js
  ui/pages/onboarding-flow/metametrics/metametrics.test.js
Labels: team-transactions, release-12.0.0

#25681 chore: refactor SwapsController so it extends from BaseControllerV2
  app/scripts/controllers/swaps.constants.ts
  app/scripts/controllers/swaps.test.ts
  app/scripts/controllers/swaps.ts
  app/scripts/controllers/swaps.types.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: type-refactor, team-swaps

#25886 fix: disables "swap and send" for MMI
  test/e2e/tests/multichain/asset-picker-send.spec.ts
  test/e2e/tests/swap-send/swap-send-erc20.spec.ts
  test/e2e/tests/swap-send/swap-send-eth.spec.ts
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
  ui/components/multichain/pages/send/components/recipient-content.tsx
Labels: team-mmi, release-12.1.0

#25895 fix: test failure on firefox
  test/e2e/tests/confirmations/transactions/contract-interaction-redesign.spec.ts
Labels: team-confirmations

#25259 feat: add custom form check alerts
  app/_locales/en/messages.json
  test/e2e/playwright/shared/pageObjects/network-controller-page.ts
  test/e2e/tests/network/add-custom-network.spec.js
  test/e2e/tests/network/custom-rpc-history.spec.js
  test/e2e/tests/network/update-network.spec.ts
  ui/components/multichain/network-list-item-menu/network-list-item-menu.js
  ui/components/multichain/network-list-item/__snapshots__/network-list-item.test.js.snap
  ui/components/multichain/network-list-item/network-list-item.js
  ui/components/multichain/network-list-menu/add-rpc-url-modal/__snapshots__/add-rpc-url-modal.test.tsx.snap
  ui/components/multichain/network-list-menu/add-rpc-url-modal/add-rpc-url-modal.test.tsx
  ui/components/multichain/network-list-menu/add-rpc-url-modal/add-rpc-url-modal.tsx
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
  ui/components/multichain/network-list-menu/network-list-search/__snapshots__/network-list-search.test.tsx.snap
  ui/components/multichain/network-list-menu/network-list-search/network-list-search.tsx
  ui/components/multichain/network-list-menu/popular-network-list/popular-network-list.tsx
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/onboarding-flow/add-network-modal/__snapshots__/add-network-modal.test.js.snap
  ui/pages/onboarding-flow/add-network-modal/add-network-modal.test.js
  ui/pages/onboarding-flow/add-network-modal/index.js
  ui/pages/settings/networks-tab/index.scss
  ui/pages/settings/networks-tab/networks-form/__snapshots__/rpc-url-editor.test.tsx.snap
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/settings/networks-tab/networks-form/networks-form.test.js
  ui/pages/settings/networks-tab/networks-form/rpc-url-editor.test.tsx
  ui/pages/settings/networks-tab/networks-form/rpc-url-editor.tsx
  ui/pages/settings/networks-tab/networks-tab-content/networks-tab-content.test.js
  ui/pages/settings/networks-tab/networks-tab.test.js
  ui/selectors/selectors.js
Labels: team-assets, needs-assets-ux-review

#25799 fix: calcTokenAmount BigNumber more than 15 digits error
  app/scripts/controllers/swaps.ts
  shared/lib/transaction-controller-utils.test.js
  shared/lib/transactions-controller-utils.js
Labels: type-bug, team-snaps, needs-dev-review, team-confirmations

#25910 test: Removed step from e2e tests
  test/e2e/playwright/shared/pageObjects/signup-page.ts
Labels: team-swaps

#25503 fix(22851): check if active device to prevent autoconnect for hw
  ui/pages/create-account/connect-hardware/index.js
Labels: team-hardware-wallets

#25905 fix: Remove abandoned test:unit:jest command
  package.json
Labels: team-extension-platform

#25907 fix: fix
  app/_locales/en/messages.json
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: team-assets, needs-assets-ux-review

#25904 fix: disables "swap and send" for MMI (#25886)
  test/e2e/tests/swap-send/swap-send-erc20.spec.ts
  test/e2e/tests/swap-send/swap-send-eth.spec.ts
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
  ui/components/multichain/pages/send/components/recipient-content.tsx
Labels: team-mmi

#25898 feat: (cherry-pick)(Version v12.1.0) update Permit Signature Redesign "Spending cap" copy (#25618)
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
Labels: team-confirmations, release-12.1.0

#25822 fix: track token detection enabled
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/nft-detection-metrics.spec.js
  test/e2e/tests/metrics/token-detection-metrics.spec.js
Labels: team-assets, needs-assets-ux-review

#24803 chore: swaps codeowners reorg
  .eslintrc.js
  .github/CODEOWNERS
  app/scripts/controllers/swaps/index.ts
  app/scripts/controllers/swaps/swaps.constants.ts
  app/scripts/controllers/swaps/swaps.test.ts
  app/scripts/controllers/swaps/swaps.types.ts
  app/scripts/controllers/swaps/swaps.utils.ts
  ui/components/multichain/pages/send/send.js
  ui/pages/swaps/hooks/useUpdateSwapsState.test.ts
  ui/pages/swaps/hooks/useUpdateSwapsState.ts
  ui/pages/swaps/index.js
Labels: team-swaps

#25670 feat: Add full screen Snap Home and Dialog
  app/_locales/en/messages.json
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-homepage.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  ui/components/app/app-components.scss
  ui/components/app/snaps/snap-authorship-expanded/snap-authorship-expanded.js
  ui/components/app/snaps/snap-authorship-header/snap-authorship-header.js
  ui/components/app/snaps/snap-home-menu/index.js
  ui/components/app/snaps/snap-home-menu/index.scss
  ui/components/app/snaps/snap-home-menu/snap-home-menu.js
  ui/components/app/snaps/snap-home-page/snap-home-renderer.js
  ui/components/app/snaps/snap-metadata-modal/snap-metadata-modal.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/pages/confirmations/confirmation/confirmation.js
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/confirmations/confirmation/templates/create-snap-account.js
  ui/pages/confirmations/confirmation/templates/remove-snap-account.js
  ui/pages/create-snap-account/create-snap-account.tsx
  ui/pages/permissions-connect/permissions-connect.component.js
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
  ui/pages/permissions-connect/snaps/snap-result/snap-result.js
  ui/pages/permissions-connect/snaps/snap-update/snap-update.js
  ui/pages/remove-snap-account/remove-snap-account.test.tsx
  ui/pages/remove-snap-account/remove-snap-account.tsx
  ui/pages/routes/routes.component.js
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
  ui/pages/snaps/snap-view/snap-home.js
  ui/pages/snaps/snap-view/snap-settings.js
  ui/pages/snaps/snap-view/snap-view.js
  ui/pages/snaps/snap-view/snap-view.test.js
Labels: team-snaps-platform

#25138 fix: Handle error when offscreen document already exists
  app/scripts/offscreen.js
Labels: team-extension-platform, needs-dev-review

#25944 fix: Implement Auto-Enable Feature for Basic Functionality in Metamask Extension v12.1.0
  app/_locales/en/messages.json
  ui/components/app/auto-detect-token/auto-detect-token-modal.tsx
Labels: team-assets, needs-assets-ux-review

#25931 fix: fix css nft detail
  test/e2e/tests/tokens/nft/view-erc1155-details.spec.js
  test/e2e/tests/tokens/nft/view-nft-details.spec.js
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/nft-details.tsx
Labels: team-assets

#25875 feat: add BTC support survey link
  app/_locales/en/messages.json
  shared/constants/urls.ts
  ui/pages/settings/experimental-tab/experimental-tab.component.tsx
Labels: team-accounts

#25435 refactor: use `withKeyring` method
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-wallet-framework

#25809 ci: Disabling non-lint CI on the l10n_crowdin_action branch
  .circleci/config.yml
  .circleci/scripts/validate-locales-only.ts
  test/e2e/changedFilesUtil.js
Labels: team-extension-platform

#25956 Allow empty ScopesObject
  app/scripts/lib/multichain-api/scope/assert.test.ts
  app/scripts/lib/multichain-api/scope/assert.ts
  app/scripts/lib/multichain-api/scope/validation.test.ts
  app/scripts/lib/multichain-api/scope/validation.ts
Labels: team-wallet-api-platform

#25957 Jl/caip multichain/fix provider request scope object check
  app/scripts/lib/multichain-api/provider-request.js
  app/scripts/lib/multichain-api/provider-request.test.js
Labels: team-wallet-api-platform

#25943 fix: v12: Fix layout of add contact page
  ui/pages/settings/contact-list-tab/index.scss
Labels: needs-assets-ux-review

#25946 fix: notification slowness and crashes
  app/scripts/controllers/authentication/authentication-controller.test.ts
  app/scripts/controllers/authentication/authentication-controller.ts
  app/scripts/controllers/metamask-notifications/metamask-notifications.ts
  app/scripts/controllers/metamask-notifications/services/feature-announcements.ts
  app/scripts/controllers/metamask-notifications/utils/utils.ts
  app/scripts/controllers/user-storage/user-storage-controller.ts
  ui/hooks/metamask-notifications/useSwitchNotifications.ts
  ui/pages/notifications-settings/notifications-settings-per-account.tsx
  ui/pages/notifications-settings/notifications-settings.tsx
Labels: team-notifications

#25870 fix: fixed max width for permissions page
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/connections/connections.tsx
  ui/components/multichain/pages/permissions-page/__snapshots__/permissions-page.test.js.snap
  ui/components/multichain/pages/permissions-page/permissions-page.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#25856 test: Add integration tests for permit simulation section
  test/integration/confirmations/signatures/permit.test.tsx
  test/integration/helpers.tsx
  ui/components/app/confirm/info/row/section.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
Labels: team-confirmations

#25884 fix(multichain): use accounts{Added,Removed} to fetch/clear balances
  app/scripts/lib/accounts/BalancesController.test.ts
  app/scripts/lib/accounts/BalancesController.ts
  app/scripts/lib/accounts/BalancesTracker.test.ts
  app/scripts/lib/accounts/BalancesTracker.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  ui/components/multichain/create-btc-account/create-btc-account.test.tsx
  ui/components/multichain/create-btc-account/create-btc-account.tsx
  ui/store/actions.ts
Labels: team-accounts

#25965 feat: Show the Close extension button on the Smart Transaction Status Page for a pending dapp transaction
  ui/pages/smart-transactions/smart-transaction-status-page/__snapshots__/smart-transactions-status-page.test.js.snap
  ui/pages/smart-transactions/smart-transaction-status-page/smart-transaction-status-page.tsx
  ui/pages/smart-transactions/smart-transaction-status-page/smart-transactions-status-page.test.js
Labels: team-transactions
