Repository MetaMask/metamask-extension, pull requests merged in 2024-08, with the labels that each got.

#26265 fix: add migration to remove any dangling instances of `perDomainNetwork` on `SelectedNetworkController` state
  app/scripts/migrations/120.2.test.ts
  app/scripts/migrations/120.2.ts
  app/scripts/migrations/index.js
Labels: team-wallet-api-platform

#26250 fix: improve warning in add network modal
  app/_locales/en/messages.json
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.js
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.test.js
Labels: team-confirmations

#26183 feat(btc): use new snap account flow for Bitcoin accounts
  app/scripts/lib/snap-keyring/snap-keyring.test.ts
  app/scripts/lib/snap-keyring/snap-keyring.ts
  ui/components/multichain/create-btc-account/create-btc-account.stories.js
  ui/components/multichain/create-btc-account/create-btc-account.test.tsx
  ui/components/multichain/create-btc-account/create-btc-account.tsx
  ui/components/multichain/create-btc-account/index.ts
  ui/components/multichain/create-named-snap-account/create-named-snap-account.test.tsx
  ui/components/multichain/create-named-snap-account/create-named-snap-account.tsx
  ui/components/multichain/index.js
  ui/pages/confirmations/confirmation/templates/create-named-snap-account.js
Labels: team-accounts

#26224 fix(multichain): fix showFiat option for test assets
  test/e2e/tests/settings/account-token-list.spec.js
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/connect-accounts-modal/__snapshots__/connect-accounts-modal.test.tsx.snap
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/components/multichain/pages/send/send.test.js
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/remove-snap-account.test.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/selectors/multichain.test.ts
  ui/selectors/multichain.ts
Labels: type-bug, team-accounts

#26181 feat: Add Snap UI Radio component
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/components/app/snaps/snap-ui-radio-group/index.ts
  ui/components/app/snaps/snap-ui-radio-group/snap-ui-radio-group.tsx
  ui/components/app/snaps/snap-ui-renderer/components/field.ts
  ui/components/app/snaps/snap-ui-renderer/components/index.ts
  ui/components/app/snaps/snap-ui-renderer/components/radioGroup.ts
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.test.js
  ui/components/app/snaps/snap-ui-renderer/utils.ts
Labels: team-snaps-platform

#26247 fix: Fix GitHub release description
  .circleci/scripts/release-create-gh-release.sh
Labels: team-wallet-framework

#25080 feat: QR-based add NGRAVE ZERO Hardware
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  shared/constants/hardware-wallets.ts
  ui/pages/create-account/connect-hardware/index.test.tsx
  ui/pages/create-account/connect-hardware/select-hardware.js
Labels: team-accounts, QA Passed, external-contributor, team-hardware-wallets

#26020 chore: Update `actions/cache` from v3 to v4
  .github/workflows/update-attributions.yml
  .github/workflows/update-lavamoat-policies.yml
Labels: team-extension-platform, needs-dev-review

#26276 fix: remove submitRequest from dapp permission
  app/scripts/lib/snap-keyring/keyring-snaps-permissions.test.ts
  app/scripts/lib/snap-keyring/keyring-snaps-permissions.ts
  test/e2e/constants.ts
  test/e2e/flask/user-operations.spec.ts
Labels: team-accounts

#26280 fix: Account for persistence flag when setting initial state in `ComposableObservableStore`
  app/scripts/lib/ComposableObservableStore.js
  app/scripts/lib/ComposableObservableStore.test.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#26275 test: fix flaky test Import flow @no-mmi Import wallet using Secret Recovery Phrase
  test/e2e/tests/account/import-flow.spec.js
Labels: team-extension-platform, flaky tests, area-qa

#26059 refactor: ENABLE_MV3 flag cleanup
  app/scripts/controllers/push-platform-notifications/push-platform-notifications.test.ts
  app/scripts/controllers/push-platform-notifications/push-platform-notifications.ts
  development/build/manifest.js
  development/build/scripts.js
  development/build/static.js
  development/build/utils.js
  package.json
  shared/modules/mv3.utils.js
  test/e2e/background-socket/socket-background-to-mocha.ts
  test/e2e/json-rpc/switchEthereumChain.spec.js
  test/e2e/tests/account/import-flow.spec.js
  test/e2e/tests/account/lockdown.spec.js
  test/e2e/webdriver/driver.js
Labels: needs-dev-review, team-notifications, team-contributor-experience, type-tech-debt

#26206 fix(26065): remove persisted state mostRecentRetrievedState after initialization if no errors
  app/scripts/background.js
  app/scripts/lib/local-store.js
  app/scripts/lib/local-store.test.js
  app/scripts/lib/network-store.js
  app/scripts/lib/setup-initial-state-hooks.js
Labels: team-extension-platform

#23823 refactor: convert `icon-factory.js` to typescript
  ui/helpers/utils/icon-factory.js
  ui/helpers/utils/icon-factory.ts
Labels: team-extension-platform

#26293 fix: Revert "fix: remove submitRequest from dapp permission"
  app/scripts/lib/snap-keyring/keyring-snaps-permissions.test.ts
  app/scripts/lib/snap-keyring/keyring-snaps-permissions.ts
  test/e2e/constants.ts
  test/e2e/flask/user-operations.spec.ts
Labels: team-accounts, team-wallet-framework, team-extension-platform, INVALID-PR-TEMPLATE

#26291 fix: Truncate extremely long transaction histories
  app/scripts/migrations/120.3.test.ts
  app/scripts/migrations/120.3.ts
  app/scripts/migrations/index.js
Labels: team-wallet-framework

#26295 fix: add guard for draft tx in send validation
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
Labels: team-bridge

#26267 fix: Adding migration 125 to remove Deprecated TxController Key from state
  app/scripts/migrations/125.test.ts
  app/scripts/migrations/125.ts
  app/scripts/migrations/index.js
Labels: team-extension-platform

#26271 fix: remove the ability to send to btc accounts in send page
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/pages/connections/connections.tsx
  ui/components/multichain/pages/send/components/account-picker.test.tsx
  ui/components/multichain/pages/send/components/account-picker.tsx
  ui/components/multichain/pages/send/components/your-accounts.test.tsx
  ui/components/multichain/pages/send/components/your-accounts.tsx
  ui/selectors/permissions.js
  ui/selectors/selectors.js
  ui/selectors/selectors.types.ts
  ui/store/store.ts
Labels: team-accounts

#26298 refactor: Refactor migration 120.2 to prepare for additions
  app/scripts/migrations/120.2.test.ts
  app/scripts/migrations/120.2.ts
Labels: team-wallet-framework, team-extension-platform, needs-dev-review

#26305 fix: Cherry-pick persistence fix to RC
  app/scripts/lib/ComposableObservableStore.js
  app/scripts/lib/ComposableObservableStore.test.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#26227 feat: Update Redesign Signature Permit to show ellipsis at max 15 digits
  ui/components/app/confirm/info/row/text-token-units.test.tsx
  ui/components/app/confirm/info/row/text-token-units.tsx
  ui/components/app/confirm/info/row/text.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/simulation-details/formatAmount.test.ts
  ui/pages/confirmations/components/simulation-details/formatAmount.ts
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: team-confirmations

#26302 fix: Remove obsolete NetworkController state
  app/scripts/migrations/120.2.test.ts
  app/scripts/migrations/120.2.ts
Labels: team-wallet-framework, team-extension-platform, needs-dev-review

#26308 fix: Remove obsolete PhishingController state
  app/scripts/migrations/120.2.test.ts
  app/scripts/migrations/120.2.ts
Labels: team-wallet-framework, team-extension-platform, needs-dev-review

#26292 fix: get permit and order signatures token decimals
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/confirm.test.tsx
Labels: team-confirmations

#26323 fix: issue where `setNetworkClientIdForDomain` was called without checking whether the origin was eligible for setting its own network
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
Labels: team-wallet-api-platform

#26310 fix: Remove invalid providerConfig id
  app/scripts/migrations/120.2.test.ts
  app/scripts/migrations/120.2.ts
Labels: team-wallet-framework, team-extension-platform, needs-dev-review

#26279 fix: Fix GitHub release description (#26247)
  .circleci/scripts/release-create-gh-release.sh
Labels: team-extension-platform, needs-dev-review

#26328 Cherry-Pick: "fix: issue where `setNetworkClientIdForDomain` was called without checking whether the origin was eligible for setting its own network (#26323)"
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
Labels: INVALID-PR-TEMPLATE

#26325 fix(2946): disable the 'restore backup' in advanced settings
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/tests/settings/backup-restore.spec.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
Labels: team-extension-platform

#26329 cherry pick: undefined market data selector (#26264)
  app/scripts/controllers/swaps.js
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
  ui/selectors/confirm-transaction.js
Labels: INVALID-PR-TEMPLATE

#26296 Jl/caip multichain/caip 25 permission origin
  app/scripts/lib/multichain-api/caip-permission-adapter-middleware.js
  app/scripts/lib/multichain-api/caip-permission-adapter-middleware.test.js
  app/scripts/lib/multichain-api/caip25permissions.test.ts
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/provider-authorize/handler.js
  app/scripts/lib/multichain-api/provider-authorize/handler.test.js
  app/scripts/lib/multichain-api/provider-request.js
  app/scripts/lib/multichain-api/provider-request.test.js
  app/scripts/lib/multichain-api/wallet-getPermissions.test.js
  app/scripts/lib/multichain-api/wallet-getSession.test.js
  app/scripts/lib/multichain-api/wallet-requestPermissions.js
  app/scripts/lib/multichain-api/wallet-requestPermissions.test.js
  app/scripts/lib/multichain-api/wallet-revokeSession.test.js
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.js
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.test.js
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#26327 fix: Fix `currentNetwork` selector when current network config is missing
  ui/components/app/assets/nfts/nft-details/nft-details.tsx
  ui/components/app/assets/nfts/nft-details/nft-full-image.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
  ui/components/multichain/nft-item/nft-item.js
  ui/components/multichain/pages/send/components/network-picker.tsx
  ui/pages/confirmations/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/switch-ethereum-chain.test.js.snap
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-wallet-framework

#26336 fix: Stop logging pipeline stream errors in the service worker if they match 'Premature close'
  app/scripts/lib/stream-utils.js
  app/scripts/metamask-controller.js
Labels: team-extension-platform

#26268 chore: normalize separator in `content` on the `viewport` `meta` tag
  app/home.html
  app/popup.html
  development/ts-migration-dashboard/app/public/index.html
Labels: team-extension-platform

#26338 fix(2946): disable the 'restore backup' in advanced settings
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/tests/settings/backup-restore.spec.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
Labels: team-extension-platform

#26347 Cherry pick 2456ba3056 (#26336) to v12.0.1
  app/scripts/lib/stream-utils.js
  app/scripts/metamask-controller.js
Labels: INVALID-PR-TEMPLATE

#26333 test: Add test for migration 120.2 and fix docs
  app/scripts/migrations/120.2.test.ts
  app/scripts/migrations/120.2.ts
Labels: team-wallet-framework

#26236 Patch: Compress transaction history
  .yarn/patches/@metamask-transaction-controller-npm-32.0.0-e23c2c3443.patch
  app/scripts/migrations/120.3.test.ts
  app/scripts/migrations/120.3.ts
  app/scripts/migrations/index.js
  package.json
  yarn.lock
Labels: team-extension-platform, needs-dev-review

#26348 Update changelog for v12.0.1
  CHANGELOG.md
Labels: INVALID-PR-TEMPLATE

#26155 fix: enable Save button on Add Contact page for address input
  ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js
  ui/pages/settings/contact-list-tab/add-contact/add-contact.test.js
Labels: team-wallet-ux, regression-RC-12.1.0, regression-beta-12.1.0

#26351 fix(25350): fix flakey token importing e2e test
  test/e2e/tests/tokens/token-list.spec.ts
Labels: team-extension-platform

#26121 feat: Add metrics for alerts (transactions redesign)
  .storybook/preview.js
  ui/components/app/alert-system/alert-modal/alert-modal.test.tsx
  ui/components/app/alert-system/alert-modal/alert-modal.tsx
  ui/components/app/alert-system/confirm-alert-modal/confirm-alert-modal.stories.tsx
  ui/components/app/alert-system/confirm-alert-modal/confirm-alert-modal.test.tsx
  ui/components/app/alert-system/contexts/alertMetricsContext.test.tsx
  ui/components/app/alert-system/contexts/alertMetricsContext.tsx
  ui/components/app/alert-system/multiple-alert-modal/multiple-alert-modal.test.tsx
  ui/components/app/confirm/info/row/alert-row/alert-row.test.tsx
  ui/components/app/confirm/info/row/alert-row/alert-row.tsx
  ui/pages/confirmations/components/confirm/confirm-alerts/confirm-alerts.tsx
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/info/contract-interaction/__snapshots__/contract-interaction.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/contract-interaction/contract-interaction.test.tsx
  ui/pages/confirmations/components/confirm/info/info.test.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/__snapshots__/edit-gas-fees-row.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/__snapshots__/gas-fees-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/gas-fees-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/__snapshots__/gas-fees-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/gas-fees-section.test.tsx
  ui/pages/confirmations/hooks/alerts/constants.ts
  ui/pages/confirmations/hooks/useConfirmationAlertMetrics.test.ts
  ui/pages/confirmations/hooks/useConfirmationAlertMetrics.ts
Labels: team-confirmations

#26044 refactor: add performance tracing infrastructure
  app/_locales/en/messages.json
  app/scripts/lib/setupSentry.js
  development/README.md
  shared/lib/trace.test.ts
  shared/lib/trace.ts
  types/global.d.ts
  ui/index.js
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/developer-options-tab/developer-options-tab.tsx
  ui/pages/settings/developer-options-tab/sentry-test.tsx
  ui/store/actions.ts
Labels: team-confirmations, team-tiger

#26366 feat: Add integration test for blockaid on contract interaction
  test/integration/confirmations/transactions/contractInteraction.test.tsx
  test/integration/confirmations/transactions/transactionDataHelpers.tsx
Labels: team-confirmations

#26319 fix: remove submitRequest from dapp permission
  app/scripts/lib/snap-keyring/keyring-snaps-permissions.test.ts
  app/scripts/lib/snap-keyring/keyring-snaps-permissions.ts
  test/e2e/constants.ts
  test/e2e/flask/user-operations.spec.ts
Labels: team-accounts

#26381 refactor(notifications): use contentful package as dev dependency
  package.json
Labels: team-notifications

#26383 fix: Add migration 120.4 to delete obsolete currency controller state
  app/scripts/migrations/120.4.test.ts
  app/scripts/migrations/120.4.ts
  app/scripts/migrations/index.js
Labels: team-extension-platform

#26125 chore: MMI move duck and selector to TS
  ui/components/institutional/custody-confirm-link-modal/custody-confirm-link-modal.tsx
  ui/components/institutional/custody-labels/custody-labels.tsx
  ui/components/institutional/interactive-replacement-token-notification/interactive-replacement-token-notification.tsx
  ui/components/institutional/wrong-network-notification/wrong-network-notification.tsx
  ui/components/multichain/badge-status/badge-status.tsx
  ui/ducks/institutional/institutional.js
  ui/ducks/institutional/institutional.test.js
  ui/ducks/institutional/institutional.test.ts
  ui/ducks/institutional/institutional.ts
  ui/helpers/utils/institutional/find-by-custodian-name.test.ts
  ui/helpers/utils/institutional/find-by-custodian-name.ts
  ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.tsx
  ui/pages/institutional/custody/custody.tsx
  ui/pages/institutional/manual-connect-custodian/manual-connect-custodian.tsx
  ui/selectors/institutional/selectors.test.ts
  ui/selectors/institutional/selectors.ts
Labels: team-mmi

#26378 feat: updated SSK version in e2e and added test for creating multiple…
  test/e2e/accounts/common.ts
  test/e2e/accounts/create-snap-account.spec.ts
  test/e2e/constants.ts
  ui/components/multichain/create-named-snap-account/create-named-snap-account.test.tsx
  ui/components/multichain/create-named-snap-account/create-named-snap-account.tsx
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
Labels: team-accounts, e2e-test

#26396 fix: Delete obsolete properties from phishingController and networkControl…
  app/scripts/migrations/120.4.test.ts
  app/scripts/migrations/120.4.ts
Labels: team-extension-platform

#26397 fix: Fix invalid state causing migration 88 to fail
  app/scripts/migrations/088.test.ts
  app/scripts/migrations/088.ts
Labels: team-wallet-framework, needs-dev-review

#26390 fix(cherry-pick): Add migration 120.4 to delete obsolete currency, phishing and network controller state
  app/scripts/migrations/120.4.test.ts
  app/scripts/migrations/120.4.ts
  app/scripts/migrations/index.js
Labels: INVALID-PR-TEMPLATE

#26234 test: snap account contract interaction
  test/e2e/accounts/snap-account-contract-interaction.spec.ts
  test/e2e/fixture-builder.js
  test/e2e/helpers.js
  test/e2e/tests/confirmations/helpers.ts
Labels: team-accounts, needs-dev-review, e2e-test

#26400 Update changelog for v12.0.2
  CHANGELOG.md
Labels: INVALID-PR-TEMPLATE

#26370 refactor: use core profile syncing controllers.
  app/scripts/controllers/authentication/auth-snap-requests.ts
  app/scripts/controllers/authentication/authentication-controller.test.ts
  app/scripts/controllers/authentication/authentication-controller.ts
  app/scripts/controllers/authentication/mocks/mockResponses.ts
  app/scripts/controllers/authentication/mocks/mockServices.ts
  app/scripts/controllers/authentication/services.test.ts
  app/scripts/controllers/authentication/services.ts
  app/scripts/controllers/metamask-notifications/metamask-notifications.test.ts
  app/scripts/controllers/metamask-notifications/metamask-notifications.ts
  app/scripts/controllers/metamask-notifications/services/onchain-notifications.ts
  app/scripts/controllers/push-platform-notifications/push-platform-notifications.test.ts
  app/scripts/controllers/push-platform-notifications/push-platform-notifications.ts
  app/scripts/controllers/user-storage/encryption/cache.ts
  app/scripts/controllers/user-storage/encryption/encryption.test.ts
  app/scripts/controllers/user-storage/encryption/encryption.ts
  app/scripts/controllers/user-storage/encryption/index.ts
  app/scripts/controllers/user-storage/encryption/utils.ts
  app/scripts/controllers/user-storage/mocks/mockResponses.ts
  app/scripts/controllers/user-storage/mocks/mockServices.ts
  app/scripts/controllers/user-storage/mocks/mockStorage.ts
  app/scripts/controllers/user-storage/schema.test.ts
  app/scripts/controllers/user-storage/schema.ts
  app/scripts/controllers/user-storage/services.test.ts
  app/scripts/controllers/user-storage/services.ts
  app/scripts/controllers/user-storage/user-storage-controller.test.ts
  app/scripts/controllers/user-storage/user-storage-controller.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/notifications/mocks.ts
  ui/selectors/metamask-notifications/authentication.ts
  ui/selectors/metamask-notifications/profile-syncing.ts
  yarn.lock
Labels: team-notifications

#26384 fix: Improve hex copy button
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/__snapshots__/transaction-data.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.tsx
Labels: team-confirmations

#26412 fix: Restore snaps-controllers version following patch
  .yarn/patches/@metamask-snaps-controllers-npm-9.2.0-09a31bab4f.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26394 fix: Enter key on Create Account checkbox should not trigger show/hide
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/create-password/index.scss
Labels: type-bug, team-accounts, needs-dev-review, team-confirmations

#26420 fix: Flaky contract interaction test
  test/e2e/tests/confirmations/transactions/shared.ts
Labels: team-confirmations

#26380 chore: Remove i18n translations from Developer Options Settings Page
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/helpers/constants/settings.js
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/developer-options-tab/developer-options-tab.tsx
  ui/pages/settings/developer-options-tab/sentry-test.tsx
Labels: needs-dev-review, team-confirmations

#25771 fix (cherry-pick): Fix page width for fullscreen mode send page
  ui/components/multichain/pages/send/index.scss
Labels: team-wallet-ux

#26419 fix: V12.0.3/cherry pick notifications events
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  test/e2e/tests/metrics/wallet-created.spec.js
  ui/components/app/modals/turn-on-metamask-notifications/turn-on-metamask-notifications.tsx
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/notification-detail-button/notification-detail-button.tsx
  ui/pages/notifications-settings/notifications-settings-allow-notifications.tsx
  ui/pages/notifications-settings/notifications-settings-per-account.tsx
  ui/pages/notifications-settings/notifications-settings-types.tsx
  ui/pages/notifications/notification-components/snap/snap.tsx
  ui/pages/notifications/notifications-list-item.tsx
  ui/pages/onboarding-flow/creation-successful/creation-successful.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.tsx
Labels: team-notifications

#25811 feat: feature-flagged cross-chain swaps route [METABRIDGE-867]
  app/scripts/controllers/bridge.test.ts
  app/scripts/controllers/bridge.ts
  app/scripts/metamask-controller.js
  privacy-snapshot.json
  test/e2e/default-fixture.js
  test/e2e/mock-e2e.js
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/integration/data/onboarding-completion-route.json
  test/integration/onboarding/wallet-created.test.tsx
  test/jest/mock-store.js
  ui/components/app/wallet-overview/btc-overview.test.tsx
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/multichain/account-overview/account-overview-btc.test.tsx
  ui/components/multichain/account-overview/account-overview-eth.test.tsx
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/bridge.test.ts
  ui/helpers/constants/routes.ts
  ui/hooks/bridge/useBridging.test.ts
  ui/hooks/bridge/useBridging.ts
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/bridge/__snapshots__/index.test.tsx.snap
  ui/pages/bridge/index.scss
  ui/pages/bridge/index.test.tsx
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.component.test.js
  ui/selectors/selectors.js
  ui/store/actions.test.js
  ui/store/actions.ts
  ui/store/store.ts
Labels: team-bridge

#26398 build(webpack): polyfill `setImmediate`
  .depcheckrc.yml
  development/webpack/webpack.config.ts
  package.json
  yarn.lock
Labels: team-extension-platform

#26428 fix: Delete invalid `SelectedNetworkController` state
  app/scripts/migrations/120.5.test.ts
  app/scripts/migrations/120.5.ts
Labels: team-wallet-framework

#26339 feat: Enable why did you render
  .metamaskrc.dist
  app/scripts/ui.js
  builds.yml
  development/wdyr.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-accounts

#26109 chore: migrate BridgeController to BaseController v2
  app/scripts/controllers/bridge.test.ts
  app/scripts/controllers/bridge.ts
  app/scripts/controllers/bridge/bridge-controller.test.ts
  app/scripts/controllers/bridge/bridge-controller.ts
  app/scripts/controllers/bridge/constants.ts
  app/scripts/controllers/bridge/types.ts
  app/scripts/metamask-controller.js
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/bridge.test.ts
  ui/pages/bridge/bridge.util.ts
  ui/selectors/selectors.js
Labels: team-bridge

#26239 fix: timeout and "Rerun failed tests"
  .circleci/config.yml
  .circleci/scripts/test-run-e2e.sh
Labels: needs-dev-review, team-contributor-experience, greptile

#26272 test: add transaction contract interaction integration tests
  .vscode/launch.json
  test/integration/confirmations/signatures/permit.test.tsx
  test/integration/confirmations/transactions/contract-interaction.test.tsx
  test/integration/confirmations/transactions/contractInteraction.test.tsx
  test/integration/data/integration-init-state.json
  test/integration/data/transaction-helpers.tsx
  test/integration/helpers.tsx
  ui/components/app/confirm/info/row/row.tsx
  ui/components/app/confirm/info/row/text.tsx
  ui/pages/confirmations/components/confirm/info/contract-interaction/__snapshots__/contract-interaction.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/__snapshots__/advanced-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/advanced-details.tsx
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/__snapshots__/edit-gas-fees-row.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/__snapshots__/gas-fees-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/gas-fees-details.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-row/gas-fees-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/__snapshots__/gas-fees-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/gas-fees-section.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/__snapshots__/transaction-data.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/__snapshots__/transaction-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
  ui/pages/confirmations/components/simulation-details/fiat-display.tsx
Labels: INVALID-PR-TEMPLATE, team-confirmations

#25175 feat: Add abstraction for Snaps permissions
  app/_locales/en/messages.json
  shared/constants/permissions.ts
  test/data/mock-state.json
  ui/components/app/snaps/snap-permission-adapter/index.js
  ui/components/app/snaps/snap-permission-adapter/snap-permission-adapter.js
  ui/components/app/snaps/snap-permission-adapter/snap-permission-adapter.test.js
  ui/components/app/snaps/snap-permissions-list/snap-permissions-list.js
  ui/components/app/snaps/update-snap-permission-list/update-snap-permission-list.js
  ui/helpers/utils/permission.js
  ui/helpers/utils/util.js
  ui/helpers/utils/util.test.js
  ui/hooks/useScrollRequired.js
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
  ui/pages/permissions-connect/snaps/snap-update/snap-update.js
  ui/pages/snaps/snap-view/snap-settings.js
  ui/pages/snaps/snap-view/snap-view.test.js
Labels: team-snaps-platform

#26422 fix: problem with origins in the Snaps permission UI
  ui/components/app/snaps/snap-permissions-list/snap-permissions-list.js
  ui/helpers/utils/permission.js
Labels: type-bug, team-snaps-platform

#26114 fix: display toast message if user quickly sends transaction on different networks
  app/_locales/en/messages.json
  app/scripts/controllers/app-state.js
  app/scripts/controllers/app-state.test.js
  app/scripts/metamask-controller.js
  shared/types/confirm.ts
  test/e2e/tests/metrics/errors.spec.js
  ui/pages/confirmations/components/confirm/network-change-toast/index.scss
  ui/pages/confirmations/components/confirm/network-change-toast/index.tsx
  ui/pages/confirmations/components/confirm/network-change-toast/network-change-toast-legacy.test.tsx
  ui/pages/confirmations/components/confirm/network-change-toast/network-change-toast-legacy.tsx
  ui/pages/confirmations/components/confirm/network-change-toast/network-change-toast.tsx
  ui/pages/confirmations/components/index.scss
  ui/pages/confirmations/components/signature-request-original/signature-request-original.component.js
  ui/pages/confirmations/components/signature-request-original/signature-request-original.test.js
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe.js
  ui/pages/confirmations/components/signature-request-siwe/signature-request-siwe.test.js
  ui/pages/confirmations/components/signature-request/signature-request.js
  ui/pages/confirmations/confirm-approve/confirm-approve.js
  ui/pages/confirmations/confirm-send-ether/confirm-send-ether.test.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmations/confirm-transaction/confirm-transaction.transaction.test.js
  ui/pages/confirmations/confirm/confirm.tsx
  ui/store/actions.ts
Labels: team-confirmations

#25161 fix: Codespaces `corepack enable`
  .devcontainer/devcontainer.json
  .devcontainer/download-builds.ts
  development/generate-attributions/package.json
  package.json
Labels: team-contributor-experience, greptile

#26395 chore: Master sync
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#26450 fix (patch): erc20 token prices on non-ETH networks
  .yarn/patches/@metamask-assets-controllers-patch-a3b39b55a6.patch
  package.json
  yarn.lock
Labels: team-assets

#26453 fix: Fix SelectedNetworkController state corruption by making NetworkForm update in-place rather than remove and add for rpcUrl changes
  .yarn/patches/@metamask-network-controller-npm-19.0.0-a5e0d1fe14.patch
  app/scripts/migrations/index.js
  ui/components/ui/deprecated-networks/deprecated-networks.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: team-wallet-api-platform

#26457 V12.0.5 cherrypick 2dc3768 fix network form update configuration in place state corruption
  .yarn/patches/@metamask-network-controller-npm-18.1.2-1bcb8d8610.patch
  app/scripts/migrations/index.js
  ui/components/ui/deprecated-networks/deprecated-networks.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#26462 fix: Remove double padding on Snap home page
  ui/pages/snaps/snap-view/index.scss
  ui/pages/snaps/snap-view/snap-view.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26458 fix: Permit ellipsis should use max 15 char
  ui/components/app/confirm/info/row/text-token-units.test.tsx
  ui/components/app/confirm/info/row/text-token-units.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/simulation-details/formatAmount.test.ts
  ui/pages/confirmations/components/simulation-details/formatAmount.ts
Labels: team-confirmations

#26463 feat: Add footers to Snap home pages
  ui/components/app/snaps/snap-home-page/snap-home-renderer.js
  ui/components/app/snaps/snap-ui-renderer/components/container.ts
  ui/components/app/snaps/snap-ui-renderer/components/footer.ts
  ui/components/app/snaps/snap-ui-renderer/components/types.ts
  ui/pages/snaps/snap-view/snap-view.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26473 Cherry pick 5ee57a63c0 (#25686) to v12.1.0
  ui/ducks/ramps/ramps.test.ts
  ui/ducks/ramps/ramps.ts
Labels: INVALID-PR-TEMPLATE

#26474 fix: Fix lint changelog 12.1.0
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#26266 fix: `rpcIdentifierUtility` client side grouping before emitting CustomRPC event
  ui/pages/onboarding-flow/add-network-modal/add-network-modal.test.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/settings/networks-tab/networks-form/use-safe-chains.test.ts
  ui/pages/settings/networks-tab/networks-form/use-safe-chains.ts
Labels: team-assets

#26451 fix: Update send transactions with custom nonce.csv
  test/manual-scenarios/transactions/send transactions with custom nonce.csv
Labels: team-confirmations

#26425 build(chore): switch to `defer` since it guarantees execution order once chunked
  app/home.html
  app/popup.html
Labels: team-extension-platform, webpack

#26317 test: Add manual scenario for upgrade testing
  test/manual-scenarios/upgrade-testing/upgrade-testing.md
Labels: area-documentation, team-extension-platform, area-qa

#26475 Cherry-pick deps audit fixes to v12.1.0
  package.json
  yarn.lock
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#26145 chore: downgrade prettier-eslint to match prettier version
  package.json
  yarn.lock
Labels: dependencies, team-security

#26456 fix (cherry-pick): Enable Save button on Add Contact page for address input
  ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js
  ui/pages/settings/contact-list-tab/add-contact/add-contact.test.js
Labels: team-wallet-ux

#26460 fix: fallback conversion rate for token market data #4615
  .yarn/patches/@metamask-assets-controllers-npm-33.0.0-3e7448c4cd.patch
  package.json
  yarn.lock
Labels: release-blocker, team-assets, release-12.1.0

#25932 fix: Restore `responsive` e2e driver option
  test/e2e/tests/account/metamask-responsive-ui.spec.js
  test/e2e/tests/swap-send/swap-send-test-utils.ts
  test/e2e/webdriver/chrome.js
  test/e2e/webdriver/index.js
Labels: team-confirmations

#26459 chore: Add Near Icon
  app/images/near.svg
  shared/constants/network.ts
Labels: team-assets

#26403 chore: remove token and nft detection modals
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/wallet-alpha.png
  app/scripts/controllers/app-metadata.test.ts
  app/scripts/controllers/app-metadata.ts
  app/scripts/controllers/preferences.js
  app/scripts/lib/backup.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  shared/modules/selectors/index.test.ts
  shared/modules/selectors/index.ts
  shared/modules/selectors/nft-auto-detect.ts
  shared/modules/selectors/token-auto-detect.ts
  test/e2e/default-fixture.js
  test/e2e/fixture-builder.js
  test/e2e/restore/MetaMaskUserData.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/jest/mock-store.js
  ui/components/app/app-components.scss
  ui/components/app/assets/auto-detect-nft/auto-detect-nft-modal.test.stories.js
  ui/components/app/assets/auto-detect-nft/auto-detect-nft-modal.test.tsx
  ui/components/app/assets/auto-detect-nft/auto-detect-nft-modal.tsx
  ui/components/app/assets/auto-detect-nft/index.scss
  ui/components/app/assets/auto-detect-token/auto-detect-token-modal.test.stories.js
  ui/components/app/assets/auto-detect-token/auto-detect-token-modal.test.tsx
  ui/components/app/assets/auto-detect-token/auto-detect-token-modal.tsx
  ui/ducks/metamask/metamask.js
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: team-assets, needs-assets-ux-review

#26489 perf: add parallel fetching for the network fee dropdown
  ui/helpers/utils/notification.util.ts
Labels: team-notifications

#26478 fix: refactor: cherry-pick 12.1.0 Permit decimal fix + introduce ConfirmInfoRowTextTokenUnits component
  ui/components/app/confirm/info/row/index.ts
  ui/components/app/confirm/info/row/text-token-units.stories.tsx
  ui/components/app/confirm/info/row/text-token-units.test.tsx
  ui/components/app/confirm/info/row/text-token-units.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/row/dataTree.tsx
Labels: team-confirmations

#26497 chore: Master sync
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#26494 feat: Update @blockaid/ppom_release to release 1.5.2
  package.json
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  yarn.lock
Labels: team-confirmations

#26485 fix: Fix migration 120.3 error caused by invalid state
  app/scripts/migrations/120.6.test.ts
  app/scripts/migrations/120.6.ts
  app/scripts/migrations/index.js
Labels: team-wallet-framework, team-extension-platform, needs-dev-review

#26496 fix: [cherry-pick][V12.1.0] fix loss of precision for very big values
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/simulation-details/formatAmount.test.ts
  ui/pages/confirmations/components/simulation-details/formatAmount.ts
Labels: team-confirmations, release-12.1.0

#26411 chore: Integrate SnapInsightsController
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/app/snaps/insight-warnings/insight-warnings.js
  ui/components/app/snaps/snap-delineator/snap-delineator.js
  ui/components/app/snaps/snap-insight/snap-insight.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/hooks/snaps/useInsightSnaps.js
  ui/hooks/snaps/useSignatureInsights.js
  ui/hooks/snaps/useTransactionInsightSnaps.js
  ui/hooks/useTransactionInsights.js
  ui/pages/confirmations/confirm-signature-request/index.js
  ui/selectors/selectors.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26500 feat: [cherry-pick][V12.1.0] Permit ellipsis fix (2/3) - show ellipsis at max 15 digits
  ui/components/app/confirm/info/row/text-token-units.test.tsx
  ui/components/app/confirm/info/row/text-token-units.tsx
  ui/components/app/confirm/info/row/text.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/simulation-details/formatAmount.test.ts
  ui/pages/confirmations/components/simulation-details/formatAmount.ts
Labels: team-confirmations

#26186 fix: permit simulation design
  ui/components/app/confirm/info/__snapshots__/info.test.tsx.snap
  ui/components/app/confirm/info/row/__snapshots__/expandable-row.test.tsx.snap
  ui/components/app/confirm/info/row/__snapshots__/row.test.tsx.snap
  ui/components/app/confirm/info/row/alert-row/__snapshots__/alert-row.test.tsx.snap
  ui/components/app/confirm/info/row/row.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/contract-interaction/__snapshots__/contract-interaction.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/__snapshots__/personal-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/__snapshots__/siwe-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/__snapshots__/advanced-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/__snapshots__/edit-gas-fees-row.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/__snapshots__/gas-fees-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-row/__snapshots__/gas-fees-row.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/__snapshots__/gas-fees-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/__snapshots__/transaction-data.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/__snapshots__/transaction-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/row/__snapshots__/dataTree.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data-v1/__snapshots__/typedSignDataV1.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data/__snapshots__/typedSignData.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: team-confirmations

#26449 test: add `driver.clickElementAndWaitForWindowToClose` helper method
  test/e2e/helpers.js
  test/e2e/mock-e2e.js
  test/e2e/snaps/test-snap-jsx.spec.js
  test/e2e/snaps/test-snap-siginsights.spec.js
  test/e2e/tests/api-usage/account-tracker-api-usage.spec.ts
  test/e2e/tests/bridge/bridge-button-opens-portfolio.spec.ts
  test/e2e/tests/bridge/bridge-button-routing.spec.ts
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  test/e2e/tests/request-queuing/ui.spec.js
  test/e2e/tests/simulation-details/simulation-details.spec.ts
  test/e2e/tests/swap-send/swap-send-erc20.spec.ts
  test/e2e/tests/swap-send/swap-send-eth.spec.ts
  test/e2e/webdriver/driver.js
Labels: team-extension-platform, team-contributor-experience

#26486 docs: Include MV2 build commands in README
  README.md
Labels: team-wallet-framework, needs-dev-review

#26506 cherry-pick: Add signature insights hotfix to RC
  ui/hooks/snaps/useSignatureInsights.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26515 fix:[cherry-pick][V12.1.0] Permit ellipsis fixes (3/4) - add ellipsis for permit fiat values (#26001)
  ui/helpers/utils/util.js
  ui/helpers/utils/util.test.js
  ui/hooks/useFiatFormatter.test.ts
  ui/hooks/useFiatFormatter.ts
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/simulation-details/amount-pill.tsx
  ui/pages/confirmations/components/simulation-details/fiat-display.tsx
Labels: team-confirmations

#26518 fix: [cherry-pick][V12.1.0] permit simulation design - fix style alignment (#26186)
  ui/components/app/confirm/info/__snapshots__/info.test.tsx.snap
  ui/components/app/confirm/info/row/alert-row/__snapshots__/alert-row.test.tsx.snap
  ui/components/app/confirm/info/row/row.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/contract-interaction/__snapshots__/contract-interaction.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/__snapshots__/personal-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/__snapshots__/siwe-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/__snapshots__/transaction-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/__snapshots__/advanced-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/row/__snapshots__/dataTree.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data-v1/__snapshots__/typedSignDataV1.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data/__snapshots__/typedSignData.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: team-confirmations

#25869 Added multichain api notifications
  app/scripts/controllers/permissions/selectors.js
  app/scripts/controllers/permissions/selectors.test.js
  app/scripts/lib/multichain-api/MultichainMiddlewareManager.test.ts
  app/scripts/lib/multichain-api/MultichainMiddlewareManager.ts
  app/scripts/lib/multichain-api/MultichainSubscriptionManager.test.ts
  app/scripts/lib/multichain-api/MultichainSubscriptionManager.ts
  app/scripts/lib/multichain-api/provider-authorize/handler.test.js
  app/scripts/lib/multichain-api/provider-request.js
  app/scripts/lib/multichain-api/provider-request.test.js
  app/scripts/metamask-controller.js
  lavamoat/build-system/policy.json
  yarn.lock
Labels: team-wallet-api-platform

#26531 feat(trezor-e2e): add private keys and sign capability
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  test/stub/keyring-bridge.js
  yarn.lock
Labels: team-wallet-framework

#26393 feat(snaps): Removed Snaps name-lookup permission code fences
  shared/constants/permissions.test.js
  shared/constants/snaps/permissions.ts
  test/e2e/run-all.js
  ui/components/multichain/pages/send/components/domain-input-resolution-cell.tsx
  ui/helpers/utils/permission.js
Labels: team-snaps-platform

#26434 fix: use a counter to show if there are pending transactions (#26116)
  app/scripts/background.js
Labels: team-notifications

#26523 fix: Permit Simulation should include decimals in fiat calculation and show tooltip if shortened
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/simulation-details/fiat-display.tsx
Labels: team-confirmations, release-12.1.0

#26477 fix: Snap Address component UI/UX (Snaps custom UI)
  ui/components/app/confirm/info/row/address.tsx
Labels: area-UI, team-snaps-platform

#25779 fix: missing deadline in swaps stx status screen
  app/scripts/controllers/swaps/index.ts
  app/scripts/controllers/swaps/swaps.constants.ts
  app/scripts/controllers/swaps/swaps.test.ts
  app/scripts/lib/setupSentry.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.js
Labels: team-swaps

#26532 fix: NetworkChangeToast width in wide screen mode
  ui/pages/confirmations/components/confirm/network-change-toast/index.scss
Labels: team-confirmations

#25766 add version in changelog/package.json files
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE, release-12.2.0

#26543 fix: set network client id for domain (#25646)
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
Labels: team-assets

#26542 fix: name being out of sync in account list
  ui/components/app/modals/new-account-modal/new-account-modal.component.js
  ui/components/app/modals/new-account-modal/new-account-modal.container.js
  ui/components/app/modals/new-account-modal/new-account-modal.test.tsx
  ui/pages/permissions-connect/permissions-connect.test.tsx
Labels: team-accounts

#26402 feat: added AccountWatcher as preinstalled snap and added to menu list
  app/_locales/en/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/lib/setupSentry.js
  app/scripts/lib/snap-keyring/account-watcher-snap.ts
  app/scripts/metamask-controller.js
  app/scripts/snaps/preinstalled-snaps.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/metametrics.ts
  test/data/mock-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/create-named-snap-account/create-named-snap-account.tsx
  ui/components/multichain/create-named-snap-account/index.scss
  ui/components/multichain/multichain-components.scss
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-named-snap-account.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.tsx
  ui/pages/settings/experimental-tab/experimental-tab.container.ts
  ui/pages/settings/experimental-tab/experimental-tab.test.js
  ui/pages/snaps/snap-view/snap-view.js
  ui/selectors/selectors.js
  ui/store/actions.ts
  yarn.lock
Labels: area-accounts, area-snaps, team-accounts

#26535 fix: track `swapAndSend` transaction type
  app/scripts/lib/transaction/metrics.ts
  ui/helpers/utils/metrics.js
  ui/helpers/utils/metrics.test.js
Labels: team-bridge

#26306 fix: adding warning for origin on redesigned pages
  app/_locales/en/messages.json
  ui/components/app/confirm/info/row/constants.ts
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/contract-interaction/__snapshots__/contract-interaction.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/__snapshots__/transaction-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.js
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.test.js
  ui/pages/confirmations/hooks/alerts/signatures/useDomainMismatchAlerts.ts
  ui/pages/confirmations/hooks/alerts/useConfirmationOriginAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/useConfirmationOriginAlerts.ts
  ui/pages/confirmations/hooks/useConfirmationAlerts.ts
  ui/pages/confirmations/utils/confirm.test.ts
  ui/pages/confirmations/utils/confirm.ts
Labels: team-confirmations

#26143 fix(deps): Bump `@metamask/eth-json-rpc-middleware` to `^14.0.0`, `@metamask/transaction-controller` to `^35.1.1`
  .yarn/patches/@trezor-connect-web-npm-9.3.0-040ab10d9a.patch
  app/scripts/lib/accounts/BalancesController.ts
  app/scripts/lib/createDupeReqFilterStream.test.ts
  app/scripts/lib/createDupeReqFilterStream.ts
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/ppom/ppom-util.test.ts
  app/scripts/lib/ppom/ppom-util.ts
  app/scripts/lib/ppom/security-alerts-api.ts
  app/scripts/lib/snap-keyring/snap-keyring.test.ts
  app/scripts/lib/transaction/util.test.ts
  app/scripts/lib/transaction/util.ts
  app/scripts/migrations/119.ts
  app/scripts/snaps/preinstalled-snaps.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  test/e2e/tests/api-usage/account-tracker-api-usage.spec.ts
  ui/contexts/snaps/snap-interface.tsx
  ui/hooks/useTheme.ts
  ui/selectors/accounts.test.ts
  ui/store/actions.ts
  yarn.lock
Labels: release-blocker, team-wallet-framework, needs-dev-review, team-confirmations, release-12.1.0

#26565 fix: Allowlist Snap UI card component
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/components/app/snaps/snap-ui-card/snap-ui-card.tsx
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26251 feat: Enable hardware wallets for smart transactions, sign a transaction only once
  app/scripts/lib/transaction/smart-transactions.test.ts
  app/scripts/lib/transaction/smart-transactions.ts
  app/scripts/metamask-controller.js
  ui/ducks/swaps/swaps.js
  ui/pages/swaps/prepare-swap-page/review-quote.js
Labels: team-transactions

#26557 Cherry-pick 6ed72f0 (PR #26542)
  ui/components/app/modals/new-account-modal/new-account-modal.component.js
  ui/components/app/modals/new-account-modal/new-account-modal.container.js
  ui/components/app/modals/new-account-modal/new-account-modal.test.tsx
Labels: team-accounts, INVALID-PR-TEMPLATE

#26544 fix: missing deadline in swaps stx status screen (#25779)
  app/scripts/controllers/swaps.constants.ts
  app/scripts/controllers/swaps.test.js
  app/scripts/controllers/swaps.ts
  app/scripts/lib/setupSentry.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/pages/swaps/smart-transaction-status/smart-transaction-status.js
Labels: team-swaps

#26467 fix: Fix MV2 build sourcemap upload
  .circleci/config.yml
  app/scripts/lib/setupSentry.js
  development/sentry-publish.js
  development/sentry-upload-artifacts.sh
  shared/modules/mv3.utils.js
Labels: team-wallet-framework, team-extension-platform, needs-dev-review

#26464 feat: Redesign Approve confirmation
  app/_locales/en/messages.json
  test/data/confirmations/contract-interaction.ts
  test/e2e/tests/confirmations/transactions/erc721-approve-redesign.spec.ts
  test/integration/confirmations/transactions/contract-interaction.test.tsx
  test/integration/confirmations/transactions/erc721-approve.test.tsx
  test/integration/confirmations/transactions/transactionDataHelpers.tsx
  test/integration/helpers.tsx
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-details/__snapshots__/approve-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-details/approve-details.stories.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve-details/approve-details.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve-details/approve-details.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.stories.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.tsx
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/utils/confirm.ts
Labels: team-confirmations

#26534 chore: Rename `permittedChains` permission to `endowment:permitted-chains`
  app/scripts/controllers/permissions/specifications.js
  app/scripts/controllers/permissions/specifications.test.js
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.test.js
  app/scripts/metamask-controller.js
  ui/pages/permissions-connect/permissions-connect.component.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26585 fix: Snapshot unit tests
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
Labels: team-confirmations

#26482 feat(sentry): Adding extensionId and installType to Sentry
  app/scripts/background.js
  app/scripts/constants/sentry-state.ts
  app/scripts/lib/setup-initial-state-hooks.js
  app/scripts/lib/setupSentry.js
  test/e2e/tests/metrics/errors.spec.js
  ui/index.js
Labels: team-extension-platform

#26514 feat: Add approval static simulation
  app/_locales/en/messages.json
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve.tsx
  ui/pages/confirmations/components/confirm/info/shared/static-simulation/static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
Labels: team-confirmations

#26517 cherry-pick: Fix migration 120.3 error caused by invalid state (#26485)
  app/scripts/migrations/120.6.test.ts
  app/scripts/migrations/120.6.ts
  app/scripts/migrations/index.js
Labels: team-extension-platform, needs-dev-review

#26594 fix: track `swapAndSend` transaction type (#26535)
  app/scripts/lib/transaction/metrics.ts
  ui/helpers/utils/metrics.js
  ui/helpers/utils/metrics.test.js
Labels: team-bridge

#26524 feat: account watcher e2e
  test/e2e/accounts/create-watch-account.spec.ts
Labels: team-accounts, e2e-test

#26512 test: add tests for insufficient funds alert
  test/e2e/tests/confirmations/alerts/insufficient-funds.spec.ts
  ui/components/app/alert-system/alert-modal/alert-modal.tsx
  ui/components/component-library/modal-header/modal-header.types.ts
Labels: team-confirmations

#26332 feat: add transaction performance metrics
  app/scripts/lib/createTracingMiddleware.test.ts
  app/scripts/lib/createTracingMiddleware.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/setupSentry.js
  app/scripts/lib/transaction/util.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/lib/trace.test.ts
  shared/lib/trace.ts
  ui/pages/confirmations/confirm-transaction/confirm-transaction.component.js
  ui/store/actions.ts
  yarn.lock
Labels: team-confirmations, team-tiger

#26382 feat: Add contract deployment redesigned transaction screen
  app/_locales/en/messages.json
  test/e2e/tests/confirmations/transactions/contract-deployment-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/metrics.spec.ts
  test/e2e/tests/confirmations/transactions/shared.ts
  ui/pages/confirmations/components/confirm/info/base-transaction-info/__snapshots__/base-transaction-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.stories.tsx
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.test.tsx
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.tsx
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/utils/confirm.ts
Labels: team-confirmations

#26583 fix: flaky test `Test Snap Name Lookup tests name-lookup functionalit...`
  test/e2e/snaps/test-snap-namelookup.spec.js
Labels: team-extension-platform, area-qa

#26492 fix: remove speed up and cancel controller validation
  ui/pages/confirmations/components/gas-timing/gas-timing.component.js
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
Labels: team-confirmations

#26602 Patch fix for initial connections in preinstalled Snaps
  .yarn/patches/@metamask-snaps-controllers-npm-9.2.0-09a31bab4f.patch
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#26148 feat: new receive flow
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/flask/btc/btc-account-overview.spec.ts
  test/e2e/tests/account/import-flow.spec.js
  test/e2e/tests/account/incremental-security.spec.js
  test/e2e/tests/portfolio/portfolio-site.spec.js
  ui/components/app/assets/asset-list/asset-list.js
  ui/components/app/assets/asset-list/asset-list.test.js
  ui/components/app/wallet-overview/btc-overview.test.tsx
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/app/wallet-overview/index.scss
  ui/components/multichain/account-overview/account-overview-btc.test.tsx
  ui/components/multichain/index.js
  ui/components/multichain/receive-modal/receive-modal.js
  ui/components/multichain/receive-modal/receive-modal.test.js
  ui/components/multichain/receive-token-link/index.ts
  ui/components/multichain/receive-token-link/receive-token-link.tsx
  ui/components/ui/qr-code-view/index.scss
  ui/components/ui/qr-code-view/qr-code-view.tsx
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
Labels: team-wallet-ux

#26607 Update v12.1.0 with changes from v12.0.6
  .circleci/config.yml
  CHANGELOG.md
  app/scripts/background.js
  app/scripts/constants/sentry-state.ts
  app/scripts/lib/setup-initial-state-hooks.js
  app/scripts/lib/setupSentry.js
  app/scripts/migrations/120.6.test.ts
  app/scripts/migrations/120.6.ts
  app/scripts/migrations/index.js
  development/sentry-publish.js
  development/sentry-upload-artifacts.sh
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  shared/modules/mv3.utils.js
  test/e2e/tests/metrics/errors.spec.js
  ui/hooks/snaps/useSignatureInsights.js
  ui/index.js
Labels: team-wallet-framework

#26598 test: [Snaps E2E] Update snaps dialog test to include Custom dialog type
  test/e2e/snaps/test-snap-dialog.spec.js
Labels: area-snaps, e2e-test, team-snaps-platform

#26584 refactor: Use generic helper function to initiate signatures
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  test/e2e/tests/confirmations/signatures/personal-sign.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v3.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v4.spec.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data.spec.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  test/e2e/tests/confirmations/signatures/siwe.spec.ts
Labels: team-confirmations

#22619 refactor: Replace usages of the deprecated `setProviderType`
  app/scripts/controllers/mmi-controller.ts
  app/scripts/metamask-controller.js
  shared/constants/network.ts
  ui/components/app/loading-network-screen/loading-network-screen.component.js
  ui/components/app/loading-network-screen/loading-network-screen.container.js
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
  ui/index.js
  ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.tsx
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-extension-platform, needs-dev-review

#26435 feat: Integrate Snaps into the redesigned confirmations
  app/_locales/en/messages.json
  ui/components/ui/delineator/delineator.tsx
  ui/components/ui/delineator/delineator.types.ts
  ui/components/ui/delineator/index.scss
  ui/components/ui/delineator/utils.ts
  ui/pages/confirmations/components/confirm/pluggable-section/pluggable-section.tsx
  ui/pages/confirmations/components/confirm/snaps/snaps-section/__snapshots__/snaps-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/snaps/snaps-section/index.ts
  ui/pages/confirmations/components/confirm/snaps/snaps-section/snap-insight.tsx
  ui/pages/confirmations/components/confirm/snaps/snaps-section/snaps-section.test.tsx
  ui/pages/confirmations/components/confirm/snaps/snaps-section/snaps-section.tsx
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26616 fix: correct duplicate notifications event tracking in global menu (#…
  ui/components/multichain/global-menu/global-menu.js
Labels: team-notifications

#26573 fix: bump accounts controller and migration to fix undefined selectedAccount
  app/scripts/lib/transaction/util.test.ts
  app/scripts/migrations/105.test.ts
  app/scripts/migrations/105.ts
  app/scripts/migrations/126.test.ts
  app/scripts/migrations/126.ts
  app/scripts/migrations/index.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/multichain/connect-accounts-modal/connect-accounts-modal-list.test.tsx
  ui/components/multichain/pages/connections/connections.tsx
  ui/components/multichain/permission-details-modal/permission-details-modal.test.tsx
  ui/components/multichain/toast/toast.test.tsx
  ui/hooks/useMultichainSelector.test.ts
  ui/pages/remove-snap-account/snap-account-card.tsx
  yarn.lock
Labels: team-accounts
