Repository MetaMask/metamask-extension, pull requests merged in 2024-09, with the labels that each got.

#26821 fix(cherry-pick): remove BTC accounts from send flow (#26271)
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/pages/connections/connections.tsx
  ui/components/multichain/pages/send/components/account-picker.test.tsx
  ui/components/multichain/pages/send/components/account-picker.tsx
  ui/components/multichain/pages/send/components/your-accounts.test.tsx
  ui/components/multichain/pages/send/components/your-accounts.tsx
  ui/selectors/permissions.js
  ui/selectors/selectors.js
  ui/selectors/selectors.types.ts
  ui/store/store.ts
Labels: team-accounts

#26619 feat: Adding context to get current confirmation PR-2
  test/data/confirmations/helper.ts
  test/data/confirmations/personal_sign.ts
  test/data/confirmations/typed_sign.ts
  ui/pages/confirmations/components/confirm/blockaid-loading-indicator/blockaid-loading-indicator.test.tsx
  ui/pages/confirmations/components/confirm/blockaid-loading-indicator/blockaid-loading-indicator.tsx
  ui/pages/confirmations/components/confirm/header/__snapshots__/header.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/header-info.test.tsx
  ui/pages/confirmations/components/confirm/header/header-info.tsx
  ui/pages/confirmations/components/confirm/header/header.stories.tsx
  ui/pages/confirmations/components/confirm/header/header.test.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/hooks/alerts/useBlockaidAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/useBlockaidAlerts.ts
  ui/pages/confirmations/hooks/useConfirmationAlerts.test.ts
  ui/pages/confirmations/hooks/useConfirmationNetworkInfo.test.ts
  ui/pages/confirmations/hooks/useConfirmationNetworkInfo.ts
  ui/pages/confirmations/hooks/useConfirmationRecipientInfo.test.ts
  ui/pages/confirmations/hooks/useConfirmationRecipientInfo.ts
  ui/pages/confirmations/hooks/useCurrentSignatureSecurityAlertResponse.test.ts
  ui/pages/confirmations/hooks/useCurrentSignatureSecurityAlertResponse.ts
  ui/pages/confirmations/selectors/confirm.test.ts
  ui/pages/confirmations/selectors/confirm.ts
Labels: team-confirmations

#26225 fix: wait for ledger offscreen iframe load
  app/scripts/offscreen.js
  offscreen/scripts/ledger.ts
  offscreen/scripts/offscreen.ts
  shared/constants/offscreen-communication.ts
Labels: team-wallet-framework

#26829 chore: Update `develop` with changes from `v12.1.1`
  CHANGELOG.md
  package.json
Labels: team-wallet-framework

#26736 chore: MMI adds cherry pick for PR 25967
  test/e2e/playwright/mmi/pageObjects/mmi-dummyApp-page.ts
  ui/pages/confirmations/confirm-approve/confirm-approve.js
  ui/pages/confirmations/token-allowance/token-allowance.js
Labels: team-mmi, release-12.2.0

#26413 feat: added edit accounts modal
  app/_locales/en/messages.json
  ui/components/multichain/edit-accounts-modal/__snapshots__/edit-accounts-modal.test.tsx.snap
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.stories.tsx
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.test.tsx
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.tsx
  ui/components/multichain/edit-accounts-modal/index.ts
  ui/components/multichain/index.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review, design-qa

#26645 feat: Adding context to get current confirmation PR-3
  test/data/confirmations/contract-interaction.ts
  test/data/confirmations/helper.ts
  test/data/confirmations/personal_sign.ts
  test/data/confirmations/typed_sign.ts
  ui/pages/confirmations/components/confirm/header/__snapshots__/header.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/header-info.tsx
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-details/approve-details.stories.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve-details/approve-details.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.stories.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.test.tsx
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.ts
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/advanced-details.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/advanced-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.tsx
  ui/pages/confirmations/components/confirm/nav/__snapshots__/nav.test.tsx.snap
  ui/pages/confirmations/components/confirm/nav/nav.stories.tsx
  ui/pages/confirmations/components/confirm/nav/nav.test.tsx
  ui/pages/confirmations/components/confirm/nav/nav.tsx
  ui/pages/confirmations/components/confirm/pluggable-section/pluggable-section.test.tsx
  ui/pages/confirmations/components/confirm/pluggable-section/pluggable-section.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.stories.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.test.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.tsx
  ui/pages/confirmations/components/confirm/signature-message/signature-message.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: team-confirmations

#26817 chore: MMI adds mmi flow to new transactions confirmations view
  ui/hooks/useMMIConfirmations.ts
  ui/hooks/useMMICustodySendTransaction.test.js
  ui/hooks/useMMICustodySendTransaction.ts
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/hooks/useConfirmationAlerts.ts
Labels: team-mmi

#26839 chore: urls update for MMI support page
  builds.yml
  test/e2e/playwright/mmi/specs/navigation.spec.ts
Labels: team-mmi

#26569 fix: nonce increment/decrement functionality using arrow buttons
  ui/pages/confirmations/confirm-transaction-base/__snapshots__/confirm-transaction-base.test.js.snap
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
Labels: QA Passed, team-confirmations

#26850 fix: Apply padding to Snaps UI root element no matter the type
  ui/components/app/snaps/snap-ui-renderer/index.scss
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26846 ci: Prevent E2E timeouts on release changes
  .circleci/config.yml
  .circleci/scripts/git-diff-develop.ts
Labels: team-wallet-framework, team-extension-platform, needs-dev-review

#26649 feat: Adding context to get current confirmation PR-4
  test/data/confirmations/helper.ts
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve.test.tsx
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.stories.tsx
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.test.tsx
  ui/pages/confirmations/components/confirm/info/info.test.tsx
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.stories.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/siwe-sign.stories.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/siwe-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/siwe-sign.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.stories.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.stories.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/components/confirm/snaps/snaps-section/snaps-section.test.tsx
  ui/pages/confirmations/components/confirm/snaps/snaps-section/snaps-section.tsx
  ui/pages/confirmations/components/confirm/title/title.stories.tsx
  ui/pages/confirmations/components/confirm/title/title.test.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/components/custom-spending-cap/custom-spending-cap.stories.js
  ui/pages/confirmations/components/custom-spending-cap/custom-spending-cap.test.js
  ui/pages/confirmations/confirm-signature-request/__snapshots__/index.test.js.snap
  ui/pages/confirmations/confirm-signature-request/index.test.js
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/confirm.test.tsx
  ui/pages/confirmations/hooks/alerts/useBlockaidAlerts.test.ts
  ui/pages/confirmations/hooks/useConfirmationNetworkInfo.test.ts
  ui/pages/confirmations/hooks/useCurrentSignatureSecurityAlertResponse.test.ts
Labels: team-confirmations

#26756 docs: Manual scenario for "Import account with private key" feature
  test/manual-scenarios/keyring/import account using private key.md
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#26765 Jl/caip multichain/replace known caip namespace with metamask utils
  .yarn/patches/@metamask-utils-npm-8.5.0-bf696c2d49.patch
  app/scripts/lib/multichain-api/scope/scope.ts
  app/scripts/lib/multichain-api/scope/supported.ts
  app/scripts/lib/multichain-api/scope/validation.ts
  app/scripts/lib/multichain-api/wallet-getPermissions.js
  app/scripts/lib/multichain-api/wallet-requestPermissions.js
  app/scripts/lib/multichain-api/wallet-revokePermissions.js
  app/scripts/lib/rpc-method-middleware/handlers/eth-accounts.js
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#26822 perf(cherry-pick): use an interstitial page to load `popup.html`; load scripts using `defer`ed script tags (#26555)
  app/background.html
  app/home.html
  app/manifest/v2/_base.json
  app/manifest/v2/firefox.json
  app/manifest/v3/_base.json
  app/notification.html
  app/popup-init.html
  app/popup.html
  app/scripts/load-app.js
  development/build/scripts.js
  development/build/static.js
  offscreen/offscreen.html
Labels: team-extension-platform, release-12.2.0

#26483 Jl/caip multichain/migrate permission eth accounts to caip25
  .storybook/test-data.js
  app/scripts/background.js
  app/scripts/controllers/permissions/background-api.js
  app/scripts/controllers/permissions/background-api.test.js
  app/scripts/controllers/permissions/selectors.js
  app/scripts/controllers/permissions/selectors.test.js
  app/scripts/controllers/permissions/specifications.js
  app/scripts/controllers/permissions/specifications.test.js
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-eth-accounts.test.ts
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-eth-accounts.ts
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-middleware.js
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-middleware.test.js
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-permittedChains.test.ts
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-permittedChains.ts
  app/scripts/lib/multichain-api/caip-permission-adapter-middleware.test.js
  app/scripts/lib/multichain-api/provider-authorize/handler.js
  app/scripts/lib/multichain-api/provider-authorize/handler.test.js
  app/scripts/lib/multichain-api/wallet-getPermissions.js
  app/scripts/lib/multichain-api/wallet-getPermissions.test.js
  app/scripts/lib/multichain-api/wallet-requestPermissions.js
  app/scripts/lib/multichain-api/wallet-requestPermissions.test.js
  app/scripts/lib/multichain-api/wallet-revokePermissions.js
  app/scripts/lib/multichain-api/wallet-revokePermissions.test.js
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/eth-accounts.js
  app/scripts/lib/rpc-method-middleware/handlers/eth-accounts.test.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.test.js
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.js
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.test.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.test.js
  app/scripts/metamask-controller.js
  app/scripts/migrations/127.test.ts
  app/scripts/migrations/127.ts
  app/scripts/migrations/index.js
  test/e2e/fixture-builder.js
  ui/components/app/alerts/unconnected-account-alert/unconnected-account-alert.test.js
  ui/components/app/permission-page-container/permission-page-container.component.js
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/connected-accounts-menu/connected-accounts-menu.test.tsx
  ui/components/multichain/pages/connections/connections.test.tsx
  ui/components/multichain/pages/connections/connections.tsx
  ui/components/multichain/pages/permissions-page/permissions-page.test.js
  ui/components/multichain/pages/send/components/account-picker.test.tsx
  ui/components/multichain/permission-details-modal/permission-details-modal.test.tsx
  ui/pages/routes/routes.component.test.js
  ui/selectors/permissions.js
  ui/selectors/permissions.test.js
  ui/selectors/selectors.test.js
Labels: team-wallet-api-platform

#26643 Sj/caip multichain api specs test
  .gitignore
  package.json
  test/e2e/api-specs/MultichainAuthorizationConfirmation.ts
  test/e2e/api-specs/helpers.ts
  test/e2e/api-specs/transform.ts
  test/e2e/run-api-specs-multichain.ts
  test/e2e/run-openrpc-api-test-coverage.ts
  yarn.lock
Labels: team-wallet-api-platform

#26732 Jl/caip multichain/namespaced methods
  app/scripts/lib/multichain-api/scope/assert.test.ts
  app/scripts/lib/multichain-api/scope/assert.ts
  app/scripts/lib/multichain-api/scope/scope.ts
  app/scripts/lib/multichain-api/scope/supported.test.ts
  app/scripts/lib/multichain-api/scope/supported.ts
Labels: team-wallet-api-platform

#26877 Remove prepopulated methods and notifications
  app/scripts/controllers/permissions/background-api.test.js
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-permittedChains.test.ts
  app/scripts/lib/multichain-api/adapters/caip-permission-adapter-permittedChains.ts
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.test.js
  app/scripts/migrations/127.test.ts
  app/scripts/migrations/127.ts
Labels: team-wallet-api-platform

#26684 fix: PermitSingle, PermitBatch, PermitTransferFrom, PermitBatchTransferFrom simulation "Spending cap"
  test/data/confirmations/typed_sign.ts
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/value-display/__snapshots__/value-display.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/value-display/value-display.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/value-display/value-display.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/components/confirm/row/dataTree.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/confirm.test.tsx
Labels: team-confirmations

#26838 test: add integration test for no gas price alert
  test/integration/confirmations/transactions/alerts.test.tsx
Labels: team-confirmations

#26859 feat: Change copy from estimated to network fee
  app/_locales/en/messages.json
  test/e2e/tests/confirmations/transactions/shared.ts
  test/integration/confirmations/transactions/contract-interaction.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/base-transaction-info/__snapshots__/base-transaction-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/__snapshots__/edit-gas-fees-row.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/__snapshots__/gas-fees-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/__snapshots__/gas-fees-section.test.tsx.snap
Labels: team-confirmations

#26673 feat: Adding context to get current confirmation PR-5
  ui/components/institutional/signature-mismatch-banner/signature-mismatch-banner.stories.tsx
  ui/components/institutional/signature-mismatch-banner/signature-mismatch-banner.test.tsx
  ui/components/institutional/signature-mismatch-banner/signature-mismatch-banner.tsx
  ui/hooks/useMMIConfirmations.test.ts
  ui/hooks/useMMIConfirmations.ts
  ui/pages/confirmations/components/confirm/footer/footer.stories.tsx
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.tsx
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.test.tsx
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.tsx
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/gas-fees-details.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/gas-fees-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/gas-fees-details.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/gas-fees-section.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/gas-fees-section.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/gas-fees-section.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.tsx
Labels: team-confirmations

#26837 feat: new basic functionality event
  ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/security-tab/security-tab.component.js
Labels: team-notifications

#26867 fix: move porfolio button next to price amount
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/app/wallet-overview/index.scss
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
Labels: team-wallet-ux

#26807 fix: update notifications events
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  test/e2e/tests/metrics/nft-detection-metrics.spec.js
  test/e2e/tests/metrics/token-detection-metrics.spec.js
  test/e2e/tests/metrics/wallet-created.spec.js
  ui/components/app/modals/turn-on-metamask-notifications/turn-on-metamask-notifications.tsx
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/notification-detail-button/notification-detail-button.tsx
  ui/components/multichain/notification-detail-copy-button/notification-detail-copy-button.tsx
  ui/components/multichain/notification-detail-network-fee/notification-detail-network-fee.tsx
  ui/components/multichain/notifications-tag-counter/notifications-tag-counter.tsx
  ui/helpers/constants/routes.ts
  ui/hooks/metamask-notifications/useCounter.test.tsx
  ui/hooks/metamask-notifications/useCounter.tsx
  ui/pages/notifications-settings/notifications-settings-allow-notifications.tsx
  ui/pages/notifications-settings/notifications-settings-types.tsx
  ui/pages/notifications/notification-components/erc20-sent-received/erc20-sent-received.tsx
  ui/pages/notifications/notification-components/eth-sent-received/eth-sent-received.tsx
  ui/pages/notifications/notification-components/lido-withdrawal-requested/lido-withdrawal-requested.tsx
  ui/pages/notifications/notification-components/snap/snap.tsx
  ui/pages/notifications/notification-components/stake/stake.tsx
  ui/pages/notifications/notification-components/swap-completed/swap-completed.tsx
  ui/pages/notifications/notifications-list-item.tsx
  ui/pages/notifications/notifications.tsx
  ui/pages/onboarding-flow/creation-successful/creation-successful.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.tsx
  ui/selectors/metamask-notifications/metamask-notifications.ts
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-notifications

#26872 fix: flaky test "Request Queuing Dapp 1 Send Tx -> Dapp 2 Request Acc..."
  test/e2e/tests/request-queuing/dapp1-switch-dapp2-eth-request-accounts.spec.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE, area-qa

#26882 fix: Fix Trezor signing and connecting
  .yarn/patches/@trezor-connect-web-npm-9.3.0-040ab10d9a.patch
  yarn.lock
Labels: team-accounts, team-wallet-framework, team-extension-platform, team-hardware-wallets

#26885 fix: Fix Trezor signing and connecting [cherry-pick]
  .yarn/patches/@trezor-connect-web-npm-9.3.0-040ab10d9a.patch
  yarn.lock
Labels: team-accounts, team-wallet-framework, team-extension-platform, team-hardware-wallets

#26886 chore: Update changelog for v12.1.2
  CHANGELOG.md
Labels: team-wallet-framework, team-extension-platform

#26814 fix: revert breaking change to requests with `null` ids (#26143)
  .yarn/patches/@trezor-connect-web-npm-9.2.2-a4de8e45fc.patch
  app/scripts/lib/createDupeReqFilterStream.ts
  test/jest/mocks.ts
Labels: team-wallet-framework

#26895 Update v12.2.0 with changes from v12.1.2
  .yarn/patches/@trezor-connect-web-npm-9.3.0-040ab10d9a.patch
  CHANGELOG.md
  yarn.lock
Labels: team-extension-platform

#26853 feat: Make footers and headers sticky in confirmation popups
  ui/pages/confirmations/confirmation/confirmation.js
  ui/pages/confirmations/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-named-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/error.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/success.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/switch-ethereum-chain.test.js.snap
Labels: team-snaps-platform

#26551 chore(deps): Bump `@metamask/utils` from `^8.2.1` to `^9.1.0`
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-wallet-framework, needs-dev-review

#26897 fix: move porfolio button next to price amount (#26867)
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/app/wallet-overview/index.scss
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
Labels: team-wallet-ux

#26914 fix: Updating @metamask/eth-json-rpc-middleware to version 14.0.1 to fix regression in typed sign requests
  package.json
  yarn.lock
Labels: team-confirmations

#26825 Jl/mmp 3048/caip multichain error handling cleanup
  app/scripts/lib/multichain-api/caip25permissions.ts
  app/scripts/lib/multichain-api/provider-authorize/handler.js
  app/scripts/lib/multichain-api/provider-request.js
  app/scripts/lib/multichain-api/provider-request.test.js
  app/scripts/lib/multichain-api/scope/validation.ts
  app/scripts/lib/multichain-api/wallet-revokeSession.js
  app/scripts/lib/multichain-api/wallet-revokeSession.test.js
Labels: team-wallet-api-platform

#26916 cherry-pick: Updating @metamask/eth-json-rpc-middleware to version 14.0.1 to fix regression in typed sign requests
  package.json
  yarn.lock
Labels: team-confirmations

#26917 chore: Update changelog for v12.1.3
  CHANGELOG.md
Labels: team-wallet-framework, team-extension-platform

#26884 feat: Icon Button to use light theme in dark mode
  ui/components/ui/icon-button/icon-button.js
  ui/components/ui/icon-button/icon-button.stories.tsx
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
Labels: area-UI, team-design-system

#26926 Fix provider_authorize missing hooks
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#26672 feat: add brand evo font files
  ui/components/component-library/text/text.scss
  ui/components/component-library/text/text.stories.tsx
  ui/components/component-library/text/text.test.tsx
  ui/components/component-library/text/text.tsx
  ui/components/component-library/text/text.types.ts
  ui/css/utilities/fonts.scss
  ui/css/utilities/fonts/CentraNo1/CentraNo1-Bold.woff2
  ui/css/utilities/fonts/CentraNo1/CentraNo1-BoldItalic.woff2
  ui/css/utilities/fonts/CentraNo1/CentraNo1-Book.woff2
  ui/css/utilities/fonts/CentraNo1/CentraNo1-BookItalic.woff2
  ui/css/utilities/fonts/CentraNo1/CentraNo1-Medium.woff2
  ui/css/utilities/fonts/CentraNo1/CentraNo1-MediumItalic.woff2
  ui/css/utilities/fonts/MMSans/MM_Sans-Variable.woff2
Labels: area-UI, team-design-system

#26924 fix: update notifications events (#26807)
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  test/e2e/tests/metrics/wallet-created.spec.js
  ui/components/app/modals/turn-on-metamask-notifications/turn-on-metamask-notifications.tsx
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/notification-detail-button/notification-detail-button.tsx
  ui/components/multichain/notification-detail-copy-button/notification-detail-copy-button.tsx
  ui/components/multichain/notification-detail-network-fee/notification-detail-network-fee.tsx
  ui/components/multichain/notifications-tag-counter/notifications-tag-counter.tsx
  ui/helpers/constants/routes.ts
  ui/hooks/metamask-notifications/useCounter.test.tsx
  ui/hooks/metamask-notifications/useCounter.tsx
  ui/pages/notifications-settings/notifications-settings-allow-notifications.tsx
  ui/pages/notifications-settings/notifications-settings-types.tsx
  ui/pages/notifications/notification-components/erc20-sent-received/erc20-sent-received.tsx
  ui/pages/notifications/notification-components/eth-sent-received/eth-sent-received.tsx
  ui/pages/notifications/notification-components/lido-withdrawal-requested/lido-withdrawal-requested.tsx
  ui/pages/notifications/notification-components/snap/snap.tsx
  ui/pages/notifications/notification-components/stake/stake.tsx
  ui/pages/notifications/notification-components/swap-completed/swap-completed.tsx
  ui/pages/notifications/notifications-list-item.tsx
  ui/pages/notifications/notifications.tsx
  ui/pages/onboarding-flow/creation-successful/creation-successful.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.tsx
  ui/selectors/metamask-notifications/metamask-notifications.ts
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-notifications

#26685 feat: Adding context to get current confirmation PR-6
  .storybook/preview.js
  test/data/confirmations/helper.ts
  test/lib/confirmations/render-helpers.tsx
  ui/components/app/alert-system/contexts/alertMetricsContext.tsx
  ui/pages/confirmations/components/confirm/blockaid-loading-indicator/blockaid-loading-indicator.test.tsx
  ui/pages/confirmations/components/confirm/confirm-alerts/confirm-alerts.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.tsx
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/advanced-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-icon/edit-gas-icon-button.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-icon/edit-gas-icon-button.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-row/gas-fees-row.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-row/gas-fees-row.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.tsx
  ui/pages/confirmations/components/confirm/ledger-info/ledger-info.stories.tsx
  ui/pages/confirmations/components/confirm/ledger-info/ledger-info.test.tsx
  ui/pages/confirmations/components/confirm/network-change-toast/network-change-toast-legacy.test.tsx
  ui/pages/confirmations/confirm/confirm.tsx
  ui/pages/confirmations/confirm/stories/utils.tsx
  ui/pages/confirmations/context/confirm/index.tsx
  ui/pages/confirmations/hooks/alerts/signatures/useAccountMismatchAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/signatures/useAccountMismatchAlerts.ts
  ui/pages/confirmations/hooks/alerts/signatures/useDomainMismatchAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/signatures/useDomainMismatchAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/useGasEstimateFailedAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useGasEstimateFailedAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/useGasFeeLowAlerts.test.tsx
  ui/pages/confirmations/hooks/alerts/transactions/useGasFeeLowAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/useGasTooLowAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useGasTooLowAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/useNetworkBusyAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useNetworkBusyAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/useNoGasPriceAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useNoGasPriceAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/usePendingTransactionAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/usePendingTransactionAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/useSigningOrSubmittingAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useSigningOrSubmittingAlerts.ts
  ui/pages/confirmations/hooks/alerts/useBlockaidAlerts.ts
  ui/pages/confirmations/hooks/alerts/useConfirmationOriginAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/useConfirmationOriginAlerts.ts
  ui/pages/confirmations/hooks/setConfirmationAlerts.test.ts
  ui/pages/confirmations/hooks/setConfirmationAlerts.ts
  ui/pages/confirmations/hooks/syncConfirmPath.test.ts
  ui/pages/confirmations/hooks/syncConfirmPath.ts
  ui/pages/confirmations/hooks/useConfirmationAlertMetrics.test.ts
  ui/pages/confirmations/hooks/useConfirmationAlertMetrics.ts
  ui/pages/confirmations/hooks/useLedgerConnection.ts
Labels: team-confirmations

#26715 fix: Show correct origins when snaps use `wallet_requestSnaps`
  app/_locales/en/messages.json
  test/data/mock-state.json
  ui/components/app/connected-sites-list/connected-sites-list.component.js
  ui/components/app/connected-sites-list/connected-sites-list.container.js
  ui/components/app/connected-sites-list/connected-sites-list.js
  ui/components/app/connected-sites-list/index.js
  ui/components/app/snaps/snap-metadata-modal/snap-metadata-modal.js
  ui/helpers/utils/snaps.js
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
  ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js
  ui/pages/snaps/snap-view/snap-settings.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26689 feat: Adding context to get current confirmation PR-7
  ui/components/app/alert-system/alert-modal/alert-modal.test.tsx
  ui/components/app/alert-system/multiple-alert-modal/multiple-alert-modal.test.tsx
  ui/components/app/confirm/info/row/alert-row/alert-row.stories.tsx
  ui/components/app/confirm/info/row/alert-row/alert-row.test.tsx
  ui/ducks/confirm/confirm.test.js
  ui/ducks/confirm/confirm.ts
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-received-token.test.ts
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-received-token.ts
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.test.tsx
  ui/pages/confirmations/confirm/confirm.tsx
  ui/pages/confirmations/hooks/alerts/useBlockaidAlerts.ts
  ui/pages/confirmations/hooks/setCurrentConfirmation.test.tsx
  ui/pages/confirmations/hooks/setCurrentConfirmation.ts
  ui/pages/confirmations/hooks/useCurrentConfirmation.ts
  ui/pages/confirmations/selectors/confirm.test.ts
  ui/pages/confirmations/selectors/confirm.ts
  ui/pages/confirmations/types/confirm.ts
Labels: team-confirmations

#26931 fix: Bug in calculating token value when number of decimals in token is large
  shared/lib/swaps-utils.js
  shared/lib/swaps-utils.test.js
Labels: team-confirmations

#26928 Jl/mmp 3037/caip multichain rename methods
  app/scripts/lib/multichain-api/MultichainSubscriptionManager.test.ts
  app/scripts/lib/multichain-api/MultichainSubscriptionManager.ts
  app/scripts/lib/multichain-api/caip25permissions.test.ts
  app/scripts/lib/multichain-api/wallet-createSession/handler.js
  app/scripts/lib/multichain-api/wallet-createSession/handler.test.js
  app/scripts/lib/multichain-api/wallet-createSession/helpers.test.ts
  app/scripts/lib/multichain-api/wallet-createSession/helpers.ts
  app/scripts/lib/multichain-api/wallet-createSession/index.js
  app/scripts/lib/multichain-api/wallet-invokeMethod.js
  app/scripts/lib/multichain-api/wallet-invokeMethod.test.js
  app/scripts/metamask-controller.js
  shared/constants/app.ts
  test/e2e/api-specs/MultichainAuthorizationConfirmation.ts
  test/e2e/run-api-specs-multichain.ts
Labels: team-wallet-api-platform

#26915 Jl/caip multichain/remove 5301 error
  app/scripts/lib/multichain-api/wallet-createSession/handler.js
  app/scripts/lib/multichain-api/wallet-createSession/handler.test.js
Labels: team-wallet-api-platform

#26938 fix: issue where `wallet_addEtherumChain` was incorrectly enforcing inclusion of a blockExplorerUrls property which is not required
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
Labels: team-wallet-api-platform

#26927 test: [Snaps E2E] Fix deprecations and add radio button and checkbox tests to snaps interactive ui test
  test/e2e/snaps/test-snap-interactive-ui.spec.js
Labels: area-snaps, e2e-test, team-snaps-platform

#26944 CherryPick: "fix: issue where `wallet_addEtherumChain` was incorrectly enforcing inclusion of a blockExplorerUrls property which is not required (#26938)"
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
Labels: team-wallet-api-platform

#25840 chore: Add basic UX and Assets team CODEOWNER rules
  .github/CODEOWNERS
Labels: team-wallet-ux, needs-assets-ux-review

#25185 fix: Add Basic Functionality to Settings Search
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/security-tab/security-tab.component.js
Labels: team-wallet-ux, needs-assets-ux-review

#25783 fix: Code cleanup on quoted attributes
  ui/components/app/alert-system/alert-modal/alert-modal.tsx
  ui/components/app/alert-system/confirm-alert-modal/confirm-alert-modal.tsx
  ui/components/app/alert-system/general-alert/general-alert.tsx
  ui/components/app/alert-system/multiple-alert-modal/multiple-alert-modal.tsx
  ui/components/multichain/toast/toast.tsx
  ui/pages/confirmations/components/confirm/header/header.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/snap-account-redirect/components/redirect-url-icon.tsx
  ui/pages/snap-account-redirect/create-snap-redirect.test.tsx
Labels: team-wallet-ux, needs-assets-ux-review

#26947 build: bump @metamask/message-manager → "^10.1.0" & @metamask/controller-utils → "^11.2.0"
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-confirmations

#26962 chore: Remove Snaps from LavaMoat policy CODEOWNERS
  .github/CODEOWNERS
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26949 test: [Snaps E2E] Create and update snap multi-install test
  test/e2e/snaps/test-snap-multi-install.spec.js
Labels: area-snaps, e2e-test, team-snaps-platform

#26960 fix: add isUnlocked Check for Metamask Notifications
  ui/contexts/metamask-notifications/metamask-notifications.tsx
Labels: team-notifications

#26887 feat: Do not require scroll-to-bottom for SIWE or Signatures with simulations before enabling Confirm footer
  test/data/confirmations/helper.ts
  test/data/mock-state.json
  ui/ducks/confirm/confirm.ts
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.test.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.tsx
  ui/pages/confirmations/types/confirm.ts
  ui/pages/confirmations/utils/confirm.ts
Labels: team-confirmations

#26966 feat: multichain support in PPOMController
  app/scripts/lib/ppom/ppom-util.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-confirmations

#26881 feat: use new `SnapAuthorshipPill` component to show snap origin in confirmation flow
  ui/components/app/app-components.scss
  ui/components/app/confirm/info/info.stories.tsx
  ui/components/app/confirm/info/row/url.tsx
  ui/components/app/snaps/snap-authorship-pill/index.scss
  ui/components/app/snaps/snap-authorship-pill/index.ts
  ui/components/app/snaps/snap-authorship-pill/snap-authorship-pill.stories.tsx
  ui/components/app/snaps/snap-authorship-pill/snap-authorship-pill.tsx
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#26941 test(btc): mock ramps endpoints
  test/e2e/flask/btc/btc-account-overview.spec.ts
  test/e2e/flask/btc/common-btc.ts
Labels: team-accounts

#26925 perf: add trace for UI startup (#26636) [cherry-pick]
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  app/scripts/ui.js
  shared/lib/trace.test.ts
  shared/lib/trace.ts
  ui/index.js
  ui/pages/settings/developer-options-tab/sentry-test.tsx
Labels: team-wallet-framework

#26950 fix: update input raw locator in account watcher e2e to use element ID
  test/e2e/accounts/create-watch-account.spec.ts
Labels: team-accounts, e2e-test, flaky tests

#26954 remove wallet_watchAsset from wallet:eip155
  app/scripts/lib/multichain-api/scope/scope.ts
Labels: team-wallet-api-platform

#26879 feat: update button primary to use light theme on dark mode
  ui/components/app/modals/transaction-already-confirmed/__snapshots__/transaction-already-confirmed.test.tsx.snap
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/component-library/button-primary/__snapshots__/button-primary.test.tsx.snap
  ui/components/component-library/button-primary/button-primary.tsx
  ui/components/component-library/button/__snapshots__/button.test.tsx.snap
  ui/components/multichain/asset-picker-amount/asset-picker/__snapshots__/asset-picker.test.tsx.snap
  ui/components/multichain/connect-accounts-modal/__snapshots__/connect-accounts-modal.test.tsx.snap
  ui/components/multichain/import-account/__snapshots__/json.test.tsx.snap
  ui/components/multichain/network-list-menu/add-rpc-url-modal/__snapshots__/add-rpc-url-modal.test.tsx.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/pages/confirmations/components/confirm/footer/__snapshots__/footer.test.tsx.snap
  ui/pages/confirmations/components/confirm/nav/__snapshots__/nav.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-named-snap-account.test.js.snap
  ui/pages/create-account/connect-hardware/__snapshots__/index.test.tsx.snap
  ui/pages/institutional/account-list/__snapshots__/account-list.test.tsx.snap
  ui/pages/institutional/custodian-accounts-connected/__snapshots__/custodian-accounts-connected.test.tsx.snap
  ui/pages/institutional/custody/__snapshots__/custody.test.tsx.snap
  ui/pages/institutional/interactive-replacement-token-page/__snapshots__/interactive-replacement-token-page.test.tsx.snap
  ui/pages/keychains/__snapshots__/reveal-seed.test.js.snap
  ui/pages/onboarding-flow/add-network-modal/__snapshots__/add-network-modal.test.js.snap
  ui/pages/onboarding-flow/metametrics/__snapshots__/metametrics.test.js.snap
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
Labels: area-UI, team-design-system

#26530 test: add Send eth with a Trezor account spec
  test/e2e/fixture-builder.js
  test/e2e/seeder/ganache.ts
  test/e2e/tests/hardware-wallets/trezor-account.spec.js
  test/e2e/tests/hardware-wallets/trezor-send.spec.ts
  test/stub/keyring-bridge.js
  test/stub/keyring-utils.js
Labels: area-hardware, team-extension-platform, e2e-test, area-qa

#26905 feat: Added UI for switching via dapp for custom chain id
  app/_locales/en/messages.json
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/pages/confirmations/confirmation/confirmation.js
  ui/pages/confirmations/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-named-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/error.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/success.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/switch-ethereum-chain.test.js.snap
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#26986 test: add integration test for pending transaction alert and fix bug …
  test/integration/confirmations/transactions/alerts.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/base-transaction-info/__snapshots__/base-transaction-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/__snapshots__/gas-fees-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/gas-fees-details.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/__snapshots__/gas-fees-section.test.tsx.snap
Labels: team-confirmations

#26857 chore: bump `@metamask/smart-transactions-controller` to `^13.0.0`
  app/scripts/lib/transaction/smart-transactions.test.ts
  app/scripts/lib/transaction/smart-transactions.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-wallet-framework

#26990 chore: Adding generic type to useConfirmContext hook
  ui/components/institutional/signature-mismatch-banner/signature-mismatch-banner.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.tsx
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-received-token.ts
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.tsx
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.ts
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/siwe-sign.tsx
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/gas-fees-details.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/gas-fees-section.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/components/confirm/signature-message/signature-message.tsx
  ui/pages/confirmations/context/confirm/index.tsx
  ui/pages/confirmations/hooks/alerts/signatures/useAccountMismatchAlerts.ts
  ui/pages/confirmations/hooks/alerts/signatures/useDomainMismatchAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/useGasEstimateFailedAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/useGasTooLowAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/useNetworkBusyAlerts.ts
  ui/pages/confirmations/hooks/alerts/transactions/useNoGasPriceAlerts.ts
  ui/pages/confirmations/hooks/useLedgerConnection.ts
Labels: team-confirmations

#26940 fix: Don't show AccountListMenu back button by default
  ui/components/component-library/modal-header/modal-header.types.ts
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
Labels: team-wallet-ux, needs-assets-ux-review

#26322 fix(2946): rename back up your data to export your data
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/tests/settings/backup-restore.spec.js
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
Labels: team-extension-platform

#26992 ci: Ensure get-changed-files-with-git-diff scripts does not run on the master branch
  .circleci/config.yml
Labels: team-extension-platform

#26995 fix: Fix flakey E2E Request Queue Switch Send Tests
  test/e2e/tests/request-queuing/dapp1-switch-dapp2-send.spec.js
Labels: team-wallet-api-platform

#27010 fix: :bug: fix typo
  ui/pages/notifications-settings/notifications-settings-per-account.tsx
  ui/pages/notifications-settings/notifications-settings-types.tsx
Labels: team-notifications

#27007 fix: flaky test `Test Snap Signature Insights tests Signature Insights functionality (Legacy)`
  test/e2e/snaps/test-snap-siginsights.spec.js
Labels: team-extension-platform, flaky tests, area-qa

#26969 refactor: remove UI initialisation callbacks
  app/scripts/ui.js
  ui/index.js
Labels: team-confirmations, team-tiger

#27006 fix: flaky test `'Import NFT should continue to display an imported NFT after importing, adding a new account, and switching back`
  test/e2e/tests/tokens/nft/import-nft.spec.js
Labels: team-extension-platform, flaky tests, area-qa

#27017 fix: flaky test `BTC Account - Overview has portfolio button enabled for BTC accounts`
  test/e2e/flask/btc/btc-account-overview.spec.ts
Labels: team-extension-platform, flaky tests, area-qa

#26639 feat: Add updates to Snaps custom UI
  ui/components/app/connected-sites-list/connected-snaps.js
  ui/components/app/snaps/copyable/copyable.js
  ui/components/app/snaps/copyable/index.scss
  ui/components/app/snaps/snap-authorship-header/snap-authorship-header.js
  ui/components/app/snaps/snap-avatar/index.js
  ui/components/app/snaps/snap-avatar/snap-avatar.js
  ui/components/app/snaps/snap-avatar/snap-avatar.stories.js
  ui/components/app/snaps/snap-connect-cell/snap-connect-cell.js
  ui/components/app/snaps/snap-home-page/snap-home-renderer.js
  ui/components/app/snaps/snap-legacy-authorship-header/snap-legacy-authorship-header.js
  ui/components/app/snaps/snap-list-item/snap-list-item.js
  ui/components/app/snaps/snap-metadata-modal/snap-metadata-modal.js
  ui/components/app/snaps/snap-ui-checkbox/snap-ui-checkbox.tsx
  ui/components/app/snaps/snap-ui-dropdown/snap-ui-dropdown.tsx
  ui/components/app/snaps/snap-ui-file-input/snap-ui-file-input.tsx
  ui/components/app/snaps/snap-ui-renderer/components/container.ts
  ui/components/app/snaps/snap-ui-renderer/components/footer.ts
  ui/components/app/snaps/snap-ui-renderer/index.scss
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/components/multichain/notification-list-item-snap/notification-list-item-snap.tsx
  ui/components/multichain/pages/permissions-page/connection-list-item.js
  ui/pages/confirmations/components/confirm/snaps/snaps-section/__snapshots__/snaps-section.test.tsx.snap
  ui/pages/confirmations/confirmation/confirmation.js
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
  ui/pages/snaps/snap-view/snap-home.js
  ui/pages/snaps/snap-view/snap-view.js
Labels: team-snaps-platform

#27024 fix: Ignore yarn audit warning for GHSA-9wv6-86v2-598j
  .yarnrc.yml
Labels: team-extension-platform

#26488 fix(AssetPrice): change `stroke-linecap` and `stroke-linejoin` properties to valid JS syntax
  ui/pages/asset/components/asset-price.tsx
Labels: team-extension-platform

#27041 fix: Add a second id to ignore for the GHSA-9wv6-86v2-598j
  .yarnrc.yml
Labels: team-extension-platform

#27044 fix: Update id for ignoring path-to-regexp advisory
  .yarnrc.yml
Labels: team-extension-platform

#27039 Version v12.2.2
  .circleci/config.yml
  .yarnrc.yml
  CHANGELOG.md
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE, release-12.2.2

#26983 fix: update `network is busy` threshold 0.9
  shared/constants/gas.ts
  ui/ducks/metamask/metamask.test.js
  ui/pages/confirmations/components/edit-gas-fee-popover/network-statistics/status-slider/status-slider.test.js
  ui/pages/confirmations/components/gas-details-item/gas-details-item.test.js
Labels: team-confirmations

#27038 fix: check if the notifications started flow is running
  ui/components/app/modals/turn-on-metamask-notifications/turn-on-metamask-notifications.tsx
Labels: team-notifications

#26718 feat: add `section` component
  ui/components/app/snaps/snap-ui-renderer/components/box.ts
  ui/components/app/snaps/snap-ui-renderer/components/index.ts
  ui/components/app/snaps/snap-ui-renderer/components/section.ts
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#27021 fix: Adding patch on eth-json-rpc-middleware to disable verifyContract field validation for cosmos
  .yarn/patches/@metamask-eth-json-rpc-middleware-npm-14.0.1-b6c2ccbe8c.patch
  package.json
  yarn.lock
Labels: team-confirmations

#26764 docs: Privacy settings manual scenarios
  test/manual-scenarios/privacy-settings/check "Display NFT media" toggle works correctly.md
  test/manual-scenarios/privacy-settings/check "IPFS gateway" toggle works correctly.md
  test/manual-scenarios/privacy-settings/check "Network details check" toggle works correctly.md
  test/manual-scenarios/privacy-settings/check "Show ENS domains in address bar" toggle works correctly.md
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#26588 perf: add Sentry tracing to CircleCI runs
  app/scripts/lib/manifestFlags.ts
  app/scripts/lib/setupSentry.js
  package.json
  test/e2e/.mocharc.js
  test/e2e/helpers.js
  test/e2e/manifest-flag-mocha-hooks.ts
  test/e2e/set-manifest-flags.ts
  test/e2e/tests/metrics/errors.spec.js
Labels: team-contributor-experience, team-tiger

#27071 fix(windows): cannot use double-quotes in filenames on Windows
  test/manual-scenarios/privacy-settings/check 'Display NFT media' toggle works correctly.md
  test/manual-scenarios/privacy-settings/check 'IPFS gateway' toggle works correctly.md
  test/manual-scenarios/privacy-settings/check 'Network details check' toggle works correctly.md
  test/manual-scenarios/privacy-settings/check 'Show ENS domains in address bar' toggle works correctly.md
Labels: team-contributor-experience

#27065 fix (cherry-pick): Adding patch on eth-json-rpc-middleware to disable verifyContract field validation for cosmos
  .yarn/patches/@metamask-eth-json-rpc-middleware-npm-14.0.1-b6c2ccbe8c.patch
  package.json
  yarn.lock
Labels: team-confirmations

#26597 refactor: Send signature metrics as event fragments in middleware & feat: Add signature alert metrics to events
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  test/e2e/tests/confirmations/signatures/malicious-signatures.spec.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  test/e2e/tests/metrics/signature-approved.spec.js
  ui/helpers/utils/metrics.js
  ui/pages/confirmations/hooks/useConfirmationAlertMetrics.ts
  ui/pages/confirmations/types/confirm.ts
Labels: team-confirmations

#27093 fix: Update id for ignoring path-to-regexp
  .yarnrc.yml
Labels: team-assets

#27095 fix: flaky test `Request Queuing for Multiple Dapps and Txs on different networks should batch confirmation txs for different dapps on different networks.`
  test/e2e/tests/request-queuing/batch-txs-per-dapp-diff-network.spec.js
Labels: type-bug, Sev2-normal, team-extension-platform, area-qa

#27064 chore: Move scroll to bottom related state on re-designed confirmation pages to confirmContext
  test/data/confirmations/helper.ts
  test/data/mock-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/ducks/confirm/confirm.ts
  ui/ducks/index.js
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.test.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.tsx
  ui/pages/confirmations/confirm/stories/utils.tsx
  ui/pages/confirmations/context/confirm/index.tsx
  ui/pages/confirmations/selectors/confirm.test.ts
  ui/pages/confirmations/selectors/confirm.ts
  ui/pages/confirmations/types/confirm.ts
  ui/store/store.ts
Labels: team-confirmations

#27004 fix: edit button on confirmation page for send ERC-1155 token
  test/e2e/tests/tokens/nft/send-nft.spec.js
  ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js
Labels: team-confirmations

#26904 feat: Add support for customizable Snap UI Input
  ui/components/app/snaps/snap-ui-renderer/components/field.ts
  ui/components/app/snaps/snap-ui-renderer/index.scss
  ui/components/app/snaps/snap-ui-renderer/utils.ts
Labels: team-snaps-platform

#27080 chore: Enable import attributes in Webpack build
  development/webpack/test/loaders.swcLoader.test.ts
  development/webpack/utils/loaders/swcLoader.ts
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#27087 fix: flaky test `Snap Account - Swap swaps ETH for DAI using a snap a...`
  test/e2e/accounts/snap-account-eth-swap.spec.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE, area-qa

#26406 feat(migration): enable token auto-detection when basic functionality is on
  app/scripts/migrations/125.1.test.ts
  app/scripts/migrations/125.1.ts
  app/scripts/migrations/index.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/multichain/asset-picker-send.spec.ts
Labels: team-assets, needs-assets-ux-review

#27106 feat(snaps): Map new `center` attribute to `Box` snap custom UI component
  ui/components/app/snaps/snap-ui-renderer/components/box.ts
Labels: team-snaps-platform

#27002 fix: Issue 26751 QR barcode scanner
  ui/components/app/modals/qr-scanner/qr-scanner.component.js
  ui/components/app/modals/qr-scanner/qr-scanner.test.js
  ui/components/app/modals/qr-scanner/scan-util.ts
Labels: team-bridge

#27074 fix: change default currency decimals for issue 26646
  ui/components/app/currency-input/currency-input.js
Labels: team-bridge

#27083 chore: fix issue 27079 incorrect 0 balance
  ui/ducks/send/send.js
Labels: team-bridge

#26426 feat: funding method modal
  app/_locales/en/messages.json
  ui/components/app/assets/asset-list/asset-list.js
  ui/components/multichain/funding-method-modal/funding-method-item.tsx
  ui/components/multichain/funding-method-modal/funding-method-modal.test.tsx
  ui/components/multichain/funding-method-modal/funding-method-modal.tsx
  ui/components/multichain/funding-method-modal/index.scss
  ui/components/multichain/funding-method-modal/index.ts
  ui/components/multichain/index.js
  ui/components/multichain/multichain-components.scss
  ui/components/multichain/ramps-card/ramps-card.js
  ui/helpers/utils/portfolio.js
Labels: team-portfolio, design-qa

#27113 fix: Resolve path-to-regexp to v1.9.0 to resolve GHSA-9wv6-86v2-598j
  .yarnrc.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#26987 fix: notification services add new allowed events
  app/scripts/controllers/push-notifications/get-notification-message.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/mock-e2e.js
  test/e2e/tests/notifications/mocks.ts
  yarn.lock
Labels: team-notifications

#27094 chore: Master sync post 12.2.2 merge
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#27100 fix: display of network name in network switch toast on confirmation pages
  ui/pages/confirmations/components/confirm/network-change-toast/network-change-toast-legacy.tsx
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: QA Passed, team-confirmations

#27082 chore(26919): bump `@metamask/signature-controller` to 19.0.0 and `@metamask/logging-controller` to 6.0.0
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#26845 feat: Edit spending cap for ERC20 `approve` and `increaseAllowance`
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/tests/confirmations/transactions/erc20-approve-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/increase-token-allowance-redesign.spec.ts
  test/e2e/webdriver/driver.js
  ui/components/app/confirm/info/row/text.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/__snapshots__/approve-static-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/approve-static-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/approve-static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.tsx
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/__snapshots__/edit-spending-cap-modal.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.test.ts
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts
  ui/pages/confirmations/components/confirm/info/approve/spending-cap/__snapshots__/spending-cap.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/spending-cap/spending-cap.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/spending-cap/spending-cap.tsx
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/advanced-details.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/constants/index.ts
  ui/pages/confirmations/utils/confirm.ts
Labels: team-confirmations

#27086 fix: storybook theme package not working
  .storybook/preview.js
  package.json
  yarn.lock
Labels: area-documentation, team-design-system

#26958 feat: add tracking event to Receive button
  shared/constants/metametrics.ts
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/pages/asset/components/asset-page.tsx
Labels: team-wallet-ux

#27145 Default RPCs: Autofocus Network, RPC, and Block Explorer form fields
  ui/components/multichain/network-list-menu/add-block-explorer-modal/add-block-explorer-modal.tsx
  ui/components/multichain/network-list-menu/add-rpc-url-modal/__snapshots__/add-rpc-url-modal.test.tsx.snap
  ui/components/multichain/network-list-menu/add-rpc-url-modal/add-rpc-url-modal.tsx
  ui/pages/settings/networks-tab/networks-form/networks-form.tsx
Labels: team-assets

#27142 chore: bump `@metamask/accounts-controller` to 18.2.0
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-wallet-framework

#26697 feat: Adding "cookie id" to metrics event
  app/scripts/background.js
  app/scripts/constants/marketing-site-whitelist.ts
  app/scripts/constants/sentry-state.ts
  app/scripts/constants/stream.ts
  app/scripts/contentscript.js
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
  app/scripts/metamask-controller.js
  app/scripts/streams/cookie-handler-stream.ts
  app/scripts/streams/shared.ts
  test/e2e/tests/metrics/marketing-cookieid-mock-page/index.html
  test/e2e/tests/metrics/marketing-cookieid.spec.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: area-privacy, team-extension-platform

#27108 feat: aggregated balance logic
  app/_locales/en/messages.json
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.d.ts
  ui/components/app/wallet-overview/__snapshots__/aggregated-percentage-overview.test.tsx.snap
  ui/components/app/wallet-overview/aggregated-percentage-overview.test.tsx
  ui/components/app/wallet-overview/aggregated-percentage-overview.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/multichain/token-list-item/price/percentage-and-amount-change/percentage-and-amount-change.test.tsx
  ui/components/multichain/token-list-item/price/percentage-and-amount-change/percentage-and-amount-change.tsx
  ui/components/ui/currency-display/currency-display.component.js
  ui/helpers/utils/util.js
  ui/helpers/utils/util.test.js
  ui/hooks/useCurrencyDisplay.js
Labels: team-assets, needs-assets-ux-review

#27160 fix: flaky test `Swaps - notifications @no-mmi tests a notification for not enough balance`
  test/e2e/tests/swaps/swaps-notifications.spec.js
Labels: Sev2-normal, team-extension-platform, flaky tests, area-qa

#26799 feat: Support CAIP-10 addresses in Snaps
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/components/app/snaps/snap-ui-address/__snapshots__/snap-ui-address.test.tsx.snap
  ui/components/app/snaps/snap-ui-address/index.ts
  ui/components/app/snaps/snap-ui-address/snap-ui-address.stories.tsx
  ui/components/app/snaps/snap-ui-address/snap-ui-address.test.tsx
  ui/components/app/snaps/snap-ui-address/snap-ui-address.tsx
  ui/components/app/snaps/snap-ui-renderer/components/address.ts
  ui/components/ui/jazzicon/jazzicon.component.js
  ui/helpers/utils/icon-factory.ts
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#27158 feat(snaps): Added support for form property in Snap footer buttons
  ui/components/app/snaps/snap-footer-button/snap-footer-button.tsx
  ui/components/app/snaps/snap-ui-renderer/components/button.ts
Labels: team-snaps-platform

#27016 fix: sentry sessions in production builds
  app/scripts/lib/setupSentry.js
  development/build/scripts.js
  test/e2e/helpers/mock-server.ts
  test/e2e/tests/metrics/sessions.spec.ts
Labels: team-confirmations, team-tiger

#27156 fix: flaky test `Simulation Details displays generic error message`
  test/e2e/tests/simulation-details/mock-request-error-malformed-transaction.ts
  test/e2e/tests/simulation-details/simulation-details.spec.ts
Labels: Sev2-normal, team-extension-platform, flaky tests, area-qa

#26952 chore: Update `asset-list` to Typescript, remove PropTypes
  ui/components/app/assets/asset-list/asset-list.test.tsx
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/asset-list/index.ts
  ui/components/app/assets/token-cell/__snapshots__/token-cell.test.tsx.snap
  ui/components/app/assets/token-cell/index.ts
  ui/components/app/assets/token-cell/token-cell.test.tsx
  ui/components/app/assets/token-cell/token-cell.tsx
  ui/components/app/assets/token-list/index.ts
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.tsx.snap
  ui/components/multichain/token-list-item/index.ts
  ui/components/multichain/token-list-item/token-list-item.test.tsx
  ui/components/multichain/token-list-item/token-list-item.tsx
Labels: team-assets

#27159 fix(cherry-pick): resolve path-to-regexp to v1.9.0 to resolve GHSA-9wv6-86v2-598j (#27113)
  .yarnrc.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#27127 fix: change asset picker button to buttonbase to fix text theming
  ui/components/multichain/asset-picker-amount/asset-picker/__snapshots__/asset-picker.test.tsx.snap
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.tsx
Labels: team-bridge, send-swap

#27116 fix: remove repeated account option
  ui/components/multichain/account-list-menu/account-list-menu.tsx
Labels: team-accounts

#27029 fix (cherry-pick): typo (#27010)
  ui/pages/notifications-settings/notifications-settings-per-account.tsx
  ui/pages/notifications-settings/notifications-settings-types.tsx
Labels: team-notifications

#27152 fix (cherry-pick): Don't show AccountListMenu back button by default
  ui/components/component-library/modal-header/modal-header.types.ts
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
Labels: team-wallet-ux

#27168 fix: cherry-pick V12.3.0 fix: PermitTransferFrom or PermitBatchTransferFrom crashes MM when value for Name address has not been loaded
  ui/components/app/name/__snapshots__/name.test.tsx.snap
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/name/name-details/name-details.test.tsx
  ui/components/app/name/name-details/name-details.tsx
  ui/components/app/name/name.test.tsx
  ui/components/app/name/name.tsx
Labels: team-confirmations, release-12.3.0

#26880 feat: migrate OnboardingController to BaseController v2
  app/scripts/background.js
  app/scripts/controllers/onboarding.test.ts
  app/scripts/controllers/onboarding.ts
  app/scripts/lib/account-tracker.js
  app/scripts/lib/account-tracker.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-wallet-framework

#24503 feat: Adding a new controller for Metametrics Data Deletion
  .metamaskrc.dist
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/metametrics-data-deletion/metametrics-data-deletion.test.ts
  app/scripts/controllers/metametrics-data-deletion/metametrics-data-deletion.ts
  app/scripts/controllers/metametrics.js
  app/scripts/metamask-controller.js
  app/scripts/services/data-deletion-service.test.ts
  app/scripts/services/data-deletion-service.ts
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/metametrics.ts
  test/e2e/default-fixture.js
  test/e2e/tests/metrics/errors.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: team-extension-platform, marketing-consent

#27181 Jl/editing flow fix incremental
  ui/components/app/permission-page-container/permission-page-container.component.js
  ui/pages/permissions-connect/permissions-connect.component.js
Labels: team-wallet-api-platform

#27019 fix(action): add a workaround for known bots
  .github/scripts/check-template-and-add-labels.ts
Labels: team-extension-platform

#23824 refactor: convert `jazzicon.component.js` to typescript
  ui/components/ui/jazzicon/jazzicon.component.js
  ui/components/ui/jazzicon/jazzicon.component.tsx
  ui/components/ui/jazzicon/jazzicon.d.ts
  ui/helpers/utils/icon-factory.ts
Labels: team-extension-platform

#26526 chore(2916): refactor stream handler for phishing warning and provider stream
  app/scripts/constants/stream.ts
  app/scripts/contentscript.js
  app/scripts/streams/cookie-handler-stream.ts
  app/scripts/streams/phishing-stream.ts
  app/scripts/streams/provider-stream.ts
  app/scripts/streams/shared.ts
  app/scripts/streams/stream-utils.ts
Labels: team-extension-platform

#27193 test: merge queue 3
  test/e2e/tests/account/add-account.spec.js
Labels: team-extension-platform

#27195 test: merge queue 5
  test/e2e/tests/account/incremental-security.spec.js
Labels: team-extension-platform

#27196 test: merge queue 6
  test/e2e/tests/account/metamask-responsive-ui.spec.js
Labels: team-extension-platform

#27200 test: merge queue 10
  test/e2e/tests/confirmations/signatures/sign-typed-data-v4.spec.ts
Labels: team-extension-platform

#27141 chore: update @metamask/bitcoin-wallet-snap to 0.6.0
  package.json
  yarn.lock
Labels: team-accounts

#27194 test: merge queue 4
  test/e2e/tests/account/import-flow.spec.js
Labels: team-extension-platform

#27198 test: merge queue 8 several commits
  test/e2e/tests/signature/signature-request.spec.js
Labels: team-extension-platform

#27199 test: mege queue 9
  test/e2e/tests/confirmations/signatures/personal-sign.spec.ts
Labels: team-extension-platform

#27170 chore: Update package @blockaid/ppom_release to version 1.5.3
  package.json
  ui/pages/confirmations/components/security-provider-banner-alert/blockaid-banner-alert/__snapshots__/blockaid-banner-alert.test.js.snap
  yarn.lock
Labels: team-confirmations

#26365 fix: permit UI integration tests
  .yarn/patches/jest-environment-jsdom-npm-29.7.0-0b72dd0e0b.patch
  package.json
  test/integration/confirmations/signatures/permit.test.tsx
  test/integration/data/integration-init-state.json
  yarn.lock
Labels: team-confirmations
