Repository MetaMask/metamask-extension, pull requests merged in 2024-05, with the labels that each got.

#23664 feat: add multiple alert component
  ui/components/app/confirmations/alerts/alert-modal/__snapshots__/alert-modal.test.tsx.snap
  ui/components/app/confirmations/alerts/alert-modal/alert-modal.test.tsx
  ui/components/app/confirmations/alerts/alert-modal/alert-modal.tsx
  ui/components/app/confirmations/alerts/alert-modal/index.scss
  ui/components/app/confirmations/alerts/multiple-alert-modal/index.tsx
  ui/components/app/confirmations/alerts/multiple-alert-modal/multiple-alert-modal.stories.tsx
  ui/components/app/confirmations/alerts/multiple-alert-modal/multiple-alert-modal.test.tsx
  ui/components/app/confirmations/alerts/multiple-alert-modal/multiple-alert-modal.tsx
Labels: team-confirmations-system, team-confirmations

#24264 fix: duplicate fee display for l2 networks
  ui/pages/confirmations/components/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.js
  ui/pages/confirmations/components/confirm-gas-display/confirm-legacy-gas-display/confirm-legacy-gas-display.test.js
  ui/pages/confirmations/components/fee-details-component/fee-details-component.js
  ui/pages/confirmations/components/fee-details-component/fee-details-component.test.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#24269 refactor: :recycle: change the way we are handling some metamask noti…
  app/scripts/controllers/metamask-notifications/metamask-notifications.test.ts
  app/scripts/controllers/metamask-notifications/metamask-notifications.ts
Labels: INVALID-PR-TEMPLATE, team-notifications

#24298 test: [Snaps E2E Test] Create test for snaps UI images
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-ui-imgs.spec.js
  ui/components/app/snaps/snap-ui-image/snap-ui-image.tsx
Labels: area-snaps, team-snaps-platform

#24296 ci: update cla-signature-bot
  .github/workflows/cla.yml
Labels: team-extension-platform

#24319 fix: Fix #24320: Prevent editing of safe-transfer-from transactions
  test/e2e/tests/tokens/nft/send-nft.spec.js
  ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js
Labels: team-assets

#24317 fix: reset streams on prerender only for affected browser versions
  app/scripts/contentscript.js
  shared/modules/browser-runtime.utils.js
  shared/modules/browser-runtime.utils.test.js
  ui/helpers/constants/common.ts
Labels: team-extension-platform, team-wallet-api-platform

#24330 chore: Master sync (following v11.14.x and the (currently reverted) v11.15.0)
  CHANGELOG.md
  package.json
Labels: DO-NOT-MERGE, INVALID-PR-TEMPLATE

#24297 chore: update `typescript` from `v5.3.3` to `v5.4.5`
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#24329 chore(deps): Bump phishing-controller to ^9.0.2 (v11.16.0 cherry-pick))
  app/scripts/lib/snap-keyring/utils/isBlockedUrl.test.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#24258 fix: Render avatar network in toast as the popup header
  ui/pages/routes/routes.component.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#24344 fix: rewrite snaps metadata selector to fix re-rendering
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/create-snap-account.test.js
  ui/pages/confirmations/confirmation/templates/remove-snap-account.test.js
  ui/selectors/selectors.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#24280 fix: remove extra header from confirmation pages in expanded view
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/multichain-meta-fox-logo.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-header/confirm-page-container-header.component.js
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  ui/pages/confirmations/hooks/useConfirmationRecipientInfo.ts
  ui/pages/routes/routes.component.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#23769 test: Request queuing e2e scenarios
  test/e2e/fixture-builder.js
  test/e2e/tests/request-queuing/batch-txs-per-dapp-diff-network.spec.js
  test/e2e/tests/request-queuing/batch-txs-per-dapp-extra-tx.spec.js
  test/e2e/tests/request-queuing/batch-txs-per-dapp-same-network.spec.js
  test/e2e/tests/request-queuing/chain-id-check.spec.js
  test/e2e/tests/request-queuing/dapp1-subscribe-network-switch.spec.js
  test/e2e/tests/request-queuing/dapp1-switch-dapp2-send.spec.js
  test/e2e/tests/request-queuing/multi-dapp-sendTx-revokePermission.spec.js
  test/e2e/tests/request-queuing/sendTx-revokePermissions.spec.js
  test/e2e/tests/request-queuing/sendTx-switchChain-sendTx.spec.js
  test/e2e/tests/request-queuing/switchChain-sendTx.spec.js
  test/e2e/tests/request-queuing/switchChain-watchAsset.spec.js
  test/e2e/tests/request-queuing/watchAsset-switchChain-watchAsset.spec.js
Labels: area-testSuite, team-wallet-api-platform, e2e-test

#23428 Added QR code
  app/_locales/en/messages.json
  app/scripts/controllers/mmi-controller.ts
  app/scripts/metamask-controller.js
  package.json
  shared/constants/mmi-controller.ts
  test/e2e/mmi/custodian-hooks/hooks.ts
  test/e2e/mmi/pageObjects/mmi-accountMenu-page.ts
  test/e2e/mmi/pageObjects/mmi-network-page.ts
  test/e2e/mmi/specs/qrCode.spec.ts
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-connection-info-mmi-visual-linux.png
  test/e2e/mmi/specs/visual.spec.ts-snapshots/custodian-list-mmi-visual-linux.png
  ui/components/institutional/qr-code-modal/index.tsx
  ui/components/institutional/qr-code-modal/qr-code-modal.stories.tsx
  ui/components/institutional/qr-code-modal/qr-code-modal.test.tsx
  ui/components/institutional/qr-code-modal/qr-code-modal.tsx
  ui/ducks/institutional/institutional.js
  ui/pages/institutional/custody/custody.js
  ui/pages/institutional/custody/custody.test.js
  ui/store/institutional/institution-background.ts
  yarn.lock
Labels: team-mmi

#24326 feat(24224): introduce flag to disable MV3 service worker keep alive code
  app/_locales/en/messages.json
  app/scripts/background.js
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/developer-options-tab/developer-options-tab.js
  ui/pages/settings/developer-options-tab/developer-options-tab.stories.tsx
  ui/pages/settings/developer-options-tab/developer-options-tab.test.tsx
  ui/pages/settings/developer-options-tab/developer-options-tab.tsx
  ui/pages/settings/developer-options-tab/index.tsx
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-extension-platform

#24350 cherry-pick fix NFT mint simulations to v11.14.5
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#24341 chore: Make use of redesignedConfirmationsEnabled preference consistent
  ui/pages/confirmations/hooks/useCurrentConfirmation.test.ts
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.container.js
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#24338 fix: "Transaction Finalized" metrics event on transaction confirmation
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE, team-confirmations

#24353 fix (cherry-pick): "Transaction Finalized" metrics event on transaction confirmation (#24338)
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
Labels: INVALID-PR-TEMPLATE

#24342 Version v11.14.5
  CHANGELOG.md
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/tests/dapp-interactions/dapp-tx-edit.spec.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-header/confirm-page-container-header.component.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container-header/confirm-page-container-header.component.test.js
  ui/pages/confirmations/components/confirm-page-container/confirm-page-container.component.js
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  yarn.lock
Labels: INVALID-PR-TEMPLATE, release-11.14.5

#24345 feat(): Add e2e tests for header component in signatures redesign
  test/e2e/tests/confirmations/header.spec.js
  test/e2e/webdriver/driver.js
  ui/components/app/confirm/info/row/currency.tsx
  ui/pages/confirmations/components/confirm/header/__snapshots__/header-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/__snapshots__/header.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/header-info.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/hooks/useConfirmationRecipientInfo.ts
Labels: team-confirmations-secure-ux, team-confirmations-secure-ux-PR, confirmation-redesign, confirmation-re-design, team-confirmations

#24356 ci: fix `Validate Conventional Commit Title` action
  .github/workflows/validate-conventional-commits.yml
Labels: team-extension-platform

#24082 feat: allow seeding of the accounts in a permission request
  app/scripts/controllers/permissions/specifications.js
  app/scripts/controllers/permissions/specifications.test.js
  ui/pages/permissions-connect/permissions-connect.component.js
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#24328 fix: currency displayed for user balance in re-designed confirmation header info modal
  ui/components/app/confirm/info/row/currency.test.tsx
  ui/components/app/confirm/info/row/currency.tsx
  ui/pages/confirmations/hooks/useConfirmationRecipientInfo.ts
Labels: team-confirmations-secure-ux-PR, needs-dev-review, confirmation-redesign

#23456 feat: Disable services with a Basic configuration toggle
  app/_locales/en/messages.json
  app/scripts/controllers/preferences.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  test/e2e/fixture-builder.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/components/app/basic-configuration-modal/basic-configuration-modal.stories.tsx
  ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
  ui/components/app/basic-configuration-modal/index.ts
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/ui/new-network-info/new-network-info.js
  ui/components/ui/new-network-info/new-network-info.test.js
  ui/ducks/app/app.ts
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/selectors/selectors.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: needs-dev-review, team-wallet-ux, needs-assets-ux-review

#24272 fix: Optimism max gas missmatch
  ui/constants/index.js
  ui/hooks/useUserPreferencedCurrency.js
  ui/pages/confirmations/confirm-token-transaction-base/confirm-token-transaction-base.js
  ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#24348 fix: improvements in network connect and display
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.js
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.test.js
  ui/pages/settings/networks-tab/networks-form/networks-form.js
  ui/pages/settings/networks-tab/networks-form/networks-form.test.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#24373 fix(syntax): remove double-declared variable
  ui/pages/confirmations/hooks/useConfirmationRecipientInfo.ts
Labels: team-security

#24193 chore(ci): fix check-pr-tag job
  .circleci/config.yml
Labels: team-security

#23145 chore(test): remove polyfill-crypto.getrandomvalues
  package.json
  test/helpers/setup-helper.js
  yarn.lock
Labels: dependencies, team-security

#24205 chore: Bump address-book-controller to ^4.0.1
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-shared-libraries

#24377 fix: Ensure smart transaction modal is shown for users upgrading from previous versions
  shared/modules/selectors/smart-transactions.ts
Labels: team-swaps, INVALID-PR-TEMPLATE

#24385 Version v11.15.2
  CHANGELOG.md
  package.json
  shared/modules/selectors/smart-transactions.ts
Labels: INVALID-PR-TEMPLATE, release-11.15.2

#24371 fix: Remove Snaps Methods from 'methodsWithConfirmation' list used to determine whether to enqueue a request
  shared/constants/methods-tags.ts
Labels: team-wallet-api-platform, amon-hen-v1

#24364 feat: Signature Redesign update settings and title description copies
  app/_locales/en/messages.json
  ui/pages/confirmations/components/confirm/title/title.test.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: team-confirmations

#24394 fix: Move "SettingsUpdated" event into the "setSmartTransactionsOptInStatus" function
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/store/actions.ts
Labels: team-transactions

#24389 feat: Add animation on the Smart Transaction status page
  ui/pages/smart-transactions/smart-transaction-status-page/__snapshots__/smart-transactions-status-page.test.js.snap
  ui/pages/smart-transactions/smart-transaction-status-page/index.scss
  ui/pages/smart-transactions/smart-transaction-status-page/smart-transaction-status-page.tsx
Labels: team-transactions

#24363 perf: disable fence linting in test builds
  development/build/index.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24396 cherrypick: fix: Move "SettingsUpdated" event into v11.15.3
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/store/actions.ts
Labels: INVALID-PR-TEMPLATE

#24397 Cherry-pick: feat: Add animation on the Smart Transaction status page (#24389) into v11.15.3
  ui/pages/smart-transactions/smart-transaction-status-page/__snapshots__/smart-transactions-status-page.test.js.snap
  ui/pages/smart-transactions/smart-transaction-status-page/index.scss
  ui/pages/smart-transactions/smart-transaction-status-page/smart-transaction-status-page.tsx
Labels: INVALID-PR-TEMPLATE

#24199 chore(deps): bump keyring controller to ^15.0.0
  .yarn/patches/@metamask-keyring-controller-npm-13.0.0-d94816a680.patch
  .yarn/patches/@metamask-keyring-controller-npm-15.0.0-fa070ce311.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/store/actions.ts
  yarn.lock
Labels: dependencies, team-accounts

#23620 refactor(preferences-controller): remove `syncIdentities` and `setAddresses`
  app/scripts/controllers/preferences.d.ts
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-shared-libraries

#24382 fix: DAPP initiated swaps in MetaMask
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
Labels: team-confirmations-secure-ux-PR, QA Passed, needs-dev-review

#24409 fix: update `@metamask/selected-network-controller` version + add migration to remove Snaps from `SelectedNetworkController` `domains` state
  app/scripts/migrations/118.test.ts
  app/scripts/migrations/118.ts
  app/scripts/migrations/index.js
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#24408 Cherry-pick: feat: post-MVP updates for Smart Transactions (#24340)
  app/_locales/en/messages.json
  app/scripts/lib/notification-manager.js
  app/scripts/lib/transaction/smart-transactions.test.ts
  app/scripts/lib/transaction/smart-transactions.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  shared/constants/notifications.ts
  shared/constants/smartTransactions.test.ts
  shared/constants/smartTransactions.ts
  shared/modules/environment.test.ts
  shared/modules/environment.ts
  shared/modules/selectors/smart-transactions.ts
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/smart-transactions/smart-transaction-status-page/__snapshots__/smart-transactions-status-page.test.js.snap
  ui/pages/smart-transactions/smart-transaction-status-page/index.scss
  ui/pages/smart-transactions/smart-transaction-status-page/smart-transaction-status-page.tsx
  ui/store/actions.ts
  yarn.lock
Labels: team-transactions, release-11.15.3

#24182 feat: add Confirmation Signature Redesign ui_customization event prop
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  ui/pages/confirmations/hooks/useCurrentConfirmation.ts
  ui/pages/confirmations/utils/confirm.ts
Labels: team-confirmations-secure-ux-PR, team-confirmations

#24395 Version v11.15.3
  CHANGELOG.md
  app/_locales/en/messages.json
  app/scripts/lib/notification-manager.js
  app/scripts/lib/transaction/smart-transactions.test.ts
  app/scripts/lib/transaction/smart-transactions.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  shared/constants/notifications.ts
  shared/constants/smartTransactions.test.ts
  shared/constants/smartTransactions.ts
  shared/modules/environment.test.ts
  shared/modules/environment.ts
  shared/modules/selectors/smart-transactions.ts
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/smart-transactions/smart-transaction-status-page/__snapshots__/smart-transactions-status-page.test.js.snap
  ui/pages/smart-transactions/smart-transaction-status-page/index.scss
  ui/pages/smart-transactions/smart-transaction-status-page/smart-transaction-status-page.tsx
  ui/store/actions.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE, release-11.15.3

#24360 chore: bump assets controllers to latest
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  test/e2e/tests/tokens/nft/mocks.js
  ui/components/app/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/nft-details/nft-details.js
  yarn.lock
Labels: team-assets, needs-assets-ux-review

#24274 feat: set useRequestQueue on by default
  app/scripts/controllers/preferences.js
  app/scripts/lib/backup.test.js
  app/scripts/migrations/119.test.ts
  app/scripts/migrations/119.ts
  app/scripts/migrations/index.js
  test/e2e/fixture-builder.js
  test/e2e/json-rpc/switchEthereumChain.spec.js
  test/e2e/restore/MetaMaskUserData.json
  test/e2e/tests/dapp-interactions/provider-api.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
Labels: needs-dev-review, INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review, amon-hen-v1

#24387 fix: gas fee editing in advance gas fee modals
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/priority-fee-input.js
Labels: team-confirmations-secure-ux-PR, needs-dev-review

#24361 feat: Add blockaid validation support for OPBNB network.
  app/scripts/lib/ppom/ppom-middleware.ts
  package.json
  shared/constants/network.ts
  yarn.lock
Labels: team-confirmations-secure-ux-PR, QA Passed, needs-dev-review

#24141 chore: Bump approval-controller to 6.0.1
  package.json
  yarn.lock
Labels: dependencies, team-shared-libraries

#24426 fix: MMI typo fix
  ui/pages/confirmations/components/signature-request-original/signature-request-original.component.js
Labels: team-mmi

#24404 chore: update mmi dependency to latest version
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/mmi/specs/navigation.spec.ts
  yarn.lock
Labels: team-mmi

#24419 fix: apply patch for preinstalled Snaps
  .yarn/patches/@metamask-snaps-controllers-npm-8.0.0-7e59688855.patch
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#24436 fix: Removing usage of driver.navigate before unlockWallet
  test/e2e/helpers.js
  test/e2e/snaps/test-snap-namelookup.spec.js
  test/e2e/snaps/test-snap-siginsights.spec.js
  test/e2e/snaps/test-snap-txinsights-v2.spec.js
  test/e2e/tests/metrics/dapp-viewed.spec.js
  test/e2e/tests/multichain/connection-page.spec.js
  test/e2e/tests/multichain/permission-page.spec.js
  test/e2e/tests/onboarding/onboarding.spec.js
  test/e2e/tests/ppom/migrate-opensea-to-blockaid-banner.spec.js
  test/e2e/tests/ppom/ppom-blockaid-alert-metrics.spec.js
  test/e2e/tests/ppom/ppom-blockaid-toggle-metrics.spec.js
  test/e2e/tests/ppom/ppom-toggle-settings.spec.js
  test/e2e/tests/request-queuing/enable-queuing.spec.js
  test/e2e/tests/synchronous-injection/synchronous-injection.spec.js
Labels: team-extension-platform

#24440 chore(test/e2e): Fix request-queueing/ui.spec.js
  test/e2e/tests/request-queuing/ui.spec.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24283 feat: Add metametrics event to switch modal confirmation
  test/e2e/json-rpc/switchEthereumChain.spec.js
  ui/pages/confirmations/confirmation/confirmation.js
Labels: needs-dev-review, team-wallet-ux, needs-assets-ux-review, amon-hen-v1

#24411 chore: removing deprecated unused site icon component from codebase
  development/ts-migration-dashboard/files-to-convert.json
  ui/components/ui/site-icon/README.mdx
  ui/components/ui/site-icon/index.js
  ui/components/ui/site-icon/site-icon.js
  ui/components/ui/site-icon/site-icon.stories.js
  ui/components/ui/site-icon/site-icon.test.js
Labels: team-design-system

#24379 chore(ci): skip check-pr-tag job if not PR
  .circleci/config.yml
Labels: area-CI, team-security

#24362 feat: Removed multichain flag for v1 release
  test/e2e/accounts/common.ts
  test/e2e/tests/account/add-account.spec.js
  test/e2e/tests/dapp-interactions/dapp-interactions.spec.js
  test/e2e/tests/dapp-interactions/permissions.spec.js
  test/e2e/tests/metrics/dapp-viewed.spec.js
  test/e2e/tests/multichain/connection-page.spec.js
  test/e2e/tests/multichain/permission-page.spec.js
  test/e2e/tests/settings/change-language.spec.ts
  ui/components/app/alerts/alerts.js
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/app-header.test.js
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/global-menu/global-menu.test.js
  ui/components/multichain/network-list-menu/network-list-menu.js
  ui/components/multichain/network-list-menu/network-list-menu.test.js
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/index.js
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/home/home.component.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/selectors/permissions.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: needs-dev-review, INVALID-PR-TEMPLATE, team-wallet-ux, needs-assets-ux-review

#23719 feat: add inline alert to confirm `AlertRow` component
  ui/components/app/confirm/info/row/alert-row/__snapshots__/alert-row.test.tsx.snap
  ui/components/app/confirm/info/row/alert-row/alert-row.stories.tsx
  ui/components/app/confirm/info/row/alert-row/alert-row.test.tsx
  ui/components/app/confirm/info/row/alert-row/alert-row.tsx
  ui/components/app/confirm/info/row/row.tsx
  ui/components/app/confirmations/alerts/inline-alert/__snapshots__/inline-alert.test.tsx.snap
  ui/components/app/confirmations/alerts/inline-alert/inline-alert.tsx
Labels: team-confirmations-system, team-confirmations

#24467 fix: fix a date in a test
  app/scripts/controllers/metamask-notifications/mocks/mock-feature-announcements.ts
Labels: INVALID-PR-TEMPLATE, team-notifications

#24459 v11.15.4
  CHANGELOG.md
  app/_locales/en/messages.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/vault-decryption-chrome.spec.js
  ui/components/app/smart-transactions/index.scss
  ui/components/app/smart-transactions/smart-transactions-opt-in-modal.tsx
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#24421 fix: reset to native asset on account change
  test/e2e/tests/transaction/change-assets.spec.js
Labels: team-assets, needs-assets-ux-review

#24466 feat: enable signatures redesign new users
  app/scripts/controllers/preferences.js
  app/scripts/metamask-controller.js
  test/e2e/tests/confirmations/header.spec.js
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/confirmations/hooks/useCurrentConfirmation.test.ts
  ui/pages/confirmations/hooks/useCurrentConfirmation.ts
  ui/pages/confirmations/utils/confirm.ts
  ui/pages/settings/experimental-tab/__snapshots__/experimental-tab.test.js.snap
  ui/pages/settings/experimental-tab/experimental-tab.component.js
  ui/pages/settings/experimental-tab/experimental-tab.test.js
Labels: team-confirmations

#24222 feat: support transaction specific gas fee estimates
  app/scripts/metamask-controller.js
  builds.yml
  development/build/set-environment-variables.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/ducks/metamask/metamask.js
  ui/ducks/metamask/metamask.test.js
  yarn.lock
Labels: QA Passed, team-confirmations

#23759 feat: add multiple alert modal to `AlertRow` component
  ui/components/app/confirm/info/row/alert-row/__snapshots__/alert-row.test.tsx.snap
  ui/components/app/confirm/info/row/alert-row/alert-row.stories.tsx
  ui/components/app/confirm/info/row/alert-row/alert-row.test.tsx
  ui/components/app/confirm/info/row/alert-row/alert-row.tsx
  ui/components/app/confirmations/alerts/inline-alert/index.scss
Labels: team-confirmations-system

#24435 fix: Reset confirm redesign hasScrolledToBottom & feat: reset scroll position
  ui/hooks/usePrevious.ts
  ui/hooks/useScrollRequired.js
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.test.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.tsx
Labels: team-confirmations

#24402 feat: Confirmation Redesign "Confirm" button should be red when transaction is malicious
  ui/pages/confirmations/components/confirm/blockaid-alert/blockaid-alert.tsx
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/footer/useIsDangerButton.ts
  ui/pages/confirmations/hooks/useSignatureSecurityAlertResponse.ts
Labels: team-confirmations

#24478 fix: desktop build
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
Labels: team-confirmations

#24357 feat: Throw when encountering unexpected RPC method hooks
  app/scripts/lib/rpc-method-middleware/createMethodMiddleware.js
  app/scripts/lib/rpc-method-middleware/createMethodMiddleware.test.js
  app/scripts/lib/rpc-method-middleware/handlers/index.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  jest.config.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24475 fix: Prevent legacy <UnconnectedAccountAlert/> component from displaying
  ui/components/app/alerts/alerts.js
Labels: team-wallet-ux, needs-assets-ux-review

#24474 fix: Make ConnectAccountToast respect setting for multichain
  ui/pages/routes/routes.container.js
Labels: team-wallet-ux, needs-assets-ux-review

#24233 fix(deps): Bump @metamask/obs-store@^8.1.0->^9.0.0
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-security

#24433 chore(deps): Bump rate-limit-controller to ^5.0.1
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-shared-libraries

#24489 fix: Signature Redesign Disabled confirm button with missing ScrollToBottom button with 16px or less scroll buffer
  ui/hooks/useScrollRequired.js
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.test.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.tsx
Labels: team-confirmations

#23838 feat: Add new privacy policy toast
  app/_locales/en/messages.json
  app/scripts/controllers/app-state.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  shared/lib/ui-utils.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/toast/__snapshots__/toast.test.tsx.snap
  ui/components/multichain/toast/index.scss
  ui/components/multichain/toast/toast.tsx
  ui/helpers/constants/privacy-policy.ts
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/home/index.scss
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: team-wallet-ux, needs-assets-ux-review

#24484 fix: signature redesign ui_customizations metric
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
Labels: team-confirmations

#24369 revert: deprecating more networks (#23695)
  app/scripts/controllers/preferences.js
  app/scripts/controllers/preferences.test.js
  app/scripts/migrations/115.test.ts
  app/scripts/migrations/115.ts
  shared/constants/network.ts
  ui/helpers/utils/i18n-helper.tsx
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.js
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js
  ui/pages/settings/networks-tab/networks-tab.constants.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-assets, needs-assets-ux-review

#24401 refactor: remove whats new notification for staking
  app/_locales/en/messages.json
  app/images/staking-light-mode-preview.png
  shared/notifications/index.ts
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: team-portfolio, team-stake, team-wallet-ux

#24315 chore: updating code owners file with design system team code ownership
  .github/CODEOWNERS
Labels: team-design-system

#24358 test: [Snaps E2E] Streamline tests
  test/e2e/snaps/test-snap-clientstatus.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-dialog.spec.js
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/snaps/test-snap-get-file.spec.js
  test/e2e/snaps/test-snap-get-locale.spec.js
  test/e2e/snaps/test-snap-getentropy.spec.js
  test/e2e/snaps/test-snap-homepage.spec.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-lifecycle.spec.js
  test/e2e/snaps/test-snap-management.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-namelookup.spec.js
  test/e2e/snaps/test-snap-networkaccess.spec.js
  test/e2e/snaps/test-snap-notification.spec.js
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-siginsights.spec.js
  test/e2e/snaps/test-snap-txinsights-v2.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-uilinks.spec.js
  test/e2e/snaps/test-snap-update-component.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  test/e2e/snaps/test-snap-wasm.spec.js
Labels: area-snaps, team-snaps-platform

#24525 feat: Slightly update UI for the STX Opt In modal
  app/_locales/en/messages.json
  test/e2e/mmi/pageObjects/mmi-signup-page.ts
  test/e2e/vault-decryption-chrome.spec.js
  ui/components/app/smart-transactions/smart-transactions-opt-in-modal.tsx
Labels: team-transactions, release-11.15.5

#24530 Cherry-pick feat: Slightly update UI for the STX Opt In modal (#24525) into v11.15.5
  app/_locales/en/messages.json
  test/e2e/mmi/pageObjects/mmi-signup-page.ts
  test/e2e/vault-decryption-chrome.spec.js
  ui/components/app/smart-transactions/smart-transactions-opt-in-modal.tsx
Labels: INVALID-PR-TEMPLATE

#23610 feat: replace snap buttons with button links
  ui/components/app/app-components.scss
  ui/components/app/snaps/snap-ui-button/index.scss
  ui/components/app/snaps/snap-ui-button/snap-ui-button.tsx
  ui/components/app/snaps/snap-ui-renderer/components/button.ts
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#24520 fix: Update gas fee controller to v11.15.2
  package.json
  yarn.lock
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24346 fix: snap avatar colors
  ui/components/app/snaps/snap-avatar/snap-avatar.js
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/snap-account-redirect/__snapshots__/create-snap-redirect.test.tsx.snap
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#24539 fix: Use double quotes in in xpath text locator in driver.buildLocator
  test/e2e/webdriver/driver.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24521 chore(codeowners): Remove brad-decker
  .github/CODEOWNERS
  ui/store/actions.ts
Labels: team-extension-platform

#24519 fix: confirmation page not loading if re-design is enabled
  ui/pages/confirmations/utils/confirm.ts
Labels: needs-dev-review, confirmation-redesign, team-confirmations

#24500 fix: newline display in signature request content.
  ui/components/app/confirm/info/row/text.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/__snapshots__/personal-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/__snapshots__/typed-sign-v1.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/__snapshots__/dataTree.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data-v1/__snapshots__/typedSignDataV1.test.tsx.snap
  ui/pages/confirmations/components/confirm/row/typed-sign-data/__snapshots__/typedSignData.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: needs-dev-review, team-confirmations

#24557 chore: quoteXPathText utility function for e2e tests
  test/e2e/webdriver/driver.js
  test/helpers/quoteXPathText.ts
Labels: team-transactions

#24560 perf: force update state after snap request
  ui/components/app/snaps/snap-home-page/useSnapHome.js
  ui/hooks/snaps/useSignatureInsights.js
  ui/hooks/snaps/useTransactionInsightSnaps.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#24432 chore(deps): Bump permission-log-controller to ^2.0.1
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-shared-libraries

#24316 fix: reduce size of token list fetch
  ui/components/ui/new-network-info/new-network-info.js
  ui/components/ui/new-network-info/new-network-info.test.js
Labels: team-assets, needs-assets-ux-review

#24050 feat: New onboarding text
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/helpers/constants/privacy-policy.ts
  ui/pages/onboarding-flow/metametrics/__snapshots__/metametrics.test.js.snap
  ui/pages/onboarding-flow/metametrics/index.scss
  ui/pages/onboarding-flow/metametrics/metametrics.js
  ui/pages/onboarding-flow/metametrics/metametrics.test.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
Labels: team-wallet-ux, needs-assets-ux-review

#24567 fix: update lavamoat policies
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
Labels: team-extension-platform

#24563 fix: add fallback method for currency formatter in `useFiatFormatter` hook
  ui/hooks/useFiatFormatter.test.ts
  ui/hooks/useFiatFormatter.ts
Labels: team-confirmations

#24564 fix: Cherry-pick pr from develop to v11.16.0 to fix flaky test
  app/scripts/controllers/metamask-notifications/mocks/mock-feature-announcements.ts
  app/scripts/lib/setupSentry.js
  package.json
  test/e2e/helpers.js
  test/e2e/snaps/test-snap-namelookup.spec.js
  test/e2e/snaps/test-snap-siginsights.spec.js
  test/e2e/snaps/test-snap-txinsights-v2.spec.js
  test/e2e/synchronous-injection/synchronous-injection.spec.js
  test/e2e/tests/metrics/dapp-viewed.spec.js
  test/e2e/tests/multichain/connection-page.spec.js
  test/e2e/tests/multichain/permission-page.spec.js
  test/e2e/tests/onboarding/onboarding.spec.js
  test/e2e/tests/ppom/migrate-opensea-to-blockaid-banner.spec.js
  test/e2e/tests/ppom/ppom-blockaid-alert-metrics.spec.js
  test/e2e/tests/ppom/ppom-blockaid-toggle-metrics.spec.js
  test/e2e/tests/ppom/ppom-toggle-settings.spec.js
  test/e2e/tests/request-queuing/enable-queuing.spec.js
  test/e2e/tests/request-queuing/ui.spec.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24549 chore: Cherry pick 9024578 (Update gas fee controller to v11.15.2 #24520)
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#24305 Version v11.16.0 changelog
  CHANGELOG.md
Labels: INVALID-PR-TEMPLATE

#24581 chore: bumps MMI packages
  app/scripts/controllers/mmi-controller.test.ts
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/mmi/pageObjects/mmi-dummyApp-page.ts
  yarn.lock
Labels: team-mmi

#24607 test: fix flaky test `Permissions Page ...` and ` Connections Page...`
  test/e2e/tests/multichain/connection-page.spec.js
  test/e2e/tests/multichain/permission-page.spec.js
Labels: team-extension-platform, needs-dev-review, flaky tests

#24442 test: Assert accounts are removed with snap removal in existing test
  test/e2e/accounts/remove-account-snap.spec.ts
Labels: team-accounts, needs-dev-review, e2e-test

#24580 test: fix flaky tests `Dapp viewed Event...` `Permissions Page...` and `Connections Page...` due to overlaying popup
  test/e2e/tests/metrics/dapp-viewed.spec.js
  test/e2e/tests/multichain/connection-page.spec.js
  test/e2e/tests/multichain/permission-page.spec.js
  test/e2e/webdriver/driver.js
Labels: team-extension-platform, flaky tests

#24526 fix: (cherry-pick Version v11.17.0) Signature Redesign "ui_customizations" metric (#24484)
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
Labels: team-confirmations, release-11.17.0

#24527 fix: (cherry-pick Version v11.17.0) Fix confirmation redesign disabled "Confirm" button with 16px or less scroll buffer
  ui/hooks/useScrollRequired.js
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.test.tsx
  ui/pages/confirmations/components/confirm/scroll-to-bottom/scroll-to-bottom.tsx
Labels: team-confirmations, release-11.17.0

#24542 feat: update push notification API request/response
  app/scripts/controllers/push-platform-notifications/services/services.test.ts
  app/scripts/controllers/push-platform-notifications/services/services.ts
Labels: team-notifications

#24555 feat: add metametrics to authentication
  app/scripts/controllers/authentication/authentication-controller.test.ts
  app/scripts/controllers/authentication/authentication-controller.ts
  app/scripts/controllers/authentication/mocks/mockServices.ts
  app/scripts/controllers/authentication/services.test.ts
  app/scripts/controllers/authentication/services.ts
  app/scripts/controllers/metametrics.js
  app/scripts/controllers/metametrics.test.js
  app/scripts/controllers/user-storage/user-storage-controller.test.ts
  app/scripts/metamask-controller.js
Labels: team-notifications

#24600 cherry-pick: fix redesign metrics
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/metamask-controller.js
  shared/constants/app.ts
Labels: team-confirmations

#24487 feat: Expire duplicate RPC requests after three minutes
  app/scripts/lib/createDupeReqFilterMiddleware.js
  app/scripts/lib/createDupeReqFilterMiddleware.test.js
  app/scripts/lib/createDupeReqFilterMiddleware.test.ts
  app/scripts/lib/createDupeReqFilterMiddleware.ts
Labels: team-extension-platform, team-wallet-api-platform, INVALID-PR-TEMPLATE

#24434 Cherry-pick fix: decimals and fiat conversion crashes in simulation (#24422) into Version-v11.16.0
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.test.ts
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
Labels: INVALID-PR-TEMPLATE

#24584 cherry-pick: add fallback method for currency formatter in `useFiatFormatter`
  ui/hooks/useFiatFormatter.test.ts
  ui/hooks/useFiatFormatter.ts
Labels: INVALID-PR-TEMPLATE

#24639 test: fix flaky test `Send ETH from inside MetaMask finds the transaction`
  test/e2e/tests/transaction/send-eth.spec.js
Labels: team-extension-platform, needs-dev-review, flaky tests

#24143 chore: Bump logging-controller to 3.0.1 and signature-controller to 14.0.1
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: dependencies, team-shared-libraries

#24673 Version v11.16.0 cherry pick 24664
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#24229 chore(deps): Bump name-controller to ^6.0.1
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-shared-libraries

#22879 chore(test/e2e): ensure test domains never map to publically resolvable names
  privacy-snapshot.json
  test/e2e/mock-e2e.js
  test/e2e/tests/network/add-custom-network.spec.js
  test/e2e/tests/network/deprecated-networks.spec.js
Labels: team-security, e2e-test

#24630 cherry-pick: bumps MMI packages (#24581)
  app/scripts/controllers/mmi-controller.test.ts
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/mmi/pageObjects/mmi-dummyApp-page.ts
  yarn.lock
Labels: team-mmi

#24671 test: Fix popup flakiness in e2e tests
  test/e2e/accounts/common.ts
  test/e2e/tests/dapp-interactions/dapp-interactions.spec.js
  test/e2e/tests/dapp-interactions/permissions.spec.js
  test/e2e/tests/multichain/connection-page.spec.js
  test/e2e/tests/petnames/petnames-signatures.spec.js
  test/e2e/tests/signature/signature-request.spec.js
  test/e2e/tests/tokens/custom-token-add-approve.spec.js
  test/e2e/webdriver/driver.js
Labels: team-extension-platform, needs-dev-review, flaky tests

#24566 refactor: removed the whats new modal for portfolio
  app/_locales/en/messages.json
  app/images/portfolio-v2-whatsnew-banner.png
  shared/notifications/index.ts
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/selectors/selectors.js
Labels: team-portfolio

#24666 fix: Delete migration 115
  app/scripts/migrations/115.test.ts
  app/scripts/migrations/115.ts
  app/scripts/migrations/116.test.ts
  app/scripts/migrations/116.ts
  app/scripts/migrations/117.test.ts
  app/scripts/migrations/117.ts
  app/scripts/migrations/118.test.ts
  app/scripts/migrations/118.ts
  app/scripts/migrations/119.test.ts
  app/scripts/migrations/119.ts
  app/scripts/migrations/index.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24691 fix: stopgap for BigNumber shift NaN issue
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
Labels: team-transactions

#24550 chore: bump Snaps packages
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#24042 fix(devDeps): bump storybook packages from 7.4.6 to 7.6.19
  lavamoat/build-system/policy.json
  package.json
  ui/components/ui/icon/preloader/index.js
  ui/components/ui/popover/index.js
  yarn.lock
Labels: dependencies, team-design-system, team-security

#24375 fix: add min account balance requirement to 'Deploy contract, deposit and withdraw' user flow scenario
  test/manual-scenarios/transactions/deposit and withdraw.csv
Labels: area-documentation, team-confirmations, release-11.18.0

#24492 feat: QR-based add OneKey Hardware
  .github/ISSUE_TEMPLATE/bug-report.yml
  app/_locales/en/messages.json
  shared/constants/hardware-wallets.ts
  ui/pages/create-account/connect-hardware/index.test.tsx
  ui/pages/create-account/connect-hardware/select-hardware.js
Labels: QA Passed, external-contributor, team-hardware-wallets

#24700 Cherry-pick fix stopgap for BigNumber shift NaN issue (#24691) into v11.16.0
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
Labels: INVALID-PR-TEMPLATE

#24696 Remove user-data-dir usage in tests on mv3 builds
  test/e2e/webdriver/chrome.js
Labels: INVALID-PR-TEMPLATE

#24548 feat: updated mmi packages
  app/scripts/controllers/mmi-controller.test.ts
  lavamoat/build-system/policy.json
  package.json
  test/e2e/mmi/.env.example
  ui/components/app/transaction-status-label/transaction-status-label.test.js
  ui/pages/institutional/confirm-add-custodian-token/confirm-add-custodian-token.test.js
  ui/pages/institutional/interactive-replacement-token-page/interactive-replacement-token-page.test.js
  ui/store/institutional/institution-background.test.js
  yarn.lock
Labels: team-mmi

#24694 fix: Improve flakiness of await driver.findElements in 'importing multiple tokens from search' test
  test/e2e/tests/tokens/import-tokens.spec.js
  test/e2e/webdriver/driver.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24623 refactor: user storage small encryption changes.
  app/scripts/controllers/user-storage/encryption/cache.ts
  app/scripts/controllers/user-storage/encryption/encryption.test.ts
  app/scripts/controllers/user-storage/encryption/encryption.ts
  app/scripts/controllers/user-storage/encryption/index.ts
  app/scripts/controllers/user-storage/encryption/utils.ts
Labels: team-notifications

#24214 feat: add support dynamic actions in alert modal
  ui/components/app/confirm/info/row/alert-row/alert-row.stories.tsx
  ui/components/app/confirm/info/row/alert-row/alert-row.test.tsx
  ui/components/app/confirmations/alerts/alert-modal/alert-modal.stories.tsx
  ui/components/app/confirmations/alerts/alert-modal/alert-modal.test.tsx
  ui/components/app/confirmations/alerts/alert-modal/alert-modal.tsx
  ui/components/app/confirmations/alerts/multiple-alert-modal/multiple-alert-modal.stories.tsx
  ui/components/app/confirmations/alerts/multiple-alert-modal/multiple-alert-modal.test.tsx
  ui/components/app/confirmations/alerts/multiple-alert-modal/multiple-alert-modal.tsx
  ui/ducks/confirm-alerts/confirm-alerts.ts
  ui/hooks/useAlertActionHandler.test.ts
  ui/hooks/useAlertActionHandler.ts
  ui/pages/confirmations/confirm/confirm.tsx
  ui/pages/confirmations/hooks/useConfirmationAlertActions.test.ts
  ui/pages/confirmations/hooks/useConfirmationAlertActions.ts
Labels: team-confirmations-system

#24709 test: fix flaky test `Import ERC1155 NFT should be able to import an ERC1155 NFT that user owns`
  test/e2e/mock-e2e.js
Labels: team-extension-platform, needs-dev-review, flaky tests

#24703 chore: use Firefox ServiceBuilder and add geckodriver path for e2e in Linux + Firefox snap
  .metamaskrc.dist
  README.md
  test/e2e/webdriver/firefox.js
Labels: team-extension-platform, needs-dev-review

#24695 fix: Reduce appInstalledEvent timeout delay
  app/scripts/background.js
  test/e2e/tests/metrics/app-installed.spec.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24400 feat: add support to handle blocking alerts in the alert modal
  ui/components/app/confirmations/alerts/alert-modal/alert-modal.test.tsx
  ui/components/app/confirmations/alerts/alert-modal/alert-modal.tsx
  ui/ducks/confirm-alerts/confirm-alerts.test.ts
  ui/ducks/confirm-alerts/confirm-alerts.ts
Labels: team-confirmations

#23236 feat: Add RPC Method Middleware params transform and tracking
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
Labels: team-wallet-api-platform, team-data-and-analytics

#24622 fix: Send correct message action from ledger offscreen bridge to ledger bridge
  app/scripts/lib/offscreen-bridge/ledger-offscreen-bridge.ts
  shared/constants/offscreen-communication.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#24697 fix: Only prevent the service worker timestamp save if initState.PreferencesController?.enableMV3TimestampSave is false
  app/scripts/background.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#23763 chore: update `@trezor/connect-web` to `v9.2.2`
  .depcheckrc.yml
  .vscode/package.json-schema.json
  .yarn/patches/@trezor-connect-web-npm-9.2.2-a4de8e45fc.patch
  .yarn/patches/@trezor-schema-utils-npm-1.0.2-7dd48689b2.patch
  .yarn/patches/ts-mixer-npm-6.0.4-5d9747bdf5.patch
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  test/e2e/tests/account/import-flow.spec.js
  ui/pages/create-account/connect-hardware/__snapshots__/index.test.tsx.snap
  ui/pages/create-account/connect-hardware/select-hardware.js
  yarn.lock
Labels: team-extension-platform

#24715 feat: disable stx opt-in modal
  ui/pages/home/home.component.js
Labels: team-transactions

#24687 Feat/notifications read all button
  app/_locales/en/messages.json
  ui/pages/notifications/index.scss
  ui/pages/notifications/notifications-list-read-all-button.test.tsx
  ui/pages/notifications/notifications-list-read-all-button.tsx
  ui/pages/notifications/notifications-list.tsx
  ui/pages/notifications/notifications.tsx
Labels: team-notifications

#24701 chore: bump transaction-controller to 29.0.2
  package.json
  yarn.lock
Labels: team-transactions

#24725 fix(devDeps): @lavamoat/allow-scripts@^3.0.1->^3.0.4 (#24664)
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#24720 cherry-pick feat: disable stx opt-in modal (#24715) into v11.15.6
  ui/pages/home/home.component.js
Labels: INVALID-PR-TEMPLATE

#24722 feat (cherry-pick): Add new privacy policy toast (#23838)
  app/_locales/en/messages.json
  app/scripts/controllers/app-state.js
  app/scripts/lib/setupSentry.js
  app/scripts/metamask-controller.js
  shared/lib/ui-utils.js
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/toast/__snapshots__/toast.test.tsx.snap
  ui/components/multichain/toast/index.scss
  ui/components/multichain/toast/toast.tsx
  ui/helpers/constants/privacy-policy.ts
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/home/index.scss
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: INVALID-PR-TEMPLATE

#24726 Version v11.15.6
  CHANGELOG.md
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/desktop/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  ui/pages/home/home.component.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE, release-11.15.6
