Repository MetaMask/metamask-extension, pull requests merged in 2025-06, with the labels that each got.

#33150 feat: Adding AdditionalNetworkInfo component
  ui/components/multichain/network-manager/components/additional-networks-info/__snapshots__/additional-networks-info.test.tsx.snap
  ui/components/multichain/network-manager/components/additional-networks-info/additional-networks-info.stories.tsx
  ui/components/multichain/network-manager/components/additional-networks-info/additional-networks-info.test.tsx
  ui/components/multichain/network-manager/components/additional-networks-info/additional-networks-info.tsx
  ui/components/multichain/network-manager/components/additional-networks-info/index.ts
Labels: team-wallet-ux

#33315 fix: log migration error
  app/scripts/migrations/156.ts
Labels: team-assets

#32006 feat: prompt for automated vault recovery from internal vault backup if corruption is detected
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/background.js
  app/scripts/lib/setup-initial-state-hooks.js
  app/scripts/lib/state-corruption-errors.ts
  app/scripts/lib/state-corruption/state-corruption-recovery.test.ts
  app/scripts/lib/state-corruption/state-corruption-recovery.test.ts-utils.test.ts
  app/scripts/lib/state-corruption/state-corruption-recovery.ts
  app/scripts/lib/stores/base-store.ts
  app/scripts/lib/stores/extension-store.ts
  app/scripts/lib/stores/indexeddb-store.ts
  app/scripts/lib/stores/persistence-manager.test.ts
  app/scripts/lib/stores/persistence-manager.ts
  app/scripts/lib/stores/read-only-network-store.ts
  app/scripts/ui.js
  development/build/index.js
  shared/constants/errors.ts
  shared/lib/manifestFlags.ts
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/tests/vault-corruption/vault-corruption.spec.ts
  ui/css/errors.scss
  ui/index.js
Labels: Sev1-high, team-extension-platform

#33058 test: adds onboarding metrics validation to e2e
  test/e2e/tests/metrics/wallet-created.spec.ts
Labels: team-qa

#33396 feat: cp-12.18.3 bump solana-wallet-snap
  package.json
  yarn.lock
Labels: team-solana

#33394 ci: fix stale bot action
  .github/workflows/stale-issues-pr.yml
Labels: team-qa

#33269 Patch transaction controller adding `origin` to security alerts request
  .yarn/patches/@metamask-transaction-controller-npm-54.3.0-2c90b81511.patch
  yarn.lock
Labels: team-confirmations

#33350 Actually correct invalid selectedNetworkClientId
  .yarn/patches/@metamask-network-controller-npm-23.2.1-backport-52eed19c47.patch
  yarn.lock
Labels: team-wallet-framework

#33284 fix: flaky test `Request-queue UI changes should show network specific to domain`
  test/e2e/tests/request-queuing/ui.spec.js
Labels: flaky tests, team-qa

#33393 feat: update accounts deps to enable `KeyringRequest.origin` support - cp-12.20.0
  app/scripts/controller-init/messengers/notifications/notification-services-controller-messenger.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: team-accounts

#33399 fix: update op logo
  app/images/optimism.svg
Labels: team-assets

#33401 chore: Update changelog for v12.18.3
  CHANGELOG.md
Labels: team-wallet-framework

#33320 ci: Fix Crowdin workflow
  .github/workflows/crowdin-action.yml
Labels: team-wallet-framework

#33332 fix: potentially broken Multichain API eth subscription and missing wallet_sessionChanged events on Permission stateChange
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#33400 chore: Version 12.18.3
  .yarn/patches/@metamask-network-controller-npm-23.2.1-backport-52eed19c47.patch
  .yarn/patches/@metamask-transaction-controller-npm-54.3.0-2c90b81511.patch
  CHANGELOG.md
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
  attribution.txt
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/app/confirm/info/row/alert-row/alert-row.tsx
  ui/components/app/confirm/info/row/constants.ts
  ui/pages/confirmations/components/simulation-details/balance-change-list.tsx
  ui/pages/confirmations/components/simulation-details/balance-change-row.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.test.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
  ui/pages/confirmations/hooks/alerts/transactions/useMultipleApprovalsAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useMultipleApprovalsAlerts.ts
  ui/pages/confirmations/hooks/useConfirmationAlerts.ts
  yarn.lock
Labels: team-wallet-framework

#33437 Feat/seedless password sync with UI
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/hooks/social-sync/useSyncSRPs.ts
  ui/pages/keychains/restore-vault.js
  ui/pages/onboarding-flow/create-password/create-password.js
Labels: team-web3auth

#33264 test: fix stx opt-in opt-out fixture
  test/e2e/fixture-builder.js
  test/e2e/json-rpc/switchEthereumChain.spec.js
  test/e2e/page-objects/flows/toggle-stx-setting.flow.ts
  test/e2e/tests/confirmations/transactions/gas-fee-tokens-eip-7702.spec.ts
  test/e2e/tests/confirmations/transactions/gas-fee-tokens-smart-transactions.spec.ts
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
Labels: team-qa

#32404 feat: updated Account selector in header
  test/e2e/page-objects/pages/header-navbar.ts
  test/e2e/page-objects/pages/reset-password-page.ts
  test/e2e/tests/account/forgot-password.spec.ts
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header-container.tsx
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/app-header/index.scss
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/account-picker.test.tsx.snap
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#32963 chore: refactor main action buttons
  test/e2e/page-objects/pages/home/homepage.ts
  test/e2e/page-objects/pages/token-overview-page.ts
  ui/components/app/wallet-overview/coin-buttons.stories.js
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/app/wallet-overview/index.scss
  ui/components/ui/icon-button/icon-button-round.js
  ui/components/ui/icon-button/icon-button.scss
  ui/components/ui/icon-button/icon-button.stories.tsx
  ui/components/ui/icon-button/icon-button.test.tsx
  ui/components/ui/icon-button/icon-button.tsx
  ui/components/ui/icon-button/index.ts
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/asset/components/asset-page.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/home/index.scss
Labels: team-design-system, INVALID-PR-TEMPLATE

#33464 chore: Update build system comment about transpiled dependencies
  development/build/scripts.js
Labels: team-wallet-framework

#33260 feat: New SRP flow Terms of use
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  test/e2e/page-objects/pages/dialog/terms-of-use-update-modal.ts
  test/e2e/page-objects/pages/onboarding/onboarding-complete-page.ts
  test/integration/onboarding/import-wallet.test.tsx
  test/integration/onboarding/wallet-created.test.tsx
  ui/components/app/terms-of-use-popup/index.scss
  ui/components/app/terms-of-use-popup/terms-of-use-popup.js
  ui/components/app/terms-of-use-popup/terms-of-use-popup.stories.js
  ui/components/app/terms-of-use-popup/terms-of-use-popup.test.js
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
  ui/pages/onboarding-flow/creation-successful/creation-successful.test.js
  ui/pages/onboarding-flow/metametrics/__snapshots__/metametrics.test.js.snap
Labels: area-onboarding, team-web3auth

#33228 test: add send EIP1559 and send legacy in the mocked bridge for Ledger accounts
  test/e2e/tests/hardware-wallets/ledger-send.spec.ts
  test/stub/keyring-bridge.js
  test/stub/keyring-utils.js
Labels: team-qa

#33492 fix: flaky test `Test Snap Management tests install disable enable and removal of a snap`
  test/e2e/snaps/test-snap-management.spec.js
Labels: flaky tests, team-qa

#33302 test: remove some entries from the mock allow list (part 2)
  privacy-snapshot.json
  test/e2e/fixture-builder.js
  test/e2e/mock-e2e-allowlist.js
  test/e2e/mock-e2e.js
  test/e2e/page-objects/pages/home/non-evm-homepage.ts
  test/e2e/tests/network/linea-discover-button.spec.ts
  test/e2e/tests/simulation-details/mock-request-error-insuffient-gas.ts
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
  test/e2e/tests/solana/check-balance.spec.ts
  test/e2e/tests/solana/common-solana.ts
  test/e2e/tests/transaction/gas-estimates.spec.js
Labels: flaky tests, team-qa

#33254 fix: adds 'auto' button for solana dynamic slippage
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/ducks/bridge/selectors.ts
  ui/pages/bridge/prepare/bridge-transaction-settings-modal.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#33481 fix: disable non EVM networks on locked screen cp-12.20.0
  ui/components/multichain/network-list-menu/network-list-menu.tsx
Labels: team-accounts

#33458 chore: delete dead code for advanced-gas-inputs
  app/_locales/am/messages.json
  app/_locales/ar/messages.json
  app/_locales/bg/messages.json
  app/_locales/bn/messages.json
  app/_locales/ca/messages.json
  app/_locales/cs/messages.json
  app/_locales/da/messages.json
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/et/messages.json
  app/_locales/fa/messages.json
  app/_locales/fi/messages.json
  app/_locales/fil/messages.json
  app/_locales/fr/messages.json
  app/_locales/he/messages.json
  app/_locales/hi/messages.json
  app/_locales/hn/messages.json
  app/_locales/hr/messages.json
  app/_locales/ht/messages.json
  app/_locales/hu/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/kn/messages.json
  app/_locales/ko/messages.json
  app/_locales/lt/messages.json
  app/_locales/lv/messages.json
  app/_locales/ms/messages.json
  app/_locales/nl/messages.json
  app/_locales/no/messages.json
  app/_locales/ph/messages.json
  app/_locales/pl/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ro/messages.json
  app/_locales/ru/messages.json
  app/_locales/sk/messages.json
  app/_locales/sl/messages.json
  app/_locales/sr/messages.json
  app/_locales/sv/messages.json
  app/_locales/sw/messages.json
  app/_locales/ta/messages.json
  app/_locales/th/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/uk/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  ui/pages/confirmations/components/advanced-gas-inputs/advanced-gas-inputs.component.js
  ui/pages/confirmations/components/advanced-gas-inputs/advanced-gas-inputs.container.js
  ui/pages/confirmations/components/advanced-gas-inputs/advanced-gas-inputs.test.js
  ui/pages/confirmations/components/advanced-gas-inputs/index.js
  ui/pages/confirmations/components/advanced-gas-inputs/index.scss
Labels: team-extension-platform, no-changelog

#33503 docs: Fix some webpack CLI option descriptions
  development/webpack/utils/cli.ts
Labels: INVALID-PR-TEMPLATE, team-ocap-kernel

#33482 chore: bridge state controller not found
  app/scripts/migrations/155.test.ts
  app/scripts/migrations/155.ts
Labels: team-swaps-and-bridge

#33261 feat: 1.3 New srp flow welcome page
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  package.json
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/page-objects/pages/onboarding/start-onboarding-page.ts
  test/e2e/tests/account/incremental-security.spec.ts
  test/e2e/tests/metrics/app-installed.spec.ts
  test/e2e/tests/onboarding/onboarding.spec.ts
  test/e2e/tests/responsive-ui/metamask-responsive-ui.spec.js
  ui/components/component-library/icon/icon.types.ts
  ui/css/utilities/fonts.scss
  ui/css/utilities/fonts/MMPoly/MM_Poly-Regular.woff2
  ui/pages/onboarding-flow/index.scss
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/welcome/index.scss
  ui/pages/onboarding-flow/welcome/login-options.tsx
  ui/pages/onboarding-flow/welcome/types.ts
  ui/pages/onboarding-flow/welcome/welcome-banner.tsx
  ui/pages/onboarding-flow/welcome/welcome-login.tsx
  ui/pages/onboarding-flow/welcome/welcome.js
  ui/pages/onboarding-flow/welcome/welcome.stories.js
  ui/pages/onboarding-flow/welcome/welcome.test.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/utils.js
  yarn.lock
Labels: area-onboarding, team-web3auth

#33262 feat: 1.4 New welcome page header design and password form component
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  package.json
  ui/components/app/create-new-vault/create-new-vault.test.js
  ui/components/app/password-form/index.ts
  ui/components/app/password-form/password-form.stories.tsx
  ui/components/app/password-form/password-form.tsx
  ui/components/component-library/form-text-field/form-text-field.types.ts
  ui/components/ui/metafox-logo/horizontal-logo.js
  ui/pages/onboarding-flow/index.scss
  ui/pages/onboarding-flow/onboarding-app-header/__snapshots__/onboarding-app-header.test.js.snap
  ui/pages/onboarding-flow/onboarding-app-header/index.scss
  ui/pages/onboarding-flow/onboarding-app-header/onboarding-app-header.js
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/routes/utils.js
  yarn.lock
Labels: area-onboarding, team-web3auth

#33172 fix: Fix race condition in send flow validation for token balance check
  test/e2e/tests/petnames/petnames-transactions.spec.js
  test/e2e/tests/tokens/custom-token-send-transfer.spec.ts
  ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx
  ui/components/multichain/pages/send/send.js
  ui/components/multichain/pages/send/send.test.js
Labels: team-confirmations

#30131 chore: Remove additional dead Snaps code
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/app-components.scss
  ui/components/app/snaps/snap-content-footer/index.js
  ui/components/app/snaps/snap-content-footer/index.scss
  ui/components/app/snaps/snap-content-footer/snap-content-footer.js
  ui/components/app/snaps/snap-content-footer/snap-content-footer.stories.js
  ui/components/app/snaps/snap-legacy-authorship-header/index.js
  ui/components/app/snaps/snap-legacy-authorship-header/snap-legacy-authorship-header.js
  ui/components/app/snaps/snap-legacy-authorship-header/snap-legacy-authorship-header.stories.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#33489 test: add `withLedgerAccount` fixture
  test/e2e/fixture-builder.js
  test/e2e/tests/hardware-wallets/ledger-send.spec.ts
Labels: team-qa

#33352 test: Added test scenario for unlock wallet
  test/e2e/page-objects/pages/login-page.ts
  test/e2e/tests/account/unlock-wallet.ts
  test/e2e/tests/dapp-interactions/dapp-interactions.spec.ts
Labels: INVALID-PR-TEMPLATE, team-qa

#33358 test: remove some entries from the mock allow list (part 3)
  test/e2e/flask/btc/common-btc.ts
  test/e2e/flask/btc/mocks/feature-flag.ts
  test/e2e/flask/btc/mocks/index.ts
  test/e2e/mock-e2e-allowlist.js
  test/e2e/mock-e2e.js
  test/e2e/mock-response-data/test-dapp-styles-1.txt
  test/e2e/mock-response-data/test-dapp-styles-2.txt
Labels: team-qa

#33506 chore: Add sophon logo
  app/images/sophon-testnet.svg
  app/images/sophon.svg
  shared/constants/network.ts
Labels: team-assets

#33216 refactor: reorganize code related to restoring vault corruption
  app/scripts/lib/state-corruption/state-corruption-recovery.test.ts
  app/scripts/lib/state-corruption/state-corruption-recovery.ts
  app/scripts/ui.js
  shared/constants/errors.ts
  shared/constants/state-corruption.ts
  ui/helpers/utils/state-corruption-html.ts
  ui/index.js
Labels: team-extension-platform, no-changelog

#33519 ci: fix Crowdin translations workflow
  .github/scripts/git-diff-default-branch.ts
  .prettierignore
Labels: team-extension-platform

#33263 feat: 1.5 New create password design
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/page-objects/pages/onboarding/onboarding-password-page.ts
  test/e2e/tests/responsive-ui/metamask-responsive-ui.spec.js
  ui/components/app/password-form/password-form.tsx
  ui/components/component-library/form-text-field/form-text-field.types.ts
  ui/components/component-library/help-text/help-text.types.ts
  ui/components/component-library/label/label.types.ts
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/create-password/create-password.test.js
  ui/pages/onboarding-flow/create-password/index.scss
  ui/pages/onboarding-flow/onboarding-flow.test.js
Labels: area-onboarding, team-web3auth

#33095 feat: added basic functionality banner
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/basic-functionality.svg
  test/e2e/page-objects/pages/home/homepage.ts
  ui/components/multichain/account-overview/account-overview-layout.tsx
  ui/components/multichain/account-overview/account-overview.tsx
  ui/components/multichain/carousel/carousel.tsx
  ui/hooks/useCarouselManagement/constants.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.test.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.ts
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#33281 feat: 1.6 srp flow srp detail modal
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/app/srp-details-modal/index.ts
  ui/components/app/srp-details-modal/srp-details-modal.stories.tsx
  ui/components/app/srp-details-modal/srp-details-modal.test.tsx
  ui/components/app/srp-details-modal/srp-details-modal.tsx
Labels: area-onboarding, team-web3auth

#33321 feat: trust signals middleware
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/app-state-controller.ts
  app/scripts/lib/trust-signals/security-alerts-api.test.ts
  app/scripts/lib/trust-signals/security-alerts-api.ts
  app/scripts/lib/trust-signals/trust-signals-middleware.test.ts
  app/scripts/lib/trust-signals/trust-signals-middleware.ts
  app/scripts/lib/trust-signals/types.ts
  app/scripts/metamask-controller.js
  builds.yml
  shared/types/background.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/integration/data/integration-init-state.json
  test/integration/data/onboarding-completion-route.json
Labels: INVALID-PR-TEMPLATE, team-product-safety

#33499 feat: add `AccountTreeController`
  app/scripts/constants/sentry-state.ts
  app/scripts/controller-init/accounts/account-tree-controller-init.test.ts
  app/scripts/controller-init/accounts/account-tree-controller-init.ts
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/accounts/account-tree-controller-messenger.test.ts
  app/scripts/controller-init/messengers/accounts/account-tree-controller-messenger.ts
  app/scripts/controller-init/messengers/accounts/index.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: team-accounts

#33285 feat: 1.7 update secure your wallet page UI
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/ph/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  test/e2e/page-objects/pages/onboarding/secure-wallet-page.ts
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/secure-your-wallet/index.scss
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.js
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.test.js
  ui/pages/onboarding-flow/secure-your-wallet/skip-srp-backup-popover.js
  ui/pages/onboarding-flow/secure-your-wallet/skip-srp-backup-popover.stories.tsx
  ui/pages/onboarding-flow/secure-your-wallet/skip-srp-backup-popover.test.tsx
  ui/pages/onboarding-flow/secure-your-wallet/skip-srp-backup-popover.tsx
Labels: area-onboarding, team-web3auth

#33541 chore: bump test dapp multichain package and respective util updates
  package.json
  test/e2e/flask/multichain-api/testHelpers.ts
  test/e2e/flask/multichain-api/wallet_invokeMethod.spec.ts
  test/e2e/flask/multichain-api/wallet_notify.spec.ts
  test/e2e/flask/multichain-api/wallet_revokeSession.spec.ts
  test/e2e/flask/multichain-api/wallet_sessionChanged.spec.ts
  test/e2e/page-objects/pages/test-dapp-multichain.ts
  yarn.lock
Labels: team-wallet-api-platform

#33098 feat: added solana swaps e2e and fix solana flakiness
  test/e2e/flask/solana-wallet-standard/transaction_sol.spec.ts
  test/e2e/flask/solana-wallet-standard/transaction_wsol.spec.ts
  test/e2e/page-objects/pages/bridge/quote-page.ts
  test/e2e/page-objects/pages/home/activity-list.ts
  test/e2e/page-objects/pages/home/non-evm-homepage.ts
  test/e2e/page-objects/pages/send/solana-confirm-tx-page.ts
  test/e2e/page-objects/pages/swap/swap-page.ts
  test/e2e/tests/solana/check-balance.spec.ts
  test/e2e/tests/solana/common-solana.ts
  test/e2e/tests/solana/mocks/ethMarketData.json
  test/e2e/tests/solana/mocks/priceApiSpotSolanaUsdc.json
  test/e2e/tests/solana/mocks/quoteSolToUsdc.json
  test/e2e/tests/solana/mocks/quoteUsdcToSol.json
  test/e2e/tests/solana/mocks/securityAlertSwap.json
  test/e2e/tests/solana/mocks/solUsdcTransaction.json
  test/e2e/tests/solana/mocks/solanaMarketData.json
  test/e2e/tests/solana/mocks/succeededTransaction.json
  test/e2e/tests/solana/mocks/tokenAccountTokenProgram.json
  test/e2e/tests/solana/mocks/tokenAccountTokenProgram2022.json
  test/e2e/tests/solana/mocks/usdcSolTransaction.json
  test/e2e/tests/solana/send-flow.spec.ts
  test/e2e/tests/solana/send-spl-token.spec.ts
  test/e2e/tests/solana/solana-networks.spec.ts
  test/e2e/tests/solana/swap.spec.ts
  test/e2e/tests/solana/transaction-activity-list.spec.ts
Labels: team-qa

#33560 fix: cp-12.20.0 remove bitcoin preferences migration (#33554) cherry-pick
  app/scripts/migrations/161.1.test.ts
  app/scripts/migrations/161.1.ts
  app/scripts/migrations/index.js
Labels: team-extension-platform, extension-delivery

#33521 test: remove some entries from the mock allow list (part 4)
  test/e2e/mock-e2e-allowlist.js
Labels: team-qa, release-12.22.0

#33513 fix: bump `@metamask/keyring-controller` to `^22.0.2`
  package.json
  yarn.lock
Labels: team-wallet-framework, team-hardware-wallets, release-12.22.0

#33471 feat: pass trackEvent to DeFiPositionsController
  app/scripts/controller-init/defi-positions/defi-positions-controller-init.ts
Labels: team-assets, release-12.22.0

#33286 feat: 1.8 Onboarding metametrics locales and UI change
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/playwright/shared/pageObjects/signup-page.ts
  ui/pages/onboarding-flow/metametrics/__snapshots__/metametrics.test.js.snap
  ui/pages/onboarding-flow/metametrics/index.scss
  ui/pages/onboarding-flow/metametrics/metametrics.js
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.js
Labels: area-onboarding, team-web3auth, release-12.22.0

#33546 refactor: Remove extraneous code fence
  ui/components/multichain/account-picker/account-picker.js
Labels: type-refactor, team-wallet-ux, release-12.22.0

#33485 feat: Add `--features` option to legacy build system CLI
  development/build/config.js
  development/build/index.js
  development/build/scripts.js
  development/build/static.js
  development/build/task.js
Labels: area-buildSystem, INVALID-PR-TEMPLATE, team-ocap-kernel

#33384 refactor(react-router): asset-list-control-bar.tsx
  .storybook/preview.js
  .vscode/cspell.json
  test/lib/render-helpers-navigate.js
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.test.tsx
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/asset-list/asset-list.ramps-card.test.js
  ui/components/app/assets/asset-list/asset-list.test.tsx
  ui/components/app/assets/defi-list/defi-tab.test.tsx
  ui/components/app/assets/nfts/nfts-tab/nfts-tab.test.js
  ui/components/multichain/account-overview/account-overview-eth.test.tsx
  ui/components/multichain/account-overview/account-overview-non-evm.test.tsx
  ui/pages/routes/routes.component.test.js
Labels: team-extension-platform, no-changelog

#33572 chore: cp-12.20.0 bump solana-wallet-standard to 0.5.0 & multichain-api-client to 0.6.2
  package.json
  yarn.lock
Labels: team-wallet-standard

#33561 test: Migrate responsive-ui e2e tests to Typescript and Page object modal
  test/e2e/multi-injected-provider/multi-provider-injection-check.spec.js
  test/e2e/multi-injected-provider/multi-provider-injection-check.spec.ts
  test/e2e/page-objects/pages/reset-password-page.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/responsive-ui/metamask-responsive-ui.spec.js
  test/e2e/tests/responsive-ui/metamask-responsive-ui.spec.ts
  test/e2e/tests/synchronous-injection/synchronous-injection.spec.ts
Labels: team-qa

#33549 test: Migrate eth-sign e2e test to Typescript and Page object modal
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/confirmations/signatures/eth-sign.spec.ts
  test/e2e/tests/signature/eth-sign.spec.js
Labels: team-qa

#33583 test: remove some entries from the mock allow list (part 5)
  test/e2e/mock-e2e-allowlist.js
  test/e2e/snaps/test-snap-uilinks.spec.js
Labels: team-qa

#33577 fix: reduce chains.json fetches by moving hook to AssetList cp-12.20.0
  ui/components/multichain/asset-picker-amount/asset-picker-modal/Asset.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/__snapshots__/AssetList.test.tsx.snap
  ui/components/multichain/token-list-item/token-list-item.test.tsx
  ui/components/multichain/token-list-item/token-list-item.tsx
Labels: area-performance, team-swaps-and-bridge

#33598 chore: Update code owners for accounts components
  .github/CODEOWNERS
Labels: team-accounts

#33545 feat: Add provisional Ocap Kernel integration
  .depcheckrc.yml
  builds.yml
  development/build/index.js
  development/build/manifest.js
  development/build/scripts.js
  development/build/static.js
  offscreen/scripts/ocap-kernel/index.ts
  offscreen/scripts/offscreen.ts
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-ocap-kernel

#33579 fix: pass safeChains prop from parent components to TokenCell cp-12.20.0
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/token-cell/token-cell.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/multichain/account-overview/account-overview-tabs.tsx
  ui/pages/asset/components/asset-page.tsx
  ui/pages/defi/components/defi-details-list.tsx
  ui/pages/settings/networks-tab/networks-form/use-safe-chains.ts
Labels: team-swaps-and-bridge

#33559 chore: Bump Snaps packages
  app/scripts/constants/sentry-state.ts
  app/scripts/controller-init/messengers/snaps/cronjob-controller-messenger.ts
  app/scripts/controller-init/snaps/cronjob-controller-init.test.ts
  app/scripts/metamask-controller.js
  app/scripts/migrations/165.test.ts
  app/scripts/migrations/165.ts
  app/scripts/migrations/index.js
  builds.yml
  development/build/scripts.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  shared/types/background.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/app/snaps/snap-ui-renderer/components/account-selector.test.ts
  yarn.lock
Labels: team-snaps-platform

#33463 chore: use the new `@metamask/foundryup` package
  .depcheckrc.yml
  .github/workflows/run-benchmarks.yml
  .github/workflows/run-e2e.yml
  .yarnrc.yml
  jest.config.js
  package.json
  test/helpers/foundry/download.ts
  test/helpers/foundry/extract.ts
  test/helpers/foundry/foundryup.test.ts
  test/helpers/foundry/foundryup.ts
  test/helpers/foundry/options.ts
  test/helpers/foundry/types.ts
  test/helpers/foundry/utils.ts
  yarn.lock
Labels: team-extension-platform

#33602 fix: include gas limit and gas fees in simulation requests
  package.json
  test/e2e/tests/simulation-details/mock-request-buy-erc1155.ts
  test/e2e/tests/simulation-details/mock-request-buy-erc20.ts
  test/e2e/tests/simulation-details/mock-request-buy-erc721.ts
  test/e2e/tests/simulation-details/mock-request-send-eth.ts
  yarn.lock
Labels: team-confirmations

#33570 fix: skip topAssets request when chainId is Solana
  shared/lib/swaps-utils.js
  ui/pages/swaps/swaps.util.test.js
  ui/pages/swaps/swaps.util.ts
Labels: team-swaps-and-bridge

#33600 test: remove some entries from the mock allow list (part 6)
  test/e2e/mock-e2e-allowlist.js
  test/e2e/mock-e2e.js
  test/e2e/tests/privacy/account-tracker-api-usage.spec.ts
  test/e2e/tests/privacy/polling.spec.ts
  test/e2e/tests/survey/survey.spec.js
Labels: team-qa

#33277 feat: base account details
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain-accounts/account-details-row/account-details-row.stories.tsx
  ui/components/multichain-accounts/account-details-row/account-details-row.test.tsx
  ui/components/multichain-accounts/account-details-row/account-details-row.tsx
  ui/components/multichain-accounts/account-details-row/index.ts
  ui/components/multichain-accounts/edit-account-name-modal/edit-account-name-modal.stories.tsx
  ui/components/multichain-accounts/edit-account-name-modal/edit-account-name-modal.test.tsx
  ui/components/multichain-accounts/edit-account-name-modal/edit-account-name-modal.tsx
  ui/components/multichain-accounts/edit-account-name-modal/index.ts
  ui/components/ui/qr-code-view/qr-code-view.tsx
  ui/helpers/constants/routes.ts
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.stories.tsx
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.test.tsx
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.tsx
  ui/pages/multichain-accounts/address-qr-code/index.ts
  ui/pages/multichain-accounts/base-account-details/base-account-details.stories.tsx
  ui/pages/multichain-accounts/base-account-details/base-account-details.test.tsx
  ui/pages/multichain-accounts/base-account-details/base-account-details.tsx
  ui/pages/multichain-accounts/base-account-details/index.ts
Labels: team-accounts, INVALID-PR-TEMPLATE

#33635 fix: remove warning from console due to duplicate key in security tab
  ui/pages/settings/security-tab/security-tab.component.js
Labels: team-extension-platform, no-changelog, deeplink, area-zero-warnings

#33636 test: fix type in `driver` test helper
  test/e2e/webdriver/driver.js
Labels: team-extension-platform, no-changelog, deeplink

#33637 test: embed favicon in "E2E Test Page" to reduce calls and request noise in tests
  test/e2e/mock-e2e.js
Labels: team-extension-platform, no-changelog, deeplink

#33642 refactor: set return type of `getState` to `MetaMaskReduxState`
  app/scripts/metamask-controller.js
Labels: team-extension-platform, no-changelog, deeplink

#33514 fix(snaps): Adjust `SnapUIAccountSelector` height
  ui/components/app/snaps/snap-ui-account-selector/index.scss
  ui/components/app/snaps/snap-ui-account-selector/snap-ui-account-selector.tsx
  ui/components/app/snaps/snap-ui-renderer/components/__snapshots__/account-selector.test.ts.snap
Labels: team-snaps-platform

#33487 feat: MMS-2553 unified UI for swaps and bridges
  ui/hooks/bridge/useTokensWithFiltering.ts
  ui/pages/bridge/hooks/useDestinationAccount.ts
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#33646 fix: flaky test Vault Decrypt uploading the log file in the vault-decryptor webapp
  test/e2e/vault-decryption-chrome.spec.ts
Labels: flaky tests, team-qa

#33649 chore: cp-12.21.0 bump solana 1.33.1
  package.json
  yarn.lock
Labels: team-new-networks

#33652 fix: Fix cronjob controller migration for state without `events`
  app/scripts/migrations/165.test.ts
  app/scripts/migrations/165.ts
Labels: team-snaps-platform

#33648 build: bump `@metamask/notification-services-controller@10.0.0`
  package.json
  yarn.lock
Labels: team-assets

#33640 fix: enable multichain API connections in MV2 (webpack) builds
  app/scripts/background.js
Labels: team-wallet-api-platform

#33651 chore: Make accounts code owners more specific
  .github/CODEOWNERS
Labels: team-accounts

#33644 fix: Solana network position
  shared/modules/network.utils.test.ts
  shared/modules/network.utils.ts
Labels: team-accounts

#33359 feat: 1.14 social flow account not found
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/helpers/constants/routes.ts
  ui/pages/onboarding-flow/account-not-found/account-not-found.stories.tsx
  ui/pages/onboarding-flow/account-not-found/account-not-found.test.tsx
  ui/pages/onboarding-flow/account-not-found/account-not-found.tsx
  ui/pages/onboarding-flow/onboarding-flow.js
Labels: area-onboarding, team-web3auth

#33360 feat: 1.15 social flow header and unlock page
  app/_locales/am/messages.json
  app/_locales/ar/messages.json
  app/_locales/bg/messages.json
  app/_locales/bn/messages.json
  app/_locales/ca/messages.json
  app/_locales/da/messages.json
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/et/messages.json
  app/_locales/fa/messages.json
  app/_locales/fi/messages.json
  app/_locales/fil/messages.json
  app/_locales/fr/messages.json
  app/_locales/he/messages.json
  app/_locales/hi/messages.json
  app/_locales/hr/messages.json
  app/_locales/ht/messages.json
  app/_locales/hu/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/kn/messages.json
  app/_locales/ko/messages.json
  app/_locales/lt/messages.json
  app/_locales/lv/messages.json
  app/_locales/ms/messages.json
  app/_locales/no/messages.json
  app/_locales/ph/messages.json
  app/_locales/pl/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ro/messages.json
  app/_locales/ru/messages.json
  app/_locales/sk/messages.json
  app/_locales/sl/messages.json
  app/_locales/sr/messages.json
  app/_locales/sv/messages.json
  app/_locales/sw/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/uk/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  app/images/forgot-password-lock.png
  test/e2e/page-objects/pages/login-page.ts
  ui/components/multichain/app-header/index.scss
  ui/pages/onboarding-flow/secure-your-wallet/skip-srp-backup-popover.test.tsx
  ui/pages/unlock-page/__snapshots__/unlock-page.test.js.snap
  ui/pages/unlock-page/formatted-counter.test.tsx
  ui/pages/unlock-page/formatted-counter.tsx
  ui/pages/unlock-page/index.scss
  ui/pages/unlock-page/reset-password-modal.tsx
  ui/pages/unlock-page/unlock-page.component.js
  ui/pages/unlock-page/unlock-page.test.js
Labels: area-onboarding, team-web3auth

#33672 ci: add `bump` and `release` to conventional commit types
  .github/workflows/validate-conventional-commits.yml
Labels: team-extension-platform, no-changelog

#33551 feat: enable backup & sync for all users
  app/scripts/metamask-controller.js
  app/scripts/migrations/167.test.ts
  app/scripts/migrations/167.ts
  app/scripts/migrations/index.js
  test/e2e/page-objects/pages/reset-password-page.ts
  test/e2e/tests/confirmations/transactions/nft-token-send-redesign.spec.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: team-identity

#33654 build: bump `@metamask/assets-controllers@68.2.0`
  .yarn/patches/@metamask-assets-controllers-npm-68.2.0-402120c55e.patch
  package.json
  yarn.lock
Labels: team-assets

#33701 fix: `clipboardRead` permission request in Firefox
  test/setup.js
  types/global.d.ts
  ui/components/app/srp-input-import/srp-input-import.test.tsx
  ui/components/app/srp-input-import/srp-input-import.tsx
Labels: area-onboarding, team-web3auth

#33664 release: Master sync v12.20.0 into main
  .github/workflows/check-pr-max-lines.yml
  CHANGELOG.md
  attribution.txt
  package.json
Labels: team-extension-platform, extension-delivery, release-12.21.0

#33694 fix: flaky tests `Gas Fee Tokens - EIP-7702`
  test/e2e/page-objects/pages/confirmations/redesign/transaction-confirmation.ts
  test/e2e/tests/confirmations/transactions/gas-fee-tokens-eip-7702.spec.ts
Labels: flaky tests, team-qa

#33717 test: fix flaky "Preinstalled example Snap can display the Snap settings page"
  test/e2e/flask/snaps/preinstalled-example.spec.ts
Labels: team-extension-platform, no-changelog

#33548 feat: new users to be opted in for smart account by default
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/controllers/app-state-controller.ts
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/migrations/168.test.ts
  app/scripts/migrations/168.ts
  app/scripts/migrations/index.js
  shared/constants/smartTransactions.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.test.tsx
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.tsx
  ui/pages/confirmations/selectors/preferences.ts
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
  ui/store/actions.ts
Labels: team-confirmations

#33531 feat: enforce simulation hook
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/controller-init/delegation/delegation-controller-init.ts
  app/scripts/controller-init/messengers/transaction-controller-messenger.ts
  app/scripts/lib/transaction/containers/enforced-simulations.test.ts
  app/scripts/lib/transaction/containers/enforced-simulations.ts
  app/scripts/lib/transaction/containers/util.test.ts
  app/scripts/lib/transaction/containers/util.ts
  app/scripts/lib/transaction/hooks/enforce-simulation-hook.test.ts
  app/scripts/lib/transaction/hooks/enforce-simulation-hook.ts
  builds.yml
  package.json
  shared/lib/delegation/caveatBuilder/erc1155BalanceChangeBuilder.test.ts
  shared/lib/delegation/caveatBuilder/erc1155BalanceChangeBuilder.ts
  shared/lib/delegation/caveatBuilder/erc20BalanceChangeBuilder.test.ts
  shared/lib/delegation/caveatBuilder/erc20BalanceChangeBuilder.ts
  shared/lib/delegation/caveatBuilder/erc721BalanceChangeBuilder.test.ts
  shared/lib/delegation/caveatBuilder/erc721BalanceChangeBuilder.ts
  shared/lib/delegation/caveatBuilder/index.ts
  shared/lib/delegation/caveatBuilder/nativeBalanceChangeBuilder.test.ts
  shared/lib/delegation/caveatBuilder/nativeBalanceChangeBuilder.ts
  shared/lib/delegation/environment.ts
  yarn.lock
Labels: team-confirmations

#33729 refactor: split account-list-menu into account-menu re-usable component
  ui/components/multichain/account-list-menu/account-list-menu.stories.tsx
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/account-menu/account-menu.stories.tsx
  ui/components/multichain/account-menu/account-menu.test.tsx
  ui/components/multichain/account-menu/account-menu.tsx
  ui/components/multichain/account-menu/index.scss
  ui/components/multichain/account-menu/index.ts
Labels: team-accounts

#33639 feat(deeplinks): allow `unlock` to navigate to the originally intended screen after unlock
  ui/helpers/higher-order-components/authenticated/authenticated.component.js
  ui/pages/unlock-page/unlock-page.component.js
  ui/pages/unlock-page/unlock-page.container.js
  ui/pages/unlock-page/unlock-page.test.js
Labels: team-extension-platform, no-changelog, deeplink

#33380 feat: 1.16 metametrics new flow
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/tests/account/incremental-security.spec.ts
  test/e2e/tests/metrics/app-installed.spec.ts
  test/e2e/tests/metrics/nft-detection-metrics.spec.ts
  test/e2e/tests/metrics/token-detection-metrics.spec.ts
  test/e2e/tests/metrics/wallet-created.spec.ts
  test/e2e/tests/metrics/wallet-imported.spec.ts
  test/e2e/tests/onboarding/onboarding.spec.ts
  test/integration/confirmations/signatures/permit.test.tsx
  test/integration/confirmations/signatures/personalSign.test.tsx
  test/integration/confirmations/transactions/contract-deployment.test.tsx
  test/integration/confirmations/transactions/contract-interaction.test.tsx
  test/integration/defi/defi-positions.test.tsx
  test/integration/nfts/nfts.test.tsx
  test/integration/notifications&auth/notifications-activation.test.tsx
  test/integration/notifications&auth/notifications-list.test.tsx
  test/integration/notifications&auth/notifications-toggle.test.tsx
  ui/components/multichain/app-header/app-header-container.tsx
  ui/contexts/metametrics.js
  ui/pages/keychains/restore-vault.js
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/create-password/create-password.test.js
  ui/pages/onboarding-flow/import-srp/import-srp.js
  ui/pages/onboarding-flow/metametrics/metametrics.js
  ui/pages/onboarding-flow/metametrics/metametrics.test.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.js
  ui/pages/onboarding-flow/recovery-phrase/confirm-recovery-phrase.js
  ui/pages/onboarding-flow/recovery-phrase/confirm-recovery-phrase.test.js
  ui/pages/onboarding-flow/recovery-phrase/review-recovery-phrase.js
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.js
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.test.js
  ui/pages/onboarding-flow/secure-your-wallet/skip-srp-backup-popover.tsx
  ui/pages/onboarding-flow/welcome/welcome.js
  ui/pages/unlock-page/unlock-page.component.js
  ui/selectors/first-time-flow.js
Labels: area-onboarding, team-web3auth

#33723 test: Migrate flask multichain-api e2e tests to Page object modal (part 1)
  test/e2e/flask/multichain-api/wallet_createSession.spec.ts
  test/e2e/flask/multichain-api/wallet_getSession.spec.ts
  test/e2e/flask/multichain-api/wallet_revokeSession.spec.ts
  test/e2e/page-objects/pages/confirmations/redesign/connect-account-confirmation.ts
  test/e2e/page-objects/pages/dialog/edit-connected-accounts-modal.ts
  test/e2e/page-objects/pages/dialog/network-permission-select-modal.ts
  test/e2e/page-objects/pages/test-dapp-multichain.ts
Labels: team-qa, no-changelog

#33724 fix: Display "Switch back" instead of "Switch" for smart accounts - extension
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/confirmations/components/confirm/smart-account-tab/account-network/account-network.test.tsx
  ui/pages/confirmations/components/confirm/smart-account-tab/account-network/account-network.tsx
Labels: team-confirmations

#33721 fix: flaky test `Migrate vault with old encryption` and `Forgot password`
  test/e2e/tests/account/forgot-password.spec.ts
  test/e2e/tests/account/migrate-old-vault.spec.ts
Labels: flaky tests, team-qa

#33593 test: Migrating snap pom
  test/e2e/page-objects/pages/dialog/snap-install.ts
  test/e2e/page-objects/pages/snap-list-page.ts
  test/e2e/page-objects/pages/test-snaps.ts
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-cronjob.spec.ts
  test/e2e/snaps/test-snap-rpc.spec.js
  test/e2e/snaps/test-snap-rpc.spec.ts
  test/e2e/snaps/test-snap-update-component.spec.js
  test/e2e/snaps/test-snap-update-component.spec.ts
Labels: INVALID-PR-TEMPLATE, team-qa

#33667 feat: replaced block explorer url link in view explorer menu item com…
  test/e2e/tests/dapp-interactions/block-explorer.spec.ts
  ui/components/app/modals/nickname-popovers/nickname-popovers.component.test.tsx
  ui/helpers/utils/multichain/blockExplorer.test.ts
  ui/helpers/utils/multichain/blockExplorer.ts
Labels: team-wallet-ux, Remove GNS

#33660 feat(deeplinks): add deep link router
  app/scripts/lib/deep-links/deep-link-router.ts
  app/scripts/lib/deep-links/deep-link.router.test.ts
  builds.yml
  shared/lib/deep-links/canonicalize.test.ts
  shared/lib/deep-links/canonicalize.ts
  shared/lib/deep-links/constants.ts
  shared/lib/deep-links/helpers.test.ts
  shared/lib/deep-links/helpers.ts
  shared/lib/deep-links/parse.test.ts
  shared/lib/deep-links/parse.ts
  shared/lib/deep-links/routes/index.test.ts
  shared/lib/deep-links/routes/index.ts
  shared/lib/deep-links/routes/route.test.ts
  shared/lib/deep-links/routes/route.ts
  shared/lib/deep-links/verify.test.ts
  shared/lib/deep-links/verify.ts
  shared/lib/manifestFlags.ts
  ui/helpers/constants/routes.ts
Labels: team-extension-platform, no-changelog, deeplink

#33710 feat: form text field margin and helptext
  test/e2e/page-objects/pages/dialog/add-edit-network.ts
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/password-form/password-form.tsx
  ui/components/app/snaps/snap-ui-renderer/components/__snapshots__/form.test.ts.snap
  ui/components/component-library/form-text-field/form-text-field.tsx
  ui/components/component-library/help-text/__snapshots__/help-text.test.tsx.snap
  ui/components/component-library/help-text/help-text.tsx
  ui/components/multichain/network-list-menu/__snapshots__/network-list-menu.test.js.snap
  ui/components/multichain/network-list-menu/add-rpc-url-modal/__snapshots__/add-rpc-url-modal.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-named-snap-account.test.js.snap
  ui/pages/unlock-page/__snapshots__/unlock-page.test.js.snap
  ui/pages/unlock-page/unlock-page.component.js
Labels: area-onboarding, team-web3auth

#33767 fix: onboarding flow fixes
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/app/srp-input-import/srp-input-import.tsx
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/onboarding-flow/recovery-phrase/__snapshots__/recovery-phrase-chips.test.js.snap
  ui/pages/onboarding-flow/recovery-phrase/recovery-phrase-chips.js
Labels: area-onboarding, team-web3auth

#33663 feat(deeplinks): install deep link feature with routes to home, swap, and notifications
  .vscode/cspell.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/background.js
  app/scripts/lib/deep-links/metrics.test.ts
  app/scripts/lib/deep-links/metrics.ts
  development/build/set-environment-variables.js
  privacy-snapshot.json
  shared/constants/metametrics.ts
  shared/constants/urls.ts
  shared/lib/deep-links/routes/buy.ts
  shared/lib/deep-links/routes/helpers.test.ts
  shared/lib/deep-links/routes/helpers.ts
  shared/lib/deep-links/routes/home.ts
  shared/lib/deep-links/routes/index.ts
  shared/lib/deep-links/routes/notifications.ts
  shared/lib/deep-links/routes/route.ts
  shared/lib/deep-links/routes/swap.ts
  test/e2e/page-objects/pages/deep-link-page.ts
  test/e2e/tests/deep-link/deep-link.spec.ts
  test/e2e/tests/deep-link/helpers.ts
  ui/pages/deep-link/deep-link.tsx
  ui/pages/deep-link/index.ts
  ui/pages/routes/routes.component.js
  ui/pages/routes/utils.js
Labels: team-extension-platform, deeplink

#33585 fix: setting correct metrics parameter for Future ETH
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  shared/constants/transaction.ts
  ui/pages/confirmations/components/confirm/info/hooks/useGasFeeToken.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useGasFeeToken.ts
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-icon/gas-fee-token-icon.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-icon/gas-fee-token-icon.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-list-item/gas-fee-token-list-item.stories.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-list-item/gas-fee-token-list-item.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-modal/gas-fee-token-modal.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-modal/gas-fee-token-modal.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-toast/gas-fee-token-toast.tsx
  ui/pages/confirmations/components/confirm/info/shared/selected-gas-fee-token/selected-gas-fee-token.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/selected-gas-fee-token/selected-gas-fee-token.tsx
  ui/pages/confirmations/hooks/useAutomaticGasFeeTokenSelect.test.ts
  ui/pages/confirmations/hooks/useAutomaticGasFeeTokenSelect.ts
Labels: team-confirmations

#33671 feat: adds a hook to confirmation alerts for address trust signals
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/lib/trust-signals/trust-signals-middleware.ts
  app/scripts/lib/trust-signals/trust-signals-util.test.ts
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/hooks/alerts/useTrustSignalAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/useTrustSignalAlerts.ts
  ui/pages/confirmations/hooks/useConfirmationAlerts.ts
Labels: team-product-safety

#33768 fix: cp-12.20.1 case where internal accounts can be undefined
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#33771 fix: don't show onboarding header on popup mode
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/onboarding-flow/recovery-phrase/confirm-recovery-phrase.js
  ui/pages/onboarding-flow/recovery-phrase/review-recovery-phrase.js
Labels: team-web3auth

#33699 feat: indicate enforced simulations are active
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/app/confirm/info/row/row.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.test.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
Labels: team-confirmations

#33778 feat: remove snap confirmation page from Swap/Bridge page
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/tests/solana/common-solana.ts
  test/e2e/tests/solana/swap.spec.ts
  ui/ducks/bridge/selectors.ts
  ui/pages/bridge/hooks/useSnapConfirmation.ts
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  yarn.lock
Labels: team-swaps-and-bridge

#33657 feat: add new multichain-accounts-list-menu (using new tree view)
  ui/components/multichain-accounts/multichain-account-list-menu/index.scss
  ui/components/multichain-accounts/multichain-account-list-menu/index.ts
  ui/components/multichain-accounts/multichain-account-list-menu/multichain-account-list-menu.stories.tsx
  ui/components/multichain-accounts/multichain-account-list-menu/multichain-account-list-menu.test.tsx
  ui/components/multichain-accounts/multichain-account-list-menu/multichain-account-list-menu.tsx
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.stories.tsx
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.test.tsx
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.tsx
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/selectors/multichain-accounts/account-tree.test.ts
  ui/selectors/multichain-accounts/account-tree.ts
  ui/selectors/multichain-accounts/account-tree.types.ts
  ui/selectors/multichain-accounts/feature-flags.ts
  ui/selectors/selectors.types.ts
Labels: team-accounts

#32027 feat: add `SEI` mainnet network support
  shared/constants/bridge.ts
  shared/constants/common.ts
  shared/constants/network.test.ts
  shared/constants/network.ts
  shared/constants/swaps.ts
  shared/modules/bridge-utils/security-alerts-api.util.ts
  ui/components/multichain/network-list-menu/__snapshots__/network-list-menu.test.js.snap
  ui/ducks/bridge/selectors.test.ts
  ui/pages/swaps/swaps.util.ts
  ui/selectors/selectors.js
Labels: QA Passed, needs-dev-review, team-network-enablement

#32904 refactor: dedupe common middleware hooks between Eip1193 and CAIP engines
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#33077 test: EIP-5792 methods on Multichain API
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  test/e2e/flask/multichain-api/wallet_invokeMethod.spec.ts
  yarn.lock
Labels: team-wallet-api-platform

#33609 feat: Improve how we display detailed of approve function in nested transaction
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  shared/constants/transaction.ts
  shared/modules/transaction.utils.test.js
  shared/modules/transaction.utils.ts
  ui/pages/confirmations/components/confirm/info/batch/nested-transaction-data/nested-transaction-data.test.tsx
  ui/pages/confirmations/components/confirm/info/batch/nested-transaction-data/nested-transaction-data.tsx
  ui/pages/confirmations/components/confirm/info/shared/batched-approval-function/batched-approval-function.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/batched-approval-function/batched-approval-function.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.tsx
Labels: team-confirmations

#33772 fix: cp-12.22.0 flaky `Token List` and `Token Details` specs
  test/e2e/page-objects/pages/home/asset-list.ts
  test/e2e/tests/tokens/import-tokens.spec.ts
  test/e2e/tests/tokens/token-details.spec.ts
  test/e2e/tests/tokens/token-list.spec.ts
  test/e2e/tests/tokens/token-sort.spec.ts
  test/e2e/webdriver/driver.js
Labels: flaky tests, team-qa

#33780 fix: replace "Remind" with "remind" in deep link locale messages
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
Labels: team-extension-platform

#33530 feat: add 7702 toggles
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain-accounts/smart-contract-account-toggle-section/__snapshots__/smart-contract-account-toggle-section.test.tsx.snap
  ui/components/multichain-accounts/smart-contract-account-toggle-section/index.ts
  ui/components/multichain-accounts/smart-contract-account-toggle-section/smart-contract-account-toggle-section.test.tsx
  ui/components/multichain-accounts/smart-contract-account-toggle-section/smart-contract-account-toggle-section.tsx
  ui/components/multichain-accounts/smart-contract-account-toggle/__snapshots__/smart-contract-account-toggle.test.tsx.snap
  ui/components/multichain-accounts/smart-contract-account-toggle/index.ts
  ui/components/multichain-accounts/smart-contract-account-toggle/smart-contract-account-toggle.test.tsx
  ui/components/multichain-accounts/smart-contract-account-toggle/smart-contract-account-toggle.tsx
Labels: team-accounts, INVALID-PR-TEMPLATE

#33752 feat: add search bar
  ui/components/multichain-accounts/multichain-account-list-menu/multichain-account-list-menu.test.tsx
  ui/components/multichain-accounts/multichain-account-list-menu/multichain-account-list-menu.tsx
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.tsx
  ui/components/multichain-accounts/multichain-accounts-tree/utils.test.ts
  ui/components/multichain-accounts/multichain-accounts-tree/utils.ts
Labels: team-accounts

#33784 release: auto-update for PR targeting release branch
  .github/workflows/auto-update-pr-targeting-release.yml
  development/generate-attributions.sh
Labels: team-extension-platform, no-changelog

#33786 feat: swap transaction scanning and alerts
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  shared/modules/bridge-utils/security-alerts-api.util.test.ts
  shared/modules/bridge-utils/security-alerts-api.util.ts
  shared/types/security-alerts-api.ts
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/bridge.ts
  ui/ducks/bridge/selectors.ts
  ui/ducks/bridge/types.ts
  ui/hooks/bridge/useIsTxSubmittable.ts
  ui/hooks/bridge/useTxAlerts.ts
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/bridge-cta-button.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#33828 chore: Make policy review tip visible again in identify-codeowners.ts
  .github/scripts/identify-codeowners.ts
Labels: team-lavamoat

#33826 fix: Using sorting by timestamp for EVM transactions also cp-12.21.0
  ui/components/app/transaction-list/transaction-list.component.js
Labels: team-confirmations

#33761 feat: pin account inside wallet
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.test.tsx
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.tsx
  ui/selectors/multichain-accounts/account-tree.test.ts
  ui/selectors/multichain-accounts/account-tree.ts
Labels: team-accounts

#33816 fix: prioritize Contentful banners over hardcoded ones
  shared/constants/app-state.ts
  ui/components/multichain/carousel/carousel.tsx
  ui/hooks/useCarouselManagement/fetchCarouselSlidesFromContentful.ts
Labels: team-phosphor

#33839 feat: add native token logo for Soneium mainnet
  shared/constants/network.ts
Labels: team-network-enablement

#33133 fix: z-index of app header
  ui/components/multichain/app-header/index.scss
  ui/components/multichain/toast/index.scss
  ui/css/design-system/_z-index.scss
Labels: team-design-system

#33698 feat: Add account selection to upgrade account splash page
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/controllers/app-state-controller.test.ts
  app/scripts/controllers/app-state-controller.ts
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/metamask-controller.js
  app/scripts/migrations/169.test.ts
  app/scripts/migrations/169.ts
  app/scripts/migrations/index.js
  shared/types/background.ts
  test/data/mock-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/pages/confirmations/components/confirm/account-selection/account-selection.scss
  ui/pages/confirmations/components/confirm/account-selection/account-selection.test.tsx
  ui/pages/confirmations/components/confirm/account-selection/account-selection.tsx
  ui/pages/confirmations/components/confirm/account-selection/index.ts
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.scss
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.test.tsx
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.tsx
  ui/pages/confirmations/components/index.scss
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmations/selectors/confirm.ts
  ui/pages/confirmations/selectors/preferences.ts
  ui/pages/confirmations/types/confirm.ts
  ui/store/actions.ts
Labels: team-confirmations

#33805 fix: cp-12.22.0 resubscribe notifications v2 on app startup.
  ui/contexts/metamask-notifications/metamask-notifications.test.ts
  ui/contexts/metamask-notifications/metamask-notifications.tsx
Labels: team-assets

#33863 fix: fix pbkdf2 yarn audit
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  yarn.lock
Labels: team-accounts

#33809 fix: fix how different approval types are displayed for batched confirmations
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/metamask-controller.js
  shared/modules/transaction.utils.test.js
  shared/modules/transaction.utils.ts
  ui/pages/confirmations/components/confirm/info/shared/batched-approval-function/batched-approval-function.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/batched-approval-function/batched-approval-function.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.tsx
Labels: team-confirmations

#33865 test: fix failing integration tests
  test/integration/swaps/swaps-alerts.test.tsx
  ui/pages/confirmations/components/confirm/account-selection/account-selection.tsx
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.tsx
Labels: team-qa

#33790 feat: hide accounts
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.test.tsx
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.tsx
  ui/components/multichain/account-list-item-menu/account-list-item-menu.js
  ui/components/multichain/account-list-menu/hidden-account-list.js
Labels: team-accounts

#33878 release: forgot to update CHANGELOG for v12.20.1
  CHANGELOG.md
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#33881 release: Master sync v12.20.1 into main
  CHANGELOG.md
  attribution.txt
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#33854 chore: replacing deprecated button with component library version
  ui/components/app/modals/hide-token-confirmation-modal/__snapshots__/hide-token-confirmation-modal.test.js.snap
  ui/components/app/modals/hide-token-confirmation-modal/hide-token-confirmation-modal.js
  ui/components/app/modals/hide-token-confirmation-modal/index.scss
  ui/components/app/modals/new-account-modal/new-account-modal.component.js
  ui/components/app/recovery-phrase-reminder/recovery-phrase-reminder.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-gas-limit/advanced-gas-fee-gas-limit.stories.tsx
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-save/advanced-gas-fee-save.js
  ui/pages/confirmations/components/advanced-gas-fee-popover/advanced-gas-fee-save/advanced-gas-fee-save.stories.tsx
  ui/pages/confirmations/components/edit-gas-display/edit-gas-display.component.js
  ui/pages/confirmations/components/edit-gas-display/index.scss
  ui/pages/connected-sites/connected-sites.component.js
  ui/pages/create-account/connect-hardware/account-list.js
  ui/pages/create-account/connect-hardware/index.scss
  ui/pages/settings/contact-list-tab/edit-contact/edit-contact.component.js
  ui/pages/settings/contact-list-tab/view-contact/view-contact.component.js
  ui/pages/swaps/select-quote-popover/select-quote-popover.js
Labels: team-design-system

#33880 fix: Change tooltip position on network indicator
  ui/components/multichain/account-network-indicator/account-network-indicator.tsx
Labels: team-accounts

#33888 fix: scroll to bottom not being triggered on some devices
  ui/components/app/terms-of-use-popup/terms-of-use-popup.js
Labels: team-web3auth

#33378 feat: 2.0 added `OAuthService` for social logins
  .metamaskrc.dist
  app/scripts/metamask-controller.js
  app/scripts/services/oauth/apple-login-handler.ts
  app/scripts/services/oauth/base-login-handler.ts
  app/scripts/services/oauth/constants.ts
  app/scripts/services/oauth/create-login-handler.ts
  app/scripts/services/oauth/google-login-handler.ts
  app/scripts/services/oauth/oauth-service.test.ts
  app/scripts/services/oauth/oauth-service.ts
  app/scripts/services/oauth/types.ts
  app/scripts/services/oauth/utils.test.ts
  app/scripts/services/oauth/utils.ts
  app/scripts/services/oauth/web-authenticator-factory.ts
  builds.yml
  development/build/constants.js
  development/build/index.js
  development/build/manifest.js
  development/build/set-environment-variables.js
  development/webpack/test/plugins.ManifestPlugin.test.ts
  development/webpack/test/webpack.config.test.ts
  development/webpack/utils/plugins/ManifestPlugin/helpers.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  shared/modules/error.ts
  test/e2e/set-manifest-flags.ts
  yarn.lock
Labels: area-onboarding, QA Passed, team-web3auth

#33877 chore: Add tests in preperation for `NetworkManager`
  app/scripts/controllers/network-order.ts
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.test.ts
  test/data/bridge/mock-bridge-store.ts
  test/e2e/default-fixture.js
  test/e2e/fixture-builder.js
  test/e2e/flask/create-watch-account.spec.ts
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/confirmations/transactions/transaction-decoding-redesign.spec.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/e2e/tests/ppom/ppom-blockaid-alert-simple-send.spec.js
  test/e2e/tests/privacy/account-tracker-api-usage.spec.ts
  test/e2e/tests/privacy/onboarding-token-price-call-privacy.spec.ts
  test/e2e/tests/privacy/polling.spec.ts
  test/e2e/tests/responsive-ui/metamask-responsive-ui.spec.ts
  test/e2e/tests/settings/account-token-list.spec.ts
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
  test/e2e/tests/swap-send/swap-send-eth-with-loaded-state.spec.ts
  test/e2e/tests/swaps/swap-erc20-with-loaded-state.spec.ts
  test/e2e/tests/tokens/import-tokens.spec.ts
  test/e2e/tests/tokens/nft/auto-detect-nft.spec.ts
  test/e2e/tests/tokens/send-erc20-with-loaded-state.spec.ts
  test/e2e/tests/transaction/ens.spec.ts
  test/e2e/tests/transaction/gas-estimates.spec.js
  test/e2e/user-actions-benchmark.ts
  test/integration/data/integration-init-state.json
  test/integration/data/onboarding-completion-route.json
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.test.tsx
  ui/components/app/assets/asset-list/network-filter/network-filter.tsx
  ui/components/app/assets/nfts/nfts-tab/nfts-tab.test.js
  ui/components/app/transaction-list/__snapshots__/transaction-list.test.js.snap
  ui/components/app/transaction-list/transaction-list.test.js
  ui/components/multichain/account-overview/account-overview-unknown.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-nft-tab.test.tsx
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/components/multichain/pages/send/send.test.js
  ui/hooks/bridge/useTokensWithFiltering.test.ts
  ui/hooks/useAccountTrackerPolling.test.ts
  ui/hooks/useCurrencyRatePolling.test.ts
  ui/hooks/useCurrencyRatePolling.ts
  ui/hooks/useTokenDetectionPolling.test.ts
  ui/hooks/useTokenDetectionPolling.ts
  ui/hooks/useTokenListPolling.test.ts
  ui/hooks/useTokenListPolling.ts
  ui/hooks/useTokenRatesPolling.test.ts
  ui/hooks/useTokenRatesPolling.ts
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/confirmations/confirmation/stories/util.js
  ui/pages/routes/routes.component.test.js
  ui/pages/settings/networks-tab/networks-form/networks-form.test.js
  ui/pages/settings/networks-tab/networks-form/networks-form.tsx
  ui/selectors/multichain/networks.ts
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: team-assets

#33858 feat: display EVM swap txs in unified tx components
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  shared/lib/transactions-controller-utils.js
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
  ui/ducks/bridge-status/selectors.ts
  ui/hooks/bridge/useBridgeChainInfo.ts
  ui/hooks/bridge/useBridgeTxHistoryData.ts
  ui/hooks/useTransactionDisplayData.js
  ui/pages/bridge/hooks/useBridgeTokenDisplayData.ts
  ui/pages/bridge/index.scss
  ui/pages/bridge/quotes/bridge-quotes-modal.tsx
  ui/pages/bridge/transaction-details/bridge-explorer-links.tsx
  ui/pages/bridge/transaction-details/transaction-detail-row.tsx
  ui/pages/bridge/transaction-details/transaction-details.test.tsx
  ui/pages/bridge/transaction-details/transaction-details.tsx
  ui/pages/bridge/utils/tx-details.test.ts
  ui/pages/bridge/utils/tx-details.ts
Labels: team-swaps-and-bridge

#33847 chore: update buttons to be monochromatic
  ui/components/app/detected-token/detected-token-ignored-popover/__snapshots__/detected-token-ignored-popover.test.tsx.snap
  ui/components/app/modals/hide-token-confirmation-modal/__snapshots__/hide-token-confirmation-modal.test.js.snap
  ui/components/app/modals/transaction-already-confirmed/__snapshots__/transaction-already-confirmed.test.tsx.snap
  ui/components/app/modals/visit-support-data-consent-modal/__snapshots__/visit-support-data.test.tsx.snap
  ui/components/app/multi-rpc-edit-modal/__snapshots__/multi-rpc-edit-modal.test.tsx.snap
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/snaps/snap-ui-renderer/__snapshots__/snap-ui-renderer.test.js.snap
  ui/components/app/update-modal/__snapshots__/update-modal.test.tsx.snap
  ui/components/component-library/button-base/button-base.scss
  ui/components/component-library/button-primary/__snapshots__/button-primary.test.tsx.snap
  ui/components/component-library/button-primary/button-primary.scss
  ui/components/component-library/button-primary/button-primary.tsx
  ui/components/component-library/button-secondary/__snapshots__/button-secondary.test.tsx.snap
  ui/components/component-library/button-secondary/button-secondary.scss
  ui/components/component-library/button-secondary/button-secondary.tsx
  ui/components/component-library/button/__snapshots__/button.test.tsx.snap
  ui/components/component-library/button/button.stories.tsx
  ui/components/multichain/connect-accounts-modal/__snapshots__/connect-accounts-modal.test.tsx.snap
  ui/components/multichain/import-account/__snapshots__/json.test.tsx.snap
  ui/components/multichain/network-list-menu/__snapshots__/network-list-menu.test.js.snap
  ui/components/multichain/network-list-menu/add-rpc-url-modal/__snapshots__/add-rpc-url-modal.test.tsx.snap
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/ui/button/buttons.scss
  ui/components/ui/page-container/page-container-footer/__snapshots__/page-container-footer.component.test.js.snap
  ui/css/design-system/_colors.scss
  ui/helpers/constants/design-system.ts
  ui/pages/bridge/__snapshots__/index.test.tsx.snap
  ui/pages/bridge/prepare/__snapshots__/bridge-cta-button.test.tsx.snap
  ui/pages/bridge/prepare/__snapshots__/prepare-bridge-page.test.tsx.snap
  ui/pages/confirm-add-suggested-nft/__snapshots__/confirm-add-suggested-nft.test.js.snap
  ui/pages/confirm-decrypt-message/__snapshots__/confirm-decrypt-message.component.test.js.snap
  ui/pages/confirm-encryption-public-key/__snapshots__/confirm-encryption-public-key.component.test.js.snap
  ui/pages/confirmations/components/confirm/footer/__snapshots__/footer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/__snapshots__/edit-spending-cap-modal.test.tsx.snap
  ui/pages/confirmations/components/confirm/nav/__snapshots__/nav.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/add-ethereum-chain.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-named-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/error.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/snap-account-redirect.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/success.test.js.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/switch-ethereum-chain.test.js.snap
  ui/pages/create-account/connect-hardware/__snapshots__/index.test.tsx.snap
  ui/pages/keychains/__snapshots__/reveal-seed.test.js.snap
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
  ui/pages/onboarding-flow/metametrics/__snapshots__/metametrics.test.js.snap
  ui/pages/onboarding-flow/recovery-phrase/__snapshots__/review-recovery-phrase.test.js.snap
  ui/pages/permissions-connect/connect-page/__snapshots__/connect-page.test.tsx.snap
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/smart-transactions/smart-transaction-status-page/__snapshots__/smart-transactions-status-page.test.tsx.snap
  ui/pages/swaps/swaps-footer/__snapshots__/swaps-footer.test.js.snap
  ui/pages/unlock-page/__snapshots__/unlock-page.test.js.snap
Labels: team-design-system

#33906 feat: add wallet property to base account details
  ui/pages/multichain-accounts/base-account-details/base-account-details.stories.tsx
  ui/pages/multichain-accounts/base-account-details/base-account-details.test.tsx
  ui/pages/multichain-accounts/base-account-details/base-account-details.tsx
  ui/selectors/multichain-accounts/account-tree.ts
Labels: team-accounts

#33837 feat: add wallet details page and update routing
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  test/e2e/page-objects/pages/settings/privacy-settings.ts
  test/e2e/tests/settings/settings-security-reveal-srp.spec.ts
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.tsx
  ui/components/multichain/multichain-accounts/wallet-details-account-item/wallet-details-account-item.test.tsx
  ui/components/multichain/multichain-accounts/wallet-details-account-item/wallet-details-account-item.tsx
  ui/helpers/constants/routes.ts
  ui/pages/keychains/reveal-seed.js
  ui/pages/keychains/reveal-seed.test.js
  ui/pages/multichain-accounts/wallet-details/index.ts
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.test.tsx
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.tsx
  ui/pages/multichain-accounts/wallet-details/wallet-details.scss
  ui/pages/pages.scss
  ui/pages/routes/routes.component.js
  ui/pages/routes/utils.js
Labels: team-accounts

#33830 fix: Created new migration to remove disabledUpgradeAccountByChain from preferences controller state as old migration had error
  app/scripts/migrations/170.test.ts
  app/scripts/migrations/170.ts
  app/scripts/migrations/index.js
Labels: team-confirmations

#33921 fix: Prevent `DeFiPositionsController` from polling while UI is closed
  app/scripts/metamask-controller.js
  shared/types/background.ts
Labels: team-extension-platform

#31287 fix: grammar on activity tab
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/ph/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/_locales/zh_TW/messages.json
  test/e2e/page-objects/flows/send-transaction.flow.ts
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/request-queuing/ui.spec.js
  test/e2e/tests/settings/address-book.spec.ts
  test/e2e/tests/settings/clear-activity.spec.ts
  test/e2e/tests/solana/transaction-activity-list.spec.ts
  test/e2e/tests/swap-send/swap-send-erc20.spec.ts
  test/e2e/tests/swap-send/swap-send-eth-with-loaded-state.spec.ts
  test/e2e/tests/tokens/custom-token-send-transfer.spec.ts
  test/e2e/tests/transaction/change-assets.spec.js
  test/e2e/tests/transaction/incoming-transactions.spec.ts
  ui/components/app/assets/defi-list/defi-list.test.tsx
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
  ui/components/app/transaction-list/__snapshots__/transaction-list.test.js.snap
  ui/components/app/transaction-list/transaction-list.test.js
  ui/hooks/useMultichainTransactionDisplay.ts
  ui/hooks/useTransactionDisplayData.js
  ui/hooks/useTransactionDisplayData.test.js
Labels: team-assets

#33919 test: Fix flaky test Import flow Import Account using json file
  test/e2e/page-objects/pages/account-list-page.ts
Labels: team-qa

#33838 chore: add logos for Abstract network
  app/images/abstract.svg
  shared/constants/network.ts
Labels: QA Passed, team-network-enablement, release-12.23.0
