Repository MetaMask/metamask-extension, pull requests merged in 2025-07, with the labels that each got.

#33991 fix: srp words are glitching when toggling show/hide all
  ui/components/app/srp-input-import/srp-input-import.scss
  ui/components/app/srp-input-import/srp-input-import.tsx
Labels: team-web3auth

#33787 test: Added e2e tests for gas included Swap and choose your own token feature
  test/e2e/page-objects/pages/home/homepage.ts
  test/e2e/page-objects/pages/send/send-token-page.ts
  test/e2e/page-objects/pages/swap/swap-page.ts
  test/e2e/tests/smart-transactions/mocks.ts
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
  test/e2e/tests/swaps/shared.ts
  test/e2e/tests/swaps/swap-erc20-with-loaded-state.spec.ts
Labels: team-qa

#33994 build: change our default Prettier and ESLint plugins
  .devcontainer/devcontainer.json
  .vscode/cspell.json
  .vscode/extensions.json
  .vscode/settings.json
Labels: team-extension-platform, no-changelog

#33397 feat: 2.4 reset wallet for social login flow
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/keychains/restore-vault.js
  ui/pages/unlock-page/reset-password-modal.tsx
  ui/selectors/first-time-flow.js
Labels: area-onboarding, QA Passed, team-web3auth

#33964 feat: account details pages w/o 7702
  test/data/mock-accounts.ts
  ui/components/multichain-accounts/account-details-row/account-details-row.tsx
  ui/components/multichain-accounts/edit-account-name-modal/edit-account-name-modal.tsx
  ui/components/multichain/menu-items/account-details-menu-item.js
  ui/pages/multichain-accounts/account-details/account-type-utils.test.ts
  ui/pages/multichain-accounts/account-details/account-type-utils.ts
  ui/pages/multichain-accounts/account-details/btc-account-details.tsx
  ui/pages/multichain-accounts/account-details/evm-account-details.tsx
  ui/pages/multichain-accounts/account-details/hardware-account-details.tsx
  ui/pages/multichain-accounts/account-details/index.ts
  ui/pages/multichain-accounts/account-details/institutional-evm-account-details.tsx
  ui/pages/multichain-accounts/account-details/multichain-account-details.test.tsx
  ui/pages/multichain-accounts/account-details/multichain-account-details.tsx
  ui/pages/multichain-accounts/account-details/private-key-account-details.tsx
  ui/pages/multichain-accounts/account-details/solana-account-details.tsx
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.scss
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.stories.tsx
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.test.tsx
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.tsx
  ui/pages/multichain-accounts/base-account-details/base-account-details.scss
  ui/pages/multichain-accounts/base-account-details/base-account-details.stories.tsx
  ui/pages/multichain-accounts/base-account-details/base-account-details.test.tsx
  ui/pages/multichain-accounts/base-account-details/base-account-details.tsx
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.tsx
  ui/pages/pages.scss
  ui/pages/routes/routes.component.js
  ui/pages/routes/utils.js
Labels: team-accounts, INVALID-PR-TEMPLATE

#34016 fix: prevent infinite render in `WalletDetails`
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.tsx
Labels: team-accounts, INVALID-PR-TEMPLATE

#33385 feat: 2.2 change password and security settings
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/metamask-controller.js
  shared/constants/app-state.ts
  test/e2e/mock-e2e-allowlist.js
  test/e2e/page-objects/pages/settings/change-password-page.ts
  test/e2e/page-objects/pages/settings/privacy-settings.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/settings/change-password.spec.ts
  ui/components/app/app-components.scss
  ui/components/app/password-form/password-form.tsx
  ui/components/app/toast-master/index.scss
  ui/components/app/toast-master/selectors.ts
  ui/components/app/toast-master/toast-master.js
  ui/components/app/toast-master/utils.ts
  ui/ducks/app/app.ts
  ui/helpers/constants/routes.ts
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/onboarding-flow/welcome/welcome-login.tsx
  ui/pages/settings/index.scss
  ui/pages/settings/security-tab/change-password/change-password.stories.tsx
  ui/pages/settings/security-tab/change-password/change-password.test.tsx
  ui/pages/settings/security-tab/change-password/change-password.tsx
  ui/pages/settings/security-tab/change-password/index.ts
  ui/pages/settings/security-tab/index.scss
  ui/pages/settings/security-tab/reveal-srp-list/reveal-srp-list.tsx
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
  ui/pages/settings/settings.stories.js
  ui/store/actionConstants.ts
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: area-onboarding, area-settings, QA Passed, team-web3auth

#33782 feat: retrieve outgoing transaction history
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  test/data/transaction-data.json
  test/e2e/tests/transaction/incoming-transactions.spec.ts
  ui/hooks/useTransactionDisplayData.js
  ui/hooks/useTransactionDisplayData.test.js
Labels: team-confirmations

#34004 feat: reveal srp list improvements
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/settings/index.scss
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
Labels: area-accounts, area-onboarding, QA Passed, team-web3auth

#33612 feat: 2.8 login error modals
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/services/oauth/oauth-service.ts
  ui/pages/onboarding-flow/welcome/login-error-modal.stories.tsx
  ui/pages/onboarding-flow/welcome/login-error-modal.tsx
  ui/pages/onboarding-flow/welcome/types.ts
  ui/pages/onboarding-flow/welcome/welcome.js
  ui/pages/onboarding-flow/welcome/welcome.test.js
Labels: area-onboarding, team-web3auth

#34020 feat: Add support for `snap_startTrace` and `snap_endTrace` RPC methods
  app/scripts/controllers/permissions/specifications.js
  app/scripts/metamask-controller.js
Labels: team-snaps-platform

#33898 feat: add ledger e2e tests for ERC20 deployment
  test/e2e/page-objects/flows/login.flow.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/hardware-wallets/ledger-erc20.spec.ts
  test/stub/keyring-bridge.js
  test/stub/keyring-utils.js
Labels: team-hardware-wallets

#33959 feat(wallet-details): adds option to add account from wallet details
  ui/components/multichain/edit-accounts-modal/add-account.tsx
  ui/components/multichain/edit-accounts-modal/add-new-account-option.tsx
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.tsx
  ui/components/multichain/multichain-accounts/wallet-details-account-type-selection/index.ts
  ui/components/multichain/multichain-accounts/wallet-details-account-type-selection/wallet-details-account-type-selection.tsx
  ui/hooks/accounts/useMultichainWalletSnapClient.ts
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.test.tsx
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.tsx
  ui/pages/multichain-accounts/wallet-details/wallet-details.scss
Labels: team-accounts

#34034 fix: adds label for unified swap token approvals
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#34037 release: add CHANGELOG to pull-request-template.md
  .github/pull-request-template.md
  .github/scripts/shared/template.ts
Labels: team-extension-platform, no-changelog

#34044 fix: hides bridge button on non-native asset page if unified is enabled
  ui/pages/asset/components/token-buttons.tsx
Labels: team-swaps-and-bridge

#34007 test: Migrate request queuing switch network test to Typescript and POM
  test/e2e/tests/request-queuing/switch-network.spec.js
  test/e2e/tests/request-queuing/switch-network.spec.ts
Labels: team-qa

#33415 feat: 2.5 password-change syncing across multiple devices
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  test/e2e/page-objects/pages/settings/change-password-page.ts
  test/e2e/page-objects/pages/settings/privacy-settings.ts
  test/e2e/tests/settings/change-password.spec.ts
  ui/components/app/password-outdated-modal/index.ts
  ui/components/app/password-outdated-modal/password-outdated-modal.stories.tsx
  ui/components/app/password-outdated-modal/password-outdated-modal.tsx
  ui/components/app/toast-master/toast-master.js
  ui/constants/index.js
  ui/ducks/metamask/metamask.js
  ui/index.js
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/keychains/restore-vault.js
  ui/pages/multi-srp/import-srp/import-srp.tsx
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/change-password/change-password-warning.tsx
  ui/pages/settings/security-tab/change-password/change-password.test.tsx
  ui/pages/settings/security-tab/change-password/change-password.tsx
  ui/pages/settings/security-tab/index.scss
  ui/pages/settings/security-tab/reveal-srp-list/reveal-srp-list.test.tsx
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
  ui/pages/unlock-page/unlock-page.component.js
  ui/pages/unlock-page/unlock-page.container.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: area-onboarding, QA Passed, INVALID-PR-TEMPLATE, team-web3auth

#34002 feat: add e2e tests for Ledger personal sign functionality
  test/e2e/tests/hardware-wallets/ledger-personal-sign.spec.ts
  test/stub/keyring-bridge.js
Labels: team-hardware-wallets, e2e-test

#34045 fix: cp-12.22.0 regression of lanchdarkly flag key
  ui/components/multichain/carousel/carousel.tsx
Labels: team-phosphor, release-12.22.0

#33581 fix: 33510 solve `Error: Ledger: Unknown error while signing transaction`
  app/scripts/lib/offscreen-bridge/ledger-offscreen-bridge.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  offscreen/scripts/ledger.ts
  package.json
  types/global.d.ts
  yarn.lock
Labels: Sev2-normal, QA Passed, needs-dev-review, team-hardware-wallets, regression-main

#33864 chore: Enable Arbitrum for smart transactions
  package.json
  shared/constants/smartTransactions.test.ts
  shared/constants/smartTransactions.ts
  ui/pages/confirmations/hooks/useSmartTransactionFeatureFlags.test.ts
  yarn.lock
Labels: team-transactions

#34051 test: Fix flaky test Carousel component e2e tests should handle slide dismissal
  test/e2e/tests/carousel/carousel.spec.ts
Labels: e2e-test, flaky tests, team-qa, no-changelog

#34050 fix: error logic for importing private keys
  ui/components/multichain/import-account/private-key.js
Labels: team-accounts

#34053 fix: bitcoin account synchronization when no history
  app/scripts/metamask-controller.js
  package.json
  ui/hooks/accounts/useMultichainWalletSnapClient.ts
  yarn.lock
Labels: team-new-networks, no-changelog

#34072 feat: enable apple login
  app/scripts/services/oauth/constants.ts
  ui/pages/onboarding-flow/welcome/login-options.tsx
Labels: team-web3auth

#34030 feat: add support to access the private key from account details
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain-accounts/account-show-private-key-row/account-show-private-key-row.stories.tsx
  ui/components/multichain-accounts/account-show-private-key-row/account-show-private-key-row.test.tsx
  ui/components/multichain-accounts/account-show-private-key-row/account-show-private-key-row.tsx
  ui/components/multichain-accounts/account-show-private-key-row/index.ts
  ui/pages/multichain-accounts/account-details/evm-account-details.tsx
  ui/pages/multichain-accounts/account-details/private-key-account-details.tsx
Labels: team-accounts

#34081 test: fix flaky test Test Survey should show 2 surveys, and then none
  test/e2e/page-objects/pages/home/homepage.ts
  test/e2e/tests/survey/survey.spec.ts
Labels: e2e-test, flaky tests, team-qa, no-changelog

#34013 feat: replace reveal srp modal with reveal srp page cp-12.23.0
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  test/e2e/page-objects/pages/onboarding/secure-wallet-page.ts
  ui/components/app/recovery-phrase-reminder/recovery-phrase-reminder.js
  ui/components/app/reveal-SRP-modal/index.js
  ui/components/app/reveal-SRP-modal/reveal-SRP-modal.js
  ui/helpers/constants/routes.ts
  ui/pages/onboarding-flow/index.scss
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/recovery-phrase/confirm-recovery-phrase.js
  ui/pages/onboarding-flow/recovery-phrase/index.scss
  ui/pages/onboarding-flow/recovery-phrase/reveal-recovery-phrase.tsx
  ui/pages/onboarding-flow/recovery-phrase/review-recovery-phrase.js
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.js
  ui/store/actions.ts
Labels: QA Passed, team-web3auth

#34078 chore: bump `@metamask/profile-sync-controller` to `^20.0.0`
  package.json
  yarn.lock
Labels: team-identity

#34096 release: Master sync v12.22.0 into main
  .prettierignore
  CHANGELOG.md
  docs/CHANGELOG_OLDER.md
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#34003 feat: ledger erc721 e2e tests
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data.spec.ts
  test/e2e/tests/hardware-wallets/ledger-erc721.spec.ts
Labels: INVALID-PR-TEMPLATE, team-hardware-wallets

#34128 fix: flaky test `Confirmation Redesign Native Send Wallet initiated Sends a type 0 transaction (Legacy)`
  test/e2e/tests/confirmations/transactions/erc1155-set-approval-for-all-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc20-token-send-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc721-set-approval-for-all-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/native-send-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/nft-token-send-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/shared.ts
Labels: flaky tests, team-qa, no-changelog

#32058 refactor(23528): add TODO for linting `@typescript-eslint/restrict-template-expressions`
  .eslintrc.js
  app/scripts/controllers/metametrics-controller.ts
  app/scripts/lib/ppom/indexed-db-backend.ts
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/migrations/094.ts
  app/scripts/migrations/120.2.ts
  app/scripts/migrations/120.5.ts
  app/scripts/migrations/133.1.ts
  app/scripts/services/oauth/create-login-handler.ts
  app/scripts/streams/cookie-handler-stream.ts
  app/scripts/streams/phishing-stream.ts
  app/scripts/streams/provider-stream.ts
  development/metamaskbot-build-announce.ts
  development/ts-migration-dashboard/common/build-module-partitions.ts
  development/ts-migration-dashboard/scripts/build-app.ts
  shared/lib/delegation/caveatBuilder/multiTokenPeriod.ts
  shared/modules/i18n.ts
  test/e2e/flask/multichain-api/evm/wallet_createSession.spec.ts
  test/e2e/flask/multichain-api/evm/wallet_sessionChanged.spec.ts
  test/e2e/page-objects/pages/permission/site-permission-page.ts
  test/e2e/page-objects/pages/settings/notifications-settings-page.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  test/e2e/tests/deep-link/deep-link.spec.ts
  test/helpers/env.ts
  ui/components/app/assets/nfts/nft-details/nft-details.tsx
  ui/components/app/multichain-bridge-transaction-list-item/multichain-bridge-transaction-list-item.tsx
  ui/components/app/snaps/snap-ui-renderer/components/footer.ts
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/component-library/box/box.tsx
  ui/components/component-library/text/text.tsx
  ui/components/multichain/pages/connections/connections.tsx
  ui/components/multichain/pages/review-permissions-page/review-permissions-page.tsx
  ui/ducks/bridge/utils.ts
  ui/ducks/send/swap-and-send-utils.ts
  ui/helpers/utils/notification.util.ts
  ui/pages/asset/components/chart/asset-chart.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/confirmations/components/simulation-details/useBalanceChanges.ts
  ui/pages/confirmations/utils/confirm.ts
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.tsx
  ui/store/actions.ts
Labels: team-extension-platform, no-changelog

#34059 test: Migrate nft and network e2e tests to Page object modal
  test/e2e/page-objects/pages/asset-picker.ts
  test/e2e/tests/multichain/asset-picker-send.spec.ts
  test/e2e/tests/solana/solana-networks.spec.ts
  test/e2e/tests/tokens/nft/send-nft.spec.ts
Labels: e2e-test, team-qa, no-changelog

#33751 feat: Network Manager cleanup
  app/scripts/controllers/network-order.ts
  app/scripts/metamask-controller.js
  app/scripts/migrations/171.test.ts
  app/scripts/migrations/171.ts
  app/scripts/migrations/index.js
  test/e2e/page-objects/flows/network.flow.ts
  test/e2e/page-objects/pages/network-manager.ts
  test/e2e/tests/network/network-connection.spec.ts
  test/e2e/tests/network/network-manager.spec.ts
  test/e2e/tests/request-queuing/dapp1-switch-dapp2-send.spec.js
  test/e2e/tests/request-queuing/ui.spec.js
  test/e2e/tests/responsive-ui/metamask-responsive-ui.spec.ts
  test/e2e/tests/tokens/defi/view-defi-details.spec.ts
  test/e2e/tests/tokens/defi/view-defi-no-positions-message.spec.ts
  test/e2e/tests/tokens/nft/filter-nfts.spec.ts
  test/e2e/tests/tokens/nft/remove-erc1155.spec.ts
  test/e2e/tests/tokens/nft/send-nft.spec.ts
  test/e2e/tests/tokens/nft/view-nft-full-image.spec.ts
  test/integration/defi/defi-positions.test.tsx
  test/integration/nfts/nfts.test.tsx
  ui/components/app/transaction-list/index.scss
  ui/components/app/wallet-overview/aggregated-percentage-overview-cross-chains.tsx
  ui/components/multichain/network-manager/components/additional-networks-info/additional-networks-info.test.tsx
  ui/components/multichain/network-manager/components/additional-networks-info/additional-networks-info.tsx
  ui/components/multichain/network-manager/components/custom-networks/custom-networks.tsx
  ui/components/multichain/network-manager/components/default-networks/default-networks.tsx
  ui/components/multichain/network-manager/hooks/useNetworkChangeHandlers.ts
  ui/components/multichain/network-manager/hooks/useNetworkManagerState.ts
  ui/components/multichain/network-manager/index.scss
  ui/components/multichain/network-manager/network-manager.test.tsx
  ui/components/multichain/network-manager/network-manager.tsx
  ui/hooks/useAccountTotalCrossChainFiatBalance.test.ts
  ui/hooks/useAccountTotalCrossChainFiatBalance.ts
  ui/pages/settings/networks-tab/networks-form/networks-form.tsx
  ui/selectors/selectors.js
Labels: team-assets, Remove GNS

#34149 fix: cp-12.23.0 feature flag enabled networks on transaction history filter
  ui/components/app/transaction-list/transaction-list.component.js
Labels: team-assets

#34164 release(cp): use activeQuote amounts when displaying approval banners cp-12.22.1
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#34130 fix: remove back button on Wallet already exist and Wallet not found pages
  ui/pages/onboarding-flow/account-exist/account-exist.tsx
  ui/pages/onboarding-flow/account-not-found/account-not-found.tsx
Labels: area-onboarding, QA Passed, team-web3auth

#34151 fix: ignore LD flag when hiding snap confirmation page cp-12.23.0
  .yarn/patches/@metamask-bridge-status-controller-npm-34.0.0-0b1d95ade1.patch
  package.json
  ui/ducks/bridge/selectors.ts
  ui/pages/bridge/hooks/useSnapConfirmation.ts
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  yarn.lock
Labels: team-swaps-and-bridge

#34176 feat: authenticate users if basic functionality is enabled
  ui/hooks/identity/useAuthentication/useAutoSignIn.test.tsx
  ui/hooks/identity/useAuthentication/useAutoSignIn.ts
Labels: team-identity

#34171 feat: update ledger ERC20 e2e test to full test suite
  test/e2e/page-objects/pages/confirmations/legacy/watch-asset-confirmation.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/hardware-wallets/ledger-erc20.spec.ts
Labels: team-hardware-wallets, e2e-test

#34161 release: 12.22.1
  CHANGELOG.md
  package.json
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#33802 feat: disable enforced simulations
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/constants/sentry-state.ts
  app/scripts/controller-init/messengers/transaction-controller-messenger.ts
  app/scripts/controllers/app-state-controller.test.ts
  app/scripts/controllers/app-state-controller.ts
  app/scripts/lib/transaction/containers/enforced-simulations.ts
  app/scripts/lib/transaction/containers/util.test.ts
  app/scripts/lib/transaction/containers/util.ts
  app/scripts/lib/transaction/hooks/enforce-simulation-hook.test.ts
  app/scripts/lib/transaction/hooks/enforce-simulation-hook.ts
  app/scripts/metamask-controller.js
  shared/types/background.ts
  test/data/confirmations/contract-interaction.ts
  test/data/mock-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/integration/data/onboarding-completion-route.json
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/base-transaction-info/__snapshots__/base-transaction-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
  ui/pages/confirmations/components/modals/simulation-settings-modal/simulation-settings-modal.stories.tsx
  ui/pages/confirmations/components/modals/simulation-settings-modal/simulation-settings-modal.test.tsx
  ui/pages/confirmations/components/modals/simulation-settings-modal/simulation-settings-modal.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
  ui/pages/confirmations/hooks/transactions/useIsEnforcedSimulationsSupported.test.ts
  ui/pages/confirmations/hooks/transactions/useIsEnforcedSimulationsSupported.ts
  ui/pages/confirmations/selectors/confirm.test.ts
  ui/pages/confirmations/selectors/confirm.ts
  ui/pages/confirmations/types/confirm.ts
  ui/store/actions.ts
Labels: team-confirmations

#34175 fix: Use transaction request network chainId for PPOM Validation
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-confirmations

#34179 fix: account list agg balance
  ui/hooks/useAccountTotalCrossChainFiatBalance.test.ts
  ui/hooks/useAccountTotalCrossChainFiatBalance.ts
  ui/selectors/selectors.js
Labels: team-assets

#34084 fix: cp-12.23.0 UI fixes in upgrade account page
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/metamask-controller.js
  app/scripts/migrations/172.test.ts
  app/scripts/migrations/172.ts
  app/scripts/migrations/index.js
  ui/components/multichain/account-overview/account-overview-layout.tsx
  ui/pages/confirmations/components/confirm/account-selection/account-selection.scss
  ui/pages/confirmations/components/confirm/account-selection/account-selection.test.tsx
  ui/pages/confirmations/components/confirm/account-selection/account-selection.tsx
  ui/pages/confirmations/components/confirm/account-selection/index.ts
  ui/pages/confirmations/components/confirm/smart-account-update-content/index.ts
  ui/pages/confirmations/components/confirm/smart-account-update-content/smart-account-update-content.scss
  ui/pages/confirmations/components/confirm/smart-account-update-content/smart-account-update-content.tsx
  ui/pages/confirmations/components/confirm/smart-account-update/smart-account-update-success.test.tsx
  ui/pages/confirmations/components/confirm/smart-account-update/smart-account-update-success.tsx
  ui/pages/confirmations/components/confirm/smart-account-update/smart-account-update.scss
  ui/pages/confirmations/components/confirm/smart-account-update/smart-account-update.test.tsx
  ui/pages/confirmations/components/confirm/smart-account-update/smart-account-update.tsx
  ui/pages/confirmations/components/confirm/splash/smart-account-update-splash/smart-account-update-splash.scss
  ui/pages/confirmations/components/confirm/splash/smart-account-update-splash/smart-account-update-splash.test.tsx
  ui/pages/confirmations/components/confirm/splash/smart-account-update-splash/smart-account-update-splash.tsx
  ui/pages/confirmations/components/index.scss
  ui/pages/confirmations/selectors/preferences.ts
  ui/store/actions.ts
Labels: team-confirmations

#34193 fix: flaky test `Transfer custom tokens Confirmation Screens - (Redesigned) transfer custom tokens from dapp customizing gas values`
  test/e2e/tests/tokens/custom-token-send-transfer.spec.ts
Labels: flaky tests, team-qa

#34207 ci: remove circleci
  .circleci/config.yml
  .github/CODEOWNERS
Labels: team-extension-platform, no-changelog

#30170 feat: implement tailwind css and design system libraries in the extension
  .github/CODEOWNERS
  .storybook/main.js
  development/build/styles.js
  development/ts-migration-dashboard/app/index.scss
  development/webpack/webpack.config.ts
  development/webpack/webpack.integration.tests.config.ts
  lavamoat/build-system/policy.json
  package.json
  tailwind.config.js
  ui/css/index.scss
  ui/css/reset.scss
  ui/css/tailwind.css
  ui/pages/design-system/design-system.stories.tsx
  yarn.lock
Labels: team-design-system

#34049 chore: Smart Transactions refactoring
  .github/CODEOWNERS
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/smart-transactions-controller-messenger.ts
  app/scripts/controller-init/smart-transactions/smart-transactions-controller-init.test.ts
  app/scripts/controller-init/smart-transactions/smart-transactions-controller-init.ts
  app/scripts/lib/smart-transaction/smart-transactions-mocks.ts
  app/scripts/lib/smart-transaction/smart-transactions.test.ts
  app/scripts/lib/smart-transaction/smart-transactions.ts
  app/scripts/metamask-controller.js
  shared/modules/selectors/feature-flags.ts
Labels: team-transactions, no-changelog

#34228 fix: Fixing migration to be cherry-picked into version 12.23.0
  app/scripts/migrations/170.1.test.ts
  app/scripts/migrations/170.1.ts
  app/scripts/migrations/index.js
Labels: team-confirmations

#34260 ci: skip broken seedless onboarding tests
  test/e2e/tests/onboarding/seedless-onboarding.spec.ts
Labels: team-extension-platform

#34035 fix(deeplinks): change from using `value` param to `amount` for swaps/bridge
  shared/lib/deep-links/routes/swap.ts
Labels: team-extension-platform

#34255 fix: cp-12.22.2 Fix crash on older browser versions
  app/scripts/app-init.js
  app/scripts/background.js
  app/scripts/lib/operation-safener.ts
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.test.ts
  app/scripts/lib/util.test.js
  app/scripts/metamask-controller.test.js
  app/scripts/ui.js
  development/webpack/test/loaders.codeFenceLoader.test.ts
  development/webpack/test/loaders.swcLoader.test.ts
  shared/lib/promise-with-resolvers.ts
  types/global.d.ts
Labels: team-wallet-framework

#34230 fix: use primary and secondary variants cp-12.23.0
  ui/pages/onboarding-flow/welcome/index.scss
  ui/pages/onboarding-flow/welcome/welcome-banner.tsx
  ui/pages/onboarding-flow/welcome/welcome-login.tsx
Labels: area-onboarding, QA Passed, team-web3auth

#34177 fix: resume metametrics if not set yet when closing/opening app during onboarding cp-12.23.0
  ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js
  ui/selectors/metametrics.js
Labels: area-onboarding, team-web3auth

#34225 fix: set confirm srp quiz word to readonly cp-12.23.0
  ui/pages/onboarding-flow/recovery-phrase/__snapshots__/recovery-phrase-chips.test.js.snap
  ui/pages/onboarding-flow/recovery-phrase/recovery-phrase-chips.js
Labels: team-web3auth

#34032 chore: bump @metamask/profile-sync-controller to ^21.0.0
  app/scripts/controller-init/identity/user-storage-controller-init.test.ts
  app/scripts/controller-init/identity/user-storage-controller-init.ts
  app/scripts/controller-init/messengers/identity/user-storage-controller-messenger.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  shared/lib/trace.ts
  shared/types/background.ts
  test/e2e/helpers/identity/user-storage/generateEncryptedData.ts
  test/e2e/helpers/identity/user-storage/userStorageMockttpController.ts
  test/e2e/tests/identity/mocks.ts
  yarn.lock
Labels: QA Passed, INVALID-PR-TEMPLATE, team-identity

#34269 fix: Log warning instead of capturing exception in migration 165
  app/scripts/migrations/165.test.ts
  app/scripts/migrations/165.ts
Labels: team-snaps-platform, no-changelog

#34273 fix: show avatar account on all screens except header
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/account-picker.test.tsx.snap
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#34257 fix: prevent swapping between native assets cp-12.23.0
  shared/constants/bridge.ts
  test/e2e/tests/metrics/bridge.spec.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/bridge.ts
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
  ui/ducks/bridge/types.ts
  ui/hooks/bridge/useTokenAlerts.test.ts
  ui/pages/bridge/prepare/__snapshots__/bridge-cta-button.test.tsx.snap
  ui/pages/bridge/prepare/bridge-cta-button.test.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#34281 fix: bump @metamask/solana-wallet-standard to 0.5.1
  package.json
  yarn.lock
Labels: team-wallet-standard

#34258 release: 12.22.2
  CHANGELOG.md
  app/scripts/app-init.js
  app/scripts/background.js
  app/scripts/lib/operation-safener.ts
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.test.ts
  app/scripts/lib/util.test.js
  app/scripts/ui.js
  development/webpack/test/loaders.codeFenceLoader.test.ts
  development/webpack/test/loaders.swcLoader.test.ts
  package.json
  shared/lib/promise-with-resolvers.ts
  types/global.d.ts
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#34265 chore: removed live network requests from seedless onboarding e2e tests
  app/scripts/services/oauth/web-authenticator-factory.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/constants.ts
  test/e2e/helpers/seedless-onboarding/constants.ts
  test/e2e/helpers/seedless-onboarding/data.ts
  test/e2e/helpers/seedless-onboarding/mock-web-authenticator.ts
  test/e2e/helpers/seedless-onboarding/mocks.ts
  test/e2e/helpers/seedless-onboarding/types.ts
  test/e2e/mock-e2e-allowlist.js
  test/e2e/tests/onboarding/seedless-onboarding.spec.ts
  test/e2e/tests/settings/change-password.spec.ts
  ui/store/actions.ts
  yarn.lock
Labels: e2e-test, flaky tests, team-web3auth

#34247 fix: render add account button only for hd wallets
  ui/components/multichain/multi-srp/srp-list/srp-list-item.tsx
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.tsx
Labels: team-accounts, INVALID-PR-TEMPLATE, no-changelog

#34263 fix: Localize message for NetworkManager
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain/network-manager/components/default-networks/default-networks.tsx
Labels: team-wallet-ux

#33829 feat: dapp scanning enabled on transactions and signatures
  app/scripts/lib/trust-signals/trust-signals-middleware.test.ts
  app/scripts/lib/trust-signals/trust-signals-middleware.ts
Labels: INVALID-PR-TEMPLATE, team-product-safety

#34293 fix: removes max button for native assets for now
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#34224 fix: overwrite eth token logo
  ui/components/app/assets/util/extractIconAndSymbol.ts
  ui/components/app/assets/util/getTokenAvatarUrl.test.ts
  ui/components/app/assets/util/getTokenAvatarUrl.ts
  ui/pages/defi/components/defi-details-list.tsx
Labels: team-assets

#34319 release: cp-12.23.0 bump multichain-api-client to 0.5.1
  package.json
  yarn.lock
Labels: team-wallet-standard, release-12.23.0

#34297 release: master sync to 12.23.0 from 12.22.2
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery

#34292 release: Master sync v12.22.2 to Main
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#34320 fix: (dev-only) ensure NetworkOrderController isn't reset when extension is reloaded
  app/scripts/metamask-controller.js
Labels: team-assets

#34329 release: categorize unsorted changes in CHANGELOG.md
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery

#33974 feat: adds trust signals to ConfirmInfoRowUrl w/ alerts
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/lib/state-utils.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/errors.spec.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/integration/confirmations/transactions/alerts.test.tsx
  ui/components/app/confirm/info/row/__snapshots__/url.test.tsx.snap
  ui/components/app/confirm/info/row/url.test.tsx
  ui/components/app/confirm/info/row/url.tsx
  ui/hooks/useOriginTrustSignals.test.ts
  ui/hooks/useOriginTrustSignals.ts
  ui/pages/confirmations/hooks/alerts/useAddressTrustSignalAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/useAddressTrustSignalAlerts.ts
  ui/pages/confirmations/hooks/alerts/useOriginTrustSignalAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/useOriginTrustSignalAlerts.ts
  ui/pages/confirmations/hooks/useConfirmationAlerts.ts
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: INVALID-PR-TEMPLATE, team-product-safety

#34313 feat: Separate `Development` and `QA (dist)` enviroments for Social Login
  .github/workflows/run-build.yml
  app/scripts/services/oauth/config.ts
  app/scripts/services/oauth/constants.ts
  app/scripts/services/oauth/oauth-service.test.ts
  app/scripts/services/oauth/oauth-service.ts
  app/scripts/services/oauth/types.ts
  builds.yml
  development/build/set-environment-variables.js
Labels: team-web3auth

#34229 fix: cp-12.23.0 no positions wording update
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/page-objects/pages/defi-tab.ts
  test/e2e/tests/tokens/defi/view-defi-no-positions-message.spec.ts
  ui/components/app/assets/defi-list/cells/defi-empty-state.tsx
  ui/components/app/assets/defi-list/defi-list.test.tsx
  ui/components/app/assets/defi-list/defi-list.tsx
  ui/components/app/assets/defi-list/defi-tab.test.tsx
Labels: team-assets

#34248 fix: ensure network deselect updates the underlying network controller to an enabled network
  app/scripts/controllers/network-order.test.ts
  app/scripts/controllers/network-order.ts
  test/e2e/tests/request-queuing/dapp1-switch-dapp2-send.spec.js
  test/e2e/tests/tokens/nft/send-nft.spec.ts
  ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx
Labels: team-assets

#34335 cherry-pick fix: cp-12.23.0 max button removal for native token in bridge experience
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#34309 fix: ellipses on long label names in destination acct picker
  ui/pages/bridge/prepare/components/destination-account-list-item.tsx
  ui/pages/bridge/prepare/components/destination-account-picker.tsx
  ui/pages/bridge/prepare/components/destination-selected-account-list-item.tsx
Labels: team-swaps-and-bridge

#34271 test: added new address book test
  test/e2e/page-objects/pages/settings/contacts-settings.ts
  test/e2e/tests/identity/contact-syncing/sync-existing-user.spec.ts
  test/e2e/tests/settings/address-book.spec.ts
  ui/pages/settings/contact-list-tab/add-contact/add-contact.component.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#34290 chore: remove Unified swaps legacy and portfolio fallbacks
  test/e2e/tests/bridge/bridge-button-opens-portfolio.spec.ts
  test/e2e/tests/bridge/bridge-button-routing.spec.ts
  test/e2e/tests/bridge/bridge-test-utils.ts
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/multichain/account-overview/account-overview-layout.tsx
  ui/hooks/bridge/useBridging.test.ts
  ui/hooks/bridge/useBridging.ts
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/bridge/index.tsx
Labels: team-swaps-and-bridge

#34252 fix: Remove switched network toast
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/app-state-controller.ts
  app/scripts/metamask-controller.js
  docs/confirmation-refactoring/signature-request/footer.png
  docs/confirmation-refactoring/signature-request/signature_request_old.png
  docs/load-dev-build-chrome.gif
  shared/types/background.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/request-queuing/ui.spec.js
  test/integration/data/integration-init-state.json
  test/integration/data/onboarding-completion-route.json
  ui/components/app/assets/nfts/nft-details/nft-details.tsx
  ui/components/app/toast-master/selectors.ts
  ui/components/app/toast-master/toast-master.js
  ui/components/app/toast-master/utils.ts
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/index.js
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: team-wallet-ux

#34308 fix: Display testnets for development mode
  ui/components/multichain/network-manager/components/custom-networks/custom-networks.tsx
Labels: team-wallet-ux

#34348 fix: cp-12.23.0 migrate BSC network RPC from bsc-dataseed.binance.org to bsc infura (#33997) - cherry-pick
  app/scripts/lib/network-controller/utils.test.ts
  app/scripts/migrations/170.2.test.ts
  app/scripts/migrations/170.2.ts
  app/scripts/migrations/index.js
  builds.yml
  development/build/config.js
  shared/constants/network.test.ts
  shared/constants/network.ts
Labels: team-extension-platform, extension-delivery

#33673 feat: add metamask mobile slide and modal
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/images/download-mobile-app-qr-code.png
  app/images/slide-metamask-icon.svg
  app/scripts/controllers/app-state-controller.ts
  app/scripts/metamask-controller.js
  shared/constants/app.ts
  shared/types/background.ts
  test/e2e/mock-e2e.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/settings/change-password.spec.ts
  ui/components/app/download-mobile-modal/download-mobile-modal.stories.tsx
  ui/components/app/download-mobile-modal/download-mobile-modal.tsx
  ui/components/app/download-mobile-modal/index.ts
  ui/components/multichain/account-overview/account-overview-layout.tsx
  ui/components/multichain/carousel/constants.ts
  ui/hooks/useCarouselManagement/constants.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.test.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.ts
  ui/selectors/selectors.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: area-onboarding, INVALID-PR-TEMPLATE, team-web3auth

#34226 fix: Multi srp sync loading remove
  ui/components/multichain/account-menu/account-menu.tsx
  ui/components/multichain/multi-srp/srp-list/srp-list.tsx
  ui/pages/settings/security-tab/reveal-srp-list/reveal-srp-list.tsx
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: area-accounts, area-settings, QA Passed, team-web3auth

#34311 feat: 2.10 handle private key sync restore and sync srp
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: area-accounts, area-settings, QA Passed, team-web3auth

#34206 refactor(identity): lighter backup-and-sync E2E test suite
  test/e2e/fixture-builder.js
  test/e2e/tests/identity/account-syncing/account-syncing-settings-toggle.spec.ts
  test/e2e/tests/identity/account-syncing/adding-and-renaming-accounts.spec.ts
  test/e2e/tests/identity/account-syncing/backup-and-sync-settings.spec.ts
  test/e2e/tests/identity/account-syncing/balances.spec.ts
  test/e2e/tests/identity/account-syncing/helpers.ts
  test/e2e/tests/identity/account-syncing/imported-accounts.spec.ts
  test/e2e/tests/identity/account-syncing/importing-private-key-account.spec.ts
  test/e2e/tests/identity/account-syncing/mock-data.ts
  test/e2e/tests/identity/account-syncing/multi-srp.spec.ts
  test/e2e/tests/identity/account-syncing/new-user-sync.spec.ts
  test/e2e/tests/identity/account-syncing/onboarding-with-opt-out.spec.ts
  test/e2e/tests/identity/account-syncing/sync-after-adding-account.spec.ts
  test/e2e/tests/identity/account-syncing/sync-after-modifying-account-name.spec.ts
  test/e2e/tests/identity/account-syncing/sync-after-onboarding.spec.ts
  test/e2e/tests/identity/account-syncing/sync-with-account-balances.spec.ts
  test/e2e/tests/identity/account-syncing/sync-with-multi-srp.spec.ts
  test/e2e/tests/identity/contact-syncing/backup-and-sync-settings.spec.ts
  test/e2e/tests/identity/contact-syncing/sync-existing-user.spec.ts
  test/e2e/tests/identity/contact-syncing/sync-new-user.spec.ts
  test/e2e/tests/notifications/enable-notifications-with-accounts-sync.spec.ts
  test/e2e/tests/notifications/enable-notifications.spec.ts
  test/e2e/tests/notifications/mocks.ts
Labels: team-identity

#34338 release: update 12.23.0 changelog
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery

#34272 test: Migrate request queuing sendTx-switchChain-sendTx test to Typescript and POM
  test/e2e/tests/request-queuing/sendTx-switchChain-sendTx.spec.js
  test/e2e/tests/request-queuing/sendTx-switchChain-sendTx.spec.ts
Labels: team-qa

#34330 test: Send Page e2e for send network switcher
  test/e2e/page-objects/pages/send/send-token-page.ts
  test/e2e/tests/send/send-network-change.spec.ts
  ui/ducks/send/send.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#34354 fix: fix token details percentage
  ui/pages/asset/components/asset-page.tsx
  ui/pages/asset/components/chart/asset-chart-price.tsx
  ui/pages/asset/components/chart/asset-chart.tsx
Labels: team-assets

#34356 fix: added toast and removed focused state
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/app/toast-master/selectors.ts
  ui/components/app/toast-master/toast-master.js
  ui/components/app/toast-master/toast-master.test.ts
  ui/components/app/toast-master/utils.ts
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
  ui/ducks/app/app.ts
  ui/store/actionConstants.ts
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#34307 fix: Show contacts for all chains
  ui/components/app/contact-list/recipient-group/recipient-group.component.js
  ui/components/multichain/pages/send/components/address-book.tsx
Labels: team-wallet-ux

#34350 fix: password form terms social and srp
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/app/password-form/password-form.tsx
  ui/pages/onboarding-flow/create-password/__snapshots__/create-password.test.js.snap
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/settings/security-tab/change-password/change-password.tsx
Labels: team-web3auth

#34345 feat(INFRA-2772): add failure notifications for nightly build failures
  .github/scripts/post-nightly-builds.ts
  .github/workflows/nightly-build.yml
Labels: INVALID-PR-TEMPLATE, team-dev-ops, no-changelog

#34240 feat: 2.13 SeedlessOnboardingController 2.2.0 update
  app/scripts/controller-init/seedless-onboarding/seedless-onboarding-controller-init.ts
  app/scripts/controller-init/types.ts
  app/scripts/services/oauth/config.ts
  app/scripts/services/oauth/oauth-service.ts
  app/scripts/services/oauth/types.ts
  development/build/config.js
  development/build/set-environment-variables.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/helpers/seedless-onboarding/mocks.ts
  yarn.lock
Labels: team-web3auth

#34369 release: master sync to from 12.23.0
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery

#34259 feat: support swap deep links cp-13.0.0
  shared/lib/asset-utils.test.ts
  shared/lib/asset-utils.ts
  shared/lib/deep-links/routes/swap.ts
  test/lib/render-helpers.js
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/bridge.ts
  ui/ducks/bridge/utils.ts
  ui/hooks/bridge/__snapshots__/useBridgeQueryParams.test.ts.snap
  ui/hooks/bridge/useBridgeExchangeRates.ts
  ui/hooks/bridge/useBridgeQueryParams.test.ts
  ui/hooks/bridge/useBridgeQueryParams.ts
  ui/hooks/bridge/useBridging.test.ts
  ui/hooks/bridge/useBridging.ts
  ui/hooks/bridge/useLatestBalance.ts
  ui/hooks/bridge/useTokenAlerts.ts
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/bridge/hooks/useIsMultichainSwap.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-swaps-and-bridge

#34280 fix: use button for quiz words instead of text-field cp-13.0.0
  ui/pages/onboarding-flow/recovery-phrase/__snapshots__/recovery-phrase-chips.test.js.snap
  ui/pages/onboarding-flow/recovery-phrase/__snapshots__/review-recovery-phrase.test.js.snap
  ui/pages/onboarding-flow/recovery-phrase/recovery-phrase-chips.js
Labels: area-onboarding, team-web3auth

#34391 fix: Apple login cp-13.0.0
  app/scripts/services/oauth/apple-login-handler.ts
  ui/store/actions.ts
Labels: team-web3auth

#34389 fix: reset parsed search params after setting quote request inputs cp-13.0.0
  ui/hooks/bridge/__snapshots__/useBridgeQueryParams.test.ts.snap
  ui/hooks/bridge/useBridgeQueryParams.test.ts
  ui/hooks/bridge/useBridgeQueryParams.ts
Labels: team-swaps-and-bridge

#34401 release: update changelog
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery

#34374 fix: remove loading spinner from create ethereum account flow
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.test.tsx
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.tsx
  ui/store/actions.ts
Labels: team-accounts, INVALID-PR-TEMPLATE, no-changelog

#34381 fix: update address qr code navigation to prevent infinite loop of navigation
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.test.tsx
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.tsx
Labels: team-accounts, INVALID-PR-TEMPLATE, no-changelog

#34377 fix: update explorer button text in address qr code page to reflect the network's explorer name
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  test/e2e/tests/multichain-accounts/account-details.spec.ts
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.test.tsx
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.tsx
Labels: team-accounts, INVALID-PR-TEMPLATE, no-changelog

#34384 chore: upgrade @metamask/design-tokens to v8.1.0
  package.json
  ui/components/multichain-accounts/smart-contract-account-toggle-section/__snapshots__/smart-contract-account-toggle-section.test.tsx.snap
  ui/components/multichain-accounts/smart-contract-account-toggle/__snapshots__/smart-contract-account-toggle.test.tsx.snap
  ui/components/multichain/network-list-menu/__snapshots__/network-list-menu.test.js.snap
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  yarn.lock
Labels: type-enhancement, area-UI, dependencies, team-design-system

#34429 feat: enable SeedlessOnboarding feature cp-13.0.0
  .github/workflows/run-build.yml
  builds.yml
  test/e2e/vault-decryption-chrome.spec.ts
Labels: team-web3auth

#34376 fix: cp-13.0.0 ensure we enable any missing networks when performing swap/bridge.
  test/e2e/tests/bridge/bridge-positive-cases.spec.ts
  ui/pages/bridge/prepare/prepare-bridge-page.test.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-assets

#34400 fix: check password outdated before import private key cp-13.0.0
  ui/components/multichain/import-account/import-account.js
Labels: area-settings, QA Passed, team-web3auth

#34403 fix: handle keyring remove when import srp seedless error cp-13.0.0
  app/scripts/metamask-controller.js
Labels: area-settings, no-changelog, team-web3auth

#34355 fix: infinite loading on spending cap when selected chain differs from dapp cp-12.22.3
  ui/ducks/metamask/metamask.js
  ui/ducks/metamask/metamask.test.js
  ui/helpers/utils/token-util.js
  ui/helpers/utils/token-util.test.js
  ui/pages/confirmations/hooks/useAssetDetails.js
Labels: team-confirmations

#34438 fix: check if metametrics is done before redirecting to page on social cp-13.0.0
  ui/selectors/first-time-flow.js
Labels: area-onboarding, team-web3auth

#34480 chore: Update `form-data` to address advisory
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy.json
  yarn.lock
Labels: team-wallet-framework

#34152 chore: Improve performance of address formatting/validation
  .yarn/patches/lodash-npm-4.17.21-6382451519.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: team-wallet-framework

#34346 fix: make bg color on the loading screen in popup match bg of app
  ui/css/base-styles.scss
Labels: team-extension-platform

#34441 fix: outdated pwd error cp-13.0.0
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
Labels: area-onboarding, team-web3auth

#34474 fix: cp-12.22.3 Stop polling multichain rates while idle
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-wallet-framework

#34506 fix: Prevent redundant persist store updates
  app/scripts/lib/ComposableObservableStore.js
  app/scripts/lib/ComposableObservableStore.test.js
  app/scripts/metamask-controller.test.js
Labels: team-wallet-framework, needs-dev-review

#34477 fix: show tx alert when simulation error is ResultWithNegativeLamports
  shared/modules/bridge-utils/security-alerts-api.util.ts
Labels: team-swaps-and-bridge

#34505 feat: Onboarding Unlock page update cp-13.0.0
  ui/pages/onboarding-flow/metametrics/metametrics.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.test.js
  ui/pages/unlock-page/__snapshots__/unlock-page.test.js.snap
  ui/pages/unlock-page/unlock-page.component.js
  ui/pages/unlock-page/unlock-page.container.js
  ui/pages/unlock-page/unlock-page.test.js
Labels: team-web3auth

#34513 chore: Update `form-data` to address advisory (#34480)
  attribution.txt
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/build-system/policy.json
  yarn.lock
Labels: team-extension-platform, extension-delivery

#34459 fix: use origin instead of mainFrameOrigin in trust signals middleware
  app/scripts/lib/trust-signals/trust-signals-middleware.test.ts
  app/scripts/lib/trust-signals/trust-signals-middleware.ts
Labels: team-product-safety

#34465 fix: cp-12.22.3 Stop persisting `permissionActivityLog` state
  app/scripts/migrations/168.1.test.ts
  app/scripts/migrations/168.1.ts
  app/scripts/migrations/index.js
  package.json
  yarn.lock
Labels: team-wallet-framework

#34216 fix: integrate phishing controller actions into NFT messengers cp-13.0.0
  .yarn/patches/@metamask-assets-controllers-npm-72.0.0-781cbafc4f.patch
  app/scripts/controller-init/messengers/assets/nft-controller-messenger.ts
  app/scripts/controller-init/messengers/assets/nft-detection-controller-messenger.ts
  package.json
  yarn.lock
Labels: team-product-safety

#34467 fix: unified swaps label
  ui/pages/bridge/index.tsx
Labels: team-swaps-and-bridge

#34385 fix: set swap src chain based on selected asset cp-13.0.0
  shared/constants/bridge.ts
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/app/wallet-overview/eth-overview.js
  ui/components/app/wallet-overview/non-evm-overview.tsx
  ui/components/multichain/account-overview/account-overview-layout.tsx
  ui/hooks/bridge/useBridging.ts
  ui/pages/asset/components/asset-page.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/selectors/selectors.js
Labels: team-swaps-and-bridge

#34526 test: Fix flaky account sync test
  test/e2e/tests/identity/account-syncing/sync-after-adding-account.spec.ts
Labels: team-wallet-framework

#34118 feat: 2.12 Session Expiry modal cp-13.0.0
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  shared/modules/provider-injection.js
  test/e2e/constants.ts
  test/e2e/helpers/seedless-onboarding/constants.ts
  test/e2e/helpers/seedless-onboarding/data.ts
  test/e2e/helpers/seedless-onboarding/mocks.ts
  test/e2e/page-objects/pages/home/homepage.ts
  test/e2e/tests/account/unlock-wallet.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/settings/change-password.spec.ts
  ui/components/app/connections-removed-modal/connections-removed-modal.stories.tsx
  ui/components/app/connections-removed-modal/connections-removed-modal.tsx
  ui/components/app/connections-removed-modal/index.ts
  ui/ducks/app/app.ts
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/selectors/selectors.js
  ui/store/actionConstants.ts
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: area-onboarding, release-blocker, team-web3auth

#34511 fix: copy and style fixes for unlock page and creation page cp-13.0.0
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/onboarding-flow/creation-successful/creation-successful.js
  ui/pages/unlock-page/index.scss
Labels: QA Passed, team-web3auth

#34518 fix: add loader for onboarding unlock page cp-13.0.0
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: QA Passed, team-web3auth

#34514 fix: security tab scroll capitalize social cp-13.0.0
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/multichain/multi-srp/srp-list/index.scss
  ui/components/multichain/multi-srp/srp-list/srp-list.tsx
  ui/pages/settings/security-tab/reveal-srp-list/reveal-srp-list.tsx
  ui/pages/settings/security-tab/security-tab.component.js
Labels: QA Passed, team-web3auth

#34541 fix: fixed incorrect navigation upon clicking back/refresh actions from browser cp-13.0.0
  ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js
  ui/pages/onboarding-flow/onboarding-flow.js
Labels: QA Passed, team-web3auth

#34545 fix: error text should not be dimmed when text field is disabled cp-13.0.0
  ui/pages/unlock-page/unlock-page.component.js
Labels: QA Passed, team-web3auth

#34382 fix: Fix silently dropped errors in shared code
  shared/lib/accounts/accounts.ts
  shared/lib/sentry.test.ts
  shared/lib/sentry.ts
  shared/lib/trace.test.ts
  shared/lib/trace.ts
  test/helpers/setup-helper.js
Labels: team-wallet-framework

#34450 fix: cp-13.0.0 improve perf for network checkbox
  test/e2e/page-objects/pages/network-manager.ts
  ui/components/multichain/network-manager/components/default-networks/default-networks.tsx
  ui/components/multichain/network-manager/hooks/useNetworkChangeHandlers.ts
Labels: team-assets

#34489 chore: adding tailwind docs
  docs/tailwind-css-guide.md
Labels: team-design-system

#34552 fix: cp-13.0.0 allows editing non-evm accounts name
  ui/pages/confirmations/hooks/useEIP7702Networks.test.ts
  ui/pages/confirmations/hooks/useEIP7702Networks.ts
Labels: team-new-networks

#34372 fix: extension update prompt in popup
  app/scripts/lib/open-update-tab-and-reload.test.ts
  app/scripts/lib/open-update-tab-and-reload.ts
  app/scripts/metamask-controller.js
  ui/components/app/update-modal/update-modal.tsx
  ui/store/actions.ts
Labels: team-extension-platform, no-changelog

#34577 fix: unlock page many attempts error time format and copywriting cp-13.0.0
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/unlock-page/formatted-counter.tsx
Labels: team-web3auth

#34576 fix: clicking back multiple times from metametrics page cp-13.0.0
  ui/pages/onboarding-flow/welcome/welcome.js
Labels: QA Passed, team-web3auth

#34570 chore: bump accounts dependencies
  .yarn/patches/@metamask-assets-controllers-npm-73.0.0-a36b91b0e4.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/tests/multichain-accounts/multichain-account-list-menu.spec.ts
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.stories.tsx
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.test.tsx
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.test.tsx
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.tsx
  ui/selectors/multichain-accounts/account-tree.ts
  ui/selectors/multichain-accounts/account-tree.types.ts
  yarn.lock
Labels: team-accounts

#34595 fix: reset app warning upon SeedlessOnboarding actions success cp-13.0.0
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: QA Passed, team-web3auth

#34580 chore: update discover link to token explore page
  test/e2e/tests/portfolio/portfolio-site.spec.ts
  ui/components/app/wallet-overview/coin-overview.tsx
Labels: team-design-system, no-changelog

#34599 fix: Throw Password Outdated error when user enters old password cp-13.0.0
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
Labels: QA Passed, team-web3auth

#34572 ci: update e2e image org
  .github/workflows/run-e2e.yml
Labels: team-dev-ops, no-changelog

#34208 feat: 2.11 added sentry error UI cp-13.0.0
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/lib/sentry-filter-events.ts
  app/scripts/lib/setupSentry.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/ducks/app/app.ts
  ui/helpers/constants/routes.ts
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/index.scss
  ui/pages/onboarding-flow/onboarding-error/index.scss
  ui/pages/onboarding-flow/onboarding-error/onboarding-error.stories.tsx
  ui/pages/onboarding-flow/onboarding-error/onboarding-error.tsx
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/welcome/welcome.js
  ui/pages/onboarding-flow/welcome/welcome.test.js
  ui/pages/unlock-page/unlock-page.component.js
  ui/pages/unlock-page/unlock-page.container.js
  ui/selectors/selectors.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: team-web3auth

#34618 fix: removed 'Use a different login method' for non-social-login flow cp-13.0.0
  ui/pages/unlock-page/__snapshots__/unlock-page.test.js.snap
  ui/pages/unlock-page/unlock-page.component.js
  ui/pages/unlock-page/unlock-page.test.js
Labels: QA Passed, team-web3auth
