Repository MetaMask/metamask-extension, pull requests merged in 2025-04, with the labels that each got.

#31467 chore: temporarily ignore `@solana/web3.js (deprecation)`
  .yarnrc.yml
Labels: team-extension-platform, team-qa

#31312 fix: srp toast message
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  test/e2e/flask/multi-srp/common-multi-srp.ts
  test/e2e/page-objects/pages/account-list-page.ts
  test/e2e/page-objects/pages/home/homepage.ts
  ui/components/app/toast-master/toast-master.js
  ui/components/app/toast-master/toast-master.test.ts
Labels: team-accounts

#31359 fix: fix button disabled for long tokenId
  app/scripts/lib/transaction/decode/util.ts
  ui/components/app/assets/nfts/nft-details/nft-details.test.js
  ui/components/app/assets/nfts/nft-details/nft-details.tsx
  ui/components/app/assets/nfts/nft-details/utils.ts
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/__snapshots__/transaction-data.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.tsx
Labels: QA Passed, team-assets

#31395 fix: hide accounts by default in reveal srp flow
  test/e2e/page-objects/pages/account-list-page.ts
  ui/components/multichain/multi-srp/srp-list/srp-list.tsx
  ui/pages/settings/security-tab/reveal-srp-list/reveal-srp-list.tsx
Labels: team-accounts

#31472 chore: cherry pick audit solana v16
  .yarnrc.yml
Labels: team-qa

#31202 chore: default account name visibility/width
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/account-picker.test.tsx.snap
Labels: team-solana

#31433 chore: bump accounts dependencies
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-accounts, release-12.17.0

#31470 test: rename more ganache old references
  test/e2e/constants.ts
  test/e2e/flask/multichain-api/testHelpers.ts
  test/e2e/flask/multichain-api/wallet_invokeMethod.spec.ts
  test/e2e/flask/user-operations.spec.ts
  test/e2e/helpers.js
  test/e2e/seeder/ganache-seeder.js
  test/e2e/seeder/ganache.ts
  test/e2e/tests/ppom/ppom-blockaid-alert-simple-send.spec.js
  test/e2e/tests/request-queuing/ui.spec.js
  test/e2e/vault-decryption-chrome.spec.ts
Labels: team-qa, skip-e2e-quality-gate

#31443 feat: updating popup width of extension from 357px to 400px
  app/popup-init.html
  app/popup.html
  ui/components/app/modals/modal.js
  ui/components/ui/mascot/mascot.stories.js
  ui/pages/unlock-page/index.scss
Labels: team-design-system

#31495 chore: sync `master` with `main` `v12.14.2` -> `v12.15.0`
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery

#31439 refactor: multichain activity tab
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/images/bitcoin-testnet-logo.svg
  shared/constants/multichain/networks.ts
  shared/constants/transaction.ts
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.stories.tsx
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.test.tsx
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx
  ui/components/app/transaction-icon/transaction-icon.js
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/app/transaction-list/transaction-list.test.js
  ui/hooks/useMultichainTransactionDisplay.ts
Labels: team-accounts

#31476 fix: Add `enableTxParamsGasFeeUpdates` to `true` in `TransactionController` config
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  test/e2e/tests/transaction/send-max.spec.js
Labels: team-confirmations

#31487 fix: codeowners file name `.yarnrc.yml`
  .github/CODEOWNERS
Labels: team-qa

#31469 fix: Fix `useTransactionGasFeeEstimate` to calculate gas estimate properly
  ui/pages/confirmations/components/confirm/info/hooks/useTransactionGasFeeEstimate.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useTransactionGasFeeEstimate.ts
Labels: team-confirmations

#31493 feat: (MMS-2076) create solana account without redirecting
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/solana-account-creation-prompt.tsx
Labels: team-swaps-and-bridge

#31500 chore: update node-pty
  package.json
  yarn.lock
Labels: team-extension-platform

#31358 feat(solana): update add account from network picker
  ui/components/multichain/create-account/create-account.tsx
  ui/components/multichain/network-list-menu/add-non-evm-account/add-non-evm-account.tsx
  ui/components/multichain/network-list-menu/index.scss
  ui/components/multichain/network-list-menu/network-list-menu.tsx
Labels: team-mmi

#31078 test: Add E2E coverage for transactions insights on more types of transactions
  test/e2e/page-objects/pages/dialog/snap-install.ts
  test/e2e/page-objects/pages/dialog/snap-txinsight.ts
  test/e2e/snaps/test-snap-txinsights.spec.ts
  ui/components/app/snaps/snap-ui-address/__snapshots__/snap-ui-address.test.tsx.snap
  ui/components/app/snaps/snap-ui-address/snap-ui-address.tsx
Labels: INVALID-PR-TEMPLATE, team-snaps-platform, area-qa, team-qa

#31428 fix(snaps): Update balance display in `AssetSelector`
  ui/components/app/snaps/snap-ui-asset-selector/useSnapAssetDisplay.tsx
Labels: team-snaps-platform

#31501 chore: Remove PortfolioView feature flags
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/hooks/useNetworkFilter.tsx
  ui/components/app/assets/util/importAllDetectedTokens.ts
  ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/pages/bridge/prepare/components/destination-account-list-item.tsx
Labels: team-assets

#31326 Refactor Connection UI for Multichain
  app/scripts/controllers/permissions/background-api.js
  app/scripts/controllers/permissions/background-api.test.js
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/network.ts
  shared/modules/selectors/networks.ts
  test/e2e/flask/multichain-api/wallet_createSession.spec.ts
  test/e2e/run-api-specs-multichain.ts
  ui/components/app/connected-status-indicator/connected-status-indicator.js
  ui/components/app/toast-master/selectors.ts
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.stories.tsx
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.test.tsx
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.tsx
  ui/components/multichain/edit-networks-modal/edit-networks-modal.js
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/components/multichain/pages/connections/connections.tsx
  ui/components/multichain/pages/permissions-page/connection-list-item.js
  ui/components/multichain/pages/review-permissions-page/review-permissions-page.tsx
  ui/components/multichain/pages/review-permissions-page/site-cell/site-cell.tsx
  ui/index.js
  ui/pages/permissions-connect/connect-page/__snapshots__/connect-page.test.tsx.snap
  ui/pages/permissions-connect/connect-page/connect-page.test.tsx
  ui/pages/permissions-connect/connect-page/connect-page.tsx
  ui/pages/permissions-connect/connect-page/utils.ts
  ui/selectors/multichain/networks.ts
  ui/selectors/selectors.js
  ui/selectors/selectors.types.ts
  ui/store/actions.ts
  yarn.lock
Labels: team-wallet-api-platform

#31535 chore: adding mm poly font files and making it available via css
  ui/css/utilities/fonts.scss
  ui/css/utilities/fonts/MMPoly/MM_Poly-Variable.woff2
Labels: team-design-system, INVALID-PR-TEMPLATE

#31526 fix: notification details event
  .madgerc
  development/circular-deps.jsonc
  ui/components/multichain/notification-detail-block-explorer-button/notification-detail-block-explorer-button.test.tsx
  ui/components/multichain/notification-detail-block-explorer-button/notification-detail-block-explorer-button.tsx
  ui/components/multichain/notification-detail-button/notification-detail-button.test.tsx
  ui/components/multichain/notification-detail-button/notification-detail-button.tsx
  ui/pages/notifications/notification-components/erc1155-sent-received/erc1155-sent-received.tsx
  ui/pages/notifications/notification-components/erc20-sent-received/erc20-sent-received.tsx
  ui/pages/notifications/notification-components/erc721-sent-received/erc721-sent-received.tsx
  ui/pages/notifications/notification-components/eth-sent-received/eth-sent-received.tsx
  ui/pages/notifications/notification-components/feature-announcement/annonucement-footer-buttons.tsx
  ui/pages/notifications/notification-components/feature-announcement/feature-announcement.tsx
  ui/pages/notifications/notification-components/feature-announcement/types.ts
  ui/pages/notifications/notification-components/lido-stake-ready-to-be-withdrawn/lido-stake-ready-to-be-withdrawn.tsx
  ui/pages/notifications/notification-components/lido-withdrawal-requested/lido-withdrawal-requested.tsx
  ui/pages/notifications/notification-components/snap/snap-footer-button.test.tsx
  ui/pages/notifications/notification-components/snap/snap-footer-button.tsx
  ui/pages/notifications/notification-components/snap/snap.tsx
  ui/pages/notifications/notification-components/snap/types.ts
  ui/pages/notifications/notification-components/stake/stake.tsx
  ui/pages/notifications/notification-components/swap-completed/swap-completed.tsx
Labels: team-assets

#30673 feat: Add clear functionality to SRP import error banner
  ui/components/multichain/multi-srp/import-srp/import-srp.test.tsx
  ui/components/multichain/multi-srp/import-srp/import-srp.tsx
Labels: team-mmi

#31508 fix: select first gas fee token automatically
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/batch-simulation-details.test.tsx
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/batch-simulation-details.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-modal/gas-fee-token-modal.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-modal/gas-fee-token-modal.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/gas-fees-details.tsx
  ui/pages/confirmations/hooks/useAutomaticGasFeeTokenSelect.test.ts
  ui/pages/confirmations/hooks/useAutomaticGasFeeTokenSelect.ts
  ui/store/controller-actions/transaction-controller.ts
Labels: team-confirmations

#31413 fix: unscrollable Remove Snap modal dialog
  ui/components/app/snaps/keyring-snap-removal-warning/keyring-snap-removal-warning.tsx
Labels: team-confirmations

#31504 test: removing some entries from live request allowlist by adding missing mocks
  test/e2e/mock-e2e-allowlist.js
  test/e2e/mock-e2e.js
  test/e2e/mock-response-data/accounts-api-tokens.json
  test/e2e/mock-response-data/bridge-get-all-feature-flags.json
  test/e2e/mock-response-data/chain-id-network-chains.json
  test/e2e/mock-response-data/client-side-detection-blocklist.json
  test/e2e/mock-response-data/on-ramp-content.json
Labels: team-extension-platform, flaky tests, team-qa

#31543 fix: prevent multiple account creations in the same flow.
  ui/components/multichain/create-snap-account/create-snap-account.test.tsx
  ui/components/multichain/create-snap-account/create-snap-account.tsx
Labels: team-accounts

#31511 feat: for batch transaction simulation section approve rows should be displayed at the top
  ui/pages/confirmations/components/simulation-details/simulation-details.test.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
Labels: team-confirmations

#31563 fix: small amounts on activity tab
  ui/components/app/transaction-list/transaction-list.test.js
  ui/hooks/useMultichainTransactionDisplay.ts
Labels: team-accounts

#31565 fix: cp-12.16.0 hide balance alert if selected gas fee token (#31497)
  ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.ts
Labels: team-confirmations

#31536 Jl/sip 26/wallet create session filter accounts non evm
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#31570 cp: fix: bump `@metamask/keyring-controller` to `^21.0.1`
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#31544 add flag to prompt connection UI for solana account creation
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.ts
  app/scripts/metamask-controller.js
  ui/pages/permissions-connect/connect-page/connect-page.tsx
Labels: team-wallet-api-platform

#31533 chore: Add XRPL EVM Testnet network
  app/images/xrp-logo.svg
  app/images/xrplevm-testnet.svg
  shared/constants/network.ts
Labels: team-assets

#31575 chore: update changelog for 12.15.1
  CHANGELOG.md
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#31534 Ad/add solana accounts changed event emit onconnect
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.ts
  app/scripts/metamask-controller.js
  ui/store/actions.ts
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#31578 chore: Resolve merge conflicts between `master` and `v12.16.0` RC
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery

#31583 attempt to DRY sip-26 todos
  app/scripts/controllers/permissions/background-api.js
  shared/lib/multichain/chain-agnostic-permission.ts
  ui/components/multichain/connected-status/connected-status.tsx
  ui/index.js
  ui/pages/permissions-connect/connect-page/connect-page.tsx
  ui/pages/permissions-connect/connect-page/utils.ts
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-wallet-api-platform

#31573 chore: Update Soneium logo
  app/images/soneium.svg
  shared/constants/network.ts
Labels: team-assets

#31594 fix: cp-12.16.0 select first gas fee token automatically (#31508)
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/batch-simulation-details.test.tsx
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/batch-simulation-details.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-modal/gas-fee-token-modal.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-modal/gas-fee-token-modal.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/gas-fees-details.tsx
  ui/pages/confirmations/hooks/useAutomaticGasFeeTokenSelect.test.ts
  ui/pages/confirmations/hooks/useAutomaticGasFeeTokenSelect.ts
  ui/store/controller-actions/transaction-controller.ts
Labels: team-confirmations

#31234 test: eip7702 setup and upgrade+batch simple spec
  test/e2e/page-objects/pages/confirmations/redesign/batch-confirmation.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/seeder/anvil.ts
  test/e2e/seeder/network-states/eip7702-state/withDelegatorContracts.json
  test/e2e/tests/confirmations/helpers.ts
  test/e2e/tests/confirmations/transactions/eip7702-eip5792-upgrade-account.spec.ts
  ui/pages/confirmations/components/confirm/info/batch/nested-transaction-data/nested-transaction-data.tsx
  ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/transaction-account-details.tsx
Labels: e2e-test, team-confirmations, team-qa

#31560 fix: cp-12.16.0 add gasless metrics
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
  shared/modules/metametrics.test.ts
  shared/types/metametrics.ts
  ui/pages/confirmations/hooks/useAutomaticGasFeeTokenSelect.test.ts
Labels: team-confirmations

#31595 fix: Prevent overflow in from Snaps UI header in confirmations
  ui/pages/confirmations/confirmation/confirmation.js
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-named-snap-account.test.js.snap
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#31596 feat: cp-12.16.0 gas fee token toast (#31338)
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/base-transaction-info/__snapshots__/base-transaction-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/hooks/useGasFeeToken.ts
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/__snapshots__/set-approval-for-all-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/__snapshots__/edit-gas-fees-row.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-icon/gas-fee-token-icon.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-icon/gas-fee-token-icon.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-modal/gas-fee-token-modal.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-toast/gas-fee-token-toast.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-toast/gas-fee-token-toast.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-toast/index.scss
  ui/pages/confirmations/components/confirm/info/shared/gas-fee-token-toast/index.ts
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/__snapshots__/gas-fees-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-details/gas-fees-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-section/__snapshots__/gas-fees-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
  ui/pages/confirmations/components/index.scss
  ui/pages/confirmations/confirm/confirm.tsx
Labels: team-confirmations

#31542 fix: workaround for first party snap account name suggestion
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/create-account/create-account.tsx
  ui/components/multichain/create-snap-account/create-snap-account.test.tsx
  ui/components/multichain/create-snap-account/create-snap-account.tsx
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-named-snap-account.test.js.snap
Labels: team-accounts

#31441 feat: fetch user balance for transaction's network
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/controller-init/test/utils.ts
  app/scripts/controller-init/types.ts
  app/scripts/metamask-controller.js
  ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.ts
  ui/selectors/confirm-transaction.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-confirmations

#31473 test: Migrate dapp interaction e2e tests to Typescript and Page object modal
  test/e2e/page-objects/flows/encrypt-decrypt.flow.ts
  test/e2e/page-objects/pages/confirmations/redesign/decrypt-message-confirmation.ts
  test/e2e/page-objects/pages/confirmations/redesign/get-encryption-key-confirmation.ts
  test/e2e/page-objects/pages/confirmations/redesign/personal-sign-confirmation.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  test/e2e/tests/confirmations/signatures/siwe.spec.ts
  test/e2e/tests/dapp-interactions/encrypt-decrypt.spec.js
  test/e2e/tests/dapp-interactions/encrypt-decrypt.spec.ts
  test/e2e/tests/dapp-interactions/eth-subscribe.spec.ts
  test/e2e/tests/dapp-interactions/signin-with-ethereum.spec.js
Labels: team-qa

#31377 feat: escape / sanitize signTypedData update
  ui/helpers/utils/util.js
  ui/helpers/utils/util.test.js
Labels: team-confirmations

#31521 fix: flaky test `MetaMask onboarding should not prevent network requests to basic functionality endpoints when the basic functionality toggle is on`
  test/e2e/fixture-builder.js
Labels: flaky tests, team-qa

#31599 fix: flaky test `Request Queueing chainId proxy sync should preserve per dapp network selections after connecting and switching without refresh calls`
  test/e2e/tests/request-queuing/chainid-check.spec.js
Labels: flaky tests, team-qa

#31608 isNamespaceInScopesObject
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.ts
  shared/lib/multichain/chain-agnostic-permission.ts
Labels: team-wallet-api-platform

#31613 fix: cp-12.15.2 Allow `verifyingContract` to be omitted from EIP-712 signatures
  .yarn/patches/@metamask-signature-controller-npm-26.0.0-ecbc8b6cda.patch
  package.json
  yarn.lock
Labels: team-wallet-framework

#31400 Throw 5100 error when no requested scopes are supported in `wallet_createSession` call
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.ts
  package.json
  yarn.lock
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#31645 test: fix failing ppom e2e
  test/e2e/tests/ppom/ppom-blockaid-alert-simple-send.spec.js
  test/e2e/tests/ppom/ppom-blockaid-alert-trade-order-farming.spec.js
Labels: team-qa

#31592 fix: multichain swap transaction to show from amount
  attribution.txt
  package.json
  test/e2e/flask/solana/common-solana.ts
  test/e2e/flask/solana/send-flow.spec.ts
  test/e2e/flask/solana/send-spl-token.spec.ts
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.test.tsx
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/app/transaction-list/transaction-list.test.js
  ui/hooks/useMultichainTransactionDisplay.ts
  yarn.lock
Labels: team-solana

#31531 feat(institutional-snap): pre-install institutional snap
  app/scripts/snaps/preinstalled-snaps.ts
  package.json
  ui/components/multichain/global-menu/global-menu.js
  ui/selectors/selectors.js
  yarn.lock
Labels: team-mmi

#31638 feat: cp-12.15.2 add icon image for `Lens` network
  app/images/lens-native.svg
  app/images/lens.png
  shared/constants/network.ts
Labels: QA Passed, team-network-enablement

#31239 fix: fix NFT balance in send flow
  ui/ducks/send/send.js
Labels: team-assets

#31456 feat: require network client ID when adding transactions
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/ducks/swaps/swaps.js
  ui/pages/confirmations/hooks/useEIP7702Account.ts
  ui/store/actions.ts
Labels: team-confirmations

#31659 test: fix failing ppom e2e (cherry-pick)
  test/e2e/tests/ppom/ppom-blockaid-alert-simple-send.spec.js
  test/e2e/tests/ppom/ppom-blockaid-alert-trade-order-farming.spec.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#31664 feat: add icon image for `Lens` network (cherry-pick) (cherry-pick to v12.15.2)
  app/images/lens-native.svg
  app/images/lens.png
  shared/constants/network.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#31654 fix: Allow verifyingContract to be omitted from EIP-712 signatures (cherry-pick)
  .yarn/patches/@metamask-signature-controller-npm-26.0.0-ecbc8b6cda.patch
  package.json
  yarn.lock
Labels: team-extension-platform

#31670 chore: additional changelog updates for Version v12.15.2
  CHANGELOG.md
Labels: INVALID-PR-TEMPLATE

#31549 feat: cp-12.16.0 remove OneKey device from hardware selection page
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/ui/logo/logo-onekey.tsx
  ui/pages/create-account/connect-hardware/__snapshots__/index.test.tsx.snap
  ui/pages/create-account/connect-hardware/index.test.tsx
  ui/pages/create-account/connect-hardware/select-hardware.js
Labels: team-hardware-wallets

#31668 fix: cp-12.16.0 bump "@metamask/smart-transactions-controller": "^16.3.1"
  package.json
  yarn.lock
Labels: team-transactions, regression-prod-12.16.0

#31641 Ad/sip 26 more utility functions
  shared/lib/multichain/chain-agnostic-permission.ts
  ui/pages/permissions-connect/connect-page/connect-page.tsx
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#31658 fix: nftController with modular init pattern
  app/scripts/controller-init/assets/index.ts
  app/scripts/controller-init/assets/nft-controller-init.test.ts
  app/scripts/controller-init/assets/nft-controller-init.ts
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/assets/index.ts
  app/scripts/controller-init/messengers/assets/nft-controller-messenger.test.ts
  app/scripts/controller-init/messengers/assets/nft-controller-messenger.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/metamask-controller.js
Labels: team-assets

#31674 fix: nftDetectionController with new initialization pattern
  app/scripts/controller-init/assets/index.ts
  app/scripts/controller-init/assets/nft-detection-controller-init.test.ts
  app/scripts/controller-init/assets/nft-detection-controller-init.ts
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/assets/index.ts
  app/scripts/controller-init/messengers/assets/nft-detection-controller-messenger.test.ts
  app/scripts/controller-init/messengers/assets/nft-detection-controller-messenger.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
Labels: team-assets

#30891 style: Update color for no balance and generic avatars
  ui/components/app/assets/token-cell/__snapshots__/token-cell.test.tsx.snap
  ui/components/app/assets/token-cell/cells/token-cell-badge.tsx
  ui/components/app/wallet-overview/__snapshots__/aggregated-percentage-overview.test.tsx.snap
  ui/components/app/wallet-overview/aggregated-percentage-overview.tsx
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
Labels: type-bug, team-assets, area-design

#31618 style: Remove shadow from toast
  ui/components/multichain/toast/index.scss
Labels: type-bug, team-assets, area-design

#31624 style: Update font weights for balance, price and other headers
  ui/components/app/assets/nfts/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/assets/nfts/nft-details/nft-details.tsx
  ui/components/app/wallet-overview/index.scss
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/asset/components/asset-price.tsx
Labels: team-assets

#31498 feat: (MMS-2106) supports copying block explorer link in bridge page
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/bridge/__snapshots__/index.test.tsx.snap
  ui/pages/bridge/prepare/__snapshots__/prepare-bridge-page.test.tsx.snap
  ui/pages/bridge/prepare/bridge-input-group.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#31672 fix: switch-ethereun-chain not passing rejectApprovalRequestsForOrigin hook correctly
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
Labels: team-confirmations

#31577 test: ensure `foundryup` works when bin path contains a space character
  test/helpers/foundry/utils.ts
Labels: team-extension-platform

#31597 chore: remove MMI hooks and upgrade transaction controller
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/lib/transaction/mmi-hooks.test.ts
  app/scripts/lib/transaction/mmi-hooks.ts
  package.json
  test/e2e/tests/metrics/errors.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/privacy/basic-functionality.spec.ts
  test/e2e/tests/settings/localization.spec.js
  yarn.lock
Labels: team-identity

#31475 fix: Update blockaid friction modal copy
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/alert-system/alert-modal/alert-modal.test.tsx
  ui/components/app/alert-system/alert-modal/alert-modal.tsx
Labels: team-confirmations

#31700 fix:`useTransactionGasFeeEstimate` to calculate gas estimate.
  ui/pages/confirmations/components/confirm/info/hooks/useTransactionGasFeeEstimate.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useTransactionGasFeeEstimate.ts
Labels: team-swaps-and-bridge

#31407 feat: Sol 208 extension asset details UI
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/app/transaction-list/transaction-list.test.js
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/hooks/useHandleSendNonEvm.test.ts
  ui/components/app/wallet-overview/hooks/useHandleSendNonEvm.ts
  ui/components/multichain/account-overview/account-overview-tabs.tsx
  ui/components/ui/aggregated-balance/aggregated-balance.tsx
  ui/pages/asset/asset.tsx
  ui/pages/asset/components/asset-options.js
  ui/pages/asset/components/asset-page.tsx
  ui/pages/asset/components/token-asset.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/asset/util.ts
  ui/selectors/assets.test.ts
  ui/selectors/assets.ts
  ui/selectors/multichain.ts
  ui/store/actions.ts
Labels: team-solana

#31696 fix(snaps): Fix type issue with assets metadata
  ui/hooks/useMultichainBalances.ts
Labels: team-snaps-platform

#31137 fix: Revert "feat(14507): improve error message for failed txn in activity…
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/transaction-list-item-details/index.scss
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.test.js
  ui/components/app/transaction-list-item/smart-transaction-list-item.component.js
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/app/transaction-status-label/__snapshots__/transaction-status-label.test.js.snap
  ui/components/app/transaction-status-label/transaction-status-label.js
  ui/components/app/transaction-status-label/transaction-status-label.test.js
Labels: team-extension-platform

#31713 fix: solana modal auto focus fix
  ui/components/app/whats-new-modal/whats-new-modal.tsx
Labels: team-solana

#31718 chore: merge master into v12.16.0 to include fixes from v12.15.2
  .yarn/patches/@metamask-signature-controller-npm-26.0.0-ecbc8b6cda.patch
  CHANGELOG.md
  app/images/lens-native.svg
  app/images/lens.png
  package.json
  shared/constants/network.ts
  test/e2e/tests/ppom/ppom-blockaid-alert-simple-send.spec.js
  test/e2e/tests/ppom/ppom-blockaid-alert-trade-order-farming.spec.js
  test/e2e/vault-decryption-chrome.spec.ts
  test/e2e/webdriver/driver.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#31689 fix: cp-12.16.0 include networkClientId in stx submitSignedTransactions call
  app/scripts/lib/transaction/smart-transactions.ts
Labels: team-swaps-and-bridge

#31720 chore: master sync (after v12.15.2)
  CHANGELOG.md
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#31695 fix: remove-duplicated-alerts
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#31679 fix: cp-12.16.0 HW wallet confirmation warning for bridge
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/ducks/bridge/selectors.ts
  ui/hooks/bridge/useBridgeChainInfo.ts
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/transaction-details/bridge-explorer-links.tsx
  ui/pages/bridge/transaction-details/transaction-details.tsx
Labels: team-swaps-and-bridge

#31660 fix: add solana modal title
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
Labels: team-mmi

#31463 feat(remote-mode): add feature slide
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/controllers/app-state-controller.ts
  ui/components/multichain/account-overview/account-overview-layout.tsx
  ui/hooks/useCarouselManagement/constants.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.test.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.ts
Labels: team-vault

#31019 fix: Update routes callbacks per react-perf's warnings
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.container.js
Labels: team-wallet-ux

#31740 chore: cherry-pick fix: HW wallet confirmation warning for bridge into v12.16.0
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/ducks/bridge/selectors.ts
  ui/hooks/bridge/useBridgeChainInfo.ts
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/transaction-details/bridge-explorer-links.tsx
  ui/pages/bridge/transaction-details/transaction-details.tsx
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#31615 style: Update alignment and hover effect for token cell
  ui/components/app/assets/token-cell/__snapshots__/token-cell.test.tsx.snap
  ui/components/app/assets/token-cell/cells/token-cell-badge.tsx
  ui/components/app/assets/token-cell/token-cell.tsx
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/asset/components/asset-page.tsx
Labels: type-bug, team-assets, area-design

#31690 fix: cp-12.16.0 update Keystone keyring package to v0.15.2
  .yarn/patches/@keystonehq-metamask-airgapped-keyring-npm-0.15.2-94dd4b40d7.patch
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/app/qr-hardware-popover/qr-hardware-sign-request/player.js
  yarn.lock
Labels: QA Passed, needs-dev-review, team-hardware-wallets

#31756 fix: carousel e2e test
  test/e2e/tests/carousel/carousel.spec.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.test.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.ts
Labels: team-extension-platform, team-network-enablement

#31387 feat(solana): update add account from opt in solana
  ui/components/app/whats-new-modal/solana/modal-footer.tsx
  ui/components/app/whats-new-modal/whats-new-modal.test.tsx
  ui/components/app/whats-new-modal/whats-new-modal.tsx
  ui/components/multichain/create-solana-account-modal/create-solana-account-modal.tsx
  ui/components/multichain/create-solana-account-modal/index.ts
Labels: team-mmi

#31684 fix: show account balances for selected XChain swap destination address
  ui/hooks/bridge/useTokensWithFiltering.ts
  ui/hooks/useMultichainBalances.ts
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#31605 fix: improvements in page to revert smart account to EOA account
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/data/confirmations/batch-transaction.ts
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/batch-simulation-details.test.tsx
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/batch-simulation-details.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
Labels: team-confirmations

#31771 chore: Bump profile-sync-controller
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#31661 fix: dark mode styling and spacing
  ui/components/multichain/multi-srp/select-srp/select-srp.tsx
  ui/components/multichain/multi-srp/srp-list/index.scss
  ui/pages/settings/index.scss
Labels: team-accounts

#31655 feat(institutional-snap): manage institutional snaps preference and account menu option
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/metamask-controller.js
  shared/lib/accounts/index.ts
  shared/lib/accounts/institutional-wallet-snap.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-identity

#31746 fix: Add `displayAvatar` prop to Snap `AddressInput` component
  ui/components/app/snaps/snap-ui-renderer/components/__snapshots__/address-input.test.ts.snap
  ui/components/app/snaps/snap-ui-renderer/components/address-input.test.ts
  ui/components/app/snaps/snap-ui-renderer/components/address-input.ts
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#31736 SIP-26 add auto network select
  app/scripts/controllers/permissions/background-api.js
  app/scripts/controllers/permissions/background-api.test.js
  app/scripts/metamask-controller.js
  shared/modules/selectors/networks.ts
  ui/pages/permissions-connect/connect-page/connect-page.tsx
Labels: team-wallet-api-platform

#31609 feat: add setting to dismiss prompt to enable smart contract
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/lib/transaction/eip5792.test.ts
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/metamask-controller.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.component.test.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
  ui/store/actions.ts
Labels: team-confirmations

#31748 enhance, cleanup, rename chain agnostic permission utilities
  app/scripts/controllers/permissions/background-api.js
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.ts
  shared/lib/multichain/chain-agnostic-permission-utils/caip-accounts.ts
  shared/lib/multichain/chain-agnostic-permission-utils/caip-chainids.ts
  shared/lib/multichain/chain-agnostic-permission-utils/misc-utils.ts
  shared/lib/multichain/chain-agnostic-permission.ts
  ui/components/app/connected-status-indicator/connected-status-indicator.js
  ui/components/multichain/connected-status/connected-status.tsx
  ui/index.js
  ui/pages/permissions-connect/connect-page/connect-page.tsx
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#31780 chore(runway): cherry-pick fix: cp-12.16.0 carousel fix
  test/e2e/tests/carousel/carousel.spec.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.test.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.ts
Labels: team-network-enablement

#29971 fix: update function name in 077-supplement-for-088.ts
  app/scripts/migrations/077-supplements/077-supplement-for-088.ts
Labels: external-contributor

#31330 ci: turn on skip-allow-scripts to save time
  .github/workflows/add-release-label.yml
  .github/workflows/build-beta.yml
  .github/workflows/build-storybook.yml
  .github/workflows/check-attributions.yml
  .github/workflows/check-pr-labels.yml
  .github/workflows/check-template-and-add-labels.yml
  .github/workflows/close-bug-report.yml
  .github/workflows/create-bug-report.yml
  .github/workflows/fitness-functions.yml
  .github/workflows/locales-only.yml
  .github/workflows/main.yml
  .github/workflows/needs-e2e.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/repository-health-checks.yml
  .github/workflows/run-benchmarks.yml
  .github/workflows/run-e2e.yml
  .github/workflows/run-tests.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-storybook.yml
  .github/workflows/update-attributions.yml
  .github/workflows/update-lavamoat-policies.yml
  .github/workflows/validate-lavamoat-policy-build.yml
  .github/workflows/validate-lavamoat-policy-webapp.yml
Labels: team-extension-platform, team-tiger

#31712 chore: add icon image for Plume network
  app/images/plume-native.svg
  app/images/plume.svg
  shared/constants/network.ts
Labels: QA Passed, team-network-enablement, release-12.17.0

#31744 feat: adds deeply liquid stablecoin slippage value of 0.5
  shared/constants/swaps.ts
  ui/ducks/swaps/swaps.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
  ui/pages/swaps/transaction-settings/transaction-settings.js
Labels: team-swaps-and-bridge

#30180 feat(institutional-snap-controller): Institutional Snap transaction handling
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/institutional-snap/institutional-snap-controller-init.test.ts
  app/scripts/controller-init/institutional-snap/institutional-snap-controller-init.ts
  app/scripts/controller-init/messengers/accounts/institutional-snap-controller-messenger.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/transaction-controller-messenger.ts
  app/scripts/controllers/institutional-snap/InstitutionalSnapController.test.ts
  app/scripts/controllers/institutional-snap/InstitutionalSnapController.ts
  app/scripts/controllers/institutional-snap/institutional-snap-controller.types.ts
  app/scripts/lib/transaction/institutional-snap/InstitutionalSnapController.test.ts
  app/scripts/lib/transaction/institutional-snap/InstitutionalSnapController.ts
  app/scripts/lib/transaction/institutional-snap/institutional-snap-controller.types.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
Labels: team-identity

#31686 fix: missing solana fiat values in XChain swaps page
  ui/ducks/bridge/selectors.ts
  ui/ducks/bridge/utils.ts
  ui/hooks/bridge/useBridgeExchangeRates.ts
Labels: team-swaps-and-bridge

#31494 chore: Updating Text component "body" font sizes
  .storybook/metamask-storybook-theme.js
  package.json
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/snaps/test-snap-revoke-perm.spec.js
  ui/components/component-library/text/text.scss
  ui/css/design-system/_typography.scss
  ui/pages/error-page/index.scss
  yarn.lock
Labels: team-design-system

#31693 chore: Bump Snaps packages
  app/scripts/lib/SnapsNameProvider.test.ts
  app/scripts/lib/SnapsNameProvider.ts
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/mock-e2e-allowlist.js
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-interactive-ui.spec.js
  ui/components/app/snaps/snap-home-page/useSnapHome.js
  ui/components/app/snaps/snap-ui-renderer/components/file-input.test.ts
  ui/components/app/snaps/snap-ui-renderer/components/form.test.ts
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.test.js
  ui/contexts/snaps/snap-interface.tsx
  ui/ducks/domains.js
  ui/hooks/snaps/useSnapSettings.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#31765 feat: Add splash page for smart account upgrade
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/petrol-pump.svg
  app/images/smart-transactions/smart-account-update.svg
  app/images/sparkle.svg
  app/images/speedometer.svg
  shared/lib/ui-utils.js
  test/data/confirmations/batch-transaction.ts
  test/e2e/page-objects/pages/confirmations/redesign/batch-confirmation.ts
  test/e2e/tests/confirmations/transactions/eip7702-eip5792-upgrade-account.spec.ts
  ui/pages/confirmations/components/confirm/footer/acknowledge/acknowledge.stories.tsx
  ui/pages/confirmations/components/confirm/footer/acknowledge/acknowledge.test.tsx
  ui/pages/confirmations/components/confirm/footer/acknowledge/acknowledge.tsx
  ui/pages/confirmations/components/confirm/footer/acknowledge/index.ts
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/upgrade-cancel-modal.tsx
  ui/pages/confirmations/components/confirm/splash/index.ts
  ui/pages/confirmations/components/confirm/splash/smart-account-update/index.ts
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.scss
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.test.tsx
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.tsx
  ui/pages/confirmations/components/confirm/splash/splash.test.tsx
  ui/pages/confirmations/components/confirm/splash/splash.tsx
  ui/pages/confirmations/components/index.scss
  ui/pages/confirmations/confirm/confirm.tsx
  ui/pages/confirmations/hooks/useSmartAccountActions.test.ts
  ui/pages/confirmations/hooks/useSmartAccountActions.ts
Labels: team-confirmations

#31822 fix: prevents unintended second redirection to activity tab
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
Labels: team-swaps-and-bridge

#31715 fix: Swap to ethereum string
  shared/constants/bridge.ts
  ui/pages/confirmations/confirmation/alerts/TemplateAlertContext.tsx
Labels: team-swaps-and-bridge

#31716 chore: sol-267 remove pill for snap accounts
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/helpers/utils/accounts.js
  ui/helpers/utils/accounts.test.js
Labels: team-solana

#31630 test: add spec `signs message with verifyingContract field missing`
  test/e2e/helpers.js
  test/e2e/page-objects/flows/transaction.ts
  test/e2e/page-objects/pages/test-dapp-individual-request.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/confirmations/signatures/sign-typed-data-v4.spec.ts
Labels: team-confirmations, team-qa

#31313 fix: cp-12.17.0 upgrade @metamask/eth-ledger-bridge-keyring to fix the ledger signTypedDataV4 with salt
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: QA Passed, needs-dev-review, team-hardware-wallets

#31561 test: fix flaky speed up and cancel transaction tests
  test/e2e/page-objects/pages/home/activity-list.ts
  test/e2e/tests/confirmations/transactions/speed-up-and-cancel-confirmations.spec.ts
Labels: team-qa

#31505 fix(swap/bridge): move to activity tab before transaction
  ui/pages/bridge/hooks/useHandleTx.ts
Labels: team-solana, team-swaps-and-bridge

#31742 fix: Prevent double filtering of tokens
  ui/pages/asset/components/asset-page.tsx
Labels: team-wallet-ux

#31593 feat: support gasless transactions via EIP-7702
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/controller-init/messengers/transaction-controller-messenger.ts
  app/scripts/lib/transaction/__snapshots__/delegation.test.ts.snap
  app/scripts/lib/transaction/delegation.test.ts
  app/scripts/lib/transaction/delegation.ts
  app/scripts/lib/transaction/hooks/delegation-7702-publish.test.ts
  app/scripts/lib/transaction/hooks/delegation-7702-publish.ts
  app/scripts/lib/transaction/transaction-relay.test.ts
  app/scripts/lib/transaction/transaction-relay.ts
  app/scripts/metamask-controller.js
  builds.yml
  package.json
  test/data/confirmations/helper.ts
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/info/shared/selected-gas-fee-token/selected-gas-fee-token.tsx
  ui/pages/confirmations/hooks/gas/useIsGaslessSupported.test.ts
  ui/pages/confirmations/hooks/gas/useIsGaslessSupported.ts
  ui/pages/confirmations/hooks/transactions/useTransactionConfirm.test.ts
  ui/pages/confirmations/hooks/transactions/useTransactionConfirm.ts
  ui/pages/confirmations/hooks/useAutomaticGasFeeTokenSelect.ts
  ui/store/controller-actions/transaction-controller.ts
  yarn.lock
Labels: team-confirmations

#31129 fix: #30115: Hide import key error
  ui/components/multichain/import-account/private-key.js
Labels: team-wallet-ux

#31812 chore: cp-12.16.0 Add default platform for suggested key
  app/manifest/v2/_base.json
  app/manifest/v3/_base.json
Labels: team-wallet-framework, team-extension-platform

#31774 feat: user to be able to disable smart account update per account
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/lib/transaction/eip5792.test.ts
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/index.scss
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/index.ts
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/upgrade-cancel-modal.stories.tsx
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/upgrade-cancel-modal.test.tsx
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/upgrade-cancel-modal.tsx
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.scss
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.test.tsx
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.tsx
  ui/pages/confirmations/components/index.scss
  ui/pages/confirmations/hooks/useSmartAccountActions.test.ts
  ui/pages/confirmations/hooks/useSmartAccountActions.ts
  ui/store/actions.ts
Labels: team-confirmations

#31832 chore: Remove multi SRP code fences
  app/scripts/metamask-controller.js
  builds.yml
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/app/srp-quiz-modal/SRPQuiz/SRPQuiz.tsx
  ui/components/app/toast-master/selectors.ts
  ui/components/app/toast-master/toast-master.js
  ui/components/app/toast-master/utils.ts
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/account-details/account-details.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/create-account/create-account.tsx
  ui/components/multichain/create-eth-account/create-eth-account.js
  ui/components/multichain/create-snap-account/create-snap-account.tsx
  ui/components/multichain/index.js
  ui/ducks/app/app.ts
  ui/helpers/constants/routes.ts
  ui/pages/keychains/reveal-seed.js
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: team-identity

#31745 fix: clear hidden accounts on restore and account list scroll
  app/scripts/metamask-controller.js
  ui/components/multichain/account-list-menu/account-list-menu.tsx
Labels: team-accounts

#31564 test: Migrate accounts e2e tests to Typescript and Page object modal
  test/e2e/constants.ts
  test/e2e/page-objects/pages/dialog/account-details-modal.ts
  test/e2e/page-objects/pages/header-navbar.ts
  test/e2e/page-objects/pages/home/homepage.ts
  test/e2e/page-objects/pages/onboarding/secure-wallet-page.ts
  test/e2e/page-objects/pages/test-dapp-send-eth-with-private-key.ts
  test/e2e/tests/account/account-details.spec.js
  test/e2e/tests/account/account-details.spec.ts
  test/e2e/tests/account/incremental-security.spec.js
  test/e2e/tests/account/incremental-security.spec.ts
Labels: team-qa

#31705 feat: Solana Wallet Standard
  app/scripts/inpage.js
  package.json
  yarn.lock
Labels: team-wallet-api-platform, team-be

#31847 feat: Solana Wallet Standard (#31705)
  app/scripts/inpage.js
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#31481 fix: trigger detectNfts on account switch
  test/e2e/tests/account/add-account.spec.ts
  test/e2e/tests/identity/account-syncing/sync-with-account-balances.spec.ts
  test/e2e/tests/identity/mocks.ts
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/connect-accounts-modal/__snapshots__/connect-accounts-modal.test.tsx.snap
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/permissions-connect/connect-page/__snapshots__/connect-page.test.tsx.snap
Labels: team-assets

#31582 feat: Remote Mode - Enabling Swaps / Daily Allowance screens and components
  app/images/icon-usdc.png
  ui/helpers/constants/routes.ts
  ui/pages/remote-mode/introducing/remote-mode-introducing.component.test.tsx
  ui/pages/remote-mode/introducing/remote-mode-introducing.component.tsx
  ui/pages/remote-mode/introducing/remote-mode-introducing.stories.tsx
  ui/pages/remote-mode/overview/index.ts
  ui/pages/remote-mode/overview/remote-mode-overview.container.tsx
  ui/pages/remote-mode/overview/remote-mode-overview.stories.tsx
  ui/pages/remote-mode/overview/remote-mode-permissions.component.tsx
  ui/pages/remote-mode/overview/remote-mode-permissions.test.tsx
  ui/pages/remote-mode/remote.types.ts
  ui/pages/remote-mode/setup/daily-allowance-card/index.tsx
  ui/pages/remote-mode/setup/daily-allowance-card/remote-mode-daily-allowance-card.component.test.tsx
  ui/pages/remote-mode/setup/daily-allowance-card/remote-mode-daily-allowance-card.component.tsx
  ui/pages/remote-mode/setup/daily-allowance-card/remote-mode-daily-allowance-card.stories.tsx
  ui/pages/remote-mode/setup/hardware-wallet-confirm-modal/index.tsx
  ui/pages/remote-mode/setup/hardware-wallet-confirm-modal/remote-mode-hardware-wallet-confirm.component.test.tsx
  ui/pages/remote-mode/setup/hardware-wallet-confirm-modal/remote-mode-hardware-wallet-confirm.component.tsx
  ui/pages/remote-mode/setup/hardware-wallet-confirm-modal/remote-mode-hardware-wallet-confirm.stories.tsx
  ui/pages/remote-mode/setup/index.ts
  ui/pages/remote-mode/setup/setup-daily-allowance/index.ts
  ui/pages/remote-mode/setup/setup-daily-allowance/remote-mode-setup-daily-allowance.component.test.tsx
  ui/pages/remote-mode/setup/setup-daily-allowance/remote-mode-setup-daily-allowance.component.tsx
  ui/pages/remote-mode/setup/setup-daily-allowance/remote-mode-setup-daily-allowance.stories.tsx
  ui/pages/remote-mode/setup/setup-swaps/index.ts
  ui/pages/remote-mode/setup/setup-swaps/remote-mode-setup-swaps.component.test.tsx
  ui/pages/remote-mode/setup/setup-swaps/remote-mode-setup-swaps.component.tsx
  ui/pages/remote-mode/setup/setup-swaps/remote-mode-setup-swaps.stories.tsx
  ui/pages/remote-mode/setup/step-indicator/index.tsx
  ui/pages/remote-mode/setup/step-indicator/step-indicator.component.test.tsx
  ui/pages/remote-mode/setup/step-indicator/step-indicator.component.tsx
  ui/pages/remote-mode/setup/step-indicator/step-indicator.stories.tsx
  ui/pages/remote-mode/setup/swap-allowance-card/index.tsx
  ui/pages/remote-mode/setup/swap-allowance-card/remote-mode-swap-allowance-card.component.test.tsx
  ui/pages/remote-mode/setup/swap-allowance-card/remote-mode-swap-allowance-card.component.tsx
  ui/pages/remote-mode/setup/swap-allowance-card/remote-mode-swap-allowance-card.stories.tsx
  ui/pages/routes/routes.component.js
Labels: team-vault

#31825 feat: cp-12.17.0 enable review permissions button for non EVM networks
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
  ui/components/multichain/app-header/app-header.js
Labels: team-wallet-api-platform

#31711 chore: Bump network-controller to v23
  .yarn/patches/@metamask-network-controller-npm-23.2.0-0223efb98a.patch
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/run-api-specs-multichain.ts
  test/e2e/run-openrpc-api-test-coverage.ts
  yarn.lock
Labels: team-wallet-framework

#31546 feat: cp-12.17.0 solana bridge activity list improvements
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  shared/lib/bridge-status/utils.ts
  ui/components/app/app-components.scss
  ui/components/app/multichain-bridge-transaction-details-modal/index.scss
  ui/components/app/multichain-bridge-transaction-details-modal/multichain-bridge-transaction-details-modal.tsx
  ui/components/app/multichain-bridge-transaction-list-item/index.scss
  ui/components/app/multichain-bridge-transaction-list-item/multichain-bridge-transaction-list-item.tsx
  ui/components/app/transaction-list/transaction-list.component.js
  ui/hooks/bridge/useSolanaBridgeTransactionMapping.ts
  ui/pages/bridge/transaction-details/bridge-activity-item-tx-segments.tsx
Labels: team-swaps-and-bridge

#31838 chore: bump institutional snap version
  package.json
  yarn.lock
Labels: team-identity

#31850 fix: filter NFTs on send flow
  test/e2e/tests/tokens/nft/send-nft.spec.ts
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-nft-tab.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-nft-tab.tsx
  ui/hooks/useNfts.ts
Labels: team-assets, no-changelog

#31554 chore: mms-1799 native address
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#31816 fix: flatten transaction list
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  package.json
  test/e2e/flask/solana/check-balance.spec.ts
  test/e2e/flask/solana/common-solana.ts
  test/e2e/flask/solana/send-flow.spec.ts
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx
  ui/components/app/transaction-list/transaction-list.component.js
  ui/hooks/useMultichainTransactionDisplay.ts
  yarn.lock
Labels: team-solana

#31834 chore: apply lint to e2e spec ts files
  .eslintrc.js
  test/e2e/flask/btc/btc-account-overview.spec.ts
  test/e2e/flask/btc/btc-dapp-connection.spec.ts
  test/e2e/flask/btc/btc-experimental-settings.spec.ts
  test/e2e/flask/btc/btc-send.spec.ts
  test/e2e/flask/btc/create-btc-account.spec.ts
  test/e2e/flask/solana/create-solana-account.spec.ts
  test/e2e/flask/solana/send-flow.spec.ts
  test/e2e/flask/solana/send-spl-token.spec.ts
  test/e2e/flask/solana/transaction-activity-list.spec.ts
  test/e2e/flask/user-operations.spec.ts
  test/e2e/json-rpc/wallet_addEthereumChain.spec.ts
  test/e2e/json-rpc/wallet_revokePermissions.spec.ts
  test/e2e/playwright/swap/specs/swap.spec.ts
  test/e2e/snaps/test-snap-installed.spec.ts
  test/e2e/tests/account/snap-account-signatures.spec.ts
  test/e2e/tests/carousel/carousel.spec.ts
  test/e2e/tests/confirmations/transactions/erc1155-revoke-set-approval-for-all-redesign.ts
  test/e2e/tests/confirmations/transactions/erc1155-set-approval-for-all-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc20-approve-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc20-token-send-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc721-approve-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc721-revoke-set-approval-for-all-redesign.ts
  test/e2e/tests/confirmations/transactions/erc721-set-approval-for-all-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/increase-token-allowance-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/native-send-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/nft-token-send-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/shared.ts
  test/e2e/tests/confirmations/transactions/transaction-decoding-redesign.spec.ts
  test/e2e/tests/content-security-policy/content-security-policy.spec.ts
  test/e2e/tests/privacy/polling.spec.ts
  test/e2e/tests/simulation-details/simulation-details.spec.ts
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
  test/e2e/tests/swaps/swap-eth.spec.ts
Labels: team-qa, skip-e2e-quality-gate

#31861 cherry-pick 12.16.0: filter NFTs on send flow (#31850)
  test/e2e/page-objects/pages/home/nft-list.ts
  test/e2e/tests/tokens/nft/send-nft.spec.ts
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-nft-tab.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-nft-tab.tsx
  ui/hooks/useNfts.ts
Labels: team-assets

#31870 fix: Use DS buttons for `PageContainerFooter`
  test/e2e/snaps/test-snap-managestate.spec.js
  ui/components/app/permission-page-container/permission-page-container-footer.component.tsx
  ui/components/ui/page-container/page-container-footer/__snapshots__/page-container-footer.component.test.js.snap
  ui/components/ui/page-container/page-container-footer/page-container-footer.component.js
  ui/components/ui/page-container/page-container-footer/page-container-footer.component.test.js
  ui/pages/confirm-add-suggested-nft/__snapshots__/confirm-add-suggested-nft.test.js.snap
  ui/pages/confirm-decrypt-message/__snapshots__/confirm-decrypt-message.component.test.js.snap
  ui/pages/confirm-encryption-public-key/__snapshots__/confirm-encryption-public-key.component.test.js.snap
  ui/pages/permissions-connect/permissions-connect.stories.js
  ui/pages/swaps/swaps-footer/__snapshots__/swaps-footer.test.js.snap
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#31782 feat: multi srp banner
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/images/slide-multi-srp-icon.svg
  test/e2e/tests/carousel/carousel.spec.ts
  ui/hooks/useCarouselManagement/constants.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.test.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.ts
Labels: team-accounts

#31513 feat: add is_suggested_name segment property
  app/scripts/lib/snap-keyring/snap-keyring.test.ts
  app/scripts/lib/snap-keyring/snap-keyring.ts
  ui/components/multichain/create-account/create-account.tsx
  ui/components/multichain/import-account/import-account.js
  ui/pages/create-account/connect-hardware/index.js
Labels: team-mmi

#31883 fix: rm commits csv from v12.16.0
  commits.csv
Labels: team-extension-platform

#31849 (cherry-pick) chore: enable multi-srp
  app/scripts/metamask-controller.js
  builds.yml
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/app/srp-quiz-modal/SRPQuiz/SRPQuiz.tsx
  ui/components/app/toast-master/selectors.ts
  ui/components/app/toast-master/toast-master.js
  ui/components/app/toast-master/utils.ts
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/account-details/account-details.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/create-account/create-account.tsx
  ui/components/multichain/create-eth-account/create-eth-account.js
  ui/components/multichain/create-snap-account/create-snap-account.tsx
  ui/components/multichain/index.js
  ui/ducks/app/app.ts
  ui/helpers/constants/routes.ts
  ui/pages/keychains/reveal-seed.js
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
  ui/store/actionConstants.ts
  ui/store/actions.ts
Labels: team-identity

#31320 feat: Load preinstalled Snaps from JSON files
  .depcheckrc.yml
  .github/CODEOWNERS
  app/scripts/background.js
  app/scripts/constants/snaps.ts
  app/scripts/controller-init/snaps/snap-controller-init.test.ts
  app/scripts/controller-init/snaps/snap-controller-init.ts
  app/scripts/controller-init/test/utils.ts
  app/scripts/controller-init/types.ts
  app/scripts/lib/snap-keyring/account-watcher-snap.ts
  app/scripts/lib/snap-keyring/snaps.ts
  app/scripts/metamask-controller.js
  app/scripts/snaps/preinstalled-snaps.ts
  babel.config.js
  builds.yml
  development/build/transforms/import-meta-url.js
  development/webpack/webpack.config.ts
  shared/lib/accounts/bitcoin-wallet-snap.ts
  shared/lib/accounts/solana-wallet-snap.ts
  test/jest/setup.js
Labels: team-snaps-platform

#31896 add extra version lines
  CHANGELOG.md
Labels: INVALID-PR-TEMPLATE, team-qa

#31537 fix: retry gas, dont show unvailable emoji
  ui/pages/confirmations/components/gas-timing/gas-timing.component.js
Labels: team-swaps-and-bridge
