Repository MetaMask/metamask-extension, pull requests merged in 2025-05, with the labels that each got.

#32356 feat: use MetaMask build name for solana cp-12.18.0
  app/scripts/inpage.js
  package.json
  yarn.lock
Labels: team-wallet-standard

#32391 fix: (cp-12.17.1) patch notification services controller
  .yarn/patches/@metamask-notification-services-controller-npm-6.0.0-d0cefeaee1.patch
  package.json
  yarn.lock
Labels: team-assets

#32440 fix: fix non-evm automatic naming cp-12.18.0 (#32122) Cherry-pick
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  shared/lib/accounts/accounts.test.ts
  shared/lib/accounts/accounts.ts
  ui/components/app/whats-new-modal/whats-new-modal.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/create-snap-account/create-snap-account.test.tsx
  ui/components/multichain/create-snap-account/create-snap-account.tsx
  ui/hooks/accounts/useMultichainWalletSnapClient.ts
Labels: team-extension-platform, extension-delivery

#32321 chore: upgrade to v60
  .yarn/patches/@metamask-assets-controllers-npm-60.0.0-7fc404c3fc.patch
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.test.js
  package.json
  ui/components/app/detected-token/detected-token.js
  ui/components/app/modals/convert-token-to-nft-modal/convert-token-to-nft-modal.js
  ui/components/multichain/import-nfts-modal/import-nfts-modal.js
  ui/components/multichain/import-nfts-modal/import-nfts-modal.test.js
  ui/pages/swaps/index.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
  yarn.lock
Labels: team-assets

#32442 fix: (cp-12.17.1) patch notification services controller (#32391)
  .yarn/patches/@metamask-notification-services-controller-npm-6.0.0-d0cefeaee1.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform, extension-delivery

#32392 fix: remove unnecessary method call cp-12.18.0
  ui/components/multichain/account-list-menu/account-list-menu.tsx
Labels: team-wallet-ux

#32448 chore: Remove MULTICHAIN_API feature flag and expose Multichain API on all build types cp-12.18.0 cherry-pick
  app/manifest/v3/chrome.json
  app/scripts/background.js
  app/scripts/inpage.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  builds.yml
  package.json
  yarn.lock
Labels: team-extension-platform, extension-delivery

#31404 feat: show error to user if vault should exist, but is missing
  CHANGELOG.md
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/background.js
  app/scripts/first-time-state.js
  app/scripts/lib/migrator/index.js
  app/scripts/lib/state-corruption-errors.ts
  app/scripts/lib/stores/base-store.ts
  app/scripts/lib/stores/extension-store.test.ts
  app/scripts/lib/stores/extension-store.ts
  app/scripts/lib/stores/indexeddb-store.test.ts
  app/scripts/lib/stores/indexeddb-store.ts
  app/scripts/lib/stores/persistence-manager.test.ts
  app/scripts/lib/stores/persistence-manager.ts
  app/scripts/lib/stores/read-only-network-store.ts
  app/scripts/metamask-controller.js
  app/scripts/ui.js
  development/build/index.js
  jest.config.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/errors.ts
  shared/lib/error-utils.js
  shared/lib/switch-direction.js
  shared/lib/ui-utils.js
  test/helpers/setup-helper.js
  ui/index.js
  ui/store/actions.ts
  yarn.lock
Labels: team-extension-platform

#31669 chore: integrate delegation-controller and delegation-toolkit
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/delegation/delegation-controller-init.test.ts
  app/scripts/controller-init/delegation/delegation-controller-init.ts
  app/scripts/controller-init/messengers/delegation/delegation-controller-messenger.test.ts
  app/scripts/controller-init/messengers/delegation/delegation-controller-messenger.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/lib/delegation/README.md
  shared/lib/delegation/caveat.test.ts
  shared/lib/delegation/caveat.ts
  shared/lib/delegation/caveatBuilder/allowedCalldataBuilder.test.ts
  shared/lib/delegation/caveatBuilder/allowedCalldataBuilder.ts
  shared/lib/delegation/caveatBuilder/allowedMethodsBuilder.test.ts
  shared/lib/delegation/caveatBuilder/allowedMethodsBuilder.ts
  shared/lib/delegation/caveatBuilder/allowedTargetsBuilder.test.ts
  shared/lib/delegation/caveatBuilder/allowedTargetsBuilder.ts
  shared/lib/delegation/caveatBuilder/caveatBuilder.test.ts
  shared/lib/delegation/caveatBuilder/caveatBuilder.ts
  shared/lib/delegation/caveatBuilder/index.ts
  shared/lib/delegation/caveatBuilder/limitedCallsBuilder.test.ts
  shared/lib/delegation/caveatBuilder/limitedCallsBuilder.ts
  shared/lib/delegation/caveatBuilder/redeemerBuilder.test.ts
  shared/lib/delegation/caveatBuilder/redeemerBuilder.ts
  shared/lib/delegation/delegation.test.ts
  shared/lib/delegation/delegation.ts
  shared/lib/delegation/environment.ts
  shared/lib/delegation/execution.test.ts
  shared/lib/delegation/execution.ts
  shared/lib/delegation/index.ts
  shared/lib/delegation/utils.test.ts
  shared/lib/delegation/utils.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/store/actions.ts
  ui/store/controller-actions/delegation-controller.ts
  yarn.lock
Labels: no-changelog, team-vault

#32461 fix: flaky test `Bridge tests Execute multiple bridge transactions`
  test/e2e/page-objects/pages/bridge/quote-page.ts
  test/e2e/tests/bridge/bridge-cross-chain-swap.spec.ts
Labels: flaky tests, team-qa

#32359 fix: cp-12.18.0 use correct networkClientId when switching account
  ui/pages/confirmations/components/confirm/smart-account-tab/account-network/account-network.tsx
  ui/pages/confirmations/hooks/useEIP7702Account.test.ts
  ui/pages/confirmations/hooks/useEIP7702Account.ts
Labels: team-confirmations

#32361 fix: flakiness multi srp mock login
  test/e2e/flask/multi-srp/add-accounts.spec.ts
  test/e2e/flask/multi-srp/common-multi-srp.ts
  test/e2e/flask/multi-srp/import-srp.spec.ts
  test/e2e/flask/multi-srp/settings-reveal-srp.spec.ts
Labels: flaky tests, team-qa

#32450 chore: update release shared workflow ref
  .github/workflows/create-release-pr.yml
Labels: team-dev-ops, no-changelog

#32476 fix: base-x audit issue
  package.json
  yarn.lock
Labels: team-accounts, team-solana

#32397 fix: remove console.log from onboarding settings
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
Labels: team-qa

#32433 chore: rename profile sync hooks and selectors to backup and sync
  test/e2e/tests/identity/account-syncing/onboarding-with-opt-out.spec.ts
  test/e2e/tests/identity/constants.ts
  test/e2e/tests/identity/mocks.ts
  test/e2e/tests/notifications/constants.ts
  ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
  ui/components/app/modals/confirm-turn-off-profile-syncing/confirm-turn-off-profile-syncing.test.tsx
  ui/components/app/modals/turn-on-metamask-notifications/turn-on-metamask-notifications.tsx
  ui/components/multichain/global-menu/global-menu.js
  ui/contexts/identity/index.test.tsx
  ui/contexts/identity/index.tsx
  ui/hooks/identity/useAccountSyncing/useAccountSyncing.ts
  ui/hooks/identity/useAuthentication/useAutoSignIn.ts
  ui/hooks/identity/useBackupAndSync/index.ts
  ui/hooks/identity/useBackupAndSync/useBackupAndSync.test.tsx
  ui/hooks/identity/useBackupAndSync/useBackupAndSync.ts
  ui/hooks/identity/useProfileSyncing/index.ts
  ui/hooks/identity/useProfileSyncing/useProfileSyncing.test.tsx
  ui/hooks/identity/useProfileSyncing/useProfileSyncing.ts
  ui/hooks/useMetametrics.ts
  ui/pages/notifications-settings/notifications-settings-allow-notifications.tsx
  ui/pages/onboarding-flow/creation-successful/creation-successful.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/developer-options-tab/backup-and-sync.test.tsx
  ui/pages/settings/developer-options-tab/backup-and-sync.tsx
  ui/pages/settings/developer-options-tab/developer-options-tab.tsx
  ui/pages/settings/security-tab/delete-metametrics-data-button/delete-metametrics-data-button.test.tsx
  ui/pages/settings/security-tab/metametrics-toggle/metametrics-toggle.tsx
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.test.tsx
  ui/pages/settings/security-tab/profile-sync-toggle/profile-sync-toggle.tsx
  ui/selectors/identity/backup-and-sync.test.ts
  ui/selectors/identity/backup-and-sync.ts
  ui/selectors/identity/profile-syncing.test.ts
  ui/store/actions.ts
Labels: team-identity

#32463 test: add Backup and Sync settings page and related tests
  test/e2e/page-objects/pages/settings/backup-and-sync-settings.ts
  test/e2e/page-objects/pages/settings/settings-page.ts
  test/e2e/tests/identity/account-syncing/backup-and-sync-settings.spec.ts
  ui/components/app/identity/backup-and-sync-features-toggles/backup-and-sync-features-toggles.tsx
  ui/components/app/identity/backup-and-sync-toggle/backup-and-sync-toggle.tsx
Labels: team-qa

#32307 test: remove erroneous `.only` from bridge test
  ui/hooks/bridge/__snapshots__/useTokensWithFiltering.test.ts.snap
  ui/hooks/bridge/useTokensWithFiltering.test.ts
Labels: team-extension-platform

#32159 chore: Update Stake copy to Earn
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/vi/messages.json
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.tsx.snap
  ui/components/multichain/token-list-item/stakeable-link.tsx
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
Labels: type-bug, team-assets, area-design

#32462 feat: add backup sync new components (unused yet)
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/images/slide-backup-and-sync-icon.png
  app/images/turn-on-backup-and-sync.png
  ui/components/app/identity/backup-and-sync-features-toggles/backup-and-sync-features-toggles.test.tsx
  ui/components/app/identity/backup-and-sync-features-toggles/backup-and-sync-features-toggles.tsx
  ui/components/app/identity/backup-and-sync-toggle/backup-and-sync-toggle.test.tsx
  ui/components/app/identity/backup-and-sync-toggle/backup-and-sync-toggle.tsx
  ui/components/app/modals/identity/confirm-turn-on-backup-and-sync-modal/confirm-turn-on-backup-and-sync-modal.test.tsx
  ui/components/app/modals/identity/confirm-turn-on-backup-and-sync-modal/confirm-turn-on-backup-and-sync-modal.tsx
  ui/components/app/modals/identity/confirm-turn-on-backup-and-sync-modal/index.tsx
  ui/components/app/modals/identity/index.tsx
  ui/components/app/modals/identity/turn-on-backup-and-sync-modal/index.tsx
  ui/components/app/modals/identity/turn-on-backup-and-sync-modal/turn-on-backup-and-sync-modal.test.tsx
  ui/components/app/modals/identity/turn-on-backup-and-sync-modal/turn-on-backup-and-sync-modal.tsx
  ui/helpers/constants/routes.ts
  ui/pages/settings/backup-and-sync-tab/backup-and-sync-tab.component.tsx
  ui/pages/settings/backup-and-sync-tab/backup-and-sync-tab.container.ts
  ui/pages/settings/backup-and-sync-tab/backup-and-sync-tab.test.tsx
  ui/pages/settings/backup-and-sync-tab/index.ts
  ui/selectors/identity/backup-and-sync.test.ts
  ui/selectors/identity/backup-and-sync.ts
Labels: team-identity

#32497 fix: base-x audit issue (#32476)
  package.json
  yarn.lock
Labels: team-extension-platform, extension-delivery

#32498 chore: update changelog
  CHANGELOG.md
Labels: extension-delivery

#32364 feat: Sol 306 extension asset details price chart cp-12.18.0
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/asset-chart-empty-state-illustration.png
  ui/pages/asset/asset.scss
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/asset/components/asset-page.tsx
  ui/pages/asset/components/asset-price.tsx
  ui/pages/asset/components/chart/asset-chart-empty-state.tsx
  ui/pages/asset/components/chart/asset-chart-loading.tsx
  ui/pages/asset/components/chart/asset-chart-price.tsx
  ui/pages/asset/components/chart/asset-chart.tsx
  ui/pages/asset/components/chart/chart-tooltip.tsx
  ui/pages/asset/hooks/useChartTimeRanges.test.ts
  ui/pages/asset/hooks/useChartTimeRanges.ts
  ui/pages/asset/hooks/useCurrentPrice.test.ts
  ui/pages/asset/hooks/useCurrentPrice.ts
  ui/pages/asset/hooks/useHistoricalPrices.test.ts
  ui/pages/asset/hooks/useHistoricalPrices.ts
  ui/pages/asset/types/PriceApiTimePeriod.ts
  ui/pages/asset/useHistoricalPrices.ts
  ui/pages/asset/util.test.ts
  ui/pages/asset/util.ts
  ui/selectors/assets.test.ts
Labels: team-solana

#32410 chore: upgrade solana cp-12.18.0
  package.json
  test/e2e/flask/solana/common-solana.ts
  yarn.lock
Labels: team-solana

#32469 fix: text flashing on Solana's "What's New" modal cp-12.18.0
  ui/components/app/whats-new-modal/solana/modal-footer.tsx
Labels: team-solana

#32505 fix: asset chart styles
  ui/pages/asset/asset.scss
  ui/pages/asset/components/chart/asset-chart-empty-state.tsx
Labels: team-solana

#32466 fix: cp-12.18.0 Update reject data on `rejectAllApprovals` utility
  app/scripts/lib/approval/utils.test.ts
  app/scripts/lib/approval/utils.ts
Labels: team-confirmations

#32240 test: Migrate metrics e2e tests to Typescript and Page object modal (part 2)
  test/e2e/page-objects/pages/settings/privacy-settings.ts
  test/e2e/tests/metrics/errors.spec.ts
  test/e2e/tests/metrics/marketing-cookieid.spec.ts
  test/e2e/tests/metrics/metametrics-persistence.spec.ts
  test/e2e/tests/metrics/sessions.spec.ts
Labels: team-qa

#32341 test: Migrate metrics e2e tests to Typescript and Page object modal (part 3)
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/metrics/permissions-approved.spec.ts
  test/e2e/tests/metrics/signature-approved.spec.ts
  test/e2e/tests/metrics/traces.spec.ts
  test/e2e/tests/metrics/transaction-finalized.spec.ts
  test/e2e/tests/metrics/unlock-wallet.spec.ts
Labels: team-qa

#32482 fix: cp-12.17.1 break render‑loop
  ui/hooks/useCarouselManagement/useCarouselManagement.ts
Labels: team-extension-platform

#32076 feat: Add RPC (sub)domain tracking to transaction event metrics for RPC endpoints usage
  CHANGELOG.md
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/lib/util.test.js
  app/scripts/lib/util.ts
  app/scripts/metamask-controller.js
  shared/lib/network-utils.ts
  shared/modules/metametrics.test.ts
  shared/types/metametrics.ts
Labels: team-confirmations, team-transactions

#31283 test: migrate insufficient funds test to POM
  test/e2e/page-objects/pages/confirmations/redesign/alert-modal.ts
  test/e2e/tests/confirmations/alerts/insufficient-funds.spec.ts
Labels: team-qa

#32129 feat: profile sync > backup and sync redesign
  CHANGELOG.md
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/page-objects/pages/error-page.ts
  test/e2e/page-objects/pages/settings/backup-and-sync-settings.ts
  test/e2e/page-objects/pages/settings/settings-page.ts
  test/e2e/tests/carousel/carousel.spec.ts
  test/e2e/tests/identity/account-syncing/backup-and-sync-settings.spec.ts
  test/e2e/tests/metrics/developer-options-sentry.spec.ts
  test/e2e/tests/remote-feature-flag/remote-feature-flag.spec.ts
  ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
  ui/components/app/identity/backup-and-sync-features-toggles/backup-and-sync-features-toggles.tsx
  ui/components/app/identity/backup-and-sync-toggle/backup-and-sync-toggle.test.tsx
  ui/components/app/identity/backup-and-sync-toggle/backup-and-sync-toggle.tsx
  ui/components/app/modals/confirm-turn-off-profile-syncing/confirm-turn-off-profile-syncing.test.tsx
  ui/components/app/modals/confirm-turn-off-profile-syncing/confirm-turn-off-profile-syncing.tsx
  ui/components/app/modals/confirm-turn-off-profile-syncing/index.ts
  ui/components/app/modals/identity/confirm-turn-on-backup-and-sync-modal/index.ts
  ui/components/app/modals/identity/turn-on-backup-and-sync-modal/index.ts
  ui/components/app/modals/modal.js
  ui/components/multichain/account-overview/account-overview-layout.tsx
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/hooks/identity/useAccountSyncing/useAccountSyncing.test.tsx
  ui/hooks/identity/useAccountSyncing/useAccountSyncing.ts
  ui/hooks/useCarouselManagement/constants.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.test.ts
  ui/hooks/useCarouselManagement/useCarouselManagement.ts
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/developer-options-tab/backup-and-sync.test.tsx
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/profile-sync-toggle/index.ts
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-identity

#32514 fix: base-x audit issue (#32476)
  package.json
  yarn.lock
Labels: extension-delivery

#28110 test: Add e2e tests for privacy check when advanced assets privacy settings toggle set to off during onboarding
  test/e2e/tests/privacy/advanced-functionality-privacy.spec.ts
Labels: team-extension-platform, e2e-test, team-qa

#32519 chore: Update v12.17.1 changelog
  CHANGELOG.md
Labels: team-wallet-framework

#32423 feat. 12.17.1
  .yarn/patches/@metamask-notification-services-controller-npm-6.0.0-d0cefeaee1.patch
  CHANGELOG.md
  attribution.txt
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  ui/hooks/useCarouselManagement/useCarouselManagement.ts
  yarn.lock
Labels: team-extension-platform, extension-delivery

#32447 chore: removing connection badge
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/badge-status/__snapshots__/badge-status.test.js.snap
  ui/components/multichain/badge-status/badge-status.test.js
  ui/components/multichain/badge-status/badge-status.tsx
  ui/components/multichain/badge-status/badge-status.types.tsx
  ui/components/multichain/connected-status/connected-status.tsx
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.tsx
  ui/pages/permissions-connect/connect-page/__snapshots__/connect-page.test.tsx.snap
  ui/pages/permissions-connect/connect-page/connect-page.tsx
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#32493 test: migrate benchmark tests to anvil and remove more ganache old references
  .github/workflows/run-benchmarks.yml
  test/e2e/benchmark.mjs
  test/e2e/flask/multichain-api/testHelpers.ts
  test/e2e/helpers.js
  test/e2e/json-rpc/eth_newBlockFilter.spec.ts
  test/e2e/tests/confirmations/helpers.ts
  test/e2e/tests/confirmations/transactions/contract-deployment-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/contract-interaction-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc20-approve-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc721-approve-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/increase-token-allowance-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/metrics.spec.ts
  test/e2e/tests/confirmations/transactions/revoke-allowance-redesign.spec.ts
  test/e2e/tests/network/chain-interactions.spec.js
  test/e2e/tests/network/custom-rpc-history.spec.js
  test/e2e/tests/onboarding/onboarding.spec.ts
  test/e2e/tests/request-queuing/ui.spec.js
  test/e2e/tests/swap-send/swap-send-erc20.spec.ts
  test/e2e/tests/swap-send/swap-send-test-utils.ts
  test/e2e/user-actions-benchmark.ts
Labels: team-qa, skip-e2e-quality-gate, no-changelog

#32024 feat: Remove failed transaction retry icon button
  CHANGELOG.md
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.test.js
  ui/components/app/transaction-list-item/transaction-list-item.component.js
Labels: team-confirmations

#32432 build: update Node and Yarn
  .circleci/config.yml
  .github/workflows/run-e2e.yml
  .nvmrc
  development/generate-attributions/package.json
  lavamoat/build-system/policy.json
  package.json
Labels: team-extension-platform, no-changelog

#32506 feat: Sol 306 extension asset details price chart cp-12.18.0 (#32364) Cherry-pick
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/asset-chart-empty-state-illustration.png
  ui/pages/asset/asset.scss
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/asset/components/asset-page.tsx
  ui/pages/asset/components/asset-price.tsx
  ui/pages/asset/components/chart/asset-chart-empty-state.tsx
  ui/pages/asset/components/chart/asset-chart-loading.tsx
  ui/pages/asset/components/chart/asset-chart-price.tsx
  ui/pages/asset/components/chart/asset-chart.tsx
  ui/pages/asset/components/chart/chart-tooltip.tsx
  ui/pages/asset/hooks/useChartTimeRanges.test.ts
  ui/pages/asset/hooks/useChartTimeRanges.ts
  ui/pages/asset/hooks/useCurrentPrice.test.ts
  ui/pages/asset/hooks/useCurrentPrice.ts
  ui/pages/asset/hooks/useHistoricalPrices.test.ts
  ui/pages/asset/hooks/useHistoricalPrices.ts
  ui/pages/asset/types/PriceApiTimePeriod.ts
  ui/pages/asset/useHistoricalPrices.ts
  ui/pages/asset/util.test.ts
  ui/pages/asset/util.ts
  ui/selectors/assets.test.ts
Labels: team-extension-platform, extension-delivery

#32520 chore: update minimum browser versions to Chrome 109 and Firefox 102
  app/manifest/v2/chrome.json
  app/manifest/v2/firefox.json
  app/manifest/v3/chrome.json
  app/manifest/v3/firefox.json
  ui/helpers/constants/common.ts
  ui/helpers/utils/util.test.js
Labels: team-extension-platform

#32487 fix: cp-12.18.0 swap/bridge tx submission fails for discovered solana accounts
  package.json
  yarn.lock
Labels: skip-e2e-quality-gate, team-swaps-and-bridge

#32387 fix: cp-12.18.0 bridge activity log doesn't update and may show incorrect token amounts
  app/scripts/metamask-controller.js
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/hooks/useTransactionDisplayData.js
  ui/pages/bridge/hooks/useBridgeTokenDisplayData.ts
Labels: skip-e2e-quality-gate, team-swaps-and-bridge

#32485 fix: cp-12.18.0 prevent bridge confirmation if user doesn't have enough balance
  ui/ducks/bridge/selectors.ts
  ui/hooks/bridge/__snapshots__/useTokensWithFiltering.test.ts.snap
  ui/hooks/bridge/useLatestBalance.ts
  ui/hooks/bridge/useTokensWithFiltering.ts
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/prepare/types.ts
Labels: skip-e2e-quality-gate, team-swaps-and-bridge

#32504 fix: cp-12.18.0 fix new NFT state with chainId
  app/scripts/migrations/156.test.ts
  app/scripts/migrations/156.ts
  app/scripts/migrations/index.js
  ui/components/app/assets/nfts/nft-grid/nft-grid.tsx
Labels: team-assets

#32365 fix: handle network change to fix custom RPC selection
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/components/multichain/network-list-menu/select-rpc-url-modal/select-rpc-url-modal.test.tsx
  ui/components/multichain/network-list-menu/select-rpc-url-modal/select-rpc-url-modal.tsx
Labels: team-confirmations

#32515 chore: update profile sync > backup and sync in CODEOWNERS
  .github/CODEOWNERS
Labels: team-identity

#32545 test: skip solana
  test/e2e/flask/solana-wallet-standard/connect.spec.ts
  test/e2e/tests/solana/send-flow.spec.ts
  test/e2e/tests/solana/solana-networks.spec.ts
  test/e2e/tests/solana/transaction-activity-list.spec.ts
Labels: team-qa

#32552 fix: cp-12.18: missing network `MegaETH`
  app/scripts/metamask-controller.js
Labels: release-blocker, QA Passed, needs-dev-review, team-network-enablement, release-12.18.0, regression-RC-12.18.0

#32547 fix: patch increase incoming trx polling
  .yarn/patches/@metamask-transaction-controller-patch-47fbbc917e.patch
  package.json
  yarn.lock
Labels: team-confirmations

#32532 chore: master sync v12.17.1
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#32557 chore: upgrade solana cp-12.18.0 (#32410)
  package.json
  test/e2e/flask/solana/common-solana.ts
  yarn.lock
Labels: team-extension-platform

#32560 fix: cp-12.18: missing network `MegaETH` (#32552)
  app/scripts/metamask-controller.js
Labels: team-extension-platform, extension-delivery

#32161 style: Update button color and hover state
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/index.scss
  ui/components/ui/icon-button/icon-button.js
  ui/components/ui/icon-button/icon-button.scss
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/asset/components/token-buttons.tsx
Labels: team-assets

#32559 feat(ramps): cp-12.18.0 use ramp api to determine solana buyability (#32431)
  ui/components/app/wallet-overview/non-evm-overview.test.tsx
  ui/components/app/wallet-overview/non-evm-overview.tsx
  ui/ducks/ramps/ramps.test.ts
  ui/ducks/ramps/ramps.ts
  ui/helpers/ramps/rampApi/rampAPI.ts
  ui/hooks/ramps/useRamps/useRamps.test.tsx
  ui/hooks/ramps/useRamps/useRamps.ts
  ui/pages/confirmations/hooks/useConfirmationAlertActions.test.ts
  ui/selectors/selectors.js
Labels: team-extension-platform, extension-delivery

#32284 feat: solana code-fence features in main cp-12.18.0
  .github/workflows/run-e2e.yml
  builds.yml
  test/e2e/flask/solana-wallet-standard/connect.spec.ts
  test/e2e/flask/solana-wallet-standard/signMessage.spec.ts
  test/e2e/flask/solana-wallet-standard/testHelpers.ts
  test/e2e/flask/solana-wallet-standard/transaction_sol.spec.ts
  test/e2e/flask/solana-wallet-standard/transaction_wsol.spec.ts
  test/e2e/page-objects/pages/account-list-page.ts
  test/e2e/page-objects/pages/home/activity-list.ts
  test/e2e/page-objects/pages/home/non-evm-homepage.ts
  test/e2e/page-objects/pages/send/solana-send-page.ts
  test/e2e/tests/carousel/carousel.spec.ts
  test/e2e/tests/identity/account-syncing/backup-and-sync-settings.spec.ts
  test/e2e/tests/identity/account-syncing/importing-private-key-account.spec.ts
  test/e2e/tests/identity/account-syncing/new-user-sync.spec.ts
  test/e2e/tests/identity/account-syncing/onboarding-with-opt-out.spec.ts
  test/e2e/tests/identity/account-syncing/sync-after-adding-account.spec.ts
  test/e2e/tests/identity/account-syncing/sync-after-modifying-account-name.spec.ts
  test/e2e/tests/identity/account-syncing/sync-after-onboarding.spec.ts
  test/e2e/tests/identity/account-syncing/sync-with-account-balances.spec.ts
  test/e2e/tests/metrics/errors.spec.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/solana/check-balance.spec.ts
  test/e2e/tests/solana/common-solana.ts
  test/e2e/tests/solana/create-solana-account.spec.ts
  test/e2e/tests/solana/send-flow.spec.ts
  test/e2e/tests/solana/send-spl-token.spec.ts
  test/e2e/tests/solana/solana-networks.spec.ts
  test/e2e/tests/solana/switching-network-accounts.spec.ts
  test/e2e/tests/solana/transaction-activity-list.spec.ts
Labels: team-solana, skip-e2e-quality-gate

#32526 feat: better test reports
  .github/scripts/create-e2e-test-report.ts
  .github/scripts/create-flaky-test-report.ts
  .github/scripts/get-job-id.ts
  .github/scripts/shared/test-reports.ts
  .github/workflows/e2e-chrome.yml
  .github/workflows/e2e-firefox.yml
  .github/workflows/run-e2e.yml
  package.json
  yarn.lock
Labels: team-extension-platform, no-changelog

#32528 cherry-pick fix: smart account splash 3rd title copy
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.tsx
Labels: team-confirmations

#32553 feat: update backup and sync settings events
  ui/components/app/identity/backup-and-sync-features-toggles/backup-and-sync-features-toggles.test.tsx
  ui/components/app/identity/backup-and-sync-features-toggles/backup-and-sync-features-toggles.tsx
  ui/components/app/identity/backup-and-sync-toggle/backup-and-sync-toggle.test.tsx
  ui/components/app/identity/backup-and-sync-toggle/backup-and-sync-toggle.tsx
Labels: team-identity

#32530 chore: remove `navigator.locks` polyfill now that native browser support is available
  app/scripts/lib/stores/persistence-manager.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
Labels: team-extension-platform

#32558 fix: cp-12.18 track swap events
  shared/constants/metametrics.ts
  ui/hooks/bridge/useBridging.ts
Labels: team-swaps-and-bridge

#32521 chore(deps): bump @metamask/message-signing-snap to v1.1.2
  package.json
  yarn.lock
Labels: release-12.18.0, team-readable-permissions

#32484 chore: consolidate bridge token image logic
  ui/ducks/bridge/bridge.ts
  ui/ducks/bridge/selectors.ts
  ui/ducks/bridge/types.ts
  ui/hooks/bridge/useBridging.ts
  ui/hooks/bridge/useTokensWithFiltering.test.ts
  ui/hooks/bridge/useTokensWithFiltering.ts
  ui/pages/bridge/prepare/bridge-input-group.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/prepare/types.ts
Labels: team-swaps-and-bridge

#32576 fix: reverts evm transaction ordering to preserve nonce ordering
  ui/components/app/transaction-list/transaction-list.component.js
Labels: team-swaps-and-bridge

#32452 feat: Remote mode design parity updates
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/images/slide-cold-storage.svg
  ui/hooks/useCarouselManagement/constants.ts
  ui/pages/remote-mode/components/daily-allowance-card/remote-mode-daily-allowance-card.component.test.tsx
  ui/pages/remote-mode/components/daily-allowance-card/remote-mode-daily-allowance-card.component.tsx
  ui/pages/remote-mode/components/swap-allowance-card/remote-mode-swap-allowance-card.component.test.tsx
  ui/pages/remote-mode/components/swap-allowance-card/remote-mode-swap-allowance-card.component.tsx
  ui/pages/remote-mode/remote.types.ts
  ui/pages/remote-mode/setup/setup-daily-allowance/remote-mode-setup-daily-allowance.component.tsx
  ui/pages/remote-mode/setup/setup-swaps/remote-mode-setup-swaps.component.tsx
Labels: team-vault

#32445 feat: load compressed snaps
  app/scripts/background.js
  babel.config.js
  development/build/transforms/import-meta-url.js
  development/webpack/webpack.config.ts
Labels: team-accounts

#31775 feat: add support for multi discover network buttons
  shared/constants/network.ts
  ui/components/multichain/network-list-menu/network-list-menu.test.js
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/selectors/selectors.js
Labels: area-customNetworks, area-UI, team-network-enablement

#32269 test: Added test for snap get preferences
  test/e2e/page-objects/pages/test-snaps.ts
  test/e2e/snaps/test-snap-get-preferences.spec.ts
Labels: team-qa

#32508 test: Migrate networks e2e tests to Typescript and Page object modal (part 1)
  test/e2e/page-objects/pages/confirmations/redesign/add-network-confirmations.ts
  test/e2e/page-objects/pages/dialog/add-network-rpc-url.ts
  test/e2e/page-objects/pages/dialog/edit-network.ts
  test/e2e/tests/network/switch-custom-network.spec.js
  test/e2e/tests/network/switch-custom-network.spec.ts
  test/e2e/tests/network/update-network.spec.ts
  test/e2e/tests/safe-window-close.spec.ts
Labels: team-qa, no-changelog

#32095 feat: Show App header only on home page
  ui/pages/routes/routes.component.js
  ui/pages/routes/utils.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#32094 feat: Global menu app header icon update
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#32459 fix: add solana account in dapp connection flow cp-12.18.0
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  test/e2e/flask/multichain-api/testHelpers.ts
  ui/components/app/whats-new-modal/whats-new-modal.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/create-snap-account/create-snap-account.test.tsx
  ui/components/multichain/create-snap-account/create-snap-account.tsx
  ui/components/multichain/edit-accounts-modal/add-account.tsx
  ui/components/multichain/edit-accounts-modal/add-new-account-option.tsx
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.test.tsx
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.tsx
Labels: team-accounts

#27490 docs: fix spelling issues
  docs/confirmation-refactoring/confirmation-page-structure/README.md
  docs/confirmation-refactoring/confirmation-state-management/README.md
  docs/confirmations.md
Labels: external-contributor, INVALID-PR-TEMPLATE

#32548 fix: cp-12.18.0 Infinite loader on `approve` request
  test/integration/confirmations/transactions/erc20-approve.test.tsx
  test/integration/confirmations/transactions/increase-allowance.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-is-nft.test.ts
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-is-nft.ts
Labels: team-confirmations

#31403 test: add tests for nft filtering
  test/e2e/page-objects/pages/home/nft-list.ts
  test/e2e/tests/tokens/nft/filter-nfts.spec.ts
  test/integration/data/integration-init-state.json
  test/integration/nfts/nfts.test.tsx
Labels: team-qa

#32346 fix: add genesys logo
  app/images/genesys.svg
  shared/constants/network.ts
Labels: team-assets

#27318 chore: Remove unused `getConnectedSnapsList` function
  ui/selectors/selectors.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#32585 chore: cherry-pick fix: cp-12.18 smart account splash 3rd title copy (#32528)
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.tsx
Labels: team-confirmations

#32551 test: Migrates settings e2e tests to Typescript and Page object modal (part 1)
  test/e2e/page-objects/pages/home/asset-list.ts
  test/e2e/page-objects/pages/home/homepage.ts
  test/e2e/page-objects/pages/settings/about-page.ts
  test/e2e/page-objects/pages/settings/advanced-settings.ts
  test/e2e/page-objects/pages/settings/settings-page.ts
  test/e2e/tests/settings/about-metamask-ui-validation.spec.ts
  test/e2e/tests/settings/show-native-as-main-balance.spec.ts
  test/e2e/tests/settings/state-logs.spec.js
  test/e2e/tests/settings/state-logs.spec.ts
  test/e2e/tests/tokens/custom-token-send-transfer.spec.ts
Labels: team-qa, no-changelog

#32574 chore: Master sync v12.17.2
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery

#32596 feat: restore OneKey under QR connection list
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/create-account/connect-hardware/select-hardware.js
Labels: team-hardware-wallets

#32434 chore: bump @metamask/bridge-controller to ^20.0.0
  .storybook/test-data.js
  app/scripts/constants/sentry-state.ts
  app/scripts/metamask-controller.js
  package.json
  test/data/bridge/mock-bridge-store.ts
  test/e2e/default-fixture.js
  test/e2e/fixture-builder.js
  test/e2e/mock-e2e.js
  test/e2e/mock-response-data/bridge-get-all-feature-flags.json
  test/e2e/tests/bridge/bridge-L2-tests.ts
  test/e2e/tests/bridge/bridge-button-routing.spec.ts
  test/e2e/tests/bridge/bridge-cross-chain-swap.spec.ts
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/bridge/constants.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/e2e/tests/privacy/advanced-functionality-privacy.spec.ts
  test/e2e/tests/swap-send/swap-send-eth-with-loaded-state.spec.ts
  test/e2e/user-actions-benchmark.ts
  test/integration/data/integration-init-state.json
  test/integration/data/onboarding-completion-route.json
  test/integration/onboarding/import-wallet.test.tsx
  test/integration/onboarding/wallet-created.test.tsx
  test/jest/mock-store.js
  ui/components/app/wallet-overview/eth-overview.test.js
  ui/components/app/wallet-overview/non-evm-overview.test.tsx
  ui/components/multichain/account-overview/account-overview-eth.test.tsx
  ui/components/multichain/account-overview/account-overview-non-evm.test.tsx
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
  ui/hooks/bridge/useBridging.test.ts
  ui/hooks/bridge/useBridging.ts
  ui/hooks/bridge/useTokenAlerts.ts
  ui/hooks/bridge/useTokensWithFiltering.ts
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/bridge/hooks/useAddToken.ts
  ui/pages/bridge/hooks/useBridgeTokenDisplayData.ts
  ui/pages/bridge/hooks/useExternalAccountResolution.ts
  ui/pages/bridge/index.test.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/prepare/types.ts
  ui/pages/bridge/transaction-details/bridge-activity-item-tx-segments.tsx
  ui/pages/bridge/transaction-details/bridge-step-description.tsx
  ui/pages/bridge/transaction-details/bridge-step-list.tsx
  ui/pages/bridge/transaction-details/transaction-details.test.tsx
  ui/pages/bridge/transaction-details/transaction-details.tsx
  ui/pages/routes/routes.component.test.js
  ui/selectors/selectors.js
  yarn.lock
Labels: team-swaps-and-bridge

#32613 fix: flaky test `Smart Transactions Swap` due to incorrect quote take…
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
  test/e2e/tests/swaps/shared.ts
Labels: team-qa

#32601 chore: bump profile-sync-controller to 13.0.0
  package.json
  yarn.lock
Labels: team-identity

#32609 feat(INFRA-2510): post rca team and regression
  .github/workflows/automated-rca.yml
Labels: team-dev-ops

#32595 fix: update logo to have non transparent background
  app/images/lens.png
Labels: team-network-enablement, release-12.19.0

#32603 chore: Make deprecated category property optional
  app/scripts/controllers/metametrics-controller.test.ts
  app/scripts/controllers/metametrics-controller.ts
  shared/constants/metametrics.ts
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#31835 fix: Define type for flattened background state, and update types for Redux store, `metamask` slice
  shared/types/background.spec.ts
  shared/types/background.ts
  shared/types/index.ts
  ui/components/app/snaps/snap-ui-renderer/components/asset-selector.test.ts
  ui/components/app/snaps/snap-ui-renderer/test-utils.tsx
  ui/components/app/toast-master/selectors.ts
  ui/components/app/toast-master/toast-master.test.ts
  ui/components/app/toast-master/utils.ts
  ui/components/multichain/pages/send/components/account-picker.test.tsx
  ui/components/ui/qr-code-view/qr-code-view.tsx
  ui/ducks/metamask/types.ts
  ui/store/store.ts
Labels: team-extension-platform

#32631 fix: patch increase incoming trx polling
  .yarn/patches/@metamask-transaction-controller-npm-54.3.0-2c90b81511.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-confirmations

#32626 fix: Fixing z-index of splash screen
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.scss
Labels: team-confirmations

#32583 chore: never emit `Dapp Viewed` events on Firefox
  app/scripts/lib/util.test.js
  app/scripts/lib/util.ts
  test/e2e/tests/metrics/dapp-viewed.spec.ts
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#32534 chore: master sync v12.17.1 & v12.17.2
  .yarn/patches/@metamask-transaction-controller-npm-54.3.0-2c90b81511.patch
  CHANGELOG.md
  attribution.txt
  package.json
  ui/hooks/useCarouselManagement/useCarouselManagement.ts
  yarn.lock
Labels: team-extension-platform, extension-delivery

#32635 fix: make phishing warning events anonymous cp-12.17.3
  app/scripts/background.js
  app/scripts/metamask-controller.js
Labels: INVALID-PR-TEMPLATE, team-product-safety

#32615 build: update `@metamask/notification-services-controller` to `^7.0.0`
  .yarn/patches/@metamask-notification-services-controller-npm-6.0.0-d0cefeaee1.patch
  package.json
  yarn.lock
Labels: team-assets

#32642 fix: cp-12.18.0 Clear unencrypted Snap state properly
  .yarn/patches/@metamask-snaps-controllers-npm-11.2.3-06777e0090.patch
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#32455 feat(remote-mode): sign, store and revoke delegations
  app/scripts/controller-init/delegation/delegation-controller-init.test.ts
  app/scripts/controller-init/delegation/delegation-controller-init.ts
  app/scripts/controller-init/messengers/delegation/delegation-controller-messenger.ts
  app/scripts/controller-init/messengers/index.ts
  shared/lib/delegation/caveatBuilder/allowedCalldataBuilder.test.ts
  shared/lib/delegation/caveatBuilder/allowedMethodsBuilder.test.ts
  shared/lib/delegation/caveatBuilder/allowedTargetsBuilder.test.ts
  shared/lib/delegation/caveatBuilder/caveatBuilder.test.ts
  shared/lib/delegation/caveatBuilder/limitedCallsBuilder.test.ts
  shared/lib/delegation/caveatBuilder/redeemerBuilder.test.ts
  shared/lib/delegation/delegation.test.ts
  shared/lib/delegation/delegation.ts
  shared/lib/delegation/environment.ts
  shared/lib/delegation/utils.ts
  test/data/mock-state.json
  ui/pages/remote-mode/hooks/useRemoteMode.test.tsx
  ui/pages/remote-mode/hooks/useRemoteMode.ts
  ui/pages/remote-mode/overview/remote-mode-overview.container.tsx
  ui/pages/remote-mode/overview/remote-mode-overview.stories.tsx
  ui/pages/remote-mode/overview/remote-mode-permissions.component.tsx
  ui/pages/remote-mode/overview/remote-mode-permissions.test.tsx
  ui/pages/remote-mode/remote.types.ts
  ui/pages/remote-mode/setup/setup-daily-allowance/remote-mode-setup-daily-allowance.component.test.tsx
  ui/pages/remote-mode/setup/setup-daily-allowance/remote-mode-setup-daily-allowance.component.tsx
  ui/pages/remote-mode/setup/setup-daily-allowance/remote-mode-setup-daily-allowance.stories.tsx
  ui/pages/remote-mode/setup/setup-swaps/remote-mode-setup-swaps.component.test.tsx
  ui/pages/remote-mode/setup/setup-swaps/remote-mode-setup-swaps.component.tsx
  ui/pages/remote-mode/setup/setup-swaps/remote-mode-setup-swaps.stories.tsx
  ui/selectors/delegation.test.ts
  ui/selectors/delegation.ts
  ui/selectors/remote-mode.test.ts
  ui/selectors/remote-mode.ts
  ui/store/controller-actions/delegation-controller.ts
Labels: team-vault

#32674 chore: never emit `Dapp Viewed` events on Firefox (#32583) cp-12.17.3
  app/scripts/lib/util.test.js
  app/scripts/lib/util.ts
  test/e2e/tests/metrics/dapp-viewed.spec.js
Labels: team-extension-platform, extension-delivery

#32471 build: bitcoin support
  builds.yml
  package.json
  yarn.lock
Labels: team-accounts

#32675 fix: make phishing warning events anonymous cp-12.17.3 (#32635)
  app/scripts/background.js
  app/scripts/metamask-controller.js
Labels: team-extension-platform, extension-delivery

#32649 fix: Ensure only EVM networks are selected by default for `eth_requestAccounts` and `wallet_requestPermission` requests
  app/scripts/metamask-controller.js
  ui/pages/permissions-connect/connect-page/connect-page.tsx
Labels: team-wallet-api-platform

#32586 chore: cp-12.18.0 modify multichain api `chain_id` event property logic
  app/scripts/controllers/metametrics-controller.ts
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  shared/constants/metametrics.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  test/e2e/tests/metrics/permissions-approved.spec.ts
  test/e2e/tests/metrics/signature-approved.spec.ts
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#32684 fix: cp-12.18.0 solana bug on account list item
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.test.js
Labels: team-assets

#32695 fix: update solana 1.26.1 cp-12.18.0
  package.json
  yarn.lock
Labels: team-solana

#32571 test: Migrates settings e2e tests to Typescript and Page object modal (part 2)
  test/e2e/page-objects/pages/dialog/terms-of-use-update-modal.ts
  test/e2e/page-objects/pages/settings/contacts-settings.ts
  test/e2e/page-objects/pages/settings/settings-page.ts
  test/e2e/tests/settings/localization.spec.ts
  test/e2e/tests/settings/settings-search.spec.js
  test/e2e/tests/settings/settings-search.spec.ts
  test/e2e/tests/settings/terms-of-use.spec.js
  test/e2e/tests/settings/terms-of-use.spec.ts
Labels: team-qa, no-changelog

#32679 fix: (cp-12.18.0) solana devnet non-native asset view should disable swap and bridge
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/asset/components/token-buttons.tsx
Labels: team-assets

#32670 fix: check if its an ethereum account before adding the prefix cp-12.18.0
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/account-details/account-details-display.test.tsx
  ui/components/multichain/account-details/account-details.tsx
Labels: team-solana

#32717 fix: (cp-12.18.0) solana devnet non-native asset view should disable swap and bridge (#32679)
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/asset/components/token-buttons.tsx
Labels: team-assets

#32712 cherry-pick: Ensure only EVM networks are selected by default for `eth_requestAccounts` and `wallet_requestPermission` requests (#32649)
  app/scripts/metamask-controller.js
  ui/pages/permissions-connect/connect-page/connect-page.tsx
Labels: team-wallet-api-platform

#32710 cherry-pick: Modify Multichain API analytics property (#32380)
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
Labels: team-wallet-api-platform

#32176 chore: UnifiedSwapBridge events
  app/scripts/metamask-controller.js
  ui/ducks/bridge/actions.ts
  ui/hooks/bridge/useBridging.test.ts
  ui/hooks/bridge/useBridging.ts
  ui/pages/bridge/index.test.tsx
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/quotes/bridge-quote-card.tsx
  ui/pages/bridge/quotes/bridge-quotes-modal.tsx
  ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx
Labels: team-swaps-and-bridge

#32511 ci: do not cancel in progress for main/master
  .github/workflows/check-pr-labels.yml
  .github/workflows/cla.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/identify-codeowners.yml
  .github/workflows/main.yml
  .github/workflows/security-code-scanner.yml
Labels: team-extension-platform, no-changelog

#32711 cherry-pick: modify multichain api `chain_id` event property logic (#32586)
  app/scripts/controllers/metametrics-controller.ts
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  shared/constants/metametrics.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  test/e2e/tests/metrics/permissions-approved.spec.js
  test/e2e/tests/metrics/signature-approved.spec.js
Labels: team-wallet-api-platform

#31959 feat: add networks to global menu
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/connected-site-popover/connected-site-popover.tsx
  ui/components/multichain/global-menu/global-menu.js
  ui/components/multichain/network-list-item/index.scss
  ui/components/multichain/network-list-item/network-list-item.tsx
  ui/components/multichain/network-list-menu/network-list-menu.test.js
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/ducks/app/app.ts
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-wallet-ux

#32154 style: Fix text-field border radius to match Figma
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/snaps/snap-ui-renderer/__snapshots__/snap-ui-renderer.test.js.snap
  ui/components/app/snaps/snap-ui-renderer/components/__snapshots__/form.test.ts.snap
  ui/components/component-library/form-text-field/__snapshots__/form-text-field.test.tsx.snap
  ui/components/component-library/text-field-search/__snapshots__/text-field-search.test.tsx.snap
  ui/components/component-library/text-field/__snapshots__/text-field.test.tsx.snap
  ui/components/component-library/text-field/text-field.tsx
  ui/components/multichain/import-account/__snapshots__/json.test.tsx.snap
  ui/components/ui/form-combo-field/__snapshots__/form-combo-field.test.tsx.snap
  ui/pages/bridge/__snapshots__/index.test.tsx.snap
  ui/pages/bridge/prepare/__snapshots__/prepare-bridge-page.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/__snapshots__/edit-spending-cap-modal.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/create-named-snap-account.test.js.snap
  ui/pages/keychains/__snapshots__/reveal-seed.test.js.snap
  ui/pages/swaps/list-with-search/__snapshots__/list-with-search.test.js.snap
Labels: type-bug, team-assets, area-design

#32705 fix: fix sol redirection to explorer
  ui/pages/asset/components/native-asset.tsx
Labels: team-assets

#32714 fix: (cp-12.18.0) re-initialise dom purify after startup
  ui/pages/notifications/notification-components/feature-announcement/feature-announcement.tsx
Labels: team-assets

#32593 fix: Suppress alert when contract detection fails in `useNonContractAddressAlerts`
  ui/pages/confirmations/hooks/alerts/transactions/useNonContractAddressAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useNonContractAddressAlerts.ts
Labels: team-confirmations

#32726 fix: update solana 1.26.1 cp-12.18.0 (#32695) cherry-pick
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: extension-delivery

#32720 chore: comment cleanup
  ui/pages/asset/components/token-buttons.tsx
Labels: team-assets

#32658 fix: cp-12.17.3 fix repeated re-rendering of approve row in simulations section
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/batch-simulation-details.tsx
  ui/pages/confirmations/components/confirm/info/hooks/useBatchApproveBalanceChanges.ts
Labels: team-confirmations

#32673 fix: cp-12.18.0 Fix test of alert displayed of selected currency is different from currency of confirmation
  ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.ts
Labels: team-confirmations

#32678 chore: disable Solana Testnet and Devnet cp-12.18.0
  shared/modules/selectors/networks.ts
  ui/selectors/multichain/networks.ts
Labels: team-accounts

#32690 fix: account sorting for snap accounts that derive entropySource cp-12.18.0
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-accounts

#32738 fix: prevent removing solana accounts cp-12.18.0
  test/e2e/tests/solana/create-solana-account.spec.ts
  ui/components/multichain/account-list-item/account-list-item.js
Labels: team-solana

#31509 test: set prague as default hardfork
  test/e2e/flask/multichain-api/testHelpers.ts
  test/e2e/helpers.js
  test/e2e/json-rpc/eth_call.spec.ts
  test/e2e/json-rpc/eth_gasPrice.spec.ts
  test/e2e/seeder/anvil.ts
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/confirmations/helpers.ts
  test/e2e/tests/confirmations/transactions/contract-deployment-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/contract-interaction-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc20-approve-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc721-approve-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/increase-token-allowance-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/metrics.spec.ts
  test/e2e/tests/confirmations/transactions/revoke-allowance-redesign.spec.ts
  test/e2e/tests/hardware-wallets/trezor-send.spec.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/swaps.spec.js
  test/e2e/tests/tokens/custom-token-send-transfer.spec.ts
  test/e2e/tests/tokens/nft/remove-erc1155.spec.ts
  test/e2e/tests/tokens/nft/remove-nft.spec.ts
  test/e2e/tests/tokens/nft/send-nft.spec.ts
  test/e2e/tests/tokens/nft/view-erc1155-details.spec.ts
  test/e2e/tests/tokens/nft/view-nft-details.spec.ts
  test/e2e/tests/transaction/gas-estimates.spec.js
  test/e2e/tests/transaction/send-edit.spec.js
  test/e2e/tests/transaction/send-eth.spec.js
Labels: team-qa, skip-e2e-quality-gate

#32677 feat: upgrade assets controller
  .yarn/patches/@metamask-assets-controllers-npm-61.0.0-4c5dc448b3.patch
  package.json
  yarn.lock
Labels: team-assets, INVALID-PR-TEMPLATE

#31089 feat: Auto-failover to Quicknode when Infura is down
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/lib/network-controller/messenger-action-handlers.test.ts
  app/scripts/lib/network-controller/messenger-action-handlers.ts
  app/scripts/lib/network-controller/utils.test.ts
  app/scripts/lib/network-controller/utils.ts
  app/scripts/metamask-controller.js
  app/scripts/migrations/157.test.ts
  app/scripts/migrations/157.ts
  app/scripts/migrations/index.js
  builds.yml
  development/build/config.js
  package.json
  shared/constants/metametrics.ts
  shared/constants/network.ts
  shared/lib/only-keep-host.test.ts
  shared/lib/only-keep-host.ts
  ui/components/multichain/network-list-menu/popular-network-list/popular-network-list.tsx
  ui/components/multichain/network-list-menu/rpc-list-item.tsx
  ui/components/multichain/network-list-menu/select-rpc-url-modal/__snapshots__/select-rpc-url-modal.test.tsx.snap
  ui/hooks/useCarouselManagement/useCarouselManagement.test.ts
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/networks-tab/networks-form/networks-form-state.ts
  ui/pages/settings/networks-tab/networks-form/networks-form.tsx
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/selectors/remote-feature-flags.ts
  ui/selectors/selectors.js
  yarn.lock
Labels: team-wallet-framework

#32758 chore: cp-12.18.0 upgrade solana-wallet-snap to v1.27.0
  package.json
  yarn.lock
Labels: team-assets

#32757 fix: cherry-pick fix sol redirection to explorer (#32705)
  ui/pages/asset/components/native-asset.tsx
Labels: team-assets

#32657 ci: better E2E test splitting
  .circleci/scripts/test-run-e2e-timeout-minutes.ts
  .github/scripts/shared/test-reports.ts
  .github/scripts/shared/utils.ts
  .github/scripts/split-tests-by-timings.ts
  .github/scripts/validate-e2e-page-object-usage.ts
  .github/workflows/e2e-chrome.yml
  .github/workflows/e2e-firefox.yml
  .github/workflows/main.yml
  .github/workflows/needs-e2e.yml
  .github/workflows/repository-health-checks.yml
  .github/workflows/run-e2e.yml
  .github/workflows/update-attributions.yml
  .github/workflows/update-lavamoat-policies.yml
  .vscode/cspell.json
  development/lib/build-type.d.ts
  development/lib/run-command.js
  package.json
  test/e2e/changedFilesUtil.js
  test/e2e/run-all.js
  test/e2e/run-all.ts
  test/e2e/tests/multichain/aggregated-balances.spec.ts
  test/e2e/tests/multichain/asset-list.spec.ts
Labels: team-extension-platform, no-changelog

#32731 fix: cp-12.18.0 graceful fallbacks for no rates
  ui/components/app/assets/token-cell/__snapshots__/token-cell.test.tsx.snap
  ui/components/app/assets/token-cell/cells/token-cell-secondary-display.tsx
  ui/components/app/assets/types.ts
  ui/components/ui/aggregated-balance/aggregated-balance.tsx
  ui/components/ui/aggregated-balance/index.test.tsx
  ui/pages/defi/components/__snapshots__/defi-details-list.test.tsx.snap
  ui/pages/defi/components/__snapshots__/defi-details-page.test.tsx.snap
  ui/pages/routes/routes.component.test.js
  ui/selectors/assets.test.ts
  ui/selectors/assets.ts
Labels: team-assets

#32797 chore: cherry-pick-e0a8b91
  ui/components/app/assets/token-cell/__snapshots__/token-cell.test.tsx.snap
  ui/components/app/assets/token-cell/cells/token-cell-secondary-display.tsx
  ui/components/app/assets/types.ts
  ui/components/ui/aggregated-balance/aggregated-balance.tsx
  ui/components/ui/aggregated-balance/index.test.tsx
  ui/pages/routes/routes.component.test.js
  ui/selectors/assets.test.ts
  ui/selectors/assets.ts
Labels: team-assets

#32808 chore: cp-12.18.0 upgrade solana-wallet-snap to v1.27.0 (#32758) cherry-pick
  package.json
  yarn.lock
Labels: team-extension-platform, extension-delivery

#32752 fix(solana-modal): wait for account syncing before displaying action text
  ui/components/app/whats-new-modal/solana/modal-footer.tsx
  ui/components/app/whats-new-modal/whats-new-modal.test.tsx
Labels: team-solana

#32510 fix: use new loader for nft tab
  ui/components/app/assets/nfts/nft-grid/nft-grid.tsx
  ui/components/app/assets/nfts/nfts-tab/nfts-tab.tsx
Labels: team-assets

#32822 fix: cp-12.18.0 fix currencyRateCheck setting for Solana
  ui/components/app/assets/hooks/useTokenDisplayInfo.tsx
  ui/components/app/assets/token-cell/cells/token-cell-secondary-display.tsx
  ui/components/app/assets/token-cell/token-cell.test.tsx
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/ui/aggregated-balance/aggregated-balance.tsx
  ui/components/ui/aggregated-balance/index.test.tsx
  ui/selectors/multichain.test.ts
  ui/selectors/multichain.ts
Labels: team-assets

#32733 fix: cp-12.17.3 support permit2 approvals in batch simulation
  shared/lib/transactions/approvals.test.ts
  shared/lib/transactions/approvals.ts
  shared/modules/transaction.utils.test.js
  shared/modules/transaction.utils.ts
  test/data/confirmations/token-approve.ts
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/__snapshots__/edit-spending-cap-modal.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.test.ts
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/batch-simulation-details.test.tsx
  ui/pages/confirmations/components/confirm/info/hooks/useBatchApproveBalanceChanges.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useBatchApproveBalanceChanges.ts
Labels: team-confirmations

#32702 fix: Allow for disabled Solana dropdown in network filter
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
Labels: team-assets

#32844 test: Add E2E coverage for `SnapExportUsed` metric
  test/e2e/snaps/test-snap-metrics.spec.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#32617 fix: add hd_entropy_index also for snap accounts
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-mmi

#32662 fix: cp-12.18.0 Improvements in upgrade account confirmation page with nested transactions
  ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/transaction-account-details.test.tsx
  ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/transaction-account-details.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
  ui/pages/confirmations/components/confirm/title/title.test.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/hooks/alerts/transactions/useAccountTypeUpgrade.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useAccountTypeUpgrade.ts
Labels: team-confirmations

#32749 fix: cp-12.18.0 Updated address in Receive Modal
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/ui/qr-code-view/qr-code-view.tsx
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#32823 fix: upgrade solana to v1.28.0 cp-12.18.0
  package.json
  test/e2e/page-objects/pages/home/non-evm-homepage.ts
  test/e2e/page-objects/pages/send/solana-send-page.ts
  test/e2e/tests/solana/common-solana.ts
  test/e2e/tests/solana/send-flow.spec.ts
  test/e2e/tests/solana/send-spl-token.spec.ts
  yarn.lock
Labels: team-solana

#32859 fix(multi-srp): cp-12.18.0 use password input for import srp
  ui/components/multichain/multi-srp/import-srp/import-srp.tsx
Labels: team-mmi

#32697 fix: cp-12.17.3 Remove upgrade rejection persistence
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/lib/transaction/eip5792.test.ts
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/metamask-controller.js
  app/scripts/migrations/152.2.test.ts
  app/scripts/migrations/152.2.ts
  app/scripts/migrations/index.js
  test/e2e/tests/confirmations/transactions/eip7702-eip5792-upgrade-account.spec.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.test.tsx
  ui/pages/confirmations/hooks/useSmartAccountActions.test.ts
  ui/pages/confirmations/hooks/useSmartAccountActions.ts
  ui/store/actions.ts
Labels: team-confirmations, release-12.17.3

#32864 fix: upgrade solana to v1.28.0 cp-12.18.0 (#32823)
  package.json
  test/e2e/page-objects/pages/home/non-evm-homepage.ts
  test/e2e/page-objects/pages/send/solana-send-page.ts
  test/e2e/tests/solana/common-solana.ts
  test/e2e/tests/solana/send-flow.spec.ts
  test/e2e/tests/solana/send-spl-token.spec.ts
  yarn.lock
Labels: team-extension-platform, extension-delivery

#32496 fix: Update visuals on NFT details to polish the page
  ui/components/app/assets/nfts/nft-details/__snapshots__/nft-details.test.js.snap
  ui/components/app/assets/nfts/nft-details/nft-details.tsx
Labels: team-assets

#32871 fix: cp-12.17.3 Remove upgrade rejection persistence (#32697) cherry-pick
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/lib/transaction/eip5792.test.ts
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/metamask-controller.js
  app/scripts/migrations/152.2.test.ts
  app/scripts/migrations/152.2.ts
  app/scripts/migrations/index.js
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/upgrade-cancel-modal.test.tsx
  ui/pages/confirmations/components/confirm/splash/smart-account-update/smart-account-update.test.tsx
  ui/pages/confirmations/hooks/useSmartAccountActions.test.ts
  ui/pages/confirmations/hooks/useSmartAccountActions.ts
  ui/store/actions.ts
Labels: team-extension-platform, extension-delivery
