Repository MetaMask/metamask-extension, pull requests merged in 2025-09, with the labels that each got.

#35486 test: Migrate ppom e2e tests to Page object modal (part 1)
  test/e2e/page-objects/pages/confirmations/redesign/transaction-confirmation.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/ppom/ppom-blockaid-alert-contract-interaction.spec.ts
  test/e2e/tests/ppom/ppom-blockaid-alert-erc20-transfer.spec.ts
Labels: team-qa, no-changelog, size-M

#34958 test: use manifestFlag to disable over-ride of smartTx migration
  app/scripts/migrations/135.ts
  shared/lib/manifestFlags.ts
  test/e2e/fixture-builder.js
  test/e2e/json-rpc/switchEthereumChain.spec.ts
  test/e2e/page-objects/flows/toggle-stx-setting.flow.ts
  test/e2e/tests/bridge/bridge-L2-tests.spec.ts
  test/e2e/tests/bridge/bridge-negative-cases.spec.ts
  test/e2e/tests/bridge/bridge-positive-cases.spec.ts
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/confirmations/transactions/gas-fee-tokens-eip-7702.spec.ts
  test/e2e/tests/metrics/bridge.spec.ts
  test/e2e/tests/swap-send/swap-send-eth-with-loaded-state.spec.ts
  test/e2e/tests/swaps/swap-erc20-with-loaded-state.spec.ts
Labels: team-qa, skip-e2e-quality-gate, no-changelog, size-M

#35525 fix(action): remove useless condition
  .github/scripts/check-template-and-add-labels.ts
Labels: team-extension-platform, size-XS

#35553 Sync v13.3.0 with master
  CHANGELOG.md
  app/scripts/lib/SnapsNameProvider.test.ts
  app/scripts/lib/SnapsNameProvider.ts
  attribution.txt
  privacy-snapshot.json
  test/e2e/tests/petnames/petnames-signatures.spec.ts
  ui/components/app/toast-master/toast-master.js
  ui/components/multichain/network-list-menu/__snapshots__/network-list-menu.test.tsx.snap
  ui/components/multichain/network-list-menu/network-list-menu.test.tsx
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/selectors/dapp.test.ts
  ui/selectors/dapp.ts
Labels: team-extension-platform, extension-delivery

#35563 chore: cp-13.3.0 update solana to 2.3.4
  package.json
  yarn.lock
Labels: team-new-networks, size-XS

#33893 refactor: use `@metamask/eth-qr-keyring`
  .storybook/main.js
  .yarn/patches/@keystonehq-metamask-airgapped-keyring-npm-0.15.2-94dd4b40d7.patch
  app/scripts/background.js
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/app-state-controller.test.ts
  app/scripts/controllers/app-state-controller.ts
  app/scripts/lib/qr-keyring-builder-factory.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  shared/types/background.ts
  test/e2e/default-fixture.js
  test/e2e/fixture-builder.js
  test/e2e/page-objects/pages/hardware-wallet/connect-hardware-wallet-page.ts
  test/e2e/tests/hardware-wallets/qr-account.spec.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/integration/data/onboarding-completion-route.json
  test/stub/keyring-bridge.js
  ui/__mocks__/ethereumjs-util.js
  ui/components/app/qr-hardware-popover/base-reader.js
  ui/components/app/qr-hardware-popover/qr-hardware-popover.js
  ui/components/app/qr-hardware-popover/qr-hardware-sign-request/qr-hardware-sign-request.component.js
  ui/components/app/qr-hardware-popover/qr-hardware-sign-request/reader.js
  ui/components/app/qr-hardware-popover/qr-hardware-wallet-importer/qr-hardware-wallet-importer.component.js
  ui/selectors/selectors.js
  ui/store/actions.ts
  yarn.lock
Labels: team-wallet-framework, size-L

#35383 feat: add e2e tests for trezor ERC721 NFT deployment and management.
  test/e2e/tests/hardware-wallets/trezor/trezor-erc721.spec.ts
Labels: hardware-trezor, team-accounts, e2e-test, size-M

#35463 feat: Ledger forget device e2e tests
  test/e2e/page-objects/pages/hardware-wallet/connect-hardware-wallet-page.ts
  test/e2e/tests/hardware-wallets/ledger/ledger-forget-device.spec.ts
Labels: team-accounts, team-hardware-wallets, e2e-test, size-S

#35580 test: Migrate ppom e2e tests to Page object modal (part 2)
  test/e2e/page-objects/pages/confirmations/redesign/transaction-confirmation.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/ppom/ppom-blockaid-alert-simple-send.spec.ts
  test/e2e/tests/ppom/ppom-blockaid-alert-trade-order-farming.spec.ts
Labels: e2e-test, team-qa, no-changelog, size-M

#35549 feat(INFRA-2847): release candidate generation from release branch
  .github/workflows/check-release-tag.yml
  .github/workflows/tag-release-branch.yml
Labels: team-dev-ops, size-M

#35559 fix: do not change the GNS on wallet_add/switchEthereumChain when the dapp has permissions
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform, size-S

#35536 feat: Add entry points for Add Wallet modal from account list page
  ui/components/multichain-accounts/add-wallet-modal/add-wallet-modal.test.tsx
  ui/components/multichain-accounts/add-wallet-modal/add-wallet-modal.tsx
  ui/components/multichain/pages/page/components/content/index.scss
  ui/pages/multichain-accounts/account-list/account-list.test.tsx
  ui/pages/multichain-accounts/account-list/account-list.tsx
Labels: team-design-system, team-accounts, size-M

#35430 chore: Bump ENS Snap
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform, size-XS

#35307 feat: Add feature flag for gator permissions page
  builds.yml
  shared/modules/environment.test.ts
  shared/modules/environment.ts
  ui/components/multichain/pages/gator-permissions/gator-permissions-page.test.tsx
  ui/components/multichain/pages/gator-permissions/gator-permissions-page.tsx
  ui/pages/routes/routes.component.tsx
Labels: INVALID-PR-TEMPLATE, no-changelog, team-delegation, size-M

#35005 refactor(5557): migrate onboarding/ to react-router-v5-compat
  ui/components/app/flask/experimental-area/experimental-area.js
  ui/pages/onboarding-flow/account-exist/account-exist.test.tsx
  ui/pages/onboarding-flow/account-exist/account-exist.tsx
  ui/pages/onboarding-flow/account-not-found/account-not-found.test.tsx
  ui/pages/onboarding-flow/account-not-found/account-not-found.tsx
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/create-password/create-password.test.js
  ui/pages/onboarding-flow/creation-successful/creation-successful.js
  ui/pages/onboarding-flow/creation-successful/creation-successful.test.js
  ui/pages/onboarding-flow/download-app/download-app.test.tsx
  ui/pages/onboarding-flow/download-app/download-app.tsx
  ui/pages/onboarding-flow/import-srp/import-srp.js
  ui/pages/onboarding-flow/import-srp/import-srp.stories.tsx
  ui/pages/onboarding-flow/import-srp/import-srp.test.js
  ui/pages/onboarding-flow/metametrics/metametrics.js
  ui/pages/onboarding-flow/metametrics/metametrics.test.js
  ui/pages/onboarding-flow/onboarding-app-header/onboarding-app-header.js
  ui/pages/onboarding-flow/onboarding-app-header/onboarding-app-header.test.js
  ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.js
  ui/pages/onboarding-flow/onboarding-flow-switch/onboarding-flow-switch.test.js
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.js
  ui/pages/onboarding-flow/pin-extension/pin-extension.test.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
  ui/pages/onboarding-flow/recovery-phrase/confirm-recovery-phrase.js
  ui/pages/onboarding-flow/recovery-phrase/confirm-recovery-phrase.test.js
  ui/pages/onboarding-flow/recovery-phrase/recovery-phrase-chips.test.js
  ui/pages/onboarding-flow/recovery-phrase/reveal-recovery-phrase.tsx
  ui/pages/onboarding-flow/recovery-phrase/review-recovery-phrase.js
  ui/pages/onboarding-flow/recovery-phrase/review-recovery-phrase.test.js
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.js
  ui/pages/onboarding-flow/secure-your-wallet/secure-your-wallet.test.js
  ui/pages/onboarding-flow/secure-your-wallet/skip-srp-backup-popover.test.tsx
  ui/pages/onboarding-flow/secure-your-wallet/skip-srp-backup-popover.tsx
  ui/pages/onboarding-flow/welcome/welcome-login.test.tsx
  ui/pages/onboarding-flow/welcome/welcome.js
  ui/pages/onboarding-flow/welcome/welcome.test.js
Labels: team-extension-platform, size-L

#35612 test: fix Upload Artifacts step if the spec has a long name
  test/e2e/webdriver/driver.js
Labels: team-qa, no-changelog, size-S

#35617 feat: bump solana snap (#35511)
  attribution.txt
  package.json
  test/e2e/tests/solana/web-socket-connection.spec.ts
  yarn.lock
Labels: team-new-networks

#35589 INFRA-2849:Added auto-create-release-pr workflow to automatically create release cp-13.3.0
  .github/workflows/auto-create-release-pr.yml
  .github/workflows/create-release-pr.yml
Labels: team-dev-ops, size-M

#35620 ci: update flaky tests bot workflow
  .github/scripts/create-flaky-test-report.ts
  .github/workflows/flaky-test-report.yml
  .github/workflows/main.yml
Labels: team-qa, no-changelog, size-M

#35421 feat: Integrate ShieldController
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/shield/shield-controller-messenger.ts
  app/scripts/controller-init/shield/shield-controller-init.ts
  app/scripts/metamask-controller.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  yarn.lock
Labels: no-changelog, team-web3auth, size-M, area-shield

#35459 feat: add tooltip for url trust signal badges
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/app/confirm/info/row/url.tsx
Labels: INVALID-PR-TEMPLATE, team-product-safety, size-S

#34720 test: Migrate request queuing dapp1-switch-dapp2-eth-request-accounts to Typescript and POM
  test/e2e/tests/request-queuing/dapp1-switch-dapp2-eth-request-accounts.spec.js
  test/e2e/tests/request-queuing/dapp1-switch-dapp2-eth-request-accounts.spec.ts
Labels: team-qa, size-M

#34724 test: Migrate request queuing batch-txs-per-dapp-extra-tx to Typescript and POM
  test/e2e/page-objects/pages/confirmations/redesign/confirmation.ts
  test/e2e/tests/request-queuing/batch-txs-per-dapp-extra-tx.spec.js
  test/e2e/tests/request-queuing/batch-txs-per-dapp-extra-tx.spec.ts
Labels: team-qa, size-M

#35630 fix: use internalAccount if selected group has no account matching scope cp-13.3.0
  test/data/bridge/mock-bridge-store.ts
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
Labels: team-swaps-and-bridge, size-S

#35625 feat: Use gasUsed from simulation for user facing network fee estimation
  package.json
  ui/pages/confirmations/components/confirm/info/hooks/useFeeCalculations.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useFeeCalculations.ts
  yarn.lock
Labels: team-confirmations, no-changelog, size-M

#34019 fix: support fallback to sequential batch
  app/scripts/lib/smart-transaction/smart-transactions.ts
Labels: INVALID-PR-TEMPLATE, team-confirmations, size-XS

#35417 refactor: Fiat currency formatting
  test/e2e/tests/settings/localization.spec.ts
  ui/components/app/assets/defi-list/defi-list.tsx
  ui/components/app/assets/hooks/useTokenDisplayInfo.tsx
  ui/components/app/confirm/info/row/__snapshots__/currency.test.tsx.snap
  ui/components/app/transaction-list-item/transaction-list-item.stories.js
  ui/components/app/wallet-overview/__snapshots__/aggregated-percentage-overview-cross-chains.test.tsx.snap
  ui/components/app/wallet-overview/__snapshots__/aggregated-percentage-overview.test.tsx.snap
  ui/components/app/wallet-overview/aggregated-percentage-overview-cross-chains.tsx
  ui/components/app/wallet-overview/aggregated-percentage-overview.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/token-list-item/price/percentage-and-amount-change/__snapshots__/percentage-and-amount-change.test.tsx.snap
  ui/components/multichain/token-list-item/price/percentage-and-amount-change/percentage-and-amount-change.tsx
  ui/components/ui/token-input/token-input.component.test.js
  ui/ducks/locale/locale.ts
  ui/helpers/formatters.test.ts
  ui/helpers/formatters.ts
  ui/helpers/utils/confirm-tx.util.ts
  ui/hooks/useCurrencyDisplay.js
  ui/hooks/useCurrencyDisplay.test.js
  ui/hooks/useTransactionDisplayData.js
  ui/pages/defi/components/defi-details-page.tsx
Labels: team-wallet-ux, size-M

#35622 test: fix flaky test `Phishing Detection should display the MetaMask Phishing Detection page and take the user to the blocked page if they continue`
  test/e2e/tests/phishing-controller/phishing-detection.spec.js
Labels: flaky tests, team-qa, no-changelog, size-XS

#35636 test: fix flaky test `Request-queue UI changes...`
  test/e2e/tests/request-queuing/ui.spec.js
Labels: flaky tests, team-qa, no-changelog, size-S

#35653 release: Bump version to 13.2.1
  package.json
Labels: extension-delivery

#35640 feat: improvements in how balance is fetched for various tokens in new send flow
  test/data/send/assets.ts
  ui/pages/confirmations/components/send/amount/amount.test.tsx
  ui/pages/confirmations/hooks/send/evm/useEvmAmountValidation.test.ts
  ui/pages/confirmations/hooks/send/evm/useEvmAmountValidation.ts
  ui/pages/confirmations/hooks/send/non-evm/useNonEvmAmountValidation.test.ts
  ui/pages/confirmations/hooks/send/non-evm/useNonEvmAmountValidation.ts
  ui/pages/confirmations/hooks/send/useAmountValidation.test.ts
  ui/pages/confirmations/hooks/send/useAmountValidation.ts
  ui/pages/confirmations/hooks/send/useBalance.test.ts
  ui/pages/confirmations/hooks/send/useBalance.ts
  ui/pages/confirmations/hooks/send/useCurrencyConversions.test.ts
  ui/pages/confirmations/hooks/send/useCurrencyConversions.ts
  ui/pages/confirmations/hooks/send/useMaxAmount.test.ts
  ui/pages/confirmations/hooks/send/useMaxAmount.ts
  ui/pages/confirmations/types/send.ts
  ui/pages/confirmations/utils/send.test.ts
  ui/pages/confirmations/utils/send.ts
Labels: team-confirmations, size-L

#35541 refactor: migrate eip-5792 & capabilities middleware handlers into monorepo
  app/scripts/lib/transaction/eip5792.test.ts
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: team-wallet-api-platform, size-XL

#35658 cherry-pick fix: stable sync secret (#35464)
  .github/workflows/stable-branch-sync.yml
Labels: team-extension-platform

#33547 feat: Add Acala/Karura logo, update bufferMultiplier
  app/images/acala-network-logo.svg
  app/images/acala-token.svg
  app/images/acala.svg
  app/images/karura-token.svg
  app/images/karura.svg
  shared/constants/network.ts
Labels: external-contributor

#35662 ci(INFRA-2849): Don't run auto create release pr on hotfix cp-13.2.1
  .github/workflows/auto-create-release-pr.yml
Labels: team-dev-ops, size-S

#35669 chore: Update `base-controller` to v8.3.0
  package.json
  yarn.lock
Labels: size-XS, team-core-platform

#35673 release: Stable sync v13.2.1 into main
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, size-XS

#35644 fix: new send implementation for native SOL token
  test/data/send/assets.ts
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/pages/confirmations/context/send/index.tsx
  ui/pages/confirmations/hooks/send/useBalance.test.ts
  ui/pages/confirmations/hooks/send/useBalance.ts
  ui/pages/confirmations/hooks/send/useCurrencyConversions.ts
  ui/pages/confirmations/hooks/send/useSendType.ts
  ui/pages/confirmations/types/send.ts
Labels: team-confirmations, size-S

#35660 test: fix flaky test `Settings Redirects to ENS domains when user inputs ENS into address bar`
  test/e2e/tests/settings/ipfs-ens-resolution.spec.ts
Labels: flaky tests, team-qa, no-changelog, size-XS

#35694 fix: using new asset selectors for re-designed send flow
  ui/components/app/assets/nfts/nft-details/nft-details.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-nft-tab.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/confirmations/components/send/amount-recipient/amount-recipient.tsx
  ui/pages/confirmations/context/send/index.tsx
  ui/pages/confirmations/hooks/send/useSendActions.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.test.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.ts
  ui/pages/confirmations/hooks/send/useSendType.test.ts
  ui/pages/confirmations/hooks/send/useSendType.ts
  ui/pages/confirmations/send/send-inner.test.tsx
Labels: team-confirmations, size-M

#35664 test: fix flaky test `Multiple ERC20 Watch Asset...`
  test/e2e/page-objects/pages/dialog/add-tokens.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/seeder/contract-address-registry.js
  test/e2e/tests/dapp-interactions/dapp-interactions.spec.ts
  test/e2e/tests/network/network-connection.spec.ts
  test/e2e/tests/tokens/add-multiple-tokens.spec.ts
Labels: flaky tests, team-qa, no-changelog, size-S

#35695 feat: bump solana snap
  package.json
  yarn.lock
Labels: team-new-networks, size-XS

#35672 chore: Memo formatter hook
  ui/helpers/formatters.ts
Labels: team-wallet-ux, size-XS

#35668 fix: txHistory migration script should update txMetaId
  app/scripts/migrations/174.test.ts
  app/scripts/migrations/174.ts
Labels: team-swaps-and-bridge, size-M

#35702 fix: Fix sending NFT tokens in new send implementation
  ui/pages/confirmations/components/send/amount/amount.test.tsx
  ui/pages/confirmations/components/send/amount/amount.tsx
  ui/pages/confirmations/hooks/send/useCurrencyConversions.ts
  ui/pages/confirmations/hooks/send/useMaxAmount.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.ts
  ui/pages/confirmations/utils/send.ts
Labels: team-confirmations, size-S

#35555 feat: Removed Getting Started Page, TOU and Added footer for tou in login
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  builds.yml
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/tests/account/incremental-security.spec.ts
  test/e2e/tests/metrics/app-installed.spec.ts
  test/e2e/tests/onboarding/onboarding.spec.ts
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/pages/onboarding-flow/onboarding-app-header/onboarding-app-header.js
  ui/pages/onboarding-flow/onboarding-flow.js
  ui/pages/onboarding-flow/onboarding-flow.test.js
  ui/pages/onboarding-flow/welcome/login-options.tsx
  ui/pages/onboarding-flow/welcome/types.ts
  ui/pages/onboarding-flow/welcome/welcome-banner.tsx
  ui/pages/onboarding-flow/welcome/welcome-login.test.tsx
  ui/pages/onboarding-flow/welcome/welcome-login.tsx
  ui/pages/onboarding-flow/welcome/welcome.js
  ui/pages/onboarding-flow/welcome/welcome.test.js
Labels: area-onboarding, QA Passed, team-web3auth, size-M

#35554 build: commit hash parameter from `Compare and comment` step in Page Load Benchmark workflow
  .github/actions/page-load-benchmark-comment/action.yml
  .github/workflows/main.yml
  .github/workflows/page-load-benchmark-pr.yml
  .github/workflows/publish-prerelease.yml
  development/page-load-benchmark-pr-comment.ts
Labels: team-wallet-api-platform, size-S

#35012 feat(assets): add aggregated balance selectors for account group and wallets
  test/e2e/tests/multichain-accounts/common.ts
  test/e2e/tests/multichain-accounts/multichain-account-list-page.spec.ts
  ui/components/app/assets/account-group-balance-change/account-group-balance-change.test.tsx
  ui/components/app/assets/account-group-balance-change/account-group-balance-change.tsx
  ui/components/app/assets/account-group-balance-change/get-display-balance.test.ts
  ui/components/app/assets/account-group-balance-change/get-display-balance.ts
  ui/components/app/assets/account-group-balance-change/useAccountGroupBalanceDisplay.test.ts
  ui/components/app/assets/account-group-balance-change/useAccountGroupBalanceDisplay.ts
  ui/components/app/assets/account-group-balance/account-group-balance.test.tsx
  ui/components/app/assets/account-group-balance/account-group-balance.tsx
  ui/components/app/wallet-overview/coin-overview.tsx
  ui/components/multichain-accounts/multichain-account-list/multichain-account-list.tsx
  ui/hooks/multichain-accounts/useAccountBalance.test.ts
  ui/hooks/multichain-accounts/useAccountBalance.ts
  ui/hooks/multichain-accounts/useWalletBalance.test.ts
  ui/hooks/multichain-accounts/useWalletBalance.ts
  ui/pages/multichain-accounts/account-list/account-list.tsx
  ui/pages/multichain-accounts/wallet-details-page/wallet-details-page.tsx
  ui/selectors/assets.test.ts
  ui/selectors/assets.ts
  ui/selectors/selectors.js
Labels: team-assets, no-changelog, size-XL

#35663 ci: page load benchmark PAT issue
  .github/workflows/main.yml
  .github/workflows/page-load-benchmark-pr.yml
  .github/workflows/page-load-benchmark-upload.yml
Labels: team-wallet-api-platform, size-S

#35051 test: ledger swap e2e test
  test/e2e/page-objects/pages/swap/swap-page.ts
  test/e2e/tests/hardware-wallets/ledger/ledger-account.spec.ts
  test/e2e/tests/hardware-wallets/ledger/ledger-erc20.spec.ts
  test/e2e/tests/hardware-wallets/ledger/ledger-erc721.spec.ts
  test/e2e/tests/hardware-wallets/ledger/ledger-personal-sign.spec.ts
  test/e2e/tests/hardware-wallets/ledger/ledger-send.spec.ts
  test/e2e/tests/hardware-wallets/ledger/ledger-sign.spec.ts
  test/e2e/tests/hardware-wallets/ledger/ledger-swap.spec.ts
  test/e2e/tests/hardware-wallets/ledger/mocks.ts
Labels: team-hardware-wallets, e2e-test, no-changelog, size-L

#35519 fix: cannot show all networks when open edit network
  ui/components/multichain/network-manager/network-manager.tsx
Labels: external-contributor

#35737 ci: remove stale flag from page load benchmark config file
  .github/workflows/page-load-benchmark-pr.yml
Labels: team-wallet-api-platform, size-XS

#35749 release: Bump version to 13.2.2
  package.json
Labels: extension-delivery

#35751 Cherry pick fix: Destructure openExtensionInBrowser from global in Routes component (#35587)
  ui/pages/routes/routes.component.tsx
Labels: team-extension-platform, extension-delivery

#35739 fix: notify the client when native balance goes to zero
  package.json
  yarn.lock
Labels: team-new-networks, size-XS

#35750 release: 13.2.2
  CHANGELOG.md
  package.json
  ui/pages/routes/routes.component.tsx
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE, release-13.2.2

#35193 feat: add `wallet_requestExecutionPermissions` method
  app/scripts/controllers/permissions/specifications.js
  app/scripts/lib/createMetamaskMiddleware.js
  app/scripts/lib/forwardRequestToSnap.test.ts
  app/scripts/lib/forwardRequestToSnap.ts
  app/scripts/metamask-controller.js
  builds.yml
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-delegation, size-M

#35754 fix: simplify transaction value calculation in useInsufficientBalanceAlerts hook
  ui/pages/confirmations/hooks/alerts/transactions/useInsufficientBalanceAlerts.ts
  ui/pages/confirmations/hooks/send/useMaxAmount.ts
  ui/selectors/confirm-transaction.js
Labels: team-confirmations, size-S

#35764 release: Stable sync v13.2.2 into main
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, size-XS

#35767 chore: bump account-tree-controller
  app/scripts/controller-init/messengers/accounts/account-tree-controller-messenger.ts
  package.json
  yarn.lock
Labels: team-accounts, size-XS

#35745 refactor: handle asset detail fetch and errors
  ui/helpers/utils/token-util.js
  ui/hooks/useTransactionDisplayData.js
  ui/pages/confirmations/hooks/useAssetDetails.js
  ui/store/actions.ts
Labels: team-assets, size-S

#35744 feat: Implement recipient validation and resolutions for Solana and EVM
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/metamask-controller.js
  ui/hooks/snaps/useSnapNameResolution.test.ts
  ui/hooks/snaps/useSnapNameResolution.ts
  ui/pages/confirmations/components/send/amount-recipient/amount-recipient.test.tsx
  ui/pages/confirmations/components/send/amount-recipient/amount-recipient.tsx
  ui/pages/confirmations/components/send/asset-list/asset-list.test.tsx
  ui/pages/confirmations/components/send/recipient-list/recipient-list.tsx
  ui/pages/confirmations/components/send/recipient/recipient.test.tsx
  ui/pages/confirmations/components/send/recipient/recipient.tsx
  ui/pages/confirmations/context/send/index.tsx
  ui/pages/confirmations/hooks/send/useSendActions.ts
  ui/pages/confirmations/hooks/send/validations/useEvmRecipientValidation.test.ts
  ui/pages/confirmations/hooks/send/validations/useEvmRecipientValidation.ts
  ui/pages/confirmations/hooks/send/validations/useRecipientValidation.test.ts
  ui/pages/confirmations/hooks/send/validations/useRecipientValidation.ts
  ui/pages/confirmations/hooks/send/validations/useSolanaRecipientValidation.test.ts
  ui/pages/confirmations/hooks/send/validations/useSolanaRecipientValidation.ts
  ui/pages/confirmations/types/send.ts
  ui/pages/confirmations/utils/sendValidations.test.ts
  ui/pages/confirmations/utils/sendValidations.ts
  ui/store/actions.ts
Labels: team-confirmations, size-XL

#35724 refactor: add navigation to BIP-44 views
  ui/components/multichain/global-menu/global-menu.tsx
  ui/components/multichain/menu-items/account-details-menu-item.js
Labels: team-accounts, size-S

#35773 chore: Update `@metamask/utils` to latest version
  .yarn/patches/lodash.memoize-npm-4.1.2-0e6250041f.patch
  development/build/scripts.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: size-S, team-core-platform

#35719 feat: reveal private key (BIP-44)
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain-accounts/multichain-address-row/multichain-address-row.stories.tsx
  ui/components/multichain-accounts/multichain-address-row/multichain-address-row.test.tsx
  ui/components/multichain-accounts/multichain-address-row/multichain-address-row.tsx
  ui/components/multichain-accounts/multichain-address-rows-list/multichain-address-rows-list.tsx
  ui/components/multichain-accounts/multichain-private-key-list/index.ts
  ui/components/multichain-accounts/multichain-private-key-list/multichain-private-key-list.test.tsx
  ui/components/multichain-accounts/multichain-private-key-list/multichain-private-key-list.tsx
  ui/helpers/constants/routes.ts
  ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx
  ui/pages/multichain-accounts/multichain-account-private-key-list-page/index.ts
  ui/pages/multichain-accounts/multichain-account-private-key-list-page/multichain-account-private-key-list-page.test.tsx
  ui/pages/multichain-accounts/multichain-account-private-key-list-page/multichain-account-private-key-list-page.tsx
  ui/pages/routes/routes.component.tsx
Labels: team-accounts, size-XL

#35782 release: 13.2.3
  CHANGELOG.md
  app/scripts/lib/tx-verification/tx-verification-middleware.test.ts
  app/scripts/lib/tx-verification/tx-verification-middleware.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE, release-13.2.3

#35791 feat: disable temporarily flaky ledger tests
  test/e2e/tests/hardware-wallets/ledger/ledger-erc20.spec.ts
  test/e2e/tests/hardware-wallets/ledger/ledger-swap.spec.ts
Labels: team-accounts, team-hardware-wallets, e2e-test, no-changelog, size-XS

#35785 ci: update page load benchmark to use localhost test dapp
  test/e2e/page-objects/benchmark/page-load-benchmark.ts
  test/e2e/playwright/benchmark/page-load-benchmark.spec.ts
Labels: team-wallet-api-platform, size-S

#35748 chore: Bump @metamask/design-system-react to 0.4.0
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/snaps/snap-ui-renderer/components/__snapshots__/account-selector.test.ts.snap
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/address-list-item/__snapshots__/address-list-item.test.tsx.snap
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/badge-status/__snapshots__/badge-status.test.js.snap
  ui/components/multichain/connect-accounts-modal/__snapshots__/connect-accounts-modal.test.tsx.snap
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/account-picker.test.tsx.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/permissions-connect/connect-page/__snapshots__/connect-page.test.tsx.snap
  yarn.lock
Labels: team-wallet-ux, size-XS, release-13.3.0

#35801 feat: Implement redesigned send flow feature flag
  test/e2e/mock-e2e.js
  ui/components/app/assets/nfts/nft-details/nft-details.tsx
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-nft-tab.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.test.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/confirmations/components/confirm/header/wallet-initiated-header.test.tsx
  ui/pages/confirmations/components/confirm/header/wallet-initiated-header.tsx
  ui/pages/confirmations/hooks/useConfirmSendNavigation.test.ts
  ui/pages/confirmations/hooks/useConfirmSendNavigation.ts
  ui/pages/confirmations/hooks/useRedesignedSendFlow.test.ts
  ui/pages/confirmations/hooks/useRedesignedSendFlow.ts
  ui/pages/confirmations/utils/send.test.ts
  ui/pages/confirmations/utils/send.ts
  ui/pages/routes/routes.component.test.js
  ui/pages/routes/routes.component.tsx
Labels: team-confirmations, no-changelog, size-M

#35806 Remove duplicate 13.2.0 changelog entries
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery

#35705 feat: Add controller metadata to encryption controllers
  app/scripts/controllers/decrypt-message.test.ts
  app/scripts/controllers/decrypt-message.ts
  app/scripts/controllers/encryption-public-key.test.ts
  app/scripts/controllers/encryption-public-key.ts
Labels: size-M, team-core-platform

#35809 refactor: update push translation copy
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
Labels: team-assets, size-S

#35803 fix: only show connected and active badge
  ui/components/multichain/account-list-item/account-list-item.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux, size-XS

#35716 ci(INFRA-2911): Hardcoded parameters values for create release pull request cp-13.3.0
  .github/scripts/extract-semver.sh
  .github/scripts/resolve-previous-ref.sh
  .github/workflows/auto-create-release-pr.yml
  .github/workflows/create-release-pr.yml
Labels: team-dev-ops, size-M, skip-e2e

#35715 fix: dapp connect title overflow
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/app/confirm/info/row/url.tsx
  ui/pages/permissions-connect/connect-page/__snapshots__/connect-page.test.tsx.snap
  ui/pages/permissions-connect/connect-page/connect-page.tsx
Labels: INVALID-PR-TEMPLATE, team-product-safety, size-S

#35762 feat: revoke token refactor
  app/scripts/controller-init/messengers/seedless-onboarding/seedless-onboarding-controller-messenger.ts
  app/scripts/controller-init/seedless-onboarding/seedless-onboarding-controller-init.test.ts
  app/scripts/controller-init/seedless-onboarding/seedless-onboarding-controller-init.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  app/scripts/services/oauth/base-login-handler.ts
  app/scripts/services/oauth/oauth-service.test.ts
  app/scripts/services/oauth/oauth-service.ts
  app/scripts/services/oauth/types.ts
  package.json
  test/e2e/helpers/seedless-onboarding/constants.ts
  test/e2e/helpers/seedless-onboarding/mocks.ts
  yarn.lock
Labels: area-onboarding, no-changelog, team-web3auth, size-M

#35896 feat(stable-sync): add write permissions to the stable sync workflow
  .github/workflows/stable-branch-sync.yml
Labels: team-dev-ops, skip-e2e-quality-gate, size-XS, skip-e2e

#35944 test: fix flakly test ` Request Queuing for Multiple Dapps and Txs on different networks should put txs from different dapps on different networks adds extra tx after in same queue. `
  test/e2e/tests/request-queuing/batch-txs-per-dapp-extra-tx.spec.ts
Labels: flaky tests, team-qa, no-changelog, size-S

#35802 test: Migrate phishing detection e2e tests to Page object modal
  test/e2e/page-objects/pages/home/homepage.ts
  test/e2e/page-objects/pages/phishing-warning-page.ts
  test/e2e/tests/phishing-controller/phishing-detection.spec.ts
Labels: e2e-test, team-qa, no-changelog, size-M

#35858 chore: Updated Carousel design for Wallet Homepage
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/app/wallet-overview/index.scss
  ui/components/multichain/account-overview/account-overview-layout.tsx
  ui/components/multichain/carousel/__tests__/carousel.test.tsx
  ui/components/multichain/carousel/animations/animationTimings.ts
  ui/components/multichain/carousel/animations/index.ts
  ui/components/multichain/carousel/animations/useTransitionToEmpty.ts
  ui/components/multichain/carousel/animations/useTransitionToNextCard.ts
  ui/components/multichain/carousel/carousel-wrapper.tsx
  ui/components/multichain/carousel/carousel.test.tsx
  ui/components/multichain/carousel/carousel.tsx
  ui/components/multichain/carousel/carousel.types.ts
  ui/components/multichain/carousel/constants.ts
  ui/components/multichain/carousel/helpers.ts
  ui/components/multichain/carousel/index.scss
  ui/components/multichain/carousel/index.ts
  ui/components/multichain/carousel/stack-card-empty/index.ts
  ui/components/multichain/carousel/stack-card-empty/stack-card-empty.tsx
  ui/components/multichain/carousel/stack-card-empty/stack-card-empty.types.ts
  ui/components/multichain/carousel/stack-card/index.ts
  ui/components/multichain/carousel/stack-card/stack-card.tsx
  ui/components/multichain/carousel/stack-card/stack-card.types.ts
  ui/components/multichain/carousel/types.ts
  ui/components/multichain/index.js
Labels: team-design-system, e2e-test, size-XL

#35927 test: a way to tolerate and log failure in E2E tests
  test/e2e/run-e2e-test.js
  test/e2e/tests/tolerate-failure/power-user.spec.ts
Labels: team-extension-platform, no-changelog, size-S

#35955 chore: rename maskicons to polycons cp-13.4.0
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/migrations/177.test.ts
  app/scripts/migrations/177.ts
  app/scripts/migrations/index.js
Labels: team-wallet-ux, size-M

#35915 fix: handle image load error
  ui/components/component-library/avatar-favicon/avatar-favicon.tsx
Labels: team-wallet-ux, size-S

#35874 feat: added ui for error states
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/settings/transaction-shield-tab/transaction-shield.tsx
Labels: team-web3auth, size-M

#35950 fix: language selector z-index update
  ui/css/design-system/_z-index.scss
  ui/pages/onboarding-flow/onboarding-app-header/index.scss
Labels: area-onboarding, QA Passed, team-web3auth, size-XS

#35954 refactor: Refactor onboarding controller to use modular init pattern
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/onboarding-controller-messenger.test.ts
  app/scripts/controller-init/messengers/onboarding-controller-messenger.ts
  app/scripts/controller-init/onboarding-controller-init.test.ts
  app/scripts/controller-init/onboarding-controller-init.ts
  app/scripts/controllers/onboarding.ts
  app/scripts/metamask-controller.js
Labels: no-changelog, size-M, team-core-platform

#35350 feat: shield plan
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/images/card-amex.svg
  app/images/card-mc.svg
  app/images/card-visa.svg
  ui/helpers/constants/routes.ts
  ui/pages/pages.scss
  ui/pages/routes/routes.component.tsx
  ui/pages/routes/utils.js
  ui/pages/shield-plan/index.scss
  ui/pages/shield-plan/index.ts
  ui/pages/shield-plan/shield-payment-modal.stories.tsx
  ui/pages/shield-plan/shield-payment-modal.test.tsx
  ui/pages/shield-plan/shield-payment-modal.tsx
  ui/pages/shield-plan/shield-plan.stories.tsx
  ui/pages/shield-plan/shield-plan.test.tsx
  ui/pages/shield-plan/shield-plan.tsx
  ui/pages/shield-plan/types.ts
Labels: team-web3auth, size-XL, area-shield

#35973 chore: chore/13.4.0-Changelog-Linting
  CHANGELOG.md
Labels: extension-delivery, INVALID-PR-TEMPLATE

#35932 fix: fix BIP-44 account picker
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
Labels: team-accounts, size-S

#35925 refactor: use Link to simplify routing
  ui/components/multichain/app-header/app-header.test.js
  ui/components/multichain/global-menu/global-menu.test.tsx
  ui/components/multichain/global-menu/global-menu.tsx
  ui/components/ui/menu/menu-item.tsx
  ui/pages/settings/settings.container.js
Labels: team-wallet-ux, size-M

#36004 fix: minor UI details in import SRP and global menu
  ui/components/multichain/global-menu/global-menu.tsx
  ui/pages/multi-srp/import-srp/import-srp.tsx
Labels: team-accounts, size-XS

#35970 feat: Shield: Enable Security Alerts Config for EIP-5792
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/metamask-controller.js
Labels: no-changelog, team-web3auth, size-S, area-shield

#35706 feat: add storybook stories for AggregatedPercentageOverview
  ui/components/app/wallet-overview/aggregated-percentage-overview.stories.tsx
Labels: team-design-system, size-S

#35929 feat: subscription payment options integration
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/subscription/index.ts
  app/scripts/controller-init/messengers/subscription/subscription-controller-messenger.ts
  app/scripts/controller-init/messengers/subscription/subscription-controller.messenger.test.ts
  app/scripts/controller-init/subscription/index.ts
  app/scripts/controller-init/subscription/subscription-controller-init.test.ts
  app/scripts/controller-init/subscription/subscription-controller-init.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/data/mock-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/hooks/subscription/useSubscription.ts
  ui/hooks/subscription/useSubscriptionPricing.ts
  ui/pages/shield-plan/shield-payment-modal.stories.tsx
  ui/pages/shield-plan/shield-payment-modal.test.tsx
  ui/pages/shield-plan/shield-payment-modal.tsx
  ui/pages/shield-plan/shield-plan.test.tsx
  ui/pages/shield-plan/shield-plan.tsx
  ui/pages/shield-plan/types.ts
  ui/selectors/subscription/index.ts
  ui/selectors/subscription/subscription.ts
  ui/store/actions.ts
  yarn.lock
Labels: team-web3auth, size-XL, area-shield

#35938 feat: email consent update settings page cp-13.4.0
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/controllers/metametrics-controller.ts
  app/scripts/metamask-controller.js
  app/scripts/services/oauth/oauth-service.ts
  shared/types/background.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/store/actions.ts
Labels: area-onboarding, QA Passed, team-web3auth, size-M

#35980 refactor: Refactor remote feature flag controller to use modular init pattern
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/remote-feature-flag-controller-messenger.test.ts
  app/scripts/controller-init/messengers/remote-feature-flag-controller-messenger.ts
  app/scripts/controller-init/remote-feature-flag-controller-init.test.ts
  app/scripts/controller-init/remote-feature-flag-controller-init.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: no-changelog, size-M, team-core-platform

#35865 fix: add wrapper for choose account
  shared/lib/multichain/scope-utils.test.ts
  ui/components/multichain-accounts/permissions/multichain-edit-accounts-page/multichain-edit-account-wrapper.test.tsx
  ui/components/multichain-accounts/permissions/multichain-edit-accounts-page/multichain-edit-account-wrapper.tsx
  ui/components/multichain-accounts/permissions/multichain-edit-accounts-page/multichain-edit-accounts-page.test.tsx
  ui/components/multichain-accounts/permissions/multichain-edit-accounts-page/multichain-edit-accounts-page.tsx
  ui/components/multichain-accounts/permissions/permission-review-page/multichain-review-permissions-page.tsx
  ui/pages/multichain-accounts/multichain-accounts-connect-page/multichain-accounts-connect-page.tsx
  ui/pages/permissions-connect/permissions-connect.component.js
  ui/pages/permissions-connect/permissions-connect.container.js
Labels: team-accounts, size-L

#35943 feat: add new controller metadata to `SwapsController`
  app/scripts/controllers/swaps/index.ts
  app/scripts/controllers/swaps/swaps.test.ts
Labels: size-M, team-core-platform

#35966 chore: add Hyperliquid referral confirmation UI
  .github/CODEOWNERS
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/images/hyperliquid-referral.png
  shared/constants/app.ts
  shared/lib/ui-utils.js
  ui/components/app/metamask-template-renderer/safe-component-list.js
  ui/pages/confirmations/confirmation/stories/hyperliquid-referral-consent.stories.tsx
  ui/pages/confirmations/confirmation/templates/hyperliquid-referral-consent.ts
  ui/pages/confirmations/confirmation/templates/index.js
  ui/pages/core/hyperliquid-referral-consent/hyperliquid-referral-consent.test.tsx
  ui/pages/core/hyperliquid-referral-consent/hyperliquid-referral-consent.tsx
  ui/pages/core/hyperliquid-referral-consent/index.ts
Labels: team-wallet-ux, size-M, skip-e2e

#36033 chore: bump multichain accounts deps
  app/scripts/controller-init/messengers/accounts/account-tree-controller-messenger.ts
  app/scripts/controller-init/messengers/accounts/multichain-account-service-messenger.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  shared/lib/accounts/accounts.ts
  yarn.lock
Labels: team-accounts, size-S

#35769 feat: add new metadata to Wallet UX controllers
  app/scripts/controllers/account-order.ts
  app/scripts/controllers/network-order.test.ts
  app/scripts/controllers/network-order.ts
Labels: size-M, team-core-platform

#35776 chore: indicate swap in HW confirmation page and alert banners
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/bridge/awaiting-signatures/awaiting-signatures.tsx
  ui/pages/bridge/awaiting-signatures/index.scss
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge, size-S

#36042 chore: Update `multichain-network-controller` to v0.12
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: size-XS, team-core-platform

#36000 fix: identicon in activity log cp-13.4.0
  test/e2e/page-objects/pages/home/activity-list.ts
  test/jest/index.js
  test/jest/rendering.js
  ui/components/app/name/name-details/formatted-value.tsx
  ui/components/app/name/name-details/name-display.tsx
  ui/components/app/name/name-details/shortened-name.tsx
  ui/components/app/name/name.tsx
  ui/components/app/transaction-list-item-details/index.scss
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.test.js
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
  ui/components/ui/popover/popover.component.js
  ui/components/ui/sender-to-recipient/index.scss
  ui/components/ui/sender-to-recipient/sender-to-recipient.component.js
Labels: team-extension-ux, team-wallet-ux, size-M

#36041 feat: Add reusable TabEmptyState UI component
  app/images/empty-state-perps-dark.png
  app/images/empty-state-perps-light.png
  ui/components/ui/tab-empty-state/index.ts
  ui/components/ui/tab-empty-state/tab-empty-state.stories.tsx
  ui/components/ui/tab-empty-state/tab-empty-state.test.tsx
  ui/components/ui/tab-empty-state/tab-empty-state.tsx
Labels: team-design-system, no-changelog, size-M

#36029 test: fix flaky test ` Revoke Dapp Permissions There are pending confirmation in the old network rejects the pending confirmations as permissions are revoked for the network`
  test/e2e/json-rpc/wallet_revokePermissions.spec.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/webdriver/driver.js
Labels: flaky tests, team-qa, no-changelog, size-M

#36056 test: fix flaky test `Segment User Traits sends identify event when user opts in both metrics and data collection during onboarding`
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/page-objects/pages/onboarding/onboarding-metrics-page.ts
Labels: flaky tests, team-qa, no-changelog, size-XS

#36043 chore: Update `signature-controller` and `user-operation-controller`
  package.json
  yarn.lock
Labels: size-XS, team-core-platform

#36066 test: fix flaky test `Metamask onboarding (with social login) Creates a new wallet with Google login and completes the onboarding process `
  test/e2e/page-objects/pages/onboarding/onboarding-complete-page.ts
Labels: flaky tests, team-qa, no-changelog, size-S

#36038 fix: send broken for native assets when triggered from asset detail page
  ui/pages/confirmations/components/UI/send-hero/send-hero.test.tsx
  ui/pages/confirmations/components/UI/send-hero/send-hero.tsx
  ui/pages/confirmations/components/send/amount-recipient/amount-recipient.test.tsx
  ui/pages/confirmations/components/send/recipient/recipient.test.tsx
  ui/pages/confirmations/components/send/recipient/recipient.tsx
  ui/pages/confirmations/context/send/index.tsx
  ui/pages/confirmations/hooks/send/useSendQueryParams.test.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.ts
Labels: team-confirmations, size-M

#36076 refactor: Refactor permission and subject metadata controller to use modular init pattern
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/permission-controller-messenger.test.ts
  app/scripts/controller-init/messengers/permission-controller-messenger.ts
  app/scripts/controller-init/messengers/subject-metadata-controller-messenger.test.ts
  app/scripts/controller-init/messengers/subject-metadata-controller-messenger.ts
  app/scripts/controller-init/permission-controller-init.test.ts
  app/scripts/controller-init/permission-controller-init.ts
  app/scripts/controller-init/subject-metadata-controller-init.test.ts
  app/scripts/controller-init/subject-metadata-controller-init.ts
  app/scripts/controllers/permissions/snaps/specifications.ts
  app/scripts/metamask-controller.js
Labels: no-changelog, size-XL, team-core-platform

#36110 fix: use transaction `chainId` instead of global network for `advancedGasFee`
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
Labels: team-confirmations, size-XS

#36111 chore: use exported constants for user storage paths
  test/e2e/helpers/identity/user-storage/userStorageMockttpController.ts
  test/e2e/tests/identity/mocks.ts
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-accounts, size-S

#36053 fix: in send flow cancel button on confirmation page should go back to send page
  ui/pages/confirmations/hooks/send/useBalance.test.ts
  ui/pages/confirmations/hooks/send/useBalance.ts
  ui/pages/confirmations/hooks/send/useCurrencyConversions.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.test.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.ts
  ui/pages/confirmations/hooks/useConfirmSendNavigation.ts
Labels: team-confirmations, size-M

#36112 fix: remove old and unused UserStorageController state properties
  app/scripts/migrations/177.test.ts
  app/scripts/migrations/177.ts
  app/scripts/migrations/index.js
Labels: team-accounts, size-M

#35947 chore: updated Ethereum network name
  app/scripts/metamask-controller.js
  app/scripts/migrations/177.ts
  shared/constants/network.test.ts
  shared/constants/network.ts
  test/data/mock-data.js
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/e2e/flask/multichain-api/evm/wallet_createSession.spec.ts
  test/e2e/flask/multichain-api/non-evm/wallet_createSession.spec.ts
  test/e2e/flask/solana-wallet-standard/connect.spec.ts
  test/e2e/mock-response-data/chain-id-network-chains.json
  test/e2e/mock-response-data/on-ramp-content.json
  test/e2e/playwright/swap/tenderly-network.ts
  test/e2e/tests/connections/edit-networks-permissions.spec.ts
  test/e2e/tests/hardware-wallets/ledger/mocks.ts
  test/e2e/tests/multichain/aggregated-balances.spec.ts
  test/e2e/tests/network/add-custom-rpc.spec.ts
  test/e2e/tests/network/custom-rpc-history.spec.ts
  test/e2e/tests/network/network-manager.spec.ts
  test/e2e/tests/network/popular-network.spec.ts
  test/e2e/tests/network/switch-custom-network.spec.ts
  test/e2e/tests/network/switch-network.spec.ts
  test/e2e/tests/request-queuing/ui.spec.js
  test/e2e/tests/swap-send/swap-send-eth-with-loaded-state.spec.ts
  test/e2e/tests/swaps/swap-erc20-with-loaded-state.spec.ts
  test/integration/swaps/mock-data.ts
  ui/components/app/transaction-list-item/transaction-list-item.component.test.js
  ui/components/app/update-modal/update-modal.test.tsx
  ui/components/app/wallet-overview/aggregated-percentage-overview-cross-chains.test.tsx
  ui/components/multichain-accounts/address-qr-code-modal/address-qr-code-modal.test.tsx
  ui/components/multichain-accounts/multichain-address-row/multichain-address-row.test.tsx
  ui/components/multichain-accounts/multichain-address-rows-list/multichain-address-rows-list.test.tsx
  ui/components/multichain-accounts/multichain-address-rows-list/utils.test.ts
  ui/components/multichain-accounts/multichain-private-key-list/multichain-private-key-list.test.tsx
  ui/components/multichain-accounts/multichain-site-cell/multichain-site-cell.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker/__snapshots__/asset-picker.test.tsx.snap
  ui/components/multichain/asset-picker-amount/asset-picker/asset-picker.test.tsx
  ui/components/multichain/network-list-menu/__snapshots__/network-list-menu.test.tsx.snap
  ui/components/multichain/network-list-menu/network-list-menu.test.tsx
  ui/components/multichain/network-manager/network-manager.test.tsx
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/ramps/ramps.test.ts
  ui/helpers/utils/network-helper.test.ts
  ui/helpers/utils/settings-search.test.js
  ui/hooks/useAccountTotalCrossChainFiatBalance.test.ts
  ui/hooks/useMultichainBalances.test.ts
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/bridge/__snapshots__/index.test.tsx.snap
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.test.tsx
  ui/pages/bridge/prepare/__snapshots__/prepare-bridge-page.test.tsx.snap
  ui/pages/bridge/prepare/components/__snapshots__/destination-account-picker-modal.test.tsx.snap
  ui/pages/confirm-add-suggested-nft/__snapshots__/confirm-add-suggested-nft.test.js.snap
  ui/pages/confirmations/components/UI/send-hero/send-hero.test.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/__snapshots__/siwe-sign.test.tsx.snap
  ui/pages/confirmations/hooks/useConfirmationNetworkInfo.test.ts
  ui/pages/confirmations/hooks/useEIP7702Networks.test.ts
  ui/pages/settings/networks-tab/networks-form/networks-form.test.js
  ui/selectors/selectors.test.js
Labels: team-assets, size-M

#36114 test: remove unnecessary steps in the hardware wallet tests by using the new option `deployFrom` from the Anvil class
  test/e2e/tests/hardware-wallets/ledger/ledger-erc721.spec.ts
  test/e2e/tests/hardware-wallets/trezor/trezor-erc721.spec.ts
Labels: team-qa, no-changelog, size-L

#35626 chore: bump SelectedNetworkController package
  app/scripts/controller-init/selected-network-controller-init.test.ts
  app/scripts/controller-init/selected-network-controller-init.ts
  package.json
  yarn.lock
Labels: team-wallet-api-platform, no-changelog, size-S

#36089 ci(merge queue): Add merge group to workflow trigger
  .github/workflows/check-template-and-add-labels.yml
  .github/workflows/fitness-functions.yml
Labels: team-extension-platform, size-XS

#36095 fix: update wallet discovery call with correct function
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-accounts, INVALID-PR-TEMPLATE, no-changelog, size-S

#36132 chore: bump multichain accounts deps
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/e2e/tests/multichain-accounts/multichain-account-list-page.spec.ts
  yarn.lock
Labels: team-accounts, size-S

#36125 chore: Update `assets-controllers` patch comment
  .yarn/patches/@metamask-assets-controllers-npm-75.2.0-26c7526112.patch
  package.json
  yarn.lock
Labels: size-S, team-core-platform

#36136 fix: Move network selector above banner in activity tab empty state
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/app/transaction-list/unified-transaction-list.component.js
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
Labels: team-design-system, size-S

#36027 fix: Update spacing, fontweight and icons on the Home Page
  app/images/icons/triangle-down.svg
  app/images/icons/triangle-up.svg
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.tsx
  ui/components/app/assets/token-cell/__snapshots__/token-cell.test.tsx.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/token-list-item/__snapshots__/token-list-item.test.tsx.snap
  ui/components/multichain/token-list-item/price/percentage-change/__snapshots__/percentage-change.test.tsx.snap
  ui/components/multichain/token-list-item/price/percentage-change/percentage-change.tsx
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/defi/components/__snapshots__/defi-details-list.test.tsx.snap
  ui/pages/defi/components/__snapshots__/defi-details-page.test.tsx.snap
Labels: team-design-system, size-S

#36091 test(ci): support tests that set manifestFlags.testing.infuraProjectId, such as power-user.spec.ts
  .github/workflows/e2e-chrome.yml
  .github/workflows/e2e-firefox.yml
  .github/workflows/main.yml
  .github/workflows/run-e2e.yml
Labels: team-extension-platform, no-changelog, size-S

#36062 fix: display of network and token icon in confirmation header for native tokens other than ETH
  test/data/send/assets.ts
  ui/pages/confirmations/hooks/send/metrics/useAssetSelectionMetrics.test.tsx
  ui/pages/confirmations/hooks/send/useCurrencyConversions.test.ts
  ui/pages/confirmations/hooks/send/useCurrencyConversions.ts
  ui/pages/confirmations/hooks/send/useSendType.ts
  ui/pages/confirmations/utils/send.ts
Labels: team-confirmations, size-M

#35987 refactor: Refactor keyring controller to use modular init pattern
  app/scripts/controller-init/accounts/snap-keyring-builder-init.test.ts
  app/scripts/controller-init/accounts/snap-keyring-builder-init.ts
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/keyring-controller-init.test.ts
  app/scripts/controller-init/keyring-controller-init.ts
  app/scripts/controller-init/messengers/accounts/index.ts
  app/scripts/controller-init/messengers/accounts/snap-keyring-builder-messenger.test.ts
  app/scripts/controller-init/messengers/accounts/snap-keyring-builder-messenger.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/keyring-controller-messenger.test.ts
  app/scripts/controller-init/messengers/keyring-controller-messenger.ts
  app/scripts/controller-init/types.ts
  app/scripts/lib/hardware-keyring-builder-factory.ts
  app/scripts/lib/qr-keyring-builder-factory.ts
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/lib/snap-keyring/types.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: size-L, team-core-platform

#36148 test: remove `openDAppWithContract` from helpers functions
  test/e2e/tests/confirmations/alerts/insufficient-funds.spec.ts
  test/e2e/tests/confirmations/transactions/contract-interaction-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc20-approve-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/erc721-approve-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/increase-token-allowance-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/revoke-allowance-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/shared.ts
Labels: team-qa, no-changelog, size-M

#36129 feat: cp-13.3.1 bump solana snap to 2.3.10
  package.json
  test/e2e/tests/metrics/delete-metametrics-data.spec.ts
  yarn.lock
Labels: team-new-networks, size-S, skip-e2e

#36140 fix: fixed OAuthConfig for experimental build cp-13.4.0
  app/scripts/services/oauth/config.ts
Labels: no-changelog, team-web3auth, seedless-onboarding, size-XS

#34923 test: remove login method from helpers and use page object flow instead
  test/e2e/helpers.js
  test/e2e/tests/swap-send/swap-send-erc20.spec.ts
  test/e2e/tests/swap-send/swap-send-eth-with-loaded-state.spec.ts
  test/e2e/tests/transaction/change-assets.spec.ts
  test/e2e/tests/transaction/gas-estimates.spec.js
  test/e2e/tests/transaction/send-eth.spec.js
  test/e2e/tests/transaction/send-hex-address.spec.js
  test/e2e/user-actions-benchmark.ts
Labels: team-qa, skip-e2e-quality-gate, no-changelog, size-M

#36172 fix: Sidestep rounding errors with Jazzicons
  .yarn/patches/@metamask-jazzicon-npm-2.0.0-36957be38d.patch
  package.json
  ui/components/app/account-list-item/__snapshots__/account-list-item-component.test.js.snap
  ui/components/app/modals/confirm-remove-account/__snapshots__/confirm-remove-account.test.js.snap
  ui/components/app/modals/hide-token-confirmation-modal/__snapshots__/hide-token-confirmation-modal.test.js.snap
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/snaps/snap-ui-address/__snapshots__/snap-ui-address.test.tsx.snap
  ui/components/app/snaps/snap-ui-renderer/components/__snapshots__/account-selector.test.ts.snap
  ui/components/app/snaps/snap-ui-renderer/components/__snapshots__/address-input.test.ts.snap
  ui/components/component-library/avatar-account/__snapshots__/avatar-account.test.tsx.snap
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/address-list-item/__snapshots__/address-list-item.test.tsx.snap
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/badge-status/__snapshots__/badge-status.test.js.snap
  ui/components/multichain/connect-accounts-modal/__snapshots__/connect-accounts-modal.test.tsx.snap
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/review-permissions-page/site-cell/__snapshots__/site-cell-tooltip.test.js.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/account-picker.test.tsx.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/components/multichain/toast/__snapshots__/toast.test.tsx.snap
  ui/components/ui/identicon/__snapshots__/identicon.component.test.js.snap
  ui/pages/bridge/prepare/components/__snapshots__/destination-account-picker-modal.test.tsx.snap
  ui/pages/confirm-add-suggested-nft/__snapshots__/confirm-add-suggested-nft.test.js.snap
  ui/pages/confirm-decrypt-message/__snapshots__/confirm-decrypt-message.component.test.js.snap
  ui/pages/confirm-encryption-public-key/__snapshots__/confirm-encryption-public-key.component.test.js.snap
  ui/pages/confirmations/components/confirm/header/__snapshots__/header.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/multichain-accounts/multichain-accounts-connect-page/__snapshots__/multichain-accounts-connect-page.test.tsx.snap
  ui/pages/permissions-connect/connect-page/__snapshots__/connect-page.test.tsx.snap
  yarn.lock
Labels: size-S, team-core-platform

#36100 feat: updates default destination token to metamask USDC on linea and ethereum
  shared/constants/bridge.ts
  test/e2e/tests/metrics/bridge.spec.ts
  ui/ducks/bridge/selectors.test.ts
  ui/pages/bridge/__snapshots__/index.test.tsx.snap
  ui/pages/bridge/prepare/__snapshots__/prepare-bridge-page.test.tsx.snap
  ui/pages/bridge/prepare/prepare-bridge-page.test.tsx
Labels: team-swaps-and-bridge, size-S

#36246 chore: bump multichain accounts deps
  package.json
  test/e2e/tests/multichain-accounts/multichain-account-list-page.spec.ts
  yarn.lock
Labels: team-accounts, size-S

#36118 fix: fixing NFT send related issues in new send flow
  test/data/send/assets.ts
  ui/pages/confirmations/components/UI/send-hero/send-hero.tsx
  ui/pages/confirmations/components/send/amount-recipient/amount-recipient.test.tsx
  ui/pages/confirmations/components/send/amount-recipient/amount-recipient.tsx
  ui/pages/confirmations/hooks/send/useSendNfts.test.ts
  ui/pages/confirmations/hooks/send/useSendNfts.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.ts
Labels: team-confirmations, no-changelog, size-M

#35804 refactor: Refactor network controller to use messenger and init pattern
  app/scripts/controller-init/assets/assets-contract-controller-init.test.ts
  app/scripts/controller-init/assets/assets-contract-controller-init.ts
  app/scripts/controller-init/confirmations/gas-fee-controller-init.ts
  app/scripts/controller-init/confirmations/ppom-controller-init.test.ts
  app/scripts/controller-init/confirmations/ppom-controller-init.ts
  app/scripts/controller-init/init-utils.ts
  app/scripts/controller-init/messengers/assets/assets-contract-controller-messenger.test.ts
  app/scripts/controller-init/messengers/assets/assets-contract-controller-messenger.ts
  app/scripts/controller-init/messengers/assets/index.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/network-controller-messenger.test.ts
  app/scripts/controller-init/messengers/network-controller-messenger.ts
  app/scripts/controller-init/messengers/ppom-controller-messenger.ts
  app/scripts/controller-init/network-controller-init.test.ts
  app/scripts/controller-init/network-controller-init.ts
  app/scripts/controller-init/test/utils.ts
  app/scripts/controller-init/token-list-controller-init.ts
  app/scripts/controller-init/tokens-controller-init.ts
  app/scripts/controller-init/types.ts
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
Labels: no-changelog, size-XL, team-core-platform

#36277 test: fix flaky test `test-e2e-chrome-api-specs
  test/e2e/api-specs/ConfirmationRejectionRule.ts
Labels: flaky tests, team-qa, no-changelog, size-XS

#36273 fix: Fix max value refresher
  ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useMaxValueRefresher.ts
Labels: team-confirmations, no-changelog, size-M

#36127 fix: amount error in fiat mode
  ui/pages/confirmations/components/confirm/header/wallet-initiated-header.tsx
  ui/pages/confirmations/components/send/amount-recipient/amount-recipient.tsx
  ui/pages/confirmations/components/send/amount/amount.test.tsx
  ui/pages/confirmations/components/send/amount/amount.tsx
  ui/pages/confirmations/hooks/send/useAmountValidation.test.ts
  ui/pages/confirmations/hooks/send/useAmountValidation.ts
  ui/pages/confirmations/hooks/send/useCurrencyConversions.test.ts
  ui/pages/confirmations/hooks/send/useCurrencyConversions.ts
  ui/pages/confirmations/hooks/useConfirmActions.test.ts
  ui/pages/confirmations/hooks/useConfirmActions.ts
  ui/pages/confirmations/hooks/useRedesignedSendFlow.test.ts
  ui/pages/confirmations/hooks/useRedesignedSendFlow.ts
  ui/pages/confirmations/utils/send.test.ts
  ui/pages/confirmations/utils/send.ts
Labels: team-confirmations, no-changelog, size-M

#35864 test: Migrate spec Request queuing UI
  test/e2e/page-objects/pages/confirmations/redesign/review-permissions-confirmation.ts
  test/e2e/page-objects/pages/confirmations/redesign/token-transfer-confirmation.ts
  test/e2e/page-objects/pages/confirmations/redesign/transaction-confirmation.ts
  test/e2e/page-objects/pages/header-navbar.ts
  test/e2e/page-objects/pages/network-manager.ts
  test/e2e/tests/request-queuing/ui.spec.ts
Labels: team-qa, no-changelog, size-M

#36065 fix: connection menu to support bip44
  ui/components/app/connected-status-indicator/connected-status-indicator.js
  ui/components/app/connected-status-indicator/connected-status-indicator.test.tsx
  ui/components/multichain/connected-site-menu/connected-site-menu.js
  ui/components/multichain/connected-site-menu/connected-site-menu.test.js
Labels: team-accounts, size-L

#34999 feat: add hyperliquid referral experience
  app/scripts/background.js
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/lib/createHyperliquidReferralMiddleware.test.ts
  app/scripts/lib/createHyperliquidReferralMiddleware.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  shared/constants/referrals.ts
  shared/types/background.ts
  test/e2e/default-fixture.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/pages/confirmations/confirmation/stories/hyperliquid-referral-consent.stories.tsx
  ui/pages/core/hyperliquid-referral-consent/hyperliquid-referral-consent.tsx
Labels: team-core-extension-ux, size-XL

#36209 feat: pre-fill Swap tokens with default BIP-44 pairs
  shared/constants/bridge.ts
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
  ui/ducks/bridge/utils.ts
  ui/hooks/bridge/useBridging.test.ts
  ui/hooks/bridge/useBridging.ts
Labels: team-swaps-and-bridge, size-M

#36291 fix(release creation scripts): adapt scripts to new branch name cp-13.3.2
  .github/scripts/push-firefox-bundle-script.sh
  .github/scripts/release-create-gh-release.sh
Labels: team-extension-platform, extension-delivery, size-S

#36300 fix: prevent non-entropy based accounts from showing "reveal private key" in account details
  ui/pages/multichain-accounts/multichain-account-details-page/multichain-account-details-page.tsx
Labels: team-accounts, size-S

#36307 feat: make wallet details title pattern consistent with account details
  ui/pages/multichain-accounts/wallet-details-page/wallet-details-page.test.tsx
  ui/pages/multichain-accounts/wallet-details-page/wallet-details-page.tsx
Labels: team-accounts, size-XS

#36323 fix: shield plan back
  ui/pages/shield-plan/shield-plan.tsx
Labels: QA Passed, team-web3auth, size-XS, area-shield

#36252 fix: always show Swap as CTA button text
  test/e2e/page-objects/pages/bridge/quote-page.ts
  ui/pages/bridge/prepare/__snapshots__/bridge-cta-button.test.tsx.snap
  ui/pages/bridge/prepare/bridge-cta-button.test.tsx
  ui/pages/bridge/prepare/bridge-cta-button.tsx
Labels: team-swaps-and-bridge, size-S

#36322 fix: fixes in check for new send flow
  ui/pages/confirmations/hooks/useRedesignedSendFlow.ts
Labels: team-confirmations, no-changelog, size-XS
