Repository MetaMask/metamask-extension, pull requests merged in 2025-01, with the labels that each got.

#29378 [cherry-pick to Version-v12.10.0] feat: bump solana snap (#29350)
  package.json
  privacy-snapshot.json
  yarn.lock
Labels: team-sol

#29434 fix: Correct theme value for Snap UI footer buttons
  ui/components/app/snaps/snap-ui-footer-button/snap-ui-footer-button.tsx
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#29422 chore: replace local `isSnapId` definition with `isSnapId` from `@metamask/snaps-utils`
  app/scripts/metamask-controller.js
  ui/components/app/confirm/info/row/url.tsx
  ui/components/app/connected-sites-list/connected-sites-list.component.js
  ui/components/app/snaps/snap-metadata-modal/snap-metadata-modal.js
  ui/components/multichain/pages/permissions-page/permissions-page.js
  ui/helpers/utils/snaps.ts
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign-v1/typed-sign-v1.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign.tsx
  ui/pages/permissions-connect/permissions-connect.component.js
  ui/pages/permissions-connect/snaps/snap-install/snap-install.js
  ui/pages/permissions-connect/snaps/snaps-connect/snaps-connect.js
  ui/pages/snaps/snap-view/snap-settings.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#29432 feat: add some authentication state to sentry logs
  app/scripts/constants/sentry-state.ts
  test/e2e/tests/metrics/errors.spec.js
Labels: team-notifications

#29399 fix (cherry-pick): remove reliance on transaction decode in confirmations #29341
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/data/confirmations/set-approval-for-all.ts
  test/data/confirmations/token-approve.ts
  test/data/confirmations/token-transfer.ts
  test/integration/confirmations/transactions/increase-allowance.test.tsx
  test/integration/confirmations/transactions/set-approval-for-all.test.tsx
  ui/helpers/constants/settings.js
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-details/__snapshots__/approve-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-details/approve-details.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve-details/approve-details.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.test.ts
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts
  ui/pages/confirmations/components/confirm/info/hooks/use-token-values.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/use-token-values.ts
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.ts
  ui/pages/confirmations/components/confirm/info/hooks/useTokenTransactionData.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useTokenTransactionData.ts
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/__snapshots__/set-approval-for-all-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/set-approval-for-all-info.test.tsx
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/set-approval-for-all-info.tsx
  ui/pages/confirmations/components/confirm/info/shared/send-heading/__snapshots__/send-heading.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/send-heading/send-heading.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/send-heading/send-heading.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/token-transfer.test.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/transaction-flow-section.test.tsx
  ui/pages/confirmations/components/confirm/info/token-transfer/transaction-flow-section.tsx
  ui/pages/confirmations/components/confirm/info/utils.test.ts
  ui/pages/confirmations/components/confirm/info/utils.ts
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/onboarding-flow/privacy-settings/privacy-settings.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
Labels: team-confirmations

#29464 Jl/multichain api e2e test refactor
  package.json
  test/e2e/flask/multichain-api/create-session.spec.ts
  test/e2e/flask/multichain-api/testHelpers.ts
  yarn.lock
Labels: team-wallet-api-platform

#29209 First Multichain API e2e Test
  .depcheckrc.yml
  development/create-static-server.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  test/e2e/fixture-builder.js
  test/e2e/flask/multichain-api/connect.spec.ts
  test/e2e/flask/multichain-api/create-session.spec.ts
  test/e2e/flask/multichain-api/get-session.spec.ts
  test/e2e/flask/multichain-api/testHelpers.ts
  test/e2e/helpers.js
  ui/components/ui/icon/preloader/preloader-icon.component.js
  ui/components/ui/list-item/__snapshots__/list-item.component.test.js.snap
  ui/ducks/bridge/selectors.ts
  ui/pages/confirmations/components/confirm/blockaid-loading-indicator/__snapshots__/blockaid-loading-indicator.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/base-transaction-info/__snapshots__/base-transaction-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/native-transfer/__snapshots__/native-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/nft-token-transfer/__snapshots__/nft-token-transfer.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/__snapshots__/advanced-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/confirm-loader/__snapshots__/confirm-loader.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/token-transfer/__snapshots__/token-transfer.test.tsx.snap
  ui/pages/confirmations/confirm-send-ether/__snapshots__/confirm-send-ether.test.js.snap
  yarn.lock
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#29437 chore: Fix flaky snap signature insights tests
  test/e2e/helpers.js
Labels: team-confirmations

#29466 fix: Use correct prop for Snap UI Avatar size
  ui/components/app/snaps/snap-ui-renderer/components/avatar.ts
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#28854 feat: enable STX by default with migration and notification
  app/_locales/en/messages.json
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/migrations/135.test.ts
  app/scripts/migrations/135.ts
  app/scripts/migrations/index.js
  shared/constants/alerts.ts
  shared/modules/selectors/smart-transactions.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/swaps.spec.js
  test/e2e/tests/swaps/shared.ts
  test/e2e/tests/swaps/swap-eth.spec.ts
  test/e2e/tests/swaps/swaps-notifications.spec.ts
  ui/pages/confirmations/components/smart-transactions-banner-alert/index.ts
  ui/pages/confirmations/components/smart-transactions-banner-alert/smart-transactions-banner-alert.test.tsx
  ui/pages/confirmations/components/smart-transactions-banner-alert/smart-transactions-banner-alert.tsx
  ui/pages/confirmations/components/transaction-alerts/transaction-alerts.js
  ui/pages/confirmations/components/transaction-alerts/transaction-alerts.test.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/confirm.test.tsx
  ui/pages/confirmations/confirm/confirm.tsx
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.test.js
Labels: team-confirmations, team-transactions, release-12.11.0

#29409 fix: xchain linea bugs
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  ui/pages/bridge/prepare/bridge-cta-button.tsx
Labels: team-bridge, team-swaps

#29320 fix: 'Incomplete Asset Displayed' called excessively via useTrackERC20WithoutDecimalInformation + clean: token details logic
  shared/modules/transaction.utils.ts
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/value-display/value-display.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/value-display/value-display.tsx
  ui/pages/confirmations/hooks/useGetTokenStandardAndDetails.ts
  ui/pages/confirmations/hooks/useTrackERC20WithoutDecimalInformation.test.ts
  ui/pages/confirmations/hooks/useTrackERC20WithoutDecimalInformation.ts
Labels: team-confirmations

#29411 fix: hide you received until bridge tx done
  ui/pages/bridge/transaction-details/transaction-details.tsx
Labels: team-swaps

#29484 Merge master into v12.10.0
  .yarn/patches/@metamask-assets-controllers-patch-d6ed5f8213.patch
  CHANGELOG.md
  app/scripts/lib/createMainFrameOriginMiddleware.ts
  app/scripts/lib/ppom/ppom-util.test.ts
  app/scripts/lib/ppom/ppom-util.ts
  app/scripts/metamask-controller.js
  app/scripts/migrations/133.2.test.ts
  app/scripts/migrations/133.2.ts
  app/scripts/migrations/index.js
  attribution.txt
  package.json
  shared/lib/confirmation.utils.test.ts
  shared/lib/confirmation.utils.ts
  ui/pages/confirmations/hooks/useCurrentConfirmation.test.ts
  ui/pages/confirmations/hooks/useCurrentConfirmation.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE

#29357 fix: import all detected tokens automatically
  ui/components/app/assets/asset-list/asset-list.test.tsx
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/multichain/account-overview/account-overview-eth.test.tsx
  ui/components/multichain/account-overview/account-overview-non-evm.test.tsx
Labels: team-assets, needs-assets-ux-review

#29412 chore: remove second inner scroll bar from tx details
  ui/pages/bridge/transaction-details/index.scss
  ui/pages/bridge/transaction-details/transaction-details.tsx
Labels: team-swaps

#29487 Jl/fix api specs multichain
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.test.ts
  app/scripts/metamask-controller.test.js
  privacy-snapshot.json
  test/e2e/api-specs/ConfirmationRejectionRule.ts
  test/e2e/fixture-builder.js
  test/e2e/run-api-specs-multichain.ts
  test/e2e/run-openrpc-api-test-coverage.ts
Labels: team-wallet-api-platform

#29046 fix: Fixes in NFT listing label and values
  app/_locales/en/messages.json
  test/e2e/tests/confirmations/signatures/nft-permit.spec.ts
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/typed-sign-v4-simulation.test.tsx
Labels: team-confirmations

#29442 test: Swap tests addition
  test/e2e/playwright/shared/pageObjects/network-controller-page.ts
  test/e2e/playwright/shared/pageObjects/signup-page.ts
  test/e2e/playwright/swap/pageObjects/swap-page.ts
  test/e2e/playwright/swap/specs/swap.spec.ts
  test/e2e/playwright/swap/tenderly-network.ts
Labels: team-swaps

#29197 feat: Adding more metrics parameters for signature decoding
  test/e2e/tests/confirmations/signatures/nft-permit.spec.ts
  test/e2e/tests/confirmations/signatures/permit.spec.ts
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  ui/pages/confirmations/hooks/useDecodedSignatureMetrics.test.ts
  ui/pages/confirmations/hooks/useDecodedSignatureMetrics.ts
Labels: team-confirmations

#29375 test: [POM] Migrate token tests
  test/e2e/page-objects/pages/home/asset-list.ts
  test/e2e/page-objects/pages/send/send-token-page.ts
  test/e2e/page-objects/pages/token-overview-page.ts
  test/e2e/tests/tokens/import-tokens.spec.ts
  test/e2e/tests/tokens/send-erc20-to-contract.spec.js
  test/e2e/tests/tokens/send-erc20-to-contract.spec.ts
  test/e2e/tests/tokens/token-list.spec.ts
  test/e2e/tests/tokens/token-sort.spec.ts
Labels: team-qa

#29496 fix: Bump Snap UI selector `min-height`
  ui/components/app/snaps/snap-ui-selector/snap-ui-selector.tsx
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#29493 fix: add lnk network logo
  app/images/ink-sepolia.svg
  app/images/ink.svg
  shared/constants/network.ts
Labels: team-assets, needs-assets-ux-review

#29495 cherry-pick: Correct theme value for Snap UI footer buttons
  ui/components/app/snaps/snap-ui-footer-button/snap-ui-footer-button.tsx
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#29494 fix: add kaia network logo
  app/images/kaia.svg
  app/images/klaytn.svg
  shared/constants/network.ts
Labels: team-assets, needs-assets-ux-review

#29478 fix: Bump smart-transactions-controller to ^16.0.1
  package.json
  yarn.lock
Labels: team-transactions

#29383 chore: add the new policy.json review process documentation and config
  .github/CODEOWNERS
  docs/lavamoat-policy-review-process.md
Labels: team-lavamoat

#29592 Jl/caip multichain/add api specs wallet create session
  test/e2e/api-specs/MultichainAuthorizationConfirmation.ts
  test/e2e/run-api-specs-multichain.ts
Labels: team-wallet-api-platform

#29480 test: fix flaky snap signature test
  test/e2e/helpers.js
  test/e2e/snaps/test-snap-siginsights.spec.js
Labels: team-confirmations

#29384 test: [POM] Migrate connections e2e tests to TS and Page Object Model
  shared/modules/bridge-utils/bridge.util.test.ts
  test/e2e/page-objects/pages/permission/site-permission-page.ts
  test/e2e/tests/connections/connect-with-metamask.spec.js
  test/e2e/tests/connections/edit-account-flow.spec.js
  test/e2e/tests/connections/edit-account-permissions.spec.ts
  test/e2e/tests/connections/edit-networks-flow.spec.js
  test/e2e/tests/connections/edit-networks-permissions.spec.ts
Labels: team-extension-platform, e2e-test

#29435 fix(snaps): Scrollbar being partially hidden behind footer
  ui/components/app/snaps/snap-ui-renderer/components/container.ts
  ui/components/app/snaps/snap-ui-renderer/index.scss
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/pages/confirmations/components/confirm/snaps/snaps-section/__snapshots__/snaps-section.test.tsx.snap
Labels: team-snaps-platform

#29476 chore: fix flaky e2e for nft token send
  test/e2e/helpers.js
  test/e2e/tests/confirmations/transactions/nft-token-send-redesign.spec.ts
Labels: team-confirmations

#29049 fix: show localized snap name in snap tag
  app/scripts/lib/accounts/BalancesController.test.ts
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/jest/mocks.ts
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-item/account-list-item.stories.js
  ui/components/multichain/account-list-item/account-list-item.test.js
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/account-list-menu/hidden-account-list.js
  ui/components/multichain/pages/connections/connections.tsx
  ui/components/multichain/pages/review-permissions-page/review-permissions-page.tsx
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/components/multichain/pages/send/components/your-accounts.tsx
  ui/components/multichain/pages/send/send.test.js
  ui/helpers/utils/accounts.js
  ui/helpers/utils/accounts.test.js
  ui/pages/permissions-connect/connect-page/connect-page.tsx
  ui/pages/remove-snap-account/snap-account-card.tsx
  ui/selectors/selectors.test.js
Labels: team-accounts

#29439 fix: Catch errors from the assets controller
  app/scripts/metamask-controller.js
Labels: team-confirmations

#28909 feat: Enable Ledger clear signing feature
  app/scripts/lib/offscreen-bridge/ledger-offscreen-bridge.ts
  offscreen/scripts/ledger.ts
Labels: QA Passed, INVALID-PR-TEMPLATE, team-hardware-wallets

#29511 cherrypick fix: xchain linea bugs (#29409)
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
  ui/pages/bridge/prepare/bridge-cta-button.tsx
Labels: team-swaps

#29486 fix: Fix bundle size tracking
  .circleci/config.yml
  package.json
  test/e2e/mv3-perf-stats/bundle-size.js
Labels: team-wallet-framework, team-extension-platform

#29618 test: Remove obsolete permitted chains feature flag tests
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.test.js
Labels: team-wallet-api-platform

#29616 test: Fix e2e swap test script
  test/e2e/playwright/shared/pageObjects/extension-page.ts
  test/e2e/playwright/shared/pageObjects/signup-page.ts
Labels: team-swaps, QA Passed

#29598 chore: bump `@metamask/profile-sync-controller` to `v3.2.0`
  package.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/integration/notifications&auth/data/notification-state.ts
  ui/selectors/identity/profile-syncing.test.ts
  yarn.lock
Labels: team-identity

#29477 feat: Display clickable cursor on hover on petname component
  ui/components/app/name/index.scss
Labels: team-confirmations

#29627 feat: Nonce is always editable in advanced details view
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/__snapshots__/advanced-details.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/advanced-details.tsx
Labels: team-confirmations

#29619 refactor: remove unused end param in ethereum-chain-util helpers
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
Labels: team-wallet-api-platform

#29491 add wallet_registerOnboarding to Multichain API
  app/scripts/metamask-controller.js
  test/e2e/run-api-specs-multichain.ts
Labels: team-wallet-api-platform

#29634 fix migration to skip malformed permission subjects
  app/scripts/migrations/137.test.ts
  app/scripts/migrations/137.ts
Labels: team-wallet-api-platform

#29522 Multichain API e2e test: calling `wallet_invokeMethod` on the same dapp across three different connected chains#3836
  package.json
  test/e2e/flask/multichain-api/create-session.spec.ts
  test/e2e/flask/multichain-api/invoke-method.spec.ts
  test/e2e/flask/multichain-api/testHelpers.ts
  yarn.lock
Labels: team-wallet-api-platform

#29635 chore: V12.10.0 changelog
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE, release-12.10.0

#29475 fix: change alert modal copy
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/alert-system/confirm-alert-modal/confirm-alert-modal.tsx
Labels: team-confirmations

#29637 fix: Fix LavaMoat build failures and restore RegExp OOM mitigation
  .yarn/patches/lavamoat-core-npm-16.2.2-e361ff1f8a.patch
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-wallet-framework, team-extension-platform, team-lavamoat, needs-dev-review

#28703 fix: Move foreground state properties from `metamask` slice to `appState` slice
  .storybook/test-data.js
  app/scripts/constants/sentry-state.ts
  docs/testing.md
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/import-tokens-modal/import-tokens-modal-confirm.js
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
  ui/ducks/app/app.test.js
  ui/ducks/app/app.ts
  ui/ducks/metamask/metamask.js
  ui/ducks/metamask/metamask.test.js
  ui/pages/asset/components/asset-page.test.tsx
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmations/confirmation/templates/remove-snap-account.test.js
  ui/pages/confirmations/token-allowance/token-allowance.test.js
  ui/pages/routes/routes.container.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-extension-platform, type-tech-debt, team-tiger

#29653 fix: duplicate content in multiple pending connect confirmations
  ui/pages/permissions-connect/permissions-connect.component.js
Labels: team-confirmations

#29292 fix: use correct color for bitcoin logo and remove the svg's embedded PNG
  app/images/bitcoin-logo.svg
Labels: team-extension-platform

#29294 build: remove unused `info-fox.svg`
  app/images/info-fox.svg
Labels: team-extension-platform

#29290 fix: center pixel art in `no-nfts.svg` and remove use of embedded png
  app/images/no-nfts.svg
Labels: team-extension-platform

#29632 feat: runway
  .github/workflows/main.yml
  .github/workflows/runway.yml
Labels: team-extension-platform

#29617 feat: improve xchain swaps slippage settings with decimals and warnings
  ui/pages/bridge/prepare/bridge-transaction-settings-modal.tsx
Labels: team-swaps

#29670 fix (cherry-pick): duplicate content in multiple pending connect confirmations (#29653)
  ui/pages/permissions-connect/permissions-connect.component.js
Labels: team-confirmations

#29413 chore: xchain tx details use short names
  ui/hooks/useTransactionDisplayData.js
  ui/pages/bridge/transaction-details/bridge-step-description.tsx
  ui/pages/bridge/transaction-details/transaction-detail-row.tsx
  ui/pages/bridge/transaction-details/transaction-details.tsx
Labels: team-swaps

#29366 feat: persist bridge state through ToS click
  ui/pages/bridge/index.test.tsx
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/bridge-input-group.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
Labels: team-swaps

#29687 fix: upgrade @metamask/eth-ledger-bridge-keyring library to latest
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: QA Passed, team-hardware-wallets

#29626 feat(snaps): add `hideBalances` to `getPreferences`
  app/scripts/metamask-controller.js
Labels: team-snaps-platform

#29654 feat: add auto sign-in for existing users
  ui/contexts/identity/index.test.tsx
  ui/contexts/identity/index.tsx
  ui/hooks/identity/useAuthentication/index.ts
  ui/hooks/identity/useAuthentication/useAutoSignIn.test.tsx
  ui/hooks/identity/useAuthentication/useAutoSignIn.ts
  ui/hooks/identity/useAuthentication/useSignIn.test.tsx
  ui/hooks/identity/useAuthentication/useSignIn.ts
Labels: team-identity

#29620 chore: remove `@metamask/ethjs` package
  app/scripts/lib/ens-ipfs/resolver.js
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
  app/scripts/ui.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/lib/four-byte.test.ts
  shared/lib/index.d.ts
  shared/modules/contract-utils.test.js
  shared/modules/contract-utils.ts
  shared/modules/transaction.utils.test.js
  shared/modules/transaction.utils.ts
  ui/ducks/confirm-transaction/confirm-transaction.duck.test.js
  ui/ducks/send/helpers.js
  ui/ducks/send/send.test.js
  ui/helpers/utils/token-util.js
  ui/helpers/utils/transactions.util.js
  ui/helpers/utils/util.js
  ui/pages/confirmations/confirm-approve/confirm-approve.js
  yarn.lock
Labels: team-wallet-framework

#29673 fix: Fix `SignatureController` hub `cancelWithReason` event handler
  app/scripts/metamask-controller.js
Labels: team-confirmations

#29639 Multichain API E2E Test: wallet_revokeSession
  test/e2e/flask/multichain-api/wallet_createSession.spec.ts
  test/e2e/flask/multichain-api/wallet_getSession.spec.ts
  test/e2e/flask/multichain-api/wallet_invokeMethod.spec.ts
  test/e2e/flask/multichain-api/wallet_notify.spec.ts
  test/e2e/flask/multichain-api/wallet_revokeSession.spec.ts
Labels: team-wallet-api-platform

#29671 test: add fixture permission controller test dapp two accounts
  test/e2e/fixture-builder.js
  test/e2e/json-rpc/eth_accounts.spec.ts
  test/e2e/tests/tokens/increase-token-allowance.spec.js
Labels: team-wallet-api-platform

#29682 address partially mutation state bugs
  app/scripts/migrations/137.test.ts
  app/scripts/migrations/137.ts
Labels: team-wallet-api-platform

#29672 Multichain API E2E Test: wallet_createSession called with an existing active session
  test/e2e/fixture-builder.js
  test/e2e/flask/multichain-api/wallet_createSession.spec.ts
  test/e2e/flask/multichain-api/wallet_revokeSession.spec.ts
Labels: team-wallet-api-platform

#29674 Jl/restore legacy fixtures
  test/e2e/fixture-builder.js
Labels: team-wallet-api-platform

#29675 test: Fix flask user-operations e2e test setup
  test/e2e/fixture-builder.js
  test/e2e/flask/user-operations.spec.ts
Labels: team-wallet-api-platform

#29710 test: Fixed Swap Playwright tests
  test/e2e/playwright/swap/pageObjects/swap-page.ts
  test/e2e/playwright/swap/tenderly-network.ts
Labels: team-swaps

#29714 chore: Remove unused `nonce-tracker` patch
  .yarn/patches/@metamask-nonce-tracker-npm-5.0.0-d81478218e.patch
  package.json
Labels: team-wallet-framework, team-extension-platform, needs-dev-review

#29676 fix: focused search field forces scroll
  ui/pages/bridge/prepare/bridge-input-group.tsx
Labels: team-bridge

#29701 fix: account syncing was not working after upgrading from a previous version
  app/scripts/migrations/137.test.ts
  app/scripts/migrations/137.ts
  app/scripts/migrations/index.js
  package.json
  yarn.lock
Labels: team-identity

#29016 feat: Add support for new Snaps state methods
  app/scripts/controllers/permissions/specifications.js
  app/scripts/metamask-controller.js
Labels: team-snaps-platform

#29718 fix: add prefix to account sync error message
  app/scripts/metamask-controller.js
Labels: team-identity

#29706 Multichain API E2E test: wallet_sessionChanged
  test/e2e/flask/multichain-api/wallet_sessionChanged.spec.ts
Labels: team-wallet-api-platform

#29649 chore: remove `@metamask/eth-query` package
  .yarn/patches/eth-query-npm-2.1.2-7c6adc825f.patch
  app/scripts/controllers/account-tracker-controller.ts
  app/scripts/lib/transaction/decode/proxy.test.ts
  app/scripts/lib/transaction/decode/proxy.ts
  app/scripts/lib/transaction/decode/util.test.ts
  app/scripts/lib/transaction/decode/util.ts
  app/scripts/lib/util.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  app/scripts/ui.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/lib/token-util.ts
  shared/modules/bridge-utils/balance.test.ts
  shared/modules/bridge-utils/balance.ts
  types/eth-query.d.ts
  types/global.d.ts
  ui/ducks/swaps/swaps.js
  ui/pages/bridge/prepare/prepare-bridge-page.test.tsx
  yarn.lock
Labels: team-wallet-framework

#29233 test: MMQA-188: remove mmi e2e tests from ci
  .circleci/config.yml
  .circleci/scripts/release-create-gh-release.sh
Labels: e2e-test, team-qa

#29732 cherry-pick: remove mmi tests into v12.10.1
  .circleci/config.yml
  .circleci/scripts/release-create-gh-release.sh
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#29733 Docs: Update Developer Docs link in README
  docs/README.md
Labels: area-documentation

#29081 feat(3744): Implement feature Flag Values with Scope Based on threshold
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/constants.ts
  test/e2e/mock-e2e.js
  test/e2e/tests/metrics/delete-metametrics-data.spec.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/portfolio/portfolio-site.spec.ts
  test/e2e/tests/remote-feature-flag/mock-data.ts
  test/e2e/tests/remote-feature-flag/remote-feature-flag.spec.ts
  ui/pages/settings/info-tab/info-tab.component.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/delete-metametrics-data-button/delete-metametrics-data-button.test.tsx
  ui/pages/settings/security-tab/delete-metametrics-data-button/delete-metametrics-data-button.tsx
  yarn.lock
Labels: team-extension-platform

#29722 fix: update eth-ledger-keyring-bridge lib to fix web pack issue.
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-hardware-wallets

#29735 chore: Update changelog for v12.10.1
  CHANGELOG.md
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#29729 test: Fix Playwright Swap e2e failures
  test/e2e/playwright/swap/specs/swap.spec.ts
Labels: team-swaps

#29734 docs: fix developer docs link in README
  README.md
Labels: area-documentation, team-snaps-platform

#29703 feat: Use a dynamic interval value for smart transaction status polling
  ui/ducks/swaps/swaps.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.container.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmations/hooks/useSmartTransactionFeatureFlags.test.ts
  ui/pages/confirmations/hooks/useSmartTransactionFeatureFlags.ts
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-transactions

#29474 feat: Add new completion_time_onchain property to Transaction Finalized events
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
Labels: team-confirmations

#29345 feat: check balance switching networks e2e tests
  privacy-snapshot.json
  test/e2e/fixture-builder.js
  test/e2e/flask/btc/common-btc.ts
  test/e2e/flask/create-watch-account.spec.ts
  test/e2e/flask/solana/check-balance.spec.ts
  test/e2e/flask/solana/common-solana.ts
  test/e2e/flask/solana/send-flow.spec.ts
  test/e2e/flask/solana/switching-network-accounts.spec.ts
  test/e2e/page-objects/pages/account-list-page.ts
  test/e2e/page-objects/pages/header-navbar.ts
  test/e2e/page-objects/pages/home/non-evm-homepage.ts
  test/e2e/page-objects/pages/send/solana-confirm-tx-page.ts
  test/e2e/page-objects/pages/send/solana-send-page.ts
  test/e2e/page-objects/pages/send/solana-tx-result-page.ts
Labels: team-sol

#29693 chore: Bump Snaps packages
  .yarn/patches/luxon-npm-3.2.1-56f8d97395.patch
  app/scripts/controllers/permissions/specifications.js
  app/scripts/metamask-controller.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-cronjob.spec.js
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/snaps/test-snap-managestate.spec.js
  test/e2e/snaps/test-snap-metrics.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/webdriver/driver.js
  ui/components/app/confirm/info/row/value-double.tsx
  ui/components/app/snaps/insight-warnings/insight-warnings.js
  ui/components/app/snaps/snap-home-page/snap-home-renderer.js
  ui/components/app/snaps/snap-insight/snap-insight.js
  ui/components/app/snaps/snap-ui-renderer/components/container.ts
  ui/components/app/snaps/snap-ui-renderer/components/section.ts
  ui/components/app/snaps/snap-ui-renderer/components/types.ts
  ui/components/app/snaps/snap-ui-renderer/components/value.ts
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/components/app/snaps/snap-ui-renderer/utils.ts
  ui/components/app/snaps/snap-ui-selector/index.scss
  ui/pages/confirmations/components/confirm/snaps/snaps-section/__snapshots__/snaps-section.test.tsx.snap
  ui/pages/confirmations/components/confirm/snaps/snaps-section/snap-insight.tsx
  ui/pages/confirmations/confirmation/confirmation.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#29614 chore: Master sync following v12.9.3, v12.10.0 and v12.10.1
  CHANGELOG.md
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#29658 chore: de-deuplicates the erc20 revoke allowance tests
  test/e2e/helpers.js
  test/e2e/tests/confirmations/transactions/erc20-approve-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/increase-token-allowance-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/revoke-allowance-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/shared.ts
Labels: team-confirmations

#29713 fix: add soneium logo
  app/images/soneium.svg
  shared/constants/network.ts
Labels: team-assets, INVALID-PR-TEMPLATE, needs-assets-ux-review

#29752 fix: remove check for changeX token from test
  test/e2e/tests/tokens/import-tokens.spec.ts
Labels: team-assets

#29467 test: fix flaky erc1155 set approval for all tests
  .vscode/cspell.json
  test/e2e/tests/confirmations/transactions/erc1155-set-approval-for-all-redesign.spec.ts
  test/e2e/webdriver/driver.js
Labels: team-confirmations

#29762 feat: add Lisk network logos
  app/images/lisk.svg
  app/images/lisk_sepolia.svg
  shared/constants/network.ts
Labels: team-assets

#29755 fix: Fix `EditAccountsModal` and `EditNetworkModal` checkboxes reseting back to default on rerender
  ui/components/multichain/edit-accounts-modal/edit-accounts-modal.tsx
  ui/components/multichain/edit-networks-modal/edit-networks-modal.js
Labels: team-wallet-api-platform

#29492 chore: remove bridge src token list from controller state
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/bridge/bridge-controller.test.ts
  app/scripts/controllers/bridge/bridge-controller.ts
  app/scripts/controllers/bridge/constants.ts
  app/scripts/controllers/bridge/types.ts
  app/scripts/metamask-controller.js
  shared/types/bridge.ts
  test/e2e/default-fixture.js
  test/e2e/fixture-builder.js
  test/e2e/tests/metrics/errors.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/components/multichain/asset-picker-amount/asset-picker-modal/AssetList.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
  ui/ducks/bridge/utils.ts
  ui/hooks/bridge/__snapshots__/useTokensWithFiltering.test.ts.snap
  ui/hooks/bridge/useBridgeTokens.ts
  ui/hooks/bridge/useTokensWithFiltering.test.ts
  ui/hooks/bridge/useTokensWithFiltering.ts
  ui/hooks/useTokensToSearch.js
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-bridge

#29761 test: Cleanup snap-account-signature e2e tests. Add permittedChains scenario to wallet_revokePermissions e2e test
  test/e2e/fixture-builder.js
  test/e2e/json-rpc/wallet_revokePermissions.spec.ts
  test/e2e/tests/account/snap-account-signatures-and-disconnects.spec.ts
  test/e2e/tests/account/snap-account-signatures.spec.ts
Labels: team-wallet-api-platform

#29767 test: Remove unused `restrictReturnedAccounts` param option
  test/e2e/fixture-builder.js
Labels: team-wallet-api-platform

#29770 add fix for lint error on v12.11.0
  CHANGELOG.md
Labels: team-extension-platform

#29778 chore: skips failing tests
  test/e2e/flask/solana/send-flow.spec.ts
Labels: team-sol

#29781 chore: cherry-pick skip failing tests from 16ac0894b3
  test/e2e/flask/solana/send-flow.spec.ts
Labels: team-extension-platform

#29597 fix: Missing "Unlimited" as value for the DAI permit
  test/integration/confirmations/signatures/permit-batch.test.tsx
  test/integration/confirmations/signatures/permit-single.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/constants.ts
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/value-display/value-display.tsx
  ui/pages/confirmations/components/confirm/row/dataTree.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/components/confirm/utils.ts
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/pages/confirmations/confirm/confirm.test.tsx
Labels: team-confirmations

#27025 refactor: use `withKeyring` method (#25435)
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
Labels: team-wallet-framework

#29747 feat: Enable BSC for smart transactions
  shared/constants/smartTransactions.test.ts
  shared/constants/smartTransactions.ts
Labels: area-transactions, team-transactions

#29783 test: Fix invalid fixture builder
  test/e2e/fixture-builder.js
Labels: team-wallet-framework, team-extension-platform, team-wallet-api-platform

#29709 chore: retain src input amount after switching tokens
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-bridge

#29502 feat: Use `gasLimitNoBuffer` on network fee estimation
  package.json
  shared/modules/gas.utils.js
  shared/modules/gas.utils.test.js
  test/data/confirmations/contract-interaction.ts
  test/data/confirmations/set-approval-for-all.ts
  test/data/confirmations/token-approve.ts
  test/data/confirmations/token-transfer.ts
  test/data/mock-state.json
  test/e2e/tests/transaction/edit-gas-fee.spec.js
  test/e2e/tests/transaction/send-edit.spec.js
  test/integration/confirmations/transactions/transactionDataHelpers.tsx
  test/integration/data/transaction-helpers.tsx
  ui/pages/confirmations/components/confirm-gas-display/confirm-gas-display.test.js
  ui/pages/confirmations/components/confirm/info/hooks/useFeeCalculations.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useFeeCalculations.ts
  ui/pages/confirmations/confirm-send-ether/confirm-send-ether.test.js
  ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.test.js
  ui/pages/confirmations/hooks/useGasEstimates.js
  ui/pages/confirmations/hooks/useGasEstimates.test.js
  ui/pages/confirmations/hooks/useGasFeeInputs.test.js
  ui/selectors/confirm-transaction.js
  yarn.lock
Labels: team-confirmations

#29790 fix: patch mantle price fix
  .yarn/patches/@metamask-assets-controllers-patch-d114308c1b.patch
  package.json
  yarn.lock
Labels: team-assets, needs-assets-ux-review

#29784 fix: Remove scroll to bottom requirement for signatures
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/webdriver/driver.js
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
Labels: team-confirmations

#29515 test: [POM] Migrate bitcoin send e2e tests to POM
  test/e2e/flask/btc/btc-send.spec.ts
  test/e2e/flask/btc/common-btc.ts
  test/e2e/page-objects/pages/home/activity-list.ts
  test/e2e/page-objects/pages/home/bitcoin-homepage.ts
  test/e2e/page-objects/pages/send/bitcoin-review-tx-page.ts
  test/e2e/page-objects/pages/send/bitcoin-send-page.ts
Labels: team-extension-platform, e2e-test, team-qa

#28184 feat: add Portfolio button to BTC accounts
  test/e2e/flask/btc/btc-account-overview.spec.ts
  ui/components/app/wallet-overview/coin-overview.tsx
Labels: team-wallet-ux

#29805 chore: Bump `@metamask/snaps-rpc-methods` from `^11.9.0` to `^11.9.1`
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#29808 fix: Revert "fix: Remove scroll to bottom requirement for signatures"
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/webdriver/driver.js
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
Labels: INVALID-PR-TEMPLATE, team-confirmations

#29807 build: update the patches applied in the package.json
  .yarn/patches/@metamask-assets-controllers-patch-d114308c1b.patch
  yarn.lock
Labels: team-notifications

#25653 feat(lavamoat/lavadome): update integration to improve security
  app/manifest/v2/brave.json
  app/manifest/v2/chrome.json
  app/manifest/v3/chrome.json
  app/scripts/ui.js
Labels: team-lavamoat, INVALID-PR-TEMPLATE

#29817 fix: Remove scroll to bottom requirement for signatures
  test/e2e/snaps/test-snap-ethprovider.spec.js
  test/e2e/webdriver/driver.js
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
Labels: INVALID-PR-TEMPLATE, team-qa

#29822 chore: Bump `@metamask/snaps-rpc-methods` from `^11.9.0` to `^11.9.1`
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#29007 test: address integration tests warnings
  test/integration/confirmations/signatures/permit-single.test.tsx
  test/integration/confirmations/signatures/personalSign.test.tsx
  test/integration/data/integration-init-state.json
  test/integration/data/onboarding-completion-route.json
  test/integration/notifications&auth/notifications-toggle.test.tsx
  test/integration/onboarding/wallet-created.test.tsx
  test/stub/provider.js
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/permit-simulation/permit-simulation.tsx
  ui/pages/routes/routes.component.js
Labels: INVALID-PR-TEMPLATE, team-confirmations

#29792 fix: Remove old properties from state
  app/scripts/migrations/140.test.ts
  app/scripts/migrations/140.ts
  app/scripts/migrations/index.js
Labels: team-wallet-framework

#29195 feat: add `scopes` field to `KeyringAccount`
  app/scripts/controllers/alert-controller.test.ts
  app/scripts/lib/snap-keyring/snap-keyring.test.ts
  app/scripts/migrations/105.test.ts
  app/scripts/migrations/105.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  test/data/mock-accounts.ts
  test/data/mock-state.json
  test/e2e/constants.ts
  test/e2e/flask/btc/common-btc.ts
  test/e2e/flask/solana/common-solana.ts
  test/e2e/mock-e2e.js
  test/jest/mocks.ts
  ui/components/multichain/connect-accounts-modal/connect-accounts-modal-list.test.tsx
  ui/components/multichain/permission-details-modal/permission-details-modal.test.tsx
  ui/hooks/accounts/useMultichainWalletSnapClient.test.ts
  ui/selectors/accounts.test.ts
  ui/selectors/selectors.test.js
  yarn.lock
Labels: team-accounts

#29809 fix: not routing to home page after bridge tx submitted
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.test.tsx
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.ts
Labels: team-swaps

#29810 refactor: Restore messengers in controller init request
  app/scripts/controller-init/confirmations/ppom-controller-init.ts
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/controller-init/messengers/messengers.ts
  app/scripts/controller-init/types.ts
  app/scripts/controller-init/utils.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-framework

#29827 chore: update test dapp version to 9.0.0
  package.json
  yarn.lock
Labels: team-qa

#29838 fix: overflow of title/description in Snap `Card` component
  ui/components/app/snaps/snap-ui-card/snap-ui-card.tsx
Labels: team-snaps-platform

#29839 chore: upgrade `@metamask/user-operation-controller`
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-accounts

#29832 fix: handle undefined token address in useBridging hook
  ui/hooks/bridge/useBridging.ts
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
Labels: team-bridge

#29850 fix: centering on Snap radio buttons
  ui/components/app/snaps/snap-ui-radio-group/snap-ui-radio-group.tsx
Labels: team-snaps-platform

#29854 fix: (cherry-pick 29832) routing to bridge from swaps after reopening popup
  ui/hooks/bridge/useBridging.ts
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
Labels: team-bridge

#29705 feat: solana swap and bridge navigation
  builds.yml
  shared/constants/bridge.ts
  shared/constants/swaps.ts
  test/e2e/flask/solana/send-flow.spec.ts
  test/e2e/page-objects/pages/home/non-evm-homepage.ts
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/app/wallet-overview/non-evm-overview.test.tsx
  ui/components/app/wallet-overview/non-evm-overview.tsx
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/bridge-input-group.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/selectors/multichain.ts
  ui/selectors/selectors.js
Labels: team-swaps

#28189 refactor: remove unused `startApprovalFlow` and `endApprovalFlow` hooks from `wallet_addEthereumChain` and `wallet_switchEthereumChain`
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.test.js
  app/scripts/metamask-controller.js
  docs/confirmations.md
Labels: team-wallet-api-platform

#29861 chore: bump `@metamask/multichain` to `^2.1.0`
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#28875 chore: integrate `MultichainBalancesController`
  .yarn/patches/@metamask-assets-controllers-npm-45.1.0-d914c453f0.patch
  .yarn/patches/@metamask-assets-controllers-npm-46.0.0-ff9413463e.patch
  app/scripts/lib/accounts/BalancesController.test.ts
  app/scripts/lib/accounts/BalancesController.ts
  app/scripts/lib/accounts/BalancesTracker.test.ts
  app/scripts/lib/accounts/BalancesTracker.ts
  app/scripts/lib/accounts/Poller.test.ts
  app/scripts/lib/accounts/Poller.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/components/app/wallet-overview/non-evm-overview.test.tsx
  ui/hooks/accounts/useMultichainWalletSnapClient.ts
  ui/hooks/useCurrencyDisplay.js
  ui/hooks/useMultichainAccountTotalFiatBalance.ts
  ui/selectors/multichain.ts
  yarn.lock
Labels: team-accounts

#29860 fix: missing smart transaction status confirmation
  ui/pages/confirmations/hooks/useConfirmationNavigation.test.ts
  ui/pages/confirmations/hooks/useConfirmationNavigation.ts
  ui/pages/home/home.component.js
Labels: team-confirmations

#29874 feat: upgrade ledger keyring to fix EIP-712 issues
  .yarn/patches/@ledgerhq-evm-tools-npm-1.3.0-57435278f6.patch
  .yarn/patches/@ledgerhq-hw-app-eth-npm-6.42.2-46a44bfbf5.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  offscreen/scripts/ledger.ts
  package.json
  yarn.lock
Labels: team-hardware-wallets

#29775 fix: Bug in transaction flow component for 1155 token
  ui/pages/confirmations/components/confirm/info/hooks/useTransferRecipient.ts
Labels: team-confirmations

#29870 fix: add mode logo
  app/images/mode-sepolia.svg
  app/images/mode.svg
  shared/constants/network.ts
Labels: team-assets

#29129 feat: SOL-46 Adds tx history via multichain transactions controller
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/scripts/metamask-controller.js
  lavamoat/browserify/flask/policy.json
  package.json
  test/e2e/flask/btc/btc-send.spec.ts
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/app/transaction-list/transaction-list.test.js
  ui/selectors/accounts.ts
  ui/selectors/multichain.test.ts
  ui/selectors/multichain.ts
  yarn.lock
Labels: team-sol

#29683 chore: rm bridge dest token list
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/bridge/bridge-controller.test.ts
  app/scripts/controllers/bridge/bridge-controller.ts
  app/scripts/controllers/bridge/constants.ts
  app/scripts/controllers/bridge/types.ts
  app/scripts/metamask-controller.js
  shared/types/bridge.ts
  test/e2e/default-fixture.js
  test/e2e/fixture-builder.js
  test/e2e/tests/metrics/errors.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/ducks/bridge/actions.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/selectors.test.ts
  ui/ducks/bridge/selectors.ts
  ui/hooks/bridge/__snapshots__/useTokensWithFiltering.test.ts.snap
  ui/hooks/bridge/useTokensWithFiltering.test.ts
  ui/hooks/bridge/useTokensWithFiltering.ts
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-bridge

#29864 fix: Fix bug where testnets do not show up correctly in the incremental permission view
  ui/selectors/selectors.js
Labels: team-wallet-api-platform

#29867 chore: update accounts deps
  .yarn/patches/@metamask-assets-controllers-npm-46.0.1-3c56f3157c.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-accounts

#29881 fix (cherry-pick): missing smart transaction status confirmation (#29860)
  ui/pages/confirmations/hooks/useConfirmationNavigation.test.ts
  ui/pages/confirmations/hooks/useConfirmationNavigation.ts
  ui/pages/home/home.component.js
Labels: team-confirmations

#29883 fix: (cherry pick) route to bridge page from swaps
  ui/hooks/bridge/useBridging.ts
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
Labels: team-bridge

#29885 add test case
  test/e2e/json-rpc/wallet_addEthereumChain.spec.ts
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#29855 fix: fix permissions not correctly being updated when all network clients are removed for a chainId
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  test/e2e/fixture-builder.js
  test/e2e/json-rpc/wallet_revokePermissions.spec.ts
  test/e2e/tests/network/remove-network.spec.ts
Labels: team-wallet-framework, team-wallet-api-platform

#29700 fix: add sonic mainnet logo
  app/images/sonic.svg
  shared/constants/network.ts
Labels: team-assets, needs-assets-ux-review

#28833 test: foundryup unit
  jest.config.js
  package.json
  test/helpers/foundry/download.ts
  test/helpers/foundry/extract.ts
  test/helpers/foundry/foundryup.mts
  test/helpers/foundry/foundryup.test.ts
  test/helpers/foundry/foundryup.ts
  test/helpers/foundry/helpers.mts
  test/helpers/foundry/options.ts
  test/helpers/foundry/tsconfig.json
  test/helpers/foundry/types.ts
  test/helpers/foundry/utils.ts
Labels: team-extension-platform, area-qa

#29651 test: migrate more token tests and update related page objects
  test/e2e/page-objects/flows/send-transaction.flow.ts
  test/e2e/page-objects/pages/confirmations/redesign/token-transfer-confirmation.ts
  test/e2e/page-objects/pages/dialog/approve-tokens.ts
  test/e2e/page-objects/pages/dialog/transfer-token.ts
  test/e2e/page-objects/pages/home/activity-list.ts
  test/e2e/page-objects/pages/home/asset-list.ts
  test/e2e/page-objects/pages/home/homepage.ts
  test/e2e/page-objects/pages/send/confirm-tx-page.ts
  test/e2e/page-objects/pages/send/send-token-page.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/tokens/add-multiple-tokens.spec.ts
  test/e2e/tests/tokens/custom-token-send-transfer.spec.js
  test/e2e/tests/tokens/custom-token-send-transfer.spec.ts
  test/e2e/tests/tokens/import-tokens.spec.ts
  test/e2e/tests/tokens/token-details.spec.ts
  test/e2e/tests/tokens/token-list.spec.ts
  test/e2e/tests/tokens/token-sort.spec.ts
  test/e2e/tests/tokens/utils/mocks.ts
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
  ui/pages/confirmations/components/approve-content-card/approve-content-card.js
  ui/pages/confirmations/components/review-spending-cap/review-spending-cap.js
Labels: team-qa

#29880 fix: updated permissions header to be consistent
  ui/pages/permissions-connect/permissions-connect.component.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux
