Repository MetaMask/metamask-extension, pull requests merged in 2025-08, with the labels that each got.

#34777 build(webpack): silence swc sourcemap messages on Windows
  development/webpack/utils/loaders/swcLoader.ts
Labels: team-extension-platform, no-changelog

#34769 test(e2e): Deflake `onStart` lifecycle hook test
  test/e2e/snaps/test-snap-lifecycle.spec.ts
Labels: team-snaps-platform, no-changelog

#34567 chore: Remove `@sentry/browser` from main bundles
  app/scripts/lib/setupSentry.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  shared/lib/sentry.ts
  shared/lib/trace.ts
  ui/helpers/utils/i18n-helper.test.js
Labels: team-wallet-framework

#34788 release: Master sync v13.0.0 into main
  CHANGELOG.md
  package.json
Labels: team-extension-platform, extension-delivery

#34793 test: remove unnecessary balance-check race in test
  test/e2e/tests/privacy/onboarding-infura-call-privacy.spec.ts
Labels: team-extension-platform, no-changelog

#34783 fix: bump @metamask/multichain-api-client to v0.6.5
  package.json
  yarn.lock
Labels: team-wallet-standard

#34717 chore: updated release workflows to eliminate confusion
  .github/workflows/create-release-pr-legacy.yml
  .github/workflows/create-release-pr.yml
Labels: INVALID-PR-TEMPLATE, team-dev-ops, no-changelog

#34641 chore: put comments back in `.yarnrc.yml`
  .yarnrc.yml
Labels: team-extension-platform, no-changelog

#34782 fix: Hide resimulate alert if transaction is wallet initiated
  ui/pages/confirmations/hooks/alerts/transactions/useResimulationAlert.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useResimulationAlert.ts
Labels: team-confirmations, no-changelog

#34733 feat: consume send bundle feature flag to determine `alternateGasFee` support
  app/scripts/lib/transaction/eip5792.test.ts
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/lib/transaction/sentinel-api.test.ts
  app/scripts/lib/transaction/sentinel-api.ts
  app/scripts/lib/transaction/transaction-relay.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/confirmations/transactions/gas-fee-tokens-eip-7702.spec.ts
  test/e2e/tests/confirmations/transactions/gas-fee-tokens-smart-transactions.spec.ts
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
  ui/pages/confirmations/hooks/gas/useIsGaslessSupported.test.ts
  ui/pages/confirmations/hooks/gas/useIsGaslessSupported.ts
  ui/store/actions.ts
Labels: team-confirmations

#34837 fix(action): pass version tag instead of a branch name to github-tools
  .github/workflows/create-release-pr.yml
Labels: team-extension-platform

#34832 test: cherry-pick `4be7602` balance e2e flaky test
  attribution.txt
  test/e2e/tests/privacy/onboarding-infura-call-privacy.spec.ts
Labels: team-qa

#34696 test: Migrate request queuing dapp1-send-dapp2-signTypedData test to Typescript and POM
  test/e2e/page-objects/pages/confirmations/redesign/sign-typed-data-confirmation.ts
  test/e2e/tests/request-queuing/dapp1-send-dapp2-signTypedData.spec.ts
Labels: team-qa

#34857 fix(snaps): Catch `handleSnapRequest` error in `SnapInterfaceContext`
  ui/contexts/snaps/snap-interface.tsx
Labels: team-snaps-platform

#34594 fix: Fix metric transaction type for bridge and swap transactions
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  package.json
  ui/pages/confirmations/hooks/transactions/useTransactionConfirm.test.ts
  ui/pages/confirmations/hooks/transactions/useTransactionConfirm.ts
  yarn.lock
Labels: team-confirmations, no-changelog

#34707 test: Optimize test server shutdown
  .eslintrc.base.js
  test/e2e/helpers.js
Labels: team-wallet-framework

#34844 test: add missing tests for `getWalletIdAndNameByAccountAddress` selector
  ui/selectors/multichain-accounts/account-tree.test.ts
Labels: team-accounts, INVALID-PR-TEMPLATE, no-changelog

#34768 feat: better manage automatic labeling of Sentry issues
  .github/scripts/check-template-and-add-labels.ts
  .github/scripts/shared/label.ts
Labels: team-extension-platform, no-changelog

#34852 fix: moved pwd-change to background cp-13.1.0
  app/scripts/controllers/onboarding.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  test/env.js
  ui/pages/onboarding-flow/welcome/welcome-login.test.tsx
  ui/pages/onboarding-flow/welcome/welcome.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/unlock-page/unlock-page.test.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: area-onboarding, team-web3auth

#34877 fix: flaky test `Multichain Aggregated Balances shows correct aggrega…
  test/e2e/page-objects/pages/send/send-token-page.ts
Labels: team-qa

#34876 fix: flaky test `Editing Confirm Transaction goes back from confirm page to edit eth value, baseFee, priorityFee and gas limit - 1559 V2` (#34854)
  test/e2e/tests/transaction/send-edit.spec.js
Labels: team-qa

#34896 ci: post validation bot to add a checklist in `feat` and `perf` PRs #17937
  .github/workflows/post-merge-validation.yml
Labels: team-qa, no-changelog

#34904 ci: add RCA-needed label on RCA workflow
  .github/workflows/add-team-label.yml
  .github/workflows/automated-rca.yml
Labels: team-qa, no-changelog

#34821 fix: slippage update on unified cp-13.1.0
  ui/hooks/bridge/useSmartSlippage.ts
  ui/pages/bridge/prepare/bridge-transaction-settings-modal.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/utils/slippage-service.test.ts
  ui/pages/bridge/utils/slippage-service.ts
  ui/pages/bridge/utils/stablecoins.ts
Labels: team-swaps-and-bridge

#34710 test: Fixed the asset list test
  test/e2e/page-objects/pages/home/asset-list.ts
  test/e2e/page-objects/pages/send/send-token-page.ts
  test/e2e/tests/multichain/asset-list.spec.ts
Labels: INVALID-PR-TEMPLATE, team-qa, no-changelog

#34912 chore: Revert "feat: set default theme to dark (#34274)"
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/fixtures/with-preferences.js
  ui/hooks/useTheme.ts
Labels: team-extension-platform

#34907 chore: Bump Snaps packages
  builds.yml
  package.json
  yarn.lock
Labels: team-snaps-platform, no-changelog

#34916 fix: add slippage to quote card cp-13.1.0
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/quotes/__snapshots__/bridge-quote-card.test.tsx.snap
  ui/pages/bridge/quotes/bridge-quote-card.tsx
  ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx
Labels: team-swaps-and-bridge

#34530 feat: add CSS-based loading timeout message
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/partial-body.html
  development/verify-locale-strings.js
  ui/css/loading.scss
Labels: team-extension-platform

#34288 fix(security): obfuscate blurred SRP to prevent blur-reversal attacks
  ui/pages/onboarding-flow/recovery-phrase/__snapshots__/review-recovery-phrase.test.js.snap
  ui/pages/onboarding-flow/recovery-phrase/recovery-phrase-chips.js
  ui/pages/onboarding-flow/recovery-phrase/recovery-phrase-chips.test.js
Labels: team-extension-platform

#34891 refactor: Add route constants infrastructure for React Router v5-compat migration
  ui/helpers/constants/routes.test.ts
  ui/helpers/constants/routes.ts
  ui/helpers/higher-order-components/with-router-hooks/with-router-hooks.test.tsx
  ui/helpers/higher-order-components/with-router-hooks/with-router-hooks.tsx
Labels: team-extension-platform

#34943 fix: handle undefined destination account in bridge
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#34930 chore: update `SEI` network's name from `Sei Network` to `Sei Mainnet`
  app/scripts/migrations/173.test.ts
  app/scripts/migrations/173.ts
  app/scripts/migrations/index.js
  shared/constants/network.test.ts
  shared/constants/network.ts
  shared/constants/swaps.ts
  ui/components/multichain/network-list-menu/__snapshots__/network-list-menu.test.js.snap
Labels: QA Passed, team-network-enablement

#34887 fix: cp-13.1.0 bump solana snap
  .yarn/patches/@metamask-assets-controllers-npm-73.0.2-a36b91b0e4.patch
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  yarn.lock
Labels: team-new-networks

#34888 fix: flaky test `Forgot password resets password and then unlock wallet with new password`, `Migrate vault with old encryption` and `Lock and unlock`
  test/e2e/tests/account/forgot-password.spec.ts
  test/e2e/tests/account/lock-account.spec.ts
  test/e2e/tests/account/migrate-old-vault.spec.ts
Labels: flaky tests, team-qa, no-changelog

#34964 fix: Remove hover state when `SnapUISelector` is disabled
  ui/components/app/snaps/snap-ui-selector/index.scss
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#34944 ci: add missing teams for the `identify-codeowners` job
  .github/scripts/identify-codeowners.ts
Labels: team-qa, no-changelog

#34963 chore: bump multichain account dependencies
  app/scripts/controller-init/messengers/accounts/account-tree-controller-messenger.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  package.json
  test/data/mock-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain-accounts/multichain-account-list-menu/multichain-account-list-menu.test.tsx
  ui/components/multichain-accounts/multichain-account-list/multichain-account-list.test.tsx
  ui/components/multichain-accounts/multichain-accounts-tree/multichain-accounts-tree.test.tsx
  ui/selectors/multichain-accounts/account-tree.test.ts
  ui/selectors/multichain-accounts/account-tree.ts
  ui/selectors/multichain-accounts/account-tree.types.ts
  yarn.lock
Labels: team-accounts

#34961 fix: fixed invalid refresh token after login attempt cp-13.0.1
  app/scripts/services/oauth/base-login-handler.ts
  app/scripts/services/oauth/oauth-service.test.ts
  package.json
  yarn.lock
Labels: team-web3auth

#34855 ci(next semver version): rely on package.json when crafting next semver version
  .github/scripts/get-next-semver-version.sh
  development/get-next-semver-version.sh
Labels: team-extension-platform

#34973 chore: chore/13.0.1-Changelog
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE, release-13.0.1

#34966 test: Force exit after running E2E test
  test/e2e/run-e2e-test.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#34970 release: 13.0.1
  .yarn/patches/@metamask-assets-controllers-npm-72.0.0-d780726ee3.patch
  CHANGELOG.md
  app/scripts/services/oauth/base-login-handler.ts
  app/scripts/services/oauth/oauth-service.test.ts
  attribution.txt
  package.json
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  yarn.lock
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE, release-13.0.1

#34981 ci: adapt PR size job to have permissions to add labels
  .github/workflows/check-pr-max-lines.yml
Labels: team-qa, no-changelog, size-XS

#34996 feat: allow offline unlock for social login users
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
Labels: QA Passed, team-web3auth, seedless-onboarding

#34823 refactor: import getCaip25PermissionFromLegacyPermissions and request requestPermittedChainsPermissionIncremental from chain agnostic permission package
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  package.json
  yarn.lock
Labels: team-wallet-api-platform, no-changelog

#35026 test: Force exit after running E2E test (#34966) cherry-pick
  test/e2e/run-e2e-test.js
Labels: team-qa

#35027 release: Master sync v13.0.1 into main
  CHANGELOG.md
Labels: team-extension-platform, size-XS

#35011 refactor(5560): migrate create-account.component.js to react-router-v5-compat
  ui/pages/create-account/connect-hardware/account-list.test.js
  ui/pages/create-account/connect-hardware/index.js
  ui/pages/create-account/connect-hardware/index.test.tsx
  ui/pages/create-account/create-account.component.js
Labels: team-extension-platform, size-S

#33276 refactor: Migrate `<Routes />` into a TypeScript functional component
  ui/helpers/higher-order-components/authenticated/authenticated.component.js
  ui/helpers/higher-order-components/initialized/initialized.component.js
  ui/helpers/utils/mm-lazy.ts
  ui/pages/routes/index.js
  ui/pages/routes/routes.component.js
  ui/pages/routes/routes.component.tsx
  ui/pages/routes/routes.container.js
  ui/selectors/assets.ts
  ui/selectors/selectors.js
  ui/store/store.ts
Labels: team-extension-platform, INVALID-PR-TEMPLATE, no-changelog, size-XL

#35036 fix: skip metametrics if user has already chosen an option
  ui/pages/onboarding-flow/create-password/create-password.js
  ui/pages/onboarding-flow/create-password/create-password.test.js
Labels: QA Passed, team-web3auth, size-S

#34988 chore: removes the Solana modal from the initial flow
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/solana-logo-transparent.svg
  shared/notifications/index.ts
  ui/components/app/whats-new-modal/notifications.ts
  ui/components/app/whats-new-modal/solana/index.ts
  ui/components/app/whats-new-modal/solana/modal-body.tsx
  ui/components/app/whats-new-modal/solana/modal-footer.tsx
  ui/components/app/whats-new-modal/solana/modal-header.tsx
  ui/components/app/whats-new-modal/whats-new-modal.stories.tsx
  ui/components/app/whats-new-modal/whats-new-modal.test.tsx
  ui/components/app/whats-new-modal/whats-new-modal.tsx
  ui/pages/home/home.container.js
  ui/selectors/selectors.js
Labels: team-new-networks

#35038 fix: show effective gas in swaps QuoteCard cp-13.1.0
  package.json
  shared/lib/bridge/metrics.ts
  shared/modules/bridge-utils/security-alerts-api.util.ts
  test/data/bridge/mock-bridge-store.ts
  ui/ducks/bridge/selectors.test.ts
  ui/pages/bridge/quotes/bridge-quotes-modal.tsx
  ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx
  yarn.lock
Labels: team-swaps-and-bridge, size-S

#35044 feat: get all internal accounts for a given scope (non user facing change)
  ui/selectors/accounts.test.ts
  ui/selectors/accounts.ts
Labels: team-accounts, size-M

#35103 chore: update design system documentation
  docs/design-system.md
Labels: team-design-system, no-changelog, size-S

#35117 feat: Add Linea for Smart Transactions, bump smart-transactions-controller to ^18.1.0
  package.json
  shared/constants/smartTransactions.test.ts
  shared/constants/smartTransactions.ts
  shared/modules/selectors/index.test.ts
  yarn.lock
Labels: team-transactions, size-S

#35119 fix: redact email from state logs
  app/scripts/lib/state-utils.test.ts
  app/scripts/lib/state-utils.ts
Labels: team-web3auth, size-XS

#35123 fix: redact email from state logs (#35119)
  app/scripts/lib/state-utils.test.ts
  app/scripts/lib/state-utils.ts
Labels: team-qa

#35126 fix: cp-13.1.0 Prevent dapp network change from network manager
  test/e2e/tests/request-queuing/ui.spec.js
  ui/components/multichain/connected-site-popover/connected-site-popover.tsx
  ui/components/multichain/network-manager/hooks/useNetworkChangeHandlers.ts
Labels: team-wallet-ux, size-S

#35048 fix: Unified Swaps QuotesReceived and tx event properties
  app/scripts/lib/bridge-status/metrics.ts
  package.json
  shared/lib/bridge-status/metrics.ts
  ui/hooks/bridge/events/useTradeProperties.ts
  ui/hooks/bridge/useBridging.ts
  ui/hooks/bridge/useQuoteFetchEvents.ts
  ui/pages/bridge/quotes/bridge-quotes-modal.tsx
  yarn.lock
Labels: team-swaps-and-bridge, size-M

#35112 release(runway): cherry-pick fix: show effective gas in swaps QuoteCard (COPY)
  attribution.txt
  package.json
  shared/lib/bridge/metrics.ts
  shared/modules/bridge-utils/security-alerts-api.util.ts
  test/data/bridge/mock-bridge-store.ts
  ui/ducks/bridge/selectors.test.ts
  ui/pages/bridge/quotes/bridge-quote-card.tsx
  ui/pages/bridge/quotes/bridge-quotes-modal.tsx
  ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx
  yarn.lock
Labels: team-extension-platform

#35121 chore: chore/13.1.0-Changelog
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, release-13.1.0

#35177 chore: Bump main version to 13.3.0
  package.json
Labels: team-extension-platform, INVALID-PR-TEMPLATE, size-XS, release-13.3.0

#35019 fix: Fix flickering alert issue
  ui/pages/confirmations/hooks/alerts/transactions/useMultipleApprovalsAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useMultipleApprovalsAlerts.ts
Labels: team-confirmations, no-changelog, size-M

#35225 cherry-pick(13.1.1): chore: removes the Solana modal from the initial flow (#34988)
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/solana-logo-transparent.svg
  shared/notifications/index.ts
  ui/components/app/whats-new-modal/notifications.ts
  ui/components/app/whats-new-modal/solana/index.ts
  ui/components/app/whats-new-modal/solana/modal-body.tsx
  ui/components/app/whats-new-modal/solana/modal-footer.tsx
  ui/components/app/whats-new-modal/solana/modal-header.tsx
  ui/components/app/whats-new-modal/whats-new-modal.stories.tsx
  ui/components/app/whats-new-modal/whats-new-modal.test.tsx
  ui/components/app/whats-new-modal/whats-new-modal.tsx
  ui/pages/home/home.container.js
  ui/selectors/selectors.js
Labels: team-new-networks

#35196 fix: Fix mapping simulation total value for bridge and swap transaction
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
Labels: team-confirmations, size-S

#35229 ci: fix version extraction regex to handle build numbers
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/scripts/check-template-and-add-labels.ts
Labels: team-qa, no-changelog, size-S

#35216 chore: use central rca form
  .github/workflows/automated-rca.yml
Labels: team-dev-ops, no-changelog, size-XS

#35230 bump: bitcoin v0.19.0
  package.json
  yarn.lock
Labels: team-new-networks, size-XS

#35179 chore: update phishing-warning@5.0.1
  package.json
  yarn.lock
Labels: team-product-safety, size-XS

#35227 chore: chore/13.1.1-Changelog
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, INVALID-PR-TEMPLATE

#35186 refactor: create PreferredAvatar
  ui/components/app/preferred-avatar/index.ts
  ui/components/app/preferred-avatar/preferred-avatar.stories.tsx
  ui/components/app/preferred-avatar/preferred-avatar.tsx
Labels: team-wallet-ux, size-S

#35244 fix: i10n fixes
  app/_locales/de/messages.json
  app/_locales/hi/messages.json
  app/_locales/ht/messages.json
  app/_locales/it/messages.json
  app/_locales/ko/messages.json
Labels: area-translation, team-extension-platform, size-S

#35122 feat: Improve dapp connection UX when the wallet is locked
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.js
  app/scripts/lib/rpc-method-middleware/handlers/request-accounts.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-getPermissions.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-getPermissions.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  test/e2e/json-rpc/eth_accounts.spec.ts
  test/e2e/json-rpc/eth_requestAccounts.spec.ts
  test/e2e/json-rpc/eth_sendTransaction.spec.ts
  test/e2e/json-rpc/wallet_getPermissions.spec.ts
  test/e2e/tests/dapp-interactions/dapp-interactions.spec.ts
Labels: team-wallet-api-platform, size-M

#35271 chore: upgrade @metamask/design-system-react@0.3.1
  package.json
  yarn.lock
Labels: team-design-system, size-XS

#35212 fix: design system react library, lavamoat policy and webpack alias for @radix-ui/react-slot
  development/webpack/webpack.config.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  ui/components/multichain/app-header/__snapshots__/app-header.test.js.snap
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
Labels: team-design-system, no-changelog, size-S

#35054 test: Migration spec Edit gas fee
  test/e2e/page-objects/pages/home/activity-list.ts
  test/e2e/page-objects/pages/send/send-token-confirmation-page.ts
  test/e2e/tests/transaction/edit-gas-fee.spec.js
  test/e2e/tests/transaction/edit-gas-fee.spec.ts
Labels: team-qa, size-L

#35204 fix: Remove use of networkClientId for global network to get next nonce.
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/advanced-details.tsx
  ui/store/actions.ts
Labels: team-confirmations, size-S

#35106 feat: Add send context and page navigation
  ui/pages/confirmations/components/send/amount/amount.tsx
  ui/pages/confirmations/components/send/amount/index.ts
  ui/pages/confirmations/components/send/asset/asset.tsx
  ui/pages/confirmations/components/send/asset/index.ts
  ui/pages/confirmations/components/send/send-to/index.ts
  ui/pages/confirmations/components/send/send-to/send-to.tsx
  ui/pages/confirmations/constants/send.ts
  ui/pages/confirmations/context/send/index.tsx
  ui/pages/confirmations/hooks/send/useNavigateSendPage.test.ts
  ui/pages/confirmations/hooks/send/useNavigateSendPage.ts
  ui/pages/confirmations/send/send-inner.tsx
  ui/pages/confirmations/send/send.tsx
Labels: team-confirmations, size-M

#35278 fix: hide fee info if swap quote does not include a MetaMask fee cp-13.1.1
  ui/pages/bridge/quotes/__snapshots__/multichain-bridge-quote-card.test.tsx.snap
  ui/pages/bridge/quotes/multichain-bridge-quote-card.test.tsx
  ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx
Labels: team-swaps-and-bridge, size-S

#35322 fix: audit failures `cipher-base` and `sha.js` (#35309) cp
  attribution.txt
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/experimental/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  yarn.lock
Labels: team-qa

#35319 fix: update `getInternalAccountByGroupAndCaip` and `getInternalAccountBySelectedAccountGroupAndCaip` selectors
  ui/selectors/multichain-accounts/account-tree.test.ts
  ui/selectors/multichain-accounts/account-tree.ts
  ui/selectors/multichain-accounts/utils.test.ts
  ui/selectors/multichain-accounts/utils.ts
Labels: team-accounts, INVALID-PR-TEMPLATE, no-changelog, size-S

#35284 refactor: Migrate AvatarAccount
  ui/components/app/snaps/snap-ui-renderer/components/__snapshots__/account-selector.test.ts.snap
  ui/components/multichain/account-list-item/__snapshots__/account-list-item.test.js.snap
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/badge-status/__snapshots__/badge-status.test.js.snap
  ui/components/multichain/badge-status/badge-status.tsx
  ui/components/multichain/connect-accounts-modal/__snapshots__/connect-accounts-modal.test.tsx.snap
  ui/components/multichain/notifications-settings-account/notifications-settings-account.test.tsx
  ui/components/multichain/notifications-settings-account/notifications-settings-account.tsx
  ui/components/multichain/pages/connections/__snapshots__/connections.test.tsx.snap
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/your-accounts.test.tsx.snap
  ui/pages/confirmations/confirmation/templates/__snapshots__/remove-snap-account.test.js.snap
  ui/pages/permissions-connect/connect-page/__snapshots__/connect-page.test.tsx.snap
  ui/pages/settings/contact-list-tab/edit-contact/edit-contact.component.js
  ui/pages/settings/contact-list-tab/view-contact/view-contact.component.js
Labels: team-wallet-ux, size-M

#35317 chore: remove dead code - currency formatting
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.d.ts
  ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js
  ui/components/ui/currency-display/currency-display.component.d.ts
  ui/components/ui/currency-display/currency-display.component.js
  ui/hooks/useUserPreferencedCurrency.js
Labels: team-wallet-ux, size-S

#35338 chore: removing portfolio url from privacy snapshot
  privacy-snapshot.json
Labels: team-design-system, no-changelog, size-XS

#35351 chore: chore/13.1.1-Changelog
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery

#35115 feat: pass asset over to send page in url parameters
  ui/components/app/assets/nfts/nft-details/nft-details.test.js
  ui/components/app/assets/nfts/nft-details/nft-details.tsx
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-nft-tab.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/confirmations/constants/send.ts
  ui/pages/confirmations/context/send/index.tsx
  ui/pages/confirmations/hooks/send/useNavigateSendPage.test.ts
  ui/pages/confirmations/hooks/send/useNavigateSendPage.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.test.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.ts
  ui/pages/confirmations/send/send-inner.test.tsx
  ui/pages/confirmations/send/send-inner.tsx
  ui/pages/confirmations/types/send.ts
  ui/pages/routes/routes.component.tsx
Labels: team-confirmations, size-M

#35357 release: Master sync v13.1.1 into main
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, size-XS

#35188 feat: Action to handle submit for EVM send
  app/scripts/metamask-controller.js
  test/data/send/assets.ts
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/confirmations/components/send/amount/amount.test.tsx
  ui/pages/confirmations/components/send/amount/amount.tsx
  ui/pages/confirmations/components/send/send-to/send-to.test.tsx
  ui/pages/confirmations/components/send/send-to/send-to.tsx
  ui/pages/confirmations/hooks/send/useSendActions.test.ts
  ui/pages/confirmations/hooks/send/useSendActions.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.test.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.ts
  ui/pages/confirmations/hooks/send/useSendType.test.ts
  ui/pages/confirmations/hooks/send/useSendType.ts
  ui/pages/confirmations/types/send.ts
  ui/pages/confirmations/utils/send.test.ts
  ui/pages/confirmations/utils/send.ts
  ui/store/actions.ts
Labels: team-confirmations, size-L

#35359 fix: cp-13.1.2 close solana websockets on inactive
  package.json
  yarn.lock
Labels: team-new-networks, size-XS

#23738 refactor: Typescript conversion of send-metadata.js
  app/scripts/lib/rpc-method-middleware/handlers/send-metadata.js
  app/scripts/lib/rpc-method-middleware/handlers/send-metadata.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/send-metadata.ts
Labels: team-extension-platform, in-progress, size-M

#23776 refactor: Typescript conversion of watch-asset.js
  app/scripts/lib/rpc-method-middleware/handlers/watch-asset.js
  app/scripts/lib/rpc-method-middleware/handlers/watch-asset.ts
Labels: team-extension-platform, size-M

#35400 chore: chore/13.1.2-Changelog
  CHANGELOG.md
Labels: extension-delivery

#34098 chore: replace deprecated button components
  ui/components/app/alerts/invalid-custom-network-alert/invalid-custom-network-alert.js
  ui/components/app/alerts/unconnected-account-alert/unconnected-account-alert.js
  ui/components/app/alerts/unconnected-account-alert/unconnected-account-alert.scss
  ui/components/app/cancel-button/cancel-button.js
  ui/components/app/detected-token/detected-token-selection-popover/detected-token-selection-popover.js
  ui/components/app/flask/experimental-area/experimental-area.js
  ui/components/app/home-notification/home-notification.component.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/settings-tab/index.scss
Labels: team-design-system, INVALID-PR-TEMPLATE, size-M

#35285 refactor: Migrate AvatarAccount
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/name/name-details/name-display.tsx
  ui/components/app/preferred-avatar/preferred-avatar.tsx
  ui/components/multichain-accounts/account-remove-modal/account-remove-modal.tsx
  ui/components/multichain/account-picker/__snapshots__/account-picker.test.js.snap
  ui/components/multichain/account-picker/account-picker.js
  ui/components/multichain/address-list-item/__snapshots__/address-list-item.test.tsx.snap
  ui/components/multichain/address-list-item/address-list-item.tsx
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/__snapshots__/account-picker.test.tsx.snap
Labels: team-wallet-ux, size-M

#35321 feat: add flag to enable metamask shield feature
  .metamaskrc.dist
  builds.yml
  development/build/set-environment-variables.js
  shared/modules/environment.ts
  test/env.js
Labels: team-web3auth, size-S

#35419 release: Master sync v13.1.2 into main
  CHANGELOG.md
Labels: team-extension-platform, extension-delivery, size-XS

#35346 feat: Adding amount fiat conversion and validation functions
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/confirmations/components/send/amount/amount.test.tsx
  ui/pages/confirmations/components/send/amount/amount.tsx
  ui/pages/confirmations/hooks/send/evm/useEvmAmountValidation.test.ts
  ui/pages/confirmations/hooks/send/evm/useEvmAmountValidation.ts
  ui/pages/confirmations/hooks/send/non-evm/useNonEvmAmountValidation.test.ts
  ui/pages/confirmations/hooks/send/non-evm/useNonEvmAmountValidation.ts
  ui/pages/confirmations/hooks/send/useAmountValidation.test.ts
  ui/pages/confirmations/hooks/send/useAmountValidation.ts
  ui/pages/confirmations/hooks/send/useBalance.ts
  ui/pages/confirmations/hooks/send/useCurrencyConversions.test.ts
  ui/pages/confirmations/hooks/send/useCurrencyConversions.ts
  ui/pages/confirmations/hooks/send/useSendActions.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.test.ts
  ui/pages/confirmations/hooks/send/useSendQueryParams.ts
  ui/pages/confirmations/types/send.ts
  ui/pages/confirmations/utils/multichain-snaps.ts
  ui/pages/confirmations/utils/send.test.ts
  ui/pages/confirmations/utils/send.ts
Labels: team-confirmations, size-L

#35420 Sync v13.2.0 with master
  CHANGELOG.md
  attribution.txt
  package.json
  yarn.lock
Labels: team-extension-platform, extension-delivery

#35009 refactor(5558): migrate notification system to react-router-v5-compat
  ui/hooks/snaps/useSnapNavigation.ts
  ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/transaction-account-details.stories.tsx
  ui/pages/multichain-accounts/address-qr-code/address-qr-code.stories.tsx
  ui/pages/multichain-accounts/base-account-details/base-account-details.stories.tsx
  ui/pages/multichain-accounts/wallet-details/wallet-details.component.stories.tsx
  ui/pages/notification-details/notification-details.tsx
  ui/pages/notifications-settings/notifications-settings.tsx
  ui/pages/notifications/notification-components/snap/snap-footer-button.test.tsx
  ui/pages/notifications/notification-components/snap/snap-footer-button.tsx
  ui/pages/notifications/notification-components/snap/snap.tsx
  ui/pages/notifications/notifications-list-item.stories.tsx
  ui/pages/notifications/notifications-list-item.tsx
  ui/pages/notifications/notifications-list-read-all-button.test.tsx
  ui/pages/notifications/notifications-list.test.tsx
  ui/pages/notifications/notifications.test.tsx
  ui/pages/notifications/notifications.tsx
  ui/pages/settings/developer-options-tab/developer-options-tab.stories.tsx
Labels: team-extension-platform, size-M

#35414 fix: insufficient number of locale subs in account-exists/not-found pages
  ui/pages/onboarding-flow/account-exist/account-exist.tsx
  ui/pages/onboarding-flow/account-not-found/account-not-found.tsx
Labels: area-onboarding, QA Passed, team-web3auth, seedless-onboarding, size-XS

#35404 bump: bitcoin v1
  package.json
  test/data/mock-accounts.ts
  test/jest/mocks.ts
  ui/components/app/wallet-overview/non-evm-overview.test.tsx
  ui/helpers/utils/permissions.test.ts
  ui/hooks/accounts/useMultichainWalletSnapClient.test.ts
  ui/pages/asset/components/asset-page.tsx
  yarn.lock
Labels: team-new-networks, size-S

#35301 chore: chore/13.2.0-Changelog
  CHANGELOG.md
Labels: extension-delivery

#35382 feat: add end-to-end tests for Trezor ERC20 token creation and management
  test/e2e/tests/hardware-wallets/trezor-erc20.spec.ts
Labels: hardware-trezor, team-accounts, team-hardware-wallets, e2e-test, size-M

#35292 chore: AddWalletModal component initial UI
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain-accounts/add-wallet-modal/add-wallet-modal.stories.tsx
  ui/components/multichain-accounts/add-wallet-modal/add-wallet-modal.test.tsx
  ui/components/multichain-accounts/add-wallet-modal/add-wallet-modal.tsx
  ui/components/multichain-accounts/add-wallet-modal/index.ts
Labels: team-design-system, no-changelog, size-M

#35276 chore: adding storybook story for asset list control bar component
  ui/components/app/assets/asset-list/asset-list-control-bar/asset-list-control-bar.stories.tsx
Labels: team-design-system, no-changelog, size-S

#35408 feat: add Trezor personal sign e2e test
  test/e2e/tests/hardware-wallets/trezor-sign.spec.ts
  test/e2e/tests/hardware-wallets/trezor/trezor-account.spec.ts
  test/e2e/tests/hardware-wallets/trezor/trezor-send.spec.ts
  test/e2e/tests/hardware-wallets/trezor/trezor-sign.spec.ts
  test/stub/keyring-bridge.js
Labels: team-accounts, INVALID-PR-TEMPLATE, team-hardware-wallets, size-M

#35464 fix: stable sync secret
  .github/workflows/stable-branch-sync.yml
Labels: team-dev-ops, size-XS

#35371 feat(INFRA-2864): rca needed label removal
  .github/workflows/remove-rca-needed-label-sheets.yml
Labels: team-dev-ops, skip-e2e-quality-gate, size-S

#35476 fix(INFRA-2864): add permissions to rca needed label removal workflow
  .github/workflows/remove-rca-needed-label-sheets.yml
Labels: team-dev-ops, skip-e2e-quality-gate

#35425 test: add Solana WebSocket specs to validate correct start and termination of connection
  test/e2e/helpers.js
  test/e2e/mock-e2e.js
  test/e2e/tests/solana/common-solana.ts
  test/e2e/tests/solana/web-socket-connection.spec.ts
  test/e2e/websocket-server.ts
  test/e2e/websocket-solana-mocks.ts
Labels: team-qa, no-changelog, size-L

#35413 feat: update SeedlessOnboarding controller to v3
  package.json
  yarn.lock
Labels: client-controller-update, team-web3auth, seedless-onboarding, size-XS

#35455 fix: skip automatic gas updates for swap and bridge transactions cp-13.2.0
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
Labels: team-swaps-and-bridge, size-S

#35438 chore: Disable React & Redux Devtools by default
  README.md
  app/scripts/ui.js
  builds.yml
  development/build/scripts.js
  development/webpack/test/webpack.config.test.ts
  development/webpack/webpack.config.ts
  package.json
  ui/store/store.ts
  yarn.lock
Labels: team-wallet-framework, size-S

#35461 feat: Implementing send metrics context and hooks
  shared/constants/metametrics.ts
  ui/pages/confirmations/components/send/recipient/recipient.tsx
  ui/pages/confirmations/context/send-metrics/index.tsx
  ui/pages/confirmations/hooks/send/metrics/useAmountSelectionMetrics.test.tsx
  ui/pages/confirmations/hooks/send/metrics/useAmountSelectionMetrics.ts
  ui/pages/confirmations/hooks/send/metrics/useAssetSelectionMetrics.test.tsx
  ui/pages/confirmations/hooks/send/metrics/useAssetSelectionMetrics.ts
  ui/pages/confirmations/hooks/send/metrics/useRecipientSelectionMetrics.test.tsx
  ui/pages/confirmations/hooks/send/metrics/useRecipientSelectionMetrics.ts
  ui/pages/confirmations/hooks/send/useAmountValidation.test.ts
  ui/pages/confirmations/send/send.tsx
Labels: team-confirmations, size-L

#35503 feat: capture amount metrics events
  ui/pages/confirmations/components/send/amount-recipient/amount-recipient.test.tsx
  ui/pages/confirmations/components/send/amount-recipient/amount-recipient.tsx
  ui/pages/confirmations/components/send/amount/amount.test.tsx
  ui/pages/confirmations/components/send/amount/amount.tsx
  ui/pages/confirmations/context/send-metrics/index.tsx
  ui/pages/confirmations/hooks/send/metrics/useAmountSelectionMetrics.ts
Labels: team-confirmations, size-M

#35339 feat(pr template): make changelog entry mandatory
  .github/scripts/check-template-and-add-labels.ts
  .github/workflows/check-template-and-add-labels.yml
Labels: team-extension-platform, size-S

#35505 feat: adding utility method for routing to send page
  ui/components/app/assets/nfts/nft-details/nft-details.tsx
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-nft-tab.tsx
  ui/pages/asset/components/token-buttons.tsx
  ui/pages/confirmations/components/confirm/header/wallet-initiated-header.tsx
  ui/pages/confirmations/utils/send.test.ts
  ui/pages/confirmations/utils/send.ts
Labels: team-confirmations, size-M

#35510 feat: Adding designs for amount input
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  test/data/send/assets.ts
  ui/pages/confirmations/components/send/amount-recipient/amount-recipient.test.tsx
  ui/pages/confirmations/components/send/amount-recipient/amount-recipient.tsx
  ui/pages/confirmations/components/send/amount/amount.test.tsx
  ui/pages/confirmations/components/send/amount/amount.tsx
  ui/pages/confirmations/components/send/index.scss
  ui/pages/confirmations/components/send/recipient/recipient.tsx
  ui/pages/confirmations/hooks/send/useCurrencyConversions.test.ts
  ui/pages/confirmations/hooks/send/useCurrencyConversions.ts
  ui/pages/confirmations/send/send-inner.test.tsx
  ui/pages/confirmations/utils/send.test.ts
  ui/pages/confirmations/utils/send.ts
Labels: team-confirmations, size-M

#35402 feat: useAccountGroupForPermissions 2
  shared/lib/multichain/scope-utils.test.ts
  shared/lib/multichain/scope-utils.ts
  ui/hooks/useAccountGroupForPermissions.test.ts
  ui/hooks/useAccountGroupsForPermissions.ts
  ui/selectors/multichain-accounts/account-tree.test.ts
  ui/selectors/multichain-accounts/account-tree.ts
  ui/selectors/multichain-accounts/test-utils.ts
Labels: team-accounts, size-XL
