Repository MetaMask/metamask-extension, pull requests merged in 2025-02, with the labels that each got.

#29879 chore: V12.11.0 changelog
  CHANGELOG.md
Labels: extension-delivery, INVALID-PR-TEMPLATE, team-qa, release-12.11.0

#30044 fix: flaky test timeout `Account syncing - User already has balances on multple accounts from inside MetaMask when a user has balances on more accounts than previously synced, it should be handled gracefully`
  test/e2e/tests/identity/account-syncing/sync-with-account-balances.spec.ts
Labels: flaky tests, area-qa, team-qa

#29825 fix: error when pending transaction alert is trigger
  ui/components/app/alert-system/alert-modal/alert-modal.tsx
Labels: team-confirmations

#30046 fix: corrupted tokens state
  .yarn/patches/@metamask-assets-controllers-npm-46.0.1-3c56f3157c.patch
  app/scripts/migrations/142.1.test.ts
  app/scripts/migrations/142.1.ts
  app/scripts/migrations/index.js
  yarn.lock
Labels: team-assets, needs-assets-ux-review

#29896 feat(snaps):Add disabled state for Snap UI interactive components
  ui/components/app/snaps/snap-ui-checkbox/snap-ui-checkbox.tsx
  ui/components/app/snaps/snap-ui-dropdown/snap-ui-dropdown.tsx
  ui/components/app/snaps/snap-ui-file-input/index.scss
  ui/components/app/snaps/snap-ui-file-input/snap-ui-file-input.tsx
  ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx
  ui/components/app/snaps/snap-ui-radio-group/snap-ui-radio-group.tsx
  ui/components/app/snaps/snap-ui-renderer/components/checkbox.ts
  ui/components/app/snaps/snap-ui-renderer/components/dropdown.ts
  ui/components/app/snaps/snap-ui-renderer/components/field.ts
  ui/components/app/snaps/snap-ui-renderer/components/file-input.ts
  ui/components/app/snaps/snap-ui-renderer/components/input.ts
  ui/components/app/snaps/snap-ui-renderer/components/radioGroup.ts
  ui/components/app/snaps/snap-ui-renderer/components/selector.ts
  ui/components/app/snaps/snap-ui-renderer/index.scss
  ui/components/app/snaps/snap-ui-selector/snap-ui-selector.tsx
  ui/components/ui/dropdown/dropdown.js
Labels: team-snaps-platform

#29811 build: track circular dependency in the codebase
  .github/CODEOWNERS
  .github/workflows/main.yml
  .github/workflows/test-circular-deps.yml
  .madgerc
  development/circular-deps.jsonc
  development/circular-deps.ts
  development/ts-migration-dashboard/common/build-module-partitions.ts
  development/ts-migration-dashboard/scripts/write-list-of-files-to-convert.ts
  lavamoat/build-system/policy.json
  package.json
  yarn.lock
Labels: team-extension-platform

#30041 chore: Rename ControllerMessenger to Messenger
  app/scripts/controller-init/confirmations/ppom-controller-init.test.ts
  app/scripts/controller-init/confirmations/transaction-controller-init.test.ts
  app/scripts/controller-init/messengers/ppom-controller-messenger.ts
  app/scripts/controller-init/messengers/transaction-controller-messenger.ts
  app/scripts/controller-init/types.ts
  app/scripts/controller-init/utils.test.ts
  app/scripts/controllers/account-order.ts
  app/scripts/controllers/account-tracker-controller.test.ts
  app/scripts/controllers/account-tracker-controller.ts
  app/scripts/controllers/alert-controller.test.ts
  app/scripts/controllers/alert-controller.ts
  app/scripts/controllers/app-metadata.test.ts
  app/scripts/controllers/app-metadata.ts
  app/scripts/controllers/app-state-controller.test.ts
  app/scripts/controllers/app-state-controller.ts
  app/scripts/controllers/bridge-status/types.ts
  app/scripts/controllers/bridge/types.ts
  app/scripts/controllers/decrypt-message.ts
  app/scripts/controllers/encryption-public-key.ts
  app/scripts/controllers/metametrics-controller.test.ts
  app/scripts/controllers/metametrics-controller.ts
  app/scripts/controllers/metametrics-data-deletion/metametrics-data-deletion.test.ts
  app/scripts/controllers/metametrics-data-deletion/metametrics-data-deletion.ts
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/controllers/network-order.ts
  app/scripts/controllers/onboarding.test.ts
  app/scripts/controllers/onboarding.ts
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/controllers/swaps/swaps.types.ts
  app/scripts/fixtures/generate-wallet-state.js
  app/scripts/lib/AbstractPetnamesBridge.ts
  app/scripts/lib/ComposableObservableStore.js
  app/scripts/lib/ComposableObservableStore.test.js
  app/scripts/lib/SnapsNameProvider.ts
  app/scripts/lib/createEvmMethodsToNonEvmAccountReqFilterMiddleware.ts
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  app/scripts/lib/snap-keyring/metrics.ts
  app/scripts/lib/snap-keyring/snap-keyring.test.ts
  app/scripts/lib/snap-keyring/types.ts
  app/scripts/lib/snap-keyring/utils/isBlockedUrl.test.ts
  app/scripts/lib/transaction/smart-transactions.test.ts
  app/scripts/lib/transaction/smart-transactions.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  shared/constants/mmi-controller.ts
Labels: team-wallet-framework

#29720 fix: remove segmented tab on confirm import modal
  ui/components/multichain/import-tokens-modal/import-tokens-modal.js
Labels: team-notifications

#29323 feat: SOL-80 transaction details
  test/e2e/flask/solana/check-balance.spec.ts
  ui/components/app/multichain-transaction-details-modal/helpers.ts
  ui/components/app/multichain-transaction-details-modal/index.ts
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.stories.tsx
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.test.tsx
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx
  ui/components/app/transaction-list/transaction-list.component.js
Labels: team-sol

#30062 chore: Bump Snaps packages
  app/_locales/en/messages.json
  app/scripts/controllers/permissions/specifications.test.js
  builds.yml
  package.json
  shared/constants/permissions.ts
  shared/constants/snaps/permissions.ts
  ui/components/app/snaps/snap-ui-checkbox/snap-ui-checkbox.tsx
  ui/components/app/snaps/snap-ui-dropdown/snap-ui-dropdown.tsx
  ui/components/app/snaps/snap-ui-file-input/index.scss
  ui/components/app/snaps/snap-ui-file-input/snap-ui-file-input.tsx
  ui/components/app/snaps/snap-ui-input/snap-ui-input.tsx
  ui/components/app/snaps/snap-ui-radio-group/snap-ui-radio-group.tsx
  ui/components/app/snaps/snap-ui-renderer/components/checkbox.ts
  ui/components/app/snaps/snap-ui-renderer/components/dropdown.ts
  ui/components/app/snaps/snap-ui-renderer/components/field.ts
  ui/components/app/snaps/snap-ui-renderer/components/file-input.ts
  ui/components/app/snaps/snap-ui-renderer/components/input.ts
  ui/components/app/snaps/snap-ui-renderer/components/radioGroup.ts
  ui/components/app/snaps/snap-ui-renderer/components/selector.ts
  ui/components/app/snaps/snap-ui-renderer/index.scss
  ui/components/app/snaps/snap-ui-selector/snap-ui-selector.tsx
  ui/components/ui/dropdown/dropdown.js
  ui/helpers/utils/permission.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#30091 fix: use same logic in details page to show IPFS images
  ui/components/app/assets/nfts/nft-grid/nft-grid.tsx
Labels: team-assets

#30092 fix: Updated snap header in review permissions screen
  ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#30097 chore: Bump `@metamask/snaps-controllers` to `^9.19.1` and `@metamask/snaps-sdk` to `^6.17.1`
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#29106 feat: update celo chain logo svg
  app/images/celo.svg
Labels: external-contributor, team-assets

#30094 chore: Use network-specific smart transaction feature flags
  shared/modules/selectors/index.test.ts
  shared/modules/selectors/smart-transactions.ts
  test/jest/mock-store.js
Labels: team-transactions

#30106 chore: Temporarily store MMI policy validation/update
  .github/workflows/update-lavamoat-policies.yml
  .github/workflows/validate-lavamoat-policy-webapp.yml
  lavamoat/browserify/mmi/policy.json
Labels: team-wallet-framework, team-extension-platform

#30111 fix: cp-12.10.4 hotfix network version / unresponsive network inpage provider
  .yarn/patches/@metamask-providers-npm-19.0.0-3d962c6f1a.patch
  app/scripts/metamask-controller.js
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#30114 fix: hotfix network version / unresponsive network inpage …
  .yarn/patches/@metamask-providers-npm-19.0.0-3d962c6f1a.patch
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-wallet-api-platform

#30113 fix: use intl locale for compatibility with Intl.NumberFormat
  test/jest/mock-store.js
  ui/pages/bridge/prepare/bridge-input-group.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/quotes/bridge-quote-card.tsx
  ui/pages/bridge/quotes/bridge-quotes-modal.tsx
Labels: team-bridge

#30117 fix: Fix MMI LavaMoat policy update
  .github/workflows/update-lavamoat-policies.yml
Labels: team-wallet-framework, team-extension-platform

#30118 fix: fix swaps modal render
  ui/pages/swaps/list-with-search/list-with-search.js
Labels: team-assets

#30122 test: Pin ff version
  .circleci/config.yml
  test/e2e/webdriver/firefox.js
Labels: team-qa

#30120 fix: (cherry-pick) use intl locale for compatibility with Intl.NumberFormat (#30113)
  test/jest/mock-store.js
  ui/pages/bridge/prepare/bridge-input-group.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/quotes/bridge-quote-card.tsx
  ui/pages/bridge/quotes/bridge-quotes-modal.tsx
Labels: team-bridge

#30119 cherry-pick: fix swaps modal render
  ui/pages/swaps/list-with-search/list-with-search.js
Labels: team-assets, team-wallet-ux

#30112 test: pin Firefox version temporarily to 134 until artifacts `tar.bz2` are available again (or a fix is provided)
  test/e2e/webdriver/firefox.js
Labels: team-qa

#30126 test: pin Firefox version temporarily to 134 until artifacts `tar.bz2…
  test/e2e/webdriver/firefox.js
Labels: team-qa

#30116 fix: fix snaps permission flow ui
  ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js
  ui/components/app/permission-page-container/permission-page-container.component.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
  ui/helpers/utils/permission.js
Labels: team-wallet-api-platform

#29609 test: [POM] Migrate connections e2e tests to TS and Page Object Model
  test/e2e/page-objects/pages/confirmations/redesign/review-permissions-confirmation.ts
  test/e2e/page-objects/pages/permission/site-permission-page.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/tests/connections/review-permissions-page.spec.js
  test/e2e/tests/connections/review-switch-permission-page.spec.js
  test/e2e/tests/connections/review-switch-permission-page.spec.ts
  test/e2e/tests/connections/revoke-permissions.spec.ts
  test/e2e/tests/content-security-policy/content-security-policy.spec.ts
Labels: team-extension-platform, e2e-test, team-qa

#30132 fix: fix snaps permission flow ui (#30116)
  ui/components/app/permission-page-container/permission-page-container-content/permission-page-container-content.component.js
  ui/components/app/permission-page-container/permission-page-container.component.js
  ui/components/app/permissions-connect-permission-list/permissions-connect-permission-list.js
  ui/helpers/utils/permission.js
Labels: team-wallet-api-platform

#30130 chore: Remove Snaps insight dead code
  ui/components/app/app-components.scss
  ui/components/app/snaps/snap-home-page/snap-home-renderer.js
  ui/components/app/snaps/snap-insight/index.js
  ui/components/app/snaps/snap-insight/index.scss
  ui/components/app/snaps/snap-insight/snap-insight.js
  ui/components/app/snaps/snap-settings-page/snap-settings-renderer.tsx
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/components/ui/tabs/snaps/dropdown-tab/dropdown-tab.js
  ui/components/ui/tabs/snaps/dropdown-tab/dropdown-tab.test.js
  ui/components/ui/tabs/snaps/dropdown-tab/index.js
  ui/components/ui/tabs/snaps/dropdown-tab/index.scss
  ui/components/ui/tabs/tabs.stories.js
  ui/components/ui/ui-components.scss
  ui/pages/confirmations/components/confirm/snaps/snaps-section/snap-insight.tsx
  ui/pages/confirmations/confirmation/confirmation.js
  ui/pages/notifications/notification-components/snap/snap.tsx
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#30133 feat: mmassets-543
  ui/components/ui/currency-display/__snapshots__/currency-display.component.test.js.snap
  ui/components/ui/currency-display/currency-display.component.js
  ui/components/ui/currency-display/currency-display.component.test.js
Labels: team-assets

#30139 fix: default network selection logic in connection flow
  ui/pages/permissions-connect/connect-page/connect-page.tsx
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#30128 fix: cp-12.12.0 30060 lattice account import issue
  .yarn/patches/eth-lattice-keyring-npm-0.12.4-c5fb3fcf54.patch
  package.json
  yarn.lock
Labels: type-bug, release-blocker, QA Passed, team-hardware-wallets, regression-RC-12.12.0

#29871 fix: Ensure has_marketing_consent user trait are correctly set and sent after participateInMetaMetrics is set to true
  app/scripts/controllers/metametrics-controller.ts
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/page-objects/pages/onboarding/onboarding-metrics-page.ts
  test/e2e/page-objects/pages/settings/privacy-settings.ts
  test/e2e/tests/metrics/marketing-cookieid.spec.ts
  test/e2e/tests/metrics/metametrics-persistence.spec.js
  test/e2e/tests/metrics/segment-user-traits.spec.ts
  ui/pages/onboarding-flow/metametrics/__snapshots__/metametrics.test.js.snap
  ui/pages/onboarding-flow/metametrics/metametrics.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/metametrics-toggle/metametrics-toggle.test.tsx
  ui/pages/settings/security-tab/metametrics-toggle/metametrics-toggle.tsx
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.test.js
Labels: team-extension-platform, QA Passed, area-attribution

#30151 test: implement user-storage encrypted data generation for mocks
  test/e2e/helpers/identity/user-storage/generateEncryptedData.ts
  test/e2e/helpers/identity/user-storage/userStorageMockttpController.ts
  test/e2e/tests/identity/account-syncing/helpers.ts
  test/e2e/tests/identity/account-syncing/importing-private-key-account.spec.ts
  test/e2e/tests/identity/account-syncing/mock-data.ts
  test/e2e/tests/identity/account-syncing/mockData.ts
  test/e2e/tests/identity/account-syncing/new-user-sync.spec.ts
  test/e2e/tests/identity/account-syncing/onboarding-with-opt-out.spec.ts
  test/e2e/tests/identity/account-syncing/sync-after-adding-account.spec.ts
  test/e2e/tests/identity/account-syncing/sync-after-modifying-account-name.spec.ts
  test/e2e/tests/identity/account-syncing/sync-after-onboarding.spec.ts
  test/e2e/tests/identity/account-syncing/sync-with-account-balances.spec.ts
  test/e2e/tests/identity/flows.ts
  test/e2e/tests/identity/mocks.ts
Labels: area-qa, team-qa

#30141 feat: Add transaction alert when sending data to EOA
  app/_locales/en/messages.json
  ui/components/app/confirm/info/row/constants.ts
  ui/pages/confirmations/components/confirm/info/token-transfer/transaction-flow-section.tsx
  ui/pages/confirmations/hooks/alerts/transactions/NonContractAddressAlertMessage.tsx
  ui/pages/confirmations/hooks/alerts/transactions/useFirstTimeInteractionAlert.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useFirstTimeInteractionAlert.ts
  ui/pages/confirmations/hooks/alerts/transactions/useNonContractAddressAlerts.test.ts
  ui/pages/confirmations/hooks/alerts/transactions/useNonContractAddressAlerts.ts
  ui/pages/confirmations/hooks/useConfirmationAlerts.ts
Labels: team-confirmations

#30034 refactor: Refactor initialisation of Snaps controllers
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/snaps/cronjob-controller-messenger.test.ts
  app/scripts/controller-init/messengers/snaps/cronjob-controller-messenger.ts
  app/scripts/controller-init/messengers/snaps/execution-service-messenger.test.ts
  app/scripts/controller-init/messengers/snaps/execution-service-messenger.ts
  app/scripts/controller-init/messengers/snaps/index.ts
  app/scripts/controller-init/messengers/snaps/rate-limit-controller-messenger.test.ts
  app/scripts/controller-init/messengers/snaps/rate-limit-controller-messenger.ts
  app/scripts/controller-init/messengers/snaps/snap-controller-messenger.test.ts
  app/scripts/controller-init/messengers/snaps/snap-controller-messenger.ts
  app/scripts/controller-init/messengers/snaps/snap-insights-controller-messenger.test.ts
  app/scripts/controller-init/messengers/snaps/snap-insights-controller-messenger.ts
  app/scripts/controller-init/messengers/snaps/snap-interface-controller-messenger.test.ts
  app/scripts/controller-init/messengers/snaps/snap-interface-controller-messenger.ts
  app/scripts/controller-init/messengers/snaps/snaps-registry-messenger.test.ts
  app/scripts/controller-init/messengers/snaps/snaps-registry-messenger.ts
  app/scripts/controller-init/snaps/cronjob-controller-init.test.ts
  app/scripts/controller-init/snaps/cronjob-controller-init.ts
  app/scripts/controller-init/snaps/execution-service-init.test.ts
  app/scripts/controller-init/snaps/execution-service-init.ts
  app/scripts/controller-init/snaps/index.ts
  app/scripts/controller-init/snaps/rate-limit-controller-init.test.ts
  app/scripts/controller-init/snaps/rate-limit-controller-init.ts
  app/scripts/controller-init/snaps/snap-controller-init.test.ts
  app/scripts/controller-init/snaps/snap-controller-init.ts
  app/scripts/controller-init/snaps/snap-insights-controller-init.test.ts
  app/scripts/controller-init/snaps/snap-insights-controller-init.ts
  app/scripts/controller-init/snaps/snap-interface-controller-init.test.ts
  app/scripts/controller-init/snaps/snap-interface-controller-init.ts
  app/scripts/controller-init/snaps/snaps-registry-init.test.ts
  app/scripts/controller-init/snaps/snaps-registry-init.ts
  app/scripts/controller-init/test/utils.ts
  app/scripts/controller-init/types.ts
  app/scripts/lib/util.test.js
  app/scripts/lib/util.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-snaps-platform

#28980 feat(ramps): Adds a close button to the buy banner
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/app-state-controller.test.ts
  app/scripts/controllers/app-state-controller.ts
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  test/e2e/default-fixture.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  ui/components/multichain/ramps-card/ramps-card.js
  ui/components/multichain/ramps-card/ramps-card.test.tsx
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/routes/routes.component.test.js
Labels: team-ramp

#30021 build(webpack): add `--sentry` status to webpack's `--dry-run` output
  development/webpack/utils/cli.ts
Labels: team-extension-platform

#30080 ci: skip type imports when checking circular dependencies
  .madgerc
  development/circular-deps.jsonc
  development/circular-deps.ts
Labels: team-extension-platform

#30163 fix: fix noisy sentry logs
  app/scripts/migrations/134.1.test.ts
  app/scripts/migrations/134.1.ts
  app/scripts/migrations/index.js
Labels: team-assets, needs-assets-ux-review

#30173 cherry-pick(#30163): fix: fix noisy sentry logs
  app/scripts/migrations/134.1.test.ts
  app/scripts/migrations/134.1.ts
  app/scripts/migrations/index.js
Labels: team-assets

#30181 chore(runway): cherry-pick fix: Ensure has_marketing_consent user tra…
  app/scripts/controllers/metametrics-controller.ts
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/page-objects/pages/onboarding/onboarding-metrics-page.ts
  test/e2e/page-objects/pages/settings/privacy-settings.ts
  test/e2e/tests/metrics/marketing-cookieid.spec.ts
  test/e2e/tests/metrics/metametrics-persistence.spec.js
  test/e2e/tests/metrics/segment-user-traits.spec.ts
  ui/pages/onboarding-flow/metametrics/__snapshots__/metametrics.test.js.snap
  ui/pages/onboarding-flow/metametrics/metametrics.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/metametrics-toggle/metametrics-toggle.test.tsx
  ui/pages/settings/security-tab/metametrics-toggle/metametrics-toggle.tsx
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.test.js
Labels: team-extension-platform

#30124 chore: update selenium
  development/build/index.js
  package.json
  test/e2e/webdriver/firefox.js
  yarn.lock
Labels: team-qa

#30189 fix: fix migration
  app/scripts/migrations/134.1.test.ts
  app/scripts/migrations/134.1.ts
Labels: team-assets

#30194 fix: cp-12.11.0 fix migration script 134.1
  app/scripts/migrations/134.1.test.ts
  app/scripts/migrations/134.1.ts
Labels: team-assets, needs-assets-ux-review

#29949 fix: add funkichain logo
  app/images/funkichain.svg
  shared/constants/network.ts
Labels: team-assets

#30199 Merge master into v12.11.0
  .yarn/patches/@metamask-providers-npm-19.0.0-3d962c6f1a.patch
  CHANGELOG.md
  app/scripts/metamask-controller.js
  attribution.txt
  package.json
  test/jest/mock-store.js
  ui/pages/bridge/prepare/bridge-input-group.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
  ui/pages/bridge/quotes/bridge-quote-card.tsx
  ui/pages/bridge/quotes/bridge-quotes-modal.tsx
  ui/pages/swaps/list-with-search/list-with-search.js
  yarn.lock
Labels: team-extension-platform

#30121 test: Cleanup extension e2e tests code
  test/e2e/page-objects/flows/send-transaction.flow.ts
  test/e2e/page-objects/pages/confirmations/legacy/navigation.ts
  test/e2e/page-objects/pages/dialog/approve-tokens.ts
  test/e2e/page-objects/pages/dialog/transfer-token.ts
  test/e2e/page-objects/pages/send/confirm-tx-page.ts
Labels: team-extension-platform, e2e-test, team-qa

#30059 fix: integrate multichainAssetsController
  app/scripts/constants/sentry-state.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/selectors/assets.ts
Labels: team-assets

#30143 chore: tab component refactor
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal-tabs.tsx
  ui/components/multichain/pages/send/__snapshots__/send.test.js.snap
  ui/components/multichain/pages/send/components/recipient.tsx
  ui/components/ui/tabs/tab/tab.component.js
  ui/components/ui/tabs/tab/tab.component.test.tsx
  ui/components/ui/tabs/tabs.component.js
  ui/components/ui/tabs/tabs.test.tsx
  ui/pages/notifications/notifications.tsx
Labels: team-design-system, INVALID-PR-TEMPLATE

#30192 fix: Ignore empty data field on hex data alert
  ui/pages/confirmations/hooks/alerts/transactions/useNonContractAddressAlerts.ts
Labels: team-confirmations

#30169 fix: show Bridge and Swap page header based on url query param
  ui/components/app/wallet-overview/coin-buttons.tsx
  ui/hooks/bridge/useBridging.ts
  ui/pages/bridge/hooks/useIsMultichainSwap.tsx
  ui/pages/bridge/index.tsx
  ui/pages/bridge/prepare/bridge-input-group.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-bridge, team-swaps

#30214 chore: removing unused css
  test/e2e/tests/transaction/send-eth.spec.js
  ui/css/itcss/components/index.scss
  ui/css/itcss/components/network.scss
  ui/css/itcss/components/newui-sections.scss
  ui/css/itcss/components/send.scss
  ui/pages/onboarding-flow/privacy-settings/index.scss
Labels: team-design-system

#30209 chore: bump controller version
  app/scripts/metamask-controller.js
  lavamoat/browserify/flask/policy.json
  package.json
  yarn.lock
Labels: team-sol

#30197 feat: Add advanced details tooltip
  app/_locales/en/messages.json
  ui/pages/confirmations/components/confirm/header/__snapshots__/advanced-details-button.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/__snapshots__/dapp-initiated-header.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/__snapshots__/header.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/__snapshots__/wallet-initiated-header.test.tsx.snap
  ui/pages/confirmations/components/confirm/header/advanced-details-button.tsx
Labels: team-confirmations

#30205 chore: update accounts deps + some related peer deps
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  ui/store/actions.ts
  yarn.lock
Labels: team-accounts

#30231 fix: `test-e2e-chrome-vault-decryption` spec with correct balance
  test/e2e/vault-decryption-chrome.spec.ts
Labels: area-qa, team-qa

#29969 fix: Clicking on report link does not add external_link_clicked to si…
  test/integration/confirmations/signatures/permit.test.tsx
  test/integration/confirmations/signatures/signature-helpers.ts
  test/integration/confirmations/transactions/contract-interaction.test.tsx
  ui/components/app/alert-system/general-alert/general-alert.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
Labels: team-confirmations, team-qa

#29915 chore: validate page object usage in new spec files on every PR
  .circleci/config.yml
  .circleci/scripts/git-diff-default-branch.ts
  .circleci/scripts/test-run-e2e-timeout-minutes.ts
  .circleci/scripts/validate-locales-only.ts
  .devcontainer/download-builds.ts
  .github/scripts/shared/circle-artifacts.ts
  .github/scripts/validate-e2e-page-object-usage.ts
  .github/workflows/validate-page-object-usage.yml
  package.json
  test/e2e/changedFilesUtil.js
  test/e2e/run-all.js
Labels: team-extension-platform, area-qa, team-qa

#30217 chore: removing more unused css
  .storybook/test-data.js
  ui/css/base-styles.scss
  ui/css/design-system/_colors.scss
  ui/css/index.scss
  ui/css/itcss/tools/index.scss
  ui/css/itcss/tools/utilities.scss
  ui/css/utilities/colors.scss
  ui/helpers/constants/design-system.ts
Labels: team-design-system

#30022 refactor: remove circular dependencies in `ui/components/app/snaps` folder
  development/circular-deps.jsonc
  ui/components/app/snaps/snap-ui-renderer/components/index.ts
  ui/components/app/snaps/snap-ui-renderer/components/types.ts
  ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.js
  ui/components/app/snaps/snap-ui-renderer/utils.ts
Labels: team-extension-platform

#30208 chore: show max network fee tooltip
  app/_locales/en/messages.json
  ui/pages/bridge/quotes/__snapshots__/bridge-quote-card.test.tsx.snap
  ui/pages/bridge/quotes/bridge-quote-card.tsx
Labels: team-bridge, team-swaps

#30218 fix: cp-12.12.0 CAIP-25 Permission Migration when eth_accounts has not been granted
  app/scripts/migrations/139.test.ts
  app/scripts/migrations/139.ts
Labels: team-wallet-api-platform

#30212 feat: Add e2e tests of speeding up and cancelling transactions
  test/e2e/page-objects/pages/home/activity-list.ts
  test/e2e/tests/confirmations/transactions/speed-up-and-cancel-confirmations.spec.ts
Labels: team-confirmations

#30196 fix: Hide network fee fiat conversion on test nets
  test/e2e/tests/transaction/edit-gas-fee.spec.js
  test/e2e/tests/transaction/gas-estimates.spec.js
  test/e2e/tests/transaction/send-edit.spec.js
  test/e2e/tests/transaction/send-eth.spec.js
  ui/pages/confirmations/components/confirm/info/shared/edit-gas-fees-row/edit-gas-fees-row.tsx
  ui/pages/confirmations/components/confirm/info/shared/gas-fees-row/gas-fees-row.tsx
Labels: team-confirmations

#30260 chore: add integration test to check nonce editing is disabled when stx is on
  test/integration/confirmations/transactions/erc20-approve.test.tsx
Labels: team-qa

#29656 feat: Add origin throttling modal
  app/_locales/en/messages.json
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/app-state-controller.test.ts
  app/scripts/controllers/app-state-controller.ts
  app/scripts/lib/createOriginThrottlingMiddleware.test.ts
  app/scripts/lib/createOriginThrottlingMiddleware.ts
  app/scripts/metamask-controller.js
  shared/constants/metametrics.ts
  shared/types/origin-throttling.ts
  test/data/mock-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/ui/origin-pill/origin-pill.tsx
  ui/ducks/metamask/metamask.js
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/footer/origin-throttle-modal.stories.tsx
  ui/pages/confirmations/components/confirm/footer/origin-throttle-modal.test.tsx
  ui/pages/confirmations/components/confirm/footer/origin-throttle-modal.tsx
  ui/pages/confirmations/hooks/useOriginThrottling.test.ts
  ui/pages/confirmations/hooks/useOriginThrottling.ts
  ui/selectors/index.js
  ui/selectors/origin-throttling.ts
  ui/store/actions.ts
Labels: team-confirmations

#30232 feat: Remove tooltip and connection badge from Connection Menu
  builds.yml
  ui/components/multichain/connected-site-menu/__snapshots__/connected-site-menu.test.js.snap
  ui/components/multichain/connected-site-menu/connected-site-menu.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#30037 refactor: remove metametrics circular dependency
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/controller-init/types.ts
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  development/circular-deps.jsonc
  shared/modules/metametrics.test.ts
  shared/modules/metametrics.ts
  shared/types/metametrics.ts
Labels: team-extension-platform

#30236 chore: adding storybook story for snap ui checkbox component
  ui/components/app/snaps/snap-ui-checkbox/snap-ui-checkbox.stories.tsx
Labels: team-design-system

#30237 chore: adding storybook story for snap install warning component
  ui/components/app/snaps/snap-install-warning/snap-install-warning.stories.tsx
Labels: team-design-system

#30265 test: remove unnecessary delays and wait for condition with `waitForUrlContaning`
  test/e2e/tests/bridge/bridge-button-opens-portfolio.spec.ts
  test/e2e/tests/bridge/bridge-button-routing.spec.ts
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/webdriver/driver.js
Labels: flaky tests, area-qa, team-qa

#30257 refactor: remove circular dependencies in `app/scripts/controllers/bridge-status/`
  app/scripts/controllers/bridge-status/bridge-status-controller.ts
  app/scripts/controllers/bridge-status/constants.ts
  app/scripts/controllers/bridge-status/utils.ts
  app/scripts/controllers/bridge-status/validators.ts
  development/circular-deps.jsonc
Labels: team-extension-platform

#29490 refactor: update network punycode warning, isValidASCIIURL, and toPunycodeURL logic
  ui/pages/confirmations/confirmation/templates/add-ethereum-chain.js
  ui/pages/confirmations/utils/confirm.test.ts
  ui/pages/confirmations/utils/confirm.ts
Labels: team-confirmations

#30239 chore: adding storybook story for unconnected account alert component
  ui/components/app/alerts/unconnected-account-alert/unconnected-account-alert.stories.tsx
Labels: team-design-system

#30175 test: snap-bip-32 test scenario migration to pom
  test/e2e/page-objects/pages/dialog/snap-install-warning.ts
  test/e2e/page-objects/pages/dialog/snap-install.ts
  test/e2e/page-objects/pages/test-snaps.ts
  test/e2e/snaps/test-snap-bip-32.spec.js
  test/e2e/snaps/test-snap-bip-32.spec.ts
  test/e2e/snaps/test-snap-bip-44.spec.js
  test/e2e/snaps/test-snap-bip-44.spec.ts
Labels: INVALID-PR-TEMPLATE, area-qa, team-qa

#30193 fix: Avoid nonce flicker when transaction is submitted
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
Labels: QA Passed, team-confirmations

#30262 chore: Refactor the way multichain balances and transactions controllers are being declared in metamask-controller
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/multichain-balances-controller-messenger.test.ts
  app/scripts/controller-init/messengers/multichain-balances-controller-messenger.ts
  app/scripts/controller-init/messengers/multichain-transactions-controller-messenger.test.ts
  app/scripts/controller-init/messengers/multichain-transactions-controller-messenger.ts
  app/scripts/controller-init/multichain/multichain-balances-controller-init.test.ts
  app/scripts/controller-init/multichain/multichain-balances-controller-init.ts
  app/scripts/controller-init/multichain/multichain-transactions-controller-init.test.ts
  app/scripts/controller-init/multichain/multichain-transactions-controller-init.ts
  app/scripts/controller-init/utils.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/errors.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: team-sol

#30210 feat: disable metametrics when disabling basic functionality
  ui/components/app/basic-configuration-modal/basic-configuration-modal.test.tsx
  ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/metametrics-toggle/metametrics-toggle.test.tsx
  ui/pages/settings/security-tab/metametrics-toggle/metametrics-toggle.tsx
  ui/pages/settings/security-tab/security-tab.component.js
Labels: team-identity

#30243 test: E2E test for Notifications Settings Syncing
  privacy-snapshot.json
  test/e2e/page-objects/pages/header-navbar.ts
  test/e2e/page-objects/pages/home/homepage.ts
  test/e2e/page-objects/pages/notifications-list-page.ts
  test/e2e/page-objects/pages/settings/notifications-settings-page.ts
  test/e2e/page-objects/pages/settings/settings-page.ts
  test/e2e/tests/identity/account-syncing/mock-data.ts
  test/e2e/tests/notifications/enable-notifications-with-accounts-sync.spec.ts
  test/e2e/tests/notifications/enable-notifications.spec.ts
  test/e2e/tests/notifications/mocks.ts
  test/integration/notifications&auth/notifications-activation.test.tsx
  test/integration/notifications&auth/notifications-toggle.test.tsx
  ui/components/multichain/notifications-settings-box/notifications-settings-box.test.tsx
  ui/components/multichain/notifications-settings-box/notifications-settings-box.tsx
  ui/pages/notifications-settings/notifications-settings-allow-notifications.test.tsx
  ui/pages/notifications-settings/notifications-settings-allow-notifications.tsx
  ui/pages/notifications-settings/notifications-settings-per-account.tsx
  ui/pages/notifications-settings/notifications-settings-types.tsx
  ui/pages/notifications-settings/notifications-settings.tsx
Labels: team-qa

#30294 fix: Update multichain controllers init
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/multichain-balances-controller-messenger.test.ts
  app/scripts/controller-init/messengers/multichain-transactions-controller-messenger.test.ts
  app/scripts/controller-init/messengers/multichain/index.ts
  app/scripts/controller-init/messengers/multichain/multichain-assets-controller-messenger.test.ts
  app/scripts/controller-init/messengers/multichain/multichain-assets-controller-messenger.ts
  app/scripts/controller-init/messengers/multichain/multichain-balances-controller-messenger.test.ts
  app/scripts/controller-init/messengers/multichain/multichain-balances-controller-messenger.ts
  app/scripts/controller-init/messengers/multichain/multichain-transactions-controller-messenger.test.ts
  app/scripts/controller-init/messengers/multichain/multichain-transactions-controller-messenger.ts
  app/scripts/controller-init/multichain/index.ts
  app/scripts/controller-init/multichain/multichain-assets-controller-init.test.ts
  app/scripts/controller-init/multichain/multichain-assets-controller-init.ts
  app/scripts/controller-init/multichain/multichain-balances-controller-init.test.ts
  app/scripts/controller-init/multichain/multichain-balances-controller-init.ts
  app/scripts/controller-init/multichain/multichain-transactions-controller-init.test.ts
  app/scripts/controller-init/multichain/multichain-transactions-controller-init.ts
  app/scripts/controller-init/utils.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/errors.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
Labels: team-snaps-platform

#30090 test: [POM] Migrate dapp interaction e2e tests to TS and Page Object Model (part1)
  test/e2e/constants.ts
  test/e2e/page-objects/pages/account-list-page.ts
  test/e2e/page-objects/pages/confirmations/redesign/add-network-confirmations.ts
  test/e2e/page-objects/pages/confirmations/redesign/connect-account-confirmation.ts
  test/e2e/page-objects/pages/home/activity-list.ts
  test/e2e/page-objects/pages/mocked-page.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/page-objects/pages/token-overview-page.ts
  test/e2e/tests/dapp-interactions/block-explorer.spec.ts
  test/e2e/tests/dapp-interactions/dapp-interactions.spec.js
  test/e2e/tests/dapp-interactions/dapp-interactions.spec.ts
Labels: team-extension-platform, e2e-test, team-qa

#29967 fix: Lint `en_GB` locale
  app/_locales/en_GB/messages.json
  development/verify-locale-strings.js
Labels: team-wallet-framework, team-extension-platform, needs-dev-review

#30258 chore: adding appear animations to modal dialog and overlay
  ui/components/component-library/modal-content/modal-content.scss
  ui/components/component-library/modal-overlay/modal-overlay.scss
Labels: team-design-system

#30280 build: add linting TS React files
  .eslintrc.js
Labels: team-assets

#30238 refactor: `token-cell`
  development/circular-deps.jsonc
  ui/components/app/assets/asset-list/asset-list.tsx
  ui/components/app/assets/asset-list/native-token/index.ts
  ui/components/app/assets/asset-list/native-token/native-token.tsx
  ui/components/app/assets/hooks/index.ts
  ui/components/app/assets/hooks/useNativeTokenBalance.tsx
  ui/components/app/assets/hooks/useShouldShowFiat.tsx
  ui/components/app/assets/hooks/useSortedFilteredTokens.tsx
  ui/components/app/assets/hooks/useTokenDisplayInfo.tsx
  ui/components/app/assets/token-cell/__snapshots__/token-cell.test.tsx.snap
  ui/components/app/assets/token-cell/cells/index.ts
  ui/components/app/assets/token-cell/cells/token-cell-badge.tsx
  ui/components/app/assets/token-cell/cells/token-cell-percent-change.tsx
  ui/components/app/assets/token-cell/cells/token-cell-primary-display.tsx
  ui/components/app/assets/token-cell/cells/token-cell-secondary-display.tsx
  ui/components/app/assets/token-cell/cells/token-cell-title.tsx
  ui/components/app/assets/token-cell/token-cell.stories.js
  ui/components/app/assets/token-cell/token-cell.test.tsx
  ui/components/app/assets/token-cell/token-cell.tsx
  ui/components/app/assets/token-list/token-list.tsx
  ui/components/app/assets/types.ts
  ui/components/app/assets/util/calculateTokenBalance.ts
  ui/components/app/assets/util/formatWithThreshold.ts
  ui/components/app/assets/util/networkTitleOverrides.ts
  ui/components/app/assets/util/sort.ts
  ui/components/app/wallet-overview/aggregated-percentage-overview-cross-chains.tsx
  ui/components/multichain/token-list-item/stakeable-link.tsx
  ui/components/multichain/token-list-item/token-list-item.tsx
  ui/hooks/useAccountTotalCrossChainFiatBalance.ts
  ui/pages/asset/components/__snapshots__/asset-page.test.tsx.snap
  ui/pages/asset/components/asset-page.tsx
Labels: team-assets

#30310 fix: update fox positioning
  app/build-types/main/fox.json
  ui/components/ui/mascot/mascot.component.js
Labels: team-wallet-ux

#30273 chore: bump `@metamask/api-specs` to `^0.10.15`
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/run-openrpc-api-test-coverage.ts
  yarn.lock
Labels: team-wallet-api-platform

#30250 fix: bump assets-controllers to v49
  .yarn/patches/@metamask-assets-controllers-npm-49.0.0-e9c0266958.patch
  app/scripts/controller-init/multichain/multichain-assets-controller-init.ts
  app/scripts/controller-init/multichain/multichain-balances-controller-init.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/flask/btc/btc-account-overview.spec.ts
  test/e2e/flask/btc/btc-send.spec.ts
  yarn.lock
Labels: team-assets

#30340 fix (cherry-pick): add Runway to CLA Allowlist (#30302)
  .github/workflows/cla.yml
Labels: team-extension-platform

#29708 chore(deps): update `express`
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  yarn.lock
Labels: team-wallet-framework

#29833 fix: Add BNB Smart Chain to Smart Transactions description in settings
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/helpers/constants/settings.js
  ui/pages/settings/advanced-tab/__snapshots__/advanced-tab.component.test.js.snap
  ui/pages/settings/advanced-tab/advanced-tab.component.js
Labels: team-transactions

#29990 fix: fetch quotes when src amount's decimals are greater than token's decimals
  ui/pages/bridge/prepare/bridge-input-group.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.test.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-bridge

#30282 feat: MMS-1872 destination account picker for sol-evm (standalone component and story)
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/pages/bridge/index.scss
  ui/pages/bridge/prepare/components/destination-account-list-item.tsx
  ui/pages/bridge/prepare/components/destination-account-picker.stories.tsx
  ui/pages/bridge/prepare/components/destination-account-picker.tsx
  ui/pages/bridge/prepare/components/destination-selected-account-list-item.tsx
  ui/pages/bridge/prepare/components/index.scss
Labels: team-swaps

#30301 fix(snaps): Add missing controller names to `ControllersToInitialize`
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/multichain/multichain-assets-controller-init.test.ts
  app/scripts/controller-init/multichain/multichain-balances-controller-init.test.ts
  app/scripts/controller-init/multichain/multichain-transactions-controller-init.test.ts
  app/scripts/controller-init/snaps/cronjob-controller-init.test.ts
  app/scripts/controller-init/snaps/execution-service-init.test.ts
  app/scripts/controller-init/snaps/snap-insights-controller-init.test.ts
  app/scripts/controller-init/snaps/snap-interface-controller-init.test.ts
  app/scripts/controller-init/snaps/snaps-registry-init.test.ts
  app/scripts/controller-init/types.ts
  app/scripts/controller-init/utils.ts
Labels: team-snaps-platform

#30307 Jl/caip25 permission refactor/fix factory differ
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  test/e2e/json-rpc/wallet_addEthereumChain.spec.ts
  ui/components/app/permission-page-container/permission-page-container.component.js
Labels: team-wallet-api-platform

#30346 fix(30190): fix flaky tests for user traits
  test/e2e/tests/metrics/segment-user-traits.spec.ts
Labels: team-extension-platform, flaky tests

#30291 feat: integrate multichain assets rates controller to extension UI
  app/scripts/constants/sentry-state.ts
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/multichain/index.ts
  app/scripts/controller-init/messengers/multichain/multichain-assets-rates-controller-messenger.test.ts
  app/scripts/controller-init/messengers/multichain/multichain-assets-rates-controller-messenger.ts
  app/scripts/controller-init/multichain/index.ts
  app/scripts/controller-init/multichain/multichain-rates-assets-controller-init.test.ts
  app/scripts/controller-init/multichain/multichain-rates-assets-controller-init.ts
  app/scripts/controller-init/utils.ts
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/errors.spec.js
  ui/selectors/assets.test.ts
  ui/selectors/assets.ts
Labels: team-assets

#30324 fix: revisit list of currencies
  app/scripts/migrations/144.test.ts
  app/scripts/migrations/144.ts
  app/scripts/migrations/index.js
  shared/constants/price-api-currencies.ts
  ui/helpers/constants/available-conversions.json
Labels: team-assets

#30370 fix: Revert "fix: Avoid nonce flicker when transaction is submitted"
  ui/pages/confirmations/components/confirm/footer/footer.test.tsx
  ui/pages/confirmations/components/confirm/footer/footer.tsx
Labels: INVALID-PR-TEMPLATE, team-confirmations

#30369 chore: adds call to the multichain transactions controller
  app/scripts/metamask-controller.js
  ui/hooks/accounts/useMultichainWalletSnapClient.test.ts
  ui/hooks/accounts/useMultichainWalletSnapClient.ts
  ui/store/actions.ts
Labels: team-sol

#29773 fix: remove supported chains check
  app/scripts/lib/ppom/ppom-middleware.test.ts
  app/scripts/lib/ppom/ppom-middleware.ts
  app/scripts/lib/ppom/ppom-util.test.ts
  app/scripts/lib/ppom/ppom-util.ts
  app/scripts/lib/ppom/security-alerts-api.test.ts
  app/scripts/lib/ppom/security-alerts-api.ts
  app/scripts/lib/transaction/util.test.ts
  app/scripts/lib/transaction/util.ts
  shared/constants/security-provider.ts
  test/data/confirmations/typed_sign.ts
  test/e2e/mock-e2e.js
  test/e2e/tests/confirmations/signatures/signature-helpers.ts
  test/e2e/tests/metrics/signature-approved.spec.js
Labels: team-confirmations

#30289 fix: Perf: Prevent AddressCopyButton rerenders
  ui/components/multichain/address-copy-button/address-copy-button.js
  ui/components/multichain/address-copy-button/index.js
Labels: team-wallet-ux

#30339 feat: bump notification services controller
  package.json
  yarn.lock
Labels: team-assets

#30244 refactor(snap-keyring): refactor Snap keyring implementation
  app/scripts/lib/snap-keyring/snap-keyring.test.ts
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/lib/snap-keyring/snaps.ts
  app/scripts/lib/snap-keyring/types.ts
  app/scripts/metamask-controller.js
Labels: team-accounts

#30290 feat: update `snap_getPreferences`
  app/scripts/metamask-controller.js
Labels: team-snaps-platform

#30342 build: remove some unncessary autofix warnings
  .eslintrc.js
Labels: team-assets

#30270 feat: update slides descriptions
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
Labels: team-wallet-ux

#30355 fix: cp-12.13.0 fix modal scroll bar flash
  ui/components/component-library/modal-content/modal-content.scss
  ui/components/component-library/modal-content/modal-content.stories.tsx
  ui/components/component-library/modal/modal.stories.tsx
Labels: team-design-system

#29936 feat: Bump `@metamask/providers` to `^20.0.0`
  .yarn/patches/@metamask-providers-npm-19.0.0-3d962c6f1a.patch
  app/scripts/controllers/permissions/enums.ts
  app/scripts/metamask-controller.js
  package.json
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  yarn.lock
Labels: team-wallet-api-platform

#29955 feat: GitHub-hosted runners for benchmarks
  .github/workflows/add-release-label.yml
  .github/workflows/build-beta.yml
  .github/workflows/build-storybook.yml
  .github/workflows/check-attributions.yml
  .github/workflows/check-pr-labels.yml
  .github/workflows/check-template-and-add-labels.yml
  .github/workflows/close-bug-report.yml
  .github/workflows/codespaces.yml
  .github/workflows/fitness-functions.yml
  .github/workflows/main.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/run-benchmarks.yml
  .github/workflows/run-tests.yml
  .github/workflows/test-circular-deps.yml
  .github/workflows/test-deps-audit.yml
  .github/workflows/test-deps-depcheck.yml
  .github/workflows/test-lint-changelog.yml
  .github/workflows/test-lint-lockfile.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-storybook.yml
  .github/workflows/test-yarn-dedupe.yml
  .github/workflows/update-attributions.yml
  .github/workflows/update-lavamoat-policies.yml
  .github/workflows/validate-lavamoat-allow-scripts.yml
  .github/workflows/validate-lavamoat-policy-build.yml
  .github/workflows/validate-lavamoat-policy-webapp.yml
  .github/workflows/validate-page-object-usage.yml
  .github/workflows/wait-for-circleci-workflow-status.yml
  test/e2e/webdriver/chrome.js
Labels: team-extension-platform

#29242 docs: add code comments to better describe date formatting util
  ui/helpers/utils/notification.util.ts
  ui/helpers/utils/notification.utils.test.ts
Labels: team-notifications

#30176 feat(action): Improve bug report creation
  .github/scripts/add-release-label-to-pr-and-linked-issues.ts
  .github/scripts/check-template-and-add-labels.ts
  .github/scripts/create-bug-report-issue.ts
  .github/scripts/shared/issue.ts
  .github/scripts/shared/label.ts
  .github/scripts/shared/project.ts
  .github/scripts/shared/repo.ts
  .github/scripts/shared/utils.ts
  .github/workflows/create-bug-report.yml
  package.json
Labels: team-extension-platform

#30322 refactor: `network-list-menu` component
  app/scripts/controller-init/confirmations/transaction-controller-init.test.ts
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/multichain/index.ts
  app/scripts/controller-init/messengers/multichain/multichain-network-controller-messenger.test.ts
  app/scripts/controller-init/messengers/multichain/multichain-network-controller-messenger.ts
  app/scripts/controller-init/messengers/transaction-controller-messenger.ts
  app/scripts/controller-init/multichain/index.ts
  app/scripts/controller-init/multichain/multichain-network-controller-init.test.ts
  app/scripts/controller-init/multichain/multichain-network-controller-init.ts
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/controllers/network-order.ts
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/multichain/networks.ts
  shared/modules/network.utils.test.ts
  shared/modules/network.utils.ts
  test/data/mock-accounts.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/components/multichain/app-header/app-header-locked-content.tsx
  ui/components/multichain/app-header/app-header-unlocked-content.tsx
  ui/components/multichain/app-header/app-header.js
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/components/multichain/network-list-menu/select-rpc-url-modal/select-rpc-url-modal.tsx
  ui/hooks/accounts/useAccountCreationOnNetworkChange.ts
  ui/pages/settings/networks-tab/networks-form/networks-form.tsx
  ui/selectors/index.js
  ui/selectors/multichain/networks.test.ts
  ui/selectors/multichain/networks.ts
  ui/store/actions.ts
  yarn.lock
Labels: team-accounts

#30426 feat: add `@metamask/multichain-network-controller`
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/messengers/multichain/index.ts
  app/scripts/controller-init/messengers/multichain/multichain-network-controller-messenger.test.ts
  app/scripts/controller-init/messengers/multichain/multichain-network-controller-messenger.ts
  app/scripts/controller-init/multichain/index.ts
  app/scripts/controller-init/multichain/multichain-network-controller-init.test.ts
  app/scripts/controller-init/multichain/multichain-network-controller-init.ts
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/data/mock-accounts.ts
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  ui/selectors/multichain/networks.test.ts
  ui/selectors/multichain/networks.ts
  yarn.lock
Labels: team-accounts

#30367 chore: bump `@metamask/keyring-controller` to `^19.1.0`
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.test.js
  package.json
  yarn.lock
Labels: team-wallet-framework

#30430 fix: flaky tests `Test Snap bip-44 can pop up bip-44 snap and get private key result` and others using `clickElementSafe`
  test/e2e/webdriver/driver.js
Labels: flaky tests, area-qa, team-qa

#30396 chore: Bump Snaps dependencies
  app/scripts/controller-init/snaps/cronjob-controller-init.ts
  app/scripts/controller-init/snaps/execution-service-init.ts
  app/scripts/controller-init/snaps/snap-insights-controller-init.ts
  app/scripts/controller-init/snaps/snap-interface-controller-init.ts
  app/scripts/controller-init/snaps/snaps-registry-init.ts
  app/scripts/metamask-controller.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/e2e/snaps/enums.js
  ui/components/app/snaps/snap-ui-renderer/components/box.ts
  ui/hooks/snaps/useDisplayName.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#30427 fix: fix spinner display in NFT tab
  ui/components/app/assets/nfts/nft-grid/nft-grid.tsx
  ui/components/app/assets/nfts/nfts-tab/nfts-tab.tsx
Labels: team-assets, needs-assets-ux-review

#30303 feat: MMS-1868 new quote card and story
  ui/pages/bridge/quotes/multichain-bridge-quote-card.stories.tsx
  ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx
Labels: team-swaps

#30284 chore: set swap input parameters
  app/scripts/controllers/bridge/bridge-controller.ts
  ui/pages/bridge/prepare/components/bridge-asset-picker-button.tsx
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-bridge

#30408 fix: text visibility issues in error page in dark mode
  ui/components/component-library/textarea/textarea.scss
  ui/css/base-styles.scss
  ui/pages/error-page/error-page.component.tsx
Labels: team-design-system

#30437 fix: cp-12.13.0 fixes drag and drop in network list menu modal
  ui/components/multichain/network-list-menu/index.scss
Labels: team-design-system

#30306 refactor: remove circular dependency between `actions.ts` and `swaps.util.ts`
  development/circular-deps.jsonc
  ui/pages/swaps/swaps.util.gas.ts
  ui/pages/swaps/swaps.util.test.js
  ui/pages/swaps/swaps.util.ts
  ui/store/actions.ts
Labels: team-extension-platform

#30435 fix: flaky test `Speed Up and Cancel Transaction Tests Cancel transaction Successfully cancels a pending transaction`
  test/e2e/tests/confirmations/transactions/speed-up-and-cancel-confirmations.spec.ts
Labels: flaky tests, area-qa, team-qa

#30279 refactor: remove circular dependencies in `ui/pages/snap-account-redirect/*`
  development/circular-deps.jsonc
  ui/pages/snap-account-redirect/components/snap-account-redirect-context.tsx
  ui/pages/snap-account-redirect/components/snap-account-redirect-message.tsx
  ui/pages/snap-account-redirect/components/url-display-box.tsx
  ui/pages/snap-account-redirect/snap-account-redirect.tsx
Labels: team-extension-platform

#30446 chore: Remove unnecessary resolutions
  .yarn/patches/@keystonehq-bc-ur-registry-npm-0.5.0-alpha.5-b95c7992a6.patch
  .yarn/patches/@trezor-schema-utils-npm-1.0.2-7dd48689b2.patch
  .yarn/patches/colors-npm-1.4.0-7e2cf12234.patch
  .yarn/patches/fast-json-patch-npm-2.2.1-63b021bb37.patch
  .yarn/patches/lavamoat-core-npm-15.1.1-51fbe39988.patch
  .yarn/patches/request-npm-2.88.2-f4a57c72c4.patch
  .yarn/patches/web3-npm-0.20.7-ee7ef00c57.patch
  package.json
  yarn.lock
Labels: team-wallet-framework

#30464 feat: re-enable account syncing
  app/scripts/metamask-controller.js
Labels: team-identity

#30466 fix: flaky test `Full-size View Setting opens the extension in popup view when opened from a dapp after enabling it in Advanced Settings`
  test/e2e/tests/settings/full-size-view-settings.spec.js
Labels: flaky tests, area-qa, team-qa

#30469 feat(cherry-pick): re-enable account syncing (#30464)
  app/scripts/metamask-controller.js
Labels: team-identity

#30444 refactor: Expose E2E Chrome driver extension ID
  test/e2e/webdriver/chrome.js
Labels: team-wallet-framework, team-extension-platform

#30414 refactor: remove circular dependency in `name-details.tsx`
  development/circular-deps.jsonc
  ui/components/app/confirm/info/row/__snapshots__/address.test.tsx.snap
  ui/components/app/name/__snapshots__/name.test.tsx.snap
  ui/components/app/name/index.scss
  ui/components/app/name/name-details/__snapshots__/name-details.test.tsx.snap
  ui/components/app/name/name-details/formatted-value.tsx
  ui/components/app/name/name-details/name-details.tsx
  ui/components/app/name/name-details/name-display.tsx
  ui/components/app/name/name-details/shortened-name.tsx
  ui/components/app/name/name.stories.tsx
  ui/components/app/name/name.tsx
  ui/pages/confirmations/components/confirm/info/__snapshots__/info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/__snapshots__/approve-static-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/__snapshots__/set-approval-for-all-info.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/revoke-set-approval-for-all-static-simulation/__snapshots__/revoke-set-approval-for-all-static-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/set-approval-for-all-info/set-approval-for-all-static-simulation/__snapshots__/set-approval-for-all-static-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/__snapshots__/typed-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/permit-simulation/__snapshots__/permit-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/value-display/__snapshots__/value-display.test.tsx.snap
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: team-extension-platform

#30455 refactor: remove circular dependencies from `account-picker.tsx`
  development/circular-deps.jsonc
  ui/components/multichain/pages/send/components/account-picker.tsx
Labels: team-extension-platform

#30178 fix(25182): reloading page during SRP creation breaks flow
  test/e2e/page-objects/flows/onboarding.flow.ts
  test/e2e/page-objects/pages/onboarding/secure-wallet-page.ts
  test/e2e/tests/onboarding/onboarding.spec.ts
  ui/pages/onboarding-flow/onboarding-flow.js
Labels: team-wallet-ux

#30457 refactor: remove circular dependencies from `ui/components/*`
  development/circular-deps.jsonc
  ui/components/multichain/pages/send/components/address-book.tsx
  ui/components/multichain/pages/send/components/hex.tsx
  ui/components/multichain/pages/send/components/network-picker.tsx
  ui/components/multichain/pages/send/components/recipient-content.test.tsx
  ui/components/multichain/pages/send/components/recipient-content.tsx
  ui/components/multichain/pages/send/components/recipient-input.tsx
  ui/components/multichain/pages/send/components/recipient.tsx
  ui/components/multichain/pages/send/components/your-accounts.tsx
Labels: team-extension-platform

#30453 refactor: remove circular dependency from `confirm-alert-model.tsx`
  development/circular-deps.jsonc
  ui/components/app/alert-system/confirm-alert-modal/confirm-alert-modal.tsx
Labels: team-extension-platform

#29696 feat(27255): allow local modification for remote feature flags
  .gitignore
  .metamaskrc.dist
  README.md
  app/scripts/lib/setupSentry.js
  builds.yml
  development/build/config.js
  development/build/manifest.js
  development/lib/get-manifest-flag.ts
  development/webpack/test/plugins.ManifestPlugin.test.ts
  development/webpack/test/webpack.config.test.ts
  development/webpack/utils/plugins/ManifestPlugin/helpers.ts
  development/webpack/webpack.config.ts
  shared/lib/manifestFlags.ts
  test/e2e/constants.ts
  test/e2e/page-objects/pages/developer-options-page.ts
  test/e2e/set-manifest-flags.ts
  test/e2e/tests/remote-feature-flag/remote-feature-flag.spec.ts
  ui/helpers/utils/mm-lazy.ts
  ui/pages/settings/developer-options-tab/__snapshots__/developer-options-tab.test.tsx.snap
  ui/pages/settings/developer-options-tab/developer-options-tab.test.tsx
  ui/pages/settings/developer-options-tab/developer-options-tab.tsx
  ui/pages/settings/info-tab/info-tab.component.js
  ui/pages/settings/info-tab/info-tab.stories.js
  ui/pages/settings/info-tab/info-tab.test.tsx
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
  ui/pages/settings/settings.stories.js
  ui/pages/settings/settings.test.js
  ui/selectors/index.js
  ui/selectors/remote-feature-flags.test.ts
  ui/selectors/remote-feature-flags.ts
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-extension-platform

#27246 test: adds Anvil classes + Viem and migrates first specs from Ganache to Anvil
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
  package.json
  test/e2e/helpers.js
  test/e2e/json-rpc/switchEthereumChain.spec.js
  test/e2e/json-rpc/wallet_addEthereumChain.spec.ts
  test/e2e/page-objects/flows/login.flow.ts
  test/e2e/page-objects/pages/home/homepage.ts
  test/e2e/run-openrpc-api-test-coverage.ts
  test/e2e/seeder/anvil-clients.ts
  test/e2e/seeder/anvil-seeder.js
  test/e2e/seeder/anvil.ts
  test/e2e/tests/confirmations/alerts/queued-confirmations.spec.ts
  test/e2e/tests/connections/review-switch-permission-page.spec.ts
  test/e2e/tests/dapp-interactions/dapp-interactions.spec.ts
  test/e2e/tests/network/chain-interactions.spec.js
  test/e2e/tests/network/custom-rpc-history.spec.js
  test/e2e/tests/network/remove-network.spec.ts
  test/e2e/tests/network/switch-custom-network.spec.js
  test/e2e/tests/onboarding/onboarding.spec.ts
  test/e2e/tests/request-queuing/batch-txs-per-dapp-diff-network.spec.js
  test/e2e/tests/request-queuing/batch-txs-per-dapp-extra-tx.spec.js
  test/e2e/tests/request-queuing/batch-txs-per-dapp-same-network.spec.js
  test/e2e/tests/request-queuing/chainid-check.spec.js
  test/e2e/tests/request-queuing/dapp1-send-dapp2-signTypedData.spec.js
  test/e2e/tests/request-queuing/dapp1-subscribe-network-switch.spec.ts
  test/e2e/tests/request-queuing/dapp1-switch-dapp2-eth-request-accounts.spec.js
  test/e2e/tests/request-queuing/dapp1-switch-dapp2-send.spec.js
  test/e2e/tests/request-queuing/multi-dapp-sendTx-revokePermission.spec.js
  test/e2e/tests/request-queuing/multiple-networks-dapps-txs.spec.js
  test/e2e/tests/request-queuing/sendTx-switchChain-sendTx.spec.js
  test/e2e/tests/request-queuing/switch-network.spec.js
  test/e2e/tests/request-queuing/switchChain-sendTx.spec.js
  test/e2e/tests/request-queuing/switchChain-watchAsset.spec.js
  test/e2e/tests/request-queuing/ui.spec.js
  test/e2e/tests/request-queuing/watchAsset-switchChain-watchAsset.spec.js
  test/e2e/tests/transaction/send-eth.spec.js
  test/e2e/tests/transaction/send-hex-address.spec.js
  yarn.lock
Labels: team-extension-platform, area-qa, skip-e2e-quality-gate

#30507 fix: Add transaction simulation supported networks global mock
  shared/constants/transaction.ts
  test/e2e/mock-e2e.js
  test/e2e/tests/simulation-details/simulation-details.spec.ts
Labels: team-wallet-framework, team-extension-platform, team-confirmations

#30498 fix: Fix attribution generation
  development/generate-attributions.sh
  development/generate-attributions/unset-postinstall.js
Labels: team-wallet-framework

#30481 fix: flaky tests `Confirmation Redesign Token Send ERC1155 Wallet initiated...`
  test/e2e/tests/confirmations/helpers.ts
  test/e2e/tests/confirmations/transactions/erc20-token-send-redesign.spec.ts
  test/e2e/tests/confirmations/transactions/nft-token-send-redesign.spec.ts
  test/e2e/tests/tokens/custom-token-send-transfer.spec.ts
Labels: flaky tests, area-qa, team-qa

#30406 feat: make Snap account creation flow async
  app/scripts/lib/snap-keyring/snap-keyring.test.ts
  app/scripts/lib/snap-keyring/snap-keyring.ts
  app/scripts/lib/snap-keyring/snaps.ts
  package.json
  yarn.lock
Labels: team-accounts

#30477 chore(bitcoin): add bitcoin build feature + disable it temporarily
  app/scripts/constants/sentry-state.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/metamask-controller.js
  app/scripts/snaps/preinstalled-snaps.ts
  builds.yml
  shared/constants/bridge.ts
  shared/constants/multichain/accounts.ts
  test/e2e/flask/btc/btc-account-overview.spec.ts
  test/e2e/flask/btc/btc-dapp-connection.spec.ts
  test/e2e/flask/btc/btc-experimental-settings.spec.ts
  test/e2e/flask/btc/btc-send.spec.ts
  test/e2e/flask/btc/create-btc-account.spec.ts
  ui/pages/settings/experimental-tab/experimental-tab.component.tsx
  ui/pages/settings/experimental-tab/experimental-tab.container.ts
  ui/selectors/selectors.js
  ui/store/actions.ts
Labels: team-accounts

#30500 fix: Handle nullish value in `alphanumeric sort`
  ui/components/app/assets/util/sort.test.ts
  ui/components/app/assets/util/sort.ts
Labels: team-assets

#29942 feat: add multi-srp support to the background script
  app/scripts/controllers/mmi-controller.test.ts
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/metamask-controller.actions.test.js
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/browserify/policy-override.json
  package.json
  test/data/mock-send-state.json
  test/data/mock-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/jest/mock-store.js
  ui/store/actions.test.js
  ui/store/actions.ts
  yarn.lock
Labels: team-accounts

#30499 chore: multichain tx package update
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-sol

#30513 fix: Cherry pick 3e51501 (attribution generation fix) to v12.13.0
  development/generate-attributions.sh
  development/generate-attributions/unset-postinstall.js
Labels: team-extension-platform, INVALID-PR-TEMPLATE

#30527 fix (cherry-pick): Add transaction simulation supported networks global mock (#30507)
  shared/constants/transaction.ts
  test/e2e/mock-e2e.js
  test/e2e/tests/simulation-details/simulation-details.spec.ts
Labels: team-extension-platform

#30085 feat(multichain): add block explorer format URLs
  shared/constants/multichain/networks.ts
  shared/lib/multichain/accounts.test.ts
  shared/lib/multichain/accounts.ts
  shared/lib/multichain/networks.test.ts
  shared/lib/multichain/networks.ts
  test/jest/mocks.ts
  ui/components/app/modals/nickname-popovers/nickname-popovers.component.test.tsx
  ui/components/app/multichain-transaction-details-modal/helpers.ts
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.stories.tsx
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.test.tsx
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/app/transaction-list/transaction-list.test.js
  ui/components/multichain/menu-items/view-explorer-menu-item.test.tsx
  ui/components/ui/jazzicon/jazzicon.component.tsx
  ui/helpers/utils/multichain/blockExplorer.ts
  ui/selectors/accounts.ts
Labels: team-accounts
