Repository MetaMask/metamask-extension, pull requests merged in 2025-03, with the labels that each got.

#30591 fix(e2e): test-artifacts/undefined folder
  test/e2e/webdriver/driver.js
Labels: team-extension-platform

#30638 refactor(snaps e2e): Refactor E2E tests to reduce duplication
  test/e2e/page-objects/pages/test-snaps.ts
  test/e2e/snaps/test-snap-bip-32.spec.ts
  test/e2e/snaps/test-snap-bip-44.spec.ts
  test/e2e/snaps/test-snap-homepage.spec.ts
  test/e2e/tests/confirmations/navigation.spec.ts
Labels: team-snaps-platform

#30680 fix: Temporarily disable "Test Snap update via snaps component" E2E test
  test/e2e/snaps/test-snap-update-component.spec.js
Labels: team-snaps-platform

#30676 fix: cherrypick-v12.14.0 bridge page
  ui/hooks/bridge/useLatestBalance.ts
Labels: team-swaps-and-bridge

#30148 ci: further enable circular dep linting
  .madgerc
  development/circular-deps.jsonc
  development/circular-deps.ts
  lavamoat/build-system/policy.json
  package.json
  types/global.d.ts
  yarn.lock
Labels: team-extension-platform

#30486 fix: add error boundary on NFT grid items
  ui/components/app/assets/nfts/nft-grid/__snapshots__/nft-grid.test.tsx.snap
  ui/components/app/assets/nfts/nft-grid/nft-grid-item-error-boundary.test.tsx
  ui/components/app/assets/nfts/nft-grid/nft-grid-item-error-boundary.tsx
  ui/components/app/assets/nfts/nft-grid/nft-grid.test.tsx
  ui/components/app/assets/nfts/nft-grid/nft-grid.tsx
Labels: team-assets

#29979 ci: a new prep-deps workflow with caching
  .github/workflows/add-release-label.yml
  .github/workflows/build-beta.yml
  .github/workflows/build-storybook.yml
  .github/workflows/check-attributions.yml
  .github/workflows/check-pr-labels.yml
  .github/workflows/check-template-and-add-labels.yml
  .github/workflows/close-bug-report.yml
  .github/workflows/create-bug-report.yml
  .github/workflows/crowdin-action.yml
  .github/workflows/fitness-functions.yml
  .github/workflows/main.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/repository-health-checks.yml
  .github/workflows/run-benchmarks.yml
  .github/workflows/run-tests.yml
  .github/workflows/test-deps-audit.yml
  .github/workflows/test-deps-depcheck.yml
  .github/workflows/test-lint-changelog.yml
  .github/workflows/test-lint-lockfile.yml
  .github/workflows/test-lint-shellcheck.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-storybook.yml
  .github/workflows/test-yarn-dedupe.yml
  .github/workflows/update-attributions.yml
  .github/workflows/update-lavamoat-policies.yml
  .github/workflows/validate-lavamoat-allow-scripts.yml
  .github/workflows/validate-lavamoat-policy-build.yml
  .github/workflows/validate-lavamoat-policy-webapp.yml
  .github/workflows/validate-page-object-usage.yml
Labels: team-extension-platform

#30671 fix(30662): balance when non evms accounts
  ui/hooks/bridge/useLatestBalance.ts
Labels: team-swaps-and-bridge

#30515 fix(30509): remove 'fake-metrics-id' in e2e to avoid controller error
  test/e2e/mock-e2e.js
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-metrics.spec.js
  test/e2e/tests/confirmations/alerts/queued-confirmations.spec.ts
  test/e2e/tests/confirmations/helpers.ts
  test/e2e/tests/confirmations/transactions/metrics.spec.ts
  test/e2e/tests/metrics/app-installed.spec.ts
  test/e2e/tests/metrics/delete-metametrics-data.spec.ts
  test/e2e/tests/metrics/errors.spec.js
  test/e2e/tests/metrics/marketing-cookieid.spec.ts
  test/e2e/tests/metrics/nft-detection-metrics.spec.ts
  test/e2e/tests/metrics/signature-approved.spec.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-before-init-opt-in-ui-state.json
  test/e2e/tests/metrics/swaps.spec.js
  test/e2e/tests/metrics/token-detection-metrics.spec.ts
  test/e2e/tests/metrics/transaction-finalized.spec.js
  test/e2e/tests/metrics/unlock-wallet.spec.js
  test/e2e/tests/metrics/wallet-created.spec.ts
  test/e2e/tests/ppom/ppom-blockaid-alert-metrics.spec.js
  test/e2e/tests/ppom/ppom-blockaid-toggle-metrics.spec.js
  test/e2e/tests/survey/survey.spec.js
  test/e2e/tests/tokens/nft/remove-nft.spec.js
Labels: team-extension-platform

#30686 fix: cp-12.14.0 replace 3D beta mascot with 2D version
  ui/helpers/utils/build-types.js
  ui/pages/onboarding-flow/welcome/welcome.js
  ui/pages/swaps/awaiting-swap/awaiting-swap.js
  ui/pages/swaps/loading-swaps-quotes/loading-swaps-quotes.js
  ui/pages/swaps/mascot-background-animation/mascot-background-animation.js
  ui/pages/unlock-page/unlock-page.component.js
Labels: team-wallet-ux

#30614 fix: chain id conversion in metrics event
  ui/components/multichain/network-list-menu/network-list-menu.tsx
Labels: team-accounts

#30746 fix(30662): balance when non evms accounts (#30671)
  ui/hooks/bridge/useLatestBalance.ts
Labels: team-swaps-and-bridge

#30557 feat: mms-1933 token alerts
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  shared/modules/bridge-utils/security-alerts-api.util.test.ts
  shared/modules/bridge-utils/security-alerts-api.util.ts
  shared/types/security-alerts-api.ts
  ui/hooks/bridge/useTokenAlerts.test.ts
  ui/hooks/bridge/useTokenAlerts.ts
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps-and-bridge

#30731 chore: solana snap version update
  package.json
  yarn.lock
Labels: team-sol

#30682 chore: whats new modal for Solana
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/es_419/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/ph/messages.json
  app/_locales/pt/messages.json
  app/_locales/pt_BR/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  app/images/solana-logo-transparent.svg
  shared/notifications/index.ts
  ui/components/app/app-components.scss
  ui/components/app/whats-new-modal/index.ts
  ui/components/app/whats-new-modal/notifications.ts
  ui/components/app/whats-new-modal/solana/index.ts
  ui/components/app/whats-new-modal/solana/modal-body.tsx
  ui/components/app/whats-new-modal/solana/modal-footer.tsx
  ui/components/app/whats-new-modal/solana/modal-header.tsx
  ui/components/app/whats-new-modal/whats-new-modal.stories.tsx
  ui/components/app/whats-new-modal/whats-new-modal.test.tsx
  ui/components/app/whats-new-modal/whats-new-modal.tsx
  ui/components/app/whats-new-popup/index.js
  ui/components/app/whats-new-popup/index.scss
  ui/components/app/whats-new-popup/whats-new-popup.js
  ui/components/app/whats-new-popup/whats-new-popup.stories.js
  ui/components/app/whats-new-popup/whats-new-popup.test.js
  ui/pages/home/home.component.js
  ui/pages/home/home.container.js
  ui/selectors/selectors.js
Labels: team-sol

#30721 fix: snap acount creation view position
  ui/components/multichain/create-named-snap-account/index.scss
Labels: team-sol

#30656 fix: fixes swap transactions showing up as bridge
  ui/hooks/bridge/useSolanaBridgeTransactionMapping.ts
Labels: team-bridge, team-swaps

#30687 fix(30348): profile sync can now be searched in settings
  ui/helpers/constants/settings.js
  ui/helpers/utils/settings-search.test.js
  ui/pages/settings/security-tab/__snapshots__/security-tab.test.js.snap
  ui/pages/settings/security-tab/security-tab.component.js
Labels: team-wallet-ux

#30760 fix: mms-2049 solana slipagge
  app/scripts/controllers/swaps/index.ts
  shared/modules/bridge-utils/bridge.util.ts
  ui/ducks/swaps/swaps.js
Labels: team-swaps-and-bridge

#30751 cherry-pick(#30731): solana snap version update
  package.json
  test/e2e/snaps/test-snap-update-component.spec.js
  yarn.lock
Labels: team-sol

#30677 chore: Bump Snaps packages
  app/scripts/controllers/permissions/specifications.js
  app/scripts/metamask-controller.js
  package.json
  test/e2e/fixture-builder.js
  test/e2e/page-objects/pages/test-snaps.ts
  test/e2e/snaps/enums.js
  test/e2e/snaps/test-snap-bip-32.spec.ts
  test/e2e/snaps/test-snap-bip-44.spec.ts
  test/e2e/snaps/test-snap-get-entropy.spec.ts
  test/e2e/snaps/test-snap-getentropy.spec.js
  test/e2e/snaps/test-snap-homepage.spec.ts
  test/e2e/snaps/test-snap-metrics.spec.js
  test/e2e/snaps/test-snap-update-component.spec.js
  test/e2e/snaps/test-snap-update.spec.js
  test/e2e/tests/confirmations/navigation.spec.ts
  test/e2e/webdriver/driver.js
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#30769 fix: flaky test `Metrics Sends a contract interaction type 2 transaction (EIP1559) with the right properties in the metric events`
  test/e2e/mock-e2e.js
Labels: flaky tests, area-qa, team-qa

#30660 fix: cp-12.14.0 disable click handler on non-evm tokens to not throw warning in …
  ui/components/app/assets/asset-list/asset-list.tsx
Labels: team-assets

#30560 test: fix "deletes a custom RPC" test
  ui/components/multichain/network-list-menu/network-list-menu.tsx
  ui/selectors/multichain/networks.test.ts
  ui/selectors/multichain/networks.ts
Labels: team-accounts

#30581 fix: show aggregated balance in account list item
  ui/components/multichain/account-list-item/account-list-item.js
  ui/hooks/useCurrencyDisplay.js
  ui/hooks/useMultichainAccountTotalFiatBalance.ts
Labels: team-assets, needs-assets-ux-review

#30775 fix(snaps e2e): Fix Snaps E2E on Firefox
  test/e2e/page-objects/pages/test-snaps.ts
Labels: team-snaps-platform

#30756 fix: fixes bridging label showing for solana swap
  ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx
Labels: team-swaps-and-bridge

#30661 style: make Git blame ignore specified large refactor and lint commits
  .git-blame-ignore-revs
  .vscode/settings.json
Labels: team-extension-platform

#30755 fix: fixes swap transactions showing up as bridge (#30656)
  ui/hooks/bridge/useSolanaBridgeTransactionMapping.ts
Labels: team-bridge, team-swaps, team-swaps-and-bridge

#30784 fix: fixes bridging label showing for solana swap (#30756)
  ui/pages/bridge/quotes/multichain-bridge-quote-card.tsx
Labels: team-swaps-and-bridge

#30749 fix: fetch quotes when dest asset is native
  ui/ducks/bridge/bridge.ts
  ui/ducks/bridge/utils.ts
Labels: team-swaps-and-bridge

#30758 fix: use networkClientId if included in transaction
  app/scripts/controllers/bridge/bridge-controller.test.ts
  app/scripts/controllers/bridge/bridge-controller.ts
  app/scripts/metamask-controller.js
  ui/pages/bridge/hooks/useHandleTx.ts
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.test.tsx
  ui/store/actions.ts
Labels: team-swaps-and-bridge

#30724 fix: Fix redux warning in `useOriginThrottling.ts`
  ui/pages/confirmations/hooks/useOriginThrottling.ts
  ui/store/actions.ts
Labels: team-confirmations

#30730 fix: remove assets detection metrics
  app/scripts/metamask-controller.js
  test/e2e/tests/metrics/nft-detection-metrics.spec.ts
  test/e2e/tests/metrics/token-detection-metrics.spec.ts
Labels: team-assets

#30745 feat: Implement editing spending cap in the simulation component
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/e2e/tests/confirmations/transactions/erc20-approve-redesign.spec.ts
  test/integration/confirmations/transactions/erc20-approve.test.tsx
  test/integration/confirmations/transactions/increase-allowance.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/__snapshots__/approve.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/__snapshots__/approve-static-simulation.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/approve-static-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve-static-simulation/approve-static-simulation.tsx
  ui/pages/confirmations/components/confirm/info/approve/approve.tsx
  ui/pages/confirmations/components/confirm/info/approve/spending-cap/__snapshots__/spending-cap.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/spending-cap/spending-cap.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/spending-cap/spending-cap.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
Labels: team-confirmations

#30808 test: fix `Send flow with some field validation`
  test/e2e/flask/solana/common-solana.ts
Labels: flaky tests, team-qa

#30835 chore: recreate policies
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  lavamoat/build-system/policy.json
Labels: team-wallet-framework

#30850 chore: fix trezor audit
  .yarnrc.yml
Labels: team-qa

#30728 test: remove `defaultGanacheOptions`
  test/e2e/helpers.js
  test/e2e/json-rpc/eth_newBlockFilter.spec.ts
  test/e2e/json-rpc/wallet_addEthereumChain.spec.ts
  test/e2e/tests/confirmations/helpers.ts
  test/e2e/tests/metrics/metametrics-persistence.spec.js
  test/e2e/tests/multichain/asset-picker-send.spec.ts
  test/e2e/tests/request-queuing/sendTx-revokePermissions.spec.ts
  test/e2e/tests/tokens/add-token-using-search.spec.ts
  test/e2e/tests/tokens/token-details.spec.ts
  test/e2e/tests/tokens/token-list.spec.ts
  test/e2e/tests/tokens/token-sort.spec.ts
Labels: area-qa, team-qa, skip-e2e-quality-gate

#30805 feat: migrate profile sync controllers to the controller init pattern
  app/scripts/controller-init/controller-list.ts
  app/scripts/controller-init/identity/authentication-controller-init.test.ts
  app/scripts/controller-init/identity/authentication-controller-init.ts
  app/scripts/controller-init/identity/user-storage-controller-init.test.ts
  app/scripts/controller-init/identity/user-storage-controller-init.ts
  app/scripts/controller-init/messengers/identity/authentication-controller-messenger.test.ts
  app/scripts/controller-init/messengers/identity/authentication-controller-messenger.ts
  app/scripts/controller-init/messengers/identity/index.ts
  app/scripts/controller-init/messengers/identity/user-storage-controller-messenger.test.ts
  app/scripts/controller-init/messengers/identity/user-storage-controller-messenger.ts
  app/scripts/controller-init/messengers/index.ts
  app/scripts/controller-init/test/utils.ts
  app/scripts/controller-init/types.ts
  app/scripts/controller-init/utils.ts
  app/scripts/metamask-controller.js
Labels: team-identity

#30716 chore: bump ethereumjs
  app/scripts/controller-init/confirmations/transaction-controller-init.test.ts
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/controller-init/messengers/transaction-controller-messenger.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  test/stub/keyring-bridge.js
  test/stub/keyring-utils.js
  yarn.lock
Labels: team-confirmations

#30634 fix: Display alerts on add network request if there are pending confirmations
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/lib/approval/utils.test.ts
  app/scripts/lib/approval/utils.ts
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.test.ts
  app/scripts/metamask-controller.js
  builds.yml
  test/data/confirmations/helper.ts
  ui/components/app/alert-system/multiple-alert-modal/multiple-alert-modal.test.tsx
  ui/components/app/alert-system/multiple-alert-modal/multiple-alert-modal.tsx
  ui/components/app/confirm/info/row/constants.ts
  ui/pages/confirmations/confirmation/alerts/TemplateAlertContext.tsx
  ui/pages/confirmations/confirmation/alerts/useAddEthereumChainAlerts.test.ts
  ui/pages/confirmations/confirmation/alerts/useAddEthereumChainAlerts.ts
  ui/pages/confirmations/confirmation/alerts/useAlertActions.test.ts
  ui/pages/confirmations/confirmation/alerts/useAlertsActions.tsx
  ui/pages/confirmations/confirmation/alerts/useTemplateConfirmationAlerts.test.ts
  ui/pages/confirmations/confirmation/alerts/useTemplateConfirmationAlerts.ts
  ui/pages/confirmations/confirmation/confirmation.js
  ui/selectors/selectors.js
Labels: team-confirmations

#30793 fix: Bridge and Send pages crash when there's no solana account
  ui/hooks/useMultichainBalances.ts
Labels: team-swaps-and-bridge

#30860 chore: cp-12.14.0 fix trezor audit (#30850)
  .yarnrc.yml
Labels: team-extension-platform

#30857 feat: update solana version
  package.json
  yarn.lock
Labels: team-sol

#30804 test: add send DAI spec using Anvil state
  test/e2e/seeder/network-states/with50Dai.json
  test/e2e/tests/tokens/send-erc20-with-loaded-state.spec.ts
Labels: area-qa, team-qa

#30855 chore: Update `CODEOWNERS` file for template renderer
  .github/CODEOWNERS
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#30866 cherry-pick: Solana RC
  package.json
  test/data/mock-accounts.ts
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.test.tsx
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/app/transaction-list/transaction-list.test.js
  yarn.lock
Labels: team-sol

#30854 test: remove `generateGanacheOptions`
  test/e2e/helpers.js
  test/e2e/json-rpc/eth_sendTransaction.spec.js
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/metrics/swaps.spec.js
  test/e2e/tests/swap-send/swap-send-test-utils.ts
  test/e2e/tests/transaction/edit-gas-fee.spec.js
  test/e2e/tests/transaction/gas-estimates.spec.js
  test/e2e/tests/transaction/multiple-transactions.spec.js
  test/e2e/tests/transaction/navigate-transactions.spec.js
  test/e2e/tests/transaction/send-edit.spec.js
  test/e2e/tests/transaction/send-max.spec.js
  test/e2e/tests/transaction/stuck-approved-transaction.spec.ts
Labels: area-qa, team-qa, skip-e2e-quality-gate

#30813 cherry-pick c9d7dd1 (#30614) in v12.14.0
  ui/components/multichain/network-list-menu/network-list-menu.tsx
Labels: team-accounts

#30845 fix: mms-2025 text ellipsis
  ui/components/multichain/activity-list-item/__snapshots__/activity-list-item.test.js.snap
  ui/components/multichain/activity-list-item/activity-list-item.js
Labels: team-swaps-and-bridge

#30288 fix: Perf: Prevent MultipleNotifications rerenders
  ui/pages/home/home.component.js
Labels: team-wallet-ux

#30871 feat: Add MegaETH Testnet as a default test network
  app/images/MegaETH-logo-testnet.svg
  app/scripts/metamask-controller.js
  shared/constants/network.ts
Labels: team-network-enablement

#30286 fix: Perf: Prevent MultichainMetaFoxLogo from multiple renders
  ui/components/multichain/app-header/multichain-meta-fox-logo.js
Labels: team-wallet-ux

#30848 fix: formatChainIdToHex fails to parse evm caip chainIds
  shared/modules/bridge-utils/caip-formatters.ts
Labels: team-swaps-and-bridge

#30874 fix: Prevent BadgeStatus' tooltip from rerendering
  ui/components/multichain/badge-status/badge-status.tsx
Labels: team-wallet-ux

#30658 fix: Prevent SrpViewSrpText from firing more than once
  ui/pages/keychains/reveal-seed.js
Labels: team-wallet-ux

#30883 chore: Update MegaETH logo
  app/images/MegaETH-logo-testnet.png
  app/images/MegaETH-logo-testnet.svg
  shared/constants/network.ts
Labels: release-12.15.0, team-network-enablement

#30863 chore(cherr-pick): a new prep-deps workflow with caching (#29979)
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/dependabot.yml
  .github/guidelines/CODING_GUIDELINES.md
  .github/guidelines/LABELING_GUIDELINES.md
  .github/pull-request-template.md
  .github/scripts/add-release-label-to-pr-and-linked-issues.ts
  .github/scripts/check-template-and-add-labels.ts
  .github/scripts/create-bug-report-issue.ts
  .github/scripts/shared/issue.ts
  .github/scripts/shared/label.ts
  .github/scripts/shared/project.ts
  .github/scripts/shared/repo.ts
  .github/scripts/shared/utils.ts
  .github/workflows/add-release-label.yml
  .github/workflows/build-beta.yml
  .github/workflows/build-storybook.yml
  .github/workflows/check-attributions.yml
  .github/workflows/check-pr-labels.yml
  .github/workflows/check-template-and-add-labels.yml
  .github/workflows/cla.yml
  .github/workflows/close-bug-report.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-bug-report.yml
  .github/workflows/create-cherry-pick-pr.yml
  .github/workflows/create-release-pr.yml
  .github/workflows/crowdin-action.yml
  .github/workflows/fitness-functions.yml
  .github/workflows/main.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/remove-labels-after-pr-closed.yml
  .github/workflows/repository-health-checks.yml
  .github/workflows/run-benchmarks.yml
  .github/workflows/run-tests.yml
  .github/workflows/security-code-scanner.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/test-lint-shellcheck.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-storybook.yml
  .github/workflows/update-attributions.yml
  .github/workflows/update-lavamoat-policies.yml
  .github/workflows/validate-conventional-commits.yml
  .github/workflows/validate-lavamoat-policy-build.yml
  .github/workflows/validate-lavamoat-policy-webapp.yml
  .github/workflows/validate-page-object-usage.yml
  .github/workflows/wait-for-circleci-workflow-status.yml
  .yarnrc.yml
  test/e2e/snaps/test-snap-uilinks.spec.js
  test/e2e/snaps/test-snap-update-component.spec.js
Labels: team-extension-platform

#30846 fix: cp-12.14.0 duplicate dest assets visible in bridge page
  shared/types/bridge.ts
  ui/ducks/bridge/bridge.test.ts
  ui/ducks/bridge/bridge.ts
  ui/ducks/bridge/selectors.ts
  ui/hooks/bridge/useTokensWithFiltering.ts
Labels: team-swaps-and-bridge

#30908 refactor: `wallet_createSession` should call `PermissionController.requestPermissions` instead of `ApprovalController.addAndShowApprovalRequest`
  app/scripts/lib/rpc-method-middleware/handlers/types.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-requestPermissions.ts
  app/scripts/metamask-controller.js
Labels: team-wallet-api-platform

#30878 fix: cp-12.14.0 set automatic slippage for swap transactions
  shared/modules/bridge-utils/bridge.util.ts
  shared/modules/bridge-utils/quote.ts
  ui/ducks/bridge/bridge.ts
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-swaps, team-swaps-and-bridge

#27782 feat: Add Multichain API to Flask
  .circleci/config.yml
  .depcheckrc.yml
  .gitignore
  app/build-types/flask/manifest/_base.json
  app/manifest/v2/_barad_dur.json
  app/manifest/v3/_barad_dur.json
  app/scripts/background.js
  app/scripts/controllers/permissions/differs.test.ts
  app/scripts/controllers/permissions/differs.ts
  app/scripts/controllers/permissions/enums.ts
  app/scripts/controllers/permissions/index.js
  app/scripts/controllers/permissions/selectors.js
  app/scripts/controllers/permissions/selectors.test.js
  app/scripts/lib/rpc-method-middleware/createMethodMiddleware.js
  app/scripts/lib/rpc-method-middleware/createMethodMiddleware.test.js
  app/scripts/lib/rpc-method-middleware/createUnsupportedMethodMiddleware.test.ts
  app/scripts/lib/rpc-method-middleware/createUnsupportedMethodMiddleware.ts
  app/scripts/lib/rpc-method-middleware/handlers/types.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/handler.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-createSession/index.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-requestPermissions.ts
  app/scripts/metamask-controller.js
  app/scripts/metamask-controller.test.js
  builds.yml
  development/build/manifest.js
  development/create-static-server.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  shared/constants/app.ts
  shared/modules/caip-stream.test.ts
  shared/modules/caip-stream.ts
  test/e2e/api-specs/ConfirmationRejectionRule.ts
  test/e2e/api-specs/MultichainAuthorizationConfirmation.ts
  test/e2e/api-specs/MultichainAuthorizationConfirmationErrors.ts
  test/e2e/api-specs/helpers.ts
  test/e2e/api-specs/transform.ts
  test/e2e/fixture-builder.js
  test/e2e/flask/multichain-api/testHelpers.ts
  test/e2e/flask/multichain-api/wallet_createSession.spec.ts
  test/e2e/flask/multichain-api/wallet_getSession.spec.ts
  test/e2e/flask/multichain-api/wallet_invokeMethod.spec.ts
  test/e2e/flask/multichain-api/wallet_notify.spec.ts
  test/e2e/flask/multichain-api/wallet_revokeSession.spec.ts
  test/e2e/flask/multichain-api/wallet_sessionChanged.spec.ts
  test/e2e/helpers.js
  test/e2e/page-objects/pages/test-dapp-multichain.ts
  test/e2e/run-api-specs-multichain.ts
  test/e2e/run-openrpc-api-test-coverage.ts
  yarn.lock
Labels: team-wallet-framework, team-wallet-api-platform, INVALID-PR-TEMPLATE

#30909 test: Use test-dapp for transaction insights E2E
  test/e2e/snaps/test-snap-txinsights.spec.js
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#30872 chore: Optimize performance of Assets hooks
  ui/hooks/useAccountTotalCrossChainFiatBalance.ts
  ui/hooks/useAccountTotalFiatBalance.js
Labels: team-wallet-ux

#30919 fix: cp-12.14.0 (MMS-2061) prompt user to create solana acct in bridge flow if selected tochain and no account
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain/asset-picker-amount/asset-picker-modal/asset-picker-modal.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-modal/solana-account-creation-prompt.tsx
  ui/ducks/bridge/selectors.ts
  ui/selectors/accounts.ts
Labels: team-swaps-and-bridge

#30897 test: remove uneeded ganache opts
  test/e2e/tests/swaps/shared.ts
  test/e2e/tests/swaps/swap-eth.spec.ts
  test/e2e/tests/swaps/swaps-notifications.spec.ts
Labels: area-qa, team-qa

#30271 feat: support atomic batch transactions
  .yarn/patches/@ethereumjs-tx-npm-5.4.0-0c4a0f973e.patch
  .yarn/patches/@metamask-transaction-controller-npm-45.0.0-010fef9da6.patch
  app/scripts/controller-init/messengers/transaction-controller-messenger.ts
  app/scripts/controllers/permissions/specifications.js
  app/scripts/lib/createMetamaskMiddleware.js
  app/scripts/lib/transaction/eip5792.test.ts
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/lib/confirmation.utils.ts
  ui/helpers/utils/transactions.util.js
  ui/hooks/useTransactionDisplayData.js
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  yarn.lock
Labels: team-confirmations

#30347 feat: account upgrade confirmation
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/controllers/preferences-controller.test.ts
  app/scripts/controllers/preferences-controller.ts
  app/scripts/lib/transaction/eip5792.test.ts
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/metamask-controller.js
  test/data/confirmations/contract-interaction.ts
  ui/helpers/constants/zendesk-url.js
  ui/pages/confirmations/components/confirm/footer/__snapshots__/footer.test.tsx.snap
  ui/pages/confirmations/components/confirm/footer/acknowledge/acknowledge.stories.tsx
  ui/pages/confirmations/components/confirm/footer/acknowledge/acknowledge.test.tsx
  ui/pages/confirmations/components/confirm/footer/acknowledge/acknowledge.tsx
  ui/pages/confirmations/components/confirm/footer/acknowledge/index.ts
  ui/pages/confirmations/components/confirm/footer/footer.tsx
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/index.scss
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/index.ts
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/upgrade-cancel-modal.stories.tsx
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/upgrade-cancel-modal.test.tsx
  ui/pages/confirmations/components/confirm/footer/upgrade-cancel-modal/upgrade-cancel-modal.tsx
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.tsx
  ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/index.ts
  ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/transaction-account-details.stories.tsx
  ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/transaction-account-details.tsx
  ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/transasction-account-details.test.tsx
  ui/pages/confirmations/components/confirm/info/hooks/useIsUpgradeTransaction.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useIsUpgradeTransaction.ts
  ui/pages/confirmations/components/index.scss
  ui/pages/confirmations/confirm/__snapshots__/confirm.test.tsx.snap
  ui/store/actions.ts
Labels: team-confirmations

#30939 test: skip smart transactions tests to unblock CI
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
Labels: team-qa

#30946 chore: ignore babel audit failure temporarily
  .yarnrc.yml
Labels: team-qa

#30895 chore: cp-12.14.0 add a migration script to include the MegaETH network in the installed extension
  app/scripts/metamask-controller.js
  app/scripts/migrations/146.test.ts
  app/scripts/migrations/146.ts
  app/scripts/migrations/index.js
  shared/constants/network.ts
  test/e2e/mock-e2e.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/privacy/basic-functionality.spec.ts
  test/e2e/tests/settings/localization.spec.js
Labels: QA Passed, release-12.14.0, team-network-enablement

#30932 test: fix ci failure Swap/STX specs due to missing mock
  test/e2e/mock-e2e.js
  test/e2e/tests/smart-transactions/smart-transactions.spec.ts
Labels: team-qa

#30950 chore: cp-12.14.0 (#30946, #30932)
  .yarnrc.yml
  test/e2e/mock-e2e.js
Labels: team-wallet-framework

#30447 feat: nested transaction data
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  test/data/confirmations/contract-interaction.ts
  test/data/confirmations/transaction-decode.ts
  ui/pages/confirmations/components/confirm/info/batch/nested-transaction-data/index.ts
  ui/pages/confirmations/components/confirm/info/batch/nested-transaction-data/nested-transaction-data.stories.tsx
  ui/pages/confirmations/components/confirm/info/batch/nested-transaction-data/nested-transaction-data.test.tsx
  ui/pages/confirmations/components/confirm/info/batch/nested-transaction-data/nested-transaction-data.tsx
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useDecodedTransactionData.ts
  ui/pages/confirmations/components/confirm/info/hooks/useFourByte.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useFourByte.ts
  ui/pages/confirmations/components/confirm/info/shared/advanced-details/advanced-details.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.test.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-data/transaction-data.tsx
  ui/pages/confirmations/components/confirm/info/shared/transaction-details/transaction-details.tsx
Labels: team-confirmations

#30913 fix: cp-12.14.0 CAIP chain ids are not parsed to Hex correctly
  shared/modules/bridge-utils/caip-formatters.ts
Labels: team-swaps-and-bridge

#30948 fix: cp-12.14.0 use networkClientId if included in transaction (#30758)
  app/scripts/controllers/bridge/bridge-controller.test.ts
  app/scripts/controllers/bridge/bridge-controller.ts
  app/scripts/metamask-controller.js
  ui/pages/bridge/hooks/useHandleTx.ts
  ui/pages/bridge/hooks/useSubmitBridgeTransaction.test.tsx
  ui/store/actions.ts
Labels: team-swaps-and-bridge

#30952 chore: wait at least 10 mins before showing bridge tx delay banner
  ui/pages/bridge/transaction-details/transaction-details.test.tsx
  ui/pages/bridge/transaction-details/transaction-details.tsx
Labels: team-swaps-and-bridge

#30951 Cherry pick 12.14.0 megaeth testnet
  app/images/MegaETH-logo-testnet.png
  app/scripts/metamask-controller.js
  app/scripts/migrations/146.test.ts
  app/scripts/migrations/146.ts
  app/scripts/migrations/index.js
  shared/constants/network.ts
  test/e2e/mock-e2e.js
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-background-state.json
  test/e2e/tests/metrics/state-snapshots/errors-after-init-opt-in-ui-state.json
  test/e2e/tests/privacy/basic-functionality.spec.ts
  test/e2e/tests/settings/localization.spec.js
Labels: INVALID-PR-TEMPLATE, team-network-enablement

#30918 fix: cp-12.14.0 bridge status validation causes transactions to be pending indefinitely
  app/scripts/controllers/bridge-status/utils.ts
  app/scripts/controllers/bridge-status/validators.ts
  shared/modules/bridge-utils/caip-formatters.ts
  ui/hooks/bridge/useBridgeChainInfo.ts
  ui/pages/bridge/transaction-details/transaction-details.tsx
Labels: team-swaps-and-bridge

#30926 fix: multichain transactions display
  test/e2e/flask/solana/common-solana.ts
  test/e2e/flask/solana/transaction-activity-list.spec.ts
  test/e2e/page-objects/pages/home/transaction-details.ts
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.test.tsx
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx
  ui/components/app/transaction-list/transaction-list.component.js
  ui/hooks/useMultichainTransactionDisplay.ts
Labels: team-sol

#30511 feat: token approvals from nested transactions in simulation details
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  shared/modules/transaction.utils.test.js
  shared/modules/transaction.utils.ts
  test/data/confirmations/set-approval-for-all.ts
  test/data/confirmations/token-approve.ts
  ui/__mocks__/actions.js
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/__snapshots__/edit-spending-cap-modal.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.test.tsx
  ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.test.ts
  ui/pages/confirmations/components/confirm/info/approve/hooks/use-approve-token-simulation.ts
  ui/pages/confirmations/components/confirm/info/base-transaction-info/base-transaction-info.tsx
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/batch-simulation-details.stories.tsx
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/batch-simulation-details.test.tsx
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/batch-simulation-details.tsx
  ui/pages/confirmations/components/confirm/info/batch/batch-simulation-details/index.ts
  ui/pages/confirmations/components/confirm/info/hooks/useBatchApproveBalanceChanges.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useBatchApproveBalanceChanges.ts
  ui/pages/confirmations/components/confirm/title/hooks/useCurrentSpendingCap.test.ts
  ui/pages/confirmations/components/simulation-details/amount-pill.test.tsx
  ui/pages/confirmations/components/simulation-details/amount-pill.tsx
  ui/pages/confirmations/components/simulation-details/balance-change-row.test.tsx
  ui/pages/confirmations/components/simulation-details/balance-change-row.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.test.tsx
  ui/pages/confirmations/components/simulation-details/simulation-details.tsx
  ui/pages/confirmations/components/simulation-details/types.ts
  ui/store/actions/transaction-controller.ts
Labels: team-confirmations

#30674 feat: When switching network alert the user and get approval if there are pending requests from origin.
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.test.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.js
  app/scripts/lib/rpc-method-middleware/handlers/ethereum-chain-utils.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js
  app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.test.js
  app/scripts/metamask-controller.js
  ui/pages/confirmations/confirmation/alerts/useAlertsActions.tsx
  ui/pages/confirmations/confirmation/alerts/useTemplateConfirmationAlerts.test.ts
  ui/pages/confirmations/confirmation/alerts/useTemplateConfirmationAlerts.ts
  ui/pages/confirmations/confirmation/alerts/useUpdateEthereumChainAlerts.test.ts
  ui/pages/confirmations/confirmation/alerts/useUpdateEthereumChainAlerts.ts
  ui/pages/confirmations/confirmation/templates/__snapshots__/switch-ethereum-chain.test.js.snap
  ui/pages/confirmations/confirmation/templates/switch-ethereum-chain.js
  ui/selectors/approvals.test.ts
  ui/selectors/approvals.ts
  ui/selectors/selectors.js
Labels: team-confirmations

#30962 cherry-pick: "fix: multichain transactions display (#30926)"
  test/e2e/flask/solana/common-solana.ts
  test/e2e/flask/solana/transaction-activity-list.spec.ts
  test/e2e/page-objects/pages/home/transaction-details.ts
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.test.tsx
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.tsx
  ui/components/app/transaction-list/transaction-list.component.js
  ui/hooks/useMultichainTransactionDisplay.ts
Labels: team-sol

#30963 fix: fix code fencing for beta build (#30935)
  ui/components/multichain/account-list-item/account-list-item.js
Labels: team-assets

#30791 refactor: resolve circular imports between permissions.js and selectors.js by moving permissions.js into selectors.js
  development/circular-deps.jsonc
  ui/selectors/index.js
  ui/selectors/permissions.js
  ui/selectors/permissions.test.js
  ui/selectors/selectors.js
Labels: team-extension-platform

#30937 fix: Add `describeChromeOnly` helper and use to exclude multichain API e2e tests from firefox e2e test runs
  test/e2e/flask/multichain-api/testHelpers.ts
  test/e2e/flask/multichain-api/wallet_createSession.spec.ts
  test/e2e/flask/multichain-api/wallet_getSession.spec.ts
  test/e2e/flask/multichain-api/wallet_invokeMethod.spec.ts
  test/e2e/flask/multichain-api/wallet_notify.spec.ts
  test/e2e/flask/multichain-api/wallet_revokeSession.spec.ts
  test/e2e/flask/multichain-api/wallet_sessionChanged.spec.ts
Labels: team-wallet-api-platform, INVALID-PR-TEMPLATE

#30979 chore: ref latest workflows for create-rls
  .github/workflows/create-release-pr.yml
Labels: team-dev-ops

#30876 fix: Provide required useEffect dependencies in TokenCell and AggregatedPercentageOverview
  ui/components/app/assets/token-cell/token-cell.tsx
  ui/components/app/wallet-overview/aggregated-percentage-overview.tsx
Labels: team-wallet-ux

#30981 fix: mms-2049 solana slipagge (#30760)
  app/scripts/controllers/swaps/index.ts
  shared/modules/bridge-utils/bridge.util.ts
  ui/ducks/swaps/swaps.js
Labels: team-swaps-and-bridge

#30929 feat: mms-1876 swap pre populated
  shared/constants/swaps.ts
  ui/hooks/swap/useSwapDefaultToToken.ts
  ui/pages/swaps/prepare-swap-page/prepare-swap-page.js
Labels: team-swaps-and-bridge

#30977 fix: Ensure env vars are correctly set for beta builds in build-beta.yml
  .github/workflows/build-beta.yml
Labels: team-extension-platform

#30604 feat: add accounts to a specific srp
  .storybook/test-data.js
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain/account-list-menu/account-list-menu.test.tsx
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/create-account/create-account.tsx
  ui/components/multichain/create-eth-account/create-eth-account.js
  ui/components/multichain/create-eth-account/create-eth-account.test.js
  ui/components/multichain/index.js
  ui/components/multichain/multi-srp/import-srp/import-srp.tsx
  ui/components/multichain/multi-srp/index.scss
  ui/components/multichain/multi-srp/index.ts
  ui/components/multichain/multi-srp/select-srp/index.scss
  ui/components/multichain/multi-srp/select-srp/index.ts
  ui/components/multichain/multi-srp/select-srp/select-srp.test.tsx
  ui/components/multichain/multi-srp/select-srp/select-srp.tsx
  ui/components/multichain/multi-srp/srp-list/index.scss
  ui/components/multichain/multi-srp/srp-list/index.ts
  ui/components/multichain/multi-srp/srp-list/srp-list-item.test.tsx
  ui/components/multichain/multi-srp/srp-list/srp-list-item.tsx
  ui/components/multichain/multi-srp/srp-list/srp-list.test.tsx
  ui/components/multichain/multi-srp/srp-list/srp-list.tsx
  ui/selectors/selectors.js
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: team-accounts

#30881 fix: Use useMemo with Receive Modal
  ui/components/multichain/receive-modal/receive-modal.js
Labels: team-wallet-ux

#31002 chore: Sync main with master, v12.10.1 -> v12.13.1
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#30967 feat: support updated EIP-5792 specification
  app/scripts/lib/createMetamaskMiddleware.js
  app/scripts/lib/transaction/eip5792.test.ts
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/lib/transaction/util.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-confirmations

#30434 fix: Update the connections menu for dapp connections
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain/connected-site-menu/connected-site-menu.js
  ui/components/multichain/connected-site-popover/connected-site-popover.stories.tsx
  ui/components/multichain/connected-site-popover/connected-site-popover.test.tsx
  ui/components/multichain/connected-site-popover/connected-site-popover.tsx
  ui/components/multichain/connected-site-popover/index.ts
  ui/components/multichain/index.js
Labels: INVALID-PR-TEMPLATE, team-wallet-ux

#30993 test: removing unnecessary ganacheOptions in specs
  test/e2e/snaps/test-snap-update-component.spec.js
  test/e2e/tests/account/incremental-security.spec.js
  test/e2e/tests/account/lockdown.spec.ts
  test/e2e/tests/confirmations/alerts/insufficient-funds.spec.ts
  test/e2e/tests/confirmations/transactions/contract-interaction-redesign.spec.ts
  test/e2e/tests/metrics/errors.spec.js
  test/e2e/tests/swaps/swaps-notifications.spec.ts
Labels: team-qa, skip-e2e-quality-gate

#30985 chore: Add v12.14.0 changelog entries
  CHANGELOG.md
Labels: DO-NOT-MERGE

#30757 fix: remove EVM network when non-EVM network is selected
  test/e2e/flask/solana/solana-eth-networks.spec.ts
  test/e2e/flask/solana/solana-networks.spec.ts
  ui/components/app/modals/confirm-delete-network/__snapshots__/confirm-delete-network.test.js.snap
  ui/components/app/modals/confirm-delete-network/confirm-delete-network.component.js
  ui/components/app/modals/confirm-delete-network/confirm-delete-network.container.js
  ui/components/app/modals/confirm-delete-network/confirm-delete-network.test.js
  ui/store/actions.ts
Labels: team-accounts

#30966 chore: Bump Snaps packages
  app/scripts/controller-init/snaps/snap-controller-init.test.ts
  app/scripts/controller-init/snaps/snap-controller-init.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-snaps-platform

#30987 chore: bump test-dapp to v9.1.0
  package.json
  yarn.lock
Labels: area-qa, team-qa

#30312 test: Migrating snaps test to POM
  test/e2e/page-objects/flows/install-test-snap.flow.ts
  test/e2e/page-objects/flows/snap-permission.flow.ts
  test/e2e/page-objects/pages/dialog/snap-install.ts
  test/e2e/page-objects/pages/test-dapp.ts
  test/e2e/page-objects/pages/test-snaps.ts
  test/e2e/snaps/test-snap-bip-32.spec.ts
  test/e2e/snaps/test-snap-bip-44.spec.ts
  test/e2e/snaps/test-snap-clientstatus.spec.js
  test/e2e/snaps/test-snap-clientstatus.spec.ts
  test/e2e/snaps/test-snap-get-entropy.spec.ts
  test/e2e/snaps/test-snap-get-file.spec.js
  test/e2e/snaps/test-snap-get-file.spec.ts
  test/e2e/snaps/test-snap-homepage.spec.ts
  test/e2e/snaps/test-snap-installed.spec.js
  test/e2e/snaps/test-snap-installed.spec.ts
  test/e2e/snaps/test-snap-lifecycle.spec.js
  test/e2e/snaps/test-snap-lifecycle.spec.ts
  test/e2e/snaps/test-snap-namelookup.spec.js
  test/e2e/snaps/test-snap-namelookup.spec.ts
  test/e2e/snaps/test-snap-txinsights.spec.js
  test/e2e/snaps/test-snap-txinsights.spec.ts
  test/e2e/snaps/test-snap-update.spec.js
  test/e2e/snaps/test-snap-update.spec.ts
  test/e2e/snaps/test-snap-wasm.spec.js
  test/e2e/snaps/test-snap-wasm.spec.ts
  test/e2e/tests/confirmations/navigation.spec.ts
  test/e2e/webdriver/README.md
  test/e2e/webdriver/driver.js
Labels: INVALID-PR-TEMPLATE, area-qa, team-qa

#29857 fix: Ensure SRP backup reminder only displays when on HDKey account
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
Labels: team-wallet-ux

#30880 fix: Use useCallback for domain input in Send flow
  ui/components/multichain/pages/send/components/recipient-input.tsx
Labels: team-wallet-ux

#30873 fix: Prevent rerenders of the AccountListItem
  ui/components/multichain/account-list-item/account-list-item.js
  ui/components/multichain/account-list-menu/account-list-menu.tsx
  ui/components/multichain/pages/send/components/account-picker.tsx
  ui/components/multichain/pages/send/components/your-accounts.tsx
  ui/pages/routes/routes.component.js
  ui/selectors/accounts.test.ts
  ui/selectors/accounts.ts
  ui/selectors/selectors.js
Labels: team-wallet-ux

#31011 fix: auth & user storage when switching srp with forgot password flow
  package.json
  ui/components/app/create-new-vault/create-new-vault.js
  ui/components/app/create-new-vault/create-new-vault.test.js
  ui/pages/keychains/restore-vault.stories.tsx
  yarn.lock
Labels: team-identity

#31051 fix: [cherry-pick] add missing mock for portfolio site in e2e testing (#31034)
  privacy-snapshot.json
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/phishing-controller/mocks.js
  test/e2e/tests/portfolio/portfolio-site.spec.ts
Labels: team-qa

#31038 fix: Prevent incomplete transaction cleanup to track bridge metrics
  app/scripts/metamask-controller.js
Labels: team-confirmations

#31035 chore: add `yarnrc.yml` to `extension-platform` codeowners
  .github/CODEOWNERS
Labels: team-qa

#31043 feat (cherry-pick): support updated EIP-5792 specification (#30967)
  app/scripts/lib/createMetamaskMiddleware.js
  app/scripts/lib/transaction/eip5792.test.ts
  app/scripts/lib/transaction/eip5792.ts
  app/scripts/lib/transaction/util.ts
  app/scripts/metamask-controller.js
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-confirmations

#29698 fix: add normalization in signature request
  app/scripts/lib/ppom/ppom-util.ts
  shared/modules/typed-signature.test.ts
  shared/modules/typed-signature.ts
Labels: team-confirmations

#31036 chore: updates dependencies
  .yarn/patches/@metamask-assets-controllers-npm-53.1.1-644979f986.patch
  app/scripts/controller-init/messengers/multichain/multichain-balances-controller-messenger.ts
  app/scripts/controller-init/messengers/multichain/multichain-transactions-controller-messenger.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-sol

#31067 fix: [cherry-pick] update multichain dependencies
  .yarn/patches/@metamask-assets-controllers-npm-53.1.1-644979f986.patch
  app/scripts/controller-init/messengers/multichain/multichain-balances-controller-messenger.ts
  app/scripts/controller-init/messengers/multichain/multichain-transactions-controller-messenger.ts
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  yarn.lock
Labels: team-sol

#30978 test: Swap playwright script fix
  test/e2e/playwright/swap/pageObjects/swap-page.ts
  test/e2e/playwright/swap/specs/swap.spec.ts
Labels: team-qa

#31069 feat (cherry-pick): add EIP-7702 revoke flow (#30969)
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/scripts/metamask-controller.js
  shared/lib/confirmation.utils.ts
  ui/__mocks__/actions.js
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/account-details/account-details-display.test.tsx
  ui/components/multichain/account-details/account-details.js
  ui/components/multichain/account-details/account-details.stories.js
  ui/helpers/utils/transactions.util.js
  ui/hooks/useTransactionDisplayData.js
  ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/transaction-account-details.tsx
  ui/pages/confirmations/components/confirm/info/batch/transaction-account-details/transasction-account-details.test.tsx
  ui/pages/confirmations/components/confirm/info/hooks/useIsUpgradeTransaction.test.ts
  ui/pages/confirmations/components/confirm/info/hooks/useIsUpgradeTransaction.ts
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
  ui/pages/confirmations/hooks/useEIP7702Account.test.ts
  ui/pages/confirmations/hooks/useEIP7702Account.ts
  ui/store/actions.ts
Labels: INVALID-PR-TEMPLATE, team-confirmations

#31001 feat: SIWE default to expanded on open
  test/e2e/tests/dapp-interactions/signin-with-ethereum.spec.js
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/__snapshots__/siwe-sign.test.tsx.snap
  ui/pages/confirmations/components/confirm/info/personal-sign/siwe-sign/siwe-sign.tsx
Labels: team-confirmations

#31076 [cherry-pick]: update solana version
  package.json
  yarn.lock
Labels: team-sol

#31039 fix: fix sentry logs noisy
  app/scripts/migrations/134.1.test.ts
  app/scripts/migrations/134.1.ts
Labels: team-assets

#31013 chore: sync `main` with `master`, v12.13.1 -> v12.14.0
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#31095 chore: Revert "chore: sync `main` with `master`, v12.13.1 -> v12.14.0"
  CHANGELOG.md
  package.json
Labels: team-wallet-framework, INVALID-PR-TEMPLATE

#31074 feat: reject pending confirmations for origin when permissions are revoked for it
  app/scripts/lib/rpc-method-middleware/handlers/wallet-revokePermissions.test.ts
  app/scripts/lib/rpc-method-middleware/handlers/wallet-revokePermissions.ts
Labels: team-confirmations

#30809 feat: Update blockaid friction modal copy
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  ui/components/app/alert-system/alert-modal/alert-modal.test.tsx
  ui/components/app/alert-system/alert-modal/alert-modal.tsx
  ui/components/app/alert-system/confirm-alert-modal/confirm-alert-modal.test.tsx
  ui/components/app/alert-system/confirm-alert-modal/confirm-alert-modal.tsx
Labels: team-confirmations

#31031 feat: add atomic batch metrics
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/app.ts
  shared/constants/metametrics.ts
  yarn.lock
Labels: team-confirmations

#31096 chore: Sync `main` with `master`, `v12.13.1` -> `v12.14.0`
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#31105 feat (cherry-pick): add atomic batch metrics (#31031)
  app/scripts/controller-init/confirmations/transaction-controller-init.ts
  app/scripts/lib/createRPCMethodTrackingMiddleware.js
  app/scripts/lib/createRPCMethodTrackingMiddleware.test.js
  app/scripts/lib/transaction/metrics.test.ts
  app/scripts/lib/transaction/metrics.ts
  app/scripts/metamask-controller.js
  builds.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  shared/constants/app.ts
  shared/constants/metametrics.ts
  yarn.lock
Labels: INVALID-PR-TEMPLATE, team-confirmations

#31103 chore: updates multichain tx controller package
  package.json
  yarn.lock
Labels: team-sol

#30384 feat: Fix plan 835 Hid request dialog keep on prompting up during pagination.
  ui/pages/create-account/connect-hardware/__snapshots__/index.test.tsx.snap
  ui/pages/create-account/connect-hardware/account-list.js
  ui/pages/create-account/connect-hardware/index.js
  ui/pages/create-account/connect-hardware/index.test.tsx
  ui/store/actions.test.js
  ui/store/actions.ts
Labels: hardware-ledger, QA Passed, needs-dev-review, team-hardware-wallets

#31114 chore: Fix CI failures affecting v12.12.x
  .github/workflows/add-release-label.yml
  .github/workflows/build-beta.yml
  .github/workflows/build-storybook.yml
  .github/workflows/check-attributions.yml
  .github/workflows/check-pr-labels.yml
  .github/workflows/check-template-and-add-labels.yml
  .github/workflows/close-bug-report.yml
  .github/workflows/codespaces.yml
  .github/workflows/fitness-functions.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/run-tests.yml
  .github/workflows/test-deps-audit.yml
  .github/workflows/test-deps-depcheck.yml
  .github/workflows/test-lint-changelog.yml
  .github/workflows/test-lint-lockfile.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-storybook.yml
  .github/workflows/test-yarn-dedupe.yml
  .github/workflows/update-attributions.yml
  .github/workflows/update-lavamoat-policies.yml
  .github/workflows/validate-lavamoat-allow-scripts.yml
  .github/workflows/validate-lavamoat-policy-build.yml
  .github/workflows/validate-lavamoat-policy-webapp.yml
  .yarnrc.yml
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  test/e2e/page-objects/pages/mocked-page.ts
  test/e2e/snaps/test-snap-uilinks.spec.js
  test/e2e/snaps/test-snap-update-component.spec.js
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/phishing-controller/mocks.js
  test/e2e/tests/portfolio/portfolio-site.spec.ts
  yarn.lock
Labels: team-wallet-framework, team-extension-platform

#31102 feat: enable account syncing for MV2
  app/scripts/controller-init/identity/user-storage-controller-init.test.ts
  app/scripts/controller-init/identity/user-storage-controller-init.ts
  test/e2e/tests/identity/account-syncing/helpers.ts
  test/e2e/tests/identity/account-syncing/sync-with-account-balances.spec.ts
Labels: team-identity

#31107 fix: Disable CSP override feature that is breaking sites
  app/scripts/background.js
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
Labels: team-wallet-framework, team-extension-platform

#31118 chore: Update changelog for v12.12.1
  CHANGELOG.md
Labels: team-wallet-framework

#31113 chore: Support building backport prod build
  .circleci/config.yml
Labels: team-wallet-framework

#31122 chore: Disable CSP test
  test/e2e/tests/content-security-policy/content-security-policy.spec.ts
Labels: team-wallet-framework

#31121 fix: cp-12.14.1 Disable CSP override feature that is breaking sites
  app/scripts/background.js
  test/e2e/tests/content-security-policy/content-security-policy.spec.ts
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
Labels: team-wallet-framework

#31125 Version v12.12.1
  .circleci/config.yml
  .github/workflows/add-release-label.yml
  .github/workflows/build-beta.yml
  .github/workflows/build-storybook.yml
  .github/workflows/check-attributions.yml
  .github/workflows/check-pr-labels.yml
  .github/workflows/check-template-and-add-labels.yml
  .github/workflows/close-bug-report.yml
  .github/workflows/codespaces.yml
  .github/workflows/fitness-functions.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/run-tests.yml
  .github/workflows/test-deps-audit.yml
  .github/workflows/test-deps-depcheck.yml
  .github/workflows/test-lint-changelog.yml
  .github/workflows/test-lint-lockfile.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-storybook.yml
  .github/workflows/test-yarn-dedupe.yml
  .github/workflows/update-attributions.yml
  .github/workflows/update-lavamoat-policies.yml
  .github/workflows/validate-lavamoat-allow-scripts.yml
  .github/workflows/validate-lavamoat-policy-build.yml
  .github/workflows/validate-lavamoat-policy-webapp.yml
  .yarnrc.yml
  CHANGELOG.md
  app/scripts/background.js
  attribution.txt
  lavamoat/browserify/beta/policy.json
  lavamoat/browserify/flask/policy.json
  lavamoat/browserify/main/policy.json
  lavamoat/browserify/mmi/policy.json
  package.json
  privacy-snapshot.json
  test/e2e/page-objects/pages/mocked-page.ts
  test/e2e/snaps/test-snap-uilinks.spec.js
  test/e2e/snaps/test-snap-update-component.spec.js
  test/e2e/tests/bridge/bridge-test-utils.ts
  test/e2e/tests/content-security-policy/content-security-policy.spec.ts
  test/e2e/tests/phishing-controller/mocks.js
  test/e2e/tests/portfolio/portfolio-site.spec.ts
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
  yarn.lock
Labels: team-wallet-framework

#30817 chore: Fix bundle size job
  .circleci/scripts/bundle-stats-commit.sh
Labels: team-qa

#28180 feat: new tx list filter
  app/scripts/metamask-controller.js
  package.json
  test/data/transaction-data.json
  ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
  ui/components/app/transaction-list-item-details/transaction-list-item-details.container.js
  ui/components/app/transaction-list-item/smart-transaction-list-item.component.js
  ui/components/app/transaction-list-item/transaction-list-item.component.js
  ui/components/app/transaction-list/__snapshots__/transaction-list.test.js.snap
  ui/components/app/transaction-list/transaction-list.component.js
  ui/components/app/transaction-list/transaction-list.test.js
  ui/components/multichain/account-overview/account-overview-tabs.tsx
  ui/components/multichain/network-filter-menu/__snapshots__/index.test.tsx.snap
  ui/components/multichain/network-filter-menu/index.test.tsx
  ui/components/multichain/network-filter-menu/index.tsx
  ui/components/ui/currency-display/__snapshots__/currency-display.component.test.js.snap
  ui/hooks/useCurrencyDisplay.js
  ui/hooks/useShouldShowSpeedUp.js
  ui/hooks/useShouldShowSpeedUp.test.ts
  ui/hooks/useTransactionDisplayData.js
  ui/hooks/useUserPreferencedCurrency.js
  ui/pages/asset/components/asset-page.tsx
  ui/selectors/transactions.js
  ui/selectors/transactions.test.js
  yarn.lock
Labels: team-assets

#31128 fix: revert "feat: enable account syncing for MV2 (#31102)"
  app/scripts/controller-init/identity/user-storage-controller-init.test.ts
  app/scripts/controller-init/identity/user-storage-controller-init.ts
  test/e2e/tests/identity/account-syncing/helpers.ts
  test/e2e/tests/identity/account-syncing/sync-with-account-balances.spec.ts
Labels: team-identity

#30999 feat: Add Linea to Smart Transaction supported chains
  shared/constants/smartTransactions.test.ts
  shared/constants/smartTransactions.ts
Labels: team-transactions, release-12.16.0

#29878 feat: Resimulate transactions for every 3 seconds on focused MM window
  app/scripts/metamask-controller.js
  ui/hooks/useWindowFocus.test.ts
  ui/hooks/useWindowFocus.ts
  ui/pages/confirmations/components/confirm/info/info.test.tsx
  ui/pages/confirmations/components/confirm/info/info.tsx
  ui/pages/confirmations/hooks/useTransactionFocusEffect.test.ts
  ui/pages/confirmations/hooks/useTransactionFocusEffect.ts
  ui/store/actions.ts
Labels: team-confirmations

#31068 chore: resolve v12.15.0 release branch conflicts with `master`
  CHANGELOG.md
  app/scripts/background.js
  attribution.txt
  test/e2e/tests/content-security-policy/content-security-policy.spec.ts
  ui/pages/settings/advanced-tab/advanced-tab.component.js
  ui/pages/settings/advanced-tab/advanced-tab.container.js
Labels: DO-NOT-MERGE

#30916 fix: Confirm Revoke Permit Decoding Simulation & Activity List item
  app/_locales/de/messages.json
  app/_locales/el/messages.json
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  app/_locales/es/messages.json
  app/_locales/fr/messages.json
  app/_locales/hi/messages.json
  app/_locales/id/messages.json
  app/_locales/ja/messages.json
  app/_locales/ko/messages.json
  app/_locales/pt/messages.json
  app/_locales/ru/messages.json
  app/_locales/tl/messages.json
  app/_locales/tr/messages.json
  app/_locales/vi/messages.json
  app/_locales/zh_CN/messages.json
  test/data/confirmations/typed_sign.ts
  test/integration/confirmations/transactions/set-approval-for-all-revoke.test.tsx
  test/integration/confirmations/transactions/transactionDataHelpers.tsx
  ui/hooks/useTransactionDisplayData.js
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.test.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/decoded-simulation/decoded-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/permit-simulation/permit-simulation.tsx
  ui/pages/confirmations/components/confirm/info/typed-sign/typed-sign-v4-simulation/value-display/value-display.tsx
  ui/pages/confirmations/components/confirm/title/title.tsx
Labels: team-confirmations

#31163 chore: Sync `master` with `main`, `v12.14.0` -> `v12.14.1`
  CHANGELOG.md
  package.json
Labels: team-extension-platform

#30641 feat: add reveal srp
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  shared/constants/accounts.ts
  shared/lib/keyring.ts
  test/e2e/flask/multi-srp/add-accounts.spec.ts
  test/e2e/flask/multi-srp/common-multi-srp.ts
  test/e2e/flask/multi-srp/import-srp.spec.ts
  test/e2e/flask/multi-srp/settings-reveal-srp.spec.ts
  test/e2e/page-objects/pages/account-list-page.ts
  test/e2e/page-objects/pages/settings/privacy-settings.ts
  ui/components/app/srp-quiz-modal/SRPQuiz/SRPQuiz.tsx
  ui/components/multichain/account-details/account-details-display.js
  ui/components/multichain/account-details/account-details.test.js
  ui/components/multichain/account-details/account-details.tsx
  ui/components/multichain/multi-srp/import-srp/import-srp.test.tsx
  ui/components/multichain/multi-srp/import-srp/import-srp.tsx
  ui/components/multichain/multi-srp/import-srp/index.scss
  ui/helpers/constants/routes.ts
  ui/helpers/utils/util.js
  ui/helpers/utils/util.test.js
  ui/pages/keychains/reveal-seed.js
  ui/pages/keychains/reveal-seed.test.js
  ui/pages/routes/routes.component.js
  ui/pages/settings/security-tab/reveal-srp-list/index.ts
  ui/pages/settings/security-tab/reveal-srp-list/reveal-srp-list.test.tsx
  ui/pages/settings/security-tab/reveal-srp-list/reveal-srp-list.tsx
  ui/pages/settings/security-tab/security-tab.component.js
  ui/pages/settings/security-tab/security-tab.container.js
  ui/pages/settings/security-tab/security-tab.test.js
  ui/pages/settings/settings.component.js
  ui/pages/settings/settings.container.js
  ui/selectors/selectors.js
  ui/selectors/selectors.test.js
  ui/store/actions.ts
Labels: team-accounts

#30887 style: Update styling of banner
  ui/components/multichain/network-list-menu/network-list-menu.tsx
Labels: type-enhancement, team-assets, area-design

#31173 Change tests to run on Anvil
  test/e2e/bridge/bridge-cross-chain-swap.spec.ts
  test/e2e/bridge/bridge-test-utils.ts
  test/e2e/page-objects/pages/bridge/quote-page.ts
  test/e2e/page-objects/pages/home/activity-list.ts
  ui/pages/bridge/prepare/prepare-bridge-page.tsx
Labels: team-qa

#31131 fix: display NFT name in send flow
  shared/constants/tokens.js
  ui/components/multichain/asset-picker-amount/asset-picker-amount.test.tsx
  ui/components/multichain/asset-picker-amount/asset-picker-amount.tsx
Labels: team-assets

#31134 chore: Swap blockstream for mempool.space as Bitcoin block explorer
  shared/constants/multichain/networks.ts
  ui/components/app/modals/confirm-remove-account/confirm-remove-account.test.js
  ui/components/app/multichain-transaction-details-modal/helpers.ts
  ui/components/app/multichain-transaction-details-modal/multichain-transaction-details-modal.test.tsx
  ui/helpers/utils/multichain/blockExplorer.test.ts
Labels: team-accounts

#31040 fix(#14716): fix send invalid hex data
  app/_locales/en/messages.json
  app/_locales/en_GB/messages.json
  ui/components/multichain/pages/send/components/hex.tsx
  ui/components/multichain/pages/send/send.js
  ui/ducks/send/send.js
  ui/ducks/send/send.test.js
  ui/pages/confirmations/send/send.constants.js
Labels: team-swaps-and-bridge
